hashicorp/terraform-provider-aws

aws/resource_aws_ram_principal_association_test.go
aws/resource_aws_ram_resource_association_test.go
aws/resource_aws_ram_resource_share_accepter_test.go
aws/resource_aws_rds_cluster_endpoint_test.go
aws/resource_aws_rds_cluster_instance_test.go
aws/resource_aws_rds_cluster_parameter_group_test.go
aws/resource_aws_rds_cluster_test.go
aws/resource_aws_rds_global_cluster_test.go
aws/resource_aws_redshift_cluster_test.go
aws/resource_aws_redshift_event_subscription_test.go
aws/resource_aws_redshift_parameter_group_test.go
aws/resource_aws_redshift_security_group_test.go
aws/resource_aws_redshift_snapshot_copy_grant_test.go
aws/resource_aws_redshift_snapshot_schedule_association_test.go
aws/resource_aws_redshift_snapshot_schedule_test.go
aws/resource_aws_redshift_subnet_group_test.go
aws/resource_aws_resourcegroups_group_test.go

tests/provider: Update resource testing to 0.12 syntax (Ra/RD/Re Resources)

---

aws/resource_aws_qldb_ledger_test.go
aws/resource_aws_quicksight_group_test.go
aws/resource_aws_quicksight_user_test.go

tests/provider: Update resource testing to 0.12 syntax (Q Resources)

---

aws/resource_aws_iam_access_key_test.go
aws/resource_aws_iam_account_password_policy_test.go
aws/resource_aws_iam_group_membership_test.go
aws/resource_aws_iam_group_policy_attachment_test.go
aws/resource_aws_iam_group_policy_test.go
aws/resource_aws_iam_instance_profile_test.go
aws/resource_aws_iam_policy_attachment_test.go
aws/resource_aws_iam_policy_test.go
aws/resource_aws_iam_role_policy_attachment_test.go
aws/resource_aws_iam_role_policy_test.go
aws/resource_aws_iam_role_test.go
aws/resource_aws_iam_saml_provider_test.go
aws/resource_aws_iam_server_certificate_test.go
aws/resource_aws_iam_user_group_membership_test.go
aws/resource_aws_iam_user_login_profile_test.go
aws/resource_aws_iam_user_policy_attachment_test.go
aws/resource_aws_iam_user_policy_test.go
aws/resource_aws_iam_user_ssh_key_test.go
aws/resource_aws_iam_user_test.go

tests/provider: Update resource testing to 0.12 syntax (IAM Resources)

---

aws/resource_aws_route53_delegation_set_test.go
aws/resource_aws_route53_health_check_test.go
aws/resource_aws_route53_query_log_test.go
aws/resource_aws_route53_record_test.go
aws/resource_aws_route53_resolver_endpoint_test.go
aws/resource_aws_route53_resolver_rule_association_test.go
aws/resource_aws_route53_resolver_rule_test.go
aws/resource_aws_route53_vpc_association_authorization_test.go
aws/resource_aws_route53_zone_association_test.go
aws/resource_aws_route53_zone_test.go
aws/resource_aws_route_table_association_test.go
aws/resource_aws_route_table_test.go
aws/resource_aws_route_test.go

tests/provider: Update resource testing to 0.12 syntax (Ro Resources)

---

aws/resource_aws_ses_active_receipt_rule_set_test.go
aws/resource_aws_ses_configuration_set_test.go
aws/resource_aws_ses_domain_dkim_test.go
aws/resource_aws_ses_domain_identity_verification_test.go
aws/resource_aws_ses_domain_mail_from_test.go
aws/resource_aws_ses_event_destination_test.go
aws/resource_aws_ses_identity_notification_topic_test.go
aws/resource_aws_ses_identity_policy_test.go
aws/resource_aws_ses_receipt_rule_test.go
aws/resource_aws_sfn_activity_test.go
aws/resource_aws_sfn_state_machine_test.go
aws/resource_aws_shield_protection_test.go

tests/provider: Update resource testing to 0.12 syntax (Ses Resources)

---

aws/resource_aws_iam_access_key_test.go
aws/resource_aws_lightsail_key_pair_test.go
aws/resource_aws_mq_broker_test.go
aws/resource_aws_ssm_activation_test.go
aws/resource_aws_ssm_association_migrate_test.go
aws/resource_aws_ssm_association_test.go
aws/resource_aws_ssm_document_test.go
aws/resource_aws_ssm_maintenance_window_target_test.go
aws/resource_aws_ssm_maintenance_window_task_test.go
aws/resource_aws_ssm_maintenance_window_test.go
aws/resource_aws_ssm_parameter_test.go
aws/resource_aws_ssm_patch_group_test.go
aws/resource_aws_ssm_resource_data_sync_test.go
aws/resource_aws_storagegateway_cache_test.go
aws/resource_aws_storagegateway_cached_iscsi_volume_test.go
aws/resource_aws_storagegateway_gateway_test.go
aws/resource_aws_storagegateway_nfs_file_share_test.go
aws/resource_aws_storagegateway_smb_file_share_test.go
aws/resource_aws_subnet_test.go

tests/provider: Update resource testing to 0.12 syntax (Ss-Sw Resources)

---

aws/resource_aws_inspector_assessment_target_test.go
aws/resource_aws_inspector_assessment_template_test.go
aws/resource_aws_inspector_resource_group_test.go
aws/resource_aws_instance_test.go
aws/resource_aws_internet_gateway_test.go
aws/resource_aws_iot_certificate_test.go
aws/resource_aws_iot_policy_attachment_test.go
aws/resource_aws_iot_policy_test.go
aws/resource_aws_iot_role_alias_test.go
aws/resource_aws_iot_thing_principal_attachment_test.go
aws/resource_aws_iot_thing_test.go
aws/resource_aws_iot_topic_rule_test.go

tests/provider: Update resource testing to 0.12 syntax (I Resources)

---

docs/MAINTAINING.md

docs/provider: Re-add Release Process section to maintaining guide

---

aws/resource_aws_vpc_endpoint_connection_notification_test.go
aws/resource_aws_vpc_endpoint_service_allowed_principal_test.go

Relates #12995 
```release-note
NONE
```
Output from acceptance testing (GovCloud partition):
```
--- PASS: TestAccAWSVpcEndpointServiceAllowedPrincipal_basic (255.82s)
--- PASS: TestAccAWSVpcEndpointConnectionNotification_basic (297.80s)
``` …

tests/provider: Update hardcoded AZs (VPC Endpoint)

---

aws/resource_aws_storagegateway_nfs_file_share.go

```release-note
NONE
```
```
--- PASS: TestAccAWSStorageGatewayNfsFileShare_tags (498.04s)
--- PASS: TestAccAWSStorageGatewayNfsFileShare_DefaultStorageClass (447.18s) …
```

r/storagegateway_nfs_file_share - dont update file share when only tags change + remove extraneous list tag call

---

aws/resource_aws_redshift_subnet_group_test.go

Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/13826
Closes #14574
```release-note
NONE
```
Output from acceptance testing in AWS Commercial:
```
--- PASS: TestAccAWSRedshiftSubnetGroup_disappears (26.83s)
``` …

tests/resource/aws_redshift_subnet_group: Implement sweeper and disappears test

---

aws/resource_aws_iam_policy_test.go
aws/resource_aws_iam_role_policy_test.go
aws/resource_aws_spot_fleet_request_test.go

Relates #14386 
```release-note
tech-debt: iam-theme acceptance test fixes
```
```
--- PASS: TestAccAWSSpotFleetRequest_iamInstanceProfileArn (251.10s)
--- PASS: TestAccAWSIAMRolePolicy_invalidJSON (2.40s)
--- …
```

tech-debt: iam-theme acceptance test fixes

---

aws/resource_aws_sns_topic_subscription.go

Fix error message

---

aws/resource_aws_backup_plan_test.go

Closes #14569
```release-note
tech-debt/aws_backup_plan: update acceptance testing with SDKv2 TypeSet checks
```
```
--- PASS: TestAccAwsBackupPlan_disappears (25.80s)
--- PASS: TestAccAwsBackupPlan_basic …
```

tech-debt/aws_backup_plan: update acceptance testing with SDKv2 TypeSet checks

---

.github/workflows/changelog.yml
.github/workflows/dependencies.yml
.github/workflows/snapshot.yml
README.md
ROADMAP.md
docs/CORE_SERVICES.md
docs/FAQ.md
docs/MAINTAINING.md
docs/roadmaps/2020_May_to_July.md

When I skimmed through the docs, my editors flagged the end-of-line whitespaces. These hurt my eye. :)
Please accept my humble contribution.
```release-note
NONE
```
```
$ make testacc …
```

Whitespaces at the end of line fixes.

---

aws/resource_aws_spot_fleet_request_test.go

Relates #14383
Continues work started in #14841 
```release-note
tech-debt/ec2: update spotfleetrequest acceptance tests to use updated TypeSet pair check
```
```
--- PASS: …
```

tech-debt/ec2: update spotfleetrequest acceptance tests to use updated TypeSet pair check

---

aws/resource_aws_instance.go

Relates https://github.com/terraform-providers/terraform-provider-aws/issues/14383
```release-note
tech-debt/aws_instance: add state conf handling for root device.0.delete_on_termination and metadata updates
```
Output from acceptance testing …

tech-debt/aws_instance: add state conf for root device and metadata updates

---

aws/resource_aws_proxy_protocol_policy_test.go

Relates #12995
```release-note
NONE
```
```
--- PASS: TestAccAWSProxyProtocolPolicy_basic (47.61s)
```
```
--- PASS: TestAccAWSProxyProtocolPolicy_basic …
```

tests/provider: Fix hardcoded (proxy protocol policy)

---

aws/resource_aws_spot_fleet_request_test.go

Relates #12995
```release-note
NONE
```
```
--- PASS: TestAccAWSSpotFleetRequest_multipleInstanceTypesInSameAz (279.13s)
```
```
--- PASS: …
```

tests/provider: Fix hardcoded AZs (spot fleet request)

---

.github/workflows/terraform_provider.yml
.hashibot.hcl
.semgrep.yml

```release-note
NONE
```
Output from acceptance testing: N/A (CI)

tests/provider: Try out semgrep in CI

---

website/docs/r/iam_group_policy.html.markdown

```release-note
Closes #15040 
```
```
...
```

Assign group name (not id) to group argument

---

.hashibot.hcl
docs/contributing/contribution-checklists.md

```release-note
NONE
```
Output from acceptance testing: N/A (hashibot configuration and documentation)

provider: Ensure hashibot labels internal service files with service label

---

aws/resource_aws_volume_attachment_test.go
aws/resource_aws_vpc_dhcp_options_association_test.go
aws/resource_aws_vpc_dhcp_options_test.go
aws/resource_aws_vpc_endpoint_connection_notification_test.go
aws/resource_aws_vpc_endpoint_route_table_association_test.go
aws/resource_aws_vpc_endpoint_service_allowed_principal_test.go
aws/resource_aws_vpc_endpoint_service_test.go
aws/resource_aws_vpc_endpoint_subnet_association_test.go
aws/resource_aws_vpc_endpoint_test.go
aws/resource_aws_vpc_ipv4_cidr_block_association_test.go
aws/resource_aws_vpc_peering_connection_accepter_test.go
aws/resource_aws_vpc_peering_connection_options_test.go
aws/resource_aws_vpc_peering_connection_test.go
aws/resource_aws_vpc_test.go
aws/resource_aws_vpn_connection_route_test.go
aws/resource_aws_vpn_connection_test.go
aws/resource_aws_vpn_gateway_attachment_test.go
aws/resource_aws_vpn_gateway_route_propagation_test.go
aws/resource_aws_vpn_gateway_test.go

tests/provider: Update resource testing to 0.12 syntax (V Resources)

---

aws/resource_aws_guardduty_filter_test.go

Relates #12995 
```release-note
NONE
```
```
kommer snart
```
```
kommer snart
```

tests/provider: Fix hardcoded (GuardDuty Filter)

---

docs/FAQ.md

Add FAQ item to describe major version backport policy

---

examples/eks-getting-started/eks-cluster.tf
website/docs/r/eks_cluster.html.markdown

Reference: https://docs.aws.amazon.com/eks/latest/userguide/security-groups-for-pods.html
```release-note
NONE
```
Output from acceptance testing: N/A (documentation and examples)

service/eks: Document enabling Security Groups for Pods functionality

---

website/docs/r/cloudhsm_v2_hsm.html.markdown

Added section how to import HSM module resources

---

aws/resource_aws_elasticsearch_domain_test.go

```release-note
NONE
```
Previously:
```
=== CONT  TestAccAWSElasticSearchDomain_vpc_update
TestAccAWSElasticSearchDomain_vpc_update: resource_aws_elasticsearch_domain_test.go:415: Step 1/3 error: terraform failed: exit status 1
stderr: …
```

tests/resource/aws_elasticsearch_domain: Fix configuration issues in TestAccAWSElasticSearchDomain_vpc_update

---

website/docs/guides/version-3-upgrade.html.md

Closes #15094 
```release-note
Document data source aws_launch_template breaking change in upgrade to 3.0
```

Document breaking change in data source aws_launch_template 

---

website/docs/r/kinesis_firehose_delivery_stream.html.markdown

Closes #15251
```release-note
NONE
```

Fix typo on key_arn documentation

---

.github/CODEOWNERS

I [constantly contribute to AWS WorkSpaces Terraform resources](https://github.com/terraform-providers/terraform-provider-aws/pulls?q=is%3Apr+is%3Apr+author%3ATensho) and would like to expand owhership there. Please add me to the CODEONWERS list to be aware of all changes in that field 🙇 
- #14577
- #14535
- #14451
- #14135
- #11428
- #13529
- #12497
- #11608
- #11282
- #11023
- #10904

AWS WorkSpaces Service Maintainer

---

website/docs/r/glue_crawler.html.markdown

```release-note
```
```
...
```

fix doc lint introduced in #14819

---

website/docs/r/kinesis_firehose_delivery_stream.html.markdown

Closes https://github.com/terraform-providers/terraform-provider-aws/issues/15036
```release-note
None
```
```
None
```
Updated aws_kinesis_firehose_delivery_stream documentation required/optional fields. Thank …

Modify aws_kinesis_firehose_delivery_stream documentation

---

aws/resource_aws_glue_job_test.go
website/docs/r/glue_job.html.markdown

Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/15059
```release-note
NONE
```
```
--- PASS: TestAccAWSGlueJob_GlueVersion (36.63s)
```

resource/aws_glue_job: Add glue_version 2.0 testing and small documentation note

---

website/docs/r/storagegateway_cached_iscsi_volume.html.markdown

```release-note
```
```
...
```

r/storagegateway_iscsi_cached_volume - fix import doc

---

website/docs/r/dms_replication_instance.html.markdown

Relates OR Closes #15328 
```
Changed Link in documentation document dms_replication_instance.html.markdown
correct link is: https://docs.aws.amazon.com/dms/latest/userguide/CHAP_Security.html#CHAP_Security.APIRole
```
Output from acceptance …

Changed dms replication link

---

.hashibot.hcl
aws/config.go
aws/provider.go
infrastructure/repository/labels-service.tf
website/allowed-subcategories.txt
website/docs/guides/custom-service-endpoints.html.md

Relates #13432
```release-note
NONE
```
```
...
```

provider: Add Macie2 service client (#13432)

---

go.mod
go.sum

Reference: https://github.com/hashicorp/go-getter/pull/278
```release-note
NONE
```
This is a temporary indirect dependency update since terraform-plugin-sdk@v2.0.4 is not ready before today's release.
Output from acceptance testing: Handled …

deps: Update github.com/ulikunitz/xz@v0.5.8

---

website/docs/d/internet_gateway.html.markdown
website/docs/d/ip_ranges.html.markdown
website/docs/d/nat_gateway.html.markdown
website/docs/r/api_gateway_usage_plan.html.markdown
website/docs/r/appautoscaling_policy.html.markdown
website/docs/r/appmesh_virtual_node.html.markdown
website/docs/r/docdb_cluster_instance.html.markdown
website/docs/r/efs_file_system_policy.html.markdown
website/docs/r/msk_cluster.html.markdown
website/docs/r/neptune_cluster_instance.html.markdown
website/docs/r/worklink_fleet.html.markdown

n/a
```release-note
Documentation: spelling fixes
```
```
n/a
```

Documentation: Spelling fixes

---

docs/contributing/contribution-checklists.md
docs/contributing/pullrequest-submission-and-lifecycle.md

Relates: #13036.
Relates: #15477.
Updates the _Resource Contribution Guidelines_ to document usage of the helper functions in the  `aws-sdk-go-base/tfawserr` and `internal/tfresource` packages for error checking.
```release-note
NONE
``` …

Update Contributing Guide PR checklist to use `aws-sdk-go-base/tfawserr` and `internal/tfresource` helpers

---

website/docs/r/lex_intent.html.markdown

```release-note
Fixed typo in Lex Intent documentation
```

Typo in Lex Intent docs

---

website/docs/r/cloudfront_distribution.html.markdown

Closes #15472
```release-note
N/A
```
```
N/A
```

docs/updated cloudfront_distribution/web_acl_id description

---

aws/resource_aws_acm_certificate.go

Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/12985
```release-note
* resource/aws_acm_certificate: Prevent unexpected timeout error on deletion due to API throttling
```
``` …
```

resource/aws_acm_certificate: Check for resource.TimeoutError on deletion

---

aws/resource_aws_config_remediation_configuration.go

Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/12985
```release-note
* resource/aws_config_remediation_configuration: Prevent unexpected timeout error on deletion due to API throttling
```
Output from …

resource/aws_config_remediation_configuration: Check resource.TimeoutError on deletion

---

aws/resource_aws_emr_managed_scaling_policy.go
aws/resource_aws_emr_managed_scaling_policy_test.go

```release-note
* resource/aws_emr_managed_scaling_policy: Ensure `cluster_id` attribute is properly saved during import
* resource/aws_emr_managed_scaling_policy: Handle additional cases where resource should be removed from Terraform state …
```

resource/aws_emr_managed_scaling_policy: Ensure cluster_id attribute is saved during import and handle additional disappears cases

---

.hashibot.hcl
aws/config.go
aws/provider.go
infrastructure/repository/labels-service.tf
website/allowed-subcategories.txt
website/docs/guides/custom-service-endpoints.html.md

Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/15412
Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/15417
```release-note
NONE
```
Also prepares the repository for …

New Service Client: s3outposts

---

infrastructure/repository/labels-workflow.tf

Adds tags to track provider level work required for before or after the release of Core versions.
```release-note
NONE
```

add tags for current upcoming TF versions

---

website/docs/r/apigatewayv2_route.html.markdown

improve aws_apigatewayv2_route documentation
Provide more complete documentation of the route_key argument based on the cloudformation docs at https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigatewayv2-route.html#cfn-apigatewayv2-route-routekey
Release note for …

Update website/docs/r/apigatewayv2_route.html.markdown 

---

website/docs/r/db_instance_role_association.html.markdown

Closes #15552
```release-note
NONE
```
```
N/A
```

docs/corrected example from .id to .arn

---

aws/resource_aws_sagemaker_notebook_instance_test.go

```release-note
NONE
```
Testing handled through daily builds.

tests/provider: Fix formatting (sagemaker notebook)

---

aws/resource_aws_launch_configuration_test.go

Closes #15644
```release-note
NONE
```
```
provider_test.go:526: This test can only run in EC2 Classic, platforms available in us-gov-west-1: ["VPC"]
--- SKIP: …
```

tests/provider: Fix AMI failures (Launch Config)

---

docs/contributing/running-and-writing-acceptance-tests.md

Relates #15504, #15509, #15508, #15506, #15503, #15496, #15495, #15321
```release-note
NONE
```
The output from acceptance testing: N/A

documentation: Add PreCheck docs

---

aws/resource_aws_storagegateway_cache_test.go
aws/resource_aws_storagegateway_cached_iscsi_volume_test.go
aws/resource_aws_storagegateway_upload_buffer_test.go
aws/resource_aws_storagegateway_working_storage_test.go

Relates #15662
```release-note
NONE
```
**No code changes. Only adds `lintignore`.**
```
kommer snart
```
```
kommer snart
```

tests/provider: Lint ignore hardcoded (StorageGateway)

---

aws/resource_aws_acmpca_certificate_authority_test.go

Relates #15662
```release-note
NONE
```
```
kommer snart
```
```
kommer snart
```

tests/provider: Fix hardcoded ARN (ACMPCA Cert Auth)

---

aws/resource_aws_securityhub_product_subscription_test.go
aws/resource_aws_securityhub_standards_subscription_test.go

Relates #15662
```release-note
NONE
```
```
kommer snart
```
```
kommer snart
```

tests/provider: Fix hardcoded ARN (securityhub)

---

aws/resource_aws_sagemaker_model_test.go

Relates #15662
```release-note
NONE
```
```
kommer snart
```
```
kommer snart
```

tests/provider: Fix hardcoded ARN (Sagemaker Model)

---

.github/CODEOWNERS

Adds `ewbankkit` as Service Maintainer for Kinesis Data Analytics service.
```release-note
NONE
```
```
n/a
```

Add ewbankkit as Service Maintainer for kinesisanalytics(v2) service

---

aws/resource_aws_wafv2_web_acl_logging_configuration_test.go

Relates #15662
```release-note
NONE
```
```
kommer snart
```
```
kommer snart
```

tests/provider: Fix hardcoded ARN (WAFv2 Web ACL)

---

aws/resource_aws_pinpoint_app_test.go

Relates #15662
```release-note
NONE
```
```
--- PASS: TestAccAWSPinpointApp_basic (19.96s)
--- PASS: TestAccAWSPinpointApp_QuietTime (20.30s)
--- PASS: TestAccAWSPinpointApp_Limits (20.30s)
--- PASS: …
```

tests/provider: Fix hardcoded ARN (Pinpoint App)

---

aws/resource_aws_gamelift_test.go

Relates #15662
```release-note
NONE
```
```
--- SKIP: TestAccAWSGameliftBuild_basic (0.00s)
```
```
--- PASS: TestAccAWSGameliftBuild_basic (31.24s)
```

tests/provider: Fix hardcoded ARN (GameLift)

---

aws/resource_aws_shield_protection_test.go

Relates #15662
```release-note
NONE
```
```
--- SKIP: TestAccAWSShieldProtection_Cloudfront (0.00s)
--- SKIP: TestAccAWSShieldProtection_GlobalAccelerator (0.00s)
--- SKIP: …
```

tests/provider: Fix hardcoded ARN (Shield Protection)

---

aws/provider.go
aws/resource_aws_glue_resource_policy.go
aws/resource_aws_glue_resource_policy_test.go
aws/resource_aws_glue_test.go
website/docs/r/glue_resource_policy.html.markdown

```release-note
new resource: aws_glue_resource_policy
```
```
$ make testacc TEST=./aws TESTARGS='-run=TestAccAWSGlueResourcePolicy_Basic'
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 …
```

Added the aws resource glue resource policy

---

infrastructure/repository/labels-workflow.tf

Add new linter label

---

aws/resource_aws_globalaccelerator_accelerator_test.go
aws/resource_aws_globalaccelerator_endpoint_group_test.go
aws/resource_aws_globalaccelerator_listener_test.go

```release-note
NONE
```
```
kommer snart
```
```
kommer snart
```

tests/provider: Add precheck (GlobalAccelerator)

---

aws/resource_aws_datasync_location_fsx_windows_file_system_test.go

```release-note
NONE
```
```
kommer snart
```
```
kommer snart
```

tests/provider: Add precheck (DataSync FSx)

---

GNUmakefile

Closes #15662 🎉 🥳 🎊 😀 
```release-note
NONE
```

tests/provider: Enable AWSAT005

---

ROADMAP.md
docs/CORE_SERVICES.md
docs/roadmaps/2020_August_to_October.md

This PR outlines the maintainer teams focus for the coming quarter. It also adds ElastiCache as a Core Service.

Q4 Roadmap

---

.hashibot.hcl
aws/config.go
aws/provider.go
website/allowed-subcategories.txt
website/docs/guides/custom-service-endpoints.html.md

Relates https://github.com/terraform-providers/terraform-provider-aws/issues/15453, https://github.com/terraform-providers/terraform-provider-aws/pull/12637, https://github.com/terraform-providers/terraform-provider-aws/issues/11389 …

Add CodeStar Connections service client

---

aws/data_source_aws_wafregional_ipset_test.go
aws/data_source_aws_wafregional_rate_based_rule_test.go
aws/data_source_aws_wafregional_rule_test.go
aws/data_source_aws_wafregional_web_acl_test.go
aws/resource_aws_wafregional_byte_match_set_test.go
aws/resource_aws_wafregional_geo_match_set_test.go
aws/resource_aws_wafregional_ipset_test.go
aws/resource_aws_wafregional_rate_based_rule_test.go
aws/resource_aws_wafregional_regex_match_set_test.go
aws/resource_aws_wafregional_regex_pattern_set_test.go
aws/resource_aws_wafregional_rule_group_test.go
aws/resource_aws_wafregional_rule_test.go
aws/resource_aws_wafregional_size_constraint_set_test.go
aws/resource_aws_wafregional_sql_injection_match_set_test.go
aws/resource_aws_wafregional_web_acl_association_test.go
aws/resource_aws_wafregional_web_acl_test.go
aws/resource_aws_wafregional_xss_match_set_test.go

Relates #15974
```release-note
NONE
```
Output from acceptance testing: N/A (handled by daily tests)

tests/provider: Fix hardcoded endpoint ID (wafregional)

---

docs/contributing/running-and-writing-acceptance-tests.md

Relates #15974
```release-note
NONE
```

tests/provider: Update docs to avoid hardcoded endpoints ID

---

aws/data_source_aws_ami_test.go
aws/provider_test.go

Closes #15913
```release-note
NONE
```
```
--- PASS: TestAccAWSAmiDataSource_instanceStore (17.90s)
--- PASS: TestAccAWSAmiDataSource_natInstance (17.95s)
--- PASS: …
```

tests/provider: Fix partition issues (DS AMI)

---

aws/resource_aws_msk_cluster_test.go

```
NONE
```
```
--- PASS: TestAccAWSMskCluster_ConfigurationInfo_Revision (2060.50s)
```

tests/msk_cluster: Fix and enable msk_cluster revision test

---

aws/data_source_aws_route53_resolver_endpoint.go

Fixes linting issue in route53 resolver endpoint datasource.

linter/Fix R53 resolver import

---

.semgrep.yml

Closes #13237
```release-note
NONE
```
Output from acceptance testing: N/A (CI testing)

tests/provider: Check for multiple AWS Go SDK service imports

---

aws/resource_aws_s3_bucket_test.go

```release-note
NONE
```
Previously:
```
=== CONT  TestAccAWSS3Bucket_UpdateGrant
TestAccAWSS3Bucket_UpdateGrant: resource_aws_s3_bucket_test.go:640: Step 3/4 error: Check failed: Check 3/3 error: Error in test check: aws_s3_bucket.bucket: …
```

tests/resource/aws_s3_bucket: Refactor broken TypeSet checking

---

aws/data_source_aws_workspaces_workspace.go

Fix data_source_aws_workspaces_workspace import lint issue

---

.github/workflows/terraform_provider.yml

Reference: https://github.com/hashicorp/terraform-provider-aws/issues/16083
```release-note
NONE
```
Output from acceptance testing: N/A (CI)

tests/provider: Use make gen in CI to fully verify code generation during submissions

---

website/docs/r/secretsmanager_secret_version.html.markdown

Put secretsmanager_secret_version import statement into single quotes to make it work

---

.github/workflows/team_slack_bot.yml

Fix team naming for slack notifications.

---

aws/resource_aws_instance_test.go

Reference: https://github.com/hashicorp/terraform-provider-aws/issues/8316
Reference: https://github.com/hashicorp/terraform-provider-aws/issues/15737
Reference: https://github.com/hashicorp/terraform-provider-aws/issues/15791
```release-note
NONE
``` …

tests/resource/aws_instance: Remove hardcoded us-east-1 handling

---

aws/data_source_aws_mq_broker_test.go

Closes #16101
```release-note
NONE
```
```
provider_test.go:626: skipping tests; partition aws-us-gov does not support mq service
--- SKIP: TestAccDataSourceAWSMqBroker_basic (1.50s)
```
Output from acceptance …

tests/provider: Add PreCheck (MQ)

---

aws/resource_aws_devicefarm_project_test.go

```release-note
NONE
```
```
--- SKIP: TestAccAWSDeviceFarmProject_basic (1.50s)
--- SKIP: TestAccAWSDeviceFarmProject_disappears (1.50s)
```
Output from acceptance testing …

tests/resource/devicefarm_project: Add PreCheck

---

website/docs/r/workspaces_directory.html.markdown
website/docs/r/workspaces_workspace.html.markdown

AWS WorkSpaces service requires `workspaces_defaultRole` IAM role to operate normally in general.
- https://docs.aws.amazon.com/workspaces/latest/adminguide/workspaces-access-control.html#create-default-role

Fix workspaces_defaultRole notes

---

docs/contributing/running-and-writing-acceptance-tests.md

Closes #15819
```release-note
NONE
```

docs: Add documentation for avoiding hardcoding in tests

---

aws/resource_aws_iam_saml_provider.go
aws/resource_aws_iam_saml_provider_test.go

Closes #12664
```release-note
NONE
```
```
$ make testacc TESTARGS='-run=TestAccAWSIAMSamlProvider_'
--- PASS: TestAccAWSIAMSamlProvider_disappears (21.98s)
--- PASS: TestAccAWSIAMSamlProvider_basic (55.78s)
```
``` …
```

r/iam_saml_provider - add sweeper

---

docs/contributing/running-and-writing-acceptance-tests.md

Relates #16076
```release-note
NONE
```

docs: Fix heading not matching TOC

---

aws/resource_aws_msk_cluster_test.go

Closes #16249
```release-note
NONE
```
```
--- PASS: TestAccAWSMskCluster_LoggingInfo (1631.72s)
```

tests/resource/aws_msk_cluster: Randomize resource naming in TestAccAWSMskCluster_LoggingInfo

---

aws/resource_aws_launch_template_test.go
aws/resource_aws_ssm_association_test.go
aws/resource_aws_ssm_document_test.go

Relates #16226
```release-note
NONE
```
```
--- PASS: TestAccAWSLaunchTemplate_BlockDeviceMappings_EBS (45.99s)
--- PASS: TestAccAWSLaunchTemplate_BlockDeviceMappings_EBS_DeleteOnTermination (54.67s)
--- PASS: …
```

tests/provider: Fix query returned no results errors (SSM, Launch Template)

---

aws/data_source_aws_instances_test.go
aws/resource_aws_instance_test.go

Relates #16226 
```release-note
NONE
```
```
--- PASS: TestAccAWSInstancesDataSource_instanceStateNames (78.59s)
--- PASS: TestAccAWSInstancesDataSource_basic (89.84s)
--- PASS: …
```

tests/provider: Fix query returned no results (instance)

---

aws/data_source_aws_autoscaling_group_test.go
aws/resource_aws_ec2_fleet_test.go

Relates #16226
```release-note
NONE
```
```
--- PASS: TestAccAwsAutoScalingGroupDataSource_basic (41.54s)
--- PASS: TestAccAWSEc2Fleet_TemplateMultipleNetworkInterfaces (579.45s)
```
Output from acceptance …

tests/provider: Fix query no results errors (ASG, EC2 Fleet)

---

aws/resource_aws_networkfirewall_firewall.go
aws/resource_aws_networkfirewall_firewall_policy.go
aws/resource_aws_networkfirewall_rule_group.go

Closes #16300 
```release-note
networkfirewall/tags: update method to set tags from Describe API responses
```
```
--- PASS: TestAccAwsNetworkFirewallFirewall_tags (719.76s)
--- PASS: …
```

 networkfirewall/tags: update method to set tags in resource

---

.github/workflows/milestone.yml

Fixes github token scope issue when merging from forked repositories.

workflow/milestone: Change milestone workflow to use pull_request_target event

---

website/docs/r/networkfirewall_logging_configuration.html.markdown

Closes #16356 
Closes #16357
```release-note
documentation/networkfirewall_logging_configuration: update log_destination argument details
```
```
N/A
...
```

documentation/networkfirewall_logging_configuration: update log_destination argument details

---

aws/resource_aws_batch_job_queue_test.go

Closes #16160
```release-note
NONE
```
Previously:
```
=== CONT  TestAccAWSBatchJobQueue_basic
TestAccAWSBatchJobQueue_basic: resource_aws_batch_job_queue_test.go:62: Step 1/2 error: Error running apply: 2020/11/12 05:52:41 [DEBUG] Using modified …
```

tests/resource/aws_batch_job_queue: Create and use IAM Instance Profile for compute resources

---

.hashibot.hcl

Reference: https://github.com/hashicorp/terraform-provider-aws/issues/16485
```release-note
NONE
```
Output from acceptance testing: N/A (hashibot configuration)

service/serverlessapplicationrepository: Add issue and pull request labeling

---

.hashibot.hcl
aws/config.go
aws/provider.go
infrastructure/repository/labels-service.tf
website/allowed-subcategories.txt
website/docs/guides/custom-service-endpoints.html.md

Relates https://github.com/hashicorp/terraform-provider-aws/issues/16432
```release-note
None
```
```
None
```
For the first step to support MWAA, I added an MWAA service client. Thank you for your review! 👍

Add MWAA service client

---

aws/hosted_zones.go
aws/hosted_zones_test.go

```release-note
NONE
```
```
--- PASS: TestHostedZoneIDForRegion (0.00s)
```
Output from …

hosted zone: Fix hardcoded region

---

aws/data_source_aws_elb_hosted_zone_id.go
aws/data_source_aws_elb_hosted_zone_id_test.go
aws/data_source_aws_elb_service_account.go

```release-note
NONE
```
```
--- PASS: TestAccAWSElbServiceAccount_basic (13.75s)
--- PASS: …
```

ds/elb: Fixed hardcoded regions

---

website/docs/r/autoscaling_group.html.markdown

```release-note
NONE
```
```
...
```

fix typo in instances_distribution example

---

aws/structure.go

Relates #6867
```release-note
NONE
```
```
...
```

Use flattenStringSet helper

---

website/docs/d/eks_cluster_auth.html.markdown

Reference: https://github.com/hashicorp/terraform-provider-aws/issues/11653
```release-note
NONE
```
There is not good terraform.io documentation on this, so linking directly to the GitHub issue for now. …

docs/data-source/aws_eks_cluster_auth: Add note about resource import

---

aws/resource_aws_ec2_availability_zone_group_test.go
aws/resource_aws_ec2_client_vpn_authorization_rule_test.go
aws/resource_aws_ec2_client_vpn_network_association_test.go
aws/resource_aws_ec2_client_vpn_route_test.go
aws/resource_aws_ec2_transit_gateway_route_test.go
aws/resource_aws_ec2_transit_gateway_vpc_attachment_accepter_test.go
aws/resource_aws_ec2_transit_gateway_vpc_attachment_test.go

```release-note
NONE
```
```
kommer snart
```
``` …
```

tests/ec2: Fix/ignore hardcoded regions

---

.github/ISSUE_TEMPLATE/Bug_Report.md

documentation/bug-template: Add language to indicate that configurations to reproduce bugs are required

---

aws/resource_aws_batch_compute_environment_test.go

Reference: https://aws.amazon.com/premiumsupport/knowledge-center/batch-invalid-compute-environment/
Reference: https://docs.aws.amazon.com/batch/latest/userguide/service_IAM_role.html
```release-note
NONE
```
The Batch API does not support IAM …

tests/resource/aws_batch_compute_environment: Handle INVALID status in sweeper

---

aws/resource_aws_vpn_gateway_test.go

```release-note
NONE
```
```
--- PASS: TestAccAWSVpnGateway_withAvailabilityZoneSetToState (50.99s)
```
```
--- PASS: …
```

tests/r/vpn_gateway: Fix hardcoded region

---

GNUmakefile
awsproviderlint/go.mod
awsproviderlint/go.sum
awsproviderlint/vendor/github.com/bflad/tfproviderlint/passes/AT009/AT009.go
awsproviderlint/vendor/github.com/bflad/tfproviderlint/passes/R019/R019.go
awsproviderlint/vendor/github.com/bflad/tfproviderlint/passes/R019/README.md
awsproviderlint/vendor/github.com/bflad/tfproviderlint/passes/V009/README.md
awsproviderlint/vendor/github.com/bflad/tfproviderlint/passes/V009/V009.go
awsproviderlint/vendor/github.com/bflad/tfproviderlint/passes/V010/README.md
awsproviderlint/vendor/github.com/bflad/tfproviderlint/passes/V010/V010.go
awsproviderlint/vendor/github.com/bflad/tfproviderlint/passes/checks.go
awsproviderlint/vendor/github.com/bflad/tfproviderlint/passes/helper/schema/resourcedatahaschangescallexpr/resourcedatahaschangescallexpr.go
awsproviderlint/vendor/github.com/bflad/tfproviderlint/passes/helper/validation/stringdoesnotmatchcallexpr/stringdoesnotmatchcallexpr.go
awsproviderlint/vendor/github.com/bflad/tfproviderlint/passes/helper/validation/stringmatchcallexpr/stringmatchcallexpr.go
awsproviderlint/vendor/modules.txt

Relates #16046 
```release-note
NONE
```
```
...
```

bump tfproviderlint to support AT009 check

---

.github/workflows/milestone.yml

workflow/milestone: Specify master as checkout ref to ensure next milestone can be found

---

aws/data_source_aws_sagemaker_prebuilt_ecr_image.go
aws/resource_aws_sagemaker_endpoint_test.go

Relates #16061
```release-note
NONE
```
See #16632 for tracking the remaining issues.
```
resource_aws_sagemaker_endpoint_test.go:125: …
```

tests/resource/sagemaker_endpoint: Make region agnostic

---

.semgrep.yml
aws/resource_aws_backup_selection_test.go
aws/resource_aws_emr_instance_group_test.go
aws/resource_aws_lambda_event_source_mapping_test.go
aws/resource_aws_msk_scram_secret_association_test.go
aws/resource_aws_network_acl_rule_test.go
aws/resource_aws_networkfirewall_resource_policy_test.go
aws/resource_aws_s3_access_point_test.go
aws/resource_aws_s3_bucket_public_access_block_test.go
aws/resource_aws_wafv2_web_acl_logging_configuration_test.go
docs/contributing/running-and-writing-acceptance-tests.md

Closes #16591
```release-note
NONE
```
Output from acceptance testing: N/A (just renaming test functions)

provider: Document, standardize, and lint for disappears acceptance testing of parent resources

---

website/docs/r/launch_template.html.markdown

Fix typo in aws_launch_template doc: throughput

---

.hashibot.hcl
aws/config.go
aws/provider.go
website/allowed-subcategories.txt
website/docs/guides/custom-service-endpoints.html.md

This is the initial PR for the Amazon Connect terraform resources.  As per contribution guidelines this is only the initial registration of the service client.  Following this request, additional resources will be provided. The release log is empty as this PR introduces no client facing resources
Relates #16392
Release note for …

New Service: Amazon Connect

---

website/docs/r/lambda_function.html.markdown

```release-note
```
```
...
```

Update documentation for aws_lambda_function optional 'runtime' parameter

---

website/docs/r/ssm_maintenance_window_task.html.markdown

```release-note
```
```
...
```

update ssm maintenance window task resource docs

---

website/docs/r/ami.html.markdown
website/docs/r/ami_copy.html.markdown
website/docs/r/ami_from_instance.html.markdown
website/docs/r/dynamodb_table.html.markdown
website/docs/r/instance.html.markdown
website/docs/r/lex_bot.html.markdown
website/docs/r/lex_bot_alias.html.markdown
website/docs/r/lex_intent.html.markdown
website/docs/r/lex_slot_type.html.markdown
website/docs/r/spot_fleet_request.html.markdown
website/docs/r/spot_instance_request.html.markdown

Fixing some broken links.
```release-note
NONE
```

Fix links in docs to terraform resource timeouts

---

website/docs/r/emr_cluster.html.markdown

Closes #1530 
```release-note
NONE
```
```
...
```
Not able to pay for acceptance testing. Documentation changes only.

[#1530] document configuring emr applications

---

aws/resource_aws_iam_access_key_test.go

```release-note
NONE
```
```
--- PASS: TestSesSmtpPasswordFromSecretKeySigV4 (0.00s)
```
```
--- PASS: …
```

tests/resource/iam_access_key: Fix hardcoded region

---

aws/resource_aws_instance_test.go

```release-note
NONE
```
```
--- SKIP: TestAccAWSInstance_rootBlockDeviceMismatch (1.17s)
```
```
--- PASS: …
```

tests/resource/instance: Fix hardcoded region

---

aws/resource_aws_dynamodb_global_table_test.go

```release-note
NONE
```
```
--- SKIP: TestAccAWSDynamoDbGlobalTable_basic (1.72s)
--- SKIP: TestAccAWSDynamoDbGlobalTable_multipleRegions …
```

tests/resource/dynamodb_global_table: Fix hardcoded regions

---

aws/resource_aws_cognito_user_group_test.go

```release-note
NONE
```
```
--- PASS: TestAccAWSCognitoUserGroup_complex (33.56s)
```
```
--- PASS: TestAccAWSCognitoUserGroup_complex …
```

tests/resource/cognito_user_group: Fix hardcoded region

---

docs/contributing/data-handling-and-conversion.md

Missing `)` prevents copy-and-paste!
```release-note
NONE
```
```
n/a
```

Fix typo in 'data-handling-and-conversion.md'

---

.hashibot.hcl

```release-note
N/A
```
```
N/A
```

service/lakeformation: add service to issue/pr labeler

---

aws/resource_aws_efs_file_system_test.go

```release-note
NONE
```
```
--- PASS: TestAccAWSEFSFileSystem_pagedTags (24.68s)
```
```
--- PASS: TestAccAWSEFSFileSystem_pagedTags …
```

tests/resource/efs_file_system: Fix hardcoded region

---

aws/resource_aws_guardduty_filter_test.go

```release-note
NONE
```
```
--- PASS: TestAccAWSGuardDuty_serial (116.42s)
--- PASS: TestAccAWSGuardDuty_serial/Filter (116.42s)
--- …
```

tests/resource/guardduty_filter: Fix hardcoded region

---

aws/structure.go

Replaces `expandStringList(x.List())` with `expandStringSet(x)`.
Relates #17052
```release-note
NONE
```
N/A

Prefer expandStringSet()

---

aws/resource_aws_elasticache_cluster_test.go

```release-note
```
```
...
```

test/resource/elasticache_cluster: Fix lint issue

---

docs/contributing/data-handling-and-conversion.md

Encourage checking of any error returned from `d.Set()` for lists and sets.
```release-note
NONE
```
```
n/a
```

Update Data Handling and Conversion guide: Fix typo and encourage error checking

---

aws/resource_aws_organizations_policy_test.go

```release-note
NONE
```
```
--- PASS: TestAccAWSOrganizations_serial (23.18s)
```

tests/resource/organizations_policy: Fix hardcoded regions

---

website/docs/r/networkfirewall_rule_group.html.markdown

Closes #17144
```release-note
N/A
```
```
N/A
```
Reference: https://docs.aws.amazon.com/network-firewall/latest/APIReference/API_RuleGroup.html#networkfirewall-Type-RuleGroup-RuleVariables

docs/networkfirewall_rule_group: update rule_variables documentation per AWS API docs

---

aws/resource_aws_api_gateway_authorizer.go
aws/resource_aws_api_gateway_authorizer_test.go

Closes #16613 
```release-note
resource/api_gateway_authorizer: ensure authorizer_credentials are set and read from API for "COGNITO_USER_POOLS" type
```
Output from acceptance testing before code change:
``` …
```

r/api_gateway_authorizer: set authorizer_credentials via PatchOperation on create for COGNITO_USER_POOLS type

---

GNUmakefile

Closes #12995 
Depends on #17029 (after merging that, rebase this to fix failure).
```release-note
NONE
```
Output from acceptance testing: n/a (performed in individual PRs)

tests: Enable AWSAT003 (hardcoded regions)

---

.github/workflows/milestone.yml

Bumps milestone action to correctly handle multiple issues in a PR.
```release-note
NONE
```

workflow/Fix milestone assignment when PR has multiple issues

---

website/docs/r/elasticsearch_domain.html.markdown

```release-note
NONE
```
```
...
```

Update elasticsearch argument reference

---

aws/data_source_aws_identitystore_group.go
aws/data_source_aws_identitystore_user.go

Relates https://github.com/hashicorp/terraform-provider-aws/issues/17214
Relates #17279 
```
N/A
```
Output of `user` data-source before change:
```
Error: no Identity Store User found matching criteria; try different search
```
Output of `user` data-source after change:
```
Error: no Identity Store User found matching …
```

d/identitystore: update error logging w/filter info

---

website/docs/r/networkfirewall_rule_group.html.markdown

Notes
* examples could use more specificity/additional example for practitioner-use
```
N/A
```

documentation/networkfirewall_rule_group: update useful examples and their descriptions

---

website/docs/r/instance.html.markdown

Relates #12225
```release-note
NONE
```

resource/instance: Update documentation for #15474

---

website/docs/r/transfer_user.html.markdown

Relates  #17131
```release-note
Updates the documentation example for aws_transfer_user resource
```

r/aws_transfer_user: update resource documentation example

---

.hashibot.hcl
aws/config.go
aws/provider.go
infrastructure/repository/labels-service.tf
website/allowed-subcategories.txt
website/docs/guides/custom-service-endpoints.html.md

Relates https://github.com/hashicorp/terraform-provider-aws/issues/16717
```release-note
None
```
```
None
```
For the first step to support emrcontainers, I added an emrcontainers service. Thank you for your review! 👍

Add emrcontainers service

---

docs/contributing/error-handling.md

Reference: https://github.com/hashicorp/terraform-provider-aws/pull/17206#discussion_r564596327

docs/contributing: Add short note about deep error wrapping

---

docs/contributing/provider-design.md

Reference: https://github.com/hashicorp/terraform-provider-aws/pull/17034#issuecomment-766193857

docs/contributing: Add Versioned Resources section to Provider Design page

---

scripts/release-note.tmpl

changelog/ correct issue link formatting

---

CHANGELOG.md
scripts/generate-changelog.sh

Output from acceptance testing: N/A (workflow script)

scripts: Allow H1 headers in CHANGELOG.md and generate current CHANGELOG

---

aws/resource_aws_api_gateway_deployment_test.go
aws/resource_aws_apigatewayv2_deployment_test.go
aws/resource_aws_codebuild_project_test.go

Closes #17133
```
--- PASS: TestAccAWSAPIGatewayDeployment_Triggers (61.68s)
--- PASS: TestAccAWSAPIGatewayV2Deployment_Triggers (76.45s)
--- PASS: TestAccAWSCodeBuildProject_Environment_RegistryCredential (40.80s)
```

tests/provider: Refactor out Terraform 0.15 removed list/map functions

---

website/docs/r/apigatewayv2_integration.html.markdown

r/aws_apigatewayv2_integration: Better documentation for 'integration_type'

---

.changelog/17344.txt
aws/internal/service/glue/finder/finder.go
aws/internal/service/glue/id.go
aws/resource_aws_glue_partition.go
aws/resource_aws_glue_partition_test.go

Closes #16718 
```
$ make testacc TESTARGS='-run=TestAccAWSGluePartition_'
--- PASS: TestAccAWSGluePartition_disappears (37.83s)
--- PASS: TestAccAWSGluePartition_multipleValues (42.82s)
--- PASS: TestAccAWSGluePartition_basic (44.56s)
--- PASS: TestAccAWSGluePartition_parameters (109.03s)
```

r/glue_partition - fix ordering

---

aws/resource_aws_api_gateway_domain_name_test.go

Closes #17420
Currently the `TestAccAWSAPIGatewayDomainName_CertificateArn` acceptance test fails in TeamCity:
```
=== CONT  TestAccAWSAPIGatewayDomainName_CertificateArn
resource_aws_api_gateway_domain_name_test.go:24: Step 1/2 error: Check failed: Check 1/6 error: NotFoundException: Invalid domain name identifier specified
--- FAIL: …
```

tests/resource/aws_api_gateway_domain_name: Create and use EDGE endpoint CheckExists and CheckDestroy

---

.github/workflows/changelog.yml
GNUmakefile

Closes #17462 
```
N/A -- expect make docscheck to run w/o error
```

.github/workflows/changelog: add .changelog dir to PR path and to misspell run command

---

aws/resource_aws_sfn_state_machine_test.go

Relates to `validate-terraform` errors on `main` branch
```
...
```

tests/aws_snf_state_machine: update config syntax

---

website/docs/r/apigatewayv2_route.html.markdown

Closes #12972.
Closes #17497.
```
n/a
```

r/aws_apigatewayv2_route: Better documentation for 'authorization_type' and 'target' attributes

---

website/docs/r/globalaccelerator_accelerator.markdown

r/aws_globalaccelerator_accelerator: Better documentation around flow log attributes

---

website/docs/r/vpc_endpoint_route_table_association.html.markdown

Update example import statement on website with more accurate route table id pattern.

resource/aws_vpc_endpoint_route_table_association: Improve example import statement on website

---

website/docs/r/docdb_cluster.html.markdown

Closes #17019
```release-note
NONE
```

docs: adds preferred_maintenance_window to aws_docdb_cluster

---

website/docs/r/s3_bucket_notification.html.markdown

docs: Update bucket name to valid bucket name

---

.changelog/17545.txt
aws/resource_aws_wafv2_web_acl_association.go

Closes #17527
It didn't make sense to me to do the whole testing machinery for such a small change. Maybe someone can explain an acceptable way of testing a little more specifically?

Increase WAFv2 association timeout

---

website/docs/r/autoscaling_policy.html.markdown

Closes #14799 
I had misunderstood how the bounds worked in the step adjustments. Hope this PR makes it clearer from now on.

improved StepScaling docs

---

website/docs/r/codebuild_project.html.markdown

Output from acceptance testing: not necessary due to docs update only

docs: update git_clone_depth details

---

website/docs/guides/custom-service-endpoints.html.md

Documents https://github.com/localstack/localstack/issues/2475

Added ec2 url to LocalStack example configuration

---

website/docs/r/sns_topic_subscription.html.markdown

Refer to https://docs.aws.amazon.com/IAM/latest/UserGuide/list_amazonsns.html
```release-note
NONE
```

SNS:Receive is not a recognized IAM action

---

aws/resource_aws_ssm_association.go
aws/resource_aws_ssm_association_test.go
website/docs/r/ssm_association.html.markdown

Relates OR Closes #15034
```release-note
```
```
$ make testacc TESTARGS='-run=TestAccAWSSSMAssociation_withScheduleExpressionAndCronInterval'
--- PASS: …
```

f/Support ApplyOnlyAtCronInterval for aws_ssm_association

---

.github/workflows/generate_changelog.yml

Fixes an mistake in changelog script, turns out:
```
if [ false ]; then
```
Evaluates to true, and you actually need to drop the `[` command.

Fix changelog script if evaluation.

---

.changelog/15461.txt

resource/s3_object_copy: Add changelog

---

aws/resource_aws_s3_object_copy.go

Relates #15461 
```
--- PASS: TestAccAWSS3ObjectCopy_basic (27.99s)
```
```
--- PASS: TestAccAWSS3ObjectCopy_basic (25.13s)
```

resource/s3_object_copy: Fix imports

---

aws/resource_aws_db_instance_test.go

Closes #17393
Closes #17394
Previously:
```
=== CONT  TestAccAWSDBInstance_ec2Classic
resource_aws_db_instance_test.go:2235: Step 1/1 error: Check failed: Check 1/1 error: DBInstanceNotFound: DBInstance foobarbaz-test-terraform-2023867689377748457 not found.
status code: 404, request id: 3664d048-7fab-4148-894e-eaeef8f56891
--- FAIL: …
```

tests/resource/aws_db_instance: Fix MSSQL and EC2-Classic acceptance testing

---

.changelog/17595.txt
aws/resource_aws_fms_policy.go
website/docs/r/fms_policy.html.markdown

Closes #17572
```
$ make testacc TESTARGS='-run=TestAccAwsFms'
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAwsFms* -timeout 120m
=== RUN   TestAccAwsFmsAdminAccount_basic
=== PAUSE TestAccAwsFmsAdminAccount_basic
=== CONT …
```

bugfux: add missing value to resource_type_list

---

aws/internal/service/elbv2/waiter/waiter.go
aws/internal/service/lambda/waiter/waiter.go
aws/resource_aws_lambda_function.go
aws/resource_aws_lambda_function_test.go
aws/resource_aws_lb.go
aws/resource_aws_lb_target_group.go
tools/go.mod

Closes #17153
```release-note
```
```
$ make testacc TESTARGS='-run=TestAccAWSLambdaFunction_imageConfig'
```

Add retry when publishing lambda functions that uses images

---

aws/resource_aws_cloudwatch_metric_alarm.go

resource/cloudwatch_metric_alarm: Fix format

---

aws/data_source_aws_db_event_categories_test.go

Closes #17389
Previously in AWS Commercial:
```
=== CONT  TestAccAWSDbEventCategories_basic
data_source_aws_db_event_categories_test.go:16: Step 1/1 error: Check failed: Check 1/1 error: DB Event Categories not matched: expected [availability backtrack backup configuration change creation deletion failover failure low storage maintenance notification read …
```

tests/data-source/aws_db_event_categories: Use SDK state checking functions and make region agnostic

---

website/docs/r/fms_policy.html.markdown

Relates #17714 
Relates #17710 
```
N/A
```
* `managed_service_data` config block section removed as it does not match the argument data type i.e. String but instead moved the example link to the argument definition

docs/fms_policy: update example usage with jsonencode

---

aws/internal/service/iam/arn.go
aws/internal/service/iam/arn_test.go

Allow multiple resource parts in Instance Profile ARNs

---

aws/data_source_aws_vpc_test.go

Closes #17707
Ideally the basic test would be split up per argument and the IPv6 test doesn't need any randomness, but this just addresses more immediate issues.
Output from acceptance testing in AWS Commercial:
```
--- PASS: TestAccDataSourceAwsVpc_basic (26.00s)
--- PASS: TestAccDataSourceAwsVpc_ipv6Associated (26.25s)
--- PASS: …
```

data-source/aws_vpc: Quick fixes to prevent inconsistent failures

---

website/docs/r/elasticache_global_replication_group.html.markdown

Reference: https://github.com/hashicorp/terraform-provider-aws/issues/17768

docs/resource/aws_elasticache_global_replication_group: Add link to AWS documentation

---

docs/contributing/running-and-writing-acceptance-tests.md

Change `Hardcoded Versions` -> `Hardcoded Database Versions`.
Fixes link.
```
n/a
```

Correct heading in running-and-writing-acceptance-tests.md

---

.changelog/17872.txt
aws/resource_aws_neptune_cluster_parameter_group.go
aws/resource_aws_neptune_cluster_parameter_group_test.go

Closes #17870 
```
--- PASS: TestAccAWSNeptuneClusterParameterGroup_namePrefix (16.91s)
--- PASS: TestAccAWSNeptuneClusterParameterGroup_basic (16.91s)
--- PASS: TestAccAWSNeptuneClusterParameterGroup_Description (16.93s)
--- PASS: TestAccAWSNeptuneClusterParameterGroup_generatedName (16.94s)
--- PASS: …
```

r/neptune_cluster_parameter_group: update parameter field modification on create/update

---

docs/contributing/data-handling-and-conversion.md

Ensure that copypasta code will compile.
```
n/a
```

Correct handling of timestamps in Data Handling and Conversion guide

---

.github/workflows/firewatch.yml

Enables slack integration now the we have been dry-running for a while.

workflow/firewatch - Enable slack

---

aws/resource_aws_lb_listener_test.go

Relates #17920
```
--- FAIL: TestAccAWSLBListener_LoadBalancerArn_GatewayLoadBalancer (18.61s) (GovCloud limitations needing ErrorCheck)
--- PASS: TestAccAWSLBListener_DefaultAction_Order (181.10s)
--- PASS: TestAccAWSLBListener_BackwardsCompatibility (182.30s)
--- PASS: TestAccAWSLBListener_basic (183.07s)
--- …
```

tests/lblistener: Remove deprecated type constraints

---

website/docs/d/ami.html.markdown
website/docs/r/instance.html.markdown

Reference: https://github.com/hashicorp/terraform-provider-aws/issues/15365
Closes #17903

docs/service/ec2: Clarifications for aws_ami data source and aws_instance resource types

---

aws/resource_aws_dx_connection_test.go
aws/resource_aws_dx_lag_test.go

Closes #17391
The acceptance testing can leave lingering resources on failed runs (e.g. via coding issues during development or panics). These lingering resources can cause quota limits to be reached, extraneous money to be spent, or in some worst cases leave open security risks in the testing account.
We do not require sweeper implementation during initial …

tests/service/directconnect: Implement aws_dx_connection and aws_dx_lag sweepers

---

website/docs/r/instance.html.markdown

Reference: https://github.com/hashicorp/terraform-provider-aws/issues/17856

docs/resource/aws_instance: Clarify credit_specification configuration block behaviors

---

.github/workflows/firewatch.yml
.github/workflows/team_slack_bot.yml

These actions have no value being run in a fork, so disable them.

Don't run slack related actions in forks

---

.github/workflows/changelog.yml
.github/workflows/dependencies.yml
.github/workflows/issues.yml
.github/workflows/pull_requests.yml

Output from acceptance testing: N/A (CI)

workflows: Ensure bill-rich gets maintainer treatment in conditionals

---

.changelog/17982.txt
aws/resource_aws_rds_cluster_instance.go

Add `configuring-iam-database-auth` pending state

---

website/docs/r/apigatewayv2_integration.html.markdown

The usage for request_parameters and response_parameters were not easy to
understand.
Add examples of how to use them in one of the implementation examples.

aws_apigatewayv2_integration request and response parameters examples

---

website/docs/r/cloudwatch_metric_alarm.html.markdown

update aws_cloudwatch_metric_alarm doc

---

website/docs/r/acm_certificate.html.markdown
website/docs/r/cognito_user_pool_client.markdown
website/docs/r/cognito_user_pool_ui_customization.html.markdown
website/docs/r/config_conformance_pack.html.markdown
website/docs/r/devicefarm_project.html.markdown
website/docs/r/emr_instance_fleet.html.markdown
website/docs/r/fms_policy.html.markdown
website/docs/r/glue_dev_endpoint.markdown
website/docs/r/iam_user_group_membership.html.markdown
website/docs/r/lightsail_domain.html.markdown
website/docs/r/lightsail_key_pair.html.markdown
website/docs/r/load_balancer_listener_policy.html.markdown
website/docs/r/networkfirewall_resource_policy.html.markdown
website/docs/r/secretsmanager_secret_policy.html.markdown
website/docs/r/securityhub_invite_accepter.markdown
website/docs/r/ssm_maintenance_window_target.html.markdown
website/docs/r/transfer_server.html.markdown
website/docs/r/transfer_ssh_key.html.markdown
website/docs/r/transfer_user.html.markdown
website/docs/r/vpc_peering_connection_options.html.markdown
website/docs/r/wafregional_web_acl_association.html.markdown
website/docs/r/workspaces_directory.html.markdown

Reference: https://github.com/hashicorp/terraform-provider-aws/issues/15842
This targets header issues except "missing attribute section" across the provider, which will be submitted separately to reduce review burden.
Previously:
```
* website/docs/r/acm_certificate.html.markdown: error checking file contents: import section heading level (3) should be: 2
* …
```

docs/provider: Fix various header issues

---

website/docs/r/db_event_subscription.html.markdown
website/docs/r/directory_service_conditional_forwarder.html.markdown
website/docs/r/directory_service_log_subscription.html.markdown
website/docs/r/dms_event_subscription.html.markdown
website/docs/r/dx_connection_association.html.markdown
website/docs/r/ebs_default_kms_key.html.markdown
website/docs/r/ebs_encryption_by_default.html.markdown
website/docs/r/ec2_client_vpn_authorization_rule.html.markdown
website/docs/r/elasticsearch_domain_policy.html.markdown
website/docs/r/elastictranscoder_preset.html.markdown
website/docs/r/elb_attachment.html.markdown
website/docs/r/emr_managed_scaling_policy.html.markdown
website/docs/r/glue_resource_policy.html.markdown
website/docs/r/iam_account_alias.html.markdown
website/docs/r/iam_group_policy_attachment.markdown
website/docs/r/iam_instance_profile.html.markdown
website/docs/r/iam_role.html.markdown
website/docs/r/iam_role_policy_attachment.markdown
website/docs/r/iam_user_policy_attachment.markdown
website/docs/r/iot_policy_attachment.html.markdown
website/docs/r/iot_thing_principal_attachment.html.markdown

Reference: https://github.com/hashicorp/terraform-provider-aws/issues/15842
Previously:
```
* website/docs/r/db_event_subscription.html.markdown: error checking file contents: attributes section heading (Attributes) should be: Attributes Reference
* website/docs/r/directory_service_conditional_forwarder.html.markdown: error checking file contents: missing …
```

docs/provider: Attribute headers and byline fixes (D-I resources)

---

website/docs/r/lakeformation_data_lake_settings.html.markdown
website/docs/r/lakeformation_permissions.html.markdown
website/docs/r/lambda_code_signing_config.html.markdown
website/docs/r/lambda_function.html.markdown
website/docs/r/lambda_permission.html.markdown
website/docs/r/media_store_container_policy.html.markdown
website/docs/r/neptune_event_subscription.html.markdown
website/docs/r/network_interface_sg_attachment.html.markdown
website/docs/r/networkfirewall_resource_policy.html.markdown
website/docs/r/organizations_policy_attachment.html.markdown
website/docs/r/pinpoint_adm_channel.markdown
website/docs/r/pinpoint_apns_channel.markdown
website/docs/r/pinpoint_apns_sandbox_channel.markdown
website/docs/r/pinpoint_apns_voip_channel.markdown
website/docs/r/pinpoint_apns_voip_sandbox_channel.markdown
website/docs/r/quicksight_user.html.markdown
website/docs/r/redshift_event_subscription.html.markdown
website/docs/r/redshift_snapshot_schedule.html.markdown
website/docs/r/redshift_snapshot_schedule_association.html.markdown

Reference: https://github.com/hashicorp/terraform-provider-aws/issues/15842
Previously:
```
* website/docs/r/lakeformation_data_lake_settings.html.markdown: error checking file contents: attributes section byline (In addition to all arguments above, no attributes are exported.) should be: "In addition to all arguments above, the following attributes are …
```

docs/provider: Attribute headers and byline fixes (L-R resources)

---

website/docs/r/globalaccelerator_endpoint_group.html.markdown
website/docs/r/globalaccelerator_listener.markdown

Add 'Timeouts' heading for Global Accelerator resource timeout documentation

---

website/docs/r/vpc_peering_connection.html.markdown

Fix some broken Markdown related to links

docs/resource/vpc_peering_connection: Fix markdown

---

aws/data_source_aws_ami_ids_test.go
aws/data_source_aws_ami_test.go
aws/data_source_aws_availability_zone_test.go
aws/data_source_aws_availability_zones_test.go
aws/data_source_aws_customer_gateway_test.go
aws/data_source_aws_ebs_default_kms_key_test.go
aws/data_source_aws_ebs_encryption_by_default_test.go
aws/data_source_aws_ebs_snapshot_ids_test.go
aws/data_source_aws_ebs_snapshot_test.go
aws/data_source_aws_ebs_volume_test.go
aws/data_source_aws_ebs_volumes_test.go

tests/ec2: Add ErrorCheck (Data Source Part 1)

---

aws/data_source_aws_eip_test.go
aws/data_source_aws_instance_test.go
aws/data_source_aws_instances_test.go
aws/data_source_aws_internet_gateway_test.go
aws/data_source_aws_launch_template_test.go
aws/data_source_aws_nat_gateway_test.go
aws/data_source_aws_network_acls_test.go
aws/data_source_aws_network_interface_test.go
aws/data_source_aws_network_interfaces_test.go
aws/data_source_aws_prefix_list_test.go

tests/ec2: Add ErrorCheck (DataSource Part 4)

---

aws/data_source_aws_region_test.go
aws/data_source_aws_regions_test.go
aws/data_source_aws_route_table_test.go
aws/data_source_aws_route_tables_test.go
aws/data_source_aws_route_test.go
aws/data_source_aws_security_group_test.go
aws/data_source_aws_security_groups_test.go
aws/data_source_aws_subnet_ids_test.go
aws/data_source_aws_subnet_test.go
aws/data_source_aws_vpc_dhcp_options_test.go

tests/ec2: Add ErrorCheck (Data Source Part 5)

---

aws/resource_aws_ami_copy_test.go
aws/resource_aws_ami_from_instance_test.go
aws/resource_aws_ami_launch_permission_test.go
aws/resource_aws_ami_test.go
aws/resource_aws_customer_gateway_test.go
aws/resource_aws_default_network_acl_test.go
aws/resource_aws_default_route_table_test.go
aws/resource_aws_default_security_group_test.go
aws/resource_aws_default_subnet_test.go
aws/resource_aws_default_vpc_dhcp_options_test.go

tests/ec2: Add ErrorCheck (Resources Part 1)

---

aws/resource_aws_ec2_client_vpn_route_test.go
aws/resource_aws_ec2_fleet_test.go
aws/resource_aws_ec2_local_gateway_route_table_vpc_association_test.go
aws/resource_aws_ec2_local_gateway_route_test.go
aws/resource_aws_ec2_managed_prefix_list_test.go
aws/resource_aws_ec2_traffic_mirror_filter_rule_test.go
aws/resource_aws_ec2_traffic_mirror_filter_test.go
aws/resource_aws_ec2_traffic_mirror_session_test.go
aws/resource_aws_ec2_traffic_mirror_target_test.go
aws/resource_aws_ec2_transit_gateway_peering_attachment_test.go

tests/ec2: Add ErrorCheck (Resource Part 3)

---

aws/resource_aws_ec2_transit_gateway_peering_attachment_accepter_test.go
aws/resource_aws_ec2_transit_gateway_prefix_list_reference_test.go
aws/resource_aws_ec2_transit_gateway_route_table_association_test.go
aws/resource_aws_ec2_transit_gateway_route_table_propagation_test.go
aws/resource_aws_ec2_transit_gateway_route_table_test.go
aws/resource_aws_ec2_transit_gateway_route_test.go
aws/resource_aws_ec2_transit_gateway_test.go
aws/resource_aws_ec2_transit_gateway_vpc_attachment_accepter_test.go
aws/resource_aws_ec2_transit_gateway_vpc_attachment_test.go
aws/resource_aws_efs_mount_target_test.go

tests/ec2: Add ErrorCheck (Resources Part 4)

---

aws/data_source_aws_db_cluster_snapshot_test.go
aws/data_source_aws_db_event_categories_test.go
aws/data_source_aws_db_instance_test.go
aws/data_source_aws_db_snapshot_test.go
aws/data_source_aws_db_subnet_group_test.go
aws/data_source_aws_rds_certificate_test.go
aws/data_source_aws_rds_cluster_test.go
aws/data_source_aws_rds_engine_version_test.go
aws/data_source_aws_rds_orderable_db_instance_test.go

tests/data-source/rds: Add ErrorCheck

---

aws/resource_aws_network_acl_test.go
aws/resource_aws_network_interface_sg_attachment_test.go
aws/resource_aws_network_interface_test.go
aws/resource_aws_placement_group_test.go
aws/resource_aws_route_table_association_test.go
aws/resource_aws_route_table_test.go
aws/resource_aws_route_test.go
aws/resource_aws_security_group_rule_test.go
aws/resource_aws_security_group_test.go
aws/resource_aws_snapshot_create_volume_permission_test.go

tests/ec2: Add ErrorCheck (Resources Part 6)

---

aws/resource_aws_spot_datafeed_subscription_test.go
aws/resource_aws_spot_fleet_request_test.go
aws/resource_aws_spot_instance_request_test.go
aws/resource_aws_subnet_test.go
aws/resource_aws_volume_attachment_test.go
aws/resource_aws_vpc_dhcp_options_association_test.go
aws/resource_aws_vpc_dhcp_options_test.go
aws/resource_aws_vpc_endpoint_route_table_association_test.go
aws/resource_aws_vpc_endpoint_service_allowed_principal_test.go
aws/resource_aws_vpc_endpoint_service_test.go

tests/ec2: Add ErrorCheck (Resources Part 7)

---

aws/resource_aws_vpc_endpoint_subnet_association_test.go
aws/resource_aws_vpc_endpoint_test.go
aws/resource_aws_vpc_ipv4_cidr_block_association_test.go
aws/resource_aws_vpc_peering_connection_accepter_test.go
aws/resource_aws_vpc_peering_connection_options_test.go
aws/resource_aws_vpc_peering_connection_test.go
aws/resource_aws_vpc_test.go
aws/resource_aws_vpn_connection_route_test.go
aws/resource_aws_vpn_connection_test.go
aws/resource_aws_vpn_gateway_attachment_test.go

tests/ec2: Add ErrorCheck (Resources Part 8)

---

aws/resource_aws_vpn_gateway_test.go

tests/ec2: Add ErrorCheck (Resources Part 9)

---

aws/resource_aws_db_cluster_snapshot_test.go
aws/resource_aws_db_event_subscription_test.go
aws/resource_aws_db_instance_role_association_test.go
aws/resource_aws_db_instance_test.go
aws/resource_aws_db_option_group_test.go
aws/resource_aws_db_parameter_group_test.go
aws/resource_aws_db_proxy_default_target_group_test.go
aws/resource_aws_db_proxy_target_test.go
aws/resource_aws_db_proxy_test.go
aws/resource_aws_db_security_group_test.go

tests/rds: Add ErrorCheck (Resources Part 1)

---

aws/resource_aws_db_snapshot_test.go
aws/resource_aws_db_subnet_group_test.go
aws/resource_aws_rds_cluster_endpoint_test.go
aws/resource_aws_rds_cluster_instance_test.go
aws/resource_aws_rds_cluster_parameter_group_test.go
aws/resource_aws_rds_cluster_test.go
aws/resource_aws_rds_global_cluster_test.go

tests/rds: Add ErrorCheck (Resources Part 2)

---

aws/data_source_aws_apigatewayv2_apis_test.go
aws/resource_aws_apigatewayv2_api_test.go
aws/resource_aws_apigatewayv2_authorizer_test.go
aws/resource_aws_apigatewayv2_deployment_test.go
aws/resource_aws_apigatewayv2_domain_name_test.go
aws/resource_aws_apigatewayv2_integration_response_test.go
aws/resource_aws_apigatewayv2_integration_test.go
aws/resource_aws_apigatewayv2_model_test.go
aws/resource_aws_apigatewayv2_route_response_test.go
aws/resource_aws_apigatewayv2_route_test.go
aws/resource_aws_apigatewayv2_stage_test.go
aws/resource_aws_apigatewayv2_vpc_link_test.go

tests/apigatewayv2: Add ErrorCheck

---

.github/workflows/terraform_provider.yml
.goreleaser.yml

ci/goreleaser: Look for more performance

---

aws/resource_aws_sagemaker_app_image_config_test.go
aws/resource_aws_sagemaker_app_test.go
aws/resource_aws_sagemaker_code_repository_test.go
aws/resource_aws_sagemaker_domain_test.go
aws/resource_aws_sagemaker_endpoint_configuration_test.go
aws/resource_aws_sagemaker_endpoint_test.go
aws/resource_aws_sagemaker_feature_group_test.go
aws/resource_aws_sagemaker_image_test.go
aws/resource_aws_sagemaker_image_version_test.go
aws/resource_aws_sagemaker_model_package_group_test.go
aws/resource_aws_sagemaker_model_test.go
aws/resource_aws_sagemaker_notebook_instance_lifecycle_configuration_test.go
aws/resource_aws_sagemaker_notebook_instance_test.go
aws/resource_aws_sagemaker_user_profile_test.go

tests/sagemaker: Add ErrorCheck

---

aws/data_source_aws_canonical_user_id_test.go
aws/data_source_aws_s3_bucket_object_test.go
aws/data_source_aws_s3_bucket_objects_test.go
aws/data_source_aws_s3_bucket_test.go
aws/resource_aws_s3_bucket_analytics_configuration_test.go
aws/resource_aws_s3_bucket_inventory_test.go
aws/resource_aws_s3_bucket_metric_test.go
aws/resource_aws_s3_bucket_notification_test.go
aws/resource_aws_s3_bucket_object_test.go
aws/resource_aws_s3_bucket_ownership_controls_test.go
aws/resource_aws_s3_bucket_policy_test.go
aws/resource_aws_s3_bucket_public_access_block_test.go
aws/resource_aws_s3_bucket_test.go
aws/resource_aws_s3_object_copy_test.go

tests/s3: Add ErrorCheck

---

aws/resource_aws_glue_ml_transform_test.go
aws/resource_aws_glue_partition_test.go
aws/resource_aws_glue_registry_test.go
aws/resource_aws_glue_resource_policy_test.go
aws/resource_aws_glue_schema_test.go
aws/resource_aws_glue_security_configuration_test.go
aws/resource_aws_glue_trigger_test.go
aws/resource_aws_glue_user_defined_function_test.go
aws/resource_aws_glue_workflow_test.go

tests/glue: Add ErrorCheck (Part 2)

---

aws/data_source_aws_glue_script_test.go
aws/resource_aws_glue_catalog_database_test.go
aws/resource_aws_glue_catalog_table_test.go
aws/resource_aws_glue_classifier_test.go
aws/resource_aws_glue_connection_test.go
aws/resource_aws_glue_crawler_test.go
aws/resource_aws_glue_data_catalog_encryption_settings_test.go
aws/resource_aws_glue_dev_endpoint_test.go
aws/resource_aws_glue_job_test.go

tests/glue: Add ErrorCheck (Part 1)

---

aws/data_source_aws_dx_gateway_test.go
aws/resource_aws_dx_bgp_peer_test.go
aws/resource_aws_dx_connection_association_test.go
aws/resource_aws_dx_connection_test.go
aws/resource_aws_dx_gateway_association_proposal_test.go
aws/resource_aws_dx_gateway_association_test.go
aws/resource_aws_dx_gateway_test.go

tests/dx: Add ErrorCheck (Part 1)

---

aws/resource_aws_iam_group_policy_attachment_test.go
aws/resource_aws_iam_group_policy_test.go
aws/resource_aws_iam_group_test.go
aws/resource_aws_iam_instance_profile_test.go
aws/resource_aws_iam_openid_connect_provider_test.go
aws/resource_aws_iam_policy_attachment_test.go
aws/resource_aws_iam_policy_test.go
aws/resource_aws_iam_role_policy_attachment_test.go
aws/resource_aws_iam_role_policy_test.go
aws/resource_aws_iam_role_test.go

tests/iam: Add ErrorCheck (Part 2)

---

aws/data_source_aws_iam_group_test.go
aws/data_source_aws_iam_instance_profile_test.go
aws/data_source_aws_iam_role_test.go
aws/data_source_aws_iam_server_certificate_test.go
aws/data_source_aws_iam_user_test.go
aws/resource_aws_iam_access_key_test.go
aws/resource_aws_iam_account_alias_test.go
aws/resource_aws_iam_account_password_policy_test.go
aws/resource_aws_iam_group_membership_test.go

tests/iam: Add ErrorCheck (Part 1)

---

aws/data_source_aws_api_gateway_api_key_test.go
aws/data_source_aws_api_gateway_domain_name_test.go
aws/data_source_aws_api_gateway_resource_test.go
aws/data_source_aws_api_gateway_rest_api_test.go
aws/data_source_aws_api_gateway_vpc_link_test.go
aws/resource_aws_api_gateway_rest_api_policy_test.go
aws/resource_aws_api_gateway_stage_test.go
aws/resource_aws_api_gateway_usage_plan_key_test.go
aws/resource_aws_api_gateway_usage_plan_test.go
aws/resource_aws_api_gateway_vpc_link_test.go

tests/apigateway: Add ErrorCheck (Part 3)

---

aws/resource_aws_api_gateway_integration_response_test.go
aws/resource_aws_api_gateway_integration_test.go
aws/resource_aws_api_gateway_method_response_test.go
aws/resource_aws_api_gateway_method_settings_test.go
aws/resource_aws_api_gateway_method_test.go
aws/resource_aws_api_gateway_model_test.go
aws/resource_aws_api_gateway_request_validator_test.go
aws/resource_aws_api_gateway_resource_test.go
aws/resource_aws_api_gateway_rest_api_policy_test.go
aws/resource_aws_api_gateway_rest_api_test.go

tests/apigateway: Add ErrorCheck (Part 2)

---

aws/resource_aws_api_gateway_account_test.go
aws/resource_aws_api_gateway_api_key_test.go
aws/resource_aws_api_gateway_authorizer_test.go
aws/resource_aws_api_gateway_base_path_mapping_test.go
aws/resource_aws_api_gateway_client_certificate_test.go
aws/resource_aws_api_gateway_deployment_test.go
aws/resource_aws_api_gateway_documentation_part_test.go
aws/resource_aws_api_gateway_documentation_version_test.go
aws/resource_aws_api_gateway_domain_name_test.go
aws/resource_aws_api_gateway_gateway_response_test.go

tests/apigateway: Add ErrorCheck (Part 1)

---

aws/data_source_aws_waf_ipset_test.go
aws/data_source_aws_waf_rate_based_rule_test.go
aws/data_source_aws_waf_rule_test.go
aws/data_source_aws_waf_web_acl_test.go
aws/resource_aws_waf_web_acl_test.go
aws/resource_aws_waf_xss_match_set_test.go

tests/waf: Add Error Check (Part 2)

---

aws/resource_aws_waf_byte_match_set_test.go
aws/resource_aws_waf_geo_match_set_test.go
aws/resource_aws_waf_ipset_test.go
aws/resource_aws_waf_rate_based_rule_test.go
aws/resource_aws_waf_regex_match_set_test.go
aws/resource_aws_waf_regex_pattern_set_test.go
aws/resource_aws_waf_rule_group_test.go
aws/resource_aws_waf_rule_test.go
aws/resource_aws_waf_size_constraint_set_test.go
aws/resource_aws_waf_sql_injection_match_set_test.go

tests/waf: Add ErrorCheck (Part 1)

---

aws/data_source_aws_backup_plan_test.go
aws/data_source_aws_backup_selection_test.go
aws/data_source_aws_backup_vault_test.go
aws/resource_aws_backup_global_settings_test.go
aws/resource_aws_backup_plan_test.go
aws/resource_aws_backup_region_settings_test.go
aws/resource_aws_backup_selection_test.go
aws/resource_aws_backup_vault_notifications_test.go
aws/resource_aws_backup_vault_policy_test.go
aws/resource_aws_backup_vault_test.go

tests/backup: Add ErrorCheck

---

aws/resource_aws_pinpoint_adm_channel_test.go
aws/resource_aws_pinpoint_apns_channel_test.go
aws/resource_aws_pinpoint_apns_sandbox_channel_test.go
aws/resource_aws_pinpoint_apns_voip_channel_test.go
aws/resource_aws_pinpoint_apns_voip_sandbox_channel_test.go
aws/resource_aws_pinpoint_app_test.go
aws/resource_aws_pinpoint_baidu_channel_test.go
aws/resource_aws_pinpoint_email_channel_test.go
aws/resource_aws_pinpoint_event_stream_test.go
aws/resource_aws_pinpoint_gcm_channel_test.go
aws/resource_aws_pinpoint_sms_channel_test.go

tests/pinpoint: Add ErrorCheck

---

aws/data_source_aws_imagebuilder_component_test.go
aws/data_source_aws_imagebuilder_distribution_configuration_test.go
aws/data_source_aws_imagebuilder_image_pipeline_test.go
aws/data_source_aws_imagebuilder_image_recipe_test.go
aws/data_source_aws_imagebuilder_image_test.go
aws/data_source_aws_imagebuilder_infrastructure_configuration_test.go
aws/resource_aws_imagebuilder_component_test.go
aws/resource_aws_imagebuilder_distribution_configuration_test.go
aws/resource_aws_imagebuilder_image_pipeline_test.go
aws/resource_aws_imagebuilder_image_recipe_test.go
aws/resource_aws_imagebuilder_image_test.go
aws/resource_aws_imagebuilder_infrastructure_configuration_test.go

tests/imagebuilder: Add ErrorCheck

---

aws/data_source_aws_elb_test.go
aws/resource_aws_app_cookie_stickiness_policy_test.go
aws/resource_aws_elb_test.go
aws/resource_aws_lb_cookie_stickiness_policy_test.go
aws/resource_aws_lb_ssl_negotiation_policy_test.go
aws/resource_aws_load_balancer_backend_server_policy_test.go
aws/resource_aws_load_balancer_listener_policy_test.go
aws/resource_aws_load_balancer_policy_test.go
aws/resource_aws_proxy_protocol_policy_test.go

tests/elb: Add ErrorCheck

---

aws/resource_aws_config_aggregate_authorization_test.go
aws/resource_aws_config_config_rule_test.go
aws/resource_aws_config_configuration_aggregator_test.go
aws/resource_aws_config_configuration_recorder_status_test.go
aws/resource_aws_config_configuration_recorder_test.go
aws/resource_aws_config_conformance_pack_test.go
aws/resource_aws_config_delivery_channel_test.go
aws/resource_aws_config_organization_custom_rule_test.go
aws/resource_aws_config_organization_managed_rule_test.go
aws/resource_aws_config_remediation_configuration_test.go

tests/configservice: Add ErrorCheck

---

aws/data_source_aws_wafregional_ipset_test.go
aws/data_source_aws_wafregional_rate_based_rule_test.go
aws/data_source_aws_wafregional_rule_test.go
aws/data_source_aws_wafregional_web_acl_test.go
aws/resource_aws_wafregional_byte_match_set_test.go
aws/resource_aws_wafregional_geo_match_set_test.go
aws/resource_aws_wafregional_ipset_test.go
aws/resource_aws_wafregional_rate_based_rule_test.go
aws/resource_aws_wafregional_regex_match_set_test.go
aws/resource_aws_wafregional_regex_pattern_set_test.go
aws/resource_aws_wafregional_rule_group_test.go
aws/resource_aws_wafregional_rule_test.go
aws/resource_aws_wafregional_size_constraint_set_test.go
aws/resource_aws_wafregional_sql_injection_match_set_test.go
aws/resource_aws_wafregional_web_acl_association_test.go
aws/resource_aws_wafregional_web_acl_test.go
aws/resource_aws_wafregional_xss_match_set_test.go

tests/wafregional: Add ErrorCheck

---

aws/data_source_aws_ssm_document_test.go
aws/data_source_aws_ssm_parameter_test.go
aws/data_source_aws_ssm_patch_baseline_test.go
aws/resource_aws_ssm_activation_test.go
aws/resource_aws_ssm_association_test.go
aws/resource_aws_ssm_document_test.go
aws/resource_aws_ssm_maintenance_window_target_test.go
aws/resource_aws_ssm_maintenance_window_task_test.go
aws/resource_aws_ssm_maintenance_window_test.go
aws/resource_aws_ssm_parameter_test.go
aws/resource_aws_ssm_patch_baseline_test.go
aws/resource_aws_ssm_patch_group_test.go
aws/resource_aws_ssm_resource_data_sync_test.go

tests/ssm: Add ErrorCheck

---

aws/data_source_aws_lambda_alias_test.go
aws/data_source_aws_lambda_code_signing_config_test.go
aws/data_source_aws_lambda_function_test.go
aws/data_source_aws_lambda_invocation_test.go
aws/data_source_aws_lambda_layer_version_test.go
aws/resource_aws_lambda_alias_test.go
aws/resource_aws_lambda_code_signing_config_test.go
aws/resource_aws_lambda_event_source_mapping_test.go
aws/resource_aws_lambda_function_event_invoke_config_test.go
aws/resource_aws_lambda_function_test.go
aws/resource_aws_lambda_layer_version_test.go
aws/resource_aws_lambda_permission_test.go
aws/resource_aws_lambda_provisioned_concurrency_config_test.go

tests/lambda: Add ErrorCheck

---

aws/data_source_aws_kms_alias_test.go
aws/data_source_aws_kms_ciphertext_test.go
aws/data_source_aws_kms_key_test.go
aws/data_source_aws_kms_secrets_test.go
aws/resource_aws_kms_alias_test.go
aws/resource_aws_kms_ciphertext_test.go
aws/resource_aws_kms_external_key_test.go
aws/resource_aws_kms_grant_test.go
aws/resource_aws_kms_key_test.go

tests/kms: Add ErrorCheck

---

aws/data_source_aws_redshift_cluster_test.go
aws/data_source_aws_redshift_orderable_cluster_test.go
aws/resource_aws_redshift_cluster_test.go
aws/resource_aws_redshift_event_subscription_test.go
aws/resource_aws_redshift_parameter_group_test.go
aws/resource_aws_redshift_security_group_test.go
aws/resource_aws_redshift_snapshot_copy_grant_test.go
aws/resource_aws_redshift_snapshot_schedule_association_test.go
aws/resource_aws_redshift_snapshot_schedule_test.go
aws/resource_aws_redshift_subnet_group_test.go

tests/redshift:Add ErrorCheck

---

aws/data_source_aws_storagegateway_local_disk_test.go
aws/resource_aws_storagegateway_cache_test.go
aws/resource_aws_storagegateway_cached_iscsi_volume_test.go
aws/resource_aws_storagegateway_gateway_test.go
aws/resource_aws_storagegateway_nfs_file_share_test.go
aws/resource_aws_storagegateway_smb_file_share_test.go
aws/resource_aws_storagegateway_stored_iscsi_volume_test.go
aws/resource_aws_storagegateway_tape_pool_test.go
aws/resource_aws_storagegateway_upload_buffer_test.go
aws/resource_aws_storagegateway_working_storage_test.go

tests:storagegateway: Add ErrorCheck

---

aws/data_source_aws_wafv2_ip_set_test.go
aws/data_source_aws_wafv2_regex_pattern_set_test.go
aws/data_source_aws_wafv2_rule_group_test.go
aws/data_source_aws_wafv2_web_acl_test.go
aws/resource_aws_wafv2_ip_set_test.go
aws/resource_aws_wafv2_regex_pattern_set_test.go
aws/resource_aws_wafv2_rule_group_test.go
aws/resource_aws_wafv2_web_acl_association_test.go
aws/resource_aws_wafv2_web_acl_logging_configuration_test.go
aws/resource_aws_wafv2_web_acl_test.go

tests/wafv2: Add ErrorCheck

---

aws/data_source_aws_ecs_cluster_test.go
aws/data_source_aws_ecs_container_definition_test.go
aws/data_source_aws_ecs_service_test.go
aws/data_source_aws_ecs_task_definition_test.go
aws/resource_aws_ecs_capacity_provider_test.go
aws/resource_aws_ecs_cluster_test.go
aws/resource_aws_ecs_service_test.go
aws/resource_aws_ecs_task_definition_test.go

tests/ecs: Add ErrorCheck

---

aws/data_source_aws_neptune_engine_version_test.go
aws/data_source_aws_neptune_orderable_db_instance_test.go
aws/resource_aws_neptune_cluster_instance_test.go
aws/resource_aws_neptune_cluster_parameter_group_test.go
aws/resource_aws_neptune_cluster_snapshot_test.go
aws/resource_aws_neptune_cluster_test.go
aws/resource_aws_neptune_event_subscription_test.go
aws/resource_aws_neptune_parameter_group_test.go
aws/resource_aws_neptune_subnet_group_test.go

tests/neptune: Add ErrorCheck

---

aws/data_source_aws_efs_access_point_test.go
aws/data_source_aws_efs_access_points_test.go
aws/data_source_aws_efs_file_system_test.go
aws/data_source_aws_efs_mount_target_test.go
aws/resource_aws_efs_access_point_test.go
aws/resource_aws_efs_file_system_policy_test.go
aws/resource_aws_efs_file_system_test.go

tests/efs: Add ErrorCheck

---

aws/data_source_aws_elasticache_replication_group_test.go
aws/resource_aws_elasticache_cluster_test.go
aws/resource_aws_elasticache_global_replication_group_test.go
aws/resource_aws_elasticache_parameter_group_test.go
aws/resource_aws_elasticache_replication_group_test.go
aws/resource_aws_elasticache_security_group_test.go
aws/resource_aws_elasticache_subnet_group_test.go

tests/elasticache: Add ErrorCheck

---

aws/data_source_aws_qldb_ledger_test.go
aws/resource_aws_qldb_ledger_test.go

tests/qldb: Add ErrorCheck

---

aws/resource_aws_athena_database_test.go
aws/resource_aws_athena_named_query_test.go
aws/resource_aws_athena_workgroup_test.go

tests/athena: Add ErrorCheck

---

aws/resource_aws_codebuild_project_test.go
aws/resource_aws_codebuild_report_group_test.go
aws/resource_aws_codebuild_source_credential_test.go
aws/resource_aws_codebuild_webhook_test.go

tests/codebuild: Add ErrorCheck

---

aws/resource_aws_ecrpublic_repository_test.go

tests/r/ecrpublic_repository: Add ErrorCheck

---

aws/resource_aws_devicefarm_project_test.go

tests/r/devicefarm_project: Add ErrorCheck

---

aws/data_source_aws_cloudhsm2_cluster_test.go
aws/resource_aws_cloudhsm2_cluster_test.go
aws/resource_aws_cloudhsm2_hsm_test.go

tests/cloudhsmv2: Add ErrorCheck

---

aws/data_source_aws_signer_signing_job_test.go
aws/data_source_aws_signer_signing_profile_test.go
aws/resource_aws_signer_signing_job_test.go
aws/resource_aws_signer_signing_profile_permission_test.go
aws/resource_aws_signer_signing_profile_test.go

tests/signer: Add ErrorCheck

---

aws/data_source_aws_codecommit_repository_test.go
aws/resource_aws_codecommit_repository_test.go
aws/resource_aws_codecommit_trigger_test.go

tests/codecommit: Add ErrorCheck

---

aws/data_source_aws_kinesis_stream_consumer_test.go
aws/data_source_aws_kinesis_stream_test.go
aws/resource_aws_kinesis_analytics_application_test.go
aws/resource_aws_kinesis_stream_consumer_test.go
aws/resource_aws_kinesis_stream_test.go
aws/resource_aws_kinesis_video_stream_test.go
aws/resource_aws_kinesisanalyticsv2_application_test.go

tests/kinesis: Add ErrorCheck

---

aws/data_source_aws_identitystore_group_test.go
aws/data_source_aws_identitystore_user_test.go
aws/resource_aws_glacier_vault_lock_test.go
aws/resource_aws_glacier_vault_test.go
aws/resource_aws_globalaccelerator_accelerator_test.go
aws/resource_aws_globalaccelerator_endpoint_group_test.go
aws/resource_aws_globalaccelerator_listener_test.go

tests/STRAGGLERS: Add ErrorCheck (Part 2)

---

aws/data_source_aws_elasticsearch_domain_test.go
aws/resource_aws_appautoscaling_policy_test.go
aws/resource_aws_appautoscaling_scheduled_action_test.go
aws/resource_aws_appautoscaling_target_test.go
aws/resource_aws_autoscalingplans_scaling_plan_test.go
aws/resource_aws_budgets_budget_test.go
aws/resource_aws_codestarconnections_connection_test.go
aws/resource_aws_codestarnotifications_notification_rule_test.go
aws/resource_aws_cognito_identity_pool_roles_attachment_test.go
aws/resource_aws_cognito_identity_pool_test.go
aws/resource_aws_cur_report_definition_test.go
aws/resource_aws_datapipeline_pipeline_test.go
aws/resource_aws_dlm_lifecycle_policy_test.go
aws/resource_aws_elastic_transcoder_pipeline_test.go
aws/resource_aws_elastic_transcoder_preset_test.go
aws/resource_aws_elasticsearch_domain_policy_test.go
aws/resource_aws_elasticsearch_domain_test.go
aws/resource_aws_fms_admin_account_test.go
aws/resource_aws_fms_policy_test.go
aws/resource_aws_fsx_lustre_file_system_test.go
aws/resource_aws_fsx_windows_file_system_test.go
aws/resource_aws_kinesis_firehose_delivery_stream_test.go

test/STRAGGLERS: Add ErrorCheck (Part 1)

---

aws/data_source_aws_eks_cluster_test.go
aws/resource_aws_eks_cluster_test.go
aws/resource_aws_eks_fargate_profile_test.go
aws/resource_aws_eks_node_group_test.go

tests/eks: Add ErrorCheck

---

aws/data_source_aws_directory_service_directory_test.go
aws/resource_aws_directory_service_conditional_forwarder_test.go
aws/resource_aws_directory_service_directory_test.go
aws/resource_aws_directory_service_log_subscription_test.go

tests/directoryservice: Add ErrorCheck

---

aws/resource_aws_cloudwatch_log_destination_policy_test.go
aws/resource_aws_cloudwatch_log_destination_test.go
aws/resource_aws_cloudwatch_log_group_test.go
aws/resource_aws_cloudwatch_log_metric_filter_test.go
aws/resource_aws_cloudwatch_log_resource_policy_test.go
aws/resource_aws_cloudwatch_log_stream_test.go
aws/resource_aws_cloudwatch_log_subscription_filter_test.go

tests/cloudwatchlogs: Add ErrorCheck

---

aws/resource_aws_dms_certificate_test.go
aws/resource_aws_dms_endpoint_test.go
aws/resource_aws_dms_event_subscription_test.go
aws/resource_aws_dms_replication_instance_test.go
aws/resource_aws_dms_replication_subnet_group_test.go
aws/resource_aws_dms_replication_task_test.go

tests/databasemigrationservice: Add ErrorCheck

---

aws/data_source_aws_elastic_beanstalk_application_test.go
aws/data_source_aws_elastic_beanstalk_solution_stack_test.go
aws/resource_aws_elastic_beanstalk_application_test.go
aws/resource_aws_elastic_beanstalk_application_version_test.go
aws/resource_aws_elastic_beanstalk_configuration_template_test.go
aws/resource_aws_elastic_beanstalk_environment_test.go

tests/elasticbeanstalk: Add ErrorCheck

---

aws/resource_aws_s3_access_point_test.go
aws/resource_aws_s3_account_public_access_block_test.go
aws/resource_aws_s3control_bucket_lifecycle_configuration_test.go
aws/resource_aws_s3control_bucket_policy_test.go
aws/resource_aws_s3control_bucket_test.go

tests/s3control: Add ErrorCheck

---

aws/data_source_aws_ram_resource_share_test.go
aws/resource_aws_ram_principal_association_test.go
aws/resource_aws_ram_resource_association_test.go
aws/resource_aws_ram_resource_share_accepter_test.go
aws/resource_aws_ram_resource_share_test.go

tests/ram: Add ErrorCheck

---

aws/resource_aws_networkfirewall_firewall_policy_test.go
aws/resource_aws_networkfirewall_firewall_test.go
aws/resource_aws_networkfirewall_logging_configuration_test.go
aws/resource_aws_networkfirewall_resource_policy_test.go
aws/resource_aws_networkfirewall_rule_group_test.go

tests/networkfirewall: Add ErrorCheck

---

aws/data_source_aws_inspector_rules_packages_test.go
aws/resource_aws_inspector_assessment_target_test.go
aws/resource_aws_inspector_assessment_template_test.go
aws/resource_aws_inspector_resource_group_test.go

tests/inspector: Add ErrorCheck

---

aws/resource_aws_gamelift_alias_test.go
aws/resource_aws_gamelift_build_test.go
aws/resource_aws_gamelift_fleet_test.go
aws/resource_aws_gamelift_game_session_queue_test.go

tests/gamelift: Add ErrorCheck

---

aws/resource_aws_dax_cluster_test.go
aws/resource_aws_dax_parameter_group_test.go
aws/resource_aws_dax_subnet_group_test.go

tests/dax: Add ErrorCheck

---

aws/resource_aws_media_convert_queue_test.go
aws/resource_aws_media_package_channel_test.go
aws/resource_aws_media_store_container_policy_test.go
aws/resource_aws_media_store_container_test.go

tests/media: Add ErrorCheck

---

aws/resource_aws_cloud9_environment_ec2_test.go

tests/r/cloud9_environment_ec2: Add ErrorCheck

---

aws/resource_aws_accessanalyzer_analyzer_test.go

tests/r/accessanalyzer_analyzer: Add ErrorCheck

---

aws/resource_aws_lightsail_domain_test.go
aws/resource_aws_lightsail_instance_test.go
aws/resource_aws_lightsail_key_pair_test.go
aws/resource_aws_lightsail_static_ip_attachment_test.go
aws/resource_aws_lightsail_static_ip_test.go

tests/lightsail: Add ErrorCheck

---

aws/data_source_aws_msk_cluster_test.go
aws/data_source_aws_msk_configuration_test.go
aws/resource_aws_msk_cluster_test.go
aws/resource_aws_msk_configuration_test.go
aws/resource_aws_msk_scram_secret_association_test.go

tests/kafka: Add ErrorCheck

---

aws/data_source_aws_acm_certificate_test.go
aws/resource_aws_acm_certificate_test.go
aws/resource_aws_acm_certificate_validation_test.go

tests/acm: Add ErrorCheck

---

aws/data_source_aws_dynamodb_table_test.go
aws/resource_aws_dynamodb_global_table_test.go
aws/resource_aws_dynamodb_table_item_test.go
aws/resource_aws_dynamodb_table_test.go

tests/dynamodb: Add ErrorCheck

---

aws/data_source_aws_acmpca_certificate_authority_test.go
aws/data_source_aws_acmpca_certificate_test.go
aws/resource_aws_acmpca_certificate_authority_certificate_test.go
aws/resource_aws_acmpca_certificate_authority_test.go
aws/resource_aws_acmpca_certificate_test.go

tests/acmpca: Add ErrorCheck

---

aws/data_source_aws_lakeformation_data_lake_settings_test.go
aws/data_source_aws_lakeformation_permissions_test.go
aws/data_source_aws_lakeformation_resource_test.go
aws/resource_aws_lakeformation_data_lake_settings_test.go
aws/resource_aws_lakeformation_permissions_test.go
aws/resource_aws_lakeformation_resource_test.go

tests/lakeformation: Add ErrorCheck

---

aws/data_source_aws_outposts_outpost_instance_type_test.go
aws/data_source_aws_outposts_outpost_instance_types_test.go
aws/data_source_aws_outposts_outpost_test.go
aws/data_source_aws_outposts_outposts_test.go
aws/data_source_aws_outposts_site_test.go
aws/data_source_aws_outposts_sites_test.go

tests/outposts: Add ErrorCheck

---

aws/data_source_aws_pricing_product_test.go
aws/data_source_aws_servicequotas_service_quota_test.go
aws/data_source_aws_servicequotas_service_test.go
aws/resource_aws_licensemanager_association_test.go
aws/resource_aws_licensemanager_license_configuration_test.go
aws/resource_aws_macie_member_account_association_test.go
aws/resource_aws_macie_s3_bucket_association_test.go
aws/resource_aws_prometheus_workspace_test.go
aws/resource_aws_quicksight_group_test.go
aws/resource_aws_quicksight_user_test.go
aws/resource_aws_resourcegroups_group_test.go
aws/resource_aws_servicecatalog_portfolio_test.go
aws/resource_aws_servicequotas_service_quota_test.go

tests/STRAGGLERS: Add ErrorCheck (Part 3)

---

aws/data_source_aws_cognito_user_pools_test.go
aws/resource_aws_cognito_identity_provider_test.go
aws/resource_aws_cognito_resource_server_test.go
aws/resource_aws_cognito_user_group_test.go
aws/resource_aws_cognito_user_pool_client_test.go
aws/resource_aws_cognito_user_pool_domain_test.go
aws/resource_aws_cognito_user_pool_test.go
aws/resource_aws_cognito_user_pool_ui_customization_test.go

tests/cognitoidentityprovider: Add ErrorCheck

---

aws/data_source_aws_route53_delegation_set_test.go
aws/data_source_aws_route53_resolver_endpoint_test.go
aws/data_source_aws_route53_resolver_rule_test.go
aws/data_source_aws_route53_resolver_rules_test.go
aws/data_source_aws_route53_zone_test.go
aws/resource_aws_route53_delegation_set_test.go
aws/resource_aws_route53_health_check_test.go
aws/resource_aws_route53_hosted_zone_dnssec_test.go
aws/resource_aws_route53_key_signing_key_test.go
aws/resource_aws_route53_query_log_test.go
aws/resource_aws_route53_resolver_dnssec_config_test.go
aws/resource_aws_route53_resolver_endpoint_test.go
aws/resource_aws_route53_resolver_query_log_config_association_test.go
aws/resource_aws_route53_resolver_query_log_config_test.go
aws/resource_aws_route53_resolver_rule_association_test.go
aws/resource_aws_route53_resolver_rule_test.go
aws/resource_aws_route53_vpc_association_authorization_test.go
aws/resource_aws_route53_zone_association_test.go
aws/resource_aws_route53_zone_test.go
aws/resource_aws_shield_protection_test.go

tests/route53resolver & route53: Refactor ErrorCheck

---

aws/data_source_aws_ecr_authorization_token_test.go
aws/data_source_aws_ecr_image_test.go
aws/data_source_aws_ecr_repository_test.go
aws/resource_aws_ecr_lifecycle_policy_test.go
aws/resource_aws_ecr_repository_policy_test.go
aws/resource_aws_ecr_repository_test.go

tests/ecr: Add ErrorCheck

---

aws/data_source_aws_codeartifact_authorization_token_test.go
aws/data_source_aws_codeartifact_repository_endpoint_test.go
aws/resource_aws_codeartifact_domain_permissions_policy_test.go
aws/resource_aws_codeartifact_domain_test.go
aws/resource_aws_codeartifact_repository_permissions_policy_test.go
aws/resource_aws_codeartifact_repository_test.go

tests/codeartifact: Add ErrorCheck

---

aws/data_source_aws_cloudformation_export_test.go
aws/data_source_aws_cloudformation_stack_test.go
aws/resource_aws_cloudformation_stack_set_instance_test.go
aws/resource_aws_cloudformation_stack_set_test.go
aws/resource_aws_cloudformation_stack_test.go

tests/cloudformation: Add ErrorCheck

---

aws/data_source_aws_workspaces_bundle_test.go
aws/data_source_aws_workspaces_directory_test.go
aws/data_source_aws_workspaces_image_test.go
aws/data_source_aws_workspaces_workspace_test.go
aws/resource_aws_workspaces_directory_test.go
aws/resource_aws_workspaces_ip_group_test.go
aws/resource_aws_workspaces_workspace_test.go

tests/workspaces: Add ErrorCheck

---

aws/data_source_aws_secretsmanager_secret_rotation_test.go
aws/data_source_aws_secretsmanager_secret_test.go
aws/data_source_aws_secretsmanager_secret_version_test.go
aws/resource_aws_secretsmanager_secret_policy_test.go
aws/resource_aws_secretsmanager_secret_rotation_test.go
aws/resource_aws_secretsmanager_secret_test.go
aws/resource_aws_secretsmanager_secret_version_test.go

tests/secretsmanager: Add ErrorCheck

---

aws/data_source_aws_sfn_activity_test.go
aws/data_source_aws_sfn_state_machine_test.go
aws/resource_aws_sfn_activity_test.go
aws/resource_aws_sfn_state_machine_test.go

tests/sfn: Add ErrorCheck

---

aws/data_source_aws_organizations_organization_test.go
aws/data_source_aws_organizations_organizational_units_test.go
aws/resource_aws_organizations_account_test.go
aws/resource_aws_organizations_organization_test.go
aws/resource_aws_organizations_organizational_unit_test.go
aws/resource_aws_organizations_policy_attachment_test.go
aws/resource_aws_organizations_policy_test.go

tests/organizations: Add ErrorCheck

---

aws/data_source_aws_ssoadmin_instances_test.go
aws/data_source_aws_ssoadmin_permission_set_test.go
aws/resource_aws_ssoadmin_account_assignment_test.go
aws/resource_aws_ssoadmin_managed_policy_attachment_test.go
aws/resource_aws_ssoadmin_permission_set_inline_policy_test.go
aws/resource_aws_ssoadmin_permission_set_test.go

tests/ssoadmin: Add ErrorCheck

---

aws/data_source_aws_sns_test.go
aws/resource_aws_sns_platform_application_test.go
aws/resource_aws_sns_sms_preferences_test.go
aws/resource_aws_sns_topic_policy_test.go
aws/resource_aws_sns_topic_subscription_test.go
aws/resource_aws_sns_topic_test.go

tests/sns: Add ErrorCheck

---

aws/data_source_aws_docdb_engine_version_test.go
aws/data_source_aws_docdb_orderable_db_instance_test.go
aws/resource_aws_docdb_cluster_instance_test.go
aws/resource_aws_docdb_cluster_parameter_group_test.go
aws/resource_aws_docdb_cluster_snapshot_test.go
aws/resource_aws_docdb_cluster_test.go
aws/resource_aws_docdb_subnet_group_test.go

tests/docdb: Add ErrorCheck

---

aws/data_source_aws_sqs_queue_test.go
aws/resource_aws_sqs_queue_policy_test.go
aws/resource_aws_sqs_queue_test.go

tests/sqs: Add ErrorCheck

---

aws/resource_aws_appmesh_gateway_route_test.go
aws/resource_aws_appmesh_mesh_test.go
aws/resource_aws_appmesh_route_test.go
aws/resource_aws_appmesh_virtual_gateway_test.go
aws/resource_aws_appmesh_virtual_node_test.go
aws/resource_aws_appmesh_virtual_router_test.go
aws/resource_aws_appmesh_virtual_service_test.go

tests/appmesh: Add ErrorCheck

---

aws/resource_aws_securityhub_account_test.go
aws/resource_aws_securityhub_action_target_test.go
aws/resource_aws_securityhub_invite_accepter_test.go
aws/resource_aws_securityhub_member_test.go
aws/resource_aws_securityhub_organization_admin_account_test.go
aws/resource_aws_securityhub_product_subscription_test.go
aws/resource_aws_securityhub_standards_subscription_test.go

tests/securityhub: Add ErrorCheck

---

aws/data_source_aws_caller_identity_test.go
aws/data_source_aws_serverlessapplicationrepository_application_test.go
aws/resource_aws_s3outposts_endpoint_test.go
aws/resource_aws_serverlessapplicationrepository_cloudformation_stack_test.go
aws/resource_aws_shield_protection_test.go
aws/resource_aws_simpledb_domain_test.go
aws/resource_aws_swf_domain_test.go
aws/resource_aws_synthetics_canary_test.go
aws/resource_aws_worklink_fleet_test.go
aws/resource_aws_worklink_website_certificate_authority_association_test.go
aws/resource_aws_xray_encryption_config_test.go
aws/resource_aws_xray_group_test.go
aws/resource_aws_xray_sampling_rule_test.go

tests/STRAGGLERS: Add ErrorCheck (Part IV - The semi-lastish one??)

---

aws/core_acceptance_test.go
aws/data_source_aws_apigatewayv2_api_test.go
aws/data_source_aws_arn_test.go
aws/data_source_aws_billing_service_account_test.go
aws/data_source_aws_cloudfront_cache_policy_test.go
aws/data_source_aws_cloudfront_origin_request_policy_test.go
aws/data_source_aws_cloudtrail_service_account_test.go
aws/data_source_aws_cloudwatch_log_group_test.go
aws/data_source_aws_cur_report_definition_test.go
aws/data_source_aws_ec2_transit_gateway_route_tables_test.go
aws/data_source_aws_eks_cluster_auth_test.go
aws/data_source_aws_elastic_beanstalk_hosted_zone_test.go
aws/data_source_aws_elasticache_cluster_test.go
aws/data_source_aws_elb_hosted_zone_id_test.go
aws/data_source_aws_elb_service_account_test.go
aws/resource_aws_cloudfront_cache_policy_test.go
aws/resource_aws_cloudfront_distribution_test.go
aws/resource_aws_cloudfront_origin_access_identity_test.go
aws/resource_aws_cloudfront_origin_request_policy_test.go
aws/resource_aws_cloudfront_public_key_test.go
aws/resource_aws_cloudfront_realtime_log_config_test.go

tests: Add ErrorCheck (Phase 2)

---

aws/data_source_aws_iam_policy_document_test.go
aws/data_source_aws_iam_policy_test.go
aws/data_source_aws_ip_ranges_test.go
aws/data_source_aws_kms_secret_test.go
aws/data_source_aws_partition_test.go
aws/data_source_aws_redshift_service_account_test.go
aws/data_source_aws_sagemaker_prebuilt_ecr_image_test.go
aws/provider_test.go
aws/resource_aws_apigatewayv2_api_mapping_test.go
aws/resource_aws_cloudfront_cache_policy_test.go
aws/resource_aws_cloudfront_distribution_test.go
aws/resource_aws_cloudfront_origin_access_identity_test.go
aws/resource_aws_cloudfront_origin_request_policy_test.go
aws/resource_aws_cloudfront_public_key_test.go
aws/resource_aws_cloudfront_realtime_log_config_test.go
aws/resource_aws_customer_gateway_test.go
aws/resource_aws_db_parameter_group_test.go
aws/resource_aws_default_route_table_test.go
aws/resource_aws_default_security_group_test.go
aws/resource_aws_default_vpc_test.go
aws/resource_aws_ec2_carrier_gateway_test.go
aws/resource_aws_ec2_client_vpn_network_association_test.go
aws/resource_aws_ec2_tag_test.go
aws/resource_aws_egress_only_internet_gateway_test.go
aws/resource_aws_eip_test.go
aws/resource_aws_elb_attachment_test.go
aws/resource_aws_elb_test.go

tests: Add ErrorCheck (Phase II 2)

---

.github/workflows/terraform_provider.yml
tools/go.mod
tools/go.sum
website/docs/r/acmpca_certificate.html.markdown
website/docs/r/acmpca_certificate_authority_certificate.html.markdown
website/docs/r/cognito_identity_provider.html.markdown
website/docs/r/config_conformance_pack.html.markdown
website/docs/r/iam_user_group_membership.html.markdown
website/docs/r/networkfirewall_resource_policy.html.markdown
website/docs/r/pinpoint_baidu_channel.markdown
website/docs/r/pinpoint_event_stream.markdown
website/docs/r/pinpoint_gcm_channel.markdown
website/docs/r/securityhub_invite_accepter.markdown
website/docs/r/ses_identity_notification_topic.markdown
website/docs/r/transfer_ssh_key.html.markdown

Closes #15842
Fixes remaining reports and enables the additional checking. The tooling also supports flags for requiring alphabetical list sorting, but that can be enabled in the future.
Previously:
```
Error checking Terraform Provider documentation: 12 errors occurred:
* website/docs/r/acmpca_certificate.html.markdown: error checking file contents: …
```

provider: Enable tfproviderdocs enhanced contents checking

---

GNUmakefile
aws/resource_aws_dms_replication_instance_test.go

Closes #18175 
Output from acceptance testing: N/A (Handled by daily build)

tests: Enable XAT001, last fix

---

aws/resource_aws_cloudfront_distribution_test.go

```
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSCloudFrontDistribution_forwardedValuesToCachePolicy -timeout 180m
=== RUN   TestAccAWSCloudFrontDistribution_forwardedValuesToCachePolicy
=== PAUSE …
```

Add missing parameter and ErrorCheck on test

---

docs/contributing/retries-and-waiters.md

Reference: https://github.com/hashicorp/terraform-provider-aws/pull/18404

docs/contributing: Add Asynchronous Operation Error Retries section to Retries and Waiters page

---

website/docs/r/dx_gateway_association.html.markdown
website/docs/r/dx_gateway_association_proposal.html.markdown
website/docs/r/ec2_transit_gateway_peering_attachment.html.markdown
website/docs/r/ec2_transit_gateway_peering_attachment_accepter.markdown
website/docs/r/ec2_transit_gateway_vpc_attachment.html.markdown
website/docs/r/ec2_transit_gateway_vpc_attachment_accepter.html.markdown

Point code example links at current default branch

---

website/docs/r/ecrpublic_repository.html.markdown

Fix typo in ECR public repository docs

---

docs/contributing/running-and-writing-acceptance-tests.md

Relates #15336
Relates #15359
Relates #15334
Output from acceptance testing: N/A (documentation only)

docs/acctests: Include concurrent sweeper examples

---

.github/CODEOWNERS

I added myself to the CODEOWNERS. Thank you!

Add shuheiktgw to CODEOWNERS

---

aws/data_source_aws_iam_account_alias_test.go
aws/resource_aws_iam_account_alias_test.go

Closes #18617
```
--- PASS: TestAccAWSIAMAccountAlias_serial (24.54s)
--- PASS: TestAccAWSIAMAccountAlias_serial/DataSource (13.72s)
--- PASS: TestAccAWSIAMAccountAlias_serial/DataSource/basic (13.72s)
--- PASS: TestAccAWSIAMAccountAlias_serial/Resource (10.82s)
--- PASS: TestAccAWSIAMAccountAlias_serial/Resource/basic …
```

tests/service/iam: Refactor and fix IAM Account Alias testing

---

.hashibot.hcl

Reference: https://github.com/hashicorp/terraform-provider-aws/pull/18621
Output from acceptance testing: N/A (hashibot configuration)

workflows: Ensure aws_cloudwatch_query_definition resource has issues and pull requests labeled as service/cloudwatchlogs

---

aws/resource_aws_placement_group_test.go

Closes #16413
Output from sweeper in AWS Commercial:
```
2021/04/07 13:40:10 [DEBUG] Running Sweepers for region (us-west-2):
2021/04/07 13:40:10 [DEBUG] Running Sweeper (aws_placement_group) in region (us-west-2)
2021/04/07 13:40:11 [DEBUG] Deleting EC2 Placement Group "asg_pg_terraform-test-njfdgjdke4"
2021/04/07 13:40:11 [DEBUG] Deleting EC2 Placement …
```

tests/resource/aws_placement_group: Implement sweeper

---

aws/resource_aws_ssm_resource_data_sync_test.go

Closes #18100
Output from sweeper in AWS Commercial:
```
$ aws ssm list-resource-data-sync | jq '.ResourceDataSyncItems | length'
4
2021/04/07 13:12:09 [DEBUG] Running Sweepers for region (us-west-2):
2021/04/07 13:12:09 [DEBUG] Running Sweeper (aws_ssm_resource_data_sync) in region (us-west-2)
2021/04/07 13:12:11 Sweeper Tests ran successfully:
- …
```

tests/resource/aws_ssm_resource_data_sync: Implement sweeper

---

website/docs/r/ecr_replication_configuration.html.markdown

docs: Incorrect reference in ecr_replication_configuration

---

.github/workflows/changelog.yml
.github/workflows/project.yml
docs/FAQ.md

Kit is joining the team! 🚀 

---

aws/data_source_aws_elb.go
aws/data_source_aws_elb_test.go

Relates #18819
Relates #16145
```
--- PASS: TestAccDataSourceAWSELB_basic (49.38s) // `us-west-2`
--- PASS: TestAccDataSourceAWSELB_basic (50.05s) // GovCloud
```

ds/elb: Unshare Read with Resource

---

website/docs/r/sns_topic_subscription.html.markdown

Fix typo, Retying -> Retrying

---

website/docs/r/autoscaling_group.html.markdown

docs: Add prioritized allocation strategy as valid value

---

.semgrep.yml
aws/resource_aws_service_discovery_public_dns_namespace_test.go
aws/resource_aws_service_discovery_service_test.go
aws/resource_aws_ses_domain_identity_test.go
aws/resource_aws_sns_platform_application_test.go
aws/resource_aws_sns_topic_test.go
aws/resource_aws_spot_fleet_request_test.go
aws/resource_aws_ssoadmin_account_assignment_test.go
aws/resource_aws_ssoadmin_permission_set_test.go
aws/resource_aws_storagegateway_gateway_test.go
docs/contributing/running-and-writing-acceptance-tests.md

Prefer lastPage for pagination, S

---

.semgrep.yml
aws/resource_aws_acm_certificate_test.go
aws/resource_aws_apigatewayv2_domain_name_test.go
aws/resource_aws_appmesh_gateway_route_test.go
aws/resource_aws_appmesh_mesh_test.go
aws/resource_aws_appmesh_route_test.go
aws/resource_aws_appmesh_virtual_gateway_test.go
aws/resource_aws_appmesh_virtual_node_test.go
aws/resource_aws_appmesh_virtual_router_test.go
aws/resource_aws_appmesh_virtual_service_test.go
aws/resource_aws_batch_job_definition_test.go

Prefer lastPage for pagination, A

---

.semgrep.yml
aws/resource_aws_cloudtrail_test.go
aws/resource_aws_cloudwatch_log_group_test.go
aws/resource_aws_codebuild_report_group_test.go
aws/resource_aws_cognito_user_pool_domain_test.go
aws/resource_aws_cognito_user_pool_test.go
aws/resource_aws_db_event_subscription_test.go
aws/resource_aws_ec2_carrier_gateway_test.go
aws/resource_aws_ec2_client_vpn_endpoint_test.go
aws/resource_aws_ec2_client_vpn_network_association_test.go
aws/resource_aws_ecr_repository_test.go

Prefer lastPage for pagination, C

---

aws/resource_aws_subnet_test.go

Relates #15334
Output from acceptance testing: NA
```
2021/04/07 23:44:47 [INFO] Deleting subnet: subnet-0a51c7b15896c4537
2021/04/07 23:44:47 [INFO] Deleting subnet: subnet-02d0710b0adc6de0e
2021/04/07 23:44:47 [DEBUG] Waiting for state to become: [destroyed]
2021/04/07 23:44:47 [DEBUG] Waiting for state to become: [destroyed]
```

tests/r/subnet: Add sweeper concurrency

---

aws/resource_aws_ecrpublic_repository_test.go

Relates #15334
Output from acceptance testing: NA

tests/r/ecrpublic_repository: Add sweeper concurrency

---

.semgrep.yml
aws/resource_aws_ecs_cluster_test.go
aws/resource_aws_ecs_service_test.go
aws/resource_aws_ecs_task_definition_test.go
aws/resource_aws_elasticache_cluster_test.go
aws/resource_aws_elasticache_parameter_group_test.go
aws/resource_aws_elasticache_replication_group_test.go
aws/resource_aws_elasticache_security_group_test.go
aws/resource_aws_elasticache_subnet_group_test.go
aws/resource_aws_elb_test.go

Prefer lastPage for pagination, E

---

.semgrep.yml
aws/resource_aws_emr_cluster_test.go
aws/resource_aws_flow_log_test.go
aws/resource_aws_glacier_vault_test.go
aws/resource_aws_iam_group_test.go
aws/resource_aws_iam_policy_test.go
aws/resource_aws_instance_test.go
aws/resource_aws_kinesis_analytics_application_test.go
aws/resource_aws_kinesisanalyticsv2_application_test.go
aws/resource_aws_lb_target_group_test.go
aws/resource_aws_lb_test.go

Prefer lastPage for pagination, F

---

.hashibot.hcl
aws/config.go
aws/provider.go
infrastructure/repository/labels-service.tf
website/allowed-subcategories.txt
website/docs/guides/custom-service-endpoints.html.md

Adds initial service client for Amazon Detective as per the [contribution guidelines](https://github.com/hashicorp/terraform-provider-aws/blob/main/docs/contributing/contribution-checklists.md#new-service).
Relates #11672
```
...
```

New service client: Amazon Detective

---

website/docs/r/s3_bucket.html.markdown

Updating IAM Role permission for `Using replication configuration` example as per AWS documentation - https://docs.aws.amazon.com/AmazonS3/latest/userguide/setting-repl-config-perm-overview.html

Update s3 replication IAM role perms as per AWS doc.

---

.changelog/17164.txt

Add CHANGELOG entry for #17164

---

website/docs/r/db_instance.html.markdown
website/docs/r/db_parameter_group.html.markdown
website/docs/r/db_subnet_group.html.markdown

Link RDS Learn tutorial from AWS provider docs

---

.changelog/18558.txt

Add CHANGELOG entry for #18558

---

website/docs/r/codepipeline.markdown

These changes are needed for the examples to run properly. 
```
...
```

Add IAM permissions to codepipeline docs

---

CHANGELOG.md

Removes duplicate **`3.37.0 (April 16, 2021)`** header.
Adds **`3.38.0 (Unreleased)`** header.
```
n/a
```

Fix CHANGELOG after 3.37.0 release

---

aws/resource_aws_gamelift_alias.go
aws/resource_aws_gamelift_build.go
aws/resource_aws_gamelift_fleet.go
aws/resource_aws_gamelift_game_session_queue.go
aws/resource_aws_glacier_vault.go
aws/resource_aws_globalaccelerator_accelerator.go
website/docs/r/gamelift_alias.html.markdown
website/docs/r/gamelift_build.html.markdown
website/docs/r/gamelift_fleet.html.markdown
website/docs/r/gamelift_game_session_queue.html.markdown
website/docs/r/glacier_vault.html.markdown
website/docs/r/globalaccelerator_accelerator.markdown

Relates #7926
```
...
```
* verified data-sources DNE in ga-glo grouping

provider: Support default tags (resources aws_ga-glo)

---

aws/resource_aws_flow_log.go
aws/resource_aws_fsx_lustre_file_system.go
aws/resource_aws_fsx_windows_file_system.go
website/docs/r/flow_log.html.markdown
website/docs/r/fsx_lustre_file_system.html.markdown
website/docs/r/fsx_windows_file_system.html.markdown

Reference: https://github.com/hashicorp/terraform-provider-aws/issues/7926

provider: Support default tags (resources aws_f*)

---

aws/resource_aws_pinpoint_app.go
aws/resource_aws_placement_group.go
website/docs/r/pinpoint_app.markdown
website/docs/r/placement_group.html.markdown

Reference: https://github.com/hashicorp/terraform-provider-aws/issues/7926

provider: Support default tags (resources aws_p*)

---

aws/resource_aws_nat_gateway.go
aws/resource_aws_neptune_cluster.go
aws/resource_aws_neptune_cluster_instance.go
aws/resource_aws_neptune_cluster_parameter_group.go
aws/resource_aws_neptune_event_subscription.go
aws/resource_aws_neptune_parameter_group.go
aws/resource_aws_neptune_subnet_group.go
aws/resource_aws_network_acl.go
aws/resource_aws_network_interface.go
aws/resource_aws_networkfirewall_firewall.go
aws/resource_aws_networkfirewall_firewall_policy.go
aws/resource_aws_networkfirewall_rule_group.go
website/docs/r/nat_gateway.html.markdown
website/docs/r/neptune_cluster.html.markdown
website/docs/r/neptune_cluster_instance.html.markdown
website/docs/r/neptune_cluster_parameter_group.html.markdown
website/docs/r/neptune_event_subscription.html.markdown
website/docs/r/neptune_parameter_group.html.markdown
website/docs/r/neptune_subnet_group.html.markdown
website/docs/r/network_acl.html.markdown
website/docs/r/network_interface.markdown
website/docs/r/networkfirewall_firewall.html.markdown
website/docs/r/networkfirewall_firewall_policy.html.markdown
website/docs/r/networkfirewall_rule_group.html.markdown

Reference: https://github.com/hashicorp/terraform-provider-aws/issues/7926

provider: Support default tags (resources aws_n*)

---

aws/resource_aws_lambda_function.go
aws/resource_aws_launch_template.go
aws/resource_aws_lb.go
aws/resource_aws_lb_target_group.go
aws/resource_aws_licensemanager_license_configuration.go
aws/resource_aws_lightsail_instance.go
website/docs/r/lambda_function.html.markdown
website/docs/r/launch_template.html.markdown
website/docs/r/lb.html.markdown
website/docs/r/lb_target_group.html.markdown
website/docs/r/licensemanager_license_configuration.markdown
website/docs/r/lightsail_instance.html.markdown

Reference: https://github.com/hashicorp/terraform-provider-aws/issues/7926

provider: Support default tags (resources aws_l*)

---

aws/data_source_aws_elb.go
aws/resource_aws_elb.go
aws/resource_aws_emr_cluster.go
website/docs/r/elb.html.markdown
website/docs/r/emr_cluster.html.markdown

Reference: #7926
NOTE: Without #18840, this PR will break the ELB data source (`data.aws_elb`).

provider: Support default tags (resources aws_e* 6)

---

aws/resource_aws_ebs_snapshot_copy.go
website/docs/r/ebs_snapshot_copy.html.markdown

r/ebs_snapshot_copy: Add default tags

---

aws/resource_aws_glue_crawler.go
aws/resource_aws_glue_dev_endpoint.go
aws/resource_aws_glue_job.go
aws/resource_aws_glue_ml_transform.go
aws/resource_aws_glue_ml_transform_test.go
aws/resource_aws_glue_registry.go
aws/resource_aws_glue_registry_test.go
aws/resource_aws_glue_schema.go
aws/resource_aws_glue_schema_test.go
aws/resource_aws_glue_trigger.go
aws/resource_aws_glue_workflow.go
website/docs/r/glue_crawler.html.markdown
website/docs/r/glue_dev_endpoint.markdown
website/docs/r/glue_job.html.markdown
website/docs/r/glue_ml_transform.html.markdown
website/docs/r/glue_registry.html.markdown
website/docs/r/glue_schema.html.markdown
website/docs/r/glue_trigger.html.markdown
website/docs/r/glue_workflow.html.markdown

Adds default tags support for AWS Glue resources.
Relates #7926

Adds default tags support to AWS Glue resources

---

docs/contributing/data-handling-and-conversion.md

Fixes a couple of typos.
```
n/a
```

Fix typos in data-handling-and-conversion.md

---

aws/internal/vault/helper/pgpkeys/keybase_test.go

Reference: https://keybase.io/hashicorp (click key to see fingerprint)
Closes #19080
Output from acceptance testing: N/A (unit testing)

internal/vault/helper/pgpkeys: Update expected fingerprint in unit testing

---

aws/resource_aws_codedeploy_app.go
aws/resource_aws_codedeploy_deployment_group.go
aws/resource_aws_eks_addon.go
aws/resource_aws_route53_resolver_firewall_domain_list.go
website/docs/r/codedeploy_app.html.markdown
website/docs/r/codedeploy_deployment_group.html.markdown
website/docs/r/route53_resolver_firewall_domain_list.markdown

Relates #7926
```
Will be covered by nightly CI tests
```

provider: add default tags support to remaining resources

---

aws/internal/experimental/nullable/bool.go
aws/resource_aws_mq_broker.go

Makes nullable bool diff suppress a standalone function

---

website/docs/r/route53_record.html.markdown

docs/resource/aws_route53_record: Change NS and SOA Record Management TTL
Relates OR Closes #18442
Output from acceptance testing: Not Applicable

Update route53_record_markdown NS TTL

---

website/docs/r/ecs_cluster.html.markdown

Added Container Insights example for `aws_ecs_cluster` resource.

r/ecs_cluster: Add container insights example

---

website/docs/r/db_instance.html.markdown

Closes #84 
```release-note
NONE
```
```
...
```
Acc tests not run as I am not able to pay for them. Documentation changes only.

[#84] updated documenation for aws_db_instance.name property

---

website/docs/r/workspaces_ip_group.html.markdown

Add rules with fake CIDRs into the example

---

.changelog/16916.txt
aws/resource_aws_appsync_resolver_test.go
aws/validators.go
aws/validators_test.go
website/docs/r/lakeformation_permissions.html.markdown

Closes #16848
Closes #18034
Closes #18374
```
In aws_lakeformation_permissions all principal types (including SAML/AD, QuickSight and other accounts) are now suported
```
```
TF_ACC=1 go test ./aws -v -count 1 -parallel …
```

adapted validatePrincipal to all allowed lakeformation principals types, solves #16848 

---

website/docs/d/resourcegroupstaggingapi_resources.html.markdown

There were mistakes in documentation part in #17804
This PR fixes the arguments

Fix argument name in documentation

---

ROADMAP.md
docs/roadmaps/2021_February_to_April.md

Updating the roadmap for May through July, moving February-April roadmap into `docs/roadmaps` archive.

May - July 2021 Roadmap

---

.github/workflows/release.yml

This PR archives belonging to a released milestone. Triggered on release.

workflow: Add card archiver job

---

website/docs/r/organizations_organization.html.markdown

This PR updates the valid policy values in the `enabled_policy_types` argument of the `aws_organizations_organization` resource.
Relates #14142

docs: update valid policy types in aws_organizations_organization

---

.github/workflows/release.yml

This adds a job to update the new target version after release with the assumption that it will be minor. Manual intervention will be required for point or major versions.

workflow/Add job to update with new minor version after release.

---

.github/workflows/release.yml

workflow/ be consistent with secrets usage in workflows

---

.github/workflows/release.yml

This will resolved the detached head issue from the last run.

Specify main as ref for post-release changelog edit

---

website/docs/r/rds_global_cluster.html.markdown

Closes #10188
```
N/A (Documentation only)
```

Add examples for mysql and postgresql

---

.changelog/19492.txt
aws/data_source_aws_launch_template.go
aws/data_source_aws_launch_template_test.go

add missing interface_type

---

website/docs/r/ec2_traffic_mirror_target.html.markdown

Trivial typo correction

---

website/docs/index.html.markdown

This PR adds a links to our Learn tutorials from the provider docs, in case new users stumble upon the provider but don't know the basics of Terraform. 
It also changes the page description and intro to active voice, to make it easier to read and align it more closely with HashiCorp's engineering writing guidance. 
I don't think the below fields are …

Add a link to Learn from docs

---

.github/workflows/issue-comment-created.yml
.hashibot.hcl

Reference: https://github.com/hashicorp/terraform-provider-aws/issues/19356
Output from acceptance testing: N/A (hashibot configuration)

hashibot: Migrate remove_labels_on_reply behavior to GitHub Actions

---

.changelog/11937.txt
.changelog/11939.txt
aws/internal/service/amplify/finder/finder.go
aws/provider.go
aws/resource_aws_amplify_test.go
aws/resource_aws_amplify_webhook.go
aws/resource_aws_amplify_webhook_test.go
website/docs/r/amplify_webhook.html.markdown

Relates #6917 
AWS Amplify service client has been merged by #9874.
Before merging this PR, #11938 must be merged. After then, I'll run git rebase for this branch.
```release-note
New Resource: aws_amplify_webhook
```
Output from acceptance …

New Resource: aws_amplify_webhook

---

.github/labeler-issue-triage.yml
.github/labeler-pr-triage.yml
aws/config.go
aws/provider.go
infrastructure/repository/labels-service.tf
website/allowed-subcategories.txt
website/docs/guides/custom-service-endpoints.html.md

feature: Add Amazon Location Service client.

---

.changelog/19705.txt
aws/resource_aws_cur_report_definition.go
aws/resource_aws_cur_report_definition_test.go
aws/resource_aws_cur_test.go
website/docs/r/cur_report_definition.html.markdown

r/aws_cur_report_definition: support update

---

.changelog/19753.txt
aws/resource_aws_datasync_location_smb.go
aws/resource_aws_datasync_location_smb_test.go

Closes #18493
```
$ make testacc TESTARGS='-run=TestAccAWSDataSyncLocationSmb_'
--- PASS: TestAccAWSDataSyncLocationSmb_disappears (307.53s)
--- PASS: TestAccAWSDataSyncLocationSmb_basic (381.70s)
--- PASS: TestAccAWSDataSyncLocationSmb_Tags (501.83s)
```

r/datasync_location_smb - support update

---

website/docs/r/cloudfront_cache_policy.html.markdown

Following on from #19830 this PR makes the same corrections to the resource file.

d/resource_cloudfront_cache_policy - fix bullet formatting for config/items

---

aws/resource_aws_subnet_test.go

Relates #16301
```
will be verified by nightly TC runs
```

sweepers/subnet: add networkfirewall firewall to dependencies

---

aws/resource_aws_backup_vault_notifications_test.go

Relates #15334
```
verified by nightly TC runs
```

sweeper/backup_vault_notifications: use paginated func and add concurrency

---

.changelog/19898.txt
aws/internal/service/neptune/finder/finder.go
aws/internal/service/neptune/id.go
aws/internal/service/neptune/waiter/status.go
aws/internal/service/neptune/waiter/waiter.go
aws/provider.go
aws/resource_aws_neptune_cluster_endpoint.go
aws/resource_aws_neptune_cluster_endpoint_test.go
website/docs/r/neptune_cluster_endpoint.html.markdown

Closes #16498
```
$ make testacc TESTARGS='-run=TestAccAWSNeptuneClusterEndpoint_'
--- PASS: TestAccAWSNeptuneClusterEndpoint_basic (249.91s)
--- PASS: TestAccAWSNeptuneClusterEndpoint_tags (298.03s)
--- PASS: TestAccAWSNeptuneClusterEndpoint_disappears (186.76s)
--- PASS: TestAccAWSNeptuneClusterEndpoint_disappears_cluster …
```

r/neptune_cluster_endpoint - new resource

---

.changelog/16874.txt

Add CHANGELOG entry for #16874

---

aws/resource_aws_route53_zone_test.go

Relates #19875, #12661
`terraformtest.com` also needs to be protected from sweeping.

tests/sweeper/route53_zone: Protect domain

---

aws/resource_aws_route53_zone_test.go

r/route53_zone: Add a new protected TLD

---

infrastructure/repository/main.tf

infrastructure: Fix github config

---

.changelog/16850.txt
.changelog/16908.txt
.changelog/16916.txt
.changelog/16961.txt
.changelog/16963.txt
.changelog/16979.txt
.changelog/17001.txt
.changelog/17295.txt
.changelog/17319.txt
.changelog/17347.txt
.changelog/17655.txt
.changelog/17754.txt
.changelog/18932.txt
.changelog/19168.txt
.changelog/19391.txt
.changelog/19415.txt
.changelog/19423.txt
.changelog/19425.txt
.changelog/19499.txt
.changelog/19503.txt
.changelog/19572.txt
.changelog/19813.txt

* Use triple tick to start entry
* `release-note`, not `release-notes`

Fixup CHANGELOG entry files

---

aws/resource_aws_lb_target_group.go

add tags when create target group in aws

---

website/docs/r/transfer_server.html.markdown

docs: removed duplicate example code snippet

---

.changelog/19718.txt

Correct resource name in CHANGELOG

---

docs/MAINTAINING.md

Relates #19356.
Fix `markdown-link-check` error:
> FILE: docs/MAINTAINING.md
> [✖] https://github.com/apps/hashibot → Status: 404
```
...
```

Remove reference to hashibot

---

aws/resource_aws_storagegateway_gateway_test.go

Added acceptance tests to StorageGateway Gateway for Managed Microsoft Active Directory.
```
$ make testacc TESTARGS='-run=TestAccAWSStorageGatewayGateway_SmbMicrosoft'
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSStorageGatewayGateway_SmbMicrosoft …
```

Added AccTests for MicrosoftAD to StorageGateway

---

.changelog/20054.txt

Correct resource name in CHANGELOG entry

---

aws/resource_aws_lb_test.go

Returns an error from `aws_lb` sweeper when deletion fails
Closes #19891
```
$ make sweep SWEEPARGS='-sweep-run=aws_lb -sweep-allow-failures=true'
2021/06/18 14:38:06 [DEBUG] Running Sweeper (aws_lb) in region (us-west-2)
2021/06/18 14:38:06 [INFO] Deleting LB: tf-lb-abc123
2021/06/18 14:38:06 [ERROR] Error running Sweeper (aws_lb) in region (us-west-2): 1 error occurred:
* failed to delete LB (tf-lb-abc123): ResourceInUse: Load balancer 'arn:aws:elasticloadbalancing:us-west-2:123456789012:loadbalancer/net/tf-lb-abc123/a1b2c3d4e5f6' cannot be deleted because it is currently associated with another service
```

sweeper/aws_lb: Fails silently

---

aws/resource_aws_wafv2_web_acl_test.go

Closes #19149 
Relates #15334
Output from sweeper testing:
```sh
$ make sweep SWEEPARGS='-sweep-run=aws_wafv2_web_acl'
go test ./aws -v -sweep=us-east-1,us-east-2,us-west-2 -sweep-run=aws_wafv2_web_acl -timeout 60m
2021/06/17 14:03:23 [DEBUG] Running Sweepers for region (us-east-1): …
```

sweepers/wafv2_web_acl: concurrency + error handling

---

website/docs/r/cloudwatch_event_rule.html.markdown

Add reference to AWS documentation for schedule_expression (#20060)

---

CHANGELOG.md

Correct new argument name in Release Notes (retro v3.47.0)

---

website/docs/r/pinpoint_email_channel.markdown

Add more info for from_address in aws_pinpoint_email_channel (#18050)

---

website/docs/d/cognito_user_pools.markdown

arns are also a part of the attributes.
```
...
```

arns are also a part of the attributes

---

website/docs/r/securityhub_organization_admin_account.html.markdown

Relates #19108.
Relates #20183.
* Fix _validate-terraform_ error `Warning: Single line comments should begin with # (terraform_comment_syntax)`
```
...
```

Fix linter errors

---

website/docs/r/fms_policy.html.markdown

The supported list of policy types is not validated by the provider, and to avoid presenting an outdated list we should refer back to AWS documentation for the must up to date list.

documentation/Refer to AWS docs for list of supported Policy Types

---

.github/labeler-issue-triage.yml
infrastructure/repository/labels-workflow.tf

Adds `sweeper` label for Issues and PRs. Adds automatic labelling for Issues.
N/A

Add `sweeper` label

---

aws/internal/service/eks/errors.go
aws/internal/service/eks/waiter/waiter.go

Relates #20199.
Relates #20226.

Better EKS waiter failure errors.

---

website/docs/r/s3_bucket.html.markdown

Closes Asana Ticket _(aws_s3_bucket replication configuration rules ignores priority when using prefix)_ 
* Changes reflect logic present here: https://github.com/hashicorp/terraform-provider-aws/blob/191d252bf2438a3f9ee722ce77e6236a7c083715/aws/resource_aws_s3_bucket.go#L2065-L2085
```
N/A
```

docs/s3_bucket: update `replication_configuration` details to be more readable

---

website/docs/d/availability_zones.html.markdown

Fix code block formatting in aws_availability_zones data source

---

website/docs/index.html.markdown

Link to default tags Learn tutorial from docs

---

.changelog/20082.txt

Tweak CHANGELOG entry

---

.changelog/10036.txt

Add CHANGELOG entry for #10036

---

aws/resource_aws_ecrpublic_repository_test.go

Closes https://github.com/hashicorp/terraform-provider-aws/issues/20359
In `us-west-2`:
```
--- SKIP: TestAccAWSEcrPublicRepository_basic (0.98s)
--- SKIP: TestAccAWSEcrPublicRepository_catalogdata_usagetext (0.98s)
--- SKIP: TestAccAWSEcrPublicRepository_catalogdata_description (0.98s)
--- SKIP: …
```

tests/resource_aws_ecrpublic_repository: check for region in ecrpublic-specific PreCheck

---

ROADMAP.md

Typo Fix ROADMAP.md

---

website/docs/index.html.markdown

Link AssumeRole Learn tutorial from docs, fix typo

---

aws/resource_aws_ses_identity_policy_test.go

Output from acceptance testing before change:
```
Error: Error requesting SES email identity verification: InvalidParameterValue: Invalid email address<f3rh8c9c.test>.
```
Output from acceptance testing after change:
```
--- PASS: TestAccAWSSESIdentityPolicy_Identity_Email (45.63s)
```

TestAccAWSSESIdentityPolicy_Identity_Email: create email with random test domain

---

.github/workflows/changelog.yml
.github/workflows/dependencies.yml
.github/workflows/issues.yml
.github/workflows/project.yml
.github/workflows/pull_requests.yml
docs/FAQ.md

Adds zhelding as maintainer to actions and documentation

---

website/docs/d/default_tags.markdown

Typo fix for documentation. No code changed, no tests affected.

Documentation fix for data.aws_default_tags

---

docs/FAQ.md

FAQ: Add section on mergability.

---

website/docs/r/cloudfront_distribution.html.markdown

fix formatting for block in docs.
N/A - docs change

fix format of example

---

.changelog/20570.txt
aws/internal/service/sagemaker/finder/finder.go
aws/provider.go
aws/resource_aws_sagemaker_human_task_ui.go
aws/resource_aws_sagemaker_human_task_ui_test.go
aws/test-fixtures/sagemaker-human-task-ui-tmpl.html
website/docs/r/sagemaker_human_task_ui.html.markdown

```
$ make testacc TESTARGS='-run=TestAccAWSSagemakerHumanTaskUi_'
--- PASS: TestAccAWSSagemakerHumanTaskUi_basic (122.65s)
--- PASS: TestAccAWSSagemakerHumanTaskUi_tags (194.21s)
--- PASS: TestAccAWSSagemakerHumanTaskUi_disappears (40.24s)
```

r/sagemaker_human_task_ui - new resource

---

.github/labeler-issue-triage.yml
.github/labeler-pr-triage.yml
aws/config.go
aws/provider.go
infrastructure/repository/labels-service.tf
website/allowed-subcategories.txt
website/docs/guides/custom-service-endpoints.html.md

Relates #20631.
```
% go test ./aws
ok      github.com/terraform-providers/terraform-provider-aws/aws       26.392s
```

Infrastructure for MemoryDB service

---

website/docs/r/s3_bucket_policy.html.markdown

Fix misleading aws_s3_bucket_policy docs

---

website/docs/r/autoscaling_group.html.markdown

Relates https://github.com/hashicorp/terraform-provider-aws/pull/7615
```
...
```

docs/r/autoscaling_group: remove merge conflicts

---

website/docs/r/dms_replication_instance.html.markdown

Update DMS documentation to add dependencies.

---

.changelog/19368.txt
aws/internal/service/cloudtrail/enum.go
aws/resource_aws_cloudtrail.go
aws/resource_aws_cloudtrail_test.go
website/docs/r/cloudtrail.html.markdown

Closes #18867
```
$ make testacc TESTARGS='-run=TestAccAWSCloudTrail_serial/Trail/advancedEventSelector'
--- PASS: TestAccAWSCloudTrail_serial/Trail/advancedEventSelector (94.83s)
$ make testacc TESTARGS='-run=TestAccAWSCloudTrail_serial/Trail/basic
--- PASS: TestAccAWSCloudTrail_serial/Trail/basic (167.76s)
```

r/aws_cloudtrail - add support for advanced event selectors

---

.changelog/20779.txt
aws/resource_aws_db_instance.go
aws/resource_aws_db_instance_test.go

Closes #19009
```
$ make testacc TESTARGS='-run=TestAccAWSDBInstance_license'
--- PASS: TestAccAWSDBInstance_license (1822.90s)
```

r/db_instance - fix update for `license_model`

---

website/docs/r/autoscaling_group.html.markdown

```
...
```
This is a documentation change and no code changes involved.

Added internal url references for sections in the doc

---

website/docs/guides/version-3-upgrade.html.md

```release-note
NONE
```
```
N/A
```
The current example given for the breaking change for `aws_acm_certificate` when upgrading v2 to v3 is very verbose. This PR includes another example which may apply to some …

Add another example of upgrading aws_acm_certificate from v2 to v3

---

website/docs/r/cognito_user_pool.markdown

Fix simple typo in cognito_user_pool docs

---

aws/internal/generators/listpages/main.go
aws/internal/keyvaluetags/generators/createtags/main.go
aws/internal/keyvaluetags/generators/gettag/main.go
aws/internal/keyvaluetags/generators/listtags/main.go
aws/internal/keyvaluetags/generators/servicetags/main.go
aws/internal/keyvaluetags/generators/updatetags/main.go
aws/internal/keyvaluetags/iam_tags.go
aws/internal/keyvaluetags/inspector_tags.go
aws/internal/keyvaluetags/s3_tags.go
aws/internal/keyvaluetags/s3control_tags.go
aws/internal/keyvaluetags/servicecatalog_tags.go
aws/internal/namevaluesfilters/ec2_filters.go
aws/internal/namevaluesfilters/generators/servicefilters/main.go
aws/internal/tagresource/generator/main.go
tools/main.go

Newer versions of Go like a few things done a little differently.

Fix formatting

---

.github/workflows/changelog.yml
.github/workflows/dependencies.yml
.github/workflows/issues.yml
.github/workflows/project.yml
.github/workflows/pull_requests.yml
docs/FAQ.md

Remove Bill from docs and workflows after his departure

---

.changelog/14671.txt

Add missing CHANGELOG entry for #14671

---

.changelog/21091.txt

Correct CHANGELOG format

---

aws/resource_aws_lakeformation_permissions.go

handle missing column

---

CHANGELOG.md

Retroactive update of v3.61.0 CHANGELOG

---

docs/contributing/contribution-checklists.md

Fix a broken link in contribution-checklists.md

---

.changelog/17991.txt
aws/internal/service/rds/enum.go
aws/internal/service/rds/finder/finder.go
aws/internal/service/rds/waiter/status.go
aws/internal/service/rds/waiter/waiter.go
aws/resource_aws_db_instance.go
aws/resource_aws_db_instance_test.go
aws/resource_aws_rds_cluster_instance.go
aws/resource_aws_rds_cluster_instance_test.go
website/docs/r/db_instance.html.markdown

Closes #17991 
```
$ make testacc TESTARGS='-run=TestAccAWSDBInstance_ReplicateSourceDb_ReplicaMode'
```

r/aws_db_instance: Add `replica_mode` attribute

---

website/docs/r/iam_role.html.markdown

Updated AWS IAM Policy Document Guide endpoint

---

internal/service/storagegateway/enum.go

storagegateway/file_system_association: Increase timeouts

---

.changelog/21639.txt
.changelog/21641.txt
internal/acctest/acctest_test.go
internal/conns/conns.go
website/docs/guides/custom-service-endpoints.html.md

Relates #21639
Relates #21637
Fixes #21437
Fixes #20823
```
--- PASS: TestTlsRsaPrivateKeyPem (0.15s)
--- PASS: TestTlsRsaPublicKeyPem (0.13s)
--- PASS: TestTlsRsaX509LocallySignedCertificatePem (0.15s)
--- PASS: TestTlsRsaX509SelfSignedCaCertificatePem (0.20s)
--- PASS: TestTlsRsaX509SelfSignedCertificatePem …
```

Fix endpoints assignment, testing

---

website/docs/r/kms_replica_external_key.html.markdown
website/docs/r/kms_replica_key.html.markdown

Update docs for `aws_kms_replica_key` and `aws_kms_replica_external_key`.
I thinks the example code is wrong.

Fix docs for kms resources

---

docs/contributing/running-and-writing-acceptance-tests.md

docs: Acctests

---

website/docs/d/ec2_transit_gateway.html.markdown

Source: https://docs.aws.amazon.com/cli/latest/reference/ec2/describe-transit-gateways.html

Docs: Add Transit Gateway filter support options

---

.github/workflows/roadmap_milestone.yml

Github Action to add roadmap milestone items to working board

---

.github/PULL_REQUEST_TEMPLATE.md
GNUmakefile
docs/contributing/contribution-checklists.md
docs/contributing/running-and-writing-acceptance-tests.md

make: Add PKG and TESTS parameters

---

.changelog/18079.txt
.github/workflows/terraform_provider.yml
internal/service/configservice/config_test.go
internal/service/configservice/remediation_configuration.go
internal/service/configservice/remediation_configuration_test.go
website/docs/r/config_remediation_configuration.html.markdown

Closes #15491
```
% AWS_PROFILE=terraform-test AWS_DEFAULT_REGION=us-west-2 make testacc TESTARGS='-run=TestAccAWSConfig_serial/RemediationConfiguration'
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSConfig_serial/RemediationConfiguration -timeout 180m …
```

Update aws_config_remediation_configuration resource to support latest schema as of 2021-03-12

---

internal/service/elb/load_balancer.go
internal/service/elb/load_balancer_data_source.go

semgrep: remove extraneous pointer conversion in elb/load_balancer.go and elb/load_balancer_data_source.go

---

.changelog/11997.txt
.changelog/21884.txt
CHANGELOG.md

Fix changelog

---

.changelog/21900.txt
internal/service/docdb/cluster_instance.go
internal/service/neptune/cluster_instance.go
internal/service/rds/cluster.go
internal/service/rds/cluster_instance.go
internal/service/rds/global_cluster.go
internal/service/rds/instance_role_association.go

RDS: Add storage-optimization pending state

---

website/docs/d/cloudwatch_event_connection.html.markdown

Relates https://github.com/hashicorp/terraform-provider-aws/pull/18905

Correct cloudwatch_event_connection Data Course Title

---

go.mod
go.sum

Updates the AWS SDK for Go to v1.42.17

Updates the AWS SDK for Go to v1.42.17

---

website/docs/d/subnet_ids.html.markdown

fix: correct usage example

---

.changelog/22011.txt
website/docs/d/autoscaling_groups.html.markdown

:memo: update docs to support asg filters change

---

website/docs/r/vpc_ipam_pool.html.markdown

…blicly_advertisable argument reference.
```
...
```
@drewmullen

docs/aws_vpc_ipam_pool - minor fixes

---

website/docs/r/vpc.html.markdown

docs/aws_vpc ipam ipv6 attributes 

---

.github/workflows/terraform_provider.yml
internal/service/emr/sweep.go
internal/sweep/sweep.go

EMR sweepers were broken. Fixes the sweeper and adds a simple check to prevent future problems.

sweepers: Fixes sweepers and adds simple check to prevent breakage

---

website/docs/r/s3_bucket_ownership_controls.html.markdown

`object_ownership` variable is required! :)

Fix markdown for aws_s3_bucket_ownership_controls docs

---

website/docs/r/lb.html.markdown

Closes #20479
For a simple test, I used the following code block:
```hcl
data "aws_availability_zones" "this" {
state = "available"
}
resource "aws_vpc" "this" {
cidr_block = "10.0.0.0/16"
}
resource "aws_internet_gateway" "this" {
vpc_id = aws_vpc.this.id
}
resource "aws_subnet" "public" {
for_each = { for idx, name in data.aws_availability_zones.this.names …
```

docs: refactor splat expression to for expression

---

website/docs/r/cloudwatch_event_target.html.markdown

docs: add role policy attachment to example

---

.changelog/22016.txt
CHANGELOG.md

Relates #22016.
Closes #22153.
```
...
```

Correct CHANGELOG for #22016

---

website/docs/r/route53_hosted_zone_dnssec.html.markdown

Add warning to documentation to hosted zone DNSSEC config

---

.changelog/22185.txt
internal/service/iam/service_linked_role.go
internal/service/iam/service_linked_role_test.go
internal/service/iam/sweep.go
internal/service/iam/wait.go
website/docs/r/iam_service_linked_role.html.markdown

Closes #22057
```
$ make testacc TESTS=TestAccIAMServiceLinkedRole_ PKG=iam
--- PASS: TestAccIAMServiceLinkedRole_disappears (66.79s)
--- PASS: TestAccIAMServiceLinkedRole_CustomSuffix_diffSuppressFunc (82.35s)
--- PASS: TestAccIAMServiceLinkedRole_customSuffix (82.50s)
--- PASS: TestAccIAMServiceLinkedRole_basic (83.02s)
--- …
```

r/iam_service_linked_role - tagging support

---

website/docs/r/quicksight_user.html.markdown

docs(quicksight): iam_arn req if IAM is specified

---

internal/service/events/sweep.go

Closes #22131.
```console
% make sweep SWEEPARGS=-sweep-run=aws_cloudwatch_event_bus SWEEP=us-east-2
go test ./internal/sweep -v -tags=sweep -sweep=us-east-2 -sweep-run=aws_cloudwatch_event_bus -timeout 60m
2021/12/09 09:49:13 [DEBUG] Running Sweepers …
```

Iterate event buses when sweeping event targets and event rules

---

website/docs/r/lightsail_instance.html.markdown

Closes #22184
This PR adds additional documentation around some attributes that were not previously documented.
https://docs.aws.amazon.com/sdk-for-go/api/service/lightsail/#Instance
https://docs.aws.amazon.com/sdk-for-go/api/service/lightsail/#InstanceHardware …

Add additional attributes to documentation

---

.changelog/22214.txt
internal/service/ses/identity_policy.go
internal/service/ses/identity_policy_test.go

Relates #21968
```console
% make testacc TESTS=TestAccSESIdentityPolicy PKG=ses       
TF_ACC=1 go test ./internal/service/ses/... -v -count 1 -parallel 20 -run='TestAccSESIdentityPolicy' -timeout 180m
--- PASS: TestAccSESIdentityPolicy_Identity_email …
```

ses/identity_policy: Fix equivalent policy diffs

---

.changelog/22227.txt
internal/service/s3/hosted_zones.go

Fix: wrong 'eu-south-1' region's S3 hosted zone ID

---

website/docs/r/s3_account_public_access_block.html.markdown

Updating to match the language at https://docs.aws.amazon.com/AmazonS3/latest/userguide/access-control-block-public-access.html
We were debugging something related to this resource and the difference in language here was pretty important!

Update aws_s3_account_public_access_block.block_public_acls docs

---

website/docs/r/connect_hours_of_operation.html.markdown

docs(connect): typo blog to block

---

.changelog/21531.txt
internal/service/ec2/route.go
internal/service/ec2/route_table.go
website/docs/r/route.html.markdown
website/docs/r/route_table.html.markdown

From 2 minutes to 5 minutes to address https://github.com/hashicorp/terraform-provider-aws/issues/21032
Relates OR Closes #21032
```
...
```

Increase route_table Create timeout

---

.changelog/22289.txt
internal/provider/provider.go
internal/service/cognitoidp/user_pool_clients_data_source.go
internal/service/cognitoidp/user_pool_clients_data_source_test.go
website/docs/d/cognito_user_pool_clients.markdown

Relates OR Closes #9139
```
$ make testacc TESTARGS="-run=TestAccCognitoIDPUserPoolClientsDataSource_basic" PKG_NAME="./internal/service/cognitoidp" ACCTEST_PARALLELISM=3
TF_ACC=1 go test ././internal/service/cognitoidp/... -v -count 1 -parallel 3 …
```

new datasource aws_cognito_user_pool_clients

---

examples/s3-api-gateway-integration/main.tf

Fix small spelling mistake in example.

Fix spelling mistake in s3-api-gateway-integration example.

---

.github/labeler-issue-triage.yml
.github/labeler-pr-triage.yml
infrastructure/repository/labels-service.tf
internal/conns/conns.go
website/allowed-subcategories.txt
website/docs/guides/custom-service-endpoints.html.md

Relates to #20942 
Output from testing:
```
make test
$ go test ./...  -timeout=5m
?       github.com/hashicorp/terraform-provider-aws     [no test files]
ok      github.com/hashicorp/terraform-provider-aws/internal/acctest    26.640s
ok      github.com/hashicorp/terraform-provider-aws/internal/conns …
```

Add kafkaconnect service

---

internal/provider/provider.go
internal/service/memorydb/acl.go
internal/service/memorydb/acl_test.go
internal/service/memorydb/find.go
internal/service/memorydb/status.go
internal/service/memorydb/wait.go
website/docs/r/memorydb_acl.html.markdown

Relates https://github.com/hashicorp/terraform-provider-aws/issues/20631
```
$ make testacc PKG=memorydb TESTS=TestAccMemoryDBACL_
TF_ACC=1 go test ./internal/service/memorydb/... -v -count 1 -parallel 20 -run='TestAccMemoryDBACL_' -timeout 180m
=== RUN …
```

New Resource: aws_memorydb_acl

---

website/docs/r/batch_compute_environment.html.markdown

Fix a typo in the Terraform documentation for the provider.

docs(batch): fix typo

---

docs/contributing/running-and-writing-acceptance-tests.md

Align Contribution guide sweeper section for post service package refactor

---

.changelog/21508.txt

Correct resource names in CHANGELOG entries

---

.changelog/22196.txt
internal/provider/provider.go
internal/service/codebuild/find.go
internal/service/codebuild/resource_policy.go
internal/service/codebuild/resource_policy_test.go
website/docs/r/codebuild_resource_policy.html.markdown

Closes #22191 
```
$ make testacc TESTS=TestAccCodeBuildResourcePolicy_ PKG=codebuild
--- PASS: TestAccCodeBuildResourcePolicy_disappears_resource (70.65s)
--- PASS: TestAccCodeBuildResourcePolicy_disappears (73.32s)
--- PASS: TestAccCodeBuildResourcePolicy_basic (83.01s)
```

r/codebuild_resource_policy - new resource

---

.changelog/22295.txt
internal/service/cloudtrail/service_account_data_source.go
internal/service/elb/hosted_zone_id_data_source.go
internal/service/s3/hosted_zones.go

Relates #22252.
prev: https://github.com/hashicorp/terraform-provider-aws/pull/12967, https://github.com/hashicorp/terraform-provider-aws/pull/13061, fixed doc links in https://github.com/hashicorp/terraform-provider-aws/pull/22294
https://docs.aws.amazon.com/general/latest/gr/s3.html#s3_region
https://docs.aws.amazon.com/general/latest/gr/elb.html#elb_region …

data_source: ap-southeast-3 (Jakarta)

---

website/docs/r/glue_user_defined_function.html.markdown

Relates OR Closes #22230 
```
```

changed to create_time

---

.changelog/21727.txt
internal/service/s3/bucket_object.go

This PR is equivalent to #14382, but conforms to the new directory layout
resulting from #21306.
Closes #788.
Closes #19336.
Supersedes #14382.
```
...
```

Use s3manager.Uploader for creating S3 bucket objects

---

.changelog/18451.txt
internal/service/codepipeline/codepipeline.go

```
$ make testacc TESTARGS='-run=TestAccAWSCodePipeline_'
--- PASS: TestAccAWSCodePipeline_disappears (75.33s)
--- PASS: TestAccAWSCodePipeline_WithNamespace (82.47s)
--- PASS: TestAccAWSCodePipeline_emptyStageArtifacts (86.13s)
--- PASS: TestAccAWSCodePipeline_multiregion_basic (91.90s)
--- PASS: …
```

r/codepipeline - add validations

---

.changelog/22414.txt
internal/provider/provider.go
internal/service/kafkaconnect/find.go
internal/service/kafkaconnect/worker_configuration.go
internal/service/kafkaconnect/worker_configuration_data_source.go
internal/service/kafkaconnect/worker_configuration_data_source_test.go
internal/service/kafkaconnect/worker_configuration_test.go
website/docs/d/mskconnect_worker_configuration.html.markdown
website/docs/r/mskconnect_worker_configuration.html.markdown

Add aws_mskconnect_worker_configuration resource

---

.changelog/22443.txt
internal/provider/provider.go
internal/service/devicefarm/find.go
internal/service/devicefarm/upload.go
internal/service/devicefarm/upload_test.go
website/docs/r/devicefarm_upload.html.markdown

```
$ make testacc TESTS=TESTS=TestAccDeviceFarmUpload_ PKG=devicefarm
--- PASS: TestAccDeviceFarmUpload_disappears_project (69.10s)
--- PASS: TestAccDeviceFarmUpload_disappears (76.15s)
--- PASS: TestAccDeviceFarmUpload_basic (153.88s)
```

r/devicefarm_upload - new resource

---

.changelog/22448.txt

Missing CHANGELOG entry

---

.changelog/22462.txt
internal/service/fsx/lustre_file_system.go

r/fsx_lustre_file_system - add more values to `per_unit_storage_throughput`

---

website/docs/r/account_alternate_contact.html.markdown

Update import documentation for aws_account_alternate_contact

---

.changelog/22472.txt
internal/service/glue/crawler.go
internal/service/glue/crawler_test.go
website/docs/r/glue_crawler.html.markdown

```
$ make testacc TESTS=TestAccGlueCrawler_deltaTarget PKG=glue
--- PASS: TestAccGlueCrawler_deltaTarget (186.13s)
```

r/glue_crawler - support delta tables

---

.changelog/22463.txt

Correct data source name in CHANGELOG

---

.github/workflows/stale.yml

Closes #22447
Increase the ops per run to see if if it helps get through the total issue/pr count.

workflow: Increase stale ops per run

---

website/docs/d/secretsmanager_secret_version.html.markdown

Closes #[22433](https://github.com/hashicorp/terraform-provider-aws/issues/22433) 
TBD

changing name of the resource to avoid confusion

---

.changelog/22514.txt

Update CHANGELOG entry

---

.changelog/22615.txt
internal/service/cognitoidp/user_pool_clients_data_source.go
internal/service/cognitoidp/user_pool_clients_data_source_test.go
website/docs/d/cognito_user_pool_clients.markdown

Relates/closes #22593.
```
$ AWS_PROFILE=private make testacc TESTS=TestAccCognitoIDPUserPoolClientsDataSource_basic PKG=cognitoidp
TF_ACC=1 go test ./internal/service/cognitoidp/... -v -count 1 -parallel 20 -run='TestAccCognitoIDPUserPoolClientsDataSource_basic' …
```

d/aws_cognito_user_pool_clients - support name attribute

---

.changelog/21776.txt
internal/service/elb/enum.go
internal/service/elb/flex.go
internal/service/elb/policy.go
internal/service/elb/policy_test.go

Closes #2867
Closes #995
```
--- PASS: TestAccELBPolicy_basic (24.17s)
--- PASS: TestAccELBPolicy_LBCookieStickinessPolicyType_computedAttributesOnly (24.19s)
--- PASS: TestAccELBPolicy_SSLNegotiationPolicyType_computedAttributesOnly (40.09s)
--- PASS: TestAccELBPolicy_SSLSecurityPolicy_predefined (43.73s)
--- …
```

r/aws_load_balancer_policy: suppress computed `policy_attribute` diffs

---

internal/service/glue/schema_test.go
website/docs/r/glue_schema.html.markdown

Closes #22657
```
$ make testacc TESTS=TestAccGlueSchema_json PKG=glue
--- PASS: TestAccGlueSchema_json (108.98s)
```

r/glue_schema - add json test + update doc

---

website/docs/r/cloudwatch_event_target.html.markdown

Doc fix - this example is a resource not a data lookup

---

internal/service/ec2/ami.go
internal/service/ec2/ebs_snapshot.go
internal/service/ec2/errors.go
internal/service/ec2/sweep.go

Closes #22684.
Before:
```
$ SWEEP="eu-central-1" SWEEPARGS=-sweep-run=aws_ebs_snapshot make sweep
go test ./internal/sweep -v -tags=sweep -sweep=eu-central-1 -sweep-run=aws_ebs_snapshot -timeout 60m
2022/01/21 09:45:18 [DEBUG] Running Sweepers for …
```

r/aws_ami - sweeper

---

.changelog/21534.txt
internal/provider/provider.go
internal/service/sagemaker/find.go
internal/service/sagemaker/project.go
internal/service/sagemaker/project_test.go
internal/service/sagemaker/status.go
internal/service/sagemaker/sweep.go
internal/service/sagemaker/wait.go
website/docs/r/sagemaker_project.html.markdown

Relates #21490
```
$ make testacc TESTARGS='-run=TestAccSageMakerProject_' PKG_NAME=internal/service/sagemaker
--- PASS: TestAccSageMakerProject_description (426.65s)
--- PASS: TestAccSageMakerProject_basic (427.42s)
--- PASS: TestAccSageMakerProject_tags (674.57s)
--- PASS: TestAccSageMakerProject_disappears (236.10s)
```

r/sagemaker_project - new resource

---

website/docs/d/cognito_user_pool_client.markdown

:memo: Replace docs to remove clients filter and just have a normal lookup

---

.changelog/22697.txt
internal/provider/provider.go
internal/service/dataexchange/data_set.go
internal/service/dataexchange/data_set_test.go
internal/service/dataexchange/find.go
internal/service/dataexchange/sweep.go
website/allowed-subcategories.txt
website/docs/r/dataexchange_data_set.html.markdown

Relates #22237
```
$ make testacc TESTS=TestAccDataExchangeDataSet_ PKG=dataexchange 
--- PASS: TestAccDataExchangeDataSet_disappears (48.21s)
--- PASS: TestAccDataExchangeDataSet_basic (93.39s)
--- PASS: TestAccDataExchangeDataSet_tags (123.72s)
```

r/dataexchange_data_set - new resource

---

.changelog/22731.txt
internal/provider/provider.go
internal/service/apigateway/export_data_source.go
internal/service/apigateway/export_data_source_test.go
internal/service/apigateway/sdk_data_source.go
internal/service/apigateway/sdk_data_source_test.go
website/docs/d/api_gateway_export.html.markdown
website/docs/d/api_gateway_sdk.html.markdown

Closes #12943
```
$ make testacc TESTS=TestAccAPIGatewayExportDataSource_basic PKG=apigateway
--- PASS: TestAccAPIGatewayExportDataSource_basic (62.88s)
```
```
$ make testacc TESTS=TestAccAPIGatewaySdkDataSource_basic PKG=apigateway
--- PASS: TestAccAPIGatewaySdkDataSource_basic (57.35s)
```

d/api_gateway_export and api_gateway_sdk - new datasources

---

internal/service/iam/instance_profile.go

Fix spelling in instance_profile error message

---

docs/contributing/naming.md

Output from acceptance testing: n/a

Naming guide fix

---

internal/service/grafana/consts.go

Add grafana package

---

website/docs/r/cognito_user_pool_domain.markdown

:memo: update example and domain description

---

ROADMAP.md
docs/roadmaps/2021_November_to_January.md
docs/roadmaps/2021_Novemeber_to_January.md

Q1 2022 roadmap: Feb - Apr

---

.changelog/22878.txt
internal/service/acmpca/certificate_authority.go
internal/service/acmpca/certificate_authority_test.go
website/docs/r/acmpca_certificate_authority.html.markdown

Closes #22875.
Relates #17832.

r/acmpca_certificate_authority: Deprecate `status` attribute

---

.changelog/22890.txt
internal/service/iam/policy_document_data_source.go
internal/service/iam/policy_document_data_source_test.go
website/docs/d/iam_policy_document.html.markdown

Closes #17555. (argument removal will take place with https://github.com/hashicorp/terraform-provider-aws/issues/22906)
Closes #22890.
```
n/a
```

d/aws_iam_policy_document: Deprecate source_json, override_json

---

.semgrep.yml
docs/contributing/data-handling-and-conversion.md

This PR updates references in documentation to flex functions after the Service Packages refactoring
Relates #20000
N/A

Update documentation and Semgrep rules for flex functions

---

examples/s3-cross-account-access/main.tf

Closes https://github.com/hashicorp/terraform-provider-aws/issues/22980
```
GA should validate without error
```

examples/s3-cross-account-access: migrate example to `aws_s3_bucket_policy` resource

---

website/docs/guides/version-4-upgrade.html.md
website/docs/index.html.markdown

Fixes #22825
Closes #22826
Relates #22804
Output from acceptance testing: n/a

Add metadata url, new arg docs

---

website/docs/r/lb_target_group.html.markdown

Add example and descriptions of related variables for alb to `lb_target_group` resource docs.

Update aws_lb_target_group resource docs

---

website/docs/d/cloudfront_log_delivery_canonical_user_id.html.markdown

docs/d/cloudfront_log_delivery_canonical_user_id: update example to `aws_s3_bucket_acl`

---

internal/service/wafregional/web_acl_test.go

```
--- PASS: TestAccWAFRegionalWebACLDataSource_basic (42.06s)
--- PASS: TestAccWAFRegionalWebACL_disappears …
```

tests/wafregional: update to `aws_s3_bucket_acl` resource

---

internal/service/mwaa/environment_test.go

```
--- PASS: TestAccMWAAEnvironment_airflowOptions (3509.98s)
--- PASS: TestAccMWAAEnvironment_basic …
```

tests/mwaa: update to `aws_s3_bucket_acl`

---

internal/service/codepipeline/codepipeline_test.go
internal/service/codepipeline/webhook_test.go

```
--- PASS: TestAccCodePipeline_basic (85.38s)
--- PASS: TestAccCodePipeline_disappears (33.74s)
--- PASS: …
```

tests/codepipeline: update to `aws_s3_bucket_acl`

---

internal/service/transfer/access_test.go

```
--- PASS: TestAccTransfer_serial (3842.19s)
--- PASS: TestAccTransfer_serial/Access (3842.19s)
--- PASS: …
```

tests/transfer: update to `aws_s3_bucket_acl`

---

website/docs/guides/version-4-upgrade.html.md

Description:
* this moves up the S3 bucket refactor content up the page and adds in another note for extra notice
* also provides links to the documentation for each new s3 bucket resource
```
N/A
```

version-4-upgrade: move s3 bucket refactor up and add note

---

website/docs/r/s3_bucket_intelligent_tiering_configuration.html.markdown

Fix access_tier list of valid values

docs/r/s3_bucket_intelligent_tiering: fix access_tier

---

website/docs/d/imagebuilder_image_recipe.html.markdown
website/docs/r/imagebuilder_image_recipe.html.markdown

r/aws_imagebuilder_image_recipe - fix errors in documentation

---

website/docs/guides/version-4-upgrade.html.md

https://github.com/hashicorp/terraform-provider-aws/pull/22818

docs: instance_interruption_behaviour -> instance_interruption_behavior upgrade typo

---

website/docs/d/cognito_user_pools.markdown

Tip on how to reference a pool ID via name

---

.changelog/23113.txt

Relates #23113.
New resource, not new data source.
```
...
```

Correct CHANGELOG for #23113

---

CHANGELOG.md

Plus update link for v2 CHANGELOG.
```
...
```

Add link to v3 CHANGELOG

---

website/docs/r/fsx_ontap_file_system.html.markdown

r/fsx_ontap_file_system - doc fix

---

go.mod
go.sum
internal/service/iam/user_login_profile_test.go
internal/vault/helper/pgpkeys/encrypt_decrypt.go
internal/vault/helper/pgpkeys/keybase.go
internal/vault/helper/pgpkeys/keybase_test.go

Supersedes #22603.
Closes https://github.com/hashicorp/terraform-provider-aws/issues/22602.
Closes https://github.com/hashicorp/terraform-provider-aws/issues/9769.
Closes #17823.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/12384#pullrequestreview-881045577.
```console
% go test -v …
```

Migrate from Keybase's Go OpenPGP crypto fork to ProtonMail's

---

website/docs/r/cloudfront_distribution.html.markdown

Weird wording / typo was corrected.
```
...
```

Correction to cloudfront_distribution doc

---

website/docs/r/vpc.html.markdown

Updating formatting

---

website/docs/r/cloudfront_distribution.html.markdown

Remove trailing spaces in documentation

---

website/docs/guides/version-4-upgrade.html.md

docs/upgrade guide: Clarify import IDs

---

website/docs/guides/version-4-upgrade.html.md

Update version 4 upgrade guide

---

website/docs/guides/version-4-upgrade.html.md

Fix v4 upgrade guide

---

website/docs/r/kinesis_firehose_delivery_stream.html.markdown

Looks like documentation for `dynamic_partitioning_configuration` in the Firehose resource was missed in #20769.
Relates #20769

Update Firehose documentation with dynamic_partitioning_configuration

---

.github/workflows/release.yml

Closes https://github.com/hashicorp/terraform-provider-aws/issues/23313
```
N/A
```

github/workflows/release: Update $NEW_RELEASE_LINE

---

go.mod

Fix `go.mod`

---

website/docs/r/appstream_fleet_stack_association.html.markdown
website/docs/r/appstream_image_builder.html.markdown
website/docs/r/appstream_user.html.markdown
website/docs/r/codeartifact_domain_permissions_policy.html.markdown
website/docs/r/codeartifact_repository_permissions_policy.html.markdown
website/docs/r/ecrpublic_repository_policy.html.markdown
website/docs/r/kinesisanalyticsv2_application.html.markdown
website/docs/r/organizations_delegated_administrator.html.markdown

Relates https://github.com/hashicorp/terraform-provider-aws/pull/23303.

docs: fix examples flagged by tflint

---

website/docs/guides/version-4-upgrade.html.md
website/docs/index.html.markdown

Updates provider documentation to clarify parameter precedence. Adds table for parameters with multiple sources.

documentation: Updates authentication and configuration docs for more clarity

---

.github/workflows/website.yml
.tflint.hcl
website/docs/r/s3_object_copy.html.markdown

Upgrade to v0.12.0 of `tflint-ruleset-aws`

---

internal/service/connect/enum.go

Run `go fmt`

---

website/docs/r/network_interface.markdown

Update attachment section for consistency

---

website/docs/r/s3_bucket_accelerate_configuration.html.markdown
website/docs/r/s3_bucket_acl.html.markdown
website/docs/r/s3_bucket_cors_configuration.html.markdown
website/docs/r/s3_bucket_lifecycle_configuration.html.markdown
website/docs/r/s3_bucket_logging.html.markdown
website/docs/r/s3_bucket_request_payment_configuration.html.markdown
website/docs/r/s3_bucket_server_side_encryption_configuration.html.markdown
website/docs/r/s3_bucket_versioning.html.markdown
website/docs/r/s3_bucket_website_configuration.html.markdown

Closes https://github.com/hashicorp/terraform-provider-aws/issues/23420
```
N/A
```

docs/s3: add missing details on choosing import syntax

---

internal/generate/tags/README.md

Corrects links in generator documentation

documentation: v3 Corrects generator documentation links

---

website/docs/r/s3_bucket_logging.html.markdown

Relates https://github.com/hashicorp/terraform-provider-aws/issues/23498
```
N/A
```

docs/s3_bucket_logging: clarify the type of logging and `target_bucket` input

---

website/docs/r/cloudtrail.html.markdown

docs(cloudtrail): Add `ApiErrorRateInsight` insight selector

---

website/docs/r/budgets_budget.html.markdown

Docs appear to have gotten outdated when `cost_filters` was deprecated.

Update cost filter example

---

internal/generate/tags/README.md
website/docs/r/s3_bucket_accelerate_configuration.html.markdown
website/docs/r/s3_bucket_server_side_encryption_configuration.html.markdown

Makes some changes to formatting in documentation

documentation: Random fixes

---

website/docs/r/s3_bucket_cors_configuration.html.markdown
website/docs/r/s3_bucket_lifecycle_configuration.html.markdown
website/docs/r/s3_bucket_replication_configuration.html.markdown

Closes https://github.com/hashicorp/terraform-provider-aws/issues/23612
```
N/A
```

docs/s3_bucket_*: add note about singular resource configurations

---

website/docs/r/msk_cluster.html.markdown

Fix typos in msk_cluster.html.markdown

---

.changelog/23662.txt
internal/service/kafka/configuration.go

fix(kafka): add customize diff func to handle revision change

---

website/docs/r/ec2_transit_gateway.html.markdown

Pulled straight from the AWS API docs:
https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_TransitGatewayRequestOptions.html

docs: Fix transit gateway CIDR blocks description

---

website/docs/r/cognito_identity_pool.markdown
website/docs/r/cognito_identity_pool_provider_principal_tag.markdown
website/docs/r/cognito_identity_pool_roles_attachment.markdown
website/docs/r/cognito_identity_provider.html.markdown
website/docs/r/cognito_resource_server.markdown
website/docs/r/cognito_user_pool.markdown
website/docs/r/cognito_user_pool_client.markdown
website/docs/r/cognito_user_pool_domain.markdown

This PR fixes various erorrs in `aws_cognito_*` docs.
Closes #23158

Fix various docs errors in aws_cognito_* resources

---

internal/service/cloudformation/sweep.go

Closes #23467.
Before:
```
2022/03/16 22:56:19 [DEBUG] [aws-sdk-go] DEBUG: Validate Response cloudformation/DeleteStack failed, attempt 0/5, error ValidationError: Stack [BucketStack] cannot be deleted while TerminationProtection is enabled
status code: 400, request id: 87e7ac59-bdc8-46d2-8842-80b851977d95
2022/03/16 22:56:19 [ERROR] error deleting …
```

sweeper/aws_cloudformation_stack - disable termination protection

---

.github/labeler-pr-triage.yml

Add `github_actions` label file match

---

.changelog/23719.txt

Correct CHANGELOG resource name

---

skaff/cmd/resource.go

skaff: import fix

---

website/docs/r/s3_bucket_replication_configuration.html.markdown

docs/s3_bucket_replication: add note about `rule.existing_object_replication`

---

.github/workflows/release.yml

Attempts to fix the error:
```
fatal: You are not currently on a branch.
To push the history leading to the current (detached HEAD)
state now, use
git push origin HEAD:<name-of-remote-branch>
```
```
N/A
```

github/workflows/release: fetch branch to commit changelog 

---

.changelog/20068.txt

Relates https://github.com/hashicorp/terraform-provider-aws/pull/22183.

Correct resource names in `CHANGELOG.md`

---

website/docs/r/iam_group.html.markdown

[Asana link](https://app.asana.com/0/632425409545160/1199918005391604/f)
This PR aims to clarify the behavior / use of `aws_iam_group_membership` or `aws_iam_user_group_membership` resources with `aws_iam_group` resources and warn about potential conflicts when managing membership in multiple ways (including outside …

Add note to aws_iam_group around user and group management

---

website/docs/r/neptune_cluster_endpoint.html.markdown

Correct cluster_identifier_endpoint to cluster_endpoint_identifier
Closes #22094

r/neptune_cluster_endpoint: Correct misnamed attribute

---

.changelog/23991.txt
internal/provider/provider.go
internal/service/memorydb/cluster.go
internal/service/memorydb/cluster_data_source.go
internal/service/memorydb/cluster_data_source_test.go
website/docs/d/memorydb_cluster.html.markdown

Closes https://github.com/hashicorp/terraform-provider-aws/issues/23795
```
$ make testacc PKG=memorydb TESTS=TestAccMemoryDBClusterDataSource_ ACCTEST_TIMEOUT=600m
TF_ACC=1 go test ./internal/service/memorydb/... -v -count 1 -parallel 20 …
```

d/aws_memorydb_cluster: new data source

---

website/docs/guides/version-4-upgrade.html.md

docs/guides: update Version 4 upgrade guide with S3 bucket remediation info

---

internal/service/cloudwatchlogs/subscription_filter.go
internal/service/ec2/spot_fleet_request.go
internal/service/elasticbeanstalk/application.go
internal/service/elasticsearch/domain.go
internal/service/emr/instance_group.go
internal/service/opensearch/domain.go
internal/service/rds/cluster_parameter_group.go
internal/service/redshift/parameter_group.go
internal/service/sns/topic.go

`gsed -i -E '/ForceNew:.*false,/d' internal/service/*/*.go`

switching explicit ForceNew false to implicit default

---

website/allowed-subcategories.txt
website/docs/r/account_alternate_contact.html.markdown

account: Update subcategory

---

website/allowed-subcategories.txt
website/docs/d/acm_certificate.html.markdown
website/docs/r/acm_certificate.html.markdown
website/docs/r/acm_certificate_validation.html.markdown

acm: Update subcategory

---

website/allowed-subcategories.txt
website/docs/r/autoscalingplans_scaling_plan.html.markdown

- autoscaling: Change subcategory
- autoscalingplans: Change subcategory

t autoscaling plans update subcat

---

website/docs/d/iam_saml_provider.html.markdown
website/docs/r/iam_saml_provider.html.markdown

Fix IAM subcategory

---

website/allowed-subcategories.txt
website/docs/d/cognito_user_pool_client.markdown
website/docs/d/cognito_user_pool_clients.markdown
website/docs/d/cognito_user_pool_signing_certificate.markdown
website/docs/d/cognito_user_pools.markdown
website/docs/r/cognito_identity_pool.markdown
website/docs/r/cognito_identity_pool_provider_principal_tag.markdown
website/docs/r/cognito_identity_pool_roles_attachment.markdown
website/docs/r/cognito_identity_provider.html.markdown
website/docs/r/cognito_resource_server.markdown
website/docs/r/cognito_user.html.markdown
website/docs/r/cognito_user_group.html.markdown
website/docs/r/cognito_user_in_group.html.markdown
website/docs/r/cognito_user_pool.markdown
website/docs/r/cognito_user_pool_client.markdown
website/docs/r/cognito_user_pool_domain.markdown
website/docs/r/cognito_user_pool_ui_customization.html.markdown

cognito: Split docs into subcategories

---

website/docs/r/lambda_permission.html.markdown

docs(lambda_permission): another typo fix

---

.changelog/24170.txt
internal/service/grafana/workspace.go

r/grafana_workspace - validations

---

.changelog/24237.txt
internal/acctest/acctest.go
internal/service/ecs/task_definition_test.go
internal/service/emr/cluster.go
internal/service/emr/cluster_test.go
internal/service/emr/errors.go
internal/service/iam/policy_document_data_source_test.go
internal/service/lambda/function_url_test.go
internal/service/rds/cluster_activity_stream_test.go
internal/service/route53/health_check_test.go

r/emr_cluster - Skip error on UnknownOperationException

---

infrastructure/repository/labels-workflow.tf

This PR adds a GitHub label for issues/PRs related to the `skaff` tool.

Add label for skaff

---

.github/labeler-issue-triage.yml
.github/labeler-pr-triage.yml
infrastructure/repository/labels-workflow.tf
skaff/resource/resourcetest.tmpl

skaff: Improvements

---

.github/labeler-pr-triage.yml
skaff/go.mod
skaff/go.sum
skaff/resource/resource.tmpl

skaff: Add TF resource import

---

skaff/README.md

skaff: Fix readme

---

skaff/resource/resource.tmpl

Skaff/update waiter template to use WaitForStateContext

---

.changelog/24264.txt

Relates https://github.com/hashicorp/terraform-provider-aws/pull/24264.
```
...
```

Correct CHANGELOG entry

---

.changelog/24312.txt
internal/service/firehose/delivery_stream.go

:bug: change StringLen for parameter value

---

go.mod
go.sum
internal/conns/conns.go
internal/sweep/sweep.go

Suppresses logging for sweepers
Closes #22922

Sets `SuppressDebugLog` for sweepers

---

website/docs/r/s3_bucket.html.markdown

r/s3_bucket: add valid value for object_lock_enabled

---

website/docs/r/kinesis_firehose_delivery_stream.html.markdown

Closes #22623 
**I'm unsure how to test a documentation update**
I am able to create and use the following resource with AWS provider 4.8.0.
```
resource "aws_kinesis_firehose_delivery_stream" "s3_partitioned_stream" {
name        = "${local.naming_prefix}-2"
destination = "extended_s3"
kinesis_source_configuration { …
```

Firehose: Documentation update for dynamic partitioning

---

.semgrep.yml
GNUmakefile
internal/generate/allowsubcats/generate.go
internal/generate/allowsubcats/main.go
website/allowed-subcategories.txt

website: Generate allowed subcats

---

internal/generate/allowsubcats/main.go
internal/generate/awsclient/main.go
internal/generate/checknames/generate.go
internal/generate/checknames/main.go
internal/generate/clientconfig/main.go

generate: Add name data checking

---

docs/contributing/running-and-writing-acceptance-tests.md
internal/sweep/sweep_test.go

Fix dataexchange sweeper + contribution sweeper docs change

---

.changelog/24385.txt
internal/service/mq/broker.go
internal/service/mq/broker_test.go
internal/service/mq/sweep.go
website/docs/r/mq_broker.html.markdown

Closes #20241
Closes #19067
Closes #18365
```
$ make testacc TESTS=TestAccMQBroker_AllFields_customVPC PKG=mq
--- PASS: TestAccMQBroker_AllFields_customVPC (1791.06s)
```

r/mq_broker - make maint window updatable + sweeper changes

---

website/docs/r/vpn_connection.html.markdown
website/docs/r/vpn_connection_route.html.markdown

Fix invalid subcategory of some documents for Site to Site VPN

Fix invalid subcategory for site-to-site VPN docs

---

.changelog/24394.txt
internal/provider/provider.go
internal/service/mq/broker_instance_type_offerings_data_source.go
internal/service/mq/broker_instance_type_offerings_data_source_test.go
website/docs/d/mq_broker_instance_type_offerings.markdown

Supersedes #18746
```
$ make testacc TESTS=TestAccMQBrokeInstanceTypeOfferingsrDataSource_basic PKG=mq
--- PASS: TestAccMQBrokeInstanceTypeOfferingsrDataSource_basic (23.93s)
```
Thanks to [bruceharrison1984](https://github.com/bruceharrison1984) for doing the heavy lifting, i mostly refactored to new struct.

d/mq_broker_instance_type_offerings - new datasource

---

names/README.md

docs/names: Fix

---

.github/workflows/stale.yml

Closes #22447
Relates #22515 
Output from acceptance testing: n/a, Action tweak
Again bumping the number of operations to try to ensure a complete processing of issues/PRs.

Increase number of operations for stale workflow

---

internal/service/athena/database.go
internal/service/athena/database_test.go
internal/service/athena/named_query_test.go
internal/service/athena/workgroup.go
internal/service/athena/workgroup_test.go

athena: Remove service from funcs

---

internal/service/amplify/app.go
internal/service/amplify/domain_association.go

amplify: Remove service from funcs

---

website/docs/r/ssm_maintenance_window_task.html.markdown

Relates #24506.
This PR improves an argument description to prevent from raising confusion as in the mentioned issue.

r/aws_ssm_maintenance_window_task - improve documentation of service_role_arn argument

---

internal/service/autoscalingplans/scaling_plan.go
internal/service/autoscalingplans/scaling_plan_test.go

autoscalingplans: Remove service from funcs

---

internal/service/ecrpublic/repository.go

ecrpublic: Remove service from funcs

---

internal/service/ecr/lifecycle_policy_test.go
internal/service/ecr/registry_scanning_configuration.go
internal/service/ecr/replication_configuration.go
internal/service/ecr/repository.go
internal/service/ecr/repository_data_source.go

ecr: Remove service from funcs

---

internal/service/dynamodb/flex.go
internal/service/dynamodb/global_table_test.go
internal/service/dynamodb/kinesis_streaming_destination.go
internal/service/dynamodb/kinesis_streaming_destination_test.go
internal/service/dynamodb/status.go
internal/service/dynamodb/table.go
internal/service/dynamodb/table_data_source.go
internal/service/dynamodb/table_item.go
internal/service/dynamodb/table_migrate.go
internal/service/dynamodb/table_test.go
internal/service/dynamodb/tag_test.go
internal/service/dynamodb/wait.go

dynamodb: Remove service from funcs

---

internal/service/eks/addon_test.go
internal/service/eks/cluster.go
internal/service/eks/cluster_data_source.go
internal/service/eks/fargate_profile.go
internal/service/eks/identity_provider_config.go
internal/service/eks/node_group.go
internal/service/eks/node_group_data_source.go
internal/service/eks/node_group_test.go

eks: Remove service from funcs

---

internal/service/emr/cluster.go
internal/service/emr/cluster_test.go
internal/service/emr/instance_group.go
internal/service/emr/managed_scaling_policy.go
internal/service/emr/managed_scaling_policy_test.go
internal/service/emr/security_configuration_test.go
internal/service/emr/studio_session_mapping_test.go
internal/service/emr/studio_test.go

emr: Remove service from funcs

---

internal/service/fms/acc_test.go
internal/service/fms/admin_account.go
internal/service/fms/admin_account_test.go
internal/service/fms/policy.go
internal/service/fms/policy_test.go

fms: Remove service from funcs

---

internal/service/glue/catalog_database.go
internal/service/glue/catalog_database_test.go
internal/service/glue/catalog_table.go
internal/service/glue/catalog_table_test.go
internal/service/glue/classifier.go
internal/service/glue/connection.go
internal/service/glue/connection_data_source.go
internal/service/glue/crawler.go
internal/service/glue/crawler_test.go
internal/service/glue/dev_endpoint.go
internal/service/glue/dev_endpoint_test.go
internal/service/glue/job.go
internal/service/glue/job_test.go
internal/service/glue/ml_transform.go
internal/service/glue/ml_transform_test.go
internal/service/glue/partition.go
internal/service/glue/partition_index.go
internal/service/glue/partition_index_test.go
internal/service/glue/partition_test.go
internal/service/glue/script_data_source.go
internal/service/glue/security_configuration.go
internal/service/glue/status.go
internal/service/glue/trigger.go
internal/service/glue/trigger_test.go
internal/service/glue/user_defined_function_test.go
internal/service/glue/wait.go

glue: Remove service from funcs

---

internal/service/neptune/cluster.go
internal/service/neptune/cluster_instance_test.go
internal/service/neptune/cluster_parameter_group.go
internal/service/neptune/cluster_snapshot_test.go
internal/service/neptune/subnet_group_test.go

neptune: Remove service from funcs

---

internal/service/mq/broker.go
internal/service/mq/configuration_test.go

mq: Remove service from funcs

---

internal/service/fsx/backup_test.go
internal/service/fsx/data_repository_association_test.go
internal/service/fsx/lustre_file_system.go
internal/service/fsx/lustre_file_system_test.go
internal/service/fsx/ontap_file_system.go
internal/service/fsx/ontap_file_system_test.go
internal/service/fsx/ontap_storage_virtual_machine.go
internal/service/fsx/ontap_storage_virtual_machine_test.go
internal/service/fsx/ontap_volume.go
internal/service/fsx/ontap_volume_test.go
internal/service/fsx/openzfs_file_system.go
internal/service/fsx/openzfs_file_system_test.go
internal/service/fsx/openzfs_snapshot_test.go
internal/service/fsx/openzfs_volume.go
internal/service/fsx/openzfs_volume_test.go
internal/service/fsx/windows_file_system.go
internal/service/fsx/windows_file_system_test.go

fsx: Remove service from funcs

---

internal/service/pinpoint/app.go

pinpoint: Remove service from funcs

---

internal/service/xray/encryption_config_test.go
internal/service/xray/group_test.go
internal/service/xray/sampling_rule_test.go

xray: Remove service from funcs

---

internal/service/timestreamwrite/table.go

timestreamwrite: Remove service from funcs

---

internal/service/transfer/access.go
internal/service/transfer/server.go
internal/service/transfer/server_test.go
internal/service/transfer/transfer_test.go
internal/service/transfer/user.go

transfer: Remove service from funcs

---

internal/service/waf/acc_test.go
internal/service/waf/byte_match_set.go
internal/service/waf/ipset.go
internal/service/waf/rate_based_rule.go
internal/service/waf/regex_match_set_test.go
internal/service/waf/regex_pattern_set.go
internal/service/waf/rule.go
internal/service/waf/rule_group.go
internal/service/waf/sql_injection_match_set.go
internal/service/waf/web_acl.go
internal/service/waf/web_acl_test.go
internal/service/wafregional/byte_match_set.go
internal/service/wafregional/geo_match_set_test.go
internal/service/wafregional/ipset.go
internal/service/wafregional/rate_based_rule.go
internal/service/wafregional/rate_based_rule_test.go
internal/service/wafregional/regex_match_set_test.go
internal/service/wafregional/regex_pattern_set.go
internal/service/wafregional/rule.go
internal/service/wafregional/rule_group.go
internal/service/wafregional/rule_test.go
internal/service/wafregional/sql_injection_match_set.go
internal/service/wafregional/web_acl.go
internal/service/wafregional/web_acl_association_test.go
internal/service/wafregional/web_acl_test.go
internal/service/wafv2/web_acl.go

waf: Remove service from funcs

---

internal/service/synthetics/canary.go
internal/service/timestreamwrite/table.go

- timestreamwrite: Remove service from funcs
- synthetics: Remove service from funcs

synthetics: Remove service from funcs

---

website/docs/index.html.markdown

Adds documentation example for assume role with web identity.
Relates #24441
N/A

docs: Add example for assume role with web identity

---

website/docs/r/cloudtrail.html.markdown

r/cloudtrail: correct example to log all S3 object events

---

website/docs/r/apprunner_service.html.markdown

Closes #24531
The example provided in the `aws_apprunner_service` docs led to the following error when run. This update corrects the configuration to be functional.
```shell
aws_apprunner_service.example: Creating...
╷
│ Error: error creating App Runner Service (example): InvalidRequestException: App Runner doesn't …
```

Update aws_apprunner_service example to be functional

---

ROADMAP.md
docs/roadmaps/2022_February_to_April.md

Updating the roadmap and archiving last quarter's.

ROADMAP: MAY - JULY 2022

---

docs/roadmaps/2022_February_to_April.md

Relates #24475.
Fixes:
```
docs/roadmaps/2022_February_to_April.md:15:47 MD009/no-trailing-spaces Trailing spaces [Expected: 0 or 2; Actual: 1]
docs/roadmaps/2022_February_to_April.md:16:18 MD009/no-trailing-spaces Trailing spaces [Expected: 0 or 2; Actual: 1]
docs/roadmaps/2022_February_to_April.md:117:69 MD009/no-trailing-spaces Trailing spaces [Expected: …
```

Fix `markdown-lint` errors

---

skaff/go.sum

Relates https://github.com/hashicorp/terraform-provider-aws/pull/24717.

Run `go mod tidy` in `skaff`

---

.github/workflows/release.yml
.goreleaser.yml
.release/release-metadata.hcl

These are the necessary components that `terraform-provider-aws` needs to onboard to Releases API. 
edit: rel-eng will merge this PR when the time is ready.

[DO NOT MERGE] RelAPI Onboarding 

---

internal/service/ds/conditional_forwarder.go
internal/service/ds/conditional_forwarder_test.go
internal/service/ds/directory.go
internal/service/ds/directory_data_source_test.go
internal/service/ds/directory_test.go
internal/service/ds/log_subscription_test.go

- ds: Remove service from funcs
- ds: Fix func name

ds: Remove service from funcs

---

internal/service/dax/cluster.go
internal/service/dax/flex.go
internal/service/dax/parameter_group.go
internal/service/dax/parameter_group_test.go
internal/service/dax/subnet_group_test.go

dax: Remove service from funcs

---

website/docs/r/connect_instance.html.markdown

Documentation change only.
Closes #24706.

Fix to warning regarding instance creation

---

internal/service/sns/platform_application_test.go
internal/service/sns/topic_subscription_test.go
internal/service/ssm/document.go
internal/service/ssm/document_test.go
internal/service/ssm/parameter.go
internal/service/ssoadmin/permission_set.go
internal/service/ssoadmin/wait.go

sns,ssm,ssoadmin: Clean up const, func names

---

internal/service/rds/cluster_parameter_group.go
internal/service/rds/cluster_snapshot.go
internal/service/rds/instance_role_association.go
internal/service/rds/snapshot_copy_test.go
internal/service/redshift/service_account_data_source_test.go

r: Clean up func, var, const names

---

internal/service/sagemaker/prebuilt_ecr_image_data_source.go
internal/service/sagemaker/prebuilt_ecr_image_data_source_test.go
internal/service/sagemaker/status.go
internal/service/sagemaker/wait.go
internal/service/securityhub/member.go
internal/service/servicequotas/acc_test.go
internal/service/servicequotas/service_quota_test.go

sa-se: Clean up const, func names

---

internal/service/elasticache/sweep.go
website/docs/r/s3_bucket.html.markdown

Minor replication typo fixes (docs/aws_s3_bucket and elasticache/sweep)

---

website/docs/r/rds_cluster.html.markdown

r/aws_rds_cluster: Docs update for serverless v2

---

internal/service/macie2/invitation_accepter_test.go
internal/service/macie2/member_test.go
internal/service/meta/billing_service_account_data_source_test.go
internal/service/meta/partition_data_source_test.go
internal/service/mq/broker_data_source.go
internal/service/mq/broker_instance_type_offerings_data_source.go
internal/service/mq/broker_test.go
internal/service/neptune/cluster_parameter_group.go
internal/service/networkmanager/device.go
internal/service/networkmanager/device_test.go

mn: Remove aws from names

---

internal/service/s3control/object_lambda_access_point.go
internal/service/ssm/document_data_source_test.go
internal/service/ssm/parameter_test.go
internal/service/storagegateway/enum.go
internal/service/sts/caller_identity_data_source_test.go
internal/service/synthetics/canary.go

s: Remove aws from names

---

website/docs/r/location_map.html.markdown

Applied the correct heading level for the section about `configuration` block details. Also moved it under **Argument Reference** from **Attribute Reference**. Moreover, ordered the attributes alphabetically.

r/aws_location_map - minor docs fixes

---

internal/service/ecr/pull_through_cache_rule.go
internal/service/ecr/pull_through_cache_rule_test.go
internal/service/ecr/repository_data_source_test.go
internal/service/ecr/repository_test.go
internal/service/ecs/account_setting_default_test.go
internal/service/ecs/cluster.go
internal/service/ecs/cluster_capacity_providers.go
internal/service/ecs/wait.go
internal/service/eks/cluster_auth_data_source_test.go
internal/service/elasticache/cluster.go
internal/service/elasticache/replication_group.go
internal/service/elasticbeanstalk/hosted_zone_data_source_test.go
internal/service/elasticbeanstalk/solution_stack_data_source_test.go

ecr-ela: AWS in names

---

.github/workflows/terraform_provider.yml

Relates https://github.com/hashicorp/terraform-provider-aws/pull/24788.
This reverts commit 09b2289eb7b44e4ff30fd35c0ca6490f8d24a14e.
Spotted [in the wild](https://github.com/hashicorp/terraform-provider-aws/runs/6490582472?check_suite_focus=true):
```
Run tj-actions/changed-files@v20
Run # "Set base sha..."
Run # "Calculating the previous and current …
```

Revert `tj-actions/changed-files` to v20

---

.changelog/23059.txt

Add CHANGELOG entry for #23059

---

internal/service/iot/topic_rule.go
internal/service/s3/bucket_object.go
internal/service/s3/object.go
internal/service/s3/object_copy.go
internal/service/timestreamwrite/table_test.go
internal/service/transfer/workflow.go
internal/service/waf/sql_injection_match_set.go
internal/service/waf/xss_match_set.go
internal/service/wafregional/sql_injection_match_set.go
internal/service/wafregional/xss_match_set.go
internal/service/wafv2/flex.go
internal/service/wafv2/web_acl.go
internal/service/workspaces/ip_group.go
internal/tags/key_value_tags.go
internal/tags/key_value_tags_test.go

t-w,tags: Fix func caps

---

.semgrep-service-name.yml
internal/service/timestreamwrite/database_test.go
internal/service/timestreamwrite/table_test.go
internal/service/transfer/access_test.go
internal/service/transfer/server_data_source_test.go
internal/service/transfer/server_test.go
internal/service/transfer/user_test.go
internal/service/transfer/workflow_test.go

t: Fix configs

---

docs/contributing/prioritization.md

This quick PR updates some of the headers from H3 to H4, since they're nested under the `### Internal` header.

Correct header levels on prioritization guide

---

.release/release-metadata.hcl

Relates #23751 
Relates https://github.com/hashicorp/terraform-provider-aws/runs/6515664728?check_suite_focus=true
Closes https://github.com/hashicorp/terraform-provider-aws/issues/24901.
```
N/A
```

Add missing file for releases API

---

website/docs/guides/using-aws-with-awscc-provider.html.md

Relates https://github.com/hashicorp/terraform-provider-awscc/issues/509.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/24368.

docs/guides: Work around current limitations with the `awscc_networkmanager_core_network` resource

---

website/docs/guides/using-aws-with-awscc-provider.html.md

update required tf core version

---

internal/service/dynamodb/contributor_insights_test.go
internal/service/dynamodb/find.go
internal/service/dynamodb/kinesis_streaming_destination.go
internal/service/dynamodb/kinesis_streaming_destination_test.go
internal/service/dynamodb/status.go
internal/service/dynamodb/table.go
internal/service/dynamodb/table_test.go

dynamodb: Remove service name

---

.semgrep-service-name1.yml
internal/service/ds/conditional_forwarder_test.go
internal/service/ds/directory_data_source_test.go
internal/service/ds/directory_test.go
internal/service/ds/log_subscription_test.go

ds: Remove service name

---

.semgrep-service-name1.yml
internal/service/docdb/cluster_parameter_group.go

docdb: Remove service name

---

.semgrep-service-name0.yml
.semgrep-service-name1.yml
internal/service/amplify/app_test.go
internal/service/deploy/app_test.go
internal/service/deploy/deployment_config_test.go
internal/service/deploy/deployment_group.go
internal/service/deploy/deployment_group_test.go

deploy: Fix service name

---

.semgrep-service-name0.yml
.semgrep-service-name1.yml
internal/service/ce/cost_category.go
internal/service/ce/cost_category_data_source.go

ce: Fix service names

---

.semgrep-service-name1.yml
internal/service/dms/replication_task_test.go

dms: Remove service name

---

.semgrep-service-name0.yml
internal/acctest/acctest.go
internal/acctest/provider_test.go
internal/conns/awsclient_test.go
internal/service/apigatewayv2/integration_test.go
internal/service/appconfig/configuration_profile.go
internal/service/appconfig/enum.go
internal/service/autoscaling/group_test.go
internal/service/cloudtrail/service_account_data_source_test.go
internal/service/codebuild/project.go
internal/service/codestarnotifications/notification_rule.go
internal/service/configservice/config_rule_test.go
internal/service/connect/contact_flow.go
internal/service/connect/contact_flow_module.go
internal/service/elbv2/hosted_zone_id_data_source_test.go

aws: Remove from names

---

.semgrep-service-name0.yml
internal/service/neptune/cluster.go
internal/service/route53/traffic_policy_document_model.go
internal/service/route53resolver/status.go

caps0: Fix const,var names

---

.semgrep-service-name0.yml
internal/service/connect/bot_association_data_source_test.go
internal/service/connect/bot_association_test.go
internal/service/connect/contact_flow_data_source_test.go
internal/service/connect/contact_flow_module_data_source_test.go
internal/service/connect/contact_flow_test.go
internal/service/connect/hours_of_operation_data_source_test.go
internal/service/connect/hours_of_operation_test.go
internal/service/connect/instance_data_source_test.go
internal/service/connect/instance_test.go
internal/service/connect/lambda_function_association_data_source_test.go
internal/service/connect/lambda_function_association_test.go
internal/service/connect/prompt_data_source_test.go
internal/service/connect/queue_data_source_test.go
internal/service/connect/queue_test.go
internal/service/connect/quick_connect_data_source_test.go
internal/service/connect/quick_connect_test.go
internal/service/connect/routing_profile_data_source_test.go
internal/service/connect/routing_profile_test.go
internal/service/connect/security_profile_data_source_test.go
internal/service/connect/security_profile_test.go
internal/service/connect/user_hierarchy_group_test.go
internal/service/connect/user_hierarchy_structure_data_source_test.go
internal/service/connect/user_hierarchy_structure_test.go

- connect: Fix test configs names
- connect: Fix configs
```
...
```

connect: Fix test configs names

---

.changelog/25096.txt
internal/provider/provider.go
internal/service/redshift/cluster.go
internal/service/redshift/cluster_iam_roles.go
internal/service/redshift/cluster_iam_roles_test.go
website/docs/r/redshift_cluster.html.markdown
website/docs/r/redshift_cluster_iam_roles.html.markdown

Closes #13570
```
$ make testacc TESTS=TestAccRedshiftClusterIamRoles_ PKG=redshift
--- PASS: TestAccRedshiftClusterIamRoles_basic (454.97s)
```

r/redshift_cluster_iam_roles - new resource

---

.changelog/25080.txt
internal/service/dms/endpoint.go
internal/service/dms/endpoint_test.go
website/docs/r/dms_endpoint.html.markdown

Relates OR Closes #24911 
Sorry, I'm not able to run tests, may I ask you to run them, please?
```
$ make testacc TESTS=TestAccDMSEndpoint_Redshift PKG=dms
$ make testacc TESTS=TestAccDMSEndpoint PKG=dms
...
```

r/aws_dms_endpoint: Secrets manager secret for `aws_dms_endpoint` with `engine_name = redshift`

---

.changelog/25109.txt
internal/provider/provider.go
internal/service/acmpca/find.go
internal/service/acmpca/policy.go
internal/service/acmpca/policy_test.go
website/docs/r/acmpca_policy.html.markdown

Closes #14784
```
$ make testacc TESTS=TestAccACMPCAPolicy PKG=acmpca
TF_ACC=1 go test ./internal/service/acmpca/... -v -count 1 -parallel 20 -run='TestAccACMPCAPolicy'  -timeout 180m
=== RUN   TestAccACMPCAPolicy
=== PAUSE TestAccACMPCAPolicy
=== CONT …
```

r/aws_acmpca_policy - new resource 

---

CHANGELOG.md

Next planned release is `v4.17.1`

---

.github/workflows/release.yml

Closes https://github.com/hashicorp/terraform-provider-aws/issues/25167.

Increase `goreleaser` timeout to 3 hours

---

website/docs/d/elasticache_user.html.markdown

Fix aws_elasticache_user doc

---

skaff/README.md

skaff: add usage documentation

---

website/docs/r/cloudwatch_event_target.html.markdown

Documentation: r/aws_cloudwatch_event_target example

---

website/docs/guides/version-4-upgrade.html.md

Documentation: remove duplicate word
```
...
```

Documentation: remove duplicate word

---

.semgrep-service-name0.yml
internal/service/acm/certificate.go
internal/service/acm/certificate_data_source.go
internal/service/acm/certificate_data_source_test.go
internal/service/acm/certificate_test.go
internal/service/acm/certificate_validation_test.go

- acm: Fix naming
- acm: Naming fixes
```
...
```

acm: Naming fixes

---

.semgrep-service-name0.yml
internal/service/emr/cluster.go
internal/service/emr/cluster_test.go
internal/service/emr/instance_fleet_test.go
internal/service/emr/instance_group.go
internal/service/emr/instance_group_test.go
internal/service/emr/managed_scaling_policy_test.go
internal/service/emr/release_labels_data_source_test.go

- emr: Fix naming
- emr: Fix naming in tests
```
...
```

emr: Fix naming

---

.semgrep-service-name0.yml
internal/service/kafka/broker_nodes_data_source_test.go
internal/service/kafka/cluster.go
internal/service/kafka/cluster_data_source_test.go
internal/service/kafka/cluster_test.go
internal/service/kafka/configuration_data_source_test.go
internal/service/kafka/configuration_test.go
internal/service/kafka/kafka_version_data_source_test.go
internal/service/kafka/scram_secret_association_test.go

- kafka: Fix caps
- kafka: Fix func naming
```
...
```

kafka: Fix func naming

---

.semgrep-service-name0.yml
internal/service/athena/data_catalog_test.go
internal/service/athena/database.go
internal/service/athena/database_test.go
internal/service/athena/named_query_test.go
internal/service/athena/workgroup.go
internal/service/athena/workgroup_test.go

- athena: Fix caps in naming
- athena: Fix func naming
```
...
```

athena: Fix func naming

---

.semgrep-service-name0.yml
internal/service/devicefarm/device_pool.go
internal/service/devicefarm/device_pool_test.go
internal/service/devicefarm/find.go
internal/service/devicefarm/instance_profile.go
internal/service/devicefarm/instance_profile_test.go
internal/service/devicefarm/network_profile.go
internal/service/devicefarm/network_profile_test.go
internal/service/devicefarm/project.go
internal/service/devicefarm/project_test.go
internal/service/devicefarm/test_grid_project.go
internal/service/devicefarm/test_grid_project_test.go
internal/service/devicefarm/upload.go
internal/service/devicefarm/upload_test.go

devicefarm: Fix func names

---

.semgrep-service-name1.yml
internal/service/connect/bot_association.go
internal/service/connect/contact_flow.go
internal/service/connect/instance.go
internal/service/connect/quick_connect_data_source_test.go
internal/service/connect/routing_profile_data_source.go
internal/service/connect/security_profile_data_source.go
internal/service/connect/user_hierarchy_group.go
internal/service/connect/user_hierarchy_structure_data_source.go
internal/service/connect/wait.go
internal/service/cur/acc_test.go
internal/service/cur/report_definition_data_source_test.go
internal/service/cur/report_definition_test.go
internal/service/dynamodb/table.go
internal/service/dynamodb/table_data_source.go
internal/service/dynamodb/table_item_test.go

ci/semgrep/a-c: Remove exclusions

---

.semgrep-service-name0.yml
internal/service/account/alternate_contact_test.go
internal/service/account/find.go
internal/service/amp/alert_manager_definition_test.go
internal/service/amp/rule_group_namespace_test.go
internal/service/amp/workspace_test.go
internal/service/apigateway/vpc_link.go
internal/service/apigateway/wait.go
internal/service/apigatewayv2/export_data_source_test.go
internal/service/apigatewayv2/stage.go
internal/service/appautoscaling/policy.go
internal/service/appautoscaling/policy_test.go
internal/service/appautoscaling/scheduled_action.go
internal/service/appautoscaling/scheduled_action_test.go
internal/service/appintegrations/event_integration_test.go

ci/semgrep/a: Remove exclusions

---

.semgrep-caps-aws-config.yml
.semgrep-service-name0.yml
internal/service/backup/consts.go
internal/service/backup/find.go
internal/service/backup/framework_data_source_test.go
internal/service/backup/framework_test.go
internal/service/backup/global_settings_test.go
internal/service/backup/plan.go
internal/service/backup/plan_test.go
internal/service/backup/region_settings_test.go
internal/service/backup/report_plan_data_source_test.go
internal/service/backup/report_plan_test.go
internal/service/backup/selection.go
internal/service/backup/selection_test.go
internal/service/backup/vault.go
internal/service/backup/vault_lock_configuration.go
internal/service/backup/vault_lock_configuration_test.go
internal/service/backup/vault_notifications_test.go
internal/service/backup/vault_policy.go
internal/service/backup/vault_policy_test.go
internal/service/backup/vault_test.go

ci/semgrep/backup: Remove exclusion

---

.semgrep-caps-aws-config.yml
.semgrep-service-name0.yml
internal/service/cloud9/environment_ec2_test.go
internal/service/cloud9/environment_membership_test.go

ci/cloud9: Remove exclusions

---

.semgrep-service-name0.yml
internal/service/budgets/budget.go
internal/service/budgets/sweep.go
internal/service/cloudfront/distribution.go
internal/service/cloudfront/distribution_configuration_structure.go
internal/service/cloudfront/distribution_configuration_structure_test.go
internal/service/cloudfront/distribution_data_source.go
internal/service/cloudfront/log_delivery_canonical_user_id_data_source.go
internal/service/cloudhsmv2/sweep.go
internal/service/cloudtrail/cloudtrail.go
internal/service/cloudtrail/cloudtrail_test.go
internal/service/cloudtrail/consts.go
internal/service/cloudtrail/event_data_store_test.go
internal/service/codebuild/project.go
internal/service/codebuild/project_test.go
internal/service/codepipeline/codepipeline.go
internal/service/codepipeline/consts.go
internal/service/codepipeline/webhook_test.go
internal/service/cognitoidentity/pool_test.go
internal/service/cognitoidp/user_in_group_test.go

ci/semgrep/b-c: Remove exclusions

---

.semgrep-caps-aws-config.yml
internal/service/appmesh/mesh_data_source_test.go
internal/service/appmesh/virtual_service_data_source_test.go
internal/service/codeartifact/authorization_token_data_source_test.go
internal/service/codeartifact/domain_permissions_policy_test.go
internal/service/codeartifact/domain_test.go
internal/service/codeartifact/repository_endpoint_data_source_test.go
internal/service/codeartifact/repository_permissions_policy_test.go
internal/service/codeartifact/repository_test.go
internal/service/codecommit/approval_rule_template_data_source_test.go
internal/service/codecommit/repository_data_source_test.go
internal/service/ecr/authorization_token_data_source_test.go
internal/service/ecr/image_data_source_test.go
internal/service/ecr/repository_data_source_test.go
internal/service/ecrpublic/authorization_token_data_source_test.go
internal/service/ecs/cluster_data_source_test.go
internal/service/ecs/container_definition_data_source_test.go
internal/service/ecs/service_data_source_test.go
internal/service/ecs/task_definition_data_source_test.go
internal/service/elasticbeanstalk/hosted_zone_data_source_test.go
internal/service/events/permission_test.go
internal/service/kinesis/stream_data_source_test.go
internal/service/meta/service_data_source_test.go
internal/service/rds/cluster_snapshot_data_source_test.go

ci/semgrep/tests: Remove exclusions

---

.semgrep-caps-aws-config.yml
internal/service/dynamodb/contributor_insights_test.go
internal/service/dynamodb/kinesis_streaming_destination_test.go
internal/service/dynamodb/table_data_source_test.go
internal/service/dynamodb/table_item_test.go
internal/service/dynamodb/table_test.go

- dynamodb: Fix test configs names
- dynamodb: Fix caps
```
...
```

dynamodb: Fix test configs names

---

.semgrep-configs.yml
internal/generate/servicesemgrep/configs.tmpl

ci/semgrep/codecommit: Remove exclusion

---

.semgrep-configs.yml
internal/generate/servicesemgrep/configs.tmpl
internal/service/kinesisanalyticsv2/application_snapshot_test.go
internal/service/kinesisanalyticsv2/application_test.go

- ci/semgrep/kinesisanalyticsv2: Remove exclusion
- ci/semgrep/kinesisanalyticsv2: Fix config
```
...
```

ci/semgrep/kinesisanalyticsv2: Remove exclusion

---

.semgrep-configs.yml
internal/generate/servicesemgrep/configs.tmpl
internal/provider/provider.go
internal/service/grafana/license_association_test.go
internal/service/grafana/role_association_test.go
internal/service/grafana/status.go
internal/service/grafana/wait.go
internal/service/grafana/workspace_data_source_test.go
internal/service/grafana/workspace_saml_configuration.go
internal/service/grafana/workspace_saml_configuration_test.go
internal/service/grafana/workspace_test.go

- ci/semgrep/grafana: Remove exclusion
- ci/semgrep/grafana: Fix caps
```
...
```

ci/semgrep/grafana: Remove exclusion

---

.semgrep-configs.yml
internal/generate/servicesemgrep/configs.tmpl
internal/service/datasync/agent_test.go
internal/service/datasync/location_efs_test.go
internal/service/datasync/location_fsx_lustre_file_system_test.go
internal/service/datasync/location_fsx_openzfs_file_system_test.go
internal/service/datasync/location_fsx_windows_file_system_test.go
internal/service/datasync/location_hdfs_test.go
internal/service/datasync/location_nfs_test.go
internal/service/datasync/location_s3_test.go
internal/service/datasync/location_smb_test.go
internal/service/datasync/task_test.go

- ci/semgrep/datasync: Remove exclusion
- ci/semgrep/datasync: Remove exclusion
```
...
```

ci/semgrep/datasync: Remove exclusion

---

.semgrep-configs.yml
internal/generate/servicesemgrep/configs.tmpl

ci/semgrep/account,appmesh: Remove exclusion

---

.semgrep-configs.yml
internal/generate/servicesemgrep/configs.tmpl
internal/service/events/api_destination_test.go
internal/service/events/archive_test.go
internal/service/events/bus_policy_test.go
internal/service/events/bus_test.go
internal/service/events/connection_data_source_test.go
internal/service/events/permission_test.go
internal/service/events/rule_test.go
internal/service/events/source_data_source_test.go
internal/service/events/target_test.go

- ci/semgrep/events: Remove exclusion
- ci/semgrep/events: Remove exclusion
```
...
```

ci/semgrep/events: Remove exclusion

---

.semgrep-configs.yml
internal/generate/servicesemgrep/configs.tmpl
internal/service/resourcegroupstaggingapi/resources_data_source_test.go

- ci/semgrep/resourcegroupstaggingapi: Remove exclusion
- ci/semgrep/resourcegroupstaggingapi: Remove exclusion
```
...
```

ci/semgrep/resourcegroupstaggingapi: Remove exclusion

---

.semgrep-configs.yml
internal/generate/servicesemgrep/configs.tmpl
internal/service/guardduty/detector_data_source_test.go
internal/service/guardduty/detector_test.go

- ci/semgrep/guardduty: Remove exclusion
- ci/semgrep/guardduty: Remove exclusion
```
...
```

ci/semgrep/guardduty: Remove exclusion

---

.semgrep-configs.yml
internal/generate/servicesemgrep/configs.tmpl
internal/service/resourcegroups/group_test.go

- ci/semgrep/resourcegroups: Remove exclusion
- ci/semgrep/resourcegroups: Remove exclusion
```
...
```

ci/semgrep/resourcegroups: Remove exclusion
