hashicorp/terraform-provider-aws

website/docs/r/cloudwatch_metric_alarm.html.markdown
Add the missing `account_id` in the documentation for `aws_cloudwatch_metric_alarm`. It was added in #20541
Relates to #20541
=> docs: Add missing account_id for CloudWatch cross account alarm

website/docs/r/db_option_group.html.markdown
> website/docs/r/db_option_group.html.markdown: error checking file contents: import section code block text should contain resource name: aws_db_option_group
```
...
```
=> Fix `tfproviderdocs` error

website/docs/r/security_group.html.markdown
The documentation reads a bit confusing as the section says "The following arguments are optional:" yet the field is marked as "required", and it fails if I comment the `protocol` out:
```
│ Error: Missing required argument
│
│   with aws_security_group.public_ingress,
│   on ingress.tf line 83, in resource "aws_security_group" "public_ingress":
│   83: …
```
=> Move protocol to required section in SG doc

website/docs/r/cloudwatch_metric_alarm.html.markdown
CloudWatch metric alarm supports more statistics than `SampleCount`, `Average`, `Sum`, `Minimum`, `Maximum` when using MetricStat. Keeping these values in documentation may confuse users thinking only these values are supported.
Replaces the closed PR #20827. Couldn't reopen it.
=> docs: Add link to the supported statistics for cloudwatch alarm

aws/ec2_transit_gateway.go, aws/internal/service/ec2/finder/finder.go, aws/resource_aws_ec2_transit_gateway_route_table_propagation.go, aws/resource_aws_ec2_transit_gateway_route_table_propagation_test.go, aws/resource_aws_ec2_transit_gateway_test.go, aws/resource_aws_ec2_transit_gateway_vpc_attachment.go, aws/resource_aws_ec2_transit_gateway_vpc_attachment_accepter.go
Relates #20775 
* Paginated method already available in ec2/finder.go, though needed to be updated:
https://github.com/hashicorp/terraform-provider-aws/blob/30873bd1d158b85cb4616b8304fe3fd9cb4d3539/aws/internal/service/ec2/finder/finder.go#L551-L584
* Test failure for `TestAccAWSEc2TransitGatewayVpcAttachment_Ipv6Support` seen in GovCloud partition as well …
=> r/ec2_transit_gateway: replace `GetTransitGatewayRouteTablePropagations` with pagination method in ec2/finder

.changelog/20861.txt, aws/internal/service/mwaa/waiter/waiter.go
I've observed under normal enough conditions MWAA creation taking about 2 hours even outside of Terraform.
The environment does create successfully. Killing it early can taint an otherwise working resource requiring a manual `untaint`.
Thanks in advance to the reviewers for taking the time review this PR!
=> Extend MWAA create timeout to 2 hours

.changelog/20797.txt, aws/resource_aws_ec2_managed_prefix_list.go, aws/resource_aws_ec2_managed_prefix_list_test.go
Closes #20738
```
$ make testacc TESTARGS='-run=TestAccAwsEc2ManagedPrefixList_'
--- PASS: TestAccAwsEc2ManagedPrefixList_disappears (59.41s)
--- PASS: TestAccAwsEc2ManagedPrefixList_AddressFamily_IPv6 (77.35s)
--- PASS: TestAccAwsEc2ManagedPrefixList_Name (118.78s)
--- PASS: TestAccAwsEc2ManagedPrefixList_Entry_Description …
```
=> r/ec2_managed_prefix_list - allow updating `max_entries`

.changelog/20795.txt, aws/internal/service/route53/finder/finder.go, aws/resource_aws_route53_health_check.go, aws/resource_aws_route53_health_check_test.go
```
$ make testacc TESTARGS='-run=TestAccAWSRoute53HealthCheck_'
--- PASS: TestAccAWSRoute53HealthCheck_disappears (106.97s)
--- PASS: TestAccAWSRoute53HealthCheck_withHealthCheckRegions (138.27s)
--- PASS: TestAccAWSRoute53HealthCheck_withChildHealthChecks (143.96s)
--- PASS: TestAccAWSRoute53HealthCheck_CloudWatchAlarmCheck …
```
=> r/route53_health_check - allow updating `ip_address` + sweeper

.changelog/20796.txt, aws/internal/service/ec2/enum.go, aws/resource_aws_launch_template.go, aws/resource_aws_launch_template_test.go
Closes #20768
```
$ make testacc TESTARGS='-run=TestAccAWSLaunchTemplate_'
--- PASS: TestAccAWSLaunchTemplate_cpuOptions (126.00s)
--- PASS: TestAccAWSLaunchTemplate_IamInstanceProfile_EmptyConfigurationBlock (127.37s)
--- PASS: TestAccAWSLaunchTemplate_basic (155.95s)
--- PASS: TestAccAWSLaunchTemplate_networkInterfaceType …
```
=> r/launch_template - add support for `http_protocol_ipv6 ` to `metadata_options`

website/docs/r/networkfirewall_rule_group.html.markdown
Closes #20867
This is just documentation update with one example which was missing and is very useful for more advanced and complex rules
=> aws_networkfirewall_rule_group - add example in docs

website/docs/r/imagebuilder_infrastructure_configuration.html.markdown
A tiny fix. An example of import is suggesting ARN for different resource which might be misleading.
=> Use better ARN as an example for importing aws_imagebuilder_infrastructure_configuration

.changelog/20600.txt, aws/resource_aws_config_delivery_channel.go, aws/resource_aws_config_delivery_channel_test.go, website/docs/r/config_delivery_channel.html.markdown
Adds `s3_kms_key_arn` allowing Config to encrypt files to the target S3 bucket. Does not support AWS Managed keys, has to be a Customer Managed one.
Updates DeliveryChannel Schema to v1.9.0 https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/configservice@v1.9.0/types#DeliveryChannel
https://docs.aws.amazon.com/config/latest/developerguide/DocumentHistory.html (February 16, 2021)
Notes: adds a KMS key for testing, adds IAM permission to the role to use the KMS key.
Verified bucket ConfigWritabilityCheckFile file generated by AWSConfig, within its SSE details, is using the KMS key correctly.
* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the …
=> AWS ConfigService KMS encryption support

.changelog/20838.txt, aws/internal/service/efs/finder/finder.go, aws/resource_aws_efs_file_system_policy.go, aws/resource_aws_efs_file_system_policy_test.go, website/docs/r/efs_file_system_policy.html.markdown
Allow the ability to bypass the EFS file system lockout protection.
The fix is to allow pass through from of the 'BypassPolicyLockoutSafetyCheck' to the underlying GoSDK.
This is the error that the fix is for, where unable to create or update an filesystem policy.
```
Error: error creating EFS File System Policy "": InvalidPolicyException: This policy would prevent future FileSystemPolicy updates. Retry the request with the BypassPolicyLockoutSafetyCheck parameter to apply this policy.
```
Tested against our test environment.
* Please do not …
=> BugFix: Add bypass_file_system_lockout_safety_check to efs efs_file_system_policy

website/docs/r/docdb_cluster.html.markdown
Closes #20829
In reviewing the [source for this resource](https://github.com/hashicorp/terraform-provider-aws/blob/main/aws/resource_aws_docdb_cluster.go) and the underlying SDK (notes below), there is indeed no attribute named `maintenance_window`. Instead, the `preferred_maintenance_window` should be used. Since `preferred_maintenance_window` is an …
=> Remove invalid maintenance_window attribute from aws_docdb_cluster

website/docs/r/autoscaling_group.html.markdown
As per [docs](https://docs.aws.amazon.com/autoscaling/ec2/userguide/asg-max-instance-lifetime.html) and API error message (see below), this PR updates acceptable values for `max_instance_lifetime` argument.
```
Error: Error updating Auto Scaling Group: ValidationError: maxInstanceLifetime must be either equal to 0 or between 86400 and 31536000 seconds (inclusive). A value of 0 is used to remove a previously set value.
status code: 400, request id: 3c1243cf-d8c2-492e-8539-5fb5c207d453
```
* Please do not leave "+1" or other comments that do not …
=> Update max_instance_lifetime limit

.changelog/20842.txt, aws/resource_aws_imagebuilder_distribution_configuration.go
This PR removes invalid suggestion of `periods` in name argument of the Distribution Configuration.
Closes #20117
```
$ make testacc TESTARGS='-run=TestAccAwsImageBuilderDistributionConfiguration_Distribution_BAmiDistributionConfiguration_Name'  х INT 3s
TF_ACC=1 go …
```
=> Improve message of name validation error

aws/resource_aws_cognito_user_pool.go
closes #20755 
```
root@47307cab8cc7:/go/src/github.com/terraform-providers/terraform-provider-aws# TEST_AWS_SES_VERIFIED_EMAIL_ARN=arn:aws:ses:us-east-1:01234567890:identity/pn@foo.com make testacc ACCTEST_PARALLELISM=1 TESTARGS='-run=TestAccAWSCognitoUserPool_withEmailConfigurationSource'
==> Checking …
```
=> configuration_set on aws_cognito_user_pool always detected as a change

.changelog/20809.txt, aws/internal/service/sagemaker/finder/finder.go, aws/resource_aws_sagemaker_endpoint_configuration.go, aws/resource_aws_sagemaker_endpoint_configuration_test.go, aws/resource_aws_sagemaker_test.go, website/docs/r/sagemaker_endpoint_configuration.html.markdown
Closes #20699
```
$ make testacc TESTARGS='-run=TestAccAWSSagemakerEndpointConfiguration_'
--- PASS: TestAccAWSSagemakerEndpointConfiguration_disappears (86.12s)
--- PASS: TestAccAWSSagemakerEndpointConfiguration_basic (89.85s)
--- PASS: TestAccAWSSagemakerEndpointConfiguration_kmsKeyId (94.09s)
--- PASS: …
```
=> r/sagemaker_endpoint_config - add support for `async_inference_config`

.changelog/20874.txt, aws/internal/service/efs/finder/finder.go, aws/internal/service/efs/waiter/status.go, aws/internal/service/efs/waiter/waiter.go, aws/resource_aws_efs_file_system.go, aws/resource_aws_efs_file_system_test.go, website/docs/r/efs_file_system.html.markdown
Closes #20773
```
$ make testacc TESTARGS='-run=TestAccAWSEFSFileSystem_'
--- PASS: TestAccAWSEFSFileSystem_kmsConfigurationWithoutEncryption (39.57s)
--- PASS: TestAccAWSEFSFileSystem_disappears (71.82s)
--- PASS: TestAccAWSEFSFileSystem_pagedTags (87.75s)
--- PASS: TestAccAWSEFSFileSystem_availabilityZoneName (104.74s)
--- …
```
=> r/efs_file_system - support transition to primary storage class

.changelog/20315.txt, aws/data_source_aws_eks_clusters.go, aws/data_source_aws_eks_clusters_test.go, aws/provider.go, website/docs/d/eks_clusters.html.markdown
Closes #20251.
Closes #13719.
Supersedes #20315.
Supersedes #15204.
```console
% make testacc TESTARGS='-run=TestAccAWSEksClustersDataSource_'
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSEksClustersDataSource_ -timeout 180m
=== RUN …
```
=> d/aws_eks_clusters: New data source

website/docs/guides/version-3-upgrade.html.md
```release-note
NONE
```
```
N/A
```
Adding more examples of upgrade paths for `aws_iam_access_key` from v2 -> v3 to the upgrade documentation.
=> Add examples of aws_iam_access_key v3 upgrade paths

.semgrep.yml, aws/resource_aws_elasticache_user.go, aws/resource_aws_elasticache_user_group.go, aws/resource_aws_elasticache_user_group_test.go, aws/resource_aws_neptune_cluster_endpoint.go, aws/resource_aws_sagemaker_device_fleet.go, aws/resource_aws_sagemaker_workteam.go, aws/resource_aws_sagemaker_workteam_test.go
This PR adds new semgrep rule to find incorrect form of non-`tags` change detection. It also fixes all 5 findings of new rule.
Before fix:
```
$ make semgrep                                                                                                                           ≡
==> Running Semgrep static analysis...
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
running 27 rules...
aws/resource_aws_elasticache_user.go
severity:warning rule:non-tags-change-detection: Incorrect form of non-tags change detection. https://github.com/hashicorp/terraform-provider-aws/blob/main/docs/contributing/contribution-checklists.md#resource-tagging-code-implementation
autofix: if …
```
=> Correct non-tags change detection

website/docs/r/waf_web_acl.html.markdown
One may think the example configuration *allows* the given IP block and blocks everything else.
I think being explicit here may improve the documentation.
=> waf_web_acl: add hint on the example

website/docs/r/lambda_function.html.markdown
Relates OR Closes #18152
As suggested in the issue, we add a small note to redirect developers to [Resource: aws_lambda_function_event_invoke_config](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lambda_function_event_invoke_config) if they want to configure retry limits for their lambda functions
=> docs: add note on lambda retry config

website/docs/r/cloudfront_key_group.html.markdown
The documentation for aws cloudfront key group was missing the import section.
```
...
```
=> Update documentation for aws cloudfront key group

website/docs/r/route53_vpc_association_authorization.html.markdown
Related to https://github.com/terraform-providers/terraform-provider-aws/issues/14872
Docs for [route53_zone_association](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/route53_zone_association) explain the required usage of `lifecycle{ ignore_changes = [vpc] }`.
The `lifecycle` example has been added here as well, along with a note to see the docs on `route53_zone_association` for additional information (so the exact same info isn't in the docs twice, which over time I'm sure would cause more confusion as things change)
* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this …
=> Added lifecycle ignore_changes stanza to example usage

website/docs/r/apprunner_service.html.markdown
When I apply apprunner_service resource with the example I see in this document ( with `python3` or `nodejs12` runtime value), I get these errors.
```
❯ terraform apply
Error: expected source_configuration.0.code_repository.0.code_configuration.0.code_configuration_values.0.runtime to be one of [PYTHON_3 NODEJS_12], got python3
on test.tf line 10, in …
```
=> Fix AppRunner Documentation: Valid values are PYTHON_3 / NODEJS_12, not python3 / nodejs12

.changelog/20914.txt, aws/internal/service/kms/waiter/waiter.go, aws/resource_aws_kms_key.go
Updates policy and tag propagation time to 5 minutes from 2 minutes.
Closes #20588
```console
$ make testacc TESTARGS='-run=TestAccAWSKmsKey'
--- PASS: TestAccAWSKmsKey_disappears (24.53s)
--- PASS: TestAccAWSKmsKey_asymmetricKey (24.96s)
--- PASS: TestAccAWSKmsKey_basic (27.23s)
--- PASS: TestAccAWSKmsKey_policy (45.64s)
--- PASS: TestAccAWSKmsKey_policyBypassUpdate (47.42s)
--- PASS: TestAccAWSKmsKey_Policy_IamRole (51.40s)
--- PASS: TestAccAWSKmsKey_Policy_IamServiceLinkedRole (58.23s)
--- PASS: TestAccAWSKmsKey_tags (90.22s)
--- PASS: TestAccAWSKmsKey_policyBypass (152.64s)
--- PASS: TestAccAWSKmsKey_isEnabled (219.20s)
```
=> resource/aws_kms_key: Updates policy and tag propagation time to 5 minutes

.changelog/20638.txt, aws/data_source_aws_msk_kafka_version.go, aws/data_source_aws_msk_kafka_version_test.go, aws/provider.go, website/docs/d/msk_kafka_version.html.markdown
Closes #16268
```
$ make testacc TESTARGS='-run=TestAccAWSMskKafkaVersion'
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSMskKafkaVersion -timeout 180m
=== RUN   TestAccAWSMskKafkaVersion_basic
=== PAUSE TestAccAWSMskKafkaVersion_basic
=== RUN …
```
=> Add msk_kafka_version data source

.changelog/20952.txt, aws/resource_aws_cognito_user_pool.go, aws/resource_aws_cognito_user_pool_test.go
Closes #20949
```
$ make testacc TESTARGS='-run=TestAccAWSCognitoUserPool_'
--- PASS: TestAccAWSCognitoUserPool_disappears (80.25s)
--- PASS: TestAccAWSCognitoUserPool_withEmailConfiguration (101.44s)
--- PASS: TestAccAWSCognitoUserPool_basic (101.51s)
--- PASS: TestAccAWSCognitoUserPool_schemaAttributesRemoved (104.54s)
--- …
```
=> r/cognito_user_pool - remove lambda config

website/docs/d/eks_node_groups.html.markdown
Small change to fix example of new resource introduced in https://github.com/hashicorp/terraform-provider-aws/pull/13564.  Fixes reference error:
```terraform
╷
│ Error: Reference to undeclared resource
│
│   on .../main.tf line 81, in data "aws_eks_node_group" "example":
│   81:   for_each = data.aws_eks_node_group_names.example.names
│
│ A data resource …
```
=> Fix AWS EKS node groups example docs

website/docs/r/vpc_peering_connection.html.markdown
Small change to update _outdated_ docs for dns resolution over inter-region VPC peering. Support was added back in 2018 [https://aws.amazon.com/about-aws/whats-new/2018/11/announcing-support-for-dns-resolution-over-inter-region-vpc-peering/](https://aws.amazon.com/about-aws/whats-new/2018/11/announcing-support-for-dns-resolution-over-inter-region-vpc-peering/) 
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the …
=> docs: update outdated info regarding dns resolution for inter-region VPC peering

.changelog/21037.txt, aws/resource_aws_sagemaker_app_image_config.go, aws/resource_aws_sagemaker_app_image_config_test.go, website/docs/r/sagemaker_app_image_config.html.markdown
Closes #17267
```
$ make testacc TESTARGS='-run=TestAccAWSSagemakerAppImageConfig_'
--- PASS: TestAccAWSSagemakerAppImageConfig_tags (126.57s)
--- PASS: TestAccAWSSagemakerAppImageConfig_disappears (38.97s)
--- PASS: TestAccAWSSagemakerAppImageConfig_basic (54.48s)
--- PASS: …
```
=> r/sagemaker_app_image_config - tagging support

.changelog/18445.txt, aws/data_source_aws_kinesis_firehose_delivery_stream.go, aws/data_source_aws_kinesis_firehose_delivery_stream_test.go, aws/internal/service/firehose/finder/finder.go, aws/internal/service/firehose/waiter/status.go, aws/internal/service/firehose/waiter/waiter.go, aws/provider.go, aws/resource_aws_kinesis_firehose_delivery_stream.go, aws/resource_aws_kinesis_firehose_delivery_stream_test.go, website/docs/d/kinesis_firehose_delivery_stream.html.markdown
The goal is to simply allow referencing preexisting Delivery Streams.
This is a feature a few have sought. Fixes #3865.
Closes #3865
```
➜  terraform-provider-aws (f-add-kinesis-delivery-stream-data-source) ✗ make testacc TESTARGS='-v -run=TestAccDataSourceAwsKinesisFirehoseDeliveryStream' …
```
=> Add data source for Kinesis Firehose Delivery Stream.

website/docs/d/launch_template.html.markdown, website/docs/r/launch_template.html.markdown
This PR add description about `http_protocol_ipv6` in aws_launch_template, because #20796 and #21008 added it but didn't update document.
=> add description about http_protocol_ipv6

.changelog/21062.txt, aws/internal/service/ec2/waiter/waiter.go
We have many automated tests that create route table associations and have witnessed extreme variance in the duration when waiting for the `aws_route_table_association` resource to be found after it is initially created. Most of the time, the `aws_route_table_association` resource finishes in about 1 second, while in others it'll retry until we hit the default 20 `MaxNotFound` checks in the `StateChangeConf` waiter, which causes the resource to always fail around the 2.5 minute mark when this condition is exhibited. This change increases the max `NotFoundChecks` for the `RouteTableAssociationCreated` `StateChangeConf` waiter to 40, which gets us closer to the max default timeout of 5 minutes. After having built my own copy of the provider plugin with this change we no longer see this …
=> r/aws_route_table_association: Wait for 40 NotFoundChecks

aws/resource_aws_connect_contact_flow_test.go, aws/resource_aws_connect_instance_test.go
Relates #16709, #16854 
```
--- PASS: TestAccAwsConnectContactFlow_serial (342.35s)
--- PASS: TestAccAwsConnectContactFlow_serial/basic (143.88s)
--- PASS: TestAccAwsConnectContactFlow_serial/filename (99.32s)
--- PASS: TestAccAwsConnectContactFlow_serial/disappears (99.15s)
--- PASS: TestAccAwsConnectInstance_serial …
```
=> fix: use `resource.Test` in serialized connect resource tests 

.changelog/21077.txt, aws/config.go, aws/provider.go, go.mod, go.sum, website/docs/index.html.markdown
The AWS Provider currently supports the environment variables `HTTP_PROXY` or `HTTPS_PROXY` to configure an HTTP proxy. In some cases, only the AWS Provider or a specific instance of the AWS Provider need to traverse the proxy.
This PR allows setting the HTTP proxy at the level of the provider configuration.
Closes #14942
=> provider: Add HTTP proxy setting

.changelog/21085.txt, aws/resource_aws_dx_connection.go, aws/resource_aws_dx_lag.go
Closes #21068.
Relates #17852.
```console
% make testacc TESTARGS='-run=TestAccAwsDxConnection_\|TestAccAwsDxLag_'                                                             
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 …
```
=> DirectConnect Connection & LAG: `provider_name` -> Computed

aws/data_source_aws_ec2_transit_gateway_dx_gateway_attachment_test.go, aws/data_source_aws_ec2_transit_gateway_peering_attachment_test.go, aws/data_source_aws_ec2_transit_gateway_route_table_test.go, aws/data_source_aws_ec2_transit_gateway_route_tables_test.go, aws/data_source_aws_ec2_transit_gateway_test.go, aws/data_source_aws_ec2_transit_gateway_vpc_attachment_test.go, aws/data_source_aws_ec2_transit_gateway_vpn_attachment_test.go, aws/resource_aws_ec2_transit_gateway_peering_attachment_accepter_test.go, aws/resource_aws_ec2_transit_gateway_peering_attachment_test.go, aws/resource_aws_ec2_transit_gateway_prefix_list_reference_test.go, aws/resource_aws_ec2_transit_gateway_route_table_association_test.go, aws/resource_aws_ec2_transit_gateway_route_table_propagation_test.go, aws/resource_aws_ec2_transit_gateway_route_table_test.go, aws/resource_aws_ec2_transit_gateway_route_test.go, aws/resource_aws_ec2_transit_gateway_test.go, aws/resource_aws_ec2_transit_gateway_vpc_attachment_accepter_test.go, aws/resource_aws_ec2_transit_gateway_vpc_attachment_test.go
In nightly CI we get many failures with error messages like
```
=== RUN   TestAccAWSEc2TransitGatewayVpcAttachmentDataSource_Filter
=== PAUSE TestAccAWSEc2TransitGatewayVpcAttachmentDataSource_Filter
=== CONT  TestAccAWSEc2TransitGatewayVpcAttachmentDataSource_Filter
data_source_aws_ec2_transit_gateway_vpc_attachment_test.go:14: Step 1/1 error: Error running …
```
=> Serialize Transit Gateway tests

aws/internal/service/rds/enum.go, aws/internal/service/rds/finder/finder.go, aws/internal/service/rds/waiter/status.go, aws/internal/service/rds/waiter/waiter.go, aws/internal/tfresource/retry.go, aws/resource_aws_db_event_subscription.go, aws/resource_aws_db_event_subscription_test.go
Closes #13264.
```
make testacc TESTARGS="-run=TestAccAWSDBEventSubscription"
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSDBEventSubscription -timeout 180m
=== RUN   TestAccAWSDBEventSubscription_basicUpdate
=== PAUSE …
```
=> r/aws_db_event_subscription: Use waiters package

.changelog/21053.txt, aws/data_source_aws_db_proxy.go, aws/data_source_aws_db_proxy_test.go, aws/internal/service/rds/finder/finder.go, aws/provider.go, website/docs/d/db_proxy.html.markdown
Closes #20943.
```
make testacc TESTARGS="-run=TestAccAWSDBProxyDataSource_basic"                                                                         18m 21s
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSDBProxyDataSource_basic -timeout 180m
=== …
```
=> d/db_proxy - new data source

website/docs/r/securityhub_invite_accepter.markdown
This PR fixes a typo in the documentation for [aws_securityhub_invite_accepter](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/securityhub_invite_accepter) where the `depends_on` statement was incorrectly listed as `aws_securityhub_account.accepter` rather than `aws_securityhub_account.invitee`.
Closes #21102
Output from …
=> Fix depends_on in securityhub_invite_accepter

.changelog/21144.txt, aws/internal/service/ec2/waiter/waiter.go, aws/resource_aws_volume_attachment.go, aws/resource_aws_volume_attachment_test.go, website/docs/r/volume_attachment.html.markdown
Closes #8602 
This is a cherry-picked continuation of #8602 (unable to make edits to it).
Fixes #6673
Fixes #2084
Fixes #2957
Fixes #4770
Fixes #288
Fixes #1017
Relates #4293
Relates #1991
```
--- PASS: TestAccAWSVolumeAttachment_disappears (114.38s)
--- PASS: TestAccAWSVolumeAttachment_stopInstance (117.35s)
--- …
```
=> Add option to stop an instance before trying to remove an attached volume

.changelog/20383.txt, .changelog/21122.txt, aws/data_source_aws_lex_bot.go, aws/data_source_aws_lex_bot_test.go, aws/data_source_aws_lex_intent.go, aws/internal/service/lex/enum.go, aws/internal/service/lex/finder/finder.go, aws/internal/service/lex/waiter/status.go, aws/internal/service/lex/waiter/waiter.go, aws/resource_aws_lex_bot.go, aws/resource_aws_lex_bot_alias_test.go, aws/resource_aws_lex_bot_test.go, aws/resource_aws_lex_intent.go, aws/resource_aws_lex_intent_test.go, website/docs/r/lex_bot.html.markdown
Closes #21107.
Closes #21045.
Closes #15555.
Closes #15605.
```
$  make testacc TESTARGS='-run=TestAccAwsLex' ACCTEST PARALLELISM=5
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAwsLex -timeout 180m
=== RUN   TestAccAwsLexBotAlias_basic
=== PAUSE …
```
=> Added proper status and waiter to Lex Bot. Fixed issues with import tests.

aws/data_source_aws_mq_broker_test.go, aws/data_source_aws_rds_cluster_test.go, aws/resource_aws_shield_protection_test.go
- tests/shield_protection: Standardize name
- tests/ds/mq_broker: Standardize naming
```
--- PASS: TestAccAWSShieldProtection_disappears (16.04s)
--- PASS: TestAccAWSShieldProtection_ElasticIPAddress (18.02s)
--- PASS: TestAccAWSShieldProtection_Elb (47.30s)
--- PASS: …
```
=> tests: Standardize test variables, config

.github/workflows/issue-comment-created.yml
The `issue-comment-created` workflow automatically removes the `waiting-response` label when a comment is left on an issue. Lately, I've noticed that if I leave a comment just before adding the `waiting-response` label, this automation will be triggered and the label I've just applied will be removed.
It's possible to work around this by waiting "a bit" …
=> Add exclusions list to issue-comment-created

.github/workflows/autoremove_labels.yml
Pretty straightforward; when I wrote the GitHub automation to automatically remove `waiting-response` and `needs-triage` labels from closed issues and PRs, I forgot to give it a name, so it's sad to look at in the GitHub UI. This PR fixes that.
=> Update workflow name

.changelog/21616.txt, website/docs/r/eks_node_group.html.markdown
Closes #21548.
As `eks.AMITypes_Values()` is used in the argument's validator, rebuilding the provider against the latest AWS Go SDK will allow all valid values.
```
...
```
=> r/aws_eks_node_group: Refer to AWS documentation for valid `ami_type` values

internal/service/storagegateway/enum.go, internal/service/storagegateway/errors.go, internal/service/storagegateway/file_system_association.go, internal/service/storagegateway/file_system_association_test.go, internal/service/storagegateway/find.go, internal/service/storagegateway/status.go, internal/service/storagegateway/wait.go
Closes #21472.
```console
% make testacc PKG_NAME=internal/service/storagegateway TESTARGS='-run=TestAccStorageGatewayFileSystemAssociation_'
TF_ACC=1 go test ./internal/service/storagegateway/... -v -count 1 -parallel 20 …
```
=> r/aws_storagegateway_file_system_association: Correct resource not found error handling

internal/conns/conns.go
=> fix initialization of serviceData in internal/conns

GNUmakefile, internal/service/dms/sweep.go, internal/service/ec2/sweep.go
The sweeper for `aws_dms_replication_instance` was failing due to an existing `aws_dms_replication_task`. Adds a sweeper for `aws_dms_replication_task` to unblock.
Also adds a dependency between the `aws_subnet` sweeper and the `aws_dms_replication_instance` sweeper, since `aws_subnet` was blocked.
Before change:
```
$ make sweep SWEEPARGS=-sweep-run=aws_dms_replication_instance
2021/10/29 16:37:37 [DEBUG] Running Sweepers for region (us-west-2):
2021/10/29 16:37:37 [DEBUG] Running Sweeper (aws_dms_replication_instance) in region (us-west-2)
2021/10/29 16:37:37 [INFO] Attempting to use session-derived credentials
2021/10/29 16:37:40 [INFO] Successfully derived credentials from session
2021/10/29 16:37:40 [INFO] AWS Auth provider used: "CredentialsEndpointProvider"
2021/10/29 16:37:40 …
```
=> Sweeper: Add sweeper for `aws_dms_replication_task`

.changelog/21542.txt, internal/service/ec2/enum.go, internal/service/ec2/errors.go, internal/service/ec2/find.go, internal/service/ec2/internet_gateway.go, internal/service/ec2/internet_gateway_data_source.go, internal/service/ec2/internet_gateway_data_source_test.go, internal/service/ec2/internet_gateway_test.go, internal/service/ec2/network_interface.go, internal/service/ec2/network_interface_attachment.go, internal/service/ec2/network_interface_data_source.go, internal/service/ec2/network_interface_data_source_test.go, internal/service/ec2/network_interfaces_data_source.go, internal/service/ec2/security_group.go, internal/service/ec2/status.go, internal/service/ec2/sweep.go, internal/service/ec2/wait.go, internal/service/elb/load_balancer.go, internal/service/elbv2/load_balancer.go
Closes #21406.
Closes #21647.
Closes #21621.
```
$ make testacc TESTARGS="-run=TestAccELBLoadBalancer_basic" PKG_NAME="internal/service/elb"                 х INT
TF_ACC=1 go test ./internal/service/elb/... -v -count 1 -parallel 20 -run=TestAccELBLoadBalancer_basic …
```
=> tech_debt: functions for detaching and deleting network interfaces

.changelog/21661.txt, internal/service/datasync/location_s3.go, internal/service/datasync/location_s3_test.go
```
$ make testacc PKG_NAME=internal/service/datasync TESTARGS='-run=TestAccDataSyncLocationS3_'
--- PASS: TestAccDataSyncLocationS3_storageClass (76.79s)
--- PASS: TestAccDataSyncLocationS3_disappears (82.97s)
--- PASS: TestAccDataSyncLocationS3_basic (85.00s)
--- PASS: TestAccDataSyncLocationS3_tags (209.89s)
```
=> r/datasync_s3_location - add validation `agent_arns`, `s3_bucket_arn` and `s3_config. bucket_access_role_arn`

.semgrep.yml, internal/generate/namevaluesfilters/generators/servicefilters/main.go, internal/generate/namevaluesfilters/service_filters_gen.go, internal/service/autoscaling/group.go, internal/service/autoscaling/launch_configuration.go, internal/service/backup/vault_notifications_test.go, internal/service/cognitoidp/user_pool_ui_customization_test.go, internal/service/ec2/network_interface_sg_attachment_test.go, internal/service/ec2/network_interface_test.go, internal/service/efs/mount_target.go, internal/service/elasticbeanstalk/environment.go, internal/service/elasticsearch/domain_saml_options_test.go, internal/service/elb/load_balancer.go, internal/service/elb/load_balancer_test.go, internal/service/elbv2/load_balancer.go, internal/service/glue/ml_transform_test.go, internal/service/iam/openid_connect_provider_test.go, internal/service/iam/server_certificate.go, internal/service/prometheus/workspace_test.go, internal/service/s3/bucket_object.go, internal/service/s3/enum.go, internal/service/serverlessapprepo/cloudformation_stack.go, internal/service/transfer/server.go, internal/service/worklink/website_certificate_authority_association_test.go
With the code reorganization for Service Packages, Semgrep checks were no longer able to run. This PR restores them.
Relates #20000
Acceptance test results
```console
$ $ make testacc TESTARGS='-run=TestAccEC2NetworkInterface\|TestAccGlueMlTransform\|TestAccElasticSearchDomainSamlOptions\|TestAccIAMOpenidConnectProvider\|TestAccPrometheusWorkspace\|TestAccELBLoadBalancer\|TestAccEC2NetworkInterfaceSgAttachment\|TestAccBackupVaultNotification\|TestAccCognitoIDPUserPoolUICustomization\|TestAccWorkLinkWebsiteCertificateAuthorityAssociation'
--- PASS: TestAccBackupVaultNotification_disappears (18.83s)
--- PASS: TestAccBackupVaultNotification_basic (21.32s)
--- PASS: TestAccCognitoIDPUserPoolUICustomization_Client_disappears (44.29s)
--- PASS: …
```
=> linting: Restores Semgrep checks

docs/roadmaps/2021_August_to_October.md
Relates #21681.
Fixes _markdown-link-check_ error:
```
FILE: docs/roadmaps/2021_August_to_October.md
[✖] docs/contributing/core-services.md → Status: 400 [Error: ENOENT: no such file or directory, access '/github/workspace/docs/roadmaps/docs/contributing/core-services.md'] {
errno: -2,
code: 'ENOENT',
syscall: 'access',
path: …
```
=> Correct `Core Services` link

internal/service/route53/record.go, internal/service/route53/record_test.go
When specifying wrong format for the recordID, the panic occurs. The index check is not enough. This fix avoids panic, and instead return the empty string value, so that caller can handle error properly.
I encountered the panic as follows, so I added the if condition to avoid the panic to fix this.
```
Stack trace from the terraform-provider-aws_v3.63.0_x5 …
```
=> Added index check for parsing record ID to avoid panic

internal/service/config/aggregate_authorization_test.go
The acceptance tests for AWS Config aggregate authorization were authorizing random AWS accounts. Disable the tests. They will be changed later.
=> Disables acceptance tests for AWS Config aggregate authorization

docs/contributing/contribution-checklists.md, docs/contributing/running-and-writing-acceptance-tests.md
=> docs: Fix randomwithprefix

.changelog/21717.txt, internal/service/ec2/ebs_encryption_by_default.go, internal/service/ec2/ebs_encryption_by_default_test.go, website/docs/r/ebs_encryption_by_default.html.markdown
Closes #21699.
```
$ make testacc TESTARGS="-run=TestAccEC2EBSEncryptionByDefault_basic" PKG_NAME="internal/service/ec2"                                                                                                                                           4s …
```
=> r/aws_ebs_encryption_by_default - add import support

internal/service/macie/s3_bucket_association_test.go
Previously
```
=== RUN   TestAccMacieS3BucketAssociation_basic
=== PAUSE TestAccMacieS3BucketAssociation_basic
=== CONT  TestAccMacieS3BucketAssociation_basic
s3_bucket_association_test.go:160: unexpected PreCheck error: InvalidInputException: The request was rejected. Macie is not enabled for this AWS account *******.
{
RespMetadata: {
StatusCode: 400, …
```
=> tests/macie: Skip Macie class acceptance tests if not enabled

internal/create/attrmap.go, internal/service/sns/sms_preferences.go, internal/service/sns/sms_preferences_test.go, internal/service/sqs/queue.go
Closes #21477.
```console
% make testacc PKG_NAME=internal/service/sns TESTARGS='-run=TestAccSNSSMSPreferences_serial'
TF_ACC=1 go test ./internal/service/sns/... -v -count 1 -parallel 20 -run=TestAccSNSSMSPreferences_serial -timeout 180m
=== RUN …
```
=> r/aws_sns_sms_preferences: Fix acceptance tests

internal/service/synthetics/canary.go, internal/service/synthetics/canary_test.go
Closes #21394.
```console
% make testacc TESTARGS='-run=TestAccSyntheticsCanary_' PKG_NAME=internal/service/synthetics
TF_ACC=1 go test ./internal/service/synthetics/... -v -count 1 -parallel 20 -run=TestAccSyntheticsCanary_ -timeout 180m
=== RUN …
```
=> r/aws_synthetics_canary: Increase IAM role propagation wait time on Create

internal/service/rds/instance_data_source.go
This PR prevents the issue described in #21663 from happening.
Closes #21663.
```
...
```
=> d/aws_db_instance - require db_instance_identifier to be non-empty

.changelog/21737.txt, internal/service/batch/job_queue.go, website/docs/r/batch_job_queue.html.markdown
* When creating a new job queue in AWS Batch, there is no actual limit
in the API to the number of compute environments you can create. This is
controlled by a service quota that can be adjusted. Other systems such
as CloudFormation allow you to submit more than 3 compute environments
per job queue, so I'm removing that limit here. …
=> Remove MaxItems Limit from CreateJobQueue

website/docs/r/ec2_managed_prefix_list.html.markdown
https://github.com/hashicorp/terraform-provider-aws/pull/20797 removed `ForceNew` for this argument. This updates the website to match.
```
...
```
=> Remove "ForceNew" from ec2_managed_prefix_list's max_entries

.changelog/21710.txt, internal/service/ec2/find.go
Relates #21683, #21629
Notes:
* The errors similar to
```
Error: error reading Route Table Association (rtbassoc-07d32038d3161359d): empty result
```
occur when finding the RouteTable, not the association itself. This _could_ be because we use an unpaginated `DescribeRouteTables` method that may be needed for heavily used AWS accounts. Testing this is not …
=> service/ec2/find: update call to`DescribeRouteTables` with paginated method

website/docs/r/docdb_cluster_parameter_group.html.markdown
Closes #21679
This PR clarifies that the values passed to the `parameter.*` arguments of the `aws_docdb_cluster_parameter_group` resource should be string representations of their values. Passing the values as an `int`, or `float` can lead to unexpected behavior and persistent diffs, as seen in the linked issue.
=> Note that aws_docdb_cluster_parameter_group.parameter.* should be strings

.changelog/21404.txt, internal/service/eks/node_group.go, internal/service/eks/node_group_test.go, website/docs/r/eks_node_group.html.markdown
This reverts commit eff27751df66602298bc1e73352f188f8d1f3982.
Fixes #21203.
Relates #20532.
Original PR stated that the order of instance types did not matter but it absolutely does.
```
...
```
=> Revert "change arg back to a TypeSet since it supports multiple values and order doesn't matter"

website/docs/r/default_route_table.html.markdown, website/docs/r/default_security_group.html.markdown, website/docs/r/emr_cluster.html.markdown, website/docs/r/network_acl.html.markdown, website/docs/r/route_table.html.markdown, website/docs/r/security_group.html.markdown
Closes #20484
Closes #20756
Closes #20911
Closes #20954
Closes #21139
Closes #21536
Closes #21573
Closes #21659
Closes #21714
Relates #20428
#20428 updated the documentation around several resources to switch them to argument syntax (see [Attributes as Blocks](https://www.terraform.io/docs/language/attr-as-blocks.html …
=> Revert documentation changes around attributes-as-blocks

.changelog/21738.txt, internal/service/elasticsearch/domain.go
Closes https://github.com/hashicorp/terraform-provider-aws/issues/20498
Output from acceptance testing (with code change):
```
=== RUN   TestAccElasticsearchDomainDataSource_Data_advanced
=== PAUSE TestAccElasticsearchDomainDataSource_Data_advanced
=== CONT  TestAccElasticsearchDomainDataSource_Data_advanced
--- PASS: …
```
=> r/elasticsearch_domin: use tags as `KeyValueTags` type instead of as `[]*elasticsearchservice.Tag` in `UpdateTags`

.changelog/21743.txt, internal/service/ec2/find.go
Relates https://github.com/hashicorp/terraform-provider-aws/issues/21628
```
in progress
--- SKIP: TestAccEC2DefaultSecurityGroup_Classic_empty (0.00s)
--- SKIP: TestAccEC2DefaultSecurityGroup_Classic_basic (2.25s)
--- PASS: TestAccEC2SecurityGroupRule_expectInvalidTypeError (13.94s)
--- PASS: …
```
=> r/security_group: add pagination to security group find method

.github/labeler-pr-triage.yml
Fixes PR labeler detection of changes to the elasticsearch service.
=> Amend PR labeler elasticsearch dir elasticsearchservice -> elasticsearch

website/docs/r/cloudfront_response_headers_policy.html.markdown
Closes #21660
This PR updates the documentation around the `cloudfront_response_headers_policy` resource to clarify, correct formatting, and provide additional information.
AWS API:
- [ResponseHeadersPolicySecurityHeadersConfig](https://docs.aws.amazon.com/cloudfront/latest/APIReference/API_ResponseHeadersPolicySecuri …
=> Correct cloudfront_response_headers_policy docs

internal/service/accessanalyzer/analyzer.go, internal/service/accessanalyzer/sweep.go, internal/sweep/sweep_test.go
Closes #21649.
```console
% make sweep SWEEPARGS=-sweep-run=aws_accessanalyzer_analyzer SWEEP=us-west-2 
go test ./internal/sweep -v -tags=sweep -sweep=us-west-2 -sweep-run=aws_accessanalyzer_analyzer -timeout 60m
2021/11/12 09:29:16 [DEBUG] Running …
```
=> r/aws_accessanalyzer_analyzer: Add test sweeper

.changelog/21765.txt, internal/service/sagemaker/endpoint.go, internal/service/sagemaker/endpoint_test.go, internal/service/sagemaker/find.go, website/docs/r/sagemaker_endpoint.html.markdown
```
$ make testacc TESTARGS='-run=TestAccSageMakerEndpoint_'
--- PASS: TestAccSageMakerEndpoint_deploymentConfig (268.33s)
--- PASS: TestAccSageMakerEndpoint_basic (298.94s)
--- PASS: TestAccSageMakerEndpoint_disappears (319.65s)
--- PASS: TestAccSageMakerEndpoint_tags (350.58s)
--- PASS: TestAccSageMakerEndpoint_endpointName …
```
=> r/sagemaker_endpoint - add `deployment_config` argument

.changelog/21760.txt, internal/service/neptune/cluster.go, internal/service/neptune/cluster_test.go, internal/service/neptune/wait.go
Closes https://github.com/hashicorp/terraform-provider-aws/issues/21378
```
--- PASS: TestAccNeptuneCluster_updateEngineVersion (1659.73s)
--- PASS: TestAccNeptuneClusterParameterGroup_description (50.76s)
--- PASS: TestAccNeptuneClusterParameterGroup_basic (51.99s)
--- PASS: TestAccNeptuneClusterParameterGroup_generatedName …
```
=> r/neptune_cluster: support in-place update of `engine_version`

.changelog/21769.txt, internal/service/iot/thing_type.go, internal/service/iot/thing_type_test.go, website/docs/r/iot_thing_type.html.markdown
```
$ AWS_PROFILE=default make testacc TESTARGS='-run=TestAccIoTThingType' PKG_NAME=internal/service/iot
TF_ACC=1 go test ./internal/service/iot/... -v -count 1 -parallel 20 -run=TestAccIoTThingType -timeout 180m
=== RUN   TestAccIoTThingType_basic
=== PAUSE …
```
=> aws_iot_thing_type tags support

.changelog/21560.txt, internal/provider/provider.go, internal/service/securityhub/finding_aggregator.go, internal/service/securityhub/finding_aggregator_test.go, internal/service/securityhub/securityhub_test.go, website/docs/r/securityhub_finding_aggregator.markdown
This PR allows the creation of `aws_securityhub_finding_aggregator` resources. These allow security hub findings to be aggregated across multiple regions into a single aggregation region. https://docs.aws.amazon.com/securityhub/latest/userguide/finding-aggregation.html
Release note for CHANGELOG:
```
New resource: aws_securityhub_finding_aggregator
``` …
=> New resource: aws_securityhub_finding_aggregator

.changelog/21505.txt, internal/acctest/acctest.go, internal/provider/provider.go, internal/service/appstream/directory_config.go, internal/service/appstream/directory_config_test.go, internal/service/appstream/fleet_test.go, internal/service/appstream/wait.go, website/docs/r/appstream_directory_config.html.markdown
Added a new resource, doc and tests for [AppStream Directory Config](https://docs.aws.amazon.com/appstream2/latest/APIReference/API_CreateDirectoryConfig.html) called `aws_appstream_directory_config`
Relates #6508
```
$ make testacc TESTARGS='-run=TestAccAppStreamDirectoryConfig' PKG_NAME=internal/service/appstream
==> …
```
=> New resource for Appstream Directory Config

.changelog/21793.txt, internal/service/cloudfront/cache_policy.go, internal/service/cloudfront/cache_policy_test.go
Closes #21788.
```console
% make testacc PKG_NAME=internal/service/cloudfront TESTARGS='-run=TestAccCloudFrontCachePolicy_'
TF_ACC=1 go test ./internal/service/cloudfront/... -v -count 1 -parallel 20 -run=TestAccCloudFrontCachePolicy_ -timeout 180m
=== RUN …
```
=> r/aws_cloudfront_cache_policy: Fix support for 0 values of `default_ttl`, `max_ttl` and `min_ttl`

.changelog/21794.txt, internal/service/ec2/wait.go
Closes #21792.
```console
% make testacc PKG_NAME=internal/service/ec2 TESTARGS='-run=TestAccEC2InternetGateway_'
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 20 -run=TestAccEC2InternetGateway_ -timeout 180m
=== RUN …
```
=> r/aws_internet_gateway: Allow `available` as a pending state during gateway detach

.changelog/21777.txt, internal/service/autoscaling/group.go, internal/service/autoscaling/group_test.go
When an instance refresh is triggered, an empty `checkpoint_percentages` array is sent, causing the refresh to hang.
Closes #21656
```
$ make testacc TESTARGS='-run=TestAccAutoScalingGroup_' PKG_NAME=internal/service/autoscaling
--- PASS: TestAccAutoScalingGroup_Name_generated (82.71s)
--- PASS: TestAccAutoScalingGroup_serviceLinkedRoleARN (92.82s)
--- PASS: TestAccAutoScalingGroup_namePrefix (98.25s)
--- PASS: TestAccAutoScalingGroup_withMetrics (135.95s)
--- PASS: TestAccAutoScalingGroup_vpcUpdates (152.26s)
--- PASS: TestAccAutoScalingGroup_maxInstanceLifetime (164.74s)
--- PASS: TestAccAutoScalingGroup_withPlacementGroup (184.06s)
--- PASS: TestAccAutoScalingGroup_classicVPCZoneIdentifier (60.14s)
--- PASS: TestAccAutoScalingGroup_enablingMetrics …
```
=> resource/aws_autoscaling_group: Fix autoscaling groups stuck in `pending` instance refresh

website/docs/r/autoscaling_group.html.markdown
Closes #21729
The values listed as valid options for `enabled_metrics` was outdated. Rather than updating them, opting to link out to the relevant API documentation so that the list is always up to date.
=> autoscaling_group: Link to API docs for metrics values

.changelog/21797.txt, internal/service/route53resolver/wait.go
DNSSEC config validation status takes longer than 5 minutes on initial creation
examples:
`ENABLING` exceeding 5 minutes
```
aws_route53_resolver_dnssec_config.main: Still creating... [4m40s elapsed]
aws_route53_resolver_dnssec_config.main: Still creating... [4m50s elapsed]
aws_route53_resolver_dnssec_config.main: Still creating... [5m0s elapsed]
╷
│ Error: timeout while waiting for state to become 'ENABLED' (last state: 'ENABLING', timeout: 5m0s)
│ 
│   with aws_route53_resolver_dnssec_config.main,
│   on network.tf line 16, in resource "aws_route53_resolver_dnssec_config" "main":
│   16: resource "aws_route53_resolver_dnssec_config" "main" {
│ 
```
`DISABLING` exceeding 5 minutes (due to the taint applied to the resource since creation exceeded initial timeout)
``` …
```
=> aws_route53_resolver_dnssec_config - increase config create/delete timeouts to 10 minutes

website/docs/r/lb_target_group_attachment.html.markdown
Thanks to https://github.com/hashicorp/terraform-provider-aws/issues/21069, we can target an ALB.
But in [the current document of target_group_attachment](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lb_target_group_attachment), there is no explanation of how to attach ALB in a target_id.
Output from acceptance testing: NA, …
=> Add description: lb_target_group_attachment for target type alb

website/docs/d/iam_server_certificate.html.markdown
The `id` attribute is already present[1][2], but not documented.
If not more, at least the `aws_cloudfront_distribution` resource needs[3] to use
`aws_iam_server_certificate.id`, so it make sense to document it.
[1] https://github.com/hashicorp/terraform-provider-aws/blob/187f1659a4fef11ac314567273b5470afe6b662f/internal/service/iam/server_certificate_data_source.go#L138
[2] https://github.com/hashicorp/terraform-provider-aws/blob/187f1659a4fef11ac314567273b5470afe6b662f/internal/service/iam/server_certificate_data_source_test.go#L56
[3] https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudfront_distribution#iam_certificate_id
* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and- …
=> Add id attribute to server_certificate_data doc

website/docs/r/quicksight_user.html.markdown
As stated here:
https://github.com/hashicorp/terraform-provider-aws/issues/17406#issuecomment-969486618
And confirmed by documentation, `user_name` is not valid for a identity type of "IAM" its only for use for Quicksight managed users. This changes the example to use `session_name`
=> Update quicksight_user documentation example to include a valid example

.semgrep.yml
https://semgrep.dev/docs/semgrep-ci/overview/ appears to suggest that the Semgrep CI container will not flag existing rule violations. It may only apply when the rule is first created.
Try removing the restrictions from one existing rule to see if this will work with existing rules. If this works, it will help prevent new rule violations
=> Semgrep: Try removing restrictions

.semgrep.yml
Reverts hashicorp/terraform-provider-aws#21822
The Semgrep checks passed in the PR, but not on the `main` branch. Oh well.
=> Revert "Semgrep: Try removing restrictions"

.changelog/20769.txt, internal/service/firehose/delivery_stream.go, internal/service/firehose/delivery_stream_data_source_test.go, internal/service/firehose/delivery_stream_test.go
Closes #20763
Added support for dynamic partitioning configuration. The syntax is very straight forward
```
dynamic_partitioning_configuration {
enabled = true
retry_options {
duration_in_seconds = 300
}
}
```
=> support for DynamicPartitioningConfiguration in firehose resource

.changelog/21837.txt, internal/service/ec2/instance_type_data_source.go, internal/service/ec2/instance_type_data_source_test.go, website/docs/d/ec2_instance_type.html.markdown
Closes https://github.com/hashicorp/terraform-provider-aws/issues/21624
```
$ make testacc TESTS=TestAccEC2InstanceTypeDataSource PKG=ec2
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 20 -run='TestAccEC2InstanceTypeDataSource' -timeout 180m
=== RUN …
```
=> Add encryption-in-transit-supported attribute to aws_ec2_instance_type

.changelog/21831.txt, internal/service/ec2/wait.go
Closes #21830
Closes #21525
```
...
```
=> r/route: Prevent giving up on route ready wait too early

.changelog/21825.txt, internal/service/lambda/layer_version.go
Closes #21742
```
$ make testacc TESTARGS='-run=TestAccLambdaLayerVersion' PKG_NAME=internal/service/lambda
TF_ACC=1 go test ./internal/service/lambda/... -v -count 1 -parallel 20 -run=TestAccLambdaLayerVersion -timeout 180m
=== RUN …
```
=> Increase aws_lambda_layer_version compatible_runtimes MaxItems value to 15

.changelog/21838.txt, internal/service/cloudfront/response_headers_policy_data_source.go, internal/service/cloudfront/response_headers_policy_data_source_test.go
Closes #21832.
```console
% make testacc PKG_NAME=internal/service/cloudfront TESTARGS='-run=TestAccCloudFrontResponseHeadersPolicyDataSource_'
TF_ACC=1 go test ./internal/service/cloudfront/... -v -count 1 -parallel 20 …
```
=> d/aws_cloudfront_response_headers_policy: Add missing `items` level in `custom_headers_config` block

.changelog/20149.txt, internal/service/apprunner/service.go, internal/service/apprunner/service_test.go, website/docs/r/apprunner_service.html.markdown
Copied from #20149 due to Git shenanigans.
Closes #20145
```
$ make testacc TESTS=TestAccAppRunnerService_ PKG= apprunner
--- PASS: TestAccAppRunnerService_disappears (287.45s)
--- PASS: TestAccAppRunnerService_ImageRepository_runtimeEnvironmentVars (292.23s)
--- PASS: TestAccAppRunnerService_ImageRepository_basic (302.72s)
--- PASS: TestAccAppRunnerService_ImageRepository_instance_NoInstanceRole (304.72s)
--- PASS: TestAccAppRunnerService_tags (366.45s)
--- PASS: TestAccAppRunnerService_ImageRepository_autoScaling (436.97s)
--- PASS: TestAccAppRunnerService_ImageRepository_instance_Update (483.29s)
--- PASS: TestAccAppRunnerService_ImageRepository_encryption (528.42s)
--- PASS: TestAccAppRunnerService_ImageRepository_healthCheck (570.65s)
```
=> apprunner/service: Make `instance_role_arn` optional

.changelog/21814.txt, internal/provider/provider.go, internal/service/imagebuilder/filters.go, internal/service/imagebuilder/image_recipes_data_source.go, internal/service/imagebuilder/image_recipes_data_source_test.go, website/docs/d/imagebuilder_image_recipes.html.markdown
Relates #17035.
```
$ make testacc TESTS=TestAccImageBuilderImageRecipesDataSource_owner PKG=imagebuilder
TF_ACC=1 go test ./internal/service/imagebuilder/... -v -count 1 -parallel 20 -run='TestAccImageBuilderImageRecipesDataSource_owner' -timeout 180m
=== RUN …
```
=> d/aws_imagebuilder_image_recipes - new data source

.changelog/12949.txt, internal/conns/conns.go
These crop up when Terraform is performing an operation against a bucket and tries to perform a conflicting operation against the same bucket in parallel. This will allow Terraform to automatically retry instead of having to rerun the Terraform command
Fixes #7628
(don't have the error from Terraform handy but here's what the details look like)
Release note …
=> Retry S3 OperationAborted errors

internal/service/apigatewayv2/authorizer_test.go, internal/service/lambda/function_test.go, internal/service/lambda/layer_version_test.go
Closes #21650.
```console
% make testacc PKG_NAME=internal/service/apigatewayv2 TESTARGS='-run=TestAccAPIGatewayV2Authorizer_'     
TF_ACC=1 go test ./internal/service/apigatewayv2/... -v -count 1 -parallel 20 -run=TestAccAPIGatewayV2Authorizer_ -timeout 180m
=== RUN …
```
=> Acceptance tests: Replace `nodejs10.x` Lambda runtime with `nodejs14.x`

.changelog/21850.txt, internal/provider/provider.go, internal/service/ec2/instance_types_data_source.go, internal/service/ec2/instance_types_data_source_test.go, website/docs/d/ec2_instance_types.html.markdown
Closes https://github.com/hashicorp/terraform-provider-aws/issues/21849
This pr uses code based on the existing `instance_type_offerings` code:
https://github.com/hashicorp/terraform-provider-aws/blob/main/internal/service/ec2/instance_type_offerings_data_source.go
https://github.com/hashicorp/terraform-provider-aws/blob/main/internal/service/ec2/instance_typ …
=> New Data Source: aws_ec2_instance_types

website/docs/r/quicksight_user.html.markdown
Adding some additional context around the documentation update made in https://github.com/hashicorp/terraform-provider-aws/pull/21819. When mutually exclusive arguments are provided, Terraform yields an `InvalidParameterValueException` during a `terraform apply` (no error occurs during a `terraform plan`). The error message is a generic `Invalid resource …
=> Add notes to quicksight_user documentation

.changelog/14764.txt, internal/service/elb/load_balancer.go, internal/service/elb/load_balancer_data_source.go, internal/service/elb/load_balancer_data_source_test.go, internal/service/elb/load_balancer_test.go, internal/service/elbv2/load_balancer.go, internal/service/elbv2/load_balancer_data_source.go, internal/service/elbv2/load_balancer_data_source_test.go, internal/service/elbv2/load_balancer_test.go, website/docs/r/elb.html.markdown, website/docs/r/lb.html.markdown
Closes #14696
```release-note
ENHANCEMENTS:
data-source/aws_elb: Add `desync_mitigation_mode` attribute
data-source/aws_lb: Add `desync_mitigation_mode` attribute
resource/aws_elb: Add `desync_mitigation_mode` attribute
resource/aws_lb: Add …
```
=> aws_elb & aws_lb: Add desync_mitigation_mode

internal/service/kafka/broker_nodes_data_source_test.go, internal/service/kafka/cluster.go, internal/service/kafka/cluster_data_source_test.go, internal/service/kafka/cluster_test.go, internal/service/kafka/configuration_data_source_test.go, internal/service/kafka/configuration_test.go, internal/service/kafka/kafka_version_data_source.go, internal/service/kafka/scram_secret_association_test.go
```console
% make testacc PKG=kafka
TF_ACC=1 go test ./internal/service/kafka/... -v -count 1 -parallel 20  -timeout 180m
--- PASS: TestSortEndpointsString (0.00s)
--- PASS: TestSortEndpointsString/empty (0.00s)
--- PASS: …
```
=> Clean up Kafka/MSK funcs

internal/service/imagebuilder/distribution_configuration.go, internal/service/imagebuilder/distribution_configuration_data_source.go, internal/service/imagebuilder/distribution_configuration_test.go, internal/service/imagebuilder/image.go, internal/service/imagebuilder/image_data_source.go, internal/service/imagebuilder/image_pipeline.go, internal/service/imagebuilder/image_pipeline_data_source.go, internal/service/imagebuilder/image_recipe.go, internal/service/imagebuilder/image_recipe_data_source.go, internal/service/imagebuilder/image_recipe_test.go, internal/service/imagebuilder/image_recipes_data_source_test.go, internal/service/imagebuilder/infrastructure_configuration.go, internal/service/imagebuilder/infrastructure_configuration_data_source.go
Closes #19642
Relates #17137
```console
--- PASS: TestAccImageBuilderComponent_basic (21.37s)
--- PASS: TestAccImageBuilderComponent_changeDescription (23.79s)
--- PASS: TestAccImageBuilderComponent_description (23.02s)
--- PASS: TestAccImageBuilderComponent_disappears (17.76s)
--- PASS: TestAccImageBuilderComponent_kmsKeyID …
```
=> imagebuilder: Allow image recipe to be updated/replaced

examples/two-tier/variables.tf
Small fix for using Ubuntu Bionic 18.04 LTS instead of unsupported 12.04, to avoid a lot of confusing situations
Relates OR Closes #8438
=> Use Ubuntu Bionic 18.04 LTS instead of unsupported 12.04 in two-tier example

.changelog/12018.txt, internal/service/autoscaling/group_waiting.go, internal/service/autoscaling/group_waiting_test.go
When updating an ASG there are currently two ways `capacitySatisfiedUpdate()` might ultimately be called from `resourceAwsAutoscalingGroupUpdate()`:
- `if d.HasChange("min_size")`, and/or
- `if d.HasChange("desired_capacity")`
The existing approach here, only checking against `desired_capacity`, is flawed because that argument is optional while `min_size` is mandatory. If `desired_capacity` is not specified, AWS will automatically [update it](https://docs.aws.amazon.com/autoscaling/ec2/APIReference/API_UpdateAutoScalingGroup.html) to match either `min_size` or `max_size` depending on whether the group is being increased or decreased.
However, the Terraform AWS provider does not predict this behaviour in advance. The new auto-updated value for `desired_capacity` is only detected at the …
=> Fix wait for ASG capacity when increasing min size

website/docs/r/wafv2_web_acl.html.markdown
- If we rate-limit clients, we should **Allow by default, block when rule is matching**
- Add a comment so geographical restriction is explicit
- Use `CLOUDFRONT` for scope to have at least one Cloudfront example for the `scope` parameter
=> wafv2_web_acl doc: Update rate based example

.changelog/21803.txt, internal/service/ssm/association.go, internal/service/ssm/association_test.go, website/docs/r/ssm_association.html.markdown
Closes #21522
I'm unable to run acceptance tests from my machine at this time. I will update the PR once I run them but I also don't want to block the review of the PR.
=> Add output S3 region to AWS SSM since it is now a supported parameter.

.changelog/21015.txt, internal/service/lambda/function_data_source.go, internal/service/lambda/function_data_source_test.go, website/docs/d/lambda_function.html.markdown
Closes #19383
Should I run acceptance tests for this change?
=> add `image_uri` to data source `aws_lambda_function`

.changelog/20707.txt, internal/service/ecs/service.go, internal/service/ecs/service_test.go, website/docs/r/ecs_service.html.markdown
Closes #11351
Original PR https://github.com/hashicorp/terraform-provider-aws/pull/16402 thanks to @m13t
```
...
```
=> Allow ECS Service Capacity Provider Updates

.changelog/19533.txt, internal/service/iam/policy_document_data_source.go, internal/service/iam/policy_document_data_source_test.go
when the conditional values is single value it always cause an update. added the single condition values handling.
Closes #18005
```
╰─ make testacc  TESTARGS='-run=TestAccAWSDataSourceIAMPolicyDocument_' 
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 …
```
=> added single condition values handling

.changelog/21943.txt, internal/service/cloudfront/distribution.go, internal/service/cloudfront/distribution_configuration_structure.go, internal/service/cloudfront/distribution_data_source.go, internal/service/cloudfront/distribution_test.go
Relates OR Closes #15223, #18169
- Not available since there's no acceptance testing for now.
This PR will return a fixed `hosted_zone_id` of Route53 with Cloudfront when the user is operating in the AWS China region.
You can review the guidance provided by AWS CN here: …
=> Return a different cloudfront hosted_zone_id if in AWS CN

.changelog/21963.txt, internal/service/synthetics/canary.go, internal/service/synthetics/canary_test.go, internal/service/synthetics/find.go, website/docs/r/synthetics_canary.html.markdown
```
$ make testacc TESTS=TestAccSyntheticsCanary_ PKG=synthetics
--- PASS: TestAccSyntheticsCanary_disappears (151.63s)
--- PASS: TestAccSyntheticsCanary_s3 (167.12s)
--- PASS: TestAccSyntheticsCanary_artifactEncryption (225.27s)
--- PASS: TestAccSyntheticsCanary_basic (240.57s)
--- PASS: …
```
=> r/synthetics_canary - add `artifact_config` + make `artifact_s3_location` updateble

.changelog/21901.txt, internal/service/s3/bucket.go, internal/service/s3/bucket_replication_configuration.go, internal/service/s3/bucket_replication_configuration_test.go, website/docs/r/s3_bucket_replication_configuration.html.markdown
Closes https://github.com/hashicorp/terraform-provider-aws/issues/21895
```
--- PASS: TestAccS3BucketReplicationConfiguration_schemaV2DestinationMetrics (269.32s)
--- PASS: TestAccS3BucketReplicationConfiguration_multipleDestinationsEmptyFilter (269.11s)
```
=> r/s3_bucket_replication_configuration: make `event_threshold` optional in `destination` `metrics` config block

.changelog/21970.txt, internal/service/elasticache/user_group_test.go
Relates #21970.
Restores bfe20a96cd31cc296ae657cbcd3bdc308a01922b which was overwritten before merge.
```console
% make testacc TESTS=TestAccElastiCacheUserGroup_tags PKG=elasticache
TF_ACC=1 go test ./internal/service/elasticache/... -v -count 1 -parallel 20 …
```
=> Restore bfe20a96cd31cc296ae657cbcd3bdc308a01922b (#21970)

website/docs/r/kinesis_firehose_delivery_stream.html.markdown
Relates #9827 
```release-note
Document kinesis firehose default processing_configuration parameters behaviour.
```
=> Add NOTE about default processing_configuration parameters

.changelog/21990.txt, internal/service/kms/external_key.go, internal/service/kms/external_key_test.go, internal/service/kms/replica_external_key.go, internal/service/kms/replica_external_key_test.go, internal/service/kms/replica_key.go, internal/service/kms/replica_key_test.go, internal/verify/json.go, internal/verify/json_test.go
Related #21968
Related #11801
```
--- PASS: TestAccKMSKey_disappears (22.36s)
--- PASS: TestAccKMSKey_asymmetricKey (25.84s)
--- PASS: TestAccKMSKeyDataSource_basic (26.49s)
--- PASS: TestAccKMSKeyDataSource_multiRegionConfiguration (26.50s)
--- PASS: TestAccKMSKey_multiRegion (29.92s)
--- PASS: …
```
=> kms: Preserve order in JSON/policies

.changelog/21888.txt, internal/service/account/alternate_contact.go, internal/service/account/alternate_contact_test.go, website/docs/r/account_alternate_contact.html.markdown
Thank to @shedimon for previous PR: https://github.com/hashicorp/terraform-provider-aws/pull/21789, this is my change to add support for managing member accounts in an AWS organization.
Relates #21118
```
make testacc TESTARGS='-run=TestAccAccountAlternateContact' PKG_NAME="internal/service/account" …
```
=> Add account_id for aws_account_alternate_contact to manage member accounts in an AWS organization

.changelog/21997.txt, internal/service/s3/bucket.go, internal/service/s3/bucket_policy.go, internal/service/s3/bucket_policy_test.go
Related #21968
Related #11801
Fixes #13144
Closes #20456
```
--- PASS: TestAccS3Bucket_Security_policy (78.33s)
--- PASS: TestAccS3BucketPolicy_basic (28.25s)
--- PASS: TestAccS3BucketPolicy_policyUpdate (46.54s)
--- PASS: TestAccS3BucketPolicy_IAMRoleOrder_policyDoc (75.62s)
--- PASS: …
```
=> s3: Preserve order in JSON/policy arrays

.changelog/22004.txt, internal/service/ecr/errorcheck_test.go, internal/service/ecr/registry_policy.go, internal/service/ecr/registry_policy_test.go, internal/service/ecr/repository_policy.go, internal/service/ecr/repository_policy_test.go, internal/service/iam/role.go, internal/service/iam/wait.go
Closes #19365
Closes #8905
Closes #22018
Related #21968
Related #11801
```
--- PASS: TestAccECRRepositoryPolicy_Disappears_repository (12.51s)
--- PASS: TestAccECRRepositoryPolicy_disappears (14.07s)
--- PASS: TestAccECRRepositoryPolicy_IAM_basic (26.41s)
--- PASS: TestAccECRRepositoryPolicy_basic (27.86s)
--- …
```
=> ecr: Preserve/ignore order in JSON/policy

website/docs/r/vpc_ipv6_cidr_block_association.html.markdown
Relates OR Closes #22014
```
...
```
=> Docs update for aws_vpc_ipv6_cidr_block_association inaccuracies

.changelog/21954.txt, internal/service/sqs/queue.go, internal/service/sqs/queue_test.go, website/docs/r/sqs_queue.html.markdown
Closes #21948 -- add support for SSE-SQS for the `aws_sqs_queue` resource.
```
$ make testacc TESTS=TestAccSQSQueue_encryption PKG=sqs
TF_ACC=1 go test ./internal/service/sqs/... -v -count 1 -parallel 20 -run='TestAccSQSQueue_encryption' -timeout 180m
=== RUN …
```
=> add support for SQS-managed SSE

.changelog/21882.txt, internal/service/cloudtrail/cloudtrail.go, internal/service/cloudtrail/cloudtrail_test.go
```
$ make testacc TESTARGS='-run=TestAccCloudTrail_serial/Trail' PKG_NAME=internal/service/cloudtrail
--- PASS: TestAccCloudTrail_serial/Trail/basic (238.57s)
--- PASS: TestAccCloudTrail_serial/Trail/kmsKey (130.22s)
--- PASS: TestAccCloudTrail_serial/Trail/tags (360.89s)
--- PASS: …
```
=> r/cloudtrail - add validations + tests

internal/service/servicequotas/acc_test.go, internal/service/servicequotas/find.go, internal/service/servicequotas/service_quota.go, internal/service/servicequotas/service_quota_data_source.go, internal/service/servicequotas/service_quota_data_source_test.go, internal/service/servicequotas/service_quota_test.go, website/docs/d/servicequotas_service_quota.html.markdown
When a Service Quota has not been set, the API call `GetServiceQuota` returns a not found error. The default value can be retrieved using `GetAWSDefaultServiceQuota` or `ListAWSDefaultServiceQuotas`. This PR updates the resource and data source to retrieve the default value first and not fail when the quota has not been set.
Closes #19745
Closes #10929
```console
$ make testacc TESTS='TestAccServiceQuotasServiceQuotaDataSource_\|TestAccServiceQuotasServiceQuota_basic' PKG=servicequotas
--- SKIP: TestAccServiceQuotasServiceQuotaDataSource_PermissionError_quotaName (1.57s)
--- SKIP: TestAccServiceQuotasServiceQuotaDataSource_PermissionError_quotaCode (1.71s)
--- PASS: TestAccServiceQuotasServiceQuotaDataSource_quotaCode_Unset (67.23s)
--- PASS: …
```
=> Fixes initial setup for Service Quota resource and data source

.changelog/21937.txt, internal/service/lambda/event_source_mapping.go, internal/service/lambda/event_source_mapping_test.go, website/docs/r/lambda_event_source_mapping.html.markdown
Closes #21921
The AWS SDK commit will be rebased over once that's been merged to main.
```
$ make testacc TESTS=TestAccLambdaEventSourceMapping_Kinesis_ PKG=lambda && make testacc TESTS=TestAccLambdaEventSourceMapping_SQS_ PKG=lambda && make testacc TESTS=TestAccLambdaEventSourceMapping_DynamoDB_ PKG=lambda
==> Checking that …
```
=> r/aws_lambda_event_source_mapping: add filter_criteria attribute

.changelog/22021.txt, internal/flex/flex.go, internal/service/backup/region_settings.go, internal/service/backup/region_settings_test.go, website/docs/r/backup_region_settings.html.markdown
Closes #22012
Release note for [CHANGELOG](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md):
```release-note:enhancement
resource/aws_backup_region_settings: Add resource_type_management_preference argument
```
```
$ make testacc TESTS=TestAccBackupRegionSettings PKG=backup …
```
=> r/aws_backup_region_settings: Add `ResourceTypeManagementPreference`

.semgrep.yml, internal/service/amp/workspace.go, internal/service/apigateway/api_key.go, internal/service/apigateway/authorizer.go, internal/service/apigateway/base_path_mapping.go, internal/service/apigateway/client_certificate.go, internal/service/apigateway/deployment.go, internal/service/apigateway/documentation_part.go, internal/service/apigateway/documentation_version.go, internal/service/apigateway/domain_name.go, internal/service/apigateway/gateway_response.go, internal/service/apigateway/integration.go, internal/service/apigateway/integration_response.go, internal/service/apigateway/method.go, internal/service/apigateway/method_response.go, internal/service/apigateway/model.go, internal/service/apigateway/request_validator.go, internal/service/apigateway/resource.go, internal/service/apigateway/rest_api.go, internal/service/apigateway/rest_api_policy.go, internal/service/apigateway/stage.go, internal/service/apigateway/usage_plan.go, internal/service/apigateway/usage_plan_key.go, internal/service/apigateway/vpc_link.go, internal/service/opsworks/layers.go, internal/service/opsworks/stack_test.go
Implements `d.IsNewResource()` Check in Read functions for OpsWorks Layers and API Gateway (v1) resources
Relates #16796
```
$ make testacc TESTARGS='-run=TestAccAWSAPIGatewayDomainName\|TestAccAWSAPIGatewayIntegration\|TestAccAWSAPIGatewayApiKey\|TestAccAWSAPIGatewayRequestValidator\|TestAccAWSAPIGatewayStage\|TestAccAWSAPIGatewayUsagePlanKey\|TestAccAWSAPIGatewayDocumentationVersion\|TestAccAWSAPIGatewayRestApi\|TestAccAWSAPIGatewayBasePathMapping\|TestAccAWSAPIGatewayIntegrationResponse\|TestAccAWSAPIGatewayMethodResponse\|TestAccAWSAPIGatewayMethodSettings\|TestAccAWSAPIGatewayDeployment\|TestAccAWSAPIGatewayModel\|TestAccAWSAPIGatewayGatewayResponse\|TestAccAWSAPIGatewayMethod\|TestAccAWSAPIGatewayUsagePlan\|TestAccAWSAPIGatewayDocumentationPart\|TestAc …
```
=> Implements `d.IsNewResource()` Check in Read functions for OpsWorks Layers and API Gateway (v1) resources

.changelog/22026.txt, internal/service/s3/bucket_replication_configuration_test.go, internal/service/s3/flex.go
Closes https://github.com/hashicorp/terraform-provider-aws/issues/21961
```
--- PASS: TestAccS3BucketReplicationConfiguration_basic (408.01s)
--- PASS: TestAccS3BucketReplicationConfiguration_configurationRuleDestinationAccessControlTranslation (399.27s)
--- PASS: TestAccS3BucketReplicationConfiguration_configurationRuleDestina …
```
=> r/s3_bucket_replication_configuration: ensure rule can be created without specifying `prefix` or `filter`

internal/service/ds/directory.go
There is a propagation delay for unregistering applications from the Directory Service directory. This PR adds a retry when `aws_directory_service_directory` still has authorized applications.
Relates #20556
Before the change
```console
$ make testacc TESTS='TestAccConnectInstance_serial/directory' PKG=connect TEST_COUNT=3
=== RUN   TestAccConnectInstance_serial
=== RUN   TestAccConnectInstance_serial/directory
--- PASS: TestAccConnectInstance_serial (913.19s)
--- PASS: TestAccConnectInstance_serial/directory (913.19s)
=== RUN   TestAccConnectInstance_serial
=== RUN   TestAccConnectInstance_serial/directory
testing_new.go:70: Error running post-test destroy, there may be dangling resources: exit status 1
Error: error deleting Directory Service Directory (d-9267770990): ClientException: …
```
=> resource/aws_directory_service_directory: Adds retry when directory still has authorized applications

.tflint.hcl
Relates #22039.
[`tflint-ruleset-aws@0.10.0`](https://github.com/terraform-linters/tflint-ruleset-aws/releases/tag/v0.10.0) is now available.
Upgrade the relevant linters.
```
...
```
=> Upgrade to v0.10.0 of `tflint-ruleset-aws`

.semgrep.yml, internal/service/autoscaling/launch_configuration.go, internal/service/cloudfront/distribution_configuration_structure.go, internal/service/dms/certificate.go, internal/service/ds/directory.go, internal/service/dynamodb/table.go, internal/service/elastictranscoder/pipeline.go, internal/service/elastictranscoder/preset.go, internal/service/fsx/ontap_volume.go, internal/service/gamelift/fleet.go, internal/service/glue/resource_policy.go, internal/service/guardduty/ipset.go, internal/service/guardduty/threatintelset.go, internal/service/iam/access_key.go, internal/service/iam/user.go, internal/service/iot/certificate.go, internal/service/kms/grant.go, internal/service/lambda/flex.go, internal/service/neptune/parameter_group.go, internal/service/opsworks/layers.go, internal/service/opsworks/stack.go, internal/service/organizations/account.go, internal/service/securityhub/invite_accepter.go, internal/service/ssm/resource_data_sync.go
Re-enables Semgrep rule `prefer-aws-go-sdk-pointer-conversion-conditional`
Relates #20000
```
$ make testacc TESTS=TestAccSSMResourceDataSync|TestAccOpsWorksStack|TestAccDynamoDBTable|TestAccAutoScalingLaunchConfiguration|TestAccDMSCertificate|TestAccElasticTranscoderPipeline|TestAccKMSGrant|TestAccElasticTranscoderPreset|TestAccFSxOntapVolume|TestAccIAMAccessKey|TestAccNeptuneParameterGroup|TestAccDirectoryServiceDirectory|TestAccGameLiftFleet|TestAccIAMUser|TestAccIoTCertificate
--- SKIP: TestAccAutoScalingLaunchConfiguration_withVPCClassicLink (2.69s)
--- PASS: TestAccAutoScalingLaunchConfigurationDataSource_ebsNoDevice (122.52s)
--- PASS: TestAccAutoScalingLaunchConfigurationDataSource_basic (123.89s)
--- PASS: …
```
=> Re-enables Semgrep rule `prefer-aws-go-sdk-pointer-conversion-conditional`

.changelog/22067.txt, go.mod, go.sum, internal/service/iam/group_policy.go, internal/service/iam/group_policy_test.go, internal/service/iam/policy.go, internal/service/iam/policy_test.go, internal/service/iam/role.go, internal/service/iam/role_policy.go, internal/service/iam/role_policy_test.go, internal/service/iam/role_test.go, internal/service/iam/user_policy.go, internal/service/iam/user_policy_test.go
Relates #21968
Relates #19444
Releates hashicorp/awspolicyequivalence#7
```
--- PASS: TestAccIAMPolicy_disappears (16.22s)
--- PASS: TestAccIAMPolicy_description (23.95s)
--- PASS: TestAccIAMPolicy_namePrefix (23.97s)
--- PASS: TestAccIAMPolicy_path (23.97s)
--- PASS: TestAccIAMPolicy_basic (23.98s)
--- PASS: …
```
=> IAM: Only set policy if actually changed

.changelog/22080.txt, internal/service/redshift/cluster.go
Adds retries to actions that enable or disable the redshift cluster's logging when returned the error code "InvalidClusterState".
Closes #21815
```
TF_ACC=1 go test ./internal/service/redshift -v -count 1 -parallel 20 -run=TestAccRedshiftCluster_loggingEnabled -timeout 180m
=== RUN   TestAccRedshiftCluster_loggingEnabled
=== …
```
=> b/aws_redshift_cluster: Adds retries to enabling and disabling the redshift cluster's logging

.changelog/21855.txt, internal/provider/provider.go, internal/service/ec2/sweep.go, internal/service/emr/find.go, internal/service/emr/managed_scaling_policy_test.go, internal/service/emr/studio.go, internal/service/emr/studio_test.go, internal/service/emr/sweep.go, website/docs/r/emr_studio.html.markdown
Closes #20597.
```
$ make testacc TESTS=TestAccEMRStudio_ PKG=emr
--- PASS: TestAccEMRStudio_disappears (79.81s)
--- PASS: TestAccEMRStudio_sso (85.61s)
--- PASS: TestAccEMRStudio_tags (201.09s)
--- PASS: TestAccEMRStudio_iam (109.14s)
```
=> r/emr studio - new resource

.changelog/22072.txt, internal/service/elbv2/load_balancer.go
Closes https://github.com/hashicorp/terraform-provider-aws/issues/22037
Output from acceptance testing before code change (`us-gov-east-1`): _Test tf config does not explicitly configure `enable_waf_fail_open`_
```
=== RUN   TestAccELBV2LoadBalancer_ALB_basic
=== PAUSE TestAccELBV2LoadBalancer_ALB_basic
=== CONT  TestAccELBV2LoadBalancer_ALB_basic …
```
=> r/alb: on create, only modify `enable_waf_fail_open` argument if change is present

.changelog/22077.txt, internal/service/appstream/image_builder.go, internal/service/appstream/image_builder_test.go
Closes #22065 
```
--- PASS: TestAccAppStreamImageBuilder_imageARN (762.97s)
```
=> r/appstream_image_builder: create with `image_arn` if configured

.changelog/22016.txt, internal/service/ecs/task_definition.go, internal/service/ecs/task_definition_test.go, website/docs/r/ecs_task_definition.html.markdown
Adds platform runtime properties and validation based on https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task_definition_parameters.html
```
runtime_platform {
operating_system_family = "WINDOWS_SERVER_2019_CORE"
cpu_architecture = "X86_64"
}
```
Adds documentation for new fields (but no new examples; I'd happily add examples for windows fargate if its wanted, I didn't want to bloat the document)
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull …
=> r/ecs - Add support for FARGATE Windows Containers and ARM based Containers

internal/service/kms/key_test.go
Closes #21225.
Before merge of #22067 and  hashicorp/awspolicyequivalence@1.4.0:
```console
% make testacc TESTARGS='-run=TestAccKMSKey_Policy_booleanCondition' PKG_NAME=internal/service/kms
TF_ACC=1 go test ./internal/service/kms/... -v -count 1 -parallel 20 …
```
=> r/aws_kms_key: Add acceptance test for policy with boolean condition

.semgrep.yml
Restores the Semgrep check for domain names
Relates #20000
N/A
=> linter/semgrep: Restore domain name check

.changelog/22096.txt, internal/provider/provider.go, internal/service/ecs/flex.go, internal/service/ecs/status.go, internal/service/ecs/task_set.go, internal/service/ecs/task_set_test.go, internal/service/ecs/wait.go, website/docs/r/ecs_task_set.html.markdown
Closes https://github.com/hashicorp/terraform-provider-aws/pull/13651 
Closes https://github.com/hashicorp/terraform-provider-aws/issues/8124
Continues the work in https://github.com/hashicorp/terraform-provider-aws/pull/13651
```
--- PASS: TestAccECSTaskSet_Tags (107.55s)
--- PASS: TestAccECSTaskSet_basic …
```
=> feat: add `aws_ecs_task_set` resource

.changelog/22100.txt, internal/service/efs/file_system_policy.go, internal/service/efs/file_system_policy_test.go
Relates #21968
Fixes #19245
```console
% make testacc TESTS=TestAccEFSFileSystemPolicy PKG=efs                            
TF_ACC=1 go test ./internal/service/efs/... -v -count 1 -parallel 20 -run='TestAccEFSFileSystemPolicy' -timeout 180m
--- PASS: TestAccEFSFileSystemPolicy_disappears (26.35s)
--- PASS: …
```
=> efs/file_system_policy: Fix diffs with equivalent policies

.changelog/22099.txt, internal/service/iam/role.go, internal/service/iam/role_test.go, website/docs/r/iam_role.html.markdown
Relates #21968
Fixes #19444
```console
% make testacc TESTS=TestAccIAMRole PKG=iam
TF_ACC=1 go test ./internal/service/iam/... -v -count 1 -parallel 20 -run='TestAccIAMRole' -timeout 180m
--- PASS: TestAccIAMRolePolicy_invalidJSON (4.27s)
--- PASS: TestAccIAMRolesDataSource_nonExistentPathPrefix (23.85s)
--- …
```
=> iam/role: Fix spurious diffs with inline_policy ordering

.changelog/22119.txt, internal/service/ecs/cluster.go, internal/service/ecs/cluster_data_source.go, internal/service/ecs/cluster_test.go, internal/service/ecs/find.go, internal/service/ecs/status.go
Relates #20720.
Continual CI failure:
```
=== RUN   TestAccECSClusterDataSource_ecsClusterContainerInsights
=== PAUSE TestAccECSClusterDataSource_ecsClusterContainerInsights
=== CONT  TestAccECSClusterDataSource_ecsClusterContainerInsights
cluster_data_source_test.go:42: Step 1/1 error: Check failed: Check 6/6 error: data.aws_ecs_cluster.test: Attribute …
```
=> tests/d/aws_ecs_cluster: Fix 'Attribute "setting.#" not set, but "setting.#" is set in aws_ecs_cluster.test as "1"'

internal/service/lambda/function_test.go
Relates #21752.
Relates #22118.
Continual CI failure:
```
=== RUN   TestAccLambdaFunction_runtimes
=== PAUSE TestAccLambdaFunction_runtimes
=== CONT  TestAccLambdaFunction_runtimes
function_test.go:1991: Step 2/20 error: Error running apply: exit status 1
Error: error creating Lambda Function (1): InvalidParameterValueException: The runtime parameter of …
```
=> test/lambda: Fix TestAccLambdaFunction_runtimes

.changelog/22115.txt, internal/service/apigateway/rest_api.go, internal/service/apigateway/rest_api_policy.go, internal/service/apigateway/rest_api_policy_test.go, internal/service/apigateway/rest_api_test.go
Relates #21968
```console
% make testacc TESTS=TestAccAPIGatewayRestAPI PKG=apigateway
TF_ACC=1 go test ./internal/service/apigateway/... -v -count 1 -parallel 20 -run='TestAccAPIGatewayRestAPI' -timeout 180m
--- PASS: TestAccAPIGatewayRestAPI_Endpoint_private (21.93s)
--- PASS: TestAccAPIGatewayRestAPI_Policy_setByBody …
```
=> apigateway/rest_api: Fix diffs from equivalent policies

internal/service/apigatewayv2/integration_test.go
Relates #21752.
CI failures:
```
=== RUN   TestAccAPIGatewayV2Integration_lambdaWebSocket
=== PAUSE TestAccAPIGatewayV2Integration_lambdaWebSocket
=== CONT  TestAccAPIGatewayV2Integration_lambdaWebSocket
integration_test.go:307: Step 1/2 error: Error running apply: exit status 1
Error: error creating Lambda Function (1): InvalidParameterValueException: The …
```
=> r/aws_apigatewayv2_integration: Use `nodejs14.x` Lambda runtime

.changelog/22130.txt, internal/service/backup/vault_policy.go, internal/service/backup/vault_policy_test.go
Relates #21968
```
--- PASS: TestAccBackupVaultPolicy_Disappears_vault (13.00s)
--- PASS: TestAccBackupVaultPolicy_disappears (14.99s)
--- PASS: TestAccBackupVaultPolicy_ignoreEquivalent (22.13s)
--- PASS: TestAccBackupVaultPolicy_basic (27.20s)
```
Output from acceptance testing (`GovCloud`):
```
--- PASS: …
```
=> backup/vault_policy: Fix diffs with equivalent policies

.changelog/22135.txt, internal/service/cloudwatchlogs/resource_policy.go, internal/service/cloudwatchlogs/resource_policy_test.go
```console
% make testacc TESTS=TestAccCloudWatchLogsResourcePolicy_ PKG=cloudwatchlogs
TF_ACC=1 go test ./internal/service/cloudwatchlogs/... -v -count 1 -parallel 20 -run='TestAccCloudWatchLogsResourcePolicy_' -timeout 180m
--- PASS: …
```
=> logs/resource_policy: Fix equivalent policy diffs

.changelog/22136.txt, internal/service/codeartifact/codeartifact_test.go, internal/service/codeartifact/domain_permissions_policy.go, internal/service/codeartifact/domain_permissions_policy_test.go, internal/service/codeartifact/repository_permissions_policy.go, internal/service/codeartifact/repository_permissions_policy_test.go
Relates #21968
```console
% make testacc TESTS="TestAccCodeArtifact_serial/RepositoryPermissionsPolicy" PKG=codeartifact
TF_ACC=1 go test ./internal/service/codeartifact/... -v -count 1 -parallel 20 …
```
=> codeartifact/permissions_policy: Fix equivalent policy diffs

.changelog/22137.txt, internal/service/ec2/vpc_endpoint.go, internal/service/ec2/vpc_endpoint_test.go
Relates #21968
```console
% make testacc TESTS=TestAccEC2VPCEndpoint_ PKG=ec2
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 20 -run='TestAccEC2VPCEndpoint_' -timeout 180m
--- PASS: TestAccEC2VPCEndpoint_disappears (36.26s)
--- PASS: …
```
=> ec2/vpc_endpoint: Fix erroneous diffs with equivalent policies

.changelog/22140.txt, internal/provider/provider.go, internal/service/emr/find.go, internal/service/emr/id.go, internal/service/emr/studio_session_mapping.go, internal/service/emr/studio_session_mapping_test.go, internal/service/emr/sweep.go, website/docs/r/emr_studio_session_mapping.html.markdown
```
$ make testacc TESTS=TestAccEMRStudioSessionMapping_ PKG=emr
--- PASS: TestAccEMRStudioSessionMapping_disappears (95.15s)
--- PASS: TestAccEMRStudioSessionMapping_basic (163.24s)
```
=> r/emr_studio_session_mapping - new resource

internal/service/s3/bucket.go, internal/service/s3/object_copy.go, internal/service/s3/validate.go, website/docs/r/s3_bucket.html.markdown, website/docs/r/s3_bucket_object.html.markdown, website/docs/r/s3_bucket_replication_configuration.html.markdown, website/docs/r/s3_object_copy.html.markdown, website/docs/r/storagegateway_nfs_file_share.html.markdown, website/docs/r/storagegateway_smb_file_share.html.markdown
This PR moves hardcoded names of S3 storage classes to:
* Code: Enums provided by the SDK
* Docs: Links to the appropriate AWS docs
There are subtle differences between the available storage classes in different situations so each enum/link is specific to the resource where it's used. This makes it easier for the provider to fully support new storage …
=> `s3`: reference storage classes from SDK and AWS docs

.changelog/22142.txt, internal/service/ecr/lifecycle_policy.go, internal/service/ecr/lifecycle_policy_test.go
Relates #21968
Relates #22004
```console
% make testacc TESTS=TestAccECRLifecyclePolicy_ PKG=ecr
TF_ACC=1 go test ./internal/service/ecr/... -v -count 1 -parallel 20 -run='TestAccECRLifecyclePolicy_' -timeout 180m
--- PASS: TestAccECRLifecyclePolicy_basic …
```
=> ecr/lifecycle_policy: Fix diffs when policy equivalent

.changelog/22157.txt, internal/flex/flex.go, internal/service/apigatewayv2/integration.go, internal/service/apigatewayv2/integration_response.go, internal/service/apigatewayv2/route.go, internal/service/apigatewayv2/route_response.go, internal/service/apigatewayv2/stage.go, internal/service/cloudwatchlogs/metric_filter.go, internal/service/ecs/task_definition.go, internal/service/elasticsearch/domain.go, internal/service/elasticsearch/domain_data_source.go, internal/service/elasticsearch/domain_policy.go, internal/service/elasticsearch/domain_policy_test.go, internal/service/elasticsearch/domain_saml_options_test.go, internal/service/elasticsearch/domain_test.go, internal/service/kinesisanalyticsv2/application.go, internal/service/kms/grant.go, internal/service/s3/bucket_object.go, internal/service/s3/bucket_object_data_source.go, internal/service/s3/object_copy.go, internal/verify/diff_test.go, internal/verify/json.go, internal/verify/verify.go
Relates #21968
Fixes #21318
```console
% make testacc TESTS=TestAccElasticsearchDomainPolicy_basic PKG=elasticsearch
TF_ACC=1 go test ./internal/service/elasticsearch/... -v -count 1 -parallel 20 -run='TestAccElasticsearchDomainPolicy_basic' -timeout 180m …
```
=> elasticsearch/domain: Fix erroneous/perpetual diffs

.changelog/21960.txt, internal/service/fsx/backup.go, internal/service/fsx/backup_test.go, website/docs/r/fsx_backup.html.markdown
Closes #20778
```
$ make testacc TESTARGS='-run=TestAccFSxBackup' PKG_NAME=internal/service/fsx
--- PASS: TestAccFSxBackup_disappears (539.93s)
--- PASS: TestAccFSxBackup_basic (555.49s)
--- PASS: TestAccFSxBackup_Disappears_filesystem (558.67s)
--- PASS: TestAccFSxBackup_implicitTags (777.16s)
--- PASS: TestAccFSxBackup_tags …
```
=> FSx Backup Volume addition

.changelog/21983.txt, internal/service/sagemaker/prebuilt_ecr_image_data_source.go
This PR adds the [Hugging Face DLCs](https://github.com/aws/deep-learning-containers/tree/master/huggingface) to the `aws_sagemaker_prebuilt_ecr_image` data source. The Hugging Face DLCs include flavors for TensorFlow and PyTorch with Training and Inference Containers. I checked the region account mapping. 
example
```hcl
data "aws_sagemaker_prebuilt_ecr_image" "test" {
repository_name = "huggingface-pytorch-inference"
image_tag       = "1.7.1-transformers4.6.1-gpu-py36-cu110-ubuntu18.04"
}
```
I hope the `.changelog` is correct. 
* Please do not …
=> Add Hugging Face DLC images to sagemaker pre-built ecr image

website/docs/r/s3_bucket_policy.html.markdown
Change the docs on the `aws_s3_bucket_policy` resource example so that:
- Instead of using the `jsonencode` function, it uses the `aws_iam_policy_document` data source
- Change the policy attached to be a bit simpler and easier to understand
Also, update the docs on the `policy` member of the resource to suggest using the `aws_iam_policy_document` data source.
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the …
=> Clean up docs on aws_s3_bucket_policy

.changelog/19292.txt, internal/service/dynamodb/table.go, internal/service/dynamodb/table_test.go, website/docs/r/dynamodb_table.html.markdown
Relates OR Closes #4558
```
$ make testacc TESTARGS='-run=TestAccAWSDynamoDbTable_backup_encryption'
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSDynamoDbTable_backup_encryption -timeout 180m
=== RUN   TestAccAWSDynamoDbTable_backup_encryption
=== PAUSE TestAccAWSDynamoDbTable_backup_encryption
=== CONT …
```
=> F/resource aws dynamodb table: restore from point in time

.changelog/22172.txt, internal/provider/provider.go, internal/service/ecr/find.go, internal/service/ecr/pull_through_cache_rule.go, internal/service/ecr/pull_through_cache_rule_test.go, website/docs/r/ecr_pull_through_cache_rule.html.markdown
Closes https://github.com/hashicorp/terraform-provider-aws/issues/21951
Implementation of `registry_id` follows the same pattern as `aws_ecr_repository`.
```
$ make testacc PKG=ecr TESTS=TestAccPullThroughCacheRule_
TF_ACC=1 go test ./internal/service/ecr/... -v -count …
```
=> New Resource: aws_ecr_pull_through_cache_rule

.changelog/22179.txt, internal/provider/provider.go, internal/service/ecr/registry_scanning_configuration.go, internal/service/ecr/registry_scanning_configuration_test.go, website/docs/r/ecr_registry_scanning_configuration.html.markdown
Closes #21964 
```
$ make testacc TESTS=TestAccECRScanningConfiguration_serial PKG=ecr (main|✔)
TF_ACC=1 go test ./internal/service/ecr/... -v -count 1 -parallel 20 -run='TestAccECRScanningConfiguration_serial' -timeout 180m
=== RUN …
```
=> New resource: ECR registry scanning configuration

.changelog/22165.txt, internal/service/events/bus_policy.go, internal/service/events/bus_policy_test.go
Relates #21968
```console
% make testacc TESTS=TestAccEventsBusPolicy_ PKG=events 
TF_ACC=1 go test ./internal/service/events/... -v -count 1 -parallel 20 -run='TestAccEventsBusPolicy_' -timeout 180m
--- PASS: TestAccEventsBusPolicy_ignoreEquivalent …
```
=> events/bus_policy: Fix diffs with policy

.changelog/22166.txt, internal/service/glacier/vault.go, internal/service/glacier/vault_lock.go, internal/service/glacier/vault_lock_test.go, internal/service/glacier/vault_test.go
```console
% make testacc TESTS=TestAccGlacierVaultLock PKG=glacier
TF_ACC=1 go test ./internal/service/glacier/... -v -count 1 -parallel 20 -run='TestAccGlacierVaultLock' -timeout 180m
--- PASS: TestAccGlacierVaultLock_basic (20.78s)
--- …
```
=> glacier/vault: Fix spurious policy diffs

.changelog/22167.txt, internal/service/glue/data_catalog_encryption_settings_data_source_test.go, internal/service/glue/data_catalog_encryption_settings_test.go, internal/service/glue/glue_test.go, internal/service/glue/resource_policy.go, internal/service/glue/resource_policy_test.go
```console
% make testacc TESTS="TestAccGlue_serial/ResourcePolicy" PKG=glue 
TF_ACC=1 go test ./internal/service/glue/... -v -count 1 -parallel 20 -run='TestAccGlue_serial/ResourcePolicy' -timeout 180m
--- PASS: TestAccGlue_serial …
```
=> glue/resource_policy: Fix diffs with equivalent policies

.changelog/22169.txt, internal/service/iot/policy.go
```console
% make testacc TESTS=TestAccIoTPolicy_basic PKG=iot
TF_ACC=1 go test ./internal/service/iot/... -v -count 1 -parallel 20 -run='TestAccIoTPolicy_basic' -timeout 180m
--- PASS: TestAccIoTPolicy_basic (16.54s)
PASS
ok …
```
=> iot/policy: Fix diffs with equivalent policies

.changelog/22170.txt, internal/service/mediastore/container_policy.go, internal/service/mediastore/container_policy_test.go
Relates #21968
```console
% make testacc TESTS=TestAccMediaStoreContainerPolicy_basic PKG=mediastore
TF_ACC=1 go test ./internal/service/mediastore/... -v -count 1 -parallel 20 -run='TestAccMediaStoreContainerPolicy_basic' -timeout 180m
--- PASS: …
```
=> mediastore/container_policy: Fix equivalent policy diffs

.changelog/22171.txt, internal/service/networkfirewall/resource_policy.go, internal/service/networkfirewall/resource_policy_test.go
Relates #21968
(For failure, see #22174)
```console
--- FAIL: TestAccNetworkFirewallResourcePolicy_disappears (11.17s) (* failing prior to this PR)
--- PASS: TestAccNetworkFirewallResourcePolicy_ignoreEquivalent (146.07s)
--- PASS: TestAccNetworkFirewallResourcePolicy_basic (148.90s)
--- PASS: …
```
=> networkfirewall/resource_policy: Fix equivalent policy diffs

internal/service/dms/endpoint.go, internal/service/dms/endpoint_test.go, website/docs/r/dms_endpoint.html.markdown
Closes #18123
```
$ make testacc TESTARGS='-run=TestAccAwsDmsEndpoint_OracleDb'
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAwsDmsEndpoint_OracleDb -timeout 180m
=== RUN   TestAccAwsDmsEndpoint_OracleDb
=== PAUSE TestAccAwsDmsEndpoint_OracleDb
=== RUN   TestAccAwsDmsEndpoint_OracleDb_SecretId
=== PAUSE …
```
=> f/resource_aws_dms_endpoint: support for secrets id for oracle and postgres

website/docs/r/dms_replication_instance.html.markdown
The docs for `aws_dms_replication_instance` are outdated and state that there are only a few available instance sizes. There are now way more available instance sizes for this, so it's probably best to just refer the user to the AWS docs.
```
$ aws dms describe-orderable-replication-instances | jq -r …
```
=> Update outdated docs on DMS instance sizes

.golangci.yml
* `Terraform Provider` Github actions workflows often error out during the `golangci-lint` job after exceeding the 20min run timeout e.g. https://github.com/hashicorp/terraform-provider-aws/runs/4513217734?check_suite_focus=true
```
N/A
```
=> fix: increase golanci timeout to 25m

.changelog/22193.txt, internal/service/transfer/access.go, internal/service/transfer/user.go
Relates #21968
```console
% make testacc TESTS="TestAccTransfer_serial/User" PKG=transfer
TF_ACC=1 go test ./internal/service/transfer/... -v -count 1 -parallel 20 -run='TestAccTransfer_serial/User' -timeout 180m
--- PASS: TestAccTransfer_serial (995.77s) …
```
=> transfer: Fix erroneous diffs with user and access policies

.changelog/22192.txt, internal/service/ssoadmin/permission_set_inline_policy.go
Relates #21968
```
--- SKIP: TestAccSSOAdminPermissionSetInlinePolicy_basic (1.47s)
```
```
--- SKIP: TestAccSSOAdminPermissionSetInlinePolicy_basic (2.03s)
```
=> ssoadmin/permission_set_inline_policy: Fix errorneous diffs

website/docs/r/appstream_fleet.html.markdown
The default values as listed in the [documentation](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/appstream_fleet) produce the following error:
`"Error - expected idle_disconnect_timeout_in_seconds to be in the range (60 - 3600), got 15"`
**Given** idle_disconnect_timeout_in_seconds
**When** value is 15
**Then** minimum value should be 60
**Otherwise error:** "Error - expected idle_disconnect_timeout_in_seconds to be in the range (60 - 3600), got 15"
* Please do not leave "+1" or other comments that do not add …
=> fix: Error - expected idle_disconnect_timeout_in_seconds to be in the range (60 - 3600), got 15

website/docs/d/iam_policy_document.html.markdown
iam statements must include either Resource or NotResource element as specified [AWS docs: IAM JSON policy elements: Resource](https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements_resource.html) which mentions "Statements must include either a Resource or a NotResource element. You specify a resource using an ARN."
Relates #21836
=> docs: iam statement Resource, NotResource conflict

.changelog/22194.txt, internal/service/sqs/queue.go, internal/service/sqs/queue_policy.go, internal/service/sqs/queue_test.go, internal/service/sqs/status.go, internal/service/sqs/wait.go
Relates #21968
Fixes #19836
Fixes #20333
**NOTE:** These changes will make SQS configurations take a little longer to apply. However, because SQS has such trouble with eventual consistency, the extra time is needed to improve consistency.
I ran each test 10X in 3 different regions. Unfortunately, these changes _do not_ perfectly fix all eventual consistency …
=> sqs: Fix diffs with policies

.changelog/22213.txt, internal/service/sns/topic.go, internal/service/sns/topic_policy.go, internal/service/sns/topic_policy_test.go
Relates #21968
```console
% make testacc TESTS=TestAccSNSTopicPolicy_ PKG=sns                
TF_ACC=1 go test ./internal/service/sns/... -v -count 1 -parallel 20 -run='TestAccSNSTopicPolicy_' -timeout 180m
--- PASS: TestAccSNSTopicPolicy_Disappears_topic …
```
=> sns/topic: Fix diffs with policies

.changelog/22221.txt, internal/service/s3/bucket.go, internal/service/s3/bucket_test.go
Closes https://github.com/hashicorp/terraform-provider-aws/issues/4494
```
--- PASS: TestAccS3Bucket_Basic_basic (92.94s)
--- PASS: TestAccS3Bucket_Manage_versioning (177.77s)
--- PASS: TestAccS3Bucket_Manage_versioningAndMfaDeleteDisabled (90.48s)
--- PASS: TestAccS3Bucket_Manage_versioningDisabled (93.08s)
--- PASS: …
```
=> r/s3_bucket: handle `versioning` configuration when explicitly disabled

.changelog/12578.txt, internal/service/emr/cluster.go, internal/service/emr/cluster_test.go, internal/service/emr/find.go, internal/service/emr/wait.go
This will fix #6279
Rewrite resourceAwsEMRClusterDelete to use cluster state returned by DescribeCluster instead of counting running cluster instances to check is cluster terminated. Previous approach might cause too early deletion of cluster's security group which might block deletion of ENI created for this cluster. In this case orphaned ENI is blocking deletion of security configuration as well as linked security group.
These changes was tested on our environments and has fixed painful security configuration deletion issues.
* Please do not …
=> resource/aws_emr_cluster: Fix aws_emr_security_configuration destroy issues

.changelog/22246.txt, internal/service/fsx/ontap_storage_virtual_machine.go, internal/service/fsx/ontap_storage_virtual_machine_test.go
Closes #21987.
Deprecates `organizational_unit_distinguidshed_name` in the `active_directory_configuration.self_managed_active_directory_configuration` configuration block in favor of `organizational_unit_distinguished_name`.
Follows the [documented best practices](https://www.terraform.io/plugin/sdkv2/best-practices/deprecations#renaming-an-optional-attribut …
=> r/aws_fsx_ontap_storage_virtual_machine: Deprecate `organizational_unit_distinguidshed_name` in favor of `organizational_unit_distinguished_name`

README.md
```
...
```
The link in the README was throwing a Vercel error this morning. It seems to work now and redirects directly to the registry docs, but why not avoid the redirect?
=> fixup: Fix link to provider docs

CHANGELOG.md, aws/resource_aws_lambda_function.go, aws/resource_aws_lambda_function_test.go
Port of #19386 to **v2** of the Terraform AWS Provider.
Relates:
* https://docs.aws.amazon.com/lambda/latest/dg/functions-states.html
* https://aws.amazon.com/blogs/compute/tracking-the-state-of-lambda-functions/
* https://aws.amazon.com/blogs/compute/coming-soon-expansion-of-aws-lambda-states-to-all-functions/
```
--- PASS: …
```
=> (v2.x) r/aws_lambda_function: Wait for successful completion of code update

website/docs/r/securityhub_standards_control.markdown
The example for this resource is using deprecated syntax. It should be updated to use the idiomatic quoted label syntax like all other resource types.
=> Update `securityhub_standards_control` example with idiomatic quoted label syntax

.changelog/22259.txt, internal/service/sagemaker/model_package_group_policy.go, internal/service/sagemaker/model_package_group_policy_test.go
Closes #21968
Closes #11801
```console
% make testacc TESTS=TestAccSageMakerModelPackageGroupPolicy_ PKG=sagemaker
TF_ACC=1 go test ./internal/service/sagemaker/... -v -count 1 -parallel 20 -run='TestAccSageMakerModelPackageGroupPolicy_' -timeout 180m
--- …
```
=> sagemaker/model_package_group_policy: Fix equivalent policy diffs

.changelog/21773.txt, internal/service/ssoadmin/managed_policy_attachment.go
Signed-off-by: haarchri <chhaar30@googlemail.com>
fix missing provisionSsoAdminPermissionSet() after delete a policy in permissionSet otherwise  we get a message in AWS WebConsole "Requires reapplying permission set"
Note: aame API-Call is used if we add new policy to permissionSet eg. https://github.com/hashicorp/terraform-provider-aws/blob/main/internal/service/ssoadmin/managed_policy_attachment.go#L75-L78 - so it is save to use 
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate …
=> fix missing provisionSsoAdminPermissionSet() after delete a policy

internal/sweep/sweep.go
Currently the `aws_sns_platform_application` sweeper fails in `us-east-2` with:
```console
% make sweep SWEEPARGS=-sweep-run=aws_sns_platform_application SWEEP=us-east-2
go test ./internal/sweep -v -tags=sweep -sweep=us-east-2 -sweep-run=aws_sns_platform_application -timeout 60m …
```
=> r/aws_sns_platform_application: Skip errors in unsupported regions

internal/service/iam/sweep.go
Currently the `aws_iam_service_linked_role` sweeper fails with:
```
01:19:35
- aws_iam_service_linked_role: 1 error occurred:
01:19:35
* error deleting IAM Service Linked Role (AWSServiceRoleForElasticBeanstalk): arn: invalid prefix
```
The resource ID should be the role ARN, not its name.
```
% make sweep SWEEPARGS=-sweep-run=aws_iam_service_linked_role …
```
=> sweeper/aws_iam_service_linked_role: Set correct resource ID

.changelog/22189.txt, internal/service/codebuild/find.go, internal/service/codebuild/project.go, internal/service/codebuild/project_test.go, internal/service/codebuild/sweep.go, website/docs/r/codebuild_project.html.markdown
Closes #20126
```
$ make testacc TESTS=TestAccCodeBuildProject_ PKG=codebuild
--- PASS: TestAccCodeBuildProject_disappears (129.86s)
--- PASS: TestAccCodeBuildProject_SecondaryArtifacts_type (130.68s)
--- PASS: TestAccCodeBuildProject_SourceType_gitHubEnterprise (154.35s)
--- PASS: …
```
=> r/codebuild_project  - add support for `bucket_access_owner` and `public_visibility`

.changelog/22281.txt, internal/service/ecr/replication_configuration.go, website/docs/r/ecr_replication_configuration.html.markdown
This Pull Request increases the rules and destination limits for the `aws_ecr_replication_configuration`. The replication configuration can contain up to 10 rules, and each rule can contain up to 25 destinations.
* [AWS ECR API Documentation for ReplicationConfig Rule limits](https://docs.aws.amazon.com/AmazonECR/latest/APIReference/API_ReplicationConfiguration.html)
* [AWS ECR API Documentation for ReplicationRule Destination Limits](https://docs.aws.amazon.com/AmazonECR/latest/APIReference/API_ReplicationRule.html)
This PR only encompasses resource schema updates to allow us to match the limits that have been declared by the AWS API.
* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the …
=> Increase rules and destination limits for aws_ecr_replication_configuration

.changelog/22261.txt, internal/provider/provider.go, internal/service/memorydb/find.go, internal/service/memorydb/status.go, internal/service/memorydb/subnet_group_test.go, internal/service/memorydb/user.go, internal/service/memorydb/user_test.go, internal/service/memorydb/wait.go, website/docs/r/memorydb_user.html.markdown
Relates #20631
Depends on PR https://github.com/hashicorp/terraform-provider-aws/pull/22256
```
$ make testacc PKG=memorydb TESTS=TestAccUser_
TF_ACC=1 go test ./internal/service/memorydb/... -v -count 1 -parallel 20 -run='TestAccUser_' -timeout 180m
=== RUN …
```
=> New Resource: aws_memorydb_user

.changelog/21094.txt, internal/service/kinesisanalyticsv2/application.go, internal/service/kinesisanalyticsv2/application_snapshot.go, internal/service/kinesisanalyticsv2/application_test.go, internal/service/kinesisanalyticsv2/wait.go, website/docs/r/kinesisanalyticsv2_application.html.markdown, website/docs/r/kinesisanalyticsv2_application_snapshot.html.markdown
This PR adds support for customizable timeouts for Kinesis Data Analytics v2 Applications. We're seeing constant timeouts with the default 5m timeouts, so this raises the default timeout to 10m for the applications and then makes it customizable as well.
According to AWS support this is somewhat expected when dealing with Flink apps that are deployed into a …
=> feat: aws_kinesisanalyticsv2_application custom timeouts

website/docs/r/emr_cluster.html.markdown
In #21702, `auto_termination_policy` was added as an optional argument to the `aws_emr_cluster` resource. However its docs anchor was accidentally swapped with that of the existing `bootstrap_action` argument.
This corrects the names of these anchors.
Relates #21702
```
...
```
=> resource/emr_cluster: Fix bootstrap_action documentation

.changelog/22310.txt, internal/provider/provider.go, internal/service/ses/active_receipt_rule_set_data_source.go, internal/service/ses/active_receipt_rule_set_data_source_test.go, internal/service/ses/active_receipt_rule_set_test.go, website/docs/d/ses_active_receipt_rule_set.html.markdown
Relates OR Closes #20318
```
$ make testacc TESTARGS="-run=TestAccSESActiveReceiptRuleSet_serial" PKG_NAME="./internal/service/ses" ACCTEST_PARALLELISM=3
TF_ACC=1 go test ././internal/service/ses/... -v -count 1 -parallel 3 -run=TestAccSESActiveReceiptRuleSet_serial …
```
=> datasource aws_ses_active_receipt_rule_set

.changelog/22298.txt, internal/service/batch/job_queue.go, internal/service/batch/job_queue_test.go, internal/service/batch/sweep.go, website/docs/r/batch_job_queue.html.markdown
Closes #21755
```
$ make testacc TESTS=TestAccBatchSchedulingPolicy PKG=batch
TF_ACC=1 go test ./internal/service/batch/... -v -count 1 -parallel 20 -run='TestAccBatchSchedulingPolicy' -timeout 180m
=== RUN   TestAccBatchSchedulingPolicy_basic
=== PAUSE …
```
=> r/aws_batch_job_queue - new attribute

.changelog/22315.txt, internal/service/ec2/traffic_mirror_filter_rule.go
Closes #22312.
```console
$ make testacc TESTS=TestAccEC2TrafficMirrorFilterRule PKG=ec2
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 20 -run='TestAccEC2TrafficMirrorFilterRule' -timeout 180m
=== RUN   TestAccEC2TrafficMirrorFilterRule_basic
=== …
```
=> fix: change the type from array to slice to prevent a panic

.changelog/22304.txt, internal/provider/provider.go, internal/service/memorydb/find.go, internal/service/memorydb/parameter_group.go, internal/service/memorydb/parameter_group_test.go, website/docs/r/memorydb_parameter_group.html.markdown
Relates https://github.com/hashicorp/terraform-provider-aws/issues/20631
```
$ make testacc PKG=memorydb TESTS=TestAccMemoryDBParameterGroup_
TF_ACC=1 go test ./internal/service/memorydb/... -v -count 1 -parallel 20 -run='TestAccMemoryDBParameterGroup_' -timeout 180m …
```
=> New Resource: aws_memorydb_parameter_group

.changelog/22321.txt, internal/provider/provider.go, internal/service/ses/domain_identity_data_source.go, internal/service/ses/domain_identity_data_source_test.go, internal/service/ses/email_identity_data_dource_test.go, internal/service/ses/email_identity_data_source.go, website/docs/d/ses_domain_identity.markdown, website/docs/d/ses_email_identity.markdown
Relates OR Closes #16878
```
$  make testacc TESTARGS="-run=TestAccSESDomainIdentityDataSource_basic" PKG_NAME="./internal/service/ses" ACCTEST_PARALLELISM=3
TF_ACC=1 go test ././internal/service/ses/... -v -count 1 -parallel 3 …
```
=> data_source `aws_ses_domain_identity` `aws_ses_email_identity`

.changelog/21334.txt, internal/service/dynamodb/table.go
Closes #19344
```
$ TF_ACC=1 go test ./internal/service/dynamodb -v -count 1 -parallel 20 -run='TestAccDynamoDBTable_TTL' -timeout=180m
=== RUN   TestAccDynamoDBTable_TTL_enabled
=== PAUSE TestAccDynamoDBTable_TTL_enabled
=== RUN   TestAccDynamoDBTable_TTL_disabled
=== PAUSE TestAccDynamoDBTable_TTL_disabled
=== CONT …
```
=> b-aws_dynamodb_table

.changelog/21856.txt, internal/service/ecs/task_definition_data_source.go, internal/service/ecs/task_definition_data_source_test.go, website/docs/d/ecs_task_definition.html.markdown
Closes #21841
```
$ make testacc TESTARGS='-run=TestAccECSTaskDefinitionDataSource_' PKG_NAME=internal/service/ecs
TF_ACC=1 go test ./internal/service/ecs/... -v -count 1 -parallel 20 -run=TestAccECSTaskDefinitionDataSource_ -timeout 180m
=== RUN …
```
=> aws_ecs_task_definition_data_source arn attribute

.changelog/22359.txt, internal/service/ses/event_destination.go
Closes #21150.
`cloudwatch_destination.default_value` can contain more the following characters
* period
* at signs (@)
Amazon SES Documentation > Developers Guide
https://docs.aws.amazon.com/ses/latest/DeveloperGuide/event-publishing-add-event-destination-cloudwatch.html#event-publishing-add-event-destination-cloudwatch-dimensions
> 10. For Default Value, …
=> r/aws_ses_event_destination: fix cloudwatch_destination more contains

.changelog/22363.txt, internal/service/timestreamwrite/table.go, internal/service/timestreamwrite/table_test.go, website/docs/r/timestreamwrite_table.html.markdown
```
$ make testacc TESTS=TestAccTimestreamWriteTable_ PKG=timestreamwrite
--- PASS: TestAccTimestreamWriteTable_disappears (91.68s)
--- PASS: TestAccTimestreamWriteTable_basic (109.46s)
--- PASS: TestAccTimestreamWriteTable_magneticStoreWriteProperties_s3KmsConfig (131.78s)
--- PASS: …
```
=> r/timestreamwrite_table - add `magnetic_store_write_properties` block

.changelog/22346.txt, internal/provider/provider.go, internal/service/datasync/find.go, internal/service/datasync/location_fsx_lustre_file_system.go, internal/service/datasync/location_fsx_lustre_file_system_test.go, internal/service/datasync/sweep.go, internal/service/datasync/uri.go, website/docs/r/datasync_location_fsx_lustre_file_system.html.markdown
```
$ make testacc TESTS=TestAccDataSyncLocationFSxLustreFileSystem PKG=datasync
--- PASS: TestAccDataSyncLocationFSxLustreFileSystem_disappears (676.21s)
--- PASS: TestAccDataSyncLocationFSxLustreFileSystem_subdirectory (698.12s)
--- PASS: TestAccDataSyncLocationFSxLustreFileSystem_basic (777.55s)
--- PASS: …
```
=> r/datasync_location_fsx_lustre_file_system - new resource

.changelog/22345.txt, internal/service/codebuild/project.go, internal/service/codebuild/project_test.go, website/docs/r/codebuild_project.html.markdown
Closes #13241
```
$ make testacc TESTS=TestAccCodeBuildProject_SecondarySourcesVersions PKG=codebuild
--- PASS: TestAccCodeBuildProject_SecondarySourcesVersions (178.08s)
--- PASS: TestAccCodeBuildProject_basic (64.64s)
```
=> r/codebuild_project  - add `secondary_source_version` argument

internal/service/codebuild/find.go, internal/service/codebuild/source_credential.go, internal/service/codebuild/source_credential_test.go, internal/service/codebuild/sweep.go
Closes #13826
```
$ make testacc TESTS=TestAccCodeBuildSourceCredential_ PKG=codebuild
--- PASS: TestAccCodeBuildSourceCredential_disappears (48.68s)
--- PASS: TestAccCodeBuildSourceCredential_basic (94.34s)
--- PASS: TestAccCodeBuildSourceCredential_basicAuth (96.39s)
```
=> r/codebuild_source_credential - finder, sweeper and disappears test

.changelog/22222.txt, internal/service/ssm/parameters_by_path_data_source.go, internal/service/ssm/parameters_by_path_data_source_test.go, website/docs/d/ssm_parameters_by_path.html.markdown
This pull request adds the ability to recursively retrieve ssm parameters under the provided  `path`. The `recursive` argument has been added to the `aws_ssm_parameters_by_path` data source. The argument remains optional and defaults to false if not provided.
Closes [#21896](https://github.com/hashicorp/terraform-provider-aws/issues/21274)
Output from …
=> f/aws_ssm_parameters_by_path: Add support for recursive parameter retrieval

.changelog/21025.txt, internal/provider/provider.go, internal/service/devicefarm/device_pool.go, internal/service/devicefarm/device_pool_test.go, internal/service/devicefarm/find.go, internal/service/devicefarm/project.go, internal/service/devicefarm/project_test.go, internal/service/devicefarm/sweep.go, website/docs/r/devicefarm_device_pool.html.markdown
Closes #20969
```
$ make testacc TESTARGS='-run=TestAccAWSDeviceFarmProject_'
--- PASS: TestAccDeviceFarmProject_disappears (67.95s)
--- PASS: TestAccDeviceFarmProject_timeout (165.83s)
--- PASS: TestAccDeviceFarmProject_basic (172.33s)
--- PASS: TestAccDeviceFarmProject_tags (237.86s)
$ make testacc …
```
=> r/devicefarm_device_pool - new resource + use finder for devicefarm project

internal/service/ec2/vpc_byoip_test.go, internal/service/ec2/vpc_ipam_pool_cidr_allocation_test.go, internal/service/ec2/vpc_ipam_pool_cidr_test.go, internal/service/ec2/vpc_ipam_pool_data_source_test.go, internal/service/ec2/vpc_ipam_pool_test.go, internal/service/ec2/vpc_ipam_scope_test.go, internal/service/ec2/vpc_ipam_test.go, internal/service/ec2/vpc_ipv4_cidr_block_association_test.go, internal/service/ec2/vpc_test.go
Closes #22386.
```console
% AWS_DEFAULT_REGION=us-east-2 make testacc TESTS=TestAccVPCIpam_basic PKG=ec2
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 20 -run='TestAccVPCIpam_basic' -timeout 180m
=== RUN   TestAccVPCIpam_basic
=== PAUSE …
```
=> Add `testAccIPAMPreCheck` to check for IPAM service-linked role

docs/contributing/contribution-checklists.md
Corrects link to the website source in the [Contribution Types and Checklists](https://github.com/hashicorp/terraform-provider-aws/blob/main/docs/contributing/contribution-checklists.md) guide.
Also removes text about running local version of the website as that's no longer in this repo.
=> docs/contributing: Correct link to website source

.changelog/22394.txt, internal/provider/provider.go, internal/service/ec2/vpc_ipam_organization_admin_account.go, internal/service/ec2/vpc_ipam_organization_admin_account_test.go, website/docs/r/vpc_ipam_organization_account_admin.html.markdown, website/docs/r/vpc_ipam_organization_admin_account.html.markdown, website/docs/r/vpc_ipam_pool_cidr.html.markdown
Relates OR Closes #22092
```
$ make testacc TESTARGS='-run=TestAccVPCIpamOrganizationAdminAccount_basic' PKG_NAME='./internal/service/ec2'
TF_ACC=1 go test ././internal/service/ec2/... -v -count 1 -parallel 20 -run=TestAccVPCIpamOrganizationAdminAccount_basic -timeout …
```
=> New resource/aws_vpc_ipam_organization_admin_account

.changelog/22348.txt, internal/service/batch/job_queue_data_source.go, internal/service/batch/job_queue_data_source_test.go, website/docs/d/batch_job_queue.html.markdown
Relates #21755
```
$ make testacc TESTS=TestAccBatchJobQueueDataSource PKG=batch 
TF_ACC=1 go test ./internal/service/batch/... -v -count 1 -parallel 20 -run='TestAccBatchJobQueueDataSource' -timeout 180m
=== RUN   TestAccBatchJobQueueDataSource_basic
=== PAUSE …
```
=> d/aws_batch_job_queue - new attribute

.changelog/22396.txt, internal/service/dax/cluster.go, internal/service/dax/cluster_test.go, internal/service/dax/consts.go, website/docs/r/dax_cluster.html.markdown
Relates OR Closes #20352
```
$ make testacc TESTS=TestAccDAXCluster PKG=dax                   
TF_ACC=1 go test ./internal/service/dax/... -v -count 1 -parallel 20 -run='TestAccDAXCluster' -timeout 180m
=== RUN   TestAccDAXCluster_basic
=== PAUSE …
```
=> r/aws_dax_cluster - new attribute

.changelog/22395.txt, internal/service/appstream/fleet.go, internal/service/appstream/fleet_test.go, website/docs/r/appstream_fleet.html.markdown
Closes https://github.com/hashicorp/terraform-provider-aws/issues/21718
```
--- PASS: TestAccAppStreamFleet_basic (819.92s)
--- PASS: TestAccAppStreamFleet_completeWithStop (2087.37s)
--- PASS: TestAccAppStreamFleet_completeWithoutStop (912.51s)
```
=> r/appstream_fleet: correctly create resource with `stream_view` argument

website/docs/r/synthetics_canary.html.markdown
Since May 7, [Amazon CloudWatch Synthetics supports cron expression for scheduling](https://aws.amazon.com/about-aws/whats-new/2021/05/amazon-cloudwatch-synthetics-supports-cron-expression-for-scheduling/).
This PR is added a description of cron expression to the documentation.
=> Update aws_synthetics_canary docs

.changelog/22402.txt, internal/service/networkfirewall/resource_policy.go, internal/service/networkfirewall/wait.go
Closes https://github.com/hashicorp/terraform-provider-aws/issues/22174
* error seems to occur only during immediate delete-after-create behavior seen during `disappears` acceptance testing as other tests were passing before code change
```
--- PASS: TestAccNetworkFirewallResourcePolicy_disappears (131.81s)
--- PASS: …
```
=> r/networkfirewall_resource_policy: add error handling during delete for possible RAM related error

.changelog/22406.txt, internal/service/codepipeline/codepipeline.go, internal/service/codepipeline/webhook.go, internal/service/codepipeline/webhook_test.go, website/docs/r/codepipeline_webhook.markdown
Closes #15804
Relates #17482
Relates #14668
```
$ make testacc TESTS=TestAccCodePipelineWebhook_ PKG=codepipeline
--- PASS: TestAccCodePipelineWebhook_basic (234.41s)
--- PASS: TestAccCodePipelineWebhook_ipAuth (96.06s)
--- PASS: TestAccCodePipelineWebhook_unauthenticated (92.08s)
--- PASS: …
```
=> r/codepipeline_webhook - validations

.changelog/18560.txt, internal/service/cloud9/environment_ec2.go, internal/service/cloud9/environment_ec2_test.go, internal/service/cloud9/find.go, internal/service/cloud9/status.go, internal/service/cloud9/sweep.go, internal/service/cloud9/wait.go, internal/service/ec2/sweep.go, internal/sweep/sweep_test.go
```
$ make testacc TESTARGS='-run=TestAccAWSCloud9EnvironmentEc2_'
--- PASS: TestAccAWSCloud9EnvironmentEc2_disappears (219.23s)
--- PASS: TestAccAWSCloud9EnvironmentEc2_basic (280.01s)
--- PASS: TestAccAWSCloud9EnvironmentEc2_tags (352.82s)
--- PASS: TestAccAWSCloud9EnvironmentEc2_allFields (383.01s)
```
=> r/cloud9_environment_ec2 - validations + refactor to use finder and waiter packages + sweeper

internal/service/fsx/sweep.go
Relates #22234.
While looking at something else:
```console
% make sweep SWEEPARGS=-sweep-run=aws_customer_gateway,aws_vpn_gateway SWEEP=us-east-1,us-east-2,us-west-1,us-west-2
go test ./internal/sweep -v -tags=sweep -sweep=us-east-1,us-east-2,us-west-1,us-west-2 …
```
=> sweeper/fsx: Avoid `Error adding (aws_fsx_ontap_volume) to sweeperFuncs: function already exists in map`

.changelog/22418.txt, internal/service/ec2/vpc_ipam_pool_cidr_allocation.go, website/docs/r/vpc_ipam_pool_cidr_allocation.html.markdown
Relates OR Closes #22401
```
$ make testacc TESTS=TestAccVPCIpamPoolAllocation PKG=ec2 ACCTEST_PARALLELISM=1     
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 1 -run='TestAccVPCIpamPoolAllocation' -timeout 180m
=== RUN …
```
=> fix validation parameter and style

.changelog/22427.txt, internal/provider/provider.go, internal/service/fsx/sweep.go, internal/service/sagemaker/device.go, internal/service/sagemaker/device_test.go, internal/service/sagemaker/find.go, internal/service/sagemaker/sweep.go, website/docs/r/sagemaker_device.html.markdown
```
$ make testacc TESTS=TestAccSageMakerDevice_ PKG=sagemaker
--- PASS: TestAccSageMakerDevice_disappears_fleet (128.68s)
--- PASS: TestAccSageMakerDevice_disappears (130.71s)
--- PASS: TestAccSageMakerDevice_basic (150.00s)
--- PASS: TestAccSageMakerDevice_description (252.02s)
```
I have omited tags on purpose as tests keep …
=> r/sagemaker_device - new resource

.changelog/22439.txt, internal/service/glue/trigger.go, internal/service/glue/trigger_test.go, website/docs/r/glue_trigger.html.markdown
Closes #22437
```
$ make testacc TESTS= TestAccGlueTrigger_ PKG=glue
--- PASS: TestAccGlueTrigger_disappears (150.53s)
--- PASS: TestAccGlueTrigger_Actions_security (180.67s)
--- PASS: TestAccGlueTrigger_basic (188.90s)
--- PASS: TestAccGlueTrigger_workflowName (189.36s)
--- PASS: TestAccGlueTrigger_startOnCreate (219.90s)
--- …
```
=> r/glue_trigger - add `start_on_creation`

.changelog/11857.txt, internal/provider/provider.go, internal/service/cloud9/environment_membership.go, internal/service/cloud9/environment_membership_test.go, internal/service/cloud9/find.go, website/docs/r/cloud9_environment_membership.markdown
Closes #15735
```
$ make testacc TESTARGS='-run=TestAccAWSCloud9EnvironmentMembership_'
--- PASS: TestAccEnvironmentMembership_disappears (238.15s)
--- PASS: TestAccEnvironmentMembership_basic (350.26s)
--- …
```
=> r/aws_cloud9_environment_membership - add new resource

internal/service/appstream/directory_config.go, internal/service/appstream/fleet.go, internal/service/appstream/image_builder.go, internal/service/appstream/stack.go, internal/service/appstream/sweep.go
AppStream Fleets and Stacks were both using `ResourceImageBuilder` to delete. Correct that and log what is going on during resource deletion.
Relates #21125.
```console
% make sweep SWEEPARGS=-sweep-run=aws_appstream_directory_config,aws_appstream_fleet,aws_appstream_image_builder,aws_appstream_stack SWEEP=us-west-2
WARNING: This will destroy infrastructure. …
```
=> sweeper/AppStream: Delete the correct resource types

internal/provider/provider.go, internal/service/devicefarm/device_pool.go, internal/service/devicefarm/find.go, internal/service/devicefarm/network_profile.go, internal/service/devicefarm/network_profile_test.go, internal/service/devicefarm/upload.go, website/docs/r/devicefarm_network_profile.html.markdown
```
$ make testacc TESTS=TestAccDeviceFarmNetworkProfile_ PKG=devicefarm
--- PASS: TestAccDeviceFarmNetworkProfile_disappears_project (86.85s)
--- PASS: TestAccDeviceFarmNetworkProfile_disappears (96.35s)
--- PASS: TestAccDeviceFarmNetworkProfile_basic (182.20s)
--- PASS: TestAccDeviceFarmNetworkProfile_tags (242.36s)
```
$ …
=> r/devicefarm_network_profile - new resource

.changelog/22342.txt, internal/service/ec2/ebs_snapshot.go, internal/service/ec2/ebs_snapshot_copy.go, internal/service/ec2/ebs_snapshot_copy_test.go, internal/service/ec2/ebs_snapshot_data_source.go, internal/service/ec2/ebs_snapshot_data_source_test.go, internal/service/ec2/ebs_snapshot_import.go, internal/service/ec2/ebs_snapshot_import_test.go, internal/service/ec2/ebs_snapshot_test.go, internal/service/ec2/enum.go, internal/service/ec2/errors.go, internal/service/ec2/find.go, internal/service/ec2/status.go, internal/service/ec2/sweep.go, internal/service/ec2/wait.go, website/docs/d/ebs_snapshot.html.markdown, website/docs/r/ebs_snapshot.html.markdown, website/docs/r/ebs_snapshot_copy.html.markdown, website/docs/r/ebs_snapshot_import.html.markdown
Closes #17491.
Supersedes #17730.
```
$ make testacc TESTS=TestAccEC2EBSSnapshot_ PKG=ec2
--- PASS: TestAccEC2EBSSnapshot_disappears (115.47s)
--- PASS: TestAccEC2EBSSnapshot_withDescription (128.47s)
--- PASS: TestAccEC2EBSSnapshot_basic (130.41s)
--- PASS: TestAccEC2EBSSnapshot_withKMS (150.40s)
--- PASS: …
```
=> r/ebs_snapshot - support storage tier + sweeper

website/docs/r/autoscaling_group.html.markdown
This is the configuration that I had and it didn't trigger the instance refresh. 
```hcl
resource "aws_autoscaling_group" "web" {
#...
launch_template {
id      = aws_launch_template.web.id
version = "$Latest"
}
instance_refresh {
strategy = "Rolling"
}
}
```
When I changed `version = "$Latest"` to `aws_launch_template.web.latest_version`, the instance_refresh was triggered. 
```hcl
resource "aws_autoscaling_group" "web" {
#...
launch_template {
id      = aws_launch_template.web.id
version = aws_launch_template.web.latest_version
}
instance_refresh {
strategy = "Rolling"
}
}
```
Because it was nowhere in the documentation, and I couldn't find any issues reported about it, I thought this was the easiest and quickest way to save some other folks a lot of time.
* Please vote on this pull …
=> docs/autoscaling_group: add note instance_refresh

.changelog/22460.txt, internal/service/cloudwatchlogs/destination_policy.go, internal/service/cloudwatchlogs/destination_policy_test.go, website/docs/r/cloudwatch_log_destination_policy.html.markdown
Closes #22445
```
$ make testacc TESTS=TestAccCloudWatchLogsDestinationPolicy_ PKG=cloudwatchlogs
--- PASS: TestAccCloudWatchLogsDestinationPolicy_basic (142.72s)
```
=> r/cloudwatch_log_destination_policy - add `force_update` argument

.changelog/22453.txt, internal/service/elb/service_account_data_source.go
https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-access-logs.html#access-logging-bucket-permissions
Relates #22252, https://github.com/hashicorp/terraform-provider-aws/pull/22295
prev: #12967, #13061, fixed doc links in #22294
=> data_source: ap-southeast-3 (Jakarta)

.changelog/22455.txt, internal/service/sagemaker/prebuilt_ecr_image_data_source.go
missed in https://github.com/hashicorp/terraform-provider-aws/pull/12967, https://github.com/hashicorp/terraform-provider-aws/pull/13061
documented process in https://github.com/hashicorp/terraform-provider-aws/pull/22454
https://docs.aws.amazon.com/sagemaker/latest/dg/ecr-af-south-1.html
https://docs.aws.amazon.com/sagemaker/latest/dg/ecr-ap-northeast-3.html
https://docs.aws.amazon.com/sagemaker/latest/dg/ecr-eu-south-1.html
also found the rest of the SparkML account IDs there too:
https://docs.aws.amazon.com/sagemaker/latest/dg/sagemaker-algo-docker-registry-paths.html
---
* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and …
=> data_source: new region Sagemaker account IDs (af-south-1, ap-northeast-3, eu-south-1)

.changelog/22461.txt, internal/service/cloudfront/distribution.go
=> r/cloudfront_distribution - bump `origin_read_timeout` validation to `180`

.changelog/22458.txt, internal/provider/provider.go, internal/service/devicefarm/find.go, internal/service/devicefarm/instance_profile.go, internal/service/devicefarm/instance_profile_test.go, website/docs/r/devicefarm_instance_profile.html.markdown, website/docs/r/devicefarm_network_profile.html.markdown
```
$ make testacc TESTS=TestAccDeviceFarmInstanceProfile_ PKG=devicefarm
--- PASS: TestAccDeviceFarmInstanceProfile_disappears (56.17s)
--- PASS: TestAccDeviceFarmInstanceProfile_basic (114.85s)
--- PASS: TestAccDeviceFarmInstanceProfile_tags (149.49s)
```
=> r/devicefarm_instance_profile - new resource

.changelog/22463.txt, internal/service/ec2/instance.go, internal/service/ec2/instance_data_source.go, internal/service/ec2/instance_data_source_test.go, internal/service/ec2/instance_test.go, internal/service/ec2/launch_template.go, internal/service/ec2/launch_template_data_source.go, internal/service/ec2/launch_template_data_source_test.go, internal/service/ec2/launch_template_test.go, website/docs/d/instance.html.markdown, website/docs/d/launch_template.html.markdown, website/docs/r/instance.html.markdown, website/docs/r/launch_template.html.markdown
EC2 Instance tags can now be exposed via the metadata service, if enabled via a metadata option 🎉 
https://aws.amazon.com/about-aws/whats-new/2022/01/instance-tags-amazon-ec2-instance-metadata-service/
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/Using_Tags.html#work-with-tags-in-IMDS
Depends on #22456 - support for instance tags on Instance and Launch Template resources (but not Launch Configurations) was added to github.com/aws/aws-sdk-go in in v1.42.29.
* Please do not leave "+1" or other comments that do not add relevant new …
=> Add support for EC2 Instance Metadata Tags

.changelog/22269.txt, GNUmakefile, internal/service/ecs/task_definition.go, internal/service/ecs/task_definition_test.go
Closes #258
Closes #11506
Relates #4198
Relates #6314
Relates #11997
```console
% make testacc TESTS='TestAccECSTaskDefinition_' PKG=ecs TESTARGS=-short
TF_ACC=1 go test ./internal/service/ecs/... -v -count 1 -parallel 20 -run='TestAccECSTaskDefinition_' …
```
=> ecs/task_definition: Add `skip_destroy` argument

.changelog/22486.txt, internal/provider/provider.go, internal/service/memorydb/cluster_test.go, internal/service/memorydb/snapshot.go, internal/service/memorydb/snapshot_test.go, internal/service/memorydb/status.go, internal/service/memorydb/wait.go, website/docs/r/memorydb_snapshot.html.markdown
Relates https://github.com/hashicorp/terraform-provider-aws/issues/20631
```
$ make testacc PKG=memorydb TESTS=TestAccMemoryDBSnapshot_ ACCTEST_PARALLELISM=3 ACCTEST_TIMEOUT=600m
TF_ACC=1 go test ./internal/service/memorydb/... -v -count 1 -parallel 3 …
```
=> New Resource: aws_memorydb_snapshot

.changelog/22411.txt, internal/service/appsync/appsync_test.go, internal/service/appsync/datasource.go, internal/service/appsync/datasource_test.go, website/docs/r/appsync_datasource.html.markdown
Supersedes #13080
Supersedes #16923
Supersedes #9337
Closes #8870
Closes #12721
Closes #9628
```
$ make testacc TESTS=TestAccAppSync_serial/DataSource PKG=appsync
--- PASS: TestAccAppSync_serial/DataSource/Type_http_auth (56.40s)
--- PASS: TestAccAppSync_serial/DataSource/Type_rdbms_options (381.87s)
--- PASS: …
```
=> r/appsync_datasource - http authorization + rdbms source

.changelog/22485.txt, internal/service/eks/cluster.go, internal/service/eks/cluster_data_source.go, internal/service/eks/cluster_data_source_test.go, internal/service/eks/cluster_test.go, website/docs/r/eks_cluster.html.markdown
Closes #22407
```
$ make testacc TESTS=TestAccEKSCluster_Network_ipFamily PKG=eks
TF_ACC=1 go test ./internal/service/eks/... -v -count 1 -parallel 20 -run='TestAccEKSCluster_Network_ipFamily'  -timeout 180m
=== RUN   TestAccEKSCluster_Network_ipFamily
=== PAUSE …
```
=> r/aws_eks_cluster: Add ip_family argument

.changelog/22470.txt, internal/service/ec2/vpc_ipam_pool_cidr_allocation.go, internal/service/ec2/vpc_ipam_pool_cidr_allocation_test.go, website/docs/r/vpc_ipam_pool_cidr_allocation.html.markdown
Closes #22471
```
$ make testacc TESTS=TestAccVPCIpamPoolAllocation PKG=ec2 ACCTEST_PARALLELISM=1 
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 1 -run='TestAccVPCIpamPoolAllocation' -timeout 180m
=== RUN   TestAccVPCIpamPoolAllocation_ipv4Basic
=== …
```
=> r/aws_vpc_ipam_pool_cidr_allocation - new attribute

.changelog/22501.txt, internal/service/ec2/vpc_ipam_preview_next_cidr.go, internal/service/ec2/vpc_ipam_preview_next_cidr_test.go, website/docs/r/vpc_ipam_preview_next_cidr.html.markdown
Relates #22305
```
$ make testacc TESTS=TestAccVPCIpamPreviewNextCidr PKG=ec2 ACCTEST_PARALLELISM=1  
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 1 -run='TestAccVPCIpamPreviewNextCidr'  -timeout 180m
=== RUN …
```
=> r/aws_vpc_ipam_preview_next_cidr - new attribute

.changelog/22484.txt, internal/service/appsync/appsync_test.go, internal/service/appsync/datasource.go, internal/service/appsync/function.go, internal/service/appsync/function_test.go, website/docs/r/appsync_function.html.markdown
Requires #22411 (sync config only works for versioned data sources)
```
$ make testacc TESTS=TestAccAppSync_serial/Function/sync PKG=appsync > a.txt
--- PASS: TestAccAppSync_serial (76.11s)
--- PASS: TestAccAppSync_serial/Function (76.11s)
--- PASS: TestAccAppSync_serial/Function/sync (76.11s)
```
=> r/appsync_function - Support `sync_config` and `max_batch_size`

.changelog/22480.txt, internal/service/fsx/openzfs_file_system.go, internal/service/fsx/openzfs_file_system_test.go, internal/service/fsx/openzfs_volume.go
Closes #22475
```
$ make testacc TESTS=TestAccFSxOpenzfsFileSystem_rootVolume PKG=fsx
=== RUN   TestAccFSxOpenzfsFileSystem_rootVolume
=== PAUSE TestAccFSxOpenzfsFileSystem_rootVolume
=== CONT  TestAccFSxOpenzfsFileSystem_rootVolume
--- PASS: TestAccFSxOpenzfsFileSystem_rootVolume (1409.91s)
PASS
ok …
```
=> added nil check for nfs exports

.changelog/22438.txt, CHANGELOG.md, internal/service/ec2/vpc_ipam_pool.go, internal/service/ec2/vpc_ipam_pool_data_source.go, internal/service/ec2/vpc_ipam_pool_data_source_test.go
Relates OR Closes #22438
2022-01-10T09:32:26-08:00 info layer=debugger launching process with args: [/var/folders/km/mt9r_90d1fv2_rpcb1nxkjb8_kl971/T/__debug_bin1626238921 -test.v -test.run ^TestAccDataSourceVPCIpamPool_basic$]
Type 'dlv help' for list of commands.
2022-01-10T09:32:33-08:00 debug layer=debugger continuing
=== RUN …
=> Modifications to resolve github CI errors

.changelog/22510.txt, internal/service/appsync/appsync_test.go, internal/service/appsync/resolver.go, internal/service/appsync/resolver_test.go, website/docs/r/appsync_resolver.html.markdown
```
$ make testacc TESTS=TestAccAppSync_serial/Resolver PKG=appsync
--- PASS: TestAccAppSync_serial (934.97s)
--- PASS: TestAccAppSync_serial/Resolver (934.97s)
--- PASS: TestAccAppSync_serial/Resolver/disappears (74.04s)
--- PASS: TestAccAppSync_serial/Resolver/multipleResolvers (145.61s)
--- PASS: …
```
=> r/appsync_resolver - add `sync_config` and `max_batch_size`

.changelog/22303.txt, internal/service/connect/contact_flow.go, internal/service/connect/contact_flow_test.go, website/docs/r/connect_contact_flow.html.markdown
Relates OR Closes #21935
```
$ make testacc TESTARGS='-run=TestAccConnectContactFlow_serial' PKG_NAME=internal/service/connect
TF_ACC=1 go test ./internal/service/connect/... -v -count 1 -parallel 20 -run=TestAccConnectContactFlow_serial -timeout 180m
=== RUN …
```
=> resource/aws_connect_contact_flow: add delete function

.changelog/22522.txt, internal/service/ssm/parameter.go, internal/service/ssm/parameter_test.go
Ensure we refresh the `version` field when updating the contents of an SSM parameter. (Drive-by: Correct use of inconsistent
resources in `TestAccSSMParameter_overwrite` test phases.)
Closes #12213.
```
Acceptance test output:
$ make testacc TESTS=TestAccSSMParameter_overwrite PKG=ssm …
```
=> r/aws_ssm_parameter: Mark `version` as computed when value changes

.changelog/22531.txt, internal/service/ec2/status.go, internal/service/ec2/subnet.go, internal/service/ec2/subnet_test.go, internal/service/ec2/wait.go
Closes #22498.
Previously:
```console
% AWS_DEFAULT_REGION=ap-southeast-3 make testacc TESTS=TestAccEC2Subnet_basic PKG=ec2
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 20 -run='TestAccEC2Subnet_basic'  -timeout 180m
=== RUN   TestAccEC2Subnet_basic
=== PAUSE …
```
=> r/aws_subnet: Resource-based naming is not available in the `ap-southeast-3` region

internal/service/ec2/instance.go, website/docs/r/instance.html.markdown
Most settings for the `root_device_volume` of an `aws_instance` can be
changed without forcing an instance replacement.
Closes #22357
```
...
```
=> r/aws_instance: Fix docs for root_device_volume

website/docs/r/ec2_client_vpn_endpoint.html.markdown
The docs for the `dns_servers` argument of the
`aws_ec2_client_vpn_endpoint` resource is erroneous. When not specified,
the Client VPN does not automatically use the VPC DNS address. This can
be verified by checking the [AWS API docs][1]:
> If no DNS server is specified, the DNS address configured on the
> device is used for the DNS server.
[1]: https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_CreateClientVpnEndpoint.html
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate …
=> docs/ec2_client_vpn_endpoint: fix dns_servers docs

website/docs/r/secretsmanager_secret_policy.html.markdown
Such policies are generally considered dangerous, as they allow access by any principal in the account, or outside the account that has permissions on the KMS key. Generally, it's a bad idea to illustrate security features with insecure examples, so I'm proposing this change.
=> Illustrate SecretsManager secret policy with a safer example

.changelog/21993.txt, internal/provider/provider.go, internal/service/shield/id.go, internal/service/shield/protection_health_check_association.go, internal/service/shield/protection_health_check_association_test.go, website/docs/r/shield_protection_health_check_association.html.markdown
Closes #19227
```
$ make testacc TESTS='TestAccShieldProtectionHealthCheckAssociation_basic|TestAccShieldProtectionHealthCheckAssociation_disappears' PKG=shield
TF_ACC=1 go test ./internal/service/shield/... -v -count 1 -parallel 20 …
```
=> New Resource: aws_shield_protection_health_check_association

.changelog/22511.txt, internal/service/sns/consts.go, internal/service/sns/topic.go
Closes #21209
Relates #22532
```console
% make testacc TESTS=TestAccSNSTopic_ PKG=sns
--- PASS: TestAccSNSTopic_fifoExpectContentBasedDeduplicationError (4.25s)
--- PASS: TestAccSNSTopic_disappears (17.49s)
--- PASS: TestAccSNSTopic_name (24.78s)
--- PASS: TestAccSNSTopic_NamePrefix_fifoTopic (24.97s)
--- PASS: …
```
=> sns/topic: ISO-friendly tagging

.changelog/22516.txt, internal/service/sqs/consts.go, internal/service/sqs/queue.go, internal/service/sqs/queue_data_source.go
Closes #18135
Relates #18593
Relates #22532
```console
% make testacc TESTS='TestAccSQSQueue_|TestAccSQSQueueDataSource_' PKG=sqs
TF_ACC=1 go test ./internal/service/sqs/... -v -count 1 -parallel 20 -run='TestAccSQSQueue_|TestAccSQSQueueDataSource_' …
```
=> sqs/queue: Make ISO-friendly tags

.changelog/22535.txt, internal/service/ecr/consts.go, internal/service/ecr/repository.go, internal/service/ecr/repository_data_source.go
Closes #18133
Relates #18593
Relates #22532
```console
% make testacc TESTS='TestAccECRRepository_|TestAccECRRepositoryDataSource_' PKG=ecr
TF_ACC=1 go test ./internal/service/ecr/... -v -count 1 -parallel 20 …
```
=> ecr: ISO-friendly tagging

.changelog/22529.txt, internal/service/ecs/capacity_provider.go, internal/service/ecs/cluster.go, internal/service/ecs/cluster_data_source.go, internal/service/ecs/flex.go, internal/service/ecs/service.go, internal/service/ecs/service_test.go, internal/service/ecs/tag_test.go, internal/service/ecs/task_definition.go, internal/service/ecs/task_definition_test.go, internal/service/ecs/task_set.go
Closes #18134
Relates #18593
Relates #22532
```console
% make testacc TESTS=TestAccECSCapacityProvider_ PKG=ecs
TF_ACC=1 go test ./internal/service/ecs/... -v -count 1 -parallel 20 -run='TestAccECSCapacityProvider_'  -timeout 180m
--- PASS: …
```
=> ecs: ISO-friendly tagging

.changelog/22544.txt, internal/service/iam/consts.go, internal/service/iam/role.go, internal/service/iam/role_data_source.go, internal/service/iam/user.go, internal/service/iam/user_data_source.go
Closes #18898
Relates #18593
Relates #22532
(* 3 pre-existing failures)
```console
% make testacc TESTS='TestAccIAMRoleDataSource_|TestAccIAMRole_' PKG=iam
TF_ACC=1 go test ./internal/service/iam/... -v -count 1 -parallel 20 …
```
=> iam: ISO-friendly tagging

.changelog/22550.txt, internal/service/events/bus.go, internal/service/events/consts.go, internal/service/events/rule.go
Relates #18593
Relates #22532
```console
% make testacc TESTS=TestAccEventsRule_ PKG=events
TF_ACC=1 go test ./internal/service/events/... -v -count 1 -parallel 20 -run='TestAccEventsRule_'  -timeout 180m
--- SKIP: TestAccEventsRule_partnerEventBus …
```
=> eventbridge: ISO-friendly tagging

.changelog/22551.txt, internal/service/elbv2/consts.go, internal/service/elbv2/listener.go, internal/service/elbv2/listener_data_source.go, internal/service/elbv2/listener_rule.go, internal/service/elbv2/listener_rule_test.go, internal/service/elbv2/listener_test.go, internal/service/elbv2/load_balancer.go, internal/service/elbv2/load_balancer_data_source.go, internal/service/elbv2/load_balancer_test.go, internal/service/elbv2/target_group.go, internal/service/elbv2/target_group_data_source.go
Relates #18593
Relates #22532
```console
% make testacc TESTS=TestAccELBV2Listener_ PKG=elbv2 TESTARGS=-short
TF_ACC=1 go test ./internal/service/elbv2/... -v -count 1 -parallel 20 -run='TestAccELBV2Listener_' -short -timeout 180m
--- SKIP: …
```
=> elbv2: ISO-friendly tagging

.changelog/22556.txt, internal/service/cloudwatch/composite_alarm.go, internal/service/cloudwatch/const.go, internal/service/cloudwatch/metric_alarm.go, internal/service/cloudwatch/metric_stream.go
Relates #18593
Relates #22532
```console
% make testacc TESTS=TestAccCloudWatchCompositeAlarm_ PKG=cloudwatch
TF_ACC=1 go test ./internal/service/cloudwatch/... -v -count 1 -parallel 20 -run='TestAccCloudWatchCompositeAlarm_'  -timeout 180m
--- PASS: …
```
=> cloudwatch: ISO-friendly tagging

.changelog/22552.txt, internal/service/cloudfront/distribution_data_source.go, internal/service/cloudfront/distribution_data_source_test.go, website/docs/d/cloudfront_distribution.html.markdown
Closes #21872
```
$ make testacc TESTARGS="-run=TestAccCloudFrontDistributionDataSource_basic" PKG_NAME="./internal/service/cloudfront" ACCTEST_PARALLELISM=3
TF_ACC=1 go test ././internal/service/cloudfront/... -v -count 1 -parallel 3 …
```
=> Add aliases to cloudfront datasource

.changelog/22580.txt, internal/service/ec2/subnet.go, website/docs/d/subnet.html.markdown, website/docs/r/subnet.html.markdown
Relates #18593
```console
% make testacc TESTS=TestAccEC2Subnet_ PKG=ec2
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 20 -run='TestAccEC2Subnet_'  -timeout 180m
--- SKIP: TestAccEC2Subnet_customerOwnedIPv4Pool (2.08s)
--- SKIP: …
```
=> ec2/subnet: Availability zone ID not supported in all partitions

.changelog/22575.txt, internal/service/s3/bucket.go
Relates #18593
```console
% make testacc TESTS=TestAccS3Bucket_ PKG=s3
TF_ACC=1 go test ./internal/service/s3/... -v -count 1 -parallel 20 -run='TestAccS3Bucket_'  -timeout 180m
--- PASS: TestAccS3Bucket_Replication_expectVersioningValidationError (24.03s)
--- PASS: …
```
=> s3/bucket: Guard against object lock error

.semgrep.yml, internal/service/cloudformation/stack.go, internal/service/ec2/fleet.go, internal/service/ec2/spot_fleet_request.go, internal/service/neptune/event_subscription.go, internal/service/redshift/snapshot_schedule_association.go, internal/service/sns/topic_subscription.go, internal/service/wafregional/regex_match_set.go
Relates #12796.
Relates #18382.
Relates #18390.
Warns if `d.SetId("")` is called in a resource's `Create` function or `d.SetId(...)` is called in a resource's `Delete` function.
```console
% make testacc TESTS=TestAccCloudFormationStack_basic PKG=cloudformation …
```
=> Add Semgrep rule to warn on calling 'd.SetId()' in a resource create or delete function

.changelog/12433.txt, internal/service/opsworks/custom_layer_test.go, internal/service/opsworks/layers.go, website/docs/r/opsworks_custom_layer.html.markdown
Closes #2656
Closes #15010
Relates #13826
```release-note
resource_aws_opsworks_custom_layer - add cloudwatch configuration
resource_aws_opsworks_custom_layer - add plan time validation to `ebs_volume.type`
``` …
=> r/aws_opsworks_custom_layer - add cloudwatch configuration + disappears test

.changelog/20222.txt, internal/service/apprunner/status.go, internal/service/apprunner/wait.go
Sometimes when the custom domain association is deleted and we want to recreate it, the status returned might be `binding_certificate` instead of the currently awaited status `pending_certificate_dns_validation`.
Why this status is being used instead of the other one is a black box to me but a wild guess I have is that AWS creates some kind of cache for those records and doesn't actually delete them, which creates some weird behavior when re-creating (like skipping a status?).
Anyway, without this fix there is no way to make the module behave properly again, even destroying the all AppRunner service ends up re-using the same custom domain association (unless you change the domain name offcourse).
* Please vote on this pull request by adding a 👍 …
=> fix AppRunner custom domain association after manual delete

website/docs/r/cloudfront_response_headers_policy.html.markdown
This PR adds origin_override under the Argument Reference section in the `website/docs/r/cloudfront_response_headers_policy.html.markdown` document.
=> This fixes #22220

.changelog/22630.txt, internal/service/dynamodb/table.go, internal/service/dynamodb/table_test.go, internal/service/dynamodb/wait.go
DynamoDB tables support two billing modes, `PAY_PER_REQUEST` and `PROVISIONED`. When using `PAY_PER_REQUEST`, provisioned throughput cannot be configured, whereas when using `PROVISIONED`, provisioned throughput must be set.
When using autoscaling for DynamoDB tables, the provisioned throughput values should ignore changes. However, if the table is switched from `PAY_PER_REQUEST` to `PROVISIONED` with ignored provisioned throughput values, no values are provided to the provider, which causes a failure.
Since the `ignore_changes` setting cannot be made conditional, this PR adds special handling when switching from `PAY_PER_REQUEST` to `PROVISIONED` and there are no values for `read_capacity` and `write_capacity`. The provider assumes that the table is configured with autoscaling and sets …
=> resource/aws_dynamodb_table: Add special case for changing billing mode with autoscaling

.changelog/22163.txt, internal/conns/envvar.go, internal/provider/provider.go, internal/service/detective/detective_test.go, internal/service/detective/find.go, internal/service/detective/graph.go, internal/service/detective/graph_test.go, internal/service/detective/invitation_accepter.go, internal/service/detective/invitation_accepter_test.go, internal/service/detective/member.go, internal/service/detective/member_test.go, internal/service/detective/status.go, internal/service/detective/wait.go, website/docs/r/detective_graph.html.markdown, website/docs/r/detective_invitation_accepter.html.markdown, website/docs/r/detective_member.html.markdown
Added a new resource, doc and tests for [Detective Member](https://docs.aws.amazon.com/detective/latest/APIReference/API_CreateMembers.html) called `aws_detective_member` and [Detective Invitation Accepter](https://docs.aws.amazon.com/detective/latest/APIReference/API_AcceptInvitation.html) called `aws_detective_invitation_accepter`
Relates #11672
Output …
=> New resource for Detective Member and Invitation Accepter

.changelog/22664.txt, internal/service/ec2/route.go, internal/service/ec2/route_table.go, website/docs/r/route.html.markdown, website/docs/r/route_table.html.markdown
Relates https://github.com/hashicorp/terraform-provider-aws/issues/14197
```
N/A
```
=> r/route and r/route_table: deprecate `instance_id`

.changelog/22665.txt, internal/service/ecr/lifecycle_policy.go, internal/service/ecr/lifecycle_policy_test.go
Closes #22641.
```
$ make testacc TESTS=TestAccECRLifecyclePolicy_ PKG_NAME=internal/service/ecr
TF_ACC=1 go test ./internal/service/ecr/... -v -count 1 -parallel 20 -run='TestAccECRLifecyclePolicy_'  -timeout 180m
=== RUN   TestAccECRLifecyclePolicy_basic
=== PAUSE …
```
=> r/aws_ecr_lifecycle_policy - fix change detection bug

docs/contributing/naming.md
=> Fix naming docs minor issue

docs/contributing/maintaining.md
Relates #22163 -- which added support for the `aws_detective_member` resource. This resource's acceptance tests require an environment variable `AWS_DETECTIVE_MEMBER_EMAIL`.
This PR adds `AWS_DETECTIVE_MEMBER_EMAIL` to our shared environment variable dictionary.
=> Add AWS_DETECTIVE_MEMBER_EMAIL to environment variable dictionary

.github/workflows/documentation.yml, .github/workflows/website.yml, .markdownlinkcheck.json, docs/contributing/running-and-writing-acceptance-tests.md
Sample error:
```
FILE: docs/contributing/development-environment.md
[✖] https://www.terraform.io/downloads.html → Status: 0 Error: ESOCKETTIMEDOUT
at ClientRequest.<anonymous> (/usr/local/lib/node_modules/markdown-link-check/node_modules/request/request.js:816:19)
at Object.onceWrapper (node:events:639:28)
at ClientRequest.emit …
```
=> Fix markdownlinkcheck

.changelog/22688.txt, internal/provider/provider.go, internal/service/devicefarm/find.go, internal/service/devicefarm/sweep.go, internal/service/devicefarm/test_grid_project.go, internal/service/devicefarm/test_grid_project_test.go, website/docs/r/devicefarm_test_grid_project.html.markdown
```
$ make testacc TESTS=TestAccDeviceFarmTestGridProject_ PKG=devicefarm > a.txt
--- PASS: TestAccDeviceFarmTestGridProject_disappears (51.09s)
--- PASS: TestAccDeviceFarmTestGridProject_basic (97.74s)
--- PASS: TestAccDeviceFarmTestGridProject_tags (133.24s) 
--- PASS: TestAccDeviceFarmTestGridProject_vpc (89.07s)
```
=> r/devicefarm_test_grid_project - new resource

docs/contributing/running-and-writing-acceptance-tests.md, internal/service/lambda/event_source_mapping_test.go, internal/service/lambda/function_data_source_test.go, internal/service/lambda/function_event_invoke_config_test.go, internal/service/lambda/function_test.go, internal/service/lambda/permission_test.go, internal/service/lambda/provisioned_concurrency_config_test.go
Relates #22701
```console
% make testacc TESTS=TestAccLambda PKG=lambda
...
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/lambda	5926.363s
% make testacc TESTS=TestAccLambda PKG=lambda TESTARGS=-short
...
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/lambda	540.399s
```
=> lambda: Add long-running test guards

.changelog/18561.txt, internal/service/apigateway/deployment.go, internal/service/apigateway/deployment_test.go, internal/service/apigateway/find.go, internal/service/apigateway/method_settings.go, internal/service/apigateway/method_settings_test.go, internal/service/apigateway/stage.go, internal/service/apigateway/stage_test.go, internal/service/apigateway/status.go, internal/service/apigateway/wait.go, website/docs/r/api_gateway_stage.html.markdown
```
$ make testacc TESTS='-run=TestAccAWSAPIGatewayStage_' PKG=apigateway
--- PASS: TestAccAPIGatewayStage_disappears (87.64s)
--- PASS: TestAccAPIGatewayStage_disappears_restApi (105.02s)
--- PASS: TestAccAPIGatewayStage_Disappears_referencingDeployment (145.40s)
--- PASS: TestAccAPIGatewayStage_basic (201.95s)
--- PASS: …
```
=> r/apigateway_stage - add `waf_acl_arn` attribute + use waiter and finder

.changelog/22693.txt, internal/service/lambda/function.go, internal/service/lambda/function_test.go
Closes #22692
```
$ make testacc TESTS=TestAccLambdaFunction_codeSigning PKG=lambda
(Failed to run. Asked for AWS credentials for running acceptance testing)
...
```
=> Disable code signing in lambda for ap-southeast-3

.changelog/22713.txt, internal/service/ec2/wait.go
Signed-off-by: ialidzhikov <i.alidjikov@gmail.com>
Closes #22711
```
...
```
=> r/internet_gateway: Prevent giving up on wait for attachement too early

.changelog/5132.txt, internal/provider/provider.go, internal/service/s3/bucket.go, internal/service/s3/bucket_versioning.go, internal/service/s3/bucket_versioning_test.go, internal/service/s3/id.go, internal/service/s3/id_test.go, website/docs/r/s3_bucket_versioning.html.markdown
Partially Fixes #4418 
Relates #20433
* Add resource aws_s3_bucket_versioning
```
$ make testacc TEST=./aws TESTARGS="-run TestAccAWSS3BucketVersioning -count=1"
TF_ACC=1 go test ./aws -v -run TestAccAWSS3BucketVersioning -count=1 -timeout 120m
=== RUN   TestAccAWSS3BucketVersioning_basic
--- PASS: TestAccAWSS3BucketVersioning_basic (92.86s)
PASS
ok      github.com/terraform-providers/terraform-provider-aws/aws       93.568s
```
I omitted anything to do with mfa_delete as there's currently no way to actually enabled/disable this via terraform.
The S3 API in us-west-2 has some major inconsistencies with updating versioning on buckets, especially between ~11a and …
=> Add resource aws_s3_bucket_versioning

.changelog/22717.txt, internal/service/cloudwatch/composite_alarm.go, internal/service/cloudwatch/consts.go, internal/service/cloudwatch/metric_alarm.go, internal/service/cloudwatch/metric_stream.go, internal/service/elbv2/consts.go, internal/service/elbv2/listener.go, internal/service/elbv2/listener_data_source.go, internal/service/elbv2/listener_rule.go, internal/service/elbv2/load_balancer.go, internal/service/elbv2/load_balancer_data_source.go, internal/service/elbv2/target_group.go, internal/service/elbv2/target_group_data_source.go, internal/service/events/bus.go, internal/service/events/consts.go, internal/service/events/rule.go, internal/verify/verify.go
Relates #22532
```console
% make testacc TESTS='TestAccCloudWatchCompositeAlarm|TestAccCloudWatchMetricAlarm|TestAccCloudWatchMetricStream' PKG=cloudwatch TESTARGS=-short
TF_ACC=1 go test ./internal/service/cloudwatch/... -v -count 1 -parallel 20 …
```
=> ISO Tags: Improve error handling

.changelog/22722.txt, internal/service/ec2/vpc_dhcp_options_association.go, internal/service/ec2/vpc_dhcp_options_association_test.go
Closes #22716.
Prior to the fix:
```console
% make testacc TESTARGS='-run=TestAccEC2VPCDHCPOptionsAssociation_default' PKG=ec2
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 20  -run=TestAccEC2VPCDHCPOptionsAssociation_default -timeout 180m
=== RUN …
```
=> r/aws_vpc_dhcp_options_association: Support `default` DHCP Options ID

.changelog/21881.txt, internal/provider/provider.go, internal/service/imagebuilder/comonents_data_source_test.go, internal/service/imagebuilder/components_data_source.go, internal/service/imagebuilder/components_data_source_test.go, website/docs/d/imagebuilder_components.html.markdown
Relates #17035.
```
$ make testacc TESTARGS="-run=TestAccImageBuilderComponentsDataSource_" PKG_NAME=internal/service/imagebuilder
TF_ACC=1 go test ./internal/service/imagebuilder/... -v -count 1 -parallel 20 -run=TestAccImageBuilderComponentsDataSource_ -timeout 180m …
```
=> d/aws_imagebuilder_components - new data source

.changelog/15806.txt, internal/service/ec2/vpn_connection.go
The computed `customer_gateway_configuration` on `aws_vpn_connection` contains the raw XML of the VPN connection. This includes all the pre-shared keys which are already sensitive on the resource. Seems like the xml should be too so you don't see it in the stdout when the resource is destroyed:
```
- resource "aws_vpn_connection" "example" {
- arn …
```
=> aws_vpn_connection resource's customer_gateway_configuration should be sensitive

.changelog/22723.txt, internal/provider/provider.go, internal/service/imagebuilder/infrastructure_configurations_data_source.go, internal/service/imagebuilder/infrastructure_configurations_data_source_test.go, website/docs/d/imagebuilder_infrastructure_configurations.html.markdown
Relates #17035.
```
$ make testacc TESTARGS="-run=TestAccImageBuilderInfrastructureConfigurationsDataSource_filter" PKG_NAME=internal/service/imagebuilder …
```
=> d/aws_imagebuilder_infrastructure_configurations - new data source

.changelog/22733.txt, internal/provider/provider.go, internal/service/imagebuilder/distribution_configurations_data_source.go, internal/service/imagebuilder/distribution_configurations_data_source_test.go, website/docs/d/imagebuilder_distribution_configurations.html.markdown
Closes #17035.
```
$ make testacc TESTARGS="-run=TestAccImageBuilderDistributionConfigurationsDataSource_" PKG_NAME=internal/service/imagebuilder …
```
=> d/aws_imagebuilder_distribution_configurations - new data source

.changelog/22732.txt, internal/provider/provider.go, internal/service/apigatewayv2/export_data_source.go, internal/service/apigatewayv2/export_data_source_test.go, website/docs/d/apigatewayv2_export.html.markdown
Closes #12942.
```
$ make testacc TESTS=TestAccExportGatewayV2ExportDataSource_ PKG=apigatewayv2
--- PASS: TestAccExportGatewayV2ExportDataSource_basic (40.71s)
--- PASS: TestAccExportGatewayV2ExportDataSource_stage (49.20s)
```
=> d/apigatewayv2_export - new data source

docs/contributing/error-handling.md, docs/contributing/retries-and-waiters.md
Removes remaining references to `waiter` package in docs, e.g. `waiter.ThingCreated'.
No further references to `waiter` package remain, aside from the service packages refactor guide instructing folks to adapt them:
```bash
❯ grep -rnw 'waiter\.\S*'
grep: .git/objects/pack/pack-8bd2e66db795e65187bf2be768561fa514040173.pack: binary file matches …
```
=> Amend remaining references to separate 'waiter' package

.changelog/22719.txt, internal/service/ec2/instance.go, internal/service/ec2/instance_test.go, internal/service/ec2/wait.go
Reworks https://github.com/hashicorp/terraform-provider-aws/pull/16694
Closes #16689
Closes #16477
Closes https://github.com/hashicorp/terraform-provider-aws/issues/17284
Closes #20821
Closes #22660 
Closes https://github.com/hashicorp/terraform-provider-aws/issues/19779
New test before code change:
```
=== RUN …
```
=> r/instance: prevent panic when instance does not have block devices

.changelog/22758.txt, internal/service/imagebuilder/distribution_configuration.go, internal/service/imagebuilder/distribution_configuration_test.go, website/docs/r/imagebuilder_distribution_configuration.html.markdown
Relates https://github.com/hashicorp/terraform-provider-aws/issues/16839.
```
$ make testacc TESTARGS="-run=TestAccImageBuilderDistributionConfiguration_DistributionContainerDistribution_" PKG_NAME=internal/service/imagebuilder …
```
=> r/aws_imagebuilder_distribution_configuration - add container_distribution_configuration attribute

website/docs/r/vpc_peering_connection.html.markdown
This PR does not update any functionality of the provider, however aims to fix some incomplete information by the documentation.
The `auto_accept` option can be used only for VPC peering between VPC in the same region and environment. According to the note at the top of the page it is suggested to use a combination of `aws_vpc_peering_connection` and …
=> vpc/peering_connection Update auto_accept description to suggest the usage of the accepter when creating inter-region peering

.changelog/22045.txt, internal/service/s3/bucket_notification.go, internal/service/s3/bucket_notification_test.go, internal/service/s3/bucket_replication_configuration_test.go, internal/service/s3/bucket_test.go, website/docs/r/s3_bucket_notification.html.markdown
Added a boolean eventbridge attribute to s3/bucket_notification in order to support the EventBridge notifications for S3 buckets.
This is a draft PR. IMHO the code looks good and the acceptance test looks good, but I haven't gone through all the contribution document in detail yet. I do have one question right now though. Where/how do I write the documentation for the new attribute I have added?
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers …
=> Added a boolean eventbridge attribute to s3/bucket_notification

.changelog/22043.txt, internal/service/cloudwatchlogs/group_data_source.go, internal/service/cloudwatchlogs/group_data_source_test.go
Closes #15073.
To match what we have on the resource create/read in https://github.com/hashicorp/terraform-provider-aws/blob/187f1659a4fef11ac314567273b5470afe6b662f/internal/service/cloudwatchlogs/group.go#L142
Potential breaking change since we don't know what string manipulation clients do on their end :/
I'll add acctest output and changelog if that makes since to merge this PR.
Potential refactor : reuse what we do after https://github.com/hashicorp/terraform-provider-aws/blob/187f1659a4fef11ac314567273b5470afe6b662f/internal/service/cloudwatchlogs/group.go#L131 in https://github.com/hashicorp/terraform-provider-aws/blame/187f1659a4fef11ac314567273b5470afe6b662f/internal/service/cloudwatchlogs/group_data_source.go#L46 - out of scope of this PR however.
* Please vote on this pull …
=> remove :* suffix on cloudwatchlog group datasource

.changelog/22780.txt, internal/service/cloudwatch/composite_alarm.go, internal/service/cloudwatch/metric_alarm.go, internal/service/cloudwatch/metric_stream.go, internal/service/ecr/consts.go, internal/service/ecr/repository.go, internal/service/ecr/repository_data_source.go, internal/service/ecs/capacity_provider.go, internal/service/ecs/cluster.go, internal/service/ecs/service.go, internal/service/ecs/task_definition.go, internal/service/ecs/task_set.go, internal/service/events/bus.go, internal/service/events/rule.go, internal/service/iam/consts.go, internal/service/iam/role.go, internal/service/iam/role_data_source.go, internal/service/iam/user.go, internal/service/iam/user_data_source.go, internal/service/sns/consts.go, internal/service/sns/topic.go, internal/service/sns/topic_test.go, internal/service/sqs/consts.go, internal/service/sqs/queue.go, internal/service/sqs/queue_data_source.go, internal/verify/verify.go
Relates #22532
```console
% make testacc TESTS='TestAccCloudWatchCompositeAlarm_|TestAccCloudWatchMetricAlarm_|TestAccCloudWatchMetricStream_' PKG=cloudwatch
TF_ACC=1 go test ./internal/service/cloudwatch/... -v -count 1 -parallel 20 …
```
=> ISO tagging: Further refine error handling

.changelog/22796.txt, internal/service/ec2/vpc_endpoint_subnet_association.go, internal/service/ec2/vpc_endpoint_subnet_association_test.go, website/docs/r/vpc_endpoint_subnet_association.html.markdown
This is essentially the same as #10454, with subnet ID replacing route table ID.
```
% make testacc TESTS=TestAccEC2VPCEndpointRouteTableAssociation_ PKG=ec2
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 20 …
```
=> r/vpc_endpoint_subnet_association: Fix resource import

website/docs/r/secretsmanager_secret.html.markdown
=> Improve attribute description in replica configuration block for r/secretsmanager

.changelog/12141.txt, internal/provider/provider.go, internal/service/s3/bucket_cors_configuration.go, internal/service/s3/bucket_cors_configuration_test.go, internal/service/s3/errors.go, website/docs/r/s3_bucket_cors_configuration.html.markdown
Relates #4418
Relates #22776 
```release-note
**New Resource:** `aws_s3_bucket_cors_configuration`
```
```
$ make testacc TEST=./aws TESTARGS='-run=TestAccAWSS3BucketCorsConfiguration' …
```
=> Add aws_s3_bucket_cors_configuration resource

.changelog/22783.txt, internal/service/ecs/cluster.go, website/docs/r/ecs_cluster.html.markdown
Closes https://github.com/hashicorp/terraform-provider-aws/issues/22754
Relates #22672
Relates #22776 
```
n/a
```
=> r/aws_ecs_cluster: deprecate capacity provider attributes

.changelog/22806.txt, internal/service/ec2/find.go, internal/service/ec2/status.go
In aws-iso region the AssociationState isn't set in the Associations for route tables. This caused a nil pointer dereference and an RPC error when refreshing state on an `aws_route_table_association` resource.
For reference the output from the AWS CLI command `aws ec2 describe-route-tables` looks like this in AWS us-west-2:
```
{
"RouteTables": [
{
"Associations": [
{
"AssociationState": {
"State": "associated"
},
"Main": false,
"RouteTableAssociationId": "rtbassoc-000000000000000000",
"RouteTableId": "rtb-000000000000000000",
"SubnetId": "subnet-000000000000000000"
}
...
```
And looks like this in an AWS ISO region:
```
{
"RouteTables": [
{
"Associations": [
{
"Main": false,
"RouteTableAssociationId": "rtbassoc-000000000000000000",
"RouteTableId": "rtb-000000000000000000",
"SubnetId": …
```
=> Add nil checks for route table association state

.changelog/22837.txt, internal/service/imagebuilder/image_recipe.go, internal/service/imagebuilder/image_recipe_test.go, website/docs/r/imagebuilder_image_recipe.html.markdown
Closes #20855.
```
$ make testacc TESTARGS="-run=TestAccImageBuilderImageRecipe_componentParameter" PKG_NAME=internal/service/imagebuilder …
```
=> r/aws_imagebuilder_image_recipe - add support for component parameters

.changelog/22838.txt, internal/service/imagebuilder/distribution_configuration_data_source.go, internal/service/imagebuilder/distribution_configuration_data_source_test.go, website/docs/d/imagebuilder_distribution_configuration.html.markdown
Relates #16839.
```
$ make testacc TESTARGS="-run=TestAccImageBuilderDistributionConfigurationDataSource_arn" PKG_NAME=internal/service/imagebuilder …
```
=> d/aws_imagebuilder_distribution_configuration - add container_distribution_configuration attribute

.changelog/22840.txt, internal/service/cloudformation/stack.go, internal/service/cloudformation/stack_test.go
Closes #22834
```
➜  terraform-provider-aws git:(master) ✗ make testacc TESTS=TestAccCloudFormationStack_withIAM PKG=cloudformation
TF_ACC=1 go test ./internal/service/cloudformation/... -v -count 1 -parallel 20 -run='TestAccCloudFormationStack_withIAM'  -timeout 180m …
```
=> aws_cloudformation_stack: use retry logic on IAM role error

.changelog/22856.txt, internal/service/imagebuilder/image_recipe_data_source.go, internal/service/imagebuilder/image_recipe_data_source_test.go, website/docs/d/imagebuilder_image_recipe.html.markdown
Relates #20855.
```
$ make testacc TESTARGS="-run=TestAccImageBuilderImageRecipeDataSource_arn" PKG_NAME=internal/service/imagebuilder 50s
TF_ACC=1 go test ./internal/service/imagebuilder/... -v -count 1 -parallel 20  -run=TestAccImageBuilderImageRecipeDataSource_arn …
```
=> d/aws_imagebuilder_image_recipe - add component parameter attribute

.changelog/22842.txt, internal/service/imagebuilder/distribution_configuration.go, internal/service/imagebuilder/distribution_configuration_test.go, website/docs/r/imagebuilder_distribution_configuration.html.markdown
Closes #19046.
```
$ make testacc TESTARGS="-run=TestAccImageBuilderDistributionConfiguration_Distribution_launchTemplateConfiguration" PKG_NAME=internal/service/imagebuilder …
```
=> r/aws_imagebuilder_distribution_configuration - add support for launch template configurations

.changelog/22863.txt, internal/service/ec2/vpc_ipam.go, internal/service/ec2/vpc_ipam_test.go, website/docs/r/vpc_ipam_pool.html.markdown, website/docs/r/vpc_ipam_pool_cidr.html.markdown
Relates OR Closes:
-  #22718
- #22862
```
$ make testacc TESTARGS="-run=TestAccVPCIpam_" PKG_NAME="./internal/service/ec2" ACCTEST_PARALLELISM=3
TF_ACC=1 go test ././internal/service/ec2/... -v -count 1 -parallel 3  -run=TestAccVPCIpam_ -timeout 180m
=== RUN …
```
=> aws_vpc_ipam* docs and modifyIpam fixes

internal/service/route53recoverycontrolconfig/cluster.go, internal/service/route53recoverycontrolconfig/control_panel.go, internal/service/route53recoverycontrolconfig/routing_control.go, internal/service/route53recoverycontrolconfig/safety_rule.go, internal/service/route53recoverycontrolconfig/sweep.go, internal/sweep/sweep_test.go
Closes #21967.
```console
% make sweep SWEEPARGS=-sweep-run=aws_route53recoverycontrolconfig_cluster SWEEP=us-east-1
go test ./internal/sweep -v -tags=sweep -sweep=us-east-1 -sweep-run=aws_route53recoverycontrolconfig_cluster -timeout 60m
2022/01/28 …
```
=> Add Route 53 Recovery Control sweepers

.changelog/22743.txt, internal/service/ec2/subnet_ids_data_source.go, website/docs/d/subnet_ids.html.markdown
Closes #20592.
Relates #20433.
Relates #22818.
```console
% make testacc TESTS=TestAccEC2SubnetIDsDataSource_ PKG=ec2
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 20 -run='TestAccEC2SubnetIDsDataSource_'  -timeout 180m
=== RUN …
```
=> d/aws_subnet_ids: Deprecate

internal/conns/conns.go, main.go
Fixes two logging issues
1. Since the Terraform CLI handles logging levels, providers should emit all logs and let Terraform handle it. Always log AWS API requests and responses.
2. Log entries from the provider had doubled timestamps and severity, with the severity assigned by Terraform always set to `INFO`.
Before:
> 2022-02-01T11:43:22.681-0800 [INFO]  provider.terraform-provider-aws: 2022/02/01 11:43:22 [DEBUG] Reading Caller Identity: timestamp=2022-02-01T11:43:22.681-0800
After:
> 2022-02-01T11:50:30.236-0800 [DEBUG] provider.terraform-provider-aws: Reading Caller Identity: timestamp=2022-02-01T11:50:30.236-0800
=> provider: Logging fixes

.changelog/22884.txt, internal/service/imagebuilder/distribution_configuration_data_source.go, internal/service/imagebuilder/distribution_configuration_data_source_test.go, website/docs/d/imagebuilder_distribution_configuration.html.markdown
Relates #19046.
```
$ make testacc TESTARGS="-run=TestAccImageBuilderDistributionConfigurationDataSource_arn" PKG_NAME=internal/service/imagebuilder …
```
=> d/aws_imagebuilder_distribution_configuration - add launch_template_configuration attribute

.changelog/22891.txt, internal/service/ec2/client_vpn_endpoint.go, internal/service/ec2/client_vpn_endpoint_test.go
Closes #22231.
```console
% make testacc TESTARGS='-run=TestAccEC2ClientVPNEndpoint_serial/Endpoint_withLogGroup' PKG=ec2
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 20  -run=TestAccEC2ClientVPNEndpoint_serial/Endpoint_withLogGroup -timeout 180m …
```
=> r/aws_ec2_client_vpn_endpoint: `connection_log_options.cloudwatch_log_stream` is Computed

.changelog/22887.txt, internal/service/ec2/client_vpn_endpoint.go, internal/service/ec2/client_vpn_network_association.go, website/docs/r/ec2_client_vpn_endpoint.html.markdown, website/docs/r/ec2_client_vpn_network_association.html.markdown
=> r/aws_ec2_client_vpn_endpoint & r/aws_ec2_client_vpn_network_association: Deprecate `status` attribute

.changelog/22882.txt, internal/service/backup/selection.go, internal/service/backup/selection_test.go
Closes #22595.
Relates #22074.
```console
% make testacc TESTARGS='-run=TestAccBackupSelection_' PKG=backup
TF_ACC=1 go test ./internal/service/backup/... -v -count 1 -parallel 20  -run=TestAccBackupSelection_ -timeout 180m
=== RUN   TestAccBackupSelection_basic
=== …
```
=> r/aws_backup_selection: Prevent continual recreation due to `condition` and `not_resources` diffs

.changelog/22898.txt, internal/service/fsx/ontap_file_system.go, internal/service/fsx/ontap_file_system_test.go, website/docs/r/fsx_ontap_file_system.html.markdown
Closes https://github.com/hashicorp/terraform-provider-aws/issues/22896
```
make testacc TESTS=TestAccFSxOntapFileSystem PKG=fsx      
TF_ACC=1 go test ./internal/service/fsx/... -v -count 1 -parallel 20 -run='TestAccFSxOntapFileSystem'  -timeout 180m
=== RUN …
```
=> Reduce minimum file system throughput for aws_fsx_ontap_file_system

website/docs/d/cloudwatch_log_group.html.markdown, website/docs/guides/version-4-upgrade.html.md
=> Version 4 Upgrade Guide Base

.changelog/22666.txt, internal/service/elasticache/replication_group.go, website/docs/r/elasticache_replication_group.html.markdown
Relates https://github.com/hashicorp/terraform-provider-aws/issues/18440
```
--- PASS: TestAccElastiCacheReplicationGroup_ClusterModeUpdateNumNodeGroupsAndReplicasPerNodeGroup_scaleDown (2895.64s)
--- PASS: TestAccElastiCacheReplicationGroup_ClusterModeUpdateNumNodeGroupsAndReplicasPerNodeGroup_scaleUp (3412.37s)
--- PASS: …
```
=> r/elasticache_replication_group: deprecations/addition of args to align with API

.changelog/22662.txt, internal/service/autoscaling/attachment.go, website/docs/r/autoscaling_attachment.html.markdown
Relates https://github.com/hashicorp/terraform-provider-aws/issues/5407
Relates #20433
* Deprecation of `alb_target_group_arn` for removal in 5.0
```
--- PASS: TestAccAutoScalingAttachment_elb (115.07s)
--- PASS: TestAccAutoScalingAttachment_albTargetGroup (131.43s)
```
=> r/autoscaling_attachment: deprecate `alb_target_group_arn` and add `lb_target_group_arn`

.changelog/22663.txt, internal/service/autoscaling/group.go, website/docs/r/autoscaling_group.html.markdown
Relates https://github.com/hashicorp/terraform-provider-aws/issues/7655
Relates #20433
* Deprecation of `tags` for removal in 5.0 (originally removal was set to 4.0 but this resource must be used frequently enough that I think warrants more time until ultimate removal)
```
N/A
```
=> r/autoscaling_group: deprecate `tags`

website/docs/r/budgets_budget.html.markdown
Link references `#Budget-Notification` where actual fragment is `#budget-notification`.
While this reference seems to work correctly on GitHub, it does not on [the actual page in production](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/budgets_budget#argument-reference).
=> Correct fragment identifier reference

.changelog/22805.txt, internal/service/batch/compute_environment.go, internal/service/batch/compute_environment_test.go
Closes #19087.
Relates #20433.
Relates #22776.
Relates #22818.
```console
% make testacc TESTS=TestAccBatchComputeEnvironment_ PKG=batch
TF_ACC=1 go test ./internal/service/batch/... -v -count 1 -parallel 20 -run='TestAccBatchComputeEnvironment_'  -timeout 180m
=== RUN …
```
=> r/aws_batch_compute_environment: Enforce no `compute_resources` block for `UNMANAGED` compute environments

.changelog/22882.txt, internal/service/backup/selection.go, internal/service/backup/selection_test.go
Relates #22882.
Relates #22595.
```console
% make testacc TESTARGS='-run=TestAccBackupSelection_' PKG=backup
TF_ACC=1 go test ./internal/service/backup/... -v -count 1 -parallel 20  -run=TestAccBackupSelection_ -timeout 180m
=== RUN   TestAccBackupSelection_basic
=== PAUSE …
```
=> release/3.x: Backport of #22882 (r/aws_backup_selection continual diffs)

.changelog/22803.txt, internal/service/events/target.go, internal/service/events/target_test.go, website/docs/guides/version-4-upgrade.html.md
Closes https://github.com/hashicorp/terraform-provider-aws/issues/16078
Relates https://github.com/hashicorp/terraform-provider-aws/pull/22776
Relates #20433 
```
--- PASS: TestAccEventsTarget_Input_transformer (104.27s)
--- PASS: TestAccEventsTarget_RetryPolicy_deadLetter (109.71s)
--- PASS: TestAccEventsTarget_basic …
```
=> r/cloudwatch_event_target: remove launch_type default

.changelog/22850.txt, .changelog/22877.txt, CHANGELOG.md, internal/provider/provider.go, internal/service/s3/bucket_object.go, internal/service/s3/bucket_object_data_source.go, internal/service/s3/bucket_object_data_source_test.go, internal/service/s3/bucket_object_test.go, internal/service/s3/bucket_objects_data_source.go, internal/service/s3/bucket_objects_data_source_test.go, website/docs/d/s3_bucket_object.html.markdown, website/docs/d/s3_bucket_objects.html.markdown, website/docs/guides/version-4-upgrade.html.md, website/docs/r/s3_bucket_object.html.markdown
Relates #15458 
Relates #22776
Relates #22850
```console
% make testacc TESTS=TestAccS3BucketObject_ PKG=s3
TF_ACC=1 go test ./internal/service/s3/... -v -count 1 -parallel 20 -run='TestAccS3BucketObject_'  -timeout 180m
--- SKIP: TestAccS3BucketObject_nonVersioned …
```
=> Add s3_bucket_object deprecated copies

.changelog/22804.txt, internal/acctest/acctest_test.go, internal/conns/conns.go, internal/provider/provider.go, internal/sweep/sweep.go, website/docs/index.html.markdown
Closes #20824
Requires hashicorp/aws-sdk-go-base#88
Relates aws/aws-sdk-go#3938
Running a similar config to #20824:
```terraform
region = "us-west-2"
assume_role {
role_arn = "arn:aws:iam::012345678901:role/Litnupras"
}
endpoints {
sts = "https://sts-fips.us-west-2.amazonaws.com"
}
}
data "aws_caller_identity" "this" {}
```
The current …
=> Enhance FIPS, DualStack, Unique STS Region Support

.changelog/22178.txt, docs/contributing/contribution-checklists.md, internal/generate/namevaluesfilters/generators/servicefilters/main.go, internal/service/rds/enum.go, internal/service/rds/instance.go, internal/service/rds/instance_test.go, internal/service/rds/wait.go, website/docs/r/db_instance.html.markdown
Setting some parameters on a replica RDS Instance causes a modify followed by a reboot. This sometimes caused errors.
Closes #11905
Closes #20538
Output from acceptance testing in Commercial partition
```
$ make testacc TESTS=TestAccRDSInstance_ PKG=rds
--- SKIP: TestAccRDSInstance_ReplicateSourceDB_deletionProtection (0.00s)
--- SKIP: TestAccRDSInstance_SnapshotIdentifier_Tags_Clear (0.00s)
--- SKIP: TestAccRDSInstance_CoIPEnabled_enabledToDisabled (1.13s)
--- SKIP: TestAccRDSInstance_CoIPEnabled_disabledToEnabled (1.23s)
--- SKIP: TestAccRDSInstance_CoIPEnabled_restoreToPointInTime (1.28s)
--- SKIP: TestAccRDSInstance_coIPEnabled (1.69s)
--- SKIP: TestAccRDSInstance_CoIPEnabled_snapshotIdentifier (7.99s)
--- SKIP: TestAccRDSInstance_ec2Classic (2.59s)
--- FAIL: …
```
=> resource/aws_db_instance: Correctly handles update and reboot for replica instances

.changelog/22648.txt, internal/provider/provider.go, internal/service/s3/bucket_website_configuration.go, internal/service/s3/bucket_website_configuration_test.go, internal/service/s3/errors.go, website/docs/r/s3_bucket_website_configuration.html.markdown
Relates #4418
Relates #20433
```
--- PASS: TestAccS3BucketWebsiteConfiguration_disappears (29.72s)
--- PASS: TestAccS3BucketWebsiteConfiguration_basic (33.03s)
--- PASS: TestAccS3BucketWebsiteConfiguration_RoutingRules_RedirectOnly (33.37s)
--- PASS: TestAccS3BucketWebsiteConfiguration_Redirect (33.38s)
--- PASS: …
```
=> r/s3_bucket_website_configuration: new resource

.changelog/22617.txt, internal/provider/provider.go, internal/service/s3/bucket_accelerate_configuration.go, internal/service/s3/bucket_accelerate_configuration_test.go, website/docs/r/s3_bucket_accelerate_configuration.html.markdown
Relates #4418
Relates #20433
```
--- PASS: TestAccS3BucketAccelerateConfiguration_disappears (27.74s)
--- PASS: TestAccS3BucketAccelerateConfiguration_basic (29.13s)
--- PASS: TestAccS3BucketAccelerateConfiguration_update (48.63s)
```
=> r/s3_bucket_accelerate_configuration: new resource

.changelog/22608.txt, internal/provider/provider.go, internal/service/s3/bucket.go, internal/service/s3/bucket_logging.go, internal/service/s3/bucket_logging_test.go, website/docs/r/s3_bucket_logging.html.markdown
Relates #4418
Relates #20433
```
--- PASS: TestAccS3BucketLogging_TargetGrantByGroup (262.51s)
--- PASS: TestAccS3BucketLogging_TargetGrantByID (266.21s)
--- PASS: TestAccS3BucketLogging_basic (104.22s)
--- PASS: TestAccS3BucketLogging_disappears (90.79s)
--- PASS: TestAccS3BucketLogging_update (266.30s)
--- SKIP: …
```
=> r/s3_bucket_logging: new resource

.changelog/22579.txt, internal/provider/provider.go, internal/service/s3/bucket_lifecycle_configuration.go, internal/service/s3/bucket_lifecycle_configuration_test.go, internal/service/s3/enum.go, internal/service/s3/errors.go, internal/service/s3/flex.go, internal/service/s3/status.go, internal/service/s3/wait.go, website/docs/r/s3_bucket_lifecycle_configuration.html.markdown
Relates https://github.com/hashicorp/terraform-provider-aws/issues/4418
Relates #20433
Closes https://github.com/hashicorp/terraform-provider-aws/issues/6188
Closes https://github.com/hashicorp/terraform-provider-aws/issues/283
```
--- PASS: TestAccS3BucketLifecycleConfiguration_disappears (294.14s)
--- PASS: …
```
=> r/s3_bucket_lifecycle_configuration: new resource

.changelog/22915.txt, .github/workflows/terraform_provider.yml, docs/contributing/contribution-checklists.md, internal/service/fsx/ontap_storage_virtual_machine.go, internal/service/fsx/ontap_storage_virtual_machine_migrate.go, internal/service/fsx/ontap_storage_virtual_machine_migrate_test.go, internal/service/fsx/ontap_storage_virtual_machine_test.go, website/docs/guides/version-4-upgrade.html.md
Closes #22247
Relates #22246
Relates #22286
```console
make testacc TESTS=TestOntapStorageVirtualMachineStateUpgradeV0 PKG=fsx
TF_ACC=1 go test ./internal/service/fsx/... -v -count 1 -parallel 20 -run='TestOntapStorageVirtualMachineStateUpgradeV0'  -timeout 180m
=== …
```
=> fsx/ontap_storeage_virtulal_mcahine: Remove deprecadted distinguidshed

.changelog/22926.txt, internal/service/ec2/customer_gateway.go, website/docs/guides/version-4-upgrade.html.md
Relates #13943
```
% make testacc TESTS=TestAccEC2CustomerGateway PKG=ec2
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 20 -run='TestAccEC2CustomerGateway'  -timeout 180m
--- PASS: TestAccEC2CustomerGateway_disappears (27.07s)
--- PASS: …
```
=> ec2/customer_gateway: Remove empty validation

.changelog/22927.txt, internal/service/ec2/route_table_association.go
Relates #22479
Closes #21629
Closes #21683 
Closes #21978 
```
➜  terraform-provider-aws git:(ec2-vpc-route-table-association-retry-logic) ✗ make testacc TESTS=TestAccEC2RouteTableAssociation PKG=ec2
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 20 …
```
=> aws_ec2_route_table_association: use retry logic on newly created resource

.changelog/22928.txt, internal/service/ec2/default_network_acl.go, internal/service/ec2/network_acl.go, website/docs/guides/version-4-upgrade.html.md
Relates #13943
```console
% make testacc TESTS='TestAccEC2DefaultNetworkACL_|TestAccEC2NetworkACL_' PKG=ec2
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 20 -run='TestAccEC2DefaultNetworkACL_|TestAccEC2NetworkACL_'  -timeout 180m
--- PASS: …
```
=> ec2/network_acl: Remove empty validation

.changelog/22939.txt, internal/service/ec2/ami.go, internal/service/ec2/ami_data_source.go, internal/service/ec2/ami_test.go, website/docs/d/ami.html.markdown, website/docs/r/ami.html.markdown
Closes #22930
```
$ make testacc TESTS=TestAccEC2AMI_ PKG=ec2
--- PASS: TestAccEC2AMI_disappears (74.03s)
--- PASS: TestAccEC2AMI_basic (79.42s)
--- PASS: TestAccEC2AMI_ephemeralBlockDevices (79.51s)
--- PASS: TestAccEC2AMI_boot (79.51s)
--- PASS: TestAccEC2AMI_gp3BlockDevice (79.98s)
--- PASS: TestAccEC2AMI_description …
```
=> rd/ami - add `boot_mode` and `outpost_arn`

.changelog/22935.txt, internal/service/fsx/lustre_file_system.go, internal/service/fsx/lustre_file_system_test.go, website/docs/r/fsx_lustre_file_system.html.markdown
Closes #22886
```
$ make testacc TESTS=TestAccFSxLustreFileSystem_ PKG=fsx
--- PASS: TestAccFSxLustreFileSystem_logConfig (834.76s)
--- PASS: TestAccFSxLustreFileSystem_basic (628.66s)
```
=> r/fsx_lustre_file_system - add `log_configuration` argument

.changelog/22941.txt, internal/service/glue/partition_index.go, internal/service/glue/wait.go, website/docs/r/glue_partition_index.html.markdown
Closes #22908
```
$ make testacc TESTS=TestAccGluePartitionIndex_ PKG=glue
--- PASS: TestAccGluePartitionIndex_Disappears_database (72.67s)
--- PASS: TestAccGluePartitionIndex_Disappears_table (78.67s)
--- PASS: TestAccGluePartitionIndex_basic (98.69s)
--- PASS: TestAccGluePartitionIndex_disappears (101.08s)
```
=> r/glue_partition_index - add timeouts

.changelog/22933.txt, internal/provider/provider.go, internal/service/dataexchange/find.go, internal/service/dataexchange/revision.go, internal/service/dataexchange/revision_test.go, website/docs/r/dataexchange_revision.html.markdown
Relates #22237
```
$ make testacc TESTS=TestAccDataExchangeRevision_ PKG=dataexchange
--- PASS: TestAccDataExchangeRevision_disappears_dataSet (29.34s)
--- PASS: TestAccDataExchangeRevision_disappears (34.00s)
--- PASS: TestAccDataExchangeRevision_basic (38.65s)
--- PASS: TestAccDataExchangeRevision_tags (91.46s)
```
=> r/dataexchanage_revision - new resource

.changelog/22946.txt, internal/service/events/target.go
Closes #22929
```
$ make testacc TESTS=TestAccEventsTarget_ PKG=events
--- PASS: TestAccEventsTarget_disappears (51.58s)
--- PASS: TestAccEventsTarget_ssmDocument (57.99s)
--- PASS: TestAccEventsTarget_generatedTargetID (58.12s)
--- PASS: TestAccEventsTarget_eventBusARN (58.92s)
--- PASS: TestAccEventsTarget_http (66.10s)
--- …
```
=> r/cloudwatch_event_target - `http_target.path_parameter_values` preserve order + validations

.changelog/22948.txt, internal/service/ec2/default_vpc.go, internal/service/ec2/instance.go, internal/service/ec2/instance_test.go, internal/service/ec2/vpc.go, internal/service/ec2/vpc_ipv6_cidr_block_association.go, website/docs/guides/version-4-upgrade.html.md
Relates #13943
```console
% make testacc TESTS='TestAccEC2VPC_|TestAccEC2VPCDataSource_' PKG=ec2
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 20 -run=TestAccEC2VPCDataSource_  -timeout 180m
--- PASS: TestAccEC2VPCDataSource_basic (39.49s)
--- PASS: …
```
=> ec2: Remove remaining empty validation

.changelog/22853.txt, internal/provider/provider.go, internal/service/s3/bucket_acl.go, internal/service/s3/bucket_acl_test.go, internal/service/s3/bucket_test.go, website/docs/r/s3_bucket.html.markdown, website/docs/r/s3_bucket_acl.html.markdown
Relates #4418
Relates #20433
```
--- PASS: TestBucketACLParseResourceID (0.00s)
--- PASS: TestBucketACLParseResourceID/empty_ID (0.00s)
--- PASS: TestBucketACLParseResourceID/incorrect_format_with_comma_separators (0.00s)
--- PASS: TestBucketACLParseResourceID/incorrect_format_with_slash_separators (0.00s)
--- PASS: …
```
=> r/s3_bucket_acl: new resource

.changelog/22613.txt, internal/service/s3/bucket.go, internal/service/s3/bucket_request_payment_configuration_test.go, internal/service/s3/bucket_test.go, website/docs/guides/version-4-upgrade.html.md, website/docs/r/s3_bucket.html.markdown
Relates #4418
Relates #20433
```
--- PASS: TestAccS3BucketAnalyticsConfiguration_WithFilter_empty (16.31s)
--- PASS: TestAccS3BucketAnalyticsConfiguration_WithFilter_multipleTags (173.68s)
--- PASS: TestAccS3BucketAnalyticsConfiguration_WithFilter_prefix (169.69s)
--- PASS: …
```
=> r/s3_bucket: read-only `request_payer` argument

.changelog/22610.txt, internal/service/s3/bucket.go, internal/service/s3/bucket_accelerate_configuration_test.go, internal/service/s3/bucket_test.go, internal/service/s3/errors.go, website/docs/guides/version-4-upgrade.html.md, website/docs/r/s3_bucket.html.markdown
Relates #4418
Relates #20433
```
--- PASS: TestAccS3BucketAnalyticsConfiguration_WithFilter_empty (15.92s)
--- PASS: TestAccS3BucketAnalyticsConfiguration_WithFilter_multipleTags (170.79s)
--- PASS: TestAccS3BucketAnalyticsConfiguration_WithFilter_prefix (173.46s)
--- PASS: …
```
=> r/s3_bucket: read-only `acceleration_status` argument

.changelog/22599.txt, internal/service/s3/bucket.go, internal/service/s3/bucket_logging_test.go, internal/service/s3/bucket_test.go, website/docs/guides/version-4-upgrade.html.md, website/docs/r/s3_bucket.html.markdown
Relates #4418
Relates #20433
```
--- PASS: TestAccS3BucketAnalyticsConfiguration_WithFilter_empty (14.78s)
--- PASS: TestAccS3BucketAnalyticsConfiguration_WithFilter_multipleTags (168.58s)
--- PASS: TestAccS3BucketAnalyticsConfiguration_WithFilter_prefix (166.48s)
--- PASS: …
```
=> r/s3_bucket: read-only `logging` argument

.changelog/22538.txt, internal/service/elb/load_balancer_test.go, internal/service/s3/bucket.go, internal/service/s3/bucket_test.go, internal/service/s3/errors.go, website/docs/d/billing_service_account.html.markdown, website/docs/d/cloudtrail_service_account.html.markdown, website/docs/d/elb_service_account.html.markdown, website/docs/d/instances.html.markdown, website/docs/d/redshift_service_account.html.markdown, website/docs/guides/version-4-upgrade.html.md, website/docs/r/s3_bucket.html.markdown
Relates #4418
Relates #20433
```
--- PASS: TestAccELBLoadBalancerDataSource_basic (162.45s)
--- PASS: TestAccELBLoadBalancer_AccessLogs_disabled (229.81s)
--- PASS: TestAccELBLoadBalancer_AccessLogs_enabled (71.85s)
--- PASS: TestAccELBLoadBalancer_ListenerSSLCertificateID_iamServerCertificate (246.75s)
--- PASS: …
```
=> r/s3_bucket: read-only `policy` argument

.changelog/22606.txt, internal/service/apigateway/domain_name_test.go, internal/service/apigatewayv2/domain_name_test.go, internal/service/athena/database_test.go, internal/service/kafkaconnect/custom_plugin_test.go, internal/service/lambda/function_test.go, internal/service/mwaa/environment_test.go, internal/service/s3/bucket.go, internal/service/s3/bucket_object_data_source_test.go, internal/service/s3/bucket_object_test.go, internal/service/s3/bucket_replication_configuration_test.go, internal/service/s3/bucket_test.go, internal/service/s3/bucket_versioning.go, internal/service/s3/errors.go, internal/service/s3/object_copy_test.go, internal/service/s3/object_data_source_test.go, internal/service/s3/object_test.go, internal/service/signer/signing_job_data_source_test.go, internal/service/signer/signing_job_test.go, internal/service/synthetics/canary_test.go, website/docs/guides/version-4-upgrade.html.md, website/docs/r/s3_bucket.html.markdown, website/docs/r/s3_bucket_lifecycle_configuration.html.markdown, website/docs/r/s3_bucket_object.html.markdown, website/docs/r/s3_bucket_replication_configuration.html.markdown, website/docs/r/s3_object.html.markdown
Relates #4418
Relates #20433
Preceded by https://github.com/hashicorp/terraform-provider-aws/pull/5132
```
--- PASS: TestAccSyntheticsCanary_StartCanary_codeChanges (106.18s)
--- PASS: TestAccSyntheticsCanary_artifactEncryption (81.56s)
--- PASS: TestAccSyntheticsCanary_basic (126.11s)
--- PASS: …
```
=> r/s3_bucket: read-only `versioning` argument

.changelog/22612.txt, internal/service/s3/bucket.go, internal/service/s3/bucket_object_lock_configuration_test.go, internal/service/s3/bucket_replication_configuration_test.go, internal/service/s3/bucket_test.go, website/docs/guides/version-4-upgrade.html.md, website/docs/r/s3_bucket.html.markdown
Relates #4418
Relates #20433
```
--- PASS: TestAccS3BucketAnalyticsConfiguration_WithFilter_empty (13.92s)
--- PASS: TestAccS3BucketAnalyticsConfiguration_WithFilter_multipleTags (167.33s)
--- PASS: TestAccS3BucketAnalyticsConfiguration_WithFilter_prefix (165.82s)
--- PASS: …
```
=> r/s3_bucket:  read-only `object_lock_configuration` `rule` argument

.changelog/22954.txt, .semgrep.yml, internal/service/efs/mount_target.go, internal/service/efs/mount_target_test.go, internal/service/elasticsearch/domain.go, internal/service/elasticsearch/domain_data_source_test.go, internal/service/elasticsearch/domain_test.go, internal/service/events/target.go, internal/service/events/target_test.go, internal/service/s3/bucket_object_test.go, website/docs/guides/version-4-upgrade.html.md
Closes #13943
```console
% make testacc TESTS=TestAccEFSMountTarget PKG=efs
TF_ACC=1 go test ./internal/service/efs/... -v -count 1 -parallel 20 -run='TestAccEFSMountTarget'  -timeout 180m
--- PASS: TestAccEFSMountTarget_IPAddress_emptyString (144.23s)
--- PASS: …
```
=> Remove last empty string validation

.changelog/22978.txt, internal/service/waf/helpers.go
Closes https://github.com/hashicorp/terraform-provider-aws/issues/22500
Closes https://github.com/hashicorp/terraform-provider-aws/issues/22378
```
--- PASS: TestAccWAFRuleGroup_noActivatedRules (24.10s)
--- PASS: TestAccWAFRuleGroup_disappears (32.71s)
--- PASS: TestAccWAFRuleGroup_basic (33.40s)
--- PASS: …
```
=> waf/helpers: prevent panic during `ExpandActivatedRule` method

internal/service/cloudformation/stack.go, internal/service/cloudformation/stack_test.go
Closes https://github.com/hashicorp/terraform-provider-aws/issues/22974
```
--- PASS: TestAccCloudFormationStack_WithURL_withParams (167.08s)
=== RUN   TestAccCloudFormationStack_WithURLWithParams_noUpdate
=== PAUSE TestAccCloudFormationStack_WithURLWithParams_noUpdate
=== CONT …
```
=> tests/cloudformation_stack: correct `aws_s3_bucket_website_configuration` resource name in test config

.changelog/22977.txt, internal/service/s3/bucket_cors_configuration.go, internal/service/s3/bucket_cors_configuration_test.go
Closes https://github.com/hashicorp/terraform-provider-aws/issues/22976
```
--- PASS: TestAccS3BucketCorsConfiguration_MultipleRules (33.28s)
--- PASS: TestAccS3BucketCorsConfiguration_basic (33.35s)
--- PASS: TestAccS3BucketCorsConfiguration_SingleRule (33.81s)
--- PASS: TestAccS3BucketCorsConfiguration_update (81.59s)
--- …
```
=> r/s3_bucket_cors_configuration: add retry around Get method during read

.changelog/22972.txt, internal/service/ec2/ami_copy.go, internal/service/ec2/ami_from_instance.go
Closes https://github.com/hashicorp/terraform-provider-aws/issues/22971
Relates: https://github.com/hashicorp/terraform-provider-aws/pull/22939
```
--- PASS: TestAccEC2AMICopy_basic (379.75s)
--- PASS: TestAccAutoScalingLaunchConfiguration_RootBlockDevice_amiDisappears (366.97s)
--- PASS: TestAccEC2AMIFromInstance_basic …
```
=> r/ami_copy, r/ami_from_instance: add `boot_mode` and `ebs_block_device.outpost_arn` args inherited from AMI resource

.changelog/22996.txt, internal/service/elbv2/target_group.go, internal/service/elbv2/target_group_test.go, website/docs/guides/version-4-upgrade.html.md
Closes #15612
```console
% make testacc TESTS=TestAccELBV2TargetGroup_ PKG=elbv2
TF_ACC=1 go test ./internal/service/elbv2/... -v -count 1 -parallel 20 -run='TestAccELBV2TargetGroup_'  -timeout 180m
--- PASS: TestAccELBV2TargetGroup_HealthCheck_without …
```
=> elbv2: Don't allow invalid configurations

.changelog/22537.txt, internal/service/s3/bucket.go, internal/service/s3/bucket_acl_test.go, internal/service/s3/bucket_test.go, website/docs/guides/version-4-upgrade.html.md, website/docs/r/s3_bucket.html.markdown
Relates https://github.com/hashicorp/terraform-provider-aws/issues/4418
```
--- PASS: TestAccS3BucketAcl_disappears (23.03s)
--- PASS: TestAccS3BucketAcl_basic (33.22s)
--- PASS: TestAccS3BucketAcl_updateACL (55.95s)
--- PASS: …
```
=> r/s3_bucket: read-only `acl` and `grant` arguments

.changelog/22668.txt, internal/service/mq/broker.go, internal/service/rds/instance.go, internal/service/rds/instance_test.go, website/docs/r/db_instance.html.markdown
Closes https://github.com/hashicorp/terraform-provider-aws/issues/22071
Requires https://github.com/hashicorp/terraform-provider-aws/pull/21457
```
```
=> r/db_instance: deprecate `name` and add `db_name`

website/docs/r/cloudwatch_event_target.html.markdown
in cloudwatch_event_target.html.markdown there is an IAM policy document referencing the action "events.PutEvents" which is not a valid action. Corrected this to "events:PutEvents"
Closes #22703
Not yet conducted
```
...
```
=> Fix error in example for cloudwatch_event_target

website/docs/r/sagemaker_domain.html.markdown
None
I'm documenting the other valid value for the `aws_sagemaker_domain` retention policy, which I found is `Delete` after looking at the [aws-go-sdk source code](https://github.com/aws/aws-sdk-go/blob/main/service/sagemaker/api.go) (search for the const `RetentionTypeDelete`), which is then used …
=> Document valid values for sagemaker domain retention policy

internal/service/ec2/errors.go, internal/service/ec2/spot_datafeed_subscription.go, internal/service/ec2/spot_datafeed_subscription_test.go
Relates #22997 
```
--- PASS: TestAccEC2SpotDatafeedSubscription_serial (70.23s)
--- PASS: TestAccEC2SpotDatafeedSubscription_serial/basic (36.93s)
--- PASS: TestAccEC2SpotDatafeedSubscription_serial/disappears (33.30s)
```
=> tests/spot_datafeed_subscription: update to `aws_s3_bucket_acl`

internal/service/cloudformation/stack_test.go, internal/service/cloudtrail/cloudtrail_test.go, internal/service/redshift/cluster_test.go
```
--- PASS: TestAccCloudFormationStack_WithURLWithParams_withYAML (91.03s)
--- SKIP: TestAccCloudTrail_serial/Trail/organization (1.58s)
--- PASS: TestAccCloudTrail_serial/Trail/logValidation (65.72s)
--- PASS: …
```
=> tech-debt/tests: Migrate to `aws_s3_bucket_policy`

internal/service/elasticache/replication_group.go, internal/service/elasticache/replication_group_test.go, website/docs/r/elasticache_replication_group.html.markdown
When creating a Redis cluster without sharding ("Cluster Mode Disabled" in AWS terminology), it is possible to specify a list of availability zones in which to place the cluster nodes. In the AWS API, the order of the list matters: the first AZ in the list is the primary AZ for the cluster, and the remainder of the nodes are assigned in order. The number of AZs in the list must match the number of nodes, and duplicates are allowed.
As currently implemented in the AWS Provider, the parameter `availability_zones` is of `TypeSet`, where order is not guaranteed and duplicates are not permitted. This means that the practitioner has no control over the location of the primary node and there can be at most one node in a given AZ.
Additionally, the current parameter name, `availability_zones`, …
=> resource/aws_elasticache_replication_group: Migrate from availability_zones TypeSet attribute to preferred_cache_cluster_azs TypeList attribute

internal/service/waf/web_acl_test.go
```
--- PASS: TestAccWAFWebACL_disappears (28.03s)
--- PASS: TestAccWAFWebACL_basic (31.43s)
--- PASS: …
```
=> tests/waf: update to `aws_s3_bucket_acl` resource

internal/service/ssm/maintenance_window_task_test.go
```
--- PASS: TestAccSSMMaintenanceWindowTask_noRole (42.72s)
--- PASS: …
```
=> tests/ssm: update to `aws_s3_bucket_acl` resource

internal/service/ses/event_destination_test.go, internal/service/ses/receipt_rule_test.go
```
--- PASS: TestAccSESReceiptRuleSet_disappears (46.00s)
--- PASS: TestAccSESReceiptRuleSet_basic (47.75s) …
```
=> tests/ses: update to `aws_s3_bucket_acl` resource

internal/service/wafv2/web_acl_logging_configuration_test.go
Relates #22537 
Relates #20433 
```
--- PASS: TestAccWAFV2WebACLLoggingConfiguration_basic (119.76s)
--- PASS: TestAccWAFV2WebACLLoggingConfiguration_updateSingleHeaderRedactedField (157.38s)
--- PASS: …
```
=> tests/wafv2: update to `aws_s3_bucket_acl` resource

internal/service/route53/record_test.go
```
--- PASS: TestAccRoute53Record_Alias_s3 (141.54s)
```
=> tests/route53: update to `aws_s3_bucket_acl` resource

internal/service/servicecatalog/constraint_test.go, internal/service/servicecatalog/product_test.go, internal/service/servicecatalog/provisioned_product_test.go, internal/service/servicecatalog/provisioning_artifact_test.go
```
--- PASS: TestAccServiceCatalogConstraintDataSource_basic (91.09s)
--- PASS: …
```
=> tests/servicecatalog: update to `aws_s3_bucket_acl` resource

website/docs/r/security_group_rule.html.markdown
I wanted to add an example which shows how to use the `aws_prefix_list`
resource to look up a prefix list which wasn't based on a VPC endpoint,
especially because there's a financial incentive to use S3 Gateway
interfaces instead of VPC endpoint interfaces.
=> Example of using a non-VPC endpoint prefix with a security group

internal/service/synthetics/canary_test.go
```
--- PASS: TestAccSyntheticsCanary_artifactEncryption (96.88s)
--- PASS: TestAccSyntheticsCanary_basic …
```
=> tests/synthetics: update to `aws_s3_bucket_acl` resource

internal/service/sagemaker/app_test.go, internal/service/sagemaker/device_fleet_test.go, internal/service/sagemaker/device_test.go, internal/service/sagemaker/endpoint_configuration_test.go, internal/service/sagemaker/endpoint_test.go, internal/service/sagemaker/feature_group_test.go, internal/service/sagemaker/flow_definition_test.go, internal/service/sagemaker/model_test.go, internal/service/sagemaker/notebook_instance_test.go, internal/service/sagemaker/project_test.go, internal/service/sagemaker/sagemaker_test.go
```
--- PASS: TestAccSageMaker_serial (7709.63s)
--- PASS: TestAccSageMaker_serial/App/basic (381.95s)
--- …
```
=> tests/sagemaker: update to `aws_s3_bucket_acl` resource

.changelog/23030.txt, internal/service/ecs/capacity_provider.go, internal/service/ecs/cluster.go, internal/service/ecs/find.go, internal/service/ecs/service.go, internal/service/ecs/task_definition.go, internal/service/ecs/task_set.go
Relates #22532
```console
% make testacc TESTS=TestAccECS PKG=ecs                      
TF_ACC=1 go test ./internal/service/ecs/... -v -count 1 -parallel 20 -run='TestAccECS'  -timeout 180m
--- PASS: TestAccECSAccountSettingDefault_containerInstanceLongARNFormat …
```
=> ecs: Fix ISO tagging

.changelog/21732.txt, internal/service/wafv2/web_acl.go, internal/service/wafv2/web_acl_test.go, website/docs/r/wafv2_web_acl.html.markdown
Closes #20817 #21546 
```
$ make testacc TESTARGS='-run=TestAccWAFV2WebACL_.*' PKG_NAME=internal/service/wafv2
TF_ACC=1 go test ./internal/service/wafv2/... -v -count 1 -parallel 20 -run=TestAccWAFV2WebACL_.* -timeout 180m
=== RUN   TestAccWAFV2WebACL_basic
=== PAUSE …
```
=> aws wafv2 webacl managed rule group version support

internal/service/quicksight/data_source_test.go
```
--- PASS: TestAccQuickSightDataSource_disappears (36.44s)
--- PASS: TestAccQuickSightDataSource_basic …
```
=> tests/quicksight: update to `aws_s3_bucket_acl`

internal/service/lakeformation/permissions_data_source_test.go, internal/service/lakeformation/permissions_test.go
```
--- PASS: TestAccLakeFormation_serial (289.72s)
--- PASS: TestAccLakeFormation_serial/PermissionsBasic …
```
=> tests/lakeformation: update to `aws_s3_bucket_acl`

website/docs/r/lex_intent.html.markdown
This is a small documentation change to enumerate accepted values for a field. Any recommended changes to match documentation style would be welcome.
```
...
```
=> Add a list of valid types to lex intent fulfillment

internal/service/lambda/function_test.go, internal/service/lambda/permission_test.go
```
--- PASS: TestAccLambdaFunction_expectFilenameAndS3Attributes (21.25s)
--- PASS: …
```
=> tests/lambda: update to `aws_s3_bucket_acl`

internal/service/networkfirewall/logging_configuration_test.go
```
--- PASS: TestAccNetworkFirewallLoggingConfiguration_CloudWatchLogDestination_logGroup (719.80s)
--- PASS: …
```
=> tests/networkfirewall: update to `aws_s3_bucket_acl`

internal/service/guardduty/ipset_test.go, internal/service/guardduty/publishing_destination_test.go, internal/service/guardduty/threatintelset_test.go
Output from acceptance testing (had to run these in the Organizations-only account...maybe they should only run there since there seems to be a …
=> tests/guardduty: update to `aws_s3_bucket_acl`

internal/service/globalaccelerator/accelerator_test.go
```
--- PASS: TestAccGlobalAcceleratorAccelerator_attributes (305.19s)
```
=> tests/globalaccelerator: update to `aws_s3_bucket_acl`

internal/service/kafka/cluster_test.go
```
--- PASS: TestAccKafkaCluster_loggingInfo (2254.91s)
```
=> tests/kafka: update to `aws_s3_bucket_acl`

internal/service/elastictranscoder/pipeline_test.go
```
--- PASS: TestAccElasticTranscoderPipeline_disappears (155.60s)
--- PASS: …
```
=> tests/elastictranscoder: update to `aws_s3_bucket_acl`

internal/service/elb/load_balancer_test.go
```
--- PASS: TestAccELBLoadBalancer_AccessLogs_disabled (85.49s)
--- PASS: …
```
=> tests/elb: update to `aws_s3_bucket_acl`

internal/service/cur/report_definition_data_source_test.go, internal/service/cur/report_definition_test.go
```
--- PASS: TestAccCURReportDefinitionDataSource_additional (22.31s)
--- PASS: …
```
=> tests/cur: update to `aws_s3_bucket_acl`

internal/service/configservice/conformance_pack_test.go, internal/service/configservice/organization_conformance_pack_test.go
```
--- PASS: TestAccConfigService_serial (4523.11s)
--- PASS: …
```
=> tests/configservice: update to `aws_s3_bucket_acl`

internal/service/s3/bucket_data_source_test.go, internal/service/s3/bucket_inventory_test.go, internal/service/s3/bucket_lifecycle_configuration_test.go, internal/service/s3/bucket_logging_test.go, internal/service/s3/bucket_metric_test.go, internal/service/s3/bucket_notification_test.go, internal/service/s3/bucket_replication_configuration_test.go, internal/service/s3/bucket_versioning_test.go, internal/service/s3/bucket_website_configuration_test.go
```
--- PASS: TestAccS3BucketAccelerateConfiguration_basic (103.15s)
--- PASS: …
```
=> tests/s3: update to `aws_s3_bucket_acl` resource

internal/service/cloudwatchlogs/subscription_filter_test.go
```
--- PASS: TestAccCloudWatchLogsSubscriptionFilter_basic (43.46s)
--- PASS: …
```
=> tests/cloudwatchlogs: update to `aws_s3_bucket_acl`

internal/service/cloudwatch/metric_stream_test.go
```
--- PASS: TestAccCloudWatchMetricStream_tags (23.25s)
--- PASS: …
```
=> tests/cloudwatch: update to `aws_s3_bucket_acl`

internal/service/cloudfront/distribution_test.go
```
--- PASS: TestAccCloudFrontDistribution_originPolicyOrdered (396.56s)
--- PASS: …
```
=> tests/cloudfront: update to `aws_s3_bucket_acl`

.changelog/23052.txt, internal/conns/conns.go, internal/provider/provider.go, internal/provider/provider_test.go, website/docs/guides/custom-service-endpoints.html.md
Adds environment variables to override AWS API endpoints for parity with the S3 backend:
* TF_AWS_DYNAMODB_ENDPOINT
* TF_AWS_IAM_ENDPOINT
* TF_AWS_S3_ENDPOINT
* TF_AWS_STS_ENDPOINT
New and already deprecated environment variables (hashicorp/terraform#30479)
* AWS_DYNAMODB_ENDPOINT
* AWS_IAM_ENDPOINT
* AWS_S3_ENDPOINT
* AWS_STS_ENDPOINT
Closes #23025
Test results
```console
$ go test ./internal/provider/... -v
=== RUN   TestExpandEndpoints
--- PASS: TestExpandEndpoints (0.00s)
=== RUN   TestEndpointMultipleKeys
--- PASS: TestEndpointMultipleKeys (0.01s)
=== RUN   TestEndpointEnvVarPrecedence
2022/02/08 17:39:13 [WARN] The environment variable "AWS_STS_ENDPOINT" is deprecated. Use "TF_AWS_STS_ENDPOINT" instead.
--- PASS: TestEndpointEnvVarPrecedence (0.01s)
PASS
ok …
```
=> provider: Add environment variable support for DynamoDB, IAM, S3, STS endpoints

internal/service/apigateway/stage_test.go
```
--- PASS: TestAccAPIGatewayStage_AccessLogSettings_kinesis (252.79s)
```
=> tests/apigateway: update to `aws_s3_bucket_acl`

internal/service/emr/cluster_test.go, internal/service/emr/studio_session_mapping_test.go, internal/service/emr/studio_test.go
```
--- FAIL: TestAccEMRCluster_visibleToAllUsers (748.82s) <--- history of failures for quite some time in …
```
=> tests/emr: update to `aws_s3_bucket_acl`

internal/service/fsx/data_repository_association_test.go, internal/service/fsx/lustre_file_system_test.go
```
--- PASS: TestAccFSxDataRepositoryAssociation_s3AutoExportPolicyUpdate (879.65s)
--- PASS: …
```
=> tests/fsx: update to `aws_s3_bucket_acl`

internal/acctest/acctest_test.go
```
--- PASS: TestAccAcctestProvider_Region_awsCommercial (21.93s)
--- PASS: …
```
=> tests/acctest: update to `aws_s3_bucket_acl`

.changelog/21076.txt, internal/service/apigateway/acc_test.go, internal/service/apigateway/domain_name.go, internal/service/apigateway/domain_name_test.go, internal/service/apigateway/errorcheck_test.go, internal/service/apigatewayv2/domain_name.go, internal/service/apigatewayv2/domain_name_test.go, internal/service/apigatewayv2/errorcheck_test.go, internal/service/s3/bucket_versioning.go, internal/service/s3/status.go, internal/service/s3/wait.go, website/docs/d/api_gateway_domain_name.html.markdown, website/docs/guides/version-4-upgrade.html.md, website/docs/r/api_gateway_domain_name.html.markdown, website/docs/r/apigatewayv2_domain_name.html.markdown, website/docs/r/s3_bucket_versioning.html.markdown
- add `ownership_verification_certificate_arn` to:
- `aws_apigatewayv2_domain_name.domain_name_configuration`,
- `aws_api_gateway_domain_name`.
- update documentation to include `ownership_verification_certificate_arn`;
- add separate tests for mTLS with ownership-verification (as it requires both a public cert. for verification plus an imported cert. to trigger the requirement.)
- the existing test framework provides `testAccAWSAPIGatewayV2DomainNameConfigPublicCert()` and `testAccAWSAPIGatewayV2DomainNameConfigImportedCerts()` for creating certs. However, both create a `aws_acm_certificate.test` resource (i.e. a conflicting name.) As this change effectively requires both (mTLS with an imported ACM cert. but using an ACM-issued cert. for verification), I've opted to use the former and …
=> Add ownership-verification-cert. to API Gateway

website/docs/index.html.markdown
Document support for `AWS_REGION` in addition to `AWS_DEFAULT_REGION`. Precedence: provider block, `AWS_REGION`, `AWS_DEFAULT_REGION`, shared configuration file.
Document support for `AWS_MAX_ATTEMPTS` environment variable. Precedence: provider block, `AWS_MAX_ATTEMPTS`.
Closes #23024
=> documentation: Provider configuration updates

.changelog/22960.txt, internal/service/sagemaker/endpoint_configuration.go, internal/service/sagemaker/endpoint_configuration_test.go
Closes #22951
```
$ make testacc TESTS=TestAccSageMakerEndpointConfiguration_ PKG=sagemaker
--- PASS: TestAccSageMakerEndpointConfiguration_ProductionVariants_initialVariantWeight (66.56s)
--- PASS: TestAccSageMakerEndpointConfiguration_disappears (76.99s)
--- PASS: TestAccSageMakerEndpointConfiguration_async_kms (78.75s)
--- …
```
=> r/sagemaker_endpoint_configuration - emptiness check for arguments

.changelog/22963.txt, internal/service/glue/trigger.go, internal/service/glue/trigger_test.go, website/docs/r/glue_trigger.html.markdown
```
$ make testacc TESTS=TestAccGlueTrigger_  PKG=glue
--- PASS: TestAccGlueTrigger_disappears (137.97s)
--- PASS: TestAccGlueTrigger_workflowName (138.09s)
--- PASS: TestAccGlueTrigger_basic (140.23s)
--- PASS: TestAccGlueTrigger_Actions_security (141.79s)
--- PASS: TestAccGlueTrigger_startOnCreate (162.45s)
--- PASS: …
```
=> r/glue_trigger - add `event_batching_condition`

.changelog/23127.txt, internal/service/ec2/enum.go
Closes #23105.
Unable to test the new value, so just ran a simple regression test:
```console
% make testacc TESTS=TestAccEC2VPNConnection_basic PKG=ec2     
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 20 -run='TestAccEC2VPNConnection_basic'  -timeout 180m
=== RUN …
```
=> Add undocumented `ipsec.1-aes256` VPN Connection type

website/docs/guides/version-4-upgrade.html.md
Updates Provider Config Block in v4 Upgrade guide to use the `terraform.required_providers` syntax necessary for TF 0.13+.
=> v4 Upgrade Guide: update tf provider configuraiton block

.changelog/23134.txt, internal/provider/provider.go, internal/service/imagebuilder/container_recipes_data_source.go, internal/service/imagebuilder/container_recipes_data_source_test.go, website/docs/d/imagebuilder_container_recipes.html.markdown
Relates #16839.
```
$ make testacc PKG_NAME=internal/service/imagebuilder TESTARGS="-run=TestAccImageBuilderContainerRecipesDataSource_filter" …
```
=> d/aws_imagebuilder_container_recipes - new data source

.changelog/23127.txt, internal/service/ec2/enum.go
Relates #23127.
Relates https://github.com/hashicorp/terraform-provider-aws/issues/23105.
```console
% make testacc TESTS=TestAccEC2VPNConnection_basic PKG=ec2
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 20 -run='TestAccEC2VPNConnection_basic' …
```
=> Backport of #23127 to `release/3.x`

.changelog/23039.txt, internal/service/rds/cluster.go, internal/service/rds/engine_version_test.go
Relates #23039.
Relates https://github.com/hashicorp/terraform-provider-aws/issues/22542.
Relates https://github.com/hashicorp/terraform-provider-aws/issues/20860.
```console
% go test -v ./internal/service/rds '-run=TestCompareActualEngineVersion'
=== RUN   TestCompareActualEngineVersion
=== PAUSE TestCompareActualEngineVersion
=== CONT …
```
=> Backport of #23039 to `release/3.x`

internal/service/lambda/permission.go, internal/service/lambda/validate.go, internal/service/lambda/validate_test.go
Relates #11872
```
--- PASS: TestAccLambdaPermission_withS3 (82.21s)
--- PASS: TestAccLambdaPermission_withIAMRole (100.22s)
--- PASS: TestAccLambdaPermission_withQualifier (111.20s)
--- PASS: TestAccLambdaPermission_withStatementIdPrefix (117.18s)
--- PASS: TestAccLambdaPermission_basic (125.70s)
--- PASS: …
```
=> service/lambda: tech debt: fix V001 linter errors

.changelog/23151.txt, internal/service/apigateway/authorizer.go, internal/service/apigateway/authorizer_test.go, website/docs/r/api_gateway_authorizer.html.markdown
```
$ make testacc TESTS=TestAccAPIGatewayAuthorizer_ PKG=apigateway
--- PASS: TestAccAPIGatewayAuthorizer_Cognito_authorizerCredentials (47.95s)
--- PASS: TestAccAPIGatewayAuthorizer_disappears (77.89s)
--- PASS: TestAccAPIGatewayAuthorizer_authTypeValidation (78.14s)
--- PASS: TestAccAPIGatewayAuthorizer_basic (140.18s)
--- …
```
=> r/api_gateway_authorizer - add `arn` attribute

.changelog/12384.txt, internal/service/iam/user_login_profile.go, internal/service/iam/user_login_profile_test.go, website/docs/r/iam_user_login_profile.html.markdown
Closes #4564
```
$ make testacc TESTARGS='-run=TestAccAWSUserLoginProfile_'
--- PASS: TestAccAWSUserLoginProfile_notAKey (34.68s)
--- PASS: TestAccAWSUserLoginProfile_keybaseDoesntExist (36.00s)
--- PASS: …
```
=>  r/aws_iam_user_login_profile  - Make the PGP key in optional

.changelog/17732.txt, internal/service/ssm/association.go, internal/service/ssm/association_test.go, internal/service/ssm/find.go, internal/service/ssm/status.go, internal/service/ssm/wait.go, website/docs/r/ssm_association.html.markdown
```
$ make testacc TESTARGS='-run=TestAccAWSSSMAssociation_'
--- PASS: TestAccSSMAssociation_withDocumentVersion (52.79s)
--- PASS: TestAccSSMAssociation_applyOnlyAtCronInterval (85.90s)
--- PASS: TestAccSSMAssociation_withScheduleExpression (86.16s)
--- PASS: TestAccSSMAssociation_withAssociationNameAndScheduleExpression …
```
=> r/ssm_association - validations + wait for association argument + arn attribute

.changelog/23035.txt, internal/service/appmesh/flex.go, internal/service/appmesh/route_test.go
Similarly to #13479 setting `max_retries` to `0` in the route retry policy fails with:
```
- missing required field, UpdateRouteInput.Spec.GrpcRoute.RetryPolicy.MaxRetries
```
Relates #13479
```
$ make testacc TESTS=TestAccAppMesh_serial/Route PKG=appmesh
--- PASS: TestAccAppMesh_serial/Route (1027.26s)
--- PASS: …
```
=> r/aws_appmesh_route: Handle zero max_retries

internal/service/iam/instance_profile.go, internal/service/iam/policy.go, internal/service/iam/role.go, internal/service/iam/role_policy.go, internal/service/iam/validate.go, internal/service/iam/validate_test.go
Fixes [`providerlint`](https://github.com/bflad/tfproviderlint) [V001](https://github.com/bflad/tfproviderlint/tree/main/passes/V001) errors for IAM resources
Relates #11872
```
$ make testacc TESTS='TestAccIAMRolePolicy_|TestAccIAMRole_|TestAccIAMPolicy_|TestAccIAMInstanceProfile_' PKG=iam
--- PASS: TestAccIAMRole_badJSON (32.62s)
--- FAIL: TestAccIAMRole_InlinePolicy_empty (92.57s)
--- PASS: TestAccIAMRole_disappears (109.38s)
--- PASS: TestAccIAMRole_nameGenerated (135.41s)
--- PASS: TestAccIAMInstanceProfile_basic (143.16s)
--- PASS: TestAccIAMRole_policiesForceDetach (145.93s)
--- FAIL: TestAccIAMRole_InlinePolicy_outOfBandRemovalAddedBack (170.76s)
--- FAIL: TestAccIAMRole_InlinePolicy_outOfBandAdditionRemovedEmpty (185.14s)
--- PASS: …
```
=> linting: Fix `providerlint` V001 errors for IAM resources

.changelog/23120.txt, internal/service/s3/bucket_lifecycle_configuration_test.go, internal/service/s3/flex.go, website/docs/r/s3_bucket_lifecycle_configuration.html.markdown
=> Allow S3 lifecycle 'days' parameter in S3 transition lifecycle to be >= 0. Issue #23117

.github/workflows/terraform_provider.yml
Should prevent CI errors like:
```
package github.com/hashicorp/terraform-provider-aws/internal/generate/listpages: build constraints exclude all Go files in /home/runner/work/terraform-provider-aws/terraform-provider-aws/internal/generate/listpages
```
=> GH Actions: Don't run tests for `internal/generate` package

.changelog/23187.txt, internal/service/autoscaling/group.go, internal/service/autoscaling/group_test.go
Closes https://github.com/hashicorp/terraform-provider-aws/issues/5278
Before draining instances during a destroy, switch off scale-in protection of all instances in the ASG. This is necessary as the resource chooses to reduce desired (and actual) instance count to 0 before destroying the ASG.
This behaviour shouldn't be a semantic concession, as deleting …
=> r/aws_autoscaling_group: disable scale-in protection before draining instances

.changelog/23195.txt, internal/service/ec2/vpc_ipam_pool_data_source.go, website/docs/d/vpc_ipam_pool.html.markdown
Relates OR Closes #23194
```
$ make testacc TESTS=TestAccDataSourceVPCIpamPool_basic PKG=ec2  
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 20 -run='TestAccDataSourceVPCIpamPool_basic'  -timeout 180m
=== RUN   TestAccDataSourceVPCIpamPool_basic
=== …
```
=> data_source/aws_vpc_ipam_pool: Add filter examples to docs, add error if no pool found

.changelog/23144.txt, internal/service/s3/bucket_lifecycle_configuration.go, internal/service/s3/bucket_lifecycle_configuration_test.go, internal/service/s3/flex.go, internal/service/s3/status.go, internal/service/s3/wait.go, website/docs/r/s3_bucket_lifecycle_configuration.html.markdown
Closes #23129
Closes #23132
Import test starting configuration (corresponding to #23129 and #23132):
```terraform
terraform {
aws = {
version = "3.74.1"
}
}
}
resource "aws_s3_bucket" "example" {
bucket = "barrameda-994617143"
lifecycle_rule {
id      = "log-expiration"
enabled = true
prefix  = ""
transition { …
```
=> s3_bucket_lifecycle_configuration: Fix import, diffs

go.mod, internal/service/grafana/workspace.go, internal/service/grafana/workspace_data_source.go
```
diff --git a/go.mod b/go.mod
index 87d688b..cb04ea3 100644
--- a/go.mod
+++ b/go.mod
@@ -5,6 +5,7 @@ go 1.17
require (
github.com/ProtonMail/go-crypto v0.0.0-2021042814[132](https://github.com/hashicorp/terraform-provider-aws/runs/5223985090?check_suite_focus=true#step:5:132)3-04723f9f07d7
github.com/aws/aws-sdk-go v1.42.53
+	github.com/aws/aws-sdk-go-v2 …
```
=> Fix `go.mod`

.changelog/23235.txt, internal/service/imagebuilder/image_recipe.go
Updated plan time validations of `aws_imagebuilder_image_recipe` as per [CreateImageRecipe](https://docs.aws.amazon.com/imagebuilder/latest/APIReference/API_CreateImageRecipe.html).
Closes #16757.
```
$ make testacc PKG_NAME=internal/service/imagebuilder TESTARGS="-run=TestAccImageBuilderImageRecipe_"     
==> Checking that …
```
=> r/aws_imagebuilder_image_recipe - update plan time validations

.changelog/23030.txt, internal/service/ecs/capacity_provider.go, internal/service/ecs/cluster.go, internal/service/ecs/find.go, internal/service/ecs/service.go, internal/service/ecs/task_definition.go, internal/service/ecs/task_set.go
Relates #23030
Relates #22532
```console
% go test ./...
?   	github.com/hashicorp/terraform-provider-aws	[no test files]
ok  	github.com/hashicorp/terraform-provider-aws/internal/acctest	6.798s
?   	github.com/hashicorp/terraform-provider-aws/internal/attrmap	[no test files]
ok …
```
=> ecs/ISO: Backport tagging fixes

.changelog/22978.txt, internal/service/waf/helpers.go
Closes #23186.
Relates #22978.
Relates https://github.com/hashicorp/terraform-provider-aws/issues/22500.
Relates https://github.com/hashicorp/terraform-provider-aws/issues/22378.
```console
% make testacc TESTS=TestAccWAFRuleGroup_ PKG=waf …
```
=> Backport of #22978 to `release/3.x`

.changelog/23232.txt, internal/service/s3/bucket_lifecycle_configuration_test.go, internal/service/s3/flex.go, website/docs/guides/version-4-upgrade.html.md, website/docs/r/s3_bucket_lifecycle_configuration.html.markdown
Closes https://github.com/hashicorp/terraform-provider-aws/issues/23228
* Perhaps we don't need the special handling if the tests still pass? @YakDriver
```
$ make testacc TESTARGS='-run=TestAccS3BucketLifecycleConfiguration' PKG=s3 ACCTEST_PARALLELISM=5
--- PASS: TestAccS3BucketLifecycleConfiguration_basic (197.31s)
--- PASS: …
```
=> r/s3_bucket_lifecycle_configuration: update value set in state for an empty `filter` argument

.changelog/23252.txt, internal/service/s3/bucket_lifecycle_configuration_test.go, internal/service/s3/flex.go, website/docs/r/s3_bucket_lifecycle_configuration.html.markdown
Closes https://github.com/hashicorp/terraform-provider-aws/issues/23239
```
--- PASS: TestAccS3BucketLifecycleConfiguration_Filter_Tag (193.92s)
--- PASS: TestAccS3BucketLifecycleConfiguration_TransitionZeroDays_intelligentTiering (197.49s)
--- PASS: TestAccS3BucketLifecycleConfiguration_TransitionStorageClassOnly_intelligentTi …
```
=> r/s3_bucket_lifecycle_configuration: correctly configure `filter` `tag` and add `and` block documentation

.changelog/23282.txt, go.mod, go.sum
Updates `aws-sdk-go-base` to v2.0.0-beta.8 and `awsv1shim` to v2.0.0-beta.9
Closes #23207
Closes #23224
Closes #23116
Closes #23176
N/A
=> Updates `aws-sdk-go-base`

.changelog/23278.txt, internal/service/s3/bucket.go, internal/service/s3/errors.go
Third party S3 might reply `NotImplemented` error when creating a
bucket. This error prevent the successful apply of the plan.
Example when checking policy:
```
╷
│ Error: error getting S3 bucket ([redacted]) policy: NotImplemented: The requested resource is not implemented
│       status code: 501, request id: [redacted], host id: [redacted]
│
│   with aws_s3_bucket.lts,
│   on main.tf line 22, in resource "aws_s3_bucket" "lts":
│   22: resource "aws_s3_bucket" "lts" {
│
╵
```
Example when checking for payment:
```
╷
│ Error: error getting S3 Bucket request payment: NotImplemented: The requested resource is not implemented
│       status code: 501, request id: txc25b2f0fe509409081b8b-00620fcb0c, host id: txc25b2f0fe509409081b8b-00620fcb0c
│
│   with aws_s3_bucket.lts,
│   on main.tf line …
```
=> Improve support for third party S3

.changelog/23283.txt, internal/provider/provider.go, internal/service/iam/find.go, internal/service/iam/instance_profile.go, internal/service/iam/openid_connect_provider.go, internal/service/iam/openid_connect_provider_test.go, internal/service/iam/policy.go, internal/service/iam/role.go, internal/service/iam/role_data_source.go, internal/service/iam/saml_provider.go, internal/service/iam/saml_provider_test.go, internal/service/iam/server_certificate.go, internal/service/iam/service_linked_role.go, internal/service/iam/service_specific_credential_test.go, internal/service/iam/signing_certificate_test.go, internal/service/iam/sweep.go, internal/service/iam/tags.go, internal/service/iam/user.go, internal/service/iam/user_data_source.go, internal/service/iam/virtual_mfa_device.go, internal/service/iam/virtual_mfa_device_test.go
Relates #22532 
Closes #23286
```console
% make testacc TESTS=TestAccIAMInstanceProfile_ PKG=iam
TF_ACC=1 go test ./internal/service/iam/... -v -count 1 -parallel 20 -run='TestAccIAMInstanceProfile_'  -timeout 180m
--- PASS: TestAccIAMInstanceProfile_Disappears_role …
```
=> iam: Improve ISO tag handling

.changelog/23254.txt, internal/service/elasticache/replication_group.go, website/docs/r/elasticache_replication_group.html.markdown
Closes https://github.com/hashicorp/terraform-provider-aws/issues/23220
```
```
=> r/elasticache_replication_group: prevent empty strings in resource description

.changelog/23293.txt, internal/service/imagebuilder/image_recipe.go, internal/service/imagebuilder/image_recipe_test.go, website/docs/r/imagebuilder_image_recipe.html.markdown
Closes #22159
```
$ make testacc TESTS=TestAccImageBuilderImageRecipe PKG=imagebuilder
TF_ACC=1 go test ./internal/service/imagebuilder/... -v -count 1 -parallel 20 -run='TestAccImageBuilderImageRecipe'  -timeout 180m
=== RUN …
```
=> imagebuilder/image_recipe: Add `systems_manager_agent.uninstall_after_build` argument

.changelog/23304.txt, internal/service/ec2/fleet.go, internal/service/ec2/fleet_test.go, website/docs/r/ec2_fleet.html.markdown
Closes #23302
```
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 20 -run='TestAccEC2Fleet'  -timeout 180m
=== RUN   TestAccEC2Fleet_basic
=== PAUSE TestAccEC2Fleet_basic
=== RUN   TestAccEC2Fleet_disappears
=== PAUSE TestAccEC2Fleet_disappears
=== …
```
=> Add 'Context' as an optional parameter for EC2 'CreateFleet'

.changelog/23322.txt, internal/service/imagebuilder/image_pipeline.go, internal/service/imagebuilder/image_pipeline_test.go, website/docs/r/imagebuilder_image_pipeline.html.markdown
Closes #23238
```
$ make testacc TESTS=TestAccImageBuilderImagePipeline PKG=imagebuilder
TF_ACC=1 go test ./internal/service/imagebuilder/... -v -count 1 -parallel 20 -run='TestAccImageBuilderImagePipeline'  -timeout 180m
=== RUN …
```
=> imagebuilder/image_pipeline: Add `schedule.timezone` parameter

.changelog/23328.txt, internal/service/dms/consts.go, internal/service/dms/find.go, internal/service/dms/replication_task.go, internal/service/dms/replication_task_test.go, internal/service/dms/status.go, internal/service/dms/wait.go
Closes https://github.com/hashicorp/terraform-provider-aws/issues/23319
```
--- FAIL: TestAccDMSReplicationTask_basic (454.72s) <-- same error in main branch
--- PASS: TestAccDMSReplicationTask_cdcStartPosition (448.43s)
```
Test error related to https://github.com/hashicorp/terraform-provider-aws/issues/19883
```
Terraform …
```
=> r/dms_replication_task: set `cdc_start_position` to computed

.changelog/23325.txt, internal/service/s3/bucket_lifecycle_configuration.go, internal/service/s3/flex.go, website/docs/r/s3_bucket_lifecycle_configuration.html.markdown
Closes https://github.com/hashicorp/terraform-provider-aws/issues/23299
Relates https://github.com/hashicorp/terraform-provider-aws/issues/23228
* The `prefix` argument is deprecated as suggested in the documentation; AWS has already announced its deprecation.
* The resource documentation examples are enhanced to encourage `filter` use and provide more …
=> r/s3_bucket_lifecycle_configuration: improve documentation and officially deprecate `prefix`

.changelog/17039.txt, internal/provider/provider.go, internal/service/ec2/vpc_endpoint_policy.go, internal/service/ec2/vpc_endpoint_policy_test.go, website/docs/r/vpc_endpoint_policy.html.markdown
```
$ make testacc TESTARGS='-run=TestAccAWSVpcEndpointPolicy_'
--- PASS: TestAccEC2VPCEndpointPolicy_disappears_endpoint (80.19s)
--- PASS: TestAccEC2VPCEndpointPolicy_disappears (97.00s)
--- PASS: …
```
=> r/vpc_endpoint_policy - new resource

.changelog/16386.txt, internal/provider/provider.go, internal/service/ec2/internet_gateway.go, internal/service/ec2/internet_gateway_attachment.go, internal/service/ec2/internet_gateway_attachment_test.go, website/docs/r/internet_gateway_attachment.html.markdown
Closes #16151
Closes #13742
Closes #9101
```
$ make testacc TESTS=TestAccEC2InternetGatewayAttachment_ PKG=ec2
--- PASS: TestAccEC2InternetGatewayAttachment_disappears (34.04s)
--- PASS: …
```
=> r/internet_gateway_attachment - new resource

.changelog/23341.txt, internal/service/ecs/cluster.go, internal/service/ecs/cluster_capacity_providers.go, internal/service/ecs/find.go
Relates #22532
Closes #23342
```console
% make testacc TESTS=TestAccECSCluster_ PKG=ecs TESTARGS=-short
TF_ACC=1 go test ./internal/service/ecs/... -v -count 1 -parallel 20 -run='TestAccECSCluster_' -short -timeout 180m
--- PASS: …
```
=> ecs/iso: Fix describe with configuration

.changelog/23270.txt, internal/service/servicecatalog/provisioned_product.go, internal/service/servicecatalog/provisioned_product_test.go, website/docs/r/servicecatalog_provisioned_product.html.markdown
Closes Asana #64503
```
--- PASS: TestAccServiceCatalogProvisionedProduct_basic (145.15s)
--- PASS: TestAccServiceCatalogProvisionedProduct_disappears (136.82s)
--- PASS: TestAccServiceCatalogProvisionedProduct_tags (244.40s)
```
=> r/servicecatalog_provisioned_product: Add `outputs` attribute

internal/service/backup/framework_data_source_test.go, internal/service/backup/framework_test.go
Closes #23382.
```console
% make testacc TESTS=TestAccBackupFramework_serial PKG=backup
TF_ACC=1 go test ./internal/service/backup/... -v -count 1 -parallel 20 -run='TestAccBackupFramework_serial'  -timeout 180m
=== RUN   TestAccBackupFramework_serial
=== RUN …
```
=> r/aws_backup_framework: Serialize acceptance tests

.changelog/23384.txt, internal/conns/conns.go, internal/provider/provider.go, website/docs/index.html.markdown
The region can now be sourced from:
* Provider config
* Environment variables
* Shared config or credentials files
* IMDS
It can no longer be a required parameter
Closes #23321
=> provider: Make `region` optional

website/docs/r/kms_grant.html.markdown
The example of `terraform import` includes unneeded space between Key ID and Grant ID.
=> [docs/kms_grant] remove unneeded space

.changelog/23398.txt, internal/service/s3/bucket.go
Relates to #23278
Signed-off-by: Wilfried Roset <wilfriedroset@users.noreply.github.com>
```
...
```
=> Add `NotImplemented` error handling in GetBucketLogging

.changelog/23368.txt, internal/service/s3/bucket_object_lock_configuration.go, website/docs/r/s3_bucket.html.markdown, website/docs/r/s3_bucket_object_lock_configuration.html.markdown
Closes https://github.com/hashicorp/terraform-provider-aws/issues/23363
TODO:
^^ not actually necessary after apply/refresh:
```
$ cat main.tf
resource "aws_s3_bucket" "example" {
bucket = "my-example-log-bucket-4444"
}
resource "aws_s3_bucket_versioning" "example" {
bucket = aws_s3_bucket.example.id
versioning_configuration {
status = "Enabled"
}
}
resource …
```
=> r/s3_bucket_object_lock_configuration: clarify usage in docs and mark token as `sensitive`

website/docs/r/ses_domain_mail_from.html.markdown
Currently, the docs for `ses_domain_mail_from` do not contain any references to the fact that an SES Verified Email address can be used in place of the `domain` property to allow a custom MAIL FROM domain as well. This is the root cause of some customer pain, identified via this Issue (https://github.com/hashicorp/terraform-provider-aws/issues/14378) and a support ticket (#67513 for internal reference)
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request …
=> ses: domain_mail_from: Update docs for email identity usecase

internal/conns/conns.go, internal/service/meta/region_data_source.go
Sets `AWSClient.Region` based on resolved AWS configuration
Relates #23384
```
$ make testacc PKG=meta TESTS=TestAccMetaRegionDataSource_basic
--- PASS: TestAccMetaRegionDataSource_basic (27.41s)
```
=> provider: Sets provider client region from resolved AWS configuration

go.mod, go.sum
Updates `aws-sdk-go-base` to v2.0.0-beta.11 and awsv1shim to v2.0.0-beta.12
=> Updates `aws-sdk-go-base` to v2.0.0-beta.11 and awsv1shim to v2.0.0-beta.12

.changelog/23366.txt, .semgrep.yml, internal/service/eks/cluster.go, internal/service/eks/wait.go
EKS delete cluster calls can fail due to an in-progress cluster upgrade operation (customer initiated or automated scaling by EKS) or service outage.
This PR helps mitigate delete cluster failures by adding a retry with backoff.
~The suite is currently running and I will update when it finishes.~ The failure seems like a flake?
<details><summary>Output from acceptance testing:</summary>
```
$  make testacc TESTS=TestAccEKSCluster PKG=eks AWS_PROFILE=burner ACCTEST_PARALLELISM=5 ACCTEST_TIMEOUT=5000m
==> Checking that code complies with gofmt requirements...                                                                                                                                     
TF_ACC=1 go test ./internal/service/eks/... -v -count 1 -parallel 5 -run='TestAccEKSCluster'  -timeout …
```
=> Add retry to eks cluster delete

.github/labeler-issue-triage.yml, .github/labeler-pr-triage.yml, infrastructure/repository/labels-service.tf, internal/conns/conns.go, website/allowed-subcategories.txt, website/docs/guides/custom-service-endpoints.html.md
This PR adds a client for CloudWatch RUM as the first step towards implementing a resource for App Monitors. I figure it's in a similar situation as that of CloudWatch Logs so it doesn't need its own entry in `website/allowed-subcategories.txt` either, but let me know if I'm wrong.
Relates #22201
Output from make test:
```
make test …
```
=> Added service client for CloudWatch RUM

.changelog/22942.txt, internal/service/cloudwatch/metric_alarm.go, internal/service/cloudwatch/metric_alarm_test.go
Adds complexity to the extended-statistic reg-ex to support the current statistics defined [in the AWS docs](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/Statistics-definitions.html) during validation. Also parametrises tests for example statistics.
Closes #22078
Relates #13622
```
$ make test …
```
=> Support modern extended statistics for CloudWatch metric alarm

.changelog/23452.txt, internal/service/eks/node_group_data_source.go, internal/service/eks/node_group_data_source_test.go, website/docs/d/eks_node_group.html.markdown
Adds the `taints` attribute to the `aws_eks_node_group` data source. It was added to the resource in https://github.com/hashicorp/terraform-provider-aws/pull/19482 but is missing from the data source.
```
$ make testacc TESTS=TestAccEKSNodeGroupDataSource PKG=eks
=== RUN   TestAccEKSNodeGroupDataSource_basic
--- PASS: …
```
=> data-source/aws_eks_node_group: Add `taints` attribute

.changelog/23330.txt, internal/provider/provider.go, internal/service/ec2/errors.go, internal/service/ec2/find.go, internal/service/ec2/network_insights_path.go, internal/service/ec2/network_insights_path_test.go, internal/service/ec2/sweep.go, website/docs/r/ec2_network_insights_path.html.markdown
Adds a new resource `aws_ec2_network_insights_path` to partially address #16715.
Adds tests, sweeper and find functions for the new resource type.
Adds documentation for the new resource type.
Example config: 
```terraform
resource "aws_ec2_network_insights_path" "test" {
source           = aws_network_interface.test.id
destination      = aws_internet_gateway.test.id
protocol         = "tcp"
destination_port = 443
}
```
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise …
=> r/aws_ec2_network_insights_path - new resource

.changelog/23444.txt, internal/service/dms/endpoint.go, internal/service/dms/endpoint_test.go
Closes #23143
Relates #19040
```console
% make testacc TESTS=TestAccDMSEndpoint PKG=dms 
TF_ACC=1 go test ./internal/service/dms/... -v -count 1 -parallel 20 -run='TestAccDMSEndpoint'  -timeout 180m
--- PASS: TestAccDMSEndpoint_MongoDB_basic (35.44s)
--- PASS: …
```
=> dms/endpoint: Fix bug where KMS key ignored

.changelog/23427.txt, internal/service/ec2/route.go, internal/service/ec2/route_test.go
Closes #23413.
```console
% make testacc TESTS=TestAccEC2Route_ipv6ToNatGateway PKG=ec2
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 20 -run='TestAccEC2Route_ipv6ToNatGateway'  -timeout 180m
=== RUN   TestAccEC2Route_ipv6ToNatGateway
=== PAUSE …
```
=> r/aws_route: NAT Gateway targets support IPv6 destinations

website/docs/r/ses_domain_mail_from.html.markdown
A link in the `aws_ses_domain_mail_from` documentation was pointing to a moved URL on the AWS documentation site
=> documentation: Updates SES documentation link

.github/workflows/maintainer-edit.yml
- n/a - adding an action.
This PR proposes a new GitHub Action for checking whether or not a PR submitter has enabled the setting that [allows changes to a PR branch created from a fork](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created …
=> Add maintainer editability check

website/docs/d/ec2_transit_gateway_vpc_attachments.html.markdown
Relates #23425
The documentation previously linked to the AWS document for `describe-transit-gateway-attachments`. This PR updates the link to the API documentation for `DescribeTransitGatewayVpcAttachments` (the call that's used in the underlying resource), to more accurately reflect the list of filter names.
=> Correct AWS documentation link in aws_ec2_transit_gateway_vpc_attachments

website/docs/d/route_tables.html.markdown
Changed in 4.x from a set to a list.
Closes #23472 
```
...
```
=> Fix to match what the output gives in v4.x

.changelog/22727.txt, internal/service/networkfirewall/rule_group.go
This allows the use of ip_sets for source and destination
Closes #22727
=> fix #22727: allow any character in networkfirewall/stateful_rule/header source/destination per the api docs

.changelog/23275.txt, CHANGELOG.md, internal/service/glue/job.go, internal/service/glue/job_test.go, website/docs/r/glue_job.html.markdown
Closes #16797
```
$make testacc TESTS=TestAccGlueJob PKG=glue
TF_ACC=1 go test ./internal/service/glue/... -v -count 1 -parallel 20 -run='TestAccGlueJob'  -timeout 180m
=== RUN   TestAccGlueJob_basic
=== PAUSE TestAccGlueJob_basic
=== RUN …
```
=> Glue streaming job update

.changelog/22451.txt, internal/service/autoscaling/policy.go, internal/service/autoscaling/policy_test.go, website/docs/r/autoscaling_policy.html.markdown
Proposed change to support [custom metrics](https://aws.amazon.com/about-aws/whats-new/2021/11/amazon-ec2-auto-scaling-predictive-scaling-custom-metrics/) in predictive scaling policy.
I am new to Terraform/Golang so I basically tried to following existing pattern implementing the change and adding tests. Please let me know if it complies with your requirement.
Solved by using `TypeSet` rather than `TypeList` for dimensions
~~One question is, I used one single [dimension](https://docs.aws.amazon.com/autoscaling/ec2/APIReference/API_MetricDimension.html) in my test,~~
```
dimensions {
name = "foo"
value = "bar"
}
```
if I tried to use two dimensions in the test,
```
dimensions {
name = "foo"
value = "bar"
}
dimensions {
name = "bar"
value = "foo"
}
```
it seems the test would fail because …
=> Support customized metric specification in autoscaling predictive scaling policy

.changelog/23485.txt, internal/service/route53resolver/firewall_domain_list.go
Removing limit for number of domains defined in aws_route53_resolver_firewall_domain_list per [API Docs](https://docs.aws.amazon.com/Route53/latest/APIReference/API_route53resolver_UpdateFirewallDomains.html#API_route53resolver_UpdateFirewallDomains_RequestSyntax)
Closes #23485
=> fix #23485: Remove limit for number of domains in aws_route53_resolver_firewall_domain_list

.github/workflows/release.yml
Requires https://github.com/hashicorp/ghaction-terraform-provider-release/pull/3
Description:
* The role duration defaults to `3600` which will be exceeded during a provider release which looks to take 1h40min by the time goreleaser starts to publish the artifacts to S3
```
N/A
```
=> github/workflows/release: set aws role duration to the release duration timeout of 2h

.goreleaser.yml, scripts/changelog-links.sh
Description
* Revert goreleaser to previous form just in case
```
...
```
=> revert gha release

examples/ecs-alb/main.tf
Update the examples to use the "new" `templatefile()` function.
The template provider has been deprecated since 0.12 and is not available on all platforms, such as arm64.
Relates #22739 
Output from acceptance testing: N/A, this is only a documentation update.
=> examples/ecs-alb: Replace template_file data sources

.changelog/23516.txt, internal/service/account/alternate_contact.go, internal/service/account/find.go, internal/service/account/status.go, internal/service/account/wait.go, website/docs/r/account_alternate_contact.html.markdown
Relates #22186
```console
% make testacc TESTS=TestAccAccountAlternateContact_ PKG=account 
TF_ACC=1 go test ./internal/service/account/... -v -count 1 -parallel 20 -run='TestAccAccountAlternateContact_'  -timeout 180m
--- PASS: TestAccAccountAlternateContact_basic …
```
=> account/alternate_contact: Fix eventual consistency

website/docs/r/internet_gateway.html.markdown
Relates #16386
Updating the docs for `aws_internet_gateway` to note the `vpc_id` is optional now since `aws_internet_gateway_attachment` can be used.
=> docs/internet_gateway: update vpc_id to optional

website/docs/r/route53_health_check.html.markdown
Closes #23536
As correctly pointed out in the linked issue, the `failure_threshold` argument of `aws_route53_health_check` is documented as required when it [is indeed optional](https://github.com/hashicorp/terraform-provider-aws/blob/1ddf4c774b7124b83cd032b777d5a0f291af54c1/internal/service/route53/health_check.go#L5 …
=> Correctly identify `failure_threshold` as optional for `aws_route53_health_check`

website/docs/r/datapipeline_pipeline_definition.html.markdown
Closes #23550
As mentioned in the linked issue, [the correct argument](https://github.com/hashicorp/terraform-provider-aws/blob/1ddf4c774b7124b83cd032b777d5a0f291af54c1/internal/service/datapipeline/pipeline_definition.go#L36) is `attribute`, while the documentation currently has `attributes`.
=> Correct documentation on argument name on aws_datapipeline_pipeline_difinition

.changelog/23556.txt, internal/service/s3/bucket.go, internal/service/s3/bucket_object_data_source_test.go, internal/service/s3/bucket_object_lock_configuration_test.go, internal/service/s3/bucket_object_test.go, internal/service/s3/bucket_test.go, internal/service/s3/object_data_source_test.go, internal/service/s3/object_test.go, website/docs/guides/version-4-upgrade.html.md, website/docs/r/s3_bucket.html.markdown, website/docs/r/s3_bucket_object.html.markdown, website/docs/r/s3_bucket_object_lock_configuration.html.markdown, website/docs/r/s3_object.html.markdown
Adds top-level `object_lock_enabled` parameter to `aws_s3_bucket` and deprecates `object_lock_configuration.object_lock_enabled`.
Closes #23549
```
$ make testacc PKG=s3 TESTS='TestAccS3Bucket_|TestAccS3BucketObject_|TestAccS3BucketObjectDataSource_|TestAccS3Object_|TestAccS3ObjectDataSource_'
--- PASS: TestAccS3Bucket_Basic_shouldFailNotFound (170.67s)
--- PASS: TestAccS3BucketObjectDataSource_basic (188.71s)
--- PASS: TestAccS3Object_objectBucketKeyEnabled (190.64s)
--- PASS: TestAccS3Object_defaultBucketSSE (196.46s)
--- PASS: TestAccS3Object_bucketBucketKeyEnabled (198.22s)
--- SKIP: TestAccS3Object_nonVersioned (0.00s)
--- PASS: TestAccS3Object_sse (244.58s)
--- PASS: TestAccS3BucketObject_sse (254.45s)
--- PASS: TestAccS3Object_kms (255.85s)
--- PASS: …
```
=> resource/aws_s3_bucket: Add top-level `object_lock_enabled` parameter

.changelog/23574.txt, internal/service/synthetics/canary.go, internal/service/synthetics/canary_test.go, website/docs/r/synthetics_canary.html.markdown
Closes #17948
```
$ make testacc TESTS=TestAccSyntheticsCanary_run PKG=synthetics
=== RUN   TestAccSyntheticsCanary_runtimeVersion
=== PAUSE TestAccSyntheticsCanary_runtimeVersion
=== RUN   TestAccSyntheticsCanary_run
=== PAUSE TestAccSyntheticsCanary_run
=== RUN   TestAccSyntheticsCanary_runTracing
=== PAUSE …
```
=> resource/aws_synthetics_canrany: Add environment variables to run config

website/docs/r/subnet.html.markdown
The documentation for the `private_dns_hostname_type_on_launch` is incorrect. 
Resource-based naming can be used for ipv4 only, dual stack and ipv6-only subnets, while the legacy IP-based naming cannot be used with ipv6-only subnets.
Docs: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-naming.html#instance-naming-types
=> Fix incorrect documentation for aws_subnet

.changelog/23580.txt, internal/service/imagebuilder/image_recipe.go, internal/service/imagebuilder/image_recipe_test.go
Closes #23568.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/23293.
Relates https://github.com/hashicorp/terraform-provider-aws/issues/22159.
The new regression test correctly catches the bug I introduced:
```
$ make testacc TESTS=TestAccImageBuilderImageRecipe_WindowsBaseImage PKG=imagebuilder
==> Checking …
```
=> r/imagebuilder_image_recipe: Fix regression with Windows base images

.changelog/23593.txt, internal/service/kms/wait.go
Our team has noticed that Amazon sometimes takes longer than the current timeout value to update tags or descriptions on a kms key resource.
A re run of terraform apply always shows the value was properly updated.
Increasing the time out value on these two waiters to allow the provider a little more time before timing out.
Closes #23592
Closes #23136
Output …
=> aws_kms_key: Increased Timeout on Tag and Description Propagation waiter

internal/service/s3/bucket_replication_configuration_test.go
Closes https://github.com/hashicorp/terraform-provider-aws/issues/23578
* Only one intermittent failure in TC for this resource but all of the dependencies are updated just in case
```
--- SKIP: TestAccS3BucketReplicationConfiguration_existingObjectReplication (0.00s)
--- PASS: …
```
=> tests/s3_bucket_replication_configuration: add destination bucket versioning dependencies

.changelog/23579.txt, internal/service/s3/bucket_replication_configuration.go, internal/service/s3/flex.go, internal/service/s3/flex_test.go
Closes https://github.com/hashicorp/terraform-provider-aws/issues/23571
* This fix is similar to #23252 such that the expand/flatten methods were not correctly reading the tag key. 
* Method names in s3/flex.go are also updated to reflect they are part of the `ReplicationRule` as functionality is very similar to LifecycleRule
* An acceptance already exists …
=> r/s3_bucket_replication_configuration: correctly expand and flatten `rule.filter.tag`

.changelog/13366.txt, internal/service/s3/bucket.go
Relates https://github.com/hashicorp/terraform-provider-aws/pull/23278
```release-note
```
```
...
```
=> handle `NotImplemented` error code for AWS Snowball for object lock

.goreleaser.yml
Relates https://github.com/hashicorp/hc-releases/pull/154
```
N/A
```
=> goreleaser: Comment out `publishers` `extra_files` to prevent runtime error

.changelog/23624.txt, internal/service/s3/bucket_replication_configuration.go, website/docs/r/s3_bucket_replication_configuration.html.markdown
This allows one to enable replication on an object-lock enabled bucket, OR enabling object lock on an existing bucket. See https://docs.aws.amazon.com/AmazonS3/latest/userguide/object-lock-managing.html#object-lock-managing-replication for details.
Closes #14061.
```
% make testacc TESTS='TestAccS3BucketReplication.*' PKG=s3 …
```
=> r/s3_bucket_replication_configuration: Add token parameter for x-amz-bucket-object-lock-token

infrastructure/repository/maintainer-list.tf
Output from acceptance testing: n/a, this PR is a meta-PR for the repo
Currently, there's several places where we employ a list to conditionally execute certain portions of certain GitHub Actions:
- [Issue Comment Created Triage](https://github.com/hashicorp/terraform-provider-aws/blob/ccc60a8423bcbd96ba92a988851c0b75b67185c6/.github/workflows/issue-comment-c …
=> Create MAINTAINER_LIST secret for GitHub Actions

.github/workflows/changelog.yml, .github/workflows/dependencies.yml, .github/workflows/issue-comment-created.yml, .github/workflows/issues.yml, .github/workflows/maintainer-edit.yml, .github/workflows/project.yml, .github/workflows/pull_requests.yml
Relates #23633
Output from acceptance testing: n/a, meta PR for GitHub Actions
This PR comes after the linked PR is merged and the secret has been created by approving the resulting Terraform run. Once that has completed, this PR can be merged to switch the GitHub Actions over to using the `MAINTAINER_LIST` secret rather than a statically defined list.
=> Switch GitHub Actions to use MAINTAINER_LIST secret

.github/workflows/changelog.yml, .github/workflows/dependencies.yml, .github/workflows/issue-comment-created.yml, .github/workflows/maintainer-edit.yml, .github/workflows/pull_requests.yml
Relates  #23636
Output from acceptance testing: n/a, relates to GitHub Actions
The linked Pull Request updated several GitHub Actions to use the new `MAINTAINER_LIST` secret to pull a list of users for an exclusion list. Unfortunately, this broke many of the workflows, so this PR aims to fix it.
There seems to be some inconsistencies, but the best I could …
=> Fix broken GitHub Actions after switch to MAINTAINER_LIST

.github/workflows/issues.yml, .github/workflows/project.yml
Relates #23640
Relates #23636
```
n/a
```
These are an additional GitHub Actions that were impacted by the malformed syntax of #23636 that were not caught in the fixes included in #23640. Applying same fixes as before.
=> Additional fixes for GitHub Actions after MAINTAINER_LIST switch

internal/service/redshift/wait.go
Relates #20812.
```console
% make lint
==> Checking source code with golangci-lint...
internal/service/redshift/wait.go:41:79: waitClusterRelocationStatusResolved - result 0 (*github.com/aws/aws-sdk-go/service/redshift.Cluster) is never used (unparam)
func waitClusterRelocationStatusResolved(conn *redshift.Redshift, id string) (*redshift.Cluster, error) {
^ …
```
=> Fix `golangci-lint` unparam error

.changelog/23600.txt, internal/service/ecs/service.go, internal/service/ecs/service_test.go
---
This pull request aims to take advantage of the recent updates to the ECS api to allow for updating `propagate_tags` `ecs_managed_tags` `load_balancer` and `service_registries` without requiring a new deployment of the `aws_ecs_service` resource
The associated updates to the API can be found [here](https://aws.amazon.com/about-aws/whats-new/2022/03/amazon …
=> r/aws_ecs_service: update `propagate_tags` `enable_ecs_managed_tags` `load_balancer` and `service_registries` without destroy & recreate

website/docs/r/api_gateway_vpc_link.html.markdown
The previous example import command for the `aws_api_gateway_vpc_link` did not include an id (see below). This documentation update provides an `id` in the import statement to make the behavior more explicit to unfamiliar users.
N/A
=> docs: use valid example id for import statement

.github/labeler-issue-triage.yml, .github/labeler-pr-triage.yml, infrastructure/repository/labels-service.tf, internal/conns/conns.go, website/allowed-subcategories.txt, website/docs/guides/custom-service-endpoints.html.md
Relates https://github.com/hashicorp/terraform-provider-aws/issues/11221
```
f-keyspaces-service-support $ make test
go test ./...  -timeout=5m
go: downloading github.com/aws/aws-sdk-go v1.43.17
go: downloading github.com/aws/aws-sdk-go-v2/service/route53domains …
```
=> Add provider infrastructure for Amazon Keyspaces

.changelog/23517.txt, internal/service/amplify/amplify_test.go, internal/service/amplify/app.go, internal/service/amplify/app_test.go, internal/service/amplify/backend_environment_test.go, internal/service/amplify/branch_test.go, internal/service/amplify/domain_association_test.go, internal/service/amplify/webhook_test.go
Fixes an issue where an `aws_amplify_app` will be destroyed and recreated when modifying the `repository` attribute instead of being updated in place.
Closes #23499
```
❯ TF_ACC=1 go test  ./internal/service/amplify -run=TestAccAmplify_serial  -v -count 1 -parallel 1   -timeout 180m
=== RUN   TestAccAmplify_serial
=== RUN …
```
=> resource/aws_amplify_app: update `repository` attribute in place

.changelog/23435.txt, internal/provider/provider.go, internal/service/s3/bucket.go, internal/service/s3/bucket_website_configuration.go, internal/service/s3/bucket_website_configuration_test.go, internal/service/s3/errors.go, internal/service/s3/id.go, internal/service/s3/id_test.go, website/docs/r/s3_bucket.html.markdown, website/docs/r/s3_bucket_website_configuration.html.markdown
Relates https://github.com/hashicorp/terraform-provider-aws/issues/23106
```
--- PASS: TestAccS3BucketWebsiteConfiguration_disappears (27.63s)
--- PASS: TestAccS3BucketWebsiteConfiguration_Redirect (31.78s)
--- PASS: TestAccS3BucketWebsiteConfiguration_basic (32.32s)
--- PASS: …
```
=> r/s3_bucket_website_configuration: backport resource

.changelog/7547.txt, internal/service/s3/bucket.go, internal/service/s3/bucket_test.go, website/docs/r/s3_bucket.html.markdown
Fixes #7546
This PR will allow adding/removing cors blocks dynamically based on a list of allowed methods and allowed origins. Currently, empty cors blocks cause a panic.  Changes proposed in this pull request are also mentioned in issue #7546.
```hcl
resource "aws_s3_bucket" "main" {
bucket = "${var.s3_bucket_name}"
acl    = "private"
cors_rule {
allowed_methods = "${var.s3_cors_allowed_methods}"
allowed_origins = "${var.s3_cors_allowed_origins}"
}
}
```
```
--- PASS: TestAccS3Bucket_Security_corsDelete (136.12s)
--- PASS: TestAccS3Bucket_Security_corsSingleMethodAndEmptyOrigin (167.95s)
--- PASS: TestAccS3Bucket_Security_corsEmptyOrigin (176.03s)
--- PASS: TestAccS3Bucket_Security_corsUpdate (283.98s)
```
=> Ignore Empty CORS Blocks for AWS S3 Bucket

.changelog/23086.txt, internal/service/rds/instance.go, website/docs/r/db_instance.html.markdown
=> Add `source_db_instance_automated_backup_arn` as point in time restore option for rds_instance

.changelog/23607.txt, docs/contributing/maintaining.md, internal/service/quicksight/user.go, internal/service/quicksight/user_test.go, website/docs/r/quicksight_user.html.markdown
Signed-off-by: Trevor Wood <Trevor.G.Wood@gmail.com>
Closes #21166
```
make testacc TESTS=TestAccQuickSightUser_ PKG=quicksight
TF_ACC=1 go test ./internal/service/quicksight/... -v -count 1 -parallel 20 -run='TestAccQuickSightUser_'  -timeout 180m
=== RUN …
```
=> r/aws_quicksight_user: allow custom namespaces

.changelog/23152.txt, internal/service/autoscaling/launch_configuration.go, internal/service/autoscaling/launch_configuration_test.go, website/docs/r/launch_configuration.html.markdown
Adding a no_device option to ephemeral block devices in a launch configuration resource.  This addresses issue [5464](https://github.com/hashicorp/terraform-provider-aws/issues/5464).
Closes #5464
```
make testacc TESTS=TestAccAutoScalingLaunchConfiguration_basic PKG=autoscaling …
```
=> resource/aws_launch_configuration: add no_device option

.changelog/23678.txt, internal/service/s3/bucket_acl.go, internal/service/s3/bucket_acl_test.go
Closes https://github.com/hashicorp/terraform-provider-aws/issues/23676
```
--- PASS: TestAccS3BucketAcl_disappears (16.56s)
--- PASS: TestAccS3BucketAcl_basic (22.07s)
--- PASS: TestAccS3BucketAcl_ACLToGrant (39.02s)
--- PASS: TestAccS3BucketAcl_grantToACL (39.02s)
--- PASS: TestAccS3BucketAcl_updateGrant (42.81s)
--- PASS: …
```
=> r/s3_bucket_acl: support pre-2018 naming for buckets in `us-east-1`

.changelog/23679.txt, internal/service/s3/bucket_acl.go, internal/service/s3/bucket_acl_test.go
Relates https://github.com/hashicorp/terraform-provider-aws/issues/23676
```
--- PASS: TestAccS3BucketAcl_disappears (23.25s)
--- PASS: TestAccS3BucketAcl_basic (35.16s)
--- PASS: TestAccS3BucketAcl_migrate_aclNoChange (58.03s)
--- PASS: TestAccS3BucketAcl_migrate_grantsNoChange (58.25s)
--- PASS: TestAccS3BucketAcl_grantToACL …
```
=> r/s3_bucket_acl: backport support of pre-2018 naming for buckets in `us-east-1`

.changelog/23126.txt, internal/service/iot/certificate.go, internal/service/iot/certificate_test.go, website/docs/r/iot_certificate.html.markdown
This PR adds the ability to register an existing certificate (with or without a CA) in AWS IoT.
```
$ make testacc TESTS=TestAccIoTCertificate_Keys_existing_certificate PKG=iot
TF_ACC=1 go test ./internal/service/iot/... -v -count 1 -parallel 20 …
```
=> Ability to register existing IoT certificate

website/docs/r/route53_key_signing_key.html.markdown
Output from acceptance testing: n/a
The example policy in the docs uses a Principal of `AWS = "*"` and this is generally accepted as a bad practice. There's a special warning the the [AWS Docs](https://docs.aws.amazon.com/kms/latest/developerguide/key-policy-modifying-external-accounts.html) about this:
>  Do not set the Principal to an asterisk (*) in any …
=> fix "*" key policy in aws_route53_key_signing_key example

internal/service/ec2/transit_gateway_connect_peer_data_source.go
Relates #13251.
```
=== RUN   TestAccEC2TransitGatewayDataSource_serial/ConnectPeer/Filter
------- Stderr: -------
panic: Invalid address to set: []string{"arn"}
goroutine 5332 [running]:
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*ResourceData).Set(0xc006761e80, {0x8e110a9, 0x3}, {0x6deeac0, 0xc00137dcc0}) …
```
=> d/aws_ec2_transit_gateway_connect_peer: Add missing `arn` attribute

.changelog/23647.txt, internal/service/imagebuilder/image.go, internal/service/imagebuilder/image_data_source.go, internal/service/imagebuilder/image_data_source_test.go, internal/service/imagebuilder/image_test.go, website/docs/d/imagebuilder_image.html.markdown, website/docs/r/imagebuilder_image.html.markdown
Closes #23380.
```
$ make testacc TESTS="TestAccImageBuilderImage_containerRecipeARN" PKG=imagebuilder
TF_ACC=1 go test ./internal/service/imagebuilder/... -v -count 1 -parallel 20 -run='TestAccImageBuilderImage_containerRecipeARN'  -timeout 180m
=== RUN …
```
=> rd/aws_imagebuilder_image - add support for container_recipe_arn

website/docs/r/s3_bucket_object_lock_configuration.html.markdown
Relates https://github.com/hashicorp/terraform-provider-aws/issues/23420
```
N/A
```
=> docs/s3_bucket_object_lock_configuration: add missing details on choosing import syntax

.goreleaser.yml
Relates #23630 
Reference hashicorp/hc-releases#154
Likely depends on `v1.0.6` or an updated `v1` tag of `setup-hc-releases` action
```
$ goreleaser check
• loading config file       file=.goreleaser.yml
• checking config:
• config is valid
```
=> goreleaser: Use new `upload-name` flag in `hc-releases` publisher

.github/workflows/autoremove_labels.yml
```
n/a
```
Previously, the Action used to automatically remove labels would fail if a particular label was not applied to a closing issue/PR. That behavior has changed, so there no longer needs to be a `strategy.matrix`, which made the Action run as multiple steps. Also took the opportunity to rename the job to be a bit more …
=> Simplify `autoremove_labels` GitHub Action

website/docs/r/route53_record.html.markdown
Closes #22822
`set_identifier` is required when using a routing policy other than simple ([reference](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-route53-recordset.html#cfn-route53-recordset-setidentifier)). Previously, the documentation did not include …
=> Update route53 set_identifier to required when using multivalue_answer

website/docs/r/s3_bucket_policy.html.markdown
Closes #22772
This small PR aims to clarify the example of importing an `aws_s3_bucket_policy` by way of matching the resource name to the example above it. This isn't necessary a "best practice", as there doesn't seem to be consistency in how imports are documented, but based on the linked issue felt like a …
=> Update `aws_s3_bucket_policy` import example to match example configuration

.changelog/23716.txt, internal/service/s3/bucket.go, internal/service/s3/bucket_replication_configuration.go, internal/service/s3/bucket_replication_configuration_test.go, internal/service/s3/flex.go, internal/service/s3/flex_test.go, website/docs/r/s3_bucket.html.markdown, website/docs/r/s3_bucket_replication_configuration.html.markdown
Relates #23624, #23616, #23586, #23582, #23579
```
--- PASS: TestExpandReplicationRuleFilterTag (0.00s)
--- PASS: TestFlattenReplicationRuleFilterTag (0.00s)
$ make testacc TESTARGS='-run=TestAccS3BucketReplicationConfiguration_' PKG=s3 ACCTEST_PARALLELISM=5 …
```
=> r/s3_bucket_replication_configuration: backport recent changes in `main` and deprecate r/s3_bucket `replication_configuration`

.changelog/23723.txt, internal/service/s3/bucket_versioning.go, internal/service/s3/bucket_versioning_test.go, internal/service/s3/enum.go, internal/service/s3/status.go, internal/service/s3/wait.go, website/docs/guides/version-4-upgrade.html.md, website/docs/r/s3_bucket_versioning.html.markdown
Closes https://github.com/hashicorp/terraform-provider-aws/issues/23718
```
--- PASS: TestAccS3BucketVersioning_disappears (27.36s)
--- PASS: TestAccS3BucketVersioning_Status_disabled (28.38s)
--- PASS: TestAccS3BucketVersioning_basic (31.13s)
--- PASS: TestAccS3BucketVersioning_MFADelete (31.16s)
--- PASS: …
```
=> r/s3_bucket_versioning: support disabled versioning i.e. unversioned buckets

website/docs/r/wafv2_web_acl_logging_configuration.html.markdown
See:
- https://docs.aws.amazon.com/waf/latest/developerguide/logging-cw-logs.html#logging-cw-logs-naming
- https://docs.aws.amazon.com/waf/latest/developerguide/logging-s3.html#logging-s3-naming
- https://docs.aws.amazon.com/waf/latest/developerguide/logging-kinesis.html
=> r/wafv2_web_acl_logging_configuration docs: specify that any log destination needs the aws-waf-logs- prefix

.changelog/23719.txt, internal/service/appconfig/configuration_profile.go, internal/service/appconfig/configuration_profile_test.go, internal/service/appconfig/enum.go, website/docs/r/appconfig_configuration_profile.html.markdown, website/docs/r/appconfig_hosted_configuration_version.html.markdown
Feature Flags in App Config are now GA, https://aws.amazon.com/about-aws/whats-new/2022/03/aws-appconfig-feature-flags/
This Pull Request exposes the ability to set the Configuration Profile type to either Free Form, or Feature Flag, as per the AWS API docs, https://docs.aws.amazon.com/appconfig/2019-10-09/APIReference/API_CreateConfigurationProfile.html#appconfig-CreateConfigurationProfile-request-Type
I've marked the default value to be FreeForm. Whilst this isn't explicitly documented on AWS, this is the observed behaviour from creating an App Config Profile without setting this value. Using this default maintains backwards compatibility. The validation function uses the regex function documented by AWS
* Please vote on this pull request by adding a 👍 …
=> feat: Add App Config Feature Flag type

.github/workflows/release.yml
* Latest release shows the commit version without the tag b/c it's no longer available in the github event triggered
```
N/A
```
=> github/workflows/release: Use output var in commit message and add release date to changelog

infrastructure/repository/maintainer-list.tf
Relates #23633
Output from acceptance testing: n/a, meta PR
With the recent switch to using the `MAINTAINER_LIST` repository secret, dependabot is now being tagged with `needs-triage`. This PR aims to correct that.
=> Add dependabot to maintainer list

.changelog/23737.txt, internal/service/s3/bucket_replication_configuration.go, internal/service/s3/bucket_replication_configuration_test.go, website/docs/r/s3_bucket_replication_configuration.html.markdown
Relates https://github.com/hashicorp/terraform-provider-aws/pull/23703
Relates https://github.com/hashicorp/terraform-provider-aws/issues/23487
Relates https://github.com/hashicorp/terraform-provider-aws/issues/23690
```
$ make testacc TESTARGS='-run=TestAccS3BucketReplicationConfiguration_' PKG=s3 ACCTEST_PARALLELISM=5
==> …
```
=> r/s3_bucket_replication_configuration: backport  update rule to a TypeList and mark `rule.id` as Computed and `rule.prefix` as Deprecated

.changelog/23750.txt, internal/service/s3/bucket_lifecycle_configuration.go, internal/service/s3/bucket_lifecycle_configuration_test.go, internal/service/s3/flex.go, website/docs/r/s3_bucket_lifecycle_configuration.html.markdown
Relates https://github.com/hashicorp/terraform-provider-aws/pull/23746
Relates https://github.com/hashicorp/terraform-provider-aws/issues/23730
```
$ make testacc TESTARGS='-run=TestAccS3BucketLifecycleConfiguration_' PKG=s3 ACCTEST_PARALLELISM=5 …
```
=> r/s3_bucket_lifecycle_configuration: backport fix; support the default filtering used in v3.x of the s3 bucket resource

.changelog/23746.txt, internal/service/s3/bucket_lifecycle_configuration.go, internal/service/s3/bucket_lifecycle_configuration_test.go, internal/service/s3/flex.go, website/docs/guides/version-4-upgrade.html.md, website/docs/r/s3_bucket_lifecycle_configuration.html.markdown
Closes https://github.com/hashicorp/terraform-provider-aws/issues/23730
```
$ make testacc TESTARGS='-run=TestAccS3BucketLifecycleConfiguration_' PKG=s3 ACCTEST_PARALLELISM=5
--- PASS: TestAccS3BucketLifecycleConfiguration_basic (192.54s)
=== CONT  TestAccS3BucketLifecycleConfiguration_TransitionStorageClassOnly_intelligentTier …
```
=> r/s3_bucket_lifecycle_configuration: support the default filtering used in v3.x of the s3 bucket resource

.changelog/23741.txt, internal/provider/provider.go, internal/service/imagebuilder/image_pipelines_data_source.go, internal/service/imagebuilder/image_pipelines_data_source_test.go, website/docs/d/imagebuilder_image_pipelines.html.markdown
```
$ make testacc PKG=imagebuilder TESTS="TestAccImageBuilderImagePipelinesDataSource_filter"
TF_ACC=1 go test ./internal/service/imagebuilder/... -v -count 1 -parallel 20 -run='TestAccImageBuilderImagePipelinesDataSource_filter'  -timeout 180m
=== RUN …
```
=> d/aws_imagebuilder_image_pipelines - new data source

.changelog/23748.txt, internal/service/athena/workgroup.go, internal/service/athena/workgroup_test.go, website/docs/r/athena_workgroup.html.markdown
```
$ make testacc TESTS=TestAccAthenaWorkGroup_ PKG=athena
--- PASS: TestAccAthenaWorkGroup_disappears (28.99s)
--- PASS: TestAccAthenaWorkGroup_aclConfig (35.61s)
--- PASS: TestAccAthenaWorkGroup_basic (38.28s)
--- PASS: TestAccAthenaWorkGroup_ResultEncryption_sseS3 (38.35s)
--- PASS: …
```
=> r/athena_workgroup - add `acl_configuration` and `expected_bucket_owner` args

.changelog/23754.txt, internal/service/apigateway/stage.go, internal/service/apigateway/stage_test.go, website/docs/r/api_gateway_stage.html.markdown
Closes #2727
Superseds #10474
```
$ make testacc TESTS=TestAccAPIGatewayStage_ PKG=apigateway
--- PASS: TestAccAPIGatewayStage_disappears_restApi (73.75s)
--- PASS: TestAccAPIGatewayStage_Disappears_referencingDeployment (92.24s)
--- PASS: TestAccAPIGatewayStage_waf (118.97s)
--- PASS: TestAccAPIGatewayStage_tags (119.23s)
--- …
```
=> r/apigateway_stage - add `canary_settings` argument

.github/labeler-issue-triage.yml, .github/labeler-pr-triage.yml, infrastructure/repository/labels-service.tf, website/allowed-subcategories.txt
API reference: https://docs.aws.amazon.com/appintegrations/latest/APIReference/API_Operations.html
Resources and Data Sources will have separate PRs
```
$ make test
go test ./...  -timeout=5m
?       github.com/hashicorp/terraform-provider-aws     [no test files]
ok …
```
=> Add provider infrastructure for Amazon AppIntegrations

website/docs/r/key_pair.html.markdown
Clarified that when no `key_name` and no `key_name_prefix` is provided, Terraform creates a unique key with prefix `terraform-`.
Closes #22992
_Not run as this is only a documentation change._
=> Clarified key_name and key_name prefix attributes

.changelog/23756.txt, internal/service/ssm/maintenance_window_task.go, internal/service/ssm/maintenance_window_task_test.go, website/docs/r/ssm_maintenance_window_task.html.markdown
Closes #20090
Closes #19396
```
$ make testacc TESTS=TestAccSSMMaintenanceWindowTask_ PKG=ssm
--- PASS: TestAccSSMMaintenanceWindowTask_disappears (37.91s)
--- PASS: TestAccSSMMaintenanceWindowTask_noRole (38.52s)
--- PASS: TestAccSSMMaintenanceWindowTask_emptyNotification (38.69s)
--- PASS: …
```
=> r/ssm_maintenance_window_task - allow not setting `targets`

.changelog/23757.txt, internal/service/ssm/document_data_source.go, internal/service/ssm/document_data_source_test.go, website/docs/d/ssm_document.html.markdown
Closes #19674
```
$ make testacc TESTS=TestAccSSMDocumentDataSource_ PKG=ssm
--- PASS: TestAccSSMDocumentDataSource_awsManaged (23.03s)
--- PASS: TestAccSSMDocumentDataSource_basic (52.19s)
```
=> d/ssm_document - dont generate `arn` for aws managed docs

examples/eks-getting-started/outputs.tf
```
...
```
The latest version of [aws-iam-authenticator](https://github.com/kubernetes-sigs/aws-iam-authenticator) is using API version `v1beta1`, and this PR is to fix the output section for the EKS example. Here is the [change …
=> update the API version to v1beta1 for aws-iam-authenticator

.changelog/23765.txt, internal/provider/provider.go, internal/service/cognitoidp/find.go, internal/service/cognitoidp/user_in_group.go, internal/service/cognitoidp/user_in_group_test.go, website/docs/r/cognito_user_in_group.html.markdown
Closes #23400.
```
$ make testacc PKG=cognitoidp TESTS="TestAccCognitoUserInGroup_"
TF_ACC=1 go test ./internal/service/cognitoidp/... -v -count 1 -parallel 20 -run='TestAccCognitoUserInGroup_'  -timeout 180m
=== RUN   TestAccCognitoUserInGroup_basic
=== PAUSE …
```
=> r/aws_cognito_user_in_group - new resource

.changelog/23760.txt, internal/service/cloudwatchlogs/find.go, internal/service/cloudwatchlogs/subscription_filter.go, internal/service/cloudwatchlogs/subscription_filter_test.go
```
$ make testacc TESTS=TestAccCloudWatchLogsSubscriptionFilter_ PKG=cloudwatchlogs
--- PASS: TestAccCloudWatchLogsSubscriptionFilter_basic (52.59s)
--- PASS: TestAccCloudWatchLogsSubscriptionFilter_disappears (64.59s)
--- PASS: TestAccCloudWatchLogsSubscriptionFilter_Disappears_logGroup (68.77s)
--- PASS: …
```
=> r/cloudwatchlogs_subscription_filter - add plan time validations

.changelog/23772.txt, website/docs/r/autoscaling_group.html.markdown
=> Add "Hibernated" as possible `pool_state` state under autoscaling_group docs.

.changelog/23767.txt, internal/service/ec2/launch_template.go, internal/service/ec2/launch_template_test.go
0 is a legal device index, moreover a launchtemplate requires a network interface with a device index of 0 to be functional
Closes #23766
```
$make testacc TESTS=TestAccEC2LaunchTemplate_networkInterface PKG=ec2 
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 …
```
=> aws_launch_template: fix network interface device_index of 0 being ignored

website/docs/r/s3_bucket_object_lock_configuration.html.markdown
* had to disable `MD029` in the doc section as it does not seem to like having code blocks between ordered list items
* removed the indentation of the code blocks as that seems to be problematic but it's not tested
Relates https://github.com/hashicorp/terraform-provider-aws/issues/23761
Relates #23449 
```
N/A
```
=> docs/s3_bucket_object_lock_configuration: remove indentation of code blocks in ordered list

website/docs/r/s3_bucket_server_side_encryption_configuration.html.markdown
=> docs/s3_bucket_server_side_encryption_configuration: add usage notes

internal/acctest/provider_test.go, internal/conns/conns.go, internal/provider/provider.go, internal/provider/provider_test.go, internal/service/route53domains/registered_domain_test.go, names/names.go, names/names_test.go
Closes #23794
Output from testing:
```console
% go test ./...
?   	github.com/hashicorp/terraform-provider-aws	[no test files]
ok  	github.com/hashicorp/terraform-provider-aws/internal/acctest	6.626s
?   	github.com/hashicorp/terraform-provider-aws/internal/attrmap	[no test files]
ok  	github.com/hashicorp/terraform-provider-aws/internal/conns	1.329s
ok …
```
=> Move service name info out of internal

names/names.go, names/names_test.go
```
--- PASS: TestAWSServiceName (0.00s)
--- PASS: TestAWSServiceName/empty (0.00s)
--- PASS: TestAWSServiceName/transcribe (0.00s)
--- PASS: TestAWSServiceName/appautoscaling (0.00s)
--- PASS: TestAWSServiceName/dms (0.00s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/names	0.308s
```
=> names: Add AWS service name getting

.changelog/23804.txt, internal/service/kafka/cluster_data_source.go, internal/service/kafka/cluster_data_source_test.go, website/docs/d/msk_cluster.html.markdown
=> Add `zookeeper_connect_string_tls` to MSK cluster data source

.changelog/23796.txt, internal/provider/provider.go, internal/service/memorydb/subnet_group_data_source.go, internal/service/memorydb/subnet_group_data_source_test.go, website/docs/d/memorydb_subnet_group.html.markdown
```
$ make testacc PKG=memorydb TESTS=TestAccMemoryDBSubnetGroupDataSource_
TF_ACC=1 go test ./internal/service/memorydb/... -v -count 1 -parallel 20 -run='TestAccMemoryDBSubnetGroupDataSource_' …
```
=> d/aws_memorydb_subnet_group: new data source

website/docs/r/guardduty_ipset.html.markdown
* Removed `public-read` acl from example as it's not required due to Guard Duty automatically updating its own service role permissions to access the object when referencing it for use in an IP list. Given the sensitive nature of this files contents, I thought it best to encourage best practice and keep the file secured by default if someone copies and …
=> Removing unnecessarily insecure S3 ACL from GuardDuty IPSet example

.changelog/23814.txt, internal/provider/provider.go, internal/service/memorydb/parameter_group_data_source.go, internal/service/memorydb/parameter_group_data_source_test.go, website/docs/d/memorydb_parameter_group.html.markdown
```
$ make testacc PKG=memorydb TESTS=TestAccMemoryDBParameterGroupDataSource_
TF_ACC=1 go test ./internal/service/memorydb/... -v -count 1 -parallel 20 …
```
=> d/aws_memorydb_parameter_group: new data source

.changelog/23815.txt, internal/service/glue/schema_test.go, website/docs/r/glue_schema.html.markdown
…supported `data_format`
Closes #23811
```
$ make testacc TESTS=TestAccGlueSchema_protobuf PKG=glue             (base) 
TF_ACC=1 go test ./internal/service/glue/... -v -count 1 -parallel 20 -run='TestAccGlueSchema_protobuf'  -timeout 180m
=== RUN …
```
=> Update docs to refelect `PROTOBUF` as a supported `data_format` for the `aws_glue_schema` resource

skaff/cmd/resource.go, skaff/go.mod, skaff/go.sum
Fix **importlint** error:
```
Run impi --local . --scheme stdThirdPartyLocal ./...
Error: skaff/cmd/resource.go: Import groups are not in the proper order: ["Third party" "Third party"]
impi verification failed: Found 1 errors
```
Plus, use local file path to import `terraform-provider-aws`.
=> Fix skaff importlint error

.github/workflows/release.yml
Relates https://github.com/hashicorp/terraform-provider-aws/pull/23856
Relates #23188
```
N/A
...
```
=> github/workflows/release: Set `actions/checkout` step in `changelog-newversion` job to default to the branch that triggered the event

.github/workflows/post_publish.yml
@breathingdust noticed this job hasn't run since `v4.4.0`, so reinstating this to the trigger used before migrating to GHA release process.
```
N/A
```
=> github/workflows/post_publish: Set job to trigger on `published` event instead

.changelog/23862.txt, internal/service/events/target.go, internal/service/events/target_test.go
Closes #23805
```
$ make testacc TESTS=TestAccEventsTarget_http PKG=events
--- PASS: TestAccEventsTarget_http (45.81s)
--- PASS: TestAccEventsTarget_http_params (86.56s)
```
=> r/cloudwatch_event_target - fix setting `path_parameter_values`

.changelog/23859.txt, internal/service/ec2/eips_data_source.go, internal/service/ec2/eips_data_source_test.go, website/docs/d/eips.html.markdown
Closes #23847
```
$ ake testacc TESTS=TestAccEC2EIPsDataSource_vpcDomain PKG=ec2
--- PASS: TestAccEC2EIPsDataSource_vpcDomain (30.42s)
```
=> d/eips - set `public_ips` for vpc as well as ec2 classic

website/docs/r/default_network_acl.html.markdown
The documentation for the resource "aws_default_network_acl" claims that the default network ACL ingress rule only accepts the traffic for the corresponding VPC, when in fact the default is to accept all ingress traffic:
https://docs.aws.amazon.com/vpc/latest/userguide/vpc-network-acls.html#default-network-acl
If someone actually believes this and applies this example, you can easily e.g. cut off your website from the internet.
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra …
=> aws_default_network_acl: fix an example of the default configuration

.changelog/22355.txt, internal/acctest/acctest.go, internal/service/networkfirewall/firewall_policy_test.go, internal/verify/validate.go
Closes #22154
```
$make testacc TESTS=TestAccNetworkFirewallFirewallPolicy_statefulRuleGroupReferenceManaged PKG=networkfirewall
TF_ACC=1 go test ./internal/service/networkfirewall/... -v -count 1 -parallel 20 …
```
=> update network firewall policy arn regex for aws managed rules

website/docs/r/ses_identity_notification_topic.markdown
This pull request improves slightly the rendering of [the `aws_ses_identity_notification_topic` resource's documentation](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ses_identity_notification_topic).
=> Improve formatting for ses_identity_notification_topic doc

.changelog/20708.txt, internal/service/autoscaling/group.go, internal/service/autoscaling/group_test.go
Closes #19714
Closes #4714
```
...
```
=> aws_autoscaling_group `initial_lifecycle_hook` set `ForceNew: true`

.changelog/23879.txt, internal/service/lambda/function.go
Continues the work in https://github.com/hashicorp/terraform-provider-aws/pull/10049
Relates https://github.com/hashicorp/terraform-provider-aws/issues/5154
```
--- PASS: TestAccLambdaFunction_basic (35.99s)
--- PASS: TestAccLambdaFunction_vpc (1575.70s)
--- PASS: TestAccLambdaFunction_disappears (206.83s)
```
=> r/lambda_function: add `ResourceConflictException` error handling on create and update

.changelog/22160.txt, internal/service/cloudformation/wait.go
A StackSet using [Managed Execution](https://aws.amazon.com/about-aws/whats-new/2021/11/aws-cloudformation-stacksets-operations-execution/) can internally queue Operations before they're executed. 
When doing so the status of the Operation is set to Queued.
Initially, concurrent Operations may also be set to Queued, until they're deemed safe to start.
The …
=> Adds Queued as a StackSet Operating Waiter Pending state

.changelog/23890.txt, internal/provider/provider.go, internal/service/memorydb/user_data_source.go, internal/service/memorydb/user_data_source_test.go, website/docs/d/memorydb_user.html.markdown
```
$ make testacc PKG=memorydb TESTS=TestAccMemoryDBUserDataSource_
TF_ACC=1 go test ./internal/service/memorydb/... -v -count 1 -parallel 20 -run='TestAccMemoryDBUserDataSource_'  -timeout 180m …
```
=> d/aws_memorydb_user: new data source

.changelog/23891.txt, internal/provider/provider.go, internal/service/memorydb/acl_data_source.go, internal/service/memorydb/acl_data_source_test.go, website/docs/d/memorydb_acl.html.markdown
```
$ make testacc PKG=memorydb TESTS=TestAccMemoryDBACLDataSource_
TF_ACC=1 go test ./internal/service/memorydb/... -v -count 1 -parallel 20 -run='TestAccMemoryDBACLDataSource_'  -timeout 180m …
```
=> d/aws_memorydb_acl: new data source

.changelog/23893.txt, internal/service/s3/bucket_lifecycle_configuration.go, internal/service/s3/bucket_lifecycle_configuration_test.go
Closes https://github.com/hashicorp/terraform-provider-aws/issues/23884
Relates https://github.com/hashicorp/terraform-provider-aws/issues/23883
```
$ make testacc TESTARGS='-run=TestAccS3BucketLifecycleConfiguration_' PKG=s3 ACCTEST_PARALLELISM=5 …
```
=> r/s3_bucket_lifecycle_configuration: use custom `DiffSuppressFunc` on `rule.filter` parameter

.changelog/23908.txt, CHANGELOG.md, internal/service/cloudformation/stack_set.go, internal/service/cloudformation/stack_set_instance.go, internal/service/cloudformation/stack_set_test.go, internal/service/cloudformation/type.go, website/docs/r/cloudformation_stack_set.html.markdown
Release Note:
```
* resource/aws_cloudformation_stack_set: Add `operation_preferences` argument
```
Could use some help from a maintainer to run acceptance tests, but all unit tests pass and I've done `go fmt`.
I've mostly adapted the work done by @Popsiclestick here https://github.com/hashicorp/terraform-provider-aws/pull/2366 …
=> Add support for operation_preferences in stackset update

.changelog/23924.txt, internal/service/imagebuilder/distribution_configuration.go, internal/service/imagebuilder/distribution_configuration_data_source.go, internal/service/imagebuilder/distribution_configuration_data_source_test.go, internal/service/imagebuilder/distribution_configuration_test.go, website/docs/d/imagebuilder_distribution_configuration.html.markdown, website/docs/r/imagebuilder_distribution_configuration.html.markdown
Closes #23919 
```
$ make testacc TESTARGS="-run=TestAccImageBuilderDistributionConfiguration_Distribution_launchTemplateConfiguration" PKG_NAME=internal/service/imagebuilder …
```
=> aws_imagebuilder_distribution_configuration: Add Account ID to Launch Template Configuration

website/docs/r/autoscaling_attachment.html.markdown
alb_target_group_arn is deprecated as stated in the reference, but was
still used in the example.
=> r/autoscaling_attachment.html.markdown: Don't use the deprecated parameter in the example

internal/service/backup/region_settings.go, internal/service/backup/region_settings_test.go, internal/service/backup/report_plan.go, internal/service/backup/report_plan_data_source.go, internal/service/backup/report_plan_data_source_test.go, internal/service/backup/report_plan_test.go
Closes #23941.
```console
% make testacc TESTS=TestAccBackupRegionSettings_ PKG=backup
TF_ACC=1 go test ./internal/service/backup/... -v -count 1 -parallel 20 -run='TestAccBackupRegionSettings_'  -timeout 180m
=== RUN   TestAccBackupRegionSettings_basic
=== PAUSE …
```
=> test/backup: Fix `TestAccBackupRegionSettings_basic` and `TestAccBackupReportPlan_basic`

website/docs/r/ses_receipt_rule.html.markdown
From https://docs.aws.amazon.com/ses/latest/APIReference/API_StopAction.html
=> SES receipt rule resource: Fix `scope` definition inside `stop_action`.

.changelog/23967.txt, internal/service/backup/consts.go, internal/service/backup/report_plan.go
Closes #23966.
```console
% make testacc TESTS=TestAccBackupReportPlan_ PKG=backup ACCTEST_PARALLELISM=3
TF_ACC=1 go test ./internal/service/backup/... -v -count 1 -parallel 3 -run='TestAccBackupReportPlan_'  -timeout 180m
=== RUN   TestAccBackupReportPlan_basic
=== …
```
=> r/aws_backup_report_plan: Wait for correct `DeploymentStatus` after lifecycle operations

website/docs/r/vpc.html.markdown
The previous documentation seemed to use the EC2 instance tenancy information, which is different from VPC tenancy. I updated the AWS provider documentation with the AWS text from [here](https://docs.aws.amazon.com/vpc/latest/userguide/working-with-vpcs.html).
Closes #23916
```
$ make testacc …
```
=> r/aws_vpc: Update tenancy

website/docs/r/glue_catalog_table.html.markdown
Add a note to the update partition_index information with a note that it only works for new tables; existing tables should use the glue_partition_index resource. I used the notes on s3_bucket as a template.
Closes #23929
=> r/glue_catalog_table: Note on partition_index

.changelog/23798.txt, internal/service/s3/bucket.go, internal/service/s3/bucket_acl_test.go, internal/service/s3/bucket_public_access_block_test.go, internal/service/s3/bucket_test.go, internal/service/s3/object_copy.go, website/docs/r/s3_bucket.html.markdown
```
$ make testacc TESTARGS='-run=TestAccS3Bucket_' PKG=s3 ACCTEST_PARALLELISM=5
TF_ACC=1 go test ./internal/service/s3/... -v -count 1 -parallel 5  -run=TestAccS3Bucket_ -timeout …
```
=> r/s3_bucket: make `acl` and `grant` configurable

.changelog/23816.txt, internal/service/s3/bucket.go, internal/service/s3/bucket_accelerate_configuration_test.go, internal/service/s3/bucket_test.go, website/docs/r/s3_bucket.html.markdown
```
--- PASS: TestAccS3Bucket_Basic_acceleration (42.63s)
--- PASS: TestAccS3BucketAccelerateConfiguration_disappears (24.41s)
--- PASS: TestAccS3BucketAccelerateConfiguration_basic (29.53s)
--- PASS: …
```
=> r/s3_bucket: make `acceleration status` configurable

.changelog/23817.txt, internal/service/s3/bucket.go, internal/service/s3/bucket_cors_configuration_test.go, internal/service/s3/bucket_test.go, website/docs/r/s3_bucket.html.markdown
```
--- PASS: TestAccS3Bucket_Security_corsDelete (20.41s)
--- PASS: TestAccS3Bucket_Security_corsSingleMethodAndEmptyOrigin (24.14s)
--- PASS: TestAccS3Bucket_Security_corsEmptyOrigin (24.44s)
--- PASS: TestAccS3Bucket_Security_corsUpdate …
```
=> r/s3_bucket: make `cors_rule` configurable

.changelog/23818.txt, internal/service/s3/bucket.go, internal/service/s3/bucket_acl_test.go, internal/service/s3/bucket_lifecycle_configuration_test.go, internal/service/s3/bucket_test.go, internal/service/s3/validate.go, website/docs/r/s3_bucket.html.markdown
```
$ make testacc TESTARGS='-run=TestAccS3BucketLifecycleConfiguration_' PKG=s3 ACCTEST_PARALLELISM=5
TF_ACC=1 go test ./internal/service/s3/... -v -count 1 -parallel 5 …
```
=> r/s3_bucket: make `lifecycle_rule` configurable

.changelog/23819.txt, internal/service/s3/bucket.go, internal/service/s3/bucket_logging_test.go, internal/service/s3/bucket_test.go, website/docs/r/s3_bucket.html.markdown
```
--- PASS: TestAccS3Bucket_Security_logging (25.98s)
--- SKIP: TestAccS3BucketLogging_TargetGrantByEmail (0.00s)
--- PASS: TestAccS3BucketLogging_disappears (24.19s)
--- PASS: TestAccS3BucketLogging_basic (28.36s)
--- PASS: …
```
=> r/s3_bucket: make `logging` configurable

.changelog/23820.txt, internal/service/s3/bucket.go, internal/service/s3/bucket_test.go, internal/service/s3/bucket_versioning_test.go, website/docs/r/s3_bucket.html.markdown
```
--- PASS: TestAccS3Bucket_Manage_lifecycleRuleExpirationEmptyBlock (62.15s)
--- PASS: TestAccS3Bucket_Manage_objectLock (63.65s)
--- PASS: TestAccS3Bucket_Manage_versioningDisabled (63.92s)
--- PASS: TestAccS3Bucket_Manage_versioningAndMfaDeleteDisabled (77.82s)
--- PASS: …
```
=> r/s3_bucket: make `versioning` configurable

.changelog/23821.txt, internal/service/s3/bucket.go, internal/service/s3/bucket_test.go, internal/service/s3/bucket_website_configuration_test.go, website/docs/r/s3_bucket.html.markdown
```
--- PASS: TestAccS3Bucket_Web_routingRules (33.35s)
--- PASS: TestAccS3Bucket_Web_simple (51.95s)
--- PASS: TestAccS3Bucket_Web_redirect (52.25s)
--- PASS: TestAccS3BucketWebsiteConfiguration_disappears (25.81s)
--- PASS: …
```
=> r/s3_bucket: make `website` configurable

.changelog/23822.txt, internal/service/s3/bucket.go, internal/service/s3/bucket_server_side_encryption_configuration_test.go, internal/service/s3/bucket_test.go, website/docs/r/s3_bucket.html.markdown
```
--- PASS: TestAccS3Bucket_Basic_forceDestroyWithEmptyPrefixes (22.69s)
--- PASS: TestAccS3Bucket_Basic_forceDestroy (23.25s)
--- PASS: TestAccS3Bucket_Basic_namePrefix (25.17s)
--- PASS: TestAccS3Bucket_Basic_generatedName (25.21s)
--- …
```
=> r/s3_bucket: make `server_side_encryption_configuration` configurable

.changelog/23842.txt, internal/service/s3/bucket.go, internal/service/s3/bucket_replication_configuration_test.go, internal/service/s3/bucket_test.go, internal/service/s3/errors.go, website/docs/r/s3_bucket.html.markdown
```
--- PASS: TestAccS3Bucket_Replication_expectVersioningValidationError (33.41s)
--- PASS: TestAccS3Bucket_Replication_schemaV2SameRegion (76.05s)
--- PASS: TestAccS3Bucket_Replication_withoutPrefix (107.86s)
--- PASS: …
```
=> r/s3_bucket: make `replication_configuration` configurable

.changelog/23843.txt, internal/service/s3/bucket.go, internal/service/s3/bucket_policy_test.go, internal/service/s3/bucket_test.go, internal/service/s3/errors.go, website/docs/r/s3_bucket.html.markdown
```
--- PASS: TestAccS3Bucket_Security_policy (44.35s)
--- PASS: TestAccS3BucketPolicy_migrate_withChange (33.55s)
--- PASS: TestAccS3BucketPolicy_migrate_noChange (33.72s)
```
=> r/s3_bucket: make `policy` configurable

.changelog/23844.txt, internal/service/s3/bucket.go, internal/service/s3/bucket_request_payment_configuration_test.go, internal/service/s3/bucket_test.go, website/docs/r/s3_bucket.html.markdown
```
--- PASS: TestAccS3Bucket_Basic_requestPayer (35.01s)
--- PASS: TestAccS3BucketRequestPaymentConfiguration_migrate_noChange (32.56s)
--- PASS: TestAccS3BucketRequestPaymentConfiguration_migrate_withChange (32.68s)
```
=> r/s3_bucket: make `request_payer` configurable

.changelog/23990.txt, internal/provider/provider.go, internal/service/memorydb/snapshot_data_source.go, internal/service/memorydb/snapshot_data_source_test.go, website/docs/d/memorydb_snapshot.html.markdown
```
$ make testacc PKG=memorydb TESTS=TestAccMemoryDBSnapshotDataSource_ ACCTEST_TIMEOUT=600m
TF_ACC=1 go test ./internal/service/memorydb/... -v -count 1 -parallel 20 …
```
=> d/aws_memorydb_snapshot: new data source

.changelog/23973.txt, internal/service/ec2/vpc_ipam.go, internal/service/ec2/vpc_ipam_test.go, website/docs/r/vpc_ipam.html.markdown
=> support aws_vpc_ipam cascade for easier deletes

.changelog/23993.txt, internal/service/iot/authorizer.go, internal/service/iot/authorizer_test.go, website/docs/r/iot_authorizer.html.markdown
Adds support for HTTP caching on an IoT authorizer.
```
$ AWS_PROFILE=default make testacc TESTARGS='-run=TestAccIoTAuthorizer_basic' PKG_NAME=internal/service/iot
TF_ACC=1 go test ./internal/service/iot/... -v -count 1 -parallel 20  -run=TestAccIoTAuthorizer_basic …
```
=> IoT Authorizer HTTP caching support

website/docs/r/lambda_function.html.markdown
**Reasoning for Change:**
I tend to look at example code first (because it's at the top of the page) and this example can be a bit misleading if the resource is in a module. Especially because it says "filename" which, given the example, leads me to believe it doesn't need a path.
**Prefer AWS Documentation:**
N/A
**Large Example Configurations:**
N/A
**Terraform Configuration Language Features:**
N/A
This recently bit me. Took me a bit to figure it out. Maybe I'm dumb ¯\\\_(ツ)\_/¯
I had a lambda resource in a module. Based on the sample I thought I had done everything right. Then I realized that because this was a module I needed to specify more than just the filename. 
I think where I get screwed up is that filename, to me, means just the name of the file but in reality this is path and …
=> Add note about filename

.changelog/23952.txt, internal/conns/conns.go
Closes https://github.com/hashicorp/terraform-provider-aws/issues/23946
* Tests already passing in nightly CI so I only ran the `update` test since the error may not be apparent with our test configs
```
--- PASS: TestAccFMS_serial (1082.54s)
--- PASS: TestAccFMS_serial/Policy (1082.54s)
--- PASS: …
```
=> internal/conns: add retry handling for `InternalErrorException` when calling FMS `PutPolicy`

.changelog/23984.txt, internal/service/s3/bucket.go, internal/service/s3/bucket_object_lock_configuration_test.go, internal/service/s3/bucket_test.go, website/docs/r/s3_bucket.html.markdown
```
--- PASS: TestAccS3BucketObjectLockConfiguration_disappears (21.35s)
--- PASS: TestAccS3BucketObjectLockConfiguration_basic (23.82s)
--- PASS: TestAccS3BucketObjectLockConfiguration_migrate_withChange (34.92s)
--- PASS: TestAccS3BucketObjectLockConfiguration_migrate_noChange (35.52s)
--- PASS: …
```
=> r/s3_bucket: make `object_lock_configuration.rule` configurable

website/docs/r/eks_addon.html.markdown
Closes #23974
Output from acceptance testing: n/a, documentation
As called out in the linked issue, we previously linked to [list-addons](https://docs.aws.amazon.com/cli/latest/reference/eks/list-addons.html), however, according to the [API Documentation](https://docs.aws.amazon.com/eks/latest/APIReference/API_CreateAddon.html#API_CreateAddon_RequestSyntax), …
=> Change the link provided to describe addons

.changelog/24002.txt, internal/service/fsx/ontap_file_system.go, internal/service/fsx/ontap_file_system_test.go
Closes #23983
Closes #23982
Closes #23861
```
$ make testacc TESTS=TestAccFSxOntapFileSystem_ PKG=fsx
--- PASS: TestAccFSxOntapFileSystem_endpointIPAddressRange (2030.71s)
--- PASS: TestAccFSxOntapFileSystem_basic (2051.03s)
--- PASS: TestAccFSxOntapFileSystem_weeklyMaintenanceStartTime (2109.52s)
--- PASS: …
```
=> r/fsx_ontap_file_system - Support updating `storage_capacity`, `throughput_capacity`, `disk_iops_configuration`

.changelog/24011.txt, internal/provider/provider.go, internal/service/ssm/maintenance_windows_data_source.go, internal/service/ssm/maintenance_windows_data_source_test.go, website/docs/d/ssm_maintenance_windows.html.markdown
Adds a new datasource for fetching a list of maintenance window IDs based on the available filters (Name and Enabled) provided by the API.
```
$ make testacc TESTS=TestAccSSMMaintenanceWindowsDataSource_filter PKG=ssm
TF_ACC=1 go test ./internal/service/ssm/... -v …
```
=> f/aws_ssm_maintenance_windows: add new datasource

.changelog/23947.txt, internal/provider/provider.go, internal/service/dynamodb/contributor_insights.go, internal/service/dynamodb/contributor_insights_test.go, internal/service/dynamodb/find.go, internal/service/dynamodb/status.go, internal/service/dynamodb/wait.go, website/docs/r/dynamodb_contributor_insights.html.markdown
Closes #13933
Creates new resource for `aws_dynamodb_contributor_insights`
```hcl
resource "aws_dynamodb_contributor_insights" "test" {
table_name = "TestTableName"
}
```
```
$ make testacc TESTS=TestAccContributorInsights_ PKG=dynamodb
=== RUN   TestAccContributorInsights_basic
=== PAUSE TestAccContributorInsights_basic
=== …
```
=> r/aws_dynamo_contributor_insights: Add new resource

.changelog/24028.txt, internal/service/xray/group.go, internal/service/xray/group_test.go, website/docs/r/xray_group.html.markdown
Adds support for `insights_configuration` to  `aws_xray_group`. See the [X-Ray Group API docs](https://docs.aws.amazon.com/xray/latest/api/API_Group.html) for more details.
```
$ make testacc TESTS=TestAccXRayGroup PKG=xray
TF_ACC=1 go test ./internal/service/xray/... …
```
=> Add insights_configuration argument to aws_xray_group resource

.changelog/24024.txt, CHANGELOG.md, internal/service/ec2/default_route_table.go, internal/service/ec2/route.go, internal/service/ec2/route_data_source.go, internal/service/ec2/route_table.go, internal/service/ec2/route_table_data_source.go, internal/service/ec2/route_test.go, internal/service/ec2/vpn_connection.go, internal/service/ec2/vpn_connection_test.go, website/docs/d/route.html.markdown, website/docs/d/route_table.html.markdown, website/docs/r/default_route_table.html.markdown, website/docs/r/route.html.markdown, website/docs/r/route_table.html.markdown, website/docs/r/vpn_connection.html.markdown
When the route's wait-for-creation operation times out, its state is leaked as `d.SetId(...)` is called after the `WaitRouteReady(...)`. So, the next time the configuration is applied, the Terraform engine tries to create the same route again, getting duplication error from AWS.
Call `d.SetId(...)` before `WaitRouteReady(...)`.
Closes  #23827
Output from …
=> r/aws_route: Call SetId before WaitRouteReady

.changelog/24053.txt, internal/provider/provider.go, internal/service/lambda/function_url.go, internal/service/lambda/function_url_data_source.go, internal/service/lambda/function_url_data_source_test.go, internal/service/lambda/function_url_test.go, website/docs/d/lambda_function_url.html.markdown, website/docs/r/lambda_function_url.html.markdown
Closes #24050.
```console
% make testacc TESTS=TestAccLambdaFunctionURL PKG=lambda ACCTEST_PARALLELISM=2
TF_ACC=1 go test ./internal/service/lambda/... -v -count 1 -parallel 2 -run='TestAccLambdaFunctionURL'  -timeout 180m
=== RUN   TestAccLambdaFunctionURLDataSource_basic
=== PAUSE …
```
=> Lambda Function URLs

website/docs/index.html.markdown
The AWS SDK for Go automatically provides the ability to assume an IAM role using web identity federation by configuring using environment variables or a named profile in shared config files.
Document these settings.
#22907 will add support for configuring this setting in the provider.
N/A
=> Adds documentation for assuming an IAM role using web identity federation

.changelog/24064.txt, go.mod, go.sum, website/docs/index.html.markdown
Adds support for reading custom CA bundle from shared config files.
N/A
=> Updates `aws-sdk-go-base` to `v2.0.0-beta.14` and `awsv1shim` to `v2/awsv1shim/v2.0.0-beta.15`

.changelog/23996.txt, internal/service/elasticache/cluster.go, internal/service/elasticache/cluster_test.go, internal/service/elasticache/replication_group.go, internal/service/elasticache/replication_group_test.go, website/docs/r/elasticache_cluster.html.markdown, website/docs/r/elasticache_replication_group.html.markdown
Enables `auto_minor_version_upgrade` for `aws_elasticache_cluster` and properly supports `auto_minor_version_upgrade` for `aws_elasticache_replication_group`.
Relates #22385
```
$ make testacc PKG=elasticache TESTS='TestAccElastiCacheCluster_|TestAccElastiCacheReplicationGroup_'
--- PASS: TestAccElastiCacheClusterDataSource_Data_basic (497.16s)
--- PASS: TestAccElastiCacheClusterDataSource_Engine_Redis_LogDeliveryConfigurations (734.80s)
--- PASS: TestAccElastiCacheCluster_EngineVersion_redis (1624.58s)
--- PASS: TestAccElastiCacheReplicationGroupDataSource_nonExistent (2.56s)
--- PASS: TestAccElastiCacheReplicationGroupDataSource_Engine_Redis_LogDeliveryConfigurations (786.95s)
--- PASS: TestAccElastiCacheReplicationGroupDataSource_multiAZ (879.79s)
--- …
```
=> elasticache/aws_elasticache_cluster: Enable `auto_minor_version_upgrade`

internal/service/gamelift/alias.go, internal/service/gamelift/alias_test.go, internal/service/gamelift/build.go, internal/service/gamelift/build_test.go, internal/service/gamelift/fleet.go, internal/service/gamelift/fleet_test.go, internal/service/gamelift/game_server_group.go, internal/service/gamelift/game_server_group_test.go, internal/service/gamelift/game_session_queue.go, internal/service/gamelift/game_session_queue_test.go, internal/service/gamelift/gamelift_test.go, internal/service/gamelift/script.go, internal/service/gamelift/script_test.go, internal/service/gamelift/sweep.go, internal/service/gamelift/wait.go, website/allowed-subcategories.txt, website/docs/r/gamelift_alias.html.markdown, website/docs/r/gamelift_build.html.markdown, website/docs/r/gamelift_fleet.html.markdown, website/docs/r/gamelift_game_server_group.markdown, website/docs/r/gamelift_game_session_queue.html.markdown, website/docs/r/gamelift_script.html.markdown
```console
% make testacc TESTS=Test PKG=gamelift 
TF_ACC=1 go test ./internal/service/gamelift/... -v -count 1 -parallel 20 -run='Test'  -timeout 180m
--- PASS: TestDiffGameLiftPortSettings (0.00s)
--- PASS: …
```
=> Correct GameLift name

website/docs/r/cloudtrail.html.markdown
This is just update of documentation as `aws_s3_bucket` policy statement was deprecated and now should be in resource `aws_s3_bucket_policy`
Before updating example:
```
╷
│ Warning: Argument is deprecated
│ 
│   with aws_s3_bucket.foo,
│   on main.tf line 14, in resource "aws_s3_bucket" "foo":
│   14:   policy = <<POLICY
│   15: {
│   16:     "Version": …
```
=> docs: update cloudtrail docs for aws_s3_bucket

website/docs/r/lambda_permission.html.markdown
Fixig typo in `lambda_permission` docs
=> docs(lambda_permission): fix typo

internal/acctest/provider_test.go
Closes #23954
```console
% TF_ACC=1 go test ./internal/acctest... -v -count 1 -parallel 20 -run='TestAccProvider' -short -timeout 180m
--- PASS: TestAccProvider_Region_stsRegion (20.73s)
--- PASS: TestAccProvider_Region_awsSC2S (20.74s)
--- PASS: TestAccProvider_Region_awsGovCloudUs (20.95s)
--- PASS: …
```
=> provider: Fix endpoints test panic

website/docs/r/cloudformation_stack_set.html.markdown
The list modified didn't have spaces between the `*` and the list item, so the markdown rendered poorly. This PR aims to fix that formatting.
=> Fix list in aws_cloudformation_stack_set docs

.changelog/24148.txt, internal/service/cloudwatchlogs/subscription_filter.go, internal/service/cloudwatchlogs/subscription_filter_test.go
Closes #24063
- Add retry for error `OperationAbortedException: [.*] Please try again.` (rather than ensuring creation is serial as originally described in issue)
```
$ make testacc TESTS=TestAccCloudWatchLogsSubscriptionFilter_many PKG=cloudwatchlogs …
```
=> Add retry for "conflicting operation" when creating/updating multiple `aws_cloudwatch_log_subscription_filter` resources

.github/labeler-issue-triage.yml, .github/labeler-pr-triage.yml, infrastructure/repository/labels-service.tf, internal/conns/conns.go, internal/generate/listpages/main.go, internal/generate/tags/main.go, names/names.go, names/names_test.go, website/allowed-subcategories.txt, website/docs/guides/custom-service-endpoints.html.md
Relates #22624
```
$ make test
go test ./...  -timeout=5m
?       github.com/hashicorp/terraform-provider-aws     [no test files]
ok      github.com/hashicorp/terraform-provider-aws/internal/acctest    (cached)
? …
```
=> Add provider infrastructure for Amazon CloudWatch Evidently

.changelog/24172.txt, internal/service/athena/database.go, internal/service/athena/database_test.go, website/docs/r/athena_database.html.markdown
Closes #24022
```
$ make testacc TESTS=TestAccAthenaDatabase_ PKG=athena
--- PASS: TestAccAthenaDatabase_nameCantHaveUppercase (4.89s)
--- PASS: TestAccAthenaDatabase_disppears (49.70s)
--- PASS: TestAccAthenaDatabase_properties (55.26s)
--- PASS: TestAccAthenaDatabase_forceDestroyAlwaysSucceeds (55.45s)
--- PASS: …
```
=> r/athena_database - add `properties` + import support

.changelog/24190.txt, internal/provider/provider.go, internal/service/ec2/nat_gateways_data_source.go, internal/service/ec2/nat_gateways_data_source_test.go, website/docs/d/nat_gateways.html.markdown
Closes #7575
```
$ make testacc TESTS=TestAccEC2NatGatewaysDataSource_basic PKG=ec2
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 20 -run='TestAccEC2NATGatewaysDataSource_basic'  -timeout 180m
=== RUN   TestAccEC2NATGatewaysDataSource_basic
=== …
```
=> Add aws_nat_gateways data source

.changelog/24188.txt, internal/service/ec2/vpc_ipam_scope.go
Closes https://github.com/hashicorp/terraform-provider-aws/issues/24168
```
make testacc TESTARGS='-run=TestAccVPCIpamScope_' PKG=ec2
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 20  -run=TestAccVPCIpamScope_ -timeout 180m
=== RUN …
```
=> r/vpc_ipam_scope: prevent panic and add pagination when describing existing scopes by ID

internal/service/rds/cluster_activity_stream_test.go
Regions that are not supported can be found [here](https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/DBActivityStreams.Overview.html)
Closes #24160
```
$ make testacc TESTS=TestAccAWSRDSClusterActivityStream_ PKG=rds …
```
=> t-aws_rds_activity_stream: Exclude regions that are not supported in test

.changelog/24204.txt, .github/workflows/documentation.yml, .github/workflows/website.yml, internal/provider/provider.go, internal/service/elasticache/user.go, internal/service/elasticache/user_group_association.go, internal/service/elasticache/user_group_association_test.go, website/docs/r/elasticache_user_group_association.html.markdown
Closes #22870
```console
% make testacc TESTS=TestAccElastiCacheUserGroupAssociation_ PKG=elasticache
TF_ACC=1 go test ./internal/service/elasticache/... -v -count 1 -parallel 20 -run='TestAccElastiCacheUserGroupAssociation_'  -timeout 180m
--- PASS: …
```
=> elasticache: Add new user_group_association resource

website/allowed-subcategories.txt
Add Elemental MediaTailor to the list of allowed subcategories for documentation navigation. This is the only missing step of the [guidelines for adding a new service](https://github.com/hashicorp/terraform-provider-aws/blob/main/docs/contributing/contribution-checklists.md#new-service) to the provider.
Relates #24214
```
$ …
```
=> fix: add Elemental MediaTailor to list of allowed subcategories

.changelog/24220.txt, internal/service/lambda/function_url.go, internal/service/lambda/function_url_test.go
Closes #24152
```
$ make testacc TESTARGS="-run=TestAccLambdaFunctionURL_TwoURLs" PKG=lambda
TF_ACC=1 go test ./internal/service/lambda/... -v -count 1 -parallel 20  -run=TestAccLambdaFunctionURL_TwoURLs -timeout 180m
=== RUN   TestAccLambdaFunctionURL_TwoURLs
=== …
```
=> fixing error for creating additonal Lambda URLs on the same function

.changelog/24218.txt, internal/service/eks/addon.go, internal/service/eks/addon_data_source_test.go, internal/service/eks/addon_test.go, internal/service/eks/addon_version_data_source_test.go, website/docs/r/eks_addon.html.markdown
Signed-off-by: Stijn De Haes <stijndehaes@gmail.com>
Closes #22226
```
$ make testacc TESTS=TestAccEKSAddon_basic PKG=eks
TF_ACC=1 go test ./internal/service/eks/... -v -count 1 -parallel 20 -run='TestAccEKSAddon_basic'  -timeout 180m
=== RUN   TestAccEKSAddon_basic …
```
=> feat: Add support for preserve to eks add-on

.changelog/24202.txt, internal/service/cloudformation/stack_set_test.go, internal/service/cloudformation/type.go
The `failure_tolerance_count` and `failure_tolerance_percentage` conflict with each other, so one should be validated only if the other has failed. The same applies for `max_concurrent_count` and `max_concurrent_percentage`.
Closes #24161
=> Do not validate items that conflict

infrastructure/repository/labels-workflow.tf
Output from acceptance testing: N/a, new GitHub label
The PR adds a new label called `new-service`, which will be used to tag issues / PRs that introduce an entirely new service to the provider. Also removes a bit of extra whitespace while we're at it.
=> [Repository] Add new-service label

website/docs/r/emr_cluster.html.markdown
Closes #23226
Previously, the `aws_emr_cluster.applications` argument had a static list of allowed values, which was out of date by quite a ways. This PR aims to update the description to point directly at the AWS documentation so that the list is never out of date.
In the description in the SDK/API documentation, it …
=> Update description of `aws_emr_cluster.applications`

website/docs/r/cognito_user_pool_client.markdown
Closes #23374
As requested in #23374, this PR adds an example to the `aws_cognito_user_pool_client` resource to demonstrate using `COGNITO` as the IdP.
**_Note: I would appreciate a fairly thorough look over this, as I'm not able to test thoroughly, and am basing the configuration entirely off of reading Cognito …
=> Add example `aws_cognito_user_pool_client` with Cognito IdP

.changelog/24223.txt, internal/conns/conns.go, internal/service/ecs/service.go, internal/service/ecs/wait.go
Closes https://github.com/hashicorp/terraform-provider-aws/pull/23747 (this PR is a continuation)
Relates https://github.com/hashicorp/terraform-provider-aws/issues/20452
```
make testacc TESTARGS='-run=TestAccECSService_' PKG=ecs ACCTEST_PARALLELISM=5 …
```
=> r/ecs_service: add wait condition after create/update and handle errors when using `wait_for_steady_state`

.github/workflows/post_publish.yml, .github/workflows/release.yml
* This attempts to trigger the post_publish workflow based on the release workflow
* This attempts to fix the error seen on the `main` branch (can't commit changelog without branch) https://github.com/hashicorp/terraform-provider-aws/runs/5684880997?check_suite_focus=true
Relates https://github.com/hashicorp/terraform-provider-aws/pull/23854
Relates …
=> github/workflows: change post_publish to workflow dependency and skip `changelog-newversion` if tag is from non-default branch

.changelog/24250.txt, internal/service/cloudformation/stack_set_test.go, internal/service/cloudformation/type.go
Currently, an aws_cloudformation_stack_set with:
```
operation_preferences {
failure_tolerance_count = 0
max_concurrent_percentage = 100
}
```
fails with `Validation Error: Exactly one of FailureTolerancePercentage and FailureToleranceCount must be specified since both parameters are present`. This is because currently the `FailureToleranceCount` and `FailureTolerancePercentage` attributes are both set (possibly to a default value of 0) and then one is removed if it is zero and the other is non-zero. Therefore with the `operation_preferences` block above both remain, leading to the `Validation Error` being raised. This PR removes the requirement that the other be non-zero and so allows the above `operation_preferences` block to work.
Note that although this does not apply to …
=> stack_set.operation_preferences.failure_tolerance_count can be zero

.changelog/24266.txt, internal/service/s3/bucket_server_side_encryption_configuration.go
Closes https://github.com/hashicorp/terraform-provider-aws/issues/24232
```
$ make testacc TESTARGS='-run=TestAccS3BucketServer' PKG=s3 ACCTEST_PARALLELISM=5
TF_ACC=1 go test ./internal/service/s3/... -v -count 1 -parallel 5  -run=TestAccS3BucketServer -timeout 180m …
```
=> r/s3_bucket_server_side_encryption_configuration: retry on SSE not found errors

.changelog/24275.txt, internal/service/elasticache/cluster_data_source_test.go, internal/service/elasticache/cluster_test.go, internal/service/elasticache/global_replication_group_test.go, internal/service/elasticache/replication_group_data_source_test.go, internal/service/elasticache/replication_group_test.go, internal/service/elasticache/user_group_association_test.go, internal/verify/verify.go
Relates #18593
Relates #22532
Relates #23980
Closes #24276
```console
% make testacc TESTS=TestAcc PKG=elasticache TESTARGS=-short
TF_ACC=1 go test ./internal/service/elasticache/... -v -count 1 -parallel 20 -run='TestAcc' -short -timeout 180m
--- PASS: …
```
=> elasticache: ISO tagging, check for additional error

.changelog/24286.txt, internal/service/waf/byte_match_set.go, internal/service/wafregional/rule.go, internal/service/wafregional/validate.go, internal/service/wafregional/web_acl.go, internal/service/workspaces/workspace.go
Relates https://github.com/hashicorp/terraform-provider-aws/issues/14601.
picks up a couple new workspace compute types: `GRAPHICS_G4DN` and `GRAPHICSPRO_G4DN`
=> source large enum validations from AWS Go SDK

.changelog/24285.txt, internal/service/imagebuilder/infrastructure_configuration.go, internal/service/imagebuilder/infrastructure_configuration_data_source.go, internal/service/imagebuilder/infrastructure_configuration_data_source_test.go, internal/service/imagebuilder/infrastructure_configuration_test.go, website/docs/d/imagebuilder_infrastructure_configuration.html.markdown, website/docs/r/imagebuilder_infrastructure_configuration.html.markdown
Closes #24006.
```
$ make testacc PKG=imagebuilder TESTS="TestAccImageBuilderInfrastructureConfiguration_|TestAccImageBuilderInfrastructureConfigurationDataSource_" ACCTEST_PARALLELISM=2
TF_ACC=1 go test ./internal/service/imagebuilder/... -v -count 1 -parallel 2 …
```
=> rd/aw_ imagebuilder_infrastructure_configuration - instance metadata options

.changelog/24274.txt, internal/service/elasticache/user.go
This PR adds in the validation logic using existing validation with the SDK to validate that a user password for an elasticache cluster is within a specific range.  Without this, a module may fail after initial validation which is especially problematic for long running Terraform scripts.
Signed-off-by: Dustin Scott <sdustin@vmware.com>
Closes #24273 
Output …
=> fix: add validation to passwords field of elasticache replication group

.changelog/24278.txt, internal/service/elasticbeanstalk/environment.go
Hey, there seems to be a subtle bug with the beanstalkCnamePrefixRegexp where it may match domains that are likely unexpected to be matched e.g. ebamazonaws.com.cn instead of eb.amazonaws.com.cn.
I've found this by accident, so please confirm if this commit/PR is correct before merging it.
=> Fix a subtle bug with beanstalkCnamePrefixRegexp

.changelog/24264.txt, internal/service/rds/find.go, internal/service/rds/proxy.go, internal/service/rds/proxy_data_source.go, internal/service/rds/proxy_test.go, internal/service/rds/status.go, internal/service/rds/wait.go
This PR adds the username parameter into the auth config for the RDS proxy, to match the API provided by AWS for the proxy. I have not included an acceptance test for setting the username field, as the behaviour of the API with this parameter does not support it: the API returns an error for requests setting both `username` and `auth_scheme`. Setting …
=> Issue-20146 Add username parameter to RDS proxy auth

website/docs/r/cloudwatch_event_target.html.markdown
- "setup" is "set up"
- link to cloudwatch events is outdated (not a 403, but it redirects to the base of cloudwatch events docs). Give link in the EventBridge world.
```
...
```
=> docfix: outdated link, grammar

.changelog/24296.txt, internal/service/shield/protection_group.go, internal/service/shield/protection_group_test.go
Closes https://github.com/hashicorp/terraform-provider-aws/issues/24245
```
--- PASS: TestAccShieldProtectionGroup_disappears (50.71s)
--- PASS: TestAccShieldProtectionGroup_basic (72.69s)
--- PASS: TestAccShieldProtectionGroup_members (77.52s)
--- PASS: TestAccShieldProtectionGroup_aggregation (111.73s)
--- PASS: …
```
=> r/shield_protection_group: use `protection_group_arn` parameter when updating tags

.changelog/24298.txt, internal/service/efs/file_system_data_source.go, internal/service/efs/file_system_data_source_test.go
Closes https://github.com/hashicorp/terraform-provider-aws/issues/24031
Closes https://github.com/hashicorp/terraform-provider-aws/issues/23309
Closes https://github.com/hashicorp/terraform-provider-aws/issues/21642
```
--- PASS: TestAccEFSFileSystemDataSource_nonExistent_fileSystemID (18.35s)
--- PASS: …
```
=> ds/efs_file_system: return error when filtering by tags returns results != 1

.changelog/24299.txt, internal/service/rds/instance_data_source.go
Closes https://github.com/hashicorp/terraform-provider-aws/issues/23925
```
--- PASS: TestAccRDSInstanceDataSource_basic (596.21s)
--- PASS: TestAccRDSInstanceDataSource_ec2Classic (604.27s)
```
=> data-source/db_instance: prevent panic when endpoint not available
