hashicorp/terraform-provider-aws

.changelog/24284.txt, internal/service/opensearch/domain.go, internal/service/opensearch/domain_data_source.go, internal/service/opensearch/domain_test.go
Closes #24195.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/19713.
```
$ make testacc TESTS=TestAccOpenSearchDomain_Cluster_coldStorage PKG=opensearch
TF_ACC=1 go test ./internal/service/opensearch/... -v -count 1 -parallel 20 …
```
=> F/aws opensearch domain Support for cold_storage

.changelog/24300.txt, internal/service/ssm/association_test.go, internal/service/ssm/status.go, internal/service/ssm/wait.go
Closes https://github.com/hashicorp/terraform-provider-aws/issues/23326
```
--- PASS: TestAccSSMAssociation_withOutputLocation_waitForSuccessTimeout (38.61s)
--- PASS: TestAccSSMAssociation_withDocumentVersion (31.01s)
--- PASS: TestAccSSMAssociation_withAssociationNameAndScheduleExpression (40.88s)
--- PASS: …
```
=> r/ssm_association: use the `Overview.Status` field in the custom wait function instead of the root-level `Status`

website/docs/r/emr_cluster.html.markdown
The security group is named `allow_access`, not `allow_all`
https://github.com/hashicorp/terraform-provider-aws/blob/85cb3b05cbfe40a88fe1478a6130dd687a63fbb4/website/docs/r/emr_cluster.html.markdown?plain=1#L374
Also, `cidr_blocks` should be `list(string)`
=> Fix slip on `emr_cluster` documentation

.changelog/24302.txt, internal/service/sfn/state_machine.go
Closes https://github.com/hashicorp/terraform-provider-aws/issues/22517
```
--- PASS: TestAccSFNStateMachine_tracing (84.84s)
--- PASS: TestAccSFNStateMachine_createUpdate (89.72s)
--- PASS: TestAccSFNStateMachine_expressUpdate (90.68s)
--- PASS: TestAccSFNStateMachine_tags (90.87s)
--- PASS: …
```
=> r/sfn_state_machine: prevent panic when accessing the tracing or logging config of the state machine after update

.changelog/24303.txt, internal/service/appstream/user_stack_association.go
Closes https://github.com/hashicorp/terraform-provider-aws/issues/22468
```
--- PASS: TestAccAppStreamUserStackAssociation_disappears (24.42s)
--- PASS: TestAccAppStreamUserStackAssociation_basic (28.31s)
--- PASS: TestAccAppStreamUserStackAssociation_complete (45.05s)
```
=> r/appstream_user_stack_association: prevent panic during resource read

internal/sweep/sweep_test.go
Closes #24336.
```console
% make sweep SWEEPARGS=-sweep-run=aws_opensearch_domain SWEEP=us-west-2
go test ./internal/sweep -v -tags=sweep -sweep=us-west-2 -sweep-run=aws_opensearch_domain -timeout 60m
2022/04/21 08:36:28 [DEBUG] Running Sweepers for region (us-west-2):
2022/04/21 …
```
=> Include OpenSearch service sweepers

.github/workflows/post_publish.yml, .github/workflows/release.yml
Closes #24258 
```
$ actionlint .github/workflows/release.yml .github/workflows/post_publish.yml
```
=> github/workflows: add id to step that outputs highest version tag and use diff action to fetch workflow artifact

website/docs/r/dms_endpoint.html.markdown
See the error when `json_unformatted` is used:
```
Error: expected kinesis_settings.0.message_format to be one of [json json-unformatted], got json_unformatted
```
```
...
```
=> Fix DMS documentation on kinesis_settings block.

.changelog/24222.txt, internal/service/elasticsearch/domain.go, internal/service/elasticsearch/domain_test.go, internal/service/elasticsearch/status.go, internal/service/elasticsearch/wait.go, internal/service/opensearch/domain.go, internal/service/opensearch/domain_test.go, internal/service/opensearch/status.go, internal/service/opensearch/wait.go, website/docs/r/elasticsearch_domain.html.markdown, website/docs/r/opensearch_domain.html.markdown
Closes #17330
```console
% make testacc TESTS=TestAccOpenSearchDomain_Encryption PKG=opensearch 
TF_ACC=1 go test ./internal/service/opensearch/... -v -count 1 -parallel 20 -run='TestAccOpenSearchDomain_Encryption'  -timeout 180m
--- PASS: …
```
=> es/domain: Enable encrypt w/o ForceNew

internal/service/connect/instance.go
Closes #24335
The validation for this argument is correct ([AWS Document](https://docs.aws.amazon.com/connect/latest/APIReference/API_CreateInstance.html)), but the validation message incorrectly states that underscores are valid. This PR removes the claim that underscores may be used.
=> Correct validation message for aws_connect_instance.instance_alias

.changelog/19790.txt, .changelog/20073.txt, internal/service/acm/certificate.go, internal/service/acm/certificate_data_source_test.go, internal/service/acm/certificate_test.go, internal/service/acm/certificate_validation.go, internal/service/acm/certificate_validation_test.go, website/docs/r/acm_certificate_validation.html.markdown
AWS automatically adds a SAN entry that matches the `domain_name` value. This entry
was being deleted in order to avoid spurious diffs where user's config didn't include
the `domain_name` value in `subject_alternative_names`.
This change reverses the logic so as to better reflect the actual state of a certificate
in ACM; all SANs are now tracked in Terraform …
=> resource/aws_acm_certificate: Correctly handle SAN entries that match `domain_name`

.changelog/22968.txt, internal/provider/provider.go, internal/service/athena/data_catalog.go, internal/service/athena/data_catalog_test.go, website/docs/r/athena_data_catalog.html.markdown
Relates #22714
```
$ make testacc TESTS=TestAccDataCatalog PKG=athena
TF_ACC=1 go test ./internal/service/athena/... -v -count 1 -parallel 20 -run='TestAccDataCatalog'  -timeout 180m
=== RUN   TestAccDataCatalog_basic
=== PAUSE TestAccDataCatalog_basic
=== RUN …
```
=> New Resource: aws_athena_data_catalog

website/docs/r/sqs_queue.html.markdown
👋 Hey folks,
I was reviewing the docs for `aws_sqs_queue` and noticed some un-necessary string interpolation.  Just throwing up a PR to remove it.
Let me know your thoughts.
Cheers,
Chris
=> Updating aws_sqs_queue web docs

.changelog/23734.txt, internal/service/elasticache/cluster.go, internal/service/elasticache/cluster_test.go, internal/service/elasticache/diff.go, internal/service/elasticache/engine_version.go, internal/service/elasticache/engine_version_test.go, internal/service/elasticache/global_replication_group.go, internal/service/elasticache/global_replication_group_test.go, internal/service/elasticache/replication_group.go, internal/service/elasticache/replication_group_test.go, internal/service/elasticache/validate.go, internal/service/elasticache/wait.go, website/docs/r/elasticache_cluster.html.markdown, website/docs/r/elasticache_replication_group.html.markdown
Closes #22385
```
$ make testacc TESTARGS='-run=TestAccElastiCacheCluster_EngineVersion_redis\|TestAccElastiCacheReplicationGroup_EngineVersion_update' PKG=elasticache ACCTEST_PARALLELISM=2
TF_ACC=1 go test ./internal/service/elasticache/... -v -count 1 -parallel 2 …
```
=> Fix ElastiCache Redis versioning

.changelog/24383.txt, internal/service/ses/receipt_filter.go
Closes https://github.com/hashicorp/terraform-provider-aws/issues/24378.
Add dot in validation regex for name in `aws_ses_receipt_filter` resource
=> Update validation pattern for aws_ses_receipt_filter.name 

website/docs/r/cloudwatch_dashboard.html.markdown
Closes #24355
The dashboard_name is not displayed and the sample code for import is incomplete,
and we would like to resolve this.
- Remove <> surrounding dashboard_name
Attached are the results of a local preview of the markdown file.
|before|after|
|---|---|
|![スクリーンショット 2022-04-23 15 35 …
=> fix: [CloudWatch Dashboard] import sample code

internal/service/elbv2/load_balancer.go
=> fix bug in elbv2:resourceLoadBalancerUpdate returning listener instead of load balancer

docs/contributing/prioritization.md
There was a trailing `i` at the end of the prioritization guide. This PR fixes that.
=> Remove trailing 'i' from prioritization guide

website/docs/r/secretsmanager_secret_version.html.markdown
The documentation for creating an `aws_secretsmanager_secret_version` recommends using a `variable` to store a map of key-value pairs.
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/secretsmanager_secret_version#key-value-pairs
```hcl
variable "example" {
default = {
key1 = "value1"
key2 = "value2"
}
type = map(string)
}
resource …
```
=> document how to protect sensitive variables in secretsmanager_secret_version docs

.changelog/24422.txt, internal/service/ec2/ec2_availability_zone_data_source.go, internal/service/ec2/ec2_availability_zone_data_source_test.go, internal/service/ec2/ec2_availability_zone_group.go, internal/service/ec2/ec2_availability_zone_group_test.go, internal/service/ec2/ec2_spot_instance_request_test.go, internal/service/ec2/find.go, internal/service/ec2/status.go, internal/service/ec2/wait.go, internal/service/ec2/wavelength_carrier_gateway_test.go
Closes #24391.
```console
% make testacc TESTS=TestAccEC2AvailabilityZoneGroup_ PKG=ec2
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 20 -run='TestAccEC2AvailabilityZoneGroup_'  -timeout 180m
=== RUN   TestAccEC2AvailabilityZoneGroup_optInStatus
=== …
```
=> r/aws_ec2_availability_zone_group: Prevent crash on unknown group name

website/docs/r/globalaccelerator_accelerator.html.markdown
I fixed website document of `globalaccelerator_accelerator` Import section.
We can import `globalaccelerator_accelerator` using `arn` but document say `id`。
=> docs: globalaccelerator_accelerator document refactor

.github/workflows/post_publish.yml
* noticed these jobs could run in parallel as they're not dependent on each other
```
N/A or @actionlint if available
```
=> github/workflows/post_publish: parallelize jobs that run when release workflow succeeds or on manual trigger

.changelog/13000.txt, internal/service/kms/alias.go, internal/service/kms/alias_data_source.go, internal/service/kms/validate.go, internal/service/kms/validate_test.go
Closes #12891
```release-note
fix KMS name validation check
```
```
$  make testacc TEST=./aws TESTARGS='-run=TestValidateAwsKmsName' …
```
=> fix KMS name validation check

.changelog/24453.txt, internal/service/acm/certificate_validation.go, internal/service/acm/certificate_validation_test.go
Resolves #24452.
Advice required from @mattburgess and @ewbankkit as it is relates to fixing breaking changes at #20073.
<details>
<summary>test output (isn't quite right?)</summary>
```
$ make testacc TESTS=TestAccACM PKG=acm …
```
=> fix: aws_acm_certificate_validation uses create timestamp as id for validation not certificate arn

.changelog/24469.txt, internal/service/kms/validate.go, internal/service/kms/validate_test.go
Relates https://github.com/hashicorp/terraform-provider-aws/pull/13000#issuecomment-1113033590
```
--- PASS: TestValidNameForDataSource (0.00s)
--- PASS: TestValidNameForResource (0.00s)
```
```
$ make testacc TESTARGS='-run=TestAccKMSAlias' PKG=kms …
```
=> r/aws_kms_alias: fix plan time validation's reserved prefix to `alias/aws/`

website/docs/r/instance.html.markdown
Closes  https://github.com/hashicorp/terraform-provider-aws/issues/24461
Property for auto_recovery feature in instance documentation  should be `disabled` instead of `dedicated`.
=> d/aws_instance: documentation change dedicated to disabled

website/docs/r/rds_cluster.html.markdown
Documentation update for aws_rds_cluster the serverlessv2_scaling_configuration had incorrect values for engine mode. The only valid value for ServerlessV2 is provisioned not serverlessv2.
Relates: #24363.
=> docs: updated to reflect the actual requirements. ServerlessV2 requires provisioned enginemode not serverlessv2

.changelog/24401.txt, internal/service/ssm/patch_baseline_data_source.go, internal/service/ssm/patch_baseline_data_source_test.go, website/docs/d/ssm_patch_baseline.html.markdown
Closes #24062.
```
$ make testacc PKG=ssm TESTS="TestAccSSMPatchBaselineDataSource_"
TF_ACC=1 go test ./internal/service/ssm/... -v -count 1 -parallel 20 -run='TestAccSSMPatchBaselineDataSource_'  -timeout 180m
=== RUN …
```
=> d/aws_ssm_patch_baseline - new attributes

.semgrep.yml, internal/service/lambda/flex.go, internal/service/lambda/function.go
Relates #12992
```
$ semgrep
```
=> service/lambda: updates to pass semgrep rule `prefer-aws-go-sdk-pointer-conversion-assignment`

.semgrep.yml, internal/service/rds/security_group.go
Relates #12992
```
$ semgrep
```
=> r/rds_security_group: updates to pass semgrep rule `prefer-aws-go-sdk-pointer-conversion-assignment`

.semgrep.yml, internal/service/servicediscovery/service.go
Relates #12992
```
semgrep
```
```
$make testacc …
```
=> r/servicediscovery_service: updates for semgrep rule `prefer-aws-go-sdk-pointer-conversion-assignment`

.semgrep.yml, internal/service/route53/flex.go
Relates #12992
```
$ semgrep
```
```
make testacc …
```
=> r/route53_record: updates to pass semgrep rule `prefer-aws-go-sdk-pointer-conversion-assignment`

.semgrep.yml, internal/service/ssm/association.go, internal/service/ssm/document.go, internal/service/ssm/flex.go, internal/service/ssm/resource_data_sync.go, internal/service/ssm/resource_data_sync_test.go
Relates https://github.com/hashicorp/terraform-provider-aws/issues/12992
```
$ semgrep
ran 31 rules …
```
=> service/ssm: updates for semgrep rule `prefer-aws-go-sdk-pointer-conversion-assignment`

.semgrep.yml, internal/service/s3/bucket_analytics_configuration.go, internal/service/s3/bucket_metric.go, internal/service/s3/bucket_metric_test.go, internal/service/s3/bucket_notification.go
Relates #12992
```
$ semgrep
```
```
$ make testacc …
```
=> service/s3: updates to pass semgrep rule `prefer-aws-go-sdk-pointer-conversion-assignment`

.semgrep.yml, internal/service/redshift/flex.go
Relates #12992
```
$ semgrep
```
=> service/redshift: updates to pass semgrep rule `prefer-aws-go-sdk-pointer-conversion-assignment`

.semgrep.yml, internal/service/opsworks/application.go, internal/service/opsworks/application_test.go, internal/service/opsworks/consts.go, internal/service/opsworks/instance.go, internal/service/opsworks/instance_test.go, internal/service/opsworks/layers.go, internal/service/opsworks/stack.go, internal/service/opsworks/status.go, internal/service/opsworks/wait.go
Relates #12992
```
$  semgrep
```
```
make testacc …
```
=> service/opworks: updates to pass semgrep rule `prefer-aws-go-sdk-pointer-conversion-assignment`

.semgrep.yml, internal/service/dax/cluster.go, internal/service/dax/parameter_group.go
Relates: #12992.
Fixes:
```
Findings:
internal/service/dax/cluster.go 
prefer-aws-go-sdk-pointer-conversion-conditional
Prefer AWS Go SDK pointer conversion functions for dereferencing during conditionals, e.g.
aws.StringValue()
350┆ if *c.NotificationConfiguration.TopicStatus == "active" {
⋮┆----------------------------------------
518┆ *b[i].NodeId < …
```
=> Fix DAX semgrep `prefer-aws-go-sdk-pointer-conversion-conditional` errors

.semgrep.yml, internal/service/iam/server_certificate.go, internal/service/iam/user_ssh_key.go
Relates #12992
Areas to fix:
```
semgrep
internal/service/iam/server_certificate.go
prefer-aws-go-sdk-pointer-conversion-assignment …
```
=> service/iam: updates to pass semgrep rule `prefer-aws-go-sdk-pointer-conversion-assignment`

.semgrep.yml, internal/service/gamelift/alias.go
Relates #12992
Areas to fix:
```
semgrep
Scanning 2346 files with 30 go rules.
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████|2346/2346 tasks
Findings:
internal/service/gamelift/alias.go …
```
=> r/gamelift_alias: updates to pass semgrep rule `prefer-aws-go-sdk-pointer-conversion-assignment`

.semgrep.yml, internal/service/elb/flex.go
Relates #12992
Areas to fix:
```
Findings:
internal/service/elb/flex.go
prefer-aws-go-sdk-pointer-conversion-assignment
Prefer AWS Go SDK pointer conversion functions for dereferencing during assignment, e.g.
aws.StringValue()
22┆ r["bucket"] = *l.S3BucketName
⋮┆----------------------------------------
26┆ r["bucket_prefix"] = *l.S3BucketPrefix …
```
=> service/elb: updates to pass semgrep rule `prefer-aws-go-sdk-pointer-conversion-assignment`

internal/service/ec2/vpc_security_group_test.go, website/docs/r/security_group.html.markdown
1. Added a new Acceptance Test to make sure that user can change `name` or `name-prefix` arguments to Security Group resource when they specify `create_before_destroy = true` property.
2. Extended Security Group documentation to provide this use-case as example. 
Closes #23708
```
$ make testacc …
```
=> doc and test of security_group for change name use-case

.changelog/24514.txt, CHANGELOG.md, internal/generate/namevaluesfilters/generators/servicefilters/main.go, internal/generate/namevaluesfilters/service_filters_gen.go, internal/generate/namevaluesfilters/service_generation_customizations.go, internal/provider/provider.go, internal/service/secretsmanager/secrets_data_source.go, internal/service/secretsmanager/secrets_data_source_test.go, website/docs/d/secretsmanager_secrets.html.markdown
Closes #24421.
```
$ make testacc PKG=secretsmanager TESTS="TestAccSecretsManagerSecretsDataSource_filter"
TF_ACC=1 go test ./internal/service/secretsmanager/... -v -count 1 -parallel 20 -run='TestAccSecretsManagerSecretsDataSource_filter'  -timeout 180m
=== RUN …
```
=> d/aws_secretsmanager_secrets - new data source

.github/workflows/README.md, .github/workflows/acctest-terraform-lint.yml, .github/workflows/examples.yml, .github/workflows/lock.yml, .github/workflows/release.yml, .github/workflows/website.yml, .github/workflows/workflow-lint.yml, GNUmakefile, tools/go.mod, tools/go.sum, tools/main.go
Closes #24249 
```
$ make gh-workflows-lint <-- should not report errors
```
=> Add GNUMakefile directive for linting github workflow files and add new workflow 

internal/service/apigatewayv2/route.go, internal/service/apigatewayv2/stage.go
=> apigatewayv2: Remove service from funcs

internal/service/appconfig/application_test.go, internal/service/appconfig/configuration_profile.go, internal/service/appconfig/configuration_profile_test.go, internal/service/appconfig/deployment_strategy_test.go, internal/service/appconfig/deployment_test.go, internal/service/appconfig/environment.go, internal/service/appconfig/environment_test.go, internal/service/appconfig/hosted_configuration_version_test.go
=> appconfig: Remove service from funcs

internal/service/acmpca/certificate.go, internal/service/acmpca/certificate_authority.go, internal/service/acmpca/certificate_authority_data_source.go, internal/service/acmpca/certificate_authority_migrate.go, internal/service/acmpca/certificate_test.go
=> acmpca: Remove service from funcs

internal/service/appstream/fleet_test.go, internal/service/appstream/image_builder.go
=> appstream: Remove service from funcs

.semgrep.yml, internal/service/ec2/ec2_eip.go, internal/service/ec2/ec2_instance.go, internal/service/ec2/ec2_spot_datafeed_subscription.go, internal/service/ec2/ec2_spot_instance_request.go, internal/service/ec2/flex.go, internal/service/ec2/vpc_route_table_data_source.go, internal/service/ec2/vpc_security_group.go, internal/service/ec2/vpc_security_group_rule.go
Relates #12992
```
make testacc TESTARGS='-run=TestAccEC2EIP_\|TestAccEC2Instance_\|TestAccEC2SpotDatafeedSubscription_\|TestAccEC2SpotInstanceRequest_\|TestAccEC2RouteTableDataSource_\|TestAccEC2SecurityGroup_\|TestAccEC2SecurityGroupRule_' PKG=ec2 ACCTEST_PARALLELISM=3 …
```
=> service/ec2: updates to pass semgrep rule `prefer-aws-go-sdk-pointer-conversion-assignment`

.changelog/24537.txt, internal/service/cloudfront/distribution.go, internal/service/cloudfront/distribution_test.go
Amazon's docs say to fetch the ETag immediately before updating to ensure it is up to date. This fix only updates it if the PreconditonFailed error occurs and tries again, since it seems AWS fails fast if the ETag is incorrect.
https://docs.aws.amazon.com/cloudfront/latest/APIReference/API_UpdateDistribution.html
From my findings, CloudFront redeploys the distribution automatically when something it depends on (like a Response Header Policy) changes, creating a new ETag variable. Fair enough, but not really conducive to having a state file with a value that can be modified by an external resource. IMO the ETag shouldn't be stored in the state at all because of this, but for simple distributions that have no external resources having the ETag can in theory speed things up, as long as all …
=> b/fix PreconditionFailed errors on aws_cloudfront_distribution

.changelog/24530.txt, internal/service/ssm/document.go
Closes #21725
```
make testacc TESTS=TestAccSSMDocument_package PKG=ssm
TF_ACC=1 go test ./internal/service/ssm/... -v -count 1 -parallel 20 -run='TestAccSSMDocument_package'  -timeout 180m
=== RUN   TestAccSSMDocument_package
=== PAUSE TestAccSSMDocument_package
=== …
```
=> Always include AttachmentsSources when updating SSM documents

internal/service/appmesh/flex.go, internal/service/appmesh/gateway_route.go, internal/service/appmesh/gateway_route_test.go, internal/service/appmesh/mesh.go, internal/service/appmesh/mesh_data_source.go, internal/service/appmesh/mesh_data_source_test.go, internal/service/appmesh/mesh_test.go, internal/service/appmesh/route.go, internal/service/appmesh/route_test.go, internal/service/appmesh/virtual_gateway.go, internal/service/appmesh/virtual_gateway_test.go, internal/service/appmesh/virtual_node.go, internal/service/appmesh/virtual_node_migrate.go, internal/service/appmesh/virtual_node_test.go, internal/service/appmesh/virtual_router.go, internal/service/appmesh/virtual_router_migrate.go, internal/service/appmesh/virtual_router_test.go, internal/service/appmesh/virtual_service.go, internal/service/appmesh/virtual_service_data_source.go, internal/service/appmesh/virtual_service_data_source_test.go, internal/service/appmesh/virtual_service_test.go
=> appmesh: Remove service from funcs

internal/service/autoscaling/group.go, internal/service/autoscaling/group_data_source.go, internal/service/autoscaling/group_data_source_test.go, internal/service/autoscaling/group_tag_test.go, internal/service/autoscaling/group_test.go, internal/service/autoscaling/groups_data_source_test.go, internal/service/autoscaling/policy_test.go
=> autoscaling: Remove service from funcs

.changelog/24541.txt, internal/conns/config.go, internal/service/ecs/wait.go
Relates https://github.com/hashicorp/terraform-provider-aws/issues/20452#issuecomment-1117386281
```
make testacc TESTARGS='-run=TestAccECSService_' PKG=ecs ACCTEST_PARALLELISM=5
TF_ACC=1 go test ./internal/service/ecs/... -v -count 1 -parallel 5 …
```
=> r/ecs_service: retry `WaitUntilServicesStable` up to 3 times within resource instead of client connection

.changelog/24579.txt, internal/service/ec2/ec2_launch_template.go, internal/service/ec2/ec2_launch_template_test.go
Closes #24575.
```console
% make testacc TESTS=TestAccEC2LaunchTemplate_licenseSpecification PKG=ec2
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 20 -run='TestAccEC2LaunchTemplate_licenseSpecification'  -timeout 180m
=== RUN   TestAccEC2LaunchTemplate_licenseSpecification
=== …
```
=> r/aws_launch_template: Fix crash in `TestAccEC2LaunchTemplate_licenseSpecification`

.semgrep.yml, internal/service/redshift/security_group.go, internal/service/redshift/snapshot_schedule_association.go
Relates: https://github.com/hashicorp/terraform-provider-aws/issues/12992.
Fixes:
```
Findings:
internal/service/redshift/security_group.go 
prefer-aws-go-sdk-pointer-conversion-conditional
Prefer AWS Go SDK pointer conversion functions for dereferencing during conditionals, e.g.
aws.StringValue()
244┆ *resp.ClusterSecurityGroups[0].ClusterSecurityGroupName …
```
=> Fix Redshift semgrep `prefer-aws-go-sdk-pointer-conversion-conditional` errors

internal/service/efs/access_point.go, internal/service/efs/access_point_data_source.go, internal/service/efs/access_point_data_source_test.go, internal/service/efs/access_point_test.go, internal/service/efs/access_points_data_source_test.go, internal/service/efs/backup_policy.go, internal/service/efs/backup_policy_test.go, internal/service/efs/file_system.go, internal/service/efs/file_system_data_source.go, internal/service/efs/file_system_data_source_test.go, internal/service/efs/file_system_policy_test.go, internal/service/efs/file_system_test.go, internal/service/efs/mount_target_test.go
=> efs: Remove service from funcs

.semgrep.yml, internal/service/elasticache/cluster.go, internal/service/elasticache/security_group.go, internal/service/elasticache/subnet_group.go
Relates: https://github.com/hashicorp/terraform-provider-aws/issues/12992.
Fixes:
```
Findings:
internal/service/elasticache/cluster.go 
prefer-aws-go-sdk-pointer-conversion-conditional
Prefer AWS Go SDK pointer conversion functions for dereferencing during conditionals, e.g.
aws.StringValue()
491┆ if *c.NotificationConfiguration.TopicStatus == "active" { …
```
=> Fix ElastiCache semgrep `prefer-aws-go-sdk-pointer-conversion-conditional` errors

.changelog/24685.txt, internal/service/ec2/vpc_default_subnet.go, internal/service/ec2/vpc_subnet.go
Closes #24681
```
$ TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 2 -run=TestAccVPCSubnet -timeout 180m …
```
=> Fixes aws_subnet on creation improperly handling IPv6 CIDR pending association state

.semgrep.yml, internal/service/cloudformation/stack.go, internal/service/cloudfront/distribution_configuration_structure.go, internal/service/dax/cluster.go, internal/service/directconnect/bgp_peer_test.go, internal/service/ec2/vpc_security_group_rule_test.go, internal/service/elasticache/cluster.go, internal/service/elb/backend_server_policy.go, internal/service/elb/listener_policy.go, internal/service/opsworks/layers.go
Relates #12992.
```console
% make testacc TESTARGS='-run=TestAccCloudFormationStack_allAttributes\|TestAccCloudFormationStack_basic' PKG=cloudformation
TF_ACC=1 go test ./internal/service/cloudformation/... -v -count 1 -parallel 20  -run=TestAccCloudFormationStack_allAttributes\|TestAccCloudFormationS …
```
=> Tech debt: Prefer AWS Go SDK pointer conversion functions for dereferencing when converting int64 to int

.changelog/24687.txt, internal/service/rds/cluster_parameter_group.go, internal/service/rds/cluster_parameter_group_test.go
Reference: #9574
Reference: #12052
Use the shared naming module to match the name and the
prefix. Acceptance tests were updated to test the import.
```
make testacc TESTS=TestAccRDSClusterParameterGroup_ PKG=rds
TF_ACC=1 go test ./internal/service/rds/... -v -count 1 …
```
=> rds: Import `name_prefix` for `aws_rds_cluster_parameter_group`

.changelog/24693.txt, internal/provider/provider.go, internal/service/location/map.go, internal/service/location/map_data_source.go, internal/service/location/map_data_source_test.go, website/docs/d/location_map.html.markdown, website/docs/r/location_map.html.markdown
```
$ make testacc PKG=location TESTS="TestAccLocationMap_|TestAccLocationMapDataSource_"
TF_ACC=1 go test ./internal/service/location/... -v -count 1 -parallel 20 -run='TestAccLocationMap_|TestAccLocationMapDataSource_'  -timeout 180m
=== RUN …
```
=> d/aws_location_map - new data source

.changelog/24691.txt, internal/service/autoscaling/group_data_source.go, internal/service/autoscaling/group_data_source_test.go, website/docs/d/autoscaling_group.html.markdown
```
$ make testacc TESTS=TestAccAutoScalingGroupDataSource_ PKG=autoscaling
TF_ACC=1 go test ./internal/service/autoscaling/... -v -count 1 -parallel 20 -run='TestAccAutoScalingGroupDataSource_'  -timeout 180m
=== RUN   TestAccAutoScalingGroupDataSource_basic
=== PAUSE …
```
=> Add enabled_metrics to aws_autoscaling_group data source

.changelog/24697.txt, internal/service/kms/key.go, internal/service/kms/key_test.go
Relates OR Closes #24696 
This PR proposes to retry KMS policy updates when a `MalformedPolicyDocumentException` occurs. The intention is to avoid failing when a KMS policy reference IAM resources that get created at the same time.
```
$ make testacc TESTS=TestAccKMSKey_Policy PKG=kms …
```
=> Add retry on `MalformedPolicyDocumentException` to wait for IAM propagation on KMS policy update

.changelog/23768.txt, internal/service/elbv2/listener_rule.go, internal/service/elbv2/listener_rule_test.go
Dont recreate listener rule after priority change
It is possible to update the priority without recreating the rule, which is preferred of course. See [docs](https://docs.aws.amazon.com/elasticloadbalancing/latest/APIReference/API_SetRulePriorities.html).
Release Notes:
```release-note:note
resource/aws_alb_listener_rule: Don't force recreate listener rule on priority change. 
```
Acceptance Tests:
```
$ make testacc TESTS=.+updateRulePriority PKG=elbv2
TF_ACC=1 go test ./internal/service/elbv2/... -v -count 1 -parallel 20 -run='.+updateRulePriority'  -timeout 180m
=== RUN   TestAccELBV2ListenerRule_updateRulePriority
=== PAUSE TestAccELBV2ListenerRule_updateRulePriority
=== CONT  TestAccELBV2ListenerRule_updateRulePriority
--- …
```
=> Dont recreate listener rule after priority change

internal/acctest/acctest.go, internal/service/autoscaling/policy.go, internal/service/sagemaker/app_image_config.go, internal/service/transfer/server.go, internal/service/transfer/workflow.go
Relates https://github.com/hashicorp/terraform-provider-aws/pull/24718.
Fixes:
```console
% make golangci-lint 
==> Checking source code with golangci-lint...
internal/acctest/acctest.go:615:4: S1038: should use t.Skipf(...) instead of t.Skip(fmt.Sprintf(...)) (gosimple)
t.Skip(fmt.Sprintf("skipping tests; partition %s does not support %s service", …
```
=> Fix `golangci-lint` errors

.changelog/24708.txt, internal/service/imagebuilder/image_recipe.go, internal/service/imagebuilder/image_recipe_test.go
Closes #22127
```
$ make testacc TESTS=TestAccImageRecipe_ PKG=imagebuilder
TF_ACC=1 go test ./internal/service/imagebuilder/... -v -count 1 -parallel 20 -run='TestAccImageRecipe_'  -timeout 180m
=== RUN   TestAccImageRecipe_basic
=== PAUSE TestAccImageRecipe_basic
=== …
```
=> r/aws_imagebuilder_image_recipe: `ForceNew` resource on updates

.changelog/24745.txt, .semgrep.yml, internal/service/autoscaling/notification.go, internal/service/ec2/ebs_volume.go, internal/service/ec2/ebs_volume_attachment.go, internal/service/ec2/ebs_volume_attachment_test.go, internal/service/ec2/ebs_volume_test.go, internal/service/ec2/errors.go, internal/service/ec2/find.go, internal/service/ec2/status.go, internal/service/ec2/wait.go, website/docs/r/ebs_volume.html.markdown
Closes https://github.com/hashicorp/terraform-provider-aws/issues/12987.
Closes https://github.com/hashicorp/terraform-provider-aws/issues/8349.
Fixes:
```console
% semgrep --config .semgrep.yml 
Scanning 3906 files.
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████|3906/3906 tasks …
```
=> Tech debt: Prefer `(*awserr.Error)` instead of `(*awserr.Error).Code()` / `(*awserr.Error).Message()` in `fmt.Errorf()`

website/docs/r/grafana_workspace.html.markdown
Closes #24753
The list of supported values for `aws_grafana_dashboard.data_sources` was out of date. This PR aims to bring it back to reality. Also alphabetized the list while I was at it.
- [`data_source` validation](https://github.com/hashicorp/terraform-provider-aws/blob/f83ba5a0f32717879115a45f3ea78544686803f8/int …
=> [Docs] Add additional services to grafana_workspace.data_sources

website/docs/r/synthetics_canary.html.markdown
Closes #24744
The docs incorrectly state the accepted values for `aws_synthetics_canary.artifact_config.s3_encryption.encryption_mode` were `SSE-S3` and `SSE-KMS`, when they are indeed `SSE_S3` and `SSE_KMS`. 
- [argument validation](https://github.com/hashicorp/terraform-provider-aws/blob/f83ba5a0f32717879115a45f3ea7 …
=> Correct aws_synthetics_canary encryption_mode argument documentation

.changelog/24758.txt, internal/service/servicecatalog/provisioned_product.go, internal/service/servicecatalog/provisioned_product_test.go, internal/service/servicecatalog/wait.go
Closes https://github.com/hashicorp/terraform-provider-aws/issues/24574
```
make testacc TESTARGS='-run=TestAccServiceCatalogProvisionedProduct_' PKG=servicecatalog
TF_ACC=1 go test ./internal/service/servicecatalog/... -v -count 1 -parallel 20 …
```
=> r/servicecatalog_provisioned_product: remove waiter from read CRUD op to prevent irreversible state

.changelog/24593.txt, internal/service/acm/certificate_data_source.go, internal/service/acm/certificate_data_source_test.go, website/docs/d/acm_certificate.html.markdown
=> Allow AWS Provider ACM Certificate Data Source to Return TLS Certificate Material

internal/service/waf/ipset_test.go, internal/service/waf/rule.go, internal/service/wafregional/ipset_test.go, internal/service/wafregional/web_acl_association_test.go, internal/service/wafv2/web_acl_association.go, internal/service/workspaces/status.go
=> waf: Clean up const, func names

internal/service/storagegateway/cache_test.go, internal/service/storagegateway/cached_iscsi_volume_test.go, internal/service/storagegateway/status.go, internal/service/storagegateway/upload_buffer_test.go, internal/service/storagegateway/wait.go, internal/service/storagegateway/working_storage_test.go
=> storagegateway: Clean up const, func names

internal/service/s3/bucket_analytics_configuration_test.go, internal/service/s3/bucket_metric_test.go, internal/service/s3/bucket_object.go, internal/service/s3/bucket_policy_data_source_test.go, internal/service/s3/object.go, internal/service/s3control/bucket.go, internal/service/sqs/queue.go, internal/service/sqs/queue_policy.go, internal/service/wafregional/web_acl_association_test.go
=> s3: Clean up const, var, func names

internal/service/route53/health_check_test.go, internal/service/route53/record_test.go, internal/service/route53/traffic_policy_document_model.go, internal/service/route53recoverycontrolconfig/wait.go, internal/service/route53resolver/rule_test.go
=> route53: Clean up names

internal/service/opsworks/layers.go, internal/service/organizations/organization.go, internal/service/organizations/organization_data_source_test.go, internal/service/organizations/organization_test.go, internal/service/organizations/organizations_test.go, internal/service/organizations/policy_test.go, internal/service/outposts/outposts_data_source.go, internal/service/outposts/outposts_data_source_test.go, internal/service/outposts/sites_data_source_test.go, internal/service/quicksight/data_source_test.go, internal/service/rds/parameter_group_test.go
=> opqr: Remove aws from names

.changelog/24688.txt, internal/service/elasticache/replication_group.go
Due to a recent change in the AWS API, `aws_elasticache_replication_group`s which were secondary members of a global replication group were returning a perpetual diff for `auto_minor_version_upgrade`.
```
$ make testacc PKG=elasticache PKG=elasticache TESTS=TestAccElastiCacheReplicationGroup
--- PASS: TestAccElastiCacheReplicationGroup_Validation_noNodeType (60.27s)
--- PASS: TestAccElastiCacheReplicationGroup_dataTiering (766.53s)
--- PASS: TestAccElastiCacheReplicationGroup_autoMinorVersionUpgrade (888.84s)
--- PASS: TestAccElastiCacheReplicationGroup_finalSnapshot (1287.60s)
--- PASS: TestAccElastiCacheReplicationGroup_tags (1379.46s)
--- PASS: TestAccElastiCacheReplicationGroup_Validation_globalReplicationGroupIdAndNodeType (1387.13s)
--- PASS: …
```
=> resource/aws_elasticache_replication_group: Fix perpetual diff for Global Replication Group members

website/docs/r/waf_web_acl.html.markdown
Closes #24812
Currently, the documentation for `aws_waf_web_acl.default_action` incorrectly states that `COUNT` is a valid option. This PR removes this, as it's invalid.
- Resource [uses `waf.CreateWebACL`](https://github.com/hashicorp/terraform-provider-aws/blob/3e72775d073cb3e0e5e765e36121bf4384f16a66/internal/servi …
=> aws_waf_web_acl: Remove COUNT from default_action allowed values list

.changelog/24767.txt, internal/service/kafka/cluster.go, internal/service/kafka/cluster_test.go, website/docs/r/msk_cluster.html.markdown
Closes #24464
```
$  make testacc TESTARGS='-run=TestAccKafkaCluster_BrokerNodeGroupInfo_modifyEbsVolume\|TestAccKafkaCluster_BrokerNodeGroupInfo_storageInfo\|TestAccKafkaCluster_BrokerNodeGroupInfo_ebsVolumeSize' PKG=kafka
TF_ACC=1 go test ./internal/service/kafka/... …
```
=> r/aws_msk_cluster - new storage_info arg

.changelog/24582.txt, internal/service/route53resolver/rules_data_source.go, internal/service/route53resolver/rules_data_source_test.go, website/docs/d/route53_resolver_rules.html.markdown
Add new `name_regex` filter argument for `aws_route53_resolver_rules` datasource. Given this isn't supported natively by [AWS API](https://docs.aws.amazon.com/Route53/latest/APIReference/API_route53resolver_Filter.html), filtering is performed locally after retrieving results from the API.
```
❯ make testacc …
```
=> d/aws_route53_resolver_rules: add new name_regex filter argument

.semgrep-service-name.yml, internal/service/elbv2/hosted_zone_id_data_source_test.go
=> semgrep: New naming rules

.changelog/24199.txt, internal/service/s3/bucket_website_configuration.go, internal/service/s3/bucket_website_configuration_test.go, website/docs/r/s3_bucket_website_configuration.html.markdown
Relates https://github.com/hashicorp/terraform-provider-aws/issues/24048
Relates https://github.com/hashicorp/terraform-provider-aws/pull/24198
```
$ make testacc TESTARGS='-run=TestAccS3BucketWebsiteConfiguration_RoutingRule' PKG=s3 ACCTEST_PARALLELISM=5
TF_ACC=1 go …
```
=> r/s3_bucket_website_configuration: backport "add `routing_rules` parameter to assist in configuring rules with empty string values"

internal/service/networkmanager/core_network_policy_document_data_source.go
```
❯ make testacc TESTS=TestAccNetworkManagerCoreNetworkPolicyDocument PKG=networkmanager
TF_ACC=1 go test ./internal/service/networkmanager/... -v -count 1 -parallel 20 -run='TestAccNetworkManagerCoreNetworkPolicyDocument'  -timeout 180m
=== RUN …
```
=> Remove integer constant causing overflow on BSD `go-releaser` build

.changelog/24899.txt, internal/service/organizations/account.go, internal/service/organizations/account_test.go, internal/service/organizations/organizations_test.go
Relates OR Closes #24897
During every account read (also of existing accounts) the create account status is read here
https://github.com/hashicorp/terraform-provider-aws/blob/5b2d3d9aa24ab96f83498f2f0aca44a7b77148c6/internal/service/organizations/account.go#L199
which calls the following SDK function …
=> Fix reading existing organizations accounts

.changelog/24821.txt, internal/provider/provider.go, internal/service/location/place_index.go, internal/service/location/place_index_test.go, website/docs/r/location_place_index.html.markdown
```
$ make testacc PKG=location TESTS="TestAccLocationPlaceIndex_"    
TF_ACC=1 go test ./internal/service/location/... -v -count 1 -parallel 20 -run='TestAccLocationPlaceIndex_'  -timeout 180m
=== RUN   TestAccLocationPlaceIndex_basic
=== PAUSE …
```
=> r/aws_location_place_index - new resource

.changelog/24856.txt, internal/service/redshift/cluster.go, internal/service/redshift/cluster_data_source.go, internal/service/redshift/cluster_test.go, internal/service/redshift/status.go, internal/service/redshift/wait.go, website/docs/d/redshift_cluster.html.markdown, website/docs/r/redshift_cluster.html.markdown
Closes #18869
```
$ make testacc TESTS=TestAccRedshiftCluster_aqua PKG=redshift
--- PASS: TestAccRedshiftCluster_aqua (550.51s)
--- PASS: TestAccRedshiftCluster_basic (249.70s)
```
=> r/redshift_cluster - add `aqua_configuration_status` argument

24882.txt, internal/service/cloudwatch/metric_stream.go, internal/service/cloudwatch/metric_stream_test.go, website/docs/r/cloudwatch_metric_stream.html.markdown
AWS CloudWatch Metric Streams recently added support for streaming additional statistics of metrics: https://aws.amazon.com/about-aws/whats-new/2022/04/amazon-cloudwatch-metric-streams-additional-statistics/
This PR adds support for this new feature by implementing the `statistics_configurations` field and it's nested fields for Metric Stream resources.
Closes #24716.
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize …
=> r/aws_cloudwatch_metric_stream support statistics_configurations resource

.semgrep-service-name0.yml, internal/service/route53resolver/endpoint_data_source_test.go, internal/service/route53resolver/rule_data_source_test.go, internal/service/route53resolver/rules_data_source_test.go
=> route53resolver: Fix test configs names

.semgrep-service-name0.yml, internal/service/serverlessrepo/application_data_source_test.go, internal/service/serverlessrepo/cloudformation_stack_test.go
=> serverlessrepo: Fix test configs names

.semgrep-service-name0.yml, internal/acctest/provider_test.go
=> acctest: Fix test config names

.semgrep-service-name0.yml, internal/service/synthetics/canary_test.go
=> synthetics: Fix test config names

internal/service/route53/health_check_test.go, internal/service/route53/hosted_zone_dnssec_test.go, internal/service/route53/key_signing_key_test.go, internal/service/route53/query_log_test.go, internal/service/route53/record_test.go, internal/service/route53/traffic_policy_document_data_source_test.go, internal/service/route53/traffic_policy_instance_test.go, internal/service/route53/traffic_policy_test.go, internal/service/route53/zone_data_source_test.go
=> route53: Fix test configs names

.semgrep-service-name0.yml, internal/service/appautoscaling/policy_test.go, internal/service/sqs/queue_data_source_test.go, internal/service/sqs/queue_policy_test.go, internal/service/sqs/queue_test.go
=> sqs: Fix test configs names

.semgrep-service-name0.yml, internal/service/pinpoint/app_test.go, internal/service/pinpoint/email_channel_test.go
=> pinpoint: Fix test configs names

.semgrep-service-name0.yml, internal/service/redshift/authentication_profile_test.go, internal/service/redshift/cluster_data_source_test.go, internal/service/redshift/cluster_test.go, internal/service/redshift/event_subscription_test.go, internal/service/redshift/orderable_cluster_data_source_test.go, internal/service/redshift/parameter_group_test.go, internal/service/redshift/scheduled_action_test.go, internal/service/redshift/service_account_data_source_test.go, internal/service/redshift/snapshot_copy_grant_test.go, internal/service/redshift/snapshot_schedule_association_test.go, internal/service/redshift/snapshot_schedule_test.go, internal/service/redshift/subnet_group_test.go, internal/service/redshift/usage_limit_test.go
=> redshift: Fix test configs names

.semgrep-service-name0.yml, internal/service/sagemaker/app_image_config_test.go, internal/service/sagemaker/app_test.go, internal/service/sagemaker/code_repository_test.go, internal/service/sagemaker/device_fleet_test.go, internal/service/sagemaker/device_test.go, internal/service/sagemaker/domain_test.go, internal/service/sagemaker/endpoint_configuration_test.go, internal/service/sagemaker/endpoint_test.go, internal/service/sagemaker/feature_group_test.go, internal/service/sagemaker/flow_definition_test.go, internal/service/sagemaker/human_task_ui_test.go, internal/service/sagemaker/image_test.go, internal/service/sagemaker/image_version_test.go, internal/service/sagemaker/model_package_group_policy_test.go, internal/service/sagemaker/model_package_group_test.go, internal/service/sagemaker/model_test.go, internal/service/sagemaker/notebook_instance_lifecycle_configuration_test.go, internal/service/sagemaker/notebook_instance_test.go, internal/service/sagemaker/prebuilt_ecr_image_data_source_test.go, internal/service/sagemaker/project_test.go, internal/service/sagemaker/studio_lifecycle_config_test.go, internal/service/sagemaker/user_profile_test.go, internal/service/sagemaker/workforce_test.go, internal/service/sagemaker/workteam_test.go
=> sagemaker: Fix test configs names

.semgrep-service-name0.yml, internal/service/qldb/ledger_data_source_test.go, internal/service/qldb/ledger_test.go, internal/service/qldb/stream_test.go
=> qldb: Fix test configs names

.semgrep-service-name0.yml, internal/service/opensearch/domain_data_source_test.go, internal/service/opensearch/domain_policy_test.go, internal/service/opensearch/domain_saml_options_test.go, internal/service/opensearch/domain_test.go
=> opensearch: Fix test configs names

.semgrep-service-name0.yml, internal/service/location/map_data_source_test.go, internal/service/location/map_test.go, internal/service/location/place_index_test.go
=> location: Fix test configs names

.semgrep-service-name0.yml, internal/service/neptune/cluster_endpoint_test.go, internal/service/neptune/cluster_instance_test.go, internal/service/neptune/cluster_parameter_group_test.go, internal/service/neptune/cluster_snapshot_test.go, internal/service/neptune/cluster_test.go, internal/service/neptune/engine_version_data_source_test.go, internal/service/neptune/event_subscription_test.go, internal/service/neptune/orderable_db_instance_data_source_test.go, internal/service/neptune/parameter_group_test.go
=> neptune: Fix test configs names

.semgrep-service-name0.yml, internal/service/keyspaces/keyspace_test.go, internal/service/keyspaces/table_test.go
=> keyspaces: Fix test configs names

.semgrep-service-name0.yml, internal/service/memorydb/acl_data_source_test.go, internal/service/memorydb/acl_test.go, internal/service/memorydb/cluster_data_source_test.go, internal/service/memorydb/cluster_test.go, internal/service/memorydb/parameter_group_data_source_test.go, internal/service/memorydb/parameter_group_test.go, internal/service/memorydb/snapshot_data_source_test.go, internal/service/memorydb/snapshot_test.go, internal/service/memorydb/subnet_group_data_source_test.go, internal/service/memorydb/subnet_group_test.go, internal/service/memorydb/user_data_source_test.go, internal/service/memorydb/user_test.go
=> memorydb: Fix test configs names

.github/goreleaser-cross-compiler-test.yml, .github/workflows/goreleaser-ci.yml
Relates https://github.com/hashicorp/terraform-provider-aws/issues/8988
Relates #24937 
Relates https://github.com/hashicorp/terraform-provider-aws/pull/24890
Output from goreleaser is using the 614939c70bfa212bc105cf0b9f4e8762fbd431a1 commit for testing:
```
$ goreleaser build --config .github/goreleaser-cross-compiler-test.yml --id 32-bit-arch --snapshot …
```
=> github/workflows: reinstate goreleaser check and build for a single 32-bit arch

website/docs/r/ecs_cluster.html.markdown
This PR fixes a grammar mistake on the `aws_ecs_cluster` page.
=> Fix grammar mistake on the aws_ecs_cluster

.semgrep-service-name0.yml, internal/service/glue/catalog_database_test.go, internal/service/glue/catalog_table_test.go, internal/service/glue/classifier_test.go, internal/service/glue/connection_data_source_test.go, internal/service/glue/connection_test.go, internal/service/glue/crawler_test.go, internal/service/glue/data_catalog_encryption_settings_data_source_test.go, internal/service/glue/data_catalog_encryption_settings_test.go, internal/service/glue/dev_endpoint_test.go, internal/service/glue/job_test.go, internal/service/glue/ml_transform_test.go, internal/service/glue/registry_test.go, internal/service/glue/resource_policy_test.go, internal/service/glue/schema_test.go, internal/service/glue/script_data_source_test.go, internal/service/glue/security_configuration_test.go, internal/service/glue/trigger_test.go, internal/service/glue/workflow_test.go
=> glue: Fix test configs names

.semgrep-service-name0.yml, internal/service/mwaa/environment_test.go
- mwaa: Fix test configs names
- mwaa: Clean up test configs
```
...
```
=> mwaa: Fix test configs names

.semgrep-service-name0.yml, internal/service/kms/alias_data_source_test.go, internal/service/kms/alias_test.go, internal/service/kms/ciphertext_data_source_test.go, internal/service/kms/ciphertext_test.go, internal/service/kms/external_key_test.go, internal/service/kms/grant_test.go, internal/service/kms/key_data_source_test.go, internal/service/kms/key_test.go, internal/service/kms/public_key_data_source_test.go, internal/service/kms/replica_external_key_test.go, internal/service/kms/replica_key_test.go, internal/service/kms/secret_data_source_test.go, internal/service/kms/secrets_data_source_test.go
- kms: Fix test configs names
- kms: Fix test configs
```
...
```
=> kms: Fix test configs names

.semgrep-service-name0.yml, internal/service/kms/grant_test.go, internal/service/ses/active_receipt_rule_set_data_source_test.go, internal/service/ses/active_receipt_rule_set_test.go, internal/service/ses/configuration_set_test.go, internal/service/ses/domain_dkim_test.go, internal/service/ses/domain_identity_data_source_test.go, internal/service/ses/domain_identity_test.go, internal/service/ses/domain_identity_verification_test.go, internal/service/ses/domain_mail_from_test.go, internal/service/ses/email_identity_data_dource_test.go, internal/service/ses/email_identity_test.go, internal/service/ses/event_destination_test.go, internal/service/ses/identity_policy_test.go, internal/service/ses/receipt_filter_test.go, internal/service/ses/receipt_rule_set_test.go, internal/service/ses/receipt_rule_test.go, internal/service/ses/template_test.go
- ses: Fix test configs names
- ses: Fix
```
...
```
=> ses: Fix test configs names

.changelog/24980.txt, internal/provider/provider.go, internal/service/location/place_index_data_source.go, internal/service/location/place_index_data_source_test.go, website/docs/d/location_place_index.html.markdown
```
$ make testacc PKG=location TESTS="TestAccLocationPlaceIndexDataSource_"
TF_ACC=1 go test ./internal/service/location/... -v -count 1 -parallel 20 -run='TestAccLocationPlaceIndexDataSource_'  -timeout 180m
=== RUN …
```
=> d/aws_location_place_index - new data source

.semgrep-service-name0.yml, internal/service/servicediscovery/dns_namespace_data_source_test.go, internal/service/servicediscovery/instance_test.go
- servicediscovery: Fix test configs names
- servicediscovery: Fix test configs
```
...
```
=> servicediscovery: Fix test configs names

internal/service/elasticache/find.go, internal/service/elasticache/global_replication_group_test.go, internal/service/elasticache/parameter_group.go, internal/service/elasticache/replication_group.go, internal/service/elasticache/replication_group_test.go
When a replication group is added to a global datastore, the API creates a custom duplicate parameter group. Delete it when deleting the replication group.
Closes #19255
```
$ make testacc PKG=elasticache TESTS='TestAccElastiCacheReplicationGroup|TestAccElastiCacheGlobalReplicationGroup|TestAccElastiCacheParameterGroup'
--- PASS: TestAccElastiCacheReplicationGroupDataSource_nonExistent (31.14s)
--- PASS: TestAccElastiCacheReplicationGroup_Validation_noNodeType (51.85s)
--- PASS: TestAccElastiCacheReplicationGroup_deprecatedAvailabilityZones_multiAzInVPC (901.48s)
--- PASS: TestAccElastiCacheReplicationGroup_finalSnapshot (935.50s)
--- PASS: TestAccElastiCacheGlobalReplicationGroup_basic (989.63s)
--- PASS: TestAccElastiCacheReplicationGroup_tags (1025.51s) …
```
=> resource/aws_elasticache_replication_group: Deletes parameter group created when replication group added to global datastore

website/docs/d/secretsmanager_secret_version.html.markdown
Closes #24932
The `aws_secretsmanager_secret_version` data source documentation incorrectly states that the `secret_binary` attribute is Base64 encoded. This PR aims to fix that.
- `aws_secretsmanager_secret_version` [uses `secretsmanager.GetSecretValue`](https://github.com/hashicorp/terraform-provider-aws/blob/05781e …
=> Correct secretsmanager_secret_version data source docs

.github/workflows/terraform_provider.yml
Relates https://github.com/hashicorp/terraform-provider-aws/pull/24955
Relates CI errors like: https://github.com/hashicorp/terraform-provider-aws/runs/6598628116?check_suite_focus=true
Issue reported in https://github.com/tj-actions/changed-files/issues/501
* Revert the update and potentially look for an alternative action  …
=> Revert tj-actions/changed-files update to v20.2

.semgrep-service-name0.yml, internal/service/logs/destination_policy_test.go, internal/service/logs/destination_test.go, internal/service/logs/group_data_source_test.go, internal/service/logs/group_test.go, internal/service/logs/groups_data_source_test.go, internal/service/logs/metric_filter_test.go, internal/service/logs/query_definition_test.go, internal/service/logs/resource_policy_test.go, internal/service/logs/stream_test.go, internal/service/logs/subscription_filter_test.go
- logs: Fix test configs names
- logs: Fix semgrep
```
...
```
=> logs: Fix test configs names

.changelog/24804.txt, internal/service/servicecatalog/provisioned_product.go, internal/service/servicecatalog/status.go, internal/service/servicecatalog/wait.go
Closes https://github.com/hashicorp/terraform-provider-aws/issues/24574
```
make testacc TESTARGS='-run=TestAccServiceCatalogProvisionedProduct_' PKG=servicecatalog
TF_ACC=1 go test ./internal/service/servicecatalog/... -v -count 1 -parallel 20 …
```
=> r/servicecatalog_provisioned_product: add `TAINTED` to target states in waiters

.changelog/25062.txt, internal/service/kafka/cluster.go, internal/service/kafka/cluster_test.go
Closes #25061
```
$ make testacc TESTARGS='-run=TestAccKafkaCluster_BrokerNodeGroupInfo' PKG=kafka
TF_ACC=1 go test ./internal/service/kafka/... -v -count 1 -parallel 20  -run=TestAccKafkaCluster_BrokerNodeGroupInfo -timeout 180m
=== RUN …
```
=> r/aws_msk_cluster - support multi update

.changelog/25072.txt, docs/contributing/data-handling-and-conversion.md, internal/service/kafka/cluster.go
Closes #24881.
```
--- PASS: TestAccKafkaCluster_basic (1834.32s)
=== CONT  TestAccKafkaCluster_Info_revision
--- PASS: TestAccKafkaCluster_EncryptionInfo_encryptionAtRestKMSKeyARN (1834.56s)
=== CONT  TestAccKafkaCluster_ClientAuthenticationTLS_initiallyNoAuthentication
--- PASS: TestAccKafkaCluster_ClientAuthenticationSASL_scram (3776.23s)
=== CONT …
```
=> r/aws_msk_cluster: Fix crash when `tls` configuration block is empty

.changelog/25073.txt, internal/provider/provider.go, internal/service/redshift/consts.go, internal/service/redshift/endpoint_access.go, internal/service/redshift/endpoint_access_test.go, internal/service/redshift/find.go, internal/service/redshift/status.go, internal/service/redshift/wait.go, website/docs/r/redshift_endpoint_access.html.markdown
Closes #22113
```
$ make testacc TESTS=TestAccRedshiftEndpointAccess_ PKG=redshift
--- PASS: TestAccRedshiftEndpointAccess_disappears_cluster (695.53s)
--- PASS: TestAccRedshiftEndpointAccess_disappears (760.81s)
--- PASS: TestAccRedshiftEndpointAccess_basic (1163.36s)
--- PASS: TestAccRedshiftEndpointAccess_sgs (1164.01s)
```
=> r/redshift_endpoint_access - new resource

.changelog/25077.txt, internal/service/elasticache/cluster.go, internal/service/elasticache/engine_version.go, internal/service/elasticache/engine_version_test.go, internal/service/elasticache/global_replication_group.go, internal/service/elasticache/global_replication_group_test.go, internal/service/elasticache/replication_group_test.go, website/docs/r/elasticache_global_replication_group.html.markdown
Adds support for upgrading the `engine_version` for an `aws_elasticache_global_replication_group`
Relates #17696
```
$ make testacc PKG=elasticache TESTS='TestAccElastiCacheCluster|TestAccElastiCacheGlobalReplicationGroup|TestAccElastiCacheReplicationGroup'
--- PASS: TestAccElastiCacheReplicationGroup_Validation_noNodeType (53.01s)
--- PASS: TestAccElastiCacheClusterDataSource_Data_basic (540.79s)
--- PASS: TestAccElastiCacheReplicationGroup_dataTiering (771.60s)
--- PASS: TestAccElastiCacheReplicationGroupDataSource_multiAZ (809.35s)
--- PASS: TestAccElastiCacheReplicationGroup_tags (952.12s)
--- PASS: TestAccElastiCacheReplicationGroup_Validation_globalReplicationGroupIdAndNodeType (1109.12s)
--- PASS: …
```
=> resource/aws_elasticache_global_replication_group: Support upgrading version

website/docs/r/elasticache_global_replication_group.html.markdown
Updates `aws_elasticache_global_replication_group ` documentation examples to include `lifecycle.ignore_changes`
N/A
=> resource/aws_elasticache_global_replication_group: Adds `lifecycle.ignore_changes` to documentation examples

.changelog/25092.txt, internal/provider/provider.go, internal/service/redshift/cluster_credentials_data_source.go, internal/service/redshift/cluster_credentials_data_source_test.go, website/docs/d/redshift_cluster_credentials.html.markdown
```
$ make testacc TESTS=TestAccRedshiftClusterCredentialsDataSource_basic
--- PASS: TestAccRedshiftClusterCredentialsDataSource_basic (283.94s)
```
=> d/redshift_cluster_credentials - new data source

.changelog/25104.txt, internal/provider/provider.go, internal/service/redshiftdata/find.go, internal/service/redshiftdata/statement.go, internal/service/redshiftdata/statement_test.go, internal/service/redshiftdata/status.go, internal/service/redshiftdata/wait.go, website/docs/r/redshiftdata_statement.html.markdown
Closes #23450
```
$ make testacc TESTS=TestAccRedshiftDataStatement_basic PKG=redshiftdata
--- PASS: TestAccRedshiftDataStatement_basic (248.09s)
```
=> r/redshiftdata_statement - new resource

.changelog/25113.txt, internal/service/ram/resource_share.go, internal/service/ram/resource_share_test.go, website/docs/r/ram_resource_share.markdown
Closes #20499
```
$ make testacc TESTS=TestAccRAMResourceShare_ PKG=ram
--- PASS: TestAccRAMResourceShare_permission (35.57s)
--- PASS: TestAccRAMResourceShare_basic (35.62s)
--- PASS: TestAccRAMResourceShare_allowExternalPrincipals (56.72s)
--- PASS: TestAccRAMResourceShare_name (57.08s)
--- PASS: TestAccRAMResourceShare_tags …
```
=> r/ram_resource_share - add `permission_arns` argument

skaff/resource/resource.tmpl
This PR adds fixes to the `skaff` generated resource template. Issues are in regards to syntax when accessing the AWS SDK. 
```
$ go test ./datasource 
ok      github.com/hashicorp/terraform-provider-aws/skaff/datasource    0.320s
$ go test ./resource  
ok …
```
=> skaff: resource generation template fixes

.changelog/25140.txt, internal/service/neptune/cluster.go, internal/service/neptune/cluster_test.go, website/docs/r/neptune_cluster.html.markdown
Closes #24512
Adding `allow_major_version_upgrade` attribute for AWS Neptune Cluster.
Sorry, I'm not able to run Acceptance Tests right now, may I ask you to run them?
```
$ make testacc TESTS=TestAccNeptuneCluster PKG=neptune
...
```
=> r/aws_neptune_cluster: added `allow_major_version_upgrade` attribute

.changelog/25130.txt, internal/service/servicecatalog/provisioned_product_test.go, internal/service/servicecatalog/wait.go, website/docs/r/servicecatalog_provisioned_product.html.markdown
Closes https://github.com/hashicorp/terraform-provider-aws/issues/24574
```
make testacc TESTARGS='-run=TestAccServiceCatalogProvisionedProduct_' PKG=servicecatalog
TF_ACC=1 go test ./internal/service/servicecatalog/... -v -count 1 -parallel 20 …
```
=> r/servicecatalog_provisioned_product: fix error when in the `TAINTED` state

internal/service/guardduty/detector_test.go
Renames GuardDuty acceptance tests to naming standards
N/A, renames functions
=> Renames GuardDuty acceptance tests to naming standards

.changelog/25145.txt, internal/service/rds/cluster_instance.go, internal/service/rds/cluster_role_association.go, internal/service/rds/cluster_role_association_test.go, internal/service/rds/instance.go, internal/service/rds/instance_role_association.go, internal/service/rds/instance_role_association_test.go, internal/service/rds/wait.go
Extends the timeouts for `aws_db_instance_role_association` and `aws_rds_cluster_role_association`.
Closes #24963
```
$ make testacc PKG=rds TESTS='TestAccRDSInstanceRoleAssociation|TestAccRDSClusterRoleAssociation'
--- PASS: TestAccRDSClusterRoleAssociation_Disappears_cluster (184.79s)
--- PASS: TestAccRDSClusterRoleAssociation_Disappears_role (187.39s)
--- PASS: TestAccRDSClusterRoleAssociation_disappears (190.88s)
--- PASS: TestAccRDSClusterRoleAssociation_basic (205.95s)
--- PASS: TestAccRDSInstanceRoleAssociation_disappears (901.54s)
--- PASS: TestAccRDSInstanceRoleAssociation_basic (972.91s)
```
=> resource/aws_db_instance_role_association & aws_rds_cluster_role_association: Extend timeouts

.changelog/25158.txt, CHANGELOG.md, internal/service/ram/resource_share.go
Closes #25156.
Relates #25113.
```
$ make testacc TESTS=TestAccRAMResourceShare_ PKG=ram
--- PASS: TestAccRAMResourceShare_disappears (27.55s)
--- PASS: TestAccRAMResourceShare_basic (37.24s)
--- PASS: TestAccRAMResourceShare_permission (37.63s)
--- PASS: TestAccRAMResourceShare_allowExternalPrincipals (62.80s)
--- PASS: …
```
=> r/ram_resource_share - Fix #25156

website/docs/r/imagebuilder_distribution_configuration.html.markdown
Fix wrong example in aws_imagebuilder_distribution_configuration.
launch_template_configuration must be defined under the distribution block.
=> fix(doc): wrong example for aws_imagebuilder_distribution_configuration

.changelog/25159.txt, internal/service/ram/resource_share_data_source.go, internal/service/ram/resource_share_data_source_test.go, website/docs/d/ram_resource_share.html.markdown
Closes #25157
```
$ make testacc TESTS=TestAccRAMResourceShareDataSource_ PKG=ram
--- PASS: TestAccRAMResourceShareDataSource_tags (35.06s)
--- PASS: TestAccRAMResourceShareDataSource_status (35.55s)
--- PASS: TestAccRAMResourceShareDataSource_basic (39.49s)
```
=> d/aws_ram_resource_share - add `resource_share_status` argument

.changelog/24764.txt, internal/service/s3/bucket.go
Signed-off-by: Wilfried Roset <wilfriedroset@users.noreply.github.com>
The following patch takes into account third party S3 who does not support CORS.
Example of error message:
```
Error: error getting S3 Bucket CORS configuration: NotImplemented: The requested resource is not implemented status code: 501, request id: [redacted], host id: [redacted] 
````
=> Add XNotEmplemented error handling in resourceBucketRead

CHANGELOG.md
Closes #24345.
Closes https://github.com/hashicorp/terraform-provider-aws/issues/25183.
While we link out to the `3.x` series changelog at the bottom of the main changelog, the main changelog had releases up to `3.74.1`, but was missing `3.74.2` through `3.75.1`. This PR brings those changelog entries over.
=> Add missing CHANGELOG entries for `3.74.2` through `3.75.1`

.github/workflows/acctest-terraform-lint.yml, .github/workflows/changelog.yml, .github/workflows/dependencies.yml, .github/workflows/documentation.yml, .github/workflows/examples.yml, .github/workflows/skaff.yml, .github/workflows/snapshot.yml, .github/workflows/terraform_provider.yml, .github/workflows/website.yml, .github/workflows/workflow-lint.yml
Closes https://github.com/hashicorp/terraform-provider-aws/issues/24937
Now that actions/setup-go#62 has been merged, the GitHub action `setup-go` can now read the Go version from the `.go-version` file. Update uses of the `setup-go` action to use this feature.
N/A
=> Updates `actions/setup-go` to use `go-version-file`

website/docs/r/workspaces_workspace.html.markdown
Relates  #25112
This PR adds a couple of additional valid values to the list of accepted values for `aws_workspaces_workspace.workspace_properties.compute_type_name`.
- `ValidateFunc` uses [`workspaces.Compute_Values()`](https://github.com/hashicorp/terraform-provider-aws/blob/e70faae038841b83dc077de02ab7a07bb7c6726e/ …
=> Add additional compute types to aws_workspaces_workspace list of valid values

website/docs/r/lakeformation_permissions.html.markdown
Closes #25202
This PR corrects an argument in one of the examples in the `aws_lakeformation_permissions` doc, as described in the linked issue.
=> Correct aws_lakeformation_permissions docs example

website/docs/r/appconfig_hosted_configuration_version.html.markdown
Resource Description field was the same for two resource types
```
...
```
=> docs: Minor change to description in the docs

website/docs/r/db_parameter_group.html.markdown
This PR adds the following note to the `aws_db_parameter_group` resource documentation page, to explain why some people might encounter a perpetual diff in their Terraform code.  I encountered this recently and it took me some time to understand what was happening.  I'm hoping this might help others understand their issue more quickly.
I had initially created an RDS Parameter Group with the `max_heap_table_size` parameter set with an apply method of `pending-reboot`.  I subsequently changed only the apply method to `immediate`.  After a successful `terraform apply` of this change (i.e. no errors), a subsequent `terraform plan` showed the same diff to be applied, perpetually.
```
~ resource "aws_db_parameter_group" "db_alt" {
id          = "prd-us-east-1-artifactory-db-alt"
name        = …
```
=> aws_db_parameter_group: add note to docs about perpetual diff/drift

website/docs/guides/version-4-upgrade.html.md
Closes #24505
This PR aims to clarify that the `id` of a lifecycle rule is a required argument in provider version `4.x`, whereas it was an optional argument in `3.x`.
=> Update upgrade guide to indicate lifecycle_rule id is required

website/docs/r/sns_platform_application.html.markdown
Closes #24760
The linked issue points out that the descriptions for the arguments for the `aws_sns_platform_application` resource didn't quite describe what some of the arguments did. This PR aims to add a bit of additional clarity to the arguments.
- `aws_sns_platform_application` uses …
=> Update `aws_sns_platform_application` argument descriptions

.changelog/25257.txt, internal/service/ec2/ipam_pool_cidr_allocation.go
Relates OR Closes #25256 
```
$ make testacc TESTS=TestAccIPAMPoolAllocation PKG=ec2                        
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 20 -run='TestAccIPAMPoolAllocation'  -timeout 180m
=== RUN …
```
=> r/aws_vpc_ipam_pool_cidr_allocation use AllocationId over filtering on `allocation-id`

.changelog/25174.txt, internal/service/ssm/parameter.go, internal/service/ssm/parameter_test.go, website/docs/r/ssm_parameter.html.markdown
AWS SSM Parameters with `Intelligent-Tiering` were not upgrading from `Standard` to `Advanced` if needed.
Removes hard-coded default of `Standard` to use the default configured for the account and region.
Closes #18521
Closes #25037
```
$ make testacc PKG=ssm TESTS=TestAccSSMParameter
--- PASS: TestAccSSMParameter_disappears (106.85s)
--- PASS: TestAccSSMParametersByPathDataSource_withRecursion (130.32s)
--- PASS: TestAccSSMParameter_Tier_intelligentTieringOnCreation (137.32s)
--- PASS: TestAccSSMParameter_overwriteWithTags (146.87s)
--- PASS: TestAccSSMParameter_secure (146.89s)
--- PASS: TestAccSSMParameter_noOverwriteWithTags (147.05s)
--- PASS: TestAccSSMParameter_fullPath (147.11s)
--- PASS: TestAccSSMParameter_basic (149.06s)
--- PASS: …
```
=> resource/aws_ssm_parameter: Allow `Intelligent-Tiering` to upgrade to `Advanced`

internal/service/ec2/sweep.go
Closes #25193
Sweeper appears to cancel spot instance requests as desired:
```bash
❯ SWEEPARGS=-sweep-run=aws_spot_instance_request make sweep
go test ./internal/sweep -v -tags=sweep -sweep=us-west-2,us-east-1,us-east-2 -sweep-run=aws_spot_instance_request -timeout 60m
2022/06/10 …
```
=> Add sweeper for spot instance requests

.changelog/25046.txt, internal/service/ec2/vpc_managed_prefix_list_entry.go, internal/service/ec2/vpc_managed_prefix_list_entry_test.go
Closes #21835
Seems like this should be straightforward but now it's giving a new error. Anyone have thoughts?
```console
% make testacc TESTS=TestAccVPCManagedPrefixListEntry_ipv4Multiple PKG=ec2
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 20 …
```
=> vpc: Problem creating multiple managed prefix list entries

.semgrep-service-name0.yml, internal/provider/provider.go, internal/service/appsync/api_cache.go, internal/service/appsync/api_cache_test.go, internal/service/appsync/datasource_test.go, internal/service/appsync/domain_name_api_association.go, internal/service/appsync/domain_name_api_association_test.go, internal/service/appsync/find.go, internal/service/appsync/function_test.go, internal/service/appsync/graphql_api_test.go, internal/service/appsync/resolver_test.go, internal/service/appsync/status.go, internal/service/appsync/sweep.go, internal/service/appsync/wait.go
- appsync: Fix naming
- appsync: Fix naming
```
...
```
=> appsync: Fix naming

.semgrep-service-name0.yml, internal/service/firehose/delivery_stream.go, internal/service/firehose/delivery_stream_data_source_test.go, internal/service/firehose/delivery_stream_test.go
- firehose: Fix func naming
- firehose: Fix func naming
```
...
```
=> firehose: Fix func naming

.semgrep-service-name0.yml, internal/service/batch/compute_environment.go, internal/service/batch/compute_environment_data_source_test.go, internal/service/batch/compute_environment_test.go, internal/service/batch/container_properties_test.go, internal/service/batch/job_definition.go, internal/service/batch/job_definition_test.go, internal/service/batch/job_queue.go, internal/service/batch/job_queue_data_source_test.go, internal/service/batch/job_queue_test.go, internal/service/batch/scheduling_policy_data_source_test.go, internal/service/batch/scheduling_policy_test.go
- batch: Fix func names
- batch: Fix func names
```
...
```
=> batch: Fix func names

.changelog/25326.txt, internal/service/dynamodb/table_item.go, internal/service/dynamodb/table_item_test.go
Closes #15700
```
$ make testacc TESTS=TestAccTableItem_ PKG=dynamodb
TF_ACC=1 go test ./internal/service/dynamodb/... -v -count 1 -parallel 20 -run='TestAccTableItem_'  -timeout 180m
=== RUN   TestAccTableItem_basic
=== PAUSE TestAccTableItem_basic
=== RUN …
```
=> r/aws_dynamodb_table_item: fix to remove item elements on update

.semgrep-caps-aws-config.yml, internal/service/efs/access_point_data_source_test.go, internal/service/efs/access_point_test.go, internal/service/efs/access_points_data_source_test.go, internal/service/efs/backup_policy_test.go, internal/service/efs/file_system_data_source_test.go, internal/service/efs/file_system_policy_test.go, internal/service/efs/file_system_test.go, internal/service/efs/mount_target_data_source_test.go, internal/service/efs/mount_target_test.go, internal/service/efs/replication_configuration_test.go
- efs: Fix test configs names
- efs: Fix test config names
```
...
```
=> efs: Fix test configs names

.semgrep-configs.yml, internal/generate/servicesemgrep/configs.tmpl, internal/service/ecr/pull_through_cache_rule_test.go, internal/service/ecr/registry_policy_test.go, internal/service/ecr/registry_scanning_configuration_test.go, internal/service/ecr/replication_configuration_test.go, internal/service/ecr/repository_policy_test.go, internal/service/ecr/repository_test.go
- ecr: Fix test configs names
- ci/semgrep/ecr: Exclude ecrpublic
```
...
```
=> ci/semgrep/ecr: Remove exclusion

.semgrep-configs.yml, internal/generate/servicesemgrep/configs.tmpl, internal/service/codestarnotifications/notification_rule_test.go
- ci/semgrep/codestarnotifications: Remove exclusion
- ci/semgrep/codestar: Fix caps
```
...
```
=> ci/semgrep/codestarnotifications: Remove exclusion

internal/service/elasticache/replication_group.go
Relates #25430 (maybe closes)
```console
% make testacc TESTS=TestAccElastiCacheReplicationGroup_vpc PKG=elasticache
TF_ACC=1 go test ./internal/service/elasticache/... -v -count 1 -parallel 20 -run='TestAccElastiCacheReplicationGroup_vpc'  -timeout 180m
--- PASS: …
```
=> elasticache/replication_group: Add nil guards for endpoints

website/docs/r/backup_selection.html.markdown
When using aws_backup_selection the resources field is needed in order to work.
Previously this example would give the following error:
```
resource "aws_backup_selection" "example" {
iam_role_arn = aws_iam_role.example.arn
name         = "tf_example_backup_selection"
plan_id      = aws_backup_plan.example.id
condition {
string_equals {
key   = …
```
=> Fix example for Selecting Backups By Conditions

website/docs/r/ce_anomaly_monitor.html.markdown
Closes #25295
It looks like just before the new `aws_ce_anomaly_monitor` resource was added, the argument names were changed, but the change didn't make it to the docs. This PR corrects the argument names in the documentation.
- PR that added resource: #25177 (new in `4.18.0`)
- [Argument …
=> Correct `aws_ce_anomaly_monitor` argument names

website/docs/r/waf_byte_match_set.html.markdown
Currently the description for this field docs gives a confusing example for this field (seems to have been copy/pasted from another field). This PR uses the example from the main example at the top of the page. It also makes the formatting consistent with the other descriptions.
Closes #25328
=> r/waf_byte_match_set.byte_match_tuples.target_string (docs) fix example, spacing (fixes #25328)

.changelog/25450.txt, internal/service/autoscaling/launch_configuration.go, internal/service/autoscaling/launch_configuration_test.go
Closes #25244.
Closes #25252.
Relates #17695.
Removes the default value for `associate_public_ip_address` argument and marks it as Computed.
This allows the pre-**v4.17.0** behavior of no configured value triggering the [API default behavior](https://docs.aws.amazon.com/autoscaling/ec2/APIReference/API_CreateLaunchConfiguration.html#API_CreateLaunchConfigurat …
=> r/aws_launch_configuration: No default for `associate_public_ip_address`

.changelog/25464.txt, internal/service/ec2/ec2_host.go, internal/service/ec2/ec2_host_data_source.go, internal/service/ec2/ec2_host_data_source_test.go, internal/service/ec2/ec2_host_test.go, website/docs/d/ec2_host.html.markdown, website/docs/r/ec2_host.html.markdown
Closes #25410
```
$ make testacc TESTS='TestAccHost_outpost' PKG=ec2 TESTARGS=-short                    2 ✘  16s
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 20 -run='TestAccHost_outpost' -short -timeout 180m
=== RUN   TestAccHost_outpost
=== …
```
=> Ec2host outpostarn

.changelog/25199.txt, internal/provider/provider.go, internal/service/kendra/find.go, internal/service/kendra/id.go, internal/service/kendra/id_test.go, internal/service/kendra/index.go, internal/service/kendra/index_test.go, internal/service/kendra/kendra_test.go, internal/service/kendra/thesaurus.go, internal/service/kendra/thesaurus_test.go, website/docs/r/kendra_thesaurus.html.markdown
Relates #13367 
```
$  make testacc TESTARGS='-run=TestAccKendra_serial/Thesaurus' PKG=kendra
TF_ACC=1 go test ./internal/service/kendra/... -v -count 1 -parallel 20  -run=TestAccKendra_serial/Thesaurus -timeout 180m
--- PASS: TestAccKendra_serial (6560.35s)
--- PASS: …
```
=> r/kendra_thesaurus: new resource

website/docs/d/iam_policy_document.html.markdown
Closes #25071
It's possible to create IAM policy documents with [conditions with multiple keys/values](https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_multi-value-conditions.html), however, it wasn't clear in the documentation how to do so. This PR adds an example displaying how to do so.
=> Add multi-key/multi-value `conditional` example to `aws_iam_policy_document` data source documentation

internal/service/sagemaker/domain.go, internal/service/sagemaker/domain_test.go, internal/service/sagemaker/sagemaker_test.go
Closes #25266
```
bug:
resource/aws_sagemaker_domain: Fix update behaviour for `default_user_settings`
```
```
$ make testacc TESTS=TestAccSageMaker_serial/Domain PKG=sagemaker                                  <aws:default> …
```
=> r/aws_sagemaker_domain: in-place update for default user settings

.changelog/25218.txt, internal/service/sagemaker/endpoint_configuration.go, internal/service/sagemaker/endpoint_configuration_test.go, website/docs/r/sagemaker_endpoint_configuration.html.markdown
Closes #22710
```
$ make testacc TESTS=TestAccSageMakerEndpointConfiguration_ PKG=sagemaker
--- PASS: TestAccSageMakerEndpointConfiguration_kmsKeyID (52.58s)
--- PASS: TestAccSageMakerEndpointConfiguration_dataCapture (54.21s)
--- PASS: TestAccSageMakerEndpointConfiguration_async (55.49s)
--- PASS: …
```
=> r/sagemaker_endpoint_configuration - add `serverless_config` argument

.changelog/25466.txt, internal/provider/provider.go, internal/service/location/tracker.go, internal/service/location/tracker_test.go, website/docs/r/location_tracker.html.markdown
```
$ make testacc PKG=location TESTS="TestAccLocationTracker_"
TF_ACC=1 go test ./internal/service/location/... -v -count 1 -parallel 20 -run='TestAccLocationTracker_'  -timeout 180m
=== RUN   TestAccLocationTracker_basic
=== PAUSE …
```
=> r/aws_location_tracker - new resource

internal/service/location/place_index_test.go
```
$ make testacc PKG=location TESTS="TestAccLocationPlaceIndex_"
TF_ACC=1 go test ./internal/service/location/... -v -count 1 -parallel 20 -run='TestAccLocationPlaceIndex_'  -timeout 180m
=== RUN   TestAccLocationPlaceIndex_basic
=== PAUSE …
```
=> r/aws_location_place_index - set correct CheckDestroy

.changelog/25245.txt, internal/service/apigateway/model.go
* Please vote on this pull request by adding a +1 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
Resolves an issue with API Gateway Schema models being marked as having changed when differences solely consist of irrelevant characters such as whitespace.
Implementation ported from [service/apigatewayv2/model.go](https://github.com/hashicorp/terraform-provider-aws/blob/main/internal/service/apigatewayv2/model.go) which already handles this issue. …
=> r/aws_api_gateway_model: suppress schema whitespace differences

internal/service/kendra/thesaurus.go, internal/service/kendra/thesaurus_test.go
Relates #25199
`thesaurus_id` attribute is used with `index_id` in the `aws_kendra_thesaurus` data source. Tagging @anGie44 for visibility. Thanks Angie! 
Commented out other tests locally to just run the `basic` test.
```
$ make testacc TESTARGS='-run=TestAccKendra_serial/Thesaurus' PKG=kendra
==> Checking that code complies …
```
=> r/aws_kendra_thesaurus - New attribute thesaurus_id

.changelog/25315.txt, internal/provider/provider.go, internal/service/kendra/experience.go, internal/service/kendra/experience_test.go, internal/service/kendra/id.go, internal/service/kendra/id_test.go, internal/service/kendra/kendra_test.go, website/docs/r/kendra_experience.html.markdown
Relates #13367 
Output from acceptance testing (**must be run in Organizations-only account**):
```
$ make testacc TESTARGS='-run=TestAccKendra_serial/Experience' PKG=kendra ACCTEST_TIMEOUT=250m
TF_ACC=1 go test ./internal/service/kendra/... -v -count 1 -parallel 20 …
```
=> r/kendra_experience: new resource

.changelog/25277.txt, internal/service/events/api_destination.go
=> Allow Eventbridge API Destination Invocation Rate Limit to be greater than 300

internal/service/location/sweep.go
```
$ SWEEPARGS=-sweep-run=aws_location_place_index make sweep
go test ./internal/sweep -v -tags=sweep -sweep=us-west-2,us-east-1,us-east-2 -sweep-run=aws_location_place_index -timeout 60m
2022/06/22 23:23:13 Completed Sweepers for …
```
=> sweeper/aws_location_place_index - new sweeper

.changelog/25284.txt, internal/service/synthetics/canary.go, internal/service/synthetics/canary_test.go, website/docs/r/synthetics_canary.html.markdown
Closes #19288
```
$ make testacc TESTS=TestAccSyntheticsCanary_ PKG=synthetics
--- PASS: TestAccSyntheticsCanary_disappears (84.28s)
--- PASS: TestAccSyntheticsCanary_s3 (93.01s)
--- PASS: TestAccSyntheticsCanary_artifactEncryption (106.73s)
--- PASS: TestAccSyntheticsCanary_runtimeVersion (130.89s)
--- PASS: …
```
=> r/synthetics_canary - add `delete_lambda` argument

.changelog/25538.txt, internal/service/iam/find.go, internal/service/iam/policy_data_source.go, internal/service/iam/policy_data_source_test.go, website/docs/d/iam_policy.html.markdown
No longer iterates over all IAM Policies in `aws_iam_policy` data source when ARN is supplied. Also fixes bug where tags are not retrieved.
Closes #25533.
Closes #25537.
Closes #19878.
```
$ make testacc PKG=iam TESTS=TestAccIAMPolicyDataSource_
--- PASS: TestAccIAMPolicyDataSource_awsManagedArn (26.32s)
--- PASS: TestAccIAMPolicyDataSource_arnTags (29.29s)
--- PASS: TestAccIAMPolicyDataSource_arn (30.15s)
--- PASS: TestAccIAMPolicyDataSource_nameAndPathPrefixTags (30.17s)
--- PASS: TestAccIAMPolicyDataSource_nameAndPathPrefix (30.49s)
--- PASS: TestAccIAMPolicyDataSource_nameTags (39.02s)
--- PASS: TestAccIAMPolicyDataSource_name (40.39s)
--- PASS: TestAccIAMPolicyDataSource_nonExistent (126.49s)
```
=> resource/aws_iam_policy: Do not iterate over all IAM Policies when ARN supplied

website/docs/r/opensearch_domain.html.markdown
This PR is only fix documentation.  
Target URL: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/opensearch_domain
The part that should be `Elasticsearch` and `elasticsearch` was `Elastisearch` and `elastisearch`.
=> fix typo in OpenSearch document

.changelog/25557.txt, internal/service/sagemaker/model.go, internal/service/sagemaker/model_test.go, website/docs/r/sagemaker_model.html.markdown
```
$ make testacc TESTS=TestAccSageMakerModel_primaryContainerPrivateDockerRegistry PKG=sagemaker
TF_ACC=1 go test ./internal/service/sagemaker/... -v -count 1 -parallel 20 -run='TestAccSageMakerModel_primaryContainerPrivateDockerRegistry' …
```
=> s/sagemaker Add support repository_auth_config in image_config

.changelog/25371.txt, internal/service/ec2/ec2_key_pair.go, internal/service/ec2/ec2_key_pair_data_source.go, internal/service/ec2/ec2_key_pair_data_source_test.go, website/docs/d/key_pair.html.markdown, website/docs/r/key_pair.html.markdown
Closes #25314 
```
bruno@pop-os ~/G/terraform-provider-aws (f/#25314-aws-key-pair-public-key)> make testacc TESTS=TestAccEC2KeyPairDataSource_ PKG=ec2                                                                                                     (base) 
TF_ACC=1 …
```
=> F/#25314 - Return the public key material for a `aws_key_pair`

.changelog/25372.txt, internal/service/appstream/stack.go, internal/service/appstream/stack_test.go
Closes #25205
```
$ make testacc TESTS=TestAccAppStreamStack PKG=appstream 
TF_ACC=1 go test ./internal/service/appstream/... -v -count 1 -parallel 20 -run='TestAccAppStreamStack'  -timeout 180m
=== RUN   TestAccAppStreamStack_basic
=== PAUSE …
```
=> bugfix: validate `embed_host_domains` correctly

.changelog/25565.txt, .github/workflows/terraform_provider.yml, internal/provider/provider.go, internal/service/lakeformation/lakeformation_test.go, internal/service/lakeformation/lf_tag_test.go, internal/service/lakeformation/resource_lf_tags.go, internal/service/lakeformation/resource_lf_tags_test.go, names/errors.go, website/docs/r/lakeformation_resource_lf_tags.html.markdown
Closes #19640
Closes #20996
Relates #19523
Relates #19648
```console
% make testacc TESTS="TestAccLakeFormation_serial/ResourceLFTags" PKG=lakeformation
TF_ACC=1 go test ./internal/service/lakeformation/... -v -count 1 -parallel 20 …
```
=> lakeformation: Add new aws_lakeformation_resource_lf_tags resource

.changelog/25623.txt, internal/service/apigateway/model.go
Fixes an issue with [25623](https://github.com/hashicorp/terraform-provider-aws/pull/25623) where the length constraint from `apigatewayv2` was incorrectly copied across to `apigateway`. This change removes the `StringLenBetween` validation entirely.
=> r/aws_api_gateway_model: remove schema length validation

.changelog/25638.txt, internal/service/sagemaker/wait.go
Closes #25637
```
bruno@pop-os ~/G/terraform-provider-aws (e/#25637-increase-sagemaker-project-timeouts)> make testacc TESTS=TestAccSageMakerProject_ PKG=sagemaker                                                                                            (base)  …
```
=> Increase SageMaker `ProjectCreatedTimeout` and `ProjectDeletedTimeout` to 15 minutes

.changelog/25639.txt, internal/provider/provider.go, internal/service/location/tracker_data_source.go, internal/service/location/tracker_data_source_test.go, website/docs/d/location_map.html.markdown, website/docs/d/location_place_index.html.markdown, website/docs/d/location_tracker.html.markdown, website/docs/r/location_map.html.markdown
Relates https://github.com/hashicorp/terraform-provider-aws/issues/19629.
```
$ make testacc PKG=location TESTS="TestAccLocationTrackerDataSource_"
TF_ACC=1 go test ./internal/service/location/... -v -count 1 -parallel 20 -run='TestAccLocationTrackerDataSource_' …
```
=> d/aws_location_tracker - new data source

.changelog/25641.txt, internal/service/ecs/find.go, internal/service/ecs/service.go, internal/service/ecs/service_test.go, internal/service/ecs/status.go, internal/service/ecs/wait.go, website/docs/r/ecs_service.html.markdown
Adds customizable timeouts for Create and Update operations on `aws_ecs_service`. In some cases, when `wait_for_steady_state` is set, deployment takes longer than the default timeout. Allow practitioners to adjust the timeout and extend the default to 20 minutes.
Also fixes various error handling problems that cause "unexpected new value" errors. 
Closes #16012
Closes #24565
Closes #24018
Closes #16184
Closes #17118
Closes #18329
```
$ make testacc PKG=ecs TESTS=TestAccECSService_
--- PASS: TestAccECSService_DaemonSchedulingStrategy_basic (98.31s)
--- PASS: TestAccECSService_DeploymentValues_basic (108.75s)
--- PASS: TestAccECSService_DeploymentValues_minZeroMaxOneHundred (125.64s)
--- PASS: TestAccECSService_iamRole (130.64s)
--- PASS: …
```
=> resource/aws_ecs_service: Add customizable timeouts for Create and Update

.changelog/25671.txt, internal/service/imagebuilder/distribution_configuration.go, internal/service/imagebuilder/distribution_configuration_data_source.go, internal/service/imagebuilder/distribution_configuration_data_source_test.go, internal/service/imagebuilder/distribution_configuration_test.go, website/docs/d/imagebuilder_distribution_configuration.html.markdown, website/docs/r/imagebuilder_distribution_configuration.html.markdown
Closes #25397.
```
$ ACCTEST_PARALLELISM=2 make testacc PKG=imagebuilder TESTS="TestAccImageBuilderDistributionConfiguration_DistributionFastLaunchConfiguration_"
TF_ACC=1 go test ./internal/service/imagebuilder/... -v -count 1 -parallel 2 …
```
=> rd/aws_imagebuilder_distribution_configuration - support fastLaunchConfigurations

website/docs/r/ec2_transit_gateway.html.markdown
According to the code 
https://github.com/hashicorp/terraform-provider-aws/blob/3bc094e858c8417c36d933118d86e127982b532e/internal/service/ec2/transitgateway_.go#L96
ec2_transit_gateway support the optional parameter  `multicast_support` but doesn't appear in documentation
=> docs(ec2_transit_gateway): add missing `multicast_support` parameter

.changelog/25668.txt, internal/service/emr/cluster.go, internal/service/emr/cluster_test.go, internal/service/emr/validate.go, website/docs/r/emr_cluster.html.markdown
=> Add `gp3` volume support to EMR cluster EBS config

.changelog/25681.txt, internal/conns/config.go
Fixes #25680.
Relates https://github.com/hashicorp/aws-sdk-go-base/pull/178.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/24441.
=> Fix web id assume role

skaff/datasource/datasourcetest.tmpl
The same as #25658 but applies to data sources.
=> skaff: Use ProviderFactories instead of Providers in data source tests

.changelog/25689.txt, internal/provider/provider.go, internal/service/location/route_calculator_data_source.go, internal/service/location/route_calculator_data_source_test.go, website/docs/d/location_route_calculator.html.markdown, website/docs/d/location_tracker.html.markdown
```
$ make testacc PKG=location TESTS="TestAccLocationRouteCalculatorDataSource_basic"
TF_ACC=1 go test ./internal/service/location/... -v -count 1 -parallel 20 -run='TestAccLocationRouteCalculatorDataSource_basic'  -timeout 180m
=== RUN …
```
=> d/aws_location_route_calculator - new data source

internal/service/cloudtrail/cloudtrail_test.go
Now skips acceptance tests which return `AccessDeniedException` instead of failing.
Closes #25563
Previously
```console
$ make testacc PKG=cloudtrail TESTS=TestAccCloudTrail_serial/Trail/enableLogging
Error: Error stopping logging on CloudTrail (tf-acc-test-3771676142374103965): AccessDeniedException: User: arn:aws:sts::123456789012:assumed-role/tf_aws_provider5_test-admin/gdavison@hashicorp.com is not authorized to perform: cloudtrail:StopLogging on resource: arn:aws:cloudtrail:us-west-2:123456789012:trail/tf-acc-test-3771676142374103965 with an explicit deny in a service control policy
status code: 400, request id: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
with aws_cloudtrail.test,
on terraform_plugin_test.tf line 37, in resource "aws_cloudtrail" "test":
37: …
```
=> resource/aws_cloudtrail: Skips CloudTrail tests on `AccessDeniedException` instead of failing

.changelog/9913.txt, internal/service/ecr/repository.go, website/docs/r/ecr_repository.html.markdown
Closes #9911
```
ENHANCEMENTS:
* resource/resource_aws_ecr_repository supports now force_delete, It can be set to false to avoid accidentally deleting the repository if it still contains images. ([#9911](https://github.com/terraform-providers/terraform-provider-aws/issues/9911))
```
Output from …
=> Add force_delete optional parameter to resource_aws_ecr_repository

website/docs/d/codestarconnections_connection.html.markdown
Small documentation update to clarify the correct use of aws_codestarconnection_connection resources when used  with GitHub Enterprise instances.
It's unclear from the current documentation that this does not work:
```hcl
resource "aws_codestarconnections_connection" "example" {
name                = "example-connection"
provider_type  = …
```
=> aws_codestarconnections_connection: update docs

.changelog/25697.txt, internal/service/apprunner/service.go, internal/service/apprunner/service_test.go, website/docs/r/apprunner_service.html.markdown
Closes #25677
```
bruno@pop-os ~/G/terraform-provider-aws (e/add-apprunner-observability-configuration-attribute-block)> make testacc TESTS=TestAccAppRunnerService_ImageRepository_observabilityConfiguration PKG=apprunner   (base)  …
```
=> Add AppRunner Observability Configuration argument configuration block

.changelog/25659.txt, internal/service/dynamodb/table.go, internal/service/dynamodb/table_test.go, internal/service/dynamodb/wait.go, website/docs/r/dynamodb_table.html.markdown
Closes #21323
Closes #25214
Closes #24473
```console
% make testacc TESTS=TestAccDynamoDBTable_ PKG=dynamodb
TF_ACC=1 go test ./internal/service/dynamodb/... -v -count 1 -parallel 20 -run='TestAccDynamoDBTable_'  -timeout 180m
--- PASS: …
```
=> dynamodb/table: Add replica PITR

examples/transit-gateway-intra-region-peering/README.md, examples/transit-gateway-intra-region-peering/main.tf, examples/transit-gateway-intra-region-peering/terraform.template.tfvars, examples/transit-gateway-intra-region-peering/variables.tf
Issue #23828 made me think that the intra-region Peering use-case
is not straight forward. Operators might assume they need to
configure the Acceptor to the Peering Attachment that Terraform creates.
In fact, AWS creates two Peering Attachment resources, one for the
Creator side and one for the Acceptor side. So, the a Data Source
is needed to find the second Acceptor side's attachment and then
use it to configure the Acceptor resource.
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they …
=> examples: configuration for intra-region Transit Gateway Peering

.changelog/25720.txt, internal/service/acmpca/certificate_authority.go, internal/service/acmpca/certificate_authority_data_source.go, internal/service/acmpca/certificate_authority_test.go, website/docs/d/acmpca_certificate_authority.html.markdown, website/docs/r/acmpca_certificate_authority.html.markdown
Closes #20946
```
$ make testacc TESTS=TestAccACMPCACertificateAuthority PKG=acmpca
TF_ACC=1 go test ./internal/service/acmpca/... -v -count 1 -parallel 20 -run='TestAccACMPCACertificateAuthority'  -timeout 180m
=== RUN …
```
=> r/aws_acmpca_certificate_authority: Add support for OCSP

skaff/resource/resource.tmpl
`ListTagsWithContext` should be used instead of `ListTags` as we pass the context to the function. Example:
https://github.com/hashicorp/terraform-provider-aws/blob/28ce9c2ce384c9b871364d1ebbc330d66590796e/internal/service/ce/tags_gen.go#L17-L33
=> skaff: Use ListTagsWithContext instead of ListTags

internal/service/location/sweep.go
```
$ SWEEPARGS=-sweep-run=aws_location_place_index SWEEP=us-west-2 make sweep
go test ./internal/sweep -v -tags=sweep -sweep=us-west-2 -sweep-run=aws_location_place_index -timeout 60m
2022/07/07 21:02:43 Completed Sweepers for region …
```
=> sweeper/aws_location - fix Place Index & Tracker sweepers

skaff/datasource/datasource.tmpl
(If I'm not mistaken) data sources should not customize diff using `verify.SetTagsDiff`.
=> skaff: Remove SetTagsDiff from data source template

.changelog/25729.txt, internal/service/rds/cluster_instance.go, internal/service/rds/cluster_instance_test.go, website/docs/r/rds_cluster_instance.html.markdown
Closes #25666
```
$ make testacc TESTS=TestAccRDSClusterInstance_performanceInsightsRetentionPeriod PKG=rds
TF_ACC=1 go test ./internal/service/rds/... -v -count 1 -parallel 20 -run='TestAccRDSClusterInstance_performanceInsightsRetentionPeriod'  -timeout 180m
=== RUN …
```
=> Make aws_rds_cluster_instance resource support monthly performance insights retention period

website/docs/r/location_map.html.markdown
Fixes
```
FILE: website/docs/r/location_map.html.markdown
[✖] https://docs.aws.amazon.com/location-maps/latest/APIReference/API_CreateMap.html → Status: 404
2 links checked.
ERROR: 1 dead links found!
[✖] https://docs.aws.amazon.com/location-maps/latest/APIReference/API_CreateMap.html → Status: 404
```
=> Fix broken `Location.CreateMap` link

website/docs/r/s3_bucket_cors_configuration.html.markdown
Closes #25604
While `bucket` is valid in this case, the other examples (for other `aws_s3_bucket_*` resources) use `id`, and that's probably a better method to suggest.
=> Switch `bucket` to `id` in `aws_s3_bucket_cors_configuration` example

.changelog/23060.txt, go.mod, go.sum, internal/service/iam/role.go, internal/service/iam/role_test.go
Closes #22274
Output from acceptance testing(us-west-2):
```
$ make testacc TESTS=TestAccIAMRole_basic PKG=iam
=== RUN   TestAccIAMRole_basic
=== PAUSE TestAccIAMRole_basic
=== RUN   TestAccIAMRole_basicWithDescription
=== PAUSE TestAccIAMRole_basicWithDescription
=== CONT  TestAccIAMRole_basicWithDescription
=== CONT  TestAccIAMRole_basic
--- PASS: …
```
=> Fix aws_iam_policy_document order

website/docs/r/cloudtrail_event_data_store.html.markdown
Closes #25730
The documentation incorrectly stated that `advanced_event_selector` was required, and that `retention_period` was optional (though elsewhere in the document, it stated that `retention_period` was required). This PR aims to correct these indicators.
- …
=> Correct required arguments for `aws_cloudtrail_event_data_store`

internal/service/networkmanager/connection.go, internal/service/networkmanager/device.go, internal/service/networkmanager/generate.go, internal/service/networkmanager/global_network.go, internal/service/networkmanager/link.go, internal/service/networkmanager/site.go, internal/service/networkmanager/tags_gen.go
Relates #25238.
```console
% make testacc TESTARGS='-run=TestAccNetworkManagerGlobalNetwork_tags' PKG=networkmanager ACCTEST_PARALLELISM=2
TF_ACC=1 go test ./internal/service/networkmanager/... -v -count 1 -parallel 2  -run=TestAccNetworkManagerGlobalNetwork_tags -timeout 180m
=== RUN …
```
=> service/Network Manager: Use `UpdateTagsWithContext`

.changelog/25789.txt, internal/service/networkmanager/core_network_policy_document_data_source_test.go, internal/service/networkmanager/core_network_policy_model.go
Closes #25787
```
$ make testacc PKG=networkmanager TESTS="TestAccNetworkManagerCoreNetworkPolicyDocumentDataSource_basic"
TF_ACC=1 go test ./internal/service/networkmanager/... -v -count 1 -parallel 20 -run='TestAccNetworkManagerCoreNetworkPolicyDocumentDataSource_basi …
```
=> d/aws_networkmanager_core_network_policy_document allow `segments` block bools to set specified values

.changelog/25762.txt, internal/provider/provider.go, internal/service/location/geofence_collection.go, internal/service/location/geofence_collection_test.go, website/docs/r/location_geofence_collection.html.markdown, website/docs/r/location_tracker.html.markdown
```
$ make testacc PKG=location TESTS="TestAccLocationGeofenceCollection_"
TF_ACC=1 go test ./internal/service/location/... -v -count 1 -parallel 20 -run='TestAccLocationGeofenceCollection_'  -timeout 180m
=== RUN …
```
=> r/aws_location_geofence_collection: new resource

.changelog/25822.txt, internal/service/outposts/outpost_asset_data_source.go, internal/service/outposts/outpost_asset_data_source_test.go, website/docs/d/outposts_asset.html.markdown
Closes #25814
```
$ make testacc TESTS='TestAccOutpostsAssetDataSource_basic' PKG=outposts TESTARGS=-short                                        
TF_ACC=1 go test ./internal/service/outposts/... -v -count 1 -parallel 20 -run='TestAccOutpostsAssetDataSource_basic' …
```
=> add 'rack_elevation' attribute to aws_outposts_asset data source

.changelog/25781.txt, CHANGELOG.md, internal/provider/provider.go, internal/service/s3control/account_public_access_block_data_source.go, internal/service/s3control/account_public_access_block_data_source_test.go, website/docs/d/s3_account_public_access_block.html.markdown
Closes #23783
```
make testacc TESTS=TestAccS3ControlAccountPublicAccessBlockDataSource PKG=s3control
TF_ACC=1 go test ./internal/service/s3control/... -v -count 1 -parallel 20 -run='TestAccS3ControlAccountPublicAccessBlockDataSource'  -timeout 180m
=== RUN …
```
=> d/aws_s3_account_public_access_block - new data source

.changelog/25718.txt, internal/service/rds/cluster.go
This PR adds the `rebooting` state to the list of allowable pending states when creating a Multi A-Z RDS cluster.
Affected resource: `aws_rds_cluster`
Closes https://github.com/hashicorp/terraform-provider-aws/issues/24721
[ Need help with running test `make testacc TESTS=TestAccRDSCluster_basic PKG=rds` ]:
```
$ make testacc …
```
=> Fix: unexpected state 'rebooting' when creating Multi A-Z rds cluster

.changelog/25819.txt, internal/service/appmesh/gateway_route.go, internal/service/appmesh/gateway_route_test.go, website/docs/r/appmesh_gateway_route.html.markdown
* added support for hostname based routing in an appmesh gateway route
* added support for rewrite settings in appmesh gateway route
Closes #23041
Closes #20272
```
$ make testacc TESTS=TestAccAppMesh_serial/GatewayRoute PKG=appmesh …
```
=> appmesh: added support for hostname based routing and  path/hostname rewrite 

.changelog/25844.txt, internal/provider/provider.go, internal/service/location/geofence_collection_data_source.go, internal/service/location/geofence_collection_data_source_test.go, website/docs/d/location_geofence_collection.html.markdown
```
$ make testacc PKG=location TESTS="TestAccLocationGeofenceCollectionDataSource_basic"
TF_ACC=1 go test ./internal/service/location/... -v -count 1 -parallel 20 -run='TestAccLocationGeofenceCollectionDataSource_basic'  -timeout 180m
=== RUN …
```
=> d/aws_location_geofence_collection: new data source

.changelog/25841.txt, internal/service/fsx/openzfs_file_system.go, internal/service/fsx/openzfs_file_system_test.go
Closes #25716
Based on PR [#24002](https://github.com/hashicorp/terraform-provider-aws/pull/24002)
```
$ make testacc TESTS=TestAccFSxOpenzfsFileSystem_ PKG=fsx ACCTEST_PARALLELISM=2 ACCTEST_TIMEOUT=720m
--- PASS: TestAccFSxOpenzfsFileSystem_diskIops (925.97s)
--- PASS: TestAccFSxOpenzfsFileSystem_storageCapacity (780.80s)
```
=> support updating fsx openzfs storage, throughput, and iops

.teamcity/scripts/setup_goenv.sh
Ensure that the main fork of `goenv` is being used. Switch remotes if needed.
Closes #25858
=> CI: Ensures main version of `goenv` being used

.changelog/25850.txt, internal/provider/provider.go, internal/service/rolesanywhere/find.go, internal/service/rolesanywhere/flex.go, internal/service/rolesanywhere/profile.go, internal/service/rolesanywhere/profile_test.go, website/docs/r/rolesanywhere_profile.html.markdown
Relates #25727
```
$ make testacc TESTS=TestAccRolesAnywhereProfile PKG=rolesanywhere
TF_ACC=1 go test ./internal/service/rolesanywhere/... -v -count 1 -parallel 20 -run='TestAccRolesAnywhereProfile'  -timeout 180m
=== RUN   TestAccRolesAnywhereProfile_basic
=== PAUSE …
```
=> Rolesanywhere profile resource

internal/service/dynamodb/arn_test.go
=> dynamodb: lintignore

internal/provider/fwprovider/duration.go, internal/provider/fwprovider/duration_test.go
Relates #25871.
Relates https://github.com/hashicorp/terraform-plugin-framework/pull/390.
```console
% make
go install
go: downloading github.com/hashicorp/terraform-plugin-go v0.12.0
go: downloading github.com/hashicorp/terraform-plugin-framework v0.10.0
go: downloading …
```
=> Fix breaking changes with Terraform Plugin Framework v0.10.0

website/docs/d/vpc_ipam_pool.html.markdown
Closes #25465
Previously, the `aws_vpc_ipam_pool` data source listed `id` as an argument (notably, it had no description), where the correct argument is `ipam_pool_id`. This PR corrects the argument name, adds a description, and then adds `id` to the list of attributes.
- [Relevant bit of data source …
=> Update argument/attribute descriptions for `aws_vpc_ipam_pool` data source

website/docs/r/apprunner_service.html.markdown
- Fixing misspelling in docs: `auto_deployment_enabled` should be `auto_deployments_enabled` (plural)
=> Correcting misspelt auto_deployments attribute (Docs)

.changelog/25918.txt, internal/provider/provider.go, internal/service/transcribe/sweep.go, internal/service/transcribe/test-fixtures/vocabulary_filter_test1.txt, internal/service/transcribe/vocabulary_filter.go, internal/service/transcribe/vocabulary_filter_test.go, internal/sweep/sweep_test.go, website/docs/r/transcribe_vocabulary_filter.html.markdown
Relates to #18865
```console
$ make testacc TESTS=TestAccTranscribeVocabularyFilter_ PKG=transcribe
TF_ACC=1 go test ./internal/service/transcribe/... -v -count 1 -parallel 20 -run='TestAccTranscribeVocabularyFilter_'  -timeout 180m
=== RUN …
```
=> New Resource: aws_transcribe_vocabulary_filter

website/docs/r/lb_target_group.html.markdown
From AWS documentation (https://docs.aws.amazon.com/elasticloadbalancing/latest/application/target-group-health-checks.html):
```
HealthCheckTimeoutSeconds | The amount of time, in seconds, during which no response from a                                 target means a failed health check. The range is 2–120 …
```
=> Change documentation to reflect default timeout of 5 seconds vs 6 seconds

website/docs/r/redshift_cluster.html.markdown
This PR updates the documentation for the `aws_redshift_cluster` resource. It clarifies the situation where `bucket_name` is required and adds the log type values that can be used in the `log_exports` argument.
=> Clarify `aws_redshift_cluster` audit logging documentation

.changelog/25922.txt, internal/service/storagegateway/gateway.go
Closes #25917
```console
% make testacc TESTS=TestAccStorageGatewayGateway_GatewayType PKG=storagegateway 
TF_ACC=1 go test ./internal/service/storagegateway/... -v -count 1 -parallel 20 -run='TestAccStorageGatewayGateway_GatewayType'  -timeout 180m
--- PASS: …
```
=> storagegateway: Rate limit error fix

examples/api-gateway-rest-api-openapi/tls.tf
=> examples/apigateway: Fix read-only attribute

internal/service/meta/arn_data_source_test.go
```console
% make testacc TESTARGS='-run=TestAccMetaARNDataSource_' PKG=meta ACCTEST_PARALLELISM=2
TF_ACC=1 go test ./internal/service/meta/... -v -count 1 -parallel 2  -run=TestAccMetaARNDataSource_ -timeout 180m
=== RUN   TestAccMetaARNDataSource_basic
=== PAUSE TestAccMetaARNDataSource_basic
=== …
```
=> d/aws_arn: Additional acceptance test to ensure backwards compatibility (TF Plugin FW)

.changelog/25941.txt, internal/service/ce/anomaly_subscription.go, internal/service/ce/anomaly_subscription_test.go
Closes #25930
```
$ make testacc TESTS=TestAccCEAnomalySubscription_MonitorARNList PKG=ce
TF_ACC=1 go test ./internal/service/ce/... -v -count 1 -parallel 20 -run='TestAccCEAnomalySubscription_MonitorARNList'  -timeout 180m
=== RUN …
```
=> Fix aws_ce_anomaly_subscription crash on update of monitor_arn_list

website/docs/r/rolesanywhere_profile.html.markdown
The IAM role trust policy to use was incorrect, per https://docs.aws.amazon.com/rolesanywhere/latest/userguide/getting-started.html#getting-started-step1
=> Fix documentation of aws_rolesanywhere_profile

website/docs/d/ecs_task_definition.html.markdown
The `aws_ecs_task_definition` data source exposes the `id` attribute (not the `arn` attribute) which is actually the `ARN` of the Task Definition.
```
...
```
=> Doc: Update data.aws_ecs_task_definition arn attribute

.ci/.semgrep.yml, internal/enum/validate.go, internal/enum/values.go, internal/service/kendra/experience.go, internal/service/kendra/faq.go, internal/service/kendra/index.go, internal/service/kendra/query_suggestions_block_list.go, internal/service/kendra/thesaurus.go, internal/service/route53domains/registered_domain.go
The AWS SDK for Go v2 uses strongly-typed string enums. This means we need to add conversion functions to strings for various uses, such as validation and waiter functions.
Adds:
* `enum.Validate[T]() schema.SchemaValidateDiagFunc` for field validation
* `enum.Values[T]() []string` to return list of all values as slice of strings
* `enum.Slice[T](l ...T) []string` to convert a slice of enum values to a slice of strings
Usage Examples
```diff
- ValidateFunc: validation.StringInSlice(faqFileFormatValues(types.FaqFileFormat("").Values()...), false),
+ ValidateDiagFunc: enum.Validate[types.FaqFileFormat](),
```
```diff
stateConf := &resource.StateChangeConf{
- 	Pending: FaqStatusValues(types.FaqStatusCreating, "PENDING_CREATION"), // API currently returns PENDING_CREATION instead of CREATING …
```
=> provider: Add functions to convert AWS SDK v2 enums to strings

internal/conns/envvar.go
Replace occurrences of `at lease` with `at least`
```
...
```
=> fix typos in code comments

website/docs/r/appstream_stack.html.markdown
Closes #25950
As pointed out in the linked issue, the `aws_appstream_stack` resource was missing the documentation for the `access_endpoints` argument block. This PR aims to add the appropriate documentation.
- [Relevant part of the resource schema](https://github.com/hashicorp/terraform-provider-aws/blob/632cff7679cb …
=> Add `aws_appstream_stack.access_endpoints` documentation

website/docs/r/glue_connection.html.markdown
Closes #25928
The `aws_glue_connection` resource had an outdated list of supported `connection_types`. This PR aims to update and alphabetize the list of supported types.
- [`aws_glue_connection` resource schema](https://github.com/hashicorp/terraform-provider-aws/blob/632cff7679cb6e1e14076b9aac3e68b73f584b70/internal …
=> Add additional supported values to `aws_glue_connection.connection_types`

website/docs/index.html.markdown
Closes #25813
As pointed out in the linked issue, the documentation index examples still showed version `~> 3.0`. This PR bumps the version to `~> 4.0`.
=> Bump provider version in index examples

website/docs/r/transfer_server.html.markdown
Closes #26007
AWS [recently added](https://aws.amazon.com/about-aws/whats-new/2022/07/aws-transfer-family-support-applicability-statement-2-as2/) `AS2` as a supported protocol for AWS Transfer Server. This PR updates the `aws_transfer_server` docs to include `AS2` as a valid value in the `protocols` argument.
- …
=> Add AS2 as valid protocol for `aws_transfer_server.protocols`

website/docs/r/lb_target_group_attachment.html.markdown
Looks like this was a typo [when the example was first introduced](https://github.com/hashicorp/terraform-provider-aws/commit/c1829d1ce400330e514ff3137e9b7b9c40dfbf41).
=> Docs for Target Group Attachment use function_name

website/docs/r/cognito_identity_pool_roles_attachment.markdown
I noticed that the identity pool ID in the import example for aws_cognito_identity_pool_roles_attachment isn't formatted correctly. It looks more like a user pool ID and doesn't pass the validation for the [GetIdentityPoolRoles](https://docs.aws.amazon.com/cognitoidentity/latest/APIReference/API_GetIdentityPoolRoles.html#API_GetIdentityPoolRoles_RequestSyntax) API call. I figured I would open a PR since it misled me into trying to use the wrong ID for a good 30 minutes.
* Please do not leave "+1" or other comments that do not add relevant new …
=> Fixed import example for aws_cognito_identity_pool_roles_attachment

.changelog/26010.txt, internal/service/networkmanager/core_network_policy_document_data_source_test.go, internal/service/networkmanager/core_network_policy_model.go
Closes #26009
```
$ make testacc TESTS=TestAccNetworkManagerCoreNetworkPolicyDocumentDataSource_basic PKG=networkmanager
=== RUN   TestAccNetworkManagerCoreNetworkPolicyDocumentDataSource_basic
=== PAUSE TestAccNetworkManagerCoreNetworkPolicyDocumentDataSource_basic
=== CONT …
```
=> d/aws_networkmanager_core_network_policy_document attachment-policy.action.require-acceptance can only be true or omitted 

.changelog/26012.txt, internal/service/appmesh/gateway_route.go
fixes the following error when using the app mesh rewrite configuration:
```
Stack trace from the terraform-provider-aws_v4.23.0_x5 plugin:
panic: runtime error: index out of range [0] with length 0
goroutine 403 [running]:
github.com/hashicorp/terraform-provider-aws/internal/service/appmesh.expandHTTPGatewayRouteRewrite({0xc0033f4ae0, 0xc002f78bc0, 0xa5dbe7c})
github.com/hashicorp/terraform-provider-aws/internal/service/appmesh/gateway_route.go:783 +0x3c9
github.com/hashicorp/terraform-provider-aws/internal/service/appmesh.expandHTTPGatewayRoute({0xc0033f4a40, 0xc002f751d0, 0xa5e66c8})
github.com/hashicorp/terraform-provider-aws/internal/service/appmesh/gateway_route.go:854 +0x195
github.com/hashicorp/terraform-provider-aws/internal/service/appmesh.expandGatewayRouteSpec({0xc0033f4a10, …
```
=> appmesh: added missing nil checks on rewrite configuration properties

.changelog/25992.txt, internal/service/guardduty/guardduty_test.go, internal/service/guardduty/organization_configuration.go, internal/service/guardduty/organization_configuration_test.go, website/docs/r/guardduty_organization_configuration.html.markdown
Closes #25992
~**_Requires update to 1.44.63_** Tested with 1.44.63 draft until sdk is updated~
```
nick@nick1 terraform-provider-aws % make testacc TESTARGS='-run=TestAccGuardDuty_serial/OrganizationConfiguration' PKG=guardduty ACCTEST_PARALLELISM=2 …
```
=> Guardduty: organization malware protection configuration #25992

website/docs/r/route53_record.html.markdown
Update documentation for `aws_route53_record` - the `ttl` property is always numeric - so update all string usages to be integers for consistency.
=> Set `aws_route53_record` resource example `ttl` properties to all integers

.github/workflows/goreleaser-ci.yml, .goreleaser.yml
Restores `.goreleaser.yml` to project root to prevent release failures.
=> Moves `.goreleaser.yml` back to project root

.changelog/26082.txt, internal/service/iam/role_policy.go, internal/service/iam/validate.go, internal/service/iam/validate_test.go, website/docs/r/iam_role_policy.html.markdown
Closes https://github.com/hashicorp/terraform-provider-aws/issues/26081
```
$ make testacc TESTARGS='-run=TestAccIAMRolePolicy_' PKG=iam
TF_ACC=1 go test ./internal/service/iam/... -v -count 1 -parallel 20  -run=TestAccIAMRolePolicy_ -timeout 180m
=== RUN …
```
=> r/iam_role_policy: add plan time validation to role argument

internal/acctest/acctest.go, internal/acctest/provider_test.go
Closes https://github.com/hashicorp/terraform-provider-aws/issues/26098.
```console
% make testacc TESTARGS='-run=TestAccProvider_' PKG_NAME=internal/acctest ACCTEST_PARALLELISM=3
TF_ACC=1 go test ./internal/acctest/... -v -count 1 -parallel 3  -run=TestAccProvider_ -timeout 180m
=== RUN …
```
=> Avoid use of the `aws_arn` data source in the provider's own acceptance tests

.changelog/26110.txt, internal/service/directconnect/location_data_source.go, internal/service/directconnect/location_data_source_test.go, website/docs/d/dx_location.html.markdown
Adds support for retrieving available MACsec port speeds with the `aws_dx_location` data source
Relates #21082
```
$ make testacc TESTS=TestAccDirectConnectLocationDataSource_basic PKG=directconnect
TF_ACC=1 go test ./internal/service/directconnect/... -v -count 1 …
```
=> f-data-aws_dx_location-add-macsec

.changelog/19856.txt, internal/provider/provider.go, internal/service/macie2/classification_export_configuration.go, internal/service/macie2/classification_export_configuration_test.go, internal/service/macie2/macie2_test.go, website/docs/r/macie2_classification_export_configuration.html.markdown
Closes #19856
Two things:
- Import doesn't care about IDs, there's only one resource, the API takes care of not found, etc. Documentation has a [dummy](https://github.com/hashicorp/terraform-provider-aws/compare/main...nickyamanaka:terraform-provider-aws:f-macie-classification-export-configuration-%2319856#diff-9633ced2359ae626d559a836fc7050965c7e891d822fa161 …
=> Macie Macie2 Classification Results - Export Configuration #19856

.ci/.semgrep-caps-aws-ec2.yml, .ci/.semgrep.yml, .github/workflows/documentation.yml, .github/workflows/examples.yml, .github/workflows/firewatch.yml, .github/workflows/generate_changelog.yml, .github/workflows/issues.yml, .github/workflows/milestone.yml, .github/workflows/post_publish.yml, .github/workflows/project.yml, .github/workflows/pull_requests.yml, .github/workflows/release.yml, .github/workflows/roadmap_milestone.yml, .github/workflows/semgrep-ci.yml, .github/workflows/stale.yml, .github/workflows/team_slack_bot.yml, .github/workflows/website.yml, .github/workflows/yaml-lint.yml, .github/workflows/yamllint.yml, .yamllint, GNUmakefile, examples/ecs-alb/cloud-config.yml, internal/generate/servicesemgrep/main.go, internal/service/cloudformation/testdata/examplecompany-exampleservice-exampleresource/resource-role.yaml, internal/service/cloudformation/testdata/examplecompany-exampleservice-exampleresource/template.yml
Adds [`yamllint`](https://yamllint.readthedocs.io/en/stable/) linting for all YAML files.
Uses the [default ruleset](https://yamllint.readthedocs.io/en/stable/configuration.html#default-configuration) with the following exceptions:
* Requires only 1 space before comments (default is 2)
* Does not require the document start marker (`---`)
* Does not limit line length
* Does not check for truthy values in keys. Otherwise this would flag the `on` key in GitHub workflows
Adds GitHub workflow and makefile rule
=> linting: Add `yamllint`

website/docs/r/flow_log.html.markdown
Encountered the following error with Transit Gateway and Transit Gateway attachment flow logs: `Error: error creating Flow Log (tgw-xxxxxx): InvalidParameter: max-aggregation-interval other than 60 sec / 1 min is not supported when the resource-type is TransitGateway or TransitGatewayAttachment` 
```
$ …
```
=> Update documentation for Transit Gateway Flow Logs

.changelog/26061.txt, internal/provider/provider.go, internal/service/location/tracker_association.go, internal/service/location/tracker_association_test.go, website/docs/r/location_tracker_association.html.markdown
```
$ make testacc PKG=location TESTS="TestAccLocationTrackerAssociation_"
TF_ACC=1 go test ./internal/service/location/... -v -count 1 -parallel 20 -run='TestAccLocationTrackerAssociation_'  -timeout 180m
=== RUN …
```
=> r/aws_location_tracker_association: new resource

internal/service/location/tracker_association_test.go
Relates https://github.com/hashicorp/terraform-provider-aws/pull/26061.
Relates #26147.
```
...
```
=> Fix semgrep `ci.avoid-context-TODO-in-tests`

.changelog/26194.txt, internal/service/elbv2/const.go, internal/service/elbv2/listener.go, internal/service/elbv2/listener_test.go, internal/service/elbv2/target_group.go, internal/service/elbv2/target_group_test.go, internal/verify/verify.go
Closes #19888
Closes #20144
```console
$ make testacc TESTS=TestAccELBV2Listener_ PKG=elbv2
TF_ACC=1 go test ./internal/service/elbv2/... -v -count 1 -parallel 20 -run='TestAccELBV2Listener_'  -timeout 180m
=== RUN   TestAccELBV2Listener_basic
=== PAUSE …
```
=> r/aws_lb_listener: update tags after creation

website/docs/r/apigatewayv2_integration.html.markdown
According to the [AWS documentation](https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-api-integration-types.html) integration type should be `AWS_PROXY` for Lambda functions. This really tripped me up for a while since it seems like the example is just wrong here.
Previously was getting the following error when trying to use `AWS` like the example shows:
> Error: error creating API Gateway v2 integration: BadRequestException: Currently, an API with a protocol type of HTTP may only be associated with proxy integrations (AWS_PROXY, HTTP_PROXY)
=> Changing Lambda Integration Type to AWS_PROXY

.changelog/26220.txt, internal/service/ec2/vpc_security_group_rule.go, internal/service/ec2/vpc_security_group_rule_test.go
Closes https://github.com/hashicorp/terraform-provider-aws/issues/26191.
Before fix:
```console
% make testacc TESTARGS='-run=TestAccVPCSecurityGroupRule_prefixListEmptyString' PKG=ec2
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 20 …
```
=> r/aws_security_group_rule: Prevent crash when empty strings in `prefix_list_ids`

website/docs/r/rds_global_cluster.html.markdown
Relates #26030
This PR aims to fix a dependency issue that caused the following error in the linked issue:
```shell
Error: error creating RDS cluster: InvalidParameterValue: The parameter MasterUsername must be provided and must not be blank.     status code: 400, request id: d2f13469-f46f-4578-bded-4cb6a523b844
with …
```
=> Correct `aws_rds_global_cluster` 'New MySQL Global Cluster' example

.changelog/26045.txt, internal/service/elasticsearch/domain.go, internal/service/elasticsearch/domain_data_source.go, internal/service/elasticsearch/domain_data_source_test.go, internal/service/elasticsearch/domain_test.go, internal/service/elasticsearch/flex.go, internal/service/opensearch/domain.go, internal/service/opensearch/domain_data_source.go, internal/service/opensearch/domain_data_source_test.go, internal/service/opensearch/domain_test.go, internal/service/opensearch/flex.go, website/docs/d/elasticsearch_domain.html.markdown, website/docs/d/opensearch_domain.html.markdown, website/docs/r/elasticsearch_domain.html.markdown, website/docs/r/opensearch_domain.html.markdown
Closes #26045
```
nick@nick1 terraform-provider-aws % make testacc TESTARGS='-run=TestAccOpenSearchDomainDataSource_Data_basic' PKG=opensearch ACCTEST_PARALLELISM=1
TF_ACC=1 go test ./internal/service/opensearch/... -v -count 1 -parallel 1 …
```
=> aws_elasticsearch_domain add throughput attr 26045

internal/service/elasticsearch/domain_data_source_test.go, internal/service/elasticsearch/domain_test.go, internal/service/opensearch/domain_data_source_test.go, internal/service/opensearch/domain_test.go
Closes https://github.com/hashicorp/terraform-provider-aws/issues/26249.
```console
% ACCTEST_TIMEOUT=600m make testacc TESTARGS='-run=TestAccOpenSearchDomain_basic' PKG=opensearch ACCTEST_PARALLELISM=3
TF_ACC=1 go test ./internal/service/opensearch/... -v -count 1 -parallel 3 …
```
=> Generate fixed-length OpenSearch & Elasticsearch random domain names in acceptance tests

.changelog/26257.txt, internal/service/dynamodb/table.go, internal/service/dynamodb/table_test.go, website/docs/r/dynamodb_table.html.markdown
Closes #26255
```console
% make testacc TESTS=TestAccDynamoDBTable_ PKG=dynamodb 
TF_ACC=1 go test ./internal/service/dynamodb/... -v -count 1 -parallel 20 -run='TestAccDynamoDBTable_'  -timeout 180m
--- PASS: TestAccDynamoDBTable_attributeUpdateValidation (48.61s)
--- …
```
=> dynamodb_table: Fix `replica.*propagate_tags` bug

.github/workflows/release.yml
Goreleaser, by default, sets parallelism to the number of cores on the machine. This could result in each build not having enough memory to compile successfully.
=> add goreleaser arg to change default parallelism

.changelog/26283.txt, internal/service/chime/voice_connector_logging.go, internal/service/chime/voice_connector_logging_test.go, website/docs/r/chime_voice_connector_logging.html.markdown
Adds an attribute to allow control of media metric monitoring.
```console
$ make testacc TESTARGS='-run=TestAccChimeVoiceConnectorLogging_' PKG=chime
go test ./internal/service/chime/... -v -count 1 -parallel 20  -run=TestAccChimeVoiceConnectorLogging_ -timeout 180m
=== RUN   TestAccChimeVoiceConnectorLogging_basic
=== PAUSE …
```
=> aws_chime_voice_connector_logging - Enable Media Metrics Logging

.changelog/26289.txt, CHANGELOG.md, internal/service/appflow/flow.go, internal/service/appflow/flow_test.go
When setting up an AppFlow with a Scheduled trigger and setting the `schedule_start_time` value, it actually sets the `scheduled_end_time` value and the app flow is not active
eg.
input
```
trigger_config {
trigger_type = "Scheduled"
trigger_properties {
scheduled {
data_pull_mode      = "Incremental"
schedule_expression = "rate(3hours)"
schedule_start_time …
```
=> AppFlow trigger start date being incorrectly set

.changelog/26286.txt, internal/service/rds/find.go, internal/service/rds/instance.go, internal/service/rds/instance_test.go
Closes https://github.com/hashicorp/terraform-provider-aws/issues/26280.
```console
% make testacc TESTARGS='-run=TestAccRDSInstance_finalSnapshotIdentifier\|TestAccRDSInstance_FinalSnapshotIdentifier_skipFinalSnapshot\|TestAccRDSInstance_noDeleteAutomatedBackups\|TestAccRDSInstance_basic\|TestAccRDSInstance_isAlreadyBeingDeleted' PKG=rds …
```
=> r/aws_db_instance: Don't call `ModifyDBInstance` when just `final_snapshot_identifier` is changed

.changelog/26281.txt, internal/service/acm/certificate.go, internal/service/acm/certificate_test.go, website/docs/r/acm_certificate.html.markdown
```
$ make testacc TESTARGS='-run=TestAccACMCertificate_' PKG=acm
TF_ACC=1 go test ./internal/service/acm/... -v -count 1 -parallel 20 -run='TestAccACMCertificate_'  -timeout 180m
=== RUN   TestAccACMCertificate_Imported_domainName
=== PAUSE …
```
=> aws_acm_certificate - Add validity dates

website/docs/d/iam_policy.html.markdown
The documentation page for the `aws_iam_policy` data source does not mention the `arn` attribute. However, the attribute is available on the data source as you can also see [here](https://github.com/hashicorp/terraform-provider-aws/blob/v4.24.0/internal/service/iam/policy_data_source.go#L101).
This PR adds `arn` to the Attributes Reference.
=> Add missing attribute to iam policy data source docs

website/docs/r/cloudwatch_log_subscription_filter.html.markdown
Working example for those, who don't want to filter anything. Filter pattern ""
is the correct way to do it. This should prevent people trying filter pattern " "
mentioned in Amazon documentation.
---
Relates #26319 
I did not run any tests :innocent:
=> cloudwatch_log_subscription_filter: better filter_pattern description

website/docs/r/codebuild_project.html.markdown
See https://docs.aws.amazon.com/cli/latest/reference/codebuild/create-project.html
I tested with GITHUB type secondary source, expecting cloned directory name to match source identifier as per docs but it did not. I checked AWS API docs and this feature is not or no longer supported.
=> fix secondary_sources.source_identifer doc

.changelog/26320.txt, internal/service/elbv2/target_group.go, internal/service/elbv2/target_group_test.go, website/docs/r/lb_target_group.html.markdown
Closes #26312
```
$ make testacc TESTARGS='-run=TestAccELBV2TargetGroup_basic\|TestAccELBV2TargetGroup_udp\|TestAccELBV2TargetGroup_ALBAlias_lambda\|TestAccELBV2TargetGroup_backwardsCompatibility\|TestAccELBV2TargetGroup_ipAddressType' PKG=elbv2 ACCTEST_PARALLELISM=3 …
```
=> Add `ip_address_type` support to elbv2 target group

.github/workflows/pull_requests.yml
Signed-off-by: Stano Bocinec <stano@redpanda.com>
This PR fixes the incorrect FAQ and Contributor guide links in the `PullRequestComments` step in the `pul_requests` github-actions workflow. Currently, the links returns 404.
Changes:
* FAQ: https://github.com/hashicorp/terraform-provider-aws/blob/main/docs/contributing/faq.md -> https://hashicorp.github.io/terraform-provider-aws/faq/
* CONTRIBUTOR GUIDE: https://github.com/hashicorp/terraform-provider-aws/blob/main/docs/contributing -> https://hashicorp.github.io/terraform-provider-aws/
* Please …
=> d/github/pr: fix faq & contrib guide links in the PR workflow

.changelog/26334.txt, internal/service/inspector/assessment_template.go, internal/service/inspector/assessment_template_test.go, internal/service/inspector/find.go, website/docs/r/inspector_assessment_template.html.markdown
Adds support to enable SNS topic subscriptions to specific assessment template events.
Supersedes #12261.
Resolves #843.
```sh
❯ make testacc TESTS=TestAccInspectorAssessmentTemplate PKG=inspector
--- PASS: TestAccInspectorAssessmentTemplate_disappears (21.28s)
--- PASS: TestAccInspectorAssessmentTemplate_basic (22.17s)
--- …
```
=> inspector: Add support for SNS subscriptions

website/docs/r/route53_record.html.markdown
To find with CMD+F the documentation of following config blocks:
* `alias`
* `failover_routing_policy`
* `geolocation_routing_policy`
* `latency_routing_policy`
* `weighted_routing_policy`
```
...
```
=> docs(route53_record): add references to block descriptions

skaff/datasource/websitedoc.tmpl
Applying changes from #25949 to data source website template.
Before & after:
```
$ diff old.html.markdown new.html.markdown 
4c4
< page_title: "AWS: aws_location_trackerassociation"
---
> page_title: "AWS: aws_location_tracker_association"
9c9
< # Data Source: aws_location_trackerassociation
---
> # Data Source: aws_location_tracker_association
18c18
< data …
```
=> skaff: Use snake name in data source website docs

.changelog/26407.txt, internal/service/glue/job.go, internal/service/glue/job_test.go, website/docs/r/glue_job.html.markdown
Closes #26350 
```
$ make testacc TESTS=TestAccGlueJob_pythonShell PKG=glue
TF_ACC=1 go test ./internal/service/glue/... -v -count 1 -parallel 20 -run='TestAccGlueJob_pythonShell'  -timeout 180m
=== RUN   TestAccGlueJob_pythonShell
=== PAUSE TestAccGlueJob_pythonShell …
```
=> Add support for python_version 3.9 in aws_glue_job

.changelog/26308.txt, internal/service/ec2/ec2_eip.go
Signed-off-by: Stano Bocinec <stano@redpanda.com>
Closes #25567
```shell
$ make testacc TESTS=TestAccEC2EIP_Tags PKG=ec2 AWS_REGION=eu-north-1                                                                  ==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 …
```
=> fix(ec2_eip): Fix default tags not set, #25567

website/docs/r/imagebuilder_distribution_configuration.html.markdown
Closes #26401
The documentation for `aws_imagebuilder_distribution_configuration` currently states that there is a top-level argument of `kms_key_id`. This argument does not exist within the resource schema (note that there is a documented and valid `distribution.ami_distribution_configuration.kms_key_id` argument). …
=> Remove erroneous reference to `aws_imagebuilder_distribution_configuration.kms_key_id` argument

.changelog/26451.txt, internal/service/firehose/delivery_stream.go, internal/service/firehose/delivery_stream_test.go
Closes #25396
```
$ AWS_DEFAULT_REGION=eu-west-1 AWS_SDK_LOAD_CONFIG=1 AWS_PROFILE=dev make testacc TESTS=TestAccFirehoseDeliveryStream_tagUpdates PKG=firehose
TF_ACC=1 go test ./internal/service/firehose/... -v -count 1 -parallel 20 …
```
=> fix: Tag changes do not cause updates to firehose destinations

.changelog/26454.txt, .ci/.tflint.hcl, .github/workflows/acctest-terraform-lint.yml, internal/service/appstream/fleet.go, internal/service/appstream/fleet_test.go
Closes #24798
```console
% make testacc TESTS=TestAccAppStreamFleet PKG=appstream
TF_ACC=1 go test ./internal/service/appstream/... -v -count 1 -parallel 20 -run='TestAccAppStreamFleet'  -timeout 180m
=== RUN   TestAccAppStreamFleetStackAssociation_basic
=== PAUSE …
```
=> appstream_fleet: Fix empty domain_join bug

website/docs/r/elb.html.markdown
Closes #26458
As mentioned in the linked issue, the documentation mentioned the default value for `aws_elb.access_logs.interval`, but did not mention that there are only 2 valid values. This edit aims to make it clear that the only options are `5` and `60`.
- [AWS …
=> Clarify valid values for `aws_elb.access_logs.interval`

website/docs/r/accessanalyzer_archive_rule.html.markdown
Closes #26463
This PR fixes a misspelling of the `analyzer_name` argument in the example on the `aws_accessanalyzer_archive_rule` resource.
=> Correct spelling of argument in example of `aws_accessanalyzer_archive_rule`

.changelog/26493.txt, internal/service/ec2/ec2_fleet.go, internal/service/ec2/ec2_fleet_test.go, internal/service/ec2/ec2_spot_fleet_request.go, internal/service/ec2/ec2_spot_fleet_request_test.go, internal/service/ec2/status.go, internal/service/ec2/wait.go, website/docs/r/ec2_fleet.html.markdown, website/docs/r/spot_fleet_request.html.markdown
feat: add target_capacity_unit_type to ec2_fleet and ec2_spot_fleet_request resources
Closes #25777
```zsh
terraform-provider-aws on  f-aws_ec2_fleet-aws_spot_fleet_request-add-target_capacity_unit_type [!] via 🐹 v1.18.4 took 2s
[I] ➜ make testacc TESTS=TestAccEC2Fleet_TargetCapacitySpecification_targetCapacityUnitType …
```
=> feat: add target_capacity_unit_type to ec2_fleet and ec2_spot_fleet_request resources

.changelog/26411.txt, internal/service/dms/endpoint.go, internal/service/dms/endpoint_test.go, website/docs/r/dms_endpoint.html.markdown
=> aws_dms_endpoint redis target settings bug fix

internal/service/location/tracker_association_data_source.go
```
$ make testacc PKG=location TESTS="TestAccLocationTrackerAssociationDataSource_"
TF_ACC=1 go test ./internal/service/location/... -v -count 1 -parallel 20 -run='TestAccLocationTrackerAssociationDataSource_'  -timeout 180m
=== RUN …
```
=> d/aws_location_tracker_association: remove unnecessary ForceNew

.changelog/26472.txt, internal/provider/provider.go, internal/service/location/tracker_associations_data_source.go, internal/service/location/tracker_associations_data_source_test.go, website/docs/d/location_tracker_associations.html.markdown
```
$ make testacc PKG=location TESTS="TestAccLocationTrackerAssociationsDataSource_"
TF_ACC=1 go test ./internal/service/location/... -v -count 1 -parallel 20 -run='TestAccLocationTrackerAssociationsDataSource_'  -timeout 180m
=== RUN …
```
=> d/aws_location_tracker_associations: new data source

.changelog/26503.txt, internal/service/elasticsearch/domain_data_source_test.go, internal/service/elasticsearch/domain_test.go, internal/service/opensearch/domain.go, internal/service/opensearch/domain_structure.go, internal/service/opensearch/domain_test.go, website/docs/r/opensearch_domain.html.markdown
Closes #22955
```console
% make testacc TESTS=TestAccOpenSearchDomain_AdvancedSecurityOptions PKG=opensearch 
TF_ACC=1 go test ./internal/service/opensearch/... -v -count 1 -parallel 20 -run='TestAccOpenSearchDomain_AdvancedSecurityOptions'  -timeout 180m
--- PASS: …
```
=> opensearch/domain: Allow fine-grained access control to be enabled

website/docs/r/ec2_managed_prefix_list_entry.html.markdown
Summary: 
Made a small update to the documentation for the `ec2_managed_prefix_list_entry` resource.  The issue was originally reported on the forums here: https://discuss.hashicorp.com/t/example-page-for-aws-managed-prefix-list-and-entry-has-an-error/43650.
Acceptance tests not ran since this was a documentation update.
=> d/ec2_managed_prefix_list_entry - updated example

.changelog/26532.txt, internal/service/ec2/ec2_instance.go, internal/service/ec2/ec2_instance_data_source.go, internal/service/ec2/ec2_instance_test.go, internal/service/ec2/ec2_instances_data_source_test.go, website/docs/d/instance.html.markdown, website/docs/r/instance.html.markdown
Closes #16995.
Closes #17282.
Supersedes https://github.com/hashicorp/terraform-provider-aws/pull/17282. 
**NOTE:** We cannot easily test this solution. We have determined that it does not seem to cause any regressions and should work. However, this is best-effort functionality. We would love to hear from you if you use this functionality and it does or …
=> ec2/instance: Dedicated host resource group compatibility

website/docs/r/eks_node_group.html.markdown
Closes #26535
The way the example was previous set up, the `update_config.max_unavailable` value was greater than the `scaling_config.max_size` value, leading to the following error:
```shell
Error: error creating EKS Node Group (<example>): InvalidParameterException: max-unavailable must be within the range 1 and …
```
=> Correct `scaling_config` and `update_config` values in `aws_eks_node_group` docs

.changelog/24772.txt, internal/service/wafv2/flex.go, internal/service/wafv2/rule_group_test.go, internal/service/wafv2/schemas.go, internal/service/wafv2/web_acl_test.go, website/docs/r/wafv2_rule_group.html.markdown, website/docs/r/wafv2_web_acl.html.markdown
Closes #18515.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/25845.
```
$ make testacc TESTS=TestAccWAFV2WebACL_ByteMatchStatement PKG=wafv2
TF_ACC=1 go test ./internal/service/wafv2/... -v -count 1 -parallel 20 …
```
=> Support json body matching in wafv2 byte match rule

.changelog/26553.txt, GNUmakefile, go.sum, internal/service/ec2/errors.go, internal/service/ec2/vpc_default_security_group.go, internal/service/ec2/vpc_default_security_group_test.go, internal/service/ec2/vpc_security_group.go, internal/service/ec2/vpc_security_group_rule.go, internal/service/ec2/vpc_security_group_rule_test.go, internal/service/ec2/vpc_security_group_test.go, website/docs/r/default_security_group.html.markdown, website/docs/r/security_group.html.markdown
Closes #1671
Closes #8285
Closes #8769
Relates #10329 
Closes #12394
Relates #12396
Closes #12420
Closes #13228
Closes #16165
Relates #18559
Closes #19932
Closes #20035
Closes #20405
Closes #20743
Closes #20925
Relates #23488 
Closes #26090
```console
% make testacc TESTS=TestAccVPCSecurityGroup_ PKG=ec2         
==> Checking …
```
=> vpc/security_group: Fix complex dependency violations

website/docs/r/redshiftserverless_workgroup.html.markdown
Fix small duplication typo in documentation.
=> Redshift Serverless (Workgroup) doc typo correction

website/docs/r/ce_anomaly_subscription.html.markdown
Closes #26505
As called out in the linked issue, the arguments for `aws_ce_anomaly_monitor` were incorrect. This PR corrects them.
- Related PR: #25301
- [`aws_ce_anomaly_monitor` docs](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ce_anomaly_monitor)
=> Correct `aws_ce_anomaly_monitor` arguments in `aws_ce_anomaly_subscription` docs

.changelog/25259.txt, internal/service/lambda/function.go, internal/service/lambda/function_test.go
=> r/aws_lambda_function: Added Lambda function name validation

internal/service/rds/instance_test.go, website/docs/r/db_instance.html.markdown, website/docs/r/rds_cluster_instance.html.markdown
Summary of changes:
* Updated the documentation for the `performance_insights_retention_period` attribute for the `aws_db_instance` resource to reflect support for retention period support in months.
* Added new acceptance test to for the monthly retention period for the `aws_db_instance` resource`.
* Minor spelling change to the `rds_cluster_instance` …
=> d/aws_db_instance - updated performance insights retention period

go.mod, go.sum, internal/conns/awsclient_gen.go, internal/conns/config.go, internal/conns/config_gen.go, internal/service/identitystore/group_data_source.go, internal/service/identitystore/user_data_source.go, names/names.go, names/names_data.csv
Relates https://github.com/hashicorp/terraform-provider-aws/issues/26598
AWS Go SDK v2 is required to update user and group attributes. (https://docs.aws.amazon.com/singlesignon/latest/IdentityStoreAPIReference/API_AttributeOperation.html)
The `Filter` attribute of the `ListUsers` and `ListGroups` API-s has been deprecated in favour of `GetUserId` and …
=> Migrate the Identity Store service to AWS Go SDK v2

.changelog/26629.txt, internal/service/eks/addon.go, internal/service/eks/wait.go, website/docs/r/eks_addon.html.markdown
Relates #26474 
I did not exercise acceptance tests on this change because the related aws_eks_cluster does not exercise Timeout settings in its acceptance tests.
=> F aws eks addon add timeouts

.changelog/26636.txt, internal/provider/provider.go, internal/service/redshiftserverless/find.go, internal/service/redshiftserverless/usage_limit.go, internal/service/redshiftserverless/usage_limit_test.go, internal/service/redshiftserverless/workgroup.go, website/docs/r/redshiftserverless_usage_limit.html.markdown
```
$ make testacc TESTS=TestAccRedshiftServerlessUsageLimit_ PKG=redshiftserverless
--- PASS: TestAccRedshiftServerlessUsageLimit_basic (507.03s)
--- PASS: TestAccRedshiftServerlessUsageLimit_disappears (526.65s)
```
=> r/aws_redshiftserverless_usage_limit - new resource

.changelog/26631.txt, internal/service/ec2/ec2_instance.go, internal/service/ec2/ec2_instance_test.go
Some AWS regions, such as `me-central-1` do not currently support Instance Metadata Tags. The default value supplied by the provider was causing the provider to fail in some cases.
Closes #26561
Previously:
```
$ AWS_REGION=me-central-1 make testacc PKG=ec2 TESTS=TestAccEC2Instance_metadataOptions
Error: updating EC2 Instance (i-abc123) metadata options: UnsupportedOperation: Specifying InstanceMetadataTags is not yet supported in this region.
```
Now (changing expected `instance_metadata_tags` to `""`)
```
--- PASS: TestAccEC2Instance_metadataOptions (291.19s)
```
Relates https://github.com/hashicorp/terraform-provider-aws/issues/25227.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/25778.
=> resource/aws_instance: Handle regions where instance metadata tags are unsupported

.changelog/26608.txt, internal/provider/provider.go, internal/service/medialive/medialive_test.go, internal/service/medialive/multiplex.go, internal/service/medialive/multiplex_test.go, internal/service/medialive/sweep.go, website/docs/r/medialive_multiplex.html.markdown
Relates #4936
```console
$ make testacc TESTS=TestAccMediaLiveMultiplex_ PKG=medialive
TF_ACC=1 go test ./internal/service/medialive/... -v -count 1 -parallel 20 -run='TestAccMediaLiveMultiplex_'  -timeout 180m
=== RUN   TestAccMediaLiveMultiplex_basic
=== PAUSE …
```
=> r/aws_medialive_multiplex: add CRUD operations

.changelog/26657.txt, internal/service/iam/policy_document_data_source_test.go, internal/service/iam/policy_model.go
Handle situation where we import a policy with a bool value in a condition.
[Quoting](https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_grammar.html#policies-grammar-json) AWS 
>Values are enclosed in quotation marks. Quotation marks are optional for numeric and Boolean values
This merge addresses the issue raised in 26485. However we may still see a scenario where we do not handle an unquoted numeric or a list of unquoted bool or numeric. I can look at addressing these problems in a separate merge or is it worth handling these issues in this merge?
Thanks
* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and …
=> Handle bool value in condition when importing json policy

website/docs/r/db_proxy_endpoint.html.markdown
The old page still exists but doesn't contain the anchor nor any specific endpoint documentation, thus I figured to switch to the new link.
=> Fix link to RDS proxy endpoints

website/docs/d/prometheus_workspace.html.markdown
The real datasource name is aws_prometheus_workspace while the documentation ex. use aws_amp_workspace
```
...
```
=> fix(doc): update aws_prometheus_workspace data source doc with good name

website/docs/index.html.markdown
This PR removes references to HashiCorp Learn from the main documentation page. This domain will no longer exist once we launch the new developer portal with the Terraform product.
=> Remove Learn References from Overview Page

website/docs/r/sagemaker_domain.html.markdown
This PR makes it clear what type of resource the `security_groups` var expects: A list of security group IDs.
```
...
```
=> Update sagemaker domain docs

.changelog/26683.txt, internal/service/ec2/consts.go, internal/service/ec2/errors.go, internal/service/ec2/find.go, internal/service/ec2/id.go, internal/service/ec2/status.go, internal/service/ec2/vpc_managed_prefix_list.go, internal/service/ec2/vpc_managed_prefix_list_data_source.go, internal/service/ec2/vpc_managed_prefix_list_data_source_test.go, internal/service/ec2/vpc_managed_prefix_list_entry.go, internal/service/ec2/vpc_managed_prefix_list_entry_test.go, internal/service/ec2/vpc_managed_prefix_list_test.go, internal/service/ec2/vpc_security_group.go, internal/service/ec2/wait.go
Closes #26004
```
$ make testacc TESTS=TestAccVPCManagedPrefixListDataSource PKG=ec2
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 20 -run='TestAccVPCManagedPrefixListDataSource'  -timeout 180m
=== RUN   TestAccVPCManagedPrefixListDataSource_basic …
```
=> Bugfix: Use DescribeManagedPrefixListsPagesWithContext to get prefix list

.github/workflows/semgrep-ci.yml
[For example](https://github.com/hashicorp/terraform-provider-aws/runs/8236235605?check_suite_focus=true):
```
Run semgrep $COMMON_PARAMS \
Findings:
internal/service/accessanalyzer/analyzer.go 
ci.helper-schema-ResourceData-Resource-Set-tags
(schema.ResourceData).Set() call with the tags key should be preceded by a call to
IgnoreConfig or include …
```
=> semgrep 0.112 breaks `helper-schema-ResourceData-Resource-Set-tags`

.changelog/26640.txt, internal/service/iam/policy_document_data_source.go, internal/service/iam/policy_document_data_source_test.go, internal/service/iam/policy_model.go
Adds empty string and JSON validation to `aws_iam_policy_document.source_policy_documents`
Closes #26071.
Closes https://github.com/hashicorp/terraform-provider-aws/issues/23910.
```
$ ACCTEST_PARALLELISM=10 make testacc TESTS=TestAccIAMPolicyDocumentDataSource PKG=iam …
```
=> Add validation to on aws_iam_policy_document source_policy_documents

internal/service/ec2/ec2_fleet.go, internal/service/ec2/sweep.go, internal/service/ec2/wait.go
Creates sweeper for `aws_ec2_fleet`.
Closes #26630
```console
$ make sweep SWEEPERS=aws_ec2_fleet
[DEBUG] Running Sweepers for region (us-west-2):
[DEBUG] Running Sweeper (aws_ec2_fleet) in region (us-west-2)
[DEBUG] Completed Sweeper (aws_ec2_fleet) in region (us-west-2) in 4.525787176s
Completed Sweepers for region (us-west-2) in 4.526096262s
Sweeper Tests for region (us-west-2) ran successfully:
- aws_ec2_fleet
```
```
$ make testacc PKG=ec2 TESTS=TestAccEC2Fleet_
--- PASS: TestAccEC2Fleet_SpotOptions_capacityRebalance (109.46s)
--- PASS: TestAccEC2Fleet_TargetCapacitySpecificationDefaultTargetCapacityType_onDemand (110.28s)
--- PASS: TestAccEC2Fleet_TargetCapacitySpecificationDefaultTargetCapacityType_spot (110.31s)
--- PASS: …
```
=> resource/aws_ec2_fleet: Create sweeper

.github/workflows/semgrep-ci.yml, GNUmakefile, internal/generate/servicesemgrep/main.go, internal/generate/sweepimp/main.go, internal/service/apigateway/base_path_mapping.go, internal/service/appstream/directory_config_test.go, internal/service/appstream/fleet_test.go, internal/service/appstream/stack_test.go, internal/service/detective/invitation_accepter.go, internal/service/glue/find.go, internal/service/networkfirewall/logging_configuration_test.go, internal/service/networkmanager/core_network_policy_model.go, internal/service/redshift/event_subscription.go, names/names_test.go, skaff/datasource/datasource.go, skaff/resource/resource.go
Adds the Semgrep rules
* [`dgryski.semgrep-go.badnilguard`](https://semgrep.dev/r?q=dgryski.semgrep-go.badnilguard)
* [`dgryski.semgrep-go.marshaljson`](https://semgrep.dev/r?q=dgryski.semgrep-go.marshaljson)
* [`dgryski.semgrep-go.oddifsequence`](https://semgrep.dev/r?q=dgryski.semgrep-go.oddifsequence)
* [`dgryski.semgrep-go.oserrors`](https://semgrep.dev/r?q=dgryski.semgrep-go.oserrors)
=> linter: Adds rules from Semgrep Registry

.changelog/25915.txt, internal/provider/provider.go, internal/service/ssoadmin/customer_managed_policy_attachment.go, internal/service/ssoadmin/customer_managed_policy_attachment_test.go, internal/service/ssoadmin/find.go, website/docs/r/ssoadmin_customer_managed_policy_attachment.html.markdown
Closes #25904.
Closes #26068.
This is my first contribution and first time working with Go, so thank you in advance for your feedback.
I have added `aws_ssoadmin_customer_managed_policy_attachment` and manually tested that it is working, creating the following resource:
```
resource "aws_ssoadmin_customer_managed_policy_attachment" "example" { …
```
=> New resource: aws_ssoadmin_customer_managed_policy_attachment

.changelog/26694.txt, go.mod, go.sum, internal/provider/fwprovider/provider.go, internal/service/medialive/medialive_test.go, internal/service/medialive/multiplex_program.go, internal/service/medialive/multiplex_program_test.go, website/docs/r/medialive_multiplex_program.html.markdown
Relates #4936
```console
$ make testacc TESTS=TestAccMediaLive_serial/MultiplexProgram PKG=medialive
TF_ACC=1 go test ./internal/service/medialive/... -v -count 1 -parallel 20 -run='TestAccMediaLive_serial/MultiplexProgram'  -timeout 180m
=== RUN …
```
=> New Resource: aws_medialive_multiplex_program

.changelog/26696.txt, internal/service/lambda/function.go, internal/service/lambda/function_data_source.go, internal/service/lambda/function_test.go, internal/service/lambda/generate.go, internal/service/lambda/sweep.go, internal/service/lambda/tags_gen.go
=> Reload Lambda Function environment variables if `kms_key_arn` has changed

.changelog/26711.txt, internal/acctest/acctest.go, internal/service/acm/sweep.go, internal/service/ec2/vpc_security_group_test.go, internal/service/opsworks/stack.go, internal/service/opsworks/stack_test.go, website/docs/r/opsworks_stack.html.markdown
When no `vpc_id` is passed to `aws_opsworks_stack`, use the default VPC to match the behaviour of the AWS API.
Relates #26525
Relates #26666
Relates https://github.com/hashicorp/terraform-provider-aws/issues/23625
```console
$ make testacc PKG=opsworks TESTS=TestAccOpsWorksStack_
acctest.go:696: skipping tests; AWS_DEFAULT_REGION (us-west-2) does not equal us-east-1
--- SKIP: TestAccOpsWorksStack_tagsAlternateRegion (1.02s)
--- PASS: TestAccOpsWorksStack_disappears (40.06s)
--- PASS: TestAccOpsWorksStack_noVPC_defaultAZ (40.93s)
--- PASS: TestAccOpsWorksStack_basic (41.47s)
--- PASS: TestAccOpsWorksStack_windows (56.94s)
--- PASS: TestAccOpsWorksStack_noVPC_basic (62.84s)
--- PASS: TestAccOpsWorksStack_tags (73.88s)
--- PASS: …
```
=> resource/aws_opsworks_stack: Use Default VPC when no VPC ID passed

.changelog/26716.txt, internal/service/acm/sweep.go, internal/service/ec2/ec2_eip.go, internal/service/ec2/ec2_eip_test.go, website/docs/r/eip.html.markdown
Default to default domain when `vpc` not set. `standard` in EC2-Classic, `vpc` otherwise
Relates #26525
Relates #26666
Relates #23625
```
$ make testacc PKG=ec2 TESTS=TestAccEC2EIP
ec2_eip_test.go:424: Environment variable AWS_EC2_EIP_PUBLIC_IPV4_POOL is not set
--- SKIP: TestAccEC2EIP_PublicIPv4Pool_custom (0.00s)
ec2_eip_test.go:566: Environment variable AWS_EC2_EIP_BYOIP_ADDRESS is not set
--- SKIP: TestAccEC2EIP_BYOIPAddress_custom (0.00s)
ec2_eip_test.go:594: Environment variable AWS_EC2_EIP_BYOIP_ADDRESS is not set
--- SKIP: TestAccEC2EIP_BYOIPAddress_customWithPublicIPv4Pool (0.00s)
acctest.go:1346: skipping since no Outposts found
--- SKIP: TestAccEC2EIPDataSource_customerOwnedIPv4Pool (1.72s)
wavelength_carrier_gateway_test.go:196: skipping since …
```
=> resource/aws_eip: Default to default domain when `vpc` not set

.github/workflows/semgrep-ci.yml
Relates https://github.com/hashicorp/terraform-provider-aws/pull/26691.
Relates https://github.com/returntocorp/semgrep/issues/6059.
=> Restore use of `latest` semgrep container image in CI

website/docs/r/flow_log.html.markdown
Closes #26664
Output from acceptance testing: N/a, docs.
The PR clarifies that either `log_group_name` (deprecated) or `log_destination` must be set. This aligns the docs with the [Renaming a Required Attribute](https://www.terraform.io/plugin/sdkv2/best-practices/deprecations#renaming-a-required-attribute) section of the plugin development documentation …
=> Docs: `aws_flow_log` - note requirement of either `log_group_name` or `log_destination`

website/docs/r/rds_cluster_instance.html.markdown
Closes #25876
As the linked issue mentions, setting the `preferred_backup_window` argument of `aws_rds_cluster_instance` leads to errors when `preferred_backup_window` is also set at the cluster level. This note aims to clarify this, as the error message received isn't particularly helpful:
```shell
╷
│ Error: error …
```
=> Add note about `preferred_backup_window` for `aws_rds_cluster_instance` resources

website/docs/r/kinesis_firehose_delivery_stream.html.markdown
Move a sentence about the required IAM permissions for the role passed to Firehose to allow OpenSearch indexing from the `domain_arn` attribute description to the `role_arn` attribute description.
=> Move IAM role perms for OpenSearch

.changelog/26744.txt, internal/service/dynamodb/status.go, internal/service/dynamodb/sweep.go, internal/service/dynamodb/table.go, internal/service/dynamodb/table_data_source.go, internal/service/dynamodb/table_replica.go
When reading a table in `ARCHIVED` status, the call to `DescribeContinuousBackups` fails with a `TableNotFoundException` as follows:
> error reading DynamoDB Table (tf-acc-test-5583795887817721678): reading Amazon DynamoDB Table (tf-acc-test-5583795887817721678): continuous backups: TableNotFoundException: Table not found: tf-acc-test-5583795887817721678
Closes #26577
```
$ make testacc PKG=dynamodb TESTS=TestAccDynamoDBTable
--- PASS: TestAccDynamoDBTable_disappears (37.48s)
--- PASS: TestAccDynamoDBTable_basic (45.73s)
--- PASS: TestAccDynamoDBTableItem_updateWithRangeKey (72.15s)
--- PASS: TestAccDynamoDBTableDataSource_basic (72.51s)
--- PASS: TestAccDynamoDBTable_TTL_disabled (80.89s)
--- PASS: …
```
=> resource/aws_dynamodb_table: Handles Tables in `ARCHIVED` status

website/docs/r/cloudfront_response_headers_policy.html.markdown
Closes #26753 
n/a, docs
The PR: 
* changes the documentation of [access_control_allow_origins](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudfront_response_headers_policy#access_control_allow_origins) of a `cors_config` block of a `aws_cloudfront_response_headers_policy` resource from an …
=> fix documentation error for resource aws_cloudfront_response_headers_policy

.changelog/26768.txt, internal/service/dms/replication_subnet_group.go, internal/service/dms/wait.go
Closes #11025.
Acceptance test passing:
```
❯ make testacc TESTS=TestAccDMSReplicationSubnetGroup PKG=dms           
TF_ACC=1 go test ./internal/service/dms/... -v -count 1 -parallel 20 -run='TestAccDMSReplicationSubnetGroup'  -timeout 180m
=== RUN   TestAccDMSReplicationSubnetGroup_basic
=== PAUSE …
```
=> Add retry to resourceReplicationSubnetGroupCreate

website/docs/d/cognito_user_pool_client.markdown
Closes #26728
This PR documents the previously undocumented `client_secret` attribute of the `aws_cognito_user_pool_client` data source.
- [Schema reference](https://github.com/hashicorp/terraform-provider-aws/blob/d24492daf45b75153e554c16e61acd2bc41ee8fa/internal/service/cognitoidp/user_pool_client_data_source.go#L77 …
=> Document `client_secret` attribute of `aws_cognito_user_pool_client` data source

.changelog/26765.txt, internal/service/rds/consts_test.go, internal/service/rds/errors.go, internal/service/rds/instance.go, internal/service/rds/instance_test.go, internal/service/rds/test-fixtures/custom-sql-cloudformation.json, internal/service/rds/wait.go, website/docs/r/db_instance.html.markdown
Closes #22084
```console
$ make testacc TESTS=TestAccRDSInstance_ PKG=rds
TF_ACC=1 go test ./internal/service/rds/... -v -count 1 -parallel 20 -run='TestAccRDSInstance_'  -timeout 180m
=== RUN   TestAccRDSInstance_basic
=== PAUSE TestAccRDSInstance_basic
=== RUN …
```
=> r/aws_db_instance: add custom_iam_instance_profile attribute

website/docs/r/db_instance.html.markdown
#22668 deprecated name and changed the rest of the doc but not the example.
```
...
```
=> Use db_name in db_instance example not deprecated name

website/docs/r/kendra_faq.html.markdown
Relates #13367
Closes #26877
Documentation fix since `aws_kendra_faq` uses `s3_path` and not `source_s3_path`
=> docs(kendra): faq source_s3_path to s3_path

website/docs/r/rds_cluster_role_association.html.markdown
Updated documentation example to use `iam_role.example.arn` attribute instead of `id`, as that is what is expected by the API.
When `.id` is used, the following error is thrown:
```
Error: "role_arn" (<role id>) is an invalid ARN: arn: invalid prefix
```
=> Update rds_cluster_role_association.html.markdown to fix example typo

.changelog/26845.txt, internal/service/ec2/vpc_managed_prefix_list.go, internal/service/ec2/vpc_managed_prefix_list_test.go
Closes #26639
```
$ make testacc TESTS=TestAccVPCManagedPrefixList PKG=ec2
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 20 -run='TestAccVPCManagedPrefixList'  -timeout 180m
=== RUN   TestAccVPCManagedPrefixListDataSource_basic
=== PAUSE TestAccVPCManagedPrefixListDataSource_basic
=== RUN   TestAccVPCManagedPrefixListDataSource_filter
=== PAUSE TestAccVPCManagedPrefixListDataSource_filter
=== RUN   TestAccVPCManagedPrefixListDataSource_matchesTooMany
=== PAUSE TestAccVPCManagedPrefixListDataSource_matchesTooMany
=== RUN   TestAccVPCManagedPrefixListEntry_ipv4
=== PAUSE TestAccVPCManagedPrefixListEntry_ipv4
=== RUN   TestAccVPCManagedPrefixListEntry_ipv4Multiple
=== PAUSE …
```
=> r/aws_ec2_managed_prefix_list - Fix: `MaxEntries` and `Entry` can be changed in same apply

.changelog/26866.txt, go.mod, go.sum, internal/service/eks/cluster.go, internal/service/eks/cluster_data_source.go, internal/service/eks/cluster_test.go, internal/service/eks/node_group_test.go, internal/service/eks/wait.go, website/docs/d/eks_cluster.html.markdown, website/docs/r/eks_cluster.html.markdown
Add support for EKS local clusters on Outposts
Closes #26913
```
$ make testacc TESTS=TestAccEKSCluster_ PKG=eks
TF_ACC=1 go test ./internal/service/eks/... -v -count 1 -parallel 2 -run='TestAccEKSCluster_'  -timeout 180m
=== RUN   TestAccEKSCluster_basic
=== PAUSE TestAccEKSCluster_basic
=== RUN   TestAccEKSCluster_disappears
=== PAUSE TestAccEKSCluster_disappears
=== RUN   TestAccEKSCluster_Encryption_create
=== PAUSE TestAccEKSCluster_Encryption_create
=== RUN   TestAccEKSCluster_Encryption_update
=== PAUSE TestAccEKSCluster_Encryption_update
=== RUN   TestAccEKSCluster_Encryption_versionUpdate
=== PAUSE TestAccEKSCluster_Encryption_versionUpdate
=== RUN   TestAccEKSCluster_version
=== PAUSE TestAccEKSCluster_version
=== RUN   TestAccEKSCluster_logging …
```
=> Add support for EKS local clusters on Outposts

website/docs/r/organizations_organization.html.markdown
Provide a warning for users of `aws_organizations_organization` resource. Not all services support enablement across the organization using `EnableAWSServiceAccess` and it may cause strange errors. For example: adding the ipam service principal to `aws_service_access_principals` will yield errors like: 
> The operation AllocateIpamPoolCidr is not supported. Account xxxx is not monitored by IPAM ipam-xxxxx.
The easiest way to avoid these issues is to use the specific service endpoint: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/vpc_ipam_organization_admin_account
=> include warning about services that do not use this endpoint

internal/service/sqs/sweep.go
The update to `aws_sqs_queue` to use WithoutTimeout CRUD handlers in #26733 caused a panic the sweeper because the sweeper directly referenced the `Delete` function.
Previously:
```
[DEBUG] Running Sweeper (aws_sqs_queue) in region (us-east-1)
```
Now:
```
[DEBUG] Running Sweeper (aws_sqs_queue) in region (us-east-1)
- aws_sqs_queue
[DEBUG] Completed Sweeper (aws_sqs_queue) in region (us-east-1) in 1.424072016s
Completed Sweepers for region (us-east-1) in 1.424115238s
```
=> resource/aws_sqs_queue: Fix panic in sweeper

internal/service/iam/sweep.go
If the associated IAM role is deleted before a `aws_iot_topic_rule_destination`, it may get stuck in `Deleting` status. Add dependency.
=> resource/aws_iam_role: Add sweeper dependency on `aws_iot_topic_rule_destination`

internal/service/ec2/sweep.go
`aws_db_proxy` creates an ENI, so it must be swept before `aws_network_interface`
=> resource/aws_network_interface : Add sweeper dependency on `aws_db_proxy`

.github/workflows/acctest-terraform-lint.yml, .github/workflows/examples.yml, .github/workflows/terraform_provider.yml, .github/workflows/website.yml, .github/workflows/workflow-lint.yml
The GitHub workflow for `Workflow Linting` did not reference the `tools` directory to trigger a run if `actionlint` is updated.
Other references were not updated for the move of `tools` into the `.ci` directory.
=> workflows: Updates paths to `tools` directory in GitHub workflows

.ci/.golangci2.yml, internal/acctest/provider_test.go, internal/service/cloudformation/stack_set_test.go, internal/service/codebuild/project_test.go, internal/service/datasync/task_test.go, internal/service/dynamodb/backup.go, internal/service/ec2/ec2_capacity_reservation_test.go, internal/service/ec2/ec2_fleet_test.go, internal/service/ec2/ec2_spot_fleet_request_test.go, internal/service/firehose/list_pages.go, internal/service/glue/data_catalog_encryption_settings_data_source_test.go, internal/service/glue/data_catalog_encryption_settings_test.go, internal/service/mediaconvert/queue_test.go, internal/service/networkmanager/transit_gateway_peering.go, internal/service/networkmanager/transit_gateway_route_table_attachment.go, internal/service/rds/instance_test.go, internal/service/redshift/consts.go, internal/service/route53/list_pages.go, internal/service/s3/bucket_replication_configuration_test.go, internal/service/s3control/bucket_lifecycle_configuration_test.go, internal/service/s3control/bucket_test.go, internal/service/ses/template_test.go, internal/service/storagegateway/cached_iscsi_volume_test.go, internal/service/storagegateway/enum.go
`golangci-lint` v1.49.0 deprecates `deadcode`, `structcheck`, and `varcheck`. `unused` is the suggested replacement.
Previously:
```
$ make lint
WARN [runner] The linter 'deadcode' is deprecated (since v1.49.0) due to: The owner seems to have abandoned the linter.  Replaced by unused. 
WARN [runner] The linter 'varcheck' is deprecated (since v1.49.0) due to: The owner seems to have abandoned the linter.  Replaced by unused. 
WARN [runner] The linter 'structcheck' is deprecated (since v1.49.0) due to: The owner seems to have abandoned the linter.  Replaced by unused. 
WARN [linters context] structcheck is disabled because of generics. You can track the evolution of the generics support by following the https://github.com/golangci/golangci-lint/issues/2649. 
...
```
Now gets no warnings or …
=> linters: Remove deprecated linters and replace with suggested alternative

website/docs/r/iam_access_key.html.markdown
Relates to #10835
When providing a base-64 encoded PGP public key as `pgp_key` for the `iam_access_key` resource, only a "raw" export is accepted - not an ASCII "armored" one with `BEGIN` and `END` markers. This commit make this explicit for a better user experience, given that previously users would just get a `invalid data: tag byte does not have MSB set` cryptic error as reported in https://github.com/hashicorp/terraform/issues/10835
This documentation addition was suggested in 2017 but never got contributed until now: https://github.com/hashicorp/terraform/issues/10835#issuecomment-348593664
=> docs(iam_access_key): add instructions about the expected `pgp_key` format

.changelog/26997.txt, internal/provider/provider.go, internal/service/kms/custom_key_store.go, internal/service/kms/custom_key_store_test.go, internal/service/kms/find.go, internal/service/kms/kms_test.go, website/docs/r/kms_custom_key_store.html.markdown
New resource for `aws_kms_custom_key_store`
Relates #16491
```console
$ make testacc TESTARGS='-run=TestAccKMS_serial/CustomKeyStore' PKG=kms ACCTEST_TIMEOUT=180m
TF_ACC=1 go test ./internal/service/kms/... -v -count 1 -parallel 20  -run=TestAccKMS_serial/CustomKeyStore -timeout 180m
=== RUN   TestAccKMS_serial
=== RUN   TestAccKMS_serial/CustomKeyStore
=== RUN   TestAccKMS_serial/CustomKeyStore/disappears
=== RUN   TestAccKMS_serial/CustomKeyStore/basic
=== RUN   TestAccKMS_serial/CustomKeyStore/update
--- PASS: TestAccKMS_serial (39.01s)
--- PASS: TestAccKMS_serial/CustomKeyStore (39.01s)
--- PASS: TestAccKMS_serial/CustomKeyStore/disappears (11.29s)
--- PASS: TestAccKMS_serial/CustomKeyStore/basic (14.52s)
--- PASS: …
```
=> New Resource: aws_kms_custom_key_store

internal/service/kms/key_test.go, website/docs/r/kms_key.html.markdown
Add documentation and tests for existing key usage parameter value `GENERATE_VERIFY_MAC`.
N/A
[The newly documented value is present in the GO SDK](https://github.com/aws/aws-sdk-go/blob/427f0372a6a485ae717e9b2a0b8f94766966901a/service/kms/api.go#L19126-L19135) meaning that it will pass validation in actual usage, but the documentation doesn't list it. 
```
$ make testacc TESTS='TestAccKMSKey_hmacKey' PKG=kms
TF_ACC=1 go test ./internal/service/kms/... -v -count 1 -parallel 20 -run='TestAccKMSKey_hmacKey'  -timeout 180m
=== RUN   TestAccKMSKey_hmacKey
=== PAUSE TestAccKMSKey_hmacKey
=== CONT  TestAccKMSKey_hmacKey
--- PASS: TestAccKMSKey_hmacKey (22.17s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/kms …
```
=> Document and test KMS `GENERATE_VERIFY_MAC` key usage value

.changelog/27011.txt, internal/service/appautoscaling/policy.go, internal/service/appautoscaling/policy_test.go, website/docs/r/appautoscaling_policy.html.markdown
This is a suggested enhancement based on my own enhancement request here: https://github.com/hashicorp/terraform-provider-aws/issues/27010
The idea is to have an attribute with a list of the ARNs of the cloudwatch alarms that are managing an app autoscaling policy such as a `TargetTrackingPolicy`. This is useful data for external systems in order to be able to enable/disable the autoscaling behavior for example.
Closes #27010
```
$ make testacc TESTS=TestAccAppAutoScalingPolicy PKG=appautoscaling                                                  
TF_ACC=1 go test ./internal/service/appautoscaling/... -v -count 1 -parallel 20 -run='TestAccAppAutoScalingPolicy'  -timeout 180m
=== RUN   TestAccAppAutoScalingPolicy_basic
=== PAUSE …
```
=> resource/aws_appautoscalingpolicy: add computed attribute `alarmARNs`

.changelog/27004.txt, internal/service/dms/endpoint.go, internal/service/dms/endpoint_test.go, website/docs/r/dms_endpoint.html.markdown
Add missing `s3_settings.use_task_start_time_for_full_load_timestamp` to `dms_endpoint` resource
https://docs.aws.amazon.com/dms/latest/userguide/CHAP_Target.S3.html#CHAP_Target.S3.Configuring
Unsure how to run these
=> dms_endpoint - use_task_start_time_for_full_load_timestamp

.changelog/26767.txt, internal/service/ec2/errors.go, internal/service/ec2/find.go, internal/service/ec2/vpc_traffic_mirror_target.go, internal/service/ec2/vpc_traffic_mirror_target_test.go, website/docs/r/ec2_traffic_mirror_target.html.markdown
Relates to #26767
```
$ make testacc PKG=ec2 TESTS=TestAccVPCTrafficMirrorTarget_gwlb
~/terraform-provider-aws (f-aws_ec2_traffic_mirror_target) $ make testacc PKG=ec2 TESTS=TestAccVPCTrafficMirrorTarget_gwlb
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 20 -run='TestAccVPCTrafficMirrorTarget_gwlb'  -timeout 180m
=== RUN   TestAccVPCTrafficMirrorTarget_gwlb
=== PAUSE TestAccVPCTrafficMirrorTarget_gwlb
=== CONT  TestAccVPCTrafficMirrorTarget_gwlb
--- PASS: TestAccVPCTrafficMirrorTarget_gwlb (258.16s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/ec2        258.244s
:~/terraform-provider-aws (f-aws_ec2_traffic_mirror_target) $ 
:~/terraform-provider-aws …
```
=> f-aws_ec2_traffic_mirror_target

website/docs/index.html.markdown, website/docs/r/acmpca_certificate_authority.html.markdown
Corrects documentation around assuming a role with a web identity to use the appropriate provider configuration.
Closes #27015 
Relates #22907
=> Documentation: use correct `assume_role_with_web_identity` config

website/docs/r/redshiftserverless_endpoint_access.html.markdown
This PR removes reference to a `security_group_ids` argument for `aws_redshiftserverless_endpoint_access` resources. This argument does not exist in the schema.
Closes #26888
- [Resource schema](https://github.com/hashicorp/terraform-provider-aws/blob/f3434154a1621a054f18955cbe7b39d91ca2601a/internal/service/redshiftserverless/endpoint_access.go#L28-L109)
=> Remove incorrect reference to `aws_redshiftserverless_endpoint_access.security_group_ids`

internal/diag/diag.go, internal/sdktypes/README.md, internal/sdktypes/duration.go, internal/sdktypes/duration_test.go, internal/sdktypes/rfc3339_duration.go, internal/sdktypes/testing_test.go, internal/service/acm/certificate.go, internal/service/acm/certificate_test.go, internal/types/duration/duration.go, internal/types/duration/duration_test.go, internal/verify/validate.go, website/docs/r/acm_certificate.html.markdown
Adds support for a subset of RFC 3339 duration to `early_renewal_duration`. Supports year, month, and day values.
Relates #26784
```
$ make testacc PKG=acm TESTS=TestAccACMCertificate_
--- PASS: TestAccACMCertificate_SubjectAlternativeNames_emptyString (4.73s)
--- PASS: TestAccACMCertificate_Root_trailingPeriod (5.25s)
--- PASS: TestAccACMCertificate_Imported_ipAddress (30.44s)
--- PASS: TestAccACMCertificate_Imported_validityDates (38.98s)
--- PASS: TestAccACMCertificate_San_trailingPeriod (51.48s)
--- PASS: TestAccACMCertificate_root (58.98s)
--- PASS: TestAccACMCertificate_wildcard (69.37s)
--- PASS: TestAccACMCertificate_wildcardAndRootSan (70.31s)
--- PASS: TestAccACMCertificate_emailValidation (71.63s)
--- PASS: TestAccACMCertificate_San_single (72.21s)
--- PASS: …
```
=> resource/aws_acm_certificate: Add RFC 3339 duration support for `early_renewal_duration`

website/docs/r/eks_cluster.html.markdown
Current example cherry picks the first cert fingerprint, whereas this includes all.
Also slight readability improvement to the URL.
=> Changed IRSA example to include all fingerprints

.changelog/26980.txt, internal/service/eks/cluster.go, internal/service/eks/cluster_data_source.go, internal/service/eks/cluster_data_source_test.go, website/docs/d/eks_cluster.html.markdown, website/docs/r/eks_cluster.html.markdown
=> eks_cluster: Export ipv6 service address range

.changelog/27038.txt, internal/service/eks/addon_test.go, website/docs/r/eks_addon.html.markdown
EKS API now provides three options for `resolve_conflicts` which are NONE, OVERWRITE and PRESERVE. 
EKS Add-on currently supports a new feature to preserve user configuration during the upgrade of EKS Add-ons. Any changes applied to the managed add-ons using `kubectl` or through any other approach will be retained during the upgrade of managed add-on to the newer version. 
Current behaviour of the upgrade add-on version overwrites the custom changes applied to the previous version of add-on However, users can retain the custom configuration during the add-on upgrades by using `resolve_conflicts = "PRESERVE"`
This new `resolve_conflicts` with `PRESERVE` feature is already supported by the current version(4.32.0) of AWS provider since the option of pulling `resolve_conflicts` string is …
=> EKS Add-on resolve_conflicts with PRESERVE feature tests and docs updated

.changelog/26812.txt, internal/service/keyspaces/table.go
In Cassandra and Amazon Keyspaces, the order of column names in a partition key and clustering key should be ordered and not changed. Today, the schema type is unordered creating issues when creating and maintaining resources. This change switches type to a list schema type which is ordered.
https://cassandra.apache.org/doc/latest/cassandra/data_modeling/data_modeling_logical.html
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help …
=> Fix PartitionKey and ClusteringKey Types in Schema

.changelog/26858.txt, internal/service/rolesanywhere/profile.go, internal/service/rolesanywhere/profile_test.go, internal/service/rolesanywhere/trust_anchor.go, internal/service/rolesanywhere/trust_anchor_test.go
Hello!
Fix typo for rolesanywhere's profile.
Please check my PR. thank you.
Fixes #26872
=> Fix typo for rolesanywhere

.changelog/27055.txt, internal/service/iam/policy_document_data_source.go, internal/service/iam/policy_document_data_source_test.go
Adds additional validation to user supplied JSON attributes on `override_policy_documents`.
Note that this change introduces additional validation on deprecated attributes (`override_json`, `source_json`). Supplying invalid JSON to these fields did not cause a 'panic' or crash and this validation + additional tests exists for completeness and to prevent against future regressions. 
Closes #27022.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/26640.
```
make testacc TESTS=TestAccIAMPolicyDocumentDataSource_overridePolicyDocumentValidJSON PKG=iam
TF_ACC=1 go test ./internal/service/iam/... -v -count 1 -parallel 20 -run='TestAccIAMPolicyDocumentDataSource_overridePolicyDocumentValidJSON'  -timeout 180m
=== RUN …
```
=> data/aws_iam_policy_document - additional json validation

.changelog/27051.txt, internal/provider/provider.go, internal/service/ec2/find.go, internal/service/ec2/ipam_pool_cidrs_data_source.go, internal/service/ec2/ipam_pool_cidrs_data_source_test.go, website/docs/d/vpc_ipam_pool_cidrs.html.markdown
Adds a new data source to list all cidrs provisioned into a pool. This is especially helpful for those who receive a pool via ram sharing and want to add all CIDRs from a pool to route tables.
Closes #27040
```
$ make testacc TESTS=TestAccIPAMPoolCidrsDataSource_basic PKG=ec2
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 20 -run='TestAccIPAMPoolCidrsDataSource_basic'  -timeout 180m
=== RUN   TestAccIPAMPoolCidrsDataSource_basic
=== PAUSE TestAccIPAMPoolCidrsDataSource_basic
=== CONT  TestAccIPAMPoolCidrsDataSource_basic
--- PASS: TestAccIPAMPoolCidrsDataSource_basic (123.34s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/ec2        127.394s
```
=> [New Data Source] d/aws_vpc_ipam_pool_cidrs

go.mod, go.sum, internal/experimental/intf/service.go, internal/provider/fwprovider/provider.go, internal/service/medialive/multiplex_program.go, internal/service/medialive/multiplex_program_test.go, internal/service/meta/arn_data_source.go, internal/service/meta/svcimpl.go
* Combines `Resource` and `ResourceType` implementations
* Combines `DataSource` and `DataSourceType` implementations
* Adds `Metadata` method to `Resource` and `DataSource` implementations
* Adds `Configure` method to `Resource` and `DataSource` implementations which allows initialization simplifications
* Changes `Provider` `GetResources` and `GetDataSources` to `Resources` and `DataSources`, with change return types. This allows PoC self-registration mechanism simplification
Relates https://github.com/hashicorp/terraform-provider-awscc/pull/685.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/26832.
```console
% make testacc TESTARGS='-run=TestAccMetaARNDataSource_' PKG=meta …
```
=> Upgrade to `terraform-plugin-framework` v0.13.0

website/docs/r/wafv2_web_acl.html.markdown
Heading was removed in https://github.com/hashicorp/terraform-provider-aws/commit/7a292ba5ebfa288c242f5238d4d584384b7bb4d9#diff-abb481e03fb308d7193a38448a81e378d5f3a25076d08a9fc4e0f1a3ea06aafd but one link remains, breaking the CI pipeline e.g. https://github.com/hashicorp/terraform-provider-aws/actions/runs/3181284850/jobs/5185856649
```
FILE: website/docs/r/wafv2_web_acl.html.markdown
[✖] #body → Status: 404
52 links checked.
ERROR: 1 dead links found!
[✖] #body → Status: 404
```
=> wafv2_web_acl: Remove broken link in docs breaking CI

.changelog/27084.txt, internal/service/ec2/ec2_ami.go, internal/service/ec2/ec2_ami_data_source.go, internal/service/ec2/ec2_ami_data_source_test.go, internal/service/ec2/ec2_ami_test.go, website/docs/d/ami.html.markdown, website/docs/r/ami.html.markdown
This pull request adds support for setting the `imds_support` attribute when creating `aws_ami` resources. It also adds support for this attribute in the `aws_ami` data source.
Note: Setting this attribute is currently only supported in the AWS API at registration time (i.e. `ec2:RegisterImage`). It is not available in `ec2:ModifyImageAttributes`.
closes #27083
https://aws.amazon.com/about-aws/whats-new/2022/10/amazon-machine-images-support-instance-metadata-service-version-2-default/
```
$ make testacc TESTS=TestAccEC2AMI_imdsSupport PKG=ec2
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 20 -run='TestAccEC2AMI_imdsSupport'  -timeout 180m
=== RUN   TestAccEC2AMI_imdsSupport
=== PAUSE TestAccEC2AMI_imdsSupport …
```
=> aws_ami: Support setting the imds_support attribute at creation time

website/docs/r/efs_file_system_policy.html.markdown
Fixes a typo in the reference documentation for `efs_file_system_policy`. The example inconsistently uses the name `fs` and `test` for the `aws_efs_file_system`.
=> Docs: Fix typo in efs_file_system_policy reference

.changelog/27073.txt, internal/service/ses/active_receipt_rule_set_data_source.go, internal/service/ses/active_receipt_rule_set_data_source_test.go, internal/service/ses/active_receipt_rule_set_test.go
Handles cases where there is no SES receipt rule set as active. An empty result error is now returned in this scenario:
```
data.aws_ses_active_receipt_rule_set.active_receipt_rule_set: Reading...
╷
│ Error: empty result
│
│   with data.aws_ses_active_receipt_rule_set.active_receipt_rule_set,
│   on main.tf line 15, in data "aws_ses_active_receipt_rule_set" "active_receipt_rule_set":
│   15: data "aws_ses_active_receipt_rule_set" "active_receipt_rule_set" {}
│
╵
```
Closes #26936
```console
$ make testacc TESTS='TestAccSESActiveReceiptRuleSet_serial' PKG=ses
TF_ACC=1 go test ./internal/service/ses/... -v -count 1 -parallel 20 -run='TestAccSESActiveReceiptRuleSet_serial'  -timeout 180m
=== RUN …
```
=> Prevent panic from nil SES active receipt rule set

.changelog/27148.txt, internal/service/directconnect/connection.go, internal/service/directconnect/connection_data_source.go, internal/service/directconnect/connection_data_source_test.go, internal/service/directconnect/connection_test.go, website/docs/d/dx_connection.html.markdown, website/docs/r/dx_connection.html.markdown
Adding VLAN ID parameter to Direct Connect datasource
Closes #26461
```
$ make testacc TESTS=TestAccDirectConnectConnectionDataSource_basic PKG=directconnect
...
```
=> Adding VLAN_ID to Direct Connect datasource

internal/service/acmpca/certificate_authority.go, internal/service/acmpca/sweep.go
ACM PCA certificate authorities are preserved for a minimum of seven days, in the state `DELETED`. The `aws_acmpca_certificate_authority` sweeper currently tries to delete the deleted CAs. Skip if already in `DELETED`.
=> sweeper/aws_acmpca_certificate_authority: skip already deleted certificate authorities

GNUmakefile, internal/acctest/acctest.go, internal/service/emr/cluster_test.go, internal/service/s3/bucket.go, internal/service/s3/object.go, internal/service/s3/sweep.go, internal/sweep/sweep.go
Updates S3 sweepers to:
* use same filtering for Buckets and Objects
* not fail silently for some failures
* not return on first failure for some failures
* run concurrently
Also renames resources in `TestAccEMRCluster_Bootstrap_ordering` to remove an S3 bucket name prefix
=> Update S3 sweepers

website/docs/r/ec2_client_vpn_route.html.markdown
=> [Docs]: Fix aws_ec2_client_vpn_route description attribute text

.changelog/27101.txt, internal/provider/provider.go, internal/service/ec2/find.go, internal/service/ec2/ipam_pools_data_source.go, internal/service/ec2/ipam_pools_data_source_test.go, website/docs/d/vpc_ipam_pools.html.markdown
Closes #22180
```
$ make testacc TESTS=TestAccIPAMPoolsDataSource_basic PKG=ec2
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 20 -run='TestAccIPAMPoolsDataSource_basic'  -timeout 180m
=== RUN   TestAccIPAMPoolsDataSource_basic
=== PAUSE TestAccIPAMPoolsDataSource_basic
=== CONT  TestAccIPAMPoolsDataSource_basic
--- PASS: TestAccIPAMPoolsDataSource_basic (79.32s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/ec2        83.193s
...
```
=> [New Data Source] data vpc ipam pools

.changelog/27129.txt, internal/service/cognitoidp/user_pool.go, internal/service/cognitoidp/user_pool_test.go, website/docs/d/ec2_transit_gateway_vpc_attachments.html.markdown, website/docs/r/cognito_user_pool.markdown
This PR adds support for user attribute update settings with Cognito IDP user pools.
Closes #26726
* https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_CreateUserPool.html
* https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_UpdateUserPool.html
* https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_UserAttributeUpdateSettingsType.html#CognitoUserPools-Type-UserAttributeUpdateSettingsType-AttributesRequireVerificationBeforeUpdate
```console
$ make testacc TESTS='TestAccCognitoIDPUserPool_withUserAttributeUpdateSettings' PKG=cognitoidp
TF_ACC=1 go test ./internal/service/cognitoidp/... -v -count 1 -parallel 20 …
```
=> r/aws_cognito_user_pool: Support `user_attribute_update_settings`

website/docs/r/apigatewayv2_integration.html.markdown
Fixes a small typo: `ths` -> `this`
-
-
-
=> Fix typo in documentation

website/docs/r/ses_domain_dkim.html.markdown
Dropping use of [`element()` function](https://www.terraform.io/language/functions/element) with `aws_ses_domain_dkim` example of setup of Route53 DKIM records, in place of just the built-in index syntax.
Provides a simpler example to reason with.
`element()` provides "wrap around" - but that won't help here - as you'd end up with conflicting `CNAME` DNS names anyway - which would fail the AWS API on `terraform apply`.
=> Remove use of `element()` function with `aws_ses_domain_dkim` documentation example

website/docs/r/ram_resource_share.markdown
Minor change to documentation of resource aws_ram_resource_share - The import help-text stated that `id` of the resource share should be used when importing, but the example code below clearly uses the complete `arn` instead.
Verified that `arn` is in fact the correct value to use when importing these resources.
=> [Docs]: Change import help-text from 'id' to 'arn'

examples/eks-getting-started/workstation-external-ip.tf
As per the Terraform `http` module docs for [`body`](https://registry.terraform.io/providers/hashicorp/http/latest/docs/data-sources/http#body) - it is deprecated. 
In a particular example, the minor update is: `body` -> [`response_body`](https://registry.terraform.io/providers/hashicorp/http/latest/docs/data-sources/http#response_body).
=> Example update: In `http` module - `body` is deprecated.

website/docs/r/security_group_rule.html.markdown
Explicitly document that a single security group rule resource may result in the EC2 API creating one or many security group rule(s) depending on whether multiple source(s)/destination(s) are provided or whether a source/destination has a list containing multiple elements.
The security group rule resource explicit states that it "Represents a single ingress or egress group rule" which is false.
For example:
```hcl
resource "aws_security_group_rule" "example" {
description              = "A single rule resource will create a total of three ingress rules in AWS"
type                     = "ingress"
security_group_id        = "sg-123456"
from_port                = 443
to_port                  = 443
protocol                 = "tcp"
cidr_blocks              = ["10.0.1.0/24", "10.0.2.0/24"] # …
```
=> security_group_rule: explictly state that a single resource can manage many security group rules.

.changelog/27181.txt, docs/acc-test-environment-variables.md, internal/service/globalaccelerator/accelerator.go, internal/service/globalaccelerator/accelerator_data_source.go, internal/service/globalaccelerator/accelerator_test.go, internal/service/globalaccelerator/find.go, website/docs/r/globalaccelerator_accelerator.html.markdown
This PR adds support for BYOIP IP addresses for creating AWS GlobalAccelerator accelerators
[API reference](https://docs.aws.amazon.com/global-accelerator/latest/api/API_CreateAccelerator.html#API_CreateAccelerator_RequestSyntax)
Closes #14002
(Changed IP address because of security reasons)
```
$ GLOBALACCELERATOR_BYOIP_IPV4_ADDRESS=127.0.0.1 make testacc TESTS=TestAccGlobalAcceleratorAccelerator_byoip PKG=globalaccelerator
TF_ACC=1 go test ./internal/service/globalaccelerator/... -v -count 1 -parallel 20 -run='TestAccGlobalAcceleratorAccelerator_byoip'  -timeout 180m
=== RUN   TestAccGlobalAcceleratorAccelerator_byoip
=== PAUSE TestAccGlobalAcceleratorAccelerator_byoip
=== CONT  TestAccGlobalAcceleratorAccelerator_byoip
--- …
```
=> Add support for AWS GlobalAccelerator BYOIP.

website/docs/d/cloudfront_origin_request_policy.html.markdown
Updates wording for [aws_cloudfront_cache_policy](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/cloudfront_origin_request_policy) to match other policies ([aws_cloudfront_cache_policy](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/cloudfront_cache_policy) and [aws_cloudfront_response_headers_policy](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/cloudfront_response_headers_policy)).
Closes #27217
=> Change aws_cloudfront_origin_request_policy wording to match other policy docs

internal/service/ec2/ipam_byoip_test.go, internal/service/ec2/ipam_pool.go, internal/service/ec2/ipam_pool_cidr_allocation_test.go, internal/service/ec2/ipam_pool_cidr_test.go, internal/service/ec2/ipam_pool_cidrs_data_source_test.go, internal/service/ec2/ipam_pool_data_source_test.go, internal/service/ec2/ipam_pool_test.go, internal/service/ec2/ipam_pools_data_source_test.go, internal/service/ec2/ipam_preview_next_cidr_data_source_test.go, internal/service/ec2/ipam_preview_next_cidr_test.go, internal/service/ec2/ipam_scope_test.go, internal/service/ec2/ipam_test.go, internal/service/ec2/sweep.go, internal/service/ec2/vpc_ipv4_cidr_block_association_test.go, internal/service/ec2/vpc_test.go
3 Primary changes:
1. IPAM introduced the --cascade argument that allows you to delete ipam resources in summary from the root ipam. this will make the delete process simpler and remove the requirement to wait for allocations to be removed by the service (can take over 30m)
1. IPAM also removed the requirement to create SLR prior to deploying IPAM, instead its made when the `create-ipam` call is made.
1. had to update `ipam_pool.go` because _tags test was failing prior to changes
Closes #0000
```
$ make testacc TESTS=TestAccIPAM PKG=ec2
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 20 -run='TestAccIPAM'  -timeout 180m
=== RUN   TestAccIPAM_byoipIPv6
ipam_byoip_test.go:21: Environment variable …
```
=> Refactor IPAM sweepers & remove SLR precheck

.github/workflows/pull_requests.yml
This pull request aims to migrate the action `first-interaction` from `v1` to `v1.1.1`.
Relates #27209
[https://github.com/actions/first-interaction/issues/101](https://github.com/actions/first-interaction/issues/101)
=> fix: migrate first interaction action from v1 to v1.1.1

.changelog/27229.txt, go.mod, internal/errs/append.go, internal/errs/diag.go, internal/errs/errs.go, internal/provider/provider.go, internal/sdktypes/duration.go, internal/sdktypes/rfc3339_duration.go, internal/service/comprehend/document_classifier.go, internal/service/comprehend/entity_recognizer.go, internal/service/inspector2/delegated_admin_account.go, internal/service/inspector2/delegated_admin_account_test.go, internal/service/inspector2/organization_configuration_test.go, website/docs/r/inspector2_delegated_admin_account.html.markdown
=> inspector2: New delegated admin account resource

.changelog/27213.txt, CHANGELOG.md, internal/service/amp/alert_manager_definition.go, internal/service/amp/alert_manager_definition_test.go, internal/service/amp/find.go, internal/service/amp/rule_group_namespace.go, internal/service/amp/rule_group_namespace_test.go, internal/service/amp/status.go, internal/service/amp/wait.go, internal/service/amp/workspace.go, internal/service/amp/workspace_data_source.go, internal/service/amp/workspace_test.go, website/docs/r/prometheus_workspace.html.markdown
Add cloudwatch_log_group_arn to aws_prometheus_workspace resource.
I did not add log_level as an extra property as it does not exist in the API and it only indicates whether the logging configuration is enabled or not. In my opinion it is clearer to leave it out for now.
For the log_group_arn configuration I use the same contract as the API call, which requires users to add ':*' to the log_group_arn (see tests for more details). I did not want to abstract this away by adding extra logic to the terraform provider. 
Closes #26444.
```
$ make testacc TESTS='TestAccAMPWorkspace_' PKG=amp
TF_ACC=1 go test ./internal/service/amp/... -v -count 1 -parallel 20 -run='TestAccAMPWorkspace_'  -timeout 180m
=== RUN   TestAccAMPWorkspace_basic …
```
=> Add log group arn to aws prometheus workspace 26444

internal/acctest/acctest.go, internal/envvar/envvar.go, internal/envvar/envvar_test.go, internal/service/codepipeline/codepipeline_test.go, internal/service/codepipeline/webhook_test.go, internal/service/ec2/transitgateway_peering_attachment_accepter_test.go, internal/service/macie2/invitation_accepter_test.go, internal/service/macie2/member_test.go, internal/service/rds/instance_test.go, internal/sweep/sweep.go
Since the environment variable handling code is only used in acceptance tests and sweeping, they should not be in the `conns` package.
This is one step in breaking the dependency of all acceptance tests on the entire non-test codebase.
=> refactor: Move environment variable functions and constants to package

.changelog/27134.txt, internal/service/elasticache/cluster.go, internal/service/elasticache/cluster_data_source.go, internal/service/elasticache/global_replication_group.go, internal/service/elasticache/global_replication_group_test.go, internal/service/elasticache/parameter_group.go, internal/service/elasticache/replication_group_test.go, internal/service/elasticache/subnet_group.go, internal/service/elasticache/sweep.go, internal/service/elasticache/user.go, internal/service/elasticache/user_group.go, internal/service/elasticache/user_test.go, website/docs/d/elasticache_cluster.html.markdown, website/docs/d/elasticache_replication_group.html.markdown, website/docs/d/elasticache_user.html.markdown, website/docs/r/elasticache_global_replication_group.html.markdown, website/docs/r/elasticache_parameter_group.html.markdown, website/docs/r/elasticache_subnet_group.html.markdown
Add support for updating `cache_node_type` and `automatic_failover_enabled` on an `aws_elasticache_global_replication_group`
Closes #17696
Closes #22528
```
$ make testacc PKG=elasticache TESTS=TestAccElastiCacheGlobalReplicationGroup_
--- PASS: TestAccElastiCacheGlobalReplicationGroup_SetEngineVersionOnCreate_NoChange_v6x (906.81s)
--- PASS: TestAccElastiCacheGlobalReplicationGroup_SetParameterGroupOnUpdate_NoVersion (927.24s)
--- PASS: TestAccElastiCacheGlobalReplicationGroup_SetEngineVersionOnCreate_NoChange_v5 (934.59s)
--- PASS: TestAccElastiCacheGlobalReplicationGroup_automaticFailover_createNoChange (1055.25s)
--- PASS: TestAccElastiCacheGlobalReplicationGroup_clusterMode (1145.08s)
--- PASS: TestAccElastiCacheGlobalReplicationGroup_SetParameterGroupOnUpdate_MinorUpgrade (1173.15s) …
```
=> resource/aws_elasticache_global_replication_group: Update node type and automatic failover setting

.changelog/27232.txt, internal/service/ssm/find.go, internal/service/ssm/service_setting.go, internal/service/ssm/service_setting_test.go, internal/service/ssm/status.go, internal/service/ssm/wait.go
This PR fixes a panic happening on an empty service setting status result.
Closes #27225.
```
$ make testacc TESTARGS='-run=TestAccSSMServiceSetting_' PKG=ssm 
TF_ACC=1 go test ./internal/service/ssm/... -v -count 1 -parallel 20  -run=TestAccSSMServiceSetting_ -timeout 180m
=== RUN   TestAccSSMServiceSetting_basic
=== PAUSE TestAccSSMServiceSetting_basic
=== CONT  TestAccSSMServiceSetting_basic
--- PASS: TestAccSSMServiceSetting_basic (51.23s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/ssm        52.976s
```
=> r/aws_ssm_service_setting: fix panic on empty result

.changelog/27263.txt, internal/service/ecs/task_definition.go, internal/service/ecs/task_definition_test.go
Prevents a panic when a 'null' element is supplied as part of the `container_definitions` JSON array argument.
This fix validates against null, however we could possibly ignore null here instead? 
Closes #19531
```
make testacc TESTS=TestAccECSTaskDefinition_invalidContainerDefinition PKG=ecs
TF_ACC=1 go test ./internal/service/ecs/... -v -count 1 -parallel 20 -run='TestAccECSTaskDefinition_invalidContainerDefinition'  -timeout 180m
=== RUN   TestAccECSTaskDefinition_invalidContainerDefinition
=== PAUSE TestAccECSTaskDefinition_invalidContainerDefinition
=== CONT  TestAccECSTaskDefinition_invalidContainerDefinition
--- PASS: TestAccECSTaskDefinition_invalidContainerDefinition (2.31s)
PASS
ok …
```
=> resource/aws_ecs_task_definition - prevent panic on null container definition

.changelog/27238.txt, internal/service/organizations/find.go, internal/service/organizations/organizations_test.go, internal/service/organizations/policy_attachment.go, internal/service/organizations/policy_attachment_test.go
Properly handle missing policy when reading policy attachment.
Closes #27231
```
$ make testacc TESTS=TestAccOrganizations_serial/PolicyAttachment/BUG27231 PKG=organizations
TF_ACC=1 go test ./internal/service/organizations/... -v -count 1 -parallel 20 -run='TestAccOrganizations_serial/PolicyAttachment/BUG27231'  -timeout 180m
=== RUN   TestAccOrganizations_serial
=== RUN   TestAccOrganizations_serial/PolicyAttachment
=== RUN   TestAccOrganizations_serial/PolicyAttachment/BUG27231
--- PASS: TestAccOrganizations_serial (20.04s)
--- PASS: TestAccOrganizations_serial/PolicyAttachment (20.04s)
--- PASS: TestAccOrganizations_serial/PolicyAttachment/BUG27231 (20.04s)
PASS
ok …
```
=> Organizations Bugfix, handle missing policy when reading policy attachment

website/docs/d/ssm_patch_baseline.html.markdown, website/docs/r/ssm_patch_baseline.html.markdown
Set `data.aws_ssm_path_baseline.operating_system` as REQUIRED. It was wrongly documented as optional and it throws an error if missing.
Set Document all values for `data.aws_ssm_path_baseline.operating_system` 
Complete values for resource.aws_ssm_path_baseline.operating_system 
Closes #27239
[Enumeration of accepted Operative Systems](https://github.com/aws/aws-sdk-go/blob/1b418b64b1c7c36cb29b8455005f1964b75ba55c/models/apis/ssm/2014-11-06/api-2.json#L7414)
=> Document data ssm_path_baseline OS as optional and explicit values

.changelog/27236.txt, internal/service/lightsail/container_service.go, internal/service/lightsail/container_service_test.go, website/docs/r/lightsail_container_service.html.markdown
Adds Private Registry Access, see tagged issue for more information.
Closes #27201
```
$ make testacc TESTS=TestAccLightsailContainerService_ PKG=lightsail 
TF_ACC=1 go test ./internal/service/lightsail/... -v -count 1 -parallel 20 -run='TestAccLightsailContainerService_'  -timeout 180m
=== RUN   TestAccLightsailContainerService_basic
=== PAUSE TestAccLightsailContainerService_basic
=== RUN   TestAccLightsailContainerService_disappears
=== PAUSE TestAccLightsailContainerService_disappears
=== RUN   TestAccLightsailContainerService_Name
=== PAUSE TestAccLightsailContainerService_Name
=== RUN   TestAccLightsailContainerService_IsDisabled
=== PAUSE TestAccLightsailContainerService_IsDisabled
=== RUN …
```
=> Private Registry Access for Lightsail container services

website/docs/r/s3_bucket_lifecycle_configuration.html.markdown
Slight error in S3 bucket lifecycle config documentation.
Closes https://github.com/hashicorp/terraform-provider-aws/issues/26294.
=> fix s3 lifecycle error

website/docs/r/directory_service_directory.html.markdown
…_service_directory
When create an aws_directory_service_directory the fields `edition`, `size` have some exclusions depending on the value of `type`. For example, if `type` is `MicrosoftAD`, field `size` is ignored, and only if `type` is not `MicrosoftAD`, `edition` fields should be used.
Closes #16487
[directory cli command](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/ds/create-microsoft-ad.html)
=> Explicit options on AWS Directory docs for size, edition and type

website/docs/r/cloudfront_distribution.html.markdown
AWS have updated CloudFront with [Origin Access Controls (OAC)](https://aws.amazon.com/blogs/networking-and-content-delivery/amazon-cloudfront-introduces-origin-access-control-oac/) which now are considered a better option vs the previous origin access identity (OAI) method.
This PR updates the documentation/example for CloudFront to better reflect this use.
It also makes it clear that an `origin {}` block can contain one of `origin_access_control_id`, `s3_origin_config` (legacy OAI) or `custom_origin_config`.
=> Update CloudFront documentation to implement use of preferred `aws_cloudfront_origin_access_control` for S3 access.

skaff/datasource/datasourcetest.tmpl
This change brings the generation of the `ErrorCheck` field in data source acceptance tests into alignment with how the same field is generated for resources:
https://github.com/hashicorp/terraform-provider-aws/blob/238ded41ee735e9a9f0fd23569c4d80866961624/skaff/resource/resourcetest.tmpl#L70-L72
https://github.com/hashicorp/terraform-provider-aws/blob/238ded41ee735e9a9f0fd23569c4d80866961624/skaff/resource/resourcetest.tmpl#L183-L187
=> skaff: Update datasource `ErrorCheck` generation

.changelog/27278.txt, internal/provider/provider.go, internal/service/sesv2/configuration_set.go, internal/service/sesv2/dedicated_ip_pool.go, internal/service/sesv2/dedicated_ip_pool_data_source.go, internal/service/sesv2/dedicated_ip_pool_data_source_test.go, internal/service/sesv2/dedicated_ip_pool_test.go, website/docs/d/sesv2_dedicated_ip_pool.html.markdown, website/docs/r/sesv2_configuration_set.html.markdown, website/docs/r/sesv2_dedicated_ip_pool.html.markdown
Adds a new resource and data source `aws_sesv2_dedicated_ip_pool`. 
Relates #26796
Closes #10703
```console
$ make testacc PKG=sesv2 TESTS="TestAccSESV2DedicatedIPPool"
TF_ACC=1 go test ./internal/service/sesv2/... -v -count 1 -parallel 20 -run='TestAccSESV2DedicatedIPPool'  -timeout 180m
=== RUN   TestAccSESV2DedicatedIPPoolDataSource_basic
=== PAUSE TestAccSESV2DedicatedIPPoolDataSource_basic
=== RUN   TestAccSESV2DedicatedIPPool_basic
=== PAUSE TestAccSESV2DedicatedIPPool_basic
=== RUN   TestAccSESV2DedicatedIPPool_disappears
=== PAUSE TestAccSESV2DedicatedIPPool_disappears
=== RUN   TestAccSESV2DedicatedIPPool_tags
=== PAUSE TestAccSESV2DedicatedIPPool_tags
=== CONT  TestAccSESV2DedicatedIPPoolDataSource_basic
=== CONT …
```
=> New Resource `aws_sesv2_dedicated_ip_pool`

aws/provider.go, aws/resource_aws_lightsail_domain_entry.go, aws/resource_aws_lightsail_domain_entry_test.go, website/aws.erb, website/docs/r/lightsail_domain_entry.html.markdown
Add new resource `aws_lightsail_domain_entry`
Closes #2731
```release-note
aws/lightsail_domain_entry: New resource
```
```
make testacc TEST=./aws TESTARGS='-run=TestAccAWSLightsailDomainEntry_basic'
TF_ACC=1 go …
```
=> New resource: aws_lightsail_domain_entry

.changelog/27335.txt, internal/attrmap/attrmap.go, internal/service/sqs/queue.go, internal/service/sqs/queue_test.go
Always send any configured value of `sqs_managed_sse_enabled` when creating an SQS Queue.
In particular a configured `false` value is sent, which overrides the [new service default value of `true`](https://aws.amazon.com/about-aws/whats-new/2022/10/amazon-sqs-announces-server-side-encryption-ssq-managed-sse-sqs-default/).
Relates https://github.com/hashicorp/terraform-provider-aws/issues/22197.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/26843#issuecomment-1283586205.
```console
% make testacc TESTARGS='-run=TestAccSQSQueue_managedEncryption\|TestAccSQSQueue_basic\|TestAccSQSQueue_encryption' PKG=sqs ==> Checking that code complies with gofmt requirements... TF_ACC=1 go test ./internal/service/sqs/... -v -count 1 -parallel 20 …
```
=> r/aws_sqs_queue: Send any configured value of `sqs_managed_sse_enabled` on Create

.changelog/26934.txt, internal/service/resourcegroups/group.go, internal/service/resourcegroups/group_test.go, website/docs/r/resourcegroups_group.html.markdown
Closes #26933
I added some new acceptance tests for the configuration group and also verified that the additions don't fail the existing acceptance tests. 
```
$ make testacc TESTS=TestAccResourceGroupsGroup PKG=resourcegroups
TF_ACC=1 go test ./internal/service/resourcegroups/... -v -count 1 -parallel 20 -run='TestAccResourceGroupsGroup'  -timeout 180m
=== RUN   TestAccResourceGroupsGroup_Resource_basic
=== PAUSE TestAccResourceGroupsGroup_Resource_basic
=== RUN   TestAccResourceGroupsGroup_Resource_Configuration
=== PAUSE TestAccResourceGroupsGroup_Resource_Configuration
=== RUN   TestAccResourceGroupsGroup_Resource_tags
=== PAUSE TestAccResourceGroupsGroup_Resource_tags
=== CONT …
```
=> enhancement(resourcegroups): Add configuration type and attribute

.changelog/27257.txt, internal/service/appstream/stack.go, internal/service/appstream/stack_test.go, website/docs/r/appstream_stack.html.markdown
Reading an `aws_appstream_stack` causes a panic.
Adds validation and improves tests
Closes #27228
```
$ make testacc PKG=appstream TESTS=TestAccAppStreamStack_
--- PASS: TestAccAppStreamStack_basic (23.86s)
--- PASS: TestAccAppStreamStack_disappears (26.55s)
--- PASS: TestAccAppStreamStack_applicationSettings_removeFromDisabled (39.51s)
--- PASS: TestAccAppStreamStack_complete (50.26s)
--- PASS: TestAccAppStreamStack_withTags (52.54s)
--- PASS: TestAccAppStreamStack_applicationSettings_removeFromEnabled (56.85s)
--- PASS: TestAccAppStreamStack_applicationSettings_basic (78.10s)
```
=> resource/aws_appstream_stack: Fix panic on read

internal/service/kendra/sweep.go, internal/sweep/sweep.go
The AWS SDK for Go v2 returns a different error than v1, which was causing an error for Amazon Kendra in unsupported regions.
=> Fix Kendra sweepers

internal/service/sagemaker/sweep.go, internal/sweep/sweep.go
In unsupported regions, such as `us-west-1`, SageMaker returns the error `UnknownOperationException: The requested operation is not supported in the called region.` Treat this as skippable.
Also removes redundant `[ERROR]` log messages and fixes silent failures.
=> Fix SageMaker sweepers

website/docs/r/route53_record.html.markdown
Also change "can" to "should" in the same sentence because you do need
to specify the set identifier in the import command or the provider
won't be able to find the record.
=> r/route53_record docs for import: remove "delegated" word as it is unncessary and confusing.

.changelog/27377.txt, internal/service/meta/default_tags_data_source.go, internal/service/meta/default_tags_data_source_test.go
Fixes a **v4.36.0** regression where the `aws_default_tags` data source returns `null` vs. an empty map (`{}`) when no `default_tags` are configured.
Closes https://github.com/hashicorp/terraform-provider-aws/issues/27372.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/27221.
**N.B.** `unset TF_CLI_CONFIG_FILE` before running.
```console
% make testacc TESTARGS='-run=TestAccMetaDefaultTagsDataSource_' PKG=meta 
TF_ACC=1 go test ./internal/service/meta/... -v -count 1 -parallel 20  -run=TestAccMetaDefaultTagsDataSource_ -timeout 180m
=== RUN   TestAccMetaDefaultTagsDataSource_basic
=== PAUSE TestAccMetaDefaultTagsDataSource_basic
=== RUN   TestAccMetaDefaultTagsDataSource_empty
=== PAUSE …
```
=> d/aws_default_tags: Fix regression with `null` vs. empty map

.changelog/27306.txt, internal/service/ec2/transitgateway_.go, internal/service/ec2/transitgateway_test.go, website/docs/r/ec2_transit_gateway.html.markdown
Add support for modifying the ASN on resource `aws_ec2_transit_gateway`
Closes #27301
- https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/ec2@v1.63.1/types#ModifyTransitGatewayOptions
- https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_ModifyTransitGatewayOptions.html
```
$ make testacc TESTARGS='-run=TestAccTransitGateway_serial/Gateway/AmazonSideASN' PKG=ec2
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 20  -run=TestAccTransitGateway_serial/Gateway/AmazonSideASN -timeout 180m
=== RUN   TestAccTransitGateway_serial
=== RUN   TestAccTransitGateway_serial/Gateway
=== RUN   TestAccTransitGateway_serial/Gateway/AmazonSideASN
--- PASS: TestAccTransitGateway_serial (140.65s)
--- PASS: …
```
=> Add support for modifying Transit Gateway ASN

.changelog/27347.txt, internal/service/connect/contact_flow.go, website/docs/r/connect_contact_flow.html.markdown
Add a `ForceNew` on the `type` argument
Closes #26790
```
$ make testacc TESTARGS='-run=TestAccConnect_serial/ContactFlow/' PKG=connect
TF_ACC=1 go test ./internal/service/connect/... -v -count 1 -parallel 20  -run=TestAccConnect_serial/ContactFlow/ -timeout 180m
=== RUN   TestAccConnect_serial
=== RUN   TestAccConnect_serial/ContactFlow
=== RUN   TestAccConnect_serial/ContactFlow/basic
=== RUN   TestAccConnect_serial/ContactFlow/disappears
=== RUN   TestAccConnect_serial/ContactFlow/filename
=== RUN   TestAccConnect_serial/ContactFlow/dataSource_id
=== RUN   TestAccConnect_serial/ContactFlow/dataSource_name
=== RUN   TestAccConnect_serial/ContactFlowModule
=== RUN   TestAccConnect_serial/ContactFlowModule/dataSource_id
=== RUN …
```
=> b/aws_connect_contact_flow - type force new

internal/service/networkfirewall/rule_group_test.go
Small modification to the ANFW Rule Group stateful rules test in Suricata flat file format. This ensures that multi-line and comments are supported by both the Terraform provider and the upstream service. No changelog required per the Changelog policy.
Relates #26517
https://docs.aws.amazon.com/network-firewall/latest/APIReference/API_CreateRuleGroup.html
```
terraform-provider-aws % make testacc TESTARGS='-run=TestAccNetworkFirewallRuleGroup_Basic_rules' PKG=networkfirewall
TF_ACC=1 go test ./internal/service/networkfirewall/... -v -count 1 -parallel 20  -run=TestAccNetworkFirewallRuleGroup_Basic_rules -timeout 180m
=== RUN   TestAccNetworkFirewallRuleGroup_Basic_rulesSourceList
=== PAUSE …
```
=> Ensure Suricata flat file comments are supported for ANFW Rule Group tests

.changelog/27336.txt, internal/service/evidently/find.go, internal/service/evidently/project.go, internal/service/evidently/project_test.go, internal/service/evidently/status.go, internal/service/evidently/wait.go, website/docs/r/evidently_project.html.markdown
CloudWatch Evidently Project has a `status` attribute (docs: [API_GetProject](https://docs.aws.amazon.com/cloudwatchevidently/latest/APIReference/API_GetProject.html)). Valid values of `status` are `AVAILABLE` and `UPDATING`
Relates #24263
Relates #22624
```
$ make testacc TESTARGS='-run=TestAccEvidentlyProject' PKG=evidently
TF_ACC=1 go test ./internal/service/evidently/... -v -count 1 -parallel 20  -run=TestAccEvidentlyProject -timeout 180m
=== RUN   TestAccEvidentlyProject_basic
=== PAUSE TestAccEvidentlyProject_basic
=== RUN   TestAccEvidentlyProject_tags
=== PAUSE TestAccEvidentlyProject_tags
=== RUN   TestAccEvidentlyProject_updateDataDeliveryCloudWatchLogGroup
=== PAUSE …
```
=> r/aws_evidently_project - waiters

website/docs/r/secretsmanager_secret_rotation.html.markdown
Fixes `markdown-link` error:
```
FILE: website/docs/r/secretsmanager_secret_rotation.html.markdown
[✖] https://docs.aws.amazon.com/secretsmanager/latest/userguide/rotating-secrets_strategies.html → Status: 404
3 links checked.
ERROR: 1 dead links found!
[✖] https://docs.aws.amazon.com/secretsmanager/latest/userguide/rotating-secrets_strategies.html → Status: 404
```
=> r/aws_secretsmanager_rotation: Correct secrets rotation link

CHANGELOG.md, website/docs/r/secretsmanager_secret.html.markdown
Fixes `markdown-link` error:
```
FILE: website/docs/r/secretsmanager_secret.html.markdown
[✖] https://docs.aws.amazon.com/secretsmanager/latest/userguide/rotating-secrets_strategies.html → Status: 404
6 links checked.
ERROR: 1 dead links found!
[✖] https://docs.aws.amazon.com/secretsmanager/latest/userguide/rotating-secrets_strategies.html → Status: 404
```
=> r/aws_secretsmanager_(rotation|secret): Correct secrets rotation link

.changelog/27388.txt, internal/service/sesv2/dedicated_ip_pool.go, internal/service/sesv2/dedicated_ip_pool_data_source.go, internal/service/sesv2/dedicated_ip_pool_test.go, website/docs/d/sesv2_dedicated_ip_pool.html.markdown, website/docs/r/sesv2_dedicated_ip_pool.html.markdown
Adds support for the `scaling_mode` attribute released in [`v1.14.0` of the SES Go SDK](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/sesv2@v1.14.0#CreateDedicatedIpPoolInput).
Relates #26796
```console
$ make testacc PKG=sesv2 TESTS="TestAccSESV2DedicatedIPPool" ACCTEST_PARALLELISM=2
TF_ACC=1 go test ./internal/service/sesv2/... -v -count 1 -parallel 2 -run='TestAccSESV2DedicatedIPPool'  -timeout 180m
=== RUN   TestAccSESV2DedicatedIPPoolDataSource_basic
=== PAUSE TestAccSESV2DedicatedIPPoolDataSource_basic
=== RUN   TestAccSESV2DedicatedIPPool_basic
=== PAUSE TestAccSESV2DedicatedIPPool_basic
=== RUN   TestAccSESV2DedicatedIPPool_disappears
=== PAUSE TestAccSESV2DedicatedIPPool_disappears
=== RUN …
```
=> Add `scaling_mode` attribute for  `aws_sesv2_dedicated_ip_pool`

.changelog/27367.txt, CHANGELOG.md, internal/service/rds/proxy_endpoint.go
Allow provider's default tags to be stored for `aws_rds_proxy_endpoint`, and remove
```
~ resource "aws_db_proxy_endpoint" "rds_proxy_read_only_endpoint" {
id                     = "production-proxy/production-proxy-read-only"
tags                   = {
"Name" = "production-proxy-read-only-endpoint"
}
~ tags_all               = {
+ "environment"     = "production"
+ "service"         = "ticketing"
}
}
Plan: 0 to add, 1 to change, 0 to destroy.
```
from every plan.
Relates #25477
```
$ make testacc TESTS=TestAccRDSProxyEndpoint_tags PKG=rds
TF_ACC=1 go test ./internal/service/rds/... -v -count 1 -parallel 20 -run='TestAccRDSProxyEndpoint_tags'  -timeout 180m
=== RUN …
```
=> Fix resource/aws_rds_proxy_endpoint: Respect `tags_all` attribute

.changelog/27329.txt, internal/service/ssm/parameter.go, internal/service/ssm/parameter_test.go, website/docs/r/ssm_parameter.html.markdown
Add support for `data_type argument` `aws:ssm:integration`
These parameters are only used for creating webhook [integrations ](https://docs.aws.amazon.com/systems-manager/latest/userguide/creating-integrations.html) as part of an 'automation' in [AWS Systems Manager](https://docs.aws.amazon.com/systems-manager/index.html) 
Closes #27146
https://docs.aws.amazon.com/systems-manager/latest/userguide/systems-manager-automation.html
https://docs.aws.amazon.com/systems-manager/latest/userguide/creating-integrations.html
```
make testacc TESTS=TestAccSSMParameter_DataType_ssmIntegration PKG=ssm
TF_ACC=1 go test ./internal/service/ssm/... -v -count 1 -parallel 20 -run='TestAccSSMParameter_DataType_ssmIntegration'  -timeout 180m
=== RUN …
```
=> r/aws_ssm_parameter - add support for aws:ssm:integration data_type

.changelog/27361.txt, docs/acc-test-environment-variables.md, internal/provider/provider.go, internal/service/sesv2/dedicated_ip_assignment.go, internal/service/sesv2/dedicated_ip_assignment_test.go, internal/service/sesv2/dedicated_ip_pool_data_source_test.go, internal/service/sesv2/dedicated_ip_pool_test.go, website/docs/r/sesv2_dedicated_ip_assignment.html.markdown
This resource will manage assignment of "standard" SES dedicated IP addresses to a dedicated IP pool. 
Relates #26796
Requesting a dedicated IP address from AWS
https://docs.aws.amazon.com/ses/latest/dg/dedicated-ip-case.html
Bring your own IP address
https://docs.aws.amazon.com/ses/latest/dg/dedicated-ip-byo.html
Default IP pool `ses-default-dedicated-ip-pool`
https://docs.aws.amazon.com/ses/latest/dg/managing-ip-pools.html
```console
$ SES_DEDICATED_IP="X.X.X.X" make testacc PKG=sesv2 TESTS="TestAccSESV2DedicatedIPAssignment_"
TF_ACC=1 go test ./internal/service/sesv2/... -v -count 1 -parallel 20 -run='TestAccSESV2DedicatedIPAssignment_'  -timeout 180m
=== RUN   TestAccSESV2DedicatedIPAssignment_serial
=== RUN …
```
=> New Resource `aws_sesv2_dedicated_ip_assignment`

.changelog/27390.txt, internal/service/ecs/service.go
Make the `task_definition` for `aws_ecs_service` truly optional.
It is defined as so in the schema, but when preparing the request body to be sent to the AWS API, it was adding the taskDefinition parameter with an empty string.
AWS doesn't accept it when defining a Service with `Deployment=EXTERNAL`:
```
An error occurred (InvalidParameterException) when calling the CreateService operation: Family should not be null or empty.
```
Closes #27362
Not sure what's the best way to test this. The result of applying the ECS service doesn't change, only what is sent to the AWS API
```
```
=> fix resource/aws_ecs_service: make task_definition truly optional

website/docs/r/transfer_workflow.html.markdown
Create an example to demonstrate how multiple steps can be used within the `aws_transfer_workflow` resource.
[Example question](https://discuss.hashicorp.com/t/aws-transfer-workflow-resource-syntax-example-for-multiple-steps/44455) on the forums suggesting clarification would be helpful. 
I, personally, worked backwards using `terraform import` to find out the expected syntax for multiple steps.
=> Provide multi step example for aws_transfer_workflow resource

.changelog/27345.txt, internal/service/apprunner/status.go, internal/service/apprunner/vpc_connector.go, internal/service/apprunner/vpc_connector_test.go, internal/service/apprunner/wait.go, website/docs/r/apprunner_vpc_connector.html.markdown
Adds the ability to modify tags for `aws_apprunner_vpc_connector `.
Closes [#26426](https://github.com/hashicorp/terraform-provider-aws/issues/26426)
https://pkg.go.dev/github.com/aws/aws-sdk-go@v1.44.118/service/apprunner#AppRunner.TagResource
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/apprunner_vpc_connector
https://docs.aws.amazon.com/apprunner/latest/api/API_TagResource.html
```
make testacc PKG=apprunner TESTS=TestAccAppRunnerVPCConnector      
TF_ACC=1 go test ./internal/service/apprunner/... -v -count 1 -parallel 20 -run='TestAccAppRunnerVPCConnector'  -timeout 180m
=== RUN   TestAccAppRunnerVPCConnector_basic
=== PAUSE TestAccAppRunnerVPCConnector_basic
=== RUN …
```
=> add support for updating tags in apprunner vpc connection

.changelog/27458.txt, internal/service/ec2/ec2_capacity_reservation.go, internal/service/ec2/ec2_capacity_reservation_test.go, website/docs/r/ec2_capacity_reservation.html.markdown
Adds support for placement_group_arn attribute
Closes https://github.com/hashicorp/terraform-provider-aws/issues/27429.
https://docs.aws.amazon.com/cli/latest/reference/ec2/create-capacity-reservation.html
```
❯ make testacc TESTS=TestAccEC2CapacityReservation_basic PKG=ec2
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 20 -run='TestAccEC2CapacityReservation_basic'  -timeout 180m
=== RUN   TestAccEC2CapacityReservation_basic
=== PAUSE TestAccEC2CapacityReservation_basic
=== CONT  TestAccEC2CapacityReservation_basic
--- PASS: TestAccEC2CapacityReservation_basic (19.41s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/ec2        19.476s
...
```
=> aws_ec2_capacity_reservation placement_group_arn attribute support

.changelog/27340.txt, internal/service/ec2/vpc_flow_log_test.go, website/docs/r/flow_log.html.markdown
Adds validation for VPC Flow logs destination type as Kinesis Data Firehose
Closes #26730
```
$make testacc TESTARGS='-run=TestAccVPCFlowLog' PKG=ec2
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 2  -run=TestAccVPCFlowLog -timeout 180m
=== RUN   TestAccVPCFlowLog_vpcID
=== PAUSE TestAccVPCFlowLog_vpcID
=== RUN   TestAccVPCFlowLog_logFormat
=== PAUSE TestAccVPCFlowLog_logFormat
=== RUN   TestAccVPCFlowLog_subnetID
=== PAUSE TestAccVPCFlowLog_subnetID
=== RUN   TestAccVPCFlowLog_transitGatewayID
=== PAUSE TestAccVPCFlowLog_transitGatewayID
=== RUN   TestAccVPCFlowLog_transitGatewayAttachmentID
=== PAUSE TestAccVPCFlowLog_transitGatewayAttachmentID
=== RUN   TestAccVPCFlowLog_LogDestinationType_cloudWatchLogs
=== …
```
=> [Enhancement] Support Amazon VPC Flow Logs to Kinesis Data Firehose

.changelog/27341.txt, internal/provider/provider.go, internal/service/directconnect/router_configuration_data_source.go, internal/service/directconnect/router_configuration_data_source_test.go, website/docs/d/dx_router_configuration.html.markdown
Adds the `aws_dx_router_configuration` data source to allow users to download sample router configurations for their Direct Connect VIF.
Closes #26432
https://docs.aws.amazon.com/directconnect/latest/UserGuide/create-vif.html#vif-router-config 
https://docs.aws.amazon.com/sdk-for-go/api/service/directconnect/#DirectConnect.DescribeRouterConfiguration
https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/directconnect#Client.DescribeRouterConfiguration 
https://docs.aws.amazon.com/directconnect/latest/APIReference/API_DescribeRouterConfiguration.html 
https://docs.aws.amazon.com/directconnect/latest/APIReference/API_RouterType.html
Note that a DX VIF must be provided via the `VIRTUAL_INTERFACE_ID` env variable.
```
terraform-provider-aws % AWS_DEFAULT_REGION=eu-west-1 …
```
=> Add data source for DX Router Configuration

.changelog/27464.txt, internal/service/elbv2/target_group.go, internal/service/elbv2/target_group_test.go
Adds the reading and setting of the `ip_address_type` value during the resource read.
Closes #27463
```
make testacc TESTARGS='-run=TestAccELBV2TargetGroup_ipAddressType' PKG=elbv2
TF_ACC=1 go test ./internal/service/elbv2/... -v -count 1 -parallel 20  -run=TestAccELBV2TargetGroup_ipAddressType -timeout 180m
=== RUN   TestAccELBV2TargetGroup_ipAddressType
=== PAUSE TestAccELBV2TargetGroup_ipAddressType
=== CONT  TestAccELBV2TargetGroup_ipAddressType
--- PASS: TestAccELBV2TargetGroup_ipAddressType (22.02s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/elbv2      23.960s
...
```
=> BugFix: Resolve import issues on `aws_lb_target_group` when specifying `ip_address_type` of `ipv4`

.changelog/27473.txt, internal/service/route53/traffic_policy_document_data_source_test.go, internal/service/route53/traffic_policy_document_model.go
Small change that corrects the generated JSON for Route53 Traffic Policy document - Changed the capitalization of the `GeoproximityLocations` stanza to match the documentation and ensures the resource is correctly provisioned. 
Closes #26481
* [Route53 Traffic Policy document format](https://docs.aws.amazon.com/Route53/latest/APIReference/api-policies-traffic-policy-document-format.html#traffic-policy-document-format-rules-geoproximity)
```
$  make testacc TESTS=TestAccRoute53TrafficPolicyDocumentDataSource_complete PKG=route53
TF_ACC=1 go test ./internal/service/route53/... -v -count 1 -parallel 20 -run='TestAccRoute53TrafficPolicyDocumentDataSource_complete'  -timeout 180m
=== RUN …
```
=> Route53/TrafficPolicyDocument - fixes the JSON output for GeoproximityLocations config block

.changelog/27462.txt, internal/provider/provider.go, internal/service/lightsail/consts.go, internal/service/lightsail/find.go, internal/service/lightsail/lb_certificate.go, internal/service/lightsail/lb_certificate_attachment.go, internal/service/lightsail/lb_certificate_attachment_test.go, internal/service/lightsail/lb_certificate_test.go, website/docs/r/lightsail_lb_certificate.html.markdown, website/docs/r/lightsail_lb_certificate_attachment.html.markdown
This Pull request provides the following two resources:
`aws_lightsail_lb_certificate` and `aws_lightsail_lb_certificate_attachment`
None
```
make testacc TESTARGS='-run=TestAccLightsailLoadBalancerCertificate_' PKG=lightsail 
TF_ACC=1 go test ./internal/service/lightsail/... -v -count 1 -parallel 20  -run=TestAccLightsailLoadBalancerCertificate_ -timeout 180m
=== RUN   TestAccLightsailLoadBalancerCertificate_basic
=== PAUSE TestAccLightsailLoadBalancerCertificate_basic
=== RUN   TestAccLightsailLoadBalancerCertificate_subjectAlternativeNames
=== PAUSE TestAccLightsailLoadBalancerCertificate_subjectAlternativeNames
=== RUN   TestAccLightsailLoadBalancerCertificate_domainValidationRecords
=== PAUSE …
```
=> New Resources: `aws_lightsail_lb_certificate` and `aws_lightsail_lb_certificate_attachment`

.changelog/27223.txt, internal/provider/fwprovider/provider.go, internal/provider/provider.go, internal/service/medialive/medialive_test.go, internal/service/medialive/multiplex_program.go, internal/service/medialive/multiplex_program_test.go, website/docs/r/medialive_multiplex_program.html.markdown
Statmux is a shortened name for Statistical Multiplexing
Rename code references from `statemux` and `Statemux` to `statmux` and `Statmux` respectively.
Relates #4936
See: 
- https://en.wikipedia.org/wiki/Statistical_time-division_multiplexing
- https://aws.amazon.com/medialive/features/statmux/
```
$ make testacc TESTS=TestAccMediaLive_serial PKG=medialive
...
```
=> Use proper name for networking term Statmux

website/docs/d/route53_traffic_policy_document.html.markdown
Added an example of a complex traffic policy with nested rules while showcasing the use of the `geoproximity` rule type. The coded example builds on the details provided in the AWS documentation for [Geoproximity routing policy](https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/routing-policy-geoproximity.html)
N/A
* https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/routing-policy-geoproximity.html
N/A
=> Documentation update for Route53 Traffic Policy data source

website/docs/r/db_parameter_group.html.markdown
Adds a new example to the `aws_db_parameter_group` documentation on when to apply the `create_before_destroy` lifecycle configuration.
Relates #6448
=> r/aws_db_parameter_group: create_before_destroy example

.changelog/27512.txt, internal/service/ec2/errors.go, internal/service/ec2/find.go, internal/service/ec2/ipam_pool.go, internal/service/ec2/ipam_pool_cidr.go, internal/service/ec2/ipam_pool_cidr_allocation.go, internal/service/ec2/ipam_pool_cidr_allocation_test.go, internal/service/ec2/ipam_pool_cidr_test.go, internal/service/ec2/status.go, internal/service/ec2/wait.go
Adds pagination to pool CIDR lookup, avoiding a crash when the CIDR is not found.
Closes https://github.com/hashicorp/terraform-provider-aws/issues/27424.
```console
% make testacc TESTARGS='-run=TestAccIPAMPoolCIDR_' PKG=ec2 ACCTEST_PARALLELISM=3
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 3  -run=TestAccIPAMPoolCIDR_ -timeout 180m
=== RUN   TestAccIPAMPoolCIDR_basic
=== PAUSE TestAccIPAMPoolCIDR_basic
=== RUN   TestAccIPAMPoolCIDR_disappears
=== PAUSE TestAccIPAMPoolCIDR_disappears
=== RUN   TestAccIPAMPoolCIDR_Disappears_ipam
=== PAUSE TestAccIPAMPoolCIDR_Disappears_ipam
=== CONT  TestAccIPAMPoolCIDR_basic
=== CONT  TestAccIPAMPoolCIDR_Disappears_ipam
=== CONT  TestAccIPAMPoolCIDR_disappears
--- PASS: …
```
=> r/aws_vpc_ipam_pool_cidr: Avoid crash when CIDR not found

.changelog/27500.txt, internal/service/elasticache/global_replication_group.go, internal/service/elasticache/global_replication_group_test.go, internal/service/elasticache/replication_group.go, internal/service/elasticache/sweep.go, internal/service/elasticache/wait.go, website/docs/r/elasticache_global_replication_group.html.markdown, website/docs/r/elasticache_replication_group.html.markdown
Allow configuring shards (node groups) on ElastiCache Global Replication Groups.
Closes #22752
```
$ make testacc PKG=elasticache TESTS=TestAccElastiCacheGlobalReplicationGroup_
--- PASS: TestAccElastiCacheGlobalReplicationGroup_SetParameterGroupOnCreate_NoVersion (8.67s)
--- PASS: TestAccElastiCacheGlobalReplicationGroup_SetParameterGroupOnUpdate_MinorUpgrade (863.27s)
--- PASS: TestAccElastiCacheGlobalReplicationGroup_SetEngineVersionOnCreate_NoChange_v6 (884.56s)
--- PASS: TestAccElastiCacheGlobalReplicationGroup_SetEngineVersionOnCreate_MajorUpgrade_6x (1106.86s)
--- PASS: TestAccElastiCacheGlobalReplicationGroup_SetEngineVersionOnCreate_NoChange_v6x (1198.54s)
--- PASS: TestAccElastiCacheGlobalReplicationGroup_SetEngineVersionOnCreate_NoChange_v5 (1199.13s)
--- PASS: …
```
=> resource/aws_elasticache_global_replication_group: Allow configuring shards

.github/dependabot.yml
Align the `/go.mod` dependabot configuration with [`terraform-provider-awscc`](https://github.com/hashicorp/terraform-provider-awscc).
Relates https://github.com/hashicorp/terraform-provider-awscc/pull/714.
=> `/go.mod` dependabot configuration aligns with `terraform-provider-awscc`

website/docs/d/cloudfront_cache_policy.html.markdown, website/docs/d/cloudfront_origin_request_policy.html.markdown, website/docs/d/cloudfront_response_headers_policy.html.markdown
This PR adds examples for retrieving managed CloudFront cache and origin request policies.
The syntax is somewhat obscure, and it doesn't look like it's explained anywhere.
I found it buried a Reddit discussion. Not the first place I would look at...
Closes #27492 
https://www.reddit.com/r/Terraform/comments/qzqt8a/how_to_get_cache_policy_id_for_cloudfront/
N/A
=> d/Add examples for retrieving managed CloudFront policies

website/docs/r/eks_node_group.html.markdown
A code block in [EKS node group docs](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/eks_node_group) is missing closing backticks and that breaks formatting in the rest of the page.
N/A
[Documentation page that needs reformatting](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/eks_node_group)
N/A
=> docs: a code block was missing closing backticks

.changelog/27538.txt, internal/service/ec2/sweep.go, internal/service/sagemaker/sagemaker_test.go, internal/service/sagemaker/status.go, internal/service/sagemaker/wait.go, internal/service/sagemaker/workforce.go, internal/service/sagemaker/workforce_test.go, website/docs/r/sagemaker_workforce.html.markdown
Add support for VPC config for sagemaker workforce.
```
$ make testacc TESTS=TestAccSageMaker_serial/Workforce PKG=sagemaker
--- PASS: TestAccSageMaker_serial (641.34s)
--- PASS: TestAccSageMaker_serial/Workforce (641.34s)
--- PASS: TestAccSageMaker_serial/Workforce/OidcConfig (67.75s)
--- PASS: TestAccSageMaker_serial/Workforce/SourceIpConfig (114.52s)
--- PASS: TestAccSageMaker_serial/Workforce/VPC (366.91s)
--- PASS: TestAccSageMaker_serial/Workforce/disappears (43.61s)
--- PASS: TestAccSageMaker_serial/Workforce/CognitoConfig (48.55s)
```
=> Sagemaker workforce - vpc support

.changelog/27548.txt, internal/provider/provider.go, internal/service/sagemaker/sagemaker_test.go, internal/service/sagemaker/servicecatalog_portfolio_status.go, internal/service/sagemaker/servicecatalog_portfolio_status_test.go, website/docs/r/sagemaker_servicecatalog_portfolio_status.html.markdown
Closes #23917
```
$ make testacc TESTS=TestAccSageMaker_serial/Servicecatalog PKG=sagemaker
--- PASS: TestAccSageMaker_serial (86.55s)
--- PASS: TestAccSageMaker_serial/Servicecatalog (86.55s)
--- PASS: TestAccSageMaker_serial/Servicecatalog/basic (86.55s)
```
=> add aws_sagemaker_servicecatalog_portfolio_status resource

.changelog/27514.txt, internal/provider/provider.go, internal/service/lightsail/consts.go, internal/service/lightsail/find.go, internal/service/lightsail/lb_stickiness_policy.go, internal/service/lightsail/lb_stickiness_policy_test.go, website/docs/r/lightsail_lb_stickiness_policy.html.markdown
This PR adds a new `aws_lightsail_lb_stickiness_policy`  resource. This allows management of Stickiness settings on Lightsail Load balancers. 
```
$ make testacc TESTARGS='-run=TestAccLightsailLoadBalancerStickinessPolicy_' PKG=lightsail      
TF_ACC=1 go test ./internal/service/lightsail/... -v -count 1 -parallel 20  -run=TestAccLightsailLoadBalancerStickinessPolicy_ -timeout 180m
=== RUN   TestAccLightsailLoadBalancerStickinessPolicy_basic
=== PAUSE TestAccLightsailLoadBalancerStickinessPolicy_basic
=== RUN   TestAccLightsailLoadBalancerStickinessPolicy_CookieDuration
=== PAUSE TestAccLightsailLoadBalancerStickinessPolicy_CookieDuration
=== RUN   TestAccLightsailLoadBalancerStickinessPolicy_disappears
=== PAUSE …
```
=> New Resource: `aws_lightsail_lb_stickiness_policy` 

.changelog/27537.txt, internal/provider/provider.go, internal/service/lightsail/consts.go, internal/service/lightsail/disk.go, internal/service/lightsail/disk_attachment.go, internal/service/lightsail/disk_attachment_test.go, internal/service/lightsail/disk_test.go, internal/service/lightsail/find.go, internal/service/lightsail/status.go, internal/service/lightsail/wait.go, website/docs/r/lightsail_disk.html.markdown, website/docs/r/lightsail_disk_attachment.html.markdown
This PR provides the following two resources: `aws_lightsail_disk` and `aws_lightsail_disk_attachment` 
Users will be able to manage lightsail disks and attaching them to instances with terraform. 
This is a revive of the #9975 pull request. I was unable to pull in commits from that PR as i received an access denied error when attempting. 
Closes #9975
```
$ make testacc TESTARGS='-run=TestAccLightsailDisk' PKG=lightsail
TF_ACC=1 go test ./internal/service/lightsail/... -v -count 1 -parallel 20  -run=TestAccLightsailDisk -timeout 180m
=== RUN   TestAccLightsailDiskAttachment_basic
=== PAUSE TestAccLightsailDiskAttachment_basic
=== RUN   TestAccLightsailDiskAttachment_disappears
=== PAUSE TestAccLightsailDiskAttachment_disappears …
```
=> New Resources: `aws_lightsail_disk` and `aws_lightsail_disk_attachment`

.changelog/27558.txt, internal/service/meta/ip_ranges_data_source.go, internal/service/meta/ip_ranges_data_source_test.go, internal/service/meta/service_data_source.go, internal/slices/slices.go, internal/slices/slices_test.go
Fixes a regression introduced in https://github.com/hashicorp/terraform-provider-aws/pull/27221 whereby comparisons for `regions` and `services` became case-sensitive.
Closes https://github.com/hashicorp/terraform-provider-aws/issues/27554.
```console
% make testacc TESTARGS='-run=TestAccMetaIPRangesDataSource_' PKG=meta ACCTEST_PARALLELISM=3 
TF_ACC=1 go test ./internal/service/meta/... -v -count 1 -parallel 3  -run=TestAccMetaIPRangesDataSource_ -timeout 180m
=== RUN   TestAccMetaIPRangesDataSource_basic
=== PAUSE TestAccMetaIPRangesDataSource_basic
=== RUN   TestAccMetaIPRangesDataSource_none
=== PAUSE TestAccMetaIPRangesDataSource_none
=== RUN   TestAccMetaIPRangesDataSource_url
=== PAUSE TestAccMetaIPRangesDataSource_url
=== …
```
=> d/aws_ip_ranges: Case insensitive comparison for `regions` and `services`

.changelog/27561.txt, internal/service/ec2/ebs_volume.go, internal/service/ec2/ec2_ami.go, internal/service/ec2/ec2_ami_copy.go, internal/service/ec2/ec2_ami_from_instance.go, internal/service/ec2/ec2_host.go, internal/service/ec2/ec2_host_test.go, internal/service/ec2/ec2_instance.go, internal/service/ec2/ec2_spot_fleet_request.go, internal/service/ec2/ec2_spot_instance_request.go, internal/service/ec2/vpc_egress_only_internet_gateway.go, internal/service/ec2/vpc_endpoint.go, internal/service/ec2/vpc_flow_log.go, internal/service/ec2/vpc_nat_gateway.go, internal/service/ec2/vpc_network_interface.go
Uses the EC2 API `ClientToken` where applicable to ensure API idempotency.
Closes https://github.com/hashicorp/terraform-provider-aws/issues/27543.
AMI changes - Relates https://github.com/hashicorp/terraform-provider-aws/issues/27083.
EC2 API Reference: https://docs.aws.amazon.com/AWSEC2/latest/APIReference/Run_Instance_Idempotency.html.
```console
% make testacc TESTARGS='-run=TestAccEC2Instance_withIAMInstanceProfile' PKG=ec2 ACCTEST_PARALLELISM=3
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 3  -run=TestAccEC2Instance_withIAMInstanceProfile -timeout 180m
=== RUN   TestAccEC2Instance_withIAMInstanceProfile
=== PAUSE TestAccEC2Instance_withIAMInstanceProfile
=== RUN …
```
=> EC2: API idempotency

.changelog/27566.txt, internal/service/dynamodb/table.go, internal/service/dynamodb/table_test.go
Closes #15189
```console
% make testacc TESTS=TestAccDynamoDBTable_ PKG=dynamodb 
TF_ACC=1 go test ./internal/service/dynamodb/... -v -count 1 -parallel 20 -run='TestAccDynamoDBTable_'  -timeout 180m
--- PASS: TestAccDynamoDBTable_attributeUpdateValidation (20.52s)
--- PASS: TestAccDynamoDBTable_basic (53.59s)
--- PASS: TestAccDynamoDBTable_TTL_enabled (54.58s)
--- PASS: TestAccDynamoDBTable_GsiUpdateNonKeyAttributes_emptyPlan (72.43s)
--- PASS: TestAccDynamoDBTable_TTL_disabled (77.42s)
--- PASS: TestAccDynamoDBTable_tableClassInfrequentAccess (85.43s)
--- PASS: TestAccDynamoDBTable_lsiUpdate (93.09s)
--- PASS: TestAccDynamoDBTable_BillingModeGSI_payPerRequestToProvisioned (100.83s)
--- PASS: …
```
=> dynamodb/table: Fix stream diff bugs

.changelog/27433.txt, internal/provider/provider.go, internal/service/sesv2/email_identity_feedback_attributes.go, internal/service/sesv2/email_identity_feedback_attributes_test.go, website/docs/r/sesv2_email_identity_feedback_attributes.html.markdown
This PR introduces a resource that allows managing feedback attributes of AWS SES Email Identity (namely `email_forwarding_enabled` for now).
Closes #14622.
Closes #4182.
https://docs.aws.amazon.com/ses/latest/APIReference-V2/API_PutEmailIdentityFeedbackAttributes.html
https://docs.aws.amazon.com/ses/latest/APIReference-V2/API_GetEmailIdentity.html
```
$ make testacc TESTARGS='-run=TestAccSESV2EmailIdentityFeedbackAttributes_' PKG=sesv2 ACCTEST_PARALLELISM=2
TF_ACC=1 go test ./internal/service/sesv2/... -v -count 1 -parallel 2  -run=TestAccSESV2EmailIdentityFeedbackAttributes_ -timeout 180m
=== RUN   TestAccSESV2EmailIdentityFeedbackAttributes_basic
=== PAUSE TestAccSESV2EmailIdentityFeedbackAttributes_basic
=== …
```
=> r/aws_sesv2_email_identity_feedback_attributes: new resource

internal/service/acmpca/certificate_authority_test.go
Set `usage_mode` to `SHORT_LIVED_CERTIFICATE` to reduce costs when running ACMPCA CA tests.
Closes #27524
```
$ make testacc TESTS=TestAccACMPCACertificateAuthority_ PKG=acmpca
TF_ACC=1 go test ./internal/service/acmpca/... -v -count 1 -parallel 20 -run='TestAccACMPCACertificateAuthority_'  -timeout 180m
=== RUN   TestAccACMPCACertificateAuthority_basic
=== PAUSE TestAccACMPCACertificateAuthority_basic
=== RUN   TestAccACMPCACertificateAuthority_disappears
=== PAUSE TestAccACMPCACertificateAuthority_disappears
=== RUN   TestAccACMPCACertificateAuthority_enabledDeprecated
=== PAUSE TestAccACMPCACertificateAuthority_enabledDeprecated
=== RUN   TestAccACMPCACertificateAuthority_usageMode
=== PAUSE …
```
=> Use `SHORT_LIVED_CERTIFICATE` ACMPCA CAs to reduce costs

website/docs/r/default_network_acl.html.markdown
At some point the relative position of this sentence and the content it refers to were switched on the page. The sentence currently directs the reader to scroll down for more information, but this information is now above the sentence.
=> Documentation Fix:  Fix reference to location of information on page

website/docs/d/acm_certificate.html.markdown
The `types` property supports `PRIVATE` as a value as well. Current documentation only indicates `AMAZON_ISSUED` and `IMPORTED` only. 
None
See more on [API documentatio](https://docs.aws.amazon.com/acm/latest/APIReference/API_CertificateDetail.html#ACM-Type-CertificateDetail-Type).
None, documentation change only
=> Correct supported types for ACM cert data source

internal/acctest/acctest.go, internal/acctest/provider_test.go, internal/provider/factory.go, main.go
Fixes failing `acctest` provider acceptance tests by using _ProtoV5ProviderFactories_.
Closes https://github.com/hashicorp/terraform-provider-aws/issues/27592.
```console
% make testacc TESTARGS='-run=TestAccProvider_' PKG_NAME=internal/acctest ACCTEST_PARALLELISM=2 
TF_ACC=1 go test ./internal/acctest/... -v -count 1 -parallel 2  -run=TestAccProvider_ -timeout 180m
=== RUN   TestAccProvider_DefaultTags_emptyBlock
=== PAUSE TestAccProvider_DefaultTags_emptyBlock
=== RUN   TestAccProvider_DefaultTagsTags_none
=== PAUSE TestAccProvider_DefaultTagsTags_none
=== RUN   TestAccProvider_DefaultTagsTags_one
=== PAUSE TestAccProvider_DefaultTagsTags_one
=== RUN   TestAccProvider_DefaultTagsTags_multiple
=== PAUSE …
```
=> Fix `acctest` provider acceptance test failures

website/docs/r/apprunner_service.html.markdown
This PR update the documentation since App Runner now propose other runtimes than NodeJS & Python.
* https://aws.amazon.com/about-aws/whats-new/2022/10/aws-app-runner-support-php-go-dot-net-ruby-managed-runtimes/
* https://github.com/aws/aws-sdk-go/blob/main/CHANGELOG.md#release-v144126-2022-10-27
* https://docs.aws.amazon.com/sdk-for-go/api/service/apprunner/#Runtime_Values
=> docs: Update App Runner runtimes values

.changelog/#27612.txt, internal/service/cognitoidp/user_pool.go, internal/service/cognitoidp/user_pool_test.go, website/docs/r/cognito_user_pool.markdown
Closes #27435
```
$ make testacc TESTS=TestAccCognitoIDPUserPool_ PKG=cognitoidp
--- PASS: TestAccCognitoIDPUserPool_disappears (32.93s)
--- PASS: TestAccCognitoIDPUserPool_withAdminCreateUserAndPasswordPolicy (44.45s)
--- PASS: TestAccCognitoIDPUserPool_basic (47.42s)
--- PASS: TestAccCognitoIDPUserPool_schemaAttributesModified (53.07s)
--- PASS: TestAccCognitoIDPUserPool_schemaAttributesRemoved (53.28s)
--- PASS: TestAccCognitoIDPUserPool_withUserAttributeUpdateSettings (65.88s)
--- PASS: TestAccCognitoIDPUserPool_withAdminCreateUser (73.19s)
--- PASS: TestAccCognitoIDPUserPool_withVerificationMessageTemplate (75.09s)
--- PASS: TestAccCognitoIDPUserPool_withEmailVerificationMessage (75.41s)
--- PASS: TestAccCognitoIDPUserPool_smsAuthenticationMessage (77.99s)
--- PASS: …
```
=> cognito user pool deletion protection

internal/service/emrcontainers/virtual_cluster_test.go
Use an alias for the external Kubernetes provider to fix EMR Containers acceptance test failures.
Closes https://github.com/hashicorp/terraform-provider-aws/issues/27603.
```console
% make testacc TESTARGS='-run=TestAccEMRContainersVirtualCluster_basic' PKG=emrcontainers
TF_ACC=1 go test ./internal/service/emrcontainers/... -v -count 1 -parallel 20  -run=TestAccEMRContainersVirtualCluster_basic -timeout 180m
=== RUN   TestAccEMRContainersVirtualCluster_basic
=== PAUSE TestAccEMRContainersVirtualCluster_basic
=== CONT  TestAccEMRContainersVirtualCluster_basic
--- PASS: TestAccEMRContainersVirtualCluster_basic (1145.36s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/emrcontainers	1149.676s
```
=> EMR Clusters: Fix acceptance tests

.changelog/27305.txt, internal/service/ec2/transitgateway_connect_peer.go, internal/service/ec2/validate.go, internal/service/ec2/validate_test.go, internal/service/ec2/vpnsite_customer_gateway.go, internal/service/networkmanager/core_network_policy_document_data_source.go, internal/service/networkmanager/core_network_policy_document_data_source_test.go, internal/service/networkmanager/core_network_policy_model.go, internal/verify/validate.go, internal/verify/validate_test.go
This PR restores the validation for a 4-byte ASN on CloudWAN (Network Manager) Core Network Policy Document data source under Edge Locations. The validation was removed due to build failures on 32-bit systems, but can be restored by re-using the `valid4ByteAsn` function from the `ec2` service provider as a common validation function.
This PR also modifies the `ec2` service provider to use the relocated common validation function (tests below).
When `terraform-plugin-framework` becomes GA, the function can be modified to leverage `Int64` as a new schema type.
No changelog entry created per [these instructions](https://hashicorp.github.io/terraform-provider-aws/changelog-process/#changes-that-should-not-have-a-changelog-entry)
Closes #24902 …
=> Relocate Valid4ByteAsn function to common lib, add to CloudWAN Network Policy Doc Data Source

.changelog/27620.txt, internal/service/cognitoidp/user_pool_client.go, internal/service/cognitoidp/user_pool_client_test.go, website/docs/r/cognito_user_pool_client.markdown
```
$ make testacc TESTS=TestAccCognitoIDPUserPoolClient_ PKG=cognitoidp
--- PASS: TestAccCognitoIDPUserPoolClient_Disappears_userPool (37.30s)
--- PASS: TestAccCognitoIDPUserPoolClient_disappears (44.93s)
--- PASS: TestAccCognitoIDPUserPoolClient_basic (48.98s)
--- PASS: TestAccCognitoIDPUserPoolClient_allFields (52.26s)
--- PASS: TestAccCognitoIDPUserPoolClient_idTokenValidity (74.28s)
--- PASS: TestAccCognitoIDPUserPoolClient_accessTokenValidity (75.13s)
--- PASS: TestAccCognitoIDPUserPoolClient_allFieldsUpdatingOneField (75.13s)
--- PASS: TestAccCognitoIDPUserPoolClient_tokenValidityUnits (75.13s)
--- PASS: TestAccCognitoIDPUserPoolClient_authSessionValidity (76.26s)
--- PASS: TestAccCognitoIDPUserPoolClient_analyticsWithARN (76.64s)
--- PASS: …
```
=> cognito user pool client - add `auth_session_validity` arg

go.mod, skaff/go.sum, tools/tfsdk2fw/go.mod, tools/tfsdk2fw/go.sum
[Fixes](https://github.com/hashicorp/terraform-provider-aws/actions/runs/3386962167/jobs/5627058824):
```
diff --git a/go.mod b/go.mod
index d7172a6..23ba497 100644
--- a/go.mod
+++ b/go.mod
@@ -78,7 +78,7 @@ require (
github.com/hashicorp/go-checkpoint v0.5.0 // indirect
github.com/hashicorp/go-hclog v1.2.1 // indirect
github.com/hashicorp/go-plugin v1.4.4 // indirect
-	github.com/hashicorp/go-uuid v1.0.3 // indirect
+	github.com/hashicorp/go-uuid v1.0.3
github.com/hashicorp/hc-install v0.4.0 // indirect
github.com/hashicorp/logutils v1.0.0 // indirect
github.com/hashicorp/terraform-exec v0.17.3 // indirect
```
=> Run `go mod tidy`

website/docs/r/evidently_segment.html.markdown
CloudWatch Evidently Segments use `arn` instead of `name`. Small documentation fix to align with the resource definition. Reference: https://github.com/hashicorp/terraform-provider-aws/blob/1952a1e8e3227b3b919d21e231fcd303f4603ad2/internal/service/evidently/segment.go#L117
Relates #27159 and #22624
=> docs(cwevi): id uses arn, import uses arn

internal/service/s3/bucket.go
Currently, the `arn` and `hosted_zone_id` attributes are marked as optional, hinting that they can be set within a resource block (as opposed to being solely `computed` attributes).
However, `arn` and `hosted_zone_id` should never be set with user-generated values. `arn` is derived from other attributes, and `hosted_zone_id` is looked up [here](https://github.com/hashicorp/terraform-provider-aws/blob/main/internal/service/s3/hosted_zones.go#L10).
n/a
https://discuss.hashicorp.com/t/providers-schema-how-to-distinguish-attributes-from-arguments/5029/3
```
...
```
=> aws_s3_bucket: Remove optional from arn and hosted_zone_id

.changelog/27665.txt, internal/provider/provider.go, internal/service/redshift/find.go, internal/service/redshift/partner.go, internal/service/redshift/partner_test.go, website/docs/r/redshift_partner.html.markdown
```
$ make testacc TESTS=TestAccRedshiftPartner_ PKG=redshift
--- PASS: TestAccRedshiftPartner_disappears (241.70s)
--- PASS: TestAccRedshiftPartner_basic (292.57s)
--- PASS: TestAccRedshiftPartner_disappears_cluster (317.52s)
```
=> redshift partner resource

website/docs/r/dynamodb_table.html.markdown
aws_dynamodb_table resource documentation of projection_type attribute is wrong
they are different than how aws dynamodb table behaves
there are indeed 3 options like docs say but the docs are not accurate on some of them:
1.  ALL option  which will project all of the values of the item into the index(like the docs says),
2.  KEYS_ONLY will project only the …
=> docs:r/aws_dynamodb_table projection_type

.changelog/27664.txt, internal/service/dynamodb/table.go, internal/service/lambda/event_source_mapping_test.go
The stream ARN is set to a default empty string when the stream is not enabled, but when the stream state is updated to enabled the plan doesn't reflect the stream are is computed so fails as the consumer of the stream expects a valid ARN( lambda in my case, hence adding the test to prove the fix in the lambda package). Adding a customdiff that sets the ARN as computed on change ensures the plan does not pass the existing empty string to the consumer.
Closes #20092
```
make testacc TESTS=TestAccLambdaEventSourceMapping_DynamoDB_streamAdded PKG=lambda
TF_ACC=1 go test ./internal/service/lambda/... -v -count 1 -parallel 20 -run='TestAccLambdaEventSourceMapping_DynamoDB_streamAdded'  -timeout 180m
=== RUN …
```
=> fix: A diff should reflect that the value of the stream arn is computed on change to the stream.

.changelog/27656.txt, internal/service/secretsmanager/secret_rotation.go
This change removes the useless `tags` argument from the `aws_secretsmanager_secret_rotation` resource.
Closes #27655
```
$ make testacc TESTARGS='-run=TestAccSecretsManagerSecretRotation' PKG=secretsmanager
TF_ACC=1 go test ./internal/service/secretsmanager/... -v -count 1 -parallel 20  -run=TestAccSecretsManagerSecretRotation -timeout 180m
=== RUN   TestAccSecretsManagerSecretRotationDataSource_basic
=== PAUSE TestAccSecretsManagerSecretRotationDataSource_basic
=== RUN   TestAccSecretsManagerSecretRotation_basic
=== PAUSE TestAccSecretsManagerSecretRotation_basic
=== CONT  TestAccSecretsManagerSecretRotationDataSource_basic
=== CONT  TestAccSecretsManagerSecretRotation_basic
--- PASS: TestAccSecretsManagerSecretRotation_basic …
```
=> remove tags field from aws_secretsmanager_secret_rotation resource

website/docs/r/db_instance.html.markdown
Link to RDS tutorial is broken. Removing the args of the url fixes it.
Closes #27649
- [rds tutorial](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/db_instance)
=> Fix Broken/Cluttered RDS Tutorial Link

.changelog/27682.txt, internal/service/wafv2/rule_group_test.go, internal/service/wafv2/schemas.go
This allows having an additional nested statement level for rules inside a `wafv2_rule_group`. Essentially it is the same change as made in #13961 for `wafv2_web_acl` but ported to `wafv2_rule_group`.
```
$ make testacc TESTS=TestAccWAFV2RuleGroup_RateBased_maxNested PKG=wafv2
TF_ACC=1 go test ./internal/service/wafv2/... -v -count 1 -parallel 20 -run='TestAccWAFV2RuleGroup_RateBased_maxNested'  -timeout 180m
=== RUN   TestAccWAFV2RuleGroup_RateBased_maxNested
=== PAUSE TestAccWAFV2RuleGroup_RateBased_maxNested
=== CONT  TestAccWAFV2RuleGroup_RateBased_maxNested
--- PASS: TestAccWAFV2RuleGroup_RateBased_maxNested (16.97s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/wafv2	17.082s
$ make testacc …
```
=> resource/wafv2_rule_group: add additional nested statement level

website/docs/r/appstream_stack.html.markdown, website/docs/r/vpc_ipam_scope.html.markdown
This change adds the documentation for the `tags` arguments for resources that support the argument. It makes the same pattern as the other resources support the `tags` argument.
Closes #27667
Used this script to help discover the pages that were missing the documentation
https://github.com/frek818/random_scripts/blob/master/supports_tagging/run.sh
Nothing to test.
=> add documenation for tags argument for pages that are missing it

.changelog/27693.txt, internal/service/ec2/vpnsite_connection.go, internal/service/ec2/vpnsite_connection_test.go, website/docs/r/vpn_connection.html.markdown
Change VPN connection parameters "transit_gateway_id" and "vpn_gateway_id" to optional. Before, one of these was required but AWS VPN API documentation states that these are optional and conflicting. 
Relates #27387 
AWS VPN API documentation https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_CreateVpnConnection.html.
```
-> % make testacc PKG=ec2 TESTS=TestAccSiteVPNConnection_basic          
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 20 -run='TestAccSiteVPNConnection_basic'  -timeout 180m
=== RUN   TestAccSiteVPNConnection_basic
=== PAUSE TestAccSiteVPNConnection_basic
=== CONT  TestAccSiteVPNConnection_basic
--- PASS: TestAccSiteVPNConnection_basic (207.34s)
PASS
ok …
```
=> Change parameter to optional and add test

website/docs/d/ce_cost_category.html.markdown, website/docs/r/ce_cost_category.html.markdown
Fixed `tags` argument for `ce_cost_category`
No tests, only documentation
=> 📝 Fixed documentation on ce_cost_category

.changelog/27718.txt, internal/provider/provider.go, internal/service/ivs/find.go, internal/service/ivs/recording_configuration.go, internal/service/ivs/recording_configuration_test.go, internal/service/ivs/status.go, internal/service/ivs/wait.go, website/docs/r/ivs_recording_configuration.html.markdown
Add new resource for AWS IVS Recording Configuration: aws_ivs_recording_configuration. This PR is the second in a set to support the full AWS IVS entities:
1. ~~Playback Key Pair~~
2. Recording Configuration
3. Channel
4. Stream Key
Relates #17272
```
$ make testacc TESTS=TestAccIVSRecordingConfiguration_ PKG=ivs
TF_ACC=1 /Users/eakevinh/go/bin/go1.18.4 test ./internal/service/ivs/... -v -count 1 -parallel 20 -run='TestAccIVSRecordingConfiguration_'  -timeout 180m
=== RUN   TestAccIVSRecordingConfiguration_basic
=== PAUSE TestAccIVSRecordingConfiguration_basic
=== RUN   TestAccIVSRecordingConfiguration_update
=== PAUSE TestAccIVSRecordingConfiguration_update
=== RUN   TestAccIVSRecordingConfiguration_disappears
=== PAUSE …
```
=> new resource: aws_ivs_recording_configuration

.changelog/26923.txt, internal/service/rds/engine_version_data_source.go, internal/service/rds/engine_version_data_source_test.go, website/docs/d/rds_engine_version.markdown
This PR adds support for `default_only`, `include_all`, and `filter` to the `aws_rds_engine_version` data source. Adding these flags make it possible to get the default minor version given only a major version for an engine, to distinguish between `provisioned` and `serverless` engine modes, or to allow querying of deprecated versions, among other things.
Closes #19715
Closes #26867
=> enhancement(rds): Support default_only, include_all, and filter for aws_rds_engine_version

website/docs/r/sesv2_configuration_set.html.markdown
Just a quick type fix, `sendig` != `sending`.
Closes #27727
N/a
N/a, docs
=> Fix typo in `aws_sesv2_configuration_set` docs

.changelog/27762.txt, internal/service/identitystore/group_data_source.go, internal/service/identitystore/group_data_source_test.go, website/docs/d/identitystore_group.html.markdown
- Refactor data source using the `aws_identitystore_user` resource.
- Refactor resource using the `GetGroupId` and `DescribeGroup` API-s instead of `ListGroups`.
- Expose all attributes of the `Group` data type.
- Deprecates the `filter` attribute in favour of the `alternate_identifier` configuration block in line with [GetGroupId](https://docs.aws.amazon.com/singlesignon/latest/IdentityStoreAPIReference/API_GetGroupId.html).
Relates https://github.com/hashicorp/terraform-provider-aws/issues/26598
Relates https://github.com/hashicorp/terraform-provider-aws/pull/27053
```
$ make testacc TESTS=TestAccIdentityStoreGroupDataSource_ PKG=identitystore
TF_ACC=1 go test ./internal/service/identitystore/... -v -count 1 -parallel 20 …
```
=> d/aws_identitystore_group: expose all group attributes

.changelog/27672.txt, internal/provider/provider.go, internal/service/sesv2/email_identity_feedback_attributes_test.go, internal/service/sesv2/email_identity_mail_from_attributes.go, internal/service/sesv2/email_identity_mail_from_attributes_test.go, website/docs/r/sesv2_email_identity_mail_from_attributes.html.markdown
This PR introduces the `aws_sesv2_email_identity_mail_from_attributes` resource.
https://docs.aws.amazon.com/ses/latest/APIReference-V2/API_PutEmailIdentityMailFromAttributes.html
```
$ make testacc TESTARGS='-run=TestAccSESV2EmailIdentityMailFromAttributes_' PKG=sesv2 ACCTEST_PARALLELISM=2
TF_ACC=1 go test ./internal/service/sesv2/... -v -count 1 -parallel 2  -run=TestAccSESV2EmailIdentityMailFromAttributes_ -timeout 180m
=== RUN   TestAccSESV2EmailIdentityMailFromAttributes_basic
=== PAUSE TestAccSESV2EmailIdentityMailFromAttributes_basic
=== RUN   TestAccSESV2EmailIdentityMailFromAttributes_disappears
=== PAUSE TestAccSESV2EmailIdentityMailFromAttributes_disappears
=== RUN …
```
=> r/aws_sesv2_email_identity_mail_from_attributes: new resource

.changelog/27726.txt, internal/provider/provider.go, internal/service/ivs/channel.go, internal/service/ivs/channel_test.go, internal/service/ivs/find.go, internal/service/ivs/status.go, internal/service/ivs/wait.go, website/docs/r/ivs_channel.html.markdown
Add new resource for AWS IVS Channel: aws_ivs_channel. This PR is the third in a set to support the full AWS IVS entities:
1. ~~Playback Key Pair~~
2. ~~Recording Configuration~~
3. Channel
4. Stream Key
Relates #17272
```
$ make testacc TESTS=TestAccIVSChannel_ PKG=ivs      
TF_ACC=1 /Users/eakevinh/go/bin/go1.18.4 test ./internal/service/ivs/... -v -count 1 -parallel 20 -run='TestAccIVSChannel_'  -timeout 180m
=== RUN   TestAccIVSChannel_basic
=== PAUSE TestAccIVSChannel_basic
=== RUN   TestAccIVSChannel_tags
=== PAUSE TestAccIVSChannel_tags
=== RUN   TestAccIVSChannel_update
=== PAUSE TestAccIVSChannel_update
=== RUN   TestAccIVSChannel_disappears
=== PAUSE TestAccIVSChannel_disappears
=== RUN …
```
=> new resource: aws_ivs_channel

website/docs/r/eks_node_group.html.markdown
There was no language tag, so the formatting on [this section of the docs](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/eks_node_group#tracking-the-latest-eks-node-group-ami-releases) was a bit ugly to look at.
- [Discuss thread](https://discuss.hashicorp.com/t/documentation-formatting-is-messed-up/46385)
N/a
N/a, docs
=> Fix formatting on `aws_eks_node_group` docs

.github/dependabot.yml
=> `hcl/v2` should only be `updated via terraform-plugin-sdk`

.changelog/22988.txt, internal/provider/provider.go, internal/service/opensearch/inbound_connection_accepter.go, internal/service/opensearch/inbound_connection_accepter_test.go, internal/service/opensearch/outbound_connection.go, internal/service/opensearch/outbound_connection_test.go, website/docs/r/opensearch_inbound_connection_accepter.html.markdown, website/docs/r/opensearch_outbound_connection.html.markdown
Closes #13609
```
$ make testacc TESTS="TestAccElasticsearchOutboundConnection_basic|TestAccElasticsearchInboundConnectionAccepter_basic" PKG=elasticsearch
TF_ACC=1 go test ./internal/service/elasticsearch/... -v -count 1 -parallel 20 …
```
=> Add support for elasticsearch outbound connection and relevant accepter

.changelog/27781.txt, internal/service/acm/certificate.go, internal/service/acm/certificate_test.go, website/docs/r/acm_certificate.html.markdown
Support specifying the key algorithm when requesting ACM certificates. Enables requesting certificates with ECDSA algorithms.
Relates #27715 
- https://aws.amazon.com/about-aws/whats-new/2022/11/aws-certificate-manager-elliptic-curve-digital-signature-algorithm-tls-certificates/
- https://docs.aws.amazon.com/acm/latest/userguide/acm-certificate.html#algorithms
```
$ ACM_CERTIFICATE_ROOT_DOMAIN=beta-env.idv.tw make testacc TESTS='TestAccACMCertificate_(root|keyAlgorithm)' PKG=acm
TF_ACC=1 go test ./internal/service/acm/... -v -count 1 -parallel 20 -run='TestAccACMCertificate_(root|keyAlgorithm)'  -timeout 180m
=== RUN   TestAccACMCertificate_root
=== PAUSE TestAccACMCertificate_root
=== RUN …
```
=> Add support for key_algorithm in `aws_acm_certificate` resource

.changelog/27795.txt, internal/service/ec2/consts.go, website/docs/r/autoscaling_group.html.markdown, website/docs/r/ec2_fleet.html.markdown, website/docs/r/spot_fleet_request.html.markdown
Documents the new `price-capacity-optimized` spot allocation strategy.
Closes https://github.com/hashicorp/terraform-provider-aws/issues/27759.
```console
% make testacc TESTARGS='-run=TestAccEC2Fleet_SpotOptions_allocationStrategy' PKG=ec2
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 20  -run=TestAccEC2Fleet_SpotOptions_allocationStrategy -timeout 180m
=== RUN   TestAccEC2Fleet_SpotOptions_allocationStrategy
=== PAUSE TestAccEC2Fleet_SpotOptions_allocationStrategy
=== CONT  TestAccEC2Fleet_SpotOptions_allocationStrategy
--- PASS: TestAccEC2Fleet_SpotOptions_allocationStrategy (104.28s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/ec2	109.196s
```
=> documentation: `price-capacity-optimized` spot allocation strategy

website/docs/r/ses_domain_identity.html.markdown, website/docs/r/ses_email_identity.html.markdown
Looking at the source code at: 
https://github.com/hashicorp/terraform-provider-aws/blob/d481be15e66cff7cf9d95f9f1258c148ef63c1cb/internal/service/ses/domain_identity.go#L67
And at the docs of [ses_domain_identity](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ses_domain_identity):
---
093a697 is just adding a dot at the and of the line, I can revert this commit if it's out of scope.
=> DOC: Added missing "domain" attr to ses_domain_identity

internal/service/ec2/vpc_peering_connection.go
Simple typo fix in the error text for the acceptVPCPeeringConnection function.
n/a
n/a
n/a
=> fix/typo in acceptVPCPeeringConnection

.changelog/27784.txt, internal/service/sesv2/email_identity_feedback_attributes.go
This PR fixes the wrong attribute used in the error messages when creating the `aws_sesv2_feedback_attributes`.
```
$ make testacc TESTARGS='-run=TestAccSESV2EmailIdentityFeedbackAttributes' PKG=sesv2 ACCTEST_PARALLELISM=2
TF_ACC=1 go test ./internal/service/sesv2/... -v -count 1 -parallel 2  -run=TestAccSESV2EmailIdentityFeedbackAttributes -timeout 180m
=== RUN   TestAccSESV2EmailIdentityFeedbackAttributes_basic
=== PAUSE TestAccSESV2EmailIdentityFeedbackAttributes_basic
=== RUN   TestAccSESV2EmailIdentityFeedbackAttributes_disappears
=== PAUSE TestAccSESV2EmailIdentityFeedbackAttributes_disappears
=== RUN   TestAccSESV2EmailIdentityFeedbackAttributes_disappears_emailIdentity
=== PAUSE …
```
=> r/aws_sesv2_email_identity_feedback_attributes: use the correct attribute as the resource ID in error messages

internal/service/sesv2/configuration_set.go, internal/service/sesv2/email_identity.go
This PR makes use of the `enum.Validate` validator and removes the redundant functions for converting AWS SDK v2 enum types.
```
$ make testacc TESTARGS='-run="TestAccSESV2ConfigurationSet_|TestAccSESV2EmailIdentity_"' PKG=sesv2 ACCTEST_PARALLELISM=2
/bin/sh: line 0: [: missing `]'
/bin/sh: TestAccSESV2EmailIdentity_: command not found
TF_ACC=1 go test ./internal/service/sesv2/... -v -count 1 -parallel 2  -run="TestAccSESV2ConfigurationSet_|TestAccSESV2EmailIdentity_" -timeout 180m
=== RUN   TestAccSESV2ConfigurationSet_basic
=== PAUSE TestAccSESV2ConfigurationSet_basic
=== RUN   TestAccSESV2ConfigurationSet_disappears
=== PAUSE TestAccSESV2ConfigurationSet_disappears
=== RUN …
```
=> r/aws_sesv2: make use of enum.Validate

website/docs/r/networkmanager_site_to_site_vpn_attachment.html.markdown
Added a full example for networkmanager_site_to_site_attachment to the documentation
Relates https://github.com/hashicorp/terraform-provider-aws/pull/27387.
=> Added a full example for `aws_networkmanager_site_to_site_vpn_attachment` documentation

.changelog/27789.txt, examples/ivs/README.md, examples/ivs/main.tf, examples/ivs/outputs.tf, examples/ivs/variables.tf, internal/provider/provider.go, internal/service/ivs/find.go, internal/service/ivs/stream_key_data_source.go, internal/service/ivs/stream_key_data_source_test.go, website/docs/d/ivs_stream_key.html.markdown
Add new data source for AWS IVS Stream Key: `aws_ivs_stream_key`. This PR is the last in a set to support the full AWS IVS entities:
1. ~~Playback Key Pair~~
2. ~~Recording Configuration~~
3. ~~Channel~~
4. Stream Key
Relates #17272
```
$ make testacc TESTS=TestAccIVSStreamKeyDataSource_ PKG=ivs
TF_ACC=1 /Users/eakevinh/go/bin/go1.18.4 test ./internal/service/ivs/... -v -count 1 -parallel 20 -run='TestAccIVSStreamKeyDataSource_'  -timeout 180m
=== RUN   TestAccIVSStreamKeyDataSource_basic
=== PAUSE TestAccIVSStreamKeyDataSource_basic
=== CONT  TestAccIVSStreamKeyDataSource_basic
--- PASS: TestAccIVSStreamKeyDataSource_basic (32.33s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/ivs        35.249s
```
=> new data source: aws_ivs_stream_key

.changelog/27785.txt, internal/service/ec2/vpc_network_interface_sg_attachment.go, internal/service/ec2/vpc_network_interface_sg_attachment_test.go, website/docs/r/network_interface_sg_attachment.html.markdown
This PR adds support for importing existing [aws_network_interface_sg_attachment](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/network_interface_sg_attachment) resources.
Closes #27076
_None_
```
$ make testacc TESTS=TestAccVPCNetworkInterfaceSgAttachment PKG=ec2
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 20 -run='TestAccVPCNetworkInterfaceSgAttachment'  -timeout 180m
=== RUN   TestAccVPCNetworkInterfaceSgAttachment_basic
=== PAUSE TestAccVPCNetworkInterfaceSgAttachment_basic
=== RUN   TestAccVPCNetworkInterfaceSgAttachment_disappears
=== PAUSE TestAccVPCNetworkInterfaceSgAttachment_disappears
=== RUN   TestAccVPCNetworkInterfaceSgAttachment_instance
=== PAUSE …
```
=> Add import support for aws_network_interface_sg_attachment resource

internal/service/batch/compute_environment_test.go, internal/service/emrcontainers/virtual_cluster_test.go
https://github.com/hashicorp/terraform-plugin-sdk/pull/1092 removes the need to use external provider aliases in acceptance test configurations.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/27499.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/27615.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/27803.
```console
% make testacc TESTARGS='-run=TestAccEMRContainersVirtualCluster_basic' PKG=emrcontainers
TF_ACC=1 go test ./internal/service/emrcontainers/... -v -count 1 -parallel 20  -run=TestAccEMRContainersVirtualCluster_basic -timeout 180m
=== RUN   TestAccEMRContainersVirtualCluster_basic
=== PAUSE TestAccEMRContainersVirtualCluster_basic
=== CONT …
```
=> Tests: Remove external provider aliases

.changelog/27744.txt, internal/service/appstream/stack.go
Increase max length of redirectUrl in appstream stack resource. Docs specify that max length is 1000: https://docs.aws.amazon.com/appstream2/latest/APIReference/API_CreateStack.html#AppStream2-CreateStack-request-RedirectURL
Fixes #27743
```
...
```
=> Update validation rule in appstream stack resource

.changelog/27517.txt, internal/service/dynamodb/table_item.go, internal/service/dynamodb/table_item_test.go
- per [AWS' documentation](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/LegacyConditionalParameters.Expected.html) `Expected` is a legacy parameter and should no longer be used
- should fix https://github.com/hashicorp/terraform-provider-aws/issues/26080, or at least be more predictable, while maintaining the same behavior for tables without composite keys. It seems like `Expected` is only checking that the hash key does not exist whereas this `ConditionExpression` will check whether an item with the same hash key _and_ range key does not exist
- [this blog post](https://www.alexdebrie.com/posts/dynamodb-condition-expressions/) explains how this `ConditionExpression` works, essentially the condition will always be compared against a single item and so it is sufficient …
=> `dynamodb_table_item` `create`: use `ConditionExpression`

.changelog/23156.txt, internal/service/dynamodb/table.go, internal/service/dynamodb/table_test.go, internal/service/dynamodb/wait.go
Closes #21726
Output from acceptance testing replica related tests:
```
➜ make testacc  TESTS='TestAccDynamoDBTable_Replica_' PKG=dynamodb
TF_ACC=1 go test ./internal/service/dynamodb/... -v -count 1 -parallel 20 -run='TestAccDynamoDBTable_Replica_'  -timeout 180m
=== RUN …
```
=> Handle KMS updates with replica tables.

.changelog/27860.txt, internal/provider/provider.go, internal/service/appconfig/extension.go, internal/service/appconfig/extension_association.go, internal/service/appconfig/extension_test.go, internal/service/appconfig/extenstion_association_test.go, internal/service/appconfig/find.go, website/docs/r/appconfig_extension.html.markdown, website/docs/r/appconfig_extension_association.html.markdown
This implements the `aws_appconfig_extension` and `aws_appconfig_extension_association` resources. 
https://docs.amazonaws.cn/en_us/appconfig/latest/userguide/working-with-appconfig-extensions-about.html
```
$ make testacc TESTARGS='-run=TestAccAppConfigExtension' PKG=appconfig
TF_ACC=1 go test ./internal/service/appconfig/... -v -count 1 -parallel 20  -run=TestAccAppConfigExtension -timeout 180m
=== RUN   TestAccAppConfigExtension_basic
=== PAUSE TestAccAppConfigExtension_basic
=== RUN   TestAccAppConfigExtension_ActionPoint
=== PAUSE TestAccAppConfigExtension_ActionPoint
=== RUN   TestAccAppConfigExtension_Parameter
=== PAUSE TestAccAppConfigExtension_Parameter
=== RUN   TestAccAppConfigExtension_Name
=== PAUSE …
```
=> New Resources: `aws_appconfig_extension` and `aws_appconfig_extension_association`

.changelog/27882.txt, internal/enum/validate.go, internal/service/medialive/channel.go, internal/service/medialive/channel_test.go, internal/service/medialive/multiplex_program.go, website/docs/r/medialive_channel.html.markdown
start/stop `aws_medialive_channel`
Closes #27706
```console
$ make testacc TESTARGS='-run=TestAccMediaLiveChannel_status' PKG=medialive
TF_ACC=1 go test ./internal/service/medialive/... -v -count 1 -parallel 20  -run=TestAccMediaLiveChannel_status -timeout 180m
=== RUN   TestAccMediaLiveChannel_status
=== PAUSE TestAccMediaLiveChannel_status
=== CONT  TestAccMediaLiveChannel_status
--- PASS: TestAccMediaLiveChannel_status (203.22s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/medialive	205.829s
...
```
=> r/aws_medialive_channel: start/stop channel

.changelog/#####.txt, .changelog/27925.txt, website/docs/r/amplify_app.html.markdown
Documents AWS Amplify support for the `WEB_DYNAMIC` platform type.
Closes https://github.com/hashicorp/terraform-provider-aws/issues/27907.
```console
% make testacc TESTARGS='-run=TestAccAmplify_serial/App/basic' PKG=amplify ACCTEST_PARALLELISM=3
TF_ACC=1 go test ./internal/service/amplify/... -v -count 1 -parallel 3  -run=TestAccAmplify_serial/App/basic -timeout 180m
=== RUN   TestAccAmplify_serial
=== RUN   TestAccAmplify_serial/App
=== RUN   TestAccAmplify_serial/App/basic
--- PASS: TestAccAmplify_serial (25.94s)
--- PASS: TestAccAmplify_serial/App (25.94s)
--- PASS: TestAccAmplify_serial/App/basic (25.94s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/amplify	30.718s
```
=> Add support for AWS Amplify `WEB_DYNAMIC` platform type

website/docs/r/cognito_user.html.markdown
This PR corrects the argument name which should be `username`, not `user_name`.
Closes #27808.
https://github.com/hashicorp/terraform-provider-aws/blob/5cae4979cecb8ad61c10bb930cd26d5c241bb47f/internal/service/cognitoidp/user.go#L98-L103
=> r/aws_cognito_user: Correct the argument name

.changelog/27891.txt, internal/provider/provider.go, internal/service/rds/clusters_data_source.go, internal/service/rds/clusters_data_source_test.go, website/docs/d/rds_clusters.html.markdown
This PR introduces the `aws_rds_clusters` plural data source.
https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_DescribeDBClusters.html
```
$ make testacc TESTARGS='-run=TestAccRDSClustersDataSource_filter' PKG=rds ACCTEST_PARALLELISM=2    
TF_ACC=1 go test ./internal/service/rds/... -v -count 1 -parallel 2  -run=TestAccRDSClustersDataSource_filter -timeout 180m
=== RUN   TestAccRDSClustersDataSource_filter
=== PAUSE TestAccRDSClustersDataSource_filter
=== CONT  TestAccRDSClustersDataSource_filter
--- PASS: TestAccRDSClustersDataSource_filter (171.03s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/rds        172.860s
```
=> d/aws_rds_clusters: new data source

internal/service/rds/cluster.go, internal/service/rds/cluster_activity_stream.go, internal/service/rds/cluster_activity_stream_test.go, internal/service/rds/cluster_data_source.go, internal/service/rds/cluster_instance.go, internal/service/rds/cluster_instance_test.go, internal/service/rds/cluster_test.go, internal/service/rds/find.go, internal/service/rds/instance.go, internal/service/rds/instance_automated_backups_replication.go, internal/service/rds/instance_data_source.go, internal/service/rds/instance_role_association.go, internal/service/rds/instance_test.go, internal/service/rds/reserved_instance.go, internal/service/rds/snapshot_copy.go, internal/service/rds/status.go, internal/service/rds/wait.go
updates `aws_db_instance`, `aws_rds_cluster`, and `aws_rds_cluster_instance` to use `WithoutTimeout` CRUD functions and `Context`-aware Import functions.
Also ensures that `Context`-aware functions are used in other resources when `WithoutTimeout` CRUD functions are used.
Acceptance test failures are pre-existing
```
$ make testacc PKG=rds TESTS='TestAccRDSInstance|TestAccRDSSnapshotCopy|TestAccRDSReservedInstance|TestAccRDSCluster' ACCTEST_TIMEOUT=5h
--- SKIP: TestAccRDSCluster_SnapshotIdentifierEngineMode_serverless (0.00s)
--- PASS: TestAccRDSCluster_iamAuth (129.02s)
--- PASS: TestAccRDSCluster_backupsUpdate (225.55s)
--- FAIL: TestAccRDSCluster_ReplicationSourceIdentifier_kmsKeyID (1.63s)
--- PASS: TestAccRDSCluster_engineVersionWithPrimaryInstance (1185.56s)
--- PASS: …
```
=> RDS: updates Instance, Cluster, and ClusterInstance to use `WithoutTimeout` CRUDI functions

website/docs/r/sagemaker_user_profile.html.markdown
A line in the documentation is duplicated, likely by mistake. This MR removes the duplicate.
=> Remove duplicate kernel_gateway_app_settings from website

website/docs/r/mq_broker.html.markdown
correct `instances.0.console_url` description to indicate this references the `consule_url` for `ActiveMQ` and `RabbitMQ` broker types
I have noticed when reading through the docs for `mq_broker` that the attribute `instances.0.console_url` seems to suggest to users that this is only for the `ActiveMQ Web Console` this could confuse users looking for the `RabbitMQ Management UI` endpoint. The resource provides the URL for both the `ActiveMQ Web Console` and the `RabbitMQ Management UI`. I have updated the docs to reflect this
=> correct instances.0.console_url description to indicate this references the consule_url for ActiveMQ and RabbitMQ broker types

.changelog/27949.txt, internal/service/dms/endpoint.go, internal/service/dms/endpoint_test.go
- Bug fix to include Sybase Engine to dms-create-endpoint. Documentation references Sybase engine but code and tests did not include support. 
- S3 and MySQL endpoint tests were updated as AWS API threw errors for improper values. 
Closes [#20400](https://github.com/hashicorp/terraform-provider-aws/issues/20400)
```
TF_ACC=1 go test ./internal/service/dms/... -v -count 1 -parallel 20 -run='TestAccDMSEndpoint'  -timeout 180m
=== RUN   TestAccDMSEndpoint_basic
=== PAUSE TestAccDMSEndpoint_basic
=== RUN   TestAccDMSEndpoint_Aurora_basic
=== PAUSE TestAccDMSEndpoint_Aurora_basic
=== RUN   TestAccDMSEndpoint_Aurora_secretID
=== PAUSE TestAccDMSEndpoint_Aurora_secretID
=== RUN   TestAccDMSEndpoint_Aurora_update
=== PAUSE …
```
=> adds sybase engine support

website/docs/r/imagebuilder_image_recipe.html.markdown
I've clarified the documentation for the 'parent_image' and 'version' fields (these are from the AWS documentation). I've also removed duplicate 'required' and 'optional' markers.
See also: #27906
=> Update documentation for the image builder component

internal/service/logs/group.go, website/docs/r/cloudwatch_log_group.html.markdown
Updates possible retention policy in days values. The AWS GO SDK does not support a `_Values()` enum for this.
Closes #28002
```
make testacc TESTARGS='-run=TestAccLogsGroup_' PKG=logs 
TF_ACC=1 go test ./internal/service/logs/... -v -count 1 -parallel 20  -run=TestAccLogsGroup_ -timeout 180m
=== RUN   TestAccLogsGroup_basic
=== PAUSE TestAccLogsGroup_basic
=== RUN   TestAccLogsGroup_nameGenerate
=== PAUSE TestAccLogsGroup_nameGenerate
=== RUN   TestAccLogsGroup_namePrefix
=== PAUSE TestAccLogsGroup_namePrefix
=== RUN   TestAccLogsGroup_disappears
=== PAUSE TestAccLogsGroup_disappears
=== RUN   TestAccLogsGroup_tags
=== PAUSE TestAccLogsGroup_tags
=== RUN   TestAccLogsGroup_kmsKey
=== PAUSE TestAccLogsGroup_kmsKey
=== RUN …
```
=> aws_cloudwatch_log_group - Update possible retention policy in days values

.changelog/28004.txt, internal/service/sns/consts.go, internal/service/sns/topic_subscription.go, internal/service/sns/topic_subscription_test.go, website/docs/r/sns_topic_subscription.html.markdown
Closes https://github.com/hashicorp/terraform-provider-aws/issues/27997
```
$ make testacc TESTS=TestAccSNSTopicSubscription_ PKG=sns
TF_ACC=1 go test ./internal/service/sns/... -v -count 1 -parallel 20 -run='TestAccSNSTopicSubscription_'  -timeout 180m
=== RUN   TestAccSNSTopicSubscription_basic
=== PAUSE TestAccSNSTopicSubscription_basic
=== RUN   TestAccSNSTopicSubscription_filterPolicy
=== PAUSE TestAccSNSTopicSubscription_filterPolicy
=== RUN   TestAccSNSTopicSubscription_filterPolicyScope
=== PAUSE TestAccSNSTopicSubscription_filterPolicyScope
=== RUN   TestAccSNSTopicSubscription_filterPolicyScope_policyNotSet
=== PAUSE TestAccSNSTopicSubscription_filterPolicyScope_policyNotSet
=== RUN …
```
=> r/aws_sns_topic_subscription: add filter_policy_scope attribute

.changelog/28025.txt, internal/service/sagemaker/status.go, internal/service/sagemaker/user_profile.go, internal/service/sagemaker/user_profile_test.go
Relates #27265
```
$ make testacc TESTS=TestAccSageMaker_serial/UserProfile/tensorboardAppSettingsWithImage
--- PASS: TestAccSageMaker_serial (304.45s)
--- PASS: TestAccSageMaker_serial/UserProfile (304.45s)
--- PASS: TestAccSageMaker_serial/UserProfile/tensorboardAppSettingsWithImage (304.45s)
```
=> r/sagemaker_user_profile - make user settings updateable + better response on error for sagemaker studio resources

.changelog/28022.txt, internal/service/memorydb/cluster.go, internal/service/memorydb/cluster_data_source.go, internal/service/memorydb/cluster_data_source_test.go, internal/service/memorydb/cluster_test.go, website/docs/d/memorydb_cluster.html.markdown, website/docs/r/memorydb_cluster.html.markdown
- Removes the `MaxItems: 1` restriction of the `snapshot_arns` attribute (the API doesn't document a limit).
- Adds the `data_tiering` attribute to the resource and data source (https://aws.amazon.com/about-aws/whats-new/2022/11/amazon-memorydb-redis-data-tiering/).
Closes https://github.com/hashicorp/terraform-provider-aws/issues/25780
- https://aws.amazon.com/about-aws/whats-new/2022/11/amazon-memorydb-redis-data-tiering/
```
$ make testacc TESTS=TestAccMemoryDBCluster_ PKG=memorydb ACCTEST_TIMEOUT=600m ACCTEST_PARALLELISM=5
TF_ACC=1 go test ./internal/service/memorydb/... -v -count 1 -parallel 5 -run='TestAccMemoryDBCluster_'  -timeout 600m
=== RUN   TestAccMemoryDBCluster_basic
=== PAUSE TestAccMemoryDBCluster_basic
=== RUN …
```
=> aws_memorydb_cluster: add data_tiering attribute and allow more than one snapshot ARN

website/docs/r/cloudformation_stack_set_instance.html.markdown
- adding valid values to region_concurrency_type argument in "`operation_preferences` Argument Reference" section
- fixing bullet list format in "`operation_preferences` Argument Reference" section
- fixing bullet list format in "`deployment_targets` Argument Reference" section
Closes #27821
=> docs: adding missing region_concurrency_type valid values (#27821)

website/docs/r/autoscaling_group.html.markdown
Add `skip_matching` to `aws_autoscaling_group` documentation.
Closes #28014 
https://github.com/hashicorp/terraform-provider-aws/pull/23059 added the skip_matching option to the instance_refresh block, closing issue https://github.com/hashicorp/terraform-provider-aws/issues/22554
=> docs: Add skip_matching to autoscaling_group

.changelog/28008.txt, internal/service/lambda/function.go, internal/service/lambda/function_test.go
Closes #27986 
```
make testacc TESTARGS='-run=TestAccLambdaFunction_codeSigning\|TestAccLambdaFunction_tracing\|TestAccLambdaFunction_basic' PKG=lambda 
TF_ACC=1 go test ./internal/service/lambda/... -v -count 1 -parallel 20  -run=TestAccLambdaFunction_codeSigning\|TestAccLambdaFunction_tracing\|TestAccLambdaFunction_basic -timeout 180m
=== RUN   TestAccLambdaFunction_basic
=== PAUSE TestAccLambdaFunction_basic
=== RUN   TestAccLambdaFunction_codeSigning
=== PAUSE TestAccLambdaFunction_codeSigning
=== RUN   TestAccLambdaFunction_tracing
=== PAUSE TestAccLambdaFunction_tracing
=== CONT  TestAccLambdaFunction_basic
=== CONT  TestAccLambdaFunction_tracing
=== CONT  TestAccLambdaFunction_codeSigning
--- PASS: …
```
=> Update available codesigning region guards

.changelog/28027.txt, internal/service/emrserverless/application.go, internal/service/emrserverless/application_test.go, website/docs/r/emrserverless_application.markdown
Closes #27999
```
$  make testacc TESTS=TestAccEMRServerlessApplication_arch  PKG=emrserverless
--- PASS: TestAccEMRServerlessApplication_basic (99.03s)
--- PASS: TestAccEMRServerlessApplication_network (113.05s)
--- PASS: TestAccEMRServerlessApplication_disappears (117.02s)
--- PASS: TestAccEMRServerlessApplication_arch (119.54s)
--- PASS: TestAccEMRServerlessApplication_maxCapacity (120.41s)
--- PASS: TestAccEMRServerlessApplication_initialCapacity (120.55s)
--- PASS: TestAccEMRServerlessApplication_tags (141.68s)
```
=> r/emrserverlesss_application - add  architecture argument

.changelog/28026.txt, internal/provider/provider.go, internal/service/redshiftserverless/credentials_data_source.go, internal/service/redshiftserverless/credentials_data_source_test.go, website/docs/d/redshift_cluster_credentials.html.markdown, website/docs/d/redshiftserverless_credentials.html.markdown
```
$ make testacc TESTS=TestAccRedshiftServerlessCredentialsDataSource_basic  PKG=redshiftserverless
--- PASS: TestAccRedshiftServerlessCredentialsDataSource_basic (625.34s)
```
=> redshift serverless creds data source

website/docs/r/cloudfront_distribution.html.markdown
The `locations` attribute is required on a `geo_restriction`, while the documentation says it's optional. This attribute can be an empty array.
=> Update the restrictions entry

.changelog/28049.txt, go.mod, go.sum, internal/conns/awsclient.go, internal/conns/awsclient_gen.go, internal/conns/config.go, internal/generate/awsclient/file.tmpl, internal/provider/provider.go, internal/service/logs/data_protection_policy.go, internal/service/logs/data_protection_policy_test.go, internal/service/logs/destination_policy.go, names/names.go, website/docs/r/cloudwatch_log_data_protection_policy.html.markdown
Closes https://github.com/hashicorp/terraform-provider-aws/pull/28045
Relates https://github.com/hashicorp/terraform-provider-aws/issues/28036
```
$ make testacc TESTS=TestAccLogsDataProtectionPolicy_ PKG=logs
TF_ACC=1 go test ./internal/service/logs/... -v -count 1 -parallel 20 -run='TestAccLogsDataProtectionPolicy_'  -timeout 180m
=== RUN   TestAccLogsDataProtectionPolicy_basic
=== PAUSE TestAccLogsDataProtectionPolicy_basic
=== RUN   TestAccLogsDataProtectionPolicy_disappears
=== PAUSE TestAccLogsDataProtectionPolicy_disappears
=== RUN   TestAccLogsDataProtectionPolicy_policyDocument
=== PAUSE TestAccLogsDataProtectionPolicy_policyDocument
=== CONT  TestAccLogsDataProtectionPolicy_basic
=== CONT …
```
=> New Resource: aws_cloudwatch_log_data_protection_policy

.changelog/28048.txt, internal/service/glue/classifier.go, internal/service/glue/classifier_test.go, internal/service/glue/find.go, internal/service/glue/sweep.go, website/docs/r/glue_classifier.html.markdown
Closes #27971
```
$ make testacc TESTS=TestAccGlueClassifier_  PKG=glue
--- PASS: TestAccGlueClassifier_disappears (36.49s)
--- PASS: TestAccGlueClassifier_CSVClassifier_quoteSymbol (76.01s)
--- PASS: TestAccGlueClassifier_CSVClassifier_custom (76.80s)
--- PASS: TestAccGlueClassifier_csvClassifier (76.80s)
--- PASS: TestAccGlueClassifier_jsonClassifier (77.05s)
--- PASS: TestAccGlueClassifier_grokClassifier (77.84s)
--- PASS: TestAccGlueClassifier_GrokClassifier_customPatterns (77.85s)
--- PASS: TestAccGlueClassifier_xmlClassifier (77.89s)
--- PASS: TestAccGlueClassifier_typeChange (118.30s)
```
=> r/glue_classfier - `custom_datatype_configured` and `custom_datatypes`

.changelog/28055.txt, internal/service/ce/cost_category.go, internal/service/ce/cost_category_test.go, website/docs/r/ce_cost_category.html.markdown
Closes #28009
```
$ make testacc TESTS=TestAccCECostCategory_ PKG=ce
--- PASS: TestAccCECostCategory_disappears (31.25s)
--- PASS: TestAccCECostCategory_basic (47.13s)
--- PASS: TestAccCECostCategory_complete (67.70s)
--- PASS: TestAccCECostCategory_effectiveStart (71.30s)
--- PASS: TestAccCECostCategory_splitCharge (72.68s)
--- PASS: TestAccCECostCategory_tags (96.73s)
```
=> r/aws_ce_cost_category - make `effective_start` an argument

website/docs/r/docdb_cluster_instance.html.markdown
According to the [documentation on the actual data type](https://docs.aws.amazon.com/documentdb/latest/developerguide/API_DBInstance.html) - and the [AWS CLI docs confirm this](https://docs.aws.amazon.com/cli/latest/reference/docdb/create-db-instance.html) - the `auto_minor_version_upgrade` settings are not applicable to DocDB instances. The options seem to be there to retain some sort of compatibility to the RDS CLI (maybe), but they have no effect.
Terraformers relying on this documentation might expect, that changing that setting changes something in their cloud setup, but it in fact does not.
This pull request should fix the documentation stating wrong things on this page:
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/docdb_cluster_instance
* AWS …
=> Fix auto_minor_version_upgrade documentation on DocumentDB instances

website/docs/r/dms_endpoint.html.markdown
This MR aims to fix link for extra_connection_attributes on [documentation website](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/dms_endpoint). Old link was pointing to a Postgres specific documentation, the new one point to the source list.
=> feat(documentation): update DMS endpoint extra_connection_attributes link.

.changelog/27972.txt, internal/service/ec2/ec2_instance.go, internal/service/ec2/ec2_instance_test.go
This PR fixes #27969.
Closes #27969
```
$ AWS_DEFAULT_REGION=ap-northeast-1 make testacc TESTS='^TestAccEC2Instance_(basic|withIAMInstanceProfile|LaunchTemplate_withIamInstanceProfile)$' PKG=ec2
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 20 -run='^TestAccEC2Instance_(basic|withIAMInstanceProfile|LaunchTemplate_withIamInstanceProfile)'  -timeout 180m
=== RUN   TestAccEC2Instance_basic
=== PAUSE TestAccEC2Instance_basic
=== RUN   TestAccEC2Instance_withIAMInstanceProfile
=== PAUSE TestAccEC2Instance_withIAMInstanceProfile
=== RUN   TestAccEC2Instance_withIAMInstanceProfilePath
=== PAUSE TestAccEC2Instance_withIAMInstanceProfilePath
=== RUN   TestAccEC2Instance_LaunchTemplate_withIamInstanceProfile
=== PAUSE …
```
=> Fix bug that makes aws_instance ignore iam instance profile of launch template

go.mod, go.sum, internal/conns/awsclient_gen.go, internal/conns/config_gen.go, internal/generate/awsclient/main.go, internal/generate/clientconfig/main.go, internal/service/cloudcontrol/resource.go, internal/service/cloudcontrol/resource_data_source.go, internal/service/cloudcontrol/resource_test.go, names/names_data.csv
Migrates the `cloudcontrol` service resource and data source to AWS SDK for Go v2.
```console
% make testacc TESTARGS='-run=TestAccCloudControlResource_' PKG=cloudcontrol ACCTEST_PARALLELISM=2
TF_ACC=1 go test ./internal/service/cloudcontrol/... -v -count 1 -parallel 2  -run=TestAccCloudControlResource_ -timeout 180m
=== RUN   TestAccCloudControlResource_basic
=== PAUSE TestAccCloudControlResource_basic
=== RUN   TestAccCloudControlResource_disappears
=== PAUSE TestAccCloudControlResource_disappears
=== RUN   TestAccCloudControlResource_DesiredState_booleanValueAdded
=== PAUSE TestAccCloudControlResource_DesiredState_booleanValueAdded
=== RUN   TestAccCloudControlResource_DesiredState_booleanValueRemoved
=== PAUSE …
```
=> Tech debt: Migrate `cloudcontrol` to AWS SDK v2

.changelog/28125.txt, internal/service/redshiftserverless/namespace.go, internal/service/redshiftserverless/namespace_test.go
Closes #28122
```
$ make testacc TESTS=TestAccRedshiftServerlessNamespace_ PKG=redshiftserverless
--- PASS: TestAccRedshiftServerlessNamespace_disappears (20.45s)
--- PASS: TestAccRedshiftServerlessNamespace_user (47.28s)
--- PASS: TestAccRedshiftServerlessNamespace_basic (51.88s)
--- PASS: TestAccRedshiftServerlessNamespace_tags (62.37s)
```
=> r/aws_redshiftserverless_namespace - fix user/pass update

.changelog/28130.txt, internal/provider/provider.go, internal/service/dms/endpoint.go, internal/service/dms/s3_endpoint.go, internal/service/dms/s3_endpoint_test.go, internal/service/dms/sweep.go, internal/service/dms/wait.go, website/docs/r/dms_s3_endpoint.html.markdown
This PR addresses at least 3 challenges currently swirling around DMS endpoints.
1. **Extra connection attributes** aren't scaling well for AWS and all the endpoint types available. Correspondingly, the `aws_dms_endpoint` resource is not well suited to handling the many endpoint types, and their unique attributes, without the use of **extra connection attributes**.  The resource is stretched thin (read it's a mess) already with attempts to handle so many endpoints and all the variious edge cases associated with each.
1. As AWS moves closer to deprecating **extra connection attributes**, it appears that they are dropping support for some attributes, like `compression_type`. You _can_ still use `compression_type` but not through **extra connection attributes**.
2. AWS seems to have …
=> dms: New resource aws_dms_s3_endpoint

website/docs/r/controltower_control.html.markdown
This is adding import documentation for a control tower control. 
https://github.com/hashicorp/terraform-provider-aws/issues/28020
Closes #28020
NA
NA
=> Adding import documentation for control tower controls

.changelog/28156.txt, internal/service/glue/crawler.go, internal/service/glue/crawler_test.go, internal/service/glue/find.go, website/docs/r/glue_crawler.html.markdown
Closes #27331
Closes #27745
```
$ make testacc TESTS=TestAccGlueCrawler_ PKG=glue
--- PASS: TestAccGlueCrawler_RoleName_path (58.00s)
--- PASS: TestAccGlueCrawler_disappears (67.33s)
--- PASS: TestAccGlueCrawler_S3Target_connectionName (86.44s)
--- PASS: TestAccGlueCrawler_S3Target_exclusions (107.86s)
--- PASS: TestAccGlueCrawler_deltaTarget (109.96s)
--- PASS: TestAccGlueCrawler_jdbcTarget (110.31s)
--- PASS: TestAccGlueCrawler_S3Target_eventqueue (116.07s)
--- PASS: TestAccGlueCrawler_S3Target_dlqeventqueue (117.16s)
--- PASS: TestAccGlueCrawler_description (117.37s)
--- PASS: TestAccGlueCrawler_S3Target_sampleSize (117.91s)
--- PASS: TestAccGlueCrawler_mongoDBTarget (118.56s)
--- PASS: TestAccGlueCrawler_dynamoDBTarget (119.01s)
--- PASS: TestAccGlueCrawler_catalogTarget (138.38s)
--- …
```
=> r/glue_crawler - add args to targets 

.goreleaser.yml
Due to a change in the release process or Go tooling, the released version of the provider was incorrectly sending `dev` as the provider version in HTTP User-Agent strings. Restore the actual version.
Previously, setting
```
-ldflags ... -X version.ProviderVersion={{ .Version }}
```
worked. We now need to specify the full path of the variable if it is not in the `main` package, i.e.
```
-ldflags ... -X 'github.com/hashicorp/terraform-provider-aws/version.ProviderVersion={{ .Version }}'
```
Using [development override](https://developer.hashicorp.com/terraform/cli/config/config-file#development-overrides-for-provider-developers):
```hcl
provider_installation {
dev_overrides {
"hashicorp/aws" = "<provider-code-directory>/dist/terraform-provider-aws_darwin_amd64_v1"
}
direct {}
}
``` …
=> Release: Restore provider version in HTTP User-Agent strings

.changelog/28253.txt, internal/service/sns/topic_subscription.go, internal/service/sns/topic_subscription_test.go
Prevents the `aws_sns_topic_subscription` resource from passing the `FilterPolicyScope` attribute _unless_ it's been set explicitly by the practitioner or read back from the API first. This should fix a change introduced in https://github.com/hashicorp/terraform-provider-aws/pull/28004 that broke subscriptions in AWS China partitions.
I don't have access to the partition where the issue occurs, so this fix is speculative. I ran manual tests to simulate the behaviour of the AWS China partition by unsetting the `FilterPolicyScope` attribute during reads, and checking whether the provider in those cases would attempt to write back the policy scope attribute.
Also increases the confirmation timeout of the `TestAccSNSTopicSubscription_autoConfirmingSecuredEndpoint` acceptance test -- at the …
=> r/aws_sns_topic_subscription: don't set the FilterPolicyScope attribute in unsupported partitions

.changelog/28018.txt, internal/service/elbv2/target_group.go, internal/service/elbv2/target_group_test.go, website/docs/r/lb_target_group.html.markdown
The elbv2 API permits health checks to be modified in place, so this removes the diff customisation pieces that were forcing recreation. It also removes some additional constraints that the API has removed.
Closes #25338
https://docs.aws.amazon.com/sdk-for-go/api/service/elbv2/#CreateTargetGroupInput
```
$ make testacc TESTS=TestAccELBV2TargetGroup_ PKG=elbv2 ACCTEST_PARALLELISM=3
TF_ACC=1 go test ./internal/service/elbv2/... -v -count 1 -parallel 3 -run='TestAccELBV2TargetGroup_'  -timeout 180m
=== RUN   TestAccELBV2TargetGroup_backwardsCompatibility
=== PAUSE TestAccELBV2TargetGroup_backwardsCompatibility
=== RUN   TestAccELBV2TargetGroup_ProtocolVersion_basic
=== PAUSE TestAccELBV2TargetGroup_ProtocolVersion_basic
=== RUN …
```
=> Don't force recreation of aws_lb_target_groups on health check modifications

internal/service/rds/instance.go, internal/service/rds/instance_test.go
Prevents errors like
```
Error: updating RDS DB Instance (tf-acc-test-5977403606277891875): operation error RDS: ModifyDBInstance, https response error StatusCode: 400, RequestID: 6086d274-e75b-445c-afc5-8f6b14bbba02, api error InvalidParameterCombination: You can't specify IOPS or storage throughput for engine mysql and a storage size less than 400.
```
modifying `allocated_storage` when `storage_type` is `"gp3"` and `allocated_storage` is below a per-engine threshold.
Closes #28160.
```console
% make testacc TESTARGS='-run=TestAccRDSInstance_storageTypePostgres' PKG=rds ACCTEST_PARALLELISM=3
TF_ACC=1 go test ./internal/service/rds/... -v -count 1 -parallel 3  -run=TestAccRDSInstance_storageTypePostgres -timeout 180m
=== RUN …
```
=> r/aws_db_instance: Fix error modifying `allocated_storage` when `storage_type` is `"gp3"`

internal/service/cloudformation/id.go
PR should fix the typo (ACCOUNDID) in the error message below.
```
╷
│ Error: unexpected format for ID (cloudtrail-ou-accounts,,eu-central-1), expected STACKSETNAME,ACCOUNDID,REGION
│ 
│   with aws_cloudformation_stack_set_instance.cloudtrail_ou,
│   on stacksets.tf line 8, in resource "aws_cloudformation_stack_set_instance" "cloudtrail_ou":
│    8: resource "aws_cloudformation_stack_set_instance" "cloudtrail_ou" {
│ 
╵
```
=> b_typo_internal-service-cloudformation-id

.changelog/28257.txt, internal/service/auditmanager/exports_test.go, internal/service/auditmanager/framework.go, internal/service/auditmanager/framework_test.go, website/docs/r/auditmanager_framework.html.markdown
`aws_auditmanager_framework` will allow practitioners to manage custom assessment frameworks.
Relates #17981 
```console
$ make testacc PKG=auditmanager TESTS=TestAccAuditManagerFramework_
TF_ACC=1 go test ./internal/service/auditmanager/... -v -count 1 -parallel 20 -run='TestAccAuditManagerFramework_'  -timeout 180m
=== RUN   TestAccAuditManagerFramework_basic
=== PAUSE TestAccAuditManagerFramework_basic
=== RUN   TestAccAuditManagerFramework_disappears
=== PAUSE TestAccAuditManagerFramework_disappears
=== RUN   TestAccAuditManagerFramework_tags
=== PAUSE TestAccAuditManagerFramework_tags
=== RUN   TestAccAuditManagerFramework_optional
=== PAUSE TestAccAuditManagerFramework_optional
=== CONT  TestAccAuditManagerFramework_basic …
```
=> New Resource: `aws_auditmanager_framework`

internal/service/auditmanager/sweep.go, internal/sweep/sweep_test.go
Adding sweepers for the `auditmanager` service. Currently this includes the `control` and `framework` resources.
Relates #17981 
```
$ SWEEPARGS=-sweep-run=aws_auditmanager_ make sweep
go test ./internal/sweep -v -tags=sweep -sweep=us-west-2,us-east-1,us-east-2 -sweep-run=aws_auditmanager_ -timeout 60m
<snip>
2022/12/09 10:31:49 [DEBUG] Completed Sweeper (aws_auditmanager_framework) in region (us-east-2) in 122.288625ms
2022/12/09 10:31:49 Completed Sweepers for region (us-east-2) in 474.862791ms
2022/12/09 10:31:49 Sweeper Tests for region (us-east-2) ran successfully:
- aws_auditmanager_control
- aws_auditmanager_framework
ok      github.com/hashicorp/terraform-provider-aws/internal/sweep      4.628s
```
=> Add `auditmanager` sweepers

website/docs/d/ec2_local_gateway_route_tables.html.markdown
Update doc for `aws_ec2_local_gateway_route_tables` to use proper plural version of the data source. It's currently referring to the singular `aws_ec2_local_gateway_route_table` version that doesn't support `ids` and expects a single route table.
=> Correct aws_ec2_local_gateway_route_tables usage doc

website/docs/r/apprunner_service.html.markdown, website/docs/r/apprunner_vpc_connector.html.markdown
There was a small typo on the Resource > AppRunner Service page, and also the Resource > AppRunner > VPC Connector page.
=> Fix typo on AppRunner service docs

.goreleaser.yml
Backports #28240 to `release/3.x`.
=> release/3.x: Set provider version in HTTP User-Agent strings

.changelog/28159.txt, internal/service/sagemaker/endpoint_configuration.go, internal/service/sagemaker/endpoint_configuration_test.go, website/docs/r/sagemaker_endpoint_configuration.html.markdown
Closes #0000
```
$ make testacc TESTS=TestAccSageMakerEndpointConfiguration_ PKG=sagemaker
--- PASS: TestAccSageMakerEndpointConfiguration_ProductionVariants_serverless (55.74s)
--- PASS: TestAccSageMakerEndpointConfiguration_disappears (56.61s)
--- PASS: TestAccSageMakerEndpointConfiguration_dataCapture (60.05s)
--- PASS: TestAccSageMakerEndpointConfiguration_kmsKeyID (60.09s)
--- PASS: TestAccSageMakerEndpointConfiguration_async_kms (62.37s)
--- PASS: TestAccSageMakerEndpointConfiguration_async (66.44s)
--- PASS: TestAccSageMakerEndpointConfiguration_Async_client (66.63s)
--- PASS: TestAccSageMakerEndpointConfiguration_ProductionVariants_initialVariantWeight (69.12s)
--- PASS: TestAccSageMakerEndpointConfiguration_Async_notif (70.48s)
--- PASS: …
```
=> r/sagemaker_endpoint_configurtion - add `shadow_production_variants` and other prod variants args 

.changelog/28154.txt, internal/provider/provider.go, internal/service/sagemaker/app.go, internal/service/sagemaker/app_test.go, internal/service/sagemaker/domain.go, internal/service/sagemaker/domain_test.go, internal/service/sagemaker/find.go, internal/service/sagemaker/sagemaker_test.go, internal/service/sagemaker/space.go, internal/service/sagemaker/space_test.go, internal/service/sagemaker/status.go, internal/service/sagemaker/sweep.go, internal/service/sagemaker/user_profile.go, internal/service/sagemaker/user_profile_test.go, internal/service/sagemaker/wait.go, website/docs/r/sagemaker_app.html.markdown, website/docs/r/sagemaker_domain.html.markdown, website/docs/r/sagemaker_model_package_group.html.markdown, website/docs/r/sagemaker_model_package_group_policy.html.markdown, website/docs/r/sagemaker_space.html.markdown, website/docs/r/sagemaker_studio_lifecycle_config.html.markdown, website/docs/r/sagemaker_user_profile.html.markdown
Closes #27265
Closes #27990
```
$ make testacc TESTS=TestAccSageMaker_serial/Space
--- PASS: TestAccSageMaker_serial (1666.88s)
--- PASS: TestAccSageMaker_serial/Space (1666.88s)
--- PASS: TestAccSageMaker_serial/Space/basic (271.61s)
--- PASS: TestAccSageMaker_serial/Space/disappears (324.01s)
--- PASS: TestAccSageMaker_serial/Space/tags (265.95s)
--- PASS: TestAccSageMaker_serial/Space/kernelGatewayAppSettings (269.04s)
--- PASS: TestAccSageMaker_serial/Space/kernelGatewayAppSettings_lifecycleConfig (267.09s)
--- PASS: TestAccSageMaker_serial/Space/jupyterServerAppSettings (269.17s)
--- PASS: TestAccSageMaker_serial (5300.99s)
--- PASS: TestAccSageMaker_serial/Domain (5300.99s)
--- PASS: TestAccSageMaker_serial/Domain/sharingSettings (444.31s)
--- PASS: …
```
=> r/sagemaker_space - new resource

website/docs/r/fsx_file_cache.html.markdown
This is a cosmetic update to the documentation page to reflect the official product name of "Amazon File Cache"
Closes #28282
https://docs.aws.amazon.com/fsx/latest/FileCacheGuide/what-is.html
=> updated product name in docs

.changelog/28254.txt, CHANGELOG.md, internal/service/lambda/functions_data_source.go, internal/service/lambda/functions_data_source_test.go, website/docs/d/lambda_functions.html.markdown
This PR introduces the `aws_lambda_functions` plural data source.
Closes #24522
Closes #17701
The Go AWS SDK does not support filters, for maintainability custom filters were not implemented in the provider.
https://docs.aws.amazon.com/sdk-for-go/api/service/lambda/#ListFunctionsInput
```
$ make testacc TESTARGS='-run=TestAccLambdaFunctionsDataSource_basic' PKG=lambda ACCTEST_PARALLELISM=2   
TF_ACC=1 go test ./internal/service/lambda/... -v -count 1 -parallel 2  -run=TestAccLambdaFunctionsDataSource_basic -timeout 180m
=== RUN   TestAccLambdaFunctionsDataSource_basic
=== PAUSE TestAccLambdaFunctionsDataSource_basic
=== CONT  TestAccLambdaFunctionsDataSource_basic
--- PASS: TestAccLambdaFunctionsDataSource_basic (28.99s)
PASS
ok …
```
=> d/aws_lambda_functions: new data resource

.changelog/28308.txt, internal/service/grafana/workspace.go, internal/service/grafana/workspace_test.go, website/docs/r/grafana_workspace.html.markdown
Closes #28244
```
$ make testacc TESTS=TestAccGrafana_serial/Workspace/vpc  PKG=grafana
--- PASS: TestAccGrafana_serial (758.78s)
--- PASS: TestAccGrafana_serial/Workspace (758.78s)
--- PASS: TestAccGrafana_serial/Workspace/vpc (758.78s)
```
=> VPC support for Grafana workspaces

.changelog/28241.txt, internal/provider/provider.go, internal/service/ssoadmin/find.go, internal/service/ssoadmin/permissions_boundary_attachment.go, internal/service/ssoadmin/permissions_boundary_attachment_test.go, website/docs/r/ssoadmin_permissions_boundary_attachment.html.markdown
Adds a `aws_ssoadmin_permissions_boundary_attachment` resource to enable attaching a permissions boundary to a permission set.  Example usage:
```hcl
resource "aws_ssoadmin_permissions_boundary_attachment" "example" {
instance_arn       = aws_ssoadmin_permission_set.example.instance_arn
permission_set_arn = aws_ssoadmin_permission_set.example.arn
permissions_boundary {
customer_managed_policy_reference {
name = aws_iam_policy.example.name
path = "/"
}
}
}
```
This is my first contribution, so if I've failed to follow any important conventions in the code, documentation, or this PR itself, please let me know!
Closes #25893
```
$ make testacc TESTS=TestAccSSOAdminPermissionsBoundaryAttachment_ PKG=ssoadmin 
TF_ACC=1 go1.19 test …
```
=> add aws_ssoadmin_permissions_boundary_attachment resource

internal/service/opsworks/sweep.go, internal/service/rds/cluster.go, internal/service/rds/cluster_parameter_group.go, internal/service/rds/cluster_snapshot.go, internal/service/rds/global_cluster.go, internal/service/rds/instance_automated_backups_replication.go, internal/service/rds/option_group.go, internal/service/rds/parameter_group.go, internal/service/rds/proxy.go, internal/service/rds/snapshot.go, internal/service/rds/sweep.go
Turned into more changes than I initially thought.
The primary issue we were having with RDS sweepers was the dependency inversion on `aws_db_instance` on `aws_db_cluster_snapshot`.
Fixing that I realized that there were other dependency issues.
Closes https://github.com/hashicorp/terraform-provider-aws/issues/26530.
```console
% make sweep SWEEPARGS=-sweep-run=aws_rds_global_cluster                       
go test ./internal/sweep -v -tags=sweep -sweep=us-west-2,us-east-1,us-east-2 -sweep-run=aws_rds_global_cluster -timeout 60m
2022/12/13 14:48:15 [DEBUG] Running Sweepers for region (us-west-2):
2022/12/13 14:48:15 [DEBUG] Running Sweeper (aws_db_instance) in region (us-west-2)
2022/12/13 14:48:15 [INFO] …
```
=> Sweepers: Various RDS fixes

website/docs/r/apigatewayv2_deployment.html.markdown
Replace `list` by `tolist` in the [API Gateway 2 documentation](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/apigatewayv2_deployment)
Closes #28157
=> Fix #28157 API Gateway v2 sample uses deprecated and now deleted "list" function

internal/provider/factory_test.go
Adds a test to benchmark provider construction.
Relates https://github.com/hashicorp/terraform-provider-aws/issues/26626.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/28202.
```console
% go test -bench=BenchmarkProtoV5ProviderServerFactory -benchtime 1x -benchmem -run=B -v ./internal/provider
goos: darwin
goarch: amd64
pkg: github.com/hashicorp/terraform-provider-aws/internal/provider
cpu: Intel(R) Core(TM) i7-1068NG7 CPU @ 2.30GHz
BenchmarkProtoV5ProviderServerFactory
factory_test.go:19: 1124 resources, 425 data sources
BenchmarkProtoV5ProviderServerFactory-8   	       1	 139206149 ns/op	78189992 B/op	 1076525 allocs/op
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/provider	4.721s
```
=> tests: Benchmark provider construction

go.mod, go.sum, internal/conns/awsclient_gen.go, internal/conns/config_gen.go, names/names_data.csv
Updated SSMincidents names_data (of which service has not yet been implemented) to correctly specify that it will use the go sdk v2 instead of v1
=> corrected names_data for ssmincidents

website/docs/r/codebuild_project.html.markdown
The documentation for `aws_codebuild_project` had a few issues, including:
- A few misnamed headers
- `file_system_location` header being out of alpha order, and in the middle of the `source` headers.
- Missing `source.build_status_config` documentation
Closes #28324
- [Resource schema](https://github.com/hashicorp/terraform-provider-aws/blob/bfcd55c7cde9b2190aa0a18e6110c967e1ad5458/internal/service/codebuild/project.go#L624-L640)
N/a, docs
=> Correct `aws_codebuild_project` documentation

website/docs/r/inspector2_enabler.html.markdown
The value values for `aws_inspector2_enabler.resource_types` has [been updated to include `LAMBDA`](https://docs.aws.amazon.com/inspector/v2/APIReference/API_Enable.html#inspector2-Enable-request-resourceTypes), which will be available as of the next release of the provider. This PR updates the documentation to match this.
Closes #28329
- [Schema `ValidateFunc` reference](https://github.com/hashicorp/terraform-provider-aws/blob/e9ea507012986603aec663169da2e8d694990112/internal/service/inspector2/enabler.go#L57)
- [Go SDK reference](https://github.com/aws/aws-sdk-go-v2/blob/93c3f1871b862d743e0bd2e2e7180246df3a9212/service/inspector2/types/enums.go#L916-L920)
N/a, docs
=> Update valid values for `resource_types` on `aws_inspector2_enabler`

.changelog/28439.txt, internal/service/lambda/function_url.go, internal/service/lambda/function_url_test.go
Though removing `cors` block of `aws_lambda_function_url` , actually Terraform does not remove the cors settings.
Reproduction steps:
1. apply
```
resource "aws_lambda_function_url" "example" {
function_name      = aws_lambda_function.example.function_name
authorization_type = "NONE"
cors {
allow_credentials = false
allow_origins     = ["*"]
allow_methods     = ["*"]
allow_headers     = ["content-type"]
}
}
```
2. delete the cors settings and apply
```
resource "aws_lambda_function_url" "example" {
function_name      = aws_lambda_function.example.function_name
authorization_type = "NONE"
}
```
3. check the AWS management console
cors settings are not removed.
Relates https://github.com/hashicorp/terraform-provider-aws/issues/24050.
N/A
```
$ make testacc TESTS=TestAccLambdaFunctionURL …
```
=> Fix Lambda function URL cors settings are not removed

internal/service/ec2/find.go, internal/service/ec2/sweep.go
Use the paginated EC2 [`DescribeImages`](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DescribeImages.html) API.
Closes https://github.com/hashicorp/terraform-provider-aws/issues/28515.
```console
% make sweep SWEEPARGS=-sweep-run=aws_ami SWEEP=us-west-1
go test ./internal/sweep -v -tags=sweep -sweep=us-west-1 -sweep-run=aws_ami -timeout 60m
2022/12/21 09:05:53 [DEBUG] Running Sweepers for region (us-west-1):
2022/12/21 09:05:53 [DEBUG] Running Sweeper (aws_ami) in region (us-west-1)
2022/12/21 09:05:53 [INFO] Retrieved credentials from "EnvConfigCredentials"
2022/12/21 09:05:53 [DEBUG] Trying to get account information via sts:GetCallerIdentity
2022/12/21 09:05:53 [DEBUG] Trying to get account …
```
=> r/aws_ami: Use paginated `DescribeImages` API

internal/service/firehose/delivery_stream_test.go
Closes #28519
```console
$ make testacc TESTARGS='-run=TestAccFirehoseDeliveryStream_' PKG=firehose
TF_ACC=1 go test ./internal/service/firehose/... -v -count 1 -parallel 20  -run=TestAccFirehoseDeliveryStream_ -timeout 180m
--- PASS: TestAccFirehoseDeliveryStream_s3KinesisStreamSource (68.20s)
--- PASS: TestAccFirehoseDeliveryStream_disappears (359.09s)
--- PASS: TestAccFirehoseDeliveryStream_missingProcessing (373.29s)
--- PASS: TestAccFirehoseDeliveryStream_basic (375.51s)
--- PASS: TestAccFirehoseDeliveryStream_ExtendedS3DataFormatConversionOpenXJSONSerDe_empty (381.63s)
--- PASS: TestAccFirehoseDeliveryStream_ExtendedS3DataFormatConversionDeserializer_update (325.75s)
--- PASS: …
```
=> r/aws_kinesis_firehose_delivery_stream: update test with defaults

.changelog/28085.txt, .changelog/28567.txt, internal/service/fsx/ontap_storage_virtual_machine.go, internal/service/fsx/ontap_storage_virtual_machine_test.go, website/docs/r/fsx_ontap_storage_virtual_machine.html.markdown
Ibid.
Closes https://github.com/hashicorp/terraform-provider-aws/issues/28565.
```console
% make testacc TESTARGS='-run=TestAccFSxOntapStorageVirtualMachine_basic' PKG=fsx
TF_ACC=1 go test ./internal/service/fsx/... -v -count 1 -parallel 20  -run=TestAccFSxOntapStorageVirtualMachine_basic -timeout 180m
=== RUN   TestAccFSxOntapStorageVirtualMachine_basic
=== PAUSE TestAccFSxOntapStorageVirtualMachine_basic
=== CONT  TestAccFSxOntapStorageVirtualMachine_basic
--- PASS: TestAccFSxOntapStorageVirtualMachine_basic (2617.64s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/fsx	2622.732s
```
=> r/aws_fsx_ontap_storage_virtual_machine: Undeprecate `subtype`

website/docs/r/dx_macsec_key_association.html.markdown
Updates the documentation for resource `aws_dx_macsec_key_association` to correct references to nonexistent resource type `aws_dx_macsec_key`.
Closes #28587 
Original PR with correct resources: https://github.com/hashicorp/terraform-provider-aws/pull/26274
```
...
```
=> Update resource references to aws_macsec_key_association

docs/running-and-writing-acceptance-tests.md
Was going through document and noticed the example for checking if resource disappeared was not what I was seeing when looking at recent code. Updated with what appears to be the standard.
=> Doc update: Standard way of checking resource disappeared

.changelog/28593.txt, internal/service/lightsail/disk_attachment.go, internal/service/lightsail/disk_attachment_test.go
This PR resolves a crash that occurs when terraform fails to attach a disk to an instance. The crash was taking place because the logs originally referenced an attribute that does not exist. 
Closes #28024
```
➜ terraform-provider-aws (b-aws_lightsail_disk_attachemnt_crash) ✗ make testacc TESTARGS='-run=TestAccLightsailDiskAttachment' PKG=lightsail
TF_ACC=1 go test ./internal/service/lightsail/... -v -count 1 -parallel 20  -run=TestAccLightsailDiskAttachment -timeout 180m
=== RUN   TestAccLightsailDiskAttachment_basic
=== PAUSE TestAccLightsailDiskAttachment_basic
=== RUN   TestAccLightsailDiskAttachment_disappears
=== PAUSE TestAccLightsailDiskAttachment_disappears
=== CONT  TestAccLightsailDiskAttachment_basic
=== CONT …
```
=> Bugfix: `aws_lightsail_disk_attachment` crash on failure

website/docs/r/glue_trigger.html.markdown
This change adds documentation for the glue trigger `EVENT` type, as stated in the [aws glue trigger docs](https://docs.aws.amazon.com/glue/latest/dg/aws-glue-api-jobs-trigger.html#aws-glue-api-jobs-trigger-CreateTrigger) and seen [in the SDK](https://github.com/aws/aws-sdk-go/blob/a9faefa96cb9bee57d55d9702b6e7de4aad69bc0/models/apis/glue/2017-03-31/api-2.json#L11419-L11427). I could not find within the AWS docs anything specifically stating why `enabled` must be set to `false` for the `EVENT` type, but I know this to be true from seeing the error myself.
Closes #0000
```
...
```
=> Doc: glue trigger "EVENT" type

go.mod, go.sum
Consolidates all the `aws_sdk-go-v2` _dependabot_ updates for the last few of weeks.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/28503.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/28625.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/28502.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/28415.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/28504.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/28506.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/28525.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/28527.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/28544.
Relates …
=> Rollup `aws_sdk-go-v2` dependency updates

website/docs/r/appstream_image_builder.html.markdown
This PR updates the `aws_appstream_image_builder` example in the documentation, as the `image_name` previous used is deprecated.
Closes #28601
- [AWS image name doc](https://docs.aws.amazon.com/appstream2/latest/developerguide/base-image-version-history.html)
n/a, docs
=> Update example in `aws_appstream_image_builder` docs

website/docs/r/glue_trigger.html.markdown
@ewbankkit 
This is to remove an invalid statement added with [a previous PR](https://github.com/hashicorp/terraform-provider-aws/pull/28630) just merged about 9 hours ago. My sincere apologies, I have since realized through subsequent attempts, that this statement is not true. Likewise, I am not able to identify why it had been necessary to resolve a previous error message. Regardless, I cannot say definitely that it is true, therefore I think the statement should be removed.
Closes #0000
```
...
```
=> Doc: Invalid statement in glue trigger docs

.changelog/28643.txt, internal/service/auditmanager/assessment.go, internal/service/auditmanager/assessment_test.go, internal/service/auditmanager/exports_test.go, internal/service/auditmanager/sweep.go, website/docs/r/auditmanager_assessment.html.markdown, website/docs/r/auditmanager_framework.html.markdown
`aws_auditmanager_assessment` will allow practitioners to manage custom assessments.
Relates #17981
Closes #28356 
Closes #28638
```console
$ make testacc PKG=auditmanager TESTS=TestAccAuditManagerAssessment_ ACCTEST_PARALLELISM=2
TF_ACC=1 go test ./internal/service/auditmanager/... -v -count 1 -parallel 2 -run='TestAccAuditManagerAssessment_'  -timeout 180m
=== RUN   TestAccAuditManagerAssessment_basic
=== PAUSE TestAccAuditManagerAssessment_basic
=== RUN   TestAccAuditManagerAssessment_disappears
=== PAUSE TestAccAuditManagerAssessment_disappears
=== RUN   TestAccAuditManagerAssessment_tags
=== PAUSE TestAccAuditManagerAssessment_tags
=== RUN   TestAccAuditManagerAssessment_optional
=== PAUSE …
```
=> New Resource `aws_auditmanager_assessment`

.changelog/28594.txt, internal/service/wafv2/flex.go, internal/service/wafv2/schemas.go, internal/service/wafv2/web_acl_test.go, website/docs/r/wafv2_web_acl.html.markdown
This PR implements Managed Rule Group Config support for the WAFv2 Resource to enable the usage of ATP and BotControl WAF rules within terraform. 
Example Configuration: 
```
statement {
managed_rule_group_statement {
name        = "AWSManagedRulesATPRuleSet"
vendor_name = "AWS"
managed_rule_group_config {
login_path     = "/login-test"
password_field = "/password"
payload_type   = "JSON"
username_field = "/username"
}
}
```
Closes #23290
Closes #26826
Closes #23287
https://docs.aws.amazon.com/waf/latest/developerguide/aws-managed-rule-groups-bot.html
https://docs.aws.amazon.com/waf/latest/developerguide/aws-managed-rule-groups-atp.html
https://docs.aws.amazon.com/waf/latest/APIReference/API_ManagedRuleGroupConfig.html
```
❯ make testacc PKG=wafv2 …
```
=> Add Managed Rule Group Config functionality to WAFv2 resource

.changelog/28663.txt, internal/service/auditmanager/assessment_report.go, internal/service/auditmanager/assessment_report_test.go, internal/service/auditmanager/exports_test.go, website/docs/r/auditmanager_assessment_report.html.markdown
`aws_auditmanager_assessment_report` will allow practitioners to manage assessment reports.
Relates #17981
```console
$ make testacc PKG=auditmanager TESTS=TestAccAuditManagerAssessmentReport_
TF_ACC=1 go test ./internal/service/auditmanager/... -v -count 1 -parallel 20 -run='TestAccAuditManagerAssessmentReport_'  -timeout 180m
=== RUN   TestAccAuditManagerAssessmentReport_basic
=== PAUSE TestAccAuditManagerAssessmentReport_basic
=== RUN   TestAccAuditManagerAssessmentReport_disappears
=== PAUSE TestAccAuditManagerAssessmentReport_disappears
=== RUN   TestAccAuditManagerAssessmentReport_optional
=== PAUSE TestAccAuditManagerAssessmentReport_optional
=== CONT  TestAccAuditManagerAssessmentReport_basic
=== CONT …
```
=> New Resource `aws_auditmanager_assessment_report`

website/docs/r/synthetics_canary.html.markdown
The SI units for the maximum zip file for canary lambda zip upload size were incorrect.
This is also incorrect on the AWS documentation (https://docs.aws.amazon.com/AmazonSynthetics/latest/APIReference/API_CanaryCodeInput.html#synthetics-Type-CanaryCodeInput-ZipFile).
I have reached out to AWS support independently, who have confirmed this to also be incorrect and have been told it will be updated once reviewed internally.
Once I hear back from AWS support that it has been corrected, I can post back here so the live AWS documentation can be confirmed.
=> docs: Fix SI unit used in maximum zip file from Kb (kilobits) to KB (kilobytes)

.changelog/28689.txt, internal/service/elasticache/user_group_association.go, internal/service/elasticache/user_group_association_test.go
If a group is in status "Modifying", attempts to create or destroy an association fail with an `InvalidUserGroupState` error. Retry the operation until the status changes back to "Active".
Creating or destroying an `aws_elasticache_user_group_association` sets the user group in status "Modifying". When the group is in this status, no other changes can be made. If two association resources are created or destroyed at the same time (even in the same module), one will fail with an `InvalidUserGroupState` error.
To avoid this, retry create and destroy operations until the `InvalidUserGroupState` error goes away.
Closes #28688
```
$ make testacc TESTS=TestAccElastiCacheUserGroupAssociation PKG=elasticache …
```
=> r/aws_elasticache_user_group_association: Handle concurrent updates (#28688)

.changelog/28579.txt, internal/service/dms/endpoint.go, internal/service/dms/endpoint_test.go, website/docs/r/dms_endpoint.html.markdown, website/docs/r/dms_s3_endpoint.html.markdown
Fix typo in setting, should be `ignore_header_rows` not `ignore_headers_row`
Closes https://github.com/hashicorp/terraform-provider-aws/issues/26957
https://docs.aws.amazon.com/dms/latest/APIReference/API_S3Settings.html
=> aws_dms_endpoint.ignore_header_rows typo

.changelog/28578.txt, internal/service/dms/endpoint.go, internal/service/dms/endpoint_test.go, website/docs/r/dms_endpoint.html.markdown, website/docs/r/dms_s3_endpoint.html.markdown
https://github.com/hashicorp/terraform-provider-aws/issues/27688 captures the details of the bug
`cdc_min_file_size` is 32 which previously was correct when api was in megabytess but has since changed to kilobytes. Updating to 32000 as default which is in aws docs.
Closes https://github.com/hashicorp/terraform-provider-aws/issues/27688
https://docs.aws.amazon.com/dms/latest/userguide/CHAP_Target.S3.html#CHAP_Target.S3.Configuring
=> aws_dms_endpoint.cdc_min_file_size is kilobytes, no longer megabytes

.github/workflows/release.yml, .goreleaser.yml, .release/release-metadata.hcl
Backports the GitHub Action release workflow to `release/2.x`.
No `terraform-registry-manifest.json` file is included.
Relates: https://github.com/hashicorp/terraform-provider-aws/pull/23895.
=> release/2.x: Backport GitHub Actions release workflow

.changelog/28702.txt, internal/service/s3/bucket.go, internal/service/s3/bucket_test.go, website/docs/r/s3_bucket.html.markdown
Changes `aws_s3_bucket. server_side_encryption_configuration` to `Computed`.
Relates https://github.com/hashicorp/terraform-provider-aws/issues/28701.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/28700.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/28703.
```console
% make testacc TESTARGS='-run=TestAccS3Bucket_Basic_basic\|TestAccS3Bucket_Security_noConfiguredServerSideEncryptionAfterDefaultEncryptionIsEnabled' PKG=s3
TF_ACC=1 go test ./internal/service/s3/... -v -count 1 -parallel 20  -run=TestAccS3Bucket_Basic_basic\|TestAccS3Bucket_Security_noConfiguredServerSideEncryptionAfterDefaultEncryptionIsEnabled -timeout 180m
=== RUN   TestAccS3Bucket_Basic_basic
=== PAUSE …
```
=> release/3.x: AWS S3 Bucket default encryption

CHANGELOG.md, aws/resource_aws_s3_bucket.go, aws/resource_aws_s3_bucket_test.go, website/docs/r/s3_bucket.html.markdown
Changes `aws_s3_bucket. server_side_encryption_configuration` to `Computed`.
Relates https://github.com/hashicorp/terraform-provider-aws/issues/28701.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/28700.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/28702.
```console
% make testacc TEST=./aws TESTARGS='-run=TestAccAWSS3Bucket_basic\|TestAccAWSS3Bucket_Security_noConfiguredServerSideEncryptionAfterDefaultEncryptionIsEnabled'
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSS3Bucket_basic\|TestAccAWSS3Bucket_Security_noConfiguredServerSideEncryptionAfterDefaultEncryptionIsEnabled -timeout 120m
=== RUN   TestAccAWSS3Bucket_basic
=== PAUSE TestAccAWSS3Bucket_basic
=== RUN …
```
=> release/2.x: AWS S3 Bucket default encryption

website/docs/r/lb.html.markdown
missing carriage return results in property 'security_groups' misaligned in doc
Closes #0000
```
...
```
=> typo in lb documentation

.goreleaser.yml, CHANGELOG.md
Corrects the built binary filename (adds `_x4` suffix) and HTTP headers to allow TF CLI versions 0.11 and 0.12 to install the **v2._x_** provider.
Closes https://github.com/hashicorp/terraform-provider-aws/issues/28706.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/28698.
=> release/2.x: Correct release incantation for Terraform CLI 0.11 & 0.12 support

website/docs/r/securityhub_standards_subscription.markdown
The CIS AWS Foundations Benchmark v1.4.0 standard is currently missing from the list of standards, and the doc change PR is to add it to the list. As well, most standard ARNs (except for CIS v1.2.0) are specific to the current region, so hardcoded references have also been generalized (similar to the docs for aws_securityhub_product-subscription) as variable references.
Closes #28522
Output from aws securityhub describe-standards (run from us-east-1) for reference:
```
{
"Standards": [
{
"StandardsArn": "arn:aws:securityhub:us-east-1::standards/aws-foundational-security-best-practices/v/1.0.0",
"Name": "AWS Foundational Security Best Practices v1.0.0",
"Description": "The AWS Foundational Security Best Practices standard is a set of automated security checks that detect when AWS accounts …
```
=> docs: update stds list in aws_securityhub_standards_subscription

website/docs/r/autoscaling_policy.html.markdown
The current example is misleading from semantic point of view. Hence, this patch uses [an example in AWS blog "Using EC2 Auto Scaling predictive scaling policies with Blue/Green deployments"](https://aws.amazon.com/blogs/compute/retaining-metrics-across-blue-green-deployment-for-predictive-scaling/) instead.
N/A
A relevant AWS blog: https://aws.amazon.com/blogs/compute/retaining-metrics-across-blue-green-deployment-for-predictive-scaling/
```
$ make testacc TESTS=TestAccAutoScalingPolicy PKG=autoscaling
...
--- PASS: TestAccAutoScalingPolicy_simpleScalingStepAdjustment (34.15s)
--- PASS: TestAccAutoScalingPolicy_predictiveScalingPredefined (37.67s)
--- PASS: TestAccAutoScalingPolicy_predictiveScalingCustom (38.91s)
--- PASS: TestAccAutoScalingPolicy_TargetTrack_predefined (43.27s)
--- …
```
=> r/aws_autoscaling_policy: Update example for predictive scaling

.goreleaser.yml, CHANGELOG.md
Add a missing space character for the `x-terraform-protocol-versions` HTTP header value separator.
Closes #28743.
=> release/2.x: Correct `x-terraform-protocol-versions` HTTP header value

internal/service/budgets/sweep.go
Configure `aws_budgets_budget` to skip any tests not named with the standard naming prefix.
```
make sweep SWEEPARGS=-sweep-run=aws_budgets_budget        
go test ./internal/sweep -v -tags=sweep -sweep=us-west-2,us-east-1,us-east-2 -sweep-run=aws_budgets_budget -timeout 60m
2023/01/05 10:43:24 [DEBUG] Running Sweepers for region (us-west-2):
2023/01/05 10:43:24 [DEBUG] Running Sweeper (aws_budgets_budget_action) in region (us-west-2)
2023/01/05 10:43:24 [INFO] Retrieved credentials from "SharedConfigCredentials: /Users/jdoe/.aws/credentials"
2023/01/05 10:43:24 [DEBUG] Trying to get account information via sts:GetCallerIdentity
2023/01/05 10:43:24 [DEBUG] Trying to get account information via …
```
=> Skip configured budgets

.changelog/28047.txt, internal/service/dms/endpoint.go, internal/service/dms/replication_task.go, internal/service/dms/replication_task_test.go, internal/service/dms/wait.go, website/docs/r/dms_endpoint.html.markdown
This PR intends to fix the bug [described here](https://github.com/hashicorp/terraform-provider-aws/issues/19938) by including `MigrationType` and `TableMappings` on the update call regardless of whether they have been changed.
That issue is well written and is great for context.
Closes #19938
[Readme in this repo for dms](https://github.com/hashicorp/terraform-provider-aws/blob/main/website/docs/r/dms_replication_task.html.markdown) - note: the altered fields are listed as required.
[AWS dms api](https://docs.aws.amazon.com/dms/latest/APIReference/API_ModifyReplicationTask.html)
I couldn't acceptance test this, hopefully you can run this on your side. I would be surprised if this change caused failures but you never know...
=> b/fix_dms_task_update_bug_19938: Add required fields to update input 

.changelog/28748.txt, internal/service/dms/replication_subnet_group.go, website/docs/r/dms_replication_subnet_group.html.markdown
This resolves 3 different problems with `aws_dms_replication_subnet_group`:
1. Inconsistent result error: This happens because of a code bug. If there's a non-timeout error during creation, instead of returning the error, it ignores it. On the `read`, when there is no resource found, there's no check for it being not found. 
2. Documenting the need to use subnets that cover 2 AZs and, thus, requiring at least 2 subnet IDs.
3. Documenting having the IAM role `dms-vpc-role` in place.
Closes #27420
```
% make testacc TESTS=TestAccDMSReplicationSubnetGroup_ PKG=dms
TF_ACC=1 go test ./internal/service/dms/... -v -count 1 -parallel 20 -run='TestAccDMSReplicationSubnetGroup_'  -timeout 180m
=== RUN …
```
=> dms/repl_subnet_grp: Fix inconsistent result after apply

internal/service/appconfig/extension_association.go
This resolves an a crash when the AWS API returns an error. The "name" attribute is not an attribute of an "association".
Closes #0000
```
➜ terraform-provider-aws (b-aws_appconfig_extension_association_crash) ✗ make testacc TESTARGS='-run=TestAccAppConfigExtensionAssociation' PKG=appconfig
TF_ACC=1 go test ./internal/service/appconfig/... -v -count 1 -parallel 20  -run=TestAccAppConfigExtensionAssociation -timeout 180m
=== RUN   TestAccAppConfigExtensionAssociation_basic
=== PAUSE TestAccAppConfigExtensionAssociation_basic
=== RUN   TestAccAppConfigExtensionAssociation_Parameters
=== PAUSE TestAccAppConfigExtensionAssociation_Parameters
=== RUN   TestAccAppConfigExtensionAssociation_disappears
=== PAUSE …
```
=> BUGFIX: `aws_appconfig_extenstion_association`, Resolve crash when logging errror

website/docs/r/docdb_global_cluster.html.markdown
aws_docdb_cluster_instance resource can't have engine_version and db_subnet_group_name
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/docdb_global_cluster#new-documentdb-global-cluster
In resource type "aws_docdb_cluster_instance", with resource name "primary" and "secondary", we can't mention below two arguments, as [aws_docdb_cluster_instance ](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/docdb_cluster_instance#argument-reference) is not having these arguments
```
engine_version       = aws_docdb_global_cluster.example.engine_version
db_subnet_group_name = "default"
```
Removing the above two arguments, in two places.
Otherwise we'll get 
```
Error: Value for unconfigurable attribute
with aws_docdb_cluster_instance.primary,
on …
```
=> documentation-issue-28533 in aws_docdb_global_cluster resource

.changelog/28766.txt, internal/service/appstream/stack.go, internal/service/appstream/stack_test.go, website/docs/r/appstream_stack.html.markdown
Fixes a pair of bugs in the `aws_appstream_stack` resource:
- Prevent unnecessary replacements for changes to attributes that can be updated in-place.
- Fix panic when `user_settings` are updated.
Also
- Updates the `user_settings` attribute documentation to indicate that all settings must be explicitly provided when not using the AWS defaults.
- Updates the `user_settings` configuration in acceptance tests.
---
Planned `description` update after code changes:
```
~ resource "aws_appstream_stack" "test" {
~ description        = "text" -> "text2"
id                 = "jb-test"
name               = "jb-test"
tags               = {}
}
Plan: 0 to add, 1 to change, 0 to destroy.
```
Closes #28764
Closes #25784
Closes #23338
Closes #22652
```console …
```
=> Fix unnecessary replacements, user settings update panic for `aws_appstream_stack`

.changelog/28777.txt, internal/service/iam/group_policy.go, internal/service/iam/policy.go, internal/service/iam/role.go, internal/service/iam/role_policy.go, internal/service/iam/user_policy.go
Relates #23288
* https://github.com/hashicorp/terraform-plugin-sdk/pull/882
```console
% make testacc TESTS=TestAccIAMRole_ PKG=iam
TF_ACC=1 go test ./internal/service/iam/... -v -count 1 -parallel 20 -run='TestAccIAMRole_'  -timeout 180m
=== RUN   TestAccIAMRole_basic
=== PAUSE TestAccIAMRole_basic
=== RUN   TestAccIAMRole_description
=== PAUSE TestAccIAMRole_description
=== RUN   TestAccIAMRole_nameGenerated
=== PAUSE TestAccIAMRole_nameGenerated
=== RUN   TestAccIAMRole_namePrefix
=== PAUSE TestAccIAMRole_namePrefix
=== RUN   TestAccIAMRole_testNameChange
=== PAUSE TestAccIAMRole_testNameChange
=== RUN   TestAccIAMRole_badJSON
=== PAUSE TestAccIAMRole_badJSON
=== RUN   TestAccIAMRole_disappears
=== PAUSE …
```
=> iam: Improve diff handling for policies

.changelog/28778.txt, internal/service/servicediscovery/service.go, internal/service/servicediscovery/service_test.go, website/docs/r/service_discovery_service.html.markdown
Adds `type` argument to `resource/aws_service_discovery_service`
Closes [#18401](https://github.com/hashicorp/terraform-provider-aws/issues/18401)
```
$ make testacc TESTS=TestAccServiceDiscoveryService_private PKG=servicediscovery
TF_ACC=1 go test ./internal/service/servicediscovery/... -v -count 1 -parallel 20 -run='TestAccServiceDiscoveryService_private'  -timeout 180m
=== RUN   TestAccServiceDiscoveryService_private
=== PAUSE TestAccServiceDiscoveryService_private
=== RUN   TestAccServiceDiscoveryService_private_http
=== PAUSE TestAccServiceDiscoveryService_private_http
=== CONT  TestAccServiceDiscoveryService_private
=== CONT  TestAccServiceDiscoveryService_private_http
--- PASS: TestAccServiceDiscoveryService_private_http …
```
=> resource/aws_service_discovery_service: Add type argument

.changelog/28789.txt, internal/service/apigateway/rest_api.go, internal/service/apigateway/rest_api_policy.go
```console
% make testacc TESTS=TestAccAPIGatewayRestAPIPolicy_ PKG=apigateway
TF_ACC=1 go test ./internal/service/apigateway/... -v -count 1 -parallel 20 -run='TestAccAPIGatewayRestAPIPolicy_'  -timeout 180m
=== RUN   TestAccAPIGatewayRestAPIPolicy_basic
=== PAUSE TestAccAPIGatewayRestAPIPolicy_basic
=== RUN   TestAccAPIGatewayRestAPIPolicy_disappears
=== PAUSE TestAccAPIGatewayRestAPIPolicy_disappears
=== RUN   TestAccAPIGatewayRestAPIPolicy_Disappears_restAPI
=== PAUSE TestAccAPIGatewayRestAPIPolicy_Disappears_restAPI
=== CONT  TestAccAPIGatewayRestAPIPolicy_basic
=== CONT  TestAccAPIGatewayRestAPIPolicy_Disappears_restAPI
=== CONT  TestAccAPIGatewayRestAPIPolicy_disappears
--- PASS: …
```
=> apigateway/rest_api: Improve diff handling for policies

.changelog/28792.txt, internal/service/cloudsearch/domain_service_access_policy.go
```console
% make testacc TESTS=TestAccCloudSearchDomainServiceAccessPolicy_ PKG=cloudsearch
TF_ACC=1 go test ./internal/service/cloudsearch/... -v -count 1 -parallel 20 -run='TestAccCloudSearchDomainServiceAccessPolicy_'  -timeout 180m
=== RUN   TestAccCloudSearchDomainServiceAccessPolicy_basic
=== PAUSE TestAccCloudSearchDomainServiceAccessPolicy_basic
=== RUN   TestAccCloudSearchDomainServiceAccessPolicy_update
=== PAUSE TestAccCloudSearchDomainServiceAccessPolicy_update
=== CONT  TestAccCloudSearchDomainServiceAccessPolicy_basic
=== CONT  TestAccCloudSearchDomainServiceAccessPolicy_update
--- PASS: TestAccCloudSearchDomainServiceAccessPolicy_basic (2192.16s)
--- PASS: …
```
=> cloudsearch/domain_service_access_policy: Improve diff handling of policy

.changelog/28751.txt, internal/service/redshiftdata/statement.go, internal/service/redshiftdata/statement_test.go, internal/service/redshiftserverless/workgroup.go, website/docs/r/redshiftdata_statement.html.markdown, website/docs/r/redshiftserverless_workgroup.html.markdown
Add support for Redshift serverless by adding `workgroup_name` to `aws_redshiftdata_statement`
Closes [#26346](https://github.com/hashicorp/terraform-provider-aws/issues/26346)
```
make testacc TESTS='TestAccRedshiftDataStatement_workgroup' PKG=redshiftdata
TF_ACC=1 go test ./internal/service/redshiftdata/... -v -count 1 -parallel 20 -run='TestAccRedshiftDataStatement_workgroup'  -timeout 180m
=== RUN   TestAccRedshiftDataStatement_workgroup
=== PAUSE TestAccRedshiftDataStatement_workgroup
=== CONT  TestAccRedshiftDataStatement_workgroup
--- PASS: TestAccRedshiftDataStatement_workgroup (533.57s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/redshiftdata       547.531s
```
=> r/aws_redshiftdata_statement - add `workgroup_name`

.changelog/28794.txt, internal/service/codeartifact/domain_permissions_policy.go, internal/service/codeartifact/repository_permissions_policy.go
```console
% make testacc TESTS="TestAccCodeArtifact_serial/RepositoryPermis" PKG=codeartifact 
TF_ACC=1 go test ./internal/service/codeartifact/... -v -count 1 -parallel 20 -run='TestAccCodeArtifact_serial/RepositoryPermis'  -timeout 180m
=== RUN   TestAccCodeArtifact_serial
=== RUN   TestAccCodeArtifact_serial/RepositoryPermissionsPolicy
=== RUN   TestAccCodeArtifact_serial/RepositoryPermissionsPolicy/disappears
=== RUN   TestAccCodeArtifact_serial/RepositoryPermissionsPolicy/owner
=== RUN   TestAccCodeArtifact_serial/RepositoryPermissionsPolicy/disappearsDomain
=== RUN   TestAccCodeArtifact_serial/RepositoryPermissionsPolicy/ignoreEquivalent
=== RUN   TestAccCodeArtifact_serial/RepositoryPermissionsPolicy/basic …
```
=> codeartifact: Improve diff handling of policies

.changelog/28796.txt, internal/service/codebuild/resource_policy.go
```
% make testacc TESTS=TestAccCodeBuildResourcePolicy_ PKG=codebuild 
TF_ACC=1 go test ./internal/service/codebuild/... -v -count 1 -parallel 20 -run='TestAccCodeBuildResourcePolicy_'  -timeout 180m
=== RUN   TestAccCodeBuildResourcePolicy_basic
=== PAUSE TestAccCodeBuildResourcePolicy_basic
=== RUN   TestAccCodeBuildResourcePolicy_disappears
=== PAUSE TestAccCodeBuildResourcePolicy_disappears
=== RUN   TestAccCodeBuildResourcePolicy_disappears_resource
=== PAUSE TestAccCodeBuildResourcePolicy_disappears_resource
=== CONT  TestAccCodeBuildResourcePolicy_basic
=== CONT  TestAccCodeBuildResourcePolicy_disappears_resource
=== CONT  TestAccCodeBuildResourcePolicy_disappears
--- PASS: …
```
=> codebuild/repository_permissions_policy: Improve policy diffs

.changelog/28798.txt, internal/service/ec2/vpc_endpoint.go, internal/service/ec2/vpc_endpoint_policy.go
Relates #23288
```console
% make testacc TESTS="TestAccVPCEndpoint_|TestAccVPCEndpointPolicy_" PKG=vpc
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 20 -run='TestAccVPCEndpoint_|TestAccVPCEndpointPolicy_'  -timeout 180m
=== RUN   TestAccVPCEndpointPolicy_basic
=== PAUSE TestAccVPCEndpointPolicy_basic
=== RUN   TestAccVPCEndpointPolicy_disappears
=== PAUSE TestAccVPCEndpointPolicy_disappears
=== RUN   TestAccVPCEndpointPolicy_disappears_endpoint
=== PAUSE TestAccVPCEndpointPolicy_disappears_endpoint
=== RUN   TestAccVPCEndpoint_gatewayBasic
=== PAUSE TestAccVPCEndpoint_gatewayBasic
=== RUN   TestAccVPCEndpoint_interfaceBasic
=== PAUSE TestAccVPCEndpoint_interfaceBasic
=== RUN   TestAccVPCEndpoint_disappears
=== …
```
=> vpc/endpoint: Improve diff handling of policy

.changelog/28799.txt, internal/service/ecr/registry_policy.go, internal/service/ecr/repository_policy.go, internal/service/ecrpublic/repository_policy.go
```console
% make testacc TESTS="TestAccECRRepositoryPolicy_|TestAccECRRegistryPolicy_serial" PKG=ecr
TF_ACC=1 go test ./internal/service/ecr/... -v -count 1 -parallel 20 -run='TestAccECRRepositoryPolicy_|TestAccECRRegistryPolicy_serial'  -timeout 180m
=== RUN   TestAccECRRegistryPolicy_serial
=== RUN   TestAccECRRegistryPolicy_serial/basic
=== RUN   TestAccECRRegistryPolicy_serial/disappears
--- PASS: TestAccECRRegistryPolicy_serial (40.78s)
--- PASS: TestAccECRRegistryPolicy_serial/basic (27.52s)
--- PASS: TestAccECRRegistryPolicy_serial/disappears (13.26s)
=== RUN   TestAccECRRepositoryPolicy_basic
=== PAUSE TestAccECRRepositoryPolicy_basic
=== RUN   TestAccECRRepositoryPolicy_IAM_basic
=== PAUSE …
```
=> ecr/policies: Improve diff handling

.changelog/28620.txt, internal/service/apprunner/service.go, internal/service/apprunner/service_test.go, website/docs/r/apprunner_service.html.markdown
Make `observability_configuration_arn` optional
Closes [#27733](https://github.com/hashicorp/terraform-provider-aws/issues/27733)
https://docs.aws.amazon.com/apprunner/latest/api/API_ServiceObservabilityConfiguration.html
```
make testacc TESTS='TestAccAppRunnerService_ImageRepository_observabilityConfiguration' PKG=apprunner
TF_ACC=1 go test ./internal/service/apprunner/... -v -count 1 -parallel 20 -run='TestAccAppRunnerService_ImageRepository_observabilityConfiguration'  -timeout 180m
=== RUN   TestAccAppRunnerService_ImageRepository_observabilityConfiguration
=== PAUSE TestAccAppRunnerService_ImageRepository_observabilityConfiguration
=== CONT  TestAccAppRunnerService_ImageRepository_observabilityConfiguration
--- PASS: …
```
=> aws_apprunner_service observability_configuration_arn optional

.changelog/28802.txt, internal/service/events/bus_policy.go
Relates: #23288 
```console
% make testacc TESTS=TestAccEventsBusPolicy_ PKG=events
TF_ACC=1 go test ./internal/service/events/... -v -count 1 -parallel 20 -run='TestAccEventsBusPolicy_'  -timeout 180m
=== RUN   TestAccEventsBusPolicy_basic
=== PAUSE TestAccEventsBusPolicy_basic
=== RUN   TestAccEventsBusPolicy_ignoreEquivalent
=== PAUSE TestAccEventsBusPolicy_ignoreEquivalent
=== RUN   TestAccEventsBusPolicy_disappears
=== PAUSE TestAccEventsBusPolicy_disappears
=== CONT  TestAccEventsBusPolicy_basic
=== CONT  TestAccEventsBusPolicy_disappears
=== CONT  TestAccEventsBusPolicy_ignoreEquivalent
--- PASS: TestAccEventsBusPolicy_ignoreEquivalent (43.97s)
--- PASS: TestAccEventsBusPolicy_basic (57.68s)
--- PASS: …
```
=> events/bus_policy: Improve diffs

.changelog/28736.txt, internal/service/apprunner/vpc_connector.go, internal/service/apprunner/vpc_connector_test.go
Fixes the bug where `default_tags` from the provider is not handled correctly by `aws_apprunner_vpc_connector`
Closes #28634 
```
❯ make testacc PKG=apprunner TESTS=TestAccAppRunnerVPCConnector
TF_ACC=1 go test ./internal/service/apprunner/... -v -count 1 -parallel 20 -run='TestAccAppRunnerVPCConnector'  -timeout 180m
=== RUN   TestAccAppRunnerVPCConnector_basic
=== PAUSE TestAccAppRunnerVPCConnector_basic
=== RUN   TestAccAppRunnerVPCConnector_disappears
=== PAUSE TestAccAppRunnerVPCConnector_disappears
=== RUN   TestAccAppRunnerVPCConnector_tags
=== PAUSE TestAccAppRunnerVPCConnector_tags
=== RUN   TestAccAppRunnerVPCConnector_defaultTags
=== PAUSE TestAccAppRunnerVPCConnector_defaultTags
=== CONT …
```
=> Fix bug in aws_apprunner_vpc_connector not handling default_tags

.changelog/28804.txt, internal/service/glacier/vault.go, internal/service/glacier/vault_lock.go
```console
% make testacc TESTS="TestAccGlacierVault_|TestAccGlacierVaultLock_" PKG=glacier
TF_ACC=1 go test ./internal/service/glacier/... -v -count 1 -parallel 20 -run='TestAccGlacierVault_|TestAccGlacierVaultLock_'  -timeout 180m
=== RUN   TestAccGlacierVaultLock_basic
=== PAUSE TestAccGlacierVaultLock_basic
=== RUN   TestAccGlacierVaultLock_completeLock
=== PAUSE TestAccGlacierVaultLock_completeLock
=== RUN   TestAccGlacierVaultLock_ignoreEquivalentPolicy
=== PAUSE TestAccGlacierVaultLock_ignoreEquivalentPolicy
=== RUN   TestAccGlacierVault_basic
=== PAUSE TestAccGlacierVault_basic
=== RUN   TestAccGlacierVault_notification
=== PAUSE TestAccGlacierVault_notification
=== RUN   TestAccGlacierVault_policy
=== …
```
=> glacier/vault: Improve policy diffs

.changelog/27565.txt, internal/provider/provider.go, internal/service/sesv2/configuration_set_event_destination.go, internal/service/sesv2/configuration_set_event_destination_test.go, website/docs/r/sesv2_configuration_set_event_destination.html.markdown
This PR introduces the `aws_sesv2_configuration_set_event_destination` resource.
Closes #17570.
https://docs.aws.amazon.com/ses/latest/APIReference-V2/Welcome.html
```
$ make testacc TESTARGS="-run=TestAccSESV2ConfigurationSetEventDestination_" PKG=sesv2 ACCTEST_PARALLELISM=2
TF_ACC=1 go test ./internal/service/sesv2/... -v -count 1 -parallel 2  -run=TestAccSESV2ConfigurationSetEventDestination_ -timeout 180m
=== RUN   TestAccSESV2ConfigurationSetEventDestination_basic
=== PAUSE TestAccSESV2ConfigurationSetEventDestination_basic
=== RUN   TestAccSESV2ConfigurationSetEventDestination_cloudWatchDestination
=== PAUSE TestAccSESV2ConfigurationSetEventDestination_cloudWatchDestination
=== RUN …
```
=> r/aws_sesv2_configuration_set_event_destination: new resource

internal/flex/framework.go, internal/flex/framework_test.go, internal/framework/base.go, internal/service/auditmanager/assessment.go, internal/service/auditmanager/control.go, internal/service/auditmanager/framework.go, internal/service/ec2/vpc_security_group_ingress_rule.go, internal/service/globalaccelerator/accelerator_data_source.go, internal/service/meta/default_tags_data_source.go, internal/service/meta/ip_ranges_data_source.go, internal/service/meta/regions_data_source.go, internal/service/resourceexplorer2/index.go
Several updates and additions to the `flex` package's framework specific helper functions, including:
- Add flatten functions for string list/set/map objects that return null values for nil and empty inputs
- Rename flatten functions for string list/set/map objects that return empty values for nil inputs with the `Legacy` suffix adopted by the value conversion helpers
- Add string list expander functions
- Extend various test cases
The non-legacy flatteners will allow omitted list/set attributes to be set as null for net-new resources, while the legacy versions preserve the empty list/set/map return behavior where needed (tags, refactored resources/data sources, etc.). 
```console
$ go test -count=1 ./internal/flex/...
ok      github.com/hashicorp/terraform-provider-aws/internal/flex …
```
=> `flex` framework flattener/expander updates

.changelog/28837.txt, internal/service/mq/configuration.go
Closes #21619
Relates #23288
```console
% make testacc TESTS=TestAccMQConfiguration_ PKG=mq
TF_ACC=1 go test ./internal/service/mq/... -v -count 1 -parallel 20 -run='TestAccMQConfiguration_'  -timeout 180m
=== RUN   TestAccMQConfiguration_basic
=== PAUSE TestAccMQConfiguration_basic
=== RUN   TestAccMQConfiguration_withData
=== PAUSE TestAccMQConfiguration_withData
=== RUN   TestAccMQConfiguration_withLdapData
=== PAUSE TestAccMQConfiguration_withLdapData
=== RUN   TestAccMQConfiguration_tags
=== PAUSE TestAccMQConfiguration_tags
=== CONT  TestAccMQConfiguration_basic
=== CONT  TestAccMQConfiguration_withLdapData
=== CONT  TestAccMQConfiguration_withData
=== CONT  TestAccMQConfiguration_tags
--- PASS: …
```
=> mq/configuration: Improve diff handling of data

.changelog/28838.txt, internal/service/iot/policy.go
Relates #23288
```console
% make testacc TESTS=TestAccIoTPolicy_ PKG=iot
TF_ACC=1 go test ./internal/service/iot/... -v -count 1 -parallel 20 -run='TestAccIoTPolicy_'  -timeout 180m
=== RUN   TestAccIoTPolicy_basic
=== PAUSE TestAccIoTPolicy_basic
=== RUN   TestAccIoTPolicy_disappears
=== PAUSE TestAccIoTPolicy_disappears
=== CONT  TestAccIoTPolicy_basic
=== CONT  TestAccIoTPolicy_disappears
--- PASS: TestAccIoTPolicy_disappears (12.54s)
--- PASS: TestAccIoTPolicy_basic (16.96s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/iot	18.694s
```
=> iot/policy: Improve diffs of policy

.changelog/26977.txt, internal/service/elbv2/find.go, internal/service/elbv2/target_group.go, internal/service/elbv2/target_group_test.go
When creating a target group check that a target group with the same name does not already exist.
The [create target group API](https://docs.aws.amazon.com/elasticloadbalancing/latest/APIReference/API_CreateTargetGroup.html) is idempotent
> This operation is idempotent, which means that it completes at most one time. If you attempt to create multiple target groups with the same settings, each call succeeds.
As a result if we create 2 target groups with the same configuration Terraform will associate all the other identical target
groups with original's ARN.
We will now call the [describe target group](https://docs.aws.amazon.com/elasticloadbalancing/latest/APIReference/API_DescribeTargetGroups.html) API before creating a new target group with the name of the target group we are about to …
=> r/aws_lb_target_group - check no target group with the same name exists

.changelog/28836.txt, internal/service/iam/group_policy.go, internal/service/iam/group_policy_test.go, internal/service/iam/policy.go, internal/service/iam/policy_test.go, internal/service/iam/role.go, internal/service/iam/role_policy.go, internal/service/iam/role_test.go, internal/service/iam/user_policy.go, internal/service/iam/user_policy_test.go, internal/verify/json.go, internal/verify/json_test.go
Based on new changes and improvements, I haven't been able to reproduce the problems noted in #28833 and #28835. I've added acceptance tests specifically to test the examples given that are now passing.
In #23288, I am not able to reproduce the issues noted there. For anything that I'm not addressing, I created new issues.
Closes #28833
Closes #28835
Closes #23288
```console
% make testacc TESTS=TestAccIAMGroupPolicy_ PKG=iam
TF_ACC=1 go test ./internal/service/iam/... -v -count 1 -parallel 20 -run='TestAccIAMGroupPolicy_'  -timeout 180m
=== RUN   TestAccIAMGroupPolicy_basic
=== PAUSE TestAccIAMGroupPolicy_basic
=== RUN   TestAccIAMGroupPolicy_disappears
=== PAUSE TestAccIAMGroupPolicy_disappears
=== RUN …
```
=> iam: Improve policy diff handling

.changelog/28853.txt, internal/service/kms/external_key.go, internal/service/kms/key.go
Relates #23288
```console
% TF_ACC=1 go test ./internal/service/kms/... -v -count 1 -parallel 3 -run='TestAccKMSExternalKey_|TestAccKMSKey_'  -timeout 180m
=== RUN   TestAccKMSExternalKey_basic
=== PAUSE TestAccKMSExternalKey_basic
=== RUN   TestAccKMSExternalKey_disappears
=== PAUSE TestAccKMSExternalKey_disappears
=== RUN   TestAccKMSExternalKey_multiRegion
=== PAUSE TestAccKMSExternalKey_multiRegion
=== RUN   TestAccKMSExternalKey_deletionWindowInDays
=== PAUSE TestAccKMSExternalKey_deletionWindowInDays
=== RUN   TestAccKMSExternalKey_description
=== PAUSE TestAccKMSExternalKey_description
=== RUN   TestAccKMSExternalKey_enabled
=== PAUSE TestAccKMSExternalKey_enabled
=== RUN   TestAccKMSExternalKey_keyMaterialBase64
=== PAUSE TestAccKMSExternalKey_keyMaterialBase64
=== RUN …
```
=> kms: Improve diffs for policies

.changelog/28855.txt, internal/service/s3/bucket.go, internal/service/s3/bucket_policy.go, internal/service/s3/bucket_test.go
Closes #18878
Closes #22030
Closes #24338
Errors unrelated to these changes.
```console
% TF_ACC=1 go test ./internal/service/s3/... -v -count 1 -parallel 3 -run='TestAccS3BucketPolicy_|TestAccS3Bucket_'  -timeout 180m
TF_ACC=1 go test ./internal/service/kms/... -v -count 1 -parallel 3 -run='TestAccKMSExternalKey_|TestAccKMSKey_'  -timeout 180m=== RUN   TestAccS3BucketPolicy_basic
=== PAUSE TestAccS3BucketPolicy_basic
=== RUN   TestAccS3BucketPolicy_disappears
=== PAUSE TestAccS3BucketPolicy_disappears
=== RUN   TestAccS3BucketPolicy_disappears_bucket
=== PAUSE TestAccS3BucketPolicy_disappears_bucket
=== RUN   TestAccS3BucketPolicy_policyUpdate
=== PAUSE TestAccS3BucketPolicy_policyUpdate
=== RUN   TestAccS3BucketPolicy_IAMRoleOrder_policyDoc
=== PAUSE …
```
=> s3/bucket policy: Improve diffs with policies

.changelog/28861.txt, internal/service/ses/identity_policy.go
Relates #23288
```console
% make testacc TESTS=TestAccSESIdentityPolicy_ PKG=ses
TF_ACC=1 go test ./internal/service/ses/... -v -count 1 -parallel 20 -run='TestAccSESIdentityPolicy_'  -timeout 180m
=== RUN   TestAccSESIdentityPolicy_basic
=== PAUSE TestAccSESIdentityPolicy_basic
=== RUN   TestAccSESIdentityPolicy_Identity_email
=== PAUSE TestAccSESIdentityPolicy_Identity_email
=== RUN   TestAccSESIdentityPolicy_policy
=== PAUSE TestAccSESIdentityPolicy_policy
=== RUN   TestAccSESIdentityPolicy_ignoreEquivalent
=== PAUSE TestAccSESIdentityPolicy_ignoreEquivalent
=== CONT  TestAccSESIdentityPolicy_basic
=== CONT  TestAccSESIdentityPolicy_ignoreEquivalent
=== CONT  TestAccSESIdentityPolicy_Identity_email
=== CONT …
```
=> ses: Improve diffs for policies

.changelog/28863.txt, internal/service/secretsmanager/secret.go, internal/service/secretsmanager/secret_policy.go
Relates #23288
```console
% make testacc TESTS="TestAccSecretsManagerSecret_|TestAccSecretsManagerSecretPolicy_" PKG=secretsmanager
TF_ACC=1 go test ./internal/service/secretsmanager/... -v -count 1 -parallel 20 -run='TestAccSecretsManagerSecret_|TestAccSecretsManagerSecretPolicy_'  -timeout 180m
=== RUN   TestAccSecretsManagerSecretPolicy_basic
=== PAUSE TestAccSecretsManagerSecretPolicy_basic
=== RUN   TestAccSecretsManagerSecretPolicy_blockPublicPolicy
=== PAUSE TestAccSecretsManagerSecretPolicy_blockPublicPolicy
=== RUN   TestAccSecretsManagerSecretPolicy_disappears
=== PAUSE TestAccSecretsManagerSecretPolicy_disappears
=== RUN   TestAccSecretsManagerSecret_basic
=== PAUSE TestAccSecretsManagerSecret_basic
=== RUN …
```
=> secretsmanager: Improve diffs with policies

.changelog/28865.txt, internal/service/sagemaker/model_package_group_policy.go
#23288
```console
% make testacc TESTS=TestAccSageMakerModelPackageGroupPolicy_ PKG=sagemaker 
TF_ACC=1 go test ./internal/service/sagemaker/... -v -count 1 -parallel 20 -run='TestAccSageMakerModelPackageGroupPolicy_'  -timeout 180m
=== RUN   TestAccSageMakerModelPackageGroupPolicy_basic
=== PAUSE TestAccSageMakerModelPackageGroupPolicy_basic
=== RUN   TestAccSageMakerModelPackageGroupPolicy_disappears
=== PAUSE TestAccSageMakerModelPackageGroupPolicy_disappears
=== RUN   TestAccSageMakerModelPackageGroupPolicy_Disappears_modelPackageGroup
=== PAUSE TestAccSageMakerModelPackageGroupPolicy_Disappears_modelPackageGroup
=== CONT  TestAccSageMakerModelPackageGroupPolicy_basic
=== CONT …
```
=> sagemaker/model_package_group_policy: Improve policy diffs

.changelog/28866.txt, internal/service/s3control/access_point.go, internal/service/s3control/access_point_policy.go, internal/service/s3control/bucket_policy.go, internal/service/s3control/multi_region_access_point_policy.go, internal/service/s3control/object_lambda_access_point_policy.go
Relates #23288
```console
% make testacc TESTS="TestAccS3ControlAccessPoint_|TestAccS3ControlAccessPointPolicy_|TestAccS3ControlBucketPolicy_|TestAccS3ControlMultiRegionAccessPointPolicy_|TestAccS3ControlObjectLambdaAccessPointPolicy_" PKG=s3control
TF_ACC=1 go test ./internal/service/s3control/... -v -count 1 -parallel 20 -run='TestAccS3ControlAccessPoint_|TestAccS3ControlAccessPointPolicy_|TestAccS3ControlBucketPolicy_|TestAccS3ControlMultiRegionAccessPointPolicy_|TestAccS3ControlObjectLambdaAccessPointPolicy_'  -timeout 180m
=== RUN   TestAccS3ControlAccessPointPolicy_basic
=== PAUSE TestAccS3ControlAccessPointPolicy_basic
=== RUN   TestAccS3ControlAccessPointPolicy_disappears
=== PAUSE …
```
=> s3control: Improve policy diffs

.changelog/28868.txt, internal/service/iam/group_policy_test.go, internal/service/iam/role_policy.go, internal/service/iam/role_policy_test.go, internal/verify/json.go, internal/verify/json_test.go
Relates #23288
```console
% make testacc TESTS="TestAccIAMRolePolicy_|TestAccIAMGroupPolicy_|TestAccIAMRole_InlinePolicy|TestAccIAMUserPolicy_" PKG=iam
TF_ACC=1 go test ./internal/service/iam/... -v -count 1 -parallel 20 -run='TestAccIAMRolePolicy_|TestAccIAMGroupPolicy_|TestAccIAMRole_InlinePolicy|TestAccIAMUserPolicy_'  -timeout 180m
=== RUN   TestAccIAMGroupPolicy_basic
=== PAUSE TestAccIAMGroupPolicy_basic
=== RUN   TestAccIAMGroupPolicy_disappears
=== PAUSE TestAccIAMGroupPolicy_disappears
=== RUN   TestAccIAMGroupPolicy_namePrefix
=== PAUSE TestAccIAMGroupPolicy_namePrefix
=== RUN   TestAccIAMGroupPolicy_generatedName
=== PAUSE TestAccIAMGroupPolicy_generatedName
=== RUN   TestAccIAMGroupPolicy_unknownsInPolicy
=== PAUSE …
```
=> iam: Provider produced inconsistent final plan

.ci/semgrep/acctest/naming/naming.yml, internal/service/appsync/datasource_test.go, internal/service/cloudformation/stack_test.go, internal/service/cloudtrail/cloudtrail_test.go, internal/service/emr/cluster_test.go, internal/service/redshift/cluster_test.go
Updates check to catch names such as
* `testAccCheckDestroy`
* `testAccCheckDestroy<Resource>`
=> Updates check for acctest check destroy function naming

.github/workflows/release.yml
This input is passed through to actions/setup-go's go-version-file input, similar to what is used in other workflows.
N/A
Reference: https://github.com/hashicorp/ghaction-terraform-provider-release/releases/tag/v2.2.0
Reference: https://github.com/hashicorp/ghaction-terraform-provider-release/blob/7e53d9adb57f05cb16c227ef0bfd030060fae82e/.github/workflows/hashicorp.yml#L26-L29
```
...
```
=> .github/workflows: Use hashicorp/ghaction-terraform-provider-release setup-go-version-file input

.changelog/28862.txt, internal/service/opensearch/domain.go, internal/service/opensearch/domain_test.go, internal/service/opensearch/flex.go
This fix prevents the `Throughput` and `Iops` EBS options from being included in the input struct when the specified volume type does not support them. 
Specifically, this can happen when a configuration uses a `gp3` volume type without specifying `iops` or `throughput`, then the volume type changes to a type that doesn't support these arguments. On the first apply, the default values set by AWS are written to state. On the subsequent apply these should be omitted from the UpdateDomain request input to avoid a `ValidationException`.
Closes #27467
https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/opensearch@v1.12.0/types#EBSOptions
```console
$ make testacc PKG=opensearch TESTS=TestAccOpenSearchDomain_VolumeType
TF_ACC=1 go …
```
=> `aws_opensearch_domain`: Omit IOPS/Throughput when not supported

website/docs/r/cloudwatch_event_target.html.markdown
Per AWS documentation the only valid value for propagate_tags in this context is `TASK_DEFINITION`: https://docs.aws.amazon.com/scheduler/latest/APIReference/API_EcsParameters.html
This PR modifies documentation only.
=> Correct documentation on ecs_target propagate_tags property

.ci/.semgrep.yml, GNUmakefile, internal/service/apigateway/authorizer.go, internal/service/autoscaling/policy.go, internal/service/autoscaling/schedule.go, internal/service/cloudwatch/metric_alarm.go, internal/service/cognitoidp/user_pool.go, internal/service/directconnect/router_configuration_data_source.go, internal/service/ec2/ec2_instance.go, internal/service/ec2/ec2_instance_data_source.go, internal/service/ec2/ec2_spot_fleet_request.go, internal/service/ec2/ipam_pool_cidr_allocation.go, internal/service/elasticache/replication_group.go, internal/service/fsx/ontap_file_system.go, internal/service/fsx/openzfs_file_system.go, internal/service/grafana/workspace_saml_configuration.go, internal/service/lexmodels/bot.go, internal/service/opsworks/stack.go, internal/service/rds/cluster.go, internal/service/rds/cluster_data_source.go, internal/service/s3/bucket_object.go, internal/service/s3/bucket_object_data_source.go, internal/service/s3/object_copy.go, internal/service/shield/protection_group.go
* fix semgrep rule to scan the correct directory
* fix semgrep invocation to avoid deprecation warning
* fix or ignore new semgrep check
Closes #15893
```
...
```
=> Remove extraneous nil checks before d.Set()

.changelog/28905.txt, internal/service/imagebuilder/component.go, internal/service/imagebuilder/component_test.go, website/docs/r/imagebuilder_component.html.markdown
This PR adds the `skip_destroy` argument to the `aws_imagebuilder_component`. This allows creating the new component versions without removing the current one and affecting all resources relying on it.
Followed the approach of [`aws_ecs_task_definition`](https://github.com/hashicorp/terraform-provider-aws/blob/b898284784188426501ddf646cc30dbdc9b42979/internal/service/ecs/task_definition.go#L251-L255) and [`aws_lambda_layer_version`](https://github.com/hashicorp/terraform-provider-aws/blob/b898284784188426501ddf646cc30dbdc9b42979/internal/service/lambda/layer_version.go#L114-L119) facing similar problems.
Closes #26117.
```
$ make testacc TESTARGS="-run=TestAccImageBuilderComponent_" PKG=imagebuilder ACCTEST_PARALLELISM=2
TF_ACC=1 …
```
=> r/aws_imagebuilder_component  - add skip_destroy argument

.changelog/28901.txt, internal/service/elasticsearch/domain.go, internal/service/elasticsearch/domain_test.go
Marks the `aws_elasticsearch_domain` `ebs_options.iops` attribute as computed to prevent persistent diffs. This schema change brings the `ebs_options` definition into alignment with the `aws_opensearch_domain` resource.
Closes #28895
Relates #27510 
```console
$ make testacc PKG=elasticsearch TESTS=TestAccElasticsearchDomain_VolumeType
TF_ACC=1 go test ./internal/service/elasticsearch/... -v -count 1 -parallel 20 -run='TestAccElasticsearchDomain_VolumeType'  -timeout 180m
=== RUN   TestAccElasticsearchDomain_VolumeType_update
=== PAUSE TestAccElasticsearchDomain_VolumeType_update
=== RUN   TestAccElasticsearchDomain_VolumeType_missing
=== PAUSE TestAccElasticsearchDomain_VolumeType_missing
=== CONT …
```
=> `aws_elasticsearch_domain`: Fix persistent IOPS diff

internal/service/datasync/location_object_storage.go
Fixes https://github.com/hashicorp/terraform-provider-aws/actions/runs/3942502778/jobs/6746234053:
```
Findings:
internal/service/datasync/location_object_storage.go 
ci.bare-error-returns
API errors should be wrapped with the CRUD info
165┆ return err
⋮┆----------------------------------------
181┆ return err
```
Relates https://github.com/hashicorp/terraform-provider-aws/pull/23154.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/28894.
=> Fix semgrep `ci.bare-error-returns`

.changelog/28937.txt, internal/service/identitystore/group.go, internal/service/identitystore/group_data_source.go, internal/service/identitystore/group_test.go, internal/service/identitystore/user.go, internal/service/identitystore/user_data_source.go, internal/service/identitystore/user_test.go
Restores use of the `ListGroups` and `ListUsers` APIs when `filter` is specified with the `aws_identitystore_group` and `aws_identitystore_user` data sources.
Closes https://github.com/hashicorp/terraform-provider-aws/issues/28139.
Closes https://github.com/hashicorp/terraform-provider-aws/issues/27830.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/27762.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/27053.
```console
% make testacc TESTARGS='-run=TestAccIdentityStoreUserDataSource_' PKG=identitystore ACCTEST_PARALLELISM=3
TF_ACC=1 go test ./internal/service/identitystore/... -v -count 1 -parallel 3  -run=TestAccIdentityStoreUserDataSource_ -timeout 180m
=== RUN …
```
=> d/aws_identitystore_(group|user): Restore use of `List` API calls when `filter` is specified

website/docs/r/cur_report_definition.html.markdown
This PR updates the description of `aws_cur_report_defintion.time_unit` to include `MONTHLY` as a valid value.
Closes #28910
- [Resource Schema](https://github.com/hashicorp/terraform-provider-aws/blob/12d15d99c627e7243273eb6dc4495355d098677e/internal/service/cur/report_definition.go#L41-L46)
- [`cur.TimeUnit_Values()` definition](https://github.com/aws/aws-sdk-go/blob/d56fdbd838aaa42cbceb7acaeaeb3d7581c0e1c2/service/costandusagereportservice/api.go#L1404-L1411)
N/a, docs
=> Update valid values for `aws_cur_report_definition.time_unit`

.changelog/28573.txt, internal/service/ce/anomaly_subscription.go, internal/service/ce/anomaly_subscription_test.go, website/docs/r/ce_anomaly_subscription.html.markdown
Closes #28571
```
$ make testacc TESTS=TestAccCEAnomalySubscription_ PKG=ce
--- PASS: TestAccCEAnomalySubscription_disappears (26.03s)
--- PASS: TestAccCEAnomalySubscription_basic (29.81s)
--- PASS: TestAccCEAnomalySubscription_thresholdExpression (30.07s)
--- PASS: TestAccCEAnomalySubscription_Frequency (46.56s)
--- PASS: TestAccCEAnomalySubscription_Threshold (48.53s)
--- PASS: TestAccCEAnomalySubscription_MonitorARNList (49.49s)
--- PASS: TestAccCEAnomalySubscription_Tags (64.24s)
--- PASS: TestAccCEAnomalySubscription_Subscriber (92.84s)
```
=> r/ce_anomaly_subscripton - add `threshold_expression` and deprecate `threshold`

.changelog/28431.txt, internal/service/rum/app_monitor.go, internal/service/rum/app_monitor_test.go, website/docs/r/rum_app_monitor.html.markdown
```
$ make testacc TESTS=TestAccRUMAppMonitor_ PKG=rum
--- PASS: TestAccRUMAppMonitor_disappears (20.41s)
--- PASS: TestAccRUMAppMonitor_basic (43.97s)
--- PASS: TestAccRUMAppMonitor_tags (62.20s)
--- PASS: TestAccRUMAppMonitor_customEvents (62.36s)
```
=> r/rum_app_monitor - add `custom_events`

.changelog/28967.txt, internal/service/auditmanager/control_data_source.go, internal/service/auditmanager/control_data_source_test.go, website/docs/d/auditmanager_control.html.markdown
`aws_auditmanager_control` will allow practitioners to utilize `Standard` (AWS-managed) controls as inputs to other resources, such as Assessment Frameworks.
Relates #17981
```console
$ make testacc PKG=auditmanager TESTS=TestAccAuditManagerControlDataSource_
TF_ACC=1 go test ./internal/service/auditmanager/... -v -count 1 -parallel 20 -run='TestAccAuditManagerControlDataSource_'  -timeout 180m
=== RUN   TestAccAuditManagerControlDataSource_standard
=== PAUSE TestAccAuditManagerControlDataSource_standard
=== RUN   TestAccAuditManagerControlDataSource_custom
=== PAUSE TestAccAuditManagerControlDataSource_custom
=== CONT  TestAccAuditManagerControlDataSource_standard
=== CONT  TestAccAuditManagerControlDataSource_custom
--- PASS: …
```
=> New Data Source: `aws_auditmanager_control`

.changelog/28968.txt, internal/service/elbv2/listener_certificate.go, internal/service/iam/server_certificate.go
* `aws_lb_listener_certificate` - Fix logic error where all errors during read would end up in remove from state branch rather than giving error. This causes problems when there are actual errors like not having the correct permissions. This is never visible except in log.
* `aws_iam_server_certificate` - Delete was returning an error no matter what, in many cases, rather than checking to see if there were an error to return `nil`.
Closes #8751
```console
% make testacc TESTS=TestAccELBV2ListenerCertificate_ PKG=elbv2
TF_ACC=1 go test ./internal/service/elbv2/... -v -count 1 -parallel 20 -run='TestAccELBV2ListenerCertificate_'  -timeout 180m
=== RUN   TestAccELBV2ListenerCertificate_basic
=== PAUSE …
```
=> elbv2/listener_certificate: Display errors on read

website/docs/r/redshiftserverless_workgroup.html.markdown
This PR updates the `aws_redshiftserverless_workgroup` resource's `subnet_ids` argument description to provide a bit more clarity on the requirements (and link out to the associated AWS doc)
Closes #28977
- [AWS doc](https://docs.aws.amazon.com/redshift/latest/mgmt/serverless-known-issues.html)
N/a, docs
=> Update aws_redshiftserverless_workgroup.subnet_ids to reflect requirements

.changelog/29018.txt, docs/acc-test-environment-variables.md, internal/service/auditmanager/exports_test.go, internal/service/auditmanager/organization_admin_account_registration.go, internal/service/auditmanager/organization_admin_account_registration_test.go, website/docs/r/auditmanager_organization_admin_account_registration.html.markdown
The `aws_auditmanager_organization_admin_account_registration` resource will allow practitioners to manage their organizations assigned AuditManager admin account via terraform.
Relates #17981 
> Note: Testing must be done in an account under an organization with at least two accounts so the `AUDITMANAGER_ORGANIZATION_ADMIN_ACCOUNT_ID` can be set.
```console
$ AUDITMANAGER_ORGANIZATION_ADMIN_ACCOUNT_ID=012345678901 make testacc PKG=auditmanager TESTS=TestAccAuditManagerOrganizationAdminAccountRegistration_
TF_ACC=1 go test ./internal/service/auditmanager/... -v -count 1 -parallel 20 -run='TestAccAuditManagerOrganizationAdminAccountRegistration_'  -timeout 180m
=== RUN   TestAccAuditManagerOrganizationAdminAccountRegistration_serial …
```
=> New Resource: `aws_auditmanager_organization_admin_account_registration`

website/docs/r/ami.html.markdown
This parameter isn't valid when creating an AMI. See https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_EbsBlockDevice.html.
Looks to have been a simple copy-pasteo from `aws_ami_copy`.
Closes #29027
* https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_EbsBlockDevice.html
> KmsKeyId (request), kmsKeyId (response)
>
>    Identifier (key ID, key alias, ID ARN, or alias ARN) for a customer managed CMK under which the EBS volume is encrypted.
>
>    This parameter is only supported on BlockDeviceMapping objects called by [RunInstances](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_RunInstances.html), [RequestSpotFleet](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_RequestSpotFleet.html), and [RequestSpotInstances](https://docs.aws.amazon.com/AWSEC2/lat …
=> r/aws_ami: Remove `kms_key_id` from docs

.ci/semgrep/migrate/context.yml, docs/running-and-writing-acceptance-tests.md, internal/service/dms/event_subscription_test.go, internal/service/dynamodb/sweep.go, internal/service/ssoadmin/sweep.go, internal/service/waf/sweep.go, internal/sweep/sweep.go
A few sweepers made direct calls to `schema.Resource`'s `Read` function. After the `Context` migration, the legacy CRUD functions are `nil`, so those sweepers panicked.
Closes https://github.com/hashicorp/terraform-provider-aws/issues/28556.
=> Fixes sweepers after `Context` migration

.changelog/29051.txt, internal/service/medialive/channel_encoder_settings_schema.go, internal/service/medialive/channel_test.go, internal/service/medialive/input.go
Closes #28970
```console
make testacc TESTARGS='-run=TestAccMediaLiveChannel_' PKG=medialive
TF_ACC=1 go test ./internal/service/medialive/... -v -count 1 -parallel 20  -run=TestAccMediaLiveChannel_ -timeout 180m
--- PASS: TestAccMediaLiveChannel_disappears (65.80s)
--- PASS: TestAccMediaLiveChannel_audioDescriptions_codecSettings (66.77s)
--- PASS: TestAccMediaLiveChannel_basic (74.44s)
--- PASS: TestAccMediaLiveChannel_hls (83.42s)
--- PASS: TestAccMediaLiveChannel_updateTags (95.51s)
--- PASS: TestAccMediaLiveChannel_update (117.68s)
--- PASS: TestAccMediaLiveChannel_status (255.92s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/medialive	258.930s
...
```
=> Bug:  add `rate_control_mode` attribute to `aws_medialive_channel`

.changelog/29049.txt, internal/service/auditmanager/exports_test.go, internal/service/auditmanager/framework_share.go, internal/service/auditmanager/framework_share_test.go, website/docs/r/auditmanager_framework_share.html.markdown
`aws_auditmanager_framework_share` will allow practitioners to share assessment frameworks across accounts and regions via terraform.
Relates #17981
```console
$ make testacc PKG=auditmanager TESTS=TestAccAuditManagerFrameworkShare_
TF_ACC=1 go test ./internal/service/auditmanager/... -v -count 1 -parallel 20 -run='TestAccAuditManagerFrameworkShare_'  -timeout 180m
=== RUN   TestAccAuditManagerFrameworkShare_basic
=== PAUSE TestAccAuditManagerFrameworkShare_basic
=== RUN   TestAccAuditManagerFrameworkShare_disappears
=== PAUSE TestAccAuditManagerFrameworkShare_disappears
=== RUN   TestAccAuditManagerFrameworkShare_optional
=== PAUSE TestAccAuditManagerFrameworkShare_optional
=== CONT  TestAccAuditManagerFrameworkShare_basic
=== …
```
=> New Resource: `aws_auditmanager_framework_share`

.changelog/29082.txt, internal/service/wafv2/flex.go, internal/service/wafv2/schemas.go, internal/service/wafv2/web_acl_test.go, website/docs/r/wafv2_web_acl.html.markdown
Closes #25545
* #26506
* https://github.com/hashicorp/terraform-provider-aws/pull/26506#issuecomment-1265928974
```console
% make testacc TESTS=TestAccWAFV2WebACL_ByteMatchStatement_body PKG=wafv2
TF_ACC=1 go test ./internal/service/wafv2/... -v -count 1 -parallel 20 -run='TestAccWAFV2WebACL_ByteMatchStatement_body'  -timeout 180m
=== RUN   TestAccWAFV2WebACL_ByteMatchStatement_body
=== PAUSE TestAccWAFV2WebACL_ByteMatchStatement_body
=== CONT  TestAccWAFV2WebACL_ByteMatchStatement_body
--- PASS: TestAccWAFV2WebACL_ByteMatchStatement_body (42.59s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/wafv2	44.256s
```
=> wafv2/web_acl: Rule add body oversize_handling

.changelog/29086.txt, internal/service/dynamodb/wait.go
Closes #24903
```console
% TF_ACC=1 go test ./internal/service/dynamodb/... -v -count 1 -parallel 4 -run='TestAccDynamoDBTable_'  -timeout 180m
=== RUN   TestAccDynamoDBTable_basic
=== PAUSE TestAccDynamoDBTable_basic
=== RUN   TestAccDynamoDBTable_disappears
=== PAUSE TestAccDynamoDBTable_disappears
=== RUN   TestAccDynamoDBTable_Disappears_payPerRequestWithGSI
=== PAUSE TestAccDynamoDBTable_Disappears_payPerRequestWithGSI
=== RUN   TestAccDynamoDBTable_extended
=== PAUSE TestAccDynamoDBTable_extended
=== RUN   TestAccDynamoDBTable_enablePITR
=== PAUSE TestAccDynamoDBTable_enablePITR
=== RUN   TestAccDynamoDBTable_BillingMode_payPerRequestToProvisioned
=== PAUSE TestAccDynamoDBTable_BillingMode_payPerRequestToProvisioned
=== RUN …
```
=> dynamodb/table: error updating PITR, unexpected state

.changelog/29099.txt, internal/service/auditmanager/assessment_delegation.go, internal/service/auditmanager/assessment_delegation_test.go, internal/service/auditmanager/exports_test.go, website/docs/r/auditmanager_assessment_delegation.html.markdown
`aws_auditmanager_assessment_delegation` will allow practitioners to manage AuditManager assessment delegations via terraform.
Relates #17981
- [BatchCreateDelegationByAssessment](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/auditmanager@v1.20.11#Client.BatchCreateDelegationByAssessment)
- [BatchDeleteDelegationByAssessment](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/auditmanager@v1.20.11#Client.BatchDeleteDelegationByAssessment)
- [GetDelegations](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/auditmanager@v1.20.11#Client.GetDelegations)
```
$ make testacc PKG=auditmanager TESTS=TestAccAuditManagerAssessmentDelegation_
TF_ACC=1 go test ./internal/service/auditmanager/... -v -count 1 -parallel 20 …
```
=> New Resource: `aws_auditmanager_assessment_delegation`

.changelog/29102.txt, internal/service/dynamodb/table.go, internal/service/dynamodb/table_replica.go, internal/service/dynamodb/table_replica_test.go, internal/service/dynamodb/table_test.go, internal/service/kms/find.go, website/docs/r/dynamodb_table.html.markdown, website/docs/r/dynamodb_table_replica.html.markdown
* `aws_dynamodb_table_replica`: Fix to allow creation of the replica without errors when `kms_key_arn` is set
* `aws_dynamodb_table_replica`: Fix to allow updating of `kms_key_arn`
* `aws_dynamodb_table_replica`: Updating `kms_key_arn` forces replacement of the replica now as required to re-encrypt the replica
* `aws_dynamodb_table`: Fix to allow updating of `replica.*.kms_key_arn`
* `aws_dynamodb_table`: Fix to allow updating of `replica.*.point_in_time_recovery` when a `replica` has `kms_key_arn` set
* `aws_dynamodb_table`: Updating `replica.*.kms_key_arn` or `replica.*.point_in_time_recovery`, when the `replica`'s `kms_key_arn` is set, requires recreating the replica.
The error message `ValidationException: One or more parameter values were invalid: KMSMasterKeyId must be specified for …
=> dynamodb/table_replica: Fix creation error when KMS

website/docs/r/config_configuration_recorder_status.html.markdown
This PR updates the example in the `aws_config_configuration_recorder_status` documentation to replace the deprecated `AWSConfigRole` managed policy with the new `AWS_ConfigRole`.
Closes #28904
- [Announcement of deprecation](https://aws.amazon.com/blogs/mt/service-notice-upcoming-changes-required-for-aws-config/)
- [Managed policy docs](https://docs.aws.amazon.com/config/latest/developerguide/security-iam-awsmanpol.html#security-iam-awsmanpol-AWS_ConfigRole)
N/a, docs
=> Replace deprecated AWSConfigRole with AWS_ConfigRole

internal/service/auditmanager/sweep.go, internal/sweep/framework.go
Adds the ability to specify additional (non-ID) attributes during creation of plugin-framework resource sweepers. This allows for cases where multiple attributes are required to perform deletion.
Also adds additional AuditManager sweepers.
```console
$ SWEEPARGS=-sweep-run=aws_auditmanager_assessment_report make sweep
go test ./internal/sweep -v -tags=sweep -sweep=us-west-2,us-east-1,us-east-2 -sweep-run=aws_auditmanager_assessment_report -timeout 60m
2023/01/26 21:05:12 [DEBUG] Running Sweepers for region (us-west-2):
2023/01/26 21:05:12 [DEBUG] Running Sweeper (aws_auditmanager_assessment_report) in region (us-west-2)
2023/01/26 21:05:12 [INFO] Retrieved credentials from "SharedConfigCredentials: …
```
=> Sweepers: Support supplemental framework attributes

internal/service/configservice/config_rule_test.go, internal/service/configservice/conformance_pack_test.go, internal/service/configservice/organization_conformance_pack_test.go, internal/service/configservice/organization_custom_rule_test.go, internal/service/configservice/organization_managed_rule_test.go
Replaces the deprecated AWS-managed `AWSConfigRole` in acceptance tests.
Closes #29129
Relates #28938
- [Announcement of deprecation](https://aws.amazon.com/blogs/mt/service-notice-upcoming-changes-required-for-aws-config/)
- [Managed policy docs](https://docs.aws.amazon.com/config/latest/developerguide/security-iam-awsmanpol.html#security-iam-awsmanpol-AWS_ConfigRole)
```console
$ make testacc PKG=configservice TESTS=TestAccConfigService_serial
TF_ACC=1 go test ./internal/service/configservice/... -v -count 1 -parallel 20 -run='TestAccConfigService_serial'  -timeout 180m
=== RUN   TestAccConfigService_serial
=== PAUSE TestAccConfigService_serial
=== CONT  TestAccConfigService_serial
=== RUN   TestAccConfigService_serial/Config …
```
=> [TechDebt]: Replace deprecated `AWSConfigRole` in acceptance tests
