.semgrep-configs.yml, internal/generate/servicesemgrep/configs.tmpl, internal/service/organizations/account_test.go, internal/service/organizations/delegated_administrator_test.go, internal/service/organizations/delegated_administrators_data_source_test.go, internal/service/organizations/delegated_services_data_source_test.go, internal/service/organizations/organization_data_source_test.go, internal/service/organizations/organization_test.go, internal/service/organizations/organizational_unit_test.go, internal/service/organizations/organizational_units_data_source_test.go, internal/service/organizations/policy_attachment_test.go, internal/service/organizations/policy_test.go, internal/service/organizations/resource_tags_data_source_test.go
=> ci/semgrep/organizations: Remove exclusion

.semgrep-configs.yml, internal/generate/servicesemgrep/configs.tmpl, internal/service/elb/app_cookie_stickiness_policy_test.go, internal/service/elb/attachment_test.go, internal/service/elb/hosted_zone_id_data_source_test.go, internal/service/elb/lb_cookie_stickiness_policy_test.go, internal/service/elb/lb_ssl_negotiation_policy_test.go, internal/service/elb/load_balancer_data_source_test.go, internal/service/elb/load_balancer_test.go, internal/service/elb/policy_test.go, internal/service/elb/proxy_protocol_policy_test.go, internal/service/elbv2/listener_certificate_test.go
- ci/semgrep/elb: Remove exclusion
- ci/semgrep/elb: Remove exclusion
```
...
```
=> ci/semgrep/elb: Remove exclusion

.semgrep-configs.yml, internal/generate/servicesemgrep/configs.tmpl, internal/service/apigatewayv2/api_data_source_test.go, internal/service/apigatewayv2/api_mapping_test.go, internal/service/apigatewayv2/api_test.go, internal/service/apigatewayv2/apis_data_source_test.go, internal/service/apigatewayv2/authorizer_test.go, internal/service/apigatewayv2/deployment_test.go, internal/service/apigatewayv2/domain_name_test.go, internal/service/apigatewayv2/export_data_source_test.go, internal/service/apigatewayv2/integration_test.go, internal/service/apigatewayv2/route_test.go, internal/service/apigatewayv2/stage_test.go
- ci/semgrep/apigatewayv2: Remove exclusion
- ci/semgrep/apigatewayv2: Remove exclusion
```
...
```
=> ci/semgrep/apigatewayv2: Remove exclusion

internal/service/ec2/ipam_pool_cidr_allocation_test.go
Relates #25268
Output from acceptance testing without code change:
```
$ make testacc TESTARGS='-run=TestAccIPAMPoolAllocation_mult' PKG=ec2
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 20  -run=TestAccIPAMPoolAllocation_mult -timeout 180m
=== RUN …
```
=> r/ipam_pool_cidr_allocation: add test to ensure filtering by ipam pool allication id

.semgrep-configs.yml, internal/generate/servicesemgrep/configs.tmpl, internal/service/autoscaling/attachment_test.go, internal/service/autoscaling/group_data_source_test.go, internal/service/autoscaling/group_test.go, internal/service/autoscaling/groups_data_source_test.go, internal/service/autoscaling/launch_configuration_data_source_test.go, internal/service/autoscaling/launch_configuration_test.go, internal/service/autoscaling/lifecycle_hook_test.go, internal/service/autoscaling/notification_test.go, internal/service/autoscaling/policy_test.go, internal/service/autoscaling/schedule_test.go
- ci/semgrep/autoscaling: Remove exclusion
- ci/semgrep/autoscaling: Remove exclusion
```
...
```
=> ci/semgrep/autoscaling: Remove exclusion

website/docs/r/organizations_account.html.markdown
=> organizations_account: Add more docs to billing iam users

.semgrep-configs.yml, internal/generate/servicesemgrep/configs.tmpl, internal/service/dms/certificate_test.go, internal/service/dms/endpoint_test.go, internal/service/dms/event_subscription_test.go, internal/service/dms/replication_instance_test.go, internal/service/dms/replication_task_test.go
=> ci/semgrep/dms: Remove exclusion

.github/scripts/providerlint.sh, .github/workflows/terraform_provider.yml
=> ci/providerlint: Improve providerlint handling

.semgrep-configs.yml, .semgrep-service-name0.yml, internal/generate/servicesemgrep/configs.tmpl, internal/generate/servicesemgrep/main.go, internal/service/cloudtrail/cloudtrail_test.go, internal/service/cloudtrail/event_data_store_test.go, internal/service/cloudtrail/service_account_data_source_test.go
- ci/semgrep/cloudtrail: Remove exclusion
- ci/semgrep/cloudtrail: Fix ci
```
...
```
=> ci/semgrep/cloudtrail: Remove exclusion

.semgrep-configs.yml, internal/generate/servicesemgrep/configs.tmpl, internal/service/dax/cluster_test.go
=> ci/semgrep/dax: Remove exclusion

.semgrep-configs.yml, internal/generate/servicesemgrep/configs.tmpl, internal/service/apigateway/base_path_mapping_test.go, internal/service/lambda/alias_data_source_test.go, internal/service/lambda/alias_test.go, internal/service/lambda/code_signing_config_data_source_test.go, internal/service/lambda/code_signing_config_test.go, internal/service/lambda/event_source_mapping_test.go, internal/service/lambda/function_data_source_test.go, internal/service/lambda/function_event_invoke_config_test.go, internal/service/lambda/function_test.go, internal/service/lambda/function_url_data_source_test.go, internal/service/lambda/function_url_test.go, internal/service/lambda/invocation_data_source_test.go, internal/service/lambda/invocation_test.go, internal/service/lambda/layer_version_data_source_test.go, internal/service/lambda/layer_version_permission_test.go, internal/service/lambda/layer_version_test.go, internal/service/lambda/permission_test.go, internal/service/lambda/provisioned_concurrency_config_test.go
- ci/semgrep/lambda: Remove exclusion
- ci/semgrep/lambda: Remove exclusion
```
...
```
=> ci/semgrep/lambda: Remove exclusion

.github/scripts/golangci-lint.sh, .github/workflows/terraform_provider.yml
=> ci/golangci-lint: Run from subshell

.github/workflows/semgrep-ci.yml
Closes https://github.com/hashicorp/terraform-provider-aws/issues/25489.
=> Workaround failing `semgrep` GitHub Action

.changelog/25245.txt
=> Fix CHANGELOG entry spelling mistake

website/docs/r/msk_cluster.html.markdown
Update Kafka version in the documentation example to the latest supported version.
Closes: https://github.com/hashicorp/terraform-provider-aws/issues/25541
=> Update kafka version on msk_cluster.html.markdown

internal/service/location/sweep.go
Relates https://github.com/hashicorp/terraform-provider-aws/issues/19629.
```
$ SWEEPARGS=-sweep-run=aws_location_tracker make sweep
go test ./internal/sweep -v -tags=sweep -sweep=us-west-2,us-east-1,us-east-2 -sweep-run=aws_location_tracker -timeout …
```
=> sweeper/aws_location_tracker - new sweeper

website/docs/r/lakeformation_permissions.html.markdown
=> Fixed Typo in doc aws_lakeformation_permissions

website/docs/r/appsync_api_cache.html.markdown
=> Fixed aws_appsync_api_cache example in docs

.changelog/25544.txt, internal/service/gamelift/game_session_queue.go, internal/service/gamelift/game_session_queue_test.go, website/docs/r/gamelift_game_session_queue.html.markdown
```
$ make testacc TESTS=TestAccGameLiftGameSessionQueue PKG=gamelift
...
```
=> resource/aws_gamelift_game_session_queue: add notification_target argument 

docs/contributing/faq.md, infrastructure/repository/maintainer-list.tf
=> Remove Mary and Angie from maintainer lists

skaff/resource/resourcetest.tmpl
=> skaff: Use ProviderFactories instead of Providers

skaff/README.md, skaff/cmd/datasource.go, skaff/cmd/resource.go, skaff/datasource/datasource.go, skaff/datasource/datasource.tmpl, skaff/datasource/datasourcetest.tmpl, skaff/resource/resource.go, skaff/resource/resource.tmpl, skaff/resource/resourcetest.tmpl
- skaff: Rework docs, v1-v2
- skaff: v1 capability
```
...
```
=> skaff: v1 capability

internal/service/location/sweep.go
```
$ SWEEPARGS=-sweep-run=aws_location_geofence_collection SWEEP=eu-central-1 make sweep
go test ./internal/sweep -v -tags=sweep -sweep=eu-central-1 -sweep-run=aws_location_geofence_collection -timeout 60m
2022/07/16 09:16:48 …
```
=> sweeper/aws_location_geofence_collection: new sweeper

website/docs/r/securityhub_product_subscription.markdown
This PR improves the docs for adding products to SecurityHub using `securityhub_product_subscription`
=> Improves docs for securityhub products

website/docs/r/backup_plan.html.markdown
=> Update backup plan documentation for argument completion_window

.changelog/25913.txt, internal/service/ec2/vpc_flow_log.go, internal/service/ec2/vpc_flow_log_test.go, website/docs/r/ec2_transit_gateway_connect.html.markdown, website/docs/r/flow_log.html.markdown
resource/aws_flow_log: Add support for Transit Gateway and Transit Gateway attachment.
Closes #25833
```
$ make testacc TESTS='^TestAccVPCFlowLog_(vpc|transitGateway(Attachment)?)ID$' PKG=ec2
--- PASS: TestAccVPCFlowLog_vpcID (23.89s)
--- PASS: TestAccVPCFlowLog_transitGatewayID (164.63s)
--- PASS: …
```
=> resource/aws_flow_log: Add support for Transit Gateway and Transit Gateway attachment

website/docs/r/elasticache_replication_group.html.markdown
Remove deprecated fields from the examples
=> r/aws_elasticache_replication_group: update examples

website/docs/r/kms_replica_external_key.html.markdown
=> Fixed typo

website/docs/r/amplify_branch.html.markdown
Updates aws_amplify_branch resource documentation for adding basic auth
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/amplify_branch#basic-authentication
=> Correct basic_auth docs for aws_amplify_branch

website/docs/r/autoscaling_group.html.markdown
Update the website documentation to reflect ASG's suspended_processes valid values to include InstanceRefresh, as per the AWS documentation: 
https://docs.aws.amazon.com/autoscaling/ec2/userguide/as-suspend-resume-processes.html
=> Update autoscaling_group.html.markdown suspended_processes valid values to include InstanceRefresh.

skaff/resource/resource.tmpl, skaff/resource/websitedoc.tmpl
=> Skaff: name updates in template

CHANGELOG.md, website/docs/r/cloudfront_field_level_encryption_config.html.markdown, website/docs/r/cloudfront_field_level_encryption_profile.html.markdown, website/docs/r/docdb_cluster.html.markdown, website/docs/r/docdb_global_cluster.html.markdown, website/docs/r/ec2_transit_gateway_route_table_association.html.markdown, website/docs/r/ec2_transit_gateway_route_table_propagation.html.markdown, website/docs/r/elasticsearch_domain_policy.html.markdown, website/docs/r/iam_group_policy.html.markdown, website/docs/r/kms_replica_key.html.markdown, website/docs/r/opensearch_domain_policy.html.markdown, website/docs/r/redshiftdata_statement.html.markdown
=> Typos in resource page titles

internal/service/ec2/vpc_security_group_rule.go, internal/service/ec2/vpc_security_group_test.go
Relates https://github.com/hashicorp/terraform-provider-aws/pull/24340.
Relates #25927.
=> Add "ci." to rule names in new `nosemgrep`s

.ci/scripts/generate-changelog.sh
Closes https://github.com/hashicorp/terraform-provider-aws/issues/25959.
=> `CHANGELOG.md` is in the root of the repository

.github/dependabot.yml
=> dependabot: `/tools` -> `/.ci/tools`

website/docs/r/s3_bucket_public_access_block.html.markdown
Include all protection attributes by default. This is the standard approach.
```
...
```
=> Update aws_s3_bucket_public_access_block example

website/docs/r/ssm_service_setting.html.markdown
This PR corrects the documentation of the new `aws_ssm_service_setting` resource. Arguments were wrong so corrected those to match the actual implementation
=> Fix SSM Service setting documentation

internal/service/appautoscaling/policy_test.go, internal/service/backup/vault_notifications_test.go, internal/service/elasticache/cluster_test.go, internal/service/elasticache/replication_group_test.go, internal/service/fms/policy_test.go, internal/service/fsx/lustre_file_system_test.go, internal/service/iot/authorizer_test.go, internal/service/rds/cluster_activity_stream_test.go, internal/service/sagemaker/feature_group_test.go, internal/service/sagemaker/workteam_test.go, internal/service/servicecatalog/constraint_test.go
=> Fix `tflint` "terraform_deprecated_interpolation" errors

website/docs/r/kendra_data_source.html.markdown
Relates #25686
Small documentation update
=> docs(kendra): rm unused depends_on

.changelog/10563.txt
=> Add missing CHANGELOG entries

website/docs/r/api_gateway_deployment.html.markdown, website/docs/r/apigatewayv2_deployment.html.markdown, website/docs/r/cloudformation_type.html.markdown, website/docs/r/rds_cluster_instance.html.markdown
Signed-off-by: Gergő Rubint <gergo@grubint.com>
https://github.com/hashicorp/terraform/commit/6e2f5eb0bea2e0c8623bff579ca71b38b5f915bc commit broke up the terraform `resources` page.
=> Docs: point lifecycle links to their new place

internal/service/firehose/list_pages.go, internal/service/firehose/sweep.go
Closes https://github.com/hashicorp/terraform-provider-aws/issues/26192.
```console
% make sweep SWEEPARGS=-sweep-run=aws_kinesis_firehose_delivery_stream SWEEP=us-west-2
go test ./internal/sweep -v -tags=sweep -sweep=us-west-2 -sweep-run=aws_kinesis_firehose_delivery_stream …
```
=> r/aws_kinesis_firehose_delivery_stream: Add paginated lister and use in sweeper

GNUmakefile
Combines the seven `semgrep` executions in the Makefile rule `semall` into one
=> Combines `semall` rule into one `semgrep` execution

internal/service/ecs/sweep.go
The sweeper for `aws_ecs_service` no longer fails silently. Runs delete operations in parallel.
Closes #25635
=> sweeper/aws_ecs_service: No longer fails silently on error

.changelog/26313.txt, go.mod, go.sum, website/docs/r/cloudfront_distribution.html.markdown
Closes https://github.com/hashicorp/terraform-provider-aws/issues/26321.
=> Add support for Cloudfront HTTP3

website/docs/r/glue_job.html.markdown
=> Correct typo in AWS Glue Job documentation

README.md, docs/README.md
=> docs: Update readme

website/docs/r/dms_replication_task.html.markdown
We stumbled over this behavior by accident, and found it surprising, to say the least. Adding a note here in the docs hopefully catches other users that "just need to do this small change to the resource" to think about this, and plan the change accordingly.
=> Add a note that changing resource attributes will stop the task

internal/service/dms/README.md
=> Fix link to "how to contribute" page in DMS docs

docs/changelog-process.md
Fixes a typo on the contributing docs "Changelog Process" page
=> Documentation: Fix deprecations section typo

website/docs/r/redshiftserverless_namespace.html.markdown
Fix small typo in documentation.
=> Redshift Serverless doc typo correction

skaff/resource/resource.tmpl
=> skaff: Improve Required, Computed, Optional explanation

.github/workflows/release.yml
=> update to custom runner and set parallelism

internal/service/ram/resource_share.go, internal/service/ram/sweep.go, internal/sweep/sweep_test.go
```console
% make sweep SWEEPARGS=-sweep-run=aws_ram_resource_share SWEEP=us-east-1,us-west-2
go test ./internal/sweep -v -tags=sweep -sweep=us-east-1,us-west-2 -sweep-run=aws_ram_resource_share -timeout 60m
2022/08/29 11:38:41 [DEBUG] Running Sweepers for region (us-east-1): …
```
=> r/aws_ram_resource_share: Add sweeper

internal/service/location/sweep.go
Closes #19629.
```
$ make sweep SWEEP=eu-central-1 SWEEPARGS=-sweep-run=aws_location_tracker_association
go test ./internal/sweep -v -tags=sweep -sweep=eu-central-1 -sweep-run=aws_location_tracker_association -timeout 60m
2022/08/29 18:56:07 Completed …
```
=> sweeper/aws_location_tracker_association:  new sweeper

website/docs/r/ecs_task_definition.html.markdown
Closes #23244.
https://github.com/hashicorp/terraform-provider-aws/blob/f9ddea8c29067016731d50727f664b9e5abd84ff/internal/service/ecs/task_definition.go#L251-L255
=> r/aws_ecs_task_definition: document skip_destroy argument

.changelog/26482.txt, website/docs/r/autoscaling_group.html.markdown
=> fix: update aws_autoscaling_group documentation for termination policies

website/docs/d/ecs_task_definition.html.markdown
=> fix example does not use data ecs_tasks_definition doc

go.sum
=> go mod tidy2

ROADMAP.md
=> Update ROADMAP's Core Services link

internal/service/backup/sweep.go
Closes #26217
```
$ SWEEP=us-west-2 SWEEPARGS=-sweep-run=aws_backup_vault make sweep
...
```
=> Backup Vault force sweep

internal/service/ec2/sweep.go
=> sweep: Add missing dependency to ENI

internal/service/ec2/sweep.go, internal/service/iam/sweep.go, internal/service/rds/cluster.go, internal/service/rds/global_cluster.go, internal/service/rds/instance.go, internal/service/rds/instance_automated_backups_replication.go, internal/service/rds/sweep.go
- sweep/ec2/vpc: Fix sweeper bugs
- sweep/rds: Fix sweeper bugs
Relates https://github.com/hashicorp/terraform-provider-aws/issues/13898 (I think).
```
...
```
=> sweepers: Fix vpc, ec2, rds sweeper problems

internal/service/location/README.md
=> aws_location: create README.md

internal/service/acm/sweep.go, internal/service/iam/sweep.go, internal/service/s3/sweep.go
=> sweep: Minor fixes

.ci/tools/go.mod, .ci/tools/go.sum
Reverts https://github.com/hashicorp/terraform-provider-aws/pull/26701.
```
ERROR: File "./internal/service/securityhub/action_target_test.go", block #2 (lines 196-205):
Failed to initialize plugins; TFLint is not compatible with this version of the "aws" plugin. A newer TFLint or plugin version may be required. Plugin version: 10, Client versions: [11]
```
=> Revert to tflint v0.39.3

.ci/tools/go.mod, .ci/tools/go.sum
Relates https://github.com/hashicorp/terraform-provider-aws/pull/26737.
=> Run `go get github.com/terraform-linters/tflint@v0.39.3`

.teamcity/settings.kts
=> ci: TeamCity schedule

.teamcity/settings.kts
=> teamcity: Cron problems

.teamcity/settings.kts
=> ci: TeamCity possible

website/docs/r/ec2_managed_prefix_list_entry.html.markdown
=> r/aws_ec2_managed_prefix_list_entry include note about pfx-lists with many entries

docs/faq.md, infrastructure/repository/maintainer-list.tf
=> Update maintainer list

.github/PULL_REQUEST_TEMPLATE.md
This pull request modifies the current pull request template to give more structure and tips in the comments. The goal here is to make pull requests look a bit more uniform, similar to what we did with Issue Forms.
Output from acceptance testing: N/a
=> Add headers, additional info to PR template

skaff/datasource/datasource.tmpl, skaff/datasource/datasourcetest.tmpl, skaff/resource/resource.tmpl, skaff/resource/resourcetest.tmpl
=> skaff: Minor fixes

names/names.go, skaff/datasource/datasource.go, skaff/datasource/datasource.tmpl, skaff/datasource/websitedoc.tmpl, skaff/resource/resource.go, skaff/resource/websitedoc.tmpl
=> skaff: Fix website doc generation

internal/service/ds/sweep.go
Makes `aws_directory_service_directory` sweeper concurrent.
Ignores `aws_directory_service_region` sweeper for directories that aren't replicated.
Previously:
```
2022/09/22 22:38:37 [ERROR] Error running Sweeper (aws_directory_service_region) in region (us-west-2): 4 errors occurred:
* describing DS Regions for us-west-2: UnsupportedOperationException: Multi-region replication is only supported for AWS Managed Microsoft AD (Enterprise edition) directories. : RequestId: 663d9837-f75d-4375-aaae-037f9191e971
{
RespMetadata: {
StatusCode: 400,
RequestID: "663d9837-f75d-4375-aaae-037f9191e971"
},
Message_: "Multi-region replication is only supported for AWS Managed Microsoft AD (Enterprise edition) directories. : RequestId: 663d9837-f75d-4375-aaae-037f9191e971",
RequestId: …
```
=> Sweepers for `aws_directory_service_directory` and `aws_directory_service_region`

website/docs/r/cloudfront_origin_request_policy.html.markdown
Documentation Update
- Added import section for aws_cloudfront_origin_request_policy
Closes #26986
=> [Documentation] #26986 Add import for aws_cloudfront_origin_request_policy

website/docs/r/cloudwatch_metric_stream.html.markdown
Added missing argument in import example command
Closes #26861
=> Added missing argument in cloudwatch_metric_stream doc

.changelog/26980.txt
Relates https://github.com/hashicorp/terraform-provider-aws/pull/26980.
=> Correct CHANGELOG entries

internal/service/ec2/ec2_capacity_reservation.go, internal/service/ec2/outposts_local_gateway_route_table_vpc_association.go
=> Tech debt: Use EC2 API constants from AWS SDK for Go now that they are available

.changelog/26951.txt
Relates https://github.com/hashicorp/terraform-provider-aws/pull/26951.
=> Add missing CHANGELOG entry

internal/conns/awsclient.go, internal/experimental/intf/README.md, internal/experimental/intf/provider.go, internal/experimental/intf/service.go, internal/provider/fwprovider/provider.go, internal/service/meta/arn_data_source.go, internal/service/meta/svcimpl.go
Modify the `aws_arn` data source `Read` implementation to match the Terraform Plugin Framework Beta example: https://developer.hashicorp.com/terraform/plugin/framework/data-sources.
=> d/aws_arn: Match Framework example use on developer.hashicorp.com

website/docs/r/rds_reserved_instance.html.markdown
=> rds: Update docs

.changelog/27184.txt, internal/service/identitystore/user.go, internal/service/identitystore/user_data_source.go
Closes #27145
Closes #27144
```
$ make testacc TESTS=TestAccIdentityStoreUserDataSource_\|TestAccIdentityStoreUser_ PKG=identitystore
```
=> Fix incorrect type on IdentityStore user resource / data source

website/docs/r/identitystore_group.html.markdown
Very exciting pull request, this trailing dot was bothering me whilst working on #27184
=> Remove trailing dot in `aws_identitystore_group` resource docs

website/docs/r/db_parameter_group.html.markdown
Fix small typos in the db_parameter_group [doc](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/db_parameter_group).
Closes #0000
```
...
```
=> Fix small typos in doc

website/docs/r/networkmanager_link.html.markdown
Fix example configuration on `aws_networkmanager_link`.
=> docs/r/networkmanager_link: Fix example

website/docs/r/ec2_transit_gateway_connect_peer.html.markdown
Fix example configuration on `aws_ec2_transit_gateway_connect_peer`.
=> docs/r/ec2_transit_gateway_connect_peer: Fix example

website/docs/d/codestarconnections_connection.html.markdown, website/docs/d/globalaccelerator_accelerator.html.markdown, website/docs/d/iam_policy_document.html.markdown, website/docs/d/kms_secrets.html.markdown, website/docs/d/lb.html.markdown, website/docs/d/lb_target_group.html.markdown, website/docs/d/networkmanager_core_network_policy_document.html.markdown, website/docs/r/autoscaling_group.html.markdown, website/docs/r/db_option_group.html.markdown, website/docs/r/ebs_volume.html.markdown, website/docs/r/ec2_fleet.html.markdown, website/docs/r/ecs_task_definition.html.markdown, website/docs/r/kinesisanalyticsv2_application.html.markdown, website/docs/r/launch_template.html.markdown, website/docs/r/s3_bucket_metric.html.markdown, website/docs/r/spot_fleet_request.html.markdown
Fixes issue where colons were added to a new line rather than as part of the 'Note' heading.
N/A
N/A
N/A
=> [Docs] - Fix formatting with `NOTE` sections

website/docs/index.html.markdown
This PR is to fix a table format issue in the markdown file
Relates to #27138
=> Fix formatting of table 'Assume Role with Web Identity Configuration Reference'

website/docs/r/emrcontainers_virtual_cluster.markdown
Signed-off-by: Sebastian Struß <struss@justtrack.io>
Closes #25560
=> r/aws_emrcontainers_virtual_cluster: update docs

website/docs/guides/version-4-upgrade.html.md
Minor improvements to the version 4 upgrade guide docs.
=> Improve examples in version 4 upgrade guide

internal/service/fis/experiment_template.go, internal/service/fis/experiment_template_test.go, website/docs/r/fis_experiment_template.html.markdown
This is to fix a validation failure for SpotInstances
Closes #26950 
I'm not sure what to add here, please let me know if there is anything though happy to add it.
=> Added FIS support for SpotInstances

website/docs/r/network_interface.markdown
=> [Docs]: Fix typo`aws_network_interface` attribute list

website/docs/r/elasticache_user_group.html.markdown
=> Update `aws_elasticache_user_group` documentation to reflect the schema

website/docs/r/launch_configuration.html.markdown
Update docs for `aws_launch_configuration` with note about optional `name_prefix`
Closes #8485
```
...
```
=> r/aws_launch_configuration: update docs with note

website/docs/r/ssm_association.html.markdown, website/docs/r/ssm_maintenance_window.html.markdown
Improve docs for `aws_ssm_association` resource `schedule_expression` parameter.
Closes #27141
=> Improve docs for aws_ssm_association schedule_expression

website/docs/r/rum_app_monitor.html.markdown
Attribute names were incorrect and have been corrected.
Closes #0000
```
...
```
=> d/rum_app_monitor: Fix app_monitor_configuration attribute name

website/docs/r/eks_node_group.html.markdown
Add an example to show how to have an EKS node group track the latest available AWS AMI. As the discussion in #26345 shows, this isn't immediately obvious, so having a common use-case available in the docs makes sense to me.
Closes #26345
```
N/A
```
=> Add example for tracking EKS AMI updates

website/docs/r/secretsmanager_secret.html.markdown, website/docs/r/secretsmanager_secret_rotation.html.markdown
Backports https://github.com/hashicorp/terraform-provider-aws/pull/27425 to `release/3.x`.
=> release/3.x: Correct secrets rotation link

website/docs/r/medialive_multiplex_program.html.markdown
Update documentation.
Closes #0000
```
...
```
=> r/aws_medialive_multiplex_program: update docs

website/docs/r/identitystore_user.html.markdown
As part of this PR, I updated `emails Configuration Block` title to `name Configuration Block` in Resource:`aws_identitystore_user` documentation.
Closes #27060
=> r/aws_identitystore_user - Update emails Configuration Block title to name Configuration Block

.changelog/27542.txt, internal/service/sagemaker/domain.go, internal/service/sagemaker/domain_test.go, internal/service/sagemaker/sagemaker_test.go, internal/service/sagemaker/user_profile.go, internal/service/sagemaker/user_profile_test.go, website/docs/r/sagemaker_domain.html.markdown, website/docs/r/sagemaker_user_profile.html.markdown
Closes #27533
```
$ make testacc TESTS=TestAccSageMaker_serial/Domain  PKG=sagemaker
...
```
=> Sagemaker domain and user profile - add args

website/docs/r/backup_framework.html.markdown
Add missing examples in https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/backup_framework
Closes #27579
=> Add missing controls examples to backup_framework resource

website/docs/r/kms_key.html.markdown
Minor doc improvement
Closes #0000
```
...
```
=> Minor doc improvement

.changelog/27741.txt, internal/provider/provider.go, internal/service/redshiftserverless/find.go, internal/service/redshiftserverless/snapshot.go, internal/service/redshiftserverless/snapshot_test.go, internal/service/redshiftserverless/status.go, internal/service/redshiftserverless/sweep.go, internal/service/redshiftserverless/wait.go, website/docs/r/redshiftserverless_snapshot.html.markdown
Relates https://github.com/hashicorp/terraform-provider-aws/issues/24501.
```
$  make testacc TESTS=TestAccRedshiftServerlessSnapshot_ PKG=redshiftserverless
--- PASS: TestAccRedshiftServerlessSnapshot_basic (724.32s)
--- PASS: TestAccRedshiftServerlessSnapshot_disappears (727.40s)
```
=> redshift serverless snapshot resource

website/docs/r/vpc_peering_connection.html.markdown
Documentation update with note to `aws_vpc_peering_connection` resource.
Closes #27750
```
...
```
=> docs: `aws_vpc_peering_connection` behavior

names/README.md
Updates the table in `names/README.md` to reflect the new `names/names_data.csv` file structure introduced in #27609.
Relates #27609
=> Update names data table with new format

website/docs/r/wafv2_ip_set.html.markdown
Corrected the incorrect description of 'arn' on outputs and improved the description of 'id' more clearly.
Closes #0000
```
...
```
=> Fix docs for `wafv2_ip_set` resource.

internal/framework/types/arn.go, internal/framework/types/duration.go, internal/service/globalaccelerator/accelerator_data_source.go, internal/service/meta/arn_data_source.go
Correct the name of Plugin Framework custom type method that return the known value.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/27883.
```
% make testacc TESTARGS='-run=TestAccMetaARNDataSource_basic' PKG=meta ACCTEST_PARALLELISM=3
TF_ACC=1 go test ./internal/service/meta/... -v -count 1 -parallel 3  -run=TestAccMetaARNDataSource_basic -timeout 180m
=== RUN   TestAccMetaARNDataSource_basic
=== PAUSE TestAccMetaARNDataSource_basic
=== CONT  TestAccMetaARNDataSource_basic
--- PASS: TestAccMetaARNDataSource_basic (12.67s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/meta	17.430s
```
=> Tech debt: Correct Plugin Framework custom type method names

.changelog/27920.txt, internal/provider/provider.go, internal/service/redshiftserverless/find.go, internal/service/redshiftserverless/resource_policy.go, internal/service/redshiftserverless/resource_policy_test.go, website/docs/r/redshiftserverless_resource_policy.html.markdown
Relates https://github.com/hashicorp/terraform-provider-aws/issues/24501.
```
$ make testacc TESTS=TestAccRedshiftServerlessResourcePolicy_ PKG=redshiftserverless
--- PASS: TestAccRedshiftServerlessResourcePolicy_basic (951.31s)
```
=> Redshift Serverless resource policy

.changelog/28099.txt, website/docs/r/kinesisanalyticsv2_application.html.markdown
Ibid.
Closes https://github.com/hashicorp/terraform-provider-aws/issues/28096.
=> r/aws_kinesisanalyticsv2_application: Document support for Apache Flink v1.15

.changelog/28114.txt, internal/service/redshiftserverless/wait.go
=> r/aws_redshiftserverless_workgroup - wait for MODIFYING on destroy

.changelog/28243.txt
Missing from https://github.com/hashicorp/terraform-provider-aws/pull/28243.
=> Add CHANGELOG entry

internal/service/ec2/ec2_instance.go, internal/service/ec2/ec2_spot_instance_request.go, internal/service/ec2/sweep.go, internal/service/eks/sweep.go, internal/service/elasticache/sweep.go, internal/service/emr/cluster.go, internal/service/emr/sweep.go
Various sweeper fixes for problems found during runs in `us-west-2`.
=> Sweepers: Various fixes

.github/workflows/post_publish.yml
Replaces old action to clean up internal tickets after release
=> Workflow: Replace Tidy GHA to work with Jira

website/docs/r/db_instance.html.markdown
Documents that `iops` and `storage_throughput` cannot be configured in certain circumstances for gp3 storage.
Closes https://github.com/hashicorp/terraform-provider-aws/issues/28271.
=> r/aws_db_instance: gp3 storage documentation additions

CHANGELOG.md
Corrects the **Unreleased** v3._x_ version in the CHANGELOG.
=> release/3.x: Next 3.x version is `3.76.0`

.github/goreleaser-cross-compiler-test.yml, .github/workflows/goreleaser-ci.yml, .github/workflows/release.yml
Relates https://github.com/hashicorp/terraform-provider-aws/pull/24938.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/26500.
=> release/3.x: Use `goreleaser` files from `main`

CHANGELOG.md
=> Add v3.76.0 release notes to main CHANGELOG

.github/workflows/post_publish.yml
=> Point Jira Tidy to main until we have stability

website/docs/r/autoscaling_schedule.html.markdown, website/docs/r/cloudwatch_event_target.html.markdown, website/docs/r/lb.html.markdown
Doc updates to close out tickets
I put them all in this PR but I can rebase and split them out into separate PRs if desired
Closes [#27171](https://github.com/hashicorp/terraform-provider-aws/issues/27171)
Closes [#27176](https://github.com/hashicorp/terraform-provider-aws/issues/27176)
Closes [#26628](https://github.com/hashicorp/terraform-provider-aws/issues/26628)
https://docs.aws.amazon.com/autoscaling/ec2/APIReference/API_PutScheduledUpdateGroupAction.html
https://docs.aws.amazon.com/elasticloadbalancing/latest/APIReference/API_SubnetMapping.html
https://docs.aws.amazon.com/whitepapers/latest/ipv6-on-aws/scaling-the-dual-stack-network-design-in-aws.html
=> Documentation updates

website/docs/r/amplify_app.html.markdown
Add an example of custom image to docs
Closes [#27319](https://github.com/hashicorp/terraform-provider-aws/issues/27319)
=> doc: Custom image example

.changelog/28585.txt, internal/provider/provider.go, internal/service/lightsail/bucket.go, internal/service/lightsail/bucket_test.go, internal/service/lightsail/consts.go, internal/service/lightsail/find.go, website/docs/r/lightsail_bucket.html.markdown
This Pull request provides the terraform resource `aws_lightsail_bucket`
Closes #20239
```
➜ terraform-provider-aws (f-aws_lightsail_bucket) ✗ make testacc TESTARGS='-run=TestAccLightsailBucket' PKG=lightsail
TF_ACC=1 go test ./internal/service/lightsail/... -v -count 1 -parallel 20  -run=TestAccLightsailBucket -timeout 180m
=== RUN   TestAccLightsailBucket_basic
=== PAUSE TestAccLightsailBucket_basic
=== RUN   TestAccLightsailBucket_BundleId
=== PAUSE TestAccLightsailBucket_BundleId
=== RUN   TestAccLightsailBucket_disappears
=== PAUSE TestAccLightsailBucket_disappears
=== RUN   TestAccLightsailBucket_tags
=== PAUSE TestAccLightsailBucket_tags
=== CONT  TestAccLightsailBucket_basic
=== CONT  TestAccLightsailBucket_disappears
=== …
```
=> New Resource: `aws_lightsail_bucket`

website/docs/r/synthetics_canary.html.markdown
This PR includes change to the synthetic monitor resource, changing the allowed size of `zip_file` accordingly to AWS API.
=> Fix maximum size of zipfile

infrastructure/repository/labels-workflow.tf
Adds a `partner` label to indicate that an issue/pr was submitted by a partner contributor.
Adds a `roadmap` label to indicate that the issue/pr is to be included in the current quarter.
=> Add partner and roadmap labels.

website/docs/d/vpc_ipam_pool.html.markdown, website/docs/d/vpc_ipam_pools.html.markdown, website/docs/r/apigatewayv2_stage.html.markdown, website/docs/r/batch_job_definition.html.markdown, website/docs/r/cloudtrail.html.markdown, website/docs/r/launch_configuration.html.markdown, website/docs/r/sagemaker_domain.html.markdown
Closes [#28582](https://github.com/hashicorp/terraform-provider-aws/issues/28582)
Closes [#28551](https://github.com/hashicorp/terraform-provider-aws/issues/28551)
Closes [#28365](https://github.com/hashicorp/terraform-provider-aws/issues/28365)
Closes [#27289](https://github.com/hashicorp/terraform-provider-aws/issues/27289)
Closes [#28452](https://github.com/hashicorp/terraform-provider-aws/issues/28452)
Closes [#28421](https://github.com/hashicorp/terraform-provider-aws/issues/28421)
=> Docs - documentation updates 20230103

.github/workflows/goreleaser-ci.yml, .goreleaser.yml, CHANGELOG.md
=> release/3.x: Unreleased version is `3.76.1`

website/docs/r/s3_bucket.html.markdown
Change `Default Server Side Encryption` to `SSE-KMS Server Side Encryption`.
Relates: https://github.com/hashicorp/terraform-provider-aws/issues/28701.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/28702.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/28703.
=> r/aws_s3_bucket: Minor documentation wording change for server-side encryption

.ci/semgrep/acctest/naming/naming.yml, .github/workflows/semgrep-ci.yml, GNUmakefile, internal/service/account/alternate_contact_test.go, internal/service/budgets/budget_action_test.go, internal/service/budgets/budget_test.go, internal/service/cloudsearch/domain_service_access_policy_test.go, internal/service/cloudsearch/domain_test.go, internal/service/ec2/ebs_snapshot_create_volume_permission_test.go, internal/service/ec2/vpc_peering_connection_accepter_test.go, internal/service/ec2/vpnsite_connection_route_test.go, internal/service/ec2/vpnsite_connection_test.go, internal/service/ecr/registry_scanning_configuration_test.go, internal/service/fis/experiment_template_test.go, internal/service/iam/user_group_membership_test.go, internal/service/ssm/service_setting_test.go
Adds Semgrep check to ensure acctest destroy check function matches spec
=> Adds check for acctest destroy check function naming

website/docs/r/apigatewayv2_authorizer.html.markdown
I will be verifying this change, will change from draft to PR once it's ready.
Closes #20304 
```
...
```
=> docs : fix API Gateway v2 Authorizer basic HTTP example

internal/service/batch/compute_environment.go, internal/service/batch/job_definition.go, internal/service/batch/job_queue.go, internal/service/batch/scheduling_policy.go, internal/service/batch/sweep.go, internal/service/glacier/sweep.go, internal/service/glacier/vault.go, internal/service/kafka/configuration.go, internal/service/kafka/sweep.go, internal/service/kinesis/sweep.go, internal/service/kms/sweep.go, internal/service/timestreamwrite/database.go, internal/service/timestreamwrite/sweep.go, internal/service/timestreamwrite/table.go
Batch, Glacier, Kafka, Kinesis, KMS & Timestream: Replace direct calls to `Resource.Delete` with `sweep.SweepOrchestrator`
Relates https://github.com/hashicorp/terraform-provider-aws/issues/28556.
=> Avoid some direct calls to `Resource.Delete`

CHANGELOG.md
=> Add `v3.76.1` entries to `main` CHANGELOG

.github/workflows/pull_requests.yml
Use the [upstream](https://github.com/CodelyTV/pr-size-labeler) `pr-size-labeler` GitHub Action.
Closes https://github.com/hashicorp/terraform-provider-aws/issues/28793.
=> Use upstream `pr-size-labeler` GitHub Action

.changelog/28788.txt, internal/service/acmpca/policy.go, internal/service/acmpca/policy_test.go
```
% make testacc TESTS=TestAccACMPCAPolicy_ PKG=acmpca
TF_ACC=1 go test ./internal/service/acmpca/... -v -count 1 -parallel 20 -run='TestAccACMPCAPolicy_'  -timeout 180m
=== RUN   TestAccACMPCAPolicy_basic
=== PAUSE TestAccACMPCAPolicy_basic
=== CONT  TestAccACMPCAPolicy_basic
--- PASS: TestAccACMPCAPolicy_basic (22.44s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/acmpca	27.059s
```
=> acmpca/policy: Improve diff handling for policies

.changelog/28791.txt, internal/service/backup/vault_policy.go
Relates #23288
```console
% make testacc TESTS=TestAccBackupVaultPolicy_ PKG=backup
TF_ACC=1 go test ./internal/service/backup/... -v -count 1 -parallel 20 -run='TestAccBackupVaultPolicy_'  -timeout 180m
=== RUN   TestAccBackupVaultPolicy_basic
=== PAUSE TestAccBackupVaultPolicy_basic
=== RUN   TestAccBackupVaultPolicy_disappears
=== PAUSE TestAccBackupVaultPolicy_disappears
=== RUN   TestAccBackupVaultPolicy_Disappears_vault
=== PAUSE TestAccBackupVaultPolicy_Disappears_vault
=== RUN   TestAccBackupVaultPolicy_ignoreEquivalent
=== PAUSE TestAccBackupVaultPolicy_ignoreEquivalent
=== CONT  TestAccBackupVaultPolicy_basic
=== CONT  TestAccBackupVaultPolicy_Disappears_vault
=== CONT  TestAccBackupVaultPolicy_disappears
=== CONT …
```
=> backup/vault_policy: Improve diff handling for policies

.changelog/28800.txt, internal/service/efs/file_system_policy.go
```console
% make testacc TESTS=TestAccEFSFileSystemPolicy_ PKG=efs 
TF_ACC=1 go test ./internal/service/efs/... -v -count 1 -parallel 20 -run='TestAccEFSFileSystemPolicy_'  -timeout 180m
=== RUN   TestAccEFSFileSystemPolicy_basic
=== PAUSE TestAccEFSFileSystemPolicy_basic
=== RUN   TestAccEFSFileSystemPolicy_disappears
=== PAUSE TestAccEFSFileSystemPolicy_disappears
=== RUN   TestAccEFSFileSystemPolicy_policyBypass
=== PAUSE TestAccEFSFileSystemPolicy_policyBypass
=== RUN   TestAccEFSFileSystemPolicy_equivalentPolicies
=== PAUSE TestAccEFSFileSystemPolicy_equivalentPolicies
=== RUN   TestAccEFSFileSystemPolicy_equivalentPoliciesIAMPolicyDoc
=== PAUSE TestAccEFSFileSystemPolicy_equivalentPoliciesIAMPolicyDoc
=== …
```
=> efs/file_system_policy: Improve diff handling

.changelog/28807.txt, internal/service/glue/resource_policy.go
```console
% make testacc TESTS="TestAccGlue_serial/ResourcePolicy" PKG=glue
TF_ACC=1 go test ./internal/service/glue/... -v -count 1 -parallel 20 -run='TestAccGlue_serial/ResourcePolicy'  -timeout 180m
=== RUN   TestAccGlue_serial
=== RUN   TestAccGlue_serial/ResourcePolicy
=== RUN   TestAccGlue_serial/ResourcePolicy/hybrid
=== RUN   TestAccGlue_serial/ResourcePolicy/disappears
=== RUN   TestAccGlue_serial/ResourcePolicy/equivalent
=== RUN   TestAccGlue_serial/ResourcePolicy/basic
=== RUN   TestAccGlue_serial/ResourcePolicy/update
--- PASS: TestAccGlue_serial (119.00s)
--- PASS: TestAccGlue_serial/ResourcePolicy (119.00s)
--- PASS: TestAccGlue_serial/ResourcePolicy/hybrid (39.60s)
--- PASS: …
```
=> glue/resource_policy: Improve policy diffs

.changelog/28840.txt, internal/attrmap/attrmap.go, internal/service/sqs/attribute_funcs.go, internal/service/sqs/queue.go, internal/service/sqs/queue_policy.go
=> sqs/queue: Improve diff handling for policy

.changelog/28801.txt, internal/service/elasticsearch/domain.go, internal/service/elasticsearch/domain_policy.go
=> elasticsearch: Improve diffs on policies

.changelog/28860.txt, internal/service/sns/topic.go, internal/service/sns/topic_policy.go
```console
% make testacc TESTS="TestAccSNSTopicPolicy_|TestAccSNSTopic_" PKG=sns  
TF_ACC=1 go test ./internal/service/sns/... -v -count 1 -parallel 20 -run='TestAccSNSTopicPolicy_|TestAccSNSTopic_'  -timeout 180m
=== RUN   TestAccSNSTopicPolicy_basic
=== PAUSE TestAccSNSTopicPolicy_basic
=== RUN   TestAccSNSTopicPolicy_updated
=== PAUSE TestAccSNSTopicPolicy_updated
=== RUN   TestAccSNSTopicPolicy_Disappears_topic
=== PAUSE TestAccSNSTopicPolicy_Disappears_topic
=== RUN   TestAccSNSTopicPolicy_disappears
=== PAUSE TestAccSNSTopicPolicy_disappears
=== RUN   TestAccSNSTopicPolicy_ignoreEquivalent
=== PAUSE TestAccSNSTopicPolicy_ignoreEquivalent
=== RUN   TestAccSNSTopic_basic
=== PAUSE TestAccSNSTopic_basic
=== RUN …
```
=> sns: Improve policy diffs

.changelog/28864.txt, internal/service/schemas/registry_policy.go
Relates #23288
```console
% make testacc TESTS=TestAccSchemasRegistryPolicy_ PKG=schemas
TF_ACC=1 go test ./internal/service/schemas/... -v -count 1 -parallel 20 -run='TestAccSchemasRegistryPolicy_'  -timeout 180m
=== RUN   TestAccSchemasRegistryPolicy_basic
=== PAUSE TestAccSchemasRegistryPolicy_basic
=== RUN   TestAccSchemasRegistryPolicy_disappears
=== PAUSE TestAccSchemasRegistryPolicy_disappears
=== RUN   TestAccSchemasRegistryPolicy_disappears_Registry
=== PAUSE TestAccSchemasRegistryPolicy_disappears_Registry
=== RUN   TestAccSchemasRegistryPolicy_Policy
=== PAUSE TestAccSchemasRegistryPolicy_Policy
=== CONT  TestAccSchemasRegistryPolicy_basic
=== CONT  TestAccSchemasRegistryPolicy_disappears_Registry
=== CONT …
```
=> schemas/registry_policy: Improve policy diffs

.changelog/28859.txt, internal/service/transfer/access.go, internal/service/transfer/user.go
Relates #23288
```console
% make testacc TESTS="TestAccTransfer_serial/Access|TestAccTransfer_serial/User" PKG=transfer
TF_ACC=1 go test ./internal/service/transfer/... -v -count 1 -parallel 20 -run='TestAccTransfer_serial/Access|TestAccTransfer_serial/User'  -timeout 180m
=== RUN   TestAccTransfer_serial
=== PAUSE TestAccTransfer_serial
=== CONT  TestAccTransfer_serial
=== RUN   TestAccTransfer_serial/Access
=== RUN   TestAccTransfer_serial/Access/disappears
=== RUN   TestAccTransfer_serial/Access/EFSBasic
=== RUN   TestAccTransfer_serial/Access/S3Basic
=== RUN   TestAccTransfer_serial/Access/S3Policy
=== RUN   TestAccTransfer_serial/User
=== RUN   TestAccTransfer_serial/User/basic
=== RUN   TestAccTransfer_serial/User/disappears …
```
=> transfer: Improve diffs for policies

.github/workflows/release.yml
Backport use of the `setup-go-version-file` input to `release/2.x`.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/28827.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/28880.
=> release/2.x: Use `hashicorp/ghaction-terraform-provider-release` `setup-go-version-file` input

.github/workflows/release.yml
Backport use of the `setup-go-version-file` input to `release/2.x`.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/28827.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/28879.
=> release/3.x: Use `hashicorp/ghaction-terraform-provider-release` `setup-go-version-file` input

website/docs/r/kinesis_firehose_delivery_stream.html.markdown
Documentation update for `name` guidance when creating a delivery stream.
Closes #28893
```
...
```
=> r/aws_firehose_delivery_stream: `name` docs for logging

internal/service/iam/role_policy_test.go
=> Remove unneccesary lint ignore

.ci/.semgrep.yml, internal/service/apigateway/authorizer.go, internal/service/apigateway/integration.go, internal/service/cloudfront/distribution_configuration_structure.go, internal/service/cloudfront/origin_access_identity.go, internal/service/codecommit/repository.go, internal/service/elasticache/cluster.go, internal/service/elasticache/cluster_data_source.go, internal/service/elastictranscoder/pipeline.go, internal/service/emr/cluster.go, internal/service/fsx/lustre_file_system.go, internal/service/lexmodels/intent.go, internal/service/neptune/event_subscription.go, internal/service/rds/cluster_data_source.go, internal/service/route53/record.go, internal/service/s3/object.go, internal/service/s3/object_data_source.go
Closes #15893
```release-note
NONE
```
```
...
```
=> Remove extraneous nil checks before d.Set()

.changelog/28561.txt, internal/service/sagemaker/find.go
Closes #28535
Closes #28548
```
$ make testacc TESTS=TestAccSageMaker_serial/App/basic PKG=sagemaker
--- PASS: TestAccSageMaker_serial (446.85s)
--- PASS: TestAccSageMaker_serial/App (446.85s)
--- PASS: TestAccSageMaker_serial/App/basic (446.85s)
```
=> r/sagemaker_app - list all apps on read

.changelog/28569.txt, internal/service/ec2/sweep.go, internal/service/grafana/sweep.go, internal/service/grafana/workspace.go, internal/service/grafana/workspace_test.go, internal/sweep/sweep_test.go, website/docs/r/grafana_workspace.html.markdown
Closes #28388
```
$  make testacc TESTS=TestAccGrafana_serial/Workspace PKG=grafana
--- PASS: TestAccGrafana_serial/Workspace/vpc (1323.34s)
--- PASS: TestAccGrafana_serial/Workspace/configuration (859.41s)
--- PASS: TestAccGrafana_serial/Workspace/saml (375.31s)
```
=> r/grafana_workspace - fix vpc config update + workspace config arg

website/docs/r/qldb_stream.html.markdown
Fix typo in the example for [qldb_stream](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/qldb_stream) resource.
=> Fix typo in `qldb_stream` doc.

website/docs/r/iam_role.html.markdown
Non consistent policy name is being used [in the docs](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/iam_role).
Closes #28949
```
...
```
=> Use consistent policy name in docs.

website/docs/d/globalaccelerator_accelerator.html.markdown
=> [Documentation]: Fix copy/paste leftover on GlobalAccelerator data source

website/docs/r/vpc_ipam_pool_cidr_allocation.html.markdown
=> Fix aws_vpc_ipam_pool_cidr_allocation import instructions

website/docs/r/flow_log.html.markdown
The `aws_flow_logs` example for [Amazon Kinesis Data Firehose logging](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/flow_log#amazon-kinesis-data-firehose-logging) was previously erroneously an example of [CloudWatch Logging](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/flow_log#cloudwatch-logging). This PR aims to fix that.
Closes #28885
This is a mildly edited lift-and-shift from the [test case](https://github.com/hashicorp/terraform-provider-aws/blob/00e3ea5f97f93dc226d20f99a4ac1a41e9267caa/internal/service/ec2/vpc_flow_log_test.go#L1172-L1246).
N/a, docs.
=> Update Amazon Kinesis Data Firehose logging example in `aws_flow_logs` docs

website/docs/r/appmesh_gateway_route.html.markdown, website/docs/r/appmesh_route.html.markdown
Update docs for appmesh services.
Relates #27799 
```
...
```
=> update appmesh docs

.changelog/28989.txt
=> Add missed changelog 

website/docs/r/securityhub_standards_subscription.markdown
This PR is to fix the the CIS AWS Foundations Benchmark v1.4.0 standard ARN. The `ruleset` keyword should have been `standards` in the ARN.
Closes #28954
Output from aws securityhub describe-standards (run from us-east-1) for reference:
```
{
"Standards": [
{
"StandardsArn": "arn:aws:securityhub:us-east-1::standards/aws-foundational-security-best-practices/v/1.0.0",
"Name": "AWS Foundational Security Best Practices v1.0.0",
"Description": "The AWS Foundational Security Best Practices standard is a set of automated security checks that detect when AWS accounts and deployed resources do not align to security best practices. The standard is defined by AWS security experts. This curated set of controls helps improve your security posture in AWS, and cover AWS's most popular and foundational …
```
=> docs: fix CIS v1.4.0 std ARN in aws_securityhub_standards_subscription

website/docs/r/s3_bucket.html.markdown
=> r/aws_s3_bucket: document that website_endpoint and website_domain are deprecated

website/docs/index.html.markdown
=> Fix doc issue - Missing Environment Variable column in assume_role table

internal/service/dms/endpoint_test.go
=> dms/endpoint: Test to show recreation of endpoint

website/docs/r/autoscaling_group.html.markdown
=> fix autoscaling group OnDemandAllocationStrategy parameter

website/docs/d/lambda_function.html.markdown
Resolves https://github.com/hashicorp/terraform-provider-aws/issues/29205.
Relates https://github.com/hashicorp/terraform-provider-aws/issues/28963.
=> Add a note to d/lambda_function docs about invoke_arn change of behavior.

website/docs/r/acmpca_certificate_authority.html.markdown
=> aws_acmpca_certificate_authority doc clarifications

README.md
My previous change made the linter angry; fixing it.
Relates #29288
- [Failed job](https://github.com/hashicorp/terraform-provider-aws/actions/runs/4118701543/jobs/7111544461)
N/a, docs
=> Update README to remove hard tabs

website/docs/r/networkmanager_core_network_policy_attachment.html.markdown
Add more information in the documentation
- Describe how the policy attachment works. This first puts the new policy document to the core network before executing the change set, which sets the policy to `LIVE`
- Note that deleting the resource does not delete the policy it manages nor does it revert the current `LIVE` policy to a previous iteration
Relates #29097
```
...
```
=> Docs/aws_networkmanager_core network_policy_attachment

website/docs/r/medialive_channel.html.markdown
Fixes a typo where video has been misspelled vidoe in the example.
=> fix typo in the aws_medialive_channel resource example

.changelog/29269.txt
=> Add changelog note

internal/service/dynamodb/global_table.go, internal/service/dynamodb/global_table_test.go, internal/service/dynamodb/table.go, internal/service/dynamodb/table_data_source.go, internal/service/dynamodb/table_data_source_test.go, internal/service/dynamodb/table_replica.go, internal/service/dynamodb/table_replica_test.go, internal/service/dynamodb/table_test.go, names/attr_consts.go
=> Reduce magic values with consts

website/docs/d/ce_cost_category.html.markdown
Correct typos in the "not" and "or" rules for Cost Category
=> Docs: Update ce_cost_category.html.markdown

website/docs/r/s3_access_point.html.markdown, website/docs/r/s3_bucket.html.markdown, website/docs/r/s3_bucket_accelerate_configuration.html.markdown, website/docs/r/s3_bucket_acl.html.markdown, website/docs/r/s3_bucket_analytics_configuration.html.markdown, website/docs/r/s3_bucket_cors_configuration.html.markdown, website/docs/r/s3_bucket_intelligent_tiering_configuration.html.markdown, website/docs/r/s3_bucket_inventory.html.markdown, website/docs/r/s3_bucket_lifecycle_configuration.html.markdown, website/docs/r/s3_bucket_logging.html.markdown, website/docs/r/s3_bucket_metric.html.markdown, website/docs/r/s3_bucket_object_lock_configuration.html.markdown, website/docs/r/s3_bucket_ownership_controls.html.markdown, website/docs/r/s3_bucket_policy.html.markdown, website/docs/r/s3_bucket_replication_configuration.html.markdown, website/docs/r/s3_bucket_request_payment_configuration.html.markdown, website/docs/r/s3_bucket_server_side_encryption_configuration.html.markdown, website/docs/r/s3_bucket_versioning.html.markdown, website/docs/r/s3_bucket_website_configuration.html.markdown, website/docs/r/s3_object_copy.html.markdown
=> s3: Cleanup docs a little

website/docs/r/medialive_channel.html.markdown
Fixes typos in documentation for `aws_medialive_channel` resource.
=> fix typos in aws_medialive_channel documentation

website/docs/r/acmpca_policy.html.markdown, website/docs/r/api_gateway_account.html.markdown, website/docs/r/api_gateway_authorizer.html.markdown, website/docs/r/api_gateway_integration.html.markdown, website/docs/r/api_gateway_rest_api_policy.html.markdown, website/docs/r/appflow_flow.html.markdown, website/docs/r/appsync_datasource.html.markdown, website/docs/r/appsync_graphql_api.html.markdown
=> Replace heredoc with aws_iam_policy_document datasource (r/a*)

website/docs/d/redshift_service_account.html.markdown
Documents the future deprecation of the `aws_redshift_service_account` data source and recommended replacement functionality.
Relates https://github.com/hashicorp/terraform-provider-aws/issues/27874.
Relates https://github.com/hashicorp/terraform-provider-aws/issues/29346.
=> d/aws_redshift_service_account: Document future deprecation

website/docs/r/dms_endpoint.html.markdown
Closes #29419
https://docs.aws.amazon.com/dms/latest/APIReference/API_S3Settings.html
```
...
```
=> docs: Fix case of dms_endpoint canned_acl_for_objects valid values

GNUmakefile
=> make: Add  target for test subset

.changelog/29615.txt
Missed changelog entry from #29615
=> Add missed changelog

internal/generate/listpages/header.tmpl, internal/generate/listpages/main.go, internal/service/amplify/list_pages_gen.go, internal/service/apigatewayv2/list_pages_gen.go, internal/service/appstream/list_pages_gen.go, internal/service/autoscaling/list_pages_gen.go, internal/service/autoscalingplans/list_pages_gen.go, internal/service/directconnect/list_pages_gen.go, internal/service/ds/list_pages_gen.go, internal/service/ec2/list_pages_gen.go, internal/service/ecs/list_pages_gen.go, internal/service/efs/list_pages_gen.go, internal/service/elasticbeanstalk/list_pages_gen.go, internal/service/events/list_pages_gen.go, internal/service/kinesisanalyticsv2/list_pages_gen.go, internal/service/licensemanager/list_pages_gen.go, internal/service/logs/list_pages_gen.go, internal/service/memorydb/list_pages_gen.go, internal/service/mq/list_pages_gen.go, internal/service/route53/list_traffic_policies_pages_gen.go, internal/service/route53/list_traffic_policy_versions_pages_gen.go, internal/service/waf/list_pages_gen.go, internal/service/wafv2/list_pages_gen.go, internal/service/workspaces/list_pages_gen.go
Modified the `listpages` generator to generate interface types for AWS SDK for Go v1 API clients.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/25238.
=> Tech debt: Use interface type for generated `listpages` AWS SDK for Go v1 API clients

website/docs/r/api_gateway_model.html.markdown, website/docs/r/apigatewayv2_model.html.markdown, website/docs/r/applicationinsights_application.html.markdown, website/docs/r/autoscaling_group.html.markdown, website/docs/r/autoscaling_lifecycle_hook.html.markdown, website/docs/r/batch_job_definition.html.markdown, website/docs/r/ce_anomaly_monitor.html.markdown, website/docs/r/cloudformation_stack.html.markdown, website/docs/r/cloudformation_stack_set.html.markdown, website/docs/r/cloudwatch_dashboard.html.markdown, website/docs/r/cloudwatch_event_archive.html.markdown, website/docs/r/cloudwatch_event_rule.html.markdown, website/docs/r/cloudwatch_event_target.html.markdown, website/docs/r/codecommit_approval_rule_template.html.markdown, website/docs/r/connect_contact_flow.html.markdown, website/docs/r/connect_contact_flow_module.html.markdown
=> Replace heredoc with jsonencode (r/a*, r/b*, r/c*)

website/docs/r/dlm_lifecycle_policy.markdown, website/docs/r/ecr_repository_policy.html.markdown, website/docs/r/ecrpublic_repository_policy.html.markdown, website/docs/r/efs_file_system_policy.html.markdown, website/docs/r/eks_cluster.html.markdown, website/docs/r/elasticsearch_domain.html.markdown, website/docs/r/emr_cluster.html.markdown
=> Replace heredoc with aws_iam_policy_document datasource (r/d*, r/e*)

website/docs/r/backup_selection.html.markdown, website/docs/r/backup_vault_policy.html.markdown, website/docs/r/batch_compute_environment.html.markdown, website/docs/r/budgets_budget_action.html.markdown, website/docs/r/cloudfront_realtime_log_config.html.markdown, website/docs/r/cloudsearch_domain_service_access_policy.html.markdown, website/docs/r/cloudtrail.html.markdown, website/docs/r/cloudwatch_event_target.html.markdown, website/docs/r/cloudwatch_metric_stream.html.markdown, website/docs/r/codeartifact_domain_permissions_policy.html.markdown, website/docs/r/codeartifact_repository_permissions_policy.html.markdown, website/docs/r/codebuild_project.html.markdown, website/docs/r/codebuild_report_group.html.markdown, website/docs/r/codedeploy_deployment_group.html.markdown, website/docs/r/codepipeline.markdown, website/docs/r/cognito_identity_pool_roles_attachment.markdown, website/docs/r/cognito_user_group.html.markdown, website/docs/r/cognito_user_pool_client.markdown, website/docs/r/config_config_rule.html.markdown, website/docs/r/config_configuration_aggregator.html.markdown, website/docs/r/config_configuration_recorder.html.markdown, website/docs/r/config_configuration_recorder_status.html.markdown, website/docs/r/config_delivery_channel.html.markdown
=> Replace heredoc with aws_iam_policy_document datasource (r/b*, r/c*)

website/docs/d/organizations_delegated_administrators.html.markdown
=> d-Update organizations_delegated_administrators.html.markdown

.github/workflows/firewatch.yml
Updates to https://github.com/breathingdust/firewatch/releases/tag/v2.0.4
=> Update Firewatch to SHA (2.0.4)

.github/workflows/milestone.yml
Pin and update current-milestone-action to : https://github.com/breathingdust/current-milestone-action/releases/tag/v5.0.0
=> Pin current-milestone-action to SHA

website/docs/r/ce_anomaly_subscription.html.markdown
Provide example usage using new `threshold_expression` arg block
Closes #29317
=> aws_ce_anomaly_subscription - add example using threshold_expression

.github/workflows/post_publish.yml
Pins github-jira-tidy to SHA at release v0.9.0: https://github.com/breathingdust/github-jira-tidy/releases/tag/v0.9.0
=> Pin github-jira-tidy to SHA

docs/add-a-new-datasource.md, docs/add-a-new-resource.md
=> docs: update contributor docs for creating new resources and datasources

.github/workflows/team_slack_bot.yml
Update and Pin to SHA: https://github.com/breathingdust/github-team-slackbot/releases/tag/v18.0.0
=> Pin GHA: github-team-slackbot to SHA

CHANGELOG.md
The next release will be **v4.57.1**, including https://github.com/hashicorp/terraform-provider-aws/pull/29812.
=> Update CHANGELOG: Next release will be `v4.57.1`

website/docs/r/sagemaker_domain.html.markdown
Small change to resolve a documentation issue regarding SageMaker domain name.
=> Fix domain_name newline in website docs

.actrc, .github/workflows/acctest-terraform-lint.yml, .github/workflows/changelog.yml, .github/workflows/dependencies.yml, .github/workflows/documentation.yml, .github/workflows/examples.yml, .github/workflows/golangci-lint.yml, .github/workflows/goreleaser-ci.yml, .github/workflows/providerlint.yml, .github/workflows/release.yml, .github/workflows/skaff.yml, .github/workflows/snapshot.yml, .github/workflows/terraform_provider.yml, .github/workflows/website.yml, .github/workflows/workflow-lint.yml
Use `go.mod` for Go version in GitHub Actions.
Closes https://github.com/hashicorp/terraform-provider-aws/issues/29630.
N/A
=> Use `go.mod` for Go version in GitHub Actions

website/docs/r/api_gateway_account.html.markdown
This PR will update the website document for `Resource: aws_api_gateway_account`.
Modify policy reference for resource aws_iam_role_policy.cloudwatch.
N/A
[Resource: aws_api_gateway_account](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/api_gateway_account)
N/A
=> docs: Modify policy reference for resource aws_iam_role_policy.cloudwatch

website/docs/r/organizations_policy.html.markdown
The example given for the aws_iam_policy_document data source in this documentation is incorrect. It needs to have a 'statement {}' block, this PR adds the necessary block.
This was a simple fix so I didn't open an issue.
=> Fixed aws_iam_policy_document data source example and added the necessary 'statement' block.

website/docs/r/sesv2_email_identity.html.markdown
https://github.com/hashicorp/terraform-provider-aws/issues/29729
=> [Docs]: Code Example for aws_sesv2_email_identity (BYODKIM) is misleading

website/docs/r/dx_private_virtual_interface.html.markdown, website/docs/r/dx_transit_virtual_interface.html.markdown
Documents the `sitelink_enabled` argument for the `aws_dx_private_virtual_interface` and `aws_dx_transit_virtual_interface` resources.
Closes https://github.com/hashicorp/terraform-provider-aws/issues/29908.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/22350.
Relates https://github.com/hashicorp/terraform-provider-aws/issues/22187.
=> Document Direct Connect SiteLink support

website/docs/r/sagemaker_app.html.markdown
=> fix r/sagemaker_app typos

website/docs/r/budgets_budget.html.markdown
Update aws_budgets_budget documentation with correct link to AWS documentation and new examples of how to use TagKeyValue cost filter
Closes #29888
```
...
```
=> docs: update aws_budgets_budget documentation

.changelog/29917.txt
=> chore: add CHANGELOG for PR 29917

.github/workflows/changelog.yml, .github/workflows/dependencies.yml, .github/workflows/goreleaser-ci.yml
Pin action to SHA at v2.11.1 https://github.com/dorny/paths-filter/commit/4512585405083f25c027a35db413c2b3b9006d50
=> Pin dorny/paths-filter to SHA (v2.11.1)

website/docs/d/eks_clusters.html.markdown
`aws_eks_cluster` != `aws_eks_clusters`
Relates #30065
N/a
N/a, docs
=> Correct page title on aws_eks_clusters data source

.github/workflows/codeql-analysis.yml
Pin github/codeql-action to v2.2.7: https://github.com/github/codeql-action/commit/a589d4087ea22a0a48fc153d1b461886e262e0f2
=> Pin github/codeql-action to v2.2.7

.github/workflows/documentation.yml, .github/workflows/website.yml
Pin yakdriver/md-check-links to sha at v2.0.5
https://github.com/YakDriver/md-check-links/commit/9044b7162323b91150cef35355e1a3514564aa82
=> Pin yakdriver/md-check-links to sha at v2.0.5

.github/workflows/changelog.yml, .github/workflows/community-comment.yml, .github/workflows/dependencies.yml, .github/workflows/maintainer-edit.yml
Pin peter-evans/create-or-update-comment to SHA: https://github.com/peter-evans/create-or-update-comment/commit/67dcc547d311b736a8e6c5c236542148a47adc3d
=> Pin peter-evans/create-or-update-comment to v2.1.1

website/docs/r/lightsail_instance.html.markdown
This is a small PR to further clarify how to use `user_data` with lightsail instances and provide an example in the docs.
Closes #20909
```
...
```
=> Website: Amend `lightsail_instance`, Add details and example for user_data

website/docs/r/vpc_ipam_resource_discovery_association.html.markdown
Fix wrong variables for `aws_vpc_ipam_resource_discovery_association` resource.
- (Deleted) `description` - Not Supported
- (Added) `tags`
Update outputs for `aws_vpc_ipam_scope` resource.
Terraform actually prints that output.
```sh
+ resource "aws_vpc_ipam_resource_discovery_association" "this" {
+ arn                        = (known after apply)
+ id                         = (known after apply)
+ ipam_arn                   = (known after apply)
+ ipam_id                    = "..."
+ ipam_region                = (known after apply)
+ ipam_resource_discovery_id = "..."
+ is_default                 = (known after apply)
+ owner_id                   = (known after apply)
+ state                      = (known after apply)
+ tags                       = {
...
}
+ tags_all …
```
=> Update vpc_ipam_resource_discovery_association docs

.github/workflows/documentation.yml, .github/workflows/terraform_provider.yml, .github/workflows/website.yml
Pin avto-dev/markdown-lint to SHA v1.5: https://github.com/avto-dev/markdown-lint/commit/04d43ee9191307b50935a753da3b775ab695eceb
=> Pin avto-dev/markdown-lint to SHA v1.5

.github/workflows/firewatch.yml, .github/workflows/release.yml, .github/workflows/snapshot.yml
Pin actions/upload-artifact to SHA v3.1.2: https://github.com/actions/upload-artifact/commit/0b7f8abb1508181956e8e162db84b466c27e18ce
=> Pin actions/upload-artifact to SHA v3.1.2

.github/workflows/examples.yml, .github/workflows/terraform_provider.yml
Pin hashicorp/setup-terraform to SHA v2.0.3: https://github.com/hashicorp/setup-terraform/commit/633666f66e0061ca3b725c73b2ec20cd13a8fdd1
=> Pin hashicorp/setup-terraform to SHA v2.0.3

GNUmakefile
=> makefile: Fix bad phony, order

website/docs/d/rds_reserved_instance_offering.html.markdown, website/docs/r/rds_reserved_instance.html.markdown
Fix wrong variables for `aws_rds_reserved_instance` resource.
- (Deleted) `instance_id` - No exist.
- (Added) `reservation_id`
Fix wrong outputs for `aws_rds_reserved_instance` resource .
- (Deleted) `instance_class` - No exist.
- (Added) `db_instance_class`
Update docs for `aws_rds_reserved_instance_offering` data source.
Closes #0000
```
...
```
=> Fix rds reserved instance docs

go.mod, go.sum, internal/conns/awsclient_gen.go, internal/conns/config_gen.go, names/names_data.csv
This PR contains the client gen as the first step of the new resource PR of AWS Recycle Bin.
Relates #25926
```
...
```
=> AWS Recycle Bin client gen

.changelog/30140.txt
Adds CHANGELOG entry for #30140
=> Adds CHANGELOG entry for #30140

.github/workflows/golangci-lint.yml, internal/framework/attrtypes_test.go, internal/service/cloudformation/stack_set_test.go, internal/service/codebuild/project_test.go, internal/service/glue/data_catalog_encryption_settings_data_source_test.go, internal/service/glue/data_catalog_encryption_settings_test.go, internal/service/mediaconvert/queue_test.go, internal/service/rds/blue_green.go, internal/service/rds/instance_test.go, internal/service/s3/bucket_replication_configuration_test.go, internal/service/s3control/bucket_lifecycle_configuration_test.go, internal/service/s3control/bucket_test.go, internal/service/storagegateway/cached_iscsi_volume_test.go
Updates GitHub Actions to use same version of `golangci-lint` as set in `.ci/tools/go.mod`
=> Updates version of `golangci-lint` used in GitHub actions

.changelog/26908.txt
Missing "`".
Relates #29064.
Relates #26908.
=> Fix CHANGELOG entry

.changelog/30299.txt
=> r/aws_fsx_openzfs_file_system: fix changelog entry

.github/workflows/pull_request_feed.yml
Adds actions to notify feed channel of merged PR's and raised maintainer PR's
=> [Internal] GHA Workflows for Feed - PullRequest

.github/workflows/community-check.yml
=> Allow commcheck to work on forks

website/docs/r/cloudfront_distribution.html.markdown
Fix the CachingDisabled managed policy id. ([ref](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/using-managed-cache-policies.html))
=> [docs] Fix managed policy id

.github/workflows/changelog.yml, .github/workflows/dependencies.yml
Attempts to fix issues with `dependencies` and `changelog` checks.
=> Add string equality checks to dependencies and changelog actions.

infrastructure/repository/community.tf
=> Remove unecessary maintainer_list secret and add dependabot as a maintainer

.changelog/30536.txt
=> Add changelog

.github/workflows/pull_request_feed.yml
Reduces noise to the channel by filtering out dependabot PR open's
=> Filter out dependabot from feed pr open action

internal/service/codeartifact/domain.go
Adds a retry for KMS Key propagation when creating `aws_codeartifact_domain`
Prevents
> Error: creating CodeArtifact Domain: ValidationException: KMS key not found:
```
$ make testacc PKG=codeartifact TESTS=TestAccCodeArtifact_serial
--- PASS: TestAccCodeArtifact_serial (410.06s)
--- PASS: TestAccCodeArtifact_serial/Domain (57.84s)
--- PASS: TestAccCodeArtifact_serial/Domain/tags (27.75s)
--- PASS: TestAccCodeArtifact_serial/Domain/basic (11.61s)
--- PASS: TestAccCodeArtifact_serial/Domain/defaultEncryptionKey (10.82s)
--- PASS: TestAccCodeArtifact_serial/Domain/disappears (7.66s)
--- PASS: TestAccCodeArtifact_serial/DomainPermissionsPolicy (64.94s)
--- PASS: TestAccCodeArtifact_serial/DomainPermissionsPolicy/basic (19.17s)
--- PASS: …
```
=> Adds retry when KMS key not found

.changelog/12310.txt, internal/service/quicksight/service_package_gen.go, internal/service/quicksight/user.go, internal/service/quicksight/user_data_source.go, internal/service/quicksight/user_data_source_test.go, website/docs/d/quicksight_user.html.markdown
Relates to #10990
```release-note
New data source aws_quicksight_user
```
```
$ make testacc TESTARGS='-run=TestAccAWSDataSourceQuickSightUser' …
```
=> Data source aws_quicksight_user

.changelog/30704.txt, internal/service/quicksight/data_set.go
Added a fix for create data set
Reference to catalog and schema were incorrect 
Closes #30702
```
...
```
=> Updated catalog and schema reference for quicksight data set

.changelog/30701.txt, internal/service/quicksight/data_set.go
=> Fix to properly flatten `cast_column_type_operation.format` field

.changelog/30699.txt, internal/service/quicksight/data_set.go
=> Fix to properly expand `project_operation.projected_columns` field

.ci/.golangci2.yml, internal/service/ce/anomaly_subscription.go
Added nolint for Threshold of anomaly_subscription
Relates #30326
=> Added nolint for Threshold of anomaly_subscription

.changelog/30742.txt, website/docs/r/quicksight_data_set.html.markdown
=> Correct aws_quicksight_data_set custom_sql documentation

.github/workflows/release-tag.yml
Adds notification when a release tag is pushed.
=> Feed: Add release tag notifier

.github/workflows/project-roadmap-label.yml
Moves any issue/pr labelled with `roadmap` to the working board.
=> Workflow: Add `roadmap` labeled issue to working board

website/docs/r/amplify_branch.html.markdown
During my process of creating an Amplify app, I found that the final step to create a SNS subscription was not included in the documentation for the Amplify branch. Thus, I've added this final step to finish the SNS setup, namely the subscription. I've used the email protocol in the example, as this is what I used when I set up my Amplify app through the GUI.
N/A
N/A
N/A
=> Added SNS topic subscription

CHANGELOG.md
Ibid.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/29278.
=> Add missing `v4.64.0` CHANGELOG entry

.changelog/30832.txt, CHANGELOG.md
Ibid.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/30832.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/30482.
=> Add missing CHANGELOG entry and correct one

.changelog/30735.txt, website/docs/r/fms_policy.html.markdown
Update the documentation for `aws_fms_policy` to state that the `orgunit` configuration needs to specify the ID(s) of the mentioned organizational units.
Closes #30464
=> Update aws_fms_policy documentation to mention IDs for orgunit

.ci/semgrep/migrate/context.yml, .github/workflows/semgrep-ci.yml, GNUmakefile
Adds validation checks for Semgrep rules using `semgrep --validate ...`
=> Adds validation for Semgrep rules

CHANGELOG.md
Ibid.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/28201#issuecomment-1527126539.
=> Correct v4.65.0 CHANGELOG entry

.changelog/31031.txt, internal/service/sagemaker/domain.go, internal/service/sagemaker/domain_test.go, internal/service/sagemaker/sagemaker_test.go, website/docs/r/sagemaker_domain.html.markdown
Closes #22789
```
$ make testacc TESTS=TestAccSageMaker_serial/Domain PKG=sagemaker
PASS: TestAccSageMaker_serial/Domain/rStudioServerProAppSettings (259.35s)
```
=> sagemaker_domain - rstudio pro and model register args

.github/workflows/project-partner-label.yml
Correct workflow to use PR payloads
=> Workflow: Use Pullrequest event payload

.github/workflows/project-partner-label.yml, .github/workflows/project-roadmap-label.yml
Resolves permissions issues for newly added roadmap/partner label actions.
=> Workflow: Use org scoped token for workflows using an org level project

website/docs/r/db_instance.html.markdown
Adding examples for RDS Custom for Oracle.
Closes #0000
Documentation changes only.
=> Added RDS Custom for Oracle examples

website/docs/guides/version-4-upgrade.html.md
Some corrections and updates to the _Terraform AWS Provider Version 4 Upgrade Guide_.
=> Changes to the Version 4 Upgrade Guide

website/docs/guides/version-5-upgrade.html.md
The _Terraform AWS Provider Version 5 Upgrade Guide_.
Relates https://github.com/hashicorp/terraform-provider-aws/issues/29842.
=> Terraform AWS Provider Version 5 Upgrade Guide

.changelog/31071.txt, internal/service/glue/catalog_database.go, internal/service/glue/catalog_database_test.go, internal/service/glue/find.go, internal/service/glue/service_package_gen.go, website/docs/r/glue_catalog_database.html.markdown
```
$ make testacc TESTS=TestAccGlueCatalogDatabase_tags PKG=glue
--- PASS: TestAccGlueCatalogDatabase_tags (63.00s)
```
=> r/glue_catalog_database - add tagging support

website/docs/r/medialive_multiplex_program.html.markdown
update documentation
Relates #31034
```
...
```
=> docs: remove statemux from `aws_medialive_multiplex_program`

website/docs/r/rbin_rule.html.markdown
resource_tag_key is a expecting a string. Documentation should include quotes in the example.
Closes #0000
No acceptance test is needed.
=> d/aws_rbin_rule: Add missing quotes in the example.

.teamcity/scripts/pullrequest_tests/tests.sh, .teamcity/settings.kts
Enables assuming role for pull request configurations
N/A
=> CI: Enables assuming role for pull request configuration

.changelog/31247.txt, internal/service/s3/hosted_zones.go
https://docs.aws.amazon.com/general/latest/gr/s3.html#s3_region
https://github.com/hashicorp/terraform-provider-aws/blob/main/docs/add-a-new-region.md#update-region-specific-values-in-static-data-sources
=> data_source: cn-north-1 (Beijing) hostedZoneID

website/docs/r/cognito_user_in_group.html.markdown
Fix example in cognito_user_in_group doc so it wont fail when run with Terraform
Closes #31234
=> Fix cognito_user_in_group doc example

website/docs/r/vpclattice_target_group.html.markdown
=> Fix typo in VPCLattice Target Group docs

website/docs/guides/version-5-upgrade.html.md
Changes to the v5 upgrade guide to make it more complete and user friendly.
Closes #0000
```
...
```
=> Revise v5 upgrade guide

internal/service/elasticache/global_replication_group_test.go, internal/service/elasticache/replication_group_data_source_test.go, internal/service/elasticache/replication_group_test.go
Fix various test failures associated with breaking changes
Closes #31493
```console
$ make testacc TESTARGS='-run=TestAccElastiCacheGlobalReplicationGroup_basic' PKG=elasticache
TF_ACC=1 go test ./internal/service/elasticache/... -v -count 1 -parallel 20  -run=TestAccElastiCacheGlobalReplicationGroup_basic -timeout 180m
--- PASS: TestAccElastiCacheGlobalReplicationGroup_basic (975.99s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/elasticache	979.197s
```
=> [Tests] elasticache

.changelog/30545.txt, website/docs/guides/version-5-upgrade.html.md
=> add changelog for launch template

.teamcity/components/service_build_config.kt, .teamcity/settings.kts
Enables TeamCity build notifications via Slack
N/A
=> CI: Enables build notifications

.changelog/31422.txt, internal/service/grafana/workspace.go
=> fix: bump Grafana Workspace to 30 minutes

website/docs/d/ec2_transit_gateway_route_tables.html.markdown
=> d/ec2_transit_gateway_route_tables: Fix example typo

internal/service/vpclattice/resource_policy_data_source_test.go
Ibid.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/31372.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/31161.
=> Fix compilation error: `cannot use acctest.ErrorCheck(t, names.VPCLatticeEndpointID) ...`

internal/service/cognitoidentity/pool_roles_attachment.go, internal/service/configservice/organization_custom_policy_rule.go, internal/service/configservice/organization_custom_rule.go, internal/service/configservice/organization_managed_rule.go, internal/service/configservice/validate.go, internal/service/ec2/ec2_availability_zones_data_source.go, internal/service/guardduty/ipset.go, internal/service/guardduty/threatintelset.go, internal/service/opensearch/domain.go, internal/service/redshift/event_subscription.go, internal/service/route53/health_check.go
https://github.com/hashicorp/terraform-provider-aws/issues/14601, https://github.com/hashicorp/terraform-provider-aws/pull/24286
=> source enum validations from AWS Go SDK

ROADMAP.md
=> Fix `ROADMAP.md` linter errors

website/docs/r/db_instance_automated_backups_replication.markdown, website/docs/r/dynamodb_table_replica.html.markdown, website/docs/r/dynamodb_tag.html.markdown, website/docs/r/route53_vpc_association_authorization.html.markdown, website/docs/r/sns_topic_subscription.html.markdown, website/docs/r/vpc_endpoint_connection_accepter.html.markdown
These examples will all currently cause deprecation warnings.
=> Documentation Improvement: Remove quotes around provider names

website/docs/r/transfer_user.html.markdown
Just a small English grammar mistake.
Just a small grammar mistake. `controls` should be `control`.
=> docs: grammar

.changelog/31849.txt, website/docs/r/quicksight_refresh_schedule.html.markdown
=> `r/aws_quicksight_refresh_schedule`: Correct `time_of_the_day` parameter name

.changelog/31900.txt, internal/service/quicksight/service_package_gen.go, internal/service/quicksight/status.go, internal/service/quicksight/theme.go, internal/service/quicksight/theme_data_source.go, internal/service/quicksight/theme_data_source_test.go, internal/service/quicksight/theme_test.go, internal/service/quicksight/wait.go, website/docs/d/quicksight_theme.html.markdown, website/docs/r/quicksight_theme.html.markdown
* New resource for Quicksight Theme.
* New data source for Quicksight Theme.
Closes #31898
Closes #31899
https://docs.aws.amazon.com/quicksight/latest/APIReference/API_CreateTheme.html
https://docs.aws.amazon.com/quicksight/latest/APIReference/API_DescribeTheme.html
https://docs.aws.amazon.com/quicksight/latest/APIReference/API_DescribeThemePermissions.html
https://docs.aws.amazon.com/quicksight/latest/APIReference/API_UpdateTheme.html
https://docs.aws.amazon.com/quicksight/latest/APIReference/API_DeleteTheme.html
```
$ make testacc TESTS=TestAccQuickSightTheme PKG=quicksight
TF_ACC=1 go test ./internal/service/quicksight/... -v -count 1 -parallel 20 -run='TestAccQuickSightTheme'  -timeout 180m
=== RUN …
```
=> New resource and data source aws_quicksight_theme

.github/workflows/cdktf-documentation.yml
Otherwise we can not create the PR.
e.g. https://github.com/hashicorp/terraform-provider-aws/actions/runs/5268486043/jobs/9525225067.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/31983.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/31596.
=> cdktf: use org scoped token for creating a PR

website/docs/r/ssm_patch_baseline.html.markdown
=> r/ssm_patch_baseline: Update list of supported OSes

website/docs/r/glue_crawler.html.markdown
- Fix typo in description of `crawler_lineage_settings`
- Valid default value for `crawler_lineage_settings` is `DISABLE`, not `Disable`.
=> Fix typo in description of `crawler_lineage_settings`

website/docs/r/opensearchserverless_security_policy.html.markdown
Example of network policy using the `aws_opensearchserverless_security_policy` resource.
```
...
```
=> [docs] opensearchserverless/security_policy: add example for network policy

website/docs/guides/continuous-validation-examples.html.md
Adds a new continuous validation example using the `aws_iam_role` data source.
Relates #31910 
N/a docs.
=> [Docs]: Add `aws_iam_role` continuous validation example

.changelog/31903.txt
=> Tidy up CHANGELOG entry (#31903)

website/docs/r/db_instance.html.markdown
Fixes a broken link in `r/db_instance.html`.
Closes #0000
```
...
```
=> fix: broken anchor link in RDS db_instance docs

.github/workflows/post_publish.yml
Updates to newest release as well as using the SHA
=> Update GHA ref to sha (github-project-archive)

website/docs/r/dms_replication_task.html.markdown
Documentation update.
```
...
```
=> [Docs ]dms/replication_task: move status attribute to exported section

website/docs/r/kinesis_firehose_delivery_stream.html.markdown
Documentation change to set variable from 'Optional' to 'Required' in line with functionality
Closes #32113
=> doc fix for aws kinesis doc

CHANGELOG.md
Corrects the unreleased version number in the CHANGELOG.
=> Next release is `v5.6.1`

.ci/tools/go.mod, .ci/tools/go.sum, .ci/tools/main.go, .github/workflows/terraform_provider.yml, GNUmakefile, website/docs/r/kendra_query_suggestions_block_list.html.markdown
=> kendra: Calliope first docs edit

website/docs/r/cloudfront_cache_policy.html.markdown
=> cloudfront: Calliope docs edit

CHANGELOG.md
Corrects the unreleased version number in the CHANGELOG.
=> Next release is `v5.6.2`

website/docs/r/cloudfront_cache_policy.html.markdown
=> cloudfront: Update cache_policy docs

website/docs/r/cognito_managed_user_pool_client.html.markdown
=> cognito: Managed user dead pool client docs update

website/docs/r/pinpoint_sms_channel.markdown
=> pinpoint: Update sms_channel docs

.ci/tools/go.mod, .ci/tools/go.sum, website/docs/d/servicecatalog_product.html.markdown, website/docs/r/ec2_managed_prefix_list_entry.html.markdown
=> ec2, servicecatalog docs

website/docs/r/wafv2_web_acl_logging_configuration.html.markdown
=> wafv2 web acl logging configuration docs

website/docs/d/opensearchserverless_vpc_endpoint.html.markdown
=> [docs]: fix documentation with correct attribute reference

website/docs/r/opensearchserverless_security_policy.html.markdown
- Adds additional examples on how to use the `aws_opensearchserverless_security_policy` resource
- Links to AWS documentation as argument values are likely to update over time
N/A
- [Encryption policies](https://docs.aws.amazon.com/opensearch-service/latest/developerguide/serverless-encryption.html#serverless-encryption-policies)
- [Network policies](https://docs.aws.amazon.com/opensearch-service/latest/developerguide/serverless-network.html#serverless-network-policies)
N/A
Verified the Terraform configurations were valid by applying `terraform apply`.
```
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
+ create
+ resource …
```
=> docs: Add examples and AWS documentation to `aws_opensearchserverless_security_policy` resource

website/docs/r/appsync_datasource.html.markdown
documentation update
```
...
```
=> [docs]: appsync/datasource: add missing documentation

website/docs/r/kendra_data_source.html.markdown
Update example using config block and headers
Closes #29993
=> aws_kendra_data_source - fix example

internal/service/ssoadmin/sweep.go
Sweepers were not correctly ignoring errors returned by `sdk.ReadResource`
Was returning errors like
> 	- aws_ssoadmin_permission_set: reading SSO Instances: AccessDeniedException: User: arn:aws:sts::123456789012:assumed-role/xxxxx is not authorized to perform: sso:ListInstances
>	- aws_ssoadmin_account_assignment: reading SSO Instances: AccessDeniedException: User: arn:aws:sts::123456789012:assumed-role/xxxxx is not authorized to perform: sso:ListInstances
=> sweeper: SSO resources

docs/design-decision-log.md, mkdocs.yml
Adds a section to our contribution guide to record and display decision making related to best practice and design standards. The intent is to bring this internal process to the public, and allow improved opportunity for feedback from the community and our core contributors. It also serves as a point of reference for related discussions around design which may or may not align to the standard.
=> Decision Log Framework

.changelog/32285.txt, internal/service/quicksight/schema/visual.go
=> `r/aws_quicksight_analysis`: Correctly expand comparison method

website/docs/r/elasticache_cluster.html.markdown
Fixed inconsistency in ElastiCache resource documentation
Closes #32542 
```
...
```
=> Moved log delivery config

.github/workflows/resource-counts.yml
Updates action to use GitHub app in order to source a token with the correct scopes to be able to create a PR.
=> Workflow: Update resource count action to use app token

infrastructure/repository/labels-workflow.tf
Some label updates relating to internal process improvements
=> Label Updates

infrastructure/repository/labels-workflow.tf
Shortens new label description to fix maxlength
=> Shorten description to fit max length

examples/opensearchserverless/README.md, examples/opensearchserverless/main.tf, examples/opensearchserverless/outputs.tf, examples/opensearchserverless/variables.tf, examples/opensearchserverless/vpc.tf
Created a comprehensive example for creating an OpenSearch Serverless collection with an encryption, network, and data access policy along with an OpenSearch Serverless-managed VPC endpoint and its required VPC resources.
N/A
- https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/opensearchserverless_access_policy
- https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/opensearchserverless_collection
- https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/opensearchserverless_security_policy
- https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/opensearchserverless_vpc_endpoint
- https://docs.aws.amazon.com/opensearch-service/latest/developerguide/serverless.html
N/A
Ran `terraform apply` in the …
=> docs: Add example for `aws_opensearchserverless` resources

.github/PULL_REQUEST_TEMPLATE.md, skaff/resource/websitedoc.tmpl
=> skaff: Update website template for new import format

.changelog/32644.txt
=> Update CHANGELOG entries

infrastructure/repository/projects.tf
This PR adds helpful GitHub Actions variables for the new View field in the main team Project
Relates #32605
N/a, infrastructure updates
=> Update projects Terraform config for View field

.github/workflows/issues.yml
This PR corrects a syntax error in `issues.yml` that prevented the service labeler from ever running.
N/a, Actions
=> Correct syntax error in `issues.yml`

website/docs/r/opensearchserverless_collection.html.markdown
With the Go SDK update to `aws/aws-sdk-go-v2/service/opensearchserverless v1.3.1`, a new collection type of `VECTORSEARCH` was introduced. This updates the documentation for the `aws_opensearchserverless_collection` resource to include the new collection type.
Relates #32729
- https://docs.aws.amazon.com/opensearch-service/latest/ServerlessAPIReference/API_CreateCollection.html#API_CreateCollection_RequestSyntax
N/A
Created a `VECTORSEARCH` collection to verify functionality
```terraform
terraform {
required_version = ">= 0.12"
}
region = "us-east-1"
}
resource "aws_opensearchserverless_security_policy" "encryption_policy" {
name        = "vectorsearch-encryption-policy"
type        = "encryption"
description = "encryption policy"
policy = jsonencode({
Rules = [
{ …
```
=> docs: Add `VECTORSEARCH` collection type to aws_opensearchserverless_collection documentation

docs/design-decision-log.md, docs/design-decisions/relationship-resource-design-standards.md
A proposal to align on design standards for relationship management resources in the Terraform AWS Provider. The branches [rendered markdown](https://github.com/hashicorp/terraform-provider-aws/blob/d-relationship-resource-rfc/docs/design-decisions/relationship-resource-design-standards.md) may be preferable for readability.
This document is public facing to allow for community feedback before approval.  Please leave suggestions in the form of review comments or general comments on the PR.
Relates #9901 
Relates #32380
=> [Design Decision]: Relationship Resource Design Standards

website/docs/r/dynamodb_tag.html.markdown
- fix `dynamodb_tag` docs example
=> docs: fix dynamodb_tag example doc

internal/service/iam/group_policy_test.go
Fixes the failing `TestAccIAMGroupPolicy_unknownsInPolicy` acceptance test.
```
$ make testacc PKG=iam TESTS=TestAccIAMGroupPolicy_unknownsInPolicy
TF_ACC=1 go test ./internal/service/iam/... -v -count 1 -parallel 20 -run='TestAccIAMGroupPolicy_unknownsInPolicy'  -timeout 180m
group_policy_test.go:184: Step 1/1 error: Error running apply: exit status 1
Error: creating S3 bucket ACL for tf-acc-test-7160076932700509089: AccessControlListNotSupported: The bucket does not allow ACLs
status code: 400, request id: ZWVNE7DZ64Z47R2C, host id: qnjaPWI3YAMZXun4Z9y8kerPdXZrlEmMnMG1ayBMuNpthiYlenBYttYh9aNevgA8RbEg7t33apslD0ygqE8heA==
on terraform_plugin_test.tf line 15, in resource "aws_s3_bucket_acl" "test":
15: …
```
=> r/aws_iam_group_policy(test): rm unnecessary s3 bucket acl config

internal/service/cloudfront/distribution_test.go
Fixes various CloudFront Distribution acceptance tests. With the recent S3 security changes, the bucket ACL configuration now also requires public access and bucket ownership resources.
Relates #28353
```console
% make testacc PKG=cloudfront TESTS=TestAccCloudFrontDistribution_
TF_ACC=1 go test ./internal/service/cloudfront/... -v -count 1 -parallel 20 -run='TestAccCloudFrontDistribution_'  -timeout 180m
--- PASS: TestAccCloudFrontDistribution_Origin_emptyDomainName (6.44s)
=== CONT  TestAccCloudFrontDistribution_originPolicyDefault
--- PASS: TestAccCloudFrontDistribution_Origin_emptyOriginID (6.65s)
=== CONT  TestAccCloudFrontDistribution_orderedCacheBehaviorCachePolicy
--- PASS: …
```
=> r/aws_cloudfront_distribution(test): fix s3 bucket acl config

internal/service/ssoadmin/sweep.go
```console
2023/08/08 12:17:17 [DEBUG] Running Sweeper (aws_ssoadmin_account_assignment) in region (us-west-2)
[07:17:17 ](https://hashicorp.teamcity.com/buildConfiguration/Aws_Organizations_Sweeper/5847?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildProblemsSection=true&showLog=5847_190_190&logFilter=debug&logView=flowAware)  panic: interface conversion: interface {} is []interface {}, not *schema.Set
[07:17:17 ](https://hashicorp.teamcity.com/buildConfiguration/Aws_Organizations_Sweeper/5847?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildProblemsSection=true&showLog=5847_191_191&logFilter=debug&logView=flowAware)  
[07:17:17 ](https://hashicorp.teamcity.com/buildConfiguration/Aws_Organizations_Sweeper/5847?hideProblemsFromDepe …
```
=> [Sweper] aws_ssoadmin_account_assignment: assert correct type in data object

website/docs/r/cloudfront_distribution.html.markdown
Cosmetic changes to the `aws_cloudfront_distribution` example docs.
=> r/aws_cloudfront_distribution(doc): add example headings, tidy descriptions

.github/workflows/golangci-lint.yml
Run _golangci-linta_ on a custom runner.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/32945.
=> Increase `golangci-lint-action` timeout

.github/dependabot.yml
Adds a Dependabot [group](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#groups) for Terraform DevEx dependencies.
=> Add `terraform-devex` Dependabot group

.teamcity/components/service_build_config.kt
Check for string in build logs without case sensitivity
```console
...
```
=> teamcity: failure condition using regex

CHANGELOG.md
=> Next version is `v5.13.1`

.changelog/33120.txt, internal/service/quicksight/schema/analysis.go, internal/service/quicksight/schema/dashboard.go, internal/service/quicksight/schema/template.go
Changes the `parameter_declarations` argument in the Analysis, Dashboard, and Template resource to a set type to prevent persistent differences.
Closes #32996 
```console
%make testacc PKG=quicksight TESTARGS="-run TestAccQuickSightAnalysis_\|TestAccQuickSightDashboard_\|TestAccQuickSightTemplate_"
TF_ACC=1 go test ./internal/service/quicksight/... -v -count 1 -parallel 20  -run TestAccQuickSightAnalysis_\|TestAccQuickSightDashboard_\|TestAccQuickSightTemplate_ -timeout 180m
--- PASS: TestAccQuickSightTemplate_disappears (82.33s)
--- PASS: TestAccQuickSightTemplate_basic (91.18s)
--- PASS: TestAccQuickSightTemplate_barChart …
```
=> r/aws_quicksight: change parameter_declarations to set type

internal/service/ssoadmin/account_assignment_test.go
Closes #0000
```console
...
```
=> Fix regex, regexache error

internal/service/batch/job_queue.go, internal/service/batch/job_queue_schema.go
Closes #0000
```console
...
```
=> batch: Fix job queue lint

internal/service/batch/job_queue.go
Early return on error
```console
% make testacc TESTARGS='-run=TestAccBatchJobQueue_' PKG=batch
TF_ACC=1 go test ./internal/service/batch/... -v -count 1 -parallel 20  -run=TestAccBatchJobQueue_ -timeout 180m
--- PASS: TestAccBatchJobQueue_MigrateFromPluginSDK (117.46s)
--- PASS: TestAccBatchJobQueue_disappears (122.12s)
--- PASS: TestAccBatchJobQueue_basic (130.10s)
--- PASS: TestAccBatchJobQueue_ComputeEnvironments_externalOrderUpdate (131.31s)
--- PASS: TestAccBatchJobQueue_tags (174.42s)
--- PASS: TestAccBatchJobQueue_state (182.53s)
--- PASS: TestAccBatchJobQueue_schedulingPolicy (187.57s)
--- PASS: TestAccBatchJobQueue_priority (190.94s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/batch	194.453s …
```
=> aws_batch_job_queue: return on error

.github/labeler-issue-triage.yml, go.mod, go.sum, internal/conns/awsclient_gen.go, names/consts_gen.go, names/names_data.csv, website/allowed-subcategories.txt, website/docs/guides/custom-service-endpoints.html.md
Setup `make gen` for new service lexv2.
Relates #21375
=> Running setup to new service aws_lexv2

internal/service/ssm/association.go
```console
$ make testacc TESTARGS='-run=TestAccSSMAssociation_' PKG=ssm
TF_ACC=1 go test ./internal/service/ssm/... -v -count 1 -parallel 20  -run=TestAccSSMAssociation_ -timeout 180m
--- PASS: TestAccSSMAssociation_withDocumentVersion (52.59s)
--- PASS: TestAccSSMAssociation_withOutputLocation_waitForSuccessTimeout (55.57s)
--- PASS: TestAccSSMAssociation_syncCompliance (79.36s)
--- PASS: TestAccSSMAssociation_withAssociationName (87.63s)
--- PASS: TestAccSSMAssociation_withScheduleExpression (88.93s)
--- PASS: TestAccSSMAssociation_withAssociationNameAndScheduleExpression (89.57s)
--- PASS: TestAccSSMAssociation_withComplianceSeverity (89.66s)
--- PASS: TestAccSSMAssociation_withParameters (90.62s)
--- PASS: …
```
=> ssm/association: attributes in alphabetical order

website/docs/r/acmpca_certificate_authority.html.markdown
Update documentation for Private CA with revocation list example:
1. Add `s3_object_acl = "BUCKET_OWNER_FULL_CONTROL"` setting to `crl_configuration` to make the sample work
2. Add `force_destroy = true` option to S3 bucket so that terraform destroy does not fail when the revocation list is configured successfully
Closes #33306
NA
...
```
=> Update the example for Private CA with revocation list

website/docs/r/db_instance.html.markdown
Added RDS Custom for SQL Server example.
Relates #28765
* https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/custom-cev-sqlserver.html
=> Added RDS Custom for SQL Server example

.changelog/33317.txt
Closes #0000
```console
...
```
=> Changelog for 33317

website/docs/r/iot_provisioning_template.html.markdown
Update `aws_iot_provisioning_template` with default working example.
Closes #33347
=> r/aws_iot_provisioning_template: include enabled = true in example

internal/service/acm/certificate.go, internal/service/appflow/connector_profile.go, internal/service/appflow/flow.go, internal/service/codepipeline/codepipeline.go, internal/service/eks/identity_provider_config.go, internal/service/evidently/feature.go, internal/service/evidently/launch.go, internal/service/finspace/kx_cluster.go, internal/service/servicediscovery/instance.go, internal/verify/validate.go
`github.com/hashicorp/terraform-plugin-sdk/v2@v2.29.0` (https://github.com/hashicorp/terraform-provider-aws/pull/33344) adds `Diag`-flavor `Any` and `All` validator combinators.
Use these instead of our own versions in `internal/verify`.
Relates https://github.com/hashicorp/terraform-plugin-sdk/pull/1155.
=> Tech debt: Use Plugin SDK v2 `Any` and `All` `Diag`-flavor validator combinators

skaff/go.mod, skaff/go.sum
Closes #0000
```console
...
```
=> skaff mod tidy

CHANGELOG.md
=> Next release is `v5.16.1`

CHANGELOG.md
Closes #0000
```console
...
```
=> Add point release

.teamcity/scripts/oneliners.txt, .teamcity/scripts/sanity.sh, .teamcity/settings.kts
Closes #0000
```console
...
```
=> Add sanity TeamCity job

.teamcity/settings.kts
Closes #0000
```console
...
```
=> Add sanity buildType

.teamcity/settings.kts
Closes #0000
```console
...
```
=> Add write lock to TC sanity

.teamcity/scripts/sanity.sh
Closes #0000
```console
...
```
=> teamcity/sanity: No log

.teamcity/scripts/sanity.sh
Closes #0000
```console
...
```
=> Sanity job fix

.teamcity/settings.kts
Closes #0000
```console
...
```
=> Change sanity job notification settings

.teamcity/scripts/sanity.sh
Closes #0000
```console
...
```
=> teamcity/sanity: Handle text file busy

.teamcity/scripts/sanity.sh
Closes #0000
```console
...
```
=> teamcity/sanity: Fix bug in reporting status

website/docs/r/wafv2_web_acl_association.html.markdown
add missing resources to the WAFv2 Web ACL Association documentation
N/a, docs
N/a, docs
N/a, docs
...
```
=> improve WAFv2 Web ACL Association documentation

docs/skaff.md, skaff/cmd/datasource.go, skaff/cmd/resource.go, skaff/resource/resourcetest.tmpl
Changes the default `skaff` behavior to generate Plugin-Framework based resources.
Relates #32917
=> skaff: default to plugin framework

website/docs/r/ec2_network_insights_path.html.markdown
Fix a little typo in the 'destination' attribute description.
=> Fix destination argument description

website/docs/r/ami.html.markdown
Simple fix of duplicate attribute documentation. 
Closes #0000
```console
...
```
=> docs(docs/ami.html.markdown): remove duplicate attribute

.teamcity/scripts/performance.sh, GNUmakefile
Closes #0000
```console
...
```
=> teamcity/performance: Fix script

.teamcity/settings.kts
Closes #0000
```console
...
```
=> teamcity/sanity: Avoid double message

internal/service/codestarconnections/sweep.go, internal/service/codestarnotifications/sweep.go, internal/service/elasticsearch/sweep.go, internal/service/emrserverless/sweep.go, internal/service/iam/sweep.go, internal/service/opensearch/inbound_connection_accepter.go, internal/service/opensearch/outbound_connection.go, internal/service/opensearch/sweep.go, internal/service/quicksight/sweep.go, internal/service/route53/sweep.go, internal/service/s3control/sweep.go, names/names.go
Various sweeper fixes found while attempting to sweep US GovCloud account.
=> Tech debt: Various sweeper fixes

website/docs/d/vpclattice_service.html.markdown
- Fix typo in docs of `vpclattice_service` data source
=> Fix typo in docs of `vpclattice_service` data source

website/docs/d/vpclattice_service_network.html.markdown
- Fix data source docs of vpclattice_service_network
- Fix typo from `network service` to `service network`.
- Update example code with sample service network identifier.
=> Fix data source docs of vpclattice_service_network

website/docs/r/vpclattice_listener_rule.html.markdown
- Fix vpclattice_listener_rule resource docs
- The descriptions of some output attributes are incorrectly written as information about the target group.
=> Fix vpclattice_listener_rule resource docs

.changelog/33630.txt, CHANGELOG.md
Preparing the changelog for `v5.18.1`
Relates #33629 
Closes #33588
=> Prepare 5.18.1 release

website/docs/r/sfn_alias.html.markdown
- Refine docs for aws_sns_alias resource
- Remove unused example documentation in docs of `aws_sns_alias` resource.
- Update the description for `routing_configuration[].state_machine_version_arn`.
=> Refine docs for aws_sns_alias resource

website/docs/r/db_instance.html.markdown
correct website/docs/r/db_instance.html.markdown documentation typo from `contraints` to `constraints`
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/db_instance
=> Fix: correct typo from contraints to constraints

CHANGELOG.md, go.mod, go.sum
Addresses potential provider initialization errors when using Terraform 1.6.
Relates https://github.com/hashicorp/terraform-plugin-framework/pull/852.
Relates https://github.com/hashicorp/terraform-plugin-framework/issues/853.
Relates https://github.com/hashicorp/terraform/issues/33990.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/33849.
```console
% make testacc TESTARGS='-run=TestAccMetaARNDataSource_' PKG=meta
TF_ACC=1 go test ./internal/service/meta/... -v -count 1 -parallel 20  -run=TestAccMetaARNDataSource_ -timeout 360m
=== RUN   TestAccMetaARNDataSource_basic
=== PAUSE TestAccMetaARNDataSource_basic
=== RUN   TestAccMetaARNDataSource_s3Bucket
=== PAUSE TestAccMetaARNDataSource_s3Bucket
=== CONT …
```
=> Build with `terraform-plugin-framework@v1.4.1`

website/docs/r/elasticache_replication_group.html.markdown
Clarify the use of the [security_group_names](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/elasticache_replication_group#security_group_names) variable for elasticache
Closes #33890
=> docs: clarify security_group_names

website/docs/r/vpc_ipv6_cidr_block_association.html.markdown
- Fix typo in vpc_ipv6_cidr_block_association resource docs
=> Fix typo in vpc_ipv6_cidr_block_association resource docs

internal/enum/values.go, internal/framework/base.go, internal/framework/types/list_nested_objectof.go, internal/framework/types/set_nested_objectof.go
Framework helpers from another galaxy...
```console
% go test ./internal/framework/flex 
ok  	github.com/hashicorp/terraform-provider-aws/internal/framework/flex	0.560s
```
=> Tech debt: Some small Framework helpers

mkdocs.yml
Fixes the navbar link to the `Terraform Plugin Development Packages` page in the contributor docs.
Relates #33595
=> doc: fix terraform plugin development packages navbar link

website/docs/r/db_instance.html.markdown
Fixes the heading level of the `blue_green_update` section so it does not appear in the right navbar for the page.
=> aws_db_instance(doc): fix blue_green_update heading level

CHANGELOG.md
=> Next release is `v5.23.1`

docs/migrate-from-sdk-to-framework.md, mkdocs.yml
=> SDKv2 to Framework migration guide

website/docs/r/vpc_endpoint.html.markdown
Adding usage tips due to unintuitive defaults and options
Based on experience
Documentation only
=> improved resource tips

.github/workflows/library_versions.yml
This change should allow the checkout of the head ref to function correctly for pull requests coming from forks.
Relates #34184
=> ci: pass repository argument during head checkout

go.mod, go.sum
`dependabot` failed: https://github.com/hashicorp/terraform-provider-aws/network/updates/744461468.
=> AWS SDK for Go 11/01/2023 updates

website/docs/guides/continuous-validation-examples.html.markdown
Additional examples for the CV Check Block Guide
N/A Doc update.
=> Additional CV Guide Examples

website/docs/cdktf/python/r/appstream_image_builder.html.markdown, website/docs/cdktf/typescript/r/appstream_image_builder.html.markdown, website/docs/r/appstream_image_builder.html.markdown
Closes #0000
```console
...
```
=> correcting values for vpc_config block

website/docs/r/ssmcontacts_plan.html.markdown
This PR expands the documentation for the `aws_ssmcontacts_plan` resource by describing all the required configuration block details.
Closes #33683
- Validated the schema of `aws_ssmcontacts_plan` in the code at [internal/service/ssmcontacts/plan.go](https://github.com/hashicorp/terraform-provider-aws/blob/c4c48f075b1987385e8036572b1ed11c6c483ec1/internal/service/ssmcontacts/plan.go#L21).
- Referred to [Stage](https://docs.aws.amazon.com/incident-manager/latest/APIReference/API_SSMContacts_Stage.html) in AWS API reference for descriptions.
- Used the [`aws_instance`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/instance) doc for general guidance for structuring the documentation for configuration blocks.
n/a
=> docs: Improve config block descs for aws_ssmcontacts_plan

website/docs/d/ssm_parameters_by_path.html.markdown
This PR is for enhancing the documentation of the `aws_ssm_parameters_by_path` data source.
Closes #26840
- Argument and attribute descriptions were improved using [GetParametersByPath AWS API doc](https://docs.aws.amazon.com/systems-manager/latest/APIReference/API_GetParametersByPath.html) as a basis.
n/a
=> docs: Improve aws_ssm_parameters_by_path data source doc

.github/dependabot.yml
See https://github.com/hashicorp/terraform-provider-aws/pull/34300#issuecomment-1801819150
Relates #34300
Relates #34307
=> deps: ignore aws-sdk-go-v2/config

.github/dependabot.yml
This will prevent the need for manual intervention on automated dependabot updates until the upstream `config` package regression is fixed. Also added some additional context and links to the comments of this ignore section.
Relates #34300
Relates #34313
=> deps: add feature/s3/manager to temporary ignore list

.changelog/34338.txt, website/docs/r/codecommit_trigger.html.markdown
Small reformatting for `aws_codecommit_trigger` docs.
Closes #33506
=> Updated docs for aws_codecommit_trigger

website/docs/r/gamelift_build.html.markdown
Ibid.
Closes https://github.com/hashicorp/terraform-provider-aws/issues/34374.
=> r/aws_gamelift_build: Document all valid values for `operating_system`

website/docs/r/vpc_security_group_ingress_rule.html.markdown
improvement of aws_vpc_security_group_ingress_rule example
```console
...
```
=> improvement of aws_vpc_security_group_ingress_rule example

website/docs/r/controltower_control.html.markdown
Closes #0000
```console
...
```
=> Fix a typo on import controltower_control

go.mod, go.sum
Ibid.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/34432.
=> `github.com/aws/aws-sdk-go@v1.47.12`

.teamcity/settings.kts
Adds VPC lock to Performance TeamCity test
=> ci: Adds VPC lock to Performance test

go.mod, go.sum, internal/conns/awsclient_gen.go, internal/service/chimesdkmediapipelines/generate.go, internal/service/chimesdkmediapipelines/media_insights_pipeline_configuration.go, internal/service/chimesdkmediapipelines/media_insights_pipeline_configuration_test.go, internal/service/chimesdkmediapipelines/service_package_gen.go, internal/service/chimesdkmediapipelines/tags_gen.go, names/names.go, names/names_data.csv
```console
$ make testacc TESTARGS="-run=TestAccChimeSDKMediaPipelinesMediaInsightsPipelineConfiguration_" PKG=chimesdkmediapipelines
TF_ACC=1 go test ./internal/service/chimesdkmediapipelines/... -v -count 1 -parallel 20  -run=TestAccChimeSDKMediaPipelinesMediaInsightsPipelineConfiguration_ -timeout 360m
--- PASS: TestAccChimeSDKMediaPipelinesMediaInsightsPipelineConfiguration_disappears (139.40s)
--- PASS: TestAccChimeSDKMediaPipelinesMediaInsightsPipelineConfiguration_basic (186.60s)
--- PASS: TestAccChimeSDKMediaPipelinesMediaInsightsPipelineConfiguration_tags (274.82s)
--- PASS: TestAccChimeSDKMediaPipelinesMediaInsightsPipelineConfiguration_updateAllProcessorTypes (491.78s)
PASS
ok …
```
=> Migrate `chimesdkmediapipelines` to AWS Go SDKv2

website/docs/r/lexv2models_bot_locale.html.markdown
Add description of voice settings
```console
...
```
=> Add description of voice settings

docs/data-handling-and-conversion.md
=> doc: fix typo in flatten complex structure example

docs/data-handling-and-conversion.md
Still what the title says, missed in last update.
=> doc: fix another typo in flatten complex structure example

website/docs/r/glue_connection.html.markdown, website/docs/r/glue_crawler.html.markdown
Corrected the typo "JBDC" in the document to "JDBC".
I did not modify Python and TypeScript versions of the documentation, because I was told those files are generated automatically.
Closes #34421
```console
...
```
=> Docs: Correct typo JBDC to JDBC

.ci/semgrep/pluginsdk/diags.yml, docs/error-handling.md, docs/retries-and-waiters.md, internal/create/errors.go, internal/service/appautoscaling/policy.go, internal/service/appconfig/configuration_profile_data_source.go, internal/service/appconfig/configuration_profiles_data_source.go, internal/service/appconfig/environment_data_source.go, internal/service/appconfig/environments_data_source.go, internal/service/appconfig/extension.go, internal/service/appconfig/extension_association.go, internal/service/appstream/fleet.go, internal/service/lakeformation/resource_lf_tags.go, internal/service/ssm/default_patch_baseline.go, skaff/datasource/datasource.tmpl, skaff/resource/resource.tmpl
Adds Semgrep checks to use `Append...` versions of diags functions in `create`. Renames functions for consistency.
=> Updates to diags functions in `create`

go.mod, go.sum
=> 11/28/2023 AWS SDK for Go updates

docs/design-decisions/rds-bluegreen-deployments.md
Addresses architectural decisions around RDS Blue/Green Deployments with Aurora clusters or as a stand-alone resource
=> Architecture decision for RDS Blue/Green Deployments

docs/design-decision-log.md
=> Adds RDS blue green design decision link to design index page

go.mod, go.sum
dependabot timed out: https://github.com/hashicorp/terraform-provider-aws/network/updates/756352888.
=> 11/30/2023 AWS SDK for Go updates

go.mod, go.sum
dependabot timed out: https://github.com/hashicorp/terraform-provider-aws/network/updates/757738198
=> 12/01/2023 AWS SDK for Go updates

.changelog/34671.txt
Relates #34671
```console
...
```
=> r/backup_vault_policy: add CHANGELOG

website/docs/d/codeguruprofiler_profiling_group.html.markdown
=> d/cloudguruprofiler_profiling_group: update documentation

.changelog/34723.txt, internal/service/ssoadmin/application.go, internal/service/ssoadmin/application_test.go, internal/service/ssoadmin/exports_test.go, internal/service/ssoadmin/service_package_gen.go, website/docs/r/ssoadmin_application.html.markdown
The `aws_ssoadmin_application` resource will allow practitioners to manage customer managed SSO applications with Terraform.
Closes #27853 
Relates #28633 
- https://docs.aws.amazon.com/singlesignon/latest/APIReference/API_CreateApplication.html
- https://docs.aws.amazon.com/singlesignon/latest/APIReference/API_DescribeApplication.html
- https://docs.aws.amazon.com/singlesignon/latest/APIReference/API_UpdateApplication.html
- https://docs.aws.amazon.com/singlesignon/latest/APIReference/API_DeleteApplication.html
```console
% make testacc PKG=ssoadmin TESTS=TestAccSSOAdminApplication_
TF_ACC=1 go test ./internal/service/ssoadmin/... -v -count 1 -parallel 20 -run='TestAccSSOAdminApplication_'  -timeout 360m
--- PASS: …
```
=> r/aws_ssoadmin_application: new resource

.changelog/34729.txt, internal/service/sagemaker/app.go, internal/service/sagemaker/domain.go, internal/service/sagemaker/domain_test.go, internal/service/sagemaker/sagemaker_test.go, internal/service/sagemaker/space.go, internal/service/sagemaker/user_profile.go, website/docs/r/sagemaker_app.html.markdown, website/docs/r/sagemaker_domain.html.markdown, website/docs/r/sagemaker_space.html.markdown, website/docs/r/sagemaker_user_profile.html.markdown
Closes #34689
Closes #34673
```console
% make testacc TESTS=TestAccSageMaker_serial PKG=sagemaker
--- PASS: TestAccSageMaker_serial/Domain/efs (541.49s)
--- PASS: TestAccSageMaker_serial/Domain/posix (386.44s)
--- PASS: TestAccSageMaker_serial/Domain/codeEditorAppSettings (384.93s)
--- PASS: TestAccSageMaker_serial/Domain/jupyterLabAppSettings (382.32s)
--- PASS: TestAccSageMaker_serial/Domain/spaceStorageSettings (391.98s)
```
=> Sagemaker Studio - Add support for new jupyter lab arguments

go.mod, go.sum
dependabot timed out: https://github.com/hashicorp/terraform-provider-aws/network/updates/759472794
Relates https://github.com/hashicorp/terraform-provider-aws/pull/34710.
=> 12/06/2023 AWS SDK for Go updates

.github/workflows/pull_request_target.yml
https://github.com/hashicorp/terraform-provider-aws/actions/runs/7143590911/job/19455410202?pr=34812
```
Run actions/labeler@8558fd74291d67161a8a78ce36a881fa63b766a9
with:
configuration-path: .github/labeler-pr-triage.yml
repo-token: ***
sync-labels: false
dot: true
The configuration file (path: .github/labeler-pr-triage.yml) was found locally, reading from the file
Error: Error: found unexpected type for label 'client-connections' (should be array of config options)
Error: found unexpected type for label 'client-connections' (should be array of config options)
```
Relates https://github.com/hashicorp/terraform-provider-aws/pull/34730.
=> Revert `actions/labeler@5.0.0`

docs/add-a-new-service.md
Adds steps required to prepare service for resource self-registration.
=> docs: update new service instructions

internal/framework/types/listof.go, internal/framework/types/listof_test.go
```console
% go test ./internal/framework/types/... -v -count=1 -run=TestListOfString
=== RUN   TestListOfStringFromTerraform
=== PAUSE TestListOfStringFromTerraform
=== CONT  TestListOfStringFromTerraform
=== RUN   TestListOfStringFromTerraform/values
=== PAUSE TestListOfStringFromTerraform/values
=== CONT  TestListOfStringFromTerraform/values
--- PASS: TestListOfStringFromTerraform (0.00s)
--- PASS: TestListOfStringFromTerraform/values (0.00s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/framework/types	0.236s
```
=> add listof framework types

docs/documentation-changes.md
=> contributor docs: cdktf docs edits

.ci/.semgrep-caps-aws-ec2.yml, names/caps.csv, names/caps.md
Closes #0000
```console
...
```
=> Added Db2 to semgrep and names

internal/framework/flex/auto_expand.go, internal/framework/flex/auto_expand_test.go, internal/framework/flex/auto_flatten.go, internal/framework/flex/auto_flatten_test.go, internal/framework/flex/autoflex.go, internal/framework/flex/autoflex_test.go
Closes #0000
```console
...
```
=> autoflex: Rename map

docs/raising-a-pull-request.md
Fixes formatting and updates to the correct `AWSClient` type assertion and field names.
=> docs: fix synthetic arn construction example

internal/service/s3/object_test.go
Tests creating an ["S3 folder"](https://www.tecracer.com/blog/2023/01/what-are-the-folders-in-the-s3-console.html).
Relates https://github.com/hashicorp/terraform-provider-aws/issues/32385. 
```console
% make testacc TESTARGS='-run=TestAccS3Object_prefix' PKG=s3
TF_ACC=1 go test ./internal/service/s3/... -v -count 1 -parallel 20  -run=TestAccS3Object_prefix -timeout 360m
=== RUN   TestAccS3Object_prefix
=== PAUSE TestAccS3Object_prefix
=== CONT  TestAccS3Object_prefix
--- PASS: TestAccS3Object_prefix (23.81s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/s3	29.516s
```
=> Add `TestAccS3Object_prefix`

website/docs/d/ec2_transit_gateway_attachments.html.markdown
Closes #35123
```console
...
```
=> d/transitgateway attachment: fix documentation reference

.github/workflows/firewatch.yml, .github/workflows/release.yml, .github/workflows/snapshot.yml
Due to conflicts with [provider common release tooling](https://github.com/hashicorp/ghaction-terraform-provider-release), restore the previous version of `actions/upload-artifact`.
Relates https://github.com/hashicorp/ghaction-terraform-provider-release/issues/76.
Relates https://github.com/hashicorp/terraform-provider-awscc/pull/1388.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/34939.
```console
...
```
=> Revert `actions/upload-artifact@4.0.0`

website/docs/cdktf/python/r/verifiedaccess_group.html.markdown, website/docs/r/verifiedaccess_endpoint.html.markdown, website/docs/r/verifiedaccess_group.html.markdown
This PR improves the documentation for the `aws_verifiedaccess_group` resource
n/a
n/a
n/a
=> fix: policy_docment -> policy_document in aws_verifiedaccess_group resource

go.mod, go.sum
This release includes the initial function implementation to allow provider developers to define their own functions.
- https://github.com/hashicorp/terraform-plugin-framework/releases/tag/v1.5.0
- https://developer.hashicorp.com/terraform/plugin/framework/functions
Relates https://github.com/hashicorp/terraform-plugin-framework/pull/889
=> deps: bump terraform-plugin-framework to 1.5.0

CHANGELOG.md
Corrects the `v5.32.1` release version in the CHANGELOG.
=> Correct patch version in CHANGELOG

website/docs/r/network_acl_association.html.markdown
This PR is to add the missing section about import to the `aws_network_acl_association` resource page in the documentation. The instructions have been verified using my AWS account.
Closes #35002
n/a
n/a
=> docs: Add import section to aws_network_acl_association resource doc

website/docs/r/s3_bucket.html.markdown, website/docs/r/s3_bucket_object_lock_configuration.html.markdown
Relates #35153
```console
...
```
=> documentation: s3 object lock configuration usage

website/docs/r/eks_cluster.html.markdown
Fixes copypasted links and section names.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/35037.
=> correct access_config link and section

.github/workflows/release.yml
Required so as to use `actions/upload-artifact@v4`.
Closes https://github.com/hashicorp/terraform-provider-aws/issues/35393.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/35383.
Relates https://github.com/hashicorp/ghaction-terraform-provider-release/issues/76.
=> GHA `Release` workflow: Upgrade to `hashicorp/ghaction-terraform-provider-release@v3`

website/docs/r/sagemaker_studio_lifecycle_config.html.markdown
Documentation update with include additional AppType Enums accepted for resource `aws_sagemaker_domain`
Closes #35332
Tested and reviewed with screenshots provided in issue
https://github.com/hashicorp/terraform-provider-aws/issues/35332
=> :pencil: docs update with additional AppType Enums

internal/service/apigateway/sweep.go, internal/service/ec2/sweep.go, internal/service/ec2/vpc_endpoint_connection_accepter.go, internal/service/eks/sweep.go, internal/service/finspace/sweep.go, internal/service/iam/sweep.go, internal/service/rds/global_cluster.go, internal/service/s3/sweep.go, internal/service/sagemaker/notebook_instance.go, internal/service/sagemaker/sweep.go, internal/service/ssmcontacts/sweep.go, internal/sweep/awsv2/skip.go
Sweepers now run to completion in GovCloud, `tf_acctest_alt1_dev` and all `terraform_team1_dev` Regions except `us-west-2`, where there are some wedged ENIs.
=> Various sweeper fixes

website/docs/r/ssoadmin_application.html.markdown
Currently the API only supports creation of custom OAuth 2.0 applications.
Relates #34813
- https://github.com/hashicorp/terraform-provider-aws/issues/34813#issuecomment-1910380297
N/a docs
=> r/aws_ssoadmin_application(doc): add note on CreateApplication API limitations

website/docs/r/wafv2_web_acl_association.html.markdown
Clear up limitations on API Gateway WAF support with the example resources
```console
...
```
=> lack of support for http api gateway doc

internal/service/backup/report_plan.go, internal/service/cloud9/environment_ec2.go, internal/service/cognitoidentity/pool.go, internal/service/fsx/openzfs_snapshot.go, internal/service/sagemaker/project.go, internal/service/storagegateway/nfs_file_share.go
The [standard](https://hashicorp.github.io/terraform-provider-aws/resource-tagging/#resource-update-operation) is:
```go
if d.HasChangesExcept("tags", "tags_all") {
...
}
```
=> Tech debt: `d.HasChangesExcept("tags_all", "tags")` -> `d.HasChangesExcept("tags", "tags_all")`

internal/service/ec2/ec2_instance.go
When aws_instance has instance_type and capacity reservation ID changes, the provider performs both changes in stop/start context.
Closes #32458
```console
...
```
=> Fix ReservationCapacityExceeded error in aws_instance

internal/service/sns/topic_policy.go
```console
=== RUN   TestAccSNSTopicPolicy_Disappears_topic
=== PAUSE TestAccSNSTopicPolicy_Disappears_topic
=== CONT  TestAccSNSTopicPolicy_Disappears_topic
testing_new.go:91: Error running post-test destroy, there may be dangling resources: exit status 1
Error: setting SNS Topic (arn:aws:sns:us-west-2:187416307283:tf-acc-test-5503287551419522950) attribute (Policy): operation error SNS: SetTopicAttributes, https response error StatusCode: 404, RequestID: cd35e33d-f000-5b72-b968-bd7ca9bd3694, NotFound: Topic does not exist
--- FAIL: TestAccSNSTopicPolicy_Disappears_topic (231.26s)
FAIL
```
```console
% make testacc TESTARGS='-run=TestAccSNSTopicPolicy' PKG=sns
TF_ACC=1 go test ./internal/service/sns/... -v …
```
=> td/aws_sns_topic_policy: fix disappears test

tools/tfsdk2fw/go.mod, tools/tfsdk2fw/go.sum
Closes #0000
```console
...
```
=> Go mod tidy

.changelog/35832.txt, .devcontainer/devcontainer.json
Closes #0000
```console
...
```
=> Add changelog for go1.21 upgrade

.ci/tools/go.mod
Closes #0000
```console
...
```
=> Remove toolchain directive

website/docs/r/workspaces_workspace.html.markdown
Update aws_workspaces_workspace documentation to reflect requirement to use a KMS CMK ARN instead of an alias.
Closes #16805
https://docs.aws.amazon.com/workspaces/latest/api/API_WorkspaceRequest.html#WorkSpaces-Type-WorkspaceRequest-VolumeEncryptionKey
=> Update Workspaces KMS documentation.

go.mod, go.sum
Work around dependabot timeout on top-level `go.mod` -- https://github.com/hashicorp/terraform-provider-aws/network/updates/790309956.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/35910.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/32867.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/32859.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/32858.
=> Latest `aws-sdk-go` modules

.github/workflows/dependencies.yml, GNUmakefile, tools/tfsdk2fw/go.mod, tools/tfsdk2fw/go.sum
Closes #0000
```console
...
```
=> make: Default tidy to default Go version

skaff/go.mod, skaff/go.sum
=> skaff: go mod tidy

infrastructure/repository/labels-workflow.tf
Adds a new label to help group SDK migration issues.
- #32976
=> New label `aws-sdk-go-migration` to help track SDK migration effort

infrastructure/repository/labels-workflow.tf
Adds a `new-function` label to tag issues and PRs related to provider defined functions.
Relates #34952
=> repo: add new-function github label

internal/generate/checknames/main.go, internal/generate/servicepackage/main.go, internal/generate/tagstests/main.go, internal/service/acm/certificate_validation.go, internal/service/acmpca/sweep.go, internal/service/appstream/user_stack_association.go, internal/service/appstream/wait.go, internal/service/backup/vault.go, internal/service/cloudformation/errors.go, internal/service/cloudformation/wait.go, internal/service/cognitoidp/find.go, internal/service/datapipeline/pipeline_definition.go, internal/service/dynamodb/table.go, internal/service/ec2/wait.go, internal/service/elasticache/engine_version.go, internal/service/elasticbeanstalk/environment.go, internal/service/elb/load_balancer.go, internal/service/events/target.go, internal/service/iam/role.go, internal/service/iam/user.go, internal/service/inspector2/enabler.go, internal/service/inspector2/enabler_test.go, internal/service/lightsail/instance_public_ports.go, internal/service/networkfirewall/logging_configuration.go, internal/service/networkmanager/core_network.go, internal/service/quicksight/wait.go, internal/service/servicecatalog/provisioned_product.go, internal/service/servicediscovery/service.go, internal/service/sns/sms_preferences_test.go, internal/service/transfer/server.go
Replaces `go-multierror`'s `multierror.Error` with `errors.Join`.
Not sweepers.
Relates https://github.com/hashicorp/terraform-provider-aws/issues/32140.
=> Replace `go-multierror` with `errors.Join`

website/docs/d/msk_bootstrap_brokers.html.markdown
The example for the data resource "aws_msk_bootstrap_brokers" was incorrect
=> docs(aws_msk_bootstrap_brokers): Correct example

GNUmakefile
Closes #0000
```console
...
```
=> make: Use .go-version by default

docs/aws-go-sdk-migrations.md
Relates #32976
```console
...
```
=> docs: Add waiter information to AWS SDK v2 migration guide

.github/dependabot.yml
Ibid.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/36367.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/36366.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/36365.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/36364.
=> `protobuf` should only be updated via `terraform-plugin-go`/`terraform-plugin-framework`

website/docs/r/msk_configuration.html.markdown
Closes #36407
- https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-msk-configuration.html
- https://docs.aws.amazon.com/cli/latest/reference/kafka/create-configuration.html
=> list kafka_versions as optional

website/docs/r/api_gateway_method_response.html.markdown
Corrects typo in `aws_api_gateway_method_response`. Previous example let to an error:
`Invalid content type specified: application-json`
Closes #36388
N/a, docs
=> Correct example in `aws_api_gateway_method_response`

internal/service/ecrpublic/sweep.go
* `aws_ecrpublic_repository`: Run sweeper only in us-east-1.
=> Sweeper fixes

CHANGELOG.md, website/docs/r/dynamodb_resource_policy.html.markdown
The comments are causing CDKTF documentation generation linting errors: https://github.com/hashicorp/terraform-provider-aws/actions/runs/8501960197/job/23285610629?pr=36666.
Relates #36666.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/36595.
=> r/aws_dynamodb_resource_policy: Remove documentation comments

website/docs/r/guardduty_organization_configuration_feature.html.markdown
Documents valid values for `aws_guardduty_organization_configuration_feature.additional_configuration.name` and `aws_guardduty_organization_configuration_feature.name`.
Closes https://github.com/hashicorp/terraform-provider-aws/issues/36673.
=> r/aws_guardduty_organization_configuration_feature: Document valid values

website/docs/r/rds_cluster_instance.html.markdown
Add to documentation clarification that to upgrade the `rds_cluster_instance` `engine_version`, it has to be done on the `rds_cluster` level because AWS handles instance upgrades when the cluster is upgraded.
```console
...
```
=> Add documentation on engine_version update on rds cluster instance

website/docs/r/guardduty_detector_feature.html.markdown
New values have been added to the SDK without any associated API change, so values have become stale several times recently. As this appears to be a fast moving area, this PR changes the value reference to point to AWS Documentation.
=> Update GuardDuty Detector Feature documentation to refer to AWS docs for supported values

.github/labeler-issue-triage.yml, .github/labeler-pr-triage.yml, infrastructure/repository/labels-workflow.tf, internal/generate/issuelabels/file.tmpl, internal/generate/prlabels/file.tmpl
This will be used to label enhancements and bug reports related to provider defined functions.
=> infrastructure/repository: add function label

.github/workflows/pull_request_target.yml, infrastructure/repository/projects.tf
After the introduction of new features, issues and PRs are added to the team's GitHub Project via built-in workflows. This PR is the first of a series of adapting our workflows with those features in mind.
This PR removes the step of manually adding partner and external maintainer PRs to the Project and setting a "view" field. The views on the Project instead use the labels themselves to filter, so their "view" values are removed. The view for Terraform Core / S3 Backend items filters on the repository, so it's value for the "view" field as well.
- [Projects without Limits](https://github.com/orgs/community/discussions/106785)
N/a
=> Initial Projects without Limits cleanup

.changelog/36819.txt
Relates #36819
```console
...
```
=> add CHANGELOG entry for `aws_datasync_location_object_storage`

tools/awssdkpatch/README.md, tools/awssdkpatch/main.go
The `out` help text included a redundant description of the default value.
Relates #36662
=> tools/awssdkpatch: tidy help text

docs/add-a-new-function.md
Now that the `skaff function` subcommand is available, the contributor guide for creating new functions needs to be updated to reflect how to use it.
Relates #36891
=> doc: add skaff instructions to new function guide

.teamcity/components/generated/services_all.kt, internal/generate/teamcity/acctest_services.hcl
Relates #36735
```console
...
```
=> td/correct test pattern for EC2 Outposts

website/docs/guides/continuous-validation-examples.html.markdown
This PR updates the Continuous Validation guide with HCP Terraform branding
N/a, docs
=> guides: Continuous Validation: replace Terraform Cloud with HCP Terraform

website/docs/r/route53domains_registered_domain.html.markdown
Update the missing description for contact blocks section in `aws_route53domains_registred_domain` resource docs.
=> Improved docs for route53domains_registred_domain resource

tools/awssdkpatch/patch.tmpl
This replaces a hardcoded error code with the proper variable substitution.
=> awssdkpatch: fix error message contains patch

internal/service/xray/sweep.go, internal/sweep/register_gen_test.go
Adds sweeper for X-Ray Group
Relates #31269
=> Adds sweeper for X-Ray Group

.ci/.semgrep.yml, internal/service/quicksight/schema/analysis.go, internal/service/quicksight/schema/dashboard.go, internal/service/quicksight/schema/parameters.go, internal/service/quicksight/schema/template.go, internal/service/quicksight/schema/template_control.go, internal/service/quicksight/schema/template_filter.go, internal/service/quicksight/schema/template_format.go, internal/service/quicksight/schema/template_parameter.go, internal/service/quicksight/schema/template_sheet.go, internal/service/quicksight/schema/visual.go, internal/service/quicksight/schema/visual_actions.go, internal/service/quicksight/schema/visual_chart_configuration.go, internal/service/quicksight/schema/visual_histogram.go, internal/service/quicksight/schema/visual_insight.go, internal/service/quicksight/schema/visual_kpi.go, internal/service/quicksight/schema/visual_line_chart.go, internal/service/quicksight/schema/visual_pivot_table.go, internal/service/quicksight/schema/visual_table.go
Relates #37293 
```console
...
```
=> quicksight: Add const over literal

.ci/.semgrep.yml, internal/service/autoscaling/group.go, internal/service/autoscaling/group_data_source.go, internal/service/autoscaling/group_migrate.go, internal/service/ec2/ec2_fleet.go, internal/service/ec2/ec2_launch_template.go, internal/service/ec2/ec2_launch_template_data_source.go, internal/service/ec2/ec2_spot_fleet_request.go, internal/service/quicksight/schema/visual_gauge_chart.go, names/attr_consts.go
Relates #37293
```console
...
```
=> .ci: Prefer min, max constants over literals

internal/service/lakeformation/sweep.go, internal/sweep/register_gen_test.go
Adds sweepers for `aws_lakeformation_permissions` and `aws_lakeformation_resource`
=> Adds sweepers for `aws_lakeformation_permissions` and `aws_lakeformation_resource`

internal/service/dms/replication_task_test.go, internal/service/dms/task_settings_json.go, internal/service/dms/task_settings_json_test.go, website/docs/r/dms_replication_task.html.markdown
Closes #36997
```console
...
```
=> dms: Clarify that read-only task settings should not be used

.goreleaser.yml
Modify .goreleaser to include license file in release package.
=> Include license file in release package

website/docs/r/bedrockagent_agent.html.markdown, website/docs/r/bedrockagent_agent_action_group.html.markdown, website/docs/r/bedrockagent_agent_alias.html.markdown, website/docs/r/bedrockagent_agent_knowledge_base_association.html.markdown, website/docs/r/bedrockagent_knowledge_base.html.markdown
This PR is to apply some placeholder and structural fixes to the documentation for the new `aws_bedrockagent_*` resources, so that their format and level of details are more consistent.
Closes #37453
Referred to [Amazon Bedrock API Reference](https://docs.aws.amazon.com/bedrock/latest/APIReference/welcome.html) for descriptions.
n/a
=> docs: Adjust formatting and add details in aws_bedrockagent_* resource docs

internal/service/xray/sampling_rule.go, internal/service/xray/sweep.go
Adds sweeper for `aws_xray_sampling_rule`
Closes #31269
=> Adds sweeper for `aws_xray_sampling_rule`

tools/awssdkpatch/patch.tmpl
Adjusts the `tfawserr` import to use the v2 variant from the `aws-sdk-go-base` library.
Relates #32976
Relates #37472
Closes #37506
=> tools/awssdkpatch: tfawserr import patch

tools/awssdkpatch/patch.tmpl
Adds a few additional filter patches missed on the previous PR adding multiclient support.
Relates #37540 
Relates https://github.com/hashicorp/terraform-provider-aws/issues/32976
=> tools/awssdkpatch: add missed filters patches

website/docs/r/cloud9_environment_membership.html.markdown
Update the documentation for `aws_cloud9_environment_membership` to fix the typo for `user_id` in the Attributes Reference section.
Closes #37550
N/A
=> docs: fix typo in user_id on r/aws_cloud9_environment_membership

website/docs/r/kms_key.html.markdown
This PR is to add more representative example usages to the `aws_kms_key` resource doc. Since the CloudFormation documentation already provides a few good examples, I decided to just port them to Terraform with a bit of tweaking.
Closes #37290
Referred to examples in the [CloudFormation user guide](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-kms-key.html#aws-resource-kms-key--examples).
```console
n/a
```
=> docs: Add more example usages for aws_kms_key

internal/generate/tagstests/test.go.gtpl, internal/service/accessanalyzer/analyzer_tags_gen_test.go, internal/service/acm/certificate_tags_gen_test.go, internal/service/acmpca/certificate_authority_tags_gen_test.go, internal/service/batch/compute_environment_tags_gen_test.go, internal/service/batch/job_definition_tags_gen_test.go, internal/service/batch/job_queue_tags_gen_test.go, internal/service/batch/scheduling_policy_tags_gen_test.go, internal/service/iam/instance_profile_tags_gen_test.go, internal/service/iam/openid_connect_provider_tags_gen_test.go, internal/service/iam/policy_tags_gen_test.go, internal/service/iam/role_tags_gen_test.go, internal/service/iam/server_certificate_tags_gen_test.go, internal/service/iam/service_linked_role_tags_gen_test.go, internal/service/iam/user_tags_gen_test.go, internal/service/iam/virtual_mfa_device_tags_gen_test.go, internal/service/servicecatalog/portfolio_tags_gen_test.go, internal/service/servicecatalog/product_tags_gen_test.go, internal/service/servicecatalog/provisioned_product_tags_gen_test.go, internal/service/xray/group_tags_gen_test.go, internal/service/xray/sampling_rule_tags_gen_test.go
Adds generated tagging test for emtpy-valued default tag.
=> Adds tagging test for empty-valued default tag

.github/workflows/changelog_misspell.yml, .github/workflows/documentation.yml, .github/workflows/provider.yml, .github/workflows/website.yml, GNUmakefile, docs/continuous-integration.md
Closes #0000
```console
...
```
=> make: Last fixes

docs/continuous-integration.md
Closes #0000
```console
...
```
=> docs/ci: Make copying easier

.changelog/37646.txt
Relates #37646
```console
...
```
=> d/lambda_layer_version: tweak changelog entry

GNUmakefile
Fixes inconsistent indentation due to recently changes target names.
=> chore: fix make help description spacing

website/docs/r/api_gateway_deployment.html.markdown
Add docs for canary_settings in apigateway_deployment
Relates ##37573
=> Add docs for canary_settings in apigateway_deployment

GNUmakefile, tools/tfsdk2fw/go.mod, tools/tfsdk2fw/go.sum
Closes #0000
```console
...
```
=> make: Respect PKG for more targets

CHANGELOG.md
Preparing for the v5.51.1 patch release.
=> chore: set unreleased version to v5.51.1

website/docs/guides/using-aws-with-awscc-provider.html.markdown
=> Remove Tech Preview verbigage

.github/workflows/README.md, .github/workflows/acctest-terraform-lint.yml, .github/workflows/changelog.yml, .github/workflows/changelog_misspell.yml, .github/workflows/community-check.yml, .github/workflows/copyright.yml, .github/workflows/dependencies.yml, .github/workflows/documentation.yml, .github/workflows/examples.yml, .github/workflows/golangci-lint.yml, .github/workflows/library_versions.yml, .github/workflows/provider.yml, .github/workflows/providerlint.yml, .github/workflows/semgrep-ci.yml, .github/workflows/skaff.yml, .github/workflows/website.yml, .github/workflows/workflow-lint.yml, .github/workflows/yamllint.yml, .markdownlint.yml, GNUmakefile, docs/continuous-integration.md, docs/makefile-cheat-sheet.md, mkdocs.yml
Closes #0000
```console
...
```
=> docs: Makefile cheat sheet

docs/continuous-integration.md, docs/makefile-cheat-sheet.md
Closes #0000
```console
...
```
=> docs/ci/make: Fix grammar and typos

.github/workflows/library_versions.yml
Closes #0000
```console
...
```
=> ci: Don't use make in library versions

tools/literally/go.mod, tools/literally/main.go, tools/literally/main_test.go
Closes #0000
```console
...
```
=> tool: literally

website/docs/r/launch_template.html.markdown
Add ssm param information to launch template `image_id` argument
- Relates to https://github.com/hashicorp/terraform-provider-aws/issues/29637
- https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/create-launch-template.html#use-an-ssm-parameter-instead-of-an-ami-id
N/A
=> chore(docs): add ssm param to launch template

.github/workflows/generate_changelog.yml, .github/workflows/team_slack_bot.yml
Use GitHub app for slack PR update workflow
=> Use GitHub app for slack update workflow

go.mod, go.sum, tools/tfsdk2fw/go.mod, tools/tfsdk2fw/go.sum
Required for https://github.com/hashicorp/terraform-provider-aws/pull/37919.
=> Latest AWS SDK for Go modules

internal/service/appflow/flow.go, internal/service/appflow/service_package_gen.go, internal/service/appflow/sweep.go, internal/sweep/register_gen_test.go
=> Adds sweeper for AppFlow Flow

CHANGELOG.md
Correct unreleased next version in CHANGELOG.
=> Next release is `v5.54.1`

website/docs/r/glue_connection.html.markdown
This PR fixes typos aws_secretmanager_secret to aws_secret"s"manager_secret in the documentation.
N/A
[secretsmanager_secret](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/secretsmanager_secret)
N/A
=> fix typos in the documentation

.changelog/33128.txt
Removes doc changelog entry
Relates #33128
=> Remove doc changelog entry

CHANGELOG.md
Usual updates as part of release action are failing -- https://github.com/hashicorp/terraform-provider-aws/actions/runs/9604020133/job/26490199844:
```
Run git config --local user.email changelogbot@hashicorp.com
git config --local user.email changelogbot@hashicorp.com
git config --local user.name changelogbot
git add CHANGELOG.md
git commit -m "Update CHANGELOG.md after v5.55.0"
git push
shell: /bin/bash -e {0}
[main df8844d96[2](https://github.com/hashicorp/terraform-provider-aws/actions/runs/9604020133/job/26490199844#step:4:2)] Update CHANGELOG.md after v5.55.0
1 file changed, 2 insertions(+), 1 deletion(-)
remote: error: GH01[3](https://github.com/hashicorp/terraform-provider-aws/actions/runs/9604020133/job/26490199844#step:4:3): Repository rule violations found for refs/heads/main. …
```
=> Update CHANGELOG after `v5.55.0` release

.github/workflows/release.yml
Updates the post release changelog update step to use the GitHub App token.
=> Use GitHub App token for post release changelog update action

.changelog/38078.txt, internal/service/sagemaker/sagemaker_test.go, internal/service/sagemaker/workforce.go, internal/service/sagemaker/workforce_test.go, website/docs/r/sagemaker_workforce.html.markdown
Closes #0000
```console
% make testacc TESTS=TestAccSageMaker_serial/Workforce/OidcConfig  PKG=sagemaker
--- PASS: TestAccSageMaker_serial (47.14s)
--- PASS: TestAccSageMaker_serial/Workforce (47.14s)
--- PASS: TestAccSageMaker_serial/Workforce/OidcConfig (24.66s)
--- PASS: TestAccSageMaker_serial/Workforce/OidcConfig_full (22.48s)
```
=> r/sagemaker_workforce - add oidc fields

website/docs/d/organizations_policy.html.markdown
Fix typo in [Data Source: aws_organizations_policy](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/organizations_policy)
nothing 
Closes #0000
nothing
Document only
=> fix: typo in organizations_policy.html.markdown

.github/workflows/issues.yml, .github/workflows/pull_request_target.yml, .github/workflows/regressions.yml
This PR improves our workflows for regressions by:
- Combining the relevant parts of `issues.yml` and `pull_request_target.yml`, reducing duplicated config
- Specifying a top-level `permissions` key that completely limits the permissions of the automatically generated GitHub auth token
- Using intermediary environment variables for any values that come from the issue/pull request to improve security and readability
Relates https://github.com/hashicorp/terraform-provider-awscc/pull/1773
N/a, Actions
=> Update regressions workflow

internal/service/efs/sweep.go, internal/service/fsx/sweep.go, internal/service/m2/environment.go, internal/service/m2/sweep.go, internal/service/s3/sweep.go, internal/sweep/register_gen_test.go
Adds sweepers for `aws_m2_application` and `aws_m2_environment`
=> Adds sweepers for M2

.changelog/38274.txt, internal/service/appstream/fleet.go, internal/service/appstream/fleet_test.go, website/docs/r/appstream_fleet.html.markdown
Closes #24014
```console
...
```
=> aws_appstream_fleet

internal/generate/listpages/main.go, internal/generate/namesconsts/main.go, internal/generate/tags/main.go, names/data/lookup.go, names/data/read.go, names/names.go, names/names_test.go
Move handling of some service data only used by generators to functions on `ServiceRecord`
=> Move handling of some service data only used by generators to functions on `ServiceRecord`

.github/dependabot.yml
Consolidate Dependabot rules for Go dependencies to update dependencies across all modules in sync
=> dependabot: Consolidate Dependabot rules for Go dependencies

website/docs/d/ec2_capacity_block_offering.html.markdown, website/docs/r/ec2_capacity_block_reservation.html.markdown
Updating the example and input parameters in the documentation.
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ec2_capacity_block_reservation
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/ec2_capacity_block_offering
Closes #38391 
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ec2_capacity_block_reservation
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/ec2_capacity_block_offering
```console
...
```
=> Updating the documentation of ec2 capacity block

.github/workflows/changelog.yml
Updates the `CHANGELOG Checks` workflow to use the new community check composite action
Similar #38228
N/a, Actions
=> Update CHANGELOG Checks to use new community check

GNUmakefile, tools/awssdkpatch/patch.tmpl
* Don't patch generated files
* Replace aws.TimeValue() with aws.ToTime()
Closes #0000
```console
...
```
=> awssdkpatch: Minor fixups

.github/workflows/dependencies.yml
Updates the dependency check workflow so that it only comments if necessary
N/a, workflows
=> Only comment if necessary

.changelog/38477.txt, internal/service/iam/role.go, internal/service/iam/role_test.go
Closes #23124
```console
% make t T=TestAccIAMRole_InlinePolicy_malformed K=iam
TF_ACC=1 go1.22.5 test ./internal/service/iam/... -v -count 1 -parallel 20 -run='TestAccIAMRole_InlinePolicy_malformed'  -timeout 360m
=== RUN   TestAccIAMRole_InlinePolicy_malformed
=== PAUSE TestAccIAMRole_InlinePolicy_malformed
=== CONT  TestAccIAMRole_InlinePolicy_malformed
--- PASS: TestAccIAMRole_InlinePolicy_malformed (6.70s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/iam	9.241s
```
=> iam/role: If inline fails, role fails

website/docs/r/launch_template.html.markdown
Pointed wrong aws documentation link to the updated path
=> Broken link fix: For EC2 stop protection

internal/service/appautoscaling/sweep.go, internal/sweep/register_gen_test.go, internal/sweep/sweep.go
Adds sweepers for `aws_appautoscaling_policy` and `aws_appautoscaling_target`
=> Adds sweepers for `aws_appautoscaling_policy` and `aws_appautoscaling_target`

skaff/go.mod, skaff/go.sum, tools/tfsdk2fw/go.mod, tools/tfsdk2fw/go.sum
Fixes e.g. https://github.com/hashicorp/terraform-provider-aws/actions/runs/10097647346/job/27922967888:
```
Run cd skaff
cd skaff
go build
shell: /usr/bin/bash -e {0}
env:
GOCACHE: /home/runner/.cache/go-build
go: downloading github.com/spf13/cobra v1.8.1
go: downloading github.com/YakDriver/regexache v0.23.0
go: downloading github.com/hashicorp/hcl/v2 v2.21.0
go: downloading github.com/google/uuid v1.6.0
go: downloading github.com/spf13/pflag v1.0.5
go: downloading github.com/zclconf/go-cty v1.14.4
go: downloading github.com/agext/levenshtein v1.2.3
go: downloading github.com/apparentlymart/go-textseg/v15 v15.0.0
go: downloading github.com/mitchellh/go-wordwrap v1.0.1
go: downloading github.com/google/go-cmp v0.6.0
go: downloading golang.org/x/text v0.16.0
go: updates to go.mod needed; …
```
=> Run `make clean-tidy`

website/docs/r/instance.html.markdown
Add more detail in `aws_instance` document. Specifically launching an instance using capacity reservation.
Closes #0000
```console
...
```
=> [document update] add capacity-block to market_type description

website/docs/r/s3_bucket_notification.html.markdown
Adding more insight to the warning note of this documentation. It'd be a benefit to inform users of the results they would see if they were to attempt to use this resource against an S3 bucket with existing notification configurations.
Closes #0000
```console
...
```
=> Add warning to s3_bucket_notification doc

docs/data-handling-and-conversion.md
Provider developer documentation for AutoFlex
=> Provider developer documentation for AutoFlex

internal/framework/flex/auto_expand_test.go, internal/framework/flex/auto_flatten_test.go
Converts slice of tests to map of tests
=> Converts slice of tests to map of tests

website/docs/r/bedrockagent_data_source.html.markdown
Fix typo in [Resource: aws_bedrockagent_data_source](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/bedrockagent_data_source#chunking_strategy)
nothing
Closes #0000
Document only
=> fix:typo in bedrockagent_data_source.html.markdown

internal/framework/flex/auto_expand.go, internal/framework/flex/auto_expand_test.go, internal/framework/flex/auto_flatten.go, internal/framework/flex/auto_flatten_test.go, internal/framework/flex/autoflex.go, internal/framework/flex/logging_test.go
Moves resource name prefix to `AutoFlexOptions`
=> Td autoflex options resource name prefix

internal/provider/provider_test.go
```console
% go test -count=1 ./internal/provider/...
?       github.com/hashicorp/terraform-provider-aws/internal/provider/fwprovider        [no test files]
ok      github.com/hashicorp/terraform-provider-aws/internal/provider   7.861s
```
=> internal/provider(test): add test case names

internal/service/amp/scraper.go, internal/service/amp/sweep.go, internal/service/eks/sweep.go, internal/sweep/register_gen_test.go
Adds sweepers for `aws_prometheus_scraper` and `aws_prometheus_workspace`
=> Adds sweepers for AMP

docs/data-handling-and-conversion.md, infrastructure/repository/README.md, infrastructure/repository/labels-workflow.tf
Tweaks AutoFlex documentation
Adds `autoflex` issue label
=> Updates AutoFlex documentation

internal/framework/flex/auto_expand_test.go, internal/framework/flex/auto_flatten_test.go, internal/framework/flex/autoflex_test.go, internal/framework/flex/logging_test.go
Renames testing structs to meaningful names
=> AutoFlex: rename testing structs to meaningful names

go.mod, tools/tfsdk2fw/go.mod, tools/tfsdk2fw/go.sum
Cleans up dependencies after the `route53recoveryreadiness` AWS SDK migration.
Relates #38801
=> chore: make clean-tidy

internal/framework/flex/auto_expand.go, internal/framework/flex/auto_expand_test.go, internal/framework/flex/auto_flatten.go, internal/framework/flex/auto_flatten_test.go, internal/framework/flex/autoflex_test.go, internal/framework/flex/logging_test.go
The Terraform Plugin Framework recently added the type `Int32`. Adds support in AutoFlex.
=> AutoFlex: Adds support for `types.Int32`

website/docs/r/securitylake_aws_log_source.html.markdown
Update documentation to include the newer log source types.
Closes #38834
Names from https://github.com/aws/aws-sdk-go-v2/blob/service/securitylake/v1.16.3/service/securitylake/types/enums.go#L26-L36
=> chore: update securitylake_aws_log_source documentation with v2.0 aws log sources

internal/framework/flex/auto_expand.go, internal/framework/flex/auto_expand_test.go, internal/framework/flex/auto_flatten.go, internal/framework/flex/auto_flatten_test.go, internal/framework/flex/autoflex_test.go
The Terraform Plugin Framework recently added the type `Float32`. Adds support in AutoFlex.
=> AutoFlex: Add support for `types.Float32`

website/docs/r/cognito_managed_user_pool_client.html.markdown, website/docs/r/cognito_user_pool_client.html.markdown
Provide better documentation around
`allowed_oauth_flows_user_pool_client` parameter.
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cognito-userpoolclient.html
=> fix(doc): update Amazon Cognito managed user pool

CHANGELOG.md
Preparing a patch release to address an SES configuration set regression which triggers a crash (#38921).
=> chore: prepare changelog for v5.63.1

website/docs/r/timestreaminfluxdb_db_instance.html.markdown
I noticed when reading the documentation for this resource a small typo in `Db` so I have updated this to be `database instance`
=> doc: update typo in Db to be database instance

website/docs/r/dlm_lifecycle_policy.html.markdown
- Fixed the arguments in share rule arguments for `aws_dlm_lifecycle_policy` to match the actual parameter names 
Closes #38985
=> docs(aws_dlm_lifecycle_policy): fix parameter names for share rule arguments 

.github/workflows/golangci-lint.yml
Closes #0000
```console
...
```
=> ci: golangci-lint killed bad

CODEOWNERS
This will allow members of `@hashicorp/terraform-aws` to approve github action related PRs when preferred reviewers are unavailable.
=> chore: adjust codeowners

.github/workflows/pull_request_feed.yml
Updates the PR feed workflow to prevent failures when the title of a PR contains quotes
- [Recent failed run](https://github.com/hashicorp/terraform-provider-aws/actions/runs/10621398648)
- [Prior art](https://github.com/hashicorp/terraform-provider-aws/blob/2145f88d813b890390bb7baff5834fdd3409d757/.github/workflows/label-notifications.yml#L44)
N/a, workflows
=> Use format to prevent quoting issues

internal/service/fms/sweep.go
When the current account has an admin account, sweepers running outside of `us-east-1` will return an error
=> Fixes `aws_fms_admin_account` sweeper

website/docs/r/grafana_workspace.html.markdown
Simple doc update about the default behaviour of Grafana workspace creation
=> (doc): Update default version for creating grafana workspace

internal/generate/allowsubcats/main.go, internal/generate/checknames/main.go, internal/generate/issuelabels/main.go, internal/generate/prlabels/main.go, internal/generate/servicelabels/main.go, internal/generate/servicepackage/main.go, internal/generate/servicesemgrep/main.go, names/data/read.go
Various cleanup of `names_data.hcl` and parsing
=> Cleanup of `names_data.hcl`

names/data/names_data.hcl
=> Formats `names_data.hcl`

website/docs/r/lexv2models_slot.html.markdown
Documents arguments nested within the `sub_slot_setting` block.
Closes #39170
- https://docs.aws.amazon.com/lexv2/latest/APIReference/API_SubSlotSetting.html
=> r/aws_lexv2models_slot(doc): add `sub_slot_setting` argument reference

website/docs/r/lexv2models_bot.html.markdown, website/docs/r/lexv2models_bot_version.html.markdown, website/docs/r/lexv2models_slot_type.html.markdown
Updated`aws_lexv2models_bot` example to reflect valid values for data privacy and idle_session_ttl_in_seconds.
- Include a role reference for the bot.
- Fixed reference to the right resource aws_lexv2models_bot in bot version example
Closes #0000
```console
...
```
=> docs: updated examples for aws_lexv2models_bot

.github/workflows/post_publish.yml
Update to this action removes the closed id action parameter so it can be removed. Also corrected casing of token parameter. This can also actually be removed but needs to happen in the action first.
=> [chore] Remove unnecessary closed id field

.github/dependabot.yml
Can we have multiple `gomod` entries?
https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#package-ecosystem
Relates https://github.com/hashicorp/terraform-provider-aws/issues/39287.
=> `dependabot`: Can we split gomod?

.github/workflows/pull_request_review.yml
Brought over from the AWSCC provider.
=> [Internal] Adds approval as a feed notification.

META.d/_summary.yaml
=> [chore] Add META.d folder

internal/service/datazone/user_profile.go
Resource has not been release yet.
Relates #38810
```console
...
```
=> r/aws_datazone_user_profile: replace when attribute cannot be updated

skaff/resource/resourcefw.gtpl
On newly generated files this syntax error prevents language server diagnostics from being displayed.
=> skaff: fix errant opening brace

CHANGELOG.md
=> update CHANGLOG for patch release

META.d/_summary.yaml
=> [Compliance] Update team name to correlate with standard

.ci/semgrep/stdlib/sort.yml, internal/generate/listpages/main.go, internal/generate/namevaluesfilters/main.go, internal/service/autoscaling/groups_data_source.go, internal/service/autoscalingplans/scaling_plan_test.go, internal/service/deploy/deployment_group_test.go, internal/service/ec2/ec2_availability_zones_data_source_test.go, internal/service/ec2/filters.go, internal/service/ec2/vpc_network_interface_test.go, internal/service/ec2/vpc_security_group.go, internal/service/ec2/vpc_security_group_rule.go, internal/service/elasticbeanstalk/environment.go, internal/service/elasticbeanstalk/environment_test.go, internal/service/elastictranscoder/pipeline_test.go, internal/service/elb/flex.go, internal/service/iam/policy_model.go, internal/service/inspector/rules_packages_data_source.go, internal/service/inspector2/enabler.go, internal/service/kafka/cluster_test.go, internal/service/kafka/sort.go, internal/service/lakeformation/permissions.go, internal/service/lakeformation/strings.go, internal/service/lambda/event_source_mapping.go, internal/service/meta/ip_ranges_data_source.go, internal/service/route53/zone.go, internal/service/s3/object_test.go, internal/service/ses/receipt_rule.go, internal/tags/key_value_tags.go, tools/literally/main.go, tools/tfsdk2fw/main.go
Replaces typed `sort` package functions with `slices.Sort`
=> Replaces typed `sort` package functions with `slices.Sort`

infrastructure/repository/labels-workflow.tf
add workflow label for new ephemeral resources.
```console
...
```
=> add label for new ephemeral resource

website/docs/r/db_cluster_snapshot.html.markdown, website/docs/r/db_snapshot.html.markdown, website/docs/r/db_snapshot_copy.html.markdown
On  `db_cluster_snapshot`, `db_snapshot` and `db_snapshot_copy` resources there's a typo on the `shared_accounts` parameter documentation.
```console
...
```
=> Fix typo on db_cluster_snapshot, db_snapshot and db_snapshot_copy

infrastructure/repository/labels-workflow.tf
This label will be used to track efforts related to migrating to Terraform Plugin Framework.
=> infrastructure/repository: add `terraform-plugin-migration` label

website/docs/r/dataexchange_data_set.html.markdown
Closes #0000
```console
...
```
=> dataexchange/docs: Update valid values

website/docs/d/organizations_policies.html.markdown, website/docs/d/organizations_policies_for_target.html.markdown, website/docs/d/organizations_policy.html.markdown, website/docs/r/organizations_organization.html.markdown
Update the docs based on the addition of Resource Control Policies. Resource enums are updated based on the SDK enums in #40145.
Extends #40145 to other possible organization resources
https://aws.amazon.com/blogs/aws/introducing-resource-control-policies-rcps-a-new-authorization-policy/
```console
...
```
=> [Docs] Additional doc additions for RCPs

internal/service/sagemaker/sweep.go
The `ListHubs` API returns `ThrottlingException` in unsupported regions.
=> sweeper/aws_sagemaker_hub: Skip sweeper in unsupported regions

docs/add-a-new-ephemeral-resource.md, mkdocs.yml
=> add ephemeral resource contributor docs

go.mod, go.sum, internal/acctest/acctest.go, internal/logging/keys.go, internal/provider/fwprovider/provider.go
- adds echo provider for easier testing on ephemeral resources
- add logging helper to mask sensitive values by key
```console
...
```
=> testing: add echo provider for testing ephemeral resources

.ci/scripts/changelog.tmpl, .ci/scripts/release-note.tmpl
Modifies the changelog templates similar to the changes made for provider defined functions in #34952.
=> .ci/scripts: add handling for `new-ephemeral` entry types

.github/workflows/comments-feed.yml, .github/workflows/label-notifications.yml, .github/workflows/post_publish.yml, .github/workflows/pull_request_feed.yml, .github/workflows/pull_request_review.yml, .github/workflows/release-tag.yml
Attempt 2 at addressing the breaking changes to workflows using `slack-github-action`. This _should_ fix all "Incoming Webhook" style actions, as those were non-functional due to a mistyped secret name in the initial attempted fix. The changes related to the workflows using the "Slack API method" technique are best effort based on the release notes.
Relates #40160 
Relates #40213
=> .github/workflows: fix slack notification actions

.changelog/40291.txt, internal/service/chatbot/slack_channel_configuration.go, internal/service/chatbot/teams_channel_configuration.go
Changes to autflex so that list ordering is not considered a diff. 
Best effort changes since we do not have a teams application configured
Relates #40253
```console
...
```
=> r/chatbot_teams_channel_configuration: Fix SNS topic ARNs ordering

go.mod, go.sum
Manual update of `github.com/aws/aws-sdk-go-v2/aws` dependencies to [`Release 2024-12-02`](https://github.com/aws/aws-sdk-go-v2/commit/776903f3dd7208803912e19d3aa25006a7fbdeee) as [`dependabot` failed](https://github.com/hashicorp/terraform-provider-aws/network/updates/925556508).
Relates: https://github.com/hashicorp/terraform-provider-aws/issues/39287.
```console
% make sane               
make: Sane Check (48 tests of Top 30 resources)
2024/12/02 08:07:04 Initializing Terraform AWS Provider...
=== RUN   TestAccIAMInstanceProfile_tags_null
=== PAUSE …
```
=> `aws-sdk-go-v2` updates (Release 2024-12-02)

docs/raising-a-pull-request.md
Adds a section to the Raising a PR section to outline PR standards.
=> [Docs] Add section on PR hygiene to contributor docs

.teamcity/settings.kts
Removes parameter overrides that were only needed on the old on-premise setup
=> ci: Remove on-premise related parameters

.teamcity/scripts/pullrequest_tests/tests.sh, .teamcity/scripts/service_tests/acceptance_tests.sh, .teamcity/settings.kts
Removes unused legacy alternate account configurations
=> ci: Removes legacy alternate account configurations

.changelog/33797.txt
CHANGELOG update
Relates #33797
```console
...
```
=> tweak CHANGELOG entry for medialive

docs/terraform-plugin-development-packages.md
This page is now more explicit about the requirement for all new resources and data sources to be written with Terraform Plugin Framework. It also switches the ordering of the plugin libraries such that Terraform Plugin Framework is always mentioned first.
=> docs: refine terraform plugin package verbiage

.github/workflows/post_publish.yml
error when running Terraform command
```console
Run terraform init -upgrade
/home/runner/work/_temp/83ea9335-e631-[4](https://github.com/hashicorp/terraform-provider-aws/actions/runs/12303207649/job/34337822441#step:3:5)540-bd8f-585a823c39d5.sh: line 1: terraform: command not found
Error: Process completed with exit code 127.
```
https://github.com/hashicorp/terraform-provider-aws/actions/runs/12303207649/job/34337822441
Closes #0000
```console
...
```
=> github workflow: install terraform on post publish check

.github/workflows/post_publish.yml
=> github workflow: fixes to post publish terraform init

CHANGELOG.md
Correct _Unreleased_ section of the CHANGELOG.
=> Next release will be `v5.82.1`

website/docs/r/batch_job_queue.html.markdown
Fix typo in batch job queue docs.
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/batch_job_queue#job_state_time_limit_action
=> Fix typo in batch_job_queue.html.markdown

ROADMAP.md
```
Run avto-dev/markdown-lint@04d43ee9191307b50935a753da3b775ab695eceb
with:
args: .
ignore: ./docs ./website/docs ./CHANGELOG.md ./internal/service/cloudformation/test-fixtures/examplecompany-exampleservice-exampleresource/docs
fix: false
env:
AWS_DEFAULT_REGION: us-west-[2](https://github.com/hashicorp/terraform-provider-aws/actions/runs/12552429993/job/34998402931#step:4:2)
TERRAFORM_VERSION: 1.8.[3](https://github.com/hashicorp/terraform-provider-aws/actions/runs/12552429993/job/34998402931#step:4:3)
/usr/bin/docker run --name d957e721a955cc31a7[4](https://github.com/hashicorp/terraform-provider-aws/actions/runs/12552429993/job/34998402931#step:4:4)a49ab7ea72e3bece2d4_475fd3 --label d957e7 --workdir /github/workspace --rm -e "AWS_DEFAULT_REGION" -e "TERRAFORM_VERSION" -e "INPUT_ARGS" …
```
=> Fix `ROADMAP.md` markdown-lint errors

mkdocs.yml
This PR removes references to non-existent pages from the navigation bar.
```
WARNING -  A reference to 'aws-go-sdk-versions.md' is included in the 'nav' configuration, which is not found in the
documentation files.
WARNING -  A reference to 'aws-go-sdk-migrations.md' is included in the 'nav' configuration, which is not found in the
documentation files.
```
N/A
N/A
N/A
=> docs: Remove non-existent pages from navigation bar

.changelog/40762.txt, internal/service/cloudfront/distribution.go, internal/service/cloudfront/distribution_test.go, website/docs/r/cloudfront_distribution.html.markdown
Closes #40492
N/A
```console
% make testacc TESTS=TestAccCloudFrontDistribution_grpcConfig PKG=cloudfront                     
TF_ACC=1 go1.23.3 test ./internal/service/cloudfront/... -v -count 1 -parallel 20 -run='TestAccCloudFrontDistribution_grpcConfig'  -timeout 360m
^@2025/01/03 16:46:16 Initializing Terraform AWS Provider...
=== RUN   TestAccCloudFrontDistribution_grpcConfig
=== PAUSE TestAccCloudFrontDistribution_grpcConfig
=== CONT  TestAccCloudFrontDistribution_grpcConfig
--- PASS: TestAccCloudFrontDistribution_grpcConfig (297.57s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/cloudfront 302.170s
...
```
=> feat: added support for grpc config in cloudfront

ROADMAP.md
January _2024_ -> January _2025_.
=> Correct year in `ROADMAP.md`

internal/service/organizations/sweep.go, internal/sweep/register_gen_test.go
Adds sweeper for `aws_organizations_organizational_unit`
=> sweeper: `aws_organizations_organizational_unit`

.changelog/40210.txt, .changelog/40794.txt
Corrections and additions.
Relates #40794.
Relates #40210.
=> Fixup CHANGELOG entries

.changelog/40972.txt, internal/service/medialive/exports_test.go, internal/service/medialive/multiplex_program.go, website/docs/r/medialive_multiplex_program.html.markdown
remove expanders/flatteners and use autoflex.
```console
% make testacc TESTS=TestAccMediaLive_serial/MultiplexProgram PKG=medialive
TF_ACC=1 go1.23.3 test ./internal/service/medialive/... -v -count 1 -parallel 20 -run='TestAccMediaLive_serial/MultiplexProgram'  -timeout 360m -vet=off
2025/01/16 16:43:23 Initializing Terraform AWS Provider...
=== RUN   TestAccMediaLive_serial
=== PAUSE TestAccMediaLive_serial
=== CONT  TestAccMediaLive_serial
=== RUN   TestAccMediaLive_serial/MultiplexProgram
=== RUN   TestAccMediaLive_serial/MultiplexProgram/basic
=== RUN   TestAccMediaLive_serial/MultiplexProgram/update
=== RUN   TestAccMediaLive_serial/MultiplexProgram/disappears
--- PASS: …
```
=> r/medialive_multiplex_program: use autoflex

website/docs/ephemeral-resources/ssm_parameter.html.markdown
This PR is to fix a simple typo found in the `aws_ssm_parameter` ephemeral resource documentation.
Closes #41008
n/a
n/a
=> docs: Fix typo in aws_ssm_parameter ephemeral resource doc

internal/service/secretsmanager/secret_rotation_test.go
This PR is to fix the test case originally named `TestAccSecretsManagerSecretRotation_scheduleExpression` for the `aws_secretsmanager_secret_rotation` resource where it was not properly testing changes to the schedule expression, and when it does, resource update fails because of the pending rotation. The fix is to add a `PreConfig` function to cancel the rotation before the next test step that updates the schedule expression.
I also changed the name of the test case to `TestAccSecretsManagerSecretRotation_scheduleExpressionBasic` so that it can be run independently from other test cases such as `TestAccSecretsManagerSecretRotation_scheduleExpressionHours` and `TestAccSecretsManagerSecretRotation_scheduleExpressionToDays`.
Closes #35023
n/a
```console
$ make testacc …
```
=> test: Fix aws_secretsmanager_secret_rotation scheduled expression test case

website/docs/r/db_parameter_group.html.markdown
Add a note in the `create_before_destroy` section explaining that the new parameter group needs to be created with a different name than the existing one. Also adapt the code snippet.
Closes #41020
=> docs: aws_db_parameter_group: Add note to `create_before_destroy` section

internal/service/bedrockagent/agent.go, internal/service/bedrockagent/sweep.go, internal/sweep/register_gen_test.go
Adds sweepers for
* `aws_bedrockagent_agent`
* `aws_bedrockagent_data_source`
* `aws_bedrockagent_knowledge_base`
=> bedrockagent: Add sweepers

docs/add-a-new-datasource.md
This PR is to make document for registering data source to the provider methods consistent with the given examples, aka adding  **@FrameworkDataSource** to the description.
This issue was not reported.
Regarding the content in https://hashicorp.github.io/terraform-provider-aws/add-a-new-datasource/#register-data-source-to-the-provider
n/a
=> docs: add @FrameworkDataSource method description to register data source to the provider

.ci/tools/go.mod, .ci/tools/go.sum, .ci/tools/main.go
This was previously installed to assist in automating migrations from AWS SDK V1. Now that that effort has completed, we no longer need to bundle this during tool installation.
Relates #32976
=> .ci/tools: remove gopatch

internal/framework/flex/auto_flatten_test.go, internal/framework/flex/bool_test.go
=> Fixes `flex` test names

website/docs/r/connect_instance_storage_config.html.markdown
Updating the accepted values for `aws_connect_instance_storage_config`
Added Values
- `EMAIL_MESSAGES`
- `REAL_TIME_CONTACT_ANALYSIS_CHAT_SEGMENTS`
- `REAL_TIME_CONTACT_ANALYSIS_VOICE_SEGMENTS`
The AWS API doc includes these values as valid:
https://docs.aws.amazon.com/connect/latest/APIReference/API_AssociateInstanceStorageConfig.html#API_AssociateInstanceStorageConfig_RequestBody
=> Adding valid aws_connect_instance_storage_config resource_type

internal/service/vpclattice/sweep.go
Adds a sweeper for the `aws_vpclattice_service_network_resource_association` resource and includes it as a dependency for the `aws_vpclattice_resource_configuration` sweeper. Resource configurations with active service network associations cannot be deleted.
Relates #41295 
```console
% make sweep SWEEPARGS="-sweep-run=aws_vpclattice_resource_gateway -sweep=us-west-2"
go1.23.5 test ./internal/sweep -v -sweep=us-west-2,us-east-1,us-east-2,us-west-1 -sweep-run=aws_vpclattice_resource_gateway -sweep=us-west-2 -timeout 360m -vet=off
2025/02/10 11:26:26 [DEBUG] Running Sweepers for region (us-west-2):
2025/02/10 11:26:26 [DEBUG] Sweeper (aws_vpclattice_resource_configuration) has dependency …
```
=> r/aws_vpclattice_service_network_resource_association: add sweeper

website/docs/r/bedrockagent_data_source.html.markdown
This PR addresses a doc addition for `aws_bedrockagent_data_source` resource . It includes `web_source` and its configurations.
Closes #41223 
https://docs.aws.amazon.com/bedrock/latest/APIReference/API_agent_WebDataSourceConfiguration.html
```console
...
```
=> docs(aws_bedrockagent_data_source): web source config

GNUmakefile
This dependency has already been removed from the `tools` subdirectory, but the installation step was missed in the previous PR.
Relates #41242
=> chore: remove `gopatch` from `make tools` target

.changelog/41472.txt
Add changelog to Cloudwatch Contributor Managed Insight DataSource
Relates #41472
```
=> Add changelog to Cloudwatch Contributor Managed Insight DataSource

internal/service/organizations/organization.go, internal/service/organizations/sweep.go
Adds sweeper for `aws_organizations_account`
=> Adds sweeper for `aws_organizations_account`

docs/terraform-plugin-migrations.md
Adds a brief section to clarify our most recent status are regards SDKv2 > Framework migration.
=> [Docs] Update introduction to plugin migration doc

.changelog/38045.txt, internal/service/directconnect/connection_data_source.go, website/docs/d/dx_connection.html.markdown
Closes #33746
```console
...
```
=> aws_dx_connection state

.ci/providerlint/go.mod
=> make clean-tidy

internal/service/datazone/sweep.go, internal/sweep/register_gen_test.go
Add sweeper for DataZone Domain.
All other list operations require parameters. Removing a domain will remove all underlying resources.
```console
...
```
=> add sweepers for datazone

CHANGELOG.md
Next release is patch **v5.90.1**.
=> Set next release version to `5.90.1`

internal/service/dataexchange/event_action.go, internal/service/dataexchange/exports_test.go, internal/service/dataexchange/service_package_gen.go, internal/service/dataexchange/sweep.go
Adds sweeper for `aws_dataexchange_event_action`
=> sweeper: aws_dataexchange_event_action

docs/makefile-cheat-sheet.md
Documents `modern-fix` target.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/41831.
=> Document `make modern-fix` target

docs/data-handling-and-conversion.md
Adds a proper link to the Terraform core issue to replace the plain text URL which is currently rendered.
=> docs: link to schema union type issue

website/docs/guides/version-6-upgrade.html.markdown
Adds an initial _Terraform AWS Provider Version 6 Upgrade Guide_.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/41775.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/41941.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/41948.
=> Add Terraform AWS Provider Version 6 Upgrade Guide

internal/service/sagemaker/domain.go
Closes #0000
```console
...
```
=> r/sagemaker_domain - use DomainId from API

.github/workflows/maintainer_helpers.yml
This PR fixes the interpolation of the issue URL for notifications for crashes/regressions
=> Fix interpolation of issue URL in regressions notifier

.changelog/33298.txt, .changelog/39970.txt, CHANGELOG.md
Adds missing CHANGELOG entries from prior v5.x.y releases.
Also updated https://github.com/hashicorp/terraform-provider-aws/releases/tag/v5.93.0 and https://github.com/hashicorp/terraform-provider-aws/releases/tag/v5.72.0.
Relates #33298.
Relates #39970.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/41158.
Relates https://github.com/hashicorp/terraform-provider-aws/issues/17135.
=> Missing CHANGELOG entries

.changelog/42036.txt
Adds CHANGELOG entry for #42036
=> Adds CHANGELOG entry for #42036

.github/ISSUE_TEMPLATE/00_bug_report.yml, .github/ISSUE_TEMPLATE/05_beta_feedback.yml
Updates the bug issue form to bring it more in line with the newly introduced beta feedback form. Also corrected a typo and made a slight wording change to the latter.
I uploaded the same form to my [test repository](https://github.com/justinretzolk/issue-forms-test/issues/new?template=00_bug_report.yml) to preview what it will look like while filling out the form, and opened an [example issue](https://github.com/justinretzolk/issue-forms-test/issues/41) in that repository to preview a final rendered issue.
=> Update bug template

website/docs/r/fms_resource_set.html.markdown
Replace the usage of 'theyy' with 'they' in Firewall manager docs for `aws_fms_resource_set`
```console
...
```
=> r/aws_fms_resource_set: replace theyy with they

.changelog/42141.txt, internal/service/sagemaker/notebook_instance_lifecycle_configuration.go, internal/service/sagemaker/notebook_instance_lifecycle_configuration_test.go, internal/service/sagemaker/service_package_gen.go, website/docs/r/sagemaker_notebook_instance_lifecycle_configuration.html.markdown
Closes #0000
```console
% make testacc TESTS=TestAccSageMakerNotebookInstanceLifecycleConfiguration_ PKG=sagemaker
--- PASS: TestAccSageMakerNotebookInstanceLifecycleConfiguration_basic (14.79s)
--- PASS: TestAccSageMakerNotebookInstanceLifecycleConfiguration_tags (31.19s)
```
=> r/sagemaker_notebook_lifecycle_config - support tags

website/docs/cdktf/python/r/iot_ca_certificate.html.markdown, website/docs/cdktf/python/r/networkfirewall_firewall.html.markdown, website/docs/cdktf/typescript/r/iot_ca_certificate.html.markdown, website/docs/cdktf/typescript/r/networkfirewall_firewall.html.markdown, website/docs/r/iot_ca_certificate.html.markdown, website/docs/r/networkfirewall_firewall.html.markdown
This fixes a couple typos in networkfirewall and iot docs.
N/A
N/A
N/A
=> docs: fix typos in networkfirewall and iot docs

.changelog/42164.txt
Condense to single entry.
Relates #42164.
=> Fixup CHANGELOG entry

.github/actionlint.yml, .github/workflows/acctest-terraform-embedded-lint.yml, .github/workflows/examples.yml, .github/workflows/golangci-lint.yml, .github/workflows/goreleaser-ci.yml, .github/workflows/modern_go.yml, .github/workflows/provider.yml, .github/workflows/providerlint.yml, .github/workflows/website.yml
Updates Actions Workflows to use newer Ubuntu images to handle deprecations
Closes #42221
N/a, workflows
=> Update workflows to newer Ubuntu images

internal/service/apigateway/account.go
=> Removes unused `import`

.changelog/42265.txt, internal/service/mediastore/container.go, internal/service/mediastore/container_policy.go, website/docs/guides/version-6-upgrade.html.markdown, website/docs/r/media_store_container.html.markdown, website/docs/r/media_store_container_policy.html.markdown
This PR deprecates the following resources in the Terraform AWS Provider:
- `aws_media_store_container`
- `aws_media_store_container_policy`
AWS has [announced](https://aws.amazon.com/blogs/media/support-for-aws-elemental-mediastore-ending-soon/) the **end-of-life for AWS Elemental MediaStore**, effective **November 13, 2025**. This decision reflects significant performance and cost improvements to Amazon S3, which now serves as a more efficient and scalable option for live video origination. Additionally, AWS Elemental MediaPackage provides more advanced packaging features for complex media workflows.
With MediaStore being discontinued, its related Terraform resources are being deprecated to guide users toward migrating their infrastructure ahead of the shutdown date.
- For simple live …
=> mediastore: Deprecate resources

.changelog/40855.txt, 40855.txt
Relates #40855
```console
...
```
=> patch: move changelog entry to correct location

website/docs/r/route53_records_exclusive.html.markdown
Closes #0000
```console
...
```
=> docs: update typo

docs/faq.md
Updates the docs FAQ
N/a, docs
=> Update docs FAQ

infrastructure/repository/labels-workflow.tf
Adds a label to help identify issues related to importing resources
N/a, labels infra
=> Add label indicating resource import issues

internal/service/appconfig/sweep.go, internal/service/cloudformation/sweep.go, internal/service/sagemaker/sweep.go
Fixes from running sweepers in the "alt" and "org" test accounts.
=> More sweeper fixes

CHANGELOG.md
Relates https://github.com/hashicorp/terraform-provider-aws/pull/42519.
=> Update CHANGELOG after `v6.0.0-beta1` release

website/docs/d/servicequotas_templates.html.markdown
Standard _Argument Reference_ byline for the `aws_servicequotas_templates` data source.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/42505.
=> d/aws_servicequotas_templates: Standard `Argument Reference` byline

.github/PULL_REQUEST_TEMPLATE.md
Closes #0000
```console
...
```
=> Adds required PCI verbiage to PR template

internal/service/bcmdataexports/export.go, internal/service/bcmdataexports/service_package_gen.go, internal/service/billing/billing_service_account_data_source.go, internal/service/budgets/service_package_gen.go, internal/service/ce/service_package_gen.go, internal/service/costoptimizationhub/enrollment_status.go, internal/service/costoptimizationhub/preferences.go, internal/service/costoptimizationhub/service_package_gen.go, internal/service/cur/service_package_gen.go, internal/service/pricing/service_package_gen.go, names/data/names_data.hcl, website/docs/guides/enhanced-region-support.html.markdown
Marks AWS Billing and Cost Management services as _global_.
Closes https://github.com/hashicorp/terraform-provider-aws/issues/42599.
=> AWS Billing and Cost Management services are global

website/docs/index.html.markdown
1. Updated tutorial links
2. TFE is claiming support for IPv6 in v202505, so I thought we should note that some AWS services do not support IPv6.
Closes #0000
```console
...
```
=> add note about ipv6

names/data/names_data.hcl, website/docs/guides/enhanced-region-support.html.markdown
User Notifications (`notifications`) is a global service.
Relates https://github.com/hashicorp/terraform-provider-aws/issues/34969.
=> notifications: Global service

.ci/tools/go.mod, .ci/tools/go.sum
Upgrade `tfproviderdocs` to **v0.20.0**.
Relates https://github.com/YakDriver/tfproviderdocs/pull/184.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/42711.
=> Upgrade `tfproviderdocs` to v0.20.0

.ci/tools/go.mod, .ci/tools/go.sum
`release/v6.0.0-beta` port of #42716.
=> `release/v6.0.0-beta` port of #42716

CHANGELOG.md
This reverts commit 8d6e0676982514e0547f60fc8b80907b8da7f940.
=> Remove incorrect CHANGELOG modification after `v6.0.0-beta2` release

CHANGELOG.md
Make `v6.0.0-beta2` the top entry.
Also updated the GitHub release notes: https://github.com/hashicorp/terraform-provider-aws/releases/tag/v6.0.0-beta2.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/42734.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/42704.
=> Correct CHANGELOG after `v6.0.0-beta2` release

CHANGELOG.md
The update-changelog action did not run. Updating manually
https://github.com/hashicorp/terraform-provider-aws/actions/runs/15331597066/job/43142718416
Closes #0000
```console
...
```
=> update changelog after release 5.99.0

CHANGELOG.md
Update _Unreleased_ version in CHANGELOG.
=> Next release is `v5.99.1`

internal/service/timestreaminfluxdb/db_instance_test.go
Adds a new acceptance test to try and reproduce the reported `aws_timestreaminfluxdb_db_instance` **v5.91.0** regression.
However, the problem could not be reproduced.
Relates https://github.com/hashicorp/terraform-provider-aws/issues/42170.
```console
% make testacc TESTARGS='-run=TestAccTimestreamInfluxDBDBInstance_upgradeV5_90_0' PKG=timestreaminfluxdb
TF_ACC=1 go1.23.8 test ./internal/service/timestreaminfluxdb/... -v -count 1 -parallel 20 …
```
=> Add `TestAccTimestreamInfluxDBDBInstance_upgradeV5_90_0`

website/docs/guides/enhanced-region-support.html.markdown
Adds a _Migrating from multiple provider configurations_ section to the **Enhanced Region Support** guide.
=> Add 'Migrating from multiple provider configurations' section to Enhanced Region Support guide

.ci/tools/go.mod, .ci/tools/go.sum
Dependency upgrade.
Relates https://github.com/YakDriver/tfproviderdocs/pull/185.
=> Upgrade to `tfproviderdocs` v0.21.0

CHANGELOG.md
This reverts commit 809586a1fe33ac22730f6053c258a9f0b5a5fe8c.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/42734.
=> Remove incorrect CHANGELOG modification after `v6.0.0-beta3` release

.changelog/42338.txt
Ibid.
Relates https://github.com/hashicorp/terraform-provider-aws/issues/42338.
=> Correct new resource name in CHANGELOG

internal/service/opensearchserverless/access_policy.go, internal/service/opensearchserverless/access_policy_data_source.go, internal/service/opensearchserverless/collection.go, internal/service/opensearchserverless/collection_data_source.go, internal/service/opensearchserverless/lifecycle_policy.go, internal/service/opensearchserverless/lifecycle_policy_data_source.go, internal/service/opensearchserverless/security_config.go, internal/service/opensearchserverless/security_config_data_source.go, internal/service/opensearchserverless/security_policy.go, internal/service/opensearchserverless/security_policy_data_source.go, internal/service/opensearchserverless/vpc_endpoint.go, internal/service/opensearchserverless/vpc_endpoint_data_source.go
Add schema descriptions
```console
...
```
=> opensearchserverless resource documentation

website/docs/r/ssm_association.html.markdown
None.
Updated the example documentation and attribute description to resolve #42431
Closes https://github.com/hashicorp/terraform-provider-aws/issues/42431
```console
...
```
=> docs: enhanced aws_ssm_association for multiple instances/tag values

website/docs/r/lightsail_lb.html.markdown, website/docs/r/lightsail_lb_certificate.html.markdown, website/docs/r/lightsail_lb_certificate_attachment.html.markdown, website/docs/r/lightsail_lb_https_redirection_policy.html.markdown, website/docs/r/lightsail_lb_stickiness_policy.html.markdown, website/docs/r/lightsail_static_ip.html.markdown, website/docs/r/lightsail_static_ip_attachment.html.markdown
Relates #42903 
Relates #42907
```console
...
```
=> Lightsail: Revise documentation (part 3)

skaff/datasource/websitedoc.gtpl, skaff/resource/websitedoc.gtpl, website/docs/r/lightsail_bucket.html.markdown, website/docs/r/lightsail_bucket_access_key.html.markdown, website/docs/r/lightsail_bucket_resource_access.html.markdown, website/docs/r/lightsail_certificate.html.markdown, website/docs/r/lightsail_container_service.html.markdown, website/docs/r/lightsail_container_service_deployment_version.html.markdown, website/docs/r/lightsail_database.html.markdown, website/docs/r/lightsail_disk.html.markdown, website/docs/r/lightsail_disk_attachment.html.markdown
Relates #42907 
Relates #42908
```console
...
```
=> Lightsail: Revise documentation (part 1)

website/docs/r/networkmanager_attachment_accepter.html.markdown, website/docs/r/networkmanager_connect_attachment.html.markdown, website/docs/r/networkmanager_connect_peer.html.markdown, website/docs/r/networkmanager_connection.html.markdown, website/docs/r/networkmanager_core_network.html.markdown, website/docs/r/networkmanager_core_network_policy_attachment.html.markdown, website/docs/r/networkmanager_customer_gateway_association.html.markdown, website/docs/r/networkmanager_device.html.markdown, website/docs/r/networkmanager_dx_gateway_attachment.html.markdown, website/docs/r/networkmanager_global_network.html.markdown
Relates:
* #42922
* #42923
* #42925 
Also:
* #42903 
* #42907 
* #42908
```console
...
```
=> networkmanager: Revise documentation (part 1)

website/docs/r/networkmanager_link.html.markdown, website/docs/r/networkmanager_link_association.html.markdown, website/docs/r/networkmanager_site.html.markdown, website/docs/r/networkmanager_site_to_site_vpn_attachment.html.markdown, website/docs/r/networkmanager_transit_gateway_connect_peer_association.html.markdown, website/docs/r/networkmanager_transit_gateway_peering.html.markdown, website/docs/r/networkmanager_transit_gateway_registration.html.markdown, website/docs/r/networkmanager_transit_gateway_route_table_attachment.html.markdown, website/docs/r/networkmanager_vpc_attachment.html.markdown
Relates:
* #42922
* #42923
* #42925 
Also:
* #42903 
* #42907 
* #42908
```console
...
```
=> networkmanager: Revise documentation (part 2)

website/docs/d/bedrock_custom_model.html.markdown, website/docs/d/mq_broker.html.markdown, website/docs/d/mq_broker_engine_types.html.markdown, website/docs/d/mq_broker_instance_type_offerings.html.markdown, website/docs/r/mq_broker.html.markdown, website/docs/r/mq_configuration.html.markdown
Relates:
* #42922
* #42923
* #42925 
* #42903 
* #42907 
* #42908
```console
...
```
=> mq: Revise documentation (part 1 of 1)

website/docs/r/lambda_alias.html.markdown, website/docs/r/lambda_event_source_mapping.html.markdown, website/docs/r/lambda_function.html.markdown, website/docs/r/lambda_function_event_invoke_config.html.markdown, website/docs/r/lambda_function_url.html.markdown, website/docs/r/lambda_layer_version.html.markdown, website/docs/r/lambda_permission.html.markdown, website/docs/r/lambda_provisioned_concurrency_config.html.markdown, website/docs/r/lambda_runtime_management_config.html.markdown
Relates #42935
```console
...
```
=> lambda: Revise documentation (part 1)

CHANGELOG.md
=> v6.0.0 is the next unreleased version on `main` branch

website/docs/r/lakeformation_resource.html.markdown
lakeformation_resource added `with_federation`argument but document is missing
Relates #35154
Closes #42962 
https://docs.aws.amazon.com/lake-formation/latest/dg/federated-catalog-data-connection.html
=> Other: Update website documentation

internal/generate/checknames/main.go, internal/generate/identitytests/main.go, internal/generate/identitytests/resource_test.go.gtpl, names/data/names_data.hcl, names/data/read.go
Populates the `sdk.arn_service` attribute in `names/data/names_data.hcl`
=> Populates the `sdk.arn_service` attribute in `names/data/names_data.hcl`

.changelog/43090.txt
=> CHANGELOG entry for #43090

website/docs/index.html.markdown
Updates the provider version to 6 on the main website readme file.
=> Update index page to show new provider version 6

.changelog/43189.txt, internal/service/rbin/exports_test.go, internal/service/rbin/rule.go, internal/service/rbin/rule_test.go, internal/service/rbin/service_package_gen.go, website/docs/r/rbin_rule.html.markdown
n/a
This PR is to add the `exclude_resource_tags` argument to the `aws_rbin_rule` resource.
Closes #43180.
Closes https://github.com/hashicorp/terraform-provider-aws/pull/40937.
Referred to [CreateRule](https://docs.aws.amazon.com/recyclebin/latest/APIReference/API_CreateRule.html) for specs and wordings.
```console
$ make testacc TESTS=TestAccRBinRule_ PKG=rbin
TF_ACC=1 go1.24.4 test ./internal/service/rbin/... -v -count 1 -parallel 20 -run='TestAccRBinRule_'  -timeout 360m -vet=off
2025/06/25 22:20:43 Creating Terraform AWS Provider (SDKv2-style)...
2025/06/25 22:20:43 Initializing Terraform AWS Provider …
```
=> feat: Add exclude_resource_tags arg to aws_rbin_rule

internal/acctest/vcr.go
The current wrappers around `resource.Test` and `resource.ParallelTest` assume provider factories are set within the `resource.TestCase` struct. Tests which set provider factories within each test step therefore do not properly record and store interactions, leading to slow performance when replaying the test with go-vcr enabled.
This change skips execution of a test when VCR is enabled and the provider factory is not configured at the test case level. Long term, tests with per-step provider factories should be supported, but this change makes the current behavior more explicit and …
=> internal/acctest: skip vcr testing for test step provider factories

docs/go-vcr.md, mkdocs.yml
Adds instructions to the contributor guide for using `go-vcr` in enabled services and enabling it where applicable.
Closes #43362
Relates #25602
=> Go-VCR: add contributor documentation

CHANGELOG.md, internal/service/apigatewayv2/domain_name_test.go, internal/service/dynamodb/table_test.go, website/docs/d/iam_principal_policy_simulation.html.markdown, website/docs/r/comprehend_document_classifier.html.markdown, website/docs/r/comprehend_entity_recognizer.html.markdown, website/docs/r/elastic_beanstalk_application_version.html.markdown
Also, update relevant documentation.
Relates https://github.com/hashicorp/terraform-provider-aws/issues/43420.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/43119.
=> Backfill v6.2.0 CHANGELOG notes with change to S3 Object `id` attribute

internal/acctest/vcr.go
Minor simplification for VCR JSON body comparison.
Relates #25602
=> VCR: Use `internal/json` for comparing VCR request and cassette JSON

skaff/datasource/datasource.gtpl, skaff/datasource/datasourcefw.gtpl, skaff/resource/resource.gtpl, skaff/resource/resourcefw.gtpl
N/A
Integrated smarterr to skaff resource and skaff datasource for streamlined new resource/data source development. See docs/smarterr.md for conversion explanations.
Relates #43121 
```console
N/A
```
=> Feature: Integrated smarterr to skaff 

ROADMAP.md
Relates #43518
```console
...
```
=> fix roadmap linting

infrastructure/repository/labels-workflow.tf
This will be applied to PRs and issues related to resource identity.
=> infrastructure/repository: add `resource-identity` label

tools/tfsdk2fw/go.mod, tools/tfsdk2fw/go.sum, tools/tfsdk2fw/main.go
Ibid.
Closes https://github.com/hashicorp/terraform-provider-aws/issues/43564.
```console
% make tfsdk2fw
make: Installing tfsdk2fw...
cd tools/tfsdk2fw && go1.24.5 install github.com/hashicorp/terraform-provider-aws/tools/tfsdk2fw
```
=> tfsdk2fw: Fix compilation errors

.changelog/43596.txt, internal/service/quicksight/exports_test.go, internal/service/quicksight/ip_restriction.go, internal/service/quicksight/ip_restriction_test.go, internal/service/quicksight/key_registration.go, internal/service/quicksight/quicksight_test.go, internal/service/quicksight/service_package_gen.go, website/docs/r/quicksight_account_settings.html.markdown, website/docs/r/quicksight_account_subscription.html.markdown, website/docs/r/quicksight_analysis.html.markdown, website/docs/r/quicksight_dashboard.html.markdown, website/docs/r/quicksight_data_set.html.markdown, website/docs/r/quicksight_data_source.html.markdown, website/docs/r/quicksight_folder.html.markdown, website/docs/r/quicksight_folder_membership.html.markdown, website/docs/r/quicksight_group.html.markdown, website/docs/r/quicksight_group_membership.html.markdown, website/docs/r/quicksight_iam_policy_assignment.html.markdown, website/docs/r/quicksight_ingestion.html.markdown, website/docs/r/quicksight_ip_restriction.html.markdown, website/docs/r/quicksight_key_registration.html.markdown, website/docs/r/quicksight_namespace.html.markdown, website/docs/r/quicksight_refresh_schedule.html.markdown, website/docs/r/quicksight_role_membership.html.markdown, website/docs/r/quicksight_template.html.markdown, website/docs/r/quicksight_template_alias.html.markdown, website/docs/r/quicksight_theme.html.markdown, website/docs/r/quicksight_user.html.markdown, website/docs/r/quicksight_vpc_connection.html.markdown
Manages the content and status of IP rules.
Closes https://github.com/hashicorp/terraform-provider-aws/issues/43588.
```console
% make testacc TESTARGS='-run=TestAccQuickSight_serial/^IPRestriction$$' PKG=quicksight 
TF_ACC=1 go1.24.5 test ./internal/service/quicksight/... -v -count 1 -parallel 20  -run=TestAccQuickSight_serial/^IPRestriction$ -timeout 360m -vet=off
2025/07/29 15:22:51 Creating Terraform AWS Provider (SDKv2-style)...
2025/07/29 15:22:51 Initializing Terraform AWS Provider …
```
=> New resource: `aws_quicksight_ip_restriction`

go.mod, go.sum
Part of `aws-sdk-go-v2` [Release 2025-07-31](https://github.com/aws/aws-sdk-go-v2/commit/eb0a91b264d3c916f1fa4e4d0c113e72e7330866).
=> github.com/aws/aws-sdk-go-v2/service/s3control@1.62.0

CHANGELOG.md
Corrects the IAM permissions listed in the CHANGELOG.
Relates https://github.com/hashicorp/terraform-provider-aws/issues/43645.
=> Correct IAM permissions in CHANGELOG for access point tagging

internal/sweep/awsv2/skip.go
=> internal/sweep: additional skippable errors

.changelog/43337.txt
Relates #43337
```console
...
```
=> add CHANGELOG entry for #43337

CHANGELOG.md
MIssing CHANGELOG entry from #43871.
Don't forget to update the GitHub release: https://github.com/hashicorp/terraform-provider-aws/releases/tag/v6.9.0.
=> Add missing v6.9.0 CHANGELOG entry

CHANGELOG.md
Fixes # number of EKS deletion protection.
=> Fix changelog # for EKS deletion protection

website/docs/r/vpc_endpoint.html.markdown
N/A
**Are there any changes to security controls (access controls, encryption, logging) in this pull request?** No
Fixing minor typo: `subnet` which should be `subnet_id` within `subnet_configuration`
N/A
N/A
N/A
=> [Docs] resource/aws_vpc_endpoint typo correction

website/docs/r/batch_compute_environment.html.markdown
N/A
Are there any changes to security controls (access controls, encryption, logging) in this pull request? No
Fixes a minor typo where a Batch Compute Environment is referred to as a "computer environment.
N/A
N/A
N/A
=> d/aws_batch_compute_environment: Fix typo

.changelog/44120.txt, internal/service/fsx/openzfs_file_system.go, website/docs/r/fsx_openzfs_file_system.html.markdown
Removes limit of 100 user_and_group_quotas from resource aws_fsx_openzfs_file_system. The existing limit in the resource schema is set to the default AWS Service Quota, customers that have received Service Quota increases may need to apply more than 100 quotas to a single FSx for OpenZFS file system.
Closes #44119
Relates to #44118 
[Resource schema setting maximum number of items to 100 fsx/openzfs_file_system.go:L230](https://github.com/hashicorp/terraform-provider-aws/blob/df2b541465689cb0a80048a01f8230fc617969e2/internal/service/fsx/openzfs_file_system.go#L230)
[FSx for OpenZFS …
=> Remove limit on user_and_group_quotas for aws_fsx_openzfs_file_system

website/docs/d/ssm_parameter.html.markdown
N/A
Are there any changes to security controls (access controls, encryption, logging) in this pull request? No
This PR updates the SSM Parameter data source documentation to clarify how to retrieve a specific parameter version.
Added two example usage blocks:
- Default – retrieves the latest version.
- With version – demonstrates how to query a specific version using the `:version` suffix.
Updated the Argument Reference for `name` to document that a version can be specified by appending `:version` (e.g., `foo:3`).
Closes #44175
N/A
N/A
=> chore: update docs - aws_ssm_parameter data block example and argument reference

go.mod, go.sum
Manual update of `github.com/aws/aws-sdk-go-v2/aws` dependencies to [Release 2025-09-08](https://github.com/aws/aws-sdk-go-v2/commit/648027edb8aeba036195538174a63cbccaca8c16) due to dependabot failures.
Relates https://github.com/hashicorp/terraform-provider-aws/issues/39287.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/43585.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/43619.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/43709.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/43829.
Relates …
=> `aws-sdk-go-v2` updates (Release 2025-09-08)
