hashicorp/terraform-provider-aws

internal/service/neptune/cluster_instance.go, internal/service/neptune/sweep.go, internal/service/rds/sweep.go
Adds sweepers for `aws_neptune_cluster` and `aws_neptune_cluster_instance`. Adds `aws_nepture_cluster` as a dependency for `aws_rds_global_cluster`, as `rds.DescribeGlobalClusters` returns Neptune global clusters as well as RDS global clusters
Closes #0000
```
$ make sweep SWEEPARGS=-sweep-run=aws_rds_global_cluster
2023/01/30 17:16:13 [DEBUG] Running Sweepers for region (us-west-2):
2023/01/30 17:16:13 [DEBUG] Running Sweeper (aws_neptune_cluster_instance) in region (us-west-2)
2023/01/30 17:16:13 [DEBUG] Completed Sweeper (aws_neptune_cluster_instance) in region (us-west-2) in 589.251958ms
2023/01/30 17:16:13 [DEBUG] Sweeper (aws_neptune_cluster) has dependency (aws_neptune_cluster_instance), running..
2023/01/30 17:16:13 [DEBUG] Sweeper (aws_neptune_cluster_instance) already ran in …
```
=> Adds sweepers for `aws_neptune_cluster` and `aws_neptune_cluster_instance`

website/docs/r/lambda_function.html.markdown
This PR addresses the issue https://github.com/hashicorp/terraform-provider-aws/issues/29109.
https://github.com/hashicorp/terraform-provider-aws/commit/bd986c7ab162bd319e4c1b508a2814a0d76d892c changed behavior of the aws lambda function resource, but that change was not reflected in the provider documentation. Since, that commit actually adheres to the original aws documentation, we need to update the provider docs.
Closes #29109 
Related commit: https://github.com/hashicorp/terraform-provider-aws/commit/bd986c7ab162bd319e4c1b508a2814a0d76d892c
Documentation changes, not necessary.
=> [Docs]: fix error in documentation for r/aws_lambda_function

internal/service/auditmanager/control.go, internal/service/auditmanager/framework.go, internal/service/medialive/multiplex_program.go, internal/service/rds/blue_green.go
=> linter: return diagnostic warnings correctly

.actrc, internal/service/dms/endpoint_test.go
Some acceptance tests passed invalid values to `extra_connection_attributes`, resulting in
> InvalidParameterValueException: Unsupported value 'key' for extra connection attributes
```
$ make testacc PKG=dms TESTS=TestAccDMSEndpoint_ 
--- PASS: TestAccDMSEndpoint_MySQL_basic (44.03s)
--- PASS: TestAccDMSEndpoint_Sybase_basic (44.92s)
--- PASS: TestAccDMSEndpoint_PostgreSQL_basic (45.12s)
--- PASS: TestAccDMSEndpoint_Oracle_basic (45.63s)
--- PASS: TestAccDMSEndpoint_Sybase_kmsKey (47.90s)
--- PASS: TestAccDMSEndpoint_SQLServer_kmsKey (48.08s)
--- PASS: TestAccDMSEndpoint_OpenSearch_basic (54.55s)
--- PASS: TestAccDMSEndpoint_MongoDB_secretID (55.40s)
--- PASS: TestAccDMSEndpoint_PostgreSQL_secretID (56.09s)
--- PASS: TestAccDMSEndpoint_OpenSearch_extraConnectionAttributes (56.31s)
--- …
```
=> resource/aws_dms_endpoint: Updates acceptance tests to use valid `extra_connection_attributes` values

.changelog/29243.txt, internal/service/s3/bucket.go
Fixes a reported crash (**v4.49.0**):
```
Error: The terraform-provider-aws_v4.49.0_x5 plugin crashed!
Stack trace from the terraform-provider-aws_v4.49.0_x5 plugin:
panic: interface conversion: interface {} is nil, not map[string]interface {}
goroutine 406 [running]:
github.com/hashicorp/terraform-provider-aws/internal/service/s3.resourceBucketInternalLoggingUpdate(0xc0010a01e0, 0xc000da8c80)
github.com/hashicorp/terraform-provider-aws/internal/service/s3/bucket.go:1889 +0x41f
github.com/hashicorp/terraform-provider-aws/internal/service/s3.resourceBucketUpdate(0xc000da8c80, {0xca6d140?, 0xc0003b7800})
github.com/hashicorp/terraform-provider-aws/internal/service/s3/bucket.go:874 +0x129d
github.com/hashicorp/terraform-provider-aws/internal/service/s3.resourceBucketCreate(0x0?, {0xca6d140?, …
```
=> r/aws_s3_bucket.logging: Fix `panic: interface conversion: interface {} is nil, not map[string]interface {}`

website/docs/r/api_gateway_rest_api.html.markdown
Removes out-of-data requirement on `endpoint.types` for non-Commercial partitions.
Closes https://github.com/hashicorp/terraform-provider-aws/issues/22583.
=> r/aws_api_gateway_rest_api: Remove out-of-date endpoint types note

website/docs/r/security_group.html.markdown
As mentioned in issue #27820 traffic can be blocked on a resource if you create a security group without any of the available `cidr_block` parameters. It's intentional to have these optional so that you're not forced to have all of them present if you only need one or the other. A note should be present informing the user about that not providing any of them could lead to your traffic being blocked. 
Closes #27820
=> (docs): Inform about potential traffic blocking

.changelog/29245.txt, .ci/.semgrep.yml, .ci/semgrep/aws/arn.yml, .github/workflows/semgrep-ci.yml, GNUmakefile, internal/service/apigateway/integration.go, internal/service/iam/group_policy_attachment_test.go, internal/service/iam/role_policy_attachment_test.go, internal/service/iam/user_policy_attachment_test.go, internal/service/iam/wait.go, internal/service/kms/grant.go, internal/service/kms/grant_test.go
In some cases, there is a race condition with KMS Key Grants where an IAM unique id is returned instead of a valid principal ARN. Retry reading until the principals are valid. Previously, the state would not be updated.
```
$ make testacc PKG=kms TESTS=TestAccKMSGrant_
--- PASS: TestAccKMSGrant_arn (22.03s)
--- PASS: TestAccKMSGrant_withRetiringPrincipal (22.07s)
--- PASS: TestAccKMSGrant_asymmetricKey (22.14s)
--- PASS: TestAccKMSGrant_basic (22.15s)
--- PASS: TestAccKMSGrant_bare (29.06s)
--- PASS: TestAccKMSGrant_withConstraints (37.19s)
--- PASS: TestAccKMSGrant_disappears (200.27s)
```
=> resource/aws_kms_grant: Retries read until principals return valid ARNs

.changelog/28699.txt, internal/create/errors.go, internal/flex/flex.go, internal/flex/flex_test.go, internal/provider/provider.go, internal/service/lightsail/bucket_access_key.go, internal/service/lightsail/bucket_access_key_test.go, internal/service/lightsail/consts.go, internal/service/lightsail/find.go, website/docs/r/lightsail_bucket_access_key.html.markdown
This Pull request Implements a new resource: `aws_lightsail_bucket_access_key` which allows creating and managing lightsail bucket access keys. 
Additionally this pull request also implements a shared `ResourceSeparator` constant and the `ExpandResourceId` and `FlattenResourceId` functions for standardizing on a common resource separator as discussed in #27843 , so that new resources can start using this new standard. 
Relates #27843
```
➜ terraform-provider-aws (f-aws_lightsail_bucket_access_key) ✗ make testacc TESTARGS='-run=TestAccLightsailBucketAccessKey' PKG=lightsail
TF_ACC=1 go test ./internal/service/lightsail/... -v -count 1 -parallel 20  -run=TestAccLightsailBucketAccessKey -timeout 180m
=== RUN …
```
=> New Resource: `aws_lightsail_bucket_access_key`. New Shared Resource Separator and associated functions

.github/workflows/golangci-lint.yml, internal/flex/flex_test.go
Fixes:
```console
% make golangci-lint
==> Checking source code with golangci-lint...
internal/flex/flex_test.go:48:1: Function TestExpandResourceId missing the call to method parallel (paralleltest)
func TestExpandResourceId(t *testing.T) {
^
internal/flex/flex_test.go:65:1: Function TestExpandResourceIdEmptyPart missing the call to method parallel (paralleltest)
func TestExpandResourceIdEmptyPart(t *testing.T) {
^
internal/flex/flex_test.go:74:1: Function TestExpandResourceIdIncorrectPartCount missing the call to method parallel (paralleltest)
func TestExpandResourceIdIncorrectPartCount(t *testing.T) {
^
internal/flex/flex_test.go:83:1: Function TestExpandResourceIdSinglePart missing the call to method parallel (paralleltest)
func TestExpandResourceIdSinglePart(t *testing.T) {
^ …
```
=> Fix golangci-lint `paralleltest` errors

website/docs/d/eks_cluster_auth.html.markdown
Just stumbled upon this! As of `hashicorp/kubernetes` version 2.0.0 the `load_config_file` attribute has been removed and is not required any more.
https://github.com/hashicorp/terraform-provider-kubernetes/issues/1223#issuecomment-824117215
`n/a`
=> Fix example for `aws_eks_cluster_auth` datasource

website/docs/r/codebuild_webhook.html.markdown
The codebuild_webhook example should use BASE_REF instead of HEAD_REF. BASE_REF would refer to a branch like `master` or `main`, whereas `HEAD_REF` would refer to a feature branch. Since most people are probably using Codebuild to run CI tests on their pull requests, and their pull requests are meant to merge into master, changing this to BASE_REF provides a more easily pasteable example.
=> codebuild_webhook example should use BASE_REF

website/docs/d/rds_cluster.html.markdown
This PR add the `tags` attribute to the RDS Cluster datasource documentation, and fix the error described in #27090. The end user was redirected on the RDS Cluster resource, but the attribute for getting resource tags is different on the datasource than the resource. 
Closes #27090
=> docs: add `tags` attribute to RDS Cluster data source

.changelog/29294.txt, internal/service/ec2/vpnclient_endpoint.go, internal/service/ec2/vpnclient_endpoint_data_source_test.go, internal/service/ec2/vpnclient_endpoint_test.go
Changes `aws_ec2_client_vpn_endpoint .authentication_options` from `TypeList` to `TypeSet` as order is not significant.
Closes https://github.com/hashicorp/terraform-provider-aws/issues/25800.
```console
% make testacc TESTARGS='-run=TestAccClientVPNEndpoint_serial/Endpoint_' PKG=ec2 
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 20  -run=TestAccClientVPNEndpoint_serial/Endpoint_ -timeout 180m
=== RUN   TestAccClientVPNEndpoint_serial
=== PAUSE TestAccClientVPNEndpoint_serial
=== CONT  TestAccClientVPNEndpoint_serial
=== RUN   TestAccClientVPNEndpoint_serial/Endpoint_msADAuthAndMutualAuth
=== PAUSE TestAccClientVPNEndpoint_serial/Endpoint_msADAuthAndMutualAuth
=== RUN …
```
=> r/aws_ec2_client_vpn_endpoint: Change `authentication_options` to `TypeSet`

.changelog/29269.txt, GNUmakefile, go.mod, go.sum, internal/service/dynamodb/table.go, internal/service/dynamodb/table_test.go, website/docs/r/dynamodb_table.html.markdown
Closes #29222 
Closes #15409
```console
% make t T=TestAccDynamoDBTable_ P=6 K=dynamodb
TF_ACC=1 go test ./internal/service/dynamodb/... -v -count 1 -parallel 6 -run='TestAccDynamoDBTable_'  -timeout 180m
=== RUN   TestAccDynamoDBTable_basic
=== PAUSE TestAccDynamoDBTable_basic
=== RUN   TestAccDynamoDBTable_disappears
=== PAUSE TestAccDynamoDBTable_disappears
=== RUN   TestAccDynamoDBTable_Disappears_payPerRequestWithGSI
=== PAUSE TestAccDynamoDBTable_Disappears_payPerRequestWithGSI
=== RUN   TestAccDynamoDBTable_extended
=== PAUSE TestAccDynamoDBTable_extended
=== RUN   TestAccDynamoDBTable_enablePITR
=== PAUSE TestAccDynamoDBTable_enablePITR
=== RUN   TestAccDynamoDBTable_BillingMode_payPerRequestToProvisioned
=== PAUSE …
```
=> dynamodb/table: Not recreate on PITR enable

.changelog/29325.txt, internal/service/logs/group.go
Retries the log group's `PutRetentionPolicyWithContext` API call if an IAM eventual consistency error is returned.
Closes https://github.com/hashicorp/terraform-provider-aws/issues/27028.
```console
% make testacc TESTARGS='-run=TestAccLogsGroup_' PKG=logs ACCTEST_PARALLELISM=3
TF_ACC=1 go test ./internal/service/logs/... -v -count 1 -parallel 3  -run=TestAccLogsGroup_ -timeout 180m
=== RUN   TestAccLogsGroup_basic
=== PAUSE TestAccLogsGroup_basic
=== RUN   TestAccLogsGroup_nameGenerate
=== PAUSE TestAccLogsGroup_nameGenerate
=== RUN   TestAccLogsGroup_namePrefix
=== PAUSE TestAccLogsGroup_namePrefix
=== RUN   TestAccLogsGroup_disappears
=== PAUSE TestAccLogsGroup_disappears
=== RUN   TestAccLogsGroup_tags
=== PAUSE …
```
=> r/aws_cloudwatch_log_group: Retry `PutRetentionPolicyWithContext` for IAM eventual consistency

internal/verify/validate.go, internal/verify/validate_test.go
`arn:aws:imagebuilder:us-east-1:third-party:component/cis-benchmark-level-1-amazon-linux` is ARN for one of ImageBuilder Components and  `third-party` is a part of imagebuilder component ARN
Right now it is not possible to use `third-party` as is part of ARN
Closes #29262
```
$ make testacc PKG=imagebuilder ACCTEST_PARALLELISM=3 TESTS="TestAccImageBuilderImageRecipe_"
...
```
=> imagebuilder component validate.go: accountIDRegexp add third-party

.changelog/29217.txt, internal/service/appmesh/route.go
If you create an aws_appmesh_route and provide a spec.0.grpc_route.0.match.service_name it gives an error that you also need to specify a spec.0.grpc_route.0.match.method_name when it is actually the other way around.
=> Moved RequiredWith from wrong attribute on an appmesh route

.changelog/28813.txt, internal/service/ecs/service.go, website/docs/r/ecs_service.html.markdown
Various elements of the aws_ecs_service relating to service_connect_configuration didn't match up with the documented API at https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_ServiceConnectConfiguration.html and https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_ServiceConnectService.html
Closes #28754
```
$ make testacc TESTS=TestAccECSService_ServiceConnect PKG=ecs
TF_ACC=1 go test ./internal/service/ecs/... -v -count 1 -parallel 20 -run='TestAccECSService_ServiceConnect'  -timeout 180m
=== RUN   TestAccECSService_ServiceConnect_basic
=== PAUSE TestAccECSService_ServiceConnect_basic
=== RUN   TestAccECSService_ServiceConnect_full
=== PAUSE TestAccECSService_ServiceConnect_full
=== RUN …
```
=> Align aws_ecs_service security_connect_configuration schema with API

internal/service/ec2/find.go, internal/service/elb/load_balancer.go, internal/service/elb/load_balancer_data_source.go, internal/service/emr/cluster_test.go, internal/service/globalaccelerator/endpoint_group_test.go
We ran into the situation described in issue #22138 where we have multiple security groups with the same name, but differing owners. When attempting to run a plan against a load balancer with one of these security groups attached, it would error out with the message:
```Error: Error looking up ELB Security Group ID: too many results: wanted 1, got 3```
We attempted to pass in a filter to only search for the security group with a certain OwnerID, but it didn't make a difference. This PR is to add the OwnerID as a filter parameter when doing the security group lookup for a load balancer. Since the OwnerID is part of the data structure of security groups and VPCs, the addition of this parameter/filter should be seamless. 
Closes #22138
I am open to suggestions on how to test this. The file …
=> Add ownerid filter to subnet search

.changelog/22339.txt, .changelog/28636.txt, internal/service/kms/wait.go
Relates #27422 (issue also deals with incorrect diff on `policy`)
```
...
```
=> Uptick kms key policy propagation timeout to 10m

internal/service/ec2/vpc_subnet_ids_data_source.go
Having a URL will be helpful for people just getting started with terraform. In my case, without a URL, I got mislead by a google search and ended up in the wrong place:
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/subnet
I'm sorry--this change is untested on my side. I'm very new to terraform and I don't have a development environment for it. The change is pretty trivial, though.
Closes #28645
=> include a doc url in aws_subnet_ids deprecation message

.changelog/28550.txt, internal/service/appflow/connector_profile.go
Fixed bug in validation regex of "aws_appflow_connector_profile" resource causing any given value for the "connector_profile_config.0.connector_profile_properties.0.sapo_data.0.logon_language" field to be denied
Closes #28550
-
Checking the available acceptance tests I quickly realized that due to the huge amount of possible argument combinations on the one hand and the necessity for having a huge bunch of third party applications like Salesforce or SAP available no specific tests for that scenario exists.
However, to test the fix I used my local development environment and checked whether setting an AppFlow Connector's SAP logon language via the updated Terraform Provider code is now possible when using a valid value (e.g. EN), and it worked as expected and is not failing with validation …
=> Fixed bug in validation regex of aws_appflow_connector_profile resource

website/docs/r/cloudfront_distribution.html.markdown
- Added example for using managed policies. 
- Updated default_cache_behavior attribute to specify 'Requires either `cache_policy_id` (prefered) or `forwarded_values` (deprecated) be set.'
- Fixed service names to be proper case.
Relates #29015
* Using managed policies: https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/using-managed-cache-policies.html
=> Added CloudFront managed policy example, added required note

internal/service/datasync/location_hdfs.go
Fixing the ```name_node``` parameter typo in the ```resourceLocationHDFSUpdate``` function located in the ```location_hdfs``` file.
=> Fixing name_node parameter typo

.changelog/28552.txt, .changelog/28600.txt, internal/service/appflow/flow.go, internal/service/appflow/flow_test.go, names/attr_consts.go, website/docs/r/appflow_flow.html.markdown
Fixed naming bug for argument of "source_connector_properties.0.sao_data" schema of "aws_appflow_flow" resource and adjusted documentation accordingly to match actual argument implementation. This change is required to make creating a new AWS AppFlow flow resource having a SAP OData connector configured as source via Terraform possible.
Closes #28552
-
Checking the available acceptance tests I quickly realized that due to the huge amount of possible argument combinations on the one hand and the necessity for having a huge bunch of third party applications like Salesforce or SAP available no specific tests for that scenario exists. 
However, to test the fix I used my local development environment and checked whether creating a AppFlow flow resource via the updated Terraform Provider code …
=> Fixed naming bug for argument of aws_appflow_flow resource

.changelog/28581.txt, .changelog/29202.txt, internal/service/sagemaker/user_profile.go
default_resource_spec are actually not required in sagemaker_user_profiles.
=> fix: default_resource_spec are actually optional

website/docs/d/elb_service_account.html.markdown, website/docs/d/s3_bucket_object.html.markdown, website/docs/d/s3_bucket_objects.html.markdown, website/docs/d/s3_object.html.markdown, website/docs/d/s3_objects.html.markdown, website/docs/guides/version-4-upgrade.html.md, website/docs/r/athena_database.html.markdown, website/docs/r/elastictranscoder_pipeline.html.markdown, website/docs/r/gamelift_build.html.markdown, website/docs/r/gamelift_script.html.markdown, website/docs/r/kinesisanalyticsv2_application.html.markdown, website/docs/r/lb.html.markdown, website/docs/r/s3_bucket_accelerate_configuration.html.markdown, website/docs/r/s3_bucket_analytics_configuration.html.markdown, website/docs/r/s3_bucket_intelligent_tiering_configuration.html.markdown, website/docs/r/s3_bucket_lifecycle_configuration.html.markdown, website/docs/r/s3_bucket_metric.html.markdown, website/docs/r/s3_bucket_object_lock_configuration.html.markdown, website/docs/r/s3_bucket_request_payment_configuration.html.markdown, website/docs/r/s3_bucket_server_side_encryption_configuration.html.markdown, website/docs/r/s3_bucket_versioning.html.markdown, website/docs/r/s3_bucket_website_configuration.html.markdown, website/docs/r/spot_datafeed_subscription.html.markdown, website/docs/r/ssm_maintenance_window_task.html.markdown, website/docs/r/ssm_resource_data_sync.html.markdown
It looks like some of the newer documentation prefers to reference S3 bucket names using the `bucket` attribute instead of the `id` attribute. This works, but the rest of the documentation is overwhelmingly using `id`: there are currently 163 places where `id` is used and 35 where `bucket` is used.
This pull request standardizes references to S3 bucket names so that `id` is always used. That seems consistent with most S3 bucket name references and with how other resources are referenced.
This is the regex I used to find all references, which could be modified to replace all `id` references to `bucket` if that is more desirable:
`(bucket\s{0,}=[\sa-zA-Z0-9_.]{1,}\.)(bucket)$`
=> Documentation Improvement: Make examples for S3 bucket references consistent across documentation

website/docs/r/s3_bucket_server_side_encryption_configuration.html.markdown
s3_bucket_server_side_encryption_configuration needs an S3 bucket name. Based on the https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket#id, the S3 bucket name is the id attribute.
=> Updated s3_bucket_server_side_encryption_configuration documentation

.changelog/27778.txt, internal/service/cloudfront/response_headers_policy.go, internal/service/cloudfront/response_headers_policy_test.go
Resource:aws_cloudfront_response_headers_policy.server_timing_headers_config
Allow 0 for sampling_rate in server_timing_headers_config.
Closes #27721
```
$ make testacc TESTS=TestAccCloudFrontResponseHeadersPolicy_ServerTimingHeadersConfig PKG=cloudfront
TF_ACC=1 go test ./internal/service/cloudfront/... -v -count 1 -parallel 20 -run='TestAccCloudFrontResponseHeadersPolicy_ServerTimingHeadersConfig'  -timeout 180m
=== RUN   TestAccCloudFrontResponseHeadersPolicy_ServerTimingHeadersConfig
=== PAUSE TestAccCloudFrontResponseHeadersPolicy_ServerTimingHeadersConfig
=== CONT  TestAccCloudFrontResponseHeadersPolicy_ServerTimingHeadersConfig
--- PASS: TestAccCloudFrontResponseHeadersPolicy_ServerTimingHeadersConfig (108.71s)
PASS
ok …
```
=> Enable setting of 0 for sampling_rate

.changelog/27704.txt, internal/service/s3/object_data_source.go
This fix allows datasource aws_s3_object to read application/xml.
Closes #27697
```
$ make testacc TESTS=TestAccS3ObjectDataSource PKG=s3
TF_ACC=1 go test ./internal/service/s3/... -v -count 1 -parallel 20 -run='TestAccS3ObjectDataSource'  -timeout 180m
=== RUN   TestAccS3ObjectDataSource_basic
=== PAUSE TestAccS3ObjectDataSource_basic
=== RUN   TestAccS3ObjectDataSource_basicViaAccessPoint
=== PAUSE TestAccS3ObjectDataSource_basicViaAccessPoint
=== RUN   TestAccS3ObjectDataSource_readableBody
=== PAUSE TestAccS3ObjectDataSource_readableBody
=== RUN   TestAccS3ObjectDataSource_kmsEncrypted
=== PAUSE TestAccS3ObjectDataSource_kmsEncrypted
=== RUN   TestAccS3ObjectDataSource_bucketKeyEnabled
=== PAUSE …
```
=> s3 datasource aws_s3_object can read application/xml

.changelog/28530.txt, internal/service/s3/tags.go
Adds support for S3-Compatible services which respond to Tag Requests with "NoSuchTagSetError" instead of "NoSuchTagSet". The current implementation only checks for "NoSuchTagSet" and fails if "NoSuchTagSetError" is received. This should allow both compliant and non-compliant implementations to return gracefully.
The ambiguity was originally described here: https://github.com/hashicorp/terraform-provider-aws/blob/1076f598ee88175e7409c5887edcf87e6cbeab20/internal/service/s3/tags.go#L33
```
$ make testacc TESTS=TestAccS3Bucket_Tags_ignoreTags PKG=s3
TF_ACC=1 go test ./internal/service/s3/... -v -count 1 -parallel 20 -run='TestAccS3Bucket_Tags_ignoreTags'  -timeout 180m
=== RUN   TestAccS3Bucket_Tags_ignoreTags
=== PAUSE …
```
=> adding support for NoSuchTagSetError

.changelog/29371.txt, internal/service/medialive/channel_encoder_settings_schema.go, internal/service/medialive/channel_test.go
This PR fixes an issue where `dvb_sub_pids` is assigned to `audio_pids` and
a typo where `audio_pids` was misspelled `audi_pids`.
```
$ make testacc TESTS=TestAccMediaLiveChannel_m2ts_settings PKG=medialive
... WIP (having a resource limit issue at the moment)
```
=> Fix typo in dvb_sub_pids and audio_pids assignment

website/docs/d/billing_service_account.html.markdown, website/docs/d/cloudtrail_service_account.html.markdown, website/docs/d/elb_service_account.html.markdown, website/docs/d/redshift_service_account.html.markdown
Replaces all instances of heredocs in datasource examples with an `aws_iam_policy_document` datasource so that users can take advantage of the validation and syntax highlighting that the latter provides.
Relates #17714
```
...
```
=> Replace heredoc with aws_iam_policy_document datasource (d/*)

internal/service/kms/grant.go, internal/service/kms/grant_test.go, internal/service/kms/key_data_source_test.go
Tweaks the error message returned on refresh if a principal is not an ARN.
Closes https://github.com/hashicorp/terraform-provider-aws/issues/29340.
```console
% make testacc TESTARGS='-run=TestAccKMSGrant_' PKG=kms ACCTEST_PARALLELISM=3
TF_ACC=1 go test ./internal/service/kms/... -v -count 1 -parallel 3  -run=TestAccKMSGrant_ -timeout 180m
=== RUN   TestAccKMSGrant_basic
=== PAUSE TestAccKMSGrant_basic
=== RUN   TestAccKMSGrant_withConstraints
=== PAUSE TestAccKMSGrant_withConstraints
=== RUN   TestAccKMSGrant_withRetiringPrincipal
=== PAUSE TestAccKMSGrant_withRetiringPrincipal
=== RUN   TestAccKMSGrant_bare
=== PAUSE TestAccKMSGrant_bare
=== RUN   TestAccKMSGrant_arn
=== PAUSE TestAccKMSGrant_arn
=== RUN …
```
=> r/aws_kms_grant: Tweak invalid principal error message

website/docs/d/elb_service_account.html.markdown
Documents the behavior of the `aws_elb_service_account` data source for newer Regions.
Relates https://github.com/hashicorp/terraform-provider-aws/issues/27874.
Relates https://github.com/hashicorp/terraform-provider-aws/issues/29322.
=> d/aws_elb_service_account: Document behavior for newer Regions

internal/service/imagebuilder/image_recipe_test.go
The acceptance test `TestAccImageBuilderImageRecipe_component` currently has a version restriction that references a deprecated depency. This causes a test failure
> Error: creating Image Builder Image Recipe: InvalidParameterValueException: The value supplied for parameter 'components' is not valid. Component ARN 'arn:aws:imagebuilder:us-west-2:aws:component/aws-cli-version-2-linux/1.0.0/1' is deprecated and cannot be included in new Recipes.
```
$ make testacc PKG=imagebuilder TESTS=TestAccImageBuilderImageRecipe_component
--- PASS: TestAccImageBuilderImageRecipe_componentParameter (15.30s)
--- PASS: TestAccImageBuilderImageRecipe_component (23.49s)
```
=> acctest/aws_imagebuilder_image_recipe: removes version restriction

internal/service/iam/policy_model.go, internal/service/iam/policy_model_test.go, internal/service/iam/role.go, internal/service/secretsmanager/secret.go, internal/service/sns/find.go, internal/service/sns/topic.go, internal/tfresource/retry_test.go
In some cases, there is a race condition with Secrets Manager Secrets where an IAM unique id is returned instead of a valid principal ARN. Retry reading until the principals are valid.
```
$ make testacc PKG=secretsmanager TESTS=TestAccSecretsManagerSecret_
--- PASS: TestAccSecretsManagerSecret_withNamePrefix (38.93s)
--- PASS: TestAccSecretsManagerSecret_basic (40.79s)
--- PASS: TestAccSecretsManagerSecret_basicReplica (57.46s)
--- PASS: TestAccSecretsManagerSecret_description (63.58s)
--- PASS: TestAccSecretsManagerSecret_kmsKeyID (65.19s)
--- PASS: TestAccSecretsManagerSecret_RecoveryWindowInDays_recreate (65.50s)
--- PASS: TestAccSecretsManagerSecret_policy (90.05s)
--- PASS: TestAccSecretsManagerSecret_rotationRules (95.67s)
--- PASS: TestAccSecretsManagerSecret_rotationLambdaARN …
```
=> resource/aws_secretsmanager_secret: Retries reading resource until policy returns valid principals

.ci/semgrep/types/nullable.yml, .github/workflows/semgrep-ci.yml, GNUmakefile, internal/experimental/nullable/bool.go, internal/experimental/nullable/bool_test.go, internal/experimental/nullable/float_test.go, internal/experimental/nullable/int_test.go, internal/experimental/nullable/testing.go, internal/service/ec2/ec2_launch_template.go, internal/service/ec2/ec2_launch_template_test.go, internal/service/elbv2/target_group.go, internal/service/elbv2/target_group_test.go, internal/service/imagebuilder/container_recipe.go, internal/service/imagebuilder/image_recipe.go, internal/verify/diff.go, internal/verify/diff_test.go, internal/verify/validate.go, internal/verify/validate_test.go, website/docs/r/launch_template.html.markdown
In `aws_launch_template` replaces type and validation functions with `nullable.TypeNullableBool` and associated functions to make intention more clear. Updates documentation to correct parameters that take nullable bool values.
Also updates nullable bool values in `aws_imagebuilder_container_recipe` and `aws_imagebuilder_image_recipe`.
Relates #27716
```
$ make testacc PKG=ec2 TESTS=TestAccEC2LaunchTemplate_
--- PASS: TestAccEC2LaunchTemplate_cpuOptions (53.19s)
--- PASS: TestAccEC2LaunchTemplate_IAMInstanceProfile_emptyBlock (58.68s)
--- PASS: TestAccEC2LaunchTemplate_networkInterfaceIPv4Prefixes (61.72s)
--- PASS: TestAccEC2LaunchTemplate_CreditSpecification_t4g (63.02s)
--- PASS: TestAccEC2LaunchTemplate_networkInterfaceIPv6Prefixes (63.14s)
--- PASS: TestAccEC2LaunchTemplate_basic …
```
=> Update nullable bool

website/docs/index.html.markdown
The small PR fixes the typo at the custom user-agent paragraph from
> ...environment variable can be set and its value will be directly added to HTTP requestsE.g.,
to
> ...environment variable can be set and its value will be directly added to HTTP requests. E.g.,
N/A
N/A
=> Fix typo in custom user-agent paragraph of provider overview

internal/service/rds/proxy.go, internal/service/wafv2/web_acl.go
Fix [CodeQL _Clear-text logging of sensitive information_](https://codeql.github.com/codeql-query-help/go/go-clear-text-logging/) warnings.
* https://github.com/hashicorp/terraform-provider-aws/security/code-scanning/240
* https://github.com/hashicorp/terraform-provider-aws/security/code-scanning/239
* https://github.com/hashicorp/terraform-provider-aws/security/code-scanning/238
* https://github.com/hashicorp/terraform-provider-aws/security/code-scanning/232
=> Fix CodeQL `go/clear-text-logging` warnings

.changelog/29467.txt, internal/service/medialive/channel_encoder_settings_schema.go, internal/service/medialive/channel_test.go
Change `arib_caption_pid` to `arib_captions_pid` and `arib_caption_pid_control` to `arib_captions_pid_control` so the parameters can be assigned
```
$ make testacc TESTS=TestAccMediaLiveChannel_m2ts_settings PKG=medialive
TF_ACC=1 go test ./internal/service/medialive/... -v -count 1 -parallel 20 -run='TestAccMediaLiveChannel_m2ts_settings'  -timeout 180m
=== RUN   TestAccMediaLiveChannel_m2ts_settings
=== PAUSE TestAccMediaLiveChannel_m2ts_settings
=== CONT  TestAccMediaLiveChannel_m2ts_settings
--- PASS: TestAccMediaLiveChannel_m2ts_settings (85.36s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/medialive	87.405s
```
=> fix typo in arib_captions_pid and arib_captions_pid_control

.changelog/29482.txt, internal/service/elb/lb_ssl_negotiation_policy.go, internal/service/elb/lb_ssl_negotiation_policy_test.go, internal/service/elb/listener_policy.go, internal/service/elb/listener_policy_test.go, website/docs/r/lb_ssl_negotiation_policy.html.markdown, website/docs/r/load_balancer_listener_policy.html.markdown
Closes #13628
```console
$ make testacc PKG=elb TESTS="TestAccELBSSLNegotiationPolicy_|TestAccELBListenerPolicy_"
TF_ACC=1 go test ./internal/service/elb/... -v -count 1 -parallel 20 -run='TestAccELBSSLNegotiationPolicy_|TestAccELBListenerPolicy_'  -timeout 180m
--- PASS: TestAccELBListenerPolicy_basic (19.67s)
--- PASS: TestAccELBListenerPolicy_disappears (20.03s)
--- PASS: TestAccELBSSLNegotiationPolicy_basic (66.53s)
--- PASS: TestAccELBSSLNegotiationPolicy_update (69.65s)
--- PASS: TestAccELBSSLNegotiationPolicy_disappears (78.85s)
--- PASS: TestAccELBListenerPolicy_update (83.03s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/elb	86.537s
...
```
=> aws_load_balancer_listener_policy: add triggers argument

internal/service/ec2/ec2_host_data_source.go, internal/service/ec2/ec2_host_data_source_test.go, internal/service/ec2/ec2_host_test.go, internal/service/ec2/find.go
Use `DescribeXYZPages` in EC2 finders.
```console
% make testacc TESTARGS='-run=TestAccSiteVPNConnection_basic\|TestAccSiteVPNConnection_disappears' PKG=ec2 ACCTEST_PARALLELISM=3
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 3  -run=TestAccSiteVPNConnection_basic\|TestAccSiteVPNConnection_disappears -timeout 180m
=== RUN   TestAccSiteVPNConnection_basic
=== PAUSE TestAccSiteVPNConnection_basic
=== RUN   TestAccSiteVPNConnection_disappears
=== PAUSE TestAccSiteVPNConnection_disappears
=== CONT  TestAccSiteVPNConnection_basic
=== CONT  TestAccSiteVPNConnection_disappears
--- PASS: TestAccSiteVPNConnection_disappears (194.14s)
--- PASS: TestAccSiteVPNConnection_basic (197.47s)
PASS
ok …
```
=> Tech debt: Use paginators in EC2 finders

.github/CODEOWNERS, CODEOWNERS
Adds commented out default owner for attribution without review requested noise.
=> Move CODEOWNERS to root and add commented out default owner line

internal/service/elbv2/listener_rule_test.go
Fixes ELBv2 CI acceptance test failures:
```
=== RUN   TestAccELBV2ListenerRule_oidc
=== PAUSE TestAccELBV2ListenerRule_oidc
=== CONT  TestAccELBV2ListenerRule_oidc
listener_rule_test.go:647: Step 1/1 error: Error running apply: exit status 1
Error: creating IAM Server Certificate (tf-acc-test-877177919464001877): MalformedCertificate: Unable to parse certificate. Please ensure the certificate is in PEM format.
status code: 400, request id: 8b3f55e2-5ab4-4967-924b-a7fd4c199356
with aws_iam_server_certificate.test,
on terraform_plugin_test.tf line 35, in resource "aws_iam_server_certificate" "test":
35: resource "aws_iam_server_certificate" "test" {
--- FAIL: TestAccELBV2ListenerRule_oidc (169.69s)
=== RUN   TestAccELBV2ListenerRule_cognito
=== PAUSE TestAccELBV2ListenerRule_cognito
=== …
```
=> ELBv2: Fix CI acceptance test failures

internal/framework/types/arn.go, internal/framework/types/arn_test.go, internal/framework/types/cidr_block.go, internal/framework/types/cidr_block_test.go, internal/framework/types/duration.go, internal/framework/types/duration_test.go
Fixes the following errors in `ARN`, `CIDRBlock` and `Duration`:
* `ToStringValue` was returning a `attr.ValueStateKnown` string value, even if the underlying value was null or unknown
* `ValueFromTerraform` was returning an error if parsing failed. [Custom type documentation](https://developer.hashicorp.com/terraform/plugin/framework/handling-data/custom-types#attr-type-interface) says that errors should not be returned for invalid data
Closes #29618
Closes #29619
=> Fixes custom Framework types

internal/service/neptune/sweep.go, internal/service/rds/blue_green.go, internal/service/rds/global_cluster.go, internal/service/rds/global_cluster_test.go, internal/service/rds/instance.go, internal/service/rds/sweep.go, internal/tfresource/retry.go
Currently, deleting an RDS Global Cluster can fail with either
> error deleting DB Instance (...): InvalidDBClusterStateFault: Cannot delete the last instance of the master cluster. Delete the replica cluster before deleting the last master cluster instance.
or
> Failed to delete RDS DB Cluster (...): InvalidGlobalClusterStateFault: Unable to delete cluster that is a primary member of global cluster while there are other global cluster members
This PR updates the RDS Global Cluster Delete operation to remove all member clusters from the global cluster.
Closes #26234
Closes #26236
```console
$ make sweep SWEEPARGS=-sweep-run=aws_rds_global_cluster
2023/02/16 17:45:37 [DEBUG] Running Sweepers for region (us-west-2):
2023/02/16 17:45:37 [DEBUG] Running Sweeper (aws_rds_global_cluster) in …
```
=> sweeper/aws_rds_global_cluster: Fixes dependency errors

website/docs/r/api_gateway_deployment.html.markdown
Doc is outdated referring to deprecated `taint` command, updating with `-replace` option and current link
Closes #29113
https://developer.hashicorp.com/terraform/cli/commands/taint
https://developer.hashicorp.com/terraform/cli/commands/plan#replace-address
=> aws_api_gateway_deployment - outdated link

website/docs/r/s3_bucket_object_lock_configuration.html.markdown
Correct case for link `U` -> `u`
Noticed the link didn't work, seems like the upper case was incorrect: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket#using-object-lock-configuration
N/A
Did not run, feel free to toss this.
=> Correct link for using-object-lock-configuration

website/docs/d/route53_delegation_set.html.markdown
This PR fixes route53_delegation_set argument description.
Argument `id` is of delegation set, not zone.
=> Fix route53_delegation_set argument description

website/docs/r/lambda_permission.html.markdown
- The existing example `/*/*/*` works technically, but yields to a warning in AWS Lambda Console. The correct usage would be `/*` as suggested by AWS docs.
- Removed "REST API" from example, because this permission works the same for API Gateway HTTP API.
Documentation states:
```
source_arn = "${aws_api_gateway_rest_api.MyDemoAPI.execution_arn}/*/*/*"
```
This configuration works, but produces an error message in the AWS Lambda Console.
The official AWS documentation for the format can be found here:
https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-control-access-using-iam-policies-to-invoke-api.html#api-gateway-calling-api-permissions
The correct syntax is:
```
arn:aws:execute-api:*:*:* for any resource path in any stage, for any API in any AWS region.
```
The …
=> #29667 Fix example for API Gateway permissions

.changelog/29460.txt, internal/provider/provider.go, internal/service/lightsail/bucket_resource_access.go, internal/service/lightsail/bucket_resource_access_test.go, internal/service/lightsail/consts.go, internal/service/lightsail/find.go, website/docs/r/lightsail_bucket_resource_access.html.markdown
This pull request adds the ability to manage lightsail resource access to lightsail buckets. 
None
```
$ make testacc TESTARGS='-run=TestAccLightsailBucketResourceAccess' PKG=lightsail
TF_ACC=1 go test ./internal/service/lightsail/... -v -count 1 -parallel 20  -run=TestAccLightsailBucketResourceAccess -timeout 180m
=== RUN   TestAccLightsailBucketResourceAccess_basic
=== PAUSE TestAccLightsailBucketResourceAccess_basic
=== RUN   TestAccLightsailBucketResourceAccess_disappears
=== PAUSE TestAccLightsailBucketResourceAccess_disappears
=== CONT  TestAccLightsailBucketResourceAccess_basic
=== CONT  TestAccLightsailBucketResourceAccess_disappears
--- PASS: TestAccLightsailBucketResourceAccess_disappears (65.08s)
--- PASS: …
```
=> New Resource: `aws_lightsail_bucket_resource_access`

internal/service/elasticache/find.go, internal/service/elasticache/replication_group_test.go
ElastiCache now uses Redis 7 as the default engine version. This broke a number of acceptance tests.
```
$ make testacc PKG=elasticache TESTS='TestAccElastiCacheReplicationGroup_|TestAccElastiCacheReplicationGroupDataSource_Engine_Redis_LogDeliveryConfigurations|TestAccElastiCacheGlobalReplicationGroup_'
--- PASS: TestAccElastiCacheReplicationGroup_clusteringAndCacheNodesCausesError (4.75s)
--- PASS: TestAccElastiCacheReplicationGroup_ValidationMultiAz_noAutomaticFailover (5.59s)
--- PASS: TestAccElastiCacheGlobalReplicationGroup_SetParameterGroupOnCreate_NoVersion (6.39s)
--- PASS: TestAccElastiCacheReplicationGroup_enableAtRestEncryption (705.76s)
--- PASS: TestAccElastiCacheGlobalReplicationGroup_SetParameterGroupOnCreate_MinorUpgrade (745.31s)
--- PASS: …
```
=> Fixes ElastiCache acceptance tests for new default Redis engine version

website/docs/r/synthetics_canary.html.markdown
The documentation related to the `s3_bucket` property for the `aws_synthetics_canary` terraform resource, states that you should include "s3://" at the start of the value. This seems to be incorrect.
Closes #20161
I'm not sure what tests are applicable here, I'm happy to take advice from maintainers/contributors on this.
=> Updated CloudWatch synthetics canary docs

.changelog/29728.txt, internal/service/dms/endpoint.go, website/docs/r/dms_endpoint.html.markdown
Closes #29725
```console
% make t T=TestAccDMSEndpoint_S3 K=dms      
TF_ACC=1 go test ./internal/service/dms/... -v -count 1 -parallel 20 -run='TestAccDMSEndpoint_S3'  -timeout 180m
=== RUN   TestAccDMSEndpoint_S3_basic
=== PAUSE TestAccDMSEndpoint_S3_basic
=== RUN   TestAccDMSEndpoint_S3_key
=== PAUSE TestAccDMSEndpoint_S3_key
=== RUN   TestAccDMSEndpoint_S3_extraConnectionAttributes
=== PAUSE TestAccDMSEndpoint_S3_extraConnectionAttributes
=== RUN   TestAccDMSEndpoint_S3_SSEKMSKeyARN
=== PAUSE TestAccDMSEndpoint_S3_SSEKMSKeyARN
=== RUN   TestAccDMSEndpoint_S3_SSEKMSKeyId
=== PAUSE TestAccDMSEndpoint_S3_SSEKMSKeyId
=== CONT  TestAccDMSEndpoint_S3_basic
=== CONT  TestAccDMSEndpoint_S3_SSEKMSKeyARN
=== CONT …
```
=> `aws_dms_endpoint`: Deprecate `s3_settings`

README.md, docs/index.md
This PR adds a link to the Google Form that we've set up to request to be added to the Contributors Slack channel. While I was at it, removed the link to Gitter, since we no longer use this service.
N/a
N/a
N/a, docs
=> Add Contributors Slack Google Form

.goreleaser.yml
Currently `goreleaser check` is failing on PR checks with the following deprecation notice:
```console
goreleaser check
• loading config file                              file=.goreleaser.yml
• checking config...
• DEPRECATED: `archives.rlcp` will be the default soon, check https://goreleaser.com/deprecations#archivesrlcp for more info
⨯ command failed                                   error=config is valid, but uses deprecated properties, check logs above for details
```
Note this deprecation notices causes the check to fail:
https://github.com/hashicorp/terraform-provider-aws/actions/runs/4305748833/jobs/7508642247
The notice points to this goreleaser deprecation:
https://goreleaser.com/deprecations/#archivesrlcp
This PR adds the `rlcp` default to get rid of the deprecation warning, …
=> GoReleaser - add new rlcp default setting to remove deprecation notice

.changelog/21293.txt, internal/conns/config.go, internal/service/ec2/ec2_ami_data_source_test.go, internal/service/ec2/ec2_spot_fleet_request_test.go
What actually happends:
- terrafrom call RunInstances (https://github.com/hashicorp/terraform-provider-aws/blob/v3.62.0/aws/resource_aws_instance.go#L771)
- AWS SDK run `Request.Send` inside `EC2.RunInstances` (https://github.com/aws/aws-sdk-go/blob/v1.40.9/service/ec2/api.go#L41652)
- inside Request.Send loop (https://github.com/hashicorp/terraform-provider-aws/blob/v3.62.0/awsproviderlint/vendor/github.com/aws/aws-sdk-go/aws/request/request.go#L537-L560):
- client send request to AWS service for running instance (https://github.com/hashicorp/terraform-provider-aws/blob/v3.62.0/awsproviderlint/vendor/github.com/aws/aws-sdk-go/aws/request/request.go#L546) and got response with **HTTP status code 500** and error code **InsufficientInstanceCapacity**
- there are no **Retry** handles in …
=> Don't retry on `InsufficientInstanceCapacity` error

.ci/.golangci2.yml, docs/resource-name-generation.md, docs/resource-tagging.md, internal/acctest/framework.go, internal/service/auditmanager/account_registration_test.go, internal/service/auditmanager/assessment_delegation_test.go, internal/service/auditmanager/assessment_report_test.go, internal/service/auditmanager/assessment_test.go, internal/service/auditmanager/control_test.go, internal/service/auditmanager/framework_share_test.go, internal/service/auditmanager/framework_test.go, internal/service/auditmanager/organization_admin_account_registration_test.go, internal/service/ec2/vpc_security_group_egress_rule_test.go, internal/service/ec2/vpc_security_group_ingress_rule_test.go, internal/service/medialive/multiplex_program_test.go, internal/service/resourceexplorer2/index_test.go, internal/service/resourceexplorer2/view_test.go, internal/service/route53/cidr_collection_test.go, internal/service/simpledb/domain_test.go, internal/sweep/framework.go, internal/tfresource/retry_test.go
Adds missing `context.Context` parameter to `acctest.CheckFrameworkResourceDisappears`.
Also cleans up documentation, sweeper, and `errorlint`
=> Adds context parameter to `acctest.CheckFrameworkResourceDisappears`

.changelog/29721.txt, internal/service/lambda/function.go
Adds additional plan time validators for the `aws_lambda_function` resource.
Closes #22897
Relates #13709 
- https://docs.aws.amazon.com/lambda/latest/dg/API_CreateFunction.html#SSS-CreateFunction-request-MemorySize
- https://docs.aws.amazon.com/lambda/latest/dg/API_CreateFunction.html#SSS-CreateFunction-request-Role
- https://docs.aws.amazon.com/lambda/latest/dg/API_CreateFunction.html#SSS-CreateFunction-request-Timeout
```
$ make testacc PKG=lambda TESTS=TestAccLambdaFunction_
TF_ACC=1 go test ./internal/service/lambda/... -v -count 1 -parallel 20 -run='TestAccLambdaFunction_'  -timeout 180m
--- PASS: TestAccLambdaFunction_Zip_validation (8.32s)
=== CONT  TestAccLambdaFunction_nameValidation
--- PASS: …
```
=> `r/aws_lambda_function`: Add `memory_size`, `role`, and `timeout` validation

internal/service/sqs/exports_test.go, internal/service/sqs/queue_test.go, internal/tfresource/retry.go
SQS Queues appear to be strongly eventually consistent, especially across different connections: One connection may report the queue is not found, while another will show it as still existing.
This was causing intermittent "dangling resource" errors in acceptance tests.
```
$ make testacc PKG=sqs TESTS=TestAccSQSQueue_
--- PASS: TestAccSQSQueue_FIFOQueue_expectNameError (5.75s)
--- PASS: TestAccSQSQueue_StandardQueue_expectContentBasedDeduplicationError (6.89s)
--- PASS: TestAccSQSQueue_basic (68.17s)
--- PASS: TestAccSQSQueue_NameGenerated_fifoQueue (68.17s)
--- PASS: TestAccSQSQueue_FIFOQueue_contentBasedDeduplication (68.32s)
--- PASS: TestAccSQSQueue_Name_generated (68.42s)
--- PASS: TestAccSQSQueue_zeroVisibilityTimeoutSeconds (68.75s)
--- PASS: TestAccSQSQueue_fifoQueue (68.94s)
--- …
```
=> Retries finding SQS Queue in tests to handle eventual consistency

.ci/semgrep/migrate/context.yml, internal/acctest/acctest.go, internal/acctest/context.go, internal/service/transfer/acc_test.go, internal/service/transfer/server_test.go, internal/service/workspaces/workspace_data_source_test.go
Creates a logging context for acceptance test functions such as pre-checks and test checks.
Adds log field `test_name`.
N/A
=> Add logging to acceptance tests

internal/service/organizations/account.go, internal/service/organizations/account_test.go
Updates "Accounts" acceptance test PreCheck to require an existing organization. This prevents the creation of a new organization and child account(s) within the same test, which would then require waiting 90 days before the child account(s) can be permanently deleted and the management account returned to a "non-organization" state.
Test account is currently over the [quota for account closures](https://docs.aws.amazon.com/organizations/latest/userguide/orgs_reference_limits.html), so tests are failing while attempting to close child accounts.
```
$ TEST_AWS_ORGANIZATION_ACCOUNT_EMAIL_DOMAIN=hashicorp.com make testacc PKG=organizations TESTS="TestAccOrganizations_serial/Account/basic|TestAccOrganizations_serial/Account/CloseOnDeletion|TestAccOrganizations_serial/Account/ParentId|TestAccOr …
```
=> `r/aws_organizations_account`: Test cleanup

.changelog/29772.txt, internal/acctest/acctest.go, internal/service/dms/endpoint.go, internal/service/dms/endpoint_test.go, internal/service/dms/s3_endpoint.go, internal/service/dms/s3_endpoint_test.go, website/docs/r/dms_s3_endpoint.html.markdown
Closes #0000
```console
% make t T=TestAccDMSS3Endpoint_ K=dms                                     
TF_ACC=1 go test ./internal/service/dms/... -v -count 1 -parallel 20 -run='TestAccDMSS3Endpoint_'  -timeout 180m
=== RUN   TestAccDMSS3Endpoint_basic
=== PAUSE TestAccDMSS3Endpoint_basic
=== RUN   TestAccDMSS3Endpoint_update
=== PAUSE TestAccDMSS3Endpoint_update
=== RUN   TestAccDMSS3Endpoint_simple
=== PAUSE TestAccDMSS3Endpoint_simple
=== RUN   TestAccDMSS3Endpoint_sourceSimple
=== PAUSE TestAccDMSS3Endpoint_sourceSimple
=== RUN   TestAccDMSS3Endpoint_source
=== PAUSE TestAccDMSS3Endpoint_source
=== RUN   TestAccDMSS3Endpoint_detachTargetOnLobLookupFailureParquet
=== PAUSE TestAccDMSS3Endpoint_detachTargetOnLobLookupFailureParquet …
```
=> dms/endpoint: Add s3 setting detachTargetOnLobLookupFailureParquet

internal/service/amplify/app_test.go, internal/service/eks/fargate_profile_test.go, internal/service/elasticache/subnet_group_data_source_test.go, internal/service/mediaconvert/queue.go, internal/service/mediaconvert/queue_test.go, internal/service/memorydb/subnet_group_test.go, internal/service/route53/traffic_policy_instance_test.go
Makes use of helpers in `acctest` and adds `Context` where missing.
```console
% make testacc TESTARGS='-run=TestAccEKSFargateProfile_' PKG=eks ACCTEST_PARALLELISM=3
TF_ACC=1 go test ./internal/service/eks/... -v -count 1 -parallel 3  -run=TestAccEKSFargateProfile_ -timeout 180m
=== RUN   TestAccEKSFargateProfile_basic
=== PAUSE TestAccEKSFargateProfile_basic
=== RUN   TestAccEKSFargateProfile_disappears
=== PAUSE TestAccEKSFargateProfile_disappears
=== RUN   TestAccEKSFargateProfile_Multi_profile
=== PAUSE TestAccEKSFargateProfile_Multi_profile
=== RUN   TestAccEKSFargateProfile_Selector_labels
=== PAUSE TestAccEKSFargateProfile_Selector_labels
=== RUN   TestAccEKSFargateProfile_tags
=== PAUSE TestAccEKSFargateProfile_tags
=== …
```
=> Tech debt: Tidy up some service-level `testAccPreCheck` functions

website/docs/r/codebuild_project.html.markdown
Updates to outdated descriptions for `secondary_artifacts` block
Closes #29614
https://docs.aws.amazon.com/codebuild/latest/APIReference/API_CreateProject.html
https://docs.aws.amazon.com/codebuild/latest/APIReference/API_ProjectArtifacts.html
=> aws_codebuild_project - update secondary_artifacts

.changelog/29793.txt, internal/service/grafana/workspace.go, internal/service/grafana/workspace_test.go, website/docs/r/grafana_workspace.html.markdown
Closes #29760
```
$ make testacc TESTS=TestAccGrafana_serial/Workspace PKG=grafana
--- PASS: TestAccGrafana_serial (637.07s)
--- PASS: TestAccGrafana_serial/Workspace (637.07s)
--- PASS: TestAccGrafana_serial/Workspace/networkAccess (637.06s)
```
=> r/grafana_workspace - add `network_access_control` support + removing VPCs

.changelog/29783.txt, internal/service/ecs/service_package_gen.go, internal/service/ecs/task_execution_data_source.go, internal/service/ecs/task_execution_data_source_test.go, website/docs/d/ecs_task_execution.html.markdown
The `aws_ecs_task_execution` data source will enable use cases when a one-time task needs to run on an existing ECS cluster.
As this data source wraps the [`RunTask`](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_RunTask.html) API, it will provision tasks on every read operation where the input attributes are known. This may include `terraform plan` commands, and should be used with caution for any tasks that cannot safely run multiple instances in parallel.
Adapted from #12096
Closes #1703
This data source was modeled after [`aws_lambda_function_invocation`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/lambda_invocation).
```console
$ make testacc PKG=ecs TESTS=TestAccECSTaskExecutionDataSource_ …
```
=> New Data Source: `aws_ecs_task_execution`

website/docs/guides/version-4-upgrade.html.md
When v4 of the provider was launched, there was a plan to deprecate older Terraform versions with v5.0. This is no longer the case, so this section should be removed.
=> Remove note on Terraform version compatibility changes v4 upgrade guide

website/docs/r/lambda_function.html.markdown
I [previously updated this doc](https://github.com/hashicorp/terraform-provider-aws/pull/26509/files), and realized I missed one reference to a filename. This change makes the output file generated by the `archive_file` match the name of the file ingested by `aws_lambda_function`. 
cc: @breathingdust since we worked together on the last one. 
Relates #26509
n/a
=> Fix file name reference for docs

.changelog/29820.txt, internal/acctest/acctest.go, internal/errs/diag.go, internal/service/batch/container_properties.go, internal/service/batch/container_properties_test.go, internal/service/batch/job_definition.go, internal/service/batch/job_definition_test.go
The AWS API accepts container properties environment variables with empty values, but ignores them. They do not get set on the Batch Job Description, and therefore do not get returned. This causes a perpetual diff, and since the field is marked `ForceNew`, the recreation of the resource.
In the AWS Console, a user can create a variable with an empty value, but is not persisted.
This PR ignores the diff when an environment variable has an empty value.
Closes #26960
```
$ make testacc PKG=batch TESTS=TestAccBatchJobDefinition_
--- PASS: TestAccBatchJobDefinition_disappears (13.95s)
--- PASS: TestAccBatchJobDefinition_ContainerProperties_EmptyField (18.50s)
--- PASS: TestAccBatchJobDefinition_ContainerProperties_advanced (18.83s)
--- PASS: TestAccBatchJobDefinition_PlatformCapabilities_ec2 …
```
=> resource/aws_batch_job_description: Ignore diffs on `container_properties` environment variables with an empty value

website/docs/r/apprunner_service.html.markdown
Improve the docs for App Runner service resource's `runtime_environment_secrets`, so that it is explicit and clear what the expected keys/values of the `runtime_environment_secrets` should be.
Closes #29681 
* [AWS App Runner docs on managing environment variables and secrets](https://docs.aws.amazon.com/apprunner/latest/dg/env-variable-manage.html#env-variable-manage.api)
* [AWS App Runner docs on referencing environment variables and secrets](https://docs.aws.amazon.com/apprunner/latest/dg/env-variable.html)
No tests affected, purely a document change
=> docs: improve detail for app runner secrets

website/docs/r/launch_configuration.html.markdown
Since AWS has deprecated this resource, this PR intends to adds a warning to discourage usage in the Terraform provider documentation, with a similar look and feel to the warning message displayed for [aws_kms_secret](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/kms_secret).
=> Add warning about discouraged launch configuration resource

website/docs/r/cognito_resource_server.markdown
The [code](https://github.com/hashicorp/terraform-provider-aws/blob/ae683662502d49e73caf3a8d01fb4689ab400592/internal/service/cognitoidp/resource_server.go#L222) expects to receive a "PoolId|ResourceServerIdentifier" string, not a colon separated string.
=> docs: adjust import syntax of aws_cognito_resource_server

.changelog/29863.txt, internal/service/elasticbeanstalk/configuration_template.go, internal/service/elasticbeanstalk/configuration_template_test.go
Maps errors like `InvalidParameterValue: No Platform named '...' found.` to `resource.NotFoundError` so `terraform refesh` correctly removes the resource.
Closes https://github.com/hashicorp/terraform-provider-aws/issues/29856.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/1222.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/27991.
```console
% make testacc TESTARGS='-run=TestAccElasticBeanstalkConfigurationTemplate_' PKG=elasticbeanstalk ACCTEST_PARALLELISM=3 
TF_ACC=1 go test ./internal/service/elasticbeanstalk/... -v -count 1 -parallel 3  -run=TestAccElasticBeanstalkConfigurationTemplate_ -timeout 180m
=== RUN   TestAccElasticBeanstalkConfigurationTemplate_basic
=== PAUSE …
```
=> r/aws_elastic_beanstalk_configuration_template: Map `InvalidParameterValue: No Platform named ...` to NotFoundError

.changelog/29808.txt, internal/service/medialive/channel_encoder_settings_schema.go, internal/service/medialive/channel_test.go
The `include_fec` attribute in `fec_output_settings` wasn't set correctly.
Relates #27824
```
$ make testacc TESTS=TestAccMediaLiveChannel_udp_output_settings PKG=medialive
TF_ACC=1 go test ./internal/service/medialive/... -v -count 1 -parallel 20 -run='TestAccMediaLiveChannel_udp_output_settings'  -timeout 180m
=== RUN   TestAccMediaLiveChannel_udp_output_settings
=== PAUSE TestAccMediaLiveChannel_udp_output_settings
=== CONT  TestAccMediaLiveChannel_udp_output_settings
--- PASS: TestAccMediaLiveChannel_udp_output_settings (83.58s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/medialive	85.575s
...
```
=> Fix issue with include_fec attribute not being set

website/docs/r/eks_cluster.html.markdown
`satement` != `statement` 🙂  
Closes #29886
N/a, typo
N/a, docs
=> Fix typo in r/aws_eks_cluster

website/docs/r/appsync_datasource.html.markdown, website/docs/r/codebuild_project.html.markdown, website/docs/r/iam_policy_attachment.html.markdown
This PR fixes a few more typos that were introduced in the recent large rewriting of IAM policies switching away from heredoc format.
Closes #29872
Closes #29858
Closes #29855
#29360
#29354
#29356
N/a, docs
=> Fix typos related to policy rewrite

.changelog/29735.txt, internal/conns/config.go
During automated CI/CD deployment of my application, I noticed the next error in my logs:
`ConflictException: Unable to complete operation due to concurrent modification. Please try again later.`
This error occurs when steps to add routes to APIGWV2 resource are started, after 6 routes this error happens.
Looking into the way this is handled in aws provider for apigateway (ver1), I have implemented the same error handling for apigatewayv2.
Closes #18018.
Since this is a simple change I believe tests are not needed.
=> fix: apigatewayv2 error handling for ConflictException: Unable to complete operation due to concurrent modification.

.changelog/29632.txt, internal/service/s3/bucket.go
Hello,
The following patch third party S3 who does not support some bucket features like accelerate configuration.
Example of error message:
```
Error: getting S3 Bucket (my-bucket) accelerate configuration: XNotImplemented: The request you provided implies functionality that is not implemented.
Error: getting S3 Bucket request payment: XNotImplemented: The request you provided implies functionality that is not implemented.
Error: getting S3 Bucket logging: XNotImplemented: The request you provided implies functionality that is not implemented.
```
=> fix: add XNotImplemented error handling in resourceBucketRead

.changelog/27598.txt, internal/service/elasticsearch/domain.go, internal/service/opensearch/domain.go, website/docs/r/elasticsearch_domain.html.markdown, website/docs/r/opensearch_domain.html.markdown
Removes the validation on the elasticsearch EBS throughput.  The existing values are correct based on limits documentation, however, its not entirely accurate.  AWS can increase these values for select customers (we're one) to be > 1000.
Am working with AWS to see if there is any documentation that can be provided here or someone from AWS that can vouch for this.
All failures appear to have been pre-existing as we see these same issues with current TF code.
```
TF_ACC=1 go test ./internal/service/elasticsearch/... -v -count 1 -parallel 20   -timeout 180m
=== RUN   TestAccElasticsearchDomainDataSource_basic
=== PAUSE TestAccElasticsearchDomainDataSource_basic
=== RUN   TestAccElasticsearchDomainDataSource_advanced
=== PAUSE …
```
=> AWS supports higher throughput ranges for select customers

.changelog/29915.txt, internal/service/sagemaker/endpoint_configuration.go, internal/service/sagemaker/endpoint_configuration_test.go
Fix to properly generate `variant_name` when the value is unset in configuration.
Closes #20966
```
$ make testacc PKG=sagemaker TESTS=TestAccSageMakerEndpointConfiguration_
TF_ACC=1 go test ./internal/service/sagemaker/... -v -count 1 -parallel 20 -run='TestAccSageMakerEndpointConfiguration_'  -timeout 180m
--- PASS: TestAccSageMakerEndpointConfiguration_ProductionVariants_serverless (33.27s)
--- PASS: TestAccSageMakerEndpointConfiguration_kmsKeyID (35.24s)
--- PASS: TestAccSageMakerEndpointConfiguration_Async_notif (35.63s)
--- PASS: TestAccSageMakerEndpointConfiguration_shadowProductionVariants (37.68s)
--- PASS: TestAccSageMakerEndpointConfiguration_Async_client (38.32s)
--- PASS: …
```
=> `r/aws_sagemaker_endpoint_configuration`: Fix `variant_name` generation when unset

.changelog/29903.txt, internal/service/lightsail/instance.go, internal/service/lightsail/instance_test.go
This PR corrects the overzealous instance name validation in `aws_lightsail_instance`. Previously the first character of an instance name had to be alphabetic; but can now be alphanumeric. I've added a positive test case for an instance with a numeric first character, and a negative test case for an instance with a symbol first character.
Due to the removal of the `amazon_linux` Lightsail blueprint, I have also updated all `aws_lightsail_instance` acceptance tests to use the `amazon_linux_2` blueprint.
Closes #29899
https://docs.aws.amazon.com/lightsail/2016-11-28/api-reference/API_CreateInstances.html - Note there is no requirement mentioned for instances to start with an alphabetic character
```
$ make testacc TESTS=TestAccLightsailInstance_name PKG=lightsail …
```
=> Fix aws_lightsail_instance name validation

.changelog/29839.txt, internal/service/lambda/function.go, internal/service/lambda/function_test.go
Resource wanted to repeatedly apply a change on an empty environment.variables. Now it will check that the variable is not empty before flattening.
Closes #29255
```
> make testacc TESTARGS='-run=TestAccLambdaFunction_' PKG=lambda
TF_ACC=1 go test ./internal/service/lambda/... -v -count 1 -parallel 20  -run=TestAccLambdaFunction_ -timeout 180m
=== RUN   TestAccLambdaFunction_basic
.......
--- PASS: TestAccLambdaFunction_VPCPublishHas_changes (2135.68s)
--- PASS: TestAccLambdaFunction_disappears (464.75s)
--- PASS: TestAccLambdaFunction_LocalUpdate_nameOnly (635.94s)
--- PASS: TestAccLambdaFunction_localUpdate (572.40s)
--- PASS: TestAccLambdaFunction_unpublishedCodeUpdate (538.12s)
--- PASS: …
```
=> Fix updates on empty env vars in aws_lambda_func

website/docs/r/launch_template.html.markdown
This PR adds gp3 under supported volume types for iops in launch template
Closes https://github.com/hashicorp/terraform-provider-aws/issues/29885
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-launchtemplate-blockdevicemapping-ebs.html
NA
```
...
```
=> Add gp3 under iops section for launch template

.changelog/27351.txt, internal/service/ecs/task_definition.go, internal/service/ecs/task_definition_data_source.go, internal/service/ecs/task_definition_test.go, website/docs/d/ecs_task_definition.html.markdown, website/docs/r/ecs_task_definition.html.markdown
This pull requests adds the attribute `arn_without_revision` to the resource `aws_ecs_task_definition` as explained in issue #27119
Closes #27119
- I do not have an AWS account, so I could not run the tests which require one.
- I'm participating in hacktoberfest 2022. So if you deem this pull request helpful, I'd be glad if you could add the `hacktoberfest-accepted` label to the PR so it helps me reaching the goal :)
=> Add attribute arn_without_revision on aws_ecs_task_definition

website/docs/r/batch_job_definition.html.markdown
Add `jobRoleArn` to Fargate example following AWS example docs
Closes #27919
https://docs.aws.amazon.com/batch/latest/userguide/example-job-definitions.html
https://docs.aws.amazon.com/batch/latest/APIReference/API_ContainerProperties.html
=> aws_batch_job_definition - fix  example

website/docs/r/launch_template.html.markdown
`device_name` is apparently required in a `block_device_mappings` entry of a `aws_launch_template`.
`terraform validate` doesn't fail when it's missing but `apply` will come back with a HTTP 400 error. The [AWS documentation on Block Device Mappings](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/block-device-mapping-concepts.html) also mentions it being required:
> When you create a block device mapping, you specify the following information for each block device that you need to attach to the instance:
> 
> * The device name used within Amazon EC2. The block device driver for the instance assigns the actual volume name when mounting the volume. The name assigned can be different from the name that Amazon EC2 recommends. For more information, see Device names on Linux instances.
The …
=> aws_launch_template: Show safer example for `device_name`, and mark it as required

.github/workflows/acctest-terraform-lint.yml, .github/workflows/changelog.yml, .github/workflows/dependencies.yml, .github/workflows/documentation.yml, .github/workflows/examples.yml, .github/workflows/golangci-lint.yml, .github/workflows/goreleaser-ci.yml, .github/workflows/providerlint.yml, .github/workflows/skaff.yml, .github/workflows/snapshot.yml, .github/workflows/terraform_provider.yml, .github/workflows/website.yml, .github/workflows/workflow-lint.yml
Replaces pinning this action from major version v3 with v3.5.0 via its SHA:
https://github.com/actions/setup-go/releases/tag/v3.5.0
=> Replace version pinning of actions/setup-go to its SHA

.github/workflows/acctest-terraform-lint.yml, .github/workflows/changelog.yml, .github/workflows/documentation.yml, .github/workflows/examples.yml, .github/workflows/goreleaser-ci.yml, .github/workflows/providerlint.yml, .github/workflows/skaff.yml, .github/workflows/snapshot.yml, .github/workflows/terraform_provider.yml, .github/workflows/website.yml
Replaces pinning this action from major version v3 with v3.2.6 via its SHA:
https://github.com/actions/cache/releases/tag/v3.2.6
=> Replace version pinning of actions/cache to its SHA

.github/workflows/acctest-terraform-lint.yml, .github/workflows/changelog.yml, .github/workflows/codeql-analysis.yml, .github/workflows/dependencies.yml, .github/workflows/documentation.yml, .github/workflows/examples.yml, .github/workflows/gen-teamcity.yml, .github/workflows/generate_changelog.yml, .github/workflows/golangci-lint.yml, .github/workflows/goreleaser-ci.yml, .github/workflows/milestone.yml, .github/workflows/mkdocs.yml, .github/workflows/providerlint.yml, .github/workflows/pull_requests.yml, .github/workflows/release.yml, .github/workflows/semgrep-ci.yml, .github/workflows/skaff.yml, .github/workflows/snapshot.yml, .github/workflows/terraform_provider.yml, .github/workflows/website.yml, .github/workflows/workflow-lint.yml, .github/workflows/yamllint.yml
Replaces pinning this action from major version v3 with v3.3.0 via its SHA:
https://github.com/actions/checkout/releases/tag/v3.3.0
=> Replace version pinning of actions/checkout to SHA

website/docs/r/api_gateway_stage.html.markdown, website/docs/r/api_gateway_usage_plan_key.html.markdown
The current documentation provides example usage which includes: 
```terraform
resource "aws_api_gateway_usage_plan" "myusageplan" {
name = "my_usage_plan"
api_stages {
api_id = aws_api_gateway_rest_api.test.id
stage  = aws_api_gateway_deployment.foo.stage_name
}
}
```
The `stage` field here references `aws_api_gateway_deployment`. If you look at the attributes available for that resource [here](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/api_gateway_deployment#attributes-reference) you can see it does not have `stage_name`. 
Instead, this should be referencing `aws_api_gateway_stage`. 
Closes #29913 
- [StackOverflow](https://stackoverflow.com/a/72824794/2558542)
- [`api_gateway_usage_plan_key` Documentation](https://registry.terraform.io/providers/hashicor …
=> docs(api-gateway-usage-plan-key): correct example

website/docs/r/cloudwatch_event_target.html.markdown
The `aws_iam_policy_document` data source needed the `statement` block. Also removed a little bit of extra whitespace while I was at it.
Closes #29969
N/a
N/a, docs
=> Fix `aws_cloudwatch_event_target` example

.changelog/29994.txt, internal/service/ec2/vpc_route.go, internal/service/ec2/vpc_route_test.go
:bug: AWS Route now Support IPv6 Destinations with VPC Endpoints as Targets
Specifically, AWS Network Firewall now supports IPv6 traffic, and in order to route IPv6 traffic there, you need to point the IPv6 destination at the VPC endpoint ID of the network firewall. 
Currently this conflict prevents you from doing so in Terraform.
Closes [#29873 ](https://github.com/hashicorp/terraform-provider-aws/issues/29837)
Added new acceptance test, however I cannot run myself, can someone please run for me?
```
$ make testacc TESTS= TestAccVPCRoute_ipv6ToVPCEndpoint PKG=ec2
...
```
=> :bug: AWS Route now Support IPv6 Destinations with VPC Endpoints as Targets

internal/service/medialive/channel_test.go
update test is intended to only update the name of the `aws_medialive_channel` resource. This fixes current behavior where the names of all resources in the base configs get updated as well.
Relates #29373
```console
$ make testacc TESTS=TestAccMediaLiveChannel_ PKG=medialive
TF_ACC=1 go test ./internal/service/medialive/... -v -count 1 -parallel 20 -run='TestAccMediaLiveChannel_'  -timeout 180m
--- PASS: TestAccMediaLiveChannel_audioDescriptions_codecSettings (75.25s)
--- PASS: TestAccMediaLiveChannel_UDP_outputSettings (90.59s)
--- PASS: TestAccMediaLiveChannel_MsSmooth_outputSettings (92.84s)
--- PASS: TestAccMediaLiveChannel_hls (103.93s)
--- PASS: TestAccMediaLiveChannel_m2ts_settings (108.87s)
--- PASS: …
```
=> [Tests] aws_medialive_channel: update only channel name

.changelog/29896.txt, internal/service/cloudwatch/metric_alarm.go, internal/service/cloudwatch/metric_alarm_test.go, website/docs/r/cloudwatch_metric_alarm.html.markdown
Adds missing `period` parameter to `metric_query` block.
Also adds validation to `metric_query.metric.period`.
Closes #29398.
Closes #28617.
Closes https://github.com/hashicorp/terraform-provider-aws/pull/28547.
```
$ make testacc PKG=cloudwatch TESTS=TestAccCloudWatchMetricAlarm_
--- PASS: TestAccCloudWatchMetricAlarm_missingStatistic (8.67s)
--- PASS: TestAccCloudWatchMetricAlarm_disappears (17.45s)
--- PASS: TestAccCloudWatchMetricAlarm_dataPointsToAlarm (19.02s)
--- PASS: TestAccCloudWatchMetricAlarm_basic (23.23s)
--- PASS: TestAccCloudWatchMetricAlarm_AlarmActions_swfAction (23.46s)
--- PASS: TestAccCloudWatchMetricAlarm_AlarmActions_snsTopic (23.51s)
--- PASS: TestAccCloudWatchMetricAlarm_evaluateLowSampleCountPercentiles (30.60s)
--- PASS: …
```
=> resource/aws_cloudwatch_metric_alarm: Add `period` to `metric_query` block

.changelog/26838.txt, internal/service/ec2/vpc_network_acl_association.go
Signed-off-by: Ringo De Smet <ringo@de-smet.name>
Fixes #23142
Similar to [this comment](https://github.com/hashicorp/terraform-provider-aws/issues/23142#issuecomment-1099539922), we have frequent errors returning:
`Error: error reading EC2 Network ACL Association (aclassoc-XXXXX): empty result`
The change wraps a retry around the function to find the …
=> fix: retry find the association in resourceNetworkACLAssociationRead

website/docs/r/cloudfront_origin_request_policy.html.markdown
Update documentation to support `allExcept` behavior in CloudFront Origin Request Policy Cookies/Header/QueryStrings Config
none
https://docs.aws.amazon.com/cloudfront/latest/APIReference/API_OriginRequestPolicyCookiesConfig.html
https://docs.aws.amazon.com/cloudfront/latest/APIReference/API_OriginRequestPolicyHeadersConfig.html
https://docs.aws.amazon.com/cloudfront/latest/APIReference/API_OriginRequestPolicyQueryStringsConfig.html
none
=> add allExcept behavior to cloudfront_origin_request_policy

.changelog/30042.txt, internal/service/appsync/appsync_test.go, internal/service/appsync/datasource.go, internal/service/appsync/datasource_test.go, internal/service/appsync/graphql_api_test.go, website/docs/r/appsync_datasource.html.markdown
Hi there,
this pull request adds a new argument, event_bridge_config, to the aws_appsync_datasource resource. 
- Added a new event_bridge_config argument to the aws_appsync_datasource resource
- Updated the resource's documentation to include the new event_bridge_config argument
- Added new acceptance tests to cover the event_bridge_config argument and its behavior
Resolves #29625
```
$ make testacc TESTS=TestAccAppSync_serial/DataSource/Type_eventBridge PKG=appsync
TF_ACC=1 go test ./internal/service/appsync/... -v -count 1 -parallel 20 -run='TestAccAppSync_serial/DataSource/Type_eventBridge'  -timeout 180m
=== RUN   TestAccAppSync_serial
=== PAUSE TestAccAppSync_serial
=== CONT  TestAccAppSync_serial
=== RUN …
```
=> Add `event_bridge_config` argument to support AppSync EventBridge data sources

internal/service/rds/cluster_test.go, internal/service/rds/global_cluster.go, internal/service/rds/global_cluster_test.go
When `force_destroy` is `true` the destroy fails if there is no cluster attached.
Closes #30027
```console
$ make testacc TESTARGS='-run=TestAccRDSGlobalCluster_' PKG=rds
TF_ACC=1 go test ./internal/service/rds/... -v -count 1 -parallel 20  -run=TestAccRDSGlobalCluster_ -timeout 180m
--- PASS: TestAccRDSGlobalCluster_disappears (18.51s)
--- PASS: TestAccRDSGlobalCluster_basic (21.48s)
--- PASS: TestAccRDSGlobalCluster_Engine_aurora (22.86s)
--- PASS: TestAccRDSGlobalCluster_EngineVersion_aurora (23.48s)
--- PASS: TestAccRDSGlobalCluster_EngineVersion_auroraPostgreSQL (24.65s)
--- PASS: TestAccRDSGlobalCluster_EngineVersion_auroraMySQL (24.74s)
--- PASS: TestAccRDSGlobalCluster_databaseName (32.93s)
--- PASS: …
```
=> [Tests] aws_rds_global_cluster: destroy fails when `force_destroy = true`

docs/acc-test-environment-variables.md, internal/service/ecrpublic/authorization_token_data_source.go, internal/service/ecrpublic/authorization_token_data_source_test.go, internal/service/ecrpublic/repository_policy_test.go, internal/service/ecrpublic/repository_test.go, website/docs/d/ecrpublic_authorization_token.html.markdown, website/docs/r/ecrpublic_repository.html.markdown, website/docs/r/ecrpublic_repository_policy.html.markdown
Updates documentation for `aws_ecrpublic_authorization_token` data source to indicate that it is only supported in the `us-east-1` region.
Also
* Enables ECR Public acceptance tests to run without special configuration
* Updates documentation for configuring acceptance tests for specific regions
Closes #28281
```
$ make testacc PKG=ecrpublic
--- PASS: TestAccECRPublicRepository_disappears (25.06s)
--- PASS: TestAccECRPublicRepositoryPolicy_Disappears_repository (25.87s)
--- PASS: TestAccECRPublicRepositoryPolicy_disappears (28.95s)
--- PASS: TestAccECRPublicRepository_basic (32.18s)
--- PASS: TestAccECRPublicRepository_CatalogData_logoImageBlob (33.01s)
--- PASS: TestAccECRPublicRepository_Basic_forceDestroy (33.05s)
--- PASS: TestAccECRPublicRepository_CatalogData_operatingSystems …
```
=> data-source/aws_ecrpublic_authorization_token: Update documentation to say `us-east-1`-only

.changelog/30067.txt, internal/service/ecr/repository.go
Fix to properly handle errors that aren't `ResourceNotFound` and nil output values.
Closes #30068
```
$ make testacc PKG=ecr TESTS=TestAccECRRepository_
TF_ACC=1 go test ./internal/service/ecr/... -v -count 1 -parallel 20 -run='TestAccECRRepository_'  -timeout 180m
=== RUN   TestAccECRRepository_basic
=== PAUSE TestAccECRRepository_basic
=== RUN   TestAccECRRepository_disappears
=== PAUSE TestAccECRRepository_disappears
=== RUN   TestAccECRRepository_tags
=== PAUSE TestAccECRRepository_tags
=== RUN   TestAccECRRepository_immutability
=== PAUSE TestAccECRRepository_immutability
=== RUN   TestAccECRRepository_Image_scanning
=== PAUSE TestAccECRRepository_Image_scanning
=== RUN   TestAccECRRepository_Encryption_kms
=== PAUSE …
```
=> r/aws_ecr_repository: handle err, nil output on read

.changelog/29976.txt, internal/service/budgets/budget_action.go, website/docs/r/budgets_budget_action.html.markdown
This PR adds configurable timeouts for the resource's create and delete and extends the default time from 2 mins to 5 mins.
Closes #21664
Closes #20125
```
> make testacc TESTARGS='-run=TestAccBudgetsBudgetAction_' PKG=budgets
TF_ACC=1 go test ./internal/service/budgets/... -v -count 1 -parallel 20  -run=TestAccBudgetsBudgetAction_ -timeout 180m
=== RUN   TestAccBudgetsBudgetAction_basic
=== PAUSE TestAccBudgetsBudgetAction_basic
=== RUN   TestAccBudgetsBudgetAction_disappears
=== PAUSE TestAccBudgetsBudgetAction_disappears
=== CONT  TestAccBudgetsBudgetAction_basic
=== CONT  TestAccBudgetsBudgetAction_disappears
--- PASS: TestAccBudgetsBudgetAction_disappears (22.81s)
--- PASS: TestAccBudgetsBudgetAction_basic (32.42s)
PASS
ok …
```
=> Extend timeouts for aws_budget_actions

.changelog/30073.txt, internal/service/ecs/cluster_data_source.go, internal/service/ecs/cluster_data_source_test.go, website/docs/d/ecs_cluster.html.markdown
Adds `tags` to the `aws_ecs_cluster` data source.
Closes #29420
```
make testacc TESTS=TestAccECSClusterDataSource PKG=ecs
TF_ACC=1 go test ./internal/service/ecs/... -v -count 1 -parallel 20 -run='TestAccECSClusterDataSource'  -timeout 180m
=== RUN   TestAccECSClusterDataSource_ecsCluster
=== PAUSE TestAccECSClusterDataSource_ecsCluster
=== RUN   TestAccECSClusterDataSource_ecsClusterContainerInsights
=== PAUSE TestAccECSClusterDataSource_ecsClusterContainerInsights
=== RUN   TestAccECSClusterDataSource_tags
=== PAUSE TestAccECSClusterDataSource_tags
=== CONT  TestAccECSClusterDataSource_ecsCluster
=== CONT  TestAccECSClusterDataSource_tags
=== CONT  TestAccECSClusterDataSource_ecsClusterContainerInsights
--- PASS: …
```
=> d/aws_ecs_cluster - add tags attribute

skaff/resource/resourcetest.tmpl
One of the `CheckDestroy` functions is missing the `ctx` argument.
N/A
N/A
N/A
=> skaff: Add missing context to the CheckDestroy function

.changelog/30074.txt, internal/acctest/acctest.go, internal/service/cognitoidp/risk_configuration.go, internal/service/cognitoidp/risk_configuration_test.go, website/docs/r/cognito_risk_configuration.html.markdown
Adds validation to the `risk_exception_configuration` parameter
Closes #29508
```
$ make testacc PKG=cognitoidp TESTS=TestAccCognitoIDPRiskConfiguration_
--- PASS: TestAccCognitoIDPRiskConfiguration_nullRiskException (2.70s)
--- PASS: TestAccCognitoIDPRiskConfiguration_emptyRiskException (2.84s)
--- PASS: TestAccCognitoIDPRiskConfiguration_empty (2.88s)
--- PASS: TestAccCognitoIDPRiskConfiguration_disappears_userPool (11.73s)
--- PASS: TestAccCognitoIDPRiskConfiguration_disappears (13.28s)
--- PASS: TestAccCognitoIDPRiskConfiguration_compromised (14.71s)
--- PASS: TestAccCognitoIDPRiskConfiguration_client (15.09s)
--- PASS: TestAccCognitoIDPRiskConfiguration_exception (22.43s)
```
=> resource/aws_cognito_risk_configuration: validation for `risk_exception_configuration`

website/docs/r/vpc_ipam.html.markdown
Add missing outputs for `aws_vpc_ipam` resource.
- `default_resource_discovery_id`
- `default_resource_discovery_association_id`
Terraform actually prints that output.
```bash
+ resource "aws_vpc_ipam" "this" {
+ arn                                       = (known after apply)
+ default_resource_discovery_association_id = (known after apply)
+ default_resource_discovery_id             = (known after apply)
+ description                               = "Test IPAM"
+ id                                        = (known after apply)
+ private_default_scope_id                  = (known after apply)
+ public_default_scope_id                   = (known after apply)
+ scope_count                               = (known after apply)
+ tags                                      = {
...
}
+ tags_all …
```
=> Updated missing outputs for `vpc_ipam` resource

website/docs/r/vpc_ipam_scope.html.markdown
Add missing outputs for `aws_vpc_ipam_scope` resource.
- `arn`
- `type`
Update description of `pool_count` output for `aws_vpc_ipam_scope` resource.
Terraform actually prints that output.
```sh
{
+ arn             = (known after apply)
+ description     = "Managed by Terraform."
+ id              = (known after apply)
+ ipam_arn        = (known after apply)
+ ipam_id         = "ipam-00cd75f95fd04902b"
+ ipam_scope_type = (known after apply)
+ is_default      = (known after apply)
+ pool_count      = (known after apply)
```
Closes #0000
```
...
```
=> Update missing outputs for vpc_iapm_scope resource

.changelog/30094.txt, internal/service/sesv2/contact_list.go, internal/service/sesv2/contact_list_test.go, internal/service/sesv2/list.go, internal/service/sesv2/service_package_gen.go, internal/service/sesv2/sweep.go, website/docs/r/sesv2_contact_list.html.markdown
This PR adds the `aws_sesv2_contact_list` resource.
https://docs.aws.amazon.com/ses/latest/APIReference-V2/
```
$ make testacc TESTARGS="-run=TestAccSESV2ContactList_" PKG=sesv2
TF_ACC=1 go test ./internal/service/sesv2/... -v -count 1 -parallel 20  -run=TestAccSESV2ContactList_ -timeout 180m
=== RUN   TestAccSESV2ContactList_basic
--- PASS: TestAccSESV2ContactList_basic (21.31s)
=== RUN   TestAccSESV2ContactList_description
--- PASS: TestAccSESV2ContactList_description (33.66s)
=== RUN   TestAccSESV2ContactList_topic
--- PASS: TestAccSESV2ContactList_topic (33.77s)
=== RUN   TestAccSESV2ContactList_tags
--- PASS: TestAccSESV2ContactList_tags (33.31s)
=== RUN   TestAccSESV2ContactList_disappears
--- PASS: …
```
=> r/aws_sesv2_contact_list: new resource

.changelog/30101.txt, internal/service/opsworks/application.go, internal/service/pinpoint/app.go
Don't return a `diags` containing a wrapper `nil` error on successful delete.
Closes https://github.com/hashicorp/terraform-provider-aws/issues/30072.
Closes https://github.com/hashicorp/terraform-provider-aws/issues/29341.
```console
% make testacc TESTARGS='-run=TestAccPinpointApp_basic' PKG=pinpoint ACCTEST_PARALLELISM=2
TF_ACC=1 go test ./internal/service/pinpoint/... -v -count 1 -parallel 2  -run=TestAccPinpointApp_basic -timeout 180m
=== RUN   TestAccPinpointApp_basic
=== PAUSE TestAccPinpointApp_basic
=== CONT  TestAccPinpointApp_basic
--- PASS: TestAccPinpointApp_basic (21.89s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/pinpoint	31.491s
% make testacc …
```
=> Pinpoint Application & OpsWorks Application: Don't return an error on successful Delete

website/docs/r/codepipeline.markdown
`resource` != `resources`
Closes #30087
- [`aws_iam_policy_document.statement.resources`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/iam_policy_document#resources)
N/a, docs
=> Fix typo in `aws_codepipeline`

.changelog/30115.txt, internal/service/transfer/server.go
Changed the key in tfMap to "as2_transports" to resolve an error caused by an incorrect key.
key should be "as2_transports":
```go
"as2_transports": {
Type:     schema.TypeSet,
Optional: true,
Computed: true,
Elem: &schema.Schema{
Type:         schema.TypeString,
ValidateFunc: validation.StringInSlice(transfer.As2Transport_Values(), false),
},
},
```
=> fix: correct key in tfMap for AS2 transports

.changelog/30114.txt, GNUmakefile, internal/service/ec2/vpc_security_group.go, internal/service/ec2/vpc_security_group_test.go, website/docs/r/codestarconnections_host.markdown, website/docs/r/security_group.html.markdown
Closes #265
```console
% make ts T=TestAccVPCSecurityGroup_ K=vpc               
TF_ACC=1 go test ./internal/service/ec2/... -v -short -count 1 -parallel 20 -run='TestAccVPCSecurityGroup_'  -timeout 180m
=== RUN   TestAccVPCSecurityGroup_basic
=== PAUSE TestAccVPCSecurityGroup_basic
=== RUN   TestAccVPCSecurityGroup_disappears
=== PAUSE TestAccVPCSecurityGroup_disappears
=== RUN   TestAccVPCSecurityGroup_noVPC
=== PAUSE TestAccVPCSecurityGroup_noVPC
=== RUN   TestAccVPCSecurityGroup_nameGenerated
=== PAUSE TestAccVPCSecurityGroup_nameGenerated
=== RUN   TestAccVPCSecurityGroup_nameTerraformPrefix
=== PAUSE TestAccVPCSecurityGroup_nameTerraformPrefix
=== RUN   TestAccVPCSecurityGroup_namePrefix
=== PAUSE …
```
=> security_group: Destroying takes forever improvements

.ci/.semgrep-service-name3.yml, internal/generate/servicesemgrep/service.tmpl, internal/service/waf/rate_based_rule_data_source_test.go, internal/service/waf/rate_based_rule_test.go
Serializes WAF Rate-Based Rule acceptance tests to avoid hitting resource limits
```
$ make testacc PKG=waf TESTS=TestAccWAFRateBasedRule
--- PASS: TestAccWAFRateBasedRule_serial (190.65s)
--- PASS: TestAccWAFRateBasedRule_serial/resource (177.08s)
--- PASS: TestAccWAFRateBasedRule_serial/resource/basic (19.85s)
--- PASS: TestAccWAFRateBasedRule_serial/resource/changeNameForceNew (36.38s)
--- PASS: TestAccWAFRateBasedRule_serial/resource/disappears (17.62s)
--- PASS: TestAccWAFRateBasedRule_serial/resource/changePredicates (31.44s)
--- PASS: TestAccWAFRateBasedRule_serial/resource/changeRateLimit (28.15s)
--- PASS: TestAccWAFRateBasedRule_serial/resource/noPredicates (13.99s)
--- PASS: TestAccWAFRateBasedRule_serial/resource/Tags (29.66s)
--- PASS: …
```
=> Serializes WAF rate-based rule tests

internal/service/events/bus_policy.go, internal/service/events/permission.go, internal/service/events/validate.go, internal/service/events/validate_test.go, internal/verify/validate.go, website/docs/r/cloudwatch_event_bus_policy.html.markdown, website/docs/r/cloudwatch_event_permission.html.markdown, website/docs/r/cloudwatch_event_rule.html.markdown, website/docs/r/cloudwatch_event_target.html.markdown
For the `event_bus_name` parameter, the EventBridge resources `aws_cloudwatch_event_rule` and  `aws_cloudwatch_event_target` accept a name or ARN, while `aws_cloudwatch_event_bus_policy` and `aws_cloudwatch_event_permission` only accept a name. This PR updates the validation for the four resources.
Closes #18182
```
$ make testacc PKG=events TESTS='TestAccEventsTarget_|TestAccEventsPermission_|TestAccEventsBusPolicy_|TestAccEventsRule_'
--- SKIP: TestAccEventsRule_partnerEventBus (0.00s)
--- SKIP: TestAccEventsTarget_partnerEventBus (0.00s)
--- PASS: TestAccEventsTarget_disappears (95.21s)
--- PASS: TestAccEventsRule_namePrefix (101.97s)
--- PASS: TestAccEventsRule_Name_generated (102.16s)
--- PASS: TestAccEventsRule_scheduleAndPattern (104.38s)
--- PASS: …
```
=> EventBridge `event_bus_name` parameter validation

.changelog/30125.txt, internal/flex/flex.go, internal/flex/flex_test.go, internal/service/inspector2/enabler.go, internal/service/oam/link.go, internal/service/oam/link_test.go, internal/service/oam/service_package_gen.go, website/docs/r/oam_link.html.markdown
This pull requests add an `aws_oam_link` resource which provides the ability to create a link to a [aws_oam_sink](https://github.com/hashicorp/terraform-provider-aws/pull/29670).
Relates #28158
[CreateLink API documentation](https://docs.aws.amazon.com/OAM/latest/APIReference/API_CreateLink.html)
```
➜ make testacc PKG=oam
TF_ACC=1 go test ./internal/service/oam/... -v -count 1 -parallel 20   -timeout 180m
=== RUN   TestExpandResourceTypesUnitTest
=== RUN   TestExpandResourceTypesUnitTest/Empty_resource_types
=== RUN   TestExpandResourceTypesUnitTest/Non-empty_resource_types
--- PASS: TestExpandResourceTypesUnitTest (0.00s)
--- PASS: TestExpandResourceTypesUnitTest/Empty_resource_types (0.00s)
--- PASS: …
```
=> New resource - `aws_oam_link`

internal/service/medialive/channel_test.go
cleanup test names for `aws_medialive_channel`
```console
$ make testacc TESTS=TestAccMediaLiveChannel_ PKG=medialive
TF_ACC=1 go test ./internal/service/medialive/... -v -count 1 -parallel 20 -run='TestAccMediaLiveChannel_'  -timeout 180m
--- PASS: TestAccMediaLiveChannel_AudioDescriptions_codecSettings (74.19s)
--- PASS: TestAccMediaLiveChannel_M2TS_settings (86.47s)
--- PASS: TestAccMediaLiveChannel_disappears (91.49s)
--- PASS: TestAccMediaLiveChannel_basic (97.57s)
--- PASS: TestAccMediaLiveChannel_updateTags (114.05s)
--- PASS: TestAccMediaLiveChannel_UDP_outputSettings (137.55s)
--- PASS: TestAccMediaLiveChannel_MsSmooth_outputSettings (150.22s)
--- PASS: TestAccMediaLiveChannel_update (169.05s)
--- PASS: …
```
=> chore: fix medialive channel test names and parameters

internal/conns/config.go, internal/provider/provider.go
Adds more detailed logging during provider configuration using `tflog`
N/A
=> Adds more detailed logging during provider configuration

internal/service/auditmanager/assessment_delegation_test.go, internal/service/auditmanager/assessment_report_test.go, internal/service/auditmanager/assessment_test.go, internal/service/cognitoidp/managed_user_pool_client_test.go
Adds `force_destroy = true` to the S3 Bucket resources used in Audit Manager acceptance tests to prevent post-test destroy errors:
```
=== NAME  TestAccAuditManagerAssessmentReport_basic
testing_new.go:82: Error running post-test destroy, there may be dangling resources: exit status 1
Error: deleting S3 Bucket (tf-acc-test-3052686201411694568): BucketNotEmpty: The bucket you tried to delete is not empty
status code: 409, request id: E4QS7ACHVC70DG46, host id: xH1DwPLjtA2LWZaKlRKNZTh83RpGzaBT6iGM4dhvL/iFLGQDe9XOBi2s4AtlwRDgkx403Rke+rM=
```
```console
$ make testacc PKG=auditmanager TESTS=TestAccAuditManagerAssessment
TF_ACC=1 go test ./internal/service/auditmanager/... -v -count 1 -parallel 20 -run='TestAccAuditManagerAssessment' …
```
=> Fix AuditManager post-test destroy s3_bucket errors

.github/actionlint.yaml, .github/workflows/golangci-lint.yml
We have started [seeing](https://github.com/hashicorp/terraform-provider-aws/actions/runs/4542741939/jobs/8006580833?pr=29769)
```
Running [/home/runner/golangci-lint-1.52.2-linux-amd64/golangci-lint run --out-format=github-actions --config .ci/.golangci2.yml] in [] ...
Killed
Error: golangci-lint exit with code 137
```
Try the `xl` custom runner.
=> Use `xl` custom runner for main `golangci-lint` job

.changelog/30214.txt, internal/service/ecs/task_execution_data_source.go, internal/service/ecs/task_execution_data_source_test.go
It seems like many of these type assertions are incorrect, running locally I found terraform would panic with things like:
panic: interface conversion: interface {} is *schema.Set, not []interface {}
These changes correct many of them however it's far from complete because the overrides end up with the zero values in places like cpu, memory etc.
Someone who knows more about terraform internal types could use this as a starting point. I can take it forward if I have the time.
Relates #29783
```
...
```
=> `d/aws_ecs_task_execution`: Fix interface conversion panics

.changelog/30299.txt, internal/service/fsx/openzfs_file_system.go
Relates #30058
https://docs.aws.amazon.com/fsx/latest/OpenZFSGuide/performance.html
Test failure unrelated to change and is failing in CI. Looks like returned default values
```console
$ make testacc PKG=fsx TESTS="TestAccFSxOpenzfsFileSystem_"
TF_ACC=1 go test ./internal/service/fsx/... -v -count 1 -parallel 20 -run='TestAccFSxOpenzfsFileSystem_'  -timeout 180m
=== NAME  TestAccFSxOpenzfsFileSystem_rootVolume
openzfs_file_system_test.go:158: Step 1/5 error: After applying this test step and performing a `terraform refresh`, the plan was not empty.
stdout
Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
~ update in-place
Terraform will …
```
=> r/aws_fsx_openzfs_file_system: add validation for `disk_iops_configuration`

.changelog/30352.txt, internal/service/wafv2/ip_set.go, internal/service/wafv2/ip_set_test.go
Diff suppression causes error when all values in `addresses` are not known during plan.
Closes #30351
```console
$ make testacc PKG=wafv2 TESTS="TestAccWAFV2IPSet_"
TF_ACC=1 go test ./internal/service/wafv2/... -v -count 1 -parallel 20 -run='TestAccWAFV2IPSet_'  -timeout 180m
--- PASS: TestAccWAFV2IPSet_disappears (11.70s)
--- PASS: TestAccWAFV2IPSet_ipv6 (16.13s)
--- PASS: TestAccWAFV2IPSet_minimal (21.74s)
--- PASS: TestAccWAFV2IPSet_large (22.03s)
--- PASS: TestAccWAFV2IPSet_basic (25.49s)
--- PASS: TestAccWAFV2IPSet_changeNameForceNew (29.61s)
--- PASS: TestAccWAFV2IPSet_addresses (30.94s)
--- PASS: TestAccWAFV2IPSet_tags (34.71s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/wafv2	38.483s
...
```
=> r/aws_wafv2_ip_set: unknown `addresses` produce error

internal/service/s3/bucket.go, internal/service/s3/object.go
Return `err` if it's non-`nil`.
```console
% make testacc TESTARGS='-run=TestAccS3Bucket_Basic_basic\|TestAccS3Bucket_disappears\|TestAccS3Object_' PKG=s3 ACCTEST_PARALLELISM=3 
TF_ACC=1 go test ./internal/service/s3/... -v -count 1 -parallel 3  -run=TestAccS3Bucket_Basic_basic\|TestAccS3Bucket_disappears\|TestAccS3Object_ -timeout 180m
=== RUN   TestAccS3Bucket_Basic_basic
=== PAUSE TestAccS3Bucket_Basic_basic
=== RUN   TestAccS3Bucket_disappears
=== PAUSE TestAccS3Bucket_disappears
=== RUN   TestAccS3Object_noNameNoKey
=== PAUSE TestAccS3Object_noNameNoKey
=== RUN   TestAccS3Object_empty
=== PAUSE TestAccS3Object_empty
=== RUN   TestAccS3Object_source
=== …
```
=> Correctly return errors from S3 Bucket & Object finders

infrastructure/repository/community.tf, infrastructure/repository/maintainer-list.tf
This PR changes how we create three GitHub Actions Secrets to help with automating via Actions.
Before: #30277
- [`github_repository_file` data source](https://registry.terraform.io/providers/integrations/github/latest/docs/data-sources/repository_file)
- [`github_actions_secret` resource](https://registry.terraform.io/providers/integrations/github/latest/docs/resources/actions_secret)
- [`github_team` data source](https://registry.terraform.io/providers/integrations/github/latest/docs/data-sources/team)
N/a, Actions
=> Switch over to using external source for GHA secrets for community

.github/workflows/community-check.yml
This PR adds a reusable workflow that can be used to determine whether an actor is a Core Contributor, Partner, or Maintainer, for use with other GitHub Actions that depend on these determinations
Depends on: #30276
Before: #30279
- [GitHub: Reusing Workflows](https://docs.github.com/en/actions/using-workflows/reusing-workflows)
- [GitHub: Security Hardening for GitHub Actions](https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions) (This has info on the reasoning behind the `permissions` block and why we need to `add-mask`)
N/a, Actions
Once this is (and the PR that this depends on) is merged, the workflow can be used something like this:
```yaml
name: Label if user is on a list
on: [issues]
jobs:
community_check:
uses: …
```
=> Add Community Check reusable workflow

website/docs/r/cloudfront_origin_access_control.html.markdown
This pull request implements changes to the documentation of the CloudFront Origin Access Control resource. The changes are:
- the `description` field is now optional and will default to `Managed by Terraform` if omitted. 
- the `origin_access_control_origin_type` field now allows for both `s3` and `mediastore` values. 
- semantic enhancements for `signing_behavior` and `signing_protocol` fields.
Closes #30334 
https://docs.aws.amazon.com/cloudfront/latest/APIReference/API_CreateOriginAccessControl.html#API_CreateOriginAccessControl_RequestSyntax
=> [Docs]: aws_cloudfront_origin_access_control arguments reference updates

.changelog/30370.txt, internal/service/glue/crawler.go, internal/service/glue/trigger.go
- According to #30371 the error we tried matching on has changed.
- Thus a retryable error became a non retryable error.
- This PR fixes the string matching, making it retryable again.
Closes https://github.com/hashicorp/terraform-provider-aws/issues/30371.
```
$ make testacc TESTARGS='-run=TestAccGlueCrawler_\|TestAccGlueTrigger_' PKG=glue ACCTEST_PARALLELISM=3
TF_ACC=1 go test ./internal/service/glue/... -v -count 1 -parallel 3  -run=TestAccGlueCrawler_\|TestAccGlueTrigger_ -timeout 180m
=== RUN   TestAccGlueCrawler_dynamoDBTarget
=== PAUSE TestAccGlueCrawler_dynamoDBTarget
=== RUN   TestAccGlueCrawler_DynamoDBTarget_scanAll
=== PAUSE TestAccGlueCrawler_DynamoDBTarget_scanAll
=== RUN   TestAccGlueCrawler_DynamoDBTarget_scanRate …
```
=> fix: Glue crawler retry-able error string fix

.changelog/30369.txt, internal/service/ce/cost_category.go
Fixed effective_start date being reset to the start of the current month. Effective_start date is required (see API documentation in the references). If the effective_start has not been changed by the current change, terraform passes nil which results on AWS side to use the default value (first day of current month).
Closes #29044 
[AWS API Reference](https://docs.aws.amazon.com/aws-cost-management/latest/APIReference/API_CostCategoryReference.html)
The [aws sdk](https://pkg.go.dev/github.com/aws/aws-sdk-go@v1.44.232/service/costexplorer#UpdateCostCategoryDefinitionInput) states:
> 	The Cost Category's effective start date. It can only be a billing start
date (first day of the month). If the date isn't provided, it's the first
day of the current month. Dates can't be before the previous …
=> AWS_CE_COST_CATEGORY: fix effective start being changed on update despite no current change

website/docs/r/apigatewayv2_api_mapping.html.markdown
The API Mapping Key has a link to WebSocket API mapping templates which is irrelevant to the resource `aws_apigatewayv2_api_mapping`.
The fix includes 3 links. The first for REST APIs, the second for HTTP APIs (they share the same principals with slight changes) and the third to the correct WebSocket API documenation.
https://docs.aws.amazon.com/apigateway/latest/developerguide/websocket-api-mappings.html
https://docs.aws.amazon.com/apigateway/latest/developerguide/rest-api-mappings.html
https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-mappings.html
https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-websocket-api-mapping-template-reference.html
=> docs: Fixed link to AWS doc based on API type

.github/workflows/autoremove_labels.yml, .github/workflows/changelog.yml, .github/workflows/dependencies.yml, .github/workflows/issue-comment-created.yml, .github/workflows/issues.yml, .github/workflows/maintainer-edit.yml, .github/workflows/project.yml, .github/workflows/pull_requests.yml
This PR moves our existing GitHub Actions workflows that previously used the `MAINTAINER_LIST` secret over to the new method outlined in the linked PRs.
Depends on: #30277
Depends on: #30276
- [GitHub Actions Workflow Syntax: `if`](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idif)
- [GitHub Actions: Reusing Workflows](https://docs.github.com/en/actions/using-workflows/reusing-workflows)
N/a, Actions
=> Move existing workflows over to reusable workflow

website/docs/r/iam_openid_connect_provider.html.markdown
Add value for required `thumbprint_list` argument in example
Closes #29963
https://docs.aws.amazon.com/IAM/latest/APIReference/API_CreateOpenIDConnectProvider.html
=> aws_iam_openid_connect_provider - required thumbprint_list

.changelog/30379.txt, internal/service/rds/cluster.go, internal/service/rds/cluster_test.go, internal/service/rds/instance.go, internal/service/rds/instance_test.go
Closes https://github.com/hashicorp/terraform-provider-aws/issues/30372.
Closes https://github.com/hashicorp/terraform-provider-aws/issues/30383.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/28848.
```console
% make testacc TESTARGS='-run=TestAccRDSInstance_password\|TestAccRDSInstance_basic' PKG=rds ACCTEST_PARALLELISM=3
TF_ACC=1 go test ./internal/service/rds/... -v -count 1 -parallel 3  -run=TestAccRDSInstance_password\|TestAccRDSInstance_basic -timeout 180m
=== RUN   TestAccRDSInstance_basic
=== PAUSE TestAccRDSInstance_basic
=== RUN   TestAccRDSInstance_password
=== PAUSE TestAccRDSInstance_password
=== CONT  TestAccRDSInstance_basic
=== CONT  TestAccRDSInstance_password
--- PASS: TestAccRDSInstance_basic …
```
=> r/aws_rds_cluster: Fix crash when attempting to update `master_password`

.changelog/30401.txt, internal/service/oam/link_data_source.go, internal/service/oam/link_data_source_test.go, internal/service/oam/links_data_source.go, internal/service/oam/links_data_source_test.go, internal/service/oam/service_package_gen.go, website/docs/d/oam_link.html.markdown, website/docs/d/oam_links.html.markdown
Adding 2 data sources for [aws_oam_link resource](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/oam_link):
aws_oam_link
aws_oam_links
Closes #28158
* [GetLink API Reference](https://docs.aws.amazon.com/OAM/latest/APIReference/API_GetLink.html)
* [ListLinks API Reference](https://docs.aws.amazon.com/OAM/latest/APIReference/API_ListLinks.html)
```
➜ make testacc PKG=oam TESTS=TestAccObservabilityAccessManagerLinkDataSource
TF_ACC=1 go test ./internal/service/oam/... -v -count 1 -parallel 20 -run='TestAccObservabilityAccessManagerLinkDataSource'  -timeout 180m
=== RUN   TestAccObservabilityAccessManagerLinkDataSource_basic
--- PASS: TestAccObservabilityAccessManagerLinkDataSource_basic (151.29s)
PASS
ok …
```
=> New DataSources - `aws_oam_link` and `aws_oam_links`

internal/service/waf/rate_based_rule.go, internal/service/waf/rule.go, internal/service/waf/rule_group.go, internal/service/waf/service_package_gen.go, internal/service/waf/web_acl.go, internal/service/wafregional/rate_based_rule.go, internal/service/wafregional/rule.go, internal/service/wafregional/rule_group.go, internal/service/wafregional/service_package_gen.go, internal/service/wafregional/web_acl.go, internal/service/wafv2/ip_set.go, internal/service/wafv2/regex_pattern_set.go, internal/service/wafv2/rule_group.go, internal/service/wafv2/service_package_gen.go, internal/service/wafv2/web_acl.go, internal/service/workspaces/directory.go, internal/service/workspaces/ip_group.go, internal/service/workspaces/service_package_gen.go, internal/service/workspaces/workspace.go, internal/service/xray/group.go, internal/service/xray/sampling_rule.go, internal/service/xray/service_package_gen.go
Extends the work done in Phase 2 to the remaining resources implemented using Terraform Plugin SDK v2.
```console
% make testacc TESTARGS='-run=TestAccXRayGroup_basic\|TestAccXRayGroup_tags\|TestAccXRaySamplingRule_basic\|TestAccXRaySamplingRule_tags' PKG=xray ACCTEST_PARALLELISM=3
TF_ACC=1 go test ./internal/service/xray/... -v -count 1 -parallel 3  -run=TestAccXRayGroup_basic\|TestAccXRayGroup_tags\|TestAccXRaySamplingRule_basic\|TestAccXRaySamplingRule_tags -timeout 180m
=== RUN   TestAccXRayGroup_basic
=== PAUSE TestAccXRayGroup_basic
=== RUN   TestAccXRayGroup_tags
=== PAUSE …
```
=> Tech debt: Reduce `tags` boilerplate code - Plugin Framework resources `w*` and `x*` (Phase 3c)

.changelog/30247.txt, internal/service/rds/cluster.go, internal/service/rds/cluster_instance.go, internal/service/rds/cluster_test.go, internal/service/rds/engine_version_test.go, internal/service/rds/instance.go, internal/service/rds/verify.go
This change fixes "inconsistent final plan" errors caused by deferred engine version updates (`apply_immediately = false`) in the RDS cluster, cluster instance, and instance resources. Specifically, read operations will now check the `PendingModifiedValues` for a non-nil `EngineVersion`. If present, and equal to the existing configured value, this will be stored in state to ensure a consistent final plan and avoid persistent diffs until the update takes place during the next maintenance window.
Additionally, this change improves the cluster update workflow when there are pending updates by:
- Setting the `EngineVersion` field if the configured and "actual" engine versions differ.
- This can occur when multiple applies happen prior to a maintenance window. In this situation the desired …
=> Handle pending RDS engine version updates

internal/service/timestreamwrite/database.go, internal/service/timestreamwrite/service_package_gen.go, internal/service/timestreamwrite/table.go, internal/service/transcribe/language_model.go, internal/service/transcribe/medical_vocabulary.go, internal/service/transcribe/service_package_gen.go, internal/service/transcribe/vocabulary.go, internal/service/transcribe/vocabulary_filter.go, internal/service/transfer/server.go, internal/service/transfer/service_package_gen.go, internal/service/transfer/user.go, internal/service/transfer/workflow.go, internal/tags/tags.go
Extends the work done in Phase 2 to the remaining resources implemented using Terraform Plugin Framework.
```console
% make testacc TESTARGS='-run=_basic$$\|_tags$$' PKG=timestreamwrite ACCTEST_PARALLELISM=3
TF_ACC=1 go test ./internal/service/timestreamwrite/... -v -count 1 -parallel 3  -run=_basic$\|_tags$ -timeout 180m
=== RUN   TestAccTimestreamWriteDatabase_basic
=== PAUSE TestAccTimestreamWriteDatabase_basic
=== RUN   TestAccTimestreamWriteDatabase_tags
=== PAUSE TestAccTimestreamWriteDatabase_tags
=== RUN …
```
=> Tech debt: Reduce `tags` boilerplate code - Plugin Framework resources `t*` (Phase 3c)

.ci/.golangci2.yml, internal/service/iam/user_login_profile_test.go
Replaced use of session.New by session.NewSession and removed the associated golanglint-ci exclusion.
Closes #30323
=> Use session.NewSession instead of deprecated session.New

.changelog/30425.txt, internal/service/secretsmanager/secret.go, internal/service/secretsmanager/secret_data_source.go, internal/service/secretsmanager/secret_rotation.go, internal/service/secretsmanager/secret_rotation_data_source.go, internal/service/secretsmanager/secret_rotation_test.go, website/docs/r/secretsmanager_secret_rotation.html.markdown
This adds `duration` and `schedule_expression` attributes to the `rotation_rules` block.
Closes #28016
https://docs.aws.amazon.com/secretsmanager/latest/apireference/API_RotationRulesType.html
```
make testacc TESTS=TestAccSecretsManagerSecretRotation PKG=secretsmanager ACCTEST_PARALLELISM=5                                     
TF_ACC=1 go test ./internal/service/secretsmanager/... -v -count 1 -parallel 5 -run='TestAccSecretsManagerSecretRotation'  -timeout 180m
=== RUN   TestAccSecretsManagerSecretRotationDataSource_basic
=== PAUSE TestAccSecretsManagerSecretRotationDataSource_basic
=== RUN   TestAccSecretsManagerSecretRotation_basic
=== PAUSE TestAccSecretsManagerSecretRotation_basic
=== RUN …
```
=> add new attributes to secrets manager rotation rules

website/docs/r/transcribe_vocabulary_filter.html.markdown
Fix typo `vocabulary_file_uri` -> `vocabulary_filter_file_uri`
Closes #30019
https://docs.aws.amazon.com/transcribe/latest/APIReference/API_CreateVocabularyFilter.html
=> aws_transcribe_vocabulary_filter - typo

internal/service/backup/framework.go, internal/service/backup/plan.go, internal/service/backup/report_plan.go, internal/service/backup/service_package_gen.go, internal/service/backup/vault.go, internal/service/batch/compute_environment.go, internal/service/batch/job_definition.go, internal/service/batch/job_queue.go, internal/service/batch/scheduling_policy.go, internal/service/batch/service_package_gen.go
```console
% make testacc TESTARGS='-run=_basic$$\|_tags$$' PKG=b... ACCTEST_PARALLELISM=2 …
```
=> Tech debt: Reduce `tags` boilerplate code - Plugin SDK resources `b*` (Phase 3c)

internal/flex/framework.go, internal/framework/flex/flex.go, internal/service/cognitoidp/managed_user_pool_client.go, internal/service/cognitoidp/managed_user_pool_client_test.go, internal/service/cognitoidp/user_pool_client.go, internal/service/cognitoidp/user_pool_client_test.go
After the migration of the `aws_cognito_user_pool_client` resource from `terraform-plugin-sdk/v2` to `terraform-plugin-framework`, resources configured with an empty set (e.g. `logout_urls = []`) would return the error
> ... produced an unexpected new value: .logout_urls: was cty.SetValEmpty(cty.String), but now null.
The similar resource `aws_cognito_managed_user_pool_client` also had the same errors.
Closes #30268
```
$ make testacc PKG=cognitoidp TESTS='TestAccCognitoIDPUserPoolClient_|TestAccCognitoIDPManagedUserPoolClient_'
--- PASS: TestAccCognitoIDPUserPoolClient_Disappears_userPool (35.58s)
--- PASS: TestAccCognitoIDPUserPoolClient_disappears (38.87s)
--- PASS: TestAccCognitoIDPUserPoolClient_allFields (41.49s)
--- PASS: TestAccCognitoIDPUserPoolClient_nulls (59.65s)
--- PASS: …
```
=> Fixes "inconsistent result" errors with empty `Set` values

.changelog/35969.txt, internal/service/vpclattice/service_network.go, internal/service/vpclattice/service_network_test.go, internal/service/vpclattice/service_package_gen.go, website/docs/r/vpclattice_service_network.html.markdown
Closes #30409
```
$ make testacc TESTS=TestAccVPCLatticeServiceNetwork_ PKG=vpclattice
TF_ACC=1 go test ./internal/service/vpclattice/... -v -count 1 -parallel 20 -run='TestAccVPCLatticeServiceNetwork_'  -timeout 180m
=== RUN   TestAccVPCLatticeServiceNetwork_basic
=== PAUSE TestAccVPCLatticeServiceNetwork_basic
=== RUN   TestAccVPCLatticeServiceNetwork_disappears
=== PAUSE TestAccVPCLatticeServiceNetwork_disappears
=== RUN   TestAccVPCLatticeServiceNetwork_full
=== PAUSE TestAccVPCLatticeServiceNetwork_full
=== RUN   TestAccVPCLatticeServiceNetwork_tags
=== PAUSE TestAccVPCLatticeServiceNetwork_tags
=== CONT  TestAccVPCLatticeServiceNetwork_basic
=== CONT  TestAccVPCLatticeServiceNetwork_full
=== CONT …
```
=> Add VPCLatticeServiceNetwork resource

.github/workflows/changelog.yml, .github/workflows/changelog_misspell.yml
The new community checks require secrets access so any action triggered by `pull_request` will fail when done from a fork. Separate this check out so the community_check action does not run unecessarily.
=> Seperate changelog misspell action

internal/service/oam/link.go, internal/service/oam/service_package_gen.go, internal/service/oam/sink.go, internal/service/opensearch/domain.go, internal/service/opensearch/service_package_gen.go, internal/service/opsworks/custom_layer.go, internal/service/opsworks/ecs_cluster_layer.go, internal/service/opsworks/ganglia_layer.go, internal/service/opsworks/haproxy_layer.go, internal/service/opsworks/java_app_layer.go, internal/service/opsworks/layers.go, internal/service/opsworks/memcached_layer.go, internal/service/opsworks/mysql_layer.go, internal/service/opsworks/nodejs_app_layer.go, internal/service/opsworks/php_app_layer.go, internal/service/opsworks/rails_app_layer.go, internal/service/opsworks/service_package_gen.go, internal/service/opsworks/stack.go, internal/service/opsworks/stack_test.go, internal/service/opsworks/static_web_layer.go, internal/service/organizations/account.go, internal/service/organizations/organizational_unit.go, internal/service/organizations/policy.go, internal/service/organizations/service_package_gen.go
=> Tech debt: Reduce `tags` boilerplate code - Plugin SDK resources `o*` (Phase 3c)

.changelog/30398.txt, internal/service/emrserverless/application.go, internal/service/emrserverless/application_test.go, internal/service/imagebuilder/container_recipe.go, internal/service/imagebuilder/container_recipe_test.go, website/docs/r/emrserverless_application.markdown, website/docs/r/imagebuilder_container_recipe.html.markdown
Adds the ability to define a custom image for an EMR Serverless application. Also added `platform_override` option support for AWS ImageBuilder.
When I tried to use a public ecr image (for example `public.ecr.aws/emr-serverless/hive/emr-6.9.0`) for the imageUri option, I received a 500 error (also occurred when using the aws-cli as well). To get around this, I had to build a custom image off that base and put it in a temporary ECR repo. Unfortunately, this make the new acceptance test a lot more complicated and long running.
Also, sorry if my Go isn't particularly idiomatic - I'm a relative newbie with it! Happy to take on any feedback :).
Closes #24711
Closes #30230
```
make testacc TESTS=TestAccEMRServerlessApplication_basic PKG=emrserverless …
```
=> Emrserverless add image configuration

internal/service/neptune/cluster.go, internal/service/neptune/cluster_endpoint.go, internal/service/neptune/cluster_instance.go, internal/service/neptune/cluster_parameter_group.go, internal/service/neptune/event_subscription.go, internal/service/neptune/parameter_group.go, internal/service/neptune/service_package_gen.go, internal/service/neptune/subnet_group.go, internal/service/networkfirewall/firewall.go, internal/service/networkfirewall/firewall_policy.go, internal/service/networkfirewall/rule_group.go, internal/service/networkfirewall/service_package_gen.go, internal/service/networkmanager/connect_attachment.go, internal/service/networkmanager/connect_peer.go, internal/service/networkmanager/connection.go, internal/service/networkmanager/core_network.go, internal/service/networkmanager/device.go, internal/service/networkmanager/global_network.go, internal/service/networkmanager/link.go, internal/service/networkmanager/service_package_gen.go, internal/service/networkmanager/site.go, internal/service/networkmanager/site_to_site_vpn_attachment.go, internal/service/networkmanager/transit_gateway_peering.go, internal/service/networkmanager/transit_gateway_route_table_attachment.go, internal/service/networkmanager/vpc_attachment.go
=> Tech debt: Reduce `tags` boilerplate code - Plugin SDK resources `n*` (Phase 3c)

.changelog/30490.txt, internal/service/vpclattice/service_data_source.go, internal/service/vpclattice/service_data_source_test.go, internal/service/vpclattice/service_package_gen.go, website/docs/d/vpclattice_service.html.markdown
Relates #30380
```
$ make testacc TESTS=TestAccVPCLatticeServiceDataSource_ PKG=vpclattice
TF_ACC=1 go test ./internal/service/vpclattice/... -v -count 1 -parallel 20 -run='TestAccVPCLatticeServiceDataSource_'  -timeout 180m
=== RUN   TestAccVPCLatticeServiceDataSource_basic
=== PAUSE TestAccVPCLatticeServiceDataSource_basic
=== CONT  TestAccVPCLatticeServiceDataSource_basic
--- PASS: TestAccVPCLatticeServiceDataSource_basic (18.00s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/vpclattice	18.085s
```
=> Add VPCLattice Service data source

internal/service/macie2/classification_job.go, internal/service/macie2/custom_data_identifier.go, internal/service/macie2/findings_filter.go, internal/service/macie2/member.go, internal/service/macie2/service_package_gen.go, internal/service/mediaconvert/queue.go, internal/service/mediaconvert/service_package_gen.go, internal/service/medialive/channel.go, internal/service/medialive/input.go, internal/service/medialive/input_security_group.go, internal/service/medialive/multiplex.go, internal/service/medialive/service_package_gen.go, internal/service/mediapackage/channel.go, internal/service/mediapackage/service_package_gen.go, internal/service/mediastore/container.go, internal/service/mediastore/service_package_gen.go, internal/service/memorydb/acl.go, internal/service/memorydb/cluster.go, internal/service/memorydb/parameter_group.go, internal/service/memorydb/service_package_gen.go, internal/service/memorydb/snapshot.go, internal/service/memorydb/subnet_group.go, internal/service/memorydb/user.go, internal/service/mq/broker.go, internal/service/mq/configuration.go, internal/service/mq/service_package_gen.go, internal/service/mwaa/environment.go, internal/service/mwaa/service_package_gen.go
=> Tech debt: Reduce `tags` boilerplate code - Plugin SDK resources `m*` (Phase 3c)

internal/service/cognitoidp/managed_user_pool_client.go, internal/service/cognitoidp/managed_user_pool_client_test.go, internal/service/cognitoidp/user_pool_client.go, internal/service/cognitoidp/user_pool_client_test.go, website/docs/r/cognito_managed_user_pool_client.html.markdown, website/docs/r/cognito_user_pool_client.html.markdown
Updates `aws_cognito_user_pool_client` and `aws_cognito_managed_user_pool_client` validation for `access_token_validity`, `id_token_validity`, and `refresh_token_validity` to account for units set in `token_validity_units`.
```
$ make testacc PKG=cognitoidp TESTS='TestAccCognitoIDPUserPoolClient_|TestAccCognitoIDPManagedUserPoolClient_'
--- PASS: TestAccCognitoIDPManagedUserPoolClient_accessTokenValidity_error (3.92s)
--- PASS: TestAccCognitoIDPManagedUserPoolClient_refreshTokenValidity_error (6.62s)
--- PASS: TestAccCognitoIDPManagedUserPoolClient_idTokenValidity_error (7.79s)
--- PASS: TestAccCognitoIDPManagedUserPoolClient_basic (1529.58s)
--- PASS: TestAccCognitoIDPManagedUserPoolClient_tokenValidityUnitsWTokenValidity (1628.51s)
--- PASS: …
```
=> Improves validation for `aws_cognito_user_pool_client` and `aws_cognito_managed_user_pool_client`

internal/service/lambda/function.go, internal/service/lambda/service_package_gen.go, internal/service/licensemanager/license_configuration.go, internal/service/licensemanager/service_package_gen.go, internal/service/lightsail/bucket.go, internal/service/lightsail/certificate.go, internal/service/lightsail/container_service.go, internal/service/lightsail/database.go, internal/service/lightsail/disk.go, internal/service/lightsail/distribution.go, internal/service/lightsail/instance.go, internal/service/lightsail/lb.go, internal/service/lightsail/service_package_gen.go, internal/service/location/geofence_collection.go, internal/service/location/map.go, internal/service/location/place_index.go, internal/service/location/route_calculator.go, internal/service/location/service_package_gen.go, internal/service/location/tracker.go
=> Tech debt: Reduce `tags` boilerplate code - Plugin SDK resources `l*` (Phase 3c)

internal/service/globalaccelerator/sweep.go, internal/service/vpclattice/service.go, internal/service/vpclattice/service_network.go, internal/service/vpclattice/sweep.go, internal/sweep/sweep_test.go
Adds test sweepers for Global Accelerator custom routing and VPC Lattice.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/28922.
Relates https://github.com/hashicorp/terraform-provider-aws/issues/30380.
```console
% make sweep SWEEPARGS=-sweep-run=aws_globalaccelerator_custom_routing_accelerator
go test ./internal/sweep -v -tags=sweep -sweep=us-west-2,us-east-1,us-east-2 -sweep-run=aws_globalaccelerator_custom_routing_accelerator -timeout 60m
2023/04/06 12:28:39 [DEBUG] Running Sweepers for region (us-west-2):
2023/04/06 12:28:39 [DEBUG] Running Sweeper (aws_globalaccelerator_custom_routing_endpoint_group) in region (us-west-2)
2023/04/06 12:28:40 [DEBUG] Completed Sweeper …
```
=> Sweepers: Add Custom Routing Accelerator and VPC Lattice sweepers

.changelog/30515.txt, internal/service/ec2/sweep.go, internal/service/ec2/vpc_default_route_table.go, internal/service/ec2/vpc_route_table.go, internal/service/ec2/vpc_route_table_data_source.go
When an [association is made](https://docs.aws.amazon.com/vpc-lattice/latest/ug/service-network-associations.html#service-network-vpc-associations) between a VPC Lattice service network and a VPC,
additional IPv4 and IPv6 destinations are added to that VPC's route tables:
```console
% aws ec2 describe-route-tables --route-table-ids rtb-b2012dc9
{
"RouteTables": [
{
"Associations": [
{
"Main": true,
"RouteTableAssociationId": "rtbassoc-6d565b10",
"RouteTableId": "rtb-b2012dc9",
"AssociationState": {
"State": "associated"
}
}
],
"PropagatingVgws": [],
"RouteTableId": "rtb-b2012dc9",
"Routes": [
{
"DestinationCidrBlock": "172.31.0.0/16",
"GatewayId": "local",
"Origin": "CreateRouteTable",
"State": "active"
},
{
"DestinationCidrBlock": "0.0.0.0/0",
"GatewayId": "igw-6aae1a13",
"Origin": …
```
=> VPC: Ignore route table routes managed by VPC Lattice

.changelog/30522.txt, internal/service/servicecatalog/provisioned_product_test.go, internal/service/servicecatalog/wait.go, website/docs/r/servicecatalog_provisioned_product.html.markdown
Closes #26237
Closes #24574
Relates #24758
Relates #24804
Relates #25130
```
% make t T=TestAccServiceCatalogProvisionedProduct_ K=servicecatalog P=3
TF_ACC=1 go test ./internal/service/servicecatalog/... -v -count 1 -parallel 3 -run='TestAccServiceCatalogProvisionedProduct_'  -timeout 180m
=== RUN   TestAccServiceCatalogProvisionedProduct_basic
=== PAUSE TestAccServiceCatalogProvisionedProduct_basic
=== RUN   TestAccServiceCatalogProvisionedProduct_update
=== PAUSE TestAccServiceCatalogProvisionedProduct_update
=== RUN   TestAccServiceCatalogProvisionedProduct_computedOutputs
=== PAUSE TestAccServiceCatalogProvisionedProduct_computedOutputs
=== RUN   TestAccServiceCatalogProvisionedProduct_disappears
=== PAUSE …
```
=> servicecat/prov_product: Allow for TAINTED

internal/service/kafka/cluster.go, internal/service/kafka/serverless_cluster.go, internal/service/kafka/service_package_gen.go, internal/service/kendra/data_source.go, internal/service/kendra/faq.go, internal/service/kendra/index.go, internal/service/kendra/query_suggestions_block_list.go, internal/service/kendra/service_package_gen.go, internal/service/kendra/thesaurus.go, internal/service/keyspaces/keyspace.go, internal/service/keyspaces/service_package_gen.go, internal/service/keyspaces/table.go, internal/service/kinesis/service_package_gen.go, internal/service/kinesis/stream.go, internal/service/kinesisanalytics/application.go, internal/service/kinesisanalytics/service_package_gen.go, internal/service/kinesisanalyticsv2/application.go, internal/service/kinesisanalyticsv2/service_package_gen.go, internal/service/kinesisvideo/service_package_gen.go, internal/service/kinesisvideo/stream.go
=> Tech debt: Reduce `tags` boilerplate code - Plugin SDK resources `k*` (Phase 3c)

internal/service/imagebuilder/component.go, internal/service/imagebuilder/container_recipe.go, internal/service/imagebuilder/distribution_configuration.go, internal/service/imagebuilder/image.go, internal/service/imagebuilder/image_pipeline.go, internal/service/imagebuilder/image_recipe.go, internal/service/imagebuilder/infrastructure_configuration.go, internal/service/imagebuilder/service_package_gen.go, internal/service/iot/provisioning_template.go, internal/service/iot/service_package_gen.go, internal/service/iot/thing_group.go, internal/service/iot/thing_type.go, internal/service/iot/topic_rule.go, internal/service/ivs/channel.go, internal/service/ivs/playback_key_pair.go, internal/service/ivs/recording_configuration.go, internal/service/ivs/service_package_gen.go, internal/service/ivschat/logging_configuration.go, internal/service/ivschat/room.go, internal/service/ivschat/service_package_gen.go
=> Tech debt: Reduce `tags` boilerplate code - Plugin SDK resources `i*` (Phase 3c)

.changelog/30535.txt, internal/service/kafka/serverless_cluster.go, internal/service/kafka/serverless_cluster_test.go
Changes `aws_msk_serverless_cluster.vpc_config.security_group_ids` to _Computed_.
Closes https://github.com/hashicorp/terraform-provider-aws/issues/30532.
```console
% make testacc TESTARGS='-run=TestAccKafkaServerlessCluster_' PKG=kafka ACCTEST_PARALLELISM=2
TF_ACC=1 go test ./internal/service/kafka/... -v -count 1 -parallel 2  -run=TestAccKafkaServerlessCluster_ -timeout 180m
=== RUN   TestAccKafkaServerlessCluster_basic
=== PAUSE TestAccKafkaServerlessCluster_basic
=== RUN   TestAccKafkaServerlessCluster_disappears
=== PAUSE TestAccKafkaServerlessCluster_disappears
=== RUN   TestAccKafkaServerlessCluster_tags
=== PAUSE TestAccKafkaServerlessCluster_tags
=== RUN   TestAccKafkaServerlessCluster_securityGroup
=== PAUSE …
```
=> r/aws_msk_serverless_cluster: `vpc_config.security_group_ids` is Computed

.changelog/30537.txt, internal/service/batch/compute_environment.go
Ibid.
Closes #30378.
```console
% make testacc TESTARGS='-run=TestAccBatchComputeEnvironment_basic\|TestAccBatchComputeEnvironment_launchTemplate' PKG=batch ACCTEST_PARALLELISM=2
TF_ACC=1 go test ./internal/service/batch/... -v -count 1 -parallel 2  -run=TestAccBatchComputeEnvironment_basic\|TestAccBatchComputeEnvironment_launchTemplate -timeout 180m
=== RUN   TestAccBatchComputeEnvironment_basic
=== PAUSE TestAccBatchComputeEnvironment_basic
=== RUN   TestAccBatchComputeEnvironment_launchTemplate
=== PAUSE TestAccBatchComputeEnvironment_launchTemplate
=== CONT  TestAccBatchComputeEnvironment_basic
=== CONT  TestAccBatchComputeEnvironment_launchTemplate
--- PASS: TestAccBatchComputeEnvironment_launchTemplate (37.71s)
--- PASS: …
```
=> r/aws_batch_compute_environment: Fix crash when `compute_resources.launch_template` is empty

.changelog/30539.txt, internal/service/ec2/ec2_launch_template.go
Ibid.
Closes #29374.
Closes #24009.
Closes #27819.
```console
% make testacc TESTARGS='-run=TestAccEC2LaunchTemplate_' PKG=ec2 ACCTEST_PARALLELISM=2
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 2  -run=TestAccEC2LaunchTemplate_ -timeout 180m
=== RUN   TestAccEC2LaunchTemplate_basic
=== PAUSE TestAccEC2LaunchTemplate_basic
=== RUN   TestAccEC2LaunchTemplate_Name_generated
=== PAUSE TestAccEC2LaunchTemplate_Name_generated
=== RUN   TestAccEC2LaunchTemplate_Name_prefix
=== PAUSE TestAccEC2LaunchTemplate_Name_prefix
=== RUN   TestAccEC2LaunchTemplate_disappears
=== PAUSE TestAccEC2LaunchTemplate_disappears
=== RUN   TestAccEC2LaunchTemplate_BlockDeviceMappings_ebs
=== PAUSE …
```
=> r/aws_launch_template: Fix crash when `instance_market_options.spot_options` is empty

.changelog/30498.txt, internal/service/dms/certificate_data_source.go, internal/service/dms/certificate_data_source_test.go, internal/service/dms/service_package_gen.go, website/docs/d/dms_certificate.html.markdown
This PR adds certificate_data_source to the dms resource.
Relates #12713
```
> make testacc TESTARGS='-run=TestAccDMSCertificateDataSource_basic' PKG=dms
TF_ACC=1 go test ./internal/service/dms/... -v -count 1 -parallel 20  -run=TestAccDMSCertificateDataSource_basic -timeout 180m
=== RUN   TestAccDMSCertificateDataSource_basic
=== PAUSE TestAccDMSCertificateDataSource_basic
=== CONT  TestAccDMSCertificateDataSource_basic
--- PASS: TestAccDMSCertificateDataSource_basic (11.85s)
PASS
...
```
=> Adding certificate_data_source to dms

internal/service/firehose/delivery_stream.go, internal/service/firehose/delivery_stream_test.go, internal/service/firehose/service_package_gen.go, internal/service/fis/experiment_template.go, internal/service/fis/service_package_gen.go, internal/service/fms/policy.go, internal/service/fms/service_package_gen.go, internal/service/fsx/backup.go, internal/service/fsx/data_repository_association.go, internal/service/fsx/data_repository_association_test.go, internal/service/fsx/file_cache.go, internal/service/fsx/file_cache_test.go, internal/service/fsx/lustre_file_system.go, internal/service/fsx/ontap_file_system.go, internal/service/fsx/ontap_storage_virtual_machine.go, internal/service/fsx/ontap_storage_virtual_machine_migrate.go, internal/service/fsx/ontap_volume.go, internal/service/fsx/openzfs_file_system.go, internal/service/fsx/openzfs_snapshot.go, internal/service/fsx/openzfs_volume.go, internal/service/fsx/service_package_gen.go, internal/service/fsx/windows_file_system.go
=> Tech debt: Reduce `tags` boilerplate code - Plugin SDK resources `f*` (Phase 3c)

.changelog/30411.txt, internal/service/vpclattice/service_network_vpc_association.go, internal/service/vpclattice/service_network_vpc_association_test.go, internal/service/vpclattice/service_package_gen.go, website/docs/r/vpclattice_service_network_vpc_association.html.markdown
This pull request will cater for a new resource in the VPC Lattice family - ServiceNetwork - VPC Association. For more information kindly refer to this page for details - https://docs.aws.amazon.com/vpc-lattice/latest/ug/service-network-associations.html
Closes #30411 
The API Reference can be found here - https://docs.aws.amazon.com/vpc-lattice/latest/APIReference/API_CreateServiceNetworkVpcAssociation.html
```
:~/terraform-provider-aws (f-aws_vpclattice_service_network_vpc_association) $ make testacc PKG=vpclattice TESTS=TestAccVPCLatticeServiceNetworkVPCAssociation_
TF_ACC=1 go test ./internal/service/vpclattice/... -v -count 1 -parallel 20 -run='TestAccVPCLatticeServiceNetworkVPCAssociation_'  -timeout 180m
=== RUN …
```
=> new service aws_vpclattice_service_network_vpc_association

.changelog/30487.txt, internal/service/quicksight/exports_test.go, internal/service/quicksight/ingestion.go, internal/service/quicksight/ingestion_test.go, internal/service/quicksight/service_package_gen.go, website/docs/r/quicksight_ingestion.html.markdown
This resource will allow practitioners to create QuickSight Ingestions via Terraform.
Closes #11833
- https://docs.aws.amazon.com/quicksight/latest/APIReference/API_CreateIngestion.html
- https://docs.aws.amazon.com/quicksight/latest/APIReference/API_DescribeIngestion.html
- https://docs.aws.amazon.com/quicksight/latest/APIReference/API_CancelIngestion.html
```
$ make testacc PKG=quicksight TESTS=TestAccQuickSightIngestion_
TF_ACC=1 go test ./internal/service/quicksight/... -v -count 1 -parallel 20 -run='TestAccQuickSightIngestion_'  -timeout 180m
=== RUN   TestAccQuickSightIngestion_basic
=== PAUSE TestAccQuickSightIngestion_basic
=== RUN   TestAccQuickSightIngestion_disappears_dataSet
=== PAUSE …
```
=> New Resource: `aws_quicksight_ingestion`

.changelog/30552.txt, internal/service/ec2/vpnclient_route.go, internal/service/ec2/wait.go, website/docs/r/ec2_client_vpn_route.html.markdown
When creating the resource aws_ec2_client_vpn_route, AWS takes between 2 and 3 minutes to create and activate the route, That means the default setting of 1 minute, is not enough, and would most likely fail to either create OR delete.
I propose to raise the default timeout to 4 minutes, which is a lot of time, sure, but  for https://github.com/hashicorp/terraform-provider-aws/blob/main/internal/service/eks/node_group.go#L38 Node_group timeout is an hour, but node groups are usually active within the first 15 minutes, so I took some headroom as well..
This, _to the best of my knowledge is not an open issue_, but rather something I encountered while creating a resource of 
`aws_ec2_client_vpn_route`.
Closes: #23787.
=> Update default timeout for aws_ec2_client_vpn_route

.changelog/30546.txt, internal/service/ec2/vpc_nat_gateway.go, internal/service/ec2/vpc_nat_gateway_data_source.go, internal/service/ec2/vpc_nat_gateway_data_source_test.go, internal/service/ec2/vpc_nat_gateway_test.go, website/docs/d/nat_gateway.html.markdown, website/docs/r/nat_gateway.html.markdown
Adds the `association_id` attribute to the `aws_nat_gateway` resource and data source.
The `association_id` (and other attributes, such as `allocation_id`) are now chosen based on whether a given IP address is designated as the primary IP address of the NAT Gateway.
A subsequent PR will add secondary associations as an independent resource.
Relates https://github.com/hashicorp/terraform-provider-aws/issues/29471
```
$ make testacc TESTS=TestAccVPCNATGateway_ PKG=ec2
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 20 -run='TestAccVPCNATGateway_'  -timeout 180m
go: downloading github.com/aws/aws-sdk-go-v2/service/healthlake v1.15.7
=== RUN   TestAccVPCNATGateway_basic
=== PAUSE TestAccVPCNATGateway_basic
=== RUN …
```
=> aws_nat_gateway: add association_id attribute to resource and data source

website/docs/r/lb.html.markdown
Fix document
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lb#enable_xff_client_port
> enable_xff_client_port
> Defaults to `true`.
Default value is `false`.
https://github.com/hashicorp/terraform-provider-aws/blob/c6e74f3cf503b124a115c90bfb44ef7e50679531/internal/service/elbv2/load_balancer.go#L156-L161
```
...
```
=> fix: enable_xff_client_port default is false

internal/service/kms/external_key.go, internal/service/kms/key.go, internal/service/kms/replica_external_key.go, internal/service/kms/replica_key.go, internal/service/kms/service_package_gen.go, internal/service/kms/wait.go
=> Tech debt: Reduce `tags` boilerplate code - Plugin SDK resources `kms` (Phase 3c)

internal/service/s3/bucket_acl_test.go, internal/service/s3/bucket_data_source_test.go, internal/service/s3/bucket_inventory_test.go, internal/service/s3/bucket_lifecycle_configuration_test.go, internal/service/s3/bucket_logging_test.go, internal/service/s3/bucket_metric_test.go, internal/service/s3/bucket_notification_test.go, internal/service/s3/bucket_policy_test.go, internal/service/s3/bucket_replication_configuration_test.go, internal/service/s3/bucket_test.go, internal/service/s3/bucket_versioning_test.go, internal/service/s3/bucket_website_configuration_test.go
Updates the S3 acceptance test suite to use configurations compatible with the recent changes to S3 default security settings.
Relates #28353 
- https://aws.amazon.com/about-aws/whats-new/2022/12/amazon-s3-automatically-enable-block-public-access-disable-access-control-lists-buckets-april-2023/
```console
$ make testacc PKG=s3 TESTS=TestAccS3Bucket_
TF_ACC=1 go test ./internal/service/s3/... -v -count 1 -parallel 20 -run='TestAccS3Bucket_'  -timeout 180m
--- PASS: TestAccS3Bucket_Manage_lifecycleRuleExpirationEmptyBlock (30.53s)
=== CONT  TestAccS3Bucket_Tags_withNoSystemTags
--- PASS: TestAccS3Bucket_Manage_lifecycleRuleAbortIncompleteMultipartUploadDaysNoExpiration (32.14s)
=== CONT  TestAccS3Bucket_Replication_twoDestination …
```
=> [TechDebt]: S3 acceptance test default security settings refactor

internal/service/route53domains/registered_domain.go, internal/service/route53domains/service_package_gen.go
=> Tech debt: Reduce `tags` boilerplate code - Plugin SDK resources `route53domains` (Phase 3c)

internal/service/s3/bucket_replication_configuration_test.go
Addresses a `CheckDestroy` panic by adding a check destroy function for use with single provider configurations such as the "same region" test.
Closes #30593 
```console
$ make testacc PKG=s3 TESTS=TestAccS3BucketReplicationConfiguration_schemaV2SameRegion
TF_ACC=1 go test ./internal/service/s3/... -v -count 1 -parallel 20 -run='TestAccS3BucketReplicationConfiguration_schemaV2SameRegion'  -timeout 180m
=== RUN   TestAccS3BucketReplicationConfiguration_schemaV2SameRegion
=== PAUSE TestAccS3BucketReplicationConfiguration_schemaV2SameRegion
=== CONT  TestAccS3BucketReplicationConfiguration_schemaV2SameRegion
--- PASS: TestAccS3BucketReplicationConfiguration_schemaV2SameRegion (141.49s)
PASS
ok …
```
=> r/aws_s3_bucket_replication_configuration: fix check destroy panic

internal/provider/intercept.go, internal/service/dynamodb/service_package_gen.go, internal/service/dynamodb/table.go, internal/service/dynamodb/table_replica.go
=> Tech debt: Reduce `tags` boilerplate code - Plugin SDK resources `dynamodb` (Phase 3c)

website/docs/r/ecs_service.html.markdown
As title says. This doesn't line up with the actual schema of the object: https://github.com/hashicorp/terraform-provider-aws/blob/main/internal/service/ecs/service.go#L60
=> Typo in ECS Service doc

website/docs/r/iam_role_policy_attachment.markdown
Contains changes for the issue : https://github.com/hashicorp/terraform-provider-aws/issues/29987
Closes #29987
The example usage of the Resource: aws_iam_role_policy_attachment is missing a statement block. The data block in the example usage is missing a statement block.
Added: Added statement block inside the data block for data "aws_iam_policy_document" "assume_role" section.
documentation containing issue: 
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/iam_role_policy_attachment
Linked issue: https://github.com/hashicorp/terraform-provider-aws/issues/29987
=> Documentation correction for aws_iam_role_policy_attachment-fix

.changelog/30653.txt, internal/service/quicksight/exports_test.go, internal/service/quicksight/iam_policy_assignment.go, internal/service/quicksight/iam_policy_assignment_test.go, internal/service/quicksight/service_package_gen.go, website/docs/r/quicksight_iam_policy_assignment.html.markdown
This resource will allow practitioners to manager QuickSight IAM policy assignments via Terraform.
Closes #11832 
- https://docs.aws.amazon.com/quicksight/latest/APIReference/API_CreateIAMPolicyAssignment.html
- https://docs.aws.amazon.com/quicksight/latest/APIReference/API_DescribeIAMPolicyAssignment.html
- https://docs.aws.amazon.com/quicksight/latest/APIReference/API_UpdateIAMPolicyAssignment.html
- https://docs.aws.amazon.com/quicksight/latest/APIReference/API_DeleteIAMPolicyAssignment.html
```console
$ make testacc PKG=quicksight TESTS=TestAccQuickSightIAMPolicyAssignment_
TF_ACC=1 go test ./internal/service/quicksight/... -v -count 1 -parallel 20 -run='TestAccQuickSightIAMPolicyAssignment_'  -timeout 180m
=== …
```
=> New Resource: `aws_quicksight_iam_policy_assignment`

internal/service/rds/cluster_test.go
The only engine modes now available are `serverless` and `provisioned`
Parallel query is now configured using parameter groups: https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/aurora-mysql-parallel-query.html#aurora-mysql-parallel-query-enabling
Closes #30355
```console
$ make testacc TESTARGS='-run=TestAccRDSCluster_' PKG=rds
TF_ACC=1 go test ./internal/service/rds/... -v -count 1 -parallel 20  -run=estAccRDSCluster_ -timeout 180m
cluster_test.go:1871: serverless does not support snapshot restore on an empty volume
--- SKIP: TestAccRDSCluster_SnapshotIdentifierEngineMode_serverless (0.00s)
--- PASS: TestAccRDSCluster_ManagedMasterPassword_managed (152.96s)
--- PASS: TestAccRDSCluster_basic (182.52s)
--- PASS: …
```
=> r/aws_rds_cluster: Fix RDS Cluster acceptance test

website/docs/r/launch_template.html.markdown
Removes default values that were incorrectly documented. The default value for all fields should be blank, to give the Launch Template an unspecified value.
Relates #29024
=> Remove incorrect default values from documentation

internal/service/elasticsearch/domain_data_source_test.go, internal/service/opensearch/domain_data_source_test.go, internal/service/opensearch/domain_test.go
Acceptance tests for `aws_elasticsearch_domain` and `aws_opensearch_domain` data sources are failing with
> ValidationException: Autotune is not supported in t2/t3 instance types.
```
$ make testacc PKG=elasticsearch TESTS=TestAccElasticsearchDomainDataSource_
--- PASS: TestAccElasticsearchDomainDataSource_basic (2377.19s)
--- PASS: TestAccElasticsearchDomainDataSource_advanced (3910.58s)
```
```
$ make testacc PKG=elasticsearch TESTS=TestAccOpenSearchDomainDataSource_
--- PASS: TestAccOpenSearchDomainDataSource_Data_basic (1792.44s)
--- PASS: TestAccOpenSearchDomainDataSource_Data_advanced (3037.74s)
```
=> Fixes OpenSearch and Elasticsearch acceptance tests

.changelog/30681.txt, internal/provider/fwprovider/intercept.go, internal/service/quicksight/account_subscription.go, internal/service/quicksight/data_set_data_source.go, internal/service/quicksight/exports_test.go, internal/service/quicksight/group.go, internal/service/quicksight/group_membership.go, internal/service/quicksight/iam_policy_assignment.go, internal/service/quicksight/ingestion.go, internal/service/quicksight/namespace.go, internal/service/quicksight/namespace_test.go, internal/service/quicksight/service_package_gen.go, internal/service/quicksight/user.go, website/docs/r/quicksight_namespace.html.markdown
This resource will allow practitioners to manage QuickSight namespaces via Terraform.
Closes #30654 
```console
$ make testacc PKG=quicksight TESTS=TestAccQuickSightNamespace_
TF_ACC=1 go test ./internal/service/quicksight/... -v -count 1 -parallel 20 -run='TestAccQuickSightNamespace_'  -timeout 180m
=== RUN   TestAccQuickSightNamespace_basic
=== PAUSE TestAccQuickSightNamespace_basic
=== RUN   TestAccQuickSightNamespace_disappears
=== PAUSE TestAccQuickSightNamespace_disappears
=== RUN   TestAccQuickSightNamespace_tags
=== PAUSE TestAccQuickSightNamespace_tags
=== CONT  TestAccQuickSightNamespace_basic
=== CONT  TestAccQuickSightNamespace_tags
=== CONT  TestAccQuickSightNamespace_disappears
--- PASS: …
```
=> New Resource: `aws_quicksight_namespace`

.changelog/30662.txt, internal/service/cognitoidp/managed_user_pool_client.go, internal/service/cognitoidp/managed_user_pool_client_test.go, internal/service/cognitoidp/user_pool_client.go, internal/service/cognitoidp/user_pool_client_test.go
Removing `token_validity_units` would return the error
> produced an unexpected new value: .token_validity_units: block count changed from 0 to 1.
Closes #30433
```
$ make testacc PKG=cognitoidp TESTS='TestAccCognitoIDPManagedUserPoolClient_| TestAccCognitoIDPUserPoolClient_'
--- PASS: TestAccCognitoIDPUserPoolClient_Disappears_userPool (64.36s)
--- PASS: TestAccCognitoIDPUserPoolClient_tokenValidityUnits_explicitDefaults (69.81s)
--- PASS: TestAccCognitoIDPUserPoolClient_allFields (80.40s)
--- PASS: TestAccCognitoIDPUserPoolClient_basic (84.47s)
--- PASS: TestAccCognitoIDPUserPoolClient_frameworkMigration_nulls (101.36s)
--- PASS: TestAccCognitoIDPUserPoolClient_frameworkMigration_emptySet (103.68s)
--- PASS: TestAccCognitoIDPUserPoolClient_frameworkMigration_basic (105.84s)
--- PASS: …
```
=> Allows removal of `token_validity_units` block

.changelog/30703.txt, internal/service/rds/instance.go, internal/service/rds/instance_test.go, website/docs/r/db_instance.html.markdown
Closes #24887
(Failure unrelated to these changes.)
```console
% make t T=TestAccRDSInstance_ K=rds P=10             
TF_ACC=1 go test ./internal/service/rds/... -v -count 1 -parallel 10 -run='TestAccRDSInstance_'  -timeout 180m
=== RUN   TestAccRDSInstance_basic
=== PAUSE TestAccRDSInstance_basic
=== RUN   TestAccRDSInstance_manage_password
=== PAUSE TestAccRDSInstance_manage_password
=== RUN   TestAccRDSInstance_identifierPrefix
=== PAUSE TestAccRDSInstance_identifierPrefix
=== RUN   TestAccRDSInstance_identifierGenerated
=== PAUSE TestAccRDSInstance_identifierGenerated
=== RUN   TestAccRDSInstance_disappears
=== PAUSE TestAccRDSInstance_disappears
=== RUN   TestAccRDSInstance_tags
=== PAUSE TestAccRDSInstance_tags
=== RUN …
```
=> rds/instance: Allow replicas to have versions

.changelog/30712.txt, internal/maps/maps.go, internal/maps/maps_test.go, internal/service/dynamodb/flex.go, internal/service/dynamodb/flex_test.go, internal/service/dynamodb/table_item.go, internal/service/dynamodb/table_item_test.go
When using a List (`"L"`) or Map (`"M"`) attribute in a DynamoDB Table Item, a plan was showing a diff, like the following:
```
~ resource "aws_dynamodb_table_item" "item" {
id         = "doormat-configuration|key||ssh_sign_ttl_config|"
~ item       = jsonencode(
~ {
~ value                = {
~ M = {
~ valid_after  = {
- B    = null -> null
- BOOL = null -> null
- BS   = null -> null
- L    = null -> null
- M    = null -> null
- NS   = null -> null
- NULL = null -> null
- S    = null -> null
- SS   = null -> null
}
~ valid_before = {
- B    = null -> null
- BOOL = null -> null
- BS   = null -> null
- L    = null -> null
- M    = null -> null
- NS   = null -> null
- NULL = null -> null
- S    = null -> null
- SS   = null -> null
}
}
}
}
)
}
```
The unchanged values, an `"N"` in this case, …
=> resource/aws_dynamodb_table_item: Correctly handle List and Map attribute JSON values

.changelog/30714.txt, internal/service/rds/instance.go, internal/service/rds/instance_test.go
`aws_db_instance` was panicking when `replica_mode` was updated
```
$ make testacc PKG=rds TESTS=TestAccRDSInstance_ReplicateSourceDB_replicaMode
--- PASS: TestAccRDSInstance_ReplicateSourceDB_replicaMode (2549.81s)
```
=> resource/aws_db_instance: Fixes panic when updating `replica_mode`

website/docs/r/lb.html.markdown
Adds the default value for the `internal` attribute in `aws_lb`.
Closes #0000
```
...
```
=> docs: add default for `internal` argument in lb

.changelog/30708.txt, internal/service/quicksight/data_set.go
=> Correctly persist `create_columns_operation.expression` field

.changelog/30739.txt, internal/service/directconnect/gateway.go
Removes the `name` argument plan-time validation.
The guidance in the AWS Console
is incorrect.
Closes https://github.com/hashicorp/terraform-provider-aws/issues/30732.
Relates #30375.
```console
% make testacc TESTARGS='-run=TestAccDirectConnectGateway_basic' PKG=directconnect
TF_ACC=1 go test ./internal/service/directconnect/... -v -count 1 -parallel 20  -run=TestAccDirectConnectGateway_basic -timeout 180m
=== RUN   TestAccDirectConnectGateway_basic
=== PAUSE TestAccDirectConnectGateway_basic
=== CONT  TestAccDirectConnectGateway_basic
--- PASS: TestAccDirectConnectGateway_basic (31.97s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/directconnect	42.123s
```
=> r/aws_dx_gateway: Remove `name` argument validation

website/docs/d/ecs_service.html.markdown
Updating description for `task_definition` to be more clear that it provides arn as well
Closes #30691
=> aws_ecs_cluster - task_definition

.changelog/30750.txt, internal/service/iam/role.go, internal/service/iam/role_data_source.go, website/docs/d/iam_role.html.markdown, website/docs/r/iam_role.html.markdown
This PR adds the `role_last_used` attribute to the `aws_iam_role` resource and datasource.
No issue that I could find relating to this.
https://docs.aws.amazon.com/IAM/latest/APIReference/API_RoleLastUsed.html
This one is tough to add an acceptance test for because in order to have that value populated, you would need to create a role and then use it and then wait for AWS to populate the last used information (which takes about 15-30 min from what I've seen).
I did run the test locally for both the role and datasource and got the following on create:
```
terraform state show aws_iam_role.role
resource "aws_iam_role" "role" {
arn                   = "arn:aws:iam::XXXXXXXXXXXXX:role/test6"
assume_role_policy    = jsonencode(
{
Statement = [
{
Action    = [
"sts:AssumeRole", …
```
=> Add role_last_used attribute to iam_role resource

.changelog/27640.txt, internal/service/cognitoidp/find.go, internal/service/ec2/find.go, internal/service/ec2/vpc_endpoint_service.go, internal/service/ec2/vpc_endpoint_service_allowed_principal.go, internal/service/ec2/vpc_endpoint_service_allowed_principal_test.go, internal/tfresource/not_found_error.go
Closes #27599 
This change provides a usable ID & supports the ability to apply tags to the service principal using `ec2_tags` resource type. 
```
make testacc TESTS=TestAccVPCEndpointServiceAllowedPrincipal_basic PKG=ec2
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 20 -run='TestAccVPCEndpointServiceAllowedPrincipal_basic'  -timeout 180m
=== RUN   TestAccVPCEndpointServiceAllowedPrincipal_basic
=== PAUSE TestAccVPCEndpointServiceAllowedPrincipal_basic
=== CONT  TestAccVPCEndpointServiceAllowedPrincipal_basic
--- PASS: TestAccVPCEndpointServiceAllowedPrincipal_basic (325.10s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/ec2        329.724s
...
```
=> [Enhancement]: Changed id to use the ServicePermissionID - the ID of the actual resource.

internal/service/iam/role_data_source_test.go
Fixes failing acceptance tests caused by exact string checking of JSON attributes.
```
=== NAME  TestAccIAMRoleDataSource_basic
role_data_source_test.go:19: Step 1/1 error: Check failed: 1 error occurred:
* Check 2/9 error: data.aws_iam_role.test: Attribute 'assume_role_policy' expected "{\"Statement\":[{\"Action\":\"sts:AssumeRole\",\"Effect\":\"Allow\",\"Principal\":{\"Service\":\"ec2.amazonaws.com\"},\"Sid\":\"\"}],\"Version\":\"2012-10-17\"}", got "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Sid\":\"\",\"Effect\":\"Allow\",\"Principal\":{\"Service\":\"ec2.amazonaws.com\"},\"Action\":\"sts:AssumeRole\"}]}"
--- FAIL: TestAccIAMRoleDataSource_basic (7.24s)
```
```console
$ make testacc PKG=iam TESTS=TestAccIAMRoleDataSource_ …
```
=> d/aws_iam_role: check json equivalence of trust

website/docs/r/vpclattice_service_network_vpc_association.html.markdown
Correction of 'vpc_identifier' attribute value in the 'Basic Usage' example block for aws_vpclattice_service_network_vpc_association Resource .
N/A
The value against vpc_identifier is wrongly specified as "aws_vpclattice_service.example.id" in
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/vpclattice_service_network_vpc_association "Example Usage" Resouce Block 
N/A
=> Documentation Update For Issue #30791

website/docs/r/emr_cluster.html.markdown
Update the IAM changes for AWS managed roles and policies used for EMR clusters. 
Additional info:
https://docs.aws.amazon.com/emr/latest/ManagementGuide/emr-iam-role.html
https://docs.aws.amazon.com/emr/latest/ManagementGuide/emr-iam-role-for-ec2.html
```
...
```
=> Update documentation related to IAM roles and policies used for emr_cluster resource

internal/service/dms/endpoint_data_source.go, internal/service/dms/endpoint_data_source_test.go, internal/service/dms/service_package_gen.go, website/docs/d/dms_endpoint.html.markdown
Added dms_endpoint data source to dms resource.
Relates #12713
```
> make testacc TESTARGS='-run=TestAccDMSEndpointDataSource_basic' PKG=dms
TF_ACC=1 go test ./internal/service/dms/... -v -count 1 -parallel 20  -run=TestAccDMSEndpointDataSource_basic -timeout 180m
=== RUN   TestAccDMSEndpointDataSource_basic
=== PAUSE TestAccDMSEndpointDataSource_basic
=== CONT  TestAccDMSEndpointDataSource_basic
--- PASS: TestAccDMSEndpointDataSource_basic (14.35s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/dms        17.435s
...
```
=> Adding dms_endpoint data source to dms resource.

.changelog/30821.txt, internal/service/networkfirewall/firewall_policy.go, internal/service/networkfirewall/firewall_policy_test.go, internal/service/networkfirewall/firewall_test.go, internal/service/networkfirewall/rule_group.go, internal/service/networkfirewall/rule_group_test.go
Fixes unexpected `encryption_configuration.type` updates from `Customer_KMS` to `AWS_KMS`.
Closes https://github.com/hashicorp/terraform-provider-aws/issues/30816.
```console
% make testacc TESTARGS='-run=TestAccNetworkFirewallFirewallPolicy_\|TestAccNetworkFirewallRuleGroup_' PKG=networkfirewall ACCTEST_PARALLELISM=1
TF_ACC=1 go test ./internal/service/networkfirewall/... -v -count 1 -parallel 1  -run=TestAccNetworkFirewallFirewallPolicy_\|TestAccNetworkFirewallRuleGroup_ -timeout 180m
=== RUN   TestAccNetworkFirewallFirewallPolicy_basic
=== PAUSE TestAccNetworkFirewallFirewallPolicy_basic
=== RUN   TestAccNetworkFirewallFirewallPolicy_encryptionConfiguration
=== PAUSE TestAccNetworkFirewallFirewallPolicy_encryptionConfiguration …
```
=> NetworkFirewall: Always specify current `EncryptionConfiguration` on Update

.changelog/30829.txt, internal/service/iam/policy_document_data_source.go, internal/service/iam/policy_document_data_source_test.go, website/docs/d/iam_policy_document.html.markdown
Closes #22906
```console
% make t T=TestAccIAMPolicyDocumentDataSource_ K=iam                   
TF_ACC=1 go test ./internal/service/iam/... -v -count 1 -parallel 20 -run='TestAccIAMPolicyDocumentDataSource_'  -timeout 180m
=== RUN   TestAccIAMPolicyDocumentDataSource_basic
=== PAUSE TestAccIAMPolicyDocumentDataSource_basic
=== RUN   TestAccIAMPolicyDocumentDataSource_singleConditionValue
=== PAUSE TestAccIAMPolicyDocumentDataSource_singleConditionValue
=== RUN   TestAccIAMPolicyDocumentDataSource_conditionWithBoolValue
=== PAUSE TestAccIAMPolicyDocumentDataSource_conditionWithBoolValue
=== RUN   TestAccIAMPolicyDocumentDataSource_source
=== PAUSE TestAccIAMPolicyDocumentDataSource_source
=== RUN …
```
=> iam_policy_document: Remove source_json, override_json

.changelog/30775.txt, internal/service/rds/subnet_group.go, internal/service/rds/subnet_group_test.go, website/docs/r/db_subnet_group.html.markdown
Adds `vpc_id` attribute to the `aws_db_subnet_group` resource.
N/A
The `vpc_id` is provided by the AWS SDK and already present as an attribute in the <https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/db_subnet_group#vpc_id> data source. 
```console
make testacc TESTS=TestAccRDSSubnetGroup_basic PKG=rds
TF_ACC=1 go test ./internal/service/rds/... -v -count 1 -parallel 20 -run='TestAccRDSSubnetGroup_basic'  -timeout 180m
=== RUN   TestAccRDSSubnetGroup_basic
=== PAUSE TestAccRDSSubnetGroup_basic
=== CONT  TestAccRDSSubnetGroup_basic
--- PASS: TestAccRDSSubnetGroup_basic (46.82s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/rds        48.170s
```
```console
$ terraform state …
```
=> Add vpcid  rds subnetgroup vpcid

docs/add-a-new-datasource.md, docs/add-a-new-resource.md, internal/conns/conns.go, internal/provider/fwprovider/provider.go, internal/provider/provider.go, skaff/datasource/datasource.tmpl, skaff/resource/resource.tmpl
Adds `name="<human friendly name>"` to the resource/data source self registration annotations generated by `skaff`.
Also adds an `IsDataSource` flag to the `InContext` structure than can be used for various purposes.
=> Minor `skaff` self-registration annotation updates

internal/service/dms/replication_subnet_group_data_source.go, internal/service/dms/replication_subnet_group_data_source_test.go, internal/service/dms/service_package_gen.go, website/docs/d/dms_replication_subnet_group.html.markdown
Adding replication_subnet_group datasource to dms resource
Relates #12713
```
> make testacc TESTARGS='-run=TestAccDMSReplicationSubnetGroupDataSource_basic' PKG=dms
TF_ACC=1 go test ./internal/service/dms/... -v -count 1 -parallel 20  -run=TestAccDMSReplicationSubnetGroupDataSource_basic -timeout 180m
=== RUN   TestAccDMSReplicationSubnetGroupDataSource_basic
=== PAUSE TestAccDMSReplicationSubnetGroupDataSource_basic
=== CONT  TestAccDMSReplicationSubnetGroupDataSource_basic
--- PASS: TestAccDMSReplicationSubnetGroupDataSource_basic (17.05s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/dms        23.625s
...
```
=> Add replication subnet group datasource to dms

internal/service/inspector2/delegated_admin_account_test.go
Acceptance tests for the `inspector2` services were failing instead of skipping when not called from an Organization Administrator account.
In non-Organization Administrator account
```
$ make testacc PKG=inspector2 TESTS=TestAccInspector2_serial
--- PASS: TestAccInspector2_serial/Enabler (0.59s)
--- SKIP: TestAccInspector2_serial/Enabler/accountID (0.48s)
--- SKIP: TestAccInspector2_serial/Enabler/disappears (0.06s)
--- SKIP: TestAccInspector2_serial/Enabler/basic (0.05s)
--- PASS: TestAccInspector2_serial/DelegatedAdminAccount (0.12s)
--- SKIP: TestAccInspector2_serial/DelegatedAdminAccount/basic (0.06s)
--- SKIP: TestAccInspector2_serial/DelegatedAdminAccount/disappears (0.06s)
--- PASS: TestAccInspector2_serial/MemberAssociation (0.11s)
--- SKIP: …
```
=> acctests: Fixes `PreCheck` error check for `inspector2` service

.changelog/30899.txt, internal/service/imagebuilder/image.go, internal/service/imagebuilder/image_data_source.go, internal/service/imagebuilder/image_data_source_test.go, internal/service/imagebuilder/image_test.go, website/docs/d/imagebuilder_image.html.markdown, website/docs/r/imagebuilder_image.html.markdown
This PR adds the `containers` attribute to the `output_resources` block of `aws_imagebuilder_image` resource and data-source.
Closes #30840.
https://docs.aws.amazon.com/imagebuilder/latest/APIReference/API_OutputResources.html
```
$ make testacc TESTARGS="-run=TestAccImageBuilderImage_outputResources_containers" PKG=imagebuilder
TF_ACC=1 go test ./internal/service/imagebuilder/... -v -count 1 -parallel 20  -run=TestAccImageBuilderImage_outputResources_containers -timeout 180m
=== RUN   TestAccImageBuilderImage_outputResources_containers
=== PAUSE TestAccImageBuilderImage_outputResources_containers
=== CONT  TestAccImageBuilderImage_outputResources_containers
--- PASS: TestAccImageBuilderImage_outputResources_containers (497.17s) …
```
=> rd/aws_imagebuilder_image: add `containers` attribute to the `output_resources` block

.changelog/30889.txt, internal/service/apprunner/service.go, internal/service/apprunner/service_test.go, website/docs/r/apprunner_service.html.markdown
This Pull Request includes the new CPU and Memory Configurations added by Apprunner.
Also, this is my first PR, I have read the guidelines and I hope I didn't miss anything.
Closes #30495
https://docs.aws.amazon.com/apprunner/latest/relnotes/release-2023-04-05-vcpu-memory.html
```
$  make testacc TESTS=TestAccAppRunnerService_ImageRepository_instance_Update1 PKG=apprunner
=== RUN   TestAccAppRunnerService_ImageRepository_instance_Update1
=== PAUSE TestAccAppRunnerService_ImageRepository_instance_Update1
=== CONT  TestAccAppRunnerService_ImageRepository_instance_Update1
--- PASS: TestAccAppRunnerService_ImageRepository_instance_Update1 (484.16s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/apprunner  484.348s
FAIL
```
=> ISSUE 30495 add missing memory and cpu configurations to apprunner

.changelog/30879.txt, internal/service/networkmanager/core_network.go, internal/service/networkmanager/core_network_policy_attachment.go, internal/service/networkmanager/core_network_policy_attachment_test.go
Currently the api `ExecuteCoreNetworkChangeSetWithContext` is called in a `retry` when there is an error of `Incorrect input` which stems from a network policy not being in the correct state. Instead of using a retry, this PR introduces a wait condition to ensure the policy is in the `READY_TO_EXECUTE` state before executing it. The waiter also catches errors when a `FAILED_GENERATION` state is detected.
As part of this waiter, the finder function is refactored to take in a policy version id so that we can accurately wait for the correct policy to finish. For compatibility with the other APIs, we introduce a `-1` check and default to reading the latest policy versions.
Separetely, this PR also adds a test case to check for expected errors should there be an incorrect policy. This helps to …
=> td/aws_networkmanager_core network_policy-enhancements

internal/service/apigateway/rest_api_test.go
Fixes failing acceptance test due to missing `put_rest_api_mode` in the `ImportStateVerifyIgnore` list.
```console
$ make testacc PKG=apigateway TESTS=TestAccAPIGatewayRestAPI_FailOnWarnings
TF_ACC=1 go test ./internal/service/apigateway/... -v -count 1 -parallel 20 -run='TestAccAPIGatewayRestAPI_FailOnWarnings'  -timeout 180m
=== RUN   TestAccAPIGatewayRestAPI_FailOnWarnings
=== PAUSE TestAccAPIGatewayRestAPI_FailOnWarnings
=== CONT  TestAccAPIGatewayRestAPI_FailOnWarnings
rest_api_test.go:1197: Step 3/5 error running import: ImportStateVerify attributes not equivalent. Difference is shown below. The - symbol indicates attributes missing after import.
map[string]string{
+       "put_rest_api_mode": "overwrite",
}
--- FAIL: …
```
=> r/aws_apigateway_rest_api: add put_rest_api_mode to ImportStateVerifyIgnore

.changelog/30871.txt, internal/service/quicksight/exports_test.go, internal/service/quicksight/folder_membership.go, internal/service/quicksight/folder_membership_test.go, internal/service/quicksight/service_package_gen.go, website/docs/r/quicksight_folder_membership.html.markdown
This PR will allow practitioners to manage QuickSight folder memberships via Terraform.
Closes #30851 
- https://docs.aws.amazon.com/quicksight/latest/APIReference/API_CreateFolderMembership.html
- https://docs.aws.amazon.com/quicksight/latest/APIReference/API_ListFolderMembers.html
- https://docs.aws.amazon.com/quicksight/latest/APIReference/API_DeleteFolderMembership.html
```console
$ make testacc PKG=quicksight TESTS=TestAccQuickSightFolderMembership_
TF_ACC=1 go test ./internal/service/quicksight/... -v -count 1 -parallel 20 -run='TestAccQuickSightFolderMembership_'  -timeout 180m
=== RUN   TestAccQuickSightFolderMembership_basic
=== PAUSE TestAccQuickSightFolderMembership_basic
=== RUN …
```
=> New Resource: `aws_quicksight_folder_membership`

.changelog/30875.txt, internal/service/networkmanager/core_network.go, internal/service/networkmanager/core_network_test.go, website/docs/r/networkmanager_core_network.html.markdown, website/docs/r/networkmanager_core_network_policy_attachment.html.markdown
Closes #29287
```console
% make t T=TestAccNetworkManagerCoreNetwork_ K=networkmanager 
TF_ACC=1 go test ./internal/service/networkmanager/... -v -count 1 -parallel 20 -run='TestAccNetworkManagerCoreNetwork_'  -timeout 180m
=== RUN   TestAccNetworkManagerCoreNetwork_basic
=== PAUSE TestAccNetworkManagerCoreNetwork_basic
=== RUN   TestAccNetworkManagerCoreNetwork_disappears
=== PAUSE TestAccNetworkManagerCoreNetwork_disappears
=== RUN   TestAccNetworkManagerCoreNetwork_tags
=== PAUSE TestAccNetworkManagerCoreNetwork_tags
=== RUN   TestAccNetworkManagerCoreNetwork_description
=== PAUSE TestAccNetworkManagerCoreNetwork_description
=== RUN   TestAccNetworkManagerCoreNetwork_createBasePolicyDocumentWithoutRegion
=== PAUSE …
```
=> networkmanager/core: Remove `policy_document` arg

website/docs/d/dynamodb_table_item.html.markdown
Documentation update for the attributes description "item" mentioned as "map" which has been rectified as " JSON representation of a map" and is inline with Resource block "item" attribut description. 
Closes  #30830
DataSource - https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/dynamodb_table_item
Resource :- https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/dynamodb_table_item
N/A
=> Documentation Update For Issue #30830

website/docs/r/elasticsearch_domain.html.markdown
Since the introduction of AWS OpenSearch, the service linked role that ElasticSearch/OpenSearch requires has changed.
It used to be a role named:
```AWSServiceRoleForAmazonElasticsearchService```
but is now a role named:
```AWSServiceRoleForAmazonOpenSearchService```
which is created and linked with:
```
resource "aws_iam_service_linked_role" "es" {
aws_service_name = "opensearchservice.amazonaws.com"
}
```
This role is required for both ElasticSearch and OpenSearch.
This PR updates the documentation to this effect.
=> aws_elasticsearch_domain - update service linked role documentation

.changelog/30788.txt, internal/service/quicksight/exports_test.go, internal/service/quicksight/refresh_schedule.go, internal/service/quicksight/refresh_schedule_test.go, internal/service/quicksight/service_package_gen.go, website/docs/r/quicksight_refresh_schedule.html.markdown
This PR adds a new `aws_quicksight_refresh_schedule` resource, allowing practitioners to manage scheduled refreshes of Quicksight data sets via Terraform.
Closes #30788
Relates To #10990 & #30744
* https://docs.aws.amazon.com/quicksight/latest/APIReference/API_CreateRefreshSchedule.html
* https://docs.aws.amazon.com/quicksight/latest/APIReference/API_DeleteRefreshSchedule.html
* https://docs.aws.amazon.com/quicksight/latest/APIReference/API_DescribeRefreshSchedule.html
* https://docs.aws.amazon.com/quicksight/latest/APIReference/API_ListRefreshSchedules.html
* https://docs.aws.amazon.com/quicksight/latest/APIReference/API_UpdateRefreshSchedule.html
```
make testacc PKG=quicksight TESTS=TestAccQuickSightRefreshSchedule_
TF_ACC=1 go …
```
=> New Resource: `aws_quicksight_refresh_schedule`

.changelog/30762.txt, website/docs/r/dms_s3_endpoint.html.markdown
Update the allowed values for `canned_acl_for_objects` in `aws_dms_s3_endpoint` resource documentation.
Closes #30741
=> Update values for canned_acl_for_objects in aws_dms_s3_endpoint resource

.changelog/30842.txt, internal/service/autoscaling/group.go, internal/service/autoscaling/group_test.go, website/docs/r/autoscaling_group.html.markdown
Removes the deprecated `tags` attribute from the `aws_autoscaling_group` resource. Documentation and acceptance test updates are also included.
Closes #7655
Closes #22905
```console
$ make testacc PKG=autoscaling TESTS=TestAccAutoScalingGroup_
TF_ACC=1 go test ./internal/service/autoscaling/... -v -count 1 -parallel 20 -run='TestAccAutoScalingGroup_'  -timeout 180m
--- PASS: TestAccAutoScalingGroup_MixedInstancesPolicyLaunchTemplateOverride_instanceRequirements_spotMaxPricePercentageOverLowestPrice (68.41s)
=== CONT  TestAccAutoScalingGroup_MixedInstancesPolicy_capacityRebalance
--- PASS: TestAccAutoScalingGroup_basic (68.74s)
=== CONT  TestAccAutoScalingGroup_mixedInstancesPolicy
--- PASS: …
```
=> `r/aws_autoscaling_group`: Remove deprecated `tags` attribute

internal/framework/base.go, internal/provider/fwprovider/intercept.go, internal/provider/intercept.go, internal/provider/tags_interceptor.go, internal/service/ec2/vpc_security_group_ingress_rule_test.go, internal/tags/key_value_tags.go
- Allow duplicate `tags` on framework resources
- properly sets `ignore_config` on SDK and Framework resources
Relates #29747
Relates #19583
Relates #19204
Relates #18311
```console
$ make testacc TESTARGS='-run=TestAccVPC_ -short' PKG=vpc
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 20  -run=TestAccVPC_ -short -timeout 180m
vpc_test.go:942: skipping long-running test in short mode
vpc_test.go:969: skipping long-running test in short mode
vpc_test.go:997: skipping long-running test in short mode
--- SKIP: TestAccVPC_IPAMIPv6 (0.00s)
=== NAME  TestAccVPC_assignGeneratedIPv6CIDRBlockWithNetworkBorderGroup …
```
=> tags: duplicate and computed tags on framework

.changelog/30994.txt, internal/service/ec2/vpc_endpoint_route_table_association.go
This fixes read after newly created **vpc_endpoint_route_table_association** that can fail because of AWS API eventual consistency https://docs.aws.amazon.com/AWSEC2/latest/APIReference/query-api-troubleshooting.html
Fixes #30993
=> Fix inconsistent read after create for vpc_endpoint_route_table_association

.changelog/30974.txt, internal/service/ec2/find.go, internal/service/ec2/vpc_endpoint_service_allowed_principal_test.go, internal/service/ec2/vpc_endpoint_service_data_source_test.go, internal/service/ec2/vpc_endpoint_service_test.go, internal/service/ec2/vpc_endpoint_test.go
A change was made to `vpc_endpoint_service_allowed` #27640 which introduced `tfresource.AssertSingleResult` however the results returned from the call to `FindVPCEndpointServicePermissions` didn't filter the result & anything above 1 allowed principal resulted in an error. I've also added an additional test which adds two service principals to be allowed access to the endpoint.
Closes #30873.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/27640.
```
$ make testacc TESTS=TestAccVPCEndpointServiceAllowedPrincipal_multiple PKG=ec2
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 20 -run='TestAccVPCEndpointServiceAllowedPrincipal_multiple'  -timeout 180m
=== RUN …
```
=> Fix: Principal allowed returned multiple when expecting one

.changelog/30914.txt, internal/service/ds/find.go
Change this method to page results like the others, it's possible the API returns a non-null `NextToken` while the `SharedDirectories` array is empty. Paging is consistent with the AWS CLI and allows us to find the required shared directory.
Not paging means for directories with large numbers of shares the provider believes the resource has been deleted outside of terraform and attempts to recreate the resources, which fails.
=> Bug: Missing shared directory resources on read

.changelog/31047.txt, internal/service/rds/consts.go, internal/service/rds/instance.go, internal/service/rds/wait.go
New `delete-precheck` status for RDS Custom.
```
module.vpc.aws_route_table_association.private["private/us-west-2a"]: Destroying... [id=rtbassoc-0656aa92a09e88bdb]
module.vpc.aws_route_table_association.private["private/us-west-2b"]: Destroying... [id=rtbassoc-0ca867f749dc899ce]
module.vpc.aws_route_table_association.private["private/us-west-2c"]: Destroying... [id=rtbassoc-05c492e63cffdbdc6]
aws_db_instance.test-replica[0]: Destroying... [id=ee-replica]
module.vpc.aws_route_table_association.private["private/us-west-2c"]: Destruction complete after 2s
module.vpc.aws_route_table_association.private["private/us-west-2b"]: Destruction complete after 2s
module.vpc.aws_route_table_association.private["private/us-west-2a"]: Destruction complete after 2s
aws_db_instance.test-replica[0]: Still …
```
=> Added new delete-precheck status for RDS

.changelog/31038.txt, docs/acc-test-environment-variables.md, internal/acctest/acctest.go, internal/envvar/envvar.go, internal/flex/flex.go, internal/service/inspector2/acc_test.go, internal/service/inspector2/delegated_admin_account_test.go, internal/service/inspector2/enabler.go, internal/service/inspector2/enabler_test.go, internal/service/inspector2/exports_test.go, internal/service/inspector2/inspector2_test.go, internal/service/inspector2/member_association.go, internal/service/inspector2/member_association_test.go, internal/service/licensemanager/grant_accepter_test.go, internal/slices/filters.go, internal/slices/slices.go, website/docs/r/inspector2_enabler.html.markdown, website/docs/r/inspector2_member_association.html.markdown
Enabling scanning for Lambda resources using `aws_inspector2_enabler` did not work, though the parameter was accepted.
Additionally, the resource used the `Disable` API call rather than `BatchGetAccountStatus`, which sometimes timed out, and also possibly ran into permissions problems if the user did not have authorization to disable Inspector.
Lastly, the `Enable` API call can either be called for the Organization Administrator account or a set of Member accounts.
Closes #30776
Closes #30144
Closes #27644
Closes #27639
```
$ AWS_PROFILE=<org admin account> AWS_ALTERNATE_PROFILE=<member account> AWS_THIRD_PROFILE=<another member account> make testacc PKG=inspector2
--- PASS: TestAccInspector2_serial (1877.80s)
--- PASS: TestAccInspector2_serial/DelegatedAdminAccount (42.24s)
--- PASS: …
```
=> resource/aws_inspector2_enabler: Fix various errors

.changelog/31061.txt, internal/service/servicecatalog/product.go, internal/service/servicecatalog/product_test.go
This change will now properly trigger a replacement when any `provisioning_artifact_parameters` arguments are modified.
Closes #31049
```console
$ make testacc PKG=servicecatalog TESTS=TestAccServiceCatalogProduct_
TF_ACC=1 go test ./internal/service/servicecatalog/... -v -count 1 -parallel 20 -run='TestAccServiceCatalogProduct_'  -timeout 180m
=== RUN   TestAccServiceCatalogProduct_basic
=== PAUSE TestAccServiceCatalogProduct_basic
=== RUN   TestAccServiceCatalogProduct_disappears
=== PAUSE TestAccServiceCatalogProduct_disappears
=== RUN   TestAccServiceCatalogProduct_update
=== PAUSE TestAccServiceCatalogProduct_update
=== RUN   TestAccServiceCatalogProduct_updateTags
=== PAUSE TestAccServiceCatalogProduct_updateTags
=== RUN …
```
=> r/aws_servicecatalog_product: provisioning_artifact_parameters changes force replacement

.changelog/31086.txt, internal/service/servicecatalog/provisioning_artifact.go, internal/service/servicecatalog/provisioning_artifact_test.go, website/docs/r/servicecatalog_provisioning_artifact.html.markdown
Adds a computed `provisioning_artifact_id` for use with downstream resources accepting artifact IDs as inputs.
Closes #31053 
```console
$ make testacc PKG=servicecatalog TESTS=TestAccServiceCatalogProvisioningArtifact_
TF_ACC=1 go test ./internal/service/servicecatalog/... -v -count 1 -parallel 20 -run='TestAccServiceCatalogProvisioningArtifact_'  -timeout 180m
=== RUN   TestAccServiceCatalogProvisioningArtifact_basic
=== PAUSE TestAccServiceCatalogProvisioningArtifact_basic
=== RUN   TestAccServiceCatalogProvisioningArtifact_disappears
=== PAUSE TestAccServiceCatalogProvisioningArtifact_disappears
=== RUN   TestAccServiceCatalogProvisioningArtifact_update
=== PAUSE TestAccServiceCatalogProvisioningArtifact_update
=== RUN …
```
=> r/aws_servicecatalog_provisioning_artifact: add `provisioning_artifact_id` attribute

.changelog/31094.txt, internal/service/servicecatalog/provisioned_product.go, internal/service/servicecatalog/provisioned_product_test.go
This fix will allow in-place updates of `product_name` to have the intended effect.
Closes #31051 
```console
$ make testacc PKG=servicecatalog TESTS=TestAccServiceCatalogProvisionedProduct_
TF_ACC=1 go test ./internal/service/servicecatalog/... -v -count 1 -parallel 20 -run='TestAccServiceCatalogProvisionedProduct_'  -timeout 180m
--- PASS: TestAccServiceCatalogProvisionedProduct_errorOnCreate (55.03s)
--- PASS: TestAccServiceCatalogProvisionedProduct_basic (136.71s)
--- PASS: TestAccServiceCatalogProvisionedProduct_disappears (141.15s)
--- PASS: TestAccServiceCatalogProvisionedProduct_update (228.62s)
--- PASS: TestAccServiceCatalogProvisionedProduct_tags (230.55s)
--- PASS: …
```
=> r/aws_servicecatalog_provisioned_product: Fix `product_name` update handling

internal/service/account/alternate_contact.go, internal/service/account/retry/wrappers.go
Ibid.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/26123.
```console
% make testacc TESTARGS='-run=TestAccAccount_serial/AlternateContact' PKG=account
TF_ACC=1 go test ./internal/service/account/... -v -count 1 -parallel 20  -run=TestAccAccount_serial/AlternateContact -timeout 180m
=== RUN   TestAccAccount_serial
=== PAUSE TestAccAccount_serial
=== CONT  TestAccAccount_serial
=== RUN   TestAccAccount_serial/AlternateContact
=== RUN   TestAccAccount_serial/AlternateContact/basic
=== RUN   TestAccAccount_serial/AlternateContact/disappears
=== RUN   TestAccAccount_serial/AlternateContact/AccountID
--- PASS: TestAccAccount_serial (81.41s)
--- PASS: TestAccAccount_serial/AlternateContact (81.41s)
--- PASS: …
```
=> r/aws_account_alternate_contact: Simplify retries

.changelog/31008.txt, internal/service/elasticache/replication_group.go, internal/service/elasticache/replication_group_data_source.go, internal/service/elasticache/replication_group_data_source_test.go, internal/service/elasticache/replication_group_test.go, website/docs/d/elasticache_replication_group.html.markdown, website/docs/r/elasticache_replication_group.html.markdown
Closes #18439
Closes #18441
Failure unrelated to these changes
```console
% make t T='TestAccElastiCacheReplicationGroup_ClusterMode_basic|TestAccElastiCacheReplicationGroup_ClusterMode_updateReplicasPerNodeGroup|TestAccElastiCacheReplicationGroup_ClusterModeUpdateNumNodeGroups_scaleDown|TestAccElastiCacheReplicationGroup_ClusterModeUpdateNumNodeGroups_scaleUp|TestAccElastiCacheReplicationGroup_ClusterModeUpdateNumNodeGroupsAndReplicasPerNodeGroup_scaleDown|TestAccElastiCacheReplicationGroup_ClusterModeUpdateNumNodeGroupsAndReplicasPerNodeGroup_scaleUp|TestAccElastiCacheReplicationGroup_enableAtRestEncryption|TestAccElastiCacheReplicationGroup_enableAuthTokenTransitEncryption|TestAccElastiCacheReplicationGroup_GlobalReplicationGroupIDClusterMode_basic|TestAccElastiCacheReplicationGroup_tag …
```
=> elasticache/rep_group: Remove availability zones and other deprecated parameters

internal/service/servicecatalog/provisioned_product_test.go
#31094 fixed a bug and introduced a new test for updating the `product_name` of provisioned products. As part of reviewing #26371 (a similar bug fix for the `provisioned_artifact_name` attribute), it was uncovered that the test added for product name updates was only passing due to the (now fixed) provisioned artifact name bug. 
The underlying cause is that updating a products `provisioning_artifact_parameters` isn't correctly triggering a destroy and replace, causing data source used for the `path_id` attribute to provide outdated values on update. This will be fixed in `v5.0.0` (via #31061), but in the short term this test will be disabled to allow the provisioned product test suite to pass. After `v5.0.0` is released, this can be re-enabled.
Relates #31094
Relates #26371
Relates #31061 …
=> Disable ServiceCatalog Provisioned Product `product_name` update test until v5

.changelog/31089.txt, CHANGELOG.md, internal/service/networkfirewall/firewall_policy_data_source.go, internal/service/networkfirewall/firewall_policy_data_source_test.go
When an AWS-managed rule is configured in a Network Firewall [with the action overridden](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/networkfirewall_firewall_policy#override) Terraform will fail it's plan or apply with `Invalid address to set: []string{"stateful_rule_group_reference", "0", "override"}`
I tried to include an `aws_networkfirewall_rule_group` resource in the test configuration to avoid depending on the referenced rule group existing ahead of time, however override blocks are only available on AWS-managed rule group references.
I was tempted to add a very comprehensive resource configuration for the test to try to pre-empt similar issues, but I couldn't find any cases where that's be done before for data sources. Let me know if that'd be …
=> Correctly fetch overridden actions in the Network Firewall policy data source

.changelog/31097.txt, internal/service/sfn/state_machine.go, website/docs/r/sfn_state_machine.html.markdown
Add configurable timeouts for `create`, `update`, and `delete` to the `aws_sfn_state_machine` resource
Closes [#27673](https://github.com/hashicorp/terraform-provider-aws/issues/27673).
Closes [#29206](https://github.com/hashicorp/terraform-provider-aws/issues/29206).
```
$ make testacc TESTARGS='-run=TestAccSFNStateMachine_' PKG=sfn ACCTEST_PARALLELISM=3
TF_ACC=1 go test ./internal/service/sfn/... -v -count 1 -parallel 3  -run=TestAccSFNStateMachine_ -timeout 180m
=== RUN   TestAccSFNStateMachine_createUpdate
=== PAUSE TestAccSFNStateMachine_createUpdate
=== RUN   TestAccSFNStateMachine_expressUpdate
=== PAUSE TestAccSFNStateMachine_expressUpdate
=== RUN   TestAccSFNStateMachine_standardUpdate
=== PAUSE …
```
=> Add configurable timeouts to aws_sfn_state_machine

.changelog/31118.txt, internal/service/ec2/vpc_nat_gateway.go, internal/service/ec2/vpc_nat_gateway_data_source.go
Speculatively fixes https://github.com/hashicorp/terraform-provider-aws/issues/30865 -- I wasn't able to reproduce the original bug report (see issue comments).
When a NAT Gateway is associated with a single address, consider it the primary. Otherwise find an address that has the `IsPrimary` attribute present and set to true.
Closes https://github.com/hashicorp/terraform-provider-aws/issues/30865
```
$ make testacc TESTS=TestAccVPCNATGateway PKG=ec2 ACCTEST_PARALLELISM=2
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 2 -run='TestAccVPCNATGateway'  -timeout 180m
=== RUN   TestAccVPCNATGatewayDataSource_basic
=== PAUSE TestAccVPCNATGatewayDataSource_basic
=== RUN   TestAccVPCNATGateway_basic
=== PAUSE …
```
=> aws_nat_gateway: guarantee that all attributes are set when the NAT Gateway is associated with a single address

.changelog/31076.txt, internal/service/elasticache/user.go, internal/service/elasticache/user_test.go, website/docs/r/elasticache_user.html.markdown
This change allows users to change the timeout for the user creation, default time is 5 minutes
```
resource "aws_elasticache_user" "test" {
user_name     = "username1"
...
timeouts {
create = "60m"
}
}
```
Closes #30921
```
$ make testacc TESTS='TestAccElastiCacheUser_basic' PKG=elasticache
TF_ACC=1 go test ./internal/service/elasticache/... -v -count 1 -parallel 20 -run='TestAccElastiCacheUser_basic'  -timeout 180m
=== RUN   TestAccElastiCacheUser_basic
=== PAUSE TestAccElastiCacheUser_basic
=== CONT  TestAccElastiCacheUser_basic
--- PASS: TestAccElastiCacheUser_basic (35.63s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/elasticache        59.948s
```
=> Add aws_elasticache_user customizable timeouts

.changelog/30452.txt, internal/service/dms/endpoint.go, website/docs/r/dms_endpoint.html.markdown
Removed deprecated field ignore_headers_row from aws_dms_endpoint.s3_settings
Closes #28695
=> Removed deprecated field ignore_headers_row

.changelog/31073.txt, internal/service/fsx/lustre_file_system.go, internal/service/fsx/lustre_file_system_test.go, website/docs/r/fsx_lustre_file_system.html.markdown
```
$ make testacc TESTS=TestAccFSxLustreFileSystem_rootSquashConfig PKG=fsx
--- PASS: TestAccFSxLustreFileSystem_basic (740.82s)
--- PASS: TestAccFSxLustreFileSystem_rootSquashConfig (922.52s)
```
=> r/fsx_lustre_file_system - add `root_squash_configuration`

.changelog/31067.txt, internal/service/autoscaling/group.go, internal/service/autoscaling/group_data_source.go, internal/service/autoscaling/group_data_source_test.go, internal/service/autoscaling/group_test.go, website/docs/d/autoscaling_group.html.markdown, website/docs/r/autoscaling_group.html.markdown
This PR adds a handful of missing attributes listed in #20398 to the `aws_autoscaling_group` data source. For every attribute, strived to match the corresponding resource schema.
Attributes:
- `LaunchTemplate` - added documentation (was already implemented)
- `EnabledMetrics` - already done
- `MaxInstanceLifetime` - added to the data source
- `MixedInstancesPolicy` - added to the data source
- `PredictedCapacity` - added to both data source and resource
- `SuspendedProcesses` - added to the data source
- `Tags` - added to the data source (in a way matching the implementation from the resource)
- `TerminationPolicies` - already done
- `WarmPoolConfiguration` - added to the data source
- `WarmPoolSize` - added to both data source and resource
Closes #20398. …
=> rd/aws_autoscaling_group: add missing attributes

.changelog/31141.txt, internal/service/firehose/delivery_stream.go, internal/service/firehose/delivery_stream_test.go, website/docs/r/kinesis_firehose_delivery_stream.html.markdown
Closes #22146
```console
% make t T=TestAccFirehoseDeliveryStream_ K=firehose P=3
TF_ACC=1 go test ./internal/service/firehose/... -v -count 1 -parallel 3 -run='TestAccFirehoseDeliveryStream_'  -timeout 180m
=== RUN   TestAccFirehoseDeliveryStream_basic
=== PAUSE TestAccFirehoseDeliveryStream_basic
=== RUN   TestAccFirehoseDeliveryStream_disappears
=== PAUSE TestAccFirehoseDeliveryStream_disappears
=== RUN   TestAccFirehoseDeliveryStream_tags
=== PAUSE TestAccFirehoseDeliveryStream_tags
=== RUN   TestAccFirehoseDeliveryStream_s3basic
=== PAUSE TestAccFirehoseDeliveryStream_s3basic
=== RUN   TestAccFirehoseDeliveryStream_s3basicWithPrefixes
=== PAUSE TestAccFirehoseDeliveryStream_s3basicWithPrefixes
=== RUN …
```
=> firehose/delivery_stream: Make buffering args consistent

.changelog/30918.txt, internal/service/ec2/ec2_spot_fleet_request.go, internal/service/ec2/ec2_spot_fleet_request_test.go, website/docs/r/spot_fleet_request.html.markdown
Add the `context` field to `aws_spot_fleet_request`.
```
$ make testacc PKG=ec2 TESTS=TestAccEC2SpotFleetRequest_context
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 20 -run='TestAccEC2SpotFleetRequest_context'  -timeout 180m
=== RUN   TestAccEC2SpotFleetRequest_context
=== PAUSE TestAccEC2SpotFleetRequest_context
=== CONT  TestAccEC2SpotFleetRequest_context
--- PASS: TestAccEC2SpotFleetRequest_context (22.72s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/ec2        22.375s
```
=> Add 'context' field to EC2 spot fleet request

website/docs/r/ecr_repository_policy.html.markdown, website/docs/r/ecrpublic_repository_policy.html.markdown
The documentation for ECR Repository policies is permissive. This is a minor update to documentation that better demonstrates best practices of explicitly setting the type and identifier in the policy.
Policy example in AWS docs can be found [here](https://docs.aws.amazon.com/AmazonECR/latest/userguide/repository-policy-examples.html) and [here](https://docs.aws.amazon.com/AmazonECR/latest/public/public-repository-policies.html).
=> Update permissive ECR policy docs to better demonstrate best practices

internal/service/quicksight/data_set.go
When reading data set details from AWS API, the `start_from_row` value `physical_table_map/s3_source/from upload_settings` it is casted as an int64 but it will make the use of `schema.NewSet()` crash as an int is expected in terraform plugin code: https://github.com/hashicorp/terraform-plugin-sdk/blob/main/helper/schema/serialize.go#L24
You get the following error:
```
Stack trace from the terraform-provider-aws plugin:
panic: interface conversion: interface {} is int64, not int
goroutine 579 [running]:
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.SerializeValueForHash(0xbb7cfa0?, {0xaeb3fa0?, 0x1580c668?}, 0xe?)
/home/comtef/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/serialize.go:24 +0x2da …
```
=> Fix aws_quicksight_data_set S3 source upload settings flatten func

.changelog/31015.txt, internal/service/rds/cluster_role_association.go, internal/service/rds/cluster_role_association_test.go, internal/service/rds/wait.go, website/docs/r/rds_cluster_role_association.html.markdown
Added configurable timeouts for the resource `aws_rds_cluster_role_association`.
The default for Create and Delete operations is still 10 minutes (there is no Update operation for the resource).
Also, omitted the `backup_retention_period` and `preferred_backup_window` which caused the acceptance test `TestAccRDSClusterRoleAssociation_basic` to try and delete the associated IAM Role while the cluster was in "backing-up" state:
```
make testacc TESTS='TestAccRDSClusterRoleAssociation_basic' PKG=rds
TF_ACC=1 go test ./internal/service/rds/... -v -count 1 -parallel 20 -run='TestAccRDSClusterRoleAssociation_basic'  -timeout 180m
=== RUN   TestAccRDSClusterRoleAssociation_basic
=== PAUSE TestAccRDSClusterRoleAssociation_basic
=== CONT …
```
=> Enhancement: add configurable timeouts to r/`aws_rds_cluster_role_association`

.changelog/31138.txt, internal/service/firehose/delivery_stream.go, internal/service/firehose/delivery_stream_test.go, website/docs/r/kinesis_firehose_delivery_stream.html.markdown
- - [x] `elasticsearch_configuration`
- - [x] `opensearch_configuration`
- - [x] `splunk_configuration`
- - [x] `redshift_configuration`
- - [x] `http_endpoint_configuration`
Closes #22309
```console 
$ make testacc TESTARGS='-run=TestAccFirehoseDeliveryStream_' PKG=firehose
TF_ACC=1 go test ./internal/service/firehose/... -v -count 1 -parallel 20  -run=TestAccFirehoseDeliveryStream_ -timeout 180m
--- PASS: TestAccFirehoseDeliveryStream_extendedS3basic (284.78s)
--- PASS: TestAccFirehoseDeliveryStream_basic (309.18s)
--- PASS: TestAccFirehoseDeliveryStream_ExtendedS3DataFormatConversionHiveJSONSerDe_empty (313.75s)
--- PASS: TestAccFirehoseDeliveryStream_missingProcessing (323.59s)
--- PASS: …
```
=> r/aws_kinesis_firehose_delivery_stream: deprecate root `s3_configuration`

.changelog/31035.txt
Changes breaking change entries to notes, as attributes are only being deprecated, not removed.
Relates #31015
=> chore: switch changelog deprecations to note

go.mod, go.sum, internal/conns/awsclient_gen.go, internal/conns/config_gen.go, internal/service/accessanalyzer/accessanalyzer_test.go, internal/service/accessanalyzer/analyzer.go, internal/service/accessanalyzer/analyzer_test.go, internal/service/accessanalyzer/archive_rule.go, internal/service/accessanalyzer/archive_rule_test.go, internal/service/accessanalyzer/exports_test.go, internal/service/accessanalyzer/generate.go, internal/service/accessanalyzer/service_package_gen.go, internal/service/accessanalyzer/sweep.go, internal/service/accessanalyzer/tags_gen.go, names/names.go, names/names_data.csv
Ibid.
```console
% make testacc TESTARGS='-run=TestAccAccessAnalyzer_serial' PKG=accessanalyzer
TF_ACC=1 go test ./internal/service/accessanalyzer/... -v -count 1 -parallel 20  -run=TestAccAccessAnalyzer_serial -timeout 180m
=== RUN   TestAccAccessAnalyzer_serial
=== PAUSE TestAccAccessAnalyzer_serial
=== CONT  TestAccAccessAnalyzer_serial
=== RUN   TestAccAccessAnalyzer_serial/Analyzer
=== RUN   TestAccAccessAnalyzer_serial/Analyzer/tags
=== RUN   TestAccAccessAnalyzer_serial/Analyzer/Type_Organization
acctest.go:895: skipping tests; this AWS account must not be an existing member of an AWS Organization
=== RUN   TestAccAccessAnalyzer_serial/Analyzer/basic
=== RUN   TestAccAccessAnalyzer_serial/Analyzer/disappears
=== RUN …
```
=> Tech debt: Migrate `accessanalyzer` resources to AWS SDK for Go v2

.changelog/31251.txt, internal/service/fsx/ontap_file_system.go, internal/service/fsx/ontap_file_system_test.go, website/docs/r/fsx_ontap_file_system.html.markdown
Closes #29301
Closes #29128
```
$ make testacc TESTS=TestAccFSxOntapFileSystem_routeTableIDs  PKG=fsx
--- PASS: TestAccFSxOntapFileSystem_routeTableIDs (2803.90s)
```
=> r/aws_fsx_ontap_file_system - allow updating route table ids + 4096 throughput_capacity support 

.changelog/31250.txt, internal/service/redshiftserverless/namespace_data_source.go, internal/service/redshiftserverless/namespace_data_source_test.go, internal/service/redshiftserverless/service_package_gen.go, website/docs/d/redshiftserverless_namespace.html.markdown
New Data Source for `aws_redshiftserverless_namespace`.
```
$ make testacc TESTS=TestAccRedshiftServerlessNamespaceDataSource PKG=redshiftserverless
TF_ACC=1 go test ./internal/service/redshiftserverless/... -v -count 1 -parallel 20 -run='TestAccRedshiftServerlessNamespaceDataSource'  -timeout 180m
=== RUN   TestAccRedshiftServerlessNamespaceDataSource_basic
=== PAUSE TestAccRedshiftServerlessNamespaceDataSource_basic
=== RUN   TestAccRedshiftServerlessNamespaceDataSource_iamRole
=== PAUSE TestAccRedshiftServerlessNamespaceDataSource_iamRole
=== RUN   TestAccRedshiftServerlessNamespaceDataSource_user
=== PAUSE TestAccRedshiftServerlessNamespaceDataSource_user
=== RUN   TestAccRedshiftServerlessNamespaceDataSource_logExports
=== …
```
=> New Data Source: aws_redshiftserverless_namespace

.changelog/31253.txt, internal/service/iam/diff.go, internal/service/iam/openid_connect_provider.go, internal/service/iam/openid_connect_provider_test.go
When creating an `aws_iam_openid_connect_provider` today, AWS does not seem to preserve the order of values provided in `client_id_list`. Functionally this is not a problem, but it does lead to #29868 where subsequent applies will lead to non-empty plans, as Terraform attempts to 'correct' the order (unless the order given in your `.tf` file *happens* to match AWS).
This PR addresses that by defining a new `DiffSuppressFunc` for this use case, which suppresses a diff if a 'new' element is found in the list of client_ids present on the current state. As long as your changes only affect the order, there will be no diff and therefore no plan. It should be noted though that once you do change somethign else than the order (i.e. add/remove client ids), the shown diff will still show that …
=> fix: Ignore order of client IDs in  iam_openid_connect_provider

.teamcity/settings.kts
Fixes parameter error in TeamCity configuration when only legacy credentials are set.
=> CI: Sets `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` to empty if not set

.changelog/31293.txt, internal/service/servicecatalog/provisioned_product.go, internal/service/servicecatalog/provisioned_product_test.go
Fixes the `stack_set_provisioned_preferences` expander to properly send the `accounts` attributes on Create/Update.
Closes #29343
```console
$ make testacc PKG=servicecatalog TESTS=TestAccServiceCatalogProvisionedProduct_
TF_ACC=1 go test ./internal/service/servicecatalog/... -v -count 1 -parallel 20 -run='TestAccServiceCatalogProvisionedProduct_'  -timeout 180m
--- PASS: TestAccServiceCatalogProvisionedProduct_errorOnCreate (53.31s)
--- PASS: TestAccServiceCatalogProvisionedProduct_disappears (131.60s)
--- PASS: TestAccServiceCatalogProvisionedProduct_basic (135.69s)
--- PASS: TestAccServiceCatalogProvisionedProduct_tags (221.81s)
--- PASS: TestAccServiceCatalogProvisionedProduct_update (222.72s)
--- PASS: …
```
=> r/aws_servicecatalog_provisioned_product: properly set `stack_set_provisioned_preferences.accounts`

website/docs/guides/version-5-upgrade.html.md
Adding v5 upgrade guide entries for the related PRs below.
Relates #29409
Relates #30842
Relates #30969
=> [Docs]: V5 Upgrade guide additions

.changelog/31310.txt, internal/service/quicksight/exports_test.go, internal/service/quicksight/service_package_gen.go, internal/service/quicksight/template_alias.go, internal/service/quicksight/template_alias_test.go, website/docs/r/quicksight_template_alias.html.markdown
This resource will allow practitioners to manager QuickSight template aliases via Terraform.
Relates #10990
Closes #11836 
- https://docs.aws.amazon.com/quicksight/latest/APIReference/API_CreateTemplateAlias.html
- https://docs.aws.amazon.com/quicksight/latest/APIReference/API_UpdateTemplateAlias.html
- https://docs.aws.amazon.com/quicksight/latest/APIReference/API_DescribeTemplateAlias.html
- https://docs.aws.amazon.com/quicksight/latest/APIReference/API_DeleteTemplateAlias.html
```console
$ make testacc PKG=quicksight TESTS=TestAccQuickSightTemplateAlias_
TF_ACC=1 go test ./internal/service/quicksight/... -v -count 1 -parallel 20 -run='TestAccQuickSightTemplateAlias_'  -timeout 180m
? …
```
=> New Resource: `aws_quicksight_template_alias`

.changelog/31315.txt, internal/service/configservice/configservice_test.go, internal/service/configservice/remediation_configuration.go, internal/service/configservice/remediation_configuration_test.go
Closes #31319
```console
$ make testacc TESTARGS='-run=TestAccConfigService_serial/RemediationConfiguration' PKG=configservice
TF_ACC=1 go test ./internal/service/configservice/... -v -count 1 -parallel 20  -run=TestAccConfigService_serial/RemediationConfiguration -timeout 180m
=== RUN   TestAccConfigService_serial
=== PAUSE TestAccConfigService_serial
=== CONT  TestAccConfigService_serial
=== RUN   TestAccConfigService_serial/RemediationConfiguration
=== RUN   TestAccConfigService_serial/RemediationConfiguration/disappears
=== RUN   TestAccConfigService_serial/RemediationConfiguration/migrateParameters
=== RUN   TestAccConfigService_serial/RemediationConfiguration/recreates
=== RUN …
```
=> configservice/remediation_configuration: parameters TypeSet -> TypeList

skaff/resource/resourcetest.tmpl
Adds a missing context argument to the testAccCheck*Exists func.
=> [TechDebt](skaff): add missing `ctx` argument

.changelog/30744.txt, docs/acc-test-environment-variables.md, internal/service/quicksight/data_set.go, internal/service/quicksight/data_set_test.go, website/docs/r/quicksight_data_set.html.markdown
This PR updates the existing `aws_quicksight_data_set` resource to allow configuration of [refresh properties](https://docs.aws.amazon.com/quicksight/latest/user/refreshing-imported-data.html#refresh-spice-data-incremental).
Closes #30744
Relates To https://github.com/hashicorp/terraform-provider-aws/issues/10990
```
make testacc PKG=quicksight TESTS=TestAccQuickSightDataSet_
TF_ACC=1 go test ./internal/service/quicksight/... -v -count 1 -parallel 20 -run='TestAccQuickSightDataSet_'  -timeout 180m
=== RUN   TestAccQuickSightDataSet_basic
=== PAUSE TestAccQuickSightDataSet_basic
=== RUN   TestAccQuickSightDataSet_disappears
=== PAUSE TestAccQuickSightDataSet_disappears
=== RUN   TestAccQuickSightDataSet_columnGroups
=== PAUSE …
```
=> aws_quicksight_data_set: Add support for configuring refresh properties

internal/service/quicksight/data_set.go, internal/service/quicksight/sweep.go
Adds sweepers for various QuickSight resources.
```
$ make sweep SWEEPARGS=-sweep-run=aws_quicksight
go test ./internal/sweep -v -tags=sweep -sweep=us-west-2,us-east-1,us-east-2 -sweep-run=aws_quicksight -timeout 60m
<snip>
2023/05/11 10:56:53 Completed Sweepers for region (us-east-2) in 1.971284917s
2023/05/11 10:56:53 Sweeper Tests for region (us-east-2) ran successfully:
- aws_quicksight_folder
- aws_quicksight_user
- aws_quicksight_data_set
- aws_quicksight_template
- aws_quicksight_data_source
ok      github.com/hashicorp/terraform-provider-aws/internal/sweep      11.007s
```
=> [TechDebt]: QuickSight sweepers

.changelog/31309.txt, internal/service/quicksight/exports_test.go, internal/service/quicksight/iam_policy_assignment.go, internal/service/quicksight/service_package_gen.go, internal/service/quicksight/vpc_connection.go, internal/service/quicksight/vpc_connection_test.go, internal/service/quicksight/wait.go, website/docs/r/quicksight_vpc_connection.html.markdown
This PR adds a new `aws_quicksight_vpc_connection` resource, allowing practitioners to manage QuickSight VPC connections via Terraform.
Closes https://github.com/hashicorp/terraform-provider-aws/issues/31281
Relates To https://github.com/hashicorp/terraform-provider-aws/issues/10990
Announcement: https://aws.amazon.com/about-aws/whats-new/2023/05/amazon-quicksight-vpc-public-apis-multi-az-support/
- https://docs.aws.amazon.com/quicksight/latest/APIReference/API_CreateVPCConnection.html
- https://docs.aws.amazon.com/quicksight/latest/APIReference/API_DeleteVPCConnection.html
- https://docs.aws.amazon.com/quicksight/latest/APIReference/API_DescribeVPCConnection.html
- https://docs.aws.amazon.com/quicksight/latest/APIReference/API_UpdateVPCConnection.html
- …
=> New Resource: `aws_quicksight_vpc_connection`

.changelog/31340.txt, internal/service/ssm/activation.go, internal/service/ssm/activation_test.go
This pull request accomplishes the following:
1. Updates the tests for aws_ssm_activation to properly test the `iam_role` field by separating out the resource name and the iam role name.
2. Updates the IamRole in the CreateActivationInput to use the proper schema field. 
I made sure that the tests were failing before the update to code and are now passing with the correct field being passed. 
Closes #30441
```
$ make testacc TESTARGS='-run=TestAccSSMActivation' PKG=ssm 
TF_ACC=1 go test ./internal/service/ssm/... -v -count 1 -parallel 20  -run=TestAccSSMActivation -timeout 180m
=== RUN   TestAccSSMActivation_basic
=== PAUSE TestAccSSMActivation_basic
=== RUN   TestAccSSMActivation_tags
=== PAUSE TestAccSSMActivation_tags
=== RUN …
```
=> Bugfix:  `aws_ssm_activation` Fails on nonexistent role

website/docs/r/cloudfront_distribution.html.markdown
The [documentation](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudfront_distribution#custom-origin-config-arguments) for CloudFront custom origin states default values for `origin_keepalive_timeout` and `origin_read_timeout` as `60`. However on the AWS console and in the AWS documentation for CloudFront the default value for `origin_keepalive_timeout` is 5 seconds and `origin_read_timeout` is 30 seconds. 
[Reference](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/RequestAndResponseBehaviorCustomOrigin.html#request-custom-request-timeout) for origin_read_timeout.
[Reference](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/distribution-web-values-specify.html#DownloadDistValuesOriginKeepaliveTimeout) for …
=> patch default AWS values for origin config in the doc

.changelog/31232.txt, examples/rds/main.tf, examples/rds/outputs.tf, internal/service/rds/blue_green.go, internal/service/rds/export_task_test.go, internal/service/rds/instance.go, internal/service/rds/instance_automated_backups_replication_test.go, internal/service/rds/instance_data_source_test.go, internal/service/rds/instance_migrate.go, internal/service/rds/instance_migrate_test.go, internal/service/rds/instance_role_association_test.go, internal/service/rds/instance_test.go, internal/service/rds/option_group_test.go, internal/service/rds/proxy_target_test.go, internal/service/rds/snapshot_copy_test.go, internal/service/rds/snapshot_data_source_test.go, internal/service/rds/snapshot_test.go, internal/service/rds/sweep.go, website/docs/d/db_snapshot.html.markdown, website/docs/r/db_event_subscription.html.markdown, website/docs/r/db_instance.html.markdown, website/docs/r/db_instance_automated_backups_replication.markdown, website/docs/r/db_instance_role_association.html.markdown, website/docs/r/db_proxy_target.html.markdown, website/docs/r/db_snapshot.html.markdown, website/docs/r/db_snapshot_copy.html.markdown, website/docs/r/rds_export_task.html.markdown, website/docs/r/ssm_parameter.html.markdown
Closes #16782
Closes #507
(Failures unrelated to these changes.)
```console
% make t T=TestAccRDSInstance_ K=rds P=5 ACCTEST_TIMEOUT=780m
TF_ACC=1 go test ./internal/service/rds/... -v -count 1 -parallel 5 -run='TestAccRDSInstance_'  -timeout 780m
=== RUN   TestAccRDSInstance_basic
=== PAUSE TestAccRDSInstance_basic
=== RUN   TestAccRDSInstance_manage_password
=== PAUSE TestAccRDSInstance_manage_password
=== RUN   TestAccRDSInstance_identifierPrefix
=== PAUSE TestAccRDSInstance_identifierPrefix
=== RUN   TestAccRDSInstance_identifierGenerated
=== PAUSE TestAccRDSInstance_identifierGenerated
=== RUN   TestAccRDSInstance_disappears
=== PAUSE TestAccRDSInstance_disappears
=== RUN   TestAccRDSInstance_tags
=== PAUSE …
```
=> rds/instance: NEW ID configuration

internal/service/s3/bucket_object.go, internal/service/s3/bucket_object_data_source.go, internal/service/s3/bucket_objects_data_source.go
Adds `DeprecationMessage` to resource and data source schemas.
Closes https://github.com/hashicorp/terraform-provider-aws/issues/29722.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/22877.
```console
% make testacc TESTARGS='-run=TestAccS3BucketObject_empty$$\|TestAccS3BucketObjectDataSource_basic$$\|TestAccS3BucketObjectsDataSource_basic$$' PKG=s3
TF_ACC=1 go test ./internal/service/s3/... -v -count 1 -parallel 20  -run=TestAccS3BucketObject_empty$\|TestAccS3BucketObjectDataSource_basic$\|TestAccS3BucketObjectsDataSource_basic$ -timeout 180m
=== RUN   TestAccS3BucketObjectDataSource_basic
=== PAUSE TestAccS3BucketObjectDataSource_basic
=== RUN   TestAccS3BucketObject_empty
=== PAUSE TestAccS3BucketObject_empty …
```
=> r/aws_s3_bucket_object: Add deprecation message to schemas

website/docs/guides/version-5-upgrade.html.md
Adds some missing attribute deprecations to the _Terraform AWS Provider Version 5 Upgrade Guide_.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/31490.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/31380.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/31382.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/31384.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/31162.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/29555.
=> Add missing Terraform AWS Provider Version 5 Upgrade Guide entries

internal/provider/intercept.go
Fixes the case of a resource having no `identifierAttribute` declared in its `@Tags` annotation and all existing tags are being removed. This was causing a provider crash.
Closes https://github.com/hashicorp/terraform-provider-aws/issues/31498.
```console
% make testacc TESTARGS='-run=TestAccCloudFormationStackSet_tags' PKG=cloudformation
TF_ACC=1 go test ./internal/service/cloudformation/... -v -count 1 -parallel 20  -run=TestAccCloudFormationStackSet_tags -timeout 180m
=== RUN   TestAccCloudFormationStackSet_tags
=== PAUSE TestAccCloudFormationStackSet_tags
=== CONT  TestAccCloudFormationStackSet_tags
--- PASS: TestAccCloudFormationStackSet_tags (82.95s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/cloud …
```
=> Fix crash when removing all tags for resources with no `identifierAttribute` declared

.ci/.golangci2.yml
Suppresses https://github.com/hashicorp/terraform-provider-aws/actions/runs/5021709902/jobs/9004392130?pr=31474
```
Running [/home/runner/golangci-lint-1.52.2-linux-amd64/golangci-lint run --out-format=github-actions --config .ci/.golangci2.yml] in [] ...
Error: SA1019: s3Config.DisableRestProtocolURICleaning is deprecated: This setting no longer has any effect. RESTful paths are no longer cleaned after request serialization.  (staticcheck)
Error: issues found
Ran golangci-lint in 557396ms
```
until https://github.com/hashicorp/terraform-provider-aws/issues/31501 is addressed.
=> Suppress `golangci-lint` `s3Config.DisableRestProtocolURICleaning is deprecated` warning

internal/service/servicecatalog/provisioned_product_test.go
Re-enables a provisioned product test dependent on features released in v5.0.0.
Closes #31119
Relates #31115 
```console
$ make testacc PKG=servicecatalog TESTS=TestAccServiceCatalogProvisionedProduct_
TF_ACC=1 go test ./internal/service/servicecatalog/... -v -count 1 -parallel 20 -run='TestAccServiceCatalogProvisionedProduct_'  -timeout 180m
--- PASS: TestAccServiceCatalogProvisionedProduct_errorOnCreate (54.10s)
--- PASS: TestAccServiceCatalogProvisionedProduct_disappears (132.30s)
--- PASS: TestAccServiceCatalogProvisionedProduct_basic (136.98s)
--- PASS: TestAccServiceCatalogProvisionedProduct_tags (223.56s)
--- PASS: TestAccServiceCatalogProvisionedProduct_update (224.91s)
--- PASS: …
```
=> r/aws_servicecatalog_provisioned_product: re-enable product namee update test

.changelog/31276.txt, internal/provider/provider.go, internal/sweep/sweep.go, website/docs/guides/version-5-upgrade.html.md, website/docs/index.html.markdown
The provider was previously setting the default retry count for the AWS SDK to 25. This would  cause the SDK to retry returnable errors for an extremely long time internally without returning control to the provider, which would look like a hang to users.
=> Use default retry count from AWS SDK

.changelog/31276.txt, internal/provider/provider.go, internal/sweep/sweep.go, website/docs/guides/version-5-upgrade.html.md, website/docs/index.html.markdown
Reverts hashicorp/terraform-provider-aws#31276
=> Revert "Use default retry count from AWS SDK"

internal/service/iam/policy_document_data_source_test.go
Adds test for multiple condition keys for same operator in policy document
```
$ make testacc PKG=iam TESTS=TestAccIAMPolicyDocumentDataSource_
--- PASS: TestAccIAMPolicyDocumentDataSource_sourceListConflicting (7.48s)
--- PASS: TestAccIAMPolicyDocumentDataSource_StatementPrincipalIdentifiers_stringAndSlice (37.54s)
--- PASS: TestAccIAMPolicyDocumentDataSource_noStatementOverride (38.87s)
--- PASS: TestAccIAMPolicyDocumentDataSource_conditionWithBoolValue (38.98s)
--- PASS: TestAccIAMPolicyDocumentDataSource_singleConditionValue (39.14s)
--- PASS: TestAccIAMPolicyDocumentDataSource_StatementPrincipalIdentifiers_multiplePrincipals (39.26s)
--- PASS: TestAccIAMPolicyDocumentDataSource_multipleConditionKeys (39.33s)
--- PASS: TestAccIAMPolicyDocumentDataSource_override (40.02s)
--- PASS: …
```
=> datasource/aws_iam_policy_document: Add test for multiple condition keys

.changelog/31587.txt, internal/service/ec2/vpc_test.go, internal/tags/key_value_tags.go
`null` values can be used as placeholders for tags that are not configured. These values should be ignored when resolving tag differences.
Closes #31583
Closes #31586
```console 
make testacc TESTARGS='-run=TestAccVPC_ -short' PKG=vpc
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 20  -run=TestAccVPC_ -short -timeout 180m
vpc_test.go:969: skipping long-running test in short mode
vpc_test.go:996: skipping long-running test in short mode
vpc_test.go:1024: skipping long-running test in short mode
--- SKIP: TestAccVPC_IPAMIPv6 (0.00s)
=== NAME  TestAccVPC_assignGeneratedIPv6CIDRBlockWithNetworkBorderGroup …
```
=> Tags: fix for null tags in config

.changelog/31588.txt, internal/service/route53/vpc_association_authorization.go, internal/service/route53/vpc_association_authorization_test.go
Retries creation and deletion of `aws_route53_vpc_association_authorization` when a `ConcurrentModification` error is received.
Closes #15762
This error is very rare. The best way to confirm that it is working is to generate a debug log and verifying that the `ConcurrentModification` error is received and retried.
```
$ make testacc PKG=route53 TESTS=TestAccRoute53VPCAssociationAuthorization_
--- PASS: TestAccRoute53VPCAssociationAuthorization_disappears (87.28s)
--- PASS: TestAccRoute53VPCAssociationAuthorization_concurrent (93.15s)
--- PASS: TestAccRoute53VPCAssociationAuthorization_basic (97.26s)
```
=> resource/aws_route53_vpc_association_authorization: Fix `ConcurrentModification` error

.changelog/31551.txt, internal/service/autoscaling/group.go, internal/service/autoscaling/group_test.go
The AWS API returns the last six weeks of Auto Scaling Group scaling activities. If old errored activities exist, this can cause failures.
Now ignores scaling activities before the start of the operation.
Closes #26377
```
$ make testacc PKG=autoscaling TESTS=TestAccAutoScalingGroup_
--- PASS: TestAccAutoScalingGroup_basic (53.70s)
--- PASS: TestAccAutoScalingGroup_MixedInstancesPolicyLaunchTemplateOverride_instanceRequirements_spotMaxPricePercentageOverLowestPrice (55.90s)
--- PASS: TestAccAutoScalingGroup_MixedInstancesPolicyLaunchTemplateOverride_instanceRequirements_onDemandMaxPricePercentageOverLowestPrice (78.87s)
--- PASS: TestAccAutoScalingGroup_MixedInstancesPolicyLaunchTemplateOverride_instanceRequirements_instanceGenerations (93.05s)
--- PASS: …
```
=> resource/aws_autoscaling_group: Ignore scaling activities from before the scaling operation started

internal/service/cloudtrail/cloudtrail_test.go, website/docs/r/cloudtrail.html.markdown
With the recent bucket ownership control updates from AWS, current policies in the acceptance tests and documentation for CloutTrail were no longer valid
Relates #31021
```
$ make testacc PKG=cloudtrail TESTS=TestAccCloudTrail_serial
--- PASS: TestAccCloudTrail_serial (425.16s)
--- PASS: TestAccCloudTrail_serial/Trail (425.16s)
--- PASS: TestAccCloudTrail_serial/Trail/insightSelector (48.00s)
--- PASS: TestAccCloudTrail_serial/Trail/disappears (14.41s)
--- SKIP: TestAccCloudTrail_serial/Trail/enableLogging (20.63s)
--- PASS: TestAccCloudTrail_serial/Trail/multiRegion (36.11s)
--- PASS: TestAccCloudTrail_serial/Trail/eventSelectorDynamoDB (21.64s)
--- PASS: TestAccCloudTrail_serial/Trail/cloudwatch (46.59s)
--- PASS: TestAccCloudTrail_serial/Trail/globalServiceEvents (15.86s)
--- PASS: …
```
=> Fixes S3 bucket policy for CloudTrail acceptance tests

.changelog/31608.txt, internal/service/cloudfront/distribution.go
`origin_keepalive_timeout` is an attribute with a default maximum, but this can be changed arbitrarily by AWS Support to a much higher value.  This change removes the upper limit, but leaves the lower minimum.
Closes #23437
```
ᐅ make testacc TESTS="TestAccCloudFrontDistribution_basic" PKG=cloudfront
TF_ACC=1 go test ./internal/service/cloudfront/... -v -count 1 -parallel 20 -run='TestAccCloudFrontDistribution_basic'  -timeout 180m
=== RUN   TestAccCloudFrontDistribution_basic
=== PAUSE TestAccCloudFrontDistribution_basic
=== CONT  TestAccCloudFrontDistribution_basic
--- PASS: TestAccCloudFrontDistribution_basic (238.03s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/cloudfront	240.855s
```
=> Remove the upper bound on aws_cloudfront_distribution/origin_keepalive_timeout

.changelog/31480.txt, internal/service/directconnect/connection.go, internal/service/directconnect/connection_data_source.go, internal/service/directconnect/connection_test.go
Fixes the schema type for vlan_id for aws_dx_connection so that null isn't returned.
Closes #29165
=> Fix schema type for vlan_id on aws_dx_connection

.changelog/31393.txt, internal/service/rbin/rule.go, internal/service/rbin/rule_test.go
aws-rbin_rule update crashes with multiple resource tags.
```go
panic: interface conversion: interface {} is *schema.Set, not []interface {}
```
Steps to re-produce the panic.
```terraform
resource "aws_rbin_rule" "example" {
description   = "example_rule"
resource_type = "EBS_SNAPSHOT"
resource_tags {
resource_tag_key   = "tag_key1"
resource_tag_value = "tag_value1"
}
retention_period {
retention_period_value = 10
retention_period_unit  = "DAYS"
}
tags = {
"test_tag_key" = "test_tag_value"
}
}
```
Update the resource with two tags
```terraform
resource "aws_rbin_rule" "example" {
description   = "example_rule"
resource_type = "EBS_SNAPSHOT"
resource_tags {
resource_tag_key   = "tag_key1"
resource_tag_value = "tag_value1"
}
resource_tags {
resource_tag_key   = "tag_key2" …
```
=> r/aws_rbin_rule: Fix multiple resource tag panic

.ci/.golangci2.yml
Reverts the `golangci-lint` deprecation suppression of `s3Config.DisableRestProtocolURICleaning`.
Closes https://github.com/hashicorp/terraform-provider-aws/issues/31501.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/31502.
Relates https://github.com/aws/aws-sdk-go/pull/4849.
=> Revert `s3Config.DisableRestProtocolURICleaning` deprecation suppression

.changelog/31424.txt, internal/service/quicksight/data_set.go
In the current implementation the join instructions were not being picked up when creating a data set in quick sight.
Closes #30948
See below comment
=> Updated map for quicksight data set join operation

.changelog/31488.txt, internal/service/quicksight/data_set.go
Ignore failure to read refresh properties for non-SPICE datasets.
Fixes #31485
Related To: #30778
=> r/aws_quicksight_data_set: Ignore failure to read refresh properties for non-SPICE datasets

.changelog/31647.txt, internal/service/medialive/channel_encoder_settings_schema.go
Closes #31629
```console
$ make testacc TESTARGS='-run=TestAccMediaLiveChannel_' PKG=medialive
TF_ACC=1 go test ./internal/service/medialive/... -v -count 1 -parallel 20  -run=TestAccMediaLiveChannel_ -timeout 180m
--- PASS: TestAccMediaLiveChannel_basic (75.04s)
--- PASS: TestAccMediaLiveChannel_M2TS_settings (85.35s)
--- PASS: TestAccMediaLiveChannel_MsSmooth_outputSettings (90.55s)
--- PASS: TestAccMediaLiveChannel_AudioDescriptions_codecSettings (93.78s)
--- PASS: TestAccMediaLiveChannel_VideoDescriptions_CodecSettings_h264Settings (94.22s)
--- PASS: TestAccMediaLiveChannel_disappears (137.96s)
--- PASS: TestAccMediaLiveChannel_hls (152.00s)
--- PASS: TestAccMediaLiveChannel_VideoDescriptions_CodecSettings_h265Settings …
```
=> medialive/channel: fix`hls_cdn_settings` mapping

.teamcity/components/service_build_config.kt, .teamcity/settings.kts
Removes the hanging build notifications from TeamCity, since they don't add value and are noisy.
=> ci/teamcity: Remove hanging build notifications

.changelog/31612.txt, internal/service/redshift/cluster.go, internal/service/redshift/cluster_test.go, internal/service/redshift/wait.go, website/docs/r/redshift_cluster.html.markdown
Fixes acceptance test failures:
* Adds `Maintenance` as valid pending status in `waitClusterDeleted`
* Deprecates unused parameter `aqua_configuration_status`
```
$ make testacc PKG=redshift TESTS=TestAccRedshiftCluster_
--- PASS: TestAccRedshiftCluster_availabilityZoneRelocation_publiclyAccessible (8.32s)
--- PASS: TestAccRedshiftCluster_changeAvailabilityZone_availabilityZoneRelocationNotSet (206.18s)
--- PASS: TestAccRedshiftCluster_disappears (243.71s)
--- PASS: TestAccRedshiftCluster_iamRoles (272.16s)
--- PASS: TestAccRedshiftCluster_kmsKey (302.10s)
--- PASS: TestAccRedshiftCluster_snapshotCopy (316.21s)
--- PASS: TestAccRedshiftCluster_publiclyAccessible (360.08s)
--- PASS: TestAccRedshiftCluster_enhancedVPCRoutingEnabled (377.35s)
--- PASS: …
```
=> resource/aws_redshift_cluster: Acceptance tests fixes

.changelog/31542.txt, internal/service/quicksight/analysis.go, internal/service/quicksight/analysis_test.go, internal/service/quicksight/schema/analysis.go, internal/service/quicksight/service_package_gen.go, internal/service/quicksight/status.go, internal/service/quicksight/wait.go, website/docs/r/quicksight_analysis.html.markdown
New resource for Quicksight Analysis.
- Definition mostly reuse underlying resources shared with Template and Dashboard.
- Tests for basic usage, update, analysis specific attributes
Relates #31666
https://docs.aws.amazon.com/quicksight/latest/APIReference/API_CreateAnalysis.html
https://docs.aws.amazon.com/quicksight/latest/APIReference/API_UpdateAnalysis.html
https://docs.aws.amazon.com/quicksight/latest/APIReference/API_DescribeAnalysis.html
https://docs.aws.amazon.com/quicksight/latest/APIReference/API_DescribeAnalysisDefinition.html
https://docs.aws.amazon.com/quicksight/latest/APIReference/API_DescribeAnalysisPermissions.html
https://docs.aws.amazon.com/quicksight/latest/APIReference/API_DeleteAnalysis.html
```
$ make testacc TESTS=TestAccQuickSightAnalysis PKG=quicksight
==> …
```
=> New resource aws_quicksight_analysis

internal/service/kendra/index_test.go, website/docs/r/kendra_index.html.markdown
A new `document_metadata_configuration_updates` was introduced called `_tenant_id` that broke 3 existing acceptance tests. This PR fixes it by adding the `_tenant_id` block to the test config, adjusting the counts of the tests accordingly, and checking for that block. Impacted tests:
- TestAccKendraIndex_basic
- TestAccKendraIndex_addDocumentMetadataConfigurationUpdates
- TestAccKendraIndex_inplaceUpdateDocumentMetadataConfigurationUpdates
```
$ make testacc TESTARGS='-run=TestAccKendraIndex_basic\|TestAccKendraIndex_addDocumentMetadataConfigurationUpdates\|TestAccKendraIndex_inplaceUpdateDocumentMetadataConfigurationUpdates' PKG=kendra
TF_ACC=1 go test ./internal/service/kendra/... -v -count 1 -parallel 20 …
```
=> b/aws_kendra_index-Fix Acceptance tests

GNUmakefile
Closes #0000
```console
% make clean
==> Cleaning Go...
WARNING: This will kill gopls and clean Go caches
ALERT: vscode is running. Close it and try again.
make: *** [cleango] Error 1
% make clean
==> Cleaning Go...
WARNING: This will kill gopls and clean Go caches
go install
go: downloading github.com/hashicorp/terraform-plugin-go v0.15.0
go: downloading github.com/hashicorp/go-cty v1.4.1-0.20200414143053-d3edf31b6320
go: downloading github.com/hashicorp/aws-sdk-go-base/v2 v2.0.0-beta.27
go: downloading github.com/hashicorp/aws-sdk-go-base/v2/awsv1shim/v2 v2.0.0-beta.28
go: downloading github.com/aws/aws-sdk-go-v2/feature/ec2/imds v1.13.3
go: downloading github.com/hashicorp/go-multierror v1.1.1
go: downloading …
```
=> make: Check for vscode in clean target

internal/service/elasticache/cluster_test.go
Removes unneeded `engine_version` from `aws_elasticache_cluster` acceptance tests
```
$ make testacc PKG=elasticache TESTS=TestAccElastiCacheCluster_
--- PASS: TestAccElastiCacheCluster_Engine_None (4.98s)
--- SKIP: TestAccElastiCacheCluster_outpost_memcached (0.99s)
--- SKIP: TestAccElastiCacheCluster_outpostID_redis (0.13s)
--- SKIP: TestAccElastiCacheCluster_outpostID_memcached (0.14s)
--- SKIP: TestAccElastiCacheCluster_outpost_redis (0.12s)
--- PASS: TestAccElastiCacheCluster_Memcached_finalSnapshot (6.59s)
--- PASS: TestAccElastiCacheCluster_AZMode_memcached (614.25s)
--- PASS: TestAccElastiCacheCluster_NumCacheNodes_redis (1.58s)
--- PASS: TestAccElastiCacheCluster_Engine_memcached (619.74s)
--- PASS: TestAccElastiCacheCluster_Engine_redis_v5 (632.44s)
--- PASS: …
```
=> Acceptance test cleanup

website/docs/r/lambda_permission.html.markdown
Adds a `replace_triggered_by` lifecycle configuration example, and clarifies the situations in which this might be required (specifically when `qualifier` is omitted).
Closes #20598
=> [Docs]: r/aws_lambda_permission: add lifecycle example

.changelog/31687.txt, internal/provider/tags_interceptor.go
`tags` can be `null` and used as placeholder values. These `null` values should be ignored when calculating values that should be applied
This may result in a crash if null tags are applied to a resource where other tags are computed.
Relates #31644
```console
$ make testacc TESTARGS='-run=TestAccVPC_ -short' PKG=vpc
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 20  -run=TestAccVPC_ -short -timeout 180m
vpc_test.go:969: skipping long-running test in short mode
vpc_test.go:996: skipping long-running test in short mode
vpc_test.go:1024: skipping long-running test in short mode
--- SKIP: TestAccVPC_IPAMIPv6 …
```
=> tags: ignore null config tags when tags are computed

website/docs/r/route53_health_check.html.markdown
This PR seeks to add some clarity around the `fqdn` argument of the `aws_route53_health_check` resource based on community feedback.
Closes #28337
- [SDK reference](https://docs.aws.amazon.com/sdk-for-go/api/service/route53/#HealthCheckConfig)
N/a, docs
=> Clarify description of the `fqdn` argument of `aws_route53_health_check`

website/docs/r/scheduler_schedule.html.markdown
This PR corrects the `schedule_expression` parameter in the examples in the `aws_scheduler_schedule` resource. The accepted units are plural (`minutes` | `hours` | `days`).
Closes #31471
https://docs.aws.amazon.com/scheduler/latest/UserGuide/schedule-types.html
N/a, docs
=> Fix example in `aws_scheduler_schedule`

.github/workflows/regressions.yml
This PR moves the regressions Slack notification workflow over to the official `slackapi` Action to comply with TSCCR.
Relates: https://github.com/hashicorp/security-tsccr/pull/454
Relates: #31014
- [GitHub Action repo](https://github.com/slackapi/slack-github-action)
- [Existing workflow using this Action](https://github.com/hashicorp/terraform-provider-aws/blob/main/.github/workflows/pull_request_feed.yml)
N/a, Actions
=> SEC-090 Compliance: Switch to official Slack notifier action for regressions 

website/docs/r/codedeploy_deployment_group.html.markdown
This PR aims to clarify that the `aws_codedeploy_deployment_group` resource's `load_balancer_info.target_group_pair_info.prod_traffic_route.listener_arns` argument may only contain one listener ARN.
Closes #31243
https://docs.aws.amazon.com/sdk-for-go/api/service/codedeploy/#TrafficRoute
>  // The Amazon Resource Name (ARN) of one listener. The listener identifies the
// route between a target group and a load balancer. This is an array of strings
// with a maximum size of one.
N/a, docs
=> Clarify `aws_codedeploy_deployment_group` argument requirements

website/docs/r/connect_instance_storage_config.html.markdown
Updating accepted values as the resource `aws_connect_instance_storage_config` accepts `ATTACHMENTS` and `CONTACT_EVALUATIONS` as argument for `resource_type` without error.
Tested creating this resource with both of these.
The AWS API doc includes these values as valid:
https://docs.aws.amazon.com/connect/latest/APIReference/API_AssociateInstanceStorageConfig.html#API_AssociateInstanceStorageConfig_RequestBody
=> Adding valid values for resource_type

website/docs/r/acm_certificate.html.markdown
The documentation state that `validation_method` is required in `aws_acm_certificate` resource.
The only method currently validated by the API are `EMAIL` and `DNS`, so people can have issue following the doc recommendation.
As the `validation_method` is currently optional, remove it from the resource fix the issue.
Closes #31425
[My answer and test done here](https://github.com/hashicorp/terraform-provider-aws/issues/31425#issuecomment-1551960350)
=> Doc : ACM certificate validation method optional

website/docs/r/cur_report_definition.html.markdown
Updated Cost and Usage Report (CUR) documentation because it is available for the Linked accounts.
https://aws.amazon.com/about-aws/whats-new/2020/12/cost-and-usage-report-now-available-to-member-linked-accounts/
=> fix: Update CUR documentation

.changelog/31716.txt, internal/service/connect/security_profile.go
Set `tags_all` correctly in state
Closes #31648
```console
$ make testacc PKG=connect TESTS="TestAccConnect_serial/SecurityProfile/tags"
TF_ACC=1 go test ./internal/service/connect/... -v -count 1 -parallel 20 -run='TestAccConnect_serial/SecurityProfile/tags'  -timeout 180m
--- PASS: TestAccConnect_serial (143.74s)
--- PASS: TestAccConnect_serial/SecurityProfile (143.74s)
--- PASS: TestAccConnect_serial/SecurityProfile/tags (143.74s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/connect	146.858s
```
=> r/aws_connect_security_profile: set correct tags in read

internal/acctest/acctest.go, internal/service/ec2/transitgateway_peering_attachment_accepter_test.go, internal/service/ec2/transitgateway_peering_attachment_test.go, internal/service/ec2/vpc_peering_connection_accepter_test.go, internal/service/route53/vpc_association_authorization_test.go, internal/service/route53/zone_association_test.go
Adds `aws_route53_zone_association` and `aws_route53_vpc_association_authorization` acceptance tests for cross account-and-region associations.
```
$ make testacc PKG=route53 TESTS='TestAccRoute53ZoneAssociation_|TestAccRoute53VPCAssociationAuthorization_'
--- PASS: TestAccRoute53VPCAssociationAuthorization_disappears (81.47s)
--- PASS: TestAccRoute53VPCAssociationAuthorization_concurrent (82.90s)
--- PASS: TestAccRoute53VPCAssociationAuthorization_basic (85.59s)
--- PASS: TestAccRoute53VPCAssociationAuthorization_crossRegion (86.71s)
--- PASS: TestAccRoute53ZoneAssociation_disappears (112.93s)
--- PASS: TestAccRoute53ZoneAssociation_basic (115.69s)
--- PASS: TestAccRoute53ZoneAssociation_crossAccount (118.89s)
--- PASS: TestAccRoute53ZoneAssociation_Disappears_zone (121.35s)
--- PASS: …
```
=> Adds cross account and region Route 53 VPC association tests

.changelog/31696.txt, internal/service/ecr/pull_through_cache_rule_data_source.go, internal/service/ecr/pull_through_cache_rule_data_source_test.go, internal/service/ecr/service_package_gen.go, website/docs/d/ecr_pull_through_cache_rule.html.markdown
Provides a new data source for the ECR Pull Through Cache Rule
Closes #31578
```
$ make testacc TESTARGS='-run=TestAccECRPullThroughCacheRuleDataSource_basic' PKG=ecr
TF_ACC=1 go test ./internal/service/ecr/... -v -count 1 -parallel 20  -run=TestAccECRPullThroughCacheRuleDataSource_basic -timeout 180m
=== RUN   TestAccECRPullThroughCacheRuleDataSource_basic
=== PAUSE TestAccECRPullThroughCacheRuleDataSource_basic
=== CONT  TestAccECRPullThroughCacheRuleDataSource_basic
--- PASS: TestAccECRPullThroughCacheRuleDataSource_basic (28.73s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/ecr        30.876s
```
=> New data source: aws_ecr_pull_through_cache_rule

.changelog/31499.txt, internal/service/fis/experiment_template.go, internal/service/fis/experiment_template_test.go, website/docs/r/fis_experiment_template.html.markdown
Adds EBS volumes as a target resource type for FIS experiment templates.
Closes #31470 
https://docs.aws.amazon.com/fis/latest/userguide/fis-actions-reference.html#ebs-actions-reference
```
$ make testacc TESTS=TestAccFISExperimentTemplate_ebs  PKG=fis                 
TF_ACC=1 go test ./internal/service/fis/... -v -count 1 -parallel 20 -run='TestAccFISExperimentTemplate_ebs'  -timeout 180m
=== RUN   TestAccFISExperimentTemplate_ebs
=== PAUSE TestAccFISExperimentTemplate_ebs
=== CONT  TestAccFISExperimentTemplate_ebs
--- PASS: TestAccFISExperimentTemplate_ebs (39.79s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/fis        43.594s
...
```
=> Add EBS Volumes as Target Resource for FIS experiment templates

.changelog/31541.txt, internal/service/networkfirewall/firewall_policy.go, internal/service/networkfirewall/firewall_policy_data_source.go, internal/service/networkfirewall/firewall_policy_test.go, website/docs/r/networkfirewall_firewall_policy.html.markdown
This adds the `stream_exception_policy` option to a Network Firewall policy, updates the existing Stateful Engine Options test, and also adds tests for when only one of the options is defined.
Closes https://github.com/hashicorp/terraform-provider-aws/issues/31539
API docs: https://docs.aws.amazon.com/network-firewall/latest/APIReference/API_StatefulEngineOptions.html
NB I've been using the parallelism flag because there's a quota of 20 policies per AWS account and I've already got one, hence 19.
```
$ make testacc TESTS=TestAccNetworkFirewallFirewallPolicy_.*tatefulEngine PKG=networkfirewall P=19
TF_ACC=1 go test ./internal/service/networkfirewall/... -v -count 1 -parallel 19 …
```
=> r/aws_networkfirewall_firewall_policy: Add stream exception policy

.changelog/31767.txt, internal/service/globalaccelerator/endpoint_group.go, internal/service/globalaccelerator/endpoint_group_test.go
Zero is a valid value for an endpoint group configuration and it shouldn't be ignored and not sent to the API.
The current behaviour causes a endpoint weight of 128 to be used instead as it is AWS default value if no weight is set. This causes traffic to be sent despite the expectations that a zero value will cause no traffic on the endpoint.
This Pull request fix the issue https://github.com/hashicorp/terraform-provider-aws/issues/31254 where a zero value for a global accelerator endpoint group configuration is ignored despite being a valid value.
Closes #31254
https://docs.aws.amazon.com/global-accelerator/latest/api/API_EndpointConfiguration.html
=> fix: ensure endpoint group weight 0 is taken into account

.changelog/31755.txt, internal/service/sagemaker/model.go, internal/service/sagemaker/model_test.go, website/docs/r/sagemaker_model.html.markdown
SageMaker `Model` object has support for passing a `ModelPackageName` to create models from model packages but this functionality was not implemented in the provider.
This PR adds this missing functionality.
Additionally, `image` is an optional argument for the `Containers` and `PrimaryContainer` structures.
Closes https://github.com/hashicorp/terraform-provider-aws/issues/23968.
Closes https://github.com/hashicorp/terraform-provider-aws/issues/31533.
Closes https://github.com/hashicorp/terraform-provider-aws/pull/31532.
Closes https://github.com/hashicorp/terraform-provider-aws/pull/24004.
^ This PR combines these PRs and addresses the contributor feedback. @bschaatsbergen 
https://docs.aws.amazon.com/sagemaker/latest/APIReference/API_CreateModel.html …
=> F/Add model_package_name for aws_sagemaker_model

internal/service/s3/bucket_logging_test.go, internal/service/s3/bucket_test.go
Closes #31771
```console
$ make testacc TESTS="TestAccS3BucketLogging_TargetGrantByID|TestAccS3BucketLogging_TargetGrantByGroup" PKG=s3
TF_ACC=1 go test ./internal/service/s3/... -v -count 1 -parallel 20 -run='TestAccS3BucketLogging_TargetGrantByID|TestAccS3BucketLogging_TargetGrantByGroup'  -timeout 180m
--- PASS: TestAccS3BucketLogging_TargetGrantByGroup (52.88s)
--- PASS: TestAccS3BucketLogging_TargetGrantByID (58.48s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/s3	61.745s
```
=> r/aws_s3_bucket_logging: fix test failures

website/docs/r/cognito_identity_pool.markdown
the format currently shown is for a user pool id, and it should be for an identity pool id
it looks like the existing ID for this documentation was copied from the page for user pool.
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cognito_user_pool
The format of the ID for identity pools is very difficult to track down anywhere, but the cloudformation docs seem to show it correctly
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cognito-identitypool.html
=> fix format for identity pool id

go.mod, go.sum, internal/conns/awsclient_gen.go, internal/conns/config_gen.go, internal/service/swf/domain.go, internal/service/swf/domain_test.go, internal/service/swf/exports_test.go, internal/service/swf/generate.go, internal/service/swf/service_package_gen.go, internal/service/swf/sweep.go, internal/service/swf/tags_gen.go, names/names.go, names/names_data.csv
Ibid.
```console
% SWF_DOMAIN_TESTING_ENABLED=true make testacc TESTARGS='-run=TestAccSWFDomain_' PKG=swf ACCTEST_PARALLELISM=2
TF_ACC=1 go test ./internal/service/swf/... -v -count 1 -parallel 2  -run=TestAccSWFDomain_ -timeout 180m
=== RUN   TestAccSWFDomain_basic
=== PAUSE TestAccSWFDomain_basic
=== RUN   TestAccSWFDomain_disappears
=== PAUSE TestAccSWFDomain_disappears
=== RUN   TestAccSWFDomain_nameGenerated
=== PAUSE TestAccSWFDomain_nameGenerated
=== RUN   TestAccSWFDomain_namePrefix
=== PAUSE TestAccSWFDomain_namePrefix
=== RUN   TestAccSWFDomain_tags
=== PAUSE TestAccSWFDomain_tags
=== RUN   TestAccSWFDomain_description
=== PAUSE TestAccSWFDomain_description
=== CONT  TestAccSWFDomain_basic
=== CONT …
```
=> Tech debt: Migrate `swf` resources to AWS SDK for Go v2

skaff/datasource/datasource.tmpl, skaff/datasource/datasourcetest.tmpl, skaff/resource/resource.tmpl, skaff/resource/resourcetest.tmpl
Updates `skaff` templates so that `diags` are collected rather than immediately returning. This ensures that if a Warning Diagnostic is added at some point, it will not get lost accidentally.
Also removes unneeded registration reminder and fixes spacing for data source imports
=> Updates `skaff` to collect `diags`

internal/service/guardduty/finding_ids_data_source.go, internal/service/guardduty/finding_ids_data_source_test.go, website/docs/d/guardduty_finding_ids.html.markdown
Adds a `has_findings` attribute. Omitting a changelog entry since the data source has not been released yet.
Relates #31711 
```console
$ make testacc PKG=guardduty TESTS=TestAccGuardDutyFindingIdsDataSource_basic
TF_ACC=1 go test ./internal/service/guardduty/... -v -count 1 -parallel 20 -run='TestAccGuardDutyFindingIdsDataSource_basic'  -timeout 180m
=== RUN   TestAccGuardDutyFindingIdsDataSource_basic
=== PAUSE TestAccGuardDutyFindingIdsDataSource_basic
=== CONT  TestAccGuardDutyFindingIdsDataSource_basic
--- PASS: TestAccGuardDutyFindingIdsDataSource_basic (15.33s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/guardduty  18.543s
```
=> d/aws_guardduty_finding_ids: add `has_findings` attribute

docs/skaff.md, docs/terraform-plugin-versions.md, mkdocs.yml
Adds a new page to the contributor documentation on Terraform plugin versions (Plugin-SDK versus Plugin-Framework), and documents `skaff` support for Plugin-Framework based resources.
Relates #30799
=> [Docs]: Terraform plugin versions and `skaff` Plugin-Framework support

.changelog/31772.txt, internal/service/redshift/cluster_data_source.go
Resolves https://github.com/hashicorp/terraform-provider-aws/issues/31407 as per suggested: https://github.com/hashicorp/terraform-provider-aws/issues/31407#issuecomment-1570495244
Resolves https://github.com/hashicorp/terraform-provider-aws/issues/31407
https://github.com/hashicorp/terraform-provider-aws/issues/31407#issuecomment-1570495244
I'll run the tests if required, but I don't see how this change will break existing functionality as it fixes a bug where terraform might crash, as per referenced issue. <insert "how did this not work"-imagery here>
=> fix(redshift): Nil-check before reading from Endpoint

.changelog/31691.txt, internal/service/budgets/budget_data_source.go, internal/service/budgets/budget_data_source_test.go, internal/service/budgets/service_package_gen.go, website/docs/d/budgets_budget.html.markdown
Add budget data source to resource budget
```
> make testacc TESTARGS='-run=TestAccBudgetsBudgetDataSource_basic' PKG=budgets
TF_ACC=1 go test ./internal/service/budgets/... -v -count 1 -parallel 20  -run=TestAccBudgetsBudgetDataSource_basic -timeout 180m
=== RUN   TestAccBudgetsBudgetDataSource_basic
=== PAUSE TestAccBudgetsBudgetDataSource_basic
=== CONT  TestAccBudgetsBudgetDataSource_basic
--- PASS: TestAccBudgetsBudgetDataSource_basic (12.34s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/budgets    15.523s
...
```
=> Add budget datasource to resource budget

.changelog/31800.txt, internal/service/ec2/ec2_spot_instance_request.go, internal/service/ec2/wait.go
Reverts the `aws_spot_instance_request` creation changes made in #31800.
Given the new `aws_instance.instance_market_options` configuration block introduced in #31495 and the documentation notes added in #31108, it is best not to overcomplicate the current implementation.
Relates https://github.com/hashicorp/terraform-provider-aws/issues/8164.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/8556.
```console
% make testacc TESTARGS='-run=TestAccEC2SpotInstanceRequest_' PKG=ec2 ACCTEST_PARALLELISM=2
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 2  -run=TestAccEC2SpotInstanceRequest_ -timeout 180m
=== RUN   TestAccEC2SpotInstanceRequest_basic
=== PAUSE TestAccEC2SpotInstanceRequest_basic
=== RUN …
```
=> Revert #31800

internal/conns/awsclient.go, internal/conns/awsclient_gen.go, internal/conns/config.go, internal/generate/awsclient/file.tmpl, internal/service/s3/bucket.go, internal/service/s3/bucket_test.go, internal/service/s3/sweep.go
Remove the `s3ConnURICleaningDisabled` field from `conns.AWSClient`, instead creating a new customized S3 API client every time `S3ConnURICleaningDisabled()` is called.
```console
% make testacc TESTARGS='-run=TestAccS3Bucket_Basic_forceDestroy' PKG=s3
TF_ACC=1 go test ./internal/service/s3/... -v -count 1 -parallel 20  -run=TestAccS3Bucket_Basic_forceDestroy -timeout 180m
=== RUN   TestAccS3Bucket_Basic_forceDestroy
=== PAUSE TestAccS3Bucket_Basic_forceDestroy
=== RUN   TestAccS3Bucket_Basic_forceDestroyWithEmptyPrefixes
=== PAUSE TestAccS3Bucket_Basic_forceDestroyWithEmptyPrefixes
=== RUN   TestAccS3Bucket_Basic_forceDestroyWithObjectLockEnabled
=== PAUSE TestAccS3Bucket_Basic_forceDestroyWithObjectLockEnabled
=== CONT …
```
=> Tech debt: Remove `AWSClient.s3ConnURICleaningDisabled`

skaff/datasource/websitedoc.tmpl, skaff/resource/websitedoc.tmpl
Adding a short list of writing tips to the beginning of each of the skag documentation templates for `Resource` and `Data Source`.  I used `TIP` to indicate that these lists should be deleted after folks have written their docs. 
None. 
I tried to distill our [Engineering Style Guide](https://github.com/hashicorp/engineering-docs/blob/main/writing/style-guide.md) into as few points as I could.
=> Add writing guidance to the top of each documentation template

.changelog/31833.txt, internal/service/mwaa/environment.go, internal/service/mwaa/environment_test.go
MWAA now supports in-place version upgrades. 
In a successful MWAA version upgrade scenario, the status will show UPDATING, then CREATING_SNAPSHOT as Amazon MWAA captures a backup of metadata. Finally, the status will return first to UPDATING, then to AVAILABLE when the procedure is done.
This PR adds CREATING_SNAPSHOT status as a valid status along with UPDATING status when waiting for MWAA upgrade
Closes #31825.
Closes https://github.com/hashicorp/terraform-provider-aws/issues/21640.
https://aws.amazon.com/blogs/big-data/introducing-in-place-version-upgrades-with-amazon-mwaa/
https://docs.aws.amazon.com/mwaa/latest/userguide/upgrading-environment.html
=> Add CREATING_SNAPSHOT status while waiting for MWAA version upgrade

website/docs/d/db_instance.html.markdown
Update `aws_db_instance` data source to clarify the difference between `db_instance_port` and `port`.
Closes #31441
N/A
N/A
=> Clarify the difference between db_instance_port and port in aws_db_instance

.github/workflows/project-partner-label.yml
This PR updates the workflow that adds items labeled `partner` to the Partner working board such that the ID used for the GraphQL mutation is the `next_global_id` rather than the `legacy_global_id`, as requested by the response from the API (linked Action run output below).
Relates #31793 - The workflows updated in that PR will need a subsequent update similar to this, but oddly enough, it doesn't appear that you can get the `next_global_id` from anything but a mutation response, so we'll need to follow up and check the logs once those workflows run to get that value.
[Action log output](https://github.com/hashicorp/terraform-provider-aws/actions/runs/5200588589/jobs/9379510726) - This job completed successfully, but threw the warn message that alerted me to the change.
n/a, Actions
=> Update Workflow to use `next_global_id` rather than `legacy_global_id`

.github/workflows/reusable-add-or-remove-labels.yml
When creating this reusable workflow, I assumed that checking the `event_type` to see if the event was related to an issue would work well enough for distinguishing between issues and PRs. I failed to account for `issue_comment` triggers, which [are triggered](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#issue_comment) for both issues _and_ pull requests with an event type of `issue_comment`, bypassing the previous test. This led to failures, as seen in the references section.
Relates #31750
- [Failed run due to not accounting for this](https://github.com/hashicorp/terraform-provider-aws/actions/runs/5215614719/jobs/9413376735)
- [GitHub recommendation on a similar approach](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows …
=> Ensure `issue_comment` triggers are correctly evaluated

website/docs/d/iam_role.html.markdown
Updates the `role_last_used` attribute documentation to match the schema.
https://github.com/hashicorp/terraform-provider-aws/blob/ecb45d645b3b2897504007540e9e480402eeee03/internal/service/iam/role_data_source.go#L55-L70
=> [Docs]: d/aws_iam_role: Fix `role_last_used` attribute reference

website/docs/r/sesv2_email_identity.html.markdown
The description for the `tags` argument of `aws_sesv2_email_identity` was previously listed under Attributes, making it less obvious that these could be defined as arguments. This PR moves the `tags` documentation up to Arguments.
Closes #30215
N/a
N/a, docs
=> Move `tags` documentation in `aws_sesv2_email_identity`

website/docs/r/eks_node_group.html.markdown
On Kubernetes version `1.18` and earlier, subnets specified for EKS node groups had a tag of `kubernetes.io/cluster/my-cluster` automatically applied, which was noted as a required tag on subnets specified in `aws_eks_node_group.subnet_ids`. This is no longer a requirement, and the versions of Kubernetes that required this are no longer supported by AWS. As such, this PR removes this note from the documentation.
Closes #31704
- [Amazon EKS VPC and subnet requirements and considerations](https://docs.aws.amazon.com/eks/latest/userguide/network_reqs.html#network-requirements-subnets)
- [Amazon EKS Kubernetes versions](https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html)
N/a, docs
=> Remove reference to previously required tag on `aws_eks_node_group.subnet_ids`

website/docs/r/fsx_ontap_volume.html.markdown
This PR corrects the documentation of `aws_fsx_ontap_volume`, where `tiering_policy.cooling_period` was incorrectly listed as `tiering_policy.cooling_policy`.
Closes #31862
[Schema](https://github.com/hashicorp/terraform-provider-aws/blob/ecb45d645b3b2897504007540e9e480402eeee03/internal/service/fsx/ontap_volume.go#L110)
N/a, docs
=> Correct argument name in `aws_fsx_ontap_volume`

website/docs/r/db_event_subscription.html.markdown
This PR adds `db-proxy` to the list of documented valid values for `aws_db_event_subscription.source_type`.
Closes #31865
[`CreateEventSubscription` API documentation](https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_CreateEventSubscription.html#API_CreateEventSubscription_RequestParameters)
N/a, docs
=> Add `db-proxy` to list of `aws_db_event_subscription.source_type` valid values

.changelog/31886.txt, internal/service/redshift/cluster.go, internal/service/redshift/cluster_test.go
Allow `availability_zone_relocation_enabled` to be true when `publicly_accessible` is true.
Fixes #31446
```
make testacc TESTS=TestAccRedshiftCluster_availabilityZoneRelocation PKG=redshift
TF_ACC=1 go test ./internal/service/redshift/... -v -count 1 -parallel 20 -run='TestAccRedshiftCluster_availabilityZoneRelocation'  -timeout 180m
=== RUN   TestAccRedshiftCluster_availabilityZoneRelocation
=== PAUSE TestAccRedshiftCluster_availabilityZoneRelocation
=== RUN   TestAccRedshiftCluster_availabilityZoneRelocation_publiclyAccessible
=== PAUSE TestAccRedshiftCluster_availabilityZoneRelocation_publiclyAccessible
=== CONT  TestAccRedshiftCluster_availabilityZoneRelocation
=== CONT …
```
=> fix: Redshift cluster relocation enabled and publicly accessible can both be true

.changelog/31877.txt, internal/service/ec2/vpc_.go, internal/service/ec2/vpc_test.go
We run Terraform in CI/CD and there appears to be a race condition in VPC creation. While the provider correctly waits up to 2 minutes for the VPC to be created and return an existant resource, the VPC attributes are assumed to return successfully. I regularly see the following output when creating VPCs:
```
Error: reading EC2 VPC (vpc-abc123) Attribute (enableDnsSupport): couldn't find resource
```
Re-attempting the Terraform run fixes the issue, but this is suboptimal. This PR treats the VPC attributes to the same retry logic as the VPC reading.
```
make testacc TESTS=TestAccVPC_ PKG=ec2                     SIGINT(2) ↵  5315  13:46:28 
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 20 -run='TestAccVPC_' …
```
=> ec2: fix unretriable error when creating vpc, while reading vpc attributes

.github/workflows/pull_request_feed.yml, .github/workflows/pull_requests.yml
Reusable workflows can only be used at the job level, not in steps within a job. This PR moves the partner labeler to a distinct job so that it can properly use the reusable flow to add the label.
- [Failed step from a previous job](https://github.com/hashicorp/terraform-provider-aws/actions/runs/5230914202/jobs/9444743245)
- [GitHub Actions documentation](https://docs.github.com/en/actions/using-workflows/reusing-workflows#limitations):
> **Reusable workflows are called directly within a job, and not from within a job step.** You cannot, therefore, use GITHUB_ENV to pass values to job steps in the caller workflow.
N/a, Actions
=> Move partner labeler to a distinct job

internal/service/cloudwatch/metric_stream_test.go, internal/service/connect/instance_storage_config_data_source_test.go, internal/service/connect/instance_storage_config_test.go, internal/service/logs/README.md, internal/service/logs/data_protection_policy_document_data_source_test.go, internal/service/networkfirewall/logging_configuration_test.go, internal/service/ses/event_destination_test.go, internal/service/sesv2/configuration_set_event_destination_test.go, internal/service/sns/topic_subscription_test.go, internal/service/waf/web_acl_test.go, internal/service/wafregional/web_acl_test.go, website/docs/d/redshift_cluster.html.markdown, website/docs/r/cloudwatch_metric_stream.html.markdown, website/docs/r/msk_cluster.html.markdown
v5.0 of the AWS Provider removes the parameter `s3_configuration` from `aws_kinesis_firehose_delivery_stream` in favour of `extended_s3_configuration`
```
$ make testacc PKG=cloudwatch TESTS=TestAccCloudWatchMetricStream_
--- PASS: TestAccCloudWatchMetricStream_includeFilters (26.96s)
--- PASS: TestAccCloudWatchMetricStream_includeFiltersWithMetricNames (27.53s)
--- PASS: TestAccCloudWatchMetricStream_excludeFiltersWithMetricNames (27.71s)
--- PASS: TestAccCloudWatchMetricStream_excludeFilters (28.29s)
--- PASS: TestAccCloudWatchMetricStream_additional_statistics (69.05s)
--- PASS: TestAccCloudWatchMetricStream_update (77.07s)
--- PASS: TestAccCloudWatchMetricStream_includeLinkedAccountsMetrics (344.80s)
--- PASS: TestAccCloudWatchMetricStream_nameGenerated (375.81s)
--- PASS: …
```
=> Update acceptance tests and documentation for removal of `aws_kinesis_firehose_delivery_stream` `s3_configuration`

.changelog/31264.txt, internal/service/elasticache/engine_version.go, internal/service/elasticache/engine_version_test.go, internal/service/elasticache/replication_group_test.go, website/docs/r/elasticache_cluster.html.markdown, website/docs/r/elasticache_global_replication_group.html.markdown, website/docs/r/elasticache_replication_group.html.markdown
Support 7+ versions of AWS elasticache redis which require `engine_version` values which do not support the `.x` syntax introduced in version 6 (e.g. `6.x`). Details are in the issue discussion linked below.
Closes #27918
=> [Enhancement]: aws elasticache redis - support redis v7

.changelog/31863.txt, internal/service/quicksight/data_set.go, internal/service/quicksight/data_set_test.go
Currently, the schema for the `aws_quicksight_data_set` resource marks the `physical_table_map` field as `Required`. 
However, the AWS API makes clear that while required, the map it represents may contain zero entries:
```
PhysicalTableMap
Declares the physical tables that are available in the underlying data sources.
Type: String to PhysicalTable object map
Map Entries: Minimum number of 0 items. Maximum number of 32 items.
Key Length Constraints: Minimum length of 1. Maximum length of 64.
Key Pattern: [0-9a-zA-Z-]*
Required: Yes
```
[Source](https://docs.aws.amazon.com/quicksight/latest/APIReference/API_CreateDataSet.html#API_CreateDataSet_RequestSyntax)
The present schema definition of `Required` therefore makes it impossible to specify an empty map. 
This PR fixes this by updating …
=> `r/aws_quicksight_data_set`: Allow physical_table_map to be optional

website/docs/r/vpc_peering_connection_options.html.markdown
Due to manual line breaks introducing a space between the `]` and `(`, the links in the `aws_vpc_peering_connection_options` document were incorrectly formatted. This PR corrects that.
These links will obviously not really help once the PR is merged, but for the sake of quickly visualizing the issue:
- [`accepter`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/vpc_peering_connection_options#accepter)
- [`requester`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/vpc_peering_connection_options#requester)
N/a, docs
=> Correct links within `aws_vpc_peering_connection_options` documentation

.changelog/31926.txt, internal/service/glue/data_quality_ruleset.go, internal/service/glue/data_quality_ruleset_test.go, website/docs/r/glue_data_quality_ruleset.html.markdown
The AWS GO SDK released support for `catalog_id` in `target_table` [here](https://docs.aws.amazon.com/sdk-for-go/api/service/glue/#DataQualityTargetTable). Feature request: add this optional argument to the resource.
Closes #31925
Relates #31604
* [AWS GO SDK - Glue DataQualityTargetTable](https://docs.aws.amazon.com/sdk-for-go/api/service/glue/#DataQualityTargetTable)
```
$ make testacc TESTARGS='-run=TestAccGlueDataQualityRuleset' PKG=glue
TF_ACC=1 go test ./internal/service/glue/... -v -count 1 -parallel 20  -run=TestAccGlueDataQualityRuleset -timeout 180m
=== RUN   TestAccGlueDataQualityRuleset_basic
=== PAUSE TestAccGlueDataQualityRuleset_basic
=== RUN   TestAccGlueDataQualityRuleset_updateRuleset
=== PAUSE …
```
=> r/aws_glue_data_quality_ruleset - support `target_table` `catalog_id`

website/docs/r/eks_node_group.html.markdown
This PR updates the `aws_eks_node_group` documentation to take care of two tasks:
1. Add the `update_config` argument, which was missing (though arguments of the block were present)
2. Add links to a few of the configuration block references, rather than having them only mentioned as "Detailed below"
Closes #30368
- [AWS API documentation for `CreateNodegroup`](https://docs.aws.amazon.com/eks/latest/APIReference/API_CreateNodegroup.html) - reference for the `update_config` argument definition.
N/a, docs
=> Update `aws_eks_node_group` documentation, add `update_config` argument

internal/service/apigatewayv2/wait.go, internal/service/ec2/vpc_dhcp_options.go, internal/service/ec2/vpc_network_acl_association.go, internal/service/mq/forge.go, internal/service/networkmanager/connect_peer.go, internal/service/opensearch/domain.go
fix function name in comment
Closes #0000
```
...
```
=> fix function name in comment

.changelog/31933.txt, internal/service/lambda/provisioned_concurrency_config.go, internal/service/lambda/provisioned_concurrency_config_migrate.go, internal/service/lambda/provisioned_concurrency_config_test.go, website/docs/r/lambda_provisioned_concurrency_config.html.markdown
Updates the resource `id` to a comma-separated string, joining `function_name` and `qualifier`. This allows the `function_name` argument to reliably accept ARN values which previously caused Read operations to fail, and migrates this resource to the preferred ID separator.
Fixes #11152
Fixes #12923
Fixes #22392
Closes #19868
Closes #11679
Closes #22808
Relates #27843
```console
$ make testacc PKG=lambda TESTS=TestAccLambdaProvisionedConcurrencyConfig_
TF_ACC=1 go test ./internal/service/lambda/... -v -count 1 -parallel 20 -run='TestAccLambdaProvisionedConcurrencyConfig_'  -timeout 180m
--- PASS: TestAccLambdaProvisionedConcurrencyConfig_Qualifier_aliasName (190.12s)
--- PASS: …
```
=> r/aws_lambda_provisioned_concurrency_config: Use comma-delimited `id`

website/docs/r/finspace_kx_cluster.html.markdown
Minor update to finspace_kx_cluster documentation. This resource no longer takes a port as an optional parameter and the parameter was removed from the documentation earlier but hasn't yet been updated in the description for the larger capacity_configuration construct.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/31806
AWS user guide documentation for finspace kx cluster: https://docs.aws.amazon.com/finspace/latest/userguide/create-kdb-clusters.html
=> docs: Quick fix to finspace_kx_cluster documentation

website/docs/r/glue_crawler.html.markdown
There is a description section for the `delta_target` block, but the description of the `delta_traget` argument at the root level is missing.
=> docs: Update description for missing delta_target argument

website/docs/r/codebuild_project.html.markdown
the current documentation shows an image that doesn't exist anymore (standard:1.0), and so we should use the most up-to-date image for Amazon Linux2.
https://docs.aws.amazon.com/codebuild/latest/userguide/build-env-ref-available.html
=> update example with up to date image

website/docs/r/appflow_flow.html.markdown
This PR updates the example within the `aws_appflow_flow` documentation, which had the following issues:
- `aws_s3_bucket.example_source` had a `bucket` argument of `example_source`, while S3 bucket naming conventions do not allow underscores.
- `aws_s3_bucket.example_destination` had a `bucket` argument of `example_destination`, while S3 bucket naming conventions do not allow underscores.
- `aws_iam_policy_document.example_destination` was missing the top-level `statement` block that contains the other arguments.
Closes #29878
- [S3 bucket naming rules](https://docs.aws.amazon.com/AmazonS3/latest/userguide/bucketnamingrules.html)
- [`aws_iam_policy_document` data source reference](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/iam_policy_document)
N/a, …
=> Correct example on `aws_appflow_flow`

website/docs/index.html.markdown
As of `v5.0.0`, the `shared_credentials_file` argument was removed from the provider configuration. This PR removes the last dangling reference to this argument from the provider docs.
Closes #31975
N/a, docs
=> Remove final reference to `shared_credential_file` from provider configuration docs

.changelog/32016.txt, internal/service/ec2/ec2_eip.go
No retry logic on this resource results in sometimes intermittent errored runs.
Closes https://github.com/hashicorp/terraform-provider-aws/issues/29604.
```
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 20 -run='TestAccEC2EIP_'  -timeout 180m
=== RUN   TestAccEC2EIP_basic
=== PAUSE TestAccEC2EIP_basic
=== RUN   TestAccEC2EIP_disappears
=== PAUSE TestAccEC2EIP_disappears
=== RUN   TestAccEC2EIP_migrateVPCToDomain
=== PAUSE TestAccEC2EIP_migrateVPCToDomain
=== RUN   TestAccEC2EIP_noVPC
=== PAUSE TestAccEC2EIP_noVPC
=== RUN   TestAccEC2EIP_tags
=== PAUSE TestAccEC2EIP_tags
=== RUN   TestAccEC2EIP_instance
=== PAUSE TestAccEC2EIP_instance
=== RUN   TestAccEC2EIP_Instance_reassociate
=== PAUSE …
```
=> r/aws_eip: use retry logic when creating new resources

.changelog/32023.txt, internal/service/networkmanager/attachment_accepter.go, internal/service/networkmanager/transit_gateway_peering_test.go, internal/service/networkmanager/transit_gateway_route_table_attachment.go, internal/service/networkmanager/transit_gateway_route_table_attachment_test.go, website/docs/r/networkmanager_attachment_accepter.html.markdown
Adding the ability to accept Transit Gateway Route Table attachments in the `aws_networkmanager_attachment_accepter` resource. Currently, when trying to accept a Transit Gateway Route Table attachment, the following error is thrown:
`Error: expected attachment_type to be one of [VPC SITE_TO_SITE_VPN CONNECT], got TRANSIT_GATEWAY_ROUTE_TABLE`
Closes #26420 (note: I'm closing this issues since this appears to be the only remaining type not supported by the accepter)
https://docs.aws.amazon.com/networkmanager/latest/APIReference/API_ListAttachments.html#API_ListAttachments_RequestSyntax
https://github.com/aws/aws-sdk-go/blob/main/service/networkmanager/api.go#L23525
**Note to admins/maintainers: I need help with testing this PR.**
```
$ make testacc TESTS=TestAccXXX PKG=networkmanager
... …
```
=> [Enhancement]: add tgw route table in aws_networkmanager_attachment_accepter ✨

.changelog/32067.txt, internal/service/redshiftserverless/find.go, internal/service/redshiftserverless/status.go, internal/service/redshiftserverless/wait.go, internal/service/redshiftserverless/workgroup.go
Adds `AVAILABLE` as a valid pending state during resource deletion.
Closes https://github.com/hashicorp/terraform-provider-aws/issues/29962.
```console
% make testacc TESTARGS='-run=TestAccRedshiftServerlessWorkgroup_basic' PKG=redshiftserverless
TF_ACC=1 go test ./internal/service/redshiftserverless/... -v -count 1 -parallel 20  -run=TestAccRedshiftServerlessWorkgroup_basic -timeout 180m
=== RUN   TestAccRedshiftServerlessWorkgroup_basic
=== PAUSE TestAccRedshiftServerlessWorkgroup_basic
=== CONT  TestAccRedshiftServerlessWorkgroup_basic
--- PASS: TestAccRedshiftServerlessWorkgroup_basic (675.04s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/redshiftserverless	680.810s
```
=> r/aws_redshiftserverless_workgroup: Workgroup may be `AVAILABLE` when deletion starts

.changelog/31903.txt, internal/service/quicksight/schema/template_filter.go, internal/service/quicksight/schema/visual_actions.go
Fixes #31903
```
$make testacc PKG=quicksight TESTS=TestAccQuickSightTemplate
TF_ACC=1 go test ./internal/service/quicksight/... -v -count 1 -parallel 20 -run='TestAccQuickSightTemplate'  -timeout 180m
?   	github.com/hashicorp/terraform-provider-aws/internal/service/quicksight/schema	[no test files]
=== RUN   TestAccQuickSightTemplateAlias_basic
=== PAUSE TestAccQuickSightTemplateAlias_basic
=== RUN   TestAccQuickSightTemplateAlias_disappears
=== PAUSE TestAccQuickSightTemplateAlias_disappears
=== RUN   TestAccQuickSightTemplate_basic
=== PAUSE TestAccQuickSightTemplate_basic
=== RUN   TestAccQuickSightTemplate_disappears
=== PAUSE TestAccQuickSightTemplate_disappears
=== RUN   TestAccQuickSightTemplate_barChart
=== PAUSE …
```
=> `r/aws_quicksight_analysis`: Fix schema mapping for string set elements

website/docs/r/eks_addon.html.markdown
Closes None
- Adds missing `PRESERVE` value to list of acceptable values for `resolve_conflicts_on_update` argument 
- Removes note regarding 1.18 clusters - no longer relevant since [minimum supported version in EKS is currently 1.23](https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html#kubernetes-release-calendar)
- Updates version of CoreDNS addon used to reflect more current version as well as the example of upgrading addons to newer versions https://docs.aws.amazon.com/eks/latest/userguide/managing-coredns.html
```
...
```
=> docs: Correct documentation for EKS add-on supported values

website/docs/r/s3_bucket_notification.html.markdown
This PR adds an EventBridge example to S3 Bucket Notification docs and explicitly indicates the default value and type of the `eventbridge` argument. This was previously unclear as to what the type of this argument was and whether it followed the the same pattern as existing other nested argument object types.
Closes #25118
N/A
=> Add EventBridge example to S3 Bucket Notification docs

.ci/.semgrep.yml, internal/service/apigateway/stage.go, internal/service/emr/cluster.go, internal/service/emr/instance_fleet.go, internal/service/glue/dev_endpoint.go, internal/service/glue/workflow.go
The `Elem` field must be a `*Schema` type for `TypeMap` arguments. Fixes various cases where `Elem` was incorrectly set directly to `TypeString`.
```console
$ rg "Elem:[ ]*schema.Type"
internal/service/apigateway/stage.go
95:                                                     Elem:     schema.TypeString,
internal/service/emr/instance_fleet.go
82:                                                                             Elem:     schema.TypeString,
internal/service/emr/cluster.go
624:                                                                            Elem:     schema.TypeString,
internal/service/glue/workflow.go
45:                             Elem:     schema.TypeString,
internal/service/glue/dev_endpoint.go
46:                             Elem:     schema.TypeString,
```
No …
=> [Bug]: Fix map arguments with incorrect `Elem` types

.changelog/32070.txt, internal/service/chimesdkvoice/service_package_gen.go, internal/service/chimesdkvoice/sip_media_application_test.go, internal/service/chimesdkvoice/sip_rule.go, internal/service/chimesdkvoice/sip_rule_test.go, website/docs/r/chimesdkvoice_sip_rule.html.markdown
Adding support for ChimeSDKVoice Sip Rule
Closes #32069
https://docs.aws.amazon.com/chime-sdk/latest/APIReference/API_voice-chime_CreateSipRule.html
```
$  export AWS_DEFAULT_REGION="us-east-1" && make testacc TESTS=TestAccChimeSDKVoiceSip PKG=chimesdkvoice
TF_ACC=1 go test ./internal/service/chimesdkvoice/... -v -count 1 -parallel 20 -run='TestAccChimeSDKVoiceSip'  -timeout 180m
=== RUN   TestAccChimeSDKVoiceSipMediaApplication_basic
=== PAUSE TestAccChimeSDKVoiceSipMediaApplication_basic
=== RUN   TestAccChimeSDKVoiceSipMediaApplication_disappears
=== PAUSE TestAccChimeSDKVoiceSipMediaApplication_disappears
=== RUN   TestAccChimeSDKVoiceSipMediaApplication_update
=== PAUSE TestAccChimeSDKVoiceSipMediaApplication_update
=== RUN …
```
=> Adding support for ChimeSDKVoice Sip Rule

internal/experimental/nullable/bool.go, internal/experimental/nullable/bool_test.go, internal/experimental/nullable/float_test.go, internal/experimental/nullable/int_test.go, internal/experimental/nullable/testing.go
The parsing rules for `TypeNullableBool` currently allow `0` and `1` as valid values, matching behaviour of very old versions of Terraform. This PR deprecates this behaviour and return a warning in the validation function.
Note: The ideal solution is to update the resources to use `terraform-plugin-framework` instead of `terraform-plugin-sdk/v2`. `terraform-plugin-framework` allows typed nullable values.
The parsing behaviour will be removed by #29379.
Closes #29378
```
$ go test ./internal/experimental/nullable/... -v
--- PASS: TestNullableBool (0.00s)
--- PASS: TestNullableFloat (0.00s)
--- PASS: TestDiffSuppressBoolFalseAsNull (0.00s)
--- PASS: TestDiffSuppressBool (0.00s)
--- PASS: TestValidationBool (0.00s)
--- PASS: TestValidationFloat (0.00s)
--- PASS: TestNullableInt (0.00s)
--- …
```
=> Deprecate "legacy" behaviour when parsing nullable Bool values

infrastructure/repository/community.tf, infrastructure/repository/projects.tf
This PR adds infrastructure to help with automating new GitHub Projects, specifically when using the reusable workflow from the linked PR.
With this PR, variables are added such that workflows can access IDs more easily. For the "Status" field's values, the variables added follow the format of `vars.team_project_status_${option_name_snake_case}`, for example "To Do" is `vars.team_project_status_to_do`.
Relates #31880
Before #31883
[`github_actions_variable` resource documentation](https://registry.terraform.io/providers/integrations/github/latest/docs/resources/actions_variable)
N/a, repo infrastructure
=> Add infrastructure to help automate new Projects

.github/workflows/reusable-team-project.yml
Since the newly added reusable workflow for automating the team project did not wrap the IDs of the project, field in quotes, it caused failures. This PR switches to interpolating them so that they may be passed as quote-wrapped strings.
- [Failed run](https://github.com/hashicorp/terraform-provider-aws/actions/runs/5335208853/jobs/9668107745)
N/a, workflow
=> Fix string values in reusable team project automation

go.mod, go.sum, internal/acctest/acctest.go, internal/conns/awsclient_gen.go, internal/service/pricing/product_data_source.go, internal/service/pricing/product_data_source_test.go, internal/service/pricing/service_package_gen.go, names/names.go, names/names_data.csv
Ibid.
```console
% AWS_DEFAULT_REGION=us-east-1 make testacc TESTARGS='-run=TestAccPricingProductDataSource_' PKG=pricing 
TF_ACC=1 go test ./internal/service/pricing/... -v -count 1 -parallel 20  -run=TestAccPricingProductDataSource_ -timeout 180m
=== RUN   TestAccPricingProductDataSource_ec2
=== PAUSE TestAccPricingProductDataSource_ec2
=== RUN   TestAccPricingProductDataSource_redshift
=== PAUSE TestAccPricingProductDataSource_redshift
=== CONT  TestAccPricingProductDataSource_ec2
=== CONT  TestAccPricingProductDataSource_redshift
--- PASS: TestAccPricingProductDataSource_redshift (15.65s)
--- PASS: TestAccPricingProductDataSource_ec2 (15.72s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/pricing …
```
=> Tech debt: Migrate `pricing` resources to AWS SDK for Go v2 

internal/framework/types/timestamp_type.go, internal/framework/types/timestamp_type_test.go, internal/framework/types/timestamp_value.go, internal/framework/types/timestamp_value_test.go
Adds `TimestampType` and `TimestampValue` for Framework RFC 3339 custom type
```
$ go test ./internal/framework/types/... -v -run=TestTimestamp
--- PASS: TestTimestampValueIsNull (0.00s)
--- PASS: TestTimestampValueIsNull/unknown (0.00s)
--- PASS: TestTimestampValueIsNull/known (0.00s)
--- PASS: TestTimestampValueIsNull/null (0.00s)
--- PASS: TestTimestampValueToStringValue (0.00s)
--- PASS: TestTimestampValueToStringValue/unknown (0.00s)
--- PASS: TestTimestampValueToStringValue/value (0.00s)
--- PASS: TestTimestampValueToStringValue/null (0.00s)
--- PASS: TestTimestampValueToTerraformValue (0.00s)
--- PASS: TestTimestampValueToTerraformValue/value (0.00s)
--- PASS: TestTimestampValueToTerraformValue/null (0.00s)
--- PASS: TestTimestampValueToTerraformValue/unknown (0.00s)
--- PASS: …
```
=> Add Timestamp type for Framework

.github/workflows/community-check.yml
A recent change to the community check reusable workflow that was intended to eliminate false positives (see linked issue) introduced a bug that made it so every check evaluated to `false` every time. This PR fixes that bug so that the evaluations are correct.
Relates #32139
**Note:** I created two local files to test this locally with `nektos/act`. So as not to expose anything, I'm omitting these files, but will look into creating files that we can actually use to test this locally more reliably. The files contained:
`prt.json`:
```json
{
"pull_request": {
"user": {
"login": "justinretzolk"
}
}
}
```
`my.secrets`:
```plaintext
CORE_CONTRIBUTORS=
MAINTAINERS=
PARTNERS=
```
```shell
➜ act pull_request_target --secret-file my.secrets -e prt.json -j community_check -W …
```
=> Fix community check reusable workflow

website/docs/r/lb_target_group_attachment.html.markdown
Cleans up argument references and examples.
N/a Docs.
=> [Docs]: r/aws_lb_target_group_attachment: Tidy argument reference, examples

.changelog/32169.txt, internal/service/apigateway/rest_api.go
Crash on resource
Closes #31827
```console
$ make testacc TESTARGS='-run=TestAccAPIGatewayRestAPI_' PKG=apigateway
TF_ACC=1 go test ./internal/service/apigateway/... -v -count 1 -parallel 20  -run=TestAccAPIGatewayRestAPI_ -timeout 180m
--- PASS: TestAccAPIGatewayRestAPI_basic (32.63s)
--- PASS: TestAccAPIGatewayRestAPI_Policy_basic (70.20s)
--- PASS: TestAccAPIGatewayRestAPI_Policy_setByBody (139.79s)
--- PASS: TestAccAPIGatewayRestAPI_Policy_overrideBody (216.69s)
--- PASS: TestAccAPIGatewayRestAPI_MinimumCompressionSize_setByBody (246.42s)
--- PASS: TestAccAPIGatewayRestAPI_EndpointVPCEndpointIDs_setByBody (258.52s)
--- PASS: TestAccAPIGatewayRestAPI_Policy_order (22.00s)
--- PASS: TestAccAPIGatewayRestAPI_FailOnWarnings …
```
=> aws_api_gateway_rest_api: fix crash on `binary_media_types` attribute

.changelog/32108.txt, .ci/providerlint/go.mod, .ci/tools/go.mod, .github/workflows/golangci-lint.yml, go.mod, internal/service/elb/load_balancer_test.go, internal/service/route53/record.go, internal/service/route53/wait.go, internal/service/route53/zone.go, skaff/go.mod, tools/tfsdk2fw/go.mod
Updates `go.mod` to Go `1.20`. Also replaces package-scoped calls to `rand.Seed()` with randomized values, as Go 1.20 now seeds the global number generator in `math/rand` with a randomized value by default. From the [1.20 release notes](https://tip.golang.org/doc/go1.20):
> The [math/rand](https://tip.golang.org/pkg/math/rand/) package now automatically seeds the global random number generator (used by top-level functions like Float64 and Int) with a random value, and the top-level Seed function has been deprecated. Programs that need a reproducible sequence of random numbers should prefer to allocate their own random source, using rand.New(rand.NewSource(seed)).
Relates #32082 (see [failed checks](https://github.com/hashicorp/terraform-provider-aws/actions/runs/5308865624/jobs/9608821669? …
=> bump go.mod to 1.20

.changelog/32171.txt, internal/service/storagegateway/smb_file_share.go, internal/service/storagegateway/smb_file_share_test.go
Resolve error during an update when `kms_encrypted` is `true` but `kms_key_arn` is not sent in the request.
Closes #20766
```console
$ make testacc TESTARGS='-run=TestAccStorageGatewaySMBFileShare_' PKG=storagegateway
TF_ACC=1 go test ./internal/service/storagegateway/... -v -count 1 -parallel 20  -run=TestAccStorageGatewaySMBFileShare_ -timeout 180m
--- PASS: TestAccStorageGatewaySMBFileShare_Authentication_guestAccess (345.92s)
--- PASS: TestAccStorageGatewaySMBFileShare_guessMIMETypeEnabled (394.40s)
--- PASS: TestAccStorageGatewaySMBFileShare_disappears (395.55s)
--- PASS: TestAccStorageGatewaySMBFileShare_encryptedUpdate (410.67s)
--- PASS: TestAccStorageGatewaySMBFileShare_audit (411.60s)
--- PASS: …
```
=> aws_storagegateway_smb_file_share: Set `kms_key_arn` when `kms_encrypted` is `true`

.github/workflows/gen-teamcity.yml, .teamcity/.java-version, .teamcity/GNUmakefile, .teamcity/components/service_build_config.kt, .teamcity/pom.xml, .teamcity/settings.kts
This PR updates the TeamCity Configuration to use the newer syntax (which is now versionless).
I'm having a little trouble validating the `jenv` setup, but this is the latest version available from the Corretto site for v17, so I think should work fine?
=> tooling: updating the TeamCity configuration

.changelog/31931.txt, internal/service/lambda/event_source_mapping.go, website/docs/r/lambda_event_source_mapping.html.markdown
This PR adds `MaxItems: 1` to the `aws_lambda_event_source_mapping.queues` argument, as this argument only accepts a single item. Documentation is also modified to reflect this requirement.
While the AWS Go SDK `lambda.CreateEventSouceMappingInput` type's `Queues` field doesn't specify a limit of one item, the API documentation (linked below) does, and adding additional items leads to errors (see related issue):
> Array Members: Fixed number of 1 item.
Closes #31919
- [AWS API `CreateEventSourceMapping` documentation](https://docs.aws.amazon.com/lambda/latest/dg/API_CreateEventSourceMapping.html#API_CreateEventSourceMapping_RequestSyntax)
```shell
$ make testacc TESTS=TestAccLambdaEventSourceMapping PKG=lambda …
```
=> Add `MaxItems` to `aws_lambda_event_source_mapping.queues`

.github/workflows/reusable-team-project.yml
The reusable workflow for automating the new style GitHub Projects was previously failing due to the token being passed not having the correct permissions. This PR moves the workflow to a newly created `PROJECT_SCOPED_TOKEN` secret to correct this.
N/a, Actions
=> Move `reusable-team-project` to Project scoped token

internal/create/errors.go, internal/service/lakeformation/lakeformation_test.go, internal/service/lakeformation/resource_lf_tags.go, internal/service/lakeformation/resource_lf_tags_test.go
When LF-Tags were defined on table columns as well as either database or table, the incorrect tags were returned for the table columns
Closes #31909
```
$ make testacc PKG=lakeformation TESTS=TestAccLakeFormation_serial/ResourceLFTags
--- PASS: TestAccLakeFormation_serial (202.59s)
--- PASS: TestAccLakeFormation_serial/ResourceLFTags (202.58s)
--- PASS: TestAccLakeFormation_serial/ResourceLFTags/table (33.85s)
--- PASS: TestAccLakeFormation_serial/ResourceLFTags/tableWithColumns (37.04s)
--- PASS: TestAccLakeFormation_serial/ResourceLFTags/basic (16.65s)
--- PASS: TestAccLakeFormation_serial/ResourceLFTags/database (31.39s)
--- PASS: TestAccLakeFormation_serial/ResourceLFTags/databaseMultipleTags (30.63s)
--- PASS: TestAccLakeFormation_serial/ResourceLFTags/disappears (16.99s)
--- PASS: …
```
=> aws_lakeformation_resource_lf_tags: Correctly reads table column tags with inheritance

website/docs/r/backup_region_settings.html.markdown
This PR adds a link to the AWS documentation for additional information around the settings available in `aws_backup_region_settings`.
Closes #25150
N/a, docs
=> Add link to additional information for `aws_backup_region_settings`

.changelog/32231.txt, internal/service/opensearchserverless/access_policy_data_source.go, internal/service/opensearchserverless/access_policy_data_source_test.go, internal/service/opensearchserverless/service_package_gen.go, website/docs/d/opensearchserverless_access_policy.html.markdown
Adds data source for `aws_opensearchserverless_access_policy`
Closes #28460
```console
$ make testacc TESTARGS='-run=TestAccOpenSearchServerlessAccessPolicyDataSource_' PKG=opensearchserverless
TF_ACC=1 go test ./internal/service/opensearchserverless/... -v -count 1 -parallel 20  -run=TestAccOpenSearchServerlessAccessPolicyDataSource_ -timeout 180m
--- PASS: TestAccOpenSearchServerlessAccessPolicyDataSource_basic (16.26s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/opensearchserverless	19.532s
```
=> [data source]: aws_opensearchserverless_access_policy

internal/service/ec2/ec2_spot_instance_request.go, internal/service/ec2/tags.go, internal/tags/tags.go
Rather than allocating memory for each shared tag schema, reference the same schema data. Each `schema.Schema` struct allocation is ~304 bytes, which adds up when multiplied times a few hundred resources using it. Not a big reduction by any means, but seems like a quick way to reduce some unnecessary memory usage.
Updated the two code locations which were directly mutating the result of shared tag schemas.
Reference: https://github.com/hashicorp/terraform-provider-aws/issues/31722
```
...
```
=> internal/tags: Used shared memory allocation for shared tag schemas

.changelog/32152.txt, internal/service/fis/experiment_template.go, website/docs/r/fis_experiment_template.html.markdown
Add new valid values for action target key.
Closes https://github.com/hashicorp/terraform-provider-aws/issues/27353
Closes https://github.com/hashicorp/terraform-provider-aws/issues/26501
Did not run acceptance test, can do so if necessary.
=> `r/aws_fis_experiment_template`: Add new action target types

internal/service/wafv2/schemas.go
Happened to notice this was generating a decent number of memory allocations while profiling and its a small change.
Reference: https://github.com/hashicorp/terraform-provider-aws/issues/31722
```
$ TF_ACC=1 go test -count=1 -run='TestAccWAFV2RuleGroup_' -timeout=10m -v ./internal/service/wafv2
...
--- PASS: TestAccWAFV2RuleGroup_basic (30.05s)
--- PASS: TestAccWAFV2RuleGroup_disappears (32.14s)
--- PASS: TestAccWAFV2RuleGroup_Operators_maxNested (34.74s)
--- PASS: TestAccWAFV2RuleGroup_changeMetricNameForceNew (58.55s)
--- PASS: TestAccWAFV2RuleGroup_changeNameForceNew (60.83s)
--- PASS: TestAccWAFV2RuleGroup_changeCapacityForceNew (65.89s)
--- PASS: TestAccWAFV2RuleGroup_updateRule (68.22s)
--- PASS: TestAccWAFV2RuleGroup_logicalRuleStatements (85.48s)
--- PASS: …
```
=> service/wafv2: Allocate memory once for emptySchema()

internal/service/events/rule.go, internal/service/events/rule_test.go
The unicode conversion of `<` `>` `&` currently is causing issues for EventBridge rules.  Instead of `NormalizeJsonString` we'll use a local helper function that will escape those characters.
```
...
```
=> Replace NormalizeJsonString with local helper func

.changelog/32278.txt, internal/service/emrserverless/application.go, internal/service/emrserverless/application_test.go
EMR Serverless now supports the ability to update the release label of an application without destroying and creating a new application. This change adds support for that functionality.
Closes #32275
Created a new test for this change.
```
make testacc PKG=emrserverless TESTS=TestAccEMRServerlessApplication_releaseLabel
TF_ACC=1 go test ./internal/service/emrserverless/... -v -count 1 -parallel 20 -run='TestAccEMRServerlessApplication_releaseLabel'  -timeout 180m
=== RUN   TestAccEMRServerlessApplication_releaseLabel
=== PAUSE TestAccEMRServerlessApplication_releaseLabel
=== CONT  TestAccEMRServerlessApplication_releaseLabel
--- PASS: TestAccEMRServerlessApplication_releaseLabel (107.93s)
PASS
ok …
```
=> Add support for updating release label on EMR Serverless applications

.changelog/32287.txt, internal/service/rds/instance.go
The RDS instance `identifier` argument is optional and might be empty when `identifier_prefix` is used. Using the  `identifier` variable ensures that the same name is polled, that is also used when creating the instance.
Closes #32179.
Closes #31594.
```
$ make testacc TESTS=TestAccRDSInstance PKG=rds
...
```
=> rds/instance: Fix create returns unready instances

.changelog/32297.txt, internal/service/ec2/ec2_spot_instance_request.go, internal/service/ec2/tags.go, internal/service/ec2/vpc_test.go, internal/tags/tags.go
Reverts the change made in #32250 to share `tags` (and `tags_all`) schema objects.
Somewhere the `ForceNew` flag is being set and affecting all resources that use tagging.
Closes https://github.com/hashicorp/terraform-provider-aws/issues/32296.
```console
% make testacc TESTARGS='-run=TestAccVPC_tags$$' PKG=ec2
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 20  -run=TestAccVPC_tags$ -timeout 180m
=== RUN   TestAccVPC_tags
=== PAUSE TestAccVPC_tags
=== CONT  TestAccVPC_tags
vpc_test.go:97: Step 3/4 error: Check failed: Check 2/5 error: VPC IDs are not equal
--- FAIL: TestAccVPC_tags (38.01s)
FAIL
FAIL	github.com/hashicorp/terraform-provider-aws/internal/service/ec2	43.766s
FAIL
make: *** [testacc] Error 1
``` …
=> provider: Prevent resource recreation if `tags` or `tags_all` change

.changelog/32317.txt, .ci/.golangci2.yml, go.mod, go.sum
Upgrade to [AWS SDK for Go v1.44.293](https://github.com/aws/aws-sdk-go/releases/tag/v1.44.293), pulling in https://github.com/aws/aws-sdk-go/pull/4898, fixing `InvalidArgument: Invalid attribute name specified` errors when listing S3 Bucket objects.
Closes https://github.com/hashicorp/terraform-provider-aws/issues/32307.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/32305.
```console
% make testacc TESTARGS='-run=TestAccS3Bucket_Basic_forceDestroy' PKG=s3
TF_ACC=1 go test ./internal/service/s3/... -v -count 1 -parallel 20  -run=TestAccS3Bucket_Basic_forceDestroy -timeout 180m
=== RUN   TestAccS3Bucket_Basic_forceDestroy
=== PAUSE TestAccS3Bucket_Basic_forceDestroy
=== RUN …
```
=> Fix `InvalidArgument: Invalid attribute name specified` errors listing S3 Bucket objects

.changelog/32283.txt, internal/service/glue/catalog_database.go, internal/service/glue/catalog_database_test.go, website/docs/r/glue_catalog_database.html.markdown
Closes #32099
```
$ make testacc TESTS=TestAccGlueCatalogDatabase_  PKG=glue
--- PASS: TestAccGlueCatalogDatabase_disappears (80.53s)
--- PASS: TestAccGlueCatalogDatabase_createTablePermission (161.43s)
--- PASS: TestAccGlueCatalogDatabase_targetDatabase (163.26s)
--- PASS: TestAccGlueCatalogDatabase_tags (210.84s)
--- PASS: TestAccGlueCatalogDatabase_full (211.01s)
```
=> r/glue_catalog_database - add region to target_database

internal/service/quicksight/sweep.go
When an account is not signed up for QuickSight, the sweepers fail with the following error:
> UnsupportedUserEditionException: Account 123456789012 is not subscribed for QuickSight
or the following error for User:
> ResourceNotFoundException: Account 123456789012 is not signed up with QuickSight with namespace default
Now:
> [WARN] Skipping QuickSight User sweep for us-west-2: ResourceNotFoundException: Account 123456789012 is not signed up with QuickSight with namespace default.
[WARN] Skipping QuickSight Folder sweep for us-west-2: UnsupportedUserEditionException: Account 123456789012 is not subscribed for QuickSight
[WARN] Skipping QuickSight Dashboard sweep for us-west-2: UnsupportedUserEditionException: Account 123456789012 is not subscribed for QuickSight
[WARN] Skipping QuickSight …
=> Fixes QuickSight sweepers when account not signed up for QuickSight

.changelog/32332.txt, internal/service/glue/crawler.go, internal/service/glue/crawler_test.go, website/docs/r/glue_crawler.html.markdown
Closes #32110
```
$ make testacc TESTS=TestAccGlueCrawler_icebergTarget  PKG=glue
$ make testacc TESTS=TestAccGlueCrawler_jdbcTarget  PKG=glue
--- PASS: TestAccGlueCrawler_jdbcTarget (96.06s)
--- PASS: TestAccGlueCrawler_icebergTarget (83.63s)
```
=> r/glue_crawler -  add `iceberg_target` + fix `enable_additional_metadata` on `jdbc_target`

.changelog/32327.txt, internal/service/lambda/function.go
The AWS docs indicate this region supports code signing: https://docs.aws.amazon.com/general/latest/gr/signer.html#signer_lambda_region
=> Add ap-east-1 to Lambda Signer supported regions

.changelog/32345.txt, go.mod, go.sum, internal/conns/awsclient_gen.go, internal/service/qldb/exports_test.go, internal/service/qldb/generate.go, internal/service/qldb/ledger.go, internal/service/qldb/ledger_data_source.go, internal/service/qldb/ledger_data_source_test.go, internal/service/qldb/ledger_test.go, internal/service/qldb/service_package_gen.go, internal/service/qldb/stream.go, internal/service/qldb/stream_test.go, internal/service/qldb/sweep.go, internal/service/qldb/tags_gen.go, names/names.go, names/names_data.csv, website/docs/r/qldb_stream.html.markdown
Ibid.
```console
% make testacc TESTARGS='-run=TestAccQLDB' PKG=qldb ACCTEST_PARALLELISM=2
TF_ACC=1 go test ./internal/service/qldb/... -v -count 1 -parallel 2  -run=TestAccQLDB -timeout 180m
=== RUN   TestAccQLDBLedgerDataSource_basic
=== PAUSE TestAccQLDBLedgerDataSource_basic
=== RUN   TestAccQLDBLedger_basic
=== PAUSE TestAccQLDBLedger_basic
=== RUN   TestAccQLDBLedger_disappears
=== PAUSE TestAccQLDBLedger_disappears
=== RUN   TestAccQLDBLedger_nameGenerated
=== PAUSE TestAccQLDBLedger_nameGenerated
=== RUN   TestAccQLDBLedger_update
=== PAUSE TestAccQLDBLedger_update
=== RUN   TestAccQLDBLedger_kmsKey
=== PAUSE TestAccQLDBLedger_kmsKey
=== RUN   TestAccQLDBLedger_tags
=== PAUSE TestAccQLDBLedger_tags
=== RUN …
```
=> Tech debt: Migrate`qldb` resources to AWS SDK for Go v2

.changelog/32021.txt, .changelog/32355.txt, internal/service/ec2/vpc_endpoint.go, internal/service/ec2/vpc_endpoint_test.go
* This PR adds logic to check against the service_name attribute provided in the resource. If the service_name matches an S3 service name such as `com.amazonaws.us-west-2.s3`, the CREATE and UPDATE calls will include the `PrivateDnsOnlyForInboundResolverEndpoint` attribute. Otherwise, this attribute will not be included in the API calls. A new acceptance test is included to cover this use case.
* Existing acceptance tests cover the scenario of enabling/disabling `PrivateDnsOnlyForInboundResolverEndpoint` on an interface endpoint resource with an existing gateway endpoint in the same VPC.
* `PrivateDnsOnlyForInboundResolverEndpoint` is only supported for services that support BOTH gateway and interface endpoints. See: https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/ec2@v1.102.0/type …
=> Fix PrivateDnsOnlyForInboundResolverEndpoint for S3 interface endpoints

.changelog/32372.txt, internal/service/ssm/parameter.go, internal/service/ssm/parameter_test.go
Ignores Update if only `overwrite` parameter changes. Prevents the error
> Error: updating SSM Parameter (example): ParameterAlreadyExists: The parameter already exists. To overwrite this value, set the overwrite option in the request to true.
when removing parameter.
Closes https://github.com/hashicorp/terraform-provider-aws/issues/31655.
```
$ make testacc PKG=ssm TESTS=TestAccSSMParameter_
--- PASS: TestAccSSMParameter_disappears (64.78s)
--- PASS: TestAccSSMParameter_Secure_basic (83.54s)
--- PASS: TestAccSSMParameter_Tier_intelligentTieringOnCreation (83.55s)
--- PASS: TestAccSSMParameter_basic (83.62s)
--- PASS: TestAccSSMParameter_Overwrite_noOverwriteTags (85.51s)
--- PASS: TestAccSSMParameter_fullPath (85.62s)
--- PASS: TestAccSSMParameter_DataType_ssmIntegration (85.95s)
--- …
```
=> resource/aws_ssm_parameter: Ignore Update if only `overwrite` parameter changes

internal/errs/sdkdiag/diags.go, internal/service/opsworks/sweep.go
Fixes "Cannot delete self" error in OpsWorks User Profile sweeper
Previously failed with:
> deleting OpsWorks User Profile (*****): ValidationException: Cannot delete self
Now succeeds with:
> [WARN] Skipping OpsWorks User Profile (*****): deleting OpsWorks User Profile (*****): ValidationException: Cannot delete self
=> Fixes "Cannot delete self" error in OpsWorks User Profile sweeper

docs/running-and-writing-acceptance-tests.md
The reference documentation for sweepers checks for skippable errors in the wrong places. This PR corrects the documentation.
=> Corrects error handling in sweeper reference documentation

.changelog/32371.txt, internal/generate/tags/main.go, internal/generate/tags/templates/v1/header_body.tmpl, internal/generate/tags/templates/v1/update_tags_body.tmpl, internal/generate/tags/templates/v1/v1.go, internal/generate/tags/templates/v1/wait_tags_propagated_body.tmpl, internal/generate/tags/templates/v2/header_body.tmpl, internal/generate/tags/templates/v2/update_tags_body.tmpl, internal/generate/tags/templates/v2/v2.go, internal/generate/tags/templates/v2/wait_tags_propagated_body.tmpl, internal/service/kms/external_key.go, internal/service/kms/external_key_test.go, internal/service/kms/generate.go, internal/service/kms/key.go, internal/service/kms/key_test.go, internal/service/kms/replica_external_key.go, internal/service/kms/replica_external_key_test.go, internal/service/kms/replica_key.go, internal/service/kms/replica_key_test.go, internal/service/kms/tags_gen.go, internal/service/kms/wait.go
Fixes timeout error when removing all tags from
* aws_kms_key
* aws_kms_external_key
* aws_kms_replica_external_key
* aws_kms_replica_key
```
$ make testacc PKG=kms TESTS=TestAccKMSKey
--- PASS: TestAccKMSKey_disappears (107.03s)
--- PASS: TestAccKMSKeyDataSource_byKeyARN (115.68s)
--- PASS: TestAccKMSKeyPolicy_disappears (120.03s)
--- PASS: TestAccKMSKey_hmacKey (127.22s)
--- PASS: TestAccKMSKey_asymmetricKey (130.71s)
--- PASS: TestAccKMSKey_Policy_booleanCondition (140.26s)
--- PASS: TestAccKMSKey_basic (152.11s)
--- PASS: TestAccKMSKey_multiRegion (152.28s)
--- PASS: TestAccKMSKeyPolicy_booleanCondition (156.69s)
--- PASS: TestAccKMSKey_Policy_iamRole (201.02s)
--- PASS: TestAccKMSKey_Policy_iamServiceLinkedRole (201.08s)
--- PASS: TestAccKMSKeyPolicy_iamServiceLinkedRole (211.75s) …
```
=> KMS Keys: Fixes timeout when removing all tags

website/docs/r/wafv2_web_acl.html.markdown
This PR fixes a few issues within the `aws_wafv2_web_acl` documentation:
- Added `terraform` tag to one of the example code blocks that was missing it.
- Concatenated a few lines that were broken up for some reason.
- Changed header level of several of the headers from h4 to h3 so that they would properly render as anchors in the Registry.
- Made the `**Note**` callouts consistent with the [Registry Documentation](https://developer.hashicorp.com/terraform/registry/providers/docs#callouts) on callouts
- Changed nested block headers to a uniform style of "`nested_block_name` Block". This accomplishes a couple of things:
- Consistency across header titles.
- Consistency in anchor links; underscores, mirroring the block name, a dash to replace the space, and then "block" …
=> Fix headers, anchor links in `aws_wafv2_web_acl docs`

internal/service/iam/sweep.go
Adds `AmazonComprehendServiceRole-` and `codebuild-` to role sweeper.
Restores skip on `AccessDenied` errors for policy sweeper.
Previously:
>	- aws_iam_policy: 5 errors occurred:
* error deleting IAM Policy (\*****): 1 error occurred:
* deleting IAM Policy (*****): DeleteConflict: Cannot delete a policy attached to entities.
status code: 409, request id: *****
>
>
>	* error deleting IAM Policy (\*****): 1 error occurred:
* deleting IAM Policy (*****): DeleteConflict: Cannot delete a policy attached to entities.
status code: 409, request id: *****
>
>
>	* error deleting IAM Policy (\*****): 1 error occurred:
* deleting IAM Policy (*****): DeleteConflict: Cannot delete a policy attached to entities.
status code: 409, request id: *****
>
>
>	* error deleting IAM Policy (\*****): 1 error …
=> Sweepers: Fixes failures in `aws_iam_policy` sweeper

website/docs/r/wafv2_rule_group.html.markdown, website/docs/r/wafv2_web_acl.html.markdown
[RateBasedStatement](https://docs.aws.amazon.com/waf/latest/APIReference/API_RateBasedStatement.html) supports `IP`, `FORWARDED_IP` but also `CONSTANT` and `CUSTOM_KEYS`.
`CONSTANT` is already supported because validation is made against aws SDK where it is declared as valid value.
Relates to #31625
=> docs/r/wafv2: add CONSTANT to aggregate_key_type

.github/dependabot.yml
Github has just released "grouped" dependabot updates in a public beta. This PR groups both v1 and v2 AWS SDK updates together.
[Announcement](https://github.com/dependabot/dependabot-core/issues/1190#issuecomment-1623832701)
[Docs](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#groups)
Closes #28454
N/a, deps.
=> deps: group aws-sdk-go dependencies

.teamcity/components/service_build_config.kt, .teamcity/settings.kts
The step "Configure GOENV" was not being added to the build steps, causing builds to fail
=> Fix TeamCity configuration

internal/service/kms/key_test.go
Sets the deletion window for the `basic` and `tag` tests to 7 days instead of the default 30 days.
N/A
=> resource/aws_kms_key: Shortens deletion window for basic and tag tests

.changelog/32329.txt, internal/service/wafregional/web_acl_association.go
Increase creation timeout value from 2 to 5 minutes to prevent WAFUnavailableEntityException for WAFClassic ACL association.
Closes #32103
The same as #17545 but for wafregional.
```
$ make testacc TESTS=TestAccWAFRegionalWebACLAssociation_ PKG=wafregional
TF_ACC=1 go test ./internal/service/wafregional/... -v -count 1 -parallel 20 -run='TestAccWAFRegionalWebACLAssociation_'  -timeout 180m
=== RUN   TestAccWAFRegionalWebACLAssociation_basic
=== PAUSE TestAccWAFRegionalWebACLAssociation_basic
=== RUN   TestAccWAFRegionalWebACLAssociation_disappears
=== PAUSE TestAccWAFRegionalWebACLAssociation_disappears
=== RUN   TestAccWAFRegionalWebACLAssociation_multipleAssociations
=== PAUSE …
```
=> waf: up aws_wafregional_web_acl_association create timeout to 5 minutes

website/docs/d/wafv2_ip_set.html.markdown, website/docs/r/wafv2_ip_set.html.markdown
I have updated the `addresses` parameter description in the `wafv2_ip_set` documents to reflect the ability to accept an empty array. The previous description was incorrect, this parameter allows for an empty array as input.
Relates #21758
* [create-ip-set — AWS CLI 2.12.6 Command Reference](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/wafv2/create-ip-set.html)
* I referenced this URL for the description.
N/A
=> Update `addresses` argument description in `wafv2_ip_set`

go.mod, go.sum
From the `terraform-plugin-framework-timeouts` release notes:
```
Prevented Value Conversion Error with terraform-plugin-framework 1.3.0 and later
```
Fixes #32322
- https://github.com/hashicorp/terraform-plugin-framework-timeouts/releases/tag/v0.4.1
- https://github.com/hashicorp/terraform-plugin-framework-timeouts/pull/72
N/a deps.
=> deps: bump terraform-plugin-framework-timeouts to v0.4.1

.github/dependabot.yml
Groups together `aws-sdk-go-base` and `awsv1shim` modules for `dependabot` updates
Also includes more `aws-sdk-go-v2` modules in `aws-sdk-go` group
=> dependabot: Groups together `aws-sdk-go-base` and `awsv1shim` modules

website/docs/r/securityhub_standards_control.markdown
Improve docs to help users find the right control ARNs.
=> securityhub_standards_control: improve docs for control ARNs

.changelog/32439.txt, internal/service/configservice/find.go
Properly returns an error when the describe config rule API call returns a nil response.
Closes #31559
```console
$ make testacc PKG=configservice TESTARGS='-run=TestAccConfigService_serial/Config'
TF_ACC=1 go test ./internal/service/configservice/... -v -count 1 -parallel 20  -run=TestAccConfigService_serial/Config -timeout 180m
--- PASS: TestAccConfigService_serial (1763.38s)
--- PASS: TestAccConfigService_serial/RemediationConfiguration (643.82s)
--- PASS: TestAccConfigService_serial/RemediationConfiguration/updates (98.11s)
--- PASS: TestAccConfigService_serial/RemediationConfiguration/values (86.53s)
--- PASS: TestAccConfigService_serial/RemediationConfiguration/basic (86.28s)
--- PASS: …
```
=> r/aws_configservice_config_rule: fix nil output handling

.github/workflows/new-project-automation.yml
Previously, this workflow called the [reusable workflow](https://github.com/hashicorp/terraform-provider-aws/blob/main/.github/workflows/reusable-team-project.yml) that adds items to the new style of GitHub Project and also passed the requisite input to set the `Status` field to `To Do`. This Project, however, uses the built-in Projects workflow (reference below) to automatically set the `Status` field to `To Do` for newly added items. Removing this means that we save an API call (and associated time, rate-limiting) for every item that gets added.
YAML formatter also removed the extraneous newlines; figured I'd leave that be to try to maintain consistency. 🤷 
- [GitHub Projects Automated Workflows](https://docs.github.com/en/issues/planning-and-tracking-with-projects/automating-your-projec …
=> Don't manually set `Status` field to `To Do` for new Projects automation

.changelog/32454.txt, internal/service/mq/broker.go, internal/service/mq/broker_test.go, website/docs/r/mq_broker.html.markdown
Adds parameter to the MQ user update/creation API calls, so that new/existing AWS MQ resources don't fail to create/update.
I copied the pre-existing parameter `console_access`, and defaulted it to `false`.
Closes #32446
[AWS recently announced support for cross-region data replication](https://aws.amazon.com/about-aws/whats-new/2023/06/amazon-mq-cross-region-data-replication-activemq/). 
While this PR does not enable any replication functionality, will hopefully unblock updating of existing, non-replicated Amazon MQ brokers managed by Terraform.
```
$ make testacc PKG=mq
TF_ACC=1 go test ./internal/service/mq/... -v -count 1 -parallel 20   -timeout 180m
=== RUN   TestAccMQBrokerDataSource_basic
=== PAUSE …
```
=> B MQ replication user fix

website/docs/r/security_group.html.markdown
* Document how to remove all managed ingress & egress rules from the `aws_security_group` resource https://github.com/hashicorp/terraform-provider-aws/issues/4399#issuecomment-488627152
* Mirrored documentation from `aws_route_table` resource https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/route_table.html#example-usage
Closes #660
Closes #1555
Closes #4399
Closes #11059
Closes #20046
```
...
```
=> aws_security_group - remove all managed ingress & egress rules

website/docs/index.html.markdown
The main index page of the provider had a couple of leftover things from v4 of the provider. This PR aims to correct them:
- Updated version pinning in example to be `~> 5.0` rather than `~> 4.0`
- Removed `duration_seconds` from `assume_role` reference
- Concatenated `assume_role.duration` line
Closes #32131
N/a, docs
=> Update index.html.markdown to match provider version 5

internal/service/kms/sweep.go, internal/service/opsworks/sweep.go
The sweeper for `aws_kms_key` fails if access is denied with an error similar to
> - aws_kms_key: 12 errors occurred:
* error reading KMS Key (xxxxx): AccessDeniedException: User: arn:aws:sts::123456789012:assumed-role/xxxxx is not authorized to perform: kms:DescribeKey on resource: arn:aws:kms:us-west-2:123456789012:key/xxxxx because no resource-based policy allows the kms:DescribeKey action
...
* error reading KMS Key (xxxxx): AccessDeniedException: User: arn:aws:sts::123456789012:assumed-role/xxxxx is not authorized to perform: kms:DescribeKey on resource: arn:aws:kms:us-west-2:123456789012:key/xxxxx because no resource-based policy allows the kms:DescribeKey action
Skips the individual keys if that error is returned
Now logs entries similar to:
> [DEBUG] Skipping KMS Key (xxxxx): …
=> sweeper: Skip KMS Keys if access is denied

skaff/datasource/datasourcetest.tmpl, skaff/resource/resourcetest.tmpl
Parallelizes `skaff` example unit tests to align with the pattern most commonly used throughout the provider.
N/a skaff.
=> skaff: parallelize unit tests

.changelog/32464.txt, internal/service/quicksight/schema/visual_chart_configuration.go, internal/service/quicksight/schema/visual_pivot_table.go
There were three typos in some of the Quicksight flattener functions that were leading to the following errors. This PR aims to correct them so that the data can successfully be written to the state.
I'm unsure on running the acceptance tests for this, so have left that out for now. I'd also be interested in how to properly approach the changelog entry for this, since it affects multiple resources due to the shared schema.
```shell
Error: setting definition: Invalid address to set: []string{"definition", "0", "sheets", "0", "visuals", "0", "bar_chart_visual", "0", "chart_configuration", "0", "category_axis", "0", "scrollbar_options", "0", "visibile_range"}
Error: setting definition: Invalid address to set: []string{"definition", "0", "sheets", "0", "visuals", "0", "pivot_table_visual", …
```
=> Correct typos in Quicksight flatteners for `visible_range`,  `rows`, and `visibility`

internal/service/batch/sweep.go
`aws_batch_job_definition` sweeper was calling wrong resource implementation
Was returning error
> 	- aws_batch_job_definition: error sweeping Batch Job Definitions (us-west-2): 1 error occurred:
* deleting Batch Scheduling Policy (arn:aws:batch:us-west-2:123456789012:job-definition/xxxxx): ClientException: Error executing request, Exception : Only scheduling policy Arn is allowed
=> sweep: `aws_batch_job_definition` sweeper was calling wrong resource implementation

.changelog/32462.txt, internal/service/iam/sweep.go, internal/service/iam/virtual_mfa_device.go, internal/service/iam/virtual_mfa_device_test.go, internal/service/opsworks/sweep.go, website/docs/r/iam_virtual_mfa_device.html.markdown
Attempting to sweep an `aws_iam_virtual_mfa_device` that is associated with an IAM User fails with the error
> deleting IAM Virtual MFA Device (arn:aws:iam::123456789012:mfa/example): DeleteConflict: MFA VirtualDevice in use. Must deactivate first
Adds `user_name` attribute needed for MFA deactivation and `enable_date`.
Also fixes panic in OpsWorks user sweeper.
```
$ make testacc PKG=iam TESTS=TestAccIAMVirtualMFADevice_
--- PASS: TestAccIAMVirtualMFADevice_disappears (18.19s)
--- PASS: TestAccIAMVirtualMFADevice_basic (23.26s)
--- PASS: TestAccIAMVirtualMFADevice_path (23.32s)
--- PASS: TestAccIAMVirtualMFADevice_tags (46.32s)
```
=> resource/aws_iam_virtual_mfa_device: Correctly sweep associated devices and add `enable_date` and `user_name` attributes

website/docs/r/db_instance.html.markdown
This PR removes the `name` attribute from the documentation on the `aws_db_instance` resource, as it does not exist within the schema.
Closes #32475
- [Resource schema](https://github.com/hashicorp/terraform-provider-aws/blob/main/internal/service/rds/instance.go)
N/a, docs
=> Remove `name` attribute from `aws_db_instance` docs

website/docs/r/wafv2_regex_pattern_set.html.markdown
The `aws_wafv2_regex_pattern_set.regular_expression` argument can take a maximum of 10 regular expressions. This limitation was not documented, so this PR adds a note indicating the limitation.
Closes #32311
- [Resource Schema](https://github.com/hashicorp/terraform-provider-aws/blob/d54824dccd7179c11347981505be66d90db750a5/internal/service/wafv2/regex_pattern_set.go#L80)
- [AWS Quotas documentation](https://docs.aws.amazon.com/waf/latest/developerguide/limits.html) (this limit is not mentioned in the API or SDK documentation, but is indicated here)
N/a, docs
=> Document max items for `aws_wafv2_regex_pattern_set.regular_expression`

docs/raising-a-pull-request.md
The "Raising a Pull Request" Contributor documentation page currently has the "Create a changelog" entry prior to the pull request creation, however the changelog file needs to be named after the PR number.
This small change is to move the "Create a changelog" step to be after the "Create a pull request" step
Nil
Nil
N/A
=> Update `raising-a-pull-request.md` contributor doc to reflect changelog creation order

website/docs/r/api_gateway_authorizer.html.markdown
Changing reference on `aws_iam_role.invocation_role` to refer `data.aws_iam_role_policy_document.invocation_assume_role.json` instead of  `data.aws_iam_role_policy_document.assume_role.json`
=> FIX api_gateway_authorizer.html.markdown data reference

internal/service/accessanalyzer/sweep.go, internal/service/acm/sweep.go, internal/service/acmpca/sweep.go, internal/service/auditmanager/sweep.go, internal/service/ec2/sweep.go, internal/service/glacier/sweep.go, internal/service/internetmonitor/sweep.go, internal/service/kendra/sweep.go, internal/service/keyspaces/sweep.go, internal/service/lightsail/sweep.go, internal/service/medialive/sweep.go, internal/service/opensearchserverless/sweep.go, internal/service/pipes/sweep.go, internal/service/qldb/sweep.go, internal/service/resourceexplorer2/sweep.go, internal/service/scheduler/sweep.go, internal/service/sesv2/sweep.go, internal/service/ssm/sweep.go, internal/service/swf/sweep.go, internal/service/timestreamwrite/sweep.go, internal/service/transcribe/sweep.go, internal/service/vpclattice/sweep.go, internal/service/workspaces/sweep.go, internal/sweep/awsv1/skip.go, internal/sweep/awsv2/skip.go, internal/sweep/sweep.go
Since AWS SDK for Go v1 and v2 have different error handling strategies and types, use separate skip checking functions in sweepers.
`awsv1.SkipSweepError` is aliased as `sweep. SkipSweepError`
=> sweepers: Create AWS SDK version-specific skip error handlers for sweepers

docs/skaff.md, skaff/cmd/datasource.go, skaff/cmd/resource.go, skaff/datasource/datasource.go, skaff/datasource/datasource.tmpl, skaff/datasource/datasourcefw.tmpl, skaff/datasource/websitedoc.tmpl, skaff/resource/resource.go, skaff/resource/resource.tmpl, skaff/resource/resourcefw.tmpl, skaff/resource/websitedoc.tmpl
This pull request adds the `--include-tags` flag to the `skaff` tool. This makes the generated code be more targeted and relevant to resources that do or do not support tagging.  I have tested generating a resource with and without the flag and the outcome is as expected. When providing the flag, code is present for tags, and it is not present when omitting the flag. The same behavior is true for the generated docs. 
```
➜ skaff (td-skaff-tags-flag) ✔ go test ./...
?       github.com/hashicorp/terraform-provider-aws/skaff       [no test files]
?       github.com/hashicorp/terraform-provider-aws/skaff/cmd   [no test files]
ok      github.com/hashicorp/terraform-provider-aws/skaff/datasource    (cached) [no tests to run]
ok      github.com/hashicorp/terraform-provider-aws/skaff/resource …
```
=> Add `skaff` `--include-tags` flag

internal/service/lakeformation/permissions.go, internal/service/lakeformation/permissions_data_source.go
```terraform
resource "aws_lakeformation_permissions" "test" {
principal   = aws_iam_role.sales_role.arn
permissions = ["CREATE_TABLE", "ALTER", "DROP"]
lf_tag_policy {
resource_type = "DATABASE"
expression {
key    = "Team"
values = ["Sales"]
}
}
}
```
resource type "aws_lakeformation_permissions" lf_tag_policy.expression.values supports only 15 values. I have added fix for this.
=> aws_lakeformation_permissions lf_tag_policy expression  values supports max 15 fix

GNUmakefile, internal/service/opensearchserverless/sweep.go, internal/service/route53resolver/sweep.go, internal/service/ses/sweep.go, internal/service/vpclattice/sweep.go
Ignores `InvalidAction` error returned by some regions when attempting to disable SES
Ignores `AccessDeniedException: UnknownError` error returned by OpenSearch Serverless in unsupported regions
Ignores `AccessDeniedException` error returned by VPC Lattice
Adds `us-west-1` to sweeper regions in `Makefile` to match CI config
=> sweepers: Fixes

.changelog/32520.txt, internal/service/configservice/config_rule.go
Properly handles non-nil `err` values during Read operations.
Closes #32512
```console
$ make testacc PKG=configservice TESTARGS='-run=TestAccConfigService_serial/Config'
TF_ACC=1 go test ./internal/service/configservice/... -v -count 1 -parallel 20  -run=TestAccConfigService_serial/Config -timeout 180m
--- PASS: TestAccConfigService_serial (1760.05s)
--- PASS: TestAccConfigService_serial/RemediationConfiguration (642.15s)
--- PASS: TestAccConfigService_serial/RemediationConfiguration/migrateParameters (101.87s)
--- PASS: TestAccConfigService_serial/RemediationConfiguration/recreates (99.61s)
--- PASS: TestAccConfigService_serial/RemediationConfiguration/updates (97.49s)
--- PASS: …
```
=> r/aws_config_config_rule: handle err during read

.changelog/32517.txt, internal/service/ec2/vpc_endpoint_data_source.go, website/docs/d/vpc_endpoint.html.markdown
This PR adds the `private_dns_only_for_inbound_resolver_endpoint` attribute to `data.aws_vpc_endpoint.dns_options`, and documents the `data.aws_vpc_endpoint.dns_options` block, which was missing from the documentation. 
Closes #32508
- [Where `dns_options` is already set](https://github.com/hashicorp/terraform-provider-aws/blob/172bc9ac324df7d0e0388bf65df83e57e4af1877/internal/service/ec2/vpc_endpoint_data_source.go#L195-L198)
- [`flattenDNSOptions` function](https://github.com/hashicorp/terraform-provider-aws/blob/172bc9ac324df7d0e0388bf65df83e57e4af1877/internal/service/ec2/vpc_endpoint.go#L568-L584)
- [API reference](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DnsOptions.html)
```
$ make testacc TESTS=TestAccVPCEndpointDataSource PKG=ec2
==> Checking that code complies …
```
=> Add additional attribute to `aws_vpc_endpoint` data source

.github/workflows/autoremove_labels.yml, .github/workflows/changelog.yml, .github/workflows/community-check.yml, .github/workflows/dependencies.yml, .github/workflows/issue-comment-created.yml, .github/workflows/maintainer-edit.yml, .github/workflows/new-project-automation.yml, .github/workflows/project.yml, .github/workflows/pull_request_feed.yml, .github/workflows/pull_requests.yml
Previously, the community check reusable workflow based its determination on `github.event.issue.user.login || github.event.pull_request.user.login`, which maps to the username of the user who created the issue or pull request. This, however, isn't always accurate when it comes to certain things we'd like to automate.
For example, for `issue_comment` events (such as is used in the `issue-comment-created` workflow, used to remove the `waiting-response` label when a non-maintainer comments on an issue or PR), this meant that when a comment was made, the determination was based on the original issue/PR author's username, rather than the commenter's username.
This PR adds a `username` input to the community check workflow to allow us to check a _specific_ username, and updates all workflows …
=> Add `username` input to community check reusable workflow

.changelog/32546.txt, internal/service/datasync/agent.go
Prevent persistent diffs on `aws_datasync_agent` configurations where `private_link_endpoint` is not explicitly configured but is returned by the AWS API.
Closes #19947
```console
$ make testacc PKG=datasync TESTS=TestAccDataSyncAgent_
TF_ACC=1 go test ./internal/service/datasync/... -v -count 1 -parallel 20 -run='TestAccDataSyncAgent_'  -timeout 180m
--- PASS: TestAccDataSyncAgent_disappears (106.23s)
--- PASS: TestAccDataSyncAgent_basic (111.66s)
--- PASS: TestAccDataSyncAgent_tags (150.82s)
--- PASS: TestAccDataSyncAgent_agentName (172.15s)
--- PASS: TestAccDataSyncAgent_vpcEndpointID (292.41s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/datasync   295.587s
```
=> r/aws_datasync_agent: handle computed `private_link_endpoint` values

website/docs/r/wafv2_web_acl_logging_configuration.html.markdown
fix to aws_wafv2_web_acl_logging_configuration doc in cloudwatch example
This PR fixes an issue with an example in the docs [here](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/wafv2_web_acl_logging_configuration#with-cloudwatch-log-group-and-managed-cloudwatch-log-resource-policy)
The example has a service in the principals identifier, but the type is `AWS` not `Service` More details are in the linked issue
Closes #32568
Please see description on the [related issue](https://github.com/hashicorp/terraform-provider-aws/issues/32568)
=> Issue #32568 aws_wafv2_web_acl_logging_configuration doc fix

internal/service/iam/sweep.go, internal/service/ssoadmin/sweep.go
In some cases, a `nil` error can cause a panic in several sweepers.
=> sweepers: Prevent panic with `nil` error

internal/service/ec2/errors.go, internal/service/ec2/vpc_traffic_mirror_filter.go, internal/service/ec2/vpc_traffic_mirror_filter_rule.go, internal/service/ec2/vpc_traffic_mirror_session.go, internal/service/ec2/vpc_traffic_mirror_session_test.go, internal/service/ec2/vpc_traffic_mirror_target.go, internal/service/ec2/vpc_traffic_mirror_target_test.go
Check for "resource not found" error codes on Delete and return no error if matched.
Relates https://github.com/hashicorp/terraform-provider-aws/issues/32589.
```console
% make testacc TESTARGS='-run=TestAccVPCTrafficMirror' PKG=ec2 ACCTEST_PARALLELISM=2
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 2  -run=TestAccVPCTrafficMirror -timeout 180m
=== RUN   TestAccVPCTrafficMirrorFilterRule_basic
=== PAUSE TestAccVPCTrafficMirrorFilterRule_basic
=== RUN   TestAccVPCTrafficMirrorFilterRule_disappears
=== PAUSE TestAccVPCTrafficMirrorFilterRule_disappears
=== RUN   TestAccVPCTrafficMirrorFilter_basic
=== PAUSE TestAccVPCTrafficMirrorFilter_basic
=== RUN   TestAccVPCTrafficMirrorFilter_tags
=== PAUSE …
```
=> VPC Traffic Mirror: Handle "resource not found" errors on Delete

.changelog/32551.txt, internal/service/dms/replication_instance_data_source.go, internal/service/dms/replication_instance_data_source_test.go, website/docs/d/dms_replication_instance.html.markdown
This PR updates the `aws_dms_replication_instance` data source to properly set the `vpc_security_group_ids`, `replication_instance_private_ips` and `replication_instance_public_ips` values. While these attributes were in the schema, they were previously not being set once read.
In updating these, I've also removed the `allow_major_version_upgrade` and `apply_immediately` attributes, as these are not returned from the SDK (this appears to have been a case of copying over the resource schema to the data source, as they were also not actually being set by the read function).
The documentation for the data source has also been updated, as it was mostly a copy from the resource of the same name. The resource-oriented notes have been removed. 
Relates #15406
Closes #32533
- …
=> Bug: Properly set DMS Replication Instance data source private/public IPs, VPC security group IDs

website/docs/r/wafv2_web_acl_logging_configuration.html.markdown
This PR removes the note on `aws_wafv2_web_acl_logging_configuration` that indicated that an intermediate Kinesis Firehose Delivery Stream was required, as this requirement on the AWS side has been dropped.
Closes #32544
- [Blog post detailing the change](https://aws.amazon.com/blogs/mt/analyzing-aws-waf-logs-in-amazon-cloudwatch-logs/)
> Previously, WAF logs had to be sent via Amazon [Kinesis Data Firehose](https://aws.amazon.com/kinesis/data-firehose/) to [AWS OpenSearch](https://aws.amazon.com/opensearch-service/), third-party solutions for dashboards, or to [Amazon Simple Storage Service (Amazon S3)](https://aws.amazon.com/s3/) paired with [Amazon Athena](https://aws.amazon.com/athena/) for log analysis. Customers would have a high volume of incoming logs, where analyzing logs would …
=> Remove outdated note about Kinesis requirement for `aws_wafv2_web_acl_logging_configuration`

internal/service/codepipeline/codepipeline_test.go
Prevents a panic in the `testAccPreCheckSupported` caused by passing an empty AWSClient struct to the `ConfigureProvider` method. Also removes various AWS s3 bucket ACL configurations which are no longer necessary.
Closes #32577
Failure is unrelated to this change, which just fixes a PreCheck panic:
```console
$ make testacc PKG=codepipeline TESTS=TestAccCodePipeline_
TF_ACC=1 go test ./internal/service/codepipeline/... -v -count 1 -parallel 20 -run='TestAccCodePipeline_'  -timeout 180m
--- PASS: TestAccCodePipeline_disappears (42.66s)
--- PASS: TestAccCodePipeline_emptyStageArtifacts (48.72s)
--- PASS: TestAccCodePipeline_withNamespace (52.21s)
--- PASS: TestAccCodePipeline_deployWithServiceRole (52.96s)
--- PASS: …
```
=> r/aws_codepipeline(test): fix PreCheck panic

.changelog/32445.txt, internal/service/cognitoidp/flex_test.go, internal/service/cognitoidp/user_pool.go, internal/service/cognitoidp/user_pool_test.go
Handles persistent differences when the `schema.string_attribute_constraints` argument is omitted from configuration for a `String` attribute type, but returned from the AWS API with default values. Because all of the existing suppression logic was implemented in the flattener function, logic to handle this case was added there as well.
Closes #21654
- https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_SchemaAttributeType.html#CognitoUserPools-Type-SchemaAttributeType-StringAttributeConstraints
```console
$ make testacc PKG=cognitoidp TESTS=TestAccCognitoIDPUserPool_schemaAttributes
TF_ACC=1 go test ./internal/service/cognitoidp/... -v -count 1 -parallel 20 …
```
=> r/aws_cognitoidp_user_pool: suppress diff when schema.string_attribute_constraints is omitted

website/docs/r/lb_target_group_attachment.html.markdown
Adds an additional example for the `aws_lb_target_group_attachment` resource demonstrating how to use the [`for_each`](https://developer.hashicorp.com/terraform/language/meta-arguments/for_each) Terraform meta-argument to register multiple targets.
Relates #9901 
N/a docs.
=> [Docs]: `aws_lb_target_group_attachment` add multiple targets example

website/docs/r/appsync_datasource.html.markdown
Adding missing option of `AMAZON_OPENSEARCH_SERVICE` to the documentation for `aws_appsync_datasource` `type`
Relates #29579
=> docs: Add missing type value for `aws_appsync_datasource`

.changelog/32592.txt, internal/service/quicksight/folder.go, internal/service/quicksight/folder_test.go
Bug fix for `aws_quicksight_folder`.
`FolderPath` seems to be ordered by older ancestors, this change ensures the correct parent folder is used.
Closes #31922 
```
make testacc TESTS=TestAccQuickSightFolder_ PKG=quicksight
TF_ACC=1 go test ./internal/service/quicksight/... -v -count 1 -parallel 20 -run='TestAccQuickSightFolder_'  -timeout 180m
=== RUN   TestAccQuickSightFolder_basic
=== PAUSE TestAccQuickSightFolder_basic
=== RUN   TestAccQuickSightFolder_disappears
=== PAUSE TestAccQuickSightFolder_disappears
=== RUN   TestAccQuickSightFolder_permissions
=== PAUSE TestAccQuickSightFolder_permissions
=== RUN …
```
=> Fix misidentification of parent folder at grandchild level or deeper.

internal/service/elasticache/replication_group_test.go
- elasticache/rep_group: Fix test
- elasticache/rep-group: Add pg to test
Relates #32252
Relates #31264
```console
% make t T=TestAccElastiCacheReplicationGroup_EngineVersion_v7 K=elasticache
TF_ACC=1 go test ./internal/service/elasticache/... -v -count 1 -parallel 20 -run='TestAccElastiCacheReplicationGroup_EngineVersion_v7'  -timeout 180m
=== RUN   TestAccElastiCacheReplicationGroup_EngineVersion_v7
=== PAUSE TestAccElastiCacheReplicationGroup_EngineVersion_v7
=== CONT  TestAccElastiCacheReplicationGroup_EngineVersion_v7
--- PASS: TestAccElastiCacheReplicationGroup_EngineVersion_v7 (878.21s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/elasticache	880.103s
```
=> elasticache/replication_group: Fix acc test for v7

.changelog/32644.txt, internal/service/quicksight/schema/template_sheet.go
Changes the grid layout `optimized_view_port_width` argument to optional, aligning with the [AWS API object](https://docs.aws.amazon.com/quicksight/latest/APIReference/API_GridLayoutScreenCanvasSizeOptions.html).
Closes #32344
- https://docs.aws.amazon.com/quicksight/latest/APIReference/API_GridLayoutScreenCanvasSizeOptions.html
```console
$ make testacc PKG=quicksight TESTS="TestAccQuickSightAnalysis_|TestAccQuickSightDashboard_|TestAccQuickSightTemplate_"
TF_ACC=1 go test ./internal/service/quicksight/... -v -count 1 -parallel 20 -run='TestAccQuickSightAnalysis_|TestAccQuickSightDashboard_|TestAccQuickSightTemplate_'  -timeout 180m
--- PASS: TestAccQuickSightTemplate_disappears (79.72s)
--- PASS: …
```
=> r/aws_quicksight: grid layout `optimized_view_port_width` argument is optional

.changelog/32595.txt, internal/service/kms/grant.go, internal/service/kms/grant_test.go, internal/verify/validate.go, internal/verify/validate_test.go
Allow usage of service principals for KMS grants
Relates #25360
```
--- PASS: TestAccKMSGrant_service (22.83s)
--- PASS: TestAccKMSGrant_arn (33.14s)
--- PASS: TestAccKMSGrant_basic (33.30s)
--- PASS: TestAccKMSGrant_bare (40.71s)
--- PASS: TestAccKMSGrant_withRetiringPrincipal (41.12s)
--- PASS: TestAccKMSGrant_asymmetricKey (41.21s)
--- PASS: TestAccKMSGrant_withConstraints (53.18s)
--- PASS: TestAccKMSGrant_disappears (209.00s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/kms        212.279s
...
```
=> Allow usage of service principals for KMS grants

.changelog/32191.txt, internal/service/ec2/status.go, internal/service/ec2/vpc_nat_gateway.go, internal/service/ec2/vpc_nat_gateway_test.go, internal/service/ec2/wait.go
This PR adds support for defining secondary IP addresses to private NAT gateways. 
https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_CreateNatGateway.html
https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_AssignPrivateNatGatewayAddress.html
```
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 20 -run='TestAccVPCNATGateway_'  -timeout 180m
=== RUN   TestAccVPCNATGateway_basic
=== PAUSE TestAccVPCNATGateway_basic
=== RUN   TestAccVPCNATGateway_disappears
=== PAUSE TestAccVPCNATGateway_disappears
=== RUN   TestAccVPCNATGateway_ConnectivityType_private
=== PAUSE TestAccVPCNATGateway_ConnectivityType_private
=== RUN   TestAccVPCNATGateway_privateIP
=== PAUSE TestAccVPCNATGateway_privateIP
=== RUN   TestAccVPCNATGateway_privateIPWithSecondary
=== PAUSE …
```
=> r/vpc_nat_gateway: Add support for secondary IP addresses

website/docs/r/licensemanager_grant_accepter.html.markdown
Documentation example for `aws_licensemanager_grant_accepter` with argument `name` doesn't match actual required argument `grant_arn`.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/29741
=> docs: Fix example for aws_licensemanager_grant_accepter

website/docs/r/api_gateway_method_settings.html.markdown
Documentation update to `api_gateway_method_settings` in order to add examples that clarify to users of the AWS Console how CloudWatch Logging options match up to Terraform/AWS API options. These examples are also useful generically, as they give examples of the different logging/tracing capabilities of the resource.
Relates #29770
The AWS Console options in question:
Docs-only PR
```
...
```
=> docs: api_gateway_method_settings: Document Cloudwatch Logging Examples

.changelog/32669.txt, internal/service/elasticache/find.go, internal/service/elasticache/parameter_group.go, internal/service/elasticache/parameter_group_test.go
If a parameter group in state is not found in AWS during resource read, reset the group's ID to force its recreation instead of failing immediately.
Closes #18338.
Closes #32244.
Running now, will post when complete!
```console
% make testacc PKG=elasticache
```
=> r/aws_elasticache_parameter_group: reset ID if deleted manually

.changelog/32664.txt, internal/service/lightsail/domain_entry.go, internal/service/lightsail/domain_entry_test.go
When I try to add an AAAA record with `aws_lightsail_domain_entry`, I get an error with `terraform validate`.
```
Error: expected type to be one of [A CNAME MX NS SOA SRV TXT], got AAAA
```
Fixed `aws_lightsail_domain_entry` to support AAAA record type.
Relates #27309
IPv6 (AAAA) domain entry type is allowed in aws cli.
https://docs.aws.amazon.com/cli/latest/reference/lightsail/create-domain-entry.html#options
> The type of domain entry, such as address for IPv4 (A), address for IPv6 (AAAA), canonical name (CNAME), mail exchanger (MX), name server (NS), start of authority (SOA), service locator (SRV), or text (TXT).
```console
make testacc TESTS=TestAccLightsailDomainEntry PKG=lightsail …
```
=> r/aws_lightsail_domain_entry: support for AAAA record type

.changelog/32654.txt, internal/service/transfer/server.go, internal/service/transfer/server_data_source.go, internal/service/transfer/server_data_source_test.go, internal/service/transfer/server_test.go, internal/service/transfer/transfer_test.go, website/docs/d/transfer_server.html.markdown, website/docs/r/transfer_server.html.markdown
This PR adds support for the AWS Transfer Server Structured Logging Destinations property.
The AWS transfer module talks about this property [here](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/transfer#CreateServerInput)
Closes #32653 
Here is some sample terraform that uses the new property and shows that the changes work, assuming that you are overriding the aws provider with the version built with this PRs code.
```terraform
terraform {
aws = {
source = "hashicorp/aws"
}
}
}
resource "aws_cloudwatch_log_group" "test" {
name_prefix = "transfer_test_"
}
data "aws_iam_policy_document" "test" {
statement {
effect = "Allow"
principals {
type        = "Service"
identifiers = ["transfer.amazonaws.com"]
}
actions = ["sts:AssumeRole"]
}
}
resource "aws_iam_role" …
```
=> F aws transfer server structured logging destinations

.changelog/32659.txt, internal/service/elasticsearch/domain.go, internal/service/elasticsearch/domain_test.go, internal/service/elasticsearch/flex.go
This fix ensures that the Throughput and Iops EBS features are not incorporated when the selected volume type doesn't support them, for instance, gp2 EBS volume type.
This specifically can occur when a setup utilizes a gp3 volume type without mentioning iops or throughput, and then the volume type switches to a type that doesn't accept these parameters, like gp2. During the first terraform apply, the default values provided by AWS are written to state, and subsequent terraform apply should be excluded from the UpdateDomain request input to prevent error `Error: ValidationException: Throughput is only valid when volume type is GP3.`
Closes [#32613](https://github.com/hashicorp/terraform-provider-aws/issues/32613).
Same issue raised here with opensearch …
=> r/aws_elasticsearch_domain: omit iops/throughput when not supported

website/docs/r/cloudtrail.html.markdown
This PR fixes an example in the `aws_cloudtrail` documentation. This `advanced_event_selector`'s name is `"Log PutObject and DeleteObject events for two S3 buckets"`, so with a `field_selector.field` of `"resources.ARN"`, `starts_with` should be used instead of `equals` in order to catch the objects in the bucket, rather than the bucket itself.
Also removed a comment of `#The trailing slash is intentional; do not exclude it.`, as there was no trailing slash where it was referenced.
Closes #32619
Relates #28582
N/a, docs
=> Fix `aws_cloudtrail` docs examples

.changelog/32668.txt, internal/service/quicksight/schema/visual.go
This PR corrects a typo in the flattener `flattenDataLabelOptions`. Previously, an error was thrown of:
```shell
Error: setting definition: Invalid address to set: []string{"definition", "0", "sheets", "0", "visuals", "0", "pie_chart_visual", "0", "chart_configuration", "0", "data_labels", "0", "measure_visibility"}
```
This was due to the incorrect usage of `measure_visibility` over `measure_label_visibility`.
Closes #32652
I'm unfortunately not able to run these tests due to account restrictions
=> Correct type in Quicksight flattener `flattenDataLabelOptions`

.changelog/32679.txt, internal/service/grafana/wait.go, internal/service/grafana/workspace.go, internal/service/grafana/workspace_data_source_test.go, internal/service/grafana/workspace_test.go, website/docs/r/grafana_workspace.html.markdown
This PR updates the `aws_grafana_workspace` resource to allow in-place updates of the Grafana Version.
There don't seem to be any issues related to this.
The AWS API was updated to allow in-place upgrades of the workspace on or around July 19th ([blog post](https://aws.amazon.com/about-aws/whats-new/2023/07/amazon-managed-grafana-in-place-update-version-9-4/), [API documentation](https://docs.aws.amazon.com/grafana/latest/APIReference/API_UpdateWorkspaceConfiguration.html)).
```console
...
```
I have not been able to run the acceptance testing for this PR, as I'm unsure how to modify the acceptance tests to test an in-place upgrade. I have located the existing `testAccWorkspace_version` test and read the documentation, but I didn't find the …
=> r/aws_grafana_workspace: Allow in-place version updates

.github/workflows/issues.yml, .github/workflows/pull_request_target.yml
This PR corrects a few jobs related to `pull_request_target` and `issues` events so that community notes are only added when issues/PRs are opened, rather than on every event type.
Relates #32605
N/a, actions
=> Add conditionals to community comment jobs

.github/workflows/issues.yml, .github/workflows/pull_request_target.yml
When adding an item to the Project and then setting a field value, we need to capture the Project Item ID from the first command to use in subsequent ones. In a few of the steps for our Project automation workflows, the requisite `| jq '.id'` was missing, and so the Project Item ID was not properly captured. This PR corrects this bug.
Relates #32605
N/a, Actions
=> Properly filter `gh` output to capture Project Item ID

.github/workflows/pull_request_target.yml
It seems that pull requests from branches always have `maintainer_can_modify` set to `false`. This PR updates the conditional for the "Maintainers Can Modify" job to ensure that the comment isn't left on maintainer PRs by mistake.
Relates #32605 
N/a, Actions
=> Fix conditional for maintainer edit check

.github/workflows/issues.yml, .github/workflows/pull_request_target.yml
While #32684 did add the correct `jq` filter in order to capture Project Item IDs when an item was added to the Project, the `--format json` flag is needed in order for the `gh` command to actually output JSON to parse. This PR adds that missing flag.
- [`gh project item-add` reference](https://cli.github.com/manual/gh_project_item-add)
Relates #32605
Relates #32684
N/a, Actions
=> Add `--format json` flag to properly retrieve Project Item ID

website/docs/r/api_gateway_authorizer.html.markdown
It looks like the documentation of aws_api_gateway_authorizer contain an invalid datasource for role definition in the provided example.
This changes `aws_iam_role_policy_document` to `aws_iam_policy_document`.
NA
NA
=> Fix api_gateway_authorizer documentation example

internal/service/ecs/task_definition_test.go
Trying to qualifying issue #23541, I've seen that no test were covering this case (ECS task definition with encryption set to disabled and authorization_config also set to disable.
Closes #23541
Closes #19549
New test added: TestAccECSTaskDefinition_EFSVolume_transitEncryptionDisabled
Output:
```console
TF_ACC=1 go test ./internal/service/ecs/... -v -count 1 -parallel 20 -run='TestAccECSTaskDefinition_EFSVolume_transitEncryptionDisabled'  -timeout 180m
=== RUN   TestAccECSTaskDefinition_EFSVolume_transitEncryptionDisabled
=== PAUSE TestAccECSTaskDefinition_EFSVolume_transitEncryptionDisabled
=== CONT  TestAccECSTaskDefinition_EFSVolume_transitEncryptionDisabled
--- PASS: TestAccECSTaskDefinition_EFSVolume_transitEncryptionDisabled …
```
=> enhancement: add tests for ECS task definition EFS volume (#24921)

internal/service/finspace/sweep.go, internal/sweep/sweep_test.go
Adds a sweeper for the `aws_finspace_kx_environment` resource. All other `aws_finspace_kx_*` resources (cluster, database, user) live within an environment, so sweeping this resource will also delete those downstream components.
Relates #31802 
```console
$ make sweep SWEEPARGS="-sweep-run=aws_finspace"
go test ./internal/sweep -v -tags=sweep -sweep=us-west-2,us-east-1,us-east-2,us-west-1 -sweep-run=aws_finspace -timeout 60m
2023/07/21 11:31:46 [DEBUG] Running Sweepers for region (us-west-2):
2023/07/21 11:31:46 [DEBUG] Running Sweeper (aws_finspace_kx_environment) in region (us-west-2)
...
2023/07/21 11:32:10 [DEBUG] Completed Sweeper (aws_finspace_kx_environment) in region (us-west-1) in 475.936292ms
2023/07/21 …
```
=> r/aws_finspace: add sweepers

website/docs/r/db_instance.html.markdown
The `identifier` and `identifier_prefix` arguments of the `aws_db_instance` resource used to ForceNew on change, however, no longer do. This PR updates the documentation to align with current behavior.
Closes #32590
- [Schema](https://github.com/hashicorp/terraform-provider-aws/blob/10937b0e5d83aac494baa44f9b35e14564573be6/internal/service/rds/instance.go#L280-L293)
N/a, docs
=> Remove indication that `identifier` and `identifier_prefix` arguments of `aws_db_instance` force new on change

.changelog/32706.txt, internal/service/lambda/diff.go
Adds check so deferred input values in CRUD lifecycle mode plans successfully.
Closes #32118
```console
> make testacc TESTS=TestAccLambdaInvocation_ PKG=lambda
TF_ACC=1 go test ./internal/service/lambda/... -v -count 1 -parallel 20 -run='TestAccLambdaInvocation_'  -timeout 180m
--- PASS: TestAccLambdaInvocation_terraformKey (57.31s)
--- PASS: TestAccLambdaInvocation_lifecycle_scopeCRUDUpdateInput (57.78s)
--- PASS: TestAccLambdaInvocation_complex (68.52s)
--- PASS: TestAccLambdaInvocation_basic (74.43s)
--- PASS: TestAccLambdaInvocation_lifecycle_scopeCreateOnlyToCRUD (76.12s)
--- PASS: TestAccLambdaInvocation_lifecycle_scopeCRUDCreate (92.90s)
--- PASS: TestAccLambdaInvocation_lifecycle_scopeCreateOnlyUpdateInput (98.90s)
--- …
```
=> Adds check so deferred input values

website/docs/r/default_route_table.html.markdown
This PR removes two unused links at the bottom of `aws_default_route_table` that are causing strange rendering in the Registry.
Closes #32691
- [Registry docs](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/default_route_table#import)
N/a, docs
=> Remove unused links from `aws_default_route_table` docs

website/docs/cdktf/python/d/eks_cluster_auth.html.markdown, website/docs/cdktf/typescript/d/eks_cluster_auth.html.markdown, website/docs/d/eks_cluster_auth.html.markdown
The documentation for [eks_cluster_auth](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/eks_cluster_auth) has a scary warning referring to a terraform limitation that has been solved since. I suggest we  mention in the note that only terraform versions `<1.3.0` are affected by the problem.
* https://github.com/hashicorp/terraform/issues/13018#issuecomment-793108732
* https://github.com/hashicorp/terraform/issues/27934
* https://github.com/hashicorp/terraform/pull/31283
N/A, this is a documentation change
=> docs(aws_eks_cluster_auth): update outdated note on resource imports

infrastructure/repository/projects.tf
"Backlog" is no longer one of our Status options in the Project, so removing the variable from the infrastructure configuration.
N/a, Actions/Infra related
=> Remove `backlog` Project Status variable

.github/dependabot.yml
There is a top-level [`github.com/aws/aws-sdk-go-v2` Go module](https://github.com/aws/aws-sdk-go-v2/blob/main/go.mod) that should be included in the `aws-sdk-go` dependabot group.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/32422.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/32397.
=> Include top-level `github.com/aws/aws-sdk-go-v2` module in `aws-sdk-go` dependabot group

.ci/scripts/add-to-milestone.sh
This PR adds a condition to the `add-to-milestone.sh` script, used to add merged PRs and the issues that they close to the current milestone, such that failures don't occur when a merged PR doesn't close any additional issues.
Relates #32707
A couple of failed runs caused by not having this change:
- https://github.com/hashicorp/terraform-provider-aws/actions/runs/5684302407/job/15406701720
- https://github.com/hashicorp/terraform-provider-aws/actions/runs/5684283002/job/15406633532
- https://github.com/hashicorp/terraform-provider-aws/actions/runs/5684126080/job/15406151399
N/a, actions
=> Add to Milestone: Conditional check for related issues

website/docs/r/opensearchserverless_collection.html.markdown
- Added notices that `aws_opensearchserverless_security_policy` and `aws_opensearchserverless_access_policy` are required for network and data access
- Added default value for `aws_opensearchserverless_collection` `type`
N/A
- https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/opensearchserverless_collection
- https://docs.aws.amazon.com/opensearch-service/latest/developerguide/serverless-encryption.html
- https://docs.aws.amazon.com/opensearch-service/latest/developerguide/serverless-network.html
N/A
=> docs: Add additional documentation for `aws_opensearchserverless_collection`

.changelog/32746.txt, internal/service/networkfirewall/rule_group_test.go, website/docs/r/networkfirewall_rule_group.html.markdown
Adds formal support for the REJECT stateful rule action in the `aws_networkfirewall_rule_group` resource by adding acceptance tests and updating the documentation. Note that setting the REJECT action was possible previously due to the validation in `networkfirewall.StatefulAction_Values()`, but was not documented nor checked as part of the acceptance tests.
Closes #28957
What's New: https://aws.amazon.com/about-aws/whats-new/2023/01/aws-network-firewall-support-reject-action-tcp-traffic/
API: https://docs.aws.amazon.com/network-firewall/latest/APIReference/API_StatefulRule.html#networkfirewall-Type-StatefulRule-Action
SDK: https://github.com/aws/aws-sdk-go-v2/blob/service/networkfirewall/v1.28.5/service/networkfirewall/types/enums.go#L291
```console
$ make testacc …
```
=> Add REJECT action to Network Firewall rule group stateful rule actions

website/docs/r/dlm_lifecycle_policy.markdown
Added some documentation to note that you can't use both count and interval in a single DLM retention schedule retain_rule block (as experienced with terraform and confirmed in AWS documentation here: https://docs.aws.amazon.com/dlm/latest/APIReference/API_RetainRule.html)
Closes #0000
```console
...
```
=> Update DLM Docs to show that count and interval cannot be used together 

.teamcity/settings.kts
Adds failure condition to sweeper run to match region failures. This will highlight each regional failure in the Build Problems list
=> TeamCity: Add failure condition to sweeper run to match region failures

website/docs/r/ssm_parameter.html.markdown
This PR aims to clarify the changes in behavior caused by the deprecation of the `aws_ssm_parameter`'s `overwrite` argument by linking to an already well-written comment on a related issue.
Closes #32736
Relates #25636
- [Issue comment that's referenced](https://github.com/hashicorp/terraform-provider-aws/issues/25636#issuecomment-1623661159)
N/a, docs
=> `aws_ssm_parameter`: Clarify `overwrite` deprecation

website/docs/r/cloudfront_distribution.html.markdown
`default_cache_behavior` cannot specify `path_pattern`.
=> docs/r/cloudfront_distribution: Fix example of default_cache_behavior

.github/workflows/pull_request_target.yml
Previously, we were only adding PRs that were ready for review to the Project board, however, this caused some PRs to be missed due to a race condition with labeling. This PR simplifies the conditional such the drafts are now added as well, and the items are added as soon as they're labeled (in the case of maintainers, as soon as it's opened).
N/a, Actions
=> Improve conditionals for adding PRs to Project

.changelog/32791.txt, internal/service/quicksight/schema/visual_insight.go
This PR corrects a typo in the `flattenInsightConfiguration` function for QuickSight that caused the following error:
```shell
Error: setting definition: Invalid address to set: []string{"definition", "0", "sheets", "6", "visuals", "0", "insight_visual", "0", "insight_configuration", "0", "computations"}
```
The correct address to set is `computation` rather than `computations`.
Closes #32788
- [Schema reference (`insightVisualSchema`)](https://github.com/hashicorp/terraform-provider-aws/blob/216156267f7cdc1aa2f9160a7d26a4e841ac40f5/internal/service/quicksight/schema/visual_insight.go#L31)
I'm not able to run the acceptance tests for this one, unfortunately.
=> Correct typo in quicksight `schema.flattenInsightConfiguration`

website/docs/r/wafv2_web_acl_logging_configuration.html.markdown
This PR aims to make the documentation of `aws_wafv2_web_acl_logging_configuration` more clear about the requirement that the destination defined by `log_destination_configs` must be prefixed with `aws-waf-logs-`
Closes #32262
- [WAF: Amazon CloudWatch Logs](https://docs.aws.amazon.com/waf/latest/developerguide/logging-cw-logs.html)
- [WAF: Amazon Simple Storage Service](https://docs.aws.amazon.com/waf/latest/developerguide/logging-s3.html)
- [WAF: Amazon Kinesis Data Firehose](https://docs.aws.amazon.com/waf/latest/developerguide/logging-kinesis.html)
N/a, docs
=> `aws_wafv2_web_acl_logging_configuration`: Clarify destination naming requirements

.changelog/32793.txt, internal/service/ecs/task_execution_data_source.go
This PR corrects an issue where the `container_overrides` expander of the `aws_ecs_task_execution` data source incorrectly set the value of `memory_reservation` to the value of `memory`.
Closes #32785
- [`ecs.ContainerOverride`](https://docs.aws.amazon.com/sdk-for-go/api/service/ecs/#ContainerOverride)
```console
$ make testacc TESTS=TestAccECSTaskExecutionDataSource PKG=ecs
TF_ACC=1 go test ./internal/service/ecs/... -v -count 1 -parallel 20 -run='TestAccECSTaskExecutionDataSource'  -timeout 180m
=== RUN   TestAccECSTaskExecutionDataSource_basic
=== PAUSE TestAccECSTaskExecutionDataSource_basic
=== RUN   TestAccECSTaskExecutionDataSource_overrides
=== PAUSE TestAccECSTaskExecutionDataSource_overrides
=== RUN …
```
=> Correct `aws_ecs_task_execution` data source `container_overrides` expander

internal/service/iam/openid_connect_provider_data_source_test.go
Fixes broken `aws_iam_openid_connect_provider` data source tests by providing a non-empty `thumbprint_lists` entry. This brings the data source test config into alignment with the corresponding resource tests.
```console
$ make testacc PKG=iam TESTS=TestAccIAMOpenidConnectProviderDataSource_
TF_ACC=1 go test ./internal/service/iam/... -v -count 1 -parallel 20 -run='TestAccIAMOpenidConnectProviderDataSource_'  -timeout 180m
=== NAME  TestAccIAMOpenidConnectProviderDataSource_basic
openid_connect_provider_data_source_test.go:22: Step 1/1 error: Error running apply: exit status 1
Error: creating IAM OIDC Provider: InvalidInput: Thumbprint list must contain at least one entry.
status code: 400, request id: …
```
=> d/aws_iam_openid_connect_provider(test): add thumbprint_list test config

go.mod, go.sum, internal/conns/awsclient_gen.go, internal/service/mediapackage/channel.go, internal/service/mediapackage/channel_test.go, internal/service/mediapackage/export_test.go, internal/service/mediapackage/generate.go, internal/service/mediapackage/service_package_gen.go, internal/service/mediapackage/sweep.go, internal/service/mediapackage/tags_gen.go, internal/sweep/sweep_test.go, names/names_data.csv
sdkv1 -> sdkv2
```console
$ make testacc TESTARGS='-run=TestAccMediaPackageChannel_' PKG=mediapackage
TF_ACC=1 go test ./internal/service/mediapackage/... -v -count 1 -parallel 20  -run=TestAccMediaPackageChannel_ -timeout 180m
--- PASS: TestAccMediaPackageChannel_disappears (17.76s)
--- PASS: TestAccMediaPackageChannel_basic (22.48s)
--- PASS: TestAccMediaPackageChannel_description (35.69s)
--- PASS: TestAccMediaPackageChannel_tags (52.90s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/mediapackage	56.004s
```
```console
$ make sweep SWEEPARGS=-sweep-run=aws_media_package_channel
go test ./internal/sweep -v -tags=sweep …
```
=> td/mediapackage: convert to sdkv2

docs/acc-test-environment-variables.md, internal/service/finspace/finspace_test.go, internal/service/finspace/kx_cluster_test.go, internal/service/finspace/kx_database_test.go, internal/service/finspace/kx_environment_test.go, internal/service/finspace/kx_user_test.go
Serializes tests for FinSpace managed kdb resources, as the default quota for kdb environments in an account is 1. Also gates the Kx Cluster resource tests with an environment variable (`FINSPACE_MANAGED_KX_LICENSE_ENABLED`), as these require an active license before resources can be provisioned.
Closes #32646 
- https://docs.aws.amazon.com/finspace/latest/userguide/finspace-quotas.html
```console
$ make testacc TESTARGS='-run=TestAccFinSpace_serial/KxUser' PKG=finspace
TF_ACC=1 go test ./internal/service/finspace/... -v -count 1 -parallel 20  -run=TestAccFinSpace_serial/KxUser -timeout 180m
--- PASS: TestAccFinSpace_serial (4054.43s)
--- PASS: TestAccFinSpace_serial/KxUser (4054.43s)
--- PASS: TestAccFinSpace_serial/KxUser/basic …
```
=> r/aws_finspace(test): serialize finspace managed kdb tests

internal/service/auditmanager/assessment_delegation_test.go, internal/service/auditmanager/assessment_report_test.go
Fixes various AuditManager acceptance tests currently failing due to unnecessary S3 bucket ACL configurations. 
Relates #28353
```console
$ make testacc PKG=auditmanager TESTS=TestAccAuditManagerAssessmentReport_
TF_ACC=1 go test ./internal/service/auditmanager/... -v -count 1 -parallel 20 -run='TestAccAuditManagerAssessmentReport_'  -timeout 180m
--- PASS: TestAccAuditManagerAssessmentReport_disappears (34.13s)
--- PASS: TestAccAuditManagerAssessmentReport_basic (36.60s)
--- PASS: TestAccAuditManagerAssessmentReport_optional (71.64s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/auditmanager       74.712s
```
```console
$ make testacc PKG=auditmanager TESTS=TestAccAuditManagerAssessmentDelegation_
==> …
```
=> [TechDebt]: AuditManager acceptance test fixes

internal/service/firehose/delivery_stream_data_source_test.go
Fixes `TestAccFirehoseDeliveryStreamDataSource_basic`
```console
$ make testacc PKG=firehose TESTS=TestAccFirehoseDeliveryStreamDataSource_basic
TF_ACC=1 go test ./internal/service/firehose/... -v -count 1 -parallel 20 -run='TestAccFirehoseDeliveryStreamDataSource_basic'  -timeout 180m
=== RUN   TestAccFirehoseDeliveryStreamDataSource_basic
=== PAUSE TestAccFirehoseDeliveryStreamDataSource_basic
=== CONT  TestAccFirehoseDeliveryStreamDataSource_basic
delivery_stream_data_source_test.go:22: Step 1/1 error: Error running apply: exit status 1
Error: creating S3 bucket ACL for tf-acc-test-7814311428223815511: AccessControlListNotSupported: The bucket does not allow ACLs
status code: 400, request id: CDJJX5A0NMYPE93X, host id: …
```
=> d/aws_kinesis_firehose_delivery_stream(test): rm unnecessary s3 bucket acl config

website/docs/r/autoscaling_policy.html.markdown
Fixes a typo in the website docs.
=> fix: typo in autoscaling policy website docs

internal/service/chimesdkvoice/global_settings.go, internal/service/chimesdkvoice/global_settings_test.go
retry for eventual consistency
```
=== RUN   TestAccChimeSDKVoiceGlobalSettings_serial
=== PAUSE TestAccChimeSDKVoiceGlobalSettings_serial
=== CONT  TestAccChimeSDKVoiceGlobalSettings_serial
=== RUN   TestAccChimeSDKVoiceGlobalSettings_serial/basic
global_settings_test.go:42: Step 1/2 error: Check failed: 1 error occurred:
* Check 1/1 error: aws_chimesdkvoice_global_settings.test: Attribute 'voice_connector.0.cdr_bucket' expected "tf-acc-test-1708425151533450177", got ""
=== RUN   TestAccChimeSDKVoiceGlobalSettings_serial/disappears
=== RUN   TestAccChimeSDKVoiceGlobalSettings_serial/update
global_settings_test.go:92: Step 1/2 error: Check failed: 1 error occurred:
* Check 1/1 error: aws_chimesdkvoice_global_settings.test: Attribute 'voice_connector.0.cdr_bucket' …
```
=> b/aws_chimesdkvoice_global_settings: retry if cdr_bucket is empty

internal/service/codepipeline/webhook_test.go
Fixes various failing CodePipeline webhook tests.
```
=== RUN   TestAccCodePipelineWebhook_basic
webhook_test.go:33: Step 1/4 error: Error running apply: exit status 1
Error: creating S3 bucket ACL for tf-acc-test-9087582508599795569: AccessControlListNotSupported: The bucket does not allow ACLs
status code: 400, request id: N6C694HZWNDV0CE1, host id: KD7bXq7B+xTRj/mnXYzJq0ELZMB47mLeti6JkcjnpODryTmWKUE/xIkAD0ZUwdw/eFpilchUMFk=
on terraform_plugin_test.tf line 6, in resource "aws_s3_bucket_acl" "test":
6: resource "aws_s3_bucket_acl" "test" {
--- FAIL: TestAccCodePipelineWebhook_basic (190.90s)
FAIL
```
Relates #28353
Acceptance testing requires configuration of a github token, so it has been omitted for this small change.
=> r/aws_codepipeline_webhook(test): rm unnecessary s3 bucket acl config

internal/service/ec2/vpc_flow_log_test.go
Fixes `TestAccVPCFlowLog_LogDestinationType_kinesisFirehose`.
```
=== CONT  TestAccVPCFlowLog_LogDestinationType_kinesisFirehose
vpc_flow_log_test.go:241: Step 1/2 error: Error running apply: exit status 1
Error: creating S3 bucket ACL for tf-acc-test-3743026901492570258: AccessControlListNotSupported: The bucket does not allow ACLs
status code: 400, request id: QS66CNJCRGPHZTK1, host id: HPiQQnD2kgRVJuFyQsNyc2YI0ZJxqoDIW2bKFYsnN9dx3XMZnEKkO1a8686hF9JXPfcrvAs0THQ=
with aws_s3_bucket_acl.bucket_acl,
on terraform_plugin_test.tf line 61, in resource "aws_s3_bucket_acl" "bucket_acl":
61: resource "aws_s3_bucket_acl" "bucket_acl" {
--- FAIL: TestAccVPCFlowLog_LogDestinationType_kinesisFirehose (124.90s)
FAIL
FAIL    github.com/hashicorp/terraform-provider-aws/internal/service/ec2 …
```
=> r/aws_flow_log: rm unnecessary s3 bucket acl config

internal/service/fsx/lustre_file_system_test.go
Fixes various Fsx Lustre File System acceptance tests. Ex.
```
=== RUN   TestAccFSxLustreFileSystem_importPath
=== PAUSE TestAccFSxLustreFileSystem_importPath
=== CONT  TestAccFSxLustreFileSystem_importPath
lustre_file_system_test.go:188: Step 1/3 error: Error running apply: exit status 1
Error: creating S3 bucket ACL for tf-acc-test-3952770834720244221: AccessControlListNotSupported: The bucket does not allow ACLs
status code: 400, request id: 4DDSKPHFA35Z8HNZ, host id: /TifripjoiLbjfcBU0XCc5OT0r5clLgHs4b4wMrjTrbBRlFFkzLuqB0m5vDPzxNmH9Dh/bXKvsIrkW4Q6EryTQ==
on terraform_plugin_test.tf line 27, in resource "aws_s3_bucket_acl" "test":
27: resource "aws_s3_bucket_acl" "test" {
--- FAIL: TestAccFSxLustreFileSystem_importPath (1096.68s)
FAIL
```
Relates #28353 …
=> r/aws_fsx_lustre_file_system(test): rm unnecessary s3 bucket acl config

internal/service/guardduty/ipset_test.go, internal/service/guardduty/publishing_destination_test.go, internal/service/guardduty/threatintelset_test.go
Fixes various GuardDuty acceptance tests failing due to unnecessary s3 bucket private ACL configurations.
Relates #28353
Due to an existing active GuardDuty detector setup, acceptance tests have been omitted for this change.
=> r/aws_guardduty(test): rm unnecessary s3 bucket acl config

.changelog/32822.txt, internal/service/quicksight/schema/template_filter.go
This PR corrects an issue with QuickSight resources that led to the incorrect function being used to return the list of valid values for `select_all_options`.
Closes #32353
These references point to the AWS Go SDK type definition for each of the affected filter types
- [`CustomFilterConfiguration`  (`category_filter.configuration.custom_filter_configuration`)](https://docs.aws.amazon.com/sdk-for-go/api/service/quicksight/#CustomFilterConfiguration)
- [`CustomFilterListConfiguration` (`category_filter.configuration.custom_filter_list_configuration`)](https://docs.aws.amazon.com/sdk-for-go/api/service/quicksight/#CustomFilterListConfiguration)
- [`FilterListConfiguration` (`category_filter.configuration.filter_list_configuration`)](https://docs.aws.amazon.com/sdk-for-go/api/service/quicksigh …
=> QuickSight: Use correct enums for template filters

internal/service/kafkaconnect/custom_plugin_test.go
Fixes all KafkaConnect acceptance tests. Ex.
```
=== CONT  TestAccKafkaConnectCustomPlugin_basic
custom_plugin_test.go:26: Step 1/2 error: Error running apply: exit status 1
Error: creating S3 bucket ACL for tf-acc-test-1956275692564207789: AccessControlListNotSupported: The bucket does not allow ACLs
status code: 400, request id: VKPTC8VAYD8HK0C8, host id: 41E3II9kxBBvOaq+4CFLV3Q+ncBwRHagK5IWGVTrKmdR7IzJst6E7gaz8EmFuZ/bYovRyEMupt8=
on terraform_plugin_test.tf line 7, in resource "aws_s3_bucket_acl" "test":
7: resource "aws_s3_bucket_acl" "test" {
--- FAIL: TestAccKafkaConnectCustomPlugin_basic (93.71s)
```
Relates #28353
```console
$ make testacc PKG=kafkaconnect TESTS=TestAccKafkaConnect
TF_ACC=1 go …
```
=> r/aws_mskconnect_custom_plugin(test): rm unnecessary s3 bucket acl config

internal/service/lambda/permission_test.go
Fixes `TestAccLambdaPermission_s3`. Ex.
```
=== CONT  TestAccLambdaPermission_s3
permission_test.go:538: Step 1/2 error: Error running apply: exit status 1
Error: creating S3 bucket ACL for tf-acc-test-2858722411593140646: AccessControlListNotSupported: The bucket does not allow ACLs
status code: 400, request id: A3AWWVHDKM1Z3CTF, host id: Xo+b7xd9YhwQ+wYRq1MJWl/3ArXHAFHoKLXm7rt52xS8Y2X39Nyn+0Fq187aK3uhHu8HuRTEhFk=
on terraform_plugin_test.tf line 42, in resource "aws_s3_bucket_acl" "test":
42: resource "aws_s3_bucket_acl" "test" {
--- FAIL: TestAccLambdaPermission_s3 (164.94s)
```
Relates #28353
```console
$ make testacc PKG=lambda TESTS=TestAccLambdaPermission_s3 …
```
=> r/aws_lambda_permission(test): rm unnecessary s3 bucket acl config

internal/service/logs/subscription_filter_test.go
Fixes `TestAccLogsSubscriptionFilter_DestinationARN_kinesisDataFirehose`. Ex.
```
=== CONT  TestAccLogsSubscriptionFilter_DestinationARN_kinesisDataFirehose
subscription_filter_test.go:131: Step 1/2 error: Error running apply: exit status 1
Error: creating S3 bucket ACL for tf-acc-test-8101964666717860644: AccessControlListNotSupported: The bucket does not allow ACLs
status code: 400, request id: 60M3E3945ZDRNC9P, host id: eDX4jJLFVUnjK23WBdIhT6v4N1vEbsDpsm00/xrPBNuJCK6J/2najOcToHUgUeGkMEudUeVJ1ds=
on terraform_plugin_test.tf line 123, in resource "aws_s3_bucket_acl" "test":
123: resource "aws_s3_bucket_acl" "test" {
--- FAIL: TestAccLogsSubscriptionFilter_DestinationARN_kinesisDataFirehose (276.53s)
FAIL
```
Relates #28353
```console
$ make testacc PKG=logs …
```
=> r/aws_cloudwatch_log_subscription_filter(test): rm unnecessary s3 bucket acl config

internal/service/sagemaker/device_fleet_test.go, internal/service/sagemaker/device_test.go, internal/service/sagemaker/endpoint_test.go, internal/service/sagemaker/project_test.go
Removes unnecessary s3 bucket private ACL configurations in various Sagemaker acceptance tests. 
Relates #28353
Acceptance tests for these resources are still failing due to issues unrelated to s3 bucket ACL configurations, so have been omitted for this change.
=> r/aws_sagemaker(test): rm unnecessary s3 bucket acl config

internal/service/servicecatalog/constraint_test.go, internal/service/servicecatalog/provisioning_artifacts_data_source_test.go
Fixes various ServiceCatalog acceptance tests currently failing due to unnecessary s3 bucket private ACL configurations. Ex.
```
=== CONT  TestAccServiceCatalogConstraint_basic
constraint_test.go:29: Step 1/2 error: Error running apply: exit status 1
Error: creating S3 bucket ACL for tf-acc-test-5666842783629746405: AccessControlListNotSupported: The bucket does not allow ACLs
status code: 400, request id: 4GHHS9D69MGDNFGV, host id: 83QwDfKELY/mJXYy92Qsc8r4BUIYzeYOjNdzb0dQDXoZoFSYlwUU10387OOAKkr3qd3TJzq9mwk=
on terraform_plugin_test.tf line 7, in resource "aws_s3_bucket_acl" "test":
7: resource "aws_s3_bucket_acl" "test" {
--- FAIL: TestAccServiceCatalogConstraint_basic (198.42s)
FAIL
```
Relates #28353
```console
$ make testacc PKG=servicecatalog …
```
=> r/aws_servicecatalog(test): rm unnecessary s3 bucket acl config

internal/service/ssm/maintenance_window_task_test.go
Fixes various SSM maintenance window task acceptance tests currently failing due to unnecessary s3 bucket private ACL configurations. Ex.
```
=== CONT  TestAccSSMMaintenanceWindowTask_taskInvocationAutomationParameters
maintenance_window_task_test.go:236: Step 2/3 error: Error running apply: exit status 1
Error: creating S3 bucket ACL for tf-acc-test-3829482191630859843: AccessControlListNotSupported: The bucket does not allow ACLs
status code: 400, request id: ZSNDXNGS8P2GCSPY, host id: k8oRkw9osENclKT/NV1nUWWc3YAhut2daUPhHOp8QDvaXptX3FtSj4yEH74/nmfizp0wJ3KHRe8=
on terraform_plugin_test.tf line 61, in resource "aws_s3_bucket_acl" "test":
61: resource "aws_s3_bucket_acl" "test" {
--- FAIL: TestAccSSMMaintenanceWindowTask_taskInvocationAutomationParameters …
```
=> r/aws_ssm_maintenance_window_task(test): rm unnecessary s3 bucket acl config

internal/service/transfer/access_test.go
Removes unnecessary s3 bucket private ACL configuration from the Transfer Access acceptance test S3 configuration.
Relates #28353
```console
$ make testacc PKG=transfer TESTS=TestAccTransfer_serial/Access/S3Basic
TF_ACC=1 go test ./internal/service/transfer/... -v -count 1 -parallel 20 -run='TestAccTransfer_serial/Access/S3Basic'  -timeout 180m
=== RUN   TestAccTransfer_serial
=== PAUSE TestAccTransfer_serial
=== CONT  TestAccTransfer_serial
=== RUN   TestAccTransfer_serial/Access
=== RUN   TestAccTransfer_serial/Access/S3Basic
--- PASS: TestAccTransfer_serial (972.65s)
--- PASS: TestAccTransfer_serial/Access (972.65s)
--- PASS: TestAccTransfer_serial/Access/S3Basic (972.65s)
PASS
ok …
```
=> r/aws_transfer_access(test): rm unnecessary s3 bucket acl config

.changelog/32794.txt, internal/service/ec2/vpc_route_data_source_test.go, internal/service/ec2/vpc_route_table.go, internal/service/ec2/vpc_route_table_test.go, internal/service/ec2/vpc_route_test.go, website/docs/r/route_table.html.markdown
This PR is similar to the changes made in #24507, which addressed `aws_route`. This PR addresses `aws_route_table` inline routes.
Because `aws_route_table` performs dual functions 1) as a parent in the parent-child relationship with `aws_route`, and 2) as a means of managing routes inline with `route` blocks, this enhancement is a bit more complicated than the scenario in `aws_route`.
Normally, `aws_route_table` ignores default `local` routes. In order to not introduce a massive breaking change, these changes preserve the previous behavior of typically ignoring the `local` routes created by AWS. However, now we want to manage these routes a bit more. We use `hasLocalConfig()` along with `flattenRoutes()` to prevent _default_ `local` routes from being stored in state (the previous …
=> vpc/route_table: Allow local inline routes

internal/service/ses/receipt_rule_test.go
Fixes `TestAccSESReceiptRule_s3Action`. With the recent S3 security changes, the bucket ACL configuration now also requires public access and bucket ownership resources. 
Ex.
```
=== CONT  TestAccSESReceiptRule_s3Action
receipt_rule_test.go:75: Step 1/2 error: Error running apply: exit status 1
Error: creating S3 bucket ACL for tf-acc-test-3436288263627848983: AccessDenied: Access Denied
status code: 403, request id: VPT00NNST9HPF5WH, host id: 8QCykSjzxw4JXwfYx+JvTFVLIWUXCWuXgR12yJjR6+s05Klr3Nsyf1RcZ6xwuaJPoItoU/0aHj0=
on terraform_plugin_test.tf line 11, in resource "aws_s3_bucket_acl" "test":
11: resource "aws_s3_bucket_acl" "test" {
--- FAIL: TestAccSESReceiptRule_s3Action (187.20s)
```
Relates #28353
```console
% make testacc PKG=ses …
```
=> r/aws_ses_receipt_rule(test): fix s3 bucket acl config

.github/dependabot.yml
The dependabot checks for the top-level `go.mod` are still timing out, e.g. https://github.com/hashicorp/terraform-provider-aws/network/updates/705091724.
Reverts #32858.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/32858.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/32733.
=> Top-level `go.mod` dependabot check times out

.github/workflows/issues.yml, .github/workflows/pull_request_target.yml
This PR moves the `issues.yml` and `pull_request_target.yml` workflows over to use a GitHub App for authentication when labeling or adding items to the GitHub Project. This is necessary, as using the automatically generated GitHub token does not allow the workflow to trigger itself, so when the workflows label something (e.g. with `partner`), it won't re-trigger the workflow, causing the `label` event, which is what we rely on to add the item to the project.
Note: this will require ensuring that our GitHub App has write permissions for issues and pull requests, as well as read/write for organization projects.
- [An example](https://github.com/hashicorp/terraform-provider-aws/actions/runs/5754481875/job/15599855690) of a partner PR being opened, labeled appropriately, and not being added …
=> Move `issues` and `pull_request_target` workflows to GitHub App

.changelog/32866.txt, internal/service/emr/instance_fleet.go
This adds another error message from the AWS api to be ignored when trying to delete an AWS EMR Instance Fleet which does not support "delete". Its lifecycle is instead linked to the EMR cluster.
Closes #31375
The acceptance testing failed but I'm fairly certain this is due to the locked down nature of the AWS Accounts that I have access to in my org. I would be very grateful if someone with a known working acceptance testing setup could reproduce this and maybe add their output.
I verified the fix with a cluster setup that was failing for my org using the published provider versions.
```console
% make testacc TESTARGS='-run=TestAccEMRCluster_ebs\|TestAccEMRCluster_basic' PKG=emr ACCTEST_PARALLELISM=2 …
```
=> Ignore additional error when deleting fleet

internal/service/rds/cluster_instance_test.go, internal/service/rds/cluster_test.go, internal/service/rds/instance_test.go
Updated AccTests that use KMS keys to limit Principal.
Closes #0000
```console
make testacc TESTARGS='-run=TestAccRDSInstance_SnapshotIdentifier_performanceInsightsEnabled\|TestAccRDSInstance_ReplicateSourceDB_performanceInsightsEnabled\|TestAccRDSInstance_ManagedMasterPassword_managedSpecificKMSKey\|TestAccRDSClusterInstance_kmsKey\|TestAccRDSCluster_kmsKey\|TestAccRDSCluster_ReplicationSourceIdentifier_kmsKeyID\|TestAccRDSInstance_kmsKey' PKG=rds ACCTEST_PARALLELISM=4
TF_ACC=1 go test ./internal/service/rds/... -v -count 1 -parallel 4  -run=TestAccRDSInstance_SnapshotIdentifier_performanceInsightsEnabled\|TestAccRDSInstance_ReplicateSourceDB_performanceInsightsEnabled\|TestAccRDSInstance_ManagedMasterPassword_managedSpecificKMSKe …
```
=> RDS AccTests - KMS Keys

.changelog/32882.txt, internal/service/events/target.go, internal/service/events/target_test.go, website/docs/r/cloudwatch_event_target.html.markdown
Closes #21374
```console
% make testacc TESTS=TestAccEventsTarget_sageMakerPipeline  PKG=events
--- PASS: TestAccEventsTarget_sageMakerPipeline (39.60s)
```
=> cloudwatch_events_target - add sagemaker pipeline support 

website/docs/r/s3_bucket_lifecycle_configuration.html.markdown
Add a note in the `aws_s3_bucket_lifecycle_configuration` resource documentation page to warn about the way propagation delays for that resource can affect Terraform. In particular, the fact that lifecycle configurations are not immediately reliably available after creation can cause Terraform configuration to be unpredictably and non-deterministically non-idempotent.
None.
Propagation delay is explained in [user documentation](https://docs.aws.amazon.com/AmazonS3/latest/userguide/how-to-set-lifecycle-configuration-intro.html), but not explicitly linked to the effects this could have on Terraform.
None. The change is documentation only.
=> docs(s3_bucket_lifecycle_configuration): add note about propagation delay

website/docs/r/ssmcontacts_contact.html.markdown, website/docs/r/ssmcontacts_contact_channel.html.markdown
Additional documentation to the "aws_ssmcontacts_contact" and "aws_ssmcontacts_contact_channel" to reflect the validation requirements on the alias and name arguments.
I didn't find any documentation to reference, but I pulled the information from the error messages in the AWS console.
No change to code
=> Added validation info to documentation for ssm contacts

.changelog/32898.txt, internal/service/glue/crawler.go, internal/service/glue/crawler_test.go, website/docs/r/glue_crawler.html.markdown
[AWS announcement](https://aws.amazon.com/about-aws/whats-new/2023/07/aws-glue-crawlers-apache-hudi-tables/).
```console
% make testacc TESTS=TestAccGlueCrawler_hudiTarget  PKG=glue
--- PASS: TestAccGlueCrawler_hudiTarget (85.72s)
```
=> r/glue_crawler - add hudi target support

internal/acctest/acctest.go, internal/service/chime/voice_connector_group_test.go, internal/service/chime/voice_connector_logging_test.go, internal/service/chime/voice_connector_origination_test.go, internal/service/chime/voice_connector_streaming_test.go, internal/service/chime/voice_connector_termination_credentials_test.go, internal/service/chime/voice_connector_termination_test.go, internal/service/chime/voice_connector_test.go
```console
=== CONT  TestAccChimeVoiceConnectorGroup_basic
voice_connector_group_test.go:28: Step 1/2 error: Error running apply: exit status 1
Error: creating Chime Voice connector: ForbiddenException: Not authorized to call Chime SDK with Account
```
```console
...
```
=> [Tests]: skip `chime` test when ForbiddenException

internal/service/s3control/access_point_policy_test.go, internal/service/s3control/access_point_test.go
In CI:
```
=== RUN   TestAccS3ControlAccessPoint_policy
=== PAUSE TestAccS3ControlAccessPoint_policy
=== CONT  TestAccS3ControlAccessPoint_policy
access_point_test.go:182: Step 1/4 error: Error running apply: exit status 1
Error: creating S3 Access Point (187416307283:tf-acc-test-4053537077800599509) policy: AccessDenied: Access Denied
status code: 403, request id: VJ0Y2JRJ2S4XDVY8, host id: 0OvEyis7Cn9glXHblD2pAluefQaLv3GF1cTOCRBvC/h7xAtqG7AqV60TGDG6OoUY8xvfLqzzQNo=
with aws_s3_access_point.test,
on terraform_plugin_test.tf line 6, in resource "aws_s3_access_point" "test":
6: resource "aws_s3_access_point" "test" {
--- FAIL: TestAccS3ControlAccessPoint_policy (171.18s)
```
```
=== RUN   TestAccS3ControlAccessPointPolicy_basic
=== PAUSE TestAccS3ControlAccessPointPolicy_basic
=== CONT …
```
=> r/aws_s3control_access_point(_policy): Fix acceptance test `AccessDenied` errors

.changelog/32890.txt, internal/service/lambda/event_source_mapping.go
This pull request updates the `MaxItems` of `aws_lambda_event_source_mapping.filter_critera.filter` from 5 to 10; while 5 is the default maximum, users can request AWS to increase their limit up to 10.
Closes #32806
- [AWS: Lamda event filtering](https://docs.aws.amazon.com/lambda/latest/dg/invocation-eventfiltering.html)
> If you need to define more than five filters for an event source, you can request a quota increase up to 10 filters for each event source. If you attempt to add more filters than your current quota permits, Lambda will return an error when you try and create the event source.
```console
$ make testacc TESTS=TestAccLambdaEventSourceMapping PKG=lambda
TF_ACC=1 go test ./internal/service/lambda/... -v -count 1 …
```
=> Increase `MaxItems` of `aws_lambda_event_source_mapping.filter_critera.filter` from 5 to 10

website/docs/r/eks_cluster.html.markdown
This update to the `aws_eks_cluster` documentation changes the value used for the `thumbprint_list` argument of the `aws_iam_openid_connect_provider` in one of the examples. OpenID Connect IdP can contain a maximum of 5 thumbprints; a limit that could be exceeded by using all of the thumbprints available in a given certificate. At the same time, AWS documents that only the top intermediate CA cert is needed. This change follows that pattern.
Closes #32847
- [AWS: Obtaining the thumbprint for an OpenID Connect Identity Provider](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_providers_create_oidc_verify-thumbprint.html)
> When you [create an OpenID Connect (OIDC) identity provider](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_providers_create_oidc.html) in IAM, you …
=> Update EKS Cluster docs example to limit OIDC thumbprint list

website/docs/r/cloudwatch_event_rule.html.markdown
The `name_prefix` argument of the `aws_cloudwatch_event_rule` resource generates a 26 character suffix, leaving 38 characters to stay under the 64 character limit of a rule's name. This PR adds a small note to the documentation as a helpful reminder of this limitation.
Closes #32838
- [Schema ValidateFunc](https://github.com/hashicorp/terraform-provider-aws/blob/5abea1af47a16e81007742638bdb8aa2c98ccfd0/internal/service/events/validate.go#L19-L22)
N/a, docs
=> Add note on character limit for `aws_cloudwatch_event_rule.name_prefix`

internal/service/autoscalingplans/scaling_plan_test.go
In CI:
```
=== RUN   TestAccAutoScalingPlansScalingPlan_basicUpdate
=== PAUSE TestAccAutoScalingPlansScalingPlan_basicUpdate
=== CONT  TestAccAutoScalingPlansScalingPlan_basicUpdate
scaling_plan_test.go:152: Step 1/3 error: Error running pre-apply refresh: exit status 1
Error: Unsupported argument
on terraform_plugin_test.tf line 51, in resource "aws_autoscaling_group" "test":
51:   tags = [
An argument named "tags" is not expected here.
--- FAIL: TestAccAutoScalingPlansScalingPlan_basicUpdate (9.20s)
```
Relates https://github.com/hashicorp/terraform-provider-aws/issues/30842.
```console
% make testacc TESTARGS='-run=TestAccAutoScalingPlansScalingPlan_' PKG=autoscalingplans ACCTEST_PARALLELISM=2  …
```
=> Auto Scaling Plans: Fix acceptance test failures

website/docs/r/ce_anomaly_subscription.html.markdown
This pull request to improve documentation of `aws_ce_anomaly_susbcription` resource argument  which is`threshold_expression` about how add expression when we need to use `and` 
Closes #32780
=> add example for threshold expression and

internal/service/s3/bucket.go, internal/service/s3/bucket_logging_test.go, internal/service/s3/bucket_server_side_encryption_configuration.go, internal/service/s3/bucket_server_side_encryption_configuration_test.go, internal/service/s3/errors.go, website/docs/r/s3_bucket_server_side_encryption_configuration.html.markdown
In CI:
```
=== RUN   TestAccS3BucketLogging_TargetGrantByID
=== PAUSE TestAccS3BucketLogging_TargetGrantByID
=== CONT  TestAccS3BucketLogging_TargetGrantByID
bucket_logging_test.go:135: Step 1/5 error: Error running apply: exit status 1
Error: putting S3 Bucket (tf-acc-test-8739557163735717587) Logging: AccessControlListNotSupported: Target grants not allowed for bucket owner enforced buckets
status code: 400, request id: 73DCYBG0A6MCFTHP, host id: n09yProXlsJSmeGGT2jZV0ePTsMvMncvsYlsfx2izZFD8sxN/XM0A6LVdmUJoXB8X4QgL/kOwFk=
with aws_s3_bucket_logging.test,
on terraform_plugin_test.tf line 33, in resource "aws_s3_bucket_logging" "test":
33: resource "aws_s3_bucket_logging" "test" {
--- FAIL: TestAccS3BucketLogging_TargetGrantByID (165.24s)
```
Relates …
=> S3: Fix acceptance test errors

.changelog/32928.txt, internal/service/rds/cluster.go, internal/service/rds/instance.go
This pull request resolves the bug related to the empty, not-null `restore_to_point_in_time` block for `aws_db_instance` resource.
Closes #32907
```console
% make testacc TESTS=TestAccRDSInstance_RestoreToPointInTime_sourceResourceID PKG=rds
TF_ACC=1 go test ./internal/service/rds/... -v -count 1 -parallel 20 -run='TestAccRDSInstance_RestoreToPointInTime_sourceResourceID'  -timeout 180m
=== RUN   TestAccRDSInstance_RestoreToPointInTime_sourceResourceID
=== PAUSE TestAccRDSInstance_RestoreToPointInTime_sourceResourceID
=== CONT  TestAccRDSInstance_RestoreToPointInTime_sourceResourceID
--- PASS: TestAccRDSInstance_RestoreToPointInTime_sourceResourceID (1344.35s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/r …
```
=> B aws db instance empty restore to point in time bug 32907

internal/service/redshift/find.go, internal/service/redshift/snapshot_copy_grant.go, internal/service/redshift/snapshot_copy_grant_test.go, internal/service/redshift/snapshot_schedule.go, internal/service/redshift/snapshot_schedule_association.go, internal/service/redshift/snapshot_schedule_association_test.go, internal/service/redshift/snapshot_schedule_test.go, internal/service/redshift/status.go, internal/service/redshift/wait.go
In CI:
```
=== RUN   TestAccRedshiftSnapshotCopyGrant_update
=== PAUSE TestAccRedshiftSnapshotCopyGrant_update
=== CONT  TestAccRedshiftSnapshotCopyGrant_update
snapshot_copy_grant_test.go:55: Step 1/4 error: After applying this test step and performing a `terraform refresh`, the plan was not empty.
stdout
Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
~ update in-place
~ resource "aws_redshift_snapshot_copy_grant" "test" {
id                       = "tf-acc-test-1194731605999433216"
~ tags                     = {
+ "Env"  = "Test"
+ "Name" = "tf-acc-test-1194731605999433216"
}
~ tags_all                 = {
+ "Env"  = "Test"
+ "Name" = …
```
=> Redshift: Fix acceptance test failures

website/docs/r/subnet.html.markdown, website/docs/r/vpc.html.markdown, website/docs/r/vpc_ipam_pool.html.markdown, website/docs/r/vpc_ipam_pool_cidr.html.markdown, website/docs/r/vpc_ipam_pool_cidr_allocation.html.markdown, website/docs/r/vpc_ipam_preview_next_cidr.html.markdown, website/docs/r/vpc_ipv4_cidr_block_association.html.markdown
This PR corrects an issue with a few resource's examples that previously used a public CIDR range, rather than a public range.
Closes #30675
- [IPv4 Private Address Space and Filtering](https://www.arin.net/reference/research/statistics/address_filters/)
N/a, docs
=> Update CIDR arguments in various resource docs to use a private range

internal/service/elasticache/engine_version.go
Previously, the `engine_version` error message had an ambiguously placed clause:
```
Error: engine_version: Redis versions must match <major>.<minor> when using version 6 or higher, or <major>.<minor>.<patch>
```
Hopefully, this new error message will be much clearer:
```
Error: engine_version: 7.0.7 is invalid. For Redis v6 or higher, use <major>.<minor>. For Redis v5 or lower, use <major>.<minor>.<patch>.
```
Closes #32252
```console
% make t T=TestAccElastiCacheReplicationGroup_EngineVersion K=elasticache   
TF_ACC=1 go test ./internal/service/elasticache/... -v -count 1 -parallel 20 -run='TestAccElastiCacheReplicationGroup_EngineVersion'  -timeout 180m
=== RUN   TestAccElastiCacheReplicationGroup_EngineVersion_v7
=== PAUSE …
```
=> elasicache/replication_group: Better version error message

.changelog/32941.txt, internal/service/elbv2/load_balancer.go, internal/service/elbv2/load_balancer_test.go
Closes #32942
```console
% make t T=TestAccELBV2LoadBalancer_ K=elbv2
TF_ACC=1 go test ./internal/service/elbv2/... -v -count 1 -parallel 20 -run='TestAccELBV2LoadBalancer_'  -timeout 180m
=== RUN   TestAccELBV2LoadBalancer_ALB_basic
=== PAUSE TestAccELBV2LoadBalancer_ALB_basic
=== RUN   TestAccELBV2LoadBalancer_NLB_basic
=== PAUSE TestAccELBV2LoadBalancer_NLB_basic
=== RUN   TestAccELBV2LoadBalancer_LoadBalancerType_gateway
=== PAUSE TestAccELBV2LoadBalancer_LoadBalancerType_gateway
=== RUN   TestAccELBV2LoadBalancer_disappears
=== PAUSE TestAccELBV2LoadBalancer_disappears
=== RUN   TestAccELBV2LoadBalancer_ipv6SubnetMapping
=== PAUSE TestAccELBV2LoadBalancer_ipv6SubnetMapping
=== RUN …
```
=> elbv2/lb: Check for duplicate name

.changelog/32939.txt, internal/service/vpclattice/service_data_source.go, internal/service/vpclattice/service_data_source_test.go, internal/service/vpclattice/service_network_data_source.go, internal/service/vpclattice/service_network_data_source_test.go, internal/service/vpclattice/service_package_gen.go
Closes #32938.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/26695.
```console
make testacc TESTARGS='-run=TestAccVPCLatticeServiceNetwork' PKG=vpclattice ACCTEST_PARALLELISM=2
TF_ACC=1 go test ./internal/service/vpclattice/... -v -count 1 -parallel 2  -run=TestAccVPCLatticeServiceNetwork -timeout 180m
=== RUN   TestAccVPCLatticeServiceNetworkDataSource_basic
=== PAUSE TestAccVPCLatticeServiceNetworkDataSource_basic
=== RUN   TestAccVPCLatticeServiceNetworkServiceAssociation_basic
=== PAUSE TestAccVPCLatticeServiceNetworkServiceAssociation_basic
=== RUN   TestAccVPCLatticeServiceNetworkServiceAssociation_arn
=== PAUSE TestAccVPCLatticeServiceNetworkServiceAssociation_arn
=== RUN …
```
=> fix: Skip listing tags on `aws_vpclattice_service_network` data source when shared via RAM

.changelog/32933.txt, internal/service/appstream/fleet.go
This PR updates the `aws_appstream_fleet` resource's `max_user_duration_in_seconds` argument validation to allow the use of up to `432000`, as per the AWS API documentation.
Closes #32874
- [AWS API: CreateFleet](https://docs.aws.amazon.com/appstream2/latest/APIReference/API_CreateFleet.html#AppStream2-CreateFleet-request-MaxUserDurationInSeconds)
I don't have the necessary permissions to successfully run the tests in the accounts I have access to, unfortunately.
=> r/aws_appstream_fleet: Update `max_user_duration_in_seconds` to `432000`

website/docs/r/lambda_function.html.markdown
This PR adds `java17` to the runtimes that are mentioned as supported by the `snap_start` setting, bringing the documentation in line with reality.
Closes #32953
- [AWS: Improving startup performance with Lambda SnapStart](https://docs.aws.amazon.com/lambda/latest/dg/snapstart.html#snapstart-runtimes)
> SnapStart supports the Java 11 and Java 17 (`java11` and `java17`) [managed runtimes](https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html).
N/a, docs
=> `aws_lambda_function`: mention `java17` support for `snap_start`

internal/service/cloudwatch/metric_stream_test.go, internal/service/logs/resource_policy_test.go
In CI:
```
=== RUN   TestAccCloudWatchMetricStream_basic
=== PAUSE TestAccCloudWatchMetricStream_basic
=== CONT  TestAccCloudWatchMetricStream_basic
testing_new.go:88: Error running post-test destroy, there may be dangling resources: exit status 1
Error: deleting Amazon S3 (Simple Storage) Bucket (tf-acc-test-7630968413981012997): BucketNotEmpty: The bucket you tried to delete is not empty
status code: 409, request id: A1FAY1WMQJB387TG, host id: GdxDA5OvTuwAwkMwD5C371HWIXXsDvpXmjgAN3gzJam3VysyRso5Z+99usu0uaC9ebvf0zjP4mI9LundoUbMWw==
--- FAIL: TestAccCloudWatchMetricStream_basic (480.11s)
```
```
=== RUN   TestAccLogsResourcePolicy_basic
=== PAUSE TestAccLogsResourcePolicy_basic
=== CONT  TestAccLogsResourcePolicy_basic
resource_policy_test.go:27: Step 1/3 error: Check failed: Check 3/3 …
```
=> CloudWatch: Fix acceptance test failures

internal/service/s3/bucket_server_side_encryption_configuration_test.go, website/docs/r/s3_bucket_server_side_encryption_configuration.html.markdown
This PR updates the documentation for the `aws_s3_bucket_server_side_encryption_configuration` resource to indicate that `aws:kms:dsse` is supported as an `sse_algorithm`. This has been the case since `5.4.0` / AWS SDK version 1.44.282. For good stewardship's sake, added test coverage as well.
Closes #32951
- Support added to the SDK in https://github.com/aws/aws-sdk-go/pull/4882
```console
$ make testacc TESTS=TestAccS3BucketServerSideEncryptionConfiguration_ApplySSEByDefault_KMSDSSE PKG=s3
TF_ACC=1 go test ./internal/service/s3/... -v -count 1 -parallel 20 -run='TestAccS3BucketServerSideEncryptionConfiguration_ApplySSEByDefault_KMSDSSE'  -timeout 180m
=== RUN   TestAccS3BucketServerSideEncryptionConfiguration_ApplySSEByDefault_KM …
```
=> S3 Bucket Server Side Encryption: add `aws:kms:dsse` to list of supported `sse_algorithm`

skaff/datasource/datasource.tmpl, skaff/datasource/datasourcefw.tmpl, skaff/datasource/datasourcetest.tmpl, skaff/resource/resource.tmpl, skaff/resource/resourcefw.tmpl, skaff/resource/resourcetest.tmpl
- Adds copyright headers to skaff templates to prevent CI failures
- Removes the `tftags` import if `--include-tags` is false
=> skaff: add copyright headers to go templates

.changelog/32936.txt, internal/service/cloudfront/continuous_deployment_policy.go, internal/service/cloudfront/continuous_deployment_policy_test.go, internal/service/cloudfront/distribution.go, internal/service/cloudfront/distribution_configuration_structure.go, internal/service/cloudfront/exports_test.go, internal/service/cloudfront/service_package_gen.go, website/docs/r/cloudfront_continuous_deployment_policy.html.markdown, website/docs/r/cloudfront_distribution.html.markdown
Adds continuous deployment support for CloudFront distributions.
- Adds a new `aws_cloudfront_continuous_deployment_policy` resource
- Adds `staging` and `continuous_deployment_policy_id` arguments to the `aws_cloudfront_distribution` resource
Closes #28920
- https://aws.amazon.com/about-aws/whats-new/2022/11/amazon-cloudfront-continuous-deployment-support/
- https://docs.aws.amazon.com/cloudfront/latest/APIReference/API_CreateContinuousDeploymentPolicy.html
- https://docs.aws.amazon.com/cloudfront/latest/APIReference/API_GetContinuousDeploymentPolicy.html
- https://docs.aws.amazon.com/cloudfront/latest/APIReference/API_UpdateContinuousDeploymentPolicy.html
- https://docs.aws.amazon.com/cloudfront/latest/APIReference/API_DeleteContinuousDeploymentPolicy.html
```console
% make testacc …
```
=> [New Resource]: `aws_cloudfront_continuous_deployment_policy`

.changelog/32535.txt, internal/service/lambda/layer_version.go, internal/service/lambda/layer_version_test.go
[Lambda Layers - New Version Every Run](https://github.com/hashicorp/terraform-provider-aws/issues/25647#top)
#25647
[Lambda Layers - New Version Every Run](https://github.com/hashicorp/terraform-provider-aws/issues/25647#top)
Closes #25647
```
...
```
=> Lambda Layers - New Version Every Run #25647

internal/service/opensearch/wait.go
https://github.com/hashicorp/terraform-provider-aws/issues/32189
Pragmatic option: reduce minimum OpenSearch update to 1 minute (from 10 minutes).
Closes #32189
https://github.com/hashicorp/terraform-provider-aws/issues/32189
Not sure about tests for this one. No prior delay-specific tests exist for this.
=> opensearch update delay: 10 min -> 1 min

.changelog/32958.txt, internal/service/appstream/fleet.go, internal/service/appstream/fleet_stack_association_test.go, internal/service/appstream/fleet_test.go, internal/service/appstream/image_builder_test.go, website/docs/r/appstream_fleet.html.markdown, website/docs/r/appstream_fleet_stack_association.html.markdown
Fixes various AppStream acceptances tests which were failing due to the use of deprecated image names. Also updates associated documentation where applicable.
```
=== RUN   TestAccAppStreamFleet_basic
=== PAUSE TestAccAppStreamFleet_basic
=== CONT  TestAccAppStreamFleet_basic
fleet_test.go:41: Step 1/2 error: Error running apply: exit status 1
Error: creating Appstream Fleet (): ResourceNotAvailableException: The image Amazon-AppStream2-Sample-Image-02-04-2019 is DEPRECATED. The image must be in an AVAILABLE state for this action to succeed.
with aws_appstream_fleet.test,
on terraform_plugin_test.tf line 2, in resource "aws_appstream_fleet" "test":
2: resource "aws_appstream_fleet" "test" {
--- FAIL: TestAccAppStreamFleet_basic (65.75s)
FAIL
```
```
=== RUN …
```
=> [TechDebt]: Fix `appstream` acceptance tests

.changelog/32896.txt, .github/labeler-pr-triage.yml, .github/workflows/provider.yml, .github/workflows/website.yml, internal/generate/prlabels/file.tmpl, internal/service/ec2/vpc_subnet.go, internal/service/ec2/vpc_subnet_test.go
enabling dns64 and resource_name_dns_aaaa_record_on_launch, need IPv6 CIDR block.
Closes https://github.com/hashicorp/terraform-provider-aws/issues/32897
```console
❯ make testacc PKG=ec2 TESTS="TestAccVPC*"
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 20 -run='TestAccVPC*'  -timeout 180m
=== RUN   TestAccVPCDataSource_basic
=== PAUSE TestAccVPCDataSource_basic
=== RUN   TestAccVPCDataSource_CIDRBlockAssociations_multiple
=== PAUSE TestAccVPCDataSource_CIDRBlockAssociations_multiple
=== RUN   TestAccVPCDefaultNetworkACL_basic
=== PAUSE TestAccVPCDefaultNetworkACL_basic
=== RUN   TestAccVPCDefaultNetworkACL_basicIPv6VPC
=== PAUSE TestAccVPCDefaultNetworkACL_basicIPv6VPC
=== RUN …
```
=> Fix: Enabling IPv6 apply error

internal/service/organizations/delegated_services_data_source_test.go
In CI:
```
=== RUN   TestAccOrganizations_serial
=== PAUSE TestAccOrganizations_serial
=== CONT  TestAccOrganizations_serial
=== RUN   TestAccOrganizations_serial/OrganizationalUnit
=== RUN   TestAccOrganizations_serial/OrganizationalUnit/Name
acctest.go:923: skipping tests; this AWS account must not be an existing member of an AWS Organization
=== RUN   TestAccOrganizations_serial/OrganizationalUnit/Tags
acctest.go:923: skipping tests; this AWS account must not be an existing member of an AWS Organization
=== RUN   TestAccOrganizations_serial/OrganizationalUnit/ChildAccountsDataSource
acctest.go:952: this AWS account must be the management account of an AWS Organization
=== RUN   TestAccOrganizations_serial/OrganizationalUnit/DescendantAccountsDataSource
acctest.go:952: this AWS account …
```
=> Organizations: Fix acceptance test failures

website/docs/r/rds_cluster.html.markdown
Cross-account restores were [enabled back in 3.19.0](https://github.com/hashicorp/terraform-provider-aws/pull/16447), but the doc wasn't updated to reflect that sometimes an ARN is required instead of a cluster identifier.  
When following the current docs, providing a cluster identifier instead of ARN results in a successful `terraform plan` but an error during `terraform apply`:
```
│ Error: creating RDS Cluster (restore to point-in-time) (dest-clone-testing): DBClusterNotFoundFault: The source cluster could not be found or cannot be accessed: source-clone-testing
```
The [AWS docs](https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/Aurora.Managing.Clone.html#Aurora.Managing.Clone.Cross-Account) specify that a cross-account restore requires an ARN with the …
=> Add cross-account details to docs for `rds_cluster`

internal/service/opsworks/rds_db_instance_test.go
In CI:
```
=== RUN   TestAccOpsWorksRDSDBInstance_basic
=== PAUSE TestAccOpsWorksRDSDBInstance_basic
=== CONT  TestAccOpsWorksRDSDBInstance_basic
rds_db_instance_test.go:31: Step 1/3 error: Error running pre-apply refresh: exit status 1
Error: reading RDS Orderable DB Instance Options: InvalidParameterCombination: Cannot find version 8.0.25 for mysql
status code: 400, request id: 45e8b364-2b45-411b-bd13-d72fae3386ea
with data.aws_rds_orderable_db_instance.test,
on terraform_plugin_test.tf line 103, in data "aws_rds_orderable_db_instance" "test":
103: data "aws_rds_orderable_db_instance" "test" {
--- FAIL: TestAccOpsWorksRDSDBInstance_basic (44.28s)
```
```console
% make testacc TESTARGS='-run=TestAccOpsWorksRDSDBInstance_' PKG=opsworks ACCTEST_PARALLELISM=2
==> Checking that code complies …
```
=> OpsWorks: Fix acceptance test failures

.github/workflows/issue_comment.yml
The `issue_comment` workflow was intended to only remove `waiting-response` and `stale` when a non-maintainer commented on issues/pull requests. Since the conditional was missing, it was running when maintainers commented too.
N/a, workflow
=> Fix `issue_comment` workflow

website/docs/r/lb.html.markdown
AWS released to support security groups for NLB. Thus updated documents.
https://aws.amazon.com/jp/about-aws/whats-new/2023/08/network-load-balancer-supports-security-groups/
No implementation updates are needed.
Closes #33009
=> docs/r/lb: Support security groups for NLB

website/docs/r/lightsail_database.html.markdown
The correct argument for the name of the database in `aws_lightsail_database` is `relational_database_name` instead of `name`
See `relational_database_name` in https://github.com/hashicorp/terraform-provider-aws/blob/main/internal/service/lightsail/database.go
=> update lightsail_database docs to use the correct name argument

internal/service/ram/find.go, internal/service/ram/resource_share.go, internal/service/ram/resource_share_accepter.go, internal/service/ram/resource_share_accepter_test.go, internal/service/ram/resource_share_test.go, internal/service/ram/status.go, internal/service/ram/wait.go
In CI:
```
=== RUN   TestAccRAMResourceShareAccepter_basic
=== PAUSE TestAccRAMResourceShareAccepter_basic
=== CONT  TestAccRAMResourceShareAccepter_basic
resource_share_accepter_test.go:30: Step 1/2 error: Error running apply: exit status 1
Error: No RAM Resource Share (arn:aws:ram:us-west-2:067819342479:resource-share/0623b688-527d-4869-9577-ebd7d14ddf29) invitation found
NOTE: If both AWS accounts are in the same AWS Organization and RAM Sharing with AWS Organizations is enabled, this resource is not necessary
with aws_ram_resource_share_accepter.test,
on terraform_plugin_test.tf line 8, in resource "aws_ram_resource_share_accepter" "test":
8: resource "aws_ram_resource_share_accepter" "test" {
--- FAIL: TestAccRAMResourceShareAccepter_basic (330.92s)
```
```console
% make testacc …
```
=> RAM: Fix acceptance test failures

.changelog/33012.txt, internal/service/quicksight/schema/analysis.go, internal/service/quicksight/schema/dashboard.go, internal/service/quicksight/schema/template.go
- Adjusts the max length of the nested `expression` field to 32000 characters. 
- Bumps the template `expression` list MaxItems to 500.
- Centralizes `expression` schema to a generation function since it is shared across several resources. 
Closes #32986
- https://docs.aws.amazon.com/quicksight/latest/APIReference/API_CalculatedField.html
- https://docs.aws.amazon.com/quicksight/latest/APIReference/API_TemplateVersionDefinition.html#QS-Type-TemplateVersionDefinition-CalculatedFields (maximum of 500 items)
```console
%  make testacc PKG=quicksight TESTARGS="-run TestAccQuickSightAnalysis_\|TestAccQuickSightDashboard_\|TestAccQuickSightTemplate_"
TF_ACC=1 go test ./internal/service/quicksight/... -v -count 1 -parallel 20  -run …
```
=> r/aws_quicksight: adjust definition.*.calculated_fields.*.expression max length to 32000

.changelog/33015.txt, internal/service/budgets/budget_action.go, internal/service/budgets/budget_action_test.go
The current behaviour of `aws_budgets_budget_action` waits for the action to have completed or be in a pending state for manual approval. If a budget action is not triggered, none of these states will be valid, and the action will be in standby status.
No longer waits for any status, since creation of an action is a synchronous operation. Adds guard to deletion, since an action cannot be deleted while in progress.
Closes #31236
```console
% make testacc PKG=budgets TESTS=TestAccBudgetsBudgetAction_
--- PASS: TestAccBudgetsBudgetAction_disappears (27.60s)
--- PASS: TestAccBudgetsBudgetAction_triggeredAutomatic (30.49s)
--- PASS: TestAccBudgetsBudgetAction_basic (30.62s)
--- PASS: TestAccBudgetsBudgetAction_triggeredManual (30.62s)
```
=> ressource/aws_budgets_budget_action : No longer waits for action to have completed running or be pending

.changelog/33023.txt, internal/service/quicksight/analysis.go, internal/service/quicksight/dashboard.go, internal/service/quicksight/template.go
Converts the `permissions` block to a set type for the QuickSight Analysis, Dashboard, and Template resources.
Closes #32991
Relates #32984
```console
% make testacc PKG=quicksight TESTARGS="-run TestAccQuickSightAnalysis_\|TestAccQuickSightDashboard_\|TestAccQuickSightTemplate_"
TF_ACC=1 go test ./internal/service/quicksight/... -v -count 1 -parallel 20  -run TestAccQuickSightAnalysis_\|TestAccQuickSightDashboard_\|TestAccQuickSightTemplate_ -timeout 180m
--- PASS: TestAccQuickSightTemplate_disappears (76.88s)
--- PASS: TestAccQuickSightTemplate_barChart (83.67s)
--- PASS: TestAccQuickSightTemplate_basic (88.05s)
--- PASS: …
```
=> r/aws_quicksight: convert `permissions` to type set

.teamcity/components/service_build_config.kt
Long running test can cause agent to run OOM and unregister. This causes a restart cycle. Test should fail with a failure message.
```console
...
```
=> teamcity: add failure condition for service build

.changelog/30293.txt, .changelog/31127.txt, .changelog/31757.txt, .changelog/32856.txt, .changelog/33023.txt
Relates #31757.
Relates #30293.
Relates #33023.
Relates #32856.
Relates #31127.
=> Fix CHANGELOG entries

internal/service/datasync/find.go, internal/service/datasync/location_nfs.go, internal/service/datasync/location_nfs_test.go
In CI:
```
=== RUN   TestAccDataSyncLocationNFS_basic
=== PAUSE TestAccDataSyncLocationNFS_basic
=== CONT  TestAccDataSyncLocationNFS_basic
location_nfs_test.go:29: Step 1/2 error: Error running pre-apply refresh: exit status 1
Error: Your query returned no results. Please change your search criteria and try again.
with data.aws_ami.aws-thinstaller,
on terraform_plugin_test.tf line 2, in data "aws_ami" "aws-thinstaller":
2: data "aws_ami" "aws-thinstaller" {
--- FAIL: TestAccDataSyncLocationNFS_basic (18.60s)
```
```console
% make testacc TESTARGS='-run=TestAccDataSyncLocationNFS_' PKG=datasync ACCTEST_PARALLELISM=2
TF_ACC=1 go test ./internal/service/datasync/... -v -count 1 -parallel 2  -run=TestAccDataSyncLocationNFS_ -timeout …
```
=> DataSync: Fix acceptance test failures

internal/service/iam/user_login_profile_test.go
Fixes acceptance tests expecting a Keybase key name for the `ppg_key` argument. The heredoc string format used in the `_required` test configuration was preventing the key name from being read properly, resulting in errors like:
```
=== CONT  TestAccIAMUserLoginProfile_keybase
user_login_profile_test.go:124: Step 1/2 error: Error running apply: exit status 1
Error: creating IAM User Login Profile for "tf-acc-test-6581599776859930449": encrypting Password: parsing given PGP key: EOF
with aws_iam_user_login_profile.test,
on terraform_plugin_test.tf line 35, in resource "aws_iam_user_login_profile" "test":
35: resource "aws_iam_user_login_profile" "test" {
```
```console
% make testacc PKG=iam TESTS=TestAccIAMUserLoginProfile_ …
```
=> r/aws_iam_user_login_profile(test): fix keybase configs

.changelog/33040.txt, internal/service/quicksight/analysis_test.go, internal/service/quicksight/dashboard.go, internal/service/quicksight/schema/analysis.go, internal/service/quicksight/schema/dashboard.go, internal/service/quicksight/schema/template.go
Converts the `definition.0.calculated_fields` argument in the Analysis, Dashboard, and Template resources to a set type.
Closes #32997
```console
% make testacc PKG=quicksight TESTARGS="-run TestAccQuickSightAnalysis_\|TestAccQuickSightDashboard_\|TestAccQuickSightTemplate_"
TF_ACC=1 go test ./internal/service/quicksight/... -v -count 1 -parallel 20  -run TestAccQuickSightAnalysis_\|TestAccQuickSightDashboard_\|TestAccQuickSightTemplate_ -timeout 180m
--- PASS: TestAccQuickSightTemplate_basic (84.83s)
--- PASS: TestAccQuickSightDashboard_disappears (93.99s)
--- PASS: TestAccQuickSightAnalysis_disappears (94.02s)
--- PASS: …
```
=> r/aws_quicksight: convert calculated_fields to set type

.changelog/33059.txt, internal/service/cloudformation/stack.go, internal/service/cloudformation/stack_test.go
When the output values of an `aws_cloudformation_stack` change, the `outputs` attribute is not correctly marked as `Computed`, so changes are not picked up by dependent resources or Terraform output values. The values in state are correctly updated.
When any configurable, non-`ForceNew` parameters are changed, now marks the `outputs` attribute as `Computed`.
Closes #32744
```console
% make testacc PKG=cloudformation TESTS=TestAccCloudFormationStack_
--- PASS: TestAccCloudFormationStack_disappears (69.58s)
--- PASS: TestAccCloudFormationStack_yaml (78.66s)
--- PASS: TestAccCloudFormationStack_onFailure (83.11s)
--- PASS: TestAccCloudFormationStack_WithURLWithParams_withYAML (85.38s)
--- PASS: TestAccCloudFormationStack_withTransform (87.62s)
--- PASS: TestAccCloudFormationStack_basic …
```
=> resource/aws_cloudformation_stack: Sets `outputs` as `Computed` when other fields change

website/docs/r/rds_cluster.html.markdown
=> r/rds_cluster documentation: put the db_cluster_parameter_group_name parameter back after it was removed for some reason.

.changelog/33103.txt, internal/service/route53/zone.go, internal/service/route53/zone_test.go
Ignores errors disabling DNS SEC on forced destruction of Route53 zones where the partition does not support it (ie. GovCloud).
```
Error: while force deleting Route53 Hosted Zone (<redacted>), disabling DNSSEC: could not get DNS SEC status for hosted zone (<redacted>): AccessDenied: The operation GetDNSSEC
is not available for the current AWS account <redacted>.
```
Closes #22334
**GovCloud:**
```console
% make testacc PKG=route53 TESTS=TestAccRoute53Zone_VPC_single_forceDestroy
TF_ACC=1 go test ./internal/service/route53/... -v -count 1 -parallel 20 -run='TestAccRoute53Zone_VPC_single_forceDestroy'  -timeout 180m
=== RUN   TestAccRoute53Zone_VPC_single_forceDestroy
=== PAUSE TestAccRoute53Zone_VPC_single_forceDestroy
=== CONT …
```
=> r/aws_route53_zone: skip disabling dnssec in unsupported partitions

internal/acctest/acctest.go, internal/service/networkmanager/connect_attachment_test.go, internal/service/networkmanager/connect_peer_test.go, internal/service/networkmanager/site_to_site_vpn_attachment_test.go, internal/service/networkmanager/transit_gateway_peering_test.go, internal/service/networkmanager/vpc_attachment_test.go
In CI:
```
=== RUN   TestAccNetworkManagerConnectAttachment_basic
=== PAUSE TestAccNetworkManagerConnectAttachment_basic
=== CONT  TestAccNetworkManagerConnectAttachment_basic
connect_attachment_test.go:28: Step 1/2 error: Error running pre-apply refresh: exit status 1
Error: Unsupported argument
on terraform_plugin_test.tf line 46, in resource "aws_networkmanager_core_network" "test":
46:   policy_document   = data.aws_networkmanager_core_network_policy_document.test.json
An argument named "policy_document" is not expected here.
--- FAIL: TestAccNetworkManagerConnectAttachment_basic (29.62s)
```
(relates https://github.com/hashicorp/terraform-provider-aws/pull/30875), and
```
=== RUN   TestAccNetworkManagerTransitGatewayPeering_basic
=== PAUSE …
```
=> Network Manager: Fix acceptance test failures

website/docs/r/docdb_global_cluster.html.markdown
This PR updates the `aws_docdb_global_cluster` documentation to fix the example by declaring an explicit dependency between `aws_docdb_cluster.primary` and `aws_docdb_cluster.secondary`. This prevents the errors described in the linked issue by ensuring `aws_docdb_cluster.primary` is created before `aws_docdb_cluster.secondary`.
Closes #32293
N/a, docs (though the example was run locally to test/verify)
=> Fix `aws_docdb_global_cluster` example

website/docs/r/pipes_pipe.html.markdown
This PR corrects the `aws_pipes_pipe` documentation's example for using `enrichment_parameters`, as it was previously non-functional. Corrected reference to `aws_iam_role` while I was at it.
Closes #33086
Docs themselves + `terraform validate`
N/a, docs
=> Correct `aws_pipes_pipe` examples

website/docs/r/sesv2_configuration_set_event_destination.html.markdown
Fix typo in markdown formatting that made one of the required parameters of the **aws_sesv2_configuration_set_event_destination** resource easy to overlook.
=> Fix typo in aws_sesv2_configuration_set_event_destination docs

.changelog/33122.txt, internal/service/quicksight/schema/visual_word_cloud.go
This PR fixes a typo in the `flattenWordCloudOptions` flattener that's used in `aws_quicksight_analysis`, `aws_quicksight_dashboard`, and `aws_quicksight_template`, which led to the following error:
```shell
│ Error: setting definition: Invalid address to set: []string{"definition", "0", "sheets", "9", "visuals", "17", "word_cloud_visual", "0", "chart_configuration", "0", "word_cloud_options", "0", "work_orientation"}
```
Closes #33109
- [Schema](https://github.com/hashicorp/terraform-provider-aws/blob/24b921e4566eb44d23cbae873bca8d3721a15558/internal/service/quicksight/schema/visual_word_cloud.go#L77)
I'm unable to run tests for Quicksight.
=> Fix typo in `flattenWordCloudOptions` flattener

website/docs/d/transfer_server.html.markdown, website/docs/r/transfer_server.html.markdown
The argument and attribute name in resource and data source respectively for `transfer_server` is invalid. It should be `structured_log_destinations` rather than `structured_logging_destinations`
Closes https://github.com/hashicorp/terraform-provider-aws/issues/33105
The feature was added in https://github.com/hashicorp/terraform-provider-aws/pull/32654
```console
...
```
=> fix parameter name structured_log_destinations

.changelog/33142.txt, internal/service/ec2/ec2_host.go
Fixes bug in issue #33140 by setting the `asset_id` field to `Computed`
Closes #33140
```console
make testacc TESTS=TestAccEC2Host_outpostAssetId PKG=ec2 ACCTEST_PARALLELISM=5  
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 5 -run='TestAccEC2Host_outpostAssetId'  -timeout 180m
=== RUN   TestAccEC2Host_outpostAssetId
=== PAUSE TestAccEC2Host_outpostAssetId
=== CONT  TestAccEC2Host_outpostAssetId
--- PASS: TestAccEC2Host_outpostAssetId (23.32s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/ec2	27.031s
...
```
=> add computed field for asset_id attribute

.ci/.semgrep.yml
Ensures use of `regexache.MustCompile()` instead of `regexp.MustCompile()`.
Relates #32289 
Relates #33147
Relates #33155
Relates #33152
```console
...
```
=> semgrep: Add regexache check

website/docs/r/s3_bucket_lifecycle_configuration.html.markdown
Documentation and example referenced at https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket_lifecycle_configuration#transition
references the wrong date type. This update clarifies the correct date type, standardizes language between both uses of date attribute on page, and updates the example to the expected input.
Closes [#33136](https://github.com/hashicorp/terraform-provider-aws/issues/33136)
References  [#33136](https://github.com/hashicorp/terraform-provider-aws/issues/33136)
=> Update s3_bucket_lifecycle_configuration documentation to correct expected date type

.ci/providerlint/passes/AWSAT001/README.md, .ci/providerlint/passes/AWSAT001/testdata/src/a/main.go, docs/debugging.md, skaff/datasource/datasourcetest.tmpl, skaff/go.mod, skaff/go.sum, skaff/resource/resource.go, skaff/resource/resourcetest.tmpl
Closes #0000
```console
...
```
=> skaff, docs: Update for regexache

.changelog/33161.txt, internal/service/quicksight/schema/template_parameter.go
Skips setting `definition.*.parameter_declarations.*.*_parameter_declaration.static_values` values when an empty slice is returned.
Closes #33004
```console
% make testacc PKG=quicksight TESTARGS="-run TestAccQuickSightAnalysis_\|TestAccQuickSightDashboard_\|TestAccQuickSightTemplate_"
TF_ACC=1 go test ./internal/service/quicksight/... -v -count 1 -parallel 20  -run TestAccQuickSightAnalysis_\|TestAccQuickSightDashboard_\|TestAccQuickSightTemplate_ -timeout 180m
--- PASS: TestAccQuickSightTemplate_disappears (84.72s)
--- PASS: TestAccQuickSightTemplate_barChart (92.30s)
--- PASS: TestAccQuickSightAnalysis_disappears (93.75s)
--- …
```
=> r/aws_quicksight: skip setting empty static_values fields

.changelog/33189.txt, internal/service/lakeformation/data_lake_settings.go, internal/service/lakeformation/data_lake_settings_data_source.go, internal/service/lakeformation/data_lake_settings_data_source_test.go, internal/service/lakeformation/data_lake_settings_test.go, internal/service/lakeformation/lakeformation_test.go, website/docs/d/lakeformation_data_lake_settings.html.markdown, website/docs/r/lakeformation_data_lake_settings.html.markdown
Add support for [ReadOnlyAdmins](https://docs.aws.amazon.com/lake-formation/latest/APIReference/API_DataLakeSettings.html#lakeformation-Type-DataLakeSettings-ReadOnlyAdmins) in the aws_lakeformation_data_lake_settings (data) resources
Closes #33143
```console
% make testacc PKG=lakeformation TESTS=TestAccLakeFormation_serial/DataLakeSettings/readOnlyAdmins
TF_ACC=1 go test ./internal/service/lakeformation/... -v -count 1 -parallel 20 -run='TestAccLakeFormation_serial/DataLakeSettings/readOnlyAdmins'  -timeout 180m
=== RUN   TestAccLakeFormation_serial
=== PAUSE TestAccLakeFormation_serial
=== CONT  TestAccLakeFormation_serial
=== RUN   TestAccLakeFormation_serial/DataLakeSettings
=== RUN …
```
=> Add support for LakeFormation ReadOnlyAdmins

.changelog/33192.txt, internal/service/appflow/connector_profile.go
Fix validation errors to AWS specification.
Closes #32660
```console
$ make testacc TESTARGS='-run=TestAccAppFlowConnectorProfile_' PKG=appflow
TF_ACC=1 go test ./internal/service/appflow/... -v -count 1 -parallel 20  -run=TestAccAppFlowConnectorProfile_ -timeout 180m
--- PASS: TestAccAppFlowConnectorProfile_disappears (251.51s)
--- PASS: TestAccAppFlowConnectorProfile_basic (257.14s)
--- PASS: TestAccAppFlowConnectorProfile_update (323.43s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/appflow	326.931s
```
=> aws_appflow_connector_profile: correct validation on oauth2 custom auth

.changelog/32926.txt, .changelog/33220.txt, internal/service/codeartifact/codeartifact_test.go, internal/service/codeartifact/domain.go, internal/service/codeartifact/domain_test.go
```console
$ make testacc TESTARGS='-run=TestAccCodeArtifact_serial/^Domain/$' PKG=codeartifact
TF_ACC=1 go test ./internal/service/codeartifact/... -v -count 1 -parallel 20  -run=TestAccCodeArtifact_serial/^Domain/ -timeout 180m
--- PASS: TestAccCodeArtifact_serial (377.54s)
--- PASS: TestAccCodeArtifact_serial/Domain (207.51s)
--- PASS: TestAccCodeArtifact_serial/Domain/tags (68.48s)
--- PASS: TestAccCodeArtifact_serial/Domain/basic (29.88s)
--- PASS: TestAccCodeArtifact_serial/Domain/defaultEncryptionKey (28.65s)
--- PASS: TestAccCodeArtifact_serial/Domain/disappears (24.28s)
--- PASS: TestAccCodeArtifact_serial/Domain/migrateAssetSizeBytesToString (56.21s)
--- PASS: TestAccCodeArtifact_serial/DomainPermissionsPolicy (170.04s) …
```
=> r/aws_codeartifact_domain: fix error with `asset_size_bytes` size

.changelog/33226.txt, internal/provider/tags_interceptor.go, internal/service/kms/key_test.go
Closes https://github.com/hashicorp/terraform-provider-aws/issues/33219.
Relates https://github.com/hashicorp/terraform-provider-aws/issues/31941.
```console
$ make testacc TESTARGS='-run=TestAccVPC_ -short' PKG=vpc
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 20  -run=TestAccVPC_ -short -timeout 180m
vpc_test.go:1021: skipping long-running test in short mode
vpc_test.go:1048: skipping long-running test in short mode
vpc_test.go:1076: skipping long-running test in short mode
--- SKIP: TestAccVPC_IPAMIPv6 (0.00s)
=== NAME  TestAccVPC_assignGeneratedIPv6CIDRBlockWithNetworkBorderGroup …
```
=> tags: send all old and new tags to updateTags

.changelog/33206.txt, internal/service/wafv2/rule_group.go, internal/service/wafv2/rule_group_test.go, website/docs/r/waf_rule_group.html.markdown
Adds support for `name_prefix` for `aws_wafv2_rule_group`; based on following https://hashicorp.github.io/terraform-provider-aws/resource-name-generation/
Closes #23334
```console
...
```
=> Add `name_prefix` support for WAFv2 rule groups

website/docs/d/opensearchserverless_collection.html.markdown, website/docs/r/opensearchserverless_collection.html.markdown
Fixing typo in [AOSS](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/opensearchserverless_collection#dashboard_endpont) documentation
none 
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/opensearchserverless_collection#dashboard_endpont
not sure what should be provided here, if anything for such change
```console
```
=> typo(docs): fix typo in aoss dashboard endpoint attribute

internal/errs/fwdiag/diags.go, internal/errs/fwdiag/diags_test.go, internal/errs/sdkdiag/diags.go, internal/errs/sdkdiag/diags_test.go, internal/framework/flex/autoflex.go, internal/framework/flex/bool.go, internal/framework/flex/float.go, internal/framework/flex/int.go, internal/framework/flex/list.go, internal/framework/flex/map.go, internal/framework/flex/set.go, internal/framework/flex/string.go, internal/framework/flex/string_test.go
Use the generic Plugin Framework flattener/expander functions `flex.Expand` and `flex.Flatten` in the type-specific helpers.
This PR does not address "legacy-mode" -- `nil` pointers are converted to zero values.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/32356.
```console
% go test ./internal/framework/flex                             
ok  	github.com/hashicorp/terraform-provider-aws/internal/framework/flex	0.253s
% go test ./internal/errs/...                         
ok  	github.com/hashicorp/terraform-provider-aws/internal/errs	0.428s
ok  	github.com/hashicorp/terraform-provider-aws/internal/errs/fwdiag	0.670s
ok  	github.com/hashicorp/terraform-provider-aws/internal/errs/sdkdiag	0.287s
```
=> Extend use of generic Plugin Framework flattener/expander functions

website/docs/r/glue_connection.html.markdown
Updated Glue documentation to include a reference example of creating a custom Glue connector using the match_criteria `template_connection` . The example specifically uses a Snowflake JDBC connector which can be extended to any of the available custom connectors. The Glue connection resource then uses the custom connector as a baseline. 
The usage of the custom connector prevents the connector from being classified as a connection in the Glue console.
=> (docs) : Updated Glue connection documentation to include custom connector

.changelog/33203.txt, internal/service/events/bus_policy.go, internal/service/events/bus_policy_test.go, internal/service/iot/thing_type.go, internal/service/iot/thing_type_test.go
- Fix an error while refreshing state if `aws_iot_thing_type` is manually deleted in AWS
- Fix an error while refreshing state for `aws_cloudwatch_event_bus_policy` if the associated `aws_cloudwatch_event_bus` is manually deleted in AWS.
Closes #31634
This is my first contribution, so please double check and let me know if I have missed anything.
```console
% make testacc TESTS=TestAccIoTThingType PKG=iot
TF_ACC=1 go test ./internal/service/iot/... -v -count 1 -parallel 20 -run='TestAccIoTThingType'  -timeout 180m
=== RUN   TestAccIoTThingType_basic
=== PAUSE TestAccIoTThingType_basic
=== RUN   TestAccIoTThingType_full
=== PAUSE TestAccIoTThingType_full
=== RUN   TestAccIoTThingType_tags
=== PAUSE TestAccIoTThingType_tags
=== RUN …
```
=> Fix: Resolve issues with aws_iot_thing_type and aws_cloudwatch_event_bus_policy disappearing resources

go.mod, go.sum, internal/conns/awsclient_gen.go, internal/service/redshiftdata/service_package_gen.go, internal/service/redshiftdata/statement.go, internal/service/redshiftdata/statement_test.go, names/names.go, names/names_data.csv
Ibid.
```console
% make testacc TESTARGS='-run=TestAccRedshiftDataStatement_' PKG=redshiftdata
TF_ACC=1 go test ./internal/service/redshiftdata/... -v -count 1 -parallel 20  -run=TestAccRedshiftDataStatement_ -timeout 180m
=== RUN   TestAccRedshiftDataStatement_basic
=== PAUSE TestAccRedshiftDataStatement_basic
=== RUN   TestAccRedshiftDataStatement_workgroup
=== PAUSE TestAccRedshiftDataStatement_workgroup
=== CONT  TestAccRedshiftDataStatement_basic
=== CONT  TestAccRedshiftDataStatement_workgroup
--- PASS: TestAccRedshiftDataStatement_basic (304.03s)
--- PASS: TestAccRedshiftDataStatement_workgroup (811.22s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/redshiftdata	817.067s
```
=> Tech debt: Migrate `redshiftdata` resources to AWS SDK for Go v2

.changelog/33263.txt, internal/service/fsx/ontap_file_system.go
Changes maximum disk_iops_configuration.iops allowed in r/aws_fsx_ontap_file_system to 160000
Closes #33257
https://aws.amazon.com/about-aws/whats-new/2022/11/amazon-fsx-netapp-ontap-doubles-maximum-throughput-capacity-ssd-iops-file-system/
```console
❯ make testacc TESTS=TestAccFSxOntapFileSystem_basic PKG=fsx
TF_ACC=1 go test ./internal/service/fsx/... -v -count 1 -parallel 20 -run='TestAccFSxOntapFileSystem_basic'  -timeout 180m
=== RUN   TestAccFSxOntapFileSystem_basic
=== PAUSE TestAccFSxOntapFileSystem_basic
=== CONT  TestAccFSxOntapFileSystem_basic
--- PASS: TestAccFSxOntapFileSystem_basic (2305.91s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/fsx        2309.229s
```
=> fix r/aws_fsx_ontap_file_system - increase max iops

website/docs/r/cloudformation_stack_set.html.markdown, website/docs/r/cloudformation_stack_set_instance.html.markdown
- Import instructions for `aws_cloudformation_stack_set` when using `DELEGATED_ADMIN` should use `,` instead of `/`: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudformation_stack_set#import
- Additionally, the formatting of the import section for `aws_cloudformation_stack_set_instance` is broken due to missing triple backticks: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudformation_stack_set_instance#import
=> Docs: Fix import instructions and formatting for 'aws_cloudformation_stack_set'

.changelog/33274.txt, internal/service/glue/catalog_table.go, internal/service/glue/catalog_table_test.go, website/docs/r/glue_catalog_table.html.markdown
``Description
This PR adds in support for AWS glue tables open table formats.  
Had some issues as the Open format input is not returned as part of the table read and is instead marked as updates to the table parameters, this meant changing some additional code to prevent issues with the state. 
Relations
Closes: https://github.com/hashicorp/terraform-provider-aws/issues/33157
References
Output from Acceptance Testing
`terraform-provider-aws % make testacc TESTS=TestAccGlueCatalogTable_openTableFormat PKG=glue
TF_ACC=1 go test ./internal/service/glue/... -v -count 1 -parallel 20 -run='TestAccGlueCatalogTable_openTableFormat'  -timeout 180m
=== RUN   TestAccGlueCatalogTable_openTableFormat
=== PAUSE …
=> feat: added open_table_format_input attribute + tests

.changelog/#####.txt, go.mod, go.sum, internal/conns/awsclient_gen.go, internal/service/s3/bucket_objects_data_source_test.go, internal/service/s3/canonical_user_id_data_source.go, internal/service/s3/canonical_user_id_data_source_test.go, internal/service/s3/objects_data_source.go, internal/service/s3/objects_data_source_test.go, internal/service/s3/service_package.go, internal/service/s3/service_package_gen.go, names/names.go, names/names_data.csv, website/docs/d/s3_objects.html.markdown
Enable use of [AWS SDK for Go v2](https://github.com/aws/aws-sdk-go-v2) for S3 resources.
Migrate the `aws_canonical_user_id` and `aws_s3_objects` data sources.
Closes https://github.com/hashicorp/terraform-provider-aws/issues/26569.
Relates https://github.com/hashicorp/terraform-provider-aws/issues/33028.
Verified (using the `aws_canonical_user_id` data source) that the defaults for S3 API endpoints have not changed:
```
```
```console
% make testacc TESTARGS='-run=TestAccS3CanonicalUserIDDataSource_' PKG=s3
TF_ACC=1 go test ./internal/service/s3/... -v -count 1 -parallel 20  -run=TestAccS3CanonicalUserIDDataSource_ -timeout 180m
=== RUN   TestAccS3CanonicalUserIDDataSource_basic
=== PAUSE TestAccS3CanonicalUserIDDataSource_basic …
```
=> s3: Enable use of AWS SDK for Go v2

.changelog/33279.txt, internal/service/apigateway/account.go, internal/service/apigateway/account_test.go, website/docs/r/api_gateway_account.html.markdown
Closes #33236
```console
% make testacc TESTS=TestAccAPIGatewayAccount_basic  PKG=apigateway
--- PASS: TestAccAPIGatewayAccount_basic (157.07s)
```
=> r/api_gateway_account - fix account import + add some attributes

.changelog/33310.txt, internal/service/autoscaling/group.go, internal/service/autoscaling/group_test.go, website/docs/r/autoscaling_group.html.markdown
Adds the `scale_in_protected_instances` and `standby_instances` attributes to the `aws_autoscaling_group` instance refresh properties. These attributes allow for further control of the instance refresh bhevaiors in conditions where an instance may not normally refresh, or may result in the instance refresh failing.
One example use case is utilizing ecs capacity provider `managed_termination_protection` with `scale_in_protected_instances` set to `Refresh` to allow for ECS compute to be fully updated with a new AMI, current default behavior results in these protected instances not refreshing and the instance refresh failing.
Closes #29827
[Refresh Preferences API Docs](https://docs.aws.amazon.com/autoscaling/ec2/APIReference/API_RefreshPreferences.html)
[AWS Release Blog …
=> r/aws_autoscaling_group: Add instance_refresh preferences

.changelog/33316.txt, internal/service/dms/consts.go
AWS DMS currently supports creating endpoint targets for Redshift Serverless w/ the engine name `redshift-serverless` as seen below:
This pull requests enables `redshift-serverless` as an available option when creating AWS DMS endpoint resources, and the below MvP will successfully deploy an AWS DMS endpoint based on the AWS whitepaper documentation [here](https://docs.aws.amazon.com/dms/latest/userguide/CHAP_Target.Redshift.html).
```
terraform {
aws = {
version = ">= 2.7.0"
}
}
}
resource "aws_dms_endpoint" "test" {
endpoint_id   = "test-dms-endpoint-tf"
endpoint_type = "target"
engine_name   = "redshift-serverless"
username      = "<USERNAME>"
password      = "<PASSWORD>"
port          = 5439
database_name = "<WORKGROUP ENDPOINT>" …
```
=> Updated aws_dms_endpoint.engine_name possible values w/ redshift-serverless

internal/conns/config.go
Bumps `aws-sdk-go-base` dependency and removes custom allowed/forbidden account handling logic in favor of shared base method.
Relates https://github.com/hashicorp/aws-sdk-go-base/pull/638
```console
% go test -count=1 ./internal/conns/...
ok      github.com/hashicorp/terraform-provider-aws/internal/conns      0.266s
```
```console
% make sanity ACCTEST_PARALLELISM=10
==> Sanity Check (48 tests of Top 30 resources)
==> Like 'sane' but less output and runs all tests despite most errors
==> NOTE: NOT an exhaustive set of tests! Finds big problems only.
17 of 48 complete: 17 passed, 0 failed
33 of 48 complete: 33 passed, 0 failed
48 of 48 complete: 48 passed, 0 failed
```
=> internal/conns: switch to shared VerifyAccountIDAllowed method

.github/workflows/golangci-lint.yml
Disables the module cache for `setup-go` GitHub Actions when used with `golangci/golangci-lint-action`.
This _should_ speedup this workflow.
Closes https://github.com/hashicorp/terraform-provider-aws/issues/33239.
=> Disable module cache for `actions/setup-go` with `golangci/golangci-lint-action`

website/docs/index.html.markdown
The main assume_role configuration does not support environment variables, since they are not supported by the AWS SDK for Go v2. However, assume_role_with_web_identity does support the environment variables.
These were incorrectly added to documentation in https://github.com/hashicorp/terraform-provider-aws/pull/28265, and reported in https://github.com/hashicorp/terraform-provider-aws/issues/27016
Closes #33313
N/A
=> Removes incorrect environment variables from assume role documentation

.changelog/33336.txt, internal/service/efs/file_system.go, internal/service/efs/file_system_data_source.go, internal/service/efs/file_system_data_source_test.go
When an AWS account has more than 101 EFS resources, If you specify the data source of aws_efs_file_system with a tag, pagination does not work and the resource cannot be found.
This PR changes the DescribeFileSystems used at that time to use pagination.
- Create 101+ EFS
- Tag the oldest resource.
- Create a data source with the oldest resource's tag.
```
data "aws_efs_file_system" "foo" {
tags = {
test = "test"
}
}
```
- terraform apply
```
data.aws_efs_file_system.foo: Reading...
╷
│ Error: Search returned 0 results, please revise so only one is returned
│ 
│   with data.aws_efs_file_system.foo,
│   on main.tf line 14, in data "aws_efs_file_system" "foo":
│   14: data "aws_efs_file_system" "foo" {
```
```
data.aws_efs_file_system.foo: Reading...
data.aws_efs_file_system.foo: Read …
```
=> Added pagination support to DescribeFileSystems in EFS

.changelog/33405.txt, internal/service/lightsail/certificate.go, internal/service/lightsail/database.go, internal/service/lightsail/disk.go, internal/service/lightsail/instance.go, internal/service/lightsail/lb.go, internal/service/lightsail/lb_attachment.go, internal/service/lightsail/lb_certificate.go, internal/service/lightsail/lb_certificate_attachment.go, internal/service/lightsail/lb_https_redirection_policy.go, internal/service/lightsail/lb_stickiness_policy.go
Closes #33386
```console
% make t T=TestAccLightsailCertificate_basic K=lightsail
TF_ACC=1 go test ./internal/service/lightsail/... -v -count 1 -parallel 20 -run='TestAccLightsailCertificate_basic'  -timeout 180m
=== RUN   TestAccLightsailCertificate_basic
=== PAUSE TestAccLightsailCertificate_basic
=== CONT  TestAccLightsailCertificate_basic
--- PASS: TestAccLightsailCertificate_basic (58.16s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/lightsail	59.917s
% make t T=TestAccLightsailDisk K=lightsail P=4
TF_ACC=1 go test ./internal/service/lightsail/... -v -count 1 -parallel 4 -run='TestAccLightsailDisk'  -timeout 180m
=== RUN …
```
=> lightsail: Fix regex name validation

.changelog/32741.txt, internal/service/transfer/connector.go, internal/service/transfer/connector_test.go, website/docs/r/transfer_connector.html.markdown
This change is to enable SFTP connector to the AWS Transfer Family which already supports AS2 Config. 
Closes #32741 
https://docs.aws.amazon.com/transfer/latest/userguide/configure-sftp-connector.html#sftp-connector-secret-procedure
```console
[ec2-user@ip-172-31-29-38 terraform-provider-aws]$ make testacc PKG=transfer TESTS=TestAccTransferConnector_basic
TF_ACC=1 go test ./internal/service/transfer/... -v -count 1 -parallel 20 -run='TestAccTransferConnector_basic'  -timeout 180m
=== RUN   TestAccTransferConnector_basic
--- PASS: TestAccTransferConnector_basic (70.74s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/transfer   70.911s
[ec2-user@ip-172-31-29-38 terraform-provider-aws]$ …
```
=> F aws transfer connector

.changelog/33448.txt, internal/service/servicecatalog/find.go, internal/service/servicecatalog/product.go, internal/service/servicecatalog/product_test.go
Relates #33253
```console
$ make testacc TESTARGS='-run=TestAccServiceCatalogProduct_' PKG=servicecatalog
TF_ACC=1 go test ./internal/service/servicecatalog/... -v -count 1 -parallel 20  -run=TestAccServiceCatalogProduct_ -timeout 180m
--- PASS: TestAccServiceCatalogProduct_disappears (33.31s)
--- PASS: TestAccServiceCatalogProduct_basic (42.26s)
--- PASS: TestAccServiceCatalogProduct_update (62.14s)
--- PASS: TestAccServiceCatalogProduct_updateTags (63.19s)
--- PASS: TestAccServiceCatalogProduct_physicalID (64.23s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/servicecatalog	67.455s
```
=> aws_servicecatalog_product: import latest `provisioning_artifact_parameters`

.changelog/33413.txt, internal/service/neptune/cluster.go, internal/service/neptune/cluster_test.go
The KMS Key parameter is presently ignored when restoring a snapshot to a new cluster.  Users will use this parameter if they want to change the KMS encryption key of the new cluster to be different than that of the key used by the snapshot.  It is also used when a user wants to create a new encrypted cluster from an unencrypted snapshot, per Issue #15240 .
This PR also modifies the existing test for restoring from a snapshot to include the KMS key parameter.
Closes #15240.
Closes https://github.com/hashicorp/terraform-provider-aws/pull/15303.
https://docs.aws.amazon.com/neptune/latest/apiref/API_RestoreDBClusterFromSnapshot.html
```console
$ make testacc TESTS=TestAccNeptuneCluster_restoreFromSnapshot PKG=neptune …
```
=> r/neptune_cluster: fix ignored kms key on snapshot restore #15240. 

internal/service/s3/bucket.go, internal/service/s3/bucket_test.go, internal/service/s3/exports_test.go
Migrates the `FindBucket` helper function used by the `aws_s3_bucket` resource to AWS SDK for Go v2.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/33431.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/33358.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/33330.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/33304.
```console
% make testacc TESTARGS='-run=TestAccS3Bucket_' PKG=s3 ACCTEST_PARALLELISM=2
TF_ACC=1 go test ./internal/service/s3/... -v -count 1 -parallel 2  -run=TestAccS3Bucket_ -timeout 180m
=== RUN   TestAccS3Bucket_Basic_basic
=== PAUSE TestAccS3Bucket_Basic_basic
=== RUN   TestAccS3Bucket_Basic_emptyString
=== PAUSE …
```
=> r/aws_s3_bucket: Migrate `FindBucket` to AWS SDK for Go v2

.changelog/33456.txt, internal/service/dms/replication_task.go
When `replication_task_settings` attribute is removed the following error occurs:
``` 
Error: updating DMS Replication Task (test-dms-replication-task-tf): InvalidParameterValueException: Invalid task settings json 
│       status code: 400, request id: ab973d14-ad51-430e-9776-9cef4dce0593
│ 
│   with aws_dms_replication_task.test,
│   on main.tf line 82, in resource "aws_dms_replication_task" "test":
│   82: resource "aws_dms_replication_task" "test" {
```
```console
$ make testacc TESTARGS='-run=TestAccDMSReplicationTask_basic' PKG=dms 
TF_ACC=1 go test ./internal/service/dms/... -v -count 1 -parallel 20  -run=TestAccDMSReplicationTask_basic -timeout 180m
--- PASS: TestAccDMSReplicationTask_basic (1033.24s)
PASS
ok …
```
=> aws_dms_replication_task: allow removal of replication_task_settings

.changelog/33451.txt, internal/service/elasticache/cluster.go, internal/service/elasticache/cluster_test.go, internal/service/elasticache/diff.go
Fixes a regression for `redis` engine types caused by the new `transit_encryption_enabled` argument (added in v5.16.0). 
- Removes the default `false` value and makes the argument optional and computed. For `redis` engine types the value will effectively always be computed.
- Removes the `CustomizeDiff` function focused on the `transit_encryption_enabled` attribute, instead relying on the native AWS errors to provide the same feedback.
1. AWS error for minimum supported memcached version check:
```
Error: creating ElastiCache Cache Cluster (jb-test-memcached): InvalidParameterCombination: Encryption features are not supported for engine version 1.6.6. Please use engine version 1.6.12
```
2. AWS error when attempting to create a `redis` cluster with `transit_encryption_enabled` set (must …
=> r/aws_elasticache_cluster: fix transit_encryption_enabled for redis

.changelog/33477.txt, internal/service/sesv2/email_identity.go, internal/service/sesv2/email_identity_data_source.go, website/docs/r/sesv2_email_identity.html.markdown
Marking the DKIM signing key as sensitive
I believe this is what we need for #33333
=> Marking dkim signing key as sensitive

.changelog/33511.txt, internal/service/rds/flex.go, internal/service/rds/option_group_test.go, website/docs/r/db_option_group.html.markdown
Previously, on reading options back from AWS, `version` and `port` would be set even if they weren't configured. This PR changes that to check first if `version` and/or `port` is set in the configuration before setting the value from AWS.
This approach can be misleading in this scenario: a) `version` is set and applied, b) `version` is removed from the configuration. Diffs in `version` will not be checked. (The same would be true of `port`.) A practitioner may assume that removing the value will clear or remove the value from the AWS infrastructure. However, removing the value from configuration will instead just mean that Terraform will not detect diffs for `version` in the future.
Closes #21367
```console
% make t T=TestAccRDSOptionGroup_ K=rds P=4 …
```
=> rds/option_group: Fix bad diffs with version and port

docs/README.md, docs/add-a-new-service.md, mkdocs.yml
To help with the transition to requiring terraform-plugin-framework / aws-sdk-go-v2 all examples in the contributor documentation should lead with the preferred format. We should however preserve legacy examples to help contributors with existing resources. In order to present these various formats in a way that doesn't make the documentation hard to navigate we could use content tabs. This PR includes the mkdocs configuration to allow the use of content tabs, as well as some sample tabs.
- #32917
- #32976
=> [Docs]: Config and example content for content tabs

.changelog/33529.txt, internal/service/rds/instance.go, internal/service/rds/instance_test.go
When changing `storage_throughput`, AWS also wants `iops` and `allocated_storage` to be passed even if these are not changing.
Closes #33512
```console
% make t T=TestAccRDSInstance_storage K=rds                              
TF_ACC=1 go test ./internal/service/rds/... -v -count 1 -parallel 20 -run='TestAccRDSInstance_storage'  -timeout 180m
=== RUN   TestAccRDSInstance_storageChangeThroughput
=== PAUSE TestAccRDSInstance_storageChangeThroughput
=== RUN   TestAccRDSInstance_storageChangeIOPSThroughput
=== PAUSE TestAccRDSInstance_storageChangeIOPSThroughput
=== RUN   TestAccRDSInstance_storageChangeIOPS
=== PAUSE TestAccRDSInstance_storageChangeIOPS
=== RUN   TestAccRDSInstance_storageThroughputSSE
=== PAUSE …
```
=> rds/instance: Fix ability to change storage IOPS, throughput

website/docs/r/vpclattice_target_group.html.markdown
Update `vpclattice_target_group` resource documentatoin.
- The target group with `ALB` type doesn't support `config.health_check` block.
=> Update vpclattice_target_group resource docs

website/docs/r/vpclattice_target_group_attachment.html.markdown
- `port` doesn't use default port by `protocol`. The default port is inherited from the parent target group.
=> Update port description in vpclattice_target_group_attachment docs

website/docs/cdktf/python/d/connect_instance_storage_config.html.markdown, website/docs/cdktf/python/r/connect_instance_storage_config.html.markdown, website/docs/d/connect_instance_storage_config.html.markdown, website/docs/r/connect_instance_storage_config.html.markdown
* Add missing values for resource_type in aws_connect_instance_storage_config
* Make enum values sorting consistent across documentation.
Closes #33589
```console
...
```
=> (doc) aws_connect_instance_storage_config : fix enums fixes #33589

.changelog/33586.txt, internal/service/lightsail/bucket.go, internal/service/lightsail/bucket_test.go, website/docs/r/lightsail_bucket.html.markdown
adds `force_delete` attribute to Lightsail Bucket which allows to force delete a non-empty bucket during `terraform destroy`
I have amended the `testAccLightsailBucket_basic` to check for default `force_delete` value and added `testAccLightsailBucket_forceDelete` to check for `force_delete=true`. Happy to amend/add more acceptance tests if required.
Closes #33585
AWS Go SDK: https://docs.aws.amazon.com/sdk-for-go/api/service/lightsail/#Lightsail.DeleteBucket
**TestAccLightsailBucket_basic**
```console
% make testacc TESTS=TestAccLightsailBucket_basic PKG=lightsail
TF_ACC=1 go test ./internal/service/lightsail/... -v -count 1 -parallel 20 -run='TestAccLightsailBucket_basic'  -timeout 360m
=== RUN   TestAccLightsailBucket_basic
=== …
```
=> [enhancement]: r/aws_lightsail_bucket: add force_delete attr for lightsail s3 bucket

internal/service/fsx/sweep.go
Sets `bypass_snaplock_enterprise_retention`, bypassing errors like
```
2023/09/26 08:05:12 [ERROR] Error running Sweeper (aws_fsx_ontap_volume) in region (us-west-2): 1 error occurred:
* error sweeping FSx ONTAP Volume for us-west-2: 2 errors occurred:
* deleting FSx for NetApp ONTAP Volume (fsvol-034641efe8270af4c): BadRequest: Cannot delete a SnapLock Enterprise volume because it contains unexpired WORM files, it has files under legal hold, it has unexpired locked snapshots, or it is an unexpired SnapLock audit log volume. Set 'BypassSnaplockEnterpriseRetention' to true and try again.
* deleting FSx for NetApp ONTAP Volume (fsvol-04a4dd8ba505ec225): BadRequest: Cannot delete a SnapLock Enterprise volume because it contains unexpired WORM files, it has files under legal hold, it has …
```
=> r/aws_fsx_ontap_volume: Set `bypass_snaplock_enterprise_retention` in sweeper

internal/service/quicksight/sweep.go
The `aws_quicksight_vpc_connection` sweeper currently fails when used in an account where QuickSight isn't configured.
Previously:
> [ERROR] Error running Sweeper (aws_quicksight_vpc_connection) in region (us-west-2): listing QuickSight VPC Connections: ResourceNotFoundException: Directory information for account 123456789012 is not found.
Now:
```console
$  make sweep SWEEPERS=aws_quicksight_vpc_connection
[WARN] Skipping QuickSight VPC Connection sweep for us-west-2: ResourceNotFoundException: Directory information for account 123456789012 is not found.
```
=> sweeper/aws_quicksight_vpc_connection: Ignores error when account not configured for QuickSight

internal/service/servicecatalog/sweep.go
The sweeper fails with an error such as
> parsing Service Catalog Provisioning Artifact ID (pa-d3wdwwz5teu74): unexpected format of ID (pa-d3wdwwz5teu74), expected artifactID:productID
=> sweeper/aws_servicecatalog_provisioning_artifact: Fix sweeper

internal/service/cloudfront/continuous_deployment_policy.go, internal/service/cloudfront/continuous_deployment_policy_test.go, internal/service/cloudfront/distribution.go, internal/service/cloudfront/distribution_configuration_structure.go, internal/service/cloudfront/distribution_test.go, internal/service/cloudfront/sweep.go, website/docs/r/cloudfront_distribution.html.markdown
There is a careful delicate dance between a production `aws_cloudfront_distribution`, an `aws_clouldfront_continuous_deployment_policy`, and a staging `aws_cloudfront_distribution`. The AWS Console ("AWS Internal") does a lot for you in this regard. This fix brings in some of this functionality to allow continous deployments to be cleanly created and destroyed using Terraform.
This PR addresses two specific issues, in addition to cleanup and logic clarification:
1. The API updates a CloudFront resource's `etag` with every change to the resource. If you're doing multiple changes as part of deleting or updating, you'll get a new `etag` at each step. It's important to include the latest with each operation or you'll get `Precondition Failed` (or potentially `Invalid MatchIf Version`) errors. …
=> aws_cloudfront_distribution: IllegalUpdate test

internal/service/quicksight/sweep.go
Ignore errors like
```
2023/09/27 14:30:09 [ERROR] Error running Sweeper (aws_quicksight_vpc_connection) in region (us-gov-east-1): listing QuickSight VPC Connections: ResourceNotFoundException: Account information for account 123456789012 is not found.
```
Relates https://github.com/hashicorp/terraform-provider-aws/pull/33615.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/33612.
=> r/aws_quicksight_vpc_connection: Fix sweeper in US GovCloud

.changelog/33602.txt, examples/cleanrooms/main.tf, internal/service/cleanrooms/configured_table.go, internal/service/cleanrooms/configured_table_test.go, internal/service/cleanrooms/service_package_gen.go, website/docs/r/cleanrooms_configured_table.html.markdown
This pull request adds a new resource for AWS Clean Rooms service which is not currently fully supported by the plugin. The change adds Configured Table resource, which is used by the Collaboration to reference AWS Glue tables.
Relates #30024 
https://docs.aws.amazon.com/clean-rooms/latest/apireference/API_ConfiguredTable.html
```console
> make testacc TESTS=TestAccCleanRoomsConfiguredTable PKG=cleanrooms
TF_ACC=1 go test ./internal/service/cleanrooms/... -v -count 1 -parallel 20 -run='TestAccCleanRoomsConfiguredTable'  -timeout 360m
=== RUN   TestAccCleanRoomsConfiguredTable_basic
=== PAUSE TestAccCleanRoomsConfiguredTable_basic
=== RUN   TestAccCleanRoomsConfiguredTable_disappears
=== PAUSE …
```
=> Add Clean Rooms Configured Table resource

.changelog/33577.txt, internal/service/batch/job_queue.go, internal/service/batch/job_queue_test.go, website/docs/r/batch_job_queue.html.markdown
The AWS API is documented to take ARNs for the list of compute environments. Add validator to `compute_environments`.
Also adds test for multiple compute environments for a job queue.
Closes #33376
```console
% make testacc PKG=batch TESTS=TestAccBatchJobQueue_
--- PASS: TestAccBatchJobQueue_disappears (141.55s)
--- PASS: TestAccBatchJobQueue_ComputeEnvironments_externalOrderUpdate (142.84s)
--- PASS: TestAccBatchJobQueue_basic (150.52s)
--- PASS: TestAccBatchJobQueue_MigrateFromPluginSDK (156.94s)
--- PASS: TestAccBatchJobQueue_tags (191.81s)
--- PASS: TestAccBatchJobQueue_schedulingPolicy (196.51s)
--- PASS: TestAccBatchJobQueue_ComputeEnvironments_multiple (206.25s)
--- PASS: TestAccBatchJobQueue_state (210.15s)
--- PASS: TestAccBatchJobQueue_priority (210.15s)
```
=> resource/aws_batch_job_queue: Require ARN for `compute_environments` elements

internal/service/cloudfront/sweep.go
The `aws_cloudfront_distribution` sweeper has an infinite loop when there are no CloudFront Distributions
=> sweeper/aws_cloudfront_distribution: Fixes infinite loop

.changelog/33475.txt, internal/framework/flex/int.go, internal/framework/flex/int_test.go, internal/service/lexv2models/bot.go, internal/service/lexv2models/bot_test.go, internal/service/lexv2models/exports_test.go, internal/service/lexv2models/service_package_gen.go, names/names.go, website/docs/r/lexv2models_bot.html.markdown
Add bot resource to lexv2 service.
Closes #0000
```console
> make testacc TESTS=TestAccLexV2ModelsBot_ PKG=lexv2models
TF_ACC=1 go test ./internal/service/lexv2models/... -v -count 1 -parallel 20 -run='TestAccLexV2ModelsBot_'  -timeout 180m
=== RUN   TestAccLexV2ModelsBot_basic
=== PAUSE TestAccLexV2ModelsBot_basic
=== RUN   TestAccLexV2ModelsBot_tags
=== PAUSE TestAccLexV2ModelsBot_tags
=== RUN   TestAccLexV2ModelsBot_disappears
=== PAUSE TestAccLexV2ModelsBot_disappears
=== CONT  TestAccLexV2ModelsBot_disappears
=== CONT  TestAccLexV2ModelsBot_basic
=== CONT  TestAccLexV2ModelsBot_tags
--- PASS: TestAccLexV2ModelsBot_disappears (24.47s)
--- PASS: TestAccLexV2ModelsBot_basic (24.88s)
--- PASS: TestAccLexV2ModelsBot_tags (51.44s) …
```
=> Bot Resource for lexv2

.changelog/33662.txt, internal/service/cloud9/environment_ec2.go, internal/service/cloud9/environment_ec2_test.go, website/docs/r/cloud9_environment_ec2.html.markdown
> ### Description
> 
> Since a few weeks AWS offers Ubuntu 22.04 LTS as image for Cloud9 Environments next to Amazon Linux 2, but currently only Ubuntu 18.04 is available via the Terraform Provider. ![image](https://user-images.githubusercontent.com/120108972/270642607-07a12d59-f98b-49ce-90ed-d7f461706629.png)
> 
> When trying to use Ubuntu 22.04 as image this is the error response: `| Error: expected image_id to be one of [amazonlinux-1-x86_64 amazonlinux-2-x86_64 ubuntu-18.04-x86_64 resolve:ssm:/aws/service/cloud9/amis/amazonlinux-1-x86_64 resolve:ssm:/aws/service/cloud9/amis/amazonlinux-2-x86_64 resolve:ssm:/aws/service/cloud9/amis/ubuntu-18.04-x86_64], got ubuntu-22.04-x86_64 │ │ with aws_cloud9_environment_ec2.this["test"], │ on main.tf line 39, in resource …
=> Add Ubuntu 22.04 to Cloud9 ec2 options

internal/service/cloudfront/distribution.go, internal/service/cloudfront/sweep.go
Relates https://github.com/hashicorp/terraform-provider-aws/pull/33663.
```console
% make t T='TestAccCloudFrontContinuousDeploymentPolicy_domainChange|TestAccCloudFrontDistribution' K=cloudfront P=8
TF_ACC=1 go test ./internal/service/cloudfront/... -v -count 1 -parallel 8 -run='TestAccCloudFrontContinuousDeploymentPolicy_domainChange|TestAccCloudFrontDistribution'  -timeout 360m
=== RUN   TestAccCloudFrontContinuousDeploymentPolicy_domainChange
=== PAUSE TestAccCloudFrontContinuousDeploymentPolicy_domainChange
=== RUN   TestAccCloudFrontDistributionDataSource_basic
=== PAUSE TestAccCloudFrontDistributionDataSource_basic
=== RUN   TestAccCloudFrontDistribution_basic
=== PAUSE TestAccCloudFrontDistribution_basic
=== RUN …
```
=> cloudfront/distribution: Sweeper infinite loop

internal/service/s3control/multi_region_access_point_test.go
Tests the `aws_s3_object` using an MRAP.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/33358.
```console
% make testacc TESTARGS='-run=TestAccS3ControlMultiRegionAccessPoint_putAndGetObject' PKG=s3control
TF_ACC=1 go test ./internal/service/s3control/... -v -count 1 -parallel 20  -run=TestAccS3ControlMultiRegionAccessPoint_putAndGetObject -timeout 360m
=== RUN   TestAccS3ControlMultiRegionAccessPoint_putAndGetObject
=== PAUSE TestAccS3ControlMultiRegionAccessPoint_putAndGetObject
=== CONT  TestAccS3ControlMultiRegionAccessPoint_putAndGetObject
--- PASS: TestAccS3ControlMultiRegionAccessPoint_putAndGetObject (257.57s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/s3control	262.784s
```
=> r/aws_s3_object: Test access through a multi-region access point

go.mod, go.sum, internal/conns/awsclient_gen.go, internal/service/servicequotas/acc_test.go, internal/service/servicequotas/find.go, internal/service/servicequotas/service_data_source.go, internal/service/servicequotas/service_data_source_test.go, internal/service/servicequotas/service_package_gen.go, internal/service/servicequotas/service_quota.go, internal/service/servicequotas/service_quota_data_source.go, internal/service/servicequotas/service_quota_data_source_test.go, internal/service/servicequotas/service_quota_test.go, names/names.go, names/names_data.csv
Updates all `servicequotas` resources and data sources to AWS Go SDK V2. 
Relates #32976
```console
% make testacc PKG=servicequotas
TF_ACC=1 go test ./internal/service/servicequotas/... -v -count 1 -parallel 20   -timeout 360m
=== RUN   TestAccServiceQuotasServiceQuota_Value_increaseOnCreate
service_quota_test.go:146: Environment variable SERVICEQUOTAS_INCREASE_ON_CREATE_QUOTA_CODE is not set. WARNING: This test will submit a real service quota increase!
--- SKIP: TestAccServiceQuotasServiceQuota_Value_increaseOnCreate (0.00s)
=== RUN   TestAccServiceQuotasServiceQuota_Value_increaseOnUpdate
service_quota_test.go:190: Environment variable SERVICEQUOTAS_INCREASE_ON_UPDATE_QUOTA_CODE is not set. WARNING: This test will submit a …
```
=> aws_servicequotas: update to aws sdk v2

skaff/resource/resourcetest.tmpl
Fixes an incorrect `nil` return inside an error check of the `CheckDestroy` helper function.
N/a skaff
=> skaff: fix check destroy err return

.changelog/33688.txt, internal/service/servicequotas/exports_test.go, internal/service/servicequotas/service_package_gen.go, internal/service/servicequotas/template.go, internal/service/servicequotas/template_test.go, website/docs/r/servicequotas_template.html.markdown
The `aws_servicequotas_template` resource allows a management organization to add quota increases to a template to be applied across all member accounts.
Relates #9119
**NOTE**: Tests must be run from the management account of an organization, and in the `us-east-1` region
```console
% make testacc PKG=servicequotas TESTS=TestAccServiceQuotasTemplate_
TF_ACC=1 go test ./internal/service/servicequotas/... -v -count 1 -parallel 20 -run='TestAccServiceQuotasTemplate_'  -timeout 360m
--- PASS: TestAccServiceQuotasTemplate_disappears (11.79s)
--- PASS: TestAccServiceQuotasTemplate_basic (14.05s)
--- PASS: TestAccServiceQuotasTemplate_value (22.16s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/servicequotas …
```
=> [New Resource]: `aws_servicequotas_template`

.changelog/33705.txt, internal/service/sesv2/account_vdm_attributes.go, internal/service/sesv2/account_vdm_attributes_test.go, internal/service/sesv2/service_package_gen.go, website/docs/r/sesv2_account_vdm_attributes.html.markdown
This PR adds the `aws_sesv2_account_vdm_attributes` resource.
Closes #31406.
https://docs.aws.amazon.com/ses/latest/APIReference-V2/API_PutAccountVdmAttributes.html
```console
$ make testacc TESTARGS="-run=TestAccSESV2AccountVdmAttributes_serial" PKG=sesv2
TF_ACC=1 go test ./internal/service/sesv2/... -v -count 1 -parallel 20  -run=TestAccSESV2AccountVdmAttributes_serial -timeout 360m
=== RUN   TestAccSESV2AccountVdmAttributes_serial
=== PAUSE TestAccSESV2AccountVdmAttributes_serial
=== CONT  TestAccSESV2AccountVdmAttributes_serial
=== RUN   TestAccSESV2AccountVdmAttributes_serial/basic
=== RUN   TestAccSESV2AccountVdmAttributes_serial/disappears
=== RUN   TestAccSESV2AccountVdmAttributes_serial/engagementMetrics
=== RUN …
```
=> r/aws_sesv2_account_vdm_attributes: new resource

website/docs/r/codedeploy_deployment_group.html.markdown
Hello. The `aws_codedeploy_deployment_group` document was missing one event value, I added it.
- The only thing missing is documentation.
- Added `DEPLOYMENT_STOP_ON_REQUEST` in auto rollback configuration in the codedeploy group property.
- This property is also available in the API and GO SDK, and requires no Terraform code changes.
- GO Sdk Docs : https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/codedeploy/types#AutoRollbackEvent
- AWS API Docs : https://docs.aws.amazon.com/codedeploy/latest/APIReference/API_AutoRollbackConfiguration.html
The result of running terraform apply.
```console
+ resource "aws_codedeploy_deployment_group" "example" {
+ app_name               = "example"
...
+ auto_rollback_configuration {
+ enabled = true
+ events  = [
+ "DEPLOYMENT_STOP_ON_REQUEST",
] …
```
=> docs: add `DEPLOYMENT_STOP_ON_REQUEST` event type in auto rollback configuration for aws_codedeploy_deployment_group

skaff/resource/resourcetest.tmpl
The resource test template makes use of errors in multiple places, so `errors` should be added by default in the import list.
N/A
N/A
N/A
=> skaff resource test template is missing errors stdlib import.

.changelog/33765.txt, internal/service/ec2/find.go
fixing the transit gateway route search function by adding an additional filter.  when more than 1,000 routes are present in a route table and the filter matches ore than 1,000 routes, the list is truncated.  as noted in the linked issue, terraform will try to start recreating routes if they aren't returned
closes #33762 
https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_SearchTransitGatewayRoutes.html
https://github.com/hashicorp/terraform-provider-aws/blob/main/internal/service/ec2/find.go#L4600
NOTE: I need help with testing this from the admins/maintainers.  I validated the filter works as desired via the AWS CLI
=> fix: add additional tgw route filter 🌽

website/docs/r/codecommit_repository.html.markdown
This change ensures the `aws_codecommit_repository` resource has consistent and correct naming for CodeCommit. Currently there is a mix between `Codecommit` and `CodeCommit` in these docs, which the latter is the [correct name](https://aws.amazon.com/codecommit/) for the service.
N/A - doc change only in `website/`
=> docs: use consistent CodeCommit service name

.changelog/33725.txt, internal/service/servicequotas/exports_test.go, internal/service/servicequotas/service_package_gen.go, internal/service/servicequotas/servicequotas_test.go, internal/service/servicequotas/template_association.go, internal/service/servicequotas/template_association_test.go, internal/service/servicequotas/template_test.go, website/docs/r/servicequotas_template_association.html.markdown
The `aws_servicequotas_template_association` resource allows a management organization to associate (activate) a quota increases template to be applied across new member accounts.
Relates #9119
- https://docs.aws.amazon.com/servicequotas/2019-06-24/apireference/API_GetAssociationForServiceQuotaTemplate.html
- https://docs.aws.amazon.com/servicequotas/2019-06-24/apireference/API_AssociateServiceQuotaTemplate.html
- https://docs.aws.amazon.com/servicequotas/2019-06-24/apireference/API_DisassociateServiceQuotaTemplate.html
```console
% make testacc PKG=servicequotas TESTS=TestAccServiceQuotas_serial/TemplateAssociation
TF_ACC=1 go test ./internal/service/servicequotas/... -v -count 1 -parallel 20 …
```
=> [New Resource]: `aws_servicequotas_template_association`

internal/service/docdb/cluster_test.go
```
=== RUN   TestAccDocDBCluster_basic
=== PAUSE TestAccDocDBCluster_basic
=== CONT  TestAccDocDBCluster_basic
cluster_test.go:41: Step 1/2 error: Error running apply: exit status 1
Error: creating DocumentDB cluster: InvalidParameterCombination: The Parameter Group default.docdb4.0 with DBParameterGroupFamily docdb4.0 cannot be used for this instance. Please use a Parameter Group with DBParameterGroupFamily docdb5.0
status code: 400, request id: b3e1beb6-2d58-4659-b074-ccbd06c04205
with aws_docdb_cluster.default,
on terraform_plugin_test.tf line 11, in resource "aws_docdb_cluster" "default":
11: resource "aws_docdb_cluster" "default" {
--- FAIL: TestAccDocDBCluster_basic (1103.71s)
FAIL
```
```console
$ make testacc TESTARGS='-run=TestAccDocDBCluster_ -short' …
```
=> [tests] docdb test failures

.changelog/33871.txt, internal/service/servicequotas/service_package_gen.go, internal/service/servicequotas/servicequotas_test.go, internal/service/servicequotas/templates_data_source.go, internal/service/servicequotas/templates_data_source_test.go, website/docs/d/servicequotas_templates.html.markdown
The `aws_servicequotas_templates` data source lists all of the increase requests for a given region.
Relates #9119
```console
% make testacc PKG=servicequotas TESTS=TestAccServiceQuotas_serial/TemplatesDataSource/basic
TF_ACC=1 go test ./internal/service/servicequotas/... -v -count 1 -parallel 20 -run='TestAccServiceQuotas_serial/TemplatesDataSource/basic'  -timeout 360m
--- PASS: TestAccServiceQuotas_serial (11.02s)
--- PASS: TestAccServiceQuotas_serial/TemplatesDataSource (11.02s)
--- PASS: TestAccServiceQuotas_serial/TemplatesDataSource/basic (11.02s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/servicequotas      14.222s
```
=> [New Data Source]: `aws_servicequotas_templates`

.changelog/33880.txt, internal/service/ec2/verifiedaccess_instance.go, internal/service/ec2/verifiedaccess_instance_test.go, website/docs/r/verifiedaccess_instance.html.markdown
Adds the `fips_enabled` (optional, forces new) argument to `aws_verifiedaccess_instance`
Relates #29689
Announcement: [AWS Verified Access supports FIPS 140-2 compliant endpoints in US and Canada Regions](https://aws.amazon.com/about-aws/whats-new/2023/09/aws-verified-access-fips-140-2-compliant-endpoints-us-canada/)
```console
% make testacc TESTARGS='-run=TestAccVerifiedAccessInstance_' PKG=ec2 ACCTEST_PARALLELISM=5
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 5  -run=TestAccVerifiedAccessInstance_ -timeout 360m
=== RUN   TestAccVerifiedAccessInstance_basic
=== PAUSE TestAccVerifiedAccessInstance_basic
=== RUN   TestAccVerifiedAccessInstance_description
=== PAUSE TestAccVerifiedAccessInstance_description
=== …
```
=> r/aws_verifiedaccess_instance - fips_enabled

.changelog/33704.txt, internal/service/rds/validate.go, internal/service/rds/validate_test.go
> ### Community Note
> 
>     * Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
> 
>     * Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
> 
>     * If you are interested in working on this issue or have submitted a pull request, please leave a comment
> 
> 
> ### Terraform Version
> 
> Terraform v0.12.21 (same with 0.12.20)
> 
>     * provider.aws v2.50.0
> 
> 
> ### Affected Resource(s)
> 
>     * aws_db_parameter_group
> 
> 
> ### Terraform Configuration Files
> 
> ```terraform
> …
```
=> Allow periods in parameter group names for RDS

internal/service/applicationinsights/wait.go
The acceptance tests for `aws_applicationinsights_application` was failing with
>     testing_new.go:90: Error running post-test destroy, there may be dangling resources: exit status 1
>        2023/09/29 17:25:57 [DEBUG] Using modified User-Agent: Terraform/0.12.31 HashiCorp-terraform-exec/0.19.0
>        
>        Error: waiting for ApplicationInsights Application (tf-acc-test-8318256665595245541) delete: unexpected state 'ACTIVE', wanted target ''. last error: %!s(<nil>)
Add `ACTIVE` to expected states
```console
% make testacc PKG=applicationinsights TESTS=TestAccApplicationInsightsApplication_
--- PASS: TestAccApplicationInsightsApplication_disappears (29.45s)
--- PASS: TestAccApplicationInsightsApplication_autoConfig (32.35s)
--- PASS: TestAccApplicationInsightsApplication_basic …
```
=> resource/aws_applicationinsights_application: Fix acceptance test

.changelog/33916.txt, internal/service/redshiftserverless/workgroup.go, internal/service/redshiftserverless/workgroup_test.go, website/docs/r/redshiftserverless_workgroup.html.markdown
Allows SSL-related `config_parameters` to be specified in Terraform. Adding these can prevent persistent differences when AWS default values are returned in the `config_parameters` array.
Longer term the `config_parameters` argument could be refactored to suppress differences when keys with default values are returned from the read operation. The complexity involved with this approach warrants a deeper dive into the API. This PR aims simply to enable explicit configuration of these new keys to unblock existing configurations.
Before:
```console
% make testacc PKG=redshiftserverless TESTS=TestAccRedshiftServerlessWorkgroup_configParameters
TF_ACC=1 go test ./internal/service/redshiftserverless/... -v -count 1 -parallel 20 …
```
=> r/aws_redshiftserverless_workgroup: allow `require_ssl`, `use_fips_ssl` config parameters

.changelog/33844.txt, internal/service/deploy/deployment_group.go, internal/service/deploy/deployment_group_test.go, website/docs/r/codedeploy_deployment_group.html.markdown
The outdated_instances_strategy property is required in the deployment group of codedeploy.
This is a rarely used value, but it can prevent duplicate deployments when auto scaling.
Closes #33811
AWS Note: https://docs.aws.amazon.com/codedeploy/latest/userguide/deployment-groups-configure-advanced-options.html
AWS API: https://docs.aws.amazon.com/codedeploy/latest/APIReference/API_CreateDeploymentGroup.html
GO SDK: https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/codedeploy@v1.18.2/types#OutdatedInstancesStrategy
```console
$ make testacc TESTS=TestAccDeployDeploymentGroup_OutdatedInstancesStrategy_update PKG=deploy
TF_ACC=1 go test ./internal/service/deploy/... -v -count 1 -parallel 20 -run='TestAccDeployDeploymentGroup_OutdatedInstancesStrategy_update'  -timeout 360m
=== RUN …
```
=> codedeploy/deployment_group: add outdated instances strategy parameters

.changelog/33918.txt, internal/service/opensearchserverless/collection.go
Fix crash on import when Read() returns an error.
Closes #33666
```console
$ make testacc TESTARGS='-run=TestAccOpenSearchServerlessCollection_' PKG=opensearchserverless
TF_ACC=1 go test ./internal/service/opensearchserverless/... -v -count 1 -parallel 20  -run=TestAccOpenSearchServerlessCollection_ -timeout 360m
--- PASS: TestAccOpenSearchServerlessCollection_disappears (450.91s)
--- PASS: TestAccOpenSearchServerlessCollection_basic (471.98s)
--- PASS: TestAccOpenSearchServerlessCollection_update (483.57s)
--- PASS: TestAccOpenSearchServerlessCollection_tags (515.02s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/opensearchserverless	518.199s
```
=> r/aws_opensearchserverless_collection: return error on read

website/docs/r/config_configuration_recorder.html.markdown
* Clarify the documentation for the `aws_config_configuration_recorder` resource on configuration block `exclusion_by_resource_types` object by adding `resource_types` attribute.
* Add an example to `show recording_group` configuration to exclude specific resources types.
=> docs: Add exclusion_by_resource_types block object details for aws_config_configuration_recorder

website/docs/r/codebuild_project.html.markdown
Replaced the `build_timeout` and `queued_timeout` values' data type from a string to a number in the document because it is expected to be a Int in the [code](https://github.com/hashicorp/terraform-provider-aws/blob/main/internal/service/codebuild/project.go#L627-L632).
While it is not illegal to use a string value, it should be of the number data type.
=> Replace the values' data type from string to number in the document
