hashicorp/terraform-provider-aws

website/docs/r/instance.html.markdown

Terraform does not seem to use gp2 as the default property for the root_block_device.volume_type field.
It seems that it takes it from what the AMI specifies.
This PR changes that information in the documentation of the instance resource.
Closes #33919 
```console
...
```

r/instance: change default volume type

---

internal/service/budgets/budget_test.go

The acceptance tests for `aws_budgets_budget` were failing with
> === NAME  TestAccBudgetsBudget_autoAdjustDataHistorical
budget_test.go:237: Step 1/3 error: Check failed: 1 error occurred:
* Check 10/11 error: aws_budgets_budget.test: Attribute "limit_amount" value: strconv.Atoi: parsing "0.0": invalid syntax
>        
>=== NAME  TestAccBudgetsBudget_autoAdjustDataForecast
budget_test.go:204: Step 1/2 error: Check failed: 1 error occurred:
* Check 6/7 error: aws_budgets_budget.test: Attribute "limit_amount" value: strconv.Atoi: parsing "0.0": invalid syntax
Removes the failing checks, since they are redundant as they are checked in other tests.
```console
% make testacc PKG=budgets TESTS=TestAccBudgetsBudget_
--- PASS: TestAccBudgetsBudget_disappears (28.45s)
--- PASS: …
```

resource/aws_budgets_budget: Fix acceptance test failures

---

.changelog/32207.txt
internal/service/codecommit/repository.go
internal/service/codecommit/repository_test.go

This pull requests attempts to adjust the CodeCommit repository resource such that attempting to rename it succeeds (as is supported by the API), rather than forcing replacement of the resource (which is undesirable behavior in a resource such as this one that contains data).
Closes #32161
I'm not currently equipped to run the tests, unfortunately :-(
```
...
```

Properly handle renaming of CodeCommit repository

---

.changelog/33933.txt
internal/service/wafv2/flex.go
internal/service/wafv2/schemas.go
internal/service/wafv2/web_acl_test.go
website/docs/r/wafv2_web_acl.html.markdown

AWS recently released JA3 fingerprints into WAFv2.
This PR adds Terraform support for `ja3_fingerprint` as a `field_to_match` in a `byte_match_statement`.
Closes #33671
* https://docs.aws.amazon.com/waf/latest/APIReference/API_JA3Fingerprint.html
* https://docs.aws.amazon.com/waf/latest/developerguide/waf-rule-statement-fields-list.html#waf-rule-statement-request-component-ja3-fingerprint
* https://aws.amazon.com/about-aws/whats-new/2023/09/aws-waf-ja3-fingerprint-match/
```console
% make testacc TESTS=TestAccWAFV2WebACL_ByteMatchStatement_ja3fingerprint PKG=wafv2
TF_ACC=1 go test ./internal/service/wafv2/... -v -count 1 -parallel 20 -run='TestAccWAFV2WebACL_ByteMatchStatement_ja3fingerprint'  -timeout 360m
=== RUN …
```

Add `ja3_fingerprint` matching support to WAFv2

---

.changelog/33937.txt
internal/service/transfer/server.go

The previous limit of 512 characters is now increased to 4096.
Closes #33889
https://docs.aws.amazon.com/transfer/latest/userguide/API_CreateServer.html#TransferFamily-CreateServer-request-PreAuthenticationLoginBanner
The current acceptance tests are not performing limit validation. As such this does not have a test to verify that 4096 is indeed the limit. I can probably make a negative test and positive test pair proving 4096 is in fact the limit.

r/[Enhancement]: aws_transfer_server support for increased length login banners

---

internal/conns/awsclient.go
internal/conns/config.go
internal/provider/fwprovider/intercept.go
internal/provider/fwprovider/provider.go
internal/provider/provider.go
internal/service/meta/regions_data_source.go
internal/service/meta/service_package_gen.go

AWS SDK for Go v2 HTTP requests and responses were missing when `TF_LOG=debug` was defined.
The configured logger is only being used during provider configuration and needs to be added to each call's `Context` -- done via the `bootstrapContext` function called from wrapped resources and data sources.
Also, wrapped Framework data sources were never initializing a local copy of `meta` and so weren't setting much in `Context`.
```console
% make testacc TESTARGS='-run=TestAccProvider_' PKG_NAME=internal/provider
TF_ACC=1 go test ./internal/provider/... -v -count 1 -parallel 20  -run=TestAccProvider_ -timeout 360m
?   	github.com/hashicorp/terraform-provider-aws/internal/provider/fwprovider	[no test files]
=== RUN …
```

Ensure AWS SDK for Go v2 HTTP requests and responses are logged

---

docs/development-environment.md

Since https://github.com/hashicorp/terraform-provider-aws/pull/32108 the minimum version of Go is 1.20. Just bumped into it by accident while setting up on a machine I didn't use for some time.

docs: update Go version to 1.20 in env setup

---

.changelog/33950.txt
internal/service/iot/provisioning_template.go
internal/service/iot/provisioning_template_test.go
website/docs/r/iot_provisioning_template.html.markdown

Closes #33055
```console
$ make testacc TESTARGS='-run=TestAccIoTProvisioningTemplate_' PKG=iot
TF_ACC=1 go test ./internal/service/iot/... -v -count 1 -parallel 20  -run=TestAccIoTProvisioningTemplate_ -timeout 360m
--- PASS: TestAccIoTProvisioningTemplate_basic (162.08s)
--- PASS: TestAccIoTProvisioningTemplate_disappears (164.56s)
--- PASS: TestAccIoTProvisioningTemplate_update (249.10s)
--- PASS: TestAccIoTProvisioningTemplate_tags (330.74s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/iot	334.060s
```

r/iot_provisioning_template: add `type` attribute

---

.changelog/33969.txt
internal/service/cloudformation/stack.go

Closes #33327
```console
$ make testacc TESTARGS='-run=TestAccCloudFormationStack_' PKG=cloudformation
TF_ACC=1 go test ./internal/service/cloudformation/... -v -count 1 -parallel 20  -run=TestAccCloudFormationStack_ -timeout 360m
--- PASS: TestAccCloudFormationStack_disappears (122.15s)
--- PASS: TestAccCloudFormationStack_yaml (143.68s)
--- PASS: TestAccCloudFormationStack_onFailure (160.02s)
--- PASS: TestAccCloudFormationStack_withTransform (162.62s)
--- PASS: TestAccCloudFormationStack_basic (168.87s)
--- PASS: TestAccCloudFormationStack_updateFailure (171.24s)
--- PASS: TestAccCloudFormationStack_defaultParams (188.29s)
--- PASS: TestAccCloudFormationStack_withParams (209.04s)
--- PASS: …
```

r/aws_cloudformation_stack: Set computed fields correctly

---

.changelog/33963.txt
internal/service/iam/role.go
internal/service/iam/role_test.go
internal/service/iam/user.go
internal/service/iam/user_test.go

Closes #16534
```console
14:21 $ make testacc PKG=iam TESTS="TestAccIAMRole_permissionsBoundary"
TF_ACC=1 go test ./internal/service/iam/... -v -count 1 -parallel 20 -run='TestAccIAMRole_permissionsBoundary'  -timeout 360m
=== RUN   TestAccIAMRole_permissionsBoundary
=== PAUSE TestAccIAMRole_permissionsBoundary
=== CONT  TestAccIAMRole_permissionsBoundary
--- PASS: TestAccIAMRole_permissionsBoundary (146.16s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/iam	149.564s
14:32 $ make testacc PKG=iam TESTS="TestAccIAMUser_permissionsBoundary"
TF_ACC=1 go test ./internal/service/iam/... -v -count 1 -parallel 20 -run='TestAccIAMUser_permissionsBoundary' …
```

r/iam: fix refreshing permission_boundary state on users and roles

---

internal/service/chime/chime_test.go
internal/service/chime/voice_connector.go
internal/service/chime/voice_connector_group.go
internal/service/chime/voice_connector_group_test.go
internal/service/chime/voice_connector_logging.go
internal/service/chime/voice_connector_logging_test.go
internal/service/chime/voice_connector_origination.go
internal/service/chime/voice_connector_origination_test.go
internal/service/chime/voice_connector_termination.go
internal/service/chime/voice_connector_termination_credentials.go
internal/service/chime/voice_connector_termination_credentials_test.go
internal/service/chime/voice_connector_termination_test.go
internal/service/chime/voice_connector_test.go

Updates the deprecated chime endpoints
Relates #2697
Closes #33633
```console
> make testacc TESTS=TestAccChimeVoiceConnector_ PKG=chime
TF_ACC=1 go test ./internal/service/chime/... -v -count 1 -parallel 20 -run='TestAccChimeVoiceConnector_'  -timeout 360m
=== RUN   TestAccChimeVoiceConnector_basic
--- PASS: TestAccChimeVoiceConnector_basic (19.40s)
=== RUN   TestAccChimeVoiceConnector_disappears
--- PASS: TestAccChimeVoiceConnector_disappears (13.30s)
=== RUN   TestAccChimeVoiceConnector_update
--- PASS: TestAccChimeVoiceConnector_update (30.13s)
=== RUN   TestAccChimeVoiceConnector_tags
--- PASS: TestAccChimeVoiceConnector_tags (42.86s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/chime …
```

Change to updated endpoint

---

.changelog/33966.txt
internal/service/s3/bucket_object_lock_configuration.go

aws_s3_bucket_object_lock_configuration was used `RetryUntilNotFound` but it can not be delete.
It will cause `resource found` loop. 
I used `RetryWhenNotFound` in case object_lock_configuration cannot be get due to some error. I think this appropriate this case.
Closes #33943
Does not exist related test.
This is my first time PR for this org. Please point out if I've made any mistakes.

resource/aws_s3_bucket_object_lock_configuration: fix deletion bug

---

.changelog/33954.txt
internal/service/elasticache/cluster_test.go
internal/service/elasticache/engine_version.go
internal/service/elasticache/engine_version_test.go
internal/service/elasticache/replication_group_test.go

The resource `aws_elasticache_replication_group` incorrectly identifies switching from version `6.x` to `6.2` as a downgrade, which requires a re-creation of the resource.
Closes #28011
Supersedes #28877
```console
% make testacc PKG=elasticache TESTS=TestAccElastiCacheReplicationGroup_
--- PASS: TestAccElastiCacheReplicationGroup_clusteringAndCacheNodesCausesError (6.37s)
--- PASS: TestAccElastiCacheReplicationGroup_ValidationMultiAz_noAutomaticFailover (8.55s)
--- FAIL: TestAccElastiCacheReplicationGroup_tagWithOtherModification (928.49s)
--- PASS: TestAccElastiCacheReplicationGroup_ClusterMode_nonClusteredParameterGroup (987.41s)
--- PASS: TestAccElastiCacheReplicationGroup_multiAzNotInVPC (1008.87s)
--- PASS: TestAccElastiCacheReplicationGroup_multiAzNotInVPC_repeated (1009.08s)
--- …
```

resource/aws_elasticache_replication_group: Fix error incorrectly forcing recreation when changing version from `6.x` to `6.2`

---

internal/service/rds/certificate_data_source.go
internal/service/rds/certificate_data_source_test.go
internal/service/rds/instance.go
internal/service/rds/instance_test.go

Since changing `password` does not require downtime, if it is the only change, bypass Blue/Green deployment
Closes #32024
```console
% make testacc PKG=rds TESTS=TestAccRDSInstance_
--- PASS: TestAccRDSInstance_basic (849.87s)
--- PASS: TestAccRDSInstance_storageTypePostgres (1225.28s)
--- PASS: TestAccRDSInstance_noDeleteAutomatedBackups (1394.53s)
--- PASS: TestAccRDSInstance_PerformanceInsightsEnabled_disabledToEnabled (1396.08s)
--- PASS: TestAccRDSInstance_storageChangeIOPSThroughput (1549.41s)
--- PASS: TestAccRDSInstance_gp3MySQL (1732.90s)
--- PASS: TestAccRDSInstance_storageChangeIOPS (1786.49s)
--- PASS: TestAccRDSInstance_newIdentifier (1840.43s)
--- PASS: TestAccRDSInstance_BlueGreenDeployment_deletionProtectionBypassesBlueGreen (1842.25s)
--- PASS: …
```

resource/aws_db_instance: Changing `password` bypasses Blue/Green deployment

---

.changelog/34015.txt
internal/service/storagegateway/gateway.go
internal/service/storagegateway/gateway_test.go

Allows a value of `0` (representing Sunday) for the `maintenance_start_time.day_of_week` attribute of `aws_storagegateway_gateway` resources.
Previously, a zero value in this field would be converted to null, resulting in an error from AWS when deploying.
Added an acceptance test that validates this case.
Closes #26597
```console
% make testacc TESTS=TestAccStorageGatewayGateway_maintenanceStartTime PKG=storagegateway
TF_ACC=1 go test ./internal/service/storagegateway/... -v -count 1 -parallel 20 -run='TestAccStorageGatewayGateway_maintenanceStartTime'  -timeout 360m
=== RUN   TestAccStorageGatewayGateway_maintenanceStartTime
=== PAUSE TestAccStorageGatewayGateway_maintenanceStartTime
=== CONT …
```

[aws_storagegateway_gateway] Allow value of 0 for `maintenance_start_time.day_of_week`

---

.changelog/33992.txt
internal/service/elbv2/load_balancer.go
internal/service/elbv2/load_balancer_test.go
website/docs/r/lb.html.markdown

`aws_lb`: Adds a new attribute `dns_record_client_routing_policy` to enable support for Availability Zonal DNS affinity on Network Load Balancer (NLB).
Closes #33992 
- Launch announcement: https://aws.amazon.com/about-aws/whats-new/2023/10/aws-nlb-availability-performance-capabilities/
- SDK: https://pkg.go.dev/github.com/aws/aws-sdk-go@v1.45.27/service/elbv2#LoadBalancerAttribute
- API reference: https://docs.aws.amazon.com/elasticloadbalancing/latest/APIReference/API_LoadBalancerAttribute.html
```console
$ make testacc TESTS='TestAccELBV2LoadBalancer' PKG=elbv2
TF_ACC=1 go test ./internal/service/elbv2/... -v -count 1 -parallel 20 -run='TestAccELBV2LoadBalancer'  -timeout 360m
=== RUN   TestAccELBV2LoadBalancerDataSource_basic …
```

Add support for Availability Zonal DNS affinity on NLB

---

.changelog/34033.txt
internal/service/configservice/config_rule.go
internal/service/configservice/config_rule_test.go
internal/service/configservice/configservice_test.go
internal/service/configservice/flex.go
website/docs/r/config_config_rule.html.markdown

Closes #33532
```console
$ make testacc PKG=configservice TESTARGS='-run=TestAccConfigService_serial/^ConfigRule/$'
TF_ACC=1 go test ./internal/service/configservice/... -v -count 1 -parallel 20  -run=TestAccConfigService_serial/^ConfigRule/ -timeout 360m
=== RUN   TestAccConfigService_serial
=== PAUSE TestAccConfigService_serial
=== CONT  TestAccConfigService_serial
=== RUN   TestAccConfigService_serial/ConfigRule
=== RUN   TestAccConfigService_serial/ConfigRule/disappears
=== RUN   TestAccConfigService_serial/ConfigRule/ownerAws
=== RUN   TestAccConfigService_serial/ConfigRule/customPolicy
=== RUN   TestAccConfigService_serial/ConfigRule/scopeTagValue
=== RUN   TestAccConfigService_serial/ConfigRule/tags
=== RUN …
```

r/aws_config_config_rule: add `evaluation_mode`

---

.teamcity/settings.kts

Because full acceptance test runs take a significant amount of time, multiple daily sweeper, performance, and sanity builds can be queued. Allow older runs to be replaced if they are queued

ci: Don't allow multiple sweeper, performance, or sanity builds in queue

---

website/docs/r/vpc_ipam_pool_cidr.html.markdown

- Current example code for IPv6 IPAM Pool is not working.
- Update example for ipv6 usecase of vpc_ipam_pool_cidr resource

Update example for ipv6 usecase of vpc_ipam_pool_cidr resource

---

.changelog/34037.txt
internal/service/identitystore/group.go
internal/service/identitystore/group_test.go

Small bugfix for updating`aws_identitystore_group` description attribute
Closes https://github.com/hashicorp/terraform-provider-aws/issues/28093
```console
%  make testacc TESTS=TestAccIdentityStoreGroup_descriptionChange PKG=identitystore
TF_ACC=1 go test ./internal/service/identitystore/... -v -count 1 -parallel 20 -run='TestAccIdentityStoreGroup_descriptionChange'  -timeout 360m
=== RUN   TestAccIdentityStoreGroup_descriptionChange
=== PAUSE TestAccIdentityStoreGroup_descriptionChange
=== CONT  TestAccIdentityStoreGroup_descriptionChange
--- PASS: TestAccIdentityStoreGroup_descriptionChange (69.26s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/identitystore	71.409s
```

fix: aws_identitystore_group update description attribute

---

.changelog/34053.txt
internal/service/neptune/cluster.go
internal/service/neptune/cluster_test.go
website/docs/cdktf/python/r/neptune_cluster.html.markdown
website/docs/r/neptune_cluster.html.markdown

Add the ability to export Neptune slow query logs to CloudWatch.
This can be done using the AWS CLI and Console, but fails validation when you try to set it using the module, which causes drifts.
Non known relations
AWS CLI instructions for setting this log export - https://docs.aws.amazon.com/neptune/latest/userguide/cloudwatch-logs.html#cloudwatch-slow-query-logs-cli
```console
% make testacc TESTS=TestAccNeptuneCluster_updateCloudWatchLogsExports PKG=neptune
TF_ACC=1 go test ./internal/service/neptune/... -v -count 1 -parallel 20 -run='TestAccNeptuneCluster_updateCloudWatchLogsExports'  -timeout 360m
=== RUN   TestAccNeptuneCluster_updateCloudWatchLogsExports
=== PAUSE TestAccNeptuneCluster_updateCloudWatchLogsExports
=== CONT …
```

Neptune slow query logs cloudwatch export

---

.changelog/32698.txt
internal/service/dms/s3_endpoint.go

Removes the default `add_trailing_padding_character` attribute for `aws_dms_s3_endpoint` resources. This default was previously `false`, but will now result in no value being specified (relying AWS's server-side default of `false`). 
This fixes an incompatibility with old versions of the DMS engine (<3.4.7), which raise an error when this attribute is defined. Behavior will remain unchanged for DMS versions >=3.4.7.
Closes #32698 
- [AWS DMS release notes](https://docs.aws.amazon.com/dms/latest/userguide/CHAP_ReleaseNotes.html#CHAP_ReleaseNotes.DMS347), showing the addition of the `AddTrailingPaddingCharacter` option in 3.4.7.
- [AWS DMS S3Settings documentation](https://docs.aws.amazon.com/dms/latest/APIReference/API_S3Settings.html), showing the default value of `false` if no …

[aws_dms_s3_endpoint] Remove the default value of `false` for `add_trailing_padding_character`

---

.changelog/34045.txt
CHANGELOG.md
internal/acctest/acctest.go
internal/service/lambda/flex.go
internal/service/lambda/function.go
internal/service/lambda/function_test.go
website/docs/r/lambda_function.html.markdown

This PR adds support for the `ipv6_allowed_for_dual_stack` field on the `aws_lambda_function` resource.
This allows outbound IPv6 traffic on VPC functions that are connected to dual-stack subnets.
Note to the reviewer, I wasn't able to run all tests within the `TestAccLambdaFunction_` suite because of a VPC quota within my project.
Closes https://github.com/hashicorp/terraform-provider-aws/issues/33922
```console
terraform-provider-aws git:(f/add-lambda-ipv6-dual-stack-field) ✗ make testacc TESTS=TestAccLambdaFunction_ipv6AllowedForDualStack PKG=lambda
TF_ACC=1 go test ./internal/service/lambda/... -v -count 1 -parallel 20 -run='TestAccLambdaFunction_ipv6AllowedForDualStack'  -timeout 360m
=== RUN …
```

Add `ipv6_allowed_for_dual_stack` field for lambda function

---

.changelog/34073.txt
internal/provider/tags_interceptor.go

Guard against `tags_all` being `null`
Closes #33995
```console
$ make testacc TESTARGS='-run=TestAccVPC_ -short' PKG=vpc
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 20  -run=TestAccVPC_ -short -timeout 360m
vpc_test.go:1021: skipping long-running test in short mode
vpc_test.go:1048: skipping long-running test in short mode
vpc_test.go:1076: skipping long-running test in short mode
--- SKIP: TestAccVPC_IPAMIPv6 (0.00s)
=== NAME  TestAccVPC_assignGeneratedIPv6CIDRBlockWithNetworkBorderGroup
ec2_availability_zone_data_source_test.go:222: skipping since no Local Zones are available
--- SKIP: …
```

tags: check that `tags_all` is not null

---

.github/workflows/library_versions.yml

Adds a new CI check which inspects a pull request diff for references to non-preferred libraries (ie. AWS SDK for Go V1). The check does not fail if references are detected, but leaves an automated comment similar to the check for modifications to `go.mod`/`go.sum`.
Successfully tested the `diffgrep` job in a private repo, and the `comment` job is largely copied from an existing workflow.
Relates #32917

ci: library version check github action

---

.github/workflows/library_versions.yml

Adjusts the grep regular expression so that only added import lines will match. Previously unmodified lines which are displayed with the diff for context could also match the provided expression. Now the line must start with a literal +, contain only whitespace prior to a double quote, and match the root path of the AWS SDK for Go v1 library.
Also fixes the `body-includes` argument in the check for existing comments so that the comment is not repeated on subsequent commits.
Relates #34083

ci: fix diff grep regex

---

go.mod
go.sum
internal/framework/flex/autoflex.go
internal/framework/flex/autoflex_test.go

Closes #0000
```console
% go test ./internal/framework/flex... -v -count 1 -parallel 20 -run='TestGeneric'  -timeout 360m
=== RUN   TestGenericExpand
=== PAUSE TestGenericExpand
=== RUN   TestGenericFlatten
=== PAUSE TestGenericFlatten
=== CONT  TestGenericExpand
=== CONT  TestGenericFlatten
=== RUN   TestGenericExpand/nil_Source_and_Target
=== PAUSE TestGenericExpand/nil_Source_and_Target
=== RUN   TestGenericFlatten/nil_Source_and_Target
=== RUN   TestGenericExpand/non-pointer_Target
=== PAUSE TestGenericExpand/non-pointer_Target
=== RUN   TestGenericExpand/non-struct_Source
=== PAUSE TestGenericFlatten/nil_Source_and_Target
=== PAUSE TestGenericExpand/non-struct_Source
=== RUN   TestGenericFlatten/non-pointer_Target
=== RUN   TestGenericExpand/non-struct_Target
=== PAUSE …
```

autoflex: Add fuzzy matching fields

---

internal/framework/flex/bool.go
internal/framework/flex/int.go
internal/framework/flex/list.go
internal/framework/flex/map.go
internal/framework/flex/set.go
internal/framework/flex/string.go
internal/framework/flex/string_test.go
internal/framework/types/arn.go
internal/framework/types/cidr_block.go
internal/framework/types/duration.go
internal/framework/types/regexp.go
internal/framework/validators/aws_account_id.go
internal/framework/validators/aws_account_id_test.go
internal/service/batch/job_queue.go
internal/service/cognitoidp/user_pool_client.go
internal/service/globalaccelerator/accelerator_data_source.go
internal/service/lexv2models/bot.go
internal/tfresource/retry.go

Additional Terraform Plugin Framework helpers and changes.
Relates #34034.
```console
% go test ./internal/framework/...
?   	github.com/hashicorp/terraform-provider-aws/internal/framework	[no test files]
ok  	github.com/hashicorp/terraform-provider-aws/internal/framework/flex	0.551s
ok  	github.com/hashicorp/terraform-provider-aws/internal/framework/types	0.709s
ok  	github.com/hashicorp/terraform-provider-aws/internal/framework/validators	0.567s
```
```console
% make testacc TESTARGS='-run=TestAccBatchJobQueue_schedulingPolicy' PKG=batch
TF_ACC=1 go test ./internal/service/batch/... -v -count 1 -parallel 20  -run=TestAccBatchJobQueue_schedulingPolicy -timeout 360m
=== RUN   TestAccBatchJobQueue_schedulingPolicy
=== PAUSE …
```

Additional Framework helpers

---

internal/service/dynamodb/sweep.go
internal/service/ec2/ec2_instance.go
internal/service/ec2/sweep.go
internal/service/finspace/sweep.go
internal/service/sagemaker/project.go
internal/service/sagemaker/sweep.go

Various sweeper fixes:
* `aws_instance` always enable API Stop
* `aws_dynamodb_table` always disable Deletion Protection
* `aws_finspace_kx_environment` skip environments in non-deletable state
* `aws_sagemaker_project` serialize to avoid throttling errors
`make sweep SWEEP=us-west-2` and `make sweep SWEEP=us-gov-west-1` successfully run to completion.

Various sweeper fixes

---

.changelog/34112.txt
internal/service/kms/external_key.go
internal/service/kms/key.go
internal/service/kms/replica_external_key.go
internal/service/kms/replica_key.go
internal/service/kms/wait.go
website/docs/r/kms_key.html.markdown

Add configurable timeout to `aws_kms_key`
```console
$ make testacc TESTARGS='-run=TestAccKMSKey_' PKG=kms
TF_ACC=1 go test ./internal/service/kms/... -v -count 1 -parallel 20  -run=TestAccKMSKey_ -timeout 360m
--- PASS: TestAccKMSKey_disappears (101.00s)
--- PASS: TestAccKMSKey_hmacKey (114.48s)
--- PASS: TestAccKMSKey_asymmetricKey (114.94s)
--- PASS: TestAccKMSKey_multiRegion (121.88s)
--- PASS: TestAccKMSKey_Policy_basic (174.00s)
--- PASS: TestAccKMSKey_basic (178.62s)
--- PASS: TestAccKMSKey_updateTagsEmptyValue (180.75s)
--- PASS: TestAccKMSKey_Policy_bypassUpdate (212.23s)
--- PASS: TestAccKMSKey_ignoreTags (224.56s)
--- PASS: TestAccKMSKey_Policy_booleanCondition (232.03s)
--- PASS: TestAccKMSKey_Policy_iamRole (237.76s) …
```

r/aws_kms key: add configurable timeout

---

.changelog/34086.txt
internal/service/autoscaling/consts.go
internal/service/autoscaling/group.go
internal/service/autoscaling/group_test.go

Closes #33912.
Closes https://github.com/hashicorp/terraform-provider-aws/pull/34027.
```console
$ make testacc TESTARGS='-run=TestAccAutoScalingGroup_basic\|TestAccAutoScalingGroup_disappears\|TestAccAutoScalingGroup_LaunchTemplate_update\|TestAccAutoScalingGroup_MixedInstancesPolicyLaunchTemplateLaunchTemplateSpecification_launchTemplateName' PKG=autoscaling
TF_ACC=1 go test ./internal/service/autoscaling/... -v -count 1 -parallel 20  -run=TestAccAutoScalingGroup_basic\|TestAccAutoScalingGroup_disappears\|TestAccAutoScalingGroup_LaunchTemplate_update\|TestAccAutoScalingGroup_MixedInstancesPolicyLaunchTemplateLaunchTemplateSpecification_launchTemplateName -timeout 360m
--- PASS: TestAccAutoScalingGroup_disappears (115.66s)
--- …
```

r/aws_autoscaling_group: launch_template name update

---

.changelog/34109.txt
internal/service/networkmanager/connect_attachment.go
internal/service/networkmanager/connect_attachment_test.go
internal/service/networkmanager/connect_peer.go
internal/service/networkmanager/connect_peer_test.go
website/docs/r/networkmanager_connect_attachment.html.markdown
website/docs/r/networkmanager_connect_peer.html.markdown

- `aws_networkmanager_connect_attachment`: Add support for the `NO_ENCAP` protocol option required for tunnel-less connect.
- `aws_networkmanager_connect_peer`: Add `subnet_arn` attribute to support tunnel-less Connect attachments
- `aws_networkmanager_connect_peer`: Mark `inside_cidr_blocks` argument as optional to support tunnel-less Connect attachments
This also updates the existing acceptance tests to check for the protocol type.
Closes #34101
Launch announcement: https://aws.amazon.com/about-aws/whats-new/2023/10/aws-cloud-wan-tunnel-less-high-performant-global-sd-wans/
API reference: https://docs.aws.amazon.com/networkmanager/latest/APIReference/API_ConnectAttachmentOptions.html#networkmanager-Type-ConnectAttachmentOptions-Protocol
```console
$ make testacc …
```

[Enhancement] Add NO_ENCAP support to aws_networkmanager_connect_attachment

---

.changelog/34141.txt
internal/service/amplify/branch.go
internal/service/amplify/branch_test.go

Unnecessary `ForceNew` are included at `enable_performance_mode`.
Closes #34130
`ForceNew` isn't written in document.
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/amplify_branch#enable_performance_mode
```console
$ make testacc TESTARGS='-run=TestAccAmplify_serial/Branch/OptionalArguments' PKG=amplify
TF_ACC=1 go test ./internal/service/amplify/... -v -count 1 -parallel 20  -run=TestAccAmplify_serial/Branch/OptionalArguments -timeout 360m
=== RUN   TestAccAmplify_serial
=== PAUSE TestAccAmplify_serial
=== CONT  TestAccAmplify_serial
=== RUN   TestAccAmplify_serial/Branch
=== RUN   TestAccAmplify_serial/Branch/OptionalArguments
--- PASS: TestAccAmplify_serial (338.48s)
--- PASS: …
```

resource/aws_amplify_branch: fix forces replacement

---

go.mod
go.sum
internal/conns/awsclient_gen.go
internal/service/athena/data_catalog.go
internal/service/athena/data_catalog_test.go
internal/service/athena/database.go
internal/service/athena/database_test.go
internal/service/athena/exports_test.go
internal/service/athena/generate.go
internal/service/athena/named_query.go
internal/service/athena/named_query_test.go
internal/service/athena/service_package_gen.go
internal/service/athena/sweep.go
internal/service/athena/tags_gen.go
internal/service/athena/workgroup.go
internal/service/athena/workgroup_test.go
internal/service/events/target.go
names/names.go
names/names_data.csv

Replace service-specific `allDiagFunc` with Plugin SDK v2 implementation.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/33355.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/27050.
Relates https://github.com/hashicorp/terraform-plugin-sdk/pull/1155.
```console
% make testacc TESTARGS='-run=TestAccAthenaDataCatalog_\|TestAccAthenaDatabase_\|TestAccAthenaNamedQuery_\|TestAccAthenaWorkGroup_' PKG=athena ACCTEST_PARALLELISM=3
TF_ACC=1 go test ./internal/service/athena/... -v -count 1 -parallel 3  -run=TestAccAthenaDataCatalog_\|TestAccAthenaDatabase_\|TestAccAthenaNamedQuery_\|TestAccAthenaWorkGroup_ -timeout 360m
=== RUN   TestAccAthenaDataCatalog_basic
=== PAUSE TestAccAthenaDataCatalog_basic
=== …
```

Tech debt: Use Plugin SDK v2 `All` `Diag`-flavor validator combinator

---

.changelog/34181.txt
internal/service/redshift/cluster.go
internal/service/redshift/cluster_test.go
website/docs/r/redshift_cluster.html.markdown

Closes #29293
```console
%  make testacc TESTS=TestAccRedshiftCluster_restoreFromSnapshot
--- PASS: TestAccRedshiftCluster_restoreFromSnapshotArn (698.39s)
```

r/redshift_cluster - add support for restoring from `snapshot_arn`

---

.github/workflows/library_versions.yml

This change should allow the Github comment job to have the necessary write permissions, even when pull requests are opened from forks.
Relates #34083
- https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target

ci: switch library_versions action to pull_request_target event

---

.changelog/34180.txt
internal/service/secretsmanager/secret_rotation.go
internal/service/secretsmanager/secret_rotation_test.go
website/docs/r/secretsmanager_secret_rotation.html.markdown

This change makes the `rotation_lambda_arn` argument optional, allowing for use cases where secrets are managed by AWS and do not require a custom lambda function ARN to be specified.
Closes #34108 
- https://docs.aws.amazon.com/secretsmanager/latest/userguide/rotate-secrets_managed.html
- https://docs.aws.amazon.com/secretsmanager/latest/apireference/API_RotateSecret.html
```console
% make testacc PKG=secretsmanager TESTS=TestAccSecretsManagerSecretRotation_
TF_ACC=1 go test ./internal/service/secretsmanager/... -v -count 1 -parallel 20 -run='TestAccSecretsManagerSecretRotation_'  -timeout 360m
--- PASS: TestAccSecretsManagerSecretRotation_basic (314.98s)
--- PASS: TestAccSecretsManagerSecretRotation_duration (315.52s)
--- PASS: …
```

r/aws_secretsmanager_secret_rotation: support managed secrets

---

.changelog/34191.txt
internal/service/iot/topic_rule.go
internal/service/iot/topic_rule_test.go
website/docs/r/iot_topic_rule.html.markdown

Allow adding Kafka headers to AWS IoT topic rules.
Closes #34005
```console
make testacc TESTS=TestAccIoTTopicRule_kafka PKG=iot
TF_ACC=1 go test ./internal/service/iot/... -v -count 1 -parallel 20 -run='TestAccIoTTopicRule_kafka'  -timeout 360m
=== RUN   TestAccIoTTopicRule_kafka
=== PAUSE TestAccIoTTopicRule_kafka
=== CONT  TestAccIoTTopicRule_kafka
--- PASS: TestAccIoTTopicRule_kafka (402.14s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/iot        404.107s
```

Add Kafka message headers to IoT topic rules

---

.changelog/34182.txt
internal/service/redshift/cluster.go
internal/service/redshift/cluster_test.go
website/docs/r/redshift_cluster.html.markdown

This change adds the `manage_master_password` and `master_password_secret_kms_key_id` arguments allowing the configuration of AWS managed credentials via SecretsManager. The `manage_master_password` argument conflicts with the `master_password` argument, and at least one must be set when creating a new cluster not restored from a snapshot. The `master_password_secret_arn` attribute was added to track the ARN of the SecretsManager secret which stores cluster credentials.
Closes #34169 
- https://docs.aws.amazon.com/redshift/latest/APIReference/API_Cluster.html
- https://docs.aws.amazon.com/redshift/latest/APIReference/API_CreateCluster.html
```console
%  make testacc PKG=redshift TESTS="TestAccRedshiftCluster_" …
```

r/aws_redshift_cluster: support managed master passwords

---

.changelog/34187.txt
internal/service/rds/cluster.go

Closes #33465
```console
% make t T=TestAccRDSCluster_ K=rds     
TF_ACC=1 go test ./internal/service/rds/... -v -count 1 -parallel 20 -run='TestAccRDSCluster_'  -timeout 360m
=== RUN   TestAccRDSCluster_basic
=== PAUSE TestAccRDSCluster_basic
=== RUN   TestAccRDSCluster_disappears
=== PAUSE TestAccRDSCluster_disappears
=== RUN   TestAccRDSCluster_identifierGenerated
=== PAUSE TestAccRDSCluster_identifierGenerated
=== RUN   TestAccRDSCluster_identifierPrefix
=== PAUSE TestAccRDSCluster_identifierPrefix
=== RUN   TestAccRDSCluster_tags
=== PAUSE TestAccRDSCluster_tags
=== RUN   TestAccRDSCluster_allowMajorVersionUpgrade
=== PAUSE TestAccRDSCluster_allowMajorVersionUpgrade
=== RUN …
```

rds/cluster: Use AWS backup retention default

---

internal/service/finspace/kx_cluster_test.go

Applies the license check pre-check to two Kx Cluster acceptance tests which are currently missing it. All Kx Cluster tests should be explicitly opted into running as a license is required to provision clusters.
Relates #33745
```console
%  make testacc PKG=finspace TESTS=TestAccFinSpaceKxCluster_
TF_ACC=1 go test ./internal/service/finspace/... -v -count 1 -parallel 20 -run='TestAccFinSpaceKxCluster_'  -timeout 360m
=== NAME  TestAccFinSpaceKxCluster_cacheConfigurations
kx_cluster_test.go:28: Environment variable FINSPACE_MANAGED_KX_LICENSE_ENABLED is not set. Certain managed KX resources require the target account to have an active license. Set the environment variable to any value to enable these tests.
--- SKIP: …
```

r/aws_finspace_kx_cluster(test): add missing license check gates

---

internal/service/lambda/event_source_mapping_test.go
internal/service/mq/broker_data_source_test.go
internal/service/mq/broker_test.go
internal/service/mq/configuration_test.go
internal/service/pipes/pipe_test.go
website/docs/r/mq_broker.html.markdown
website/docs/r/mq_configuration.html.markdown

The acceptance tests for the MQ service were using outdated engine versions. Update them to current versions.
Long-term solution will be #34168
AWS Partition
```console
% make testacc PKG=mq
--- PASS: TestCanonicalXML (0.00s)
--- PASS: TestCanonicalXML/Config_sample_from_MSDN (0.00s)
--- PASS: TestCanonicalXML/A_note (0.00s)
--- PASS: TestCanonicalXML/Config_sample_from_MSDN,_flaw (0.00s)
--- PASS: TestCanonicalXML/Config_sample_from_MSDN,_modified (0.00s)
--- PASS: TestDiffUsers (0.00s)
--- PASS: TestAccMQConfiguration_withRabbitMQData (394.04s)
--- PASS: TestAccMQConfiguration_withActiveMQLdapData (396.93s)
--- PASS: TestAccMQConfiguration_withActiveMQData (401.39s)
--- PASS: TestValidateBrokerName (0.00s)
--- PASS: TestBrokerPasswordValidation (0.00s)
--- PASS: …
```

acctest: Bump engine versions for MQ tests

---

.changelog/34144.txt
internal/service/opensearchserverless/exports_test.go
internal/service/opensearchserverless/find.go
internal/service/opensearchserverless/lifecycle_policy.go
internal/service/opensearchserverless/lifecycle_policy_data_source.go
internal/service/opensearchserverless/lifecycle_policy_data_source_test.go
internal/service/opensearchserverless/lifecycle_policy_test.go
internal/service/opensearchserverless/service_package_gen.go
website/docs/d/opensearchserverless_lifecycle_policy.html.markdown
website/docs/r/opensearchserverless_lifecycle_policy.html.markdown

Combining the resource and data source into 1 PR with 2 separate commits.
- Adding new resource for OpenSearch Serverless Lifecycle Policy
- Adding new data source for OpenSearch Serverless Lifecycle Policy
Closes #34092
- https://docs.aws.amazon.com/opensearch-service/latest/ServerlessAPIReference/API_CreateLifecyclePolicy.html
```console
% make testacc TESTS=TestAccOpenSearchServerlessLifecyclePolicy PKG=opensearchserverless
TF_ACC=1 go test ./internal/service/opensearchserverless/... -v -count 1 -parallel 20 -run='TestAccOpenSearchServerlessLifecyclePolicy'  -timeout 360m
=== RUN   TestAccOpenSearchServerlessLifecyclePolicy_basic
=== PAUSE TestAccOpenSearchServerlessLifecyclePolicy_basic
=== RUN …
```

Add `aws_opensearchserverless_lifecycle_policy` resource and data source

---

internal/flex/flex.go
internal/maps/maps.go
internal/service/apigatewayv2/integration.go
internal/service/apigatewayv2/integration_response.go
internal/service/apigatewayv2/route.go
internal/service/apigatewayv2/route_response.go
internal/service/apigatewayv2/stage.go
internal/service/ecs/task_definition.go
internal/service/elasticsearch/domain.go
internal/service/elasticsearch/domain_data_source.go
internal/service/kinesisanalyticsv2/application.go
internal/service/kms/grant.go
internal/service/opensearch/domain.go
internal/service/opensearch/domain_data_source.go
internal/slices/slices.go
internal/verify/diff_test.go

Consistent FlEx function naming.
```console
% make testacc TESTARGS='-run=TestAccAPIGatewayV2Integration_' PKG=apigatewayv2 ACCTEST_PARALLELISM=2
TF_ACC=1 go test ./internal/service/apigatewayv2/... -v -count 1 -parallel 2  -run=TestAccAPIGatewayV2Integration_ -timeout 360m
=== RUN   TestAccAPIGatewayV2Integration_basicWebSocket
=== PAUSE TestAccAPIGatewayV2Integration_basicWebSocket
=== RUN   TestAccAPIGatewayV2Integration_basicHTTP
=== PAUSE TestAccAPIGatewayV2Integration_basicHTTP
=== RUN   TestAccAPIGatewayV2Integration_disappears
=== PAUSE TestAccAPIGatewayV2Integration_disappears
=== RUN   TestAccAPIGatewayV2Integration_dataMappingHTTP
=== PAUSE TestAccAPIGatewayV2Integration_dataMappingHTTP
=== RUN …
```

`flex.PointersMapToStringList` -> `flex.FlattenStringMap`

---

internal/errs/unsupported.go
internal/service/ec2/ec2_instance.go
internal/service/ecr/repository_data_source.go
internal/service/ecs/find.go
internal/service/ecs/task_definition.go
internal/service/ecs/task_set.go
internal/service/elasticache/cluster_data_source.go
internal/service/elasticache/parameter_group.go
internal/service/elbv2/listener_data_source.go
internal/service/elbv2/load_balancer_data_source.go
internal/service/elbv2/target_group_data_source.go
internal/verify/verify.go

Replace `verify.ErrorISOUnsupported` with `errs.IsUnsupportedOperationInPartitionError`, which supports AWS SDK for Go v2 errors.
```console
% make testacc TESTARGS='-run=TestAccEC2Instance_basic' PKG=ec2
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 20  -run=TestAccEC2Instance_basic -timeout 360m
=== RUN   TestAccEC2Instance_basic
=== PAUSE TestAccEC2Instance_basic
=== RUN   TestAccEC2Instance_basicWithSpot
=== PAUSE TestAccEC2Instance_basicWithSpot
=== CONT  TestAccEC2Instance_basic
=== CONT  TestAccEC2Instance_basicWithSpot
--- PASS: TestAccEC2Instance_basicWithSpot (91.66s)
--- PASS: TestAccEC2Instance_basic (123.64s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/ec2	129.271s
% make …
```

Tech debt: Use `errs.IsUnsupportedOperationInPartitionError` instead of `verify.ErrorISOUnsupported`

---

.changelog/34230.txt
internal/service/quicksight/schema/visual_map.go

The various nested bounds arguments all contained validation functions checking for integer ranges, but were TypeFloat types. Changing the validation function to one which expects float types should resolve static validation failures.
Closes #33223
```console
% make testacc PKG=quicksight TESTS="TestAccQuickSightAnalysis_|TestAccQuickSightDashboard_|TestAccQuickSightTemplate_"
TF_ACC=1 go test ./internal/service/quicksight/... -v -count 1 -parallel 20 -run='TestAccQuickSightAnalysis_|TestAccQuickSightDashboard_|TestAccQuickSightTemplate_'  -timeout 360m
--- PASS: TestAccQuickSightTemplate_basic (1130.62s)
--- PASS: …
```

r/aws_quicksight: fix window_options.bounds validator

---

website/docs/r/lambda_layer_version.html.markdown

This PR is a doc update for the `compatible_runtimes` argument description for the `aws_lambda_layer_version` resource to change the max # of items of the list from 5 to 15.
Closes #27375
n/a
n/a

docs: Update compatible runtime limit for lambada_layer_version

---

website/docs/r/appsync_datasource.html.markdown

This PR is a doc update for the `service_role_arn` argument description for the `aws_appsync_datasource` resource to include the conditions under which the argument is required (when `type` is of certain values).
Closes #27498
- AWS doc reference: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-appsync-datasource.html#cfn-appsync-datasource-servicerolearn
n/a

docs: Added service_role_arn conditional req for aws_appsync_datasource

---

website/docs/r/glue_classifier.html.markdown

This PR is a doc update for the `custom_datatype_configured` argument description for the `aws_glue_classifier` resource to align with the description in the AWS API reference. The original description was inaccurate/incorrect.
Closes #33548
- [Classifier API](https://docs.aws.amazon.com/glue/latest/dg/aws-glue-api-crawler-classifiers.html)
n/a

docs: Fix desc of custom_datatype_configured arg for aws_glue_classifier

---

website/docs/r/ce_anomaly_subscription.html.markdown

Remove mentions of the deprecated _threshold_ variable from aws_ce_anomaly_subscription documentation.
Closes #33947

remove deprecated threshold field references

---

.changelog/34212.txt
internal/service/route53/record.go
internal/service/route53/record_test.go
website/docs/r/route53_record.html.markdown

fix[aws_route53_record]: Allow importing with empty record name

---

internal/service/cloudfront/origin_access_identities_data_source.go
internal/service/docdb/cluster.go
internal/service/resourceexplorer2/index.go
internal/service/resourceexplorer2/view.go
internal/service/waf/helpers.go
internal/slices/slices.go
internal/slices/slices_test.go
internal/verify/verify.go

Replaces `verify.SliceContainsString` with a more generic function in `internal/slices`.
Also migrates the `resourceexplorer2` resources to AutoFlEx.
```console
% make testacc TESTARGS='-run=TestAccCloudFrontOriginAccessIdentitiesDataSource_comments' PKG=cloudfront
TF_ACC=1 go test ./internal/service/cloudfront/... -v -count 1 -parallel 20  -run=TestAccCloudFrontOriginAccessIdentitiesDataSource_comments -timeout 360m
=== RUN   TestAccCloudFrontOriginAccessIdentitiesDataSource_comments
=== PAUSE TestAccCloudFrontOriginAccessIdentitiesDataSource_comments
=== CONT  TestAccCloudFrontOriginAccessIdentitiesDataSource_comments
--- PASS: TestAccCloudFrontOriginAccessIdentitiesDataSource_comments (23.97s)
PASS
ok …
```

Tech debt: Replace `verify.SliceContainsString`

---

.changelog/34248.txt
internal/service/appflow/connector_profile.go
website/docs/r/appflow_connector_profile.html.markdown

Adds support for JWT related arguments in the `salesforce` configuration block.
Closes #31306
```console
% make testacc PKG=appflow TESTS=TestAccAppFlowConnectorProfile_
TF_ACC=1 go test ./internal/service/appflow/... -v -count 1 -parallel 20 -run='TestAccAppFlowConnectorProfile_'  -timeout 360m
--- PASS: TestAccAppFlowConnectorProfile_basic (574.54s)
--- PASS: TestAccAppFlowConnectorProfile_disappears (588.36s)
--- PASS: TestAccAppFlowConnectorProfile_update (764.88s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/appflow    768.024s
```

r/aws_appflow_connector_profile: add salesforce jwt_token and oauth2_grant_type arguments

---

website/docs/d/iam_group.html.markdown
website/docs/d/iam_user.html.markdown
website/docs/r/iam_group.html.markdown
website/docs/r/iam_user.html.markdown

This PR is to add or correct id- and name-related attributes for `aws_iam_group` and `aws_iam_user` resources and data sources.
Closes #34107
Refer to https://github.com/hashicorp/terraform-provider-aws/issues/34107#issuecomment-1791714689 for a table of the name- and id-related attribute values for `aws_iam_*` resources and data sources.
n/a

docs: Fix id and name attr descs for aws_iam_group and aws_iam_user

---

website/docs/r/glue_crawler.html.markdown

This PR is to add the missing description for the `catalog_target` attribute of the `aws_glue_crawler` resource.
Closes #34081
- Referred to [Crawler API](https://docs.aws.amazon.com/glue/latest/dg/aws-glue-api-crawler-crawling.html#aws-glue-api-crawler-crawling-CatalogTarget) for the standard name of the target (vs. just calling it "catalog target") in the description.
n/a

docs: Add catalog_target description for aws_glue_crawler

---

website/docs/r/cloudwatch_event_connection.html.markdown

This PR is to relocate the `invocation_http_parameters` argument description of the `aws_cloudwatch_event_connection` resource from under the root to under the `auth_parameters` block where it belongs.
Closes #34032
- The schema at https://github.com/hashicorp/terraform-provider-aws/blob/c4c48f075b1987385e8036572b1ed11c6c483ec1/internal/service/events/connection.go#L245 indicates that `invocation_http_parameters` is indeed defined as a child of `auth_parameters`.
n/a

docs: Moved invocation_http_parameters arg under auth_parameters for

---

website/docs/r/batch_compute_environment.html.markdown

This PR is to fix the `service_role` argument in the `aws_batch_compute_environment` resource documentation, which is optional instead of required.
Closes #34143
n/a
n/a

docs: Mark service_role as optional for aws_batch_compute_environment

---

.changelog/34216.txt
internal/service/rds/instance.go

AWS have announced support for postgres engines for Blue/Green deployments: https://aws.amazon.com/about-aws/whats-new/2023/10/amazon-rds-blue-green-deployments-aurora-rds-postgresql/
Closes #0000
```console
...
```

feat(rds): Add postgres to supported blue green engines

---

.changelog/34261.txt
internal/service/inspector2/inspector2_test.go
internal/service/inspector2/organization_configuration.go
internal/service/inspector2/organization_configuration_test.go
website/docs/r/inspector2_organization_configuration.html.markdown

This PR is for adding the `lambda_code` attribute to the `auto_enable` block of the `aws_inspector2_organization_configuration` resource, which will add support for managing Lambda code scanning at the organizational level.
Closes #34200
- Reference links that were included in #34200
- [Scanning AWS Lambda functions with Amazon Inspector](https://docs.aws.amazon.com/inspector/latest/user/scanning-lambda.html)
```console
antw@U-UQPXPV4N2NIW:~/git/terraform-provider-aws$ make testacc TESTS=TestAccInspector2_serial PKG=inspector2
TF_ACC=1 go test ./internal/service/inspector2/... -v -count 1 -parallel 20 -run='TestAccInspector2_serial'  -timeout 360m
=== RUN   TestAccInspector2_serial
=== PAUSE TestAccInspector2_serial
=== CONT …
```

feat: Add lambda_code attr to aws_inspector2_organization_configuration resource

---

.changelog/34260.txt
internal/service/autoscaling/group.go
internal/service/autoscaling/group_test.go

Fix a bug where if an `initial_lifecycle_hook` attribute is updated, it doesn't replace `aws_autoscaling_group` to apply `initial_lifecycle_hook` change.
Closes #34178
```console
% make testacc TESTS='TestAccAutoScalingGroup_initialLifecycleHook' PKG=autoscaling ACCTEST_PARALLELISM=3
TF_ACC=1 go test ./internal/service/autoscaling/... -v -count 1 -parallel 3 -run='TestAccAutoScalingGroup_initialLifecycleHook'  -timeout 360m
=== RUN   TestAccAutoScalingGroup_initialLifecycleHook
=== PAUSE TestAccAutoScalingGroup_initialLifecycleHook
=== CONT  TestAccAutoScalingGroup_initialLifecycleHook
--- PASS: TestAccAutoScalingGroup_initialLifecycleHook (923.37s)
PASS
ok   [github.com/hashicorp/terraform-provider-aws/internal/service/autoscaling …
```

r/aws_autoscaling_group: Force new in case of initial_lifecycle_hook update

---

website/docs/r/wafv2_rule_group.html.markdown

This PR replaces the technical max length 512 of the `regex_string` file in the `aws_wafv2_rule_group` resource documentation with the non-adjustable quota 200. The min length of 1 is inferred and isn't normally called out in AWS Terraform Provider documentation, so I've removed it for consistency.
Closes #33626
- [AWS WAF quotas](https://docs.aws.amazon.com/waf/latest/developerguide/limits.html) lists the non-adjustable quota.
- [RegexMatchStatement](https://docs.aws.amazon.com/waf/latest/APIReference/API_RegexMatchStatement.html) shows the technical max length in the AWS API schema.
n/a

docs: Add note about regex_string quota for aws_wafv2_rule_group

---

.changelog/34300.txt
go.mod
go.sum
internal/errs/sdkdiag/compare.go
internal/errs/sdkdiag/diags.go
internal/provider/provider_config_test.go
internal/service/acmpca/certificate_test.go

Rolls back `github.com/aws/aws-sdk-go-v2/config` and `github.com/aws/aws-sdk-go-v2/internal/ini` versions which contain shared config file parsing bug https://github.com/aws/aws-sdk-go-v2/issues/2349
Adds exclusions to `go.mod` file and adds test for this regression
Relates #34234.
Closes #34257.
```console
% go test -v ./internal/provider/... -run=TestSharedConfigFileParsing
--- PASS: TestSharedConfigFileParsing (0.08s)
--- PASS: TestSharedConfigFileParsing/leading_whitespace (0.08s)
```

Rolls back AWS SDK modules with shared config parsing bug

---

website/docs/r/lex_bot_alias.html.markdown

This PR addresses a documentation error for the `lex_bot_alias` resource, related to the `bot_version` argument. Clarified that `bot_version`  represents the version of the bot, not the name of the bot.
N/A, docs
N/A, docs
N/A

Fix error in `lex_bot_alias` resource documentation

---

website/docs/r/budgets_budget.html.markdown

Importing `aws_budgets_budget` only requires the account ID and budget name.
The action ID required is `aws_budgets_budget_action`.
The following document was also affected, but I did not change it because I thought it would be fixed automatically.
```
website/docs/cdktf/python/r/budgets_budget.html.markdown
website/docs/cdktf/typescript/r/budgets_budget.html.markdown
```
Closes #0000
```console
...
```

docs: fix resource id

---

.changelog/34316.txt
internal/service/dms/endpoint.go
internal/service/dms/endpoint_test.go
internal/service/dms/replication_task.go
website/docs/r/dms_endpoint.html.markdown

h
Closes #27661
```console
% make t T=TestAccDMSEndpoint_pauseReplicationTasks K=dms
TF_ACC=1 go test ./internal/service/dms/... -v -count 1 -parallel 20 -run='TestAccDMSEndpoint_pauseReplicationTasks'  -timeout 360m
=== RUN   TestAccDMSEndpoint_pauseReplicationTasks
=== PAUSE TestAccDMSEndpoint_pauseReplicationTasks
=== CONT  TestAccDMSEndpoint_pauseReplicationTasks
--- PASS: TestAccDMSEndpoint_pauseReplicationTasks (2599.54s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/dms	2602.433s
% make t T=TestAccDMSReplicationTask_ K=dms
TF_ACC=1 go test ./internal/service/dms/... -v -count 1 -parallel 20 -run='TestAccDMSReplicationTask_'  -timeout 360m …
```

dms/endpoint: Pause replication tasks for updates

---

.changelog/34334.txt
internal/service/chime/chime_test.go
internal/service/chime/exports_test.go
internal/service/chime/find.go
internal/service/chime/generate.go
internal/service/chime/tags_gen.go
internal/service/chime/voice_connector.go
internal/service/chime/voice_connector_group.go
internal/service/chime/voice_connector_group_test.go
internal/service/chime/voice_connector_logging.go
internal/service/chime/voice_connector_logging_test.go
internal/service/chime/voice_connector_origination.go
internal/service/chime/voice_connector_origination_test.go
internal/service/chime/voice_connector_streaming_test.go
internal/service/chime/voice_connector_termination.go
internal/service/chime/voice_connector_termination_credentials.go
internal/service/chime/voice_connector_termination_credentials_test.go
internal/service/chime/voice_connector_termination_test.go
internal/service/chime/voice_connector_test.go
internal/service/chimesdkmediapipelines/media_insights_pipeline_configuration.go

multiple fixes for eventual consistency errors.
Tests are now successful in regions other than `us-east-1`
Closes #34218
```console
$ make testacc TESTARGS="-run=TestAccChime_serial" PKG=chime
TF_ACC=1 go test ./internal/service/chime/... -v -count 1 -parallel 20  -run=TestAccChime_serial -timeout 360m
--- PASS: TestAccChime_serial (2349.97s)
--- PASS: TestAccChime_serial/VoiceConnectorTerminationCredentials (427.25s)
--- PASS: TestAccChime_serial/VoiceConnectorTerminationCredentials/disappears (110.37s)
--- PASS: TestAccChime_serial/VoiceConnectorTerminationCredentials/update (199.87s)
--- PASS: TestAccChime_serial/VoiceConnectorTerminationCredentials/basic (117.01s)
--- PASS: TestAccChime_serial/VoiceConnector (338.63s)
--- …
```

chime service: fix race condition when not using `us-east-1`

---

internal/framework/flex/autoflex.go
internal/framework/flex/list.go
internal/framework/flex/list_test.go
internal/framework/flex/set.go
internal/framework/flex/set_test.go
internal/service/bedrock/foundation_model_data_source.go
internal/service/bedrock/foundation_models_data_source.go

This will allow the `FlattenFrameworkStringValue[List|Set]*` functions to be used with lists and sets of AWS enum types, implemented as custom string types.
Relates #34148 
```console
% go test -count=1 ./internal/framework/flex/...
ok      github.com/hashicorp/terraform-provider-aws/internal/framework/flex     0.223s
```
The regions data source utilizes the `flex.FlattenFrameworkStringValueSetLegacy` function.
```console
% make testacc PKG=meta TESTS=TestAccMetaRegionsDataSource_
TF_ACC=1 go test ./internal/service/meta/... -v -count 1 -parallel 20 -run='TestAccMetaRegionsDataSource_'  -timeout 360m
--- PASS: TestAccMetaRegionsDataSource_allRegions (33.47s)
--- PASS: TestAccMetaRegionsDataSource_filter (33.64s)
--- PASS: …
```

internal/framework/flex: generic set/list of string value flatteners

---

.changelog/34378.txt
internal/service/iam/exports_test.go
internal/service/iam/find.go
internal/service/iam/group_policy_attachment.go
internal/service/iam/group_policy_attachment_test.go
internal/service/iam/policy.go
internal/service/iam/policy_attachment.go
internal/service/iam/policy_attachment_test.go
internal/service/iam/policy_data_source.go
internal/service/iam/role.go
internal/service/iam/role_policy_attachment.go
internal/service/iam/role_policy_attachment_test.go
internal/service/iam/service_package_gen.go
internal/service/iam/sweep.go
internal/service/iam/user_policy_attachment.go
internal/service/iam/user_policy_attachment_test.go

Seems like AWS IAM now returns ConcurrentModification when previously this was not a problem.
Just retry the operation like we do in other parts of the code.
Closes #34371

service/iam: retry attaching policy on ConcurrentModificationException

---

.changelog/34396.txt
internal/service/elasticache/sweep.go
internal/service/elasticache/user.go
internal/service/elasticache/user_test.go
website/docs/r/elasticache_user.html.markdown

Fix `UserNotFound: ... is not available for tagging` errors on resource Read when there is a concurrent update to the user by waiting for the resource to be in `active` state.
As many stray ElastiCache users were created during testing, sweeper for `aws_elasticache_user` and `aws_elasticache_user_group` have been added.
Closes https://github.com/hashicorp/terraform-provider-aws/issues/34002.
```
% make testacc TESTARGS='-run=TestAccElastiCacheUser_' PKG=elasticache ACCTEST_PARALLELISM=2
TF_ACC=1 go test ./internal/service/elasticache/... -v -count 1 -parallel 2  -run=TestAccElastiCacheUser_ -timeout 360m
=== RUN   TestAccElastiCacheUser_basic
=== PAUSE TestAccElastiCacheUser_basic
=== RUN …
```

r/aws_elasticache_user: Add acceptance test for tagging during out-of-band modification

---

docs/design-decision-log.md
docs/design-decisions/secretsmanager-secret-target-attachment.md

Design document to assess the feasibility of replicating the `AWS::SecretsManager::SecretTargetAttachment` CloudFormation function with Terraform.
> **Proposal**
> 
> Given the currently available AWS APIs, there isn’t a path to implement the workflow from the SecretTargetAttachment CloudFormation function in the AWS Terraform Provider. Existing resources provide options to either fully customize a manual secret with both database credentials and connection information, or to fully offload secret management to AWS. These options cover the core use case of storing and rotating database secrets via AWS SecretsManager.
> 
> With existing options already available in the provider, and no clear path forward the proposal is to close this issue.
Relates #9183

[Design Decision]: SecretsManager Secret Target Attachment

---

.github/workflows/regressions.yml

This PR fixes an issue where a title with a quote would break the regressions Slack notifier.
- https://github.com/slackapi/slack-github-action/issues/202#issuecomment-1769132156
N/a, Actions

Regressions notifier: wrap title with toJSON to prevent quoting issues

---

.changelog/34426.txt
internal/service/chimesdkvoice/exports_test.go
internal/service/chimesdkvoice/find..go
internal/service/chimesdkvoice/sip_media_application.go
internal/service/chimesdkvoice/sip_media_application_test.go
internal/service/chimesdkvoice/sip_rule.go
internal/service/chimesdkvoice/sip_rule_test.go

Test are successful in regions other than `us-east-1`
Closes #32678
```console
$ make testacc TESTARGS="-run=TestAccChimeSDKVoiceSipMediaApplication_" PKG=chimesdkvoice
TF_ACC=1 go test ./internal/service/chimesdkvoice/... -v -count 1 -parallel 20  -run=TestAccChimeSDKVoiceSipMediaApplication_ -timeout 360m
--- PASS: TestAccChimeSDKVoiceSipMediaApplication_disappears (129.17s)
--- PASS: TestAccChimeSDKVoiceSipMediaApplication_basic (145.59s)
--- PASS: TestAccChimeSDKVoiceSipMediaApplication_update (254.78s)
--- PASS: TestAccChimeSDKVoiceSipMediaApplication_tags (352.36s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/chimesdkvoice	355.659s
```
```console
$ make testacc …
```

r/chimesdkvoice service: fix eventual consistency errors

---

.changelog/34398.txt
internal/service/finspace/kx_cluster.go
internal/service/finspace/kx_environment.go
website/docs/r/finspace_kx_cluster.html.markdown
website/docs/r/finspace_kx_environment.html.markdown

Increases create and update default timeouts of kx_cluster resource to 18 hours to prepare for upcoming changes involving cache warming.
Also increase delete default timeout of kx_environment resource to 75 minutes to prepare for bug fix coming to deletion workflow when environment has deleting clusters (as in acceptance tests).
Relates #33745 and #31806
Fix on cluster/environment deletion still in progress for kx_cluster tests, but ran TestAccFinSpaceKxCluster_code after making timeout changes and verified that create and update both worked as expected, along with their checks. Will rerun all cluster tests once deletion bug is fixed.

finspace: Increase kx_cluster create/update and kx_environment delete timeouts

---

website/docs/r/sagemaker_domain.html.markdown

I found a small formatting issue in the [sagemaker_domain](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sagemaker_domain) doc, it looks like this:
This PR fixeds that

Fix domain_name argument formatting

---

website/docs/r/rds_cluster.html.markdown

As of 2023-Feb-28, the `multimaster` engine mode is no longer offered. This PR removes references to it from the RDS Cluster documentation.
Closes #34414
[AWS blog post](https://aws.amazon.com/about-aws/whats-new/2019/08/amazon-aurora-multimaster-now-generally-available/) with bottom annotation:
> 9/8/23: Multi-Master is no longer available as of Feb 28, 2023
N/a, docs

Aurora: Remove references to `multimaster`

---

.changelog/34481.txt
go.mod
go.sum
internal/conns/awsclient_gen.go
internal/framework/flex/float.go
internal/framework/flex/float_test.go
internal/service/emr/service_package_gen.go
internal/service/emr/supported_instance_types_data_source.go
internal/service/emr/supported_instance_types_data_source_test.go
names/names.go
names/names_data.csv
website/docs/d/emr_supported_instance_types.html.markdown

Returns a list of supported instance types for the provided release label (ie. `emr-6.15.0`).
Also adds a V2 EMR service client and `flex` flatteners to support `float32` builtin type conversions to framework `Float64` types.
Closes #34438
Relates #33998
- https://docs.aws.amazon.com/emr/latest/APIReference/API_ListSupportedInstanceTypes.html
- https://docs.aws.amazon.com/emr/latest/APIReference/API_SupportedInstanceType.html
```console
% make testacc PKG=emr TESTS=TestAccEMRSupportedInstanceTypesDataSource_
TF_ACC=1 go test ./internal/service/emr/... -v -count 1 -parallel 20 -run='TestAccEMRSupportedInstanceTypesDataSource_'  -timeout 360m
=== RUN   TestAccEMRSupportedInstanceTypesDataSource_basic
=== PAUSE …
```

[New Data Source]: `aws_emr_supported_instance_types`

---

website/docs/r/dynamodb_table.html.markdown

The PR #33802 added the parameter `import_table` to `aws_dynamodb_table`. The parameter `import_table. client_token` was removed from the implementation but left in documentation. Update the documentation.
Closes #34139
N/A

documentation: Removes unimplemented parameter

---

internal/service/ec2/vpc_network_interface.go
internal/service/ec2/vpc_security_group.go
internal/service/ec2/vpc_subnet.go
internal/service/lambda/function_test.go
internal/sweep/context.go
internal/sweep/framework/resource.go
internal/sweep/logging.go
internal/sweep/sdk/resource.go
internal/sweep/sweep.go

When there is a large number of Subnets in a region, the `aws_subnet` sweeper may fail with an error like
> Error running Sweeper (aws_subnet) in region (us-west-2): error sweeping EC2 Subnets (us-west-2): 73 errors occurred:
* deleting ENIs for EC2 Subnet (subnet-abc123): 1 error occurred:
* listing EC2 Network Interfaces: RequestLimitExceeded: Request limit exceeded.
The sweeper is not identifying `RequestLimitExceeded` as a throttling error, and therefore not retrying.
The subnet `Delete` function checks for lingering ENIs in three cases:
* Lambda
* Comprehend
* DMS
For each case, the `DescribeNetworkInterfaces` API is called with appropriate filters, thus three times per subnet.
This PR
1. uses a single call to `DescribeNetworkInterfaces` per subnet,
2. identifies throttling error …

sweepers: Fix `RequestLimitExceeded` error when sweeping large number of Subnets

---

.changelog/34487.txt
internal/service/pipes/pipe_test.go
internal/service/pipes/source_parameters.go

Closes #32423
```console
% make testacc TESTARGS="-run=TestAccPipesPipe_" PKG=pipes
TF_ACC=1 go test ./internal/service/pipes/... -v -count 1 -parallel 20  -run=TestAccPipesPipe_ -timeout 360m
acctest.go:89: DependencyViolation errors deleting subnets and security group
--- SKIP: TestAccPipesPipe_mskSourceHTTPTarget (0.00s)
acctest.go:89: DependencyViolation errors deleting subnets and security group
--- SKIP: TestAccPipesPipe_selfManagedKafkaSourceLambdaFunctionTarget (0.00s)
acctest.go:89: aws_sagemaker_pipeline resource not yet implemented
--- SKIP: TestAccPipesPipe_SourceSageMakerTarget (0.00s)
acctest.go:89: ValidationException: [numeric instance is lower than the required minimum (minimum: 1, found: 0)]
--- SKIP: …
```

r/aws_pipes_pipe: fix zero value vs `null` value on update

---

.changelog/34510.txt
internal/service/events/rule.go
internal/service/events/rule_migrate.go
internal/service/events/rule_test.go
website/docs/r/cloudwatch_event_rule.html.markdown

Previously, the provider used the boolean parameter `is_enabled` to configure the AWS API parameter `State` with values `ENABLED` and `DISABLED`. Recently, AWS added the value `ENABLED_WITH_CLOUDTRAIL_READ_ONLY_EVENTS` to `State`.
Adds the parameter `state` and deprecates `is_enabled`.
```console
% make testacc PKG=events TESTS=TestAccEventsRule_
--- PASS: TestAccEventsRule_patternJSONEncoder (202.70s)
--- PASS: TestAccEventsRule_Name_generated (219.52s)
--- PASS: TestAccEventsRule_scheduleAndPattern (228.14s)
--- PASS: TestAccEventsRule_namePrefix (228.40s)
--- PASS: TestAccEventsRule_migrateV0 (0.00s)
--- PASS: TestAccEventsRule_migrateV0/enabled (241.41s)
--- PASS: TestAccEventsRule_migrateV0/disabled (241.48s)
--- PASS: TestAccEventsRule_migrateV0/basic (244.05s)
--- PASS: …
```

resource/aws_cloudwatch_event_rule: Adds `state` parameter

---

.changelog/34524.txt
internal/service/lexv2models/bot.go
internal/service/lexv2models/bot_test.go

Previously, explicitly configured values for the `type` argument were not sent during create or update operations, resulting in the default `Bot` type in all cases. These operations will now send the `type` value when set.
Note: An acceptance test using the `BotNetwork` bot type could not be written at this time, as it is dependent on the `aws_lexv2models_bot_alias` resource which is not yet available.
Relates #33475 
```console
% make testacc PKG=lexv2models TESTS=TestAccLexV2ModelsBot_
TF_ACC=1 go test ./internal/service/lexv2models/... -v -count 1 -parallel 20 -run='TestAccLexV2ModelsBot_'  -timeout 360m
--- PASS: TestAccLexV2ModelsBot_disappears (103.22s)
--- PASS: TestAccLexV2ModelsBot_type (104.00s)
--- PASS: …
```

r/aws_lexv2models_bot: support explicit type argument on create and update

---

internal/service/s3/bucket_public_access_block.go
internal/service/s3/bucket_public_access_block_test.go
internal/service/s3/errors.go
internal/service/s3/exports_test.go

Migrates the `aws_s3_bucket_public_access_block` resource to AWS SDK for Go v2.
Relates https://github.com/hashicorp/terraform-provider-aws/issues/33654.
Relates https://github.com/hashicorp/terraform-provider-aws/issues/32976.
```console
% make testacc TESTARGS='-run=TestAccS3BucketPublicAccessBlock_' PKG=s3 ACCTEST_PARALLELISM=2
TF_ACC=1 go test ./internal/service/s3/... -v -count 1 -parallel 2  -run=TestAccS3BucketPublicAccessBlock_ -timeout 360m
=== RUN   TestAccS3BucketPublicAccessBlock_basic
=== PAUSE TestAccS3BucketPublicAccessBlock_basic
=== RUN   TestAccS3BucketPublicAccessBlock_disappears
=== PAUSE TestAccS3BucketPublicAccessBlock_disappears
=== RUN   TestAccS3BucketPublicAccessBlock_Disappears_bucket
=== PAUSE …
```

r/aws_s3_bucket_public_access_block: Migrate to AWS SDK for Go v2

---

.changelog/34530.txt
internal/service/glue/trigger.go

This change will retry trigger creation when a `ConcurrentModificationException` is received. This can occur when multiple triggers reference a single workflow within the same configuration.
Successfully tested against the example configuration provided in the linked issue.
Closes #21759
```console
% make testacc PKG=glue TESTS=TestAccGlueTrigger_
TF_ACC=1 go test ./internal/service/glue/... -v -count 1 -parallel 20 -run='TestAccGlueTrigger_'  -timeout 360m
=== NAME  TestAccGlueTrigger_crawler
trigger_test.go:71: Step 1/3 error: Error running apply: exit status 1
Error: creating Glue Crawler (tf-acc-test-7273293400628501361): InvalidInputException: S3 bucket test_bucket does not exist.
{
RespMetadata: {
StatusCode: 400,
RequestID: …
```

r/aws_glue_trigger: handle concurrent modification exceptions

---

.changelog/34532.txt
internal/service/lexv2models/bot_locale.go
internal/service/lexv2models/bot_locale_test.go
website/docs/r/lexv2models_bot_locale.html.markdown

Fixes validation of the `voice_settings.engine` argument to use the correct enum values of `standard` and `neural`. Also addresses a value conversion error caused by a typo in the struct tag for the `engine` arguments underlying struct field. Adds an acceptance test and example with the `voice_settings` argument configured.
Closes #34531
Relates #33949 
- https://docs.aws.amazon.com/lexv2/latest/APIReference/API_VoiceSettings.html
```console
% make testacc PKG=lexv2models TESTS=TestAccLexV2ModelsBotLocale_
TF_ACC=1 go test ./internal/service/lexv2models/... -v -count 1 -parallel 20 -run='TestAccLexV2ModelsBotLocale_'  -timeout 360m
--- PASS: TestAccLexV2ModelsBotLocale_disappears (115.42s)
--- PASS: …
```

r/aws_lexv2models_bot_locale: fix `voice_settings.engine` validation 

---

go.mod
go.sum
internal/conns/awsclient_gen.go
internal/flex/flex.go
internal/service/evidently/feature.go
internal/service/evidently/feature_test.go
internal/service/evidently/find.go
internal/service/evidently/generate.go
internal/service/evidently/launch.go
internal/service/evidently/launch_test.go
internal/service/evidently/project.go
internal/service/evidently/project_test.go
internal/service/evidently/segment.go
internal/service/evidently/segment_test.go
internal/service/evidently/service_package_gen.go
internal/service/evidently/status.go
internal/service/evidently/sweep.go
internal/service/evidently/tags_gen.go
internal/service/evidently/wait.go
names/names.go
names/names_data.csv

```console
% make testacc TESTARGS="-run=TestAccEvidently" PKG=evidently
TF_ACC=1 go test ./internal/service/evidently/... -v -count 1 -parallel 20  -run=TestAccEvidently -timeout 360m
--- PASS: TestAccEvidentlyProject_disappears (129.74s)
--- PASS: TestAccEvidentlySegment_description (157.78s)
--- PASS: TestAccEvidentlyFeature_basic (250.65s)
--- PASS: TestAccEvidentlyProject_basic (268.45s)
--- PASS: TestAccEvidentlySegment_basic (159.27s)
--- PASS: TestAccEvidentlyProject_tags (387.44s)
--- PASS: TestAccEvidentlyLaunch_disappears (391.11s)
--- PASS: TestAccEvidentlyLaunch_basic (396.27s)
--- PASS: TestAccEvidentlySegment_disappears (129.65s)
--- PASS: TestAccEvidentlyFeature_updateDescription (429.05s)
--- PASS: …
```

Migrate Evidently service to Go SDKv2

---

.changelog/34600.txt
internal/service/elasticache/replication_group.go
internal/service/elasticache/replication_group_migrate.go
internal/service/elasticache/replication_group_test.go

This state upgrader resolves issues with the default `auth_token_update_strategy` value, introduced in v5.27.0, which causes a diff upon upgrade and triggers an attempted in-place update. The default value will now instead be written to state by the state upgrader, resulting in no changes on the initial apply.
Before:
```console
% make testacc PKG=elasticache TESTS="TestAccElastiCacheReplicationGroup_stateUpgrade5270"
TF_ACC=1 go test ./internal/service/elasticache/... -v -count 1 -parallel 20 -run='TestAccElastiCacheReplicationGroup_stateUpgrade5270'  -timeout 360m
=== RUN   TestAccElastiCacheReplicationGroup_stateUpgrade5270
=== PAUSE TestAccElastiCacheReplicationGroup_stateUpgrade5270
=== CONT …
```

r/aws_elasticache_replication_group: v2 state upgrader

---

website/docs/r/elasticache_replication_group.html.markdown

While this value is only sent to the AWS API if auth_token is set (and by association, transit_encryption_enabled is set to true), the default value means it is always set in state. As such, indiciating in the documentation that it can only specified when transit encrpytion is enabled is no longer true.
Relates #34460 
Originally suggested in this comment: https://github.com/hashicorp/terraform-provider-aws/pull/34460#issuecomment-1829317390

r/aws_elasticache_replication_group(doc): clarify auth_token_update_strategy argument dependencies

---

.changelog/34547.txt
internal/service/networkmanager/README.md
internal/service/networkmanager/attachment_accepter.go
internal/service/networkmanager/core_network.go
internal/service/networkmanager/vpc_attachment.go
internal/service/networkmanager/vpc_attachment_test.go
website/docs/r/networkmanager_attachment_accepter.html.markdown
website/docs/r/networkmanager_connect_attachment.html.markdown
website/docs/r/networkmanager_connect_peer.html.markdown
website/docs/r/networkmanager_site_to_site_vpn_attachment.html.markdown
website/docs/r/networkmanager_vpc_attachment.html.markdown

When waiting for acceptance, the resource `aws_networkmanager_vpc_attachment` previously incorrectly returned an error stating that it could  not be deleted.
This PR now rejects the VPC attachment and deletes it.
Previously, the Delete operation of the resource `aws_networkmanager_attachment_accepter` was a no-op, leaving any attachments in place.
For VPC attachments, deleting a corresponding `aws_networkmanager_attachment_accepter` now removes the attachment.
Previously, modifying the fields of the `options` parameter of `aws_networkmanager_vpc_attachment` would cause a run-time error.
Modifying these fields now causes re-creation of the `aws_networkmanager_vpc_attachment`.
Closes #34501
Relates #34502
```console
% make testacc PKG=networkmanager TESTS=TestAccNetworkManagerVPCAttachment_ …
```

resource/aws_networkmanager_vpc_attachment: Allow deleting when not attached

---

.changelog/34679.txt
internal/service/logs/group.go
internal/service/logs/group_test.go
website/docs/r/cloudwatch_log_group.html.markdown

This PR adds the [recently announced](https://aws.amazon.com/blogs/aws/new-amazon-cloudwatch-log-class-for-infrequent-access-logs-at-a-reduced-price) Cloudwatch Log Group log classes (`STANDARD` or `INFREQUENT_ACCESS`).
Feature request: https://github.com/hashicorp/terraform-provider-aws/issues/34570
https://aws.amazon.com/blogs/aws/new-amazon-cloudwatch-log-class-for-infrequent-access-logs-at-a-reduced-price
https://github.com/aws/aws-sdk-go/releases/tag/v1.48.4
https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/CloudWatch_Logs_Log_Classes.html
```
❯ make testacc TESTS=TestAccLogsGroup_logClass PKG=logs
TF_ACC=1 go test ./internal/service/logs/... -v -count 1 -parallel 20 -run='TestAccLogsGroup_logClass'  -timeout 360m
=== …
```

Add Cloudwatch Logs log classes argument

---

.changelog/34670.txt
internal/service/ssoadmin/application_providers_data_source.go
internal/service/ssoadmin/application_providers_data_source_test.go
internal/service/ssoadmin/service_package_gen.go
website/docs/d/ssoadmin_application_providers.html.markdown

A new data source to enable searching for available application providers in a given IAM Identity Center region.
Closes #34665
Relates #27853 
- https://docs.aws.amazon.com/singlesignon/latest/APIReference/API_ListApplicationProviders.html
```console
% make testacc PKG=ssoadmin TESTS=TestAccSSOAdminApplicationProvidersDataSource_
TF_ACC=1 go test ./internal/service/ssoadmin/... -v -count 1 -parallel 20 -run='TestAccSSOAdminApplicationProvidersDataSource_'  -timeout 360m
=== RUN   TestAccSSOAdminApplicationProvidersDataSource_basic
=== PAUSE TestAccSSOAdminApplicationProvidersDataSource_basic
=== CONT  TestAccSSOAdminApplicationProvidersDataSource_basic
--- PASS: TestAccSSOAdminApplicationProvidersDataSource_basic (24.18s)
PASS
ok …
```

d/aws_ssoadmin_application_providers: new data source

---

internal/framework/flex/autoflex_test.go
internal/framework/types/mapof.go

Closes #0000
```console
% go test ./internal/framework/flex/... -v -count 1 -parallel 20 -run='TestGenericExpand2'
=== RUN   TestGenericExpand2
=== PAUSE TestGenericExpand2
=== CONT  TestGenericExpand2
=== RUN   TestGenericExpand2/map_string
=== PAUSE TestGenericExpand2/map_string
=== RUN   TestGenericExpand2/object_map
=== PAUSE TestGenericExpand2/object_map
=== RUN   TestGenericExpand2/object_map_ptr_target
=== PAUSE TestGenericExpand2/object_map_ptr_target
=== RUN   TestGenericExpand2/object_map_ptr_source_and_target
=== PAUSE TestGenericExpand2/object_map_ptr_source_and_target
=== RUN   TestGenericExpand2/nested_string_map
=== PAUSE TestGenericExpand2/nested_string_map
=== RUN   TestGenericExpand2/nested_object_map
=== PAUSE TestGenericExpand2/nested_object_map
=== CONT …
```

autoflex: Fix MapValueOf bug

---

.changelog/34737.txt
internal/service/glue/connection.go

This PR fixes the [bug](https://github.com/hashicorp/terraform-provider-aws/issues/34735) in `aws_glue_connection` resource.
Closes #34735
```console
make testacc TESTS=TestAccGlueConnection_basic PKG=glue
TF_ACC=1 go test ./internal/service/glue/... -v -count 1 -parallel 20 -run='TestAccGlueConnection_basic'  -timeout 360m
=== RUN   TestAccGlueConnection_basic
=== PAUSE TestAccGlueConnection_basic
=== CONT  TestAccGlueConnection_basic
--- PASS: TestAccGlueConnection_basic (25.07s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/glue       30.483s
...
```

Fixing empty `physical_connection_requirements` in `aws_glue_connection` resource

---

CHANGELOG.md

Missing new resource, `aws_bedrock_model_invocation_logging_configuration`,  from **v5.26.0** section.
Missing backtick in the CHANGELOG entry file.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/34303.

Update `CHANGELOG.md` for `v5.26.0` -- missing new resource entry

---

.changelog/34741.txt
internal/service/ssoadmin/application_assignment.go
internal/service/ssoadmin/application_assignment_test.go
internal/service/ssoadmin/exports_test.go
internal/service/ssoadmin/service_package_gen.go
website/docs/r/ssoadmin_application_assignment.html.markdown

This resource will allow practitioners to manage Identity Center application assignments with Terraform.
Closes #28633
- https://docs.aws.amazon.com/singlesignon/latest/APIReference/API_CreateApplicationAssignment.html
- https://docs.aws.amazon.com/singlesignon/latest/APIReference/API_DescribeApplicationAssignment.html
- https://docs.aws.amazon.com/singlesignon/latest/APIReference/API_DeleteApplicationAssignment.html
```console
% make testacc PKG=ssoadmin TESTS=TestAccSSOAdminApplicationAssignment_
TF_ACC=1 go test ./internal/service/ssoadmin/... -v -count 1 -parallel 20 -run='TestAccSSOAdminApplicationAssignment_'  -timeout 360m
--- PASS: TestAccSSOAdminApplicationAssignment_disappears (83.07s)
--- PASS: …
```

r/aws_ssoadmin_application_assignment: new resource

---

website/docs/r/codecatalyst_project.html.markdown
website/docs/r/codecatalyst_source_repository.html.markdown
website/docs/r/codeguruprofiler_profiling_group.html.markdown
website/docs/r/lexv2models_bot.html.markdown
website/docs/r/lexv2models_bot_locale.html.markdown
website/docs/r/lexv2models_bot_version.html.markdown
website/docs/r/servicequotas_template.html.markdown
website/docs/r/servicequotas_template_association.html.markdown
website/docs/r/sesv2_contact_list.html.markdown
website/docs/r/vpclattice_auth_policy.html.markdown
website/docs/r/vpclattice_listener_rule.html.markdown

Fixes the import section of various resources where the placeholder skaff argument `example_id_arg` was not replaced with the proper import key. Also fixes timeout argument values for a subset of the same resources.

[Docs]: Fix errant import references to `example_id_arg`

---

skaff/resource/resourcetest.tmpl

This newline was causing the import linter (impi) to fail when using skaff for resources with AWS SDK for Go V2.

skaff: remove unintended newline in imports

---

website/docs/r/ssoadmin_account_assignment.html.markdown
website/docs/r/ssoadmin_managed_policy_attachment.html.markdown

This PR addresses the bug with `aws_ssoadmin_account_assignment` and `aws_ssoadmin_managed_policy_attachment` listed in this [GitHub Issue - #33337](https://github.com/hashicorp/terraform-provider-aws/issues/33337). Per @jar-b's further investigation, adding an explicit dependency between these two resources resolves a provider issue where both resources are attempted to be destroyed at the same time, causing `terraform destroy` to fail until the command is run a second time.
This PR adds clear documentation of this error and the resolution to resource documentation pages for the above affected resources.
Closes [#33337](https://github.com/hashicorp/terraform-provider-aws/issues/33337)
Closes[#33384](https://github.com/hashicorp/terraform-provider-aws/pull/33384)
```console
% make testacc …
```

update docs for sso to address provider issue

---

.changelog/34598.txt
website/docs/r/kinesis_firehose_delivery_stream.html.markdown

Fixes an issue with the `kinesis_firehose_delivery_stream` resource documentation. An extra sentence appeared in the `destination` argument values from a previous revision. The two sentences are correctly revised now.
Closes #34598

Amend destination argument config for kinesis_firehose_delivery_stream resource docs

---

skaff/datasource/datasourcetest.tmpl

Fixes import spacing and adds a conditional to the `PreCheckPartitionHasService` function to properly account for the use of AWS SDK for Go V2.

skaff: datasource test template fixes

---

.changelog/34691.txt
internal/service/ec2/ec2_ami.go
internal/service/ec2/ec2_ami_test.go

The parameters `description` and `deprecation_time` are set or modified using eventually consistent operations. This was causing them to not be updated in Terraform state.
Also affects `aws_ami_from_instance` and `aws_ami_copy`
```console
% make testacc PKG=ec2 TESTS='TestAccEC2AMI_|TestAccEC2AMICopy_|TestAccEC2AMIFromInstance_'
--- PASS: TestAccEC2AMI_ephemeralBlockDevices (1049.53s)
--- PASS: TestAccEC2AMI_gp3BlockDevice (1058.41s)
--- PASS: TestAccEC2AMI_imdsSupport (1066.79s)
--- PASS: TestAccEC2AMI_tpmSupport (1071.75s)
--- PASS: TestAccEC2AMI_disappears (1074.21s)
--- PASS: TestAccEC2AMI_boot (1075.10s)
--- PASS: TestAccEC2AMI_basic (1086.15s)
--- PASS: TestAccEC2AMIFromInstance_basic (1140.95s)
--- PASS: TestAccEC2AMIFromInstance_disappears (1155.93s)
--- PASS: …
```

resource/aws_ami: Fixes eventual consistency errors

---

.changelog/34773.txt
internal/service/ssoadmin/application_data_source.go
internal/service/ssoadmin/application_data_source_test.go
internal/service/ssoadmin/service_package_gen.go
website/docs/d/ssoadmin_application.html.markdown

This data source will allow practitioners to manage AWS Identity Center applications with Terraform.
Relates #34723 
- https://docs.aws.amazon.com/singlesignon/latest/APIReference/API_DescribeApplication.html
```console
% make testacc PKG=ssoadmin TESTS=TestAccSSOAdminApplicationDataSource_
TF_ACC=1 go test ./internal/service/ssoadmin/... -v -count 1 -parallel 20 -run='TestAccSSOAdminApplicationDataSource_'  -timeout 360m
=== RUN   TestAccSSOAdminApplicationDataSource_basic
=== PAUSE TestAccSSOAdminApplicationDataSource_basic
=== CONT  TestAccSSOAdminApplicationDataSource_basic
--- PASS: TestAccSSOAdminApplicationDataSource_basic (43.73s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/ssoadmin   46.932s …
```

d/aws_ssoadmin_application: new data source

---

.changelog/34820.txt
internal/framework/flex/autoflex.go
internal/framework/flex/autoflex_test.go

The underlying cause was the auto-flattening of a `nil` string pointer into the `ARN` custom type.
AutoFlEx was not correctly dealing with flattening `nil` pointers to any primitive type into a custom type -- it always assumed that the target was the "non-custom", base type.
I foresee problems with slices and maps of custom primitive types...
Closes https://github.com/hashicorp/terraform-provider-aws/issues/34802.
```console
% make testacc TESTARGS='-run=TestAccSecurityLake_serial/DataLake' PKG=securitylake
TF_ACC=1 go test ./internal/service/securitylake/... -v -count 1 -parallel 20  -run=TestAccSecurityLake_serial/DataLake -timeout 360m
=== RUN   TestAccSecurityLake_serial
=== PAUSE TestAccSecurityLake_serial
=== CONT …
```

r/aws_securitylake_data_lake: Fix panic on import

---

website/docs/d/emr_supported_instance_types.html.markdown

Adds an example describing how to pair this data source with a lifecycle precondition to create validation of the configured `instance_type` on resources such as `aws_emr_cluster`.
Closes #33998
- https://github.com/hashicorp/terraform-provider-aws/issues/33998#issuecomment-1821203656

d/aws_emr_supported_instance_types: add lifecycle precondition example

---

.changelog/34728.txt
.ci/semgrep/pluginsdk/isnewresource.yml
internal/service/rds/blue_green.go
internal/service/rds/exports_test.go
internal/service/rds/instance.go
internal/service/rds/instance_test.go

If an `aws_db_instance` is updated manually using a Blue/Green Deployment, the provider would lose track of it. Allow the provider to keep it under management.
```console
% make testacc PKG=rds TESTS=TestAccRDSInstance_BlueGreenDeployment_
--- PASS: TestAccRDSInstance_BlueGreenDeployment_deletionProtectionBypassesBlueGreen (978.93s)
--- PASS: TestAccRDSInstance_BlueGreenDeployment_tags (1082.57s)
--- PASS: TestAccRDSInstance_BlueGreenDeployment_passwordBypassesBlueGreen (1203.86s)
--- PASS: TestAccRDSInstance_BlueGreenDeployment_updateParameterGroup (2564.51s)
--- PASS: TestAccRDSInstance_BlueGreenDeployment_updateEngineVersion (2620.85s)
--- PASS: TestAccRDSInstance_BlueGreenDeployment_updateInstanceClass (2704.70s)
--- PASS: TestAccRDSInstance_BlueGreenDeployment_updateAndEnableBackups …
```

resource/aws_db_instance: Allow out-of-band Blue/Green update

---

.changelog/34716.txt
internal/service/ecr/pull_through_cache_rule.go
internal/service/ecr/pull_through_cache_rule_data_source.go
internal/service/ecr/pull_through_cache_rule_data_source_test.go
internal/service/ecr/pull_through_cache_rule_test.go

Fixes validation of `ecr_repository_prefix` in `aws_ecr_pull_through_cache_rule`.
Referred to the latest AWS documentation and corrected the string size and regular expression pattern for `ecr_repository_prefix`.
Closes #34516
- https://docs.aws.amazon.com/AmazonECR/latest/APIReference/API_CreatePullThroughCacheRule.html
```console
% make testacc TESTS=TestAccECRPullThroughCacheRule_ PKG=ecr          
TF_ACC=1 go test ./internal/service/ecr/... -v -count 1 -parallel 20 -run='TestAccECRPullThroughCacheRule_'  -timeout 360m
=== RUN   TestAccECRPullThroughCacheRule_basic
=== PAUSE TestAccECRPullThroughCacheRule_basic
=== RUN   TestAccECRPullThroughCacheRule_disappears
=== PAUSE TestAccECRPullThroughCacheRule_disappears
=== RUN …
```

Fix `ecr_repository_prefix` validation in `aws_ecr_pull_through_cache_rule`

---

infrastructure/repository/labels-workflow.tf

I've noticed for a while that the `service/meta` label was being recreated on every run in Terraform Cloud. Finally decided to chase it down, and it's due to us creating it in two places: where I've removed it in this PR, and in the `labels-service.tf` file. Since `labels-service.tf` is generated, it seemed more appropriate to remove the explicit definition here.
`labels-service.tf` references:
- [in the list of services](https://github.com/hashicorp/terraform-provider-aws/blob/bca478224726ecd358774f2e333c95a4784bdc0b/infrastructure/repository/labels-service.tf#L210)
- ...which is used [in this `for_each`](https://github.com/hashicorp/terraform-provider-aws/blob/bca478224726ecd358774f2e333c95a4784bdc0b/infrastructure/repository/labels-service.tf#L342-L349)
N/a, labels automation

Fix duplicate `service/meta` label issue

---

website/docs/r/cloudwatch_metric_stream.html.markdown

AWS CloudWatch Metric Streams just released support for the OpenTelmetry1.0 output format. This is a small doc change to include the new value supported for `output_format`.
- AWS What's New: https://aws.amazon.com/about-aws/whats-new/2023/12/amazon-cloudwatch-metric-streams-opentelemetry-1-0-0/
- AWS CloudWatch Metric Streams output format documentation: https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch-metric-streams-formats.html

Update CW Metric Stream doc with support for OpenTelemetry1.0

---

internal/service/s3/sweep.go

If a Region doesn't support S3 directory buckets still allow object from general purpose buckets to be deleted by the sweeper.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/34612.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/34647.

US GovCloud S3 sweeper fixes

---

website/docs/r/cloudfront_function.html.markdown

This seems to have been a recent addition that hasn't been announced anywhere. It was mentioned in https://aws.amazon.com/blogs/aws/introducing-amazon-cloudfront-keyvaluestore-a-low-latency-datastore-for-cloudfront-functions/ but otherwise it just seems to have appeared in the documentation
I have updated the runtime version shown in the example as I assume most people would prefer to use the more recent runtime version.
https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/functions-javascript-runtime-20.html
https://docs.aws.amazon.com/cloudfront/latest/APIReference/API_FunctionConfig.html
I have not run this since it's a documentation-only change.

Mention "cloudfront-js-2.0" now is an available runtime for CloudFront funcs

---

.changelog/34859.txt
internal/service/ec2/vpc_.go

IPAM can take ~30 minutes to release allocations, so the 20 minute time out is not long enough. This PR increases the timeout to 35 minutes.
Relates https://github.com/hashicorp/terraform-provider-aws/issues/30165.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/34628.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/30795.
Relates https://github.com/hashicorp/terraform-provider-aws/issues/31211.
```console
...
```

Fix IPAM allocation timeout

---

website/docs/r/lightsail_instance.html.markdown

This patch adds `eu-north-1` to the lightsail instance documentation and also mentions the AWS CLI command `aws lightsail get-bundles` to list available bundles. Perhaps the section about bundles can be removed in favor of this (cf. how `blueprint_id`s are documented)?
Closes #34840

lightsail: link to upstream documentation for zones, bundles, blueprints

---

internal/framework/flex/auto_flatten.go
internal/framework/flex/auto_flatten_test.go
internal/framework/flex/autoflex_test.go

This should prevent panics for list/sets/maps of string/*string types when nil values are returned from the AWS API and custom [List/Set/Map]Of types are used in the underlying Terraform data structures.
Before:
```console
% go test -count=1 ./internal/framework/flex/...
--- FAIL: TestFlatten (0.01s)
--- FAIL: TestFlatten/zero_value_slice/map_of_string_type_Source_and_List/Set/Map_of_string_types_Target (0.00s)
panic: reflect.Set: value of type basetypes.ListValue is not assignable to type types.ListValueOf[github.com/hashicorp/terraform-plugin-framework/types/basetypes.StringValue] [recovered]
panic: reflect.Set: value of type basetypes.ListValue is not assignable to type types.ListValueOf[github.com/hashicorp/terraform-plugin-framework/types/basetypes.StringValue]
goroutine 305 …
```

internal/framework/flex: use ValueFromList for nil slice and map values

---

.changelog/34839.txt
internal/service/ssoadmin/exports_test.go
internal/service/ssoadmin/service_package_gen.go
internal/service/ssoadmin/trusted_token_issuer.go
internal/service/ssoadmin/trusted_token_issuer_test.go
website/docs/r/ssoadmin_trusted_token_issuer.html.markdown

This PR adds the ability to manage AWS Identity Center trusted token issuers with Terraform by introducing the `aws_ssoadmin_trusted_token_issuer` resource.
Closes https://github.com/hashicorp/terraform-provider-aws/issues/34766
```console
make testacc TESTS=TestAccSSOAdminTrustedTokenIssuer_ PKG=ssoadmin
TF_ACC=1 go test ./internal/service/ssoadmin/... -v -count 1 -parallel 20 -run='TestAccSSOAdminTrustedTokenIssuer_'  -timeout 360m
=== RUN   TestAccSSOAdminTrustedTokenIssuer_basic
=== PAUSE TestAccSSOAdminTrustedTokenIssuer_basic
=== RUN   TestAccSSOAdminTrustedTokenIssuer_update
=== PAUSE TestAccSSOAdminTrustedTokenIssuer_update
=== RUN   TestAccSSOAdminTrustedTokenIssuer_disappears
=== PAUSE …
```

[New Resource]: Added ssoadmin `trusted_token_issuer` resource

---

.changelog/34916.txt
internal/service/polly/service_package_gen.go
internal/service/polly/voices_data_source.go
internal/service/polly/voices_data_source_test.go
names/names.go
website/docs/d/polly_voices.html.markdown

This data source will allow practitioners to list available voices from AWS Polly.
Closes #34641
- https://docs.aws.amazon.com/polly/latest/dg/API_DescribeVoices.html
```console
% make testacc PKG=polly
TF_ACC=1 go test ./internal/service/polly/... -v -count 1 -parallel 20   -timeout 360m
--- PASS: TestAccPollyVoicesDataSource_basic (7.79s)
--- PASS: TestAccPollyVoicesDataSource_languageCode (7.79s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/polly      11.095s
```

d/aws_polly_voices: new data source

---

internal/service/finspace/kx_volume_test.go

Adds missed commit from #34833 .
Relates #34833 
```console
% make testacc TESTS=TestAccFinSpaceKxVolume_tags PKG=finspace ACCTEST_PARALLELISM=1
TF_ACC=1 go test ./internal/service/finspace/... -v -count 1 -parallel 1 -run='TestAccFinSpaceKxVolume_tags'  -timeout 360m
=== RUN   TestAccFinSpaceKxVolume_tags
=== PAUSE TestAccFinSpaceKxVolume_tags
=== CONT  TestAccFinSpaceKxVolume_tags
--- PASS: TestAccFinSpaceKxVolume_tags (1626.74s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/finspace   1630.055s
```

r/aws_finspace_kx_volume(test): add tags test

---

internal/framework/flex/auto_expand.go
internal/framework/flex/auto_expand_test.go
internal/framework/flex/auto_flatten.go
internal/framework/flex/auto_flatten_test.go
internal/framework/flex/autoflex.go
internal/framework/flex/autoflex_test.go

Closes #0000
```console
% go test ./internal/framework/flex/... -v -count 1 -parallel 20 -run='TestFlat'  
=== RUN   TestFlatten
=== PAUSE TestFlatten
=== RUN   TestFlattenGeneric
=== PAUSE TestFlattenGeneric
=== RUN   TestFlattenFrameworkStringList
=== PAUSE TestFlattenFrameworkStringList
=== RUN   TestFlattenFrameworkStringListLegacy
=== PAUSE TestFlattenFrameworkStringListLegacy
=== RUN   TestFlattenFrameworkStringValueList
=== PAUSE TestFlattenFrameworkStringValueList
=== RUN   TestFlattenFrameworkStringValueListLegacy
=== PAUSE TestFlattenFrameworkStringValueListLegacy
=== RUN   TestFlattenFrameworkStringMap
=== PAUSE TestFlattenFrameworkStringMap
=== RUN   TestFlattenFrameworkStringValueMap
=== PAUSE TestFlattenFrameworkStringValueMap
=== RUN …
```

autoflex: Add block key map

---

.changelog/34890.txt
internal/service/s3/bucket.go

Closes #34389.
The change acknowledges the variations in error message text across different S3 implementations while ensuring that the correct error code is the primary criterion for error detection.

Make serverside encryption error check more compatible

---

.changelog/34967.txt
internal/service/ssoadmin/application.go

This fix prevents the portal_options.sign_in_options.application_url argument from being sent on all create and update requests. Now, a value will only be sent when set to a non-nil value.
Closes #34836
- https://docs.aws.amazon.com/singlesignon/latest/APIReference/API_SignInOptions.html
```console
% make testacc PKG=ssoadmin TESTS=TestAccSSOAdminApplication_
TF_ACC=1 go test ./internal/service/ssoadmin/... -v -count 1 -parallel 20 -run='TestAccSSOAdminApplication_'  -timeout 360m
--- PASS: TestAccSSOAdminApplication_disappears (11.18s)
--- PASS: TestAccSSOAdminApplication_basic (13.04s)
--- PASS: TestAccSSOAdminApplication_portalOptions (18.73s)
--- PASS: TestAccSSOAdminApplication_description (19.34s)
--- PASS: …
```

r/aws_ssoadmin_application: send application_url only when set

---

.changelog/34353.txt
.changelog/CHANGEME.txt
internal/service/batch/compute_environment.go
internal/service/batch/compute_environment_data_source.go
internal/service/batch/compute_environment_data_source_test.go
internal/service/batch/compute_environment_test.go
website/docs/d/batch_compute_environment.html.markdown
website/docs/r/batch_compute_environment.html.markdown

Closes: #32927, #34145
```shell
$ make testacc TESTS=TestAccBatchComputeEnvironment_ PKG=batch
TF_ACC=1 go test ./internal/service/batch/... -v -count 1 -parallel 20 -run='TestAccBatchComputeEnvironment_'  -timeout 360m
=== RUN   TestAccBatchComputeEnvironment_basic
=== PAUSE TestAccBatchComputeEnvironment_basic
=== RUN   TestAccBatchComputeEnvironment_disappears
=== PAUSE TestAccBatchComputeEnvironment_disappears
=== RUN   TestAccBatchComputeEnvironment_nameGenerated
=== PAUSE TestAccBatchComputeEnvironment_nameGenerated
=== RUN   TestAccBatchComputeEnvironment_namePrefix
=== PAUSE TestAccBatchComputeEnvironment_namePrefix
=== RUN   TestAccBatchComputeEnvironment_eksConfiguration
=== PAUSE …
```

AWS Batch Compute Environment add `update_policy` parameter

---

internal/framework/flex/auto_expand.go
internal/framework/flex/auto_expand_test.go
internal/framework/flex/auto_flatten.go
internal/framework/flex/auto_flatten_test.go
internal/framework/flex/autoflex_test.go
internal/framework/types/string_enum.go

Closes #0000
```console
% go test ./internal/framework/flex/... -v -count 1 -parallel 2 -run="Test"
=== RUN   TestExpand
=== PAUSE TestExpand
=== RUN   TestExpandGeneric
=== PAUSE TestExpandGeneric
=== RUN   TestFlatten
=== PAUSE TestFlatten
=== RUN   TestFlattenGeneric
=== PAUSE TestFlattenGeneric
=== RUN   TestSet_Difference_strings
=== PAUSE TestSet_Difference_strings
=== RUN   TestBoolFromFramework
=== PAUSE TestBoolFromFramework
=== RUN   TestBoolToFramework
=== PAUSE TestBoolToFramework
=== RUN   TestBoolToFrameworkLegacy
=== PAUSE TestBoolToFrameworkLegacy
=== RUN   TestFloat64ToFramework
=== PAUSE TestFloat64ToFramework
=== RUN   TestFloat64ToFrameworkLegacy
=== PAUSE TestFloat64ToFrameworkLegacy
=== RUN   TestFloat32ToFramework
=== PAUSE TestFloat32ToFramework
=== RUN …
```

autoflex: Add StringEnum capability for MapBlockKeys

---

.changelog/34998.txt
internal/service/finspace/kx_dataview.go
internal/service/finspace/kx_dataview_test.go
website/docs/index.html.markdown

Composes a synthetic `arn` attribute on read to allow transparent tagging to properly list tags for dataview resources. Previously, read always returned an empty map of tags causing a persistent diff when `tags` were set in configuration. If in the future `DataviewArn` is returned from the Describe API, the composed ARN value can be replaced with the value from the API response insead.
Closes #34990
Relates #34828
```console
% make testacc PKG=finspace TESTS=TestAccFinSpaceKxDataview_ ACCTEST_PARALELLISM=1
TF_ACC=1 go test ./internal/service/finspace/... -v -count 1 -parallel 20 -run='TestAccFinSpaceKxDataview_'  -timeout 360m
--- PASS: TestAccFinSpaceKxDataview_disappears (996.11s)
--- PASS: TestAccFinSpaceKxDataview_basic …
```

r/aws_finspace_kx_dataview: properly set arn, enabling tagging

---

.changelog/35024.txt
internal/service/secretsmanager/secret.go
internal/service/secretsmanager/secret_rotation.go
internal/service/secretsmanager/secret_rotation_test.go
internal/service/secretsmanager/secret_version.go

Due to a `DiffSuppressFunc`, changes to `rotation_rules.automatically_after_days` were incorrectly ignored if `rotation_rules.schedule_expression` was set.
Also adds required `ClientRequestToken` for idempotent requests.
```console
% make testacc PKG=secretsmanager TESTS=TestAccSecretsManagerSecretRotation_
--- PASS: TestAccSecretsManagerSecretRotation_basic (41.36s)
--- PASS: TestAccSecretsManagerSecretRotation_scheduleExpressionToDays (52.99s)
--- PASS: TestAccSecretsManagerSecretRotation_scheduleExpression (54.47s)
--- PASS: TestAccSecretsManagerSecretRotation_duration (56.11s)
--- PASS: TestAccSecretsManagerSecretRotation_scheduleExpressionHours (61.52s)
```
```console
% make testacc PKG=secretsmanager TESTS=TestAccSecretsManagerSecret_
--- PASS: …
```

resource/aws_secretsmanager_secret_rotation: Fix bug with updates

---

website/docs/r/sqs_queue.html.markdown

Updated the documentation of the sqs_queue resource related to the dead letter queue. The current documentation will lead developers to a cycle error. The updated documentation shows how to use the aws_sqs_queue_redrive_allow_policy resource to set up a dead letter queue.
Closes #34219 
https://github.com/hashicorp/terraform-provider-aws/issues/22577#issuecomment-1326119133

Update sqs_queue dead letter queue section documentation

---

.changelog/35050.txt
internal/service/lambda/function.go
internal/service/lambda/function_data_source.go
internal/service/lambda/function_data_source_test.go
internal/service/lambda/function_test.go
internal/service/lambda/validate.go
website/docs/d/lambda_function.html.markdown
website/docs/r/lambda_function.html.markdown

Add `logging_config` configuration block in support of AWS Lambda advanced logging controls.
Closes #34455
- [Docs: AWS Lambda advanced logging controls](https://docs.aws.amazon.com/lambda/latest/dg/monitoring-cloudwatchlogs.html#monitoring-cloudwatchlogs-advanced)
```console
% make testacc 'TESTS=TestAccLambdaFunction(DataSource)?_(basic|loggingConfig)'  PKG=lambda
TF_ACC=1 go test ./internal/service/lambda/... -v -count 1 -parallel 20 -run='TestAccLambdaFunction(DataSource)?_(basic|loggingConfig)'  -timeout 360m
=== RUN   TestAccLambdaFunctionDataSource_basic
=== PAUSE TestAccLambdaFunctionDataSource_basic
=== RUN   TestAccLambdaFunctionDataSource_loggingConfig
=== PAUSE TestAccLambdaFunctionDataSource_loggingConfig
=== RUN …
```

Add support for logging_config in `aws_lambda_function` resource

---

.changelog/35062.txt
internal/service/amp/workspace.go
internal/service/amp/workspace_data_source.go
internal/service/amp/workspace_data_source_test.go
internal/service/amp/workspace_test.go
website/docs/d/prometheus_workspace.html.markdown
website/docs/r/prometheus_workspace.html.markdown

Implements AWS Key Management Service encryption for Amazon Managed Service for Prometheus Workspace
Closes #35048
[Encryption at rest](https://docs.aws.amazon.com/prometheus/latest/userguide/encryption-at-rest-Amazon-Service-Prometheus.html)
```Console
make testacc TESTS=TestAccAMPWorkspace_kms PKG=amp
TF_ACC=1 go test ./internal/service/amp/... -v -count 1 -parallel 20 -run='TestAccAMPWorkspace_kms'  -timeout 360m
=== RUN   TestAccAMPWorkspace_kms
=== PAUSE TestAccAMPWorkspace_kms
=== CONT  TestAccAMPWorkspace_kms
--- PASS: TestAccAMPWorkspace_kms (29.89s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/amp        29.997s
```

Add support for KMS key ARN in AMP Workspace resource

---

.changelog/35056.txt
internal/service/ses/configuration_set.go
website/docs/r/ses_configuration_set.html.markdown

This PR fixes a bug that caused omitting `tracking_options` from `aws_ses_configuration_set` state and resulted in persistent diff.
No acceptance tests added/updated as this functionality is best-effort. Tests would require a verified SES domain identity. Please see:
https://github.com/hashicorp/terraform-provider-aws/blob/5deca6413355b80d737a33f646223798dc0af2cc/internal/service/ses/configuration_set_test.go#L319-L320
Performed manual test instead:
```terraform
terraform {
aws = {
version = "~> 5.0"
}
}
}
region = "eu-central-1"
}
variable "domain" {
type = string
}
resource "aws_route53_zone" "this" {
name = var.domain
}
resource "aws_ses_domain_identity" "this" {
domain = var.domain
}
resource "aws_ses_domain_dkim" "this" …
```

r/aws_ses_configuration_set: reflect `tracking_options` in state

---

.changelog/35043.txt
internal/service/codebuild/project.go
internal/service/codebuild/project_test.go
website/docs/r/codebuild_project.html.markdown

- In November, AWS CodeBuild released the ability to build using the Lambda runtime.
- Lambda runtime does not have a `queued_timeout` `build_timeout` property.
- However, due to the `build_timeout`, `queue_timeout` default, it tries to assign a default value every time you replace Compute_Type with Lambda, resulting in an error.
```
"queued_timeout": {
Type:         schema.TypeInt,
Optional:     true,
Default:      480,
...
"build_timeout": {
Type:         schema.TypeInt,
Optional:     true,
Default:      60,
}
```
Closes #34376 
- Since CodeBuild runs its own Container, it has a `queued_timeout` property that can handle exceptions until the Container runs.
- However, lambdas have a very short warm-up time, so they don't have that property.
URL
- …

Fix unsupported properties for lambda compute types in `codebuild`.

---

.changelog/35071.txt
internal/service/autoscaling/attachment.go
internal/service/autoscaling/attachment_test.go
internal/service/autoscaling/errors.go
internal/service/autoscaling/group.go
internal/service/autoscaling/group_data_source_test.go
internal/service/autoscaling/group_tag_test.go
internal/service/autoscaling/group_test.go
internal/service/autoscaling/groups_data_source_test.go
internal/service/autoscaling/launch_configuration.go
internal/service/autoscaling/launch_configuration_data_source_test.go
internal/service/autoscaling/launch_configuration_test.go
internal/service/autoscaling/lifecycle_hook.go
internal/service/autoscaling/lifecycle_hook_test.go
internal/service/autoscaling/notification_test.go
internal/service/autoscaling/policy.go
internal/service/autoscaling/policy_test.go
internal/service/autoscaling/schedule.go
internal/service/autoscaling/traffic_source_attachment_test.go

Set instance protection can fail when instance, will be already removed from autoscaling group. 
Method `drainGroup` is first updating AutoScalingGroup with `{DesiredCapacity: 0, MinSize:0, MaxSize: 0}`
next ensure that instances are not prevented from scaling in, as make sens updating autoscaling group as soon as posible.
Is posible that `SetInstanceProtectionWithContext` will fail, this can happen at least in two cases:
1) API will be throttled for few sec by other client calls, but when throttling ends instance can be already fully removed 
so then  `SetInstanceProtectionWithContext` return ValidationError
2) The number of instances in autoscaling group is large, there will be multiple requests to run `SetInstanceProtectionWithContext` as they are run with package of 50 instances there …

[Fix] Set instance protection can fail as instance can be already deleted from Autoscaling Group

---

website/docs/r/route.html.markdown

The current example usage specifies a hard-coded route table ID, and then proceeds to use an explicit `depends_on` on the route table. Besides the fact that logically it doesn’t make sense since if it’s being deployed together you wouldn’t have the ID yet, `depends_on` shouldn’t be promoted in general as it can cause issues when used unnecessarily.
Closes #35084

Remove unnecessary depends_on+hard coded ID of dependency

---

website/docs/cdktf/python/r/lb_trust_store.html.markdown
website/docs/cdktf/python/r/lb_trust_store_revocation.html.markdown
website/docs/r/lb_trust_store.html.markdown
website/docs/r/lb_trust_store_revocation.html.markdown

The `lb_trust_store` docs reference an S3 Bucket name for the `ca_certificates_bundle_s3_key` argument, when it should be an S3 Object key.
Closes #35072
As can be confirmed in the test here, it is expected to be an object key, not a bucket name:
[terraform-provider-aws/internal/service/elbv2/trust_store_test.go](https://github.com/hashicorp/terraform-provider-aws/blob/5deca6413355b80d737a33f646223798dc0af2cc/internal/service/elbv2/trust_store_test.go#L304)

docs(lb_trust_store): fix reference description

---

website/docs/r/instance.html.markdown

Updates the AMI filter in the aws_instance example code to use the latest available Ubuntu LTS release. This prevents people who are using this example from having to update the AMI filter to use the current LTS release.

Update AMI filter example to use latest Ubuntu LTS

---

.changelog/35096.txt
internal/service/efs/file_system.go
internal/service/efs/file_system_data_source.go
internal/service/efs/file_system_test.go
website/docs/r/efs_file_system.html.markdown

Implement transition_to_archive lifecycle policy in efs_file_system.
Closes #35082 
```console
❯ make testacc TESTARGS="-run=TestAccEFSFileSystem_lifecyclePolicy\|TestAccEFSFileSystemDataSource_id" PKG=efs
TF_ACC=1 go test ./internal/service/efs/... -v -count 1 -parallel 20  -run=TestAccEFSFileSystem_lifecyclePolicy\|TestAccEFSFileSystemDataSource_id -timeout 360m
=== RUN   TestAccEFSFileSystemDataSource_id
=== PAUSE TestAccEFSFileSystemDataSource_id
=== RUN   TestAccEFSFileSystem_lifecyclePolicy
=== PAUSE TestAccEFSFileSystem_lifecyclePolicy
=== CONT  TestAccEFSFileSystemDataSource_id
=== CONT  TestAccEFSFileSystem_lifecyclePolicy
--- PASS: TestAccEFSFileSystemDataSource_id (31.59s)
--- PASS: TestAccEFSFileSystem_lifecyclePolicy …
```

feat(efs_file_system): lifecycle_policy transition_to_archive

---

.changelog/35098.txt
internal/service/route53resolver/endpoint.go
internal/service/route53resolver/endpoint_data_source.go
internal/service/route53resolver/endpoint_data_source_test.go
internal/service/route53resolver/endpoint_test.go
website/docs/d/route53_resolver_endpoint.html.markdown
website/docs/r/route53_resolver_endpoint.html.markdown

Adds `protocols` as an option in `aws_route53_resolver_endpoint`.
Closes #35047
[UpdateResolverEndpoint API](https://docs.aws.amazon.com/Route53/latest/APIReference/API_route53resolver_UpdateResolverEndpoint.html#API_route53resolver_UpdateResolverEndpoint_RequestSyntax)
```console
% make testacc TESTS=TestAccRoute53ResolverEndpoint_updateOutbound PKG=route53resolver
TF_ACC=1 go test ./internal/service/route53resolver/... -v -count 1 -parallel 20 -run='TestAccRoute53ResolverEndpoint_updateOutbound'  -timeout 360m
=== RUN   TestAccRoute53ResolverEndpoint_updateOutbound
=== PAUSE TestAccRoute53ResolverEndpoint_updateOutbound
=== CONT  TestAccRoute53ResolverEndpoint_updateOutbound
--- PASS: …
```

`r/aws_route53_resolver_endpoint`: add `protocols`

---

.changelog/35150.txt
internal/service/datasync/agent.go

This requirement previously prevented successful import of agents initialized with an `activation_key`. The `activation_key` is not returned by the read operation, so setting this required value in configuration always forced a new resource on the next apply. Practitioners could work around the issue with an `ignore_changes` lifecycle argument, but removing the `ExactlyOneOf` condition in favor of a `ConflictsWith` condition allows agents created with an activation key to be imported _without_ requiring the attribute to be set in the corresponding Terraform configuration.
An import statement can now look like:
```hcl
import {
to = aws_datasync_agent.example
id = "arn:aws:datasync:us-east-1:123456789012:agent/agent-12345678901234567"
}
resource "aws_datasync_agent" "example" {
name = …
```

r/aws_datasync_agent: remove ExactlyOneOf activation_key, ip_address

---

website/docs/r/finspace_kx_cluster.html.markdown

This PR has been created to make Doc updates for the Cluster Resource. (Adding Tickerplant cluster to the types of clusters available.) 
N/A
Closes #0000
This change is being made to align with the FinSpace Public [documentation](https://docs.aws.amazon.com/cli/latest/reference/finspace/create-kx-cluster.html).

Cluster doc update to add TP type cluster.

---

.changelog/34817.txt
internal/service/glue/catalog_table.go
internal/service/glue/catalog_table_data_source.go
internal/service/glue/catalog_table_test.go
website/docs/d/glue_catalog_table.html.markdown
website/docs/r/glue_catalog_table.html.markdown

Adds the `region` to the `target_table` block for both the resource and data source: `aws_glue_catalog_table`
Closes #34806
Resource `aws_glue_catalog_table `:
```console
make testacc TESTS=TestAccGlueCatalogTable_ PKG=glue                                                                                                             rbenv:3.1.0
TF_ACC=1 go test ./internal/service/glue/... -v -count 1 -parallel 20 -run='TestAccGlueCatalogTable_'  -timeout 360m
=== RUN   TestAccGlueCatalogTable_basic
=== PAUSE TestAccGlueCatalogTable_basic
=== RUN   TestAccGlueCatalogTable_columnParameters
=== PAUSE TestAccGlueCatalogTable_columnParameters
=== RUN   TestAccGlueCatalogTable_full
=== PAUSE TestAccGlueCatalogTable_full
=== RUN …
```

chore: add `region` argument to `target_table` in `aws_glue_catalog_table`

---

.changelog/35195.txt
internal/service/glue/catalog_database.go

Previously `EntityNotFound` exceptions were not handled during deletion, resulting in a hard error message where the provider should instead proceed without error.
Before:
```console
% make testacc PKG=glue TESTS=TestAccGlueCatalogDatabase_disappears
TF_ACC=1 go test ./internal/service/glue/... -v -count 1 -parallel 20 -run='TestAccGlueCatalogDatabase_disappears'  -timeout 360m
=== RUN   TestAccGlueCatalogDatabase_disappears
=== PAUSE TestAccGlueCatalogDatabase_disappears
=== CONT  TestAccGlueCatalogDatabase_disappears
testing_new.go:91: Error running post-test destroy, there may be dangling resources: exit status 1
Error: deleting Glue Catalog Database (727561393803:tf-acc-test-7599062601241076411): EntityNotFoundException: …
```

r/aws_glue_catalog_database: handle disappearing resources on delete

---

website/docs/r/accessanalyzer_analyzer.html.markdown

This PR updates the list of value values for the `type` attribute for the `aws_accessanalyzer_analyzer` resource, since Access Analyzer now supports unused access analyzer.
Closes #35145
[API reference for CreateAnalyzer](https://docs.aws.amazon.com/access-analyzer/latest/APIReference/API_CreateAnalyzer.html) is used as a reference for the doc update in this PR.
n/a

docs: Update type valid values for aws_accessanalyzer_analyzer

---

.changelog/35207.txt
internal/service/finspace/kx_dataview.go
website/docs/r/finspace_kx_dataview.html.markdown

Increasing the Timeout for Dataview Operations to match the FinSpace API in order to support customer use-cases.

Increase Dataview operation Timeouts to match the FinSpace API.

---

website/docs/d/networkfirewall_firewall.html.markdown
website/docs/r/networkfirewall_firewall.html.markdown

This PR enhances the description of the protection-related flags/attributes for the `aws_netwrokfirewall_firewall` resource and data source. Note that the API reference still used confusing wordings for the `deletion_protection` field but the other protection-related fields are fine, so for consistency the latter wordings are used to update the `deletion_protection` description.
Closes #35136
The wordings in the [Firewall API reference](https://docs.aws.amazon.com/network-firewall/latest/APIReference/API_Firewall.html) is used to clarify the Terraform target documentation in this PR.
n/a

docs: Clarify protection attr descs for aws_networkfirewall_firewall

---

website/docs/r/dms_endpoint.html.markdown

This PR updates the documentation for `aws_dms_endpoint` with the conditions for specifying either the attributes related to Secrets Manager or the plain-text endpoint details, but not both.
Closes #35019
The [DocDbSettings data type reference](https://docs.aws.amazon.com/dms/latest/APIReference/API_DocDbSettings.html) linked from the [CreateEndpoint API](https://docs.aws.amazon.com/dms/latest/APIReference/API_CreateEndpoint.html) has a note on this requirement which is ported into the target doc in this PR.
n/a

docs: Add note re. secret-related attrs in aws_dms_endpoint

---

website/docs/r/lexv2models_bot_version.html.markdown

This PR improves the documentation for the `aws_lexv2models_bot_version` resource, in particular providing the spec for the `locale_specification` map atrribute.
Closes #35015
The description in [CreateBotVersion API reference](https://docs.aws.amazon.com/lexv2/latest/APIReference/API_CreateBotVersion.html) is used to improve the current descriptions int he doc.
n/a

docs: Improve attr descs for aws_lexv2models_bot_version

---

internal/service/lambda/function_url.go
internal/service/lambda/function_url_data_source.go
website/docs/d/lambda_function_url.html.markdown
website/docs/r/lambda_function_url.html.markdown

Contrary to the AWS documentation, the Lambda URL does include a trailing slash.
Visible with a `aws lambda get-function-url-config` or `terraform state show` :
```
resource "aws_lambda_function_url" "example" {
authorization_type = "NONE"
function_arn       = "arn:aws:lambda:eu-central-1:12345:function:example"
function_name      = "example"
function_url       = "https://xxxxxsvlvu4esyqomzxe7crnte0xxxxx.lambda-url.eu-central-1.on.aws/"
id                 = "example"
invoke_mode        = "BUFFERED"
url_id             = "xxxxxxxxx"
}
```
[AWS Documentation](https://docs.aws.amazon.com/lambda/latest/dg/lambda-urls.html)
N/A

Add trailing slash in Lambda URL documentation

---

internal/service/s3/object_data_source_test.go

S3 objects keys with a multiple leading slashes (`/`) have those characters removed by AWS SDK for Go v1.
Test this.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/35220.
```console
% make testacc TESTARGS='-run=TestAccS3ObjectDataSource_leadingMultipleSlashes' PKG=s3
TF_ACC=1 go test ./internal/service/s3/... -v -count 1 -parallel 20  -run=TestAccS3ObjectDataSource_leadingMultipleSlashes -timeout 180m
=== RUN   TestAccS3ObjectDataSource_leadingMultipleSlashes
=== PAUSE TestAccS3ObjectDataSource_leadingMultipleSlashes
=== CONT  TestAccS3ObjectDataSource_leadingMultipleSlashes
--- PASS: TestAccS3ObjectDataSource_leadingMultipleSlashes (35.58s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/s …
```

[release/4.x] d/aws_s3_object: Test key with multiple leading slashes

---

website/docs/r/ec2_managed_prefix_list_entry.html.markdown

This PR corrects an incorrect copy/paste of the description of `aws_ec2_managed_prefix_list_entry.prefix_list_id`.
Closes #34963
N/a, docs

Correct `prefix_list_id` argument description in `aws_ec2_managed_prefix_list_entry`

---

.changelog/35215.txt
internal/service/appflow/flow.go
website/docs/cdktf/python/r/appflow_flow.html.markdown
website/docs/r/appflow_flow.html.markdown

This pull request adds the `target_file_size` field to the `resourceFlow` function and the `AppFlow` flow configuration. The `target_file_size` field is an optional property that specifies the desired file size, in MB, for each output file that Amazon AppFlow writes to the flow destination.
closes https://github.com/hashicorp/terraform-provider-aws/issues/34635
https://docs.aws.amazon.com/appflow/1.0/APIReference/API_AggregationConfig.html
n/a - test passed on private account

Add target_file_size field to AppFlow

---

.changelog/35225.txt
internal/service/iot/indexing_configuration.go
internal/service/iot/indexing_configuration_test.go

Add missing '$' to regex validation
Closes #35201 
```console
❯ make testacc TESTARGS="-run=TestAccIoTIndexingConfiguration_serial" PKG=iot
TF_ACC=1 go test ./internal/service/iot/... -v -count 1 -parallel 20  -run=TestAccIoTIndexingConfiguration_serial -timeout 360m
=== RUN   TestAccIoTIndexingConfiguration_serial
=== PAUSE TestAccIoTIndexingConfiguration_serial
=== CONT  TestAccIoTIndexingConfiguration_serial
=== RUN   TestAccIoTIndexingConfiguration_serial/basic
=== RUN   TestAccIoTIndexingConfiguration_serial/allAttributes
--- PASS: TestAccIoTIndexingConfiguration_serial (44.24s)
--- PASS: TestAccIoTIndexingConfiguration_serial/basic (22.32s)
--- PASS: TestAccIoTIndexingConfiguration_serial/allAttributes (21.92s)
PASS
ok …
```

chore(iot_indexing_configuration): fix reserved shadow regex

---

.changelog/35173.txt
internal/service/appstream/fleet.go
website/docs/r/appstream_fleet.html.markdown

Updated the max idle timeout for appstream fleet to be 360000, from 3600, to match aws documentation. See below
Closes #34453 
https://docs.aws.amazon.com/appstream2/latest/APIReference/API_Fleet.html See DisconnectTimeoutInSeconds

update the appstream fleet idle timeout per aws docs

---

website/docs/r/config_config_rule.html.markdown

config_rule resource docs fix

---

website/docs/r/cloudhsm_v2_hsm.html.markdown

Updating the documentation for cloudhsm_v2_hsm to include missing output parameters as given in Issue 34025: https://github.com/hashicorp/terraform-provider-aws/issues/34025
Closes #34025

Update cloudhsm_v2_hsm documentation per issue 34025

---

website/docs/r/security_group.html.markdown

Documentation change - this PR will update the aws_security_group resource to be more in line with best practices by using the aws_vpc_security_group_ingress_rule and aws_vpc_security_group_egress_rule together. I have modeled my example over the default example provided previously. 
References: AWS Unique ID: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/security-group-rules.html

Updating basic usage to include updated security group flow

---

.changelog/35223.txt
internal/service/s3/object.go
internal/service/s3/object_data_source_test.go

Removes any leading `./` from S3 object key names to maintain AWS SDK for Go v1 compatibility.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/33358.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/35220.
Relates https://github.com/hashicorp/terraform/issues/34279.
```console
% make testacc TESTARGS='-run=TestAccS3ObjectDataSource_' PKG=s3 ACCTEST_PARALLELISM=2
TF_ACC=1 go test ./internal/service/s3/... -v -count 1 -parallel 2  -run=TestAccS3ObjectDataSource_ -timeout 360m
=== RUN   TestAccS3ObjectDataSource_basic
=== PAUSE TestAccS3ObjectDataSource_basic
=== RUN   TestAccS3ObjectDataSource_basicViaAccessPoint
=== PAUSE TestAccS3ObjectDataSource_basicViaAccessPoint
=== RUN …
```

Remove leading `./` from S3 object key name -- AWS SDK for Go v1 compatibility

---

.changelog/35228.txt
internal/service/elbv2/load_balancer.go

When an update to an LB is desired the provider repeatedly calls `ModifyLoadBalancerAttributesWithContext()`, removing attributes-to-update as needed when the appropriate error is returned, e.g. `InvalidConfigurationRequest: Load balancer attribute key 'dns_record.client_routing_policy' is not supported on load balancers with type 'network'` will cause a retry without the `dns_record.client_routing_policy` attribute.
When there is only one attribute to update and it is not supported in this partition, we hit a case where we'll retry the `Modify...` call with an empty attribute list.  This is the case in the related issue.
The fix is to no-op if the attributes list is pruned to the empty slice.
:information_source:  I'm not sure how to write a new acceptance test for this one because the …

aws_lb: Handle case where no updated attributes are supported

---

website/docs/r/vpc_ipam_pool.html.markdown

This PR is used to correctly mark the `address_family` and `ipam_scope_id` attributes as required for the `aws_vpc_ipam_pool` resource.
Closes #35044
The [CreateIpamPool API reference](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_CreateIpamPool.html) is used as the official guide for whether attributes are required for cross-checking with the Terraform resource code and doc.
n/a

docs: Mark aws_vpc_ipam_pool attrs as required correctly

---

.github/workflows/issues.yml
.github/workflows/pull_request_target.yml

This PR updates our GitHub Actions workflows to move items labeled `regression` to the top of the working board. There's not currently support for this mutation in the `gh` CLI, so `gh api` is used to call the GraphQL API directly.
- [`updateprojectv2itemposition`](https://docs.github.com/en/graphql/reference/mutations#updateprojectv2itemposition)
- [`gh api`](https://cli.github.com/manual/gh_api)
N/a, Actions

Update workflows to move regressions to the top of the working board

---

.changelog/35269.txt
internal/service/ecr/image_data_source.go
internal/service/ecr/image_data_source_test.go

Most recent image can be different than the imaged tagged as `latest` and do not share the same tags.
Closes #35263.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/24526.
```console
% make testacc TESTARGS="-run=TestAccECRImageDataSource_basic" PKG=ecr
TF_ACC=1 go test ./internal/service/ecr/... -v -count 1 -parallel 20  -run=TestAccECRImageDataSource_basic -timeout 360m
=== RUN   TestAccECRImageDataSource_basic
=== PAUSE TestAccECRImageDataSource_basic
=== CONT  TestAccECRImageDataSource_basic
--- PASS: TestAccECRImageDataSource_basic (11.67s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/ecr	15.495s
```

r/aws_ecr_image: fix regression for most recent

---

website/docs/r/elasticache_serverless_cache.html.markdown

Fix typo in documentation
None
None
None

Fix typo in elasticache_serverless_cache docs

---

.changelog/35254.txt
internal/service/fis/experiment_template.go

Resource type `aws:eks:pod` can be created in a target and does not require `resource_arns` or `resource_tags`. Remove validation to allow operation to complete.
```hcl 
resource "aws_fis_experiment_template" "test" {
description = "test"
role_arn    = aws_iam_role.test.arn
stop_condition {
source = "none"
}
action {
name        = "Memory-Stress-1"
action_id   = "aws:eks:pod-memory-stress"
description = "EKS token service memory stress"
parameter {
key   = "duration"
value = "PT15M"
}
parameter {
key   = "kubernetesServiceAccount"
value = "fis-experiment"
}
target {
key   = "Pods"
value = "Pod-Target-1"
}
}
target {
name           = "Pod-Target-1"
resource_type  = "aws:eks:pod"
selection_mode = "ALL"
parameters = {
"clusterIdentifier" = "test"
"namespace"         = "default" …
```

r/aws_fis_expermient_template: remove validation for target properties

---

.changelog/35105.txt
internal/service/secretsmanager/secret_rotation.go
internal/service/secretsmanager/secret_rotation_test.go
website/docs/r/secretsmanager_secret_rotation.html.markdown

Add support for the `rotate_immediatley` argument for the resource `aws_secretsmanager_secret_rotation`
Closes #34961
[AWS SDK V1](https://pkg.go.dev/github.com/aws/aws-sdk-go@v1.49.13/service/secretsmanager#RotateSecretInput)
```Console
make testacc TESTS=TestAccSecretsManagerSecretRotation_ PKG=secretsmanager
TF_ACC=1 go test ./internal/service/secretsmanager/... -v -count 1 -parallel 20 -run='TestAccSecretsManagerSecretRotation_'  -timeout 360m
=== RUN   TestAccSecretsManagerSecretRotation_basic
=== PAUSE TestAccSecretsManagerSecretRotation_basic
=== RUN   TestAccSecretsManagerSecretRotation_rotateImmediately
=== PAUSE TestAccSecretsManagerSecretRotation_rotateImmediately
=== RUN …
```

Add rotate_immediately argument to secret rotation

---

website/docs/r/lambda_function.html.markdown

In order to align the documentation with the new released updates, this pull request includes **Java21** among the runtimes specified as being supported by snap_start.
Closes #35312
Check this : 
- [Improving startup performance with Lambda SnapStart](https://docs.aws.amazon.com/lambda/latest/dg/snapstart.html#snapstart-runtimes)
> SnapStart supports Java 11 and later [Java managed runtimes](https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html).
N/A, docs.

docs(lambda): add java21 support for snap_start

---

.changelog/35282.txt
internal/service/datasync/task.go
internal/service/datasync/task_test.go

Removing the schedule from a task should clear it completely.
Initial config
```hcl
resource "aws_datasync_task" "test" {
destination_location_arn = aws_datasync_location_s3.test1.arn
name                     = local.name1
source_location_arn      = aws_datasync_location_s3.test2.arn
options {
posix_permissions = "NONE"
verify_mode       = "ONLY_FILES_TRANSFERRED"
gid               = "NONE"
uid               = "NONE"
}
schedule {
schedule_expression = "cron(0/60 * * * ? *)"
}
}
```
update:
```hcl
resource "aws_datasync_task" "test" {
destination_location_arn = aws_datasync_location_s3.test1.arn
name                     = local.name1
source_location_arn      = aws_datasync_location_s3.test2.arn
options {
posix_permissions = "NONE"
verify_mode       = "ONLY_FILES_TRANSFERRED"
gid …
```

r/aws_datasync_task: allow removal of schedule

---

website/docs/r/api_gateway_method_response.html.markdown

This PR aims to improve the description of the `response_models` and `response_parameters` and provide a sample usage on how to use them.
Closes #31614
Used the [MethodResponse API data type documentation](https://docs.aws.amazon.com/apigateway/latest/api/API_MethodResponse.html#responseParameters) for reference on wordings.
n/a

docs: Improve response models and params descs for aws_api_gateway_method_response

---

website/docs/r/docdb_cluster_instance.html.markdown

This PR moves the `ca_cert_identifier` attribute from the attributes (read-only) section to the arguments section in the `aws_docdb_cluster_instance` resource documentation.
Closes #35089
Cross checked argument spec and description with the [aws docdb create-db-instance AWS CLI documentation](https://awscli.amazonaws.com/v2/documentation/api/2.0.34/reference/docdb/create-db-instance.html).
n/a

docs: Move ca_cert_identifier to arg list for1 aws_docdb_cluster_instance

---

.changelog/35284.txt
internal/service/lakeformation/resource.go
internal/service/lakeformation/resource_test.go
website/docs/r/lakeformation_resource.html.markdown

This argument will allow pracitioners to explicitly configure whether the value of `UseServiceLinkedRole` boolean in the underlying AWS RegisterResource API. Also fixes a bug where deleted resource registrations were not handled correctly by the destroy operation.
Closes #35283
- https://docs.aws.amazon.com/lake-formation/latest/APIReference/API_RegisterResource.html
```console
% make testacc PKG=lakeformation TESTS=TestAccLakeFormationResource_
TF_ACC=1 go test ./internal/service/lakeformation/... -v -count 1 -parallel 20 -run='TestAccLakeFormationResource_'  -timeout 360m
--- PASS: TestAccLakeFormationResource_basic (15.66s)
--- PASS: TestAccLakeFormationResource_disappears (16.16s)
--- PASS: …
```

r/aws_lakeformation_resource: add `use_service_linked_role` argument

---

.changelog/34891.txt
GNUmakefile
internal/framework/flex/auto_expand_test.go
internal/framework/flex/auto_flatten_test.go
internal/framework/types/mapof.go
internal/service/lexv2models/bot_locale.go
internal/service/lexv2models/exports_test.go
internal/service/lexv2models/intent.go
internal/service/lexv2models/intent_test.go
internal/service/lexv2models/service_package_gen.go
website/docs/r/lexv2models_intent.html.markdown

Relates #21375
```console
% make t T=TestAccLexV2ModelsIntent_ K=lexv2models 
TF_ACC=1 go test ./internal/service/lexv2models/... -v -count 1 -parallel 20 -run='TestAccLexV2ModelsIntent_'  -timeout 360m
=== RUN   TestAccLexV2ModelsIntent_basic
=== PAUSE TestAccLexV2ModelsIntent_basic
=== RUN   TestAccLexV2ModelsIntent_disappears
=== PAUSE TestAccLexV2ModelsIntent_disappears
=== RUN   TestAccLexV2ModelsIntent_updateConfirmationSetting
=== PAUSE TestAccLexV2ModelsIntent_updateConfirmationSetting
=== RUN   TestAccLexV2ModelsIntent_updateClosingSetting
=== PAUSE TestAccLexV2ModelsIntent_updateClosingSetting
=== RUN   TestAccLexV2ModelsIntent_updateInputContext
=== PAUSE TestAccLexV2ModelsIntent_updateInputContext
=== RUN …
```

lexv2models/intent: New resource

---

website/docs/r/db_option_group.html.markdown
website/docs/r/db_parameter_group.html.markdown

This PR is to add more clarity to the configuration block arguments in the `aws_db_option_group` and `aws_db_parameter_group` resource documentation.
Closes #33887
Used the [aws_vpn_connection resource doc](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/vpn_connection) as guidance for better structuring the configuration block descriptions.
n/a

docs: Identify cfg blocks more explicitly for option and param group docs

---

website/docs/r/s3_bucket.html.markdown

This PR adds more details for the `access_control_translation` configuration block that is relevant to replication configuration for the `aws_s3_bucket` resource.
Closes #33894
Referenced the [AccessControlTranslation API data type](https://docs.aws.amazon.com/AmazonS3/latest/API/API_AccessControlTranslation.html) for wordings.
n/a

docs: Add access_control_translation cfg block desc to aws_s3_bucket resource doc

---

website/docs/r/shield_application_layer_automatic_response.html.markdown

Corrects the `var` block in `aws_shield_application_layer_automatic_response` documentation page.
Closes #35372
https://developer.hashicorp.com/terraform/language/values/variables
n/a

docs: correct variable block in shield_application_layer_automatic_response documentation

---

website/docs/r/docdbelastic_cluster.html.markdown

Fixes misspelling of two of the arguments.
Closes #34970
- [`name`](https://github.com/hashicorp/terraform-provider-aws/blob/18e91a237e4af7ef729e08aa55271766e5887dea/internal/service/docdbelastic/cluster.go#L99)
- [`preferred_maintenance_window`](https://github.com/hashicorp/terraform-provider-aws/blob/18e91a237e4af7ef729e08aa55271766e5887dea/internal/service/docdbelastic/cluster.go#L105)
N/a, docs

Fix typos in r/aws_docdbelastic_cluster documentation

---

website/docs/r/db_instance.html.markdown

This PR changes the name used as an example value for `custom_iam_instance_profile` from including "InstanceRole" to "InstanceProfile" to avoid confusion, better reflect what's being shown, and parity with the other example configurations.
Closes #35086
N/a, docs

Change name of custom profile in `aws_db_instance` example for clarity

---

website/docs/cdktf/python/r/lambda_event_source_mapping.html.markdown
website/docs/r/lambda_event_source_mapping.html.markdown

In order to align the documentation with the new release of Lambda MSK and self-managed Apache Kafka event source mapping support [configuring on-failure destinations](https://docs.aws.amazon.com/lambda/latest/dg/with-msk.html#services-msk-configuring-destinations).
Closes #35107
https://docs.aws.amazon.com/lambda/latest/dg/with-msk.html#services-msk-configuring-destinations
N/A

docs/aws_lambda_event_source_mapping: MSK and self-managed Kafka event source mapping support configuring on-failure destinations

---

.changelog/35391.txt
internal/service/eks/access_entry.go
internal/service/eks/access_entry_test.go
internal/service/eks/cluster.go
internal/service/eks/consts.go
internal/service/eks/find.go
internal/service/eks/identity_provider_config.go
website/docs/r/eks_access_entry.html.markdown

currently `type` and `user_name` properties of `aws_eks_access_entry`, which makes it impossible to utilize this resource for nodes. fixed it
Relates https://github.com/hashicorp/terraform-provider-aws/pull/35037.

make EKS access entry user_name and type configurable

---

internal/conns/awsclient_gen.go
internal/provider/provider_acc_test.go
internal/service/eks/cluster_auth_data_source.go
internal/service/eks/cluster_auth_data_source_test.go
internal/service/eks/token.go
internal/service/emrcontainers/job_template.go
internal/service/emrcontainers/virtual_cluster.go
names/data/names_data.csv

The AWS SDK for Go v1 STS connection was only used for generating presigned STS URLs for EKS. Updates presigning to use the `sts.PresignClient` for AWS SDK for Go v2.
Also fixes `disappears` tests from `emrcontainers`.
Relates #35333
```console
% make testacc PKG=eks TESTS=TestAccEKSClusterAuthDataSource_
--- PASS: TestAccEKSClusterAuthDataSource_basic (7.78s)
```
```console
% make testacc PKG=batch TESTS=TestAccBatchComputeEnvironment_eksConfiguration
--- PASS: TestAccBatchComputeEnvironment_eksConfiguration (684.76s)
```
```console
% make testacc PKG=emrcontainers
--- PASS: TestAccEMRContainersJobTemplate_disappears (18.71s)
--- PASS: TestAccEMRContainersJobTemplate_basic (22.15s)
--- PASS: TestAccEMRContainersJobTemplate_tags (23.88s)
--- PASS: TestAccEMRContainersVirtualCluster_basic …
```

Remove AWS SDK for Go v1 STS connection

---

website/docs/r/msk_cluster.html.markdown

This PR moves the `storage_mode` attribute from the attributes (read-only) section to the arguments section in the `aws_msk_cluster` resource documentation.
Closes #34579
Cross checked argument spec and description with the [MSK V2 Cluster API documentation](https://docs.aws.amazon.com/MSK/2.0/APIReference/v2-clusters.html#v2-clusters-schemas).
n/a

docs: Move storage_mode to arg list for aws_msk_clsuter

---

internal/service/cognitoidp/managed_user_pool_client.go

Fixes a warning string that previous output a literal `%s` rather than interpolating the ID
Closes #35426
I'm not able to run them at the moment

Fix warning string in `aws_managed_user_pool_client`

---

.changelog/35435.txt
internal/service/ec2/vpc_network_interface_sg_attachment.go
internal/service/ec2/vpc_network_interface_sg_attachment_test.go
website/docs/r/network_interface_sg_attachment.html.markdown

Add configurable timeouts to `aws_network_interface_sg_attachment`.
Closes #35436
```console
% make t T=TestAccVPCNetworkInterfaceSGAttachment_ K=vpc
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 20 -run='TestAccVPCNetworkInterfaceSGAttachment_'  -timeout 360m
=== RUN   TestAccVPCNetworkInterfaceSGAttachment_basic
=== PAUSE TestAccVPCNetworkInterfaceSGAttachment_basic
=== RUN   TestAccVPCNetworkInterfaceSGAttachment_disappears
=== PAUSE TestAccVPCNetworkInterfaceSGAttachment_disappears
=== RUN   TestAccVPCNetworkInterfaceSGAttachment_instance
=== PAUSE TestAccVPCNetworkInterfaceSGAttachment_instance
=== RUN   TestAccVPCNetworkInterfaceSGAttachment_multiple
=== PAUSE …
```

vpc/eni_sg_attach: Add configurable timeouts

---

website/docs/r/eks_access_policy_association.html.markdown

The documentation for importing aws_eks_access_policy_association specifies the wrong id format for the import. It states the id should be `my_cluster_name:my_policy_arn:my_principal_arn` but this causes a validation error:
```
│ Error: unexpected format for ID (<cluster-name>:arn:aws:eks::aws:cluster-access-policy/AmazonEKSViewPolicy:arn:aws:iam::<account-id>:role/<IAM-role), expected cluster-name#principal-arn#policy-arn
```
Looking at the code [here](https://github.com/hashicorp/terraform-provider-aws/blob/43bd19db00807459b8c5ae3b4faaa91a183d3a7f/internal/service/eks/access_policy_association.go#L186)
```go
const accessPolicyAssociationResourceIDSeparator = "#"
func accessPolicyAssociationCreateResourceID(clusterName, principalARN, policyARN string) string {
parts := …
```

Fix Docs for importing eks_access_policy_association

---

internal/service/synthetics/canary_test.go
internal/service/synthetics/group_association.go

```
=== RUN   TestAccSyntheticsCanary_runEnvironmentVariables
=== PAUSE TestAccSyntheticsCanary_runEnvironmentVariables
=== CONT  TestAccSyntheticsCanary_runEnvironmentVariables
canary_test.go:406: Step 1/3 error: Error running apply: exit status 1
Error: creating Synthetics Canary (tf-acc-test-29hhqw9j): ValidationException: Deprecated runtime version specified.
with aws_synthetics_canary.test,
on terraform_plugin_test.tf line 115, in resource "aws_synthetics_canary" "test":
115: resource "aws_synthetics_canary" "test" {
--- FAIL: TestAccSyntheticsCanary_runEnvironmentVariables (62.59s)
FAIL
```
```console
% make testacc TESTARGS="-run=TestAccSynthetics" PKG=synthetics …
```

Synthetics service: fix various failing tests

---

website/docs/r/quicksight_account_subscription.html.markdown

Updates the list of accepted values for `authentication_method` to include the recently added `IAM_IDENTITY_CENTER`. This has been a valid option since 5.27.0 (see references for details)
Closes #34801
Closes #34509
- [SDK PR that added the functionality](https://github.com/aws/aws-sdk-go/pull/5082)
- [AWS SDK version bumped via this PR to the provider](https://github.com/hashicorp/terraform-provider-aws/pull/34563)
- [API docs for good measure](https://docs.aws.amazon.com/quicksight/latest/APIReference/API_CreateAccountSubscription.html#QS-CreateAccountSubscription-request-AuthenticationMethod)
N/a, docs

Update list of valid auth methods for `aws_quicksight_account_subscription`

---

website/docs/r/quicksight_iam_policy_assignment.html.markdown

Updates the `aws_quicksight_iam_policy_assignment` to:
- Fix a typo in `identities.group`
- Correct an issue where the header links are broken due to a collision
Closes #34485
[Schema](https://github.com/hashicorp/terraform-provider-aws/blob/43bd19db00807459b8c5ae3b4faaa91a183d3a7f/internal/service/quicksight/iam_policy_assignment.go#L106)
N/a, docs

Update `aws_quicksight_iam_policy_assignment` documentation

---

website/docs/r/route53domains_registered_domain.html.markdown

Clarifies `aws_route53domains_registered_domain` docs by adding headers for child block sections.
Closes #35219
N/a, docs

Refresh `aws_route53domains_registered_domain` documentation

---

.changelog/35300.txt
internal/service/fis/experiment_template.go
website/docs/r/fis_experiment_template.html.markdown

Add all remaining action targets supported by AWS FIS service:
- Auto Scaling groups – Amazon EC2 Auto Scaling groups
- Buckets – Amazon S3 buckets
- Encrypted global tables – Amazon DynamoDB; global tables encrypted with a customer managed key
- ReplicationGroups – ElastiCache Redis Replication Groups
- TransitGateways – Transit gateways
Closes #35299
[AWS FIS - Action targets](https://docs.aws.amazon.com/fis/latest/userguide/actions.html#action-targets)
```console
% make testacc TESTARGS="-run=TestAccFISExperimentTemplate_basic" PKG=fis
TF_ACC=1 go test ./internal/service/fis/... -v -count 1 -parallel 20  -run=TestAccFISExperimentTemplate_basic -timeout 360m
=== RUN   TestAccFISExperimentTemplate_basic
=== PAUSE TestAccFISExperimentTemplate_basic
=== CONT …
```

r/aws_fis_experiment_template: Add all supported action targets

---

website/docs/r/sns_sms_preferences.html.markdown

I was very confused when attempting to import an existing resource, since there was no Import section [in the docs](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sns_sms_preferences).
So I just tried an apply, and it seemed to work. This PR adds a note to the documentation if/when somebody else runs into a similar situation and is confused that the resource docs don't say anything about importing.
[docs page that led to this PR](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sns_sms_preferences)

add note about what to do with existing resources

---

website/docs/r/eks_access_policy_association.html.markdown

Corrects the example in `aws_eks_access_policy_association` to correctly show `access_scope` as a block rather than a map. Also breaks arguments within child blocks out to headers to be more consistent with other documentation.
Closes #35459
- [AWS API docs](https://docs.aws.amazon.com/eks/latest/APIReference/API_AssociateAccessPolicy.html)
- [Schema reference](https://github.com/hashicorp/terraform-provider-aws/blob/73bd1c7ecb6b791a1e09da2b2cff15bdcd77bf4b/internal/service/eks/access_policy_association.go#L45-L68)
N/a, docs

Correct `aws_eks_access_policy_association` example

---

website/docs/r/sagemaker_domain.html.markdown

Updates `aws_sagemaker_domain` documentation to ensure all arguments are documented, and that headers aren't formatted in a way that break anchor links
Closes #35434
- [Schema](https://github.com/hashicorp/terraform-provider-aws/blob/73bd1c7ecb6b791a1e09da2b2cff15bdcd77bf4b/internal/service/sagemaker/domain.go#L40-L999)
- [AWS API docs for phrasing](https://docs.aws.amazon.com/sagemaker/latest/APIReference/API_UserSettings.html#sagemaker-Type-UserSettings-JupyterLabAppSettings)
N/a, docs

Update `aws_sagemaker_domain` documentation

---

internal/service/ec2/ec2_capacity_reservation.go
internal/service/ec2/ec2_fleet.go
internal/service/ec2/ec2_instance.go
internal/service/ec2/errors.go
internal/service/ec2/service_package_gen.go
internal/service/ec2/verifiedaccess_endpoint.go
internal/service/ec2/verifiedaccess_group.go
internal/service/ec2/verifiedaccess_trust_provider.go
internal/service/ec2/vpc_endpoint_connection_notification.go
internal/service/ec2/vpc_endpoint_service.go
internal/service/ec2/vpc_managed_prefix_list.go
internal/service/ec2/vpc_network_acl.go
internal/service/ec2/vpc_network_insights_path.go
internal/service/ec2/vpc_route_table.go
internal/service/ec2/vpc_traffic_mirror_filter.go
internal/service/ec2/vpc_traffic_mirror_filter_rule.go
internal/service/ec2/vpc_traffic_mirror_session.go
internal/service/ec2/vpc_traffic_mirror_target.go
internal/service/ec2/vpnclient_authorization_rule.go
internal/service/ec2/vpnclient_endpoint.go
internal/service/ec2/vpnclient_network_association.go
internal/service/ec2/vpnclient_route.go
internal/service/ec2/wavelength_carrier_gateway.go

Add `ClientToken` to all EC2 API methods that support it.
Closes https://github.com/hashicorp/terraform-provider-aws/issues/35489.
```console
% make testacc TESTARGS='-run=TestAccVPCRouteTable_basic\|TestAccVPCEndpointConnectionNotification_basic\|TestAccVPCEndpointService_basic\|TestAccVPCNetworkACL_basic\|TestAccWavelengthCarrierGateway_basic\|TestAccVPCManagedPrefixList_basic\|TestAccVPCTrafficMirrorFilterRule_basic' PKG=ec2 ACCTEST_PARALLELISM=3
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 3  -run=TestAccVPCRouteTable_basic\|TestAccVPCEndpointConnectionNotification_basic\|TestAccVPCEndpointService_basic\|TestAccVPCNetworkACL_basic\|TestAccWavelengthCarrierGateway_basic\|TestAccVPCManagedPrefixList_basic\|Te …
```

EC2: Make additional (mainly `Create`) API calls idempotent

---

website/docs/r/iot_topic_rule.html.markdown

This PR renames the IAM resources in the usage example of the `aws_iot_topic_rule` resource for better consistency. I also noticed that the resource description is missing, so I added that in as well.
Closes #27234
Referenced [Granting an AWS IoT rule the access it requires](https://docs.aws.amazon.com/iot/latest/developerguide/iot-create-role.html) in the AWS IoT Developer Guide.
n/a

docs: Rename IAM resource names for clarity in aws_iot_topic_rule example

---

.changelog/35535.txt
internal/service/eks/access_entry.go
internal/service/eks/access_entry_test.go

If an EKS Access Entry is made in the same Terraform apply as the IAM role associated with it, it may fail due to eventual consistency with IAM. This PR adds a retry to handle this case.
The existing tests would not have triggered this as the IAM role resource did not depend on the cluster resource, so the role would have been made early, with plenty of time for consistency to catch up by the time the cluster was ready to accept access entry resources.
N/A
N/A
```console
% make testacc TESTS=TestAccEKSAccessEntry_eventualConsistency PKG=eks
TF_ACC=1 go test ./internal/service/eks/... -v -count 1 -parallel 20 -run='TestAccEKSAccessEntry_eventualConsistency'  -timeout 360m
=== RUN   TestAccEKSAccessEntry_eventualConsistency
=== …
```

fix: add iam retry to eks access entry

---

go.mod
go.sum
internal/conns/awsclient_gen.go
internal/service/codegurureviewer/exports_test.go
internal/service/codegurureviewer/generate.go
internal/service/codegurureviewer/list_pages.go
internal/service/codegurureviewer/repository_association.go
internal/service/codegurureviewer/repository_association_test.go
internal/service/codegurureviewer/service_package_gen.go
internal/service/codegurureviewer/sweep.go
internal/service/codegurureviewer/tags_gen.go
names/data/names_data.csv
names/names.go

Ibid.
Relates https://github.com/hashicorp/terraform-provider-aws/issues/32976.
```console
% make testacc TESTARGS='-run=TestAccCodeGuruReviewerRepositoryAssociation_' PKG=codegurureviewer ACCTEST_PARALLELISM=2
TF_ACC=1 go test ./internal/service/codegurureviewer/... -v -count 1 -parallel 2  -run=TestAccCodeGuruReviewerRepositoryAssociation_ -timeout 360m
=== RUN   TestAccCodeGuruReviewerRepositoryAssociation_basic
=== PAUSE TestAccCodeGuruReviewerRepositoryAssociation_basic
=== RUN   TestAccCodeGuruReviewerRepositoryAssociation_KMSKey
=== PAUSE TestAccCodeGuruReviewerRepositoryAssociation_KMSKey
=== RUN   TestAccCodeGuruReviewerRepositoryAssociation_S3Repository
=== PAUSE TestAccCodeGuruReviewerRepositoryAssociation_S3Repository …
```

Tech debt: Migrate `codegurureviewer` resources to AWS SDK for Go v2

---

.changelog/35521.txt
internal/service/wafv2/flex.go
internal/service/wafv2/rule_group_test.go
internal/service/wafv2/schemas.go
internal/service/wafv2/web_acl_test.go
website/docs/r/wafv2_rule_group.html.markdown
website/docs/r/wafv2_web_acl.html.markdown

This PR is to add support for the `header_order` field to match for `aws_wafv2_rule_group` and `aws_wafv2_web_acl` rules.
Closes #35377
Referenced [Request component options](https://docs.aws.amazon.com/waf/latest/developerguide/waf-rule-statement-fields-list.html#waf-rule-statement-request-component-header-order) for details about the feature, and [CreateRuleGroup](https://docs.aws.amazon.com/waf/latest/APIReference/API_CreateRuleGroup.html) and other pages in the API reference to confirm syntax and behavior.
Tests for `aws_wafv2_rule_group`:
```console
$ make testacc TESTS=TestAccWAFV2RuleGroup_ PKG=wafv2
TF_ACC=1 go test ./internal/service/wafv2/... -v -count 1 -parallel 20 -run='TestAccWAFV2RuleGroup_'  -timeout 360m
=== RUN …
```

feat: Add header_order field support to aws_wafv2_webacl and rule_group

---

.changelog/35509.txt
internal/service/redshiftserverless/endpoint_access.go
internal/service/redshiftserverless/endpoint_access_test.go
internal/service/redshiftserverless/service_package_gen.go
website/docs/r/redshiftserverless_endpoint_access.html.markdown

I have added owner_account component to endpoint_access in redshiftserverless.
Closes #35347
Added component - 
https://github.com/aws/aws-sdk-go/blob/main/service/redshiftserverless/api.go#L6057 
There is no way to get OwnerAccount from redshiftserverless AWS API -
https://docs.aws.amazon.com/redshift-serverless/latest/APIReference/API_GetEndpointAccess.html#API_GetEndpointAccess_ResponseElements 
```console
% make testacc TESTS=redshiftserverless_test PKG=redshiftserverless
...
```

Adding owneraccount component to endpointaccess from redshiftserverless

---

website/docs/r/lakeformation_permissions.html.markdown

This PR fixes the permissions attribute in the example usage for LF S3 resource. Only DATA_LOCATION_ACCESS is allowed.
Closes #33751
Referred to [Granting data location permissions](https://docs.aws.amazon.com/lake-formation/latest/dg/granting-location-permissions.html) in the LF Developer Guide to confirm options.
n/a

docs: Fix S3 example for aws_lakeformation_permissions resource

---

website/docs/r/instance.html.markdown

This PR is to add the missing `id` attribute to the `aws_instance` resource documentation. I double checked the resource state to make sure that `id` is indeed set to the instance ID after creation.
Closes #27286
n/a
n/a

docs: Add missing id attr for aws_instance resource

---

.changelog/35486.txt
internal/service/sesv2/email_identity_policy.go
internal/service/sesv2/email_identity_policy_test.go
internal/service/sesv2/service_package_gen.go
website/docs/r/sesv2_email_identity_policy.html.markdown

This PR introduces a new `aws_sesv2_email_identity_policy` resource.
https://docs.aws.amazon.com/ses/latest/APIReference-V2/API_CreateEmailIdentityPolicy.html
https://docs.aws.amazon.com/ses/latest/APIReference-V2/API_DeleteEmailIdentityPolicy.html
https://docs.aws.amazon.com/ses/latest/APIReference-V2/API_GetEmailIdentityPolicies.html
https://docs.aws.amazon.com/ses/latest/APIReference-V2/API_UpdateEmailIdentityPolicy.html
```console
% make testacc TESTARGS="-run=TestAccSESV2EmailIdentityPolicy_" PKG=sesv2
TF_ACC=1 go test ./internal/service/sesv2/... -v -count 1 -parallel 20  -run=TestAccSESV2EmailIdentityPolicy_ -timeout 360m
=== RUN   TestAccSESV2EmailIdentityPolicy_basic
=== PAUSE …
```

r/aws_sesv2_email_identity_policy: new resource

---

.changelog/35508.txt
internal/service/redshift/cluster.go
internal/service/redshift/cluster_data_source.go
internal/service/redshift/cluster_data_source_test.go
internal/service/redshift/cluster_test.go
internal/service/redshift/service_package_gen.go
website/docs/d/redshift_cluster.html.markdown
website/docs/r/redshift_cluster.html.markdown

Add supports for the multi_az configuration for Redshift cluster.
Closes #34926 
Closes #32180
https://docs.aws.amazon.com/redshift/latest/mgmt/using-multi-az.html
```console
make testacc TESTS=TestAccRedshiftCluster_basic PKG=redshift
TF_ACC=1 go test ./internal/service/redshift/... -v -count 1 -parallel 20 -run='TestAccRedshiftCluster_basic'  -timeout 360m
=== RUN   TestAccRedshiftCluster_basic
=== PAUSE TestAccRedshiftCluster_basic
=== CONT  TestAccRedshiftCluster_basic
--- PASS: TestAccRedshiftCluster_basic (154.65s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/redshift	180.059s
```
```console
make testacc TESTS=TestAccRedshiftCluster_multiAZ PKG=redshift …
```

redshift/cluster: Add multi_az configuration

---

.changelog/35555.txt
internal/framework/flex/autoflex.go
internal/service/lexv2models/exports_test.go
internal/service/lexv2models/service_package_gen.go
internal/service/lexv2models/slot_type.go
internal/service/lexv2models/slot_type_test.go
website/docs/r/lexv2models_slot_type.html.markdown

New resource LexV2Models `slot_type` 
```console
> make testacc TESTS=TestAccLexV2ModelsSlotType_ PKG=lexv2models
TF_ACC=1 go test ./internal/service/lexv2models/... -v -count 1 -parallel 20 -run='TestAccLexV2ModelsSlotType_'  -timeout 360m
=== RUN   TestAccLexV2ModelsSlotType_basic
=== PAUSE TestAccLexV2ModelsSlotType_basic
=== RUN   TestAccLexV2ModelsSlotType_disappears
=== PAUSE TestAccLexV2ModelsSlotType_disappears
=== CONT  TestAccLexV2ModelsSlotType_basic
=== CONT  TestAccLexV2ModelsSlotType_disappears
--- PASS: TestAccLexV2ModelsSlotType_disappears (37.69s)
--- PASS: TestAccLexV2ModelsSlotType_basic (56.21s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/lexv2models        62.650s
...
```

New Resource slot_type

---

.changelog/35501.txt
internal/service/cognitoidp/consts.go
internal/service/cognitoidp/exports_test.go
internal/service/cognitoidp/service_package_gen.go
internal/service/cognitoidp/user_group.go
internal/service/cognitoidp/user_group_test.go

FIx issue when import cognito user group contains "/".
Closes #35491

fix #35491

---

website/docs/d/codestarconnections_connection.html.markdown
website/docs/r/codestarconnections_connection.html.markdown

Adding `Gitlab` and `GitLabSelfManaged` as they are now supported in the SDK https://docs.aws.amazon.com/sdk-for-go/api/service/codestarconnections/#pkg-constants
Just confirmed using `hashicorp/aws v5.34.0` with an invalid `provider_type` (to check the SDK complaining and showing the available types):
```terraform
resource "aws_codestarconnections_connection" "example" {
name          = "example-connection"
provider_type = "LabGit"
}
```
```shell
nicosingh@nicomac test-codestar % terraform plan
╷
│ Error: expected provider_type to be one of ["Bitbucket" "GitHub" "GitHubEnterpriseServer" "GitLab" "GitLabSelfManaged"], got LabGit
│
│   with aws_codestarconnections_connection.example,
│   on main.tf line 3, in resource "aws_codestarconnections_connection" "example":
│    3:   provider_type …
```

docs: update codestarconnections_connection supported provider_type values

---

.changelog/35585.txt
internal/service/networkmanager/core_network_policy_document_data_source.go

Removing the `MaxItems` limit for `edge_locations` under the `aws_networkmanager_core_network_policy_document` data source. There are more than 17 regions supported today by AWS Cloud WAN, so this limit prevents users from defining all supported regions.
I did not find any public documentation or discussion pointing to why this limit was initially added.
Closes #35404
```console
$ make testacc TESTS=TestAccNetworkManagerCoreNetworkPolicyDocumentDataSource_basic PKG=networkmanager
TF_ACC=1 go test ./internal/service/networkmanager/... -v -count 1 -parallel 20 -run='TestAccNetworkManagerCoreNetworkPolicyDocumentDataSource_basic'  -timeout 360m
=== RUN   TestAccNetworkManagerCoreNetworkPolicyDocumentDataSource_basic
=== PAUSE …
```

fix: Remove MaxItems limitation for `aws_networkmanager_core_network_policy_document` edge_locations

---

internal/service/rekognition/collection.go
website/docs/r/rekognition_collection.html.markdown

Add retry during create when resource is not found.
Relates #35407
```console
% make testacc TESTARGS="-run=TestAccRekognitionCollection_" PKG=rekognition
TF_ACC=1 go test ./internal/service/rekognition/... -v -count 1 -parallel 20  -run=TestAccRekognitionCollection_ -timeout 360m
--- PASS: TestAccRekognitionCollection_disappears (11.65s)
--- PASS: TestAccRekognitionCollection_basic (12.64s)
--- PASS: TestAccRekognitionCollection_tags (23.40s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/rekognition	30.406s
```

r/aws_rekognition_collection: retry on create

---

.changelog/35606.txt
internal/service/ssm/default_patch_baseline.go
internal/service/ssm/exports_test.go
internal/service/ssm/patch_baseline.go
internal/service/ssm/patch_baseline_test.go
internal/service/ssm/service_package_gen.go
internal/service/ssm/sweep.go

https://github.com/hashicorp/terraform-provider-aws/issues/33565 introduced a bug where the json value was not recalculated when the configuration changed. This PR address this. And adds a test to prevent a regression next time
Relates #33565 
```console
% ❯ make testacc TESTS=TestAccSSMPatchBaseline_basic PKG=ssm
TF_ACC=1 go test ./internal/service/ssm/... -v -count 1 -parallel 20 -run='TestAccSSMPatchBaseline_basic'  -timeout 360m
=== RUN   TestAccSSMPatchBaseline_basic
=== PAUSE TestAccSSMPatchBaseline_basic
=== CONT  TestAccSSMPatchBaseline_basic
--- PASS: TestAccSSMPatchBaseline_basic (18.35s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/ssm        18.456s
...
```

B fix ssm patching manager to set computed value as new

---

go.mod
go.sum
internal/conns/awsclient_gen.go
internal/service/lexv2models/generate.go
internal/service/lexv2models/tags_gen.go
internal/service/synthetics/canary.go
internal/service/synthetics/canary_test.go
internal/service/synthetics/find.go
internal/service/synthetics/generate.go
internal/service/synthetics/group.go
internal/service/synthetics/group_association.go
internal/service/synthetics/group_association_test.go
internal/service/synthetics/group_test.go
internal/service/synthetics/retry.go
internal/service/synthetics/service_endpoints_gen_test.go
internal/service/synthetics/service_package_gen.go
internal/service/synthetics/status.go
internal/service/synthetics/sweep.go
internal/service/synthetics/tags_gen.go
internal/service/synthetics/wait.go
names/data/names_data.csv
names/names.go

Relates #32976
```console
% make testacc TESTARGS="-run=TestAccSynthetics" PKG=synthetics
TF_ACC=1 go test ./internal/service/synthetics/... -v -count 1 -parallel 20  -run=TestAccSynthetics -timeout 360m
--- PASS: TestAccSyntheticsGroup_disappears (15.82s)
--- PASS: TestAccSyntheticsGroup_basic (17.69s)
--- PASS: TestAccSyntheticsGroup_tags (31.50s)
--- PASS: TestAccSyntheticsGroupAssociation_disappears (59.94s)
--- PASS: TestAccSyntheticsCanary_s3 (62.23s)
--- PASS: TestAccSyntheticsCanary_artifactEncryption (65.36s)
--- PASS: TestAccSyntheticsCanary_disappears (65.90s)
--- PASS: TestAccSyntheticsCanary_runTracing (66.15s)
--- PASS: TestAccSyntheticsGroupAssociation_basic (68.31s)
--- PASS: …
```

Tech Debt: `synthetics` service to AWS Go SDKv2

---

website/docs/r/cognito_resource_server.html.markdown

This PR adds the required field `user_pool_id` to the `aws_cognito_resource_server` resource docs for enhanced clarity and alignment.
- **Clarity Improvement:**
The inclusion of `user_pool_id` offers explicit configuration guidance, reducing implementation confusion.
- **Alignment:**
Requiring `user_pool_id` aligns with standard AWS resource practices.
Closes #0000
https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/cognito-idp/client/create_resource_server.html

Enhancing Documentation for aws_cognito_resource_server with Required Field - user_pool_id

---

website/docs/d/opensearch_domain.html.markdown
website/docs/r/opensearch_domain.html.markdown

This PR adds the missing `multi_az_with_standby_enabled` description to the doc for the `aws_opensearch_domain` resource and data source.
Closes #35578
Referred to [ClusterConfig](https://docs.aws.amazon.com/opensearch-service/latest/APIReference/API_ClusterConfig.html#opensearchservice-Type-ClusterConfig-MultiAZWithStandbyEnabled) API data model doc for wordings.
n/a

docs: Add missing multi_az_with_standby_enabled attr desc for aws_opensearch_domain

---

website/docs/r/opensearch_domain.html.markdown

This PR replaces the list of valid values for the `tls_security_policy` attribute with a link to the AWS documentation for the `aws_opensearch_domain` resource, so that the list doesn't have to be constantly maintained.
Closes #35580
Referenced the  [AWS documentation](https://docs.aws.amazon.com/opensearch-service/latest/APIReference/API_DomainEndpointOptions.html#opensearchservice-Type-DomainEndpointOptions-TLSSecurityPolicy) in the doc.
n/a

docs: Refer to AWS doc for tls_security_policy valid values for aws_opensearch_domain

---

internal/service/route53domains/registered_domain_test.go

This PR updates the contact emails used for Route53 Registered Domain acceptance tests.
```console
% make testacc TESTS=TestAccXXX PKG=route53domains
...
```

fix(tests): Update Route53 Registered Domain acceptance test emails

---

.markdownlint.yml
docs/design-decisions/rds-bluegreen-deployments.md
internal/service/rds/instance_test.go
website/docs/r/db_instance.html.markdown

Updates documentation to indicate that the `aws_db_instance` field `blue_green_update` cannot be used for low-downtime-updates for DB Instances with replicas.
Closes #33702

Updates documentation around Blue/Green Deployments with DB Instances with replicas

---

website/docs/r/codebuild_project.html.markdown

The resource access role is only applicable to public log access (and isn’t annotated as optional), and the log stream name is actually a prefix.
Clarify the two points mentioned above
N/A
https://docs.aws.amazon.com/codebuild/latest/userguide/change-project-console.html#change-project-console.public-builds
https://docs.aws.amazon.com/codebuild/latest/APIReference/API_UpdateProjectVisibility.html
https://docs.aws.amazon.com/codebuild/latest/APIReference/API_CloudWatchLogsConfig.html
N/A

[docs] CodeBuild Project attribute clarifications

---

go.mod
go.sum
internal/conns/awsclient_gen.go
internal/service/mediastore/container.go
internal/service/mediastore/container_policy.go
internal/service/mediastore/container_policy_test.go
internal/service/mediastore/container_test.go
internal/service/mediastore/exports_test.go
internal/service/mediastore/generate.go
internal/service/mediastore/service_endpoints_gen_test.go
internal/service/mediastore/service_package_gen.go
internal/service/mediastore/tags_gen.go
names/data/names_data.csv
names/names.go

Relates #32976
```console
% make testacc TESTARGS="-run=TestAccMediaStore" PKG=mediastore
TF_ACC=1 go test ./internal/service/mediastore/... -v -count 1 -parallel 20  -run=TestAccMediaStore -timeout 360m
--- PASS: TestAccMediaStoreContainer_disappears (93.62s)
--- PASS: TestAccMediaStoreContainer_tags (105.43s)
--- PASS: TestAccMediaStoreContainerPolicy_basic (107.86s)
--- PASS: TestAccMediaStoreContainerPolicy_disappears (120.30s)
--- PASS: TestAccMediaStoreContainer_basic (121.77s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/mediastore	128.944s
```

Tech Debt: convert mediastore to AWS Go SDKv2

---

.changelog/35671.txt
internal/service/elbv2/listener.go
internal/service/elbv2/listener_certificate_test.go
internal/service/elbv2/listener_data_source.go
internal/service/elbv2/listener_rule.go
internal/service/elbv2/listener_rule_test.go
internal/service/elbv2/listener_test.go
website/docs/r/lb_listener.html.markdown
website/docs/r/lb_listener_rule.html.markdown

The resource types `aws_lb_listener` and `aws_lb_listener_rule` allow specifying forward actions in two ways: if a single target group is used, either the `target_group_arn` or `forward.target_group.arn` can be specified; if multiple target groups are used, multiple `forward.target_group`s can be specified.
However, if a single `forward.target_group` was specified, other settings in the `forward` block were not honoured.
Closes #35621
Closes #35576
Closes #32983
Closes #28083
Closes #22526
Closes #20200
Closes #15144
Closes #14119
```console
% make testacc PKG=elbv2 TESTS=TestAccELBV2Listener_
--- PASS: TestAccELBV2Listener_LoadBalancerARN_gatewayLoadBalancer (163.63s)
--- PASS: TestAccELBV2Listener_Protocol_tls (214.88s)
--- PASS: TestAccELBV2Listener_oidc (219.47s)
--- PASS: …
```

Fixes errors with `target_group_arn` and `forward` for `aws_lb_listener` and `aws_lb_listener_rule`

---

.changelog/35678.txt
internal/service/elbv2/listener.go
internal/service/elbv2/listener_rule.go
internal/service/elbv2/listener_rule_test.go
internal/service/elbv2/listener_test.go

Prior to v5.35.0, invalid parameters for the action `type` were ignored. In order to provide warnings to users in advance of returning errors in v6.0, the invalid configurations were no longer ignored. However, this caused unexpected diffs to be reported for existing `aws_lb_listener` and `aws_lb_listener_rule` resources.
Ignores the invalid configuration again. This means that there will be no warnings about the invalid configuration for users.
Closes #35668
```console
% make testacc PKG=elbv2 TESTS=TestAccELBV2Listener_
--- PASS: TestAccELBV2Listener_forwardTargetARNAndBlock (4.80s)
--- PASS: TestAccELBV2Listener_LoadBalancerARN_gatewayLoadBalancer (167.17s)
--- PASS: TestAccELBV2Listener_Gateway_basic (187.15s)
--- PASS: TestAccELBV2Listener_EmptyDefaultAction (0.00s)
--- PASS: …
```

Fixes unexpected diff for `aws_lb_listener` and `aws_lb_listener_rule`

---

website/docs/r/vpclattice_listener.html.markdown
website/docs/r/vpclattice_service.html.markdown

Some vpc lattice resources were missing `terraform` syntax highlighting
Some vpc lattice attribute descriptions were using template text for descriptions
Closes #35706
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/vpclattice_listener https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/vpclattice_service
N/A -- just updating docs

docs: update vpclattice docs

---

.changelog/35694.txt
internal/service/lambda/function.go
internal/service/lambda/function_test.go

Suppresses incorrect diff on consecutive apply, and maintains existing log levels, when `logging_config.application_log_level` or `logging_config.system_log_level` have not been specified in configuration.
Closes #35301
```console
make testacc 'TESTS=TestAccLambdaFunction(DataSource)?_(basic|loggingConfig)'  PKG=lambda
TF_ACC=1 go test ./internal/service/lambda/... -v -count 1 -parallel 20 -run='TestAccLambdaFunction(DataSource)?_(basic|loggingConfig)'  -timeout 360m
=== RUN   TestAccLambdaFunctionDataSource_basic
=== PAUSE TestAccLambdaFunctionDataSource_basic
=== RUN   TestAccLambdaFunctionDataSource_loggingConfig
=== PAUSE TestAccLambdaFunctionDataSource_loggingConfig
=== RUN   TestAccLambdaFunction_basic
=== PAUSE …
```

Resolve logging_config consecutive diff issue

---

website/docs/r/rds_cluster.html.markdown

The `storage_encrypted` value of RDS Serverless v1 and Serverless v2 is different, which may adversely affect migration. Added warning and example to resolve this.
Closes #35369
https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/aurora-serverless.html
N/A

[Docs] Added help migrating from RDS Serverless v1 to Serverless v2

---

website/docs/r/lexv2models_slot.html.markdown

Currently there is a broken example in the new Lex v2 `aws_lexv2models_slot` example, this corrects that type.

aws_lexv2models_slot - Correct locale_id example to aws_lexv2models_bot_locale

---

website/docs/d/cloudfront_origin_access_identity.html.markdown

Updated description for the `id` attribute of `data.aws_cloudfront_origin_access_identity`. Id should be that of the access identity, not the CLoudfront distribution.
Closes #34416
[Cloudfront Access Control](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/private-content-restricting-access-to-s3.html) (Legacy OAI at the bottom)
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/cloudfront_origin_access_identity

Fixed docs for data.aws_cloudfront_origin_access_identity

---

.changelog/33798.txt
.changelog/35738.txt
internal/service/medialive/channel.go

Relates #33798
```console
% make testacc TESTARGS='-run=TestAccMediaLiveChannel_' PKG=medialive
TF_ACC=1 go test ./internal/service/medialive/... -v -count 1 -parallel 20  -run=TestAccMediaLiveChannel_ -timeout 360m
--- PASS: TestAccMediaLiveChannel_MsSmooth_outputSettings (71.97s)
--- PASS: TestAccMediaLiveChannel_captionDescriptions (88.18s)
--- PASS: TestAccMediaLiveChannel_VideoDescriptions_CodecSettings_h265Settings (107.84s)
--- PASS: TestAccMediaLiveChannel_basic (143.69s)
--- PASS: TestAccMediaLiveChannel_UDP_outputSettings (172.74s)
--- PASS: TestAccMediaLiveChannel_M2TS_settings (213.53s)
--- PASS: TestAccMediaLiveChannel_hls (247.95s)
--- PASS: TestAccMediaLiveChannel_status (266.42s)
--- PASS: …
```

r/medialive_channel: add `client_cache` to HLS group settings

---

.changelog/33798.txt
internal/service/medialive/channel_encoder_settings_schema.go
internal/service/medialive/channel_test.go

Added missing `client_cache` to `expandHLSGroupSettings`.
```console
% make testacc TESTS=TestAccMediaLiveChannel_hls PKG=medialive
TF_ACC=1 go test ./internal/service/medialive/... -v -count 1 -parallel 20 -run='TestAccMediaLiveChannel_hls'  -timeout 360m
=== RUN   TestAccMediaLiveChannel_hls
=== PAUSE TestAccMediaLiveChannel_hls
=== CONT  TestAccMediaLiveChannel_hls
--- PASS: TestAccMediaLiveChannel_hls (67.40s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/medialive	69.526s
...
```

added client_cache to expandHLSGroupSettings

---

go.mod
go.sum
internal/conns/awsclient_gen.go
internal/flex/flex.go
internal/service/cloudsearch/domain.go
internal/service/cloudsearch/domain_service_access_policy.go
internal/service/cloudsearch/domain_service_access_policy_test.go
internal/service/cloudsearch/domain_test.go
internal/service/cloudsearch/exports_test.go
internal/service/cloudsearch/service_endpoints_gen_test.go
internal/service/cloudsearch/service_package_gen.go
internal/service/cloudsearch/sweep.go
names/data/names_data.csv
names/names.go

Ibid.
Relates https://github.com/hashicorp/terraform-provider-aws/issues/32976.
```console
% make testacc TESTARGS='-run=TestAccCloudSearch' PKG=cloudsearch ACCTEST_PARALLELISM=2
TF_ACC=1 go test ./internal/service/cloudsearch/... -v -count 1 -parallel 2  -run=TestAccCloudSearch -timeout 360m
=== RUN   TestAccCloudSearchDomainServiceAccessPolicy_basic
=== PAUSE TestAccCloudSearchDomainServiceAccessPolicy_basic
=== RUN   TestAccCloudSearchDomainServiceAccessPolicy_update
=== PAUSE TestAccCloudSearchDomainServiceAccessPolicy_update
=== RUN   TestAccCloudSearchDomain_basic
=== PAUSE TestAccCloudSearchDomain_basic
=== RUN   TestAccCloudSearchDomain_disappears
=== PAUSE TestAccCloudSearchDomain_disappears
=== RUN …
```

Tech debt: Migrate `cloudsearch` resources to AWS SDK for Go v2

---

docs/acc-test-environment-variables.md
internal/acctest/acctest.go
internal/envvar/envvar.go
internal/experimental/sync/sync.go
internal/service/ec2/find.go
internal/service/ec2/sweep.go
internal/service/ec2/verifiedaccess_endpoint_test.go
internal/service/ec2/verifiedaccess_group_test.go
internal/service/ec2/verifiedaccess_instance.go
internal/service/ec2/verifiedaccess_instance_logging_configuration.go
internal/service/ec2/verifiedaccess_instance_logging_configuration_test.go
internal/service/ec2/verifiedaccess_instance_test.go
internal/service/ec2/verifiedaccess_instance_trust_provider_attachment.go
internal/service/ec2/verifiedaccess_instance_trust_provider_attachment_test.go
internal/service/ec2/verifiedaccess_test.go
internal/service/ec2/verifiedaccess_trust_provider.go
internal/service/ec2/vpnclient_authorization_rule_test.go
internal/service/ec2/vpnclient_endpoint_data_source_test.go
internal/service/ec2/vpnclient_endpoint_test.go
internal/service/ec2/vpnclient_network_association_test.go
internal/service/ec2/vpnclient_route_test.go
internal/service/ec2/vpnclient_test.go

Limits `aws_verifiedaccess_*` acceptance test concurrency using the same mechanism as Client VPN.
Fixes:
```
Error: creating Verified Access Instance: operation error EC2: CreateVerifiedAccessInstance, https response error StatusCode: 400, RequestID: ..., api error VerifiedAccessInstanceLimitExceeded: The number of instances you have are exceeding your current defined limit
```
Closes https://github.com/hashicorp/terraform-provider-aws/issues/33768.
Relates https://github.com/hashicorp/terraform-provider-aws/issues/35747.
```console
% make testacc TESTARGS='-run=TestAccVerifiedAccess_serial' PKG=ec2                 
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 20  -run=TestAccVerifiedAccess_serial -timeout …
```

Verified Access: Limit acceptance test concurrency

---

.ci/scripts/unlabel-on-milestone-closed.sh

When migrating to a separate script in [this commit](https://github.com/hashicorp/terraform-provider-aws/pull/32605/commits/f7fccf41592e76923f204fb3d638095f4a844a29), a typo was introduced that caused the script to remove the `bug` label from all issues/PRs in a milestone (rather than the `prioritized` label) when a milestone was closed. This PR corrects that typo. Separate remediation efforts have already happened to fix the removed labels.
Relates #32605
N/a, workflow/script

Correct issue with unlabel-on-milestone-closed

---

.changelog/35771.txt
internal/service/redshift/data_share_authorization.go
internal/service/redshift/data_share_consumer_association.go
internal/service/redshift/data_share_consumer_association_test.go
internal/service/redshift/exports_test.go
internal/service/redshift/service_package_gen.go
website/docs/r/redshift_data_share_consumer_association.html.markdown

This resource will allow practitioners to manage Redshift data share consumer associations via Terraform.
Also fixes a bug in the `aws_redshift_data_share_authorization` data source that incorrectly handled an `ACTIVE` data share status, causing persistent differences and forced re-creation of the resource.
Closes #33454
Relates #35703 
- https://docs.aws.amazon.com/redshift/latest/APIReference/API_AssociateDataShareConsumer.html
- https://docs.aws.amazon.com/redshift/latest/APIReference/API_DisassociateDataShareConsumer.html
- https://docs.aws.amazon.com/redshift/latest/APIReference/API_DescribeDataShares.html
```console
% make testacc PKG=redshift TESTS=TestAccRedshiftDataShareConsumerAssociation_ …
```

[New Resource]: `aws_redshift_data_share_consumer_association`

---

go.mod
go.sum
internal/conns/awsclient_gen.go
internal/service/cloudfront/service_endpoints_gen_test.go
internal/service/cloudfront/service_package_gen.go
names/data/names_data.csv

Adds AWS SDK for Go v2 for the CloudFront service.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/35663.

cloudfront: Add support for AWS SDK for Go v2

---

website/docs/r/secretsmanager_secret_rotation.html.markdown

Correct wrong default value for rotate_immediatley argument for the resource aws_secretsmanager_secret_rotation.
Closes #35702

[Docs]: Correct default rotate_immediately argument for aws_secretsmanager_secret_rotation

---

.changelog/35774.txt
internal/service/autoscaling/group.go
internal/service/autoscaling/group_test.go

Add computed fields for `version` to fix `inconsistent final plan` issue.
Closes #34543
```console
> make testacc TESTARGS='-run=TestAccAutoScalingGroup_LaunchTemplate_\|TestAccAutoScalingGroup_basic\|TestAccAutoScalingGroup_MixedInstancesPolicyLaunchTemplate' PKG=autoscaling
TF_ACC=1 go test ./internal/service/autoscaling/... -v -count 1 -parallel 20  -run=TestAccAutoScalingGroup_LaunchTemplate_\|TestAccAutoScalingGroup_basic\|TestAccAutoScalingGroup_MixedInstancesPolicyLaunchTemplate -timeout 360m
=== RUN   TestAccAutoScalingGroup_basic
=== PAUSE TestAccAutoScalingGroup_basic
=== RUN   TestAccAutoScalingGroup_LaunchTemplate_update
=== PAUSE TestAccAutoScalingGroup_LaunchTemplate_update
=== RUN …
```

Fix launch template bug with versions

---

.changelog/34753.txt
internal/service/ram/resource_share_accepter.go

When a RAM resource share invitation from another account is accepted, there will be a slight delay until the resource share can be found. This PR adds wait for the delay.
Closes #33701
With AWS_PROFILE env variable:
```console
% make testacc TESTS=TestAccRAMResourceShareAccepter PKG=ram
TF_ACC=1 go test ./internal/service/ram/... -v -count 1 -parallel 20 -run='TestAccRAMResourceShareAccepter'  -timeout 360m
=== RUN   TestAccRAMResourceShareAccepter_basic
=== PAUSE TestAccRAMResourceShareAccepter_basic
=== RUN   TestAccRAMResourceShareAccepter_disappears
=== PAUSE TestAccRAMResourceShareAccepter_disappears
=== RUN   TestAccRAMResourceShareAccepter_resourceAssociation
=== PAUSE TestAccRAMResourceShareAccepter_resourceAssociation …
```

fix: Wait until RAM resource share available after accepting the invitation

---

.changelog/35775.txt
internal/service/s3/bucket_acl.go
internal/service/s3/bucket_acl_test.go
internal/service/s3/bucket_analytics_configuration_test.go
internal/service/s3/bucket_cors_configuration_test.go
internal/service/s3/bucket_lifecycle_configuration_test.go
internal/service/s3/bucket_server_side_encryption_configuration_test.go
website/docs/r/s3_bucket_acl.html.markdown

Fixes bugs or acceptance test errors in various S3 bucket configuration resources:
* `aws_s3_bucket_acl`
* `aws_s3_bucket_analytics_configuration`
* `aws_s3_bucket_cors_configuration`
* `aws_s3_bucket_lifecycle_configuration`
* `aws_s3_bucket_server_side_encryption_configuration`
```console
% make testacc PKG=s3 TESTS=TestAccS3BucketACL_
--- PASS: TestAccS3BucketACL_directoryBucket (12.46s)
--- PASS: TestAccS3BucketACL_disappears (17.78s)
--- PASS: TestAccS3BucketACL_basic (21.57s)
--- PASS: TestAccS3BucketACL_migrate_aclNoChange (27.91s)
--- PASS: TestAccS3BucketACL_migrate_grantsWithChange (28.14s)
--- PASS: TestAccS3BucketACL_migrate_aclWithChange (30.32s)
--- PASS: TestAccS3BucketACL_grantToACL (31.11s)
--- PASS: TestAccS3BucketACL_ACLToGrant (31.31s)
--- PASS: …
```

Fix assorted S3 bucket configuration resources

---

.changelog/35744.txt
internal/service/route53resolver/rule.go
internal/service/route53resolver/rule_test.go

`target_ip.protocol` parameter added to select a `protocol` for multiprotocol endpoints.
Closes #35733
#35098
```console
% make testacc TESTS=TestAccRoute53ResolverRule_forward PKG=route53resolver
TF_ACC=1 go test ./internal/service/route53resolver/... -v -count 1 -parallel 20 -run='TestAccRoute53ResolverRule_forwardMultiProtocol'  -timeout 360m
=== RUN   TestAccRoute53ResolverRule_forward
=== PAUSE TestAccRoute53ResolverRule_forward
=== RUN   TestAccRoute53ResolverRule_forwardMultiProtocol
=== PAUSE TestAccRoute53ResolverRule_forwardMultiProtocol
=== RUN   TestAccRoute53ResolverRule_forwardEndpointRecreate
=== PAUSE TestAccRoute53ResolverRule_forwardEndpointRecreate
=== CONT  TestAccRoute53ResolverRule_forward
=== CONT …
```

`r/aws_route53_resolver_rule`: add `protocols`

---

.changelog/35800.txt
internal/service/ram/resource_share_accepter.go

Previously, resource shares left out-of-band would result in the terraform destroy operation failing with an UnknownResourceException indicating the share could not be found. Nowthis error will be appropriately ignored allowing destroy to exit cleanly.
Before:
```console
% AWS_ALTERNATE_PROFILE=foo make testacc TESTS=TestAccRAMResourceShareAccepter_disappears PKG=ram
TF_ACC=1 go test ./internal/service/ram/... -v -count 1 -parallel 20 -run='TestAccRAMResourceShareAccepter_disappears'  -timeout 360m
=== RUN   TestAccRAMResourceShareAccepter_disappears
=== PAUSE TestAccRAMResourceShareAccepter_disappears
=== CONT  TestAccRAMResourceShareAccepter_disappears
testing_new.go:91: Error running post-test destroy, there may be dangling …
```

r/aws_ram_resource_share_accepter: handle out-of-band resource deletion

---

.changelog/35799.txt
internal/service/glue/catalog_database.go
internal/service/glue/catalog_database_test.go
internal/service/lakeformation/resource.go
website/docs/r/glue_catalog_database.html.markdown

The `federated_database` argument will allow practitioners to configure a glue database referencing a federated database entity outside the AWS Glue Data Catalog.
Also addresses a bug with `aws_lakeformation_resource` where the `use_service_linked_role` was being ignored when explicitly configured to `false`.
Closes #33453
Relates #35703 
Relates #35771 
- https://docs.aws.amazon.com/redshift/latest/dg/r_CREATE_DATASHARE.html
- https://docs.aws.amazon.com/lake-formation/latest/dg/setup-ds-perms.html
```console
% make testacc PKG=glue TESTS=TestAccGlueCatalogDatabase_federatedDatabase
TF_ACC=1 go test ./internal/service/glue/... -v -count 1 -parallel 20 -run='TestAccGlueCatalogDatabase_federatedDatabase'  -timeout 360m
=== RUN …
```

r/aws_glue_catalog_database: add `federated_database` argument

---

.changelog/35778.txt
internal/service/datasync/task.go
website/docs/r/datasync_task.html.markdown

This fixes 2 bugs:
- One could cause a complete plugin crash due to accessing an uninitialized object in the AWS read response
- This would occur in the `flattenTaskReportConfigReportOverrides` method
- Leaving a `report_override` property blank could cause empty quotes to be sent in certain circumstances
- This would cause validation failures on the AWS side, preventing the resource from being created.
- This would occur in the `expandTaskReportOverrides` method
A third change was made in the docs to highlight how setting `report_override` to the same value as the report default would cause changes to always be detected.

Fix bug in `aws_datasync_task`

---

internal/service/shield/drt_access_log_bucket_association_test.go
internal/service/shield/drt_access_role_arn_association.go
internal/service/shield/drt_access_role_arn_association_test.go
internal/service/shield/protection_group_test.go
internal/service/shield/shield_test.go

```
=== RUN   TestAccShieldDRTAccessLogBucketAssociation_basic
drt_access_log_bucket_association_test.go:35: Step 1/1 error: Error running apply: exit status 1
Error: creating AWS Shield DRT Access Log Bucket Association ("tf-acc-test-1909124837205883387"): OptimisticLockException: Resource has been modified by another client. Please retry
```
```console
% AWS_DEFAULT_REGION=us-east-1 make testacc TESTARGS='-run=TestAccShield' PKG=shield
TF_ACC=1 go test ./internal/service/shield/... -v -count 1 -parallel 20  -run=TestAccShield -timeout 360m
--- PASS: TestAccShieldProtectionGroup_disappears (20.64s)
--- PASS: TestAccShieldProtection_disappears (22.74s)
--- PASS: …
```

td/shield: fix various tests

---

go.mod
go.sum
internal/conns/awsclient_gen.go
internal/service/shield/application_layer_automatic_response.go
internal/service/shield/application_layer_automatic_response_test.go
internal/service/shield/drt_access_log_bucket_association.go
internal/service/shield/drt_access_log_bucket_association_test.go
internal/service/shield/drt_access_role_arn_association.go
internal/service/shield/drt_access_role_arn_association_test.go
internal/service/shield/generate.go
internal/service/shield/protection.go
internal/service/shield/protection_group.go
internal/service/shield/protection_group_test.go
internal/service/shield/protection_health_check_association.go
internal/service/shield/protection_health_check_association_test.go
internal/service/shield/protection_test.go
internal/service/shield/service_endpoints_gen_test.go
internal/service/shield/service_package.go
internal/service/shield/service_package_gen.go
internal/service/shield/tags_gen.go
names/data/names_data.csv
names/names.go

Relates #32976
```console
% AWS_DEFAULT_REGION=us-east-1 make testacc TESTARGS='-run=TestAccShield' PKG=shield
TF_ACC=1 go test ./internal/service/shield/... -v -count 1 -parallel 20  -run=TestAccShield -timeout 360m
--- PASS: TestAccShieldProtectionGroup_disappears (20.00s)
--- PASS: TestAccShieldProtection_disappears (21.74s)
--- PASS: TestAccShieldProtectionHealthCheckAssociation_disappears (23.31s)
--- PASS: TestAccShieldProtection_elasticIPAddress (35.05s)
--- PASS: TestAccShieldProtectionGroup_members (40.88s)
--- PASS: TestAccShieldProtection_elb (42.01s)
--- PASS: TestAccShieldProtectionGroup_basic (48.32s)
--- PASS: TestAccShieldProtectionGroup_tags (56.18s)
--- PASS: TestAccShieldProtectionGroup_protectionGroupID …
```

Tech Debt: migrate `shield` resources to AWS SDK for Go v2

---

.changelog/35844.txt
internal/service/amp/scraper.go
internal/service/amp/scraper_test.go

When updating `tags` on `aws_prometheus_scraper`, the apply fails with the error
> Provider returned invalid result object after apply
```console
% make testacc PKG=amp TESTS=TestAccAMPScraper_
--- PASS: TestAccAMPScraper_securityGroups (2005.56s)
--- PASS: TestAccAMPScraper_disappears (2053.51s)
--- PASS: TestAccAMPScraper_basic (2053.55s)
--- PASS: TestAccAMPScraper_alias (2188.96s)
--- PASS: TestAccAMPScraper_tags (2205.76s)
```

resource/aws_prometheus_scraper: Fix `Provider returned invalid result object after apply` error

---

.changelog/35840.txt
internal/service/ec2/ec2_instance_type_data_source.go
internal/service/ec2/ec2_instance_type_data_source_test.go
website/docs/d/ec2_instance_type.html.markdown

- Add attribute for `maximum_network_cards` to the `aws_ec2_instance_type` data source. This is used to show the max number of EFA devices that can be exposed on EFA supported instance types
```console
make testacc TESTS="TestAccEC2InstanceTypeDataSource_" PKG=ec2                 
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 20 -run='TestAccEC2InstanceTypeDataSource_'  -timeout 360m
=== RUN   TestAccEC2InstanceTypeDataSource_basic
=== PAUSE TestAccEC2InstanceTypeDataSource_basic
=== RUN   TestAccEC2InstanceTypeDataSource_metal
=== PAUSE TestAccEC2InstanceTypeDataSource_metal
=== RUN   TestAccEC2InstanceTypeDataSource_gpu
=== PAUSE TestAccEC2InstanceTypeDataSource_gpu
=== RUN …
```

d/aws_ec2_instance_type maximum_network_cards

---

.changelog/35720.txt
internal/service/redshiftserverless/workgroup.go
internal/service/redshiftserverless/workgroup_test.go
website/docs/r/redshiftserverless_workgroup.html.markdown

Adds max_capacity argument to aws_redshiftserverless_workgroup resource allowing for better control of workgroup scale-out hence costs.
Closes #35719
Closes #34440
Maximum capacity setting is described in [AWS docs here](https://docs.aws.amazon.com/redshift/latest/mgmt/serverless-billing.html)
```console
% make testacc TESTS=TestAccRedshiftServerlessWorkgroup_baseAndMaxCapacityAndPubliclyAccessible PKG=redshiftserverless
```

r/aws_redshiftserverless_workgroup: Add max_capacity argument

---

.changelog/35860.txt
internal/service/sts/caller_identity_data_source_test.go
internal/service/sts/service_package.go

Error: `SignatureDoesNotMatch: Credential should be scoped to a valid region.`
```console
% AWS_DEFAULT_REGION=us-west-2 AWS_ALTERNATE_REGION=us-east-1 make testacc TESTARGS='-run=TestAccSTSCallerIdentityDataSource_stsRegion' PKG=sts
TF_ACC=1 go test ./internal/service/sts/... -v -count 1 -parallel 20  -run=TestAccSTSCallerIdentityDataSource_stsRegion -timeout 360m
caller_identity_data_source_test.go:47: Step 1/1 error: Error running pre-apply plan: exit status 1
Error: reading STS Caller Identity
with data.aws_caller_identity.current,
on terraform_plugin_test.tf line 21, in data "aws_caller_identity" "current":
21: data "aws_caller_identity" "current" {}
operation error STS: GetCallerIdentity, https response error StatusCode: …
```

b/aws_caller_identity: fix error when `sts_region` is different from `default_region`

---

go.mod
go.sum
internal/conns/awsclient_gen.go
internal/service/redshiftserverless/service_endpoints_gen_test.go
internal/service/redshiftserverless/service_package_gen.go
names/data/names_data.csv

This PR introduces AWS SDK for Go V2 service client to support Amazon Redshift Serverless enhancements, among others, Custom Domain Name Association: #35288

f/redshiftserverless: add AWS SDK for Go V2 client to implement new resource for custom domain association

---

.changelog/35861.txt
internal/service/sqs/attribute_funcs.go
internal/service/sqs/consts.go

A dependency race condition occurs where the AWS API would sometimes return an ID instead of a correct ARN, resulting in an InvalidAttributeValue when trying to set the SQS Queue Policy. Adding a retry on applying the SQS Queue Policy results in fixing this eventual consistency bug.  
Relates #21355 
Relates #13980 
```console
% make testacc TESTARGS='-run=TestAccSQSQueuePolicy_basic' PKG_NAME=internal/service/sqs
TF_ACC=1 go test ./internal/service/sqs/... -v -count 1 -parallel 20  -run=TestAccSQSQueuePolicy_basic -timeout 360m
=== RUN   TestAccSQSQueuePolicy_basic
=== PAUSE TestAccSQSQueuePolicy_basic
=== CONT  TestAccSQSQueuePolicy_basic
--- PASS: TestAccSQSQueuePolicy_basic (96.09s)
PASS
ok …
```

Add eventual consistency protection on queue policy attributes

---

.changelog/35888.txt
internal/service/deploy/deployment_config.go
internal/service/deploy/deployment_config_test.go
website/docs/r/codedeploy_deployment_config.html.markdown

- Added `arn` attribute to `aws_codedeploy_deployment_config`
- Modified `TestAccDeployDeploymentConfig_basic` to check whether `arn` is correct.
Closes #35281.
```console
$ make testacc TESTS=TestAccDeployDeploymentConfig_basic PKG=deploy
Notice: Behaving like ASDF_GOLANG_MOD_VERSION_ENABLED=true
In the future this will have to be set to continue
reading from the go.mod and go.work files
Notice: Behaving like ASDF_GOLANG_MOD_VERSION_ENABLED=true
In the future this will have to be set to continue
reading from the go.mod and go.work files
TF_ACC=1 go test ./internal/service/deploy/... -v -count 1 -parallel 20 -run='TestAccDeployDeploymentConfig_basic'  -timeout 360m
Notice: Behaving like ASDF_GOLANG_MOD_VERSION_ENABLED=true
In the …
```

[feat] add arn attribute to aws_codedeploy_deployment_config

---

.changelog/35874.txt
internal/service/eks/validate.go
internal/service/eks/validate_test.go
website/docs/d/eks_access_entry.html.markdown
website/docs/d/eks_addon.html.markdown
website/docs/d/eks_cluster.html.markdown
website/docs/r/eks_access_entry.html.markdown
website/docs/r/eks_access_policy_association.html.markdown
website/docs/r/eks_addon.html.markdown
website/docs/r/eks_cluster.html.markdown
website/docs/r/eks_fargate_profile.html.markdown
website/docs/r/eks_node_group.html.markdown

This PR is to fix the regex pattern for the EKS cluster name that is included in the documentation for numerous EKS-related resources.
I'd also like to ask the maintainers to see whether it makes sense to just remove the regex from the non-cluster resource docs. Once the EKS cluster is created (and it makes sense to provide the regex there), the name is simply referenced by other resources so I don't think providing the exact format is super useful. Let me know what you think - I can update the PR to remove them if you think it makes sense. Thanks.
Closes #35843
Referred to the [API reference](https://docs.aws.amazon.com/eks/latest/APIReference/API_CreateCluster.html#AmazonEKS-CreateCluster-request-name) for the cluster name regex.
```console
$ make testacc TESTS=TestValidClusterName …
```

fix: Fix EKS cluster name regex

---

.changelog/35875.txt
internal/service/codepipeline/codepipeline.go
internal/service/codepipeline/codepipeline_test.go
website/docs/r/codepipeline.html.markdown

This PR adds a new argument called `execution_mode` to the `aws_codepipeline` resource to support additional execution mode for V2 pipelines per https://aws.amazon.com/about-aws/whats-new/2024/02/codepipeline-trigger-filters-execution-modes/.
Closes #35810
Referred to the [AWS API reference](https://docs.aws.amazon.com/codepipeline/latest/APIReference/API_CreatePipeline.html) for specs of the new argument.
Note that `TestAccCodePipeline_pipelinetype` was enhanced to validate the new `execution_mode` argument.
Separately, there is a failure in the `TestAccCodePipeline_MultiRegion_convertSingleRegion` test case which is unrelated. I will try to see if I can fix it, but it's not caused by this PR's changes.
**Updated:** It looks like the test case is failing because the `region` attribute …

feat: Add execution_mode arg to aws_codepipeline

---

website/docs/r/s3_bucket_notification.html.markdown

aws_iam_policy_document has statement property missing in its body in [Trigger multiple Lambda functions](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket_notification#trigger-multiple-lambda-functions) section. This change, fixes it.
Closes [#35871](https://github.com/hashicorp/terraform-provider-aws/issues/35871)
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket_notification#trigger-multiple-lambda-functions
Not applicable

docs: updated s3_bucket_notification docs

---

.changelog/35870.txt
internal/service/rds/instance.go
internal/service/rds/instance_test.go

The valid values for the performance insights retention period are 7, 731 (2 years) or a multiple of 31. This is properly documented. However, in case of an invalid value terraform plan does not complain, you will get the error only after trying to apply the change.
```
~ resource "aws_db_instance" "this" {
id                                    = "db-XXXXXX"
~ performance_insights_retention_period = 7 -> 8
tags                                  = {
"Name" = "db-dev"
}
}
```
Closes #34342
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/db_instance#performance_insights_retention_period
```

[Enhancement] : Validation function for RDS performance_insights_retention_period attribute

---

go.mod
go.sum
internal/conns/awsclient_gen.go
internal/service/redshift/service_endpoints_gen_test.go
internal/service/redshift/service_package_gen.go
names/data/names_data.csv

Does not include migration of existing resources, just creation of both V1 and V2 clients to enable net-new resources to utilize the V2 SDK.

redshift: add v2 aws sdk client

---

.changelog/35955.txt
internal/service/ec2/ec2_instance.go
internal/service/ec2/ec2_instance_data_source.go
internal/service/ec2/ec2_spot_instance_request.go
website/docs/r/instance.html.markdown
website/docs/r/spot_instance_request.html.markdown

Closes #19313
```console
% make testacc TESTARGS='-run=TestAccEC2InstanceDataSource_GetPasswordData_falseToTrue\|TestAccEC2Instance_basic\|TestAccEC2Instance_GetPasswordData_falseToTrue\|TestAccEC2Instance_disappears\|TestAccEC2SpotInstanceRequest_basic\|TestAccEC2SpotInstanceRequest_getPasswordData' PKG=ec2
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 20  -run=TestAccEC2InstanceDataSource_GetPasswordData_falseToTrue\|TestAccEC2Instance_basic\|TestAccEC2Instance_GetPasswordData_falseToTrue\|TestAccEC2Instance_disappears\|TestAccEC2SpotInstanceRequest_basic\|TestAccEC2SpotInstanceRequest_getPasswordData -timeout 360m
--- PASS: TestAccEC2InstanceDataSource_GetPasswordData_falseToTrue (143.07s)
--- PASS: …
```

r/aws_ec2_instance/spot_instance_request: add configurable `read` timeout

---

website/docs/r/ecr_registry_policy.html.markdown

This PR is to add a note/warning about the `aws_ecr_registry_policy` resource being singleton at the regional level, thus it should not be used multiple times to define different policies/statements.
Closes #35940
Referred to the relevant [Actions](https://docs.aws.amazon.com/AmazonECR/latest/APIReference/API_Operations.html) in the AWS API reference doc to confirm schema for ECR registry policies.
n/a

docs: Add note about aws_ecr_registry_policy resource being singleton

---

website/docs/r/iot_domain_configuration.html.markdown

This PR adds the `status` argument description to the `aws_iot_domain_configuration` resource documentation. I've also added links to the two configuration block arguments that were missing.
Closes #35928
Referred to [UpdateDomainConfiguration](https://docs.aws.amazon.com/iot/latest/apireference/API_UpdateDomainConfiguration.html) for wording.
n/a

docs: Add status arg desc for  the aws_iot_domain_configuration resource

---

website/docs/r/lambda_event_source_mapping.html.markdown

This PR adds a link to the AWS documentation for the full list of valid values for the `type` argument of the `source_access_configuration` config block for the `aws_lambda_event_source_mapping` resource. The list of valid values is so long that it makes more sense to just refer to the AWS API reference which is constantly updated by AWS. The code uses an enum from the AWS SDK so it should be fine to always refer to the latest doc.
Closes #25911
Referred to [SourceAccessConfiguration](https://docs.aws.amazon.com/lambda/latest/api/API_SourceAccessConfiguration.html).
n/a

docs: Refer to AWS doc for source_access_configuration.type valid values for aws_lambda_event_source_mapping

---

website/docs/r/fsx_openzfs_volume.html.markdown

This PR is to add the missing description for the `origin_snapshot` block for the `aws_fsx_openzfs_filesystem` resource.
Closes #30434
Referenced [CreateOpenZFSVolumeConfiguration](https://docs.aws.amazon.com/fsx/latest/APIReference/API_CreateOpenZFSVolumeConfiguration.html) for API object specs and descriptions.
n/a

docs: Add origin_snapshot block decription for aws_fsx_openzfs_volume

---

website/docs/r/cloudwatch_event_rule.html.markdown

This PR is to add a note regarding the `ENABLED_WITH_ALL_CLOUDTRAIL_MANAGEMENT_EVENTS` value for the `state` argument being incompatible with the `schedule_expression` argument set for the `aws_cloudwatch_event_rule` resource.
Closes #34988
n/a
n/a

docs: Add note about incompability of schedule_expression and certain state for aws_cloudwatch_event_rule

---

.changelog/35974.txt
internal/service/wafv2/web_acl.go
internal/service/wafv2/web_acl_test.go
website/docs/r/wafv2_web_acl.html.markdown

- Adds the `application_integration_url` as an exported attribute of the `aws_wafv2_web_acl` resource
- https://docs.aws.amazon.com/waf/latest/developerguide/waf-javascript-api.html
```console
╰─❯ make testacc TESTS=TestAccWAFV2WebACL PKG=wafv2
TF_ACC=1 go test ./internal/service/wafv2/... -v -count 1 -parallel 20 -run='TestAccWAFV2WebACL'  -timeout 360m
=== RUN   TestAccWAFV2WebACLAssociation_basic
=== PAUSE TestAccWAFV2WebACLAssociation_basic
=== RUN   TestAccWAFV2WebACLAssociation_disappears
=== PAUSE TestAccWAFV2WebACLAssociation_disappears
=== RUN   TestAccWAFV2WebACLDataSource_basic
=== PAUSE TestAccWAFV2WebACLDataSource_basic
=== RUN   TestAccWAFV2WebACLLoggingConfiguration_basic
=== PAUSE …
```

add application integration url as exported attribute

---

.changelog/35966.txt
internal/service/kafka/replicator.go

This PR fixes the issue where the value of `detect_and_copy_new_topics` is incorrectly set to the value of `CopyAccessControlListsForTopics` from the API when reading the state (flattening).
Closes #35964
n/a
```console
$ make testacc TESTS=TestAccKafkaReplicator_update PKG=kafka
TF_ACC=1 go test ./internal/service/kafka/... -v -count 1 -parallel 20 -run='TestAccKafkaReplicator_update'  -timeout 360m
=== RUN   TestAccKafkaReplicator_update
=== PAUSE TestAccKafkaReplicator_update
=== CONT  TestAccKafkaReplicator_update
--- PASS: TestAccKafkaReplicator_update (7517.64s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/kafka      7517.820s
$
```

fix: Fix bad detect_and_copy_new_topics state mapping on read for aws_msk_replicator

---

internal/service/cloudsearch/sweep.go

Fixes:
```
2024/02/27 08:05:04 [DEBUG] Running Sweeper (aws_cloudsearch_domain) in region (us-gov-east-1)
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xc9cb1b9]
goroutine 1 [running]:
github.com/hashicorp/terraform-provider-aws/internal/service/cloudsearch.sweepDomains({0x7ff7bfeff693, 0xd})
/Users/ewbankkit/altsrc.2/github.com/terraform-providers/terraform-provider-aws/internal/service/cloudsearch/sweep.go:36 +0xd9
github.com/hashicorp/terraform-plugin-testing/helper/resource.runSweeperWithRegion({0x7ff7bfeff693, 0xd}, 0xc000a7ec00, 0xc000b87d08?, 0xc000843510?, 0x0)
/Users/ewbankkit/go/pkg/mod/github.com/hashicorp/terraform-plugin-testing@v1.6.0/helper/resource/testing.go:272 +0x642 …
```

Sweeper fixes

---

.changelog/35937.txt
internal/service/redshift/data_shares_data_source.go
internal/service/redshift/data_shares_data_source_test.go
internal/service/redshift/service_package_gen.go
names/names.go
website/docs/d/redshift_data_shares.html.markdown

This data source will allow practitioners to list existing Redshift data shares in a given region.
Closes #35915
- https://docs.aws.amazon.com/redshift/latest/APIReference/API_DescribeDataShares.html
```console
% make testacc PKG=redshift TESTS=TestAccRedshiftDataSharesDataSource_
TF_ACC=1 go test ./internal/service/redshift/... -v -count 1 -parallel 20 -run='TestAccRedshiftDataSharesDataSource_'  -timeout 360m
--- PASS: TestAccRedshiftDataSharesDataSource_basic (298.64s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/redshift   305.822s
```

d/aws_redshift_data_sources: new data source

---

website/docs/r/wafv2_ip_set.html.markdown
website/docs/r/wafv2_web_acl.html.markdown

Update the provider documentation for aws_wafv2_ip_set and aws_wafv2_web_acl to highlight when changing attributes will force a new resource.
Closes #35907
```console
...
```

docs(35907): add forces new resource warning to ip set and web acl docs

---

.changelog/35993.txt
internal/service/appflow/flow.go
internal/service/appflow/flow_test.go

- Allows `source_fields` to be an empty list.
Closes #25095
Closes #35992
```console
% make testacc TESTARGS="-run=TestAccAppFlowFlow_" PKG=appflow
TF_ACC=1 go test ./internal/service/appflow/... -v -count 1 -parallel 20  -run=TestAccAppFlowFlow_ -timeout 360m
--- PASS: TestAccAppFlowFlow_taskProperties (19.10s)
--- PASS: TestAccAppFlowFlow_disappears (19.59s)
--- PASS: TestAccAppFlowFlow_basic (21.72s)
--- PASS: TestAccAppFlowFlow_task_mapAll (23.49s)
--- PASS: TestAccAppFlowFlow_update (29.12s)
--- PASS: TestAccAppFlowFlow_S3_outputFormatConfig_ParquetFileType (29.65s)
--- PASS: TestAccAppFlowFlow_taskUpdate (29.71s)
--- PASS: TestAccAppFlowFlow_tags (40.47s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/ …
```

r/aws_appflow_flow: suppress diff when `task_type` value of `Map_all` is used

---

.changelog/36029.txt
internal/service/ecs/task_definition.go
internal/service/ecs/task_definition_equivalency.go

When the order of the container definitions does not match between AWS API and aws_ecs_task_definition, terraform tries to replace the task definition to match the container definitions order. This is unnecessary as the container order does not mean anything. 
I am trying to to import bunch of  different task definitions using a single module, and I keep getting diffs due to container definitions order. This PR prevents unnecessary diffs for when the container definitions order does not match between API and Terraform.
```hcl
resource "aws_ecs_task_definition" "test" {
family = "testtaskdef1"
container_definitions = jsonencode([
{
"name": "sidecard",
"image": "sidecar:1",
"cpu": 0,
"portMappings": [],
"essential": false,
"environment": [
{
"name": "sidecarenv",
"value": "sidecarenvvalue" …
```

resource/aws_ecs_task_definition: prevent spurious container definition diffs

---

.changelog/35990.txt
internal/service/mq/broker.go
internal/service/mq/broker_test.go
internal/service/mq/exports_test.go
website/docs/r/mq_broker.html.markdown

This change adds the `data_replication_mode` and `data_replication_primary_broker_arn` arguments, enabling support for cross-region data replication. See the AWS MQ documentation for configuration details.
- https://docs.aws.amazon.com/amazon-mq/latest/developer-guide/crdr-for-active-mq.html
Closes #32566
- https://docs.aws.amazon.com/amazon-mq/latest/api-reference/brokers.html#brokers-schemas
```console
% make testacc PKG=mq TESTS=TestAccMQBroker_dataReplicationMode
TF_ACC=1 go test ./internal/service/mq/... -v -count 1 -parallel 20 -run='TestAccMQBroker_dataReplicationMode'  -timeout 360m
--- PASS: TestAccMQBroker_dataReplicationMode (511.53s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/mq 518.736s …
```

r/aws_mq_broker: enable cross-region data replication

---

.changelog/33769.txt
docs/resource-tagging.md
internal/provider/intercept.go
internal/service/ec2/ec2_instance.go
internal/service/ec2/ec2_instance_data_source.go
internal/service/ec2/ec2_instance_test.go
internal/service/ec2/ec2_spot_instance_request.go
internal/service/ec2/tags.go
website/docs/r/instance.html.markdown

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
```
$ terraform -v
Terraform v0.14.6
+ provider registry.terraform.io/hashicorp/aws v3.46.0
```
* `aws_instance`
Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.
```terraform …
```

Use default tags for ec2 root block device 

---

internal/service/elasticbeanstalk/configuration_template.go
internal/service/elasticbeanstalk/configuration_template_test.go
internal/service/elasticbeanstalk/environment.go
internal/service/elasticbeanstalk/environment_test.go

```
=== RUN   TestAccElasticBeanstalkEnvironment_disappears
=== PAUSE TestAccElasticBeanstalkEnvironment_disappears
=== CONT  TestAccElasticBeanstalkEnvironment_disappears
testing_new.go:91: Error running post-test destroy, there may be dangling resources: exit status 1
Error: waiting for Elastic Beanstalk Environment (e-pi4wxzyprr) update: couldn't find resource (21 retries)
--- FAIL: TestAccElasticBeanstalkEnvironment_disappears (678.47s)
FAIL
```
```console
% make testacc TESTARGS="-run=TestAccElasticBeanstalk" PKG=elasticbeanstalk
TF_ACC=1 go test ./internal/service/elasticbeanstalk/... -v -count 1 -parallel 20  -run=TestAccElasticBeanstalk -timeout 360m
--- PASS: …
```

td/elasticbeanstalk: fix multiple tests in service

---

internal/service/s3/object_copy_test.go

Corrects check in acceptance test `TestAccS3ObjectCopy_basicViaAccessPoint`
```console
% make testacc PKG=s3 TESTS=TestAccS3ObjectCopy_basicViaAccessPoint
--- PASS: TestAccS3ObjectCopy_basicViaAccessPoint (16.45s)
```

resource/aws_s3_object_copy: Fixes acceptance test

---

docs/add-a-new-service.md

Updated the SDK V2 example for adding a Custom Service Client based on the changes in the pull request #36023 
None
#36023 
```console
make testacc PKG=costoptimizationhub
TF_ACC=1 go test ./internal/service/costoptimizationhub/... -v -count 1 -parallel 20   -timeout 360m
=== RUN   TestEndpointConfiguration
=== RUN   TestEndpointConfiguration/package_name_endpoint_config_overrides_service_config_file
=== RUN   TestEndpointConfiguration/service_aws_envvar
=== RUN   TestEndpointConfiguration/service_aws_envvar_overrides_base_config_file
=== RUN   TestEndpointConfiguration/service_config_file
=== RUN   TestEndpointConfiguration/no_config
=== RUN   TestEndpointConfiguration/package_name_endpoint_config_overrides_aws_service_envvar
=== …
```

Documentation - Updated the example for adding a Custom Service Client

---

.changelog/36080.txt
docs/running-and-writing-acceptance-tests.md
internal/service/rds/instance.go
internal/service/rds/instance_test.go

When creating a replica RDS Instance, the parameter group was set during a modify step after creation. This is because the parameter group cannot be set when creating a replica in the same region as the source. When using parameter values that cannot be changed after creation, such as the `max_string_size` for Oracle, this would cause errors when creating a replica.
Now sets the parameter group on creation when the source DB is located in a different region.
Closes #31719
```console
% make testacc PKG=rds TESTS=TestAccRDSInstance_ReplicateSourceDB
--- PASS: TestAccRDSInstance_ReplicateSourceDB_allowMajorVersionUpgrade (1313.53s)
--- PASS: TestAccRDSInstance_ReplicateSourceDB_iops (1374.11s)
--- PASS: TestAccRDSInstance_ReplicateSourceDB_allocatedStorage (1496.60s)
--- PASS: …
```

resource/aws_db_instance: Sets `parameter_group_name` on replica when source is in different region

---

.changelog/36088.txt
internal/service/cloudfront/distribution.go

`origin_read_timeout` is an attribute with a default maximum of 180 seconds, but this upper limit can be lifted by AWS Support and be set to a much higher value. This change removes the upper limit, but leaves the lower minimum, allowing for these changes to be reflected and supported by Terraform.
Relates #31608 
```console
% make testacc TESTS="TestAccCloudFrontDistribution_basic" PKG=cloudfront
TF_ACC=1 go test ./internal/service/cloudfront/... -v -count 1 -parallel 20 -run='TestAccCloudFrontDistribution_basic'  -timeout 360m
=== RUN   TestAccCloudFrontDistribution_basic
=== PAUSE TestAccCloudFrontDistribution_basic
=== CONT  TestAccCloudFrontDistribution_basic
--- PASS: TestAccCloudFrontDistribution_basic (284.29s)
PASS
ok …
```

Remove upper limit on origin_read_timeout for CloudFront distribution

---

.changelog/36095.txt
internal/service/vpclattice/listener_rule.go

Registering VPC Lattice target groups to a listener rule is limited to a max of 2 by the provider. However, it's perfectly possible to add more than 2 to a rule using AWS CLI.
```
aws vpc-lattice create-rule \
--action '{"forward":{"targetGroups":[{"targetGroupIdentifier":"tg-xxxx","weight":1},{"targetGroupIdentifier":"tg-yyyy","weight":1},{"targetGroupIdentifier":"tg-zzzz","weight":1}]}}' \
--listener-identifier "arn:aws:vpc-lattice:us-east-1:..." \
--match '{"httpMatch":{"pathMatch":{"caseSensitive":false,"match":{"prefix":"/"}}}}' \
--name "ms-1" \
--priority 10 \
--service-identifier "arn:aws:vpc-lattice:us-east-1:..."
```
Attempting this with the current provider leads to an error:
```terraform
│ Error: Too many target_groups blocks
│ 
│   on main.tf line 55, in resource …
```

Remove max target group limit

---

internal/service/rds/consts.go
website/docs/r/rds_cluster_instance.html.markdown

resource `aws_rds_cluster` and resource `aws_rds_cluster_instance`, 
- if `aurora-mysql` or `aurora-postgres` is specified in the `engine`, it means Aurora Cluster.
- if `mysql` or `postgres` is specified in the `engine`, it means RDS Multi-AZ Cluster.
Therefore resouce `aws_rds_cluster_instance` shoud be supported not only "aurora-mysql" and "aurora-postgres" but also "mysql" and "postgres".
<details>
<summary>sample.tf</summary>
```terraform
terraform {
aws = {
version = "5.28.0"
}
}
required_version = ">= 1.2.0"
}
region  = "ap-northeast-1"
}
resource "aws_rds_cluster" "rds_cluster" {
cluster_identifier                  = "im-a-db-cluster"
allocated_storage                   = 100
availability_zones                  = …
```

Fix RDS ClusterInstanceEngine Validation

---

.changelog/34750.txt
internal/service/batch/job_queue.go
internal/service/batch/job_queue_schema.go
internal/service/batch/job_queue_test.go
website/docs/r/batch_job_queue.html.markdown

- `compute_environments` (CEs) and `compute_environment_order` (CEOs) are mutually exclusive
- In order to preserve schema migration, `compute_environments` must stay as the "default" or it will cause breaking changes when a users schema is migrated from CEs in state without requiring them to update their HCL to use CEOs.
- Because import requires `CEs` it is impossible to migrate to CEOs parameter :/  You must have done the initial `Create` with it
Closes #34760
Closes #19247
Closes #20764
**Does not close or resolve** #34794 however, migration does appear to work as expected
```console
$ make testacc TESTS=TestAccBatchJobQueue_ PKG=batch
TF_ACC=1 go test ./internal/service/batch/... -v -count 1 -parallel 20 …
```

aws_batch_job_queue add `compute_environment_order` and deprecate `compute_environments`

---

.changelog/36097.txt
internal/service/medialive/channel_encoder_settings_schema.go
internal/service/medialive/channel_test.go
website/docs/r/medialive_channel.html.markdown

Audio descriptions are not actually required.
Useful for when you are creating a video only channel with no audio.
Relates https://github.com/hashicorp/terraform-provider-aws/issues/27824
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-medialive-channel-encodersettings.html#aws-properties-medialive-channel-encodersettings-properties
```console
% make testacc TESTS=TestAccMediaLiveChannel_ PKG=medialive
TF_ACC=1 go test ./internal/service/medialive/... -v -count 1 -parallel 20 -run='TestAccMediaLiveChannel_'  -timeout 360m
=== RUN   TestAccMediaLiveChannel_basic
=== PAUSE TestAccMediaLiveChannel_basic
=== RUN   TestAccMediaLiveChannel_captionDescriptions
=== PAUSE …
```

r/medialive_channel: allow empty audio descriptions

---

website/docs/r/guardduty_detector_feature.html.markdown

Runtime monitoring is already supported, however the values required for configuration are not present in the documention.
Closes #34973
- https://docs.aws.amazon.com/guardduty/latest/APIReference/API_DetectorAdditionalConfiguration.html
- https://docs.aws.amazon.com/guardduty/latest/APIReference/API_DetectorFeatureConfiguration.html

[Documentation] Update `aws_guardduty_detector_feature`documentation with runtime monitoring values

---

internal/service/acm/certificate_data_source_test.go

Relates #32976
```console
% make testacc TESTS='TestAccACMCertificateDataSource_' PKG=acm
TF_ACC=1 go test ./internal/service/acm/... -v -count 1 -parallel 20 -run='TestAccACMCertificateDataSource_'  -timeout 360m
=== RUN   TestAccACMCertificateDataSource_singleIssued
=== PAUSE TestAccACMCertificateDataSource_singleIssued
=== RUN   TestAccACMCertificateDataSource_multipleIssued
=== PAUSE TestAccACMCertificateDataSource_multipleIssued
=== RUN   TestAccACMCertificateDataSource_noMatchReturnsError
=== PAUSE TestAccACMCertificateDataSource_noMatchReturnsError
=== RUN   TestAccACMCertificateDataSource_keyTypes
=== PAUSE TestAccACMCertificateDataSource_keyTypes
=== CONT  TestAccACMCertificateDataSource_singleIssued
=== CONT …
```

d/aws_acm_certificate: Migrate tests to AWS SDK v2

---

.changelog/36285.txt
internal/service/route53domains/exports_test.go
internal/service/route53domains/registered_domain.go
internal/service/route53domains/registered_domain_test.go
internal/service/route53domains/service_package_gen.go
website/docs/r/route53domains_registered_domain.html.markdown

This changeset adds billing_contact and billing_privacy to the aws_route53domains_registered_domain resource.
Closes #36269 
Please see the corresponding issue for references
No acceptance tests were executed as I don't have a test domain to execute them on at the moment.

aws_route53domains_registered_domain: Add billing_contact and billing_privacy

---

.changelog/36236.txt
internal/service/ec2/vpnsite_connection.go
internal/service/ec2/vpnsite_connection_test.go

Fixes incorrect regex to properly allow any CIDR in `fd00::/8` (the current regex incorrectly only allows CIDRs from `fd00::/16`).
Closes #36232
```console
% make testacc TESTS=TestAccSiteVPNConnection_tunnel1InsideIPv6CIDR PKG=ec2
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 20 -run='TestAccSiteVPNConnection_tunnel1InsideIPv6CIDR'  -timeout 360m
=== RUN   TestAccSiteVPNConnection_tunnel1InsideIPv6CIDR
=== PAUSE TestAccSiteVPNConnection_tunnel1InsideIPv6CIDR
=== CONT  TestAccSiteVPNConnection_tunnel1InsideIPv6CIDR
--- PASS: TestAccSiteVPNConnection_tunnel1InsideIPv6CIDR (405.46s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/ec2	405.565s
...
```

resource/aws_vpn_connection: Fixes CIDR validation for inside_ipv6_cidr fields

---

.changelog/36298.txt
internal/service/opensearch/domain_data_source.go

This PR is to fix a regression introduced by #36067. The `use_off_peak_window` argument was added to the `aws_opensearch_domain` resource, however the the `aws_openserach_domain` data source wasn't updated accordingly.
Closes #36291
n/a
```console
$ make testacc TESTARGS="-run=TestAccOpenSearchDomainDataSource_Data_" PKG=opensearch
TF_ACC=1 go test ./internal/service/opensearch/... -v -count 1 -parallel 20  -run=TestAccOpenSearchDomainDataSource_Data_ -timeout 360m       
=== RUN   TestAccOpenSearchDomainDataSource_Data_basic
=== PAUSE TestAccOpenSearchDomainDataSource_Data_basic
=== RUN   TestAccOpenSearchDomainDataSource_Data_advanced
=== PAUSE TestAccOpenSearchDomainDataSource_Data_advanced
=== CONT …
```

fix: Add missing use_off_peak_window arg to schema for aws_opensearch_domain data source

---

internal/acctest/acctest.go
internal/service/cloudformation/find.go
internal/service/cloudformation/stack_set_instance_test.go
internal/service/cloudformation/stack_set_test.go

Add acceptance tests for the `aws_cloudformation_stack_set` and `aws_cloudformation_stack_set_instance` resources where the primary account is a [delegated administrator](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/stacksets-orgs-delegated-admin.html).
Relates https://github.com/hashicorp/terraform-provider-aws/issues/22867.
Relates https://github.com/hashicorp/terraform-provider-aws/issues/32536.
```console
% make testacc TESTARGS='-run=TestAccCloudFormationStackSet_delegatedAdministrator' PKG=cloudformation
TF_ACC=1 go test ./internal/service/cloudformation/... -v -count 1 -parallel 20  -run=TestAccCloudFormationStackSet_delegatedAdministrator -timeout 360m
=== RUN …
```

Add `aws_cloudformation_stack_set(_instance)` delegated administrator acceptance tests

---

internal/service/ec2/exports_test.go
internal/service/ec2/findv2.go
internal/service/ec2/service_package_gen.go
internal/service/ec2/sweep.go
internal/service/ec2/vpc_default_network_acl.go
internal/service/ec2/vpc_default_network_acl_test.go
internal/service/ec2/vpc_network_acl.go
internal/service/ec2/vpc_network_acl_test.go

Relates #36219.
Relates https://github.com/hashicorp/terraform-provider-aws/issues/35747.
```console
% make testacc TESTS='TestAccVPCDefaultNetworkACL_basic' PKG=ec2
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 20 -run='TestAccVPCDefaultNetworkACL_basic'  -timeout 360m
=== RUN   TestAccVPCDefaultNetworkACL_basic
=== PAUSE TestAccVPCDefaultNetworkACL_basic
=== RUN   TestAccVPCDefaultNetworkACL_basicIPv6VPC
=== PAUSE TestAccVPCDefaultNetworkACL_basicIPv6VPC
=== CONT  TestAccVPCDefaultNetworkACL_basic
=== CONT  TestAccVPCDefaultNetworkACL_basicIPv6VPC
--- PASS: TestAccVPCDefaultNetworkACL_basic (15.58s)
--- PASS: TestAccVPCDefaultNetworkACL_basicIPv6VPC (25.41s)
PASS
ok …
```

r/aws_vpc_default_network_acl: Migrate to AWS SDK v2

---

website/docs/d/opensearch_domain.html.markdown

This is a follow-up PR to add the documentation for the `use_off_peak_window` attribute to the `aws_opensearch_domain` data source. The first PR was focused on getting the fix in ASAP, so now I have time to review and update the doc.
Relates #36291
Referred to #36067 for the same attribute description.
```console
n/a
```

docs: Add use_off_peak_window attr to aws_opensearch_domain data source

---

.changelog/36310.txt
internal/generate/tags/main.go
internal/generate/tags/templates/v1/get_tag_body.tmpl
internal/generate/tags/templates/v1/list_tags_body.tmpl
internal/generate/tags/templates/v1/update_tags_body.tmpl
internal/service/elasticache/generate.go
internal/service/elasticache/replication_group.go
internal/service/elasticache/tags_gen.go
internal/tfresource/retry.go

Closes #31819
Closes #30444
Closes #33859
Closes #23219
```console
% make t T=TestAccElastiCacheReplicationGroup K=elasticache P=10
TF_ACC=1 go test ./internal/service/elasticache/... -v -count 1 -parallel 10 -run='TestAccElastiCacheReplicationGroup'  -timeout 360m
=== RUN   TestAccElastiCacheReplicationGroupDataSource_basic
=== PAUSE TestAccElastiCacheReplicationGroupDataSource_basic
=== RUN   TestAccElastiCacheReplicationGroupDataSource_clusterMode
=== PAUSE TestAccElastiCacheReplicationGroupDataSource_clusterMode
=== RUN   TestAccElastiCacheReplicationGroupDataSource_multiAZ
=== PAUSE TestAccElastiCacheReplicationGroupDataSource_multiAZ
=== RUN   TestAccElastiCacheReplicationGroupDataSource_nonExistent
=== PAUSE …
```

elasticache: Allow for tagging retries

---

website/docs/r/instance.html.markdown

Update the aws_instance documentation.  Clarifies that `market_type` is required when `spot_options` are defined.
Closes #35770
https://github.com/hashicorp/terraform-provider-aws/issues/35770

35770 - Clarify market_type is required

---

.changelog/36308.txt
internal/service/ec2/ec2_instance.go
internal/service/ec2/ec2_instance_test.go

This will allow adjusting the `ipv6_address_count` address on an instance's primary NIC without replacing the instance.
Closes #33707
```console
% make testacc TESTS=TestAccEC2Instance_IPv6AddressCount PKG=ec2
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 20 -run='TestAccEC2Instance_IPv6AddressCount'  -timeout 360m
=== RUN   TestAccEC2Instance_IPv6AddressCount
=== PAUSE TestAccEC2Instance_IPv6AddressCount
=== CONT  TestAccEC2Instance_IPv6AddressCount
--- PASS: TestAccEC2Instance_IPv6AddressCount (140.24s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/ec2	144.286s
```

aws_ec2_instance: allow adjusting ipv6_address_count without replacing the instance

---

.changelog/36341.txt
internal/service/ecs/cluster.go

This PR is to fix provider crashes in three locations due to empty configuration blocks (`configuration`, `execute_command_configuration` and `log_configuration`) being loaded as `nil` into the list of blocks from the config during expansion. The AWS API also seems to set a default value for the `logging` argument in the `execute_command_configuration` block, so I also had to set a default value to avoid perpetual differences.
**Note:** Since this is a widely used resource, I appreciate that a maintainer review this change to make sure I am not introducing any side effects. If there is anything I could do to help validate further, let me know.
Closes #36330
Referred to other resource code like that of [`aws_openserach_domain`](https://github.com/hashicorp/terraform-provider-aws/blob/main/i …

fix: Add nil check for empty blocks to fix crashes for aws_ecs_cluster

---

internal/service/elbv2/listener_rule_test.go
internal/service/elbv2/listener_test.go

Fixes `panic: runtime error: slice bounds out of range [:30] with length 29` errors.
Closes https://github.com/hashicorp/terraform-provider-aws/issues/36351.
```console
% make testacc TESTARGS='-run=TestAccELBV2ListenerRule_updateForwardBasic\|TestAccELBV2ListenerRule_ActionForward_IgnoreFields\|TestAccELBV2Listener_updateForwardBasic\|TestAccELBV2Listener_ActionForward_IgnoreFields' PKG=elbv2 ACCTEST_PARALLELISM=3
TF_ACC=1 go1.21.7 test ./internal/service/elbv2/... -v -count 1 -parallel 3  -run=TestAccELBV2ListenerRule_updateForwardBasic\|TestAccELBV2ListenerRule_ActionForward_IgnoreFields\|TestAccELBV2Listener_updateForwardBasic\|TestAccELBV2Listener_ActionForward_IgnoreFields -timeout 360m
=== RUN …
```

elbv2: Fix occasionally crashing acceptance tests

---

.changelog/36311.txt
internal/service/cognitoidp/identity_provider.go

A recent AWS feature release for Cognito added read-only ActiveEncryptionCertificate property to Cognito Identity Provider describe ProviderDetails map. UpdateIdentityProvider API call responds with the following error if ActiveEncryptionCertificate is included in the ProviderDetails map in the request. For example:
```
Error: Error updating Cognito Identity Provider: InvalidParameterException: ActiveEncryptionCertificate is not a valid key for SAML identity provider details.
```
If the Terraform plan for aws_cognito_identity_provider includes changes on the `provider_details` argument then we'll run into the above error during apply.
Closes #35588 
[AWS announcement for the feature that introduced the API change](https://aws.amazon.com/about-aws/whats-new/2024/02/amazon-cognito-signing-en …

fix: aws_cognito_identity_provider update ProviderDetails ActiveEncryptionCertificate on update

---

.changelog/36361.txt
internal/service/finspace/kx_cluster.go
internal/service/finspace/kx_cluster_test.go

This PR fixes a bug where updating command line args on a cluster with an existing init script (not updated) would remove the init script from the cluster, and vice versa (updating init script on a cluster with command line args could remove command line args from cluster). This change has been tested both through manual testing (approaching both ends of the bug) and through rerunning relevant acceptance tests to ensure there are no regressions.
Relates #31806
```console
% make testacc TESTS=TestAccFinSpaceKxCluster_commandLineArgs PKG=finspace
TF_ACC=1 go test ./internal/service/finspace/... -v -count 1 -parallel 20 -run='TestAccFinSpaceKxCluster_commandLineArgs'  -timeout 360m
=== RUN   TestAccFinSpaceKxCluster_commandLineArgs …
```

[Bug Fix] kx_cluster Init script and command line arg updates

---

.github/dependabot.yml

Missed `.ci/providerlint`.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/36378.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/36367.

`.ci/providerlint`: `protobuf` should only be updated via `terraform-plugin-go`/`terraform-plugin-framework`

---

internal/conns/awsclient_gen.go
internal/service/lakeformation/data_lake_settings.go
internal/service/lakeformation/data_lake_settings_data_source.go
internal/service/lakeformation/data_lake_settings_data_source_test.go
internal/service/lakeformation/data_lake_settings_test.go
internal/service/lakeformation/filter.go
internal/service/lakeformation/filter_test.go
internal/service/lakeformation/lf_tag.go
internal/service/lakeformation/lf_tag_test.go
internal/service/lakeformation/permissions.go
internal/service/lakeformation/permissions_data_source.go
internal/service/lakeformation/permissions_test.go
internal/service/lakeformation/prettify.go
internal/service/lakeformation/resource.go
internal/service/lakeformation/resource_data_source.go
internal/service/lakeformation/resource_data_source_test.go
internal/service/lakeformation/resource_lf_tags.go
internal/service/lakeformation/resource_lf_tags_test.go
internal/service/lakeformation/resource_test.go
internal/service/lakeformation/service_endpoints_gen_test.go
internal/service/lakeformation/service_package_gen.go
internal/service/lakeformation/status.go
internal/service/lakeformation/strings.go
internal/service/lakeformation/strings_test.go
internal/service/lakeformation/wait.go
names/data/names_data.csv

Closes #36179
```console
% make testacc TESTARGS="-run=TestAccLakeFormation" PKG=lakeformation
TF_ACC=1 go test ./internal/service/lakeformation/... -v -count 1 -parallel 20  -run=TestAccLakeFormation -timeout 360m
--- PASS: TestAccLakeFormationResource_basic (16.64s)
--- PASS: TestAccLakeFormationResourceDataSource_basic (17.17s)
--- PASS: TestAccLakeFormationResource_disappears (17.29s)
--- PASS: TestAccLakeFormationResource_hybridAccessEnabled (17.51s)
--- PASS: TestAccLakeFormationResource_serviceLinkedRole (17.56s)
--- PASS: TestAccLakeFormationResource_updateRoleToRole (27.31s)
--- PASS: TestAccLakeFormationResource_updateSLRToRole (27.70s)
--- PASS: TestAccLakeFormation_serial (1160.88s)
--- PASS: …
```

Migrate LakeFormation Service to AWS Go SDKv2

---

website/docs/r/elasticache_serverless_cache.html.markdown

Update the [Memcached Serverless](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/elasticache_serverless_cache#memcached-serverless) and [Redis Serverless]( https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/elasticache_serverless_cache#redis-serverless) examples by replacing the invalid value of 5 for maximum ecpus per second.
```hcl
ecpu_per_second {
maximum = 5
}
```
with an allowed value of 5000.
The allowed range has been added to the documentation. At same time the allowed range for the maximum cache size has been added.
Closes #35648 
When setting up a serverless cache via AWS Management Console details on the expected/ allowed range can be seen.
The value of 5 that is at present in the documentation is not allowed here.
No tests …

docs: add details on restrictions for maximum ecpus and data storage

---

internal/acctest/framework.go

This change adds a new helper function to the `acctest` package, `CheckFrameworkResourceDisappearsWithStateFunc`, that allows for a custom function to be provided which constructs the plugin framework state from the Terraform instance state. This is helpful for resources where the default behavior of the `CheckFrameworkResourceDisappears` helper (which only copies root level string arguments into the plugin framework state) results in missing inputs for the delete operation. Cases where nested or non-string arguments must be copied can now rely on custom state functions local to the service testing package.
Relates #35746
Verifying the existing behavior of `CheckFrameworkResourceDisappears` is not impacted:
```console
% make testacc PKG=auditmanager …
```

internal/acctest: custom framework disappears state function

---

website/docs/cdktf/python/r/cognito_user_pool.html.markdown
website/docs/r/cognito_user_pool.html.markdown

This PR corrects the casing of the lambda_arn variable in the documentation for the pre-token generation configuration. Previously, the casing may have been incorrect, leading to potential confusion or errors. The correction ensures that users referencing the documentation will use the correct casing for lambda_arn in their own configurations.
Closes #36420.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/35236.
```console
Not needed since is documentation
...
```

docs: Fix lambda_arn casing in pre_token_generation_config

---

website/docs/r/securitylake_subscriber.html.markdown

Fix `aws_securitylake_subscriber` import instructions in documentation. Import is done by subscriber ID and not the ARN.
Verified an import myself.
NA

Fix `aws_securitylake_subscriber` import ID

---

internal/service/opensearch/domain.go
internal/service/opensearch/domain_test.go
internal/service/opensearch/wait.go

When adding an IAM Role to the OpenSearch Domain's access policy, IAM eventual consistency sometimes leads to an error such as
> Error: updating OpenSearch Domain (...): InvalidTypeException: Error setting policy:
The error message also wraps the policy in `[` and `]`, suggesting that the policy is unexpectedly a single-element array.
Closes #26433
```console
% make testacc PKG=opensearch TESTS=TestAccOpenSearchDomain_Policy_
--- PASS: TestAccOpenSearchDomain_Policy_ignoreEquivalent (2133.95s)
--- PASS: TestAccOpenSearchDomain_Policy_addPrincipal (2116.35s)
--- PASS: TestAccOpenSearchDomain_Policy_basic (2080.24s)
```
Note that there are other existing errors for `aws_opensearch_domain`, mostly
> Error: updating OpenSearch Domain (...): ValidationException: A change/update is in progress. …

resource/aws_opensearch_domain: Fixes eventual consistency error when adding role to access policy

---

website/docs/r/lb_listener.html.markdown

The `lb_listener` resource has a `mutual_authentication` block that is incorrectly documented as an expression.
Closes #35809
https://github.com/hashicorp/terraform-provider-aws/blob/20d3854c8acf036a3abcaa75344aca2f563be405/internal/service/elbv2/listener_data_source.go#L263-L264

Fix documentation error for lb_listener mutual_authentication block

---

website/docs/r/sfn_state_machine.html.markdown

Add the attribute `state_machine_version_arn` to the attribute reference of the state machine.
Closes #36274.
* [SFN State Machine Attribute Reference (current version)](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sfn_state_machine#attribute-reference)
* [SFN Alias Example usage (current version)](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sfn_alias#example-usage) already using the not documented attribute
```hcl
resource "aws_sfn_alias" "sfn_alias" {
name = "my_sfn_alias"
routing_configuration {
state_machine_version_arn = aws_sfn_state_machine.sfn_test.state_machine_version_arn
weight                    = 100
}
}
resource "aws_sfn_alias" "my_sfn_alias" {
name = "my_sfn_alias"
routing_configuration { …
```

docs: add missing attribute for aws_sfn_state_machine

---

skaff/datasource/datasourcetest.tmpl
skaff/resource/resourcetest.tmpl

#35866 added semgrep rules to verify `acctest.ErrorCheck` uses the generated `names.{Service}ServiceID` constant, and migrated all existing references. This updates the corresponding `skaff` templates.
Relates #35866

skaff: use service ID with acctest.ErrorCheck

---

docs/aws-go-sdk-base.md
docs/aws-sdk-go-base.md
docs/terraform-plugin-migrations.md
mkdocs.yml

Miscellaneous cleanup of the developer reference section of the contributor guide, including:
- Moving the `Terraform Plugin Migration` document from the `Contribute` section to `Developer Reference` for consistency with the `AWS SDK for Go Migration` documentation.
- Fixing naming of the `AWS SDK Go Base` and minor cleanup.
- Alphabetizing the developer reference navbar.

docs: cleanup developer reference section

---

.changelog/36458.txt
internal/service/glue/job.go
internal/service/glue/job_test.go

Lower the minimum of `number_of_workers` to 1
Closes #23372
```console
make testacc TESTS=TestAccGlueJob_ PKG=glue
TF_ACC=1 go test ./internal/service/glue/... -v -count 1 -parallel 20 -run='TestAccGlueJob_'  -timeout 360m
=== RUN   TestAccGlueJob_basic
=== PAUSE TestAccGlueJob_basic
=== RUN   TestAccGlueJob_disappears
=== PAUSE TestAccGlueJob_disappears
=== RUN   TestAccGlueJob_basicStreaming
=== PAUSE TestAccGlueJob_basicStreaming
=== RUN   TestAccGlueJob_command
=== PAUSE TestAccGlueJob_command
=== RUN   TestAccGlueJob_defaultArguments
=== PAUSE TestAccGlueJob_defaultArguments
=== RUN   TestAccGlueJob_nonOverridableArguments
=== PAUSE TestAccGlueJob_nonOverridableArguments
=== RUN   TestAccGlueJob_description
=== PAUSE …
```

chore: allow a minimum of 1 worker for a Glue Job

---

internal/generate/listpages/v2/function.tmpl

When specifying multiple `ListOps` then functions were starting on the same line as the closing brace of the preceding function. Add a blank line to match the v1 function template.
Closes #0000
```console
...
```

Fix listpages generator for AWS SDK v2

---

internal/flex/flex.go
internal/flex/flex_test.go

When migrating `apigateway` and `apigatewayv2` I came across a couple of conversions that would be useful to have in `flex`.
Closes #0000
```console
% make test
go1.21.8 test ./...  -timeout=5m
?   	github.com/hashicorp/terraform-provider-aws	[no test files]
?   	github.com/hashicorp/terraform-provider-aws/internal/attrmap	[no test files]
ok  	github.com/hashicorp/terraform-provider-aws/internal/acctest	(cached)
ok  	github.com/hashicorp/terraform-provider-aws/internal/conns	(cached)
ok  	github.com/hashicorp/terraform-provider-aws/internal/create	(cached)
ok  	github.com/hashicorp/terraform-provider-aws/internal/enum	(cached)
ok  	github.com/hashicorp/terraform-provider-aws/internal/envvar	(cached)
ok …
```

flex: Add helpers for AWS SDK v2

---

.changelog/36391.txt
internal/service/ec2/vpc_peering_connection_data_source.go
internal/service/ec2/vpc_peering_connection_data_source_test.go
website/docs/d/vpc_peering_connection.html.markdown

Adds the `ipv6_cidr_block_set` and `peer_ipv6_cidr_block_set` attributes to the vpc_peering_connection data source.
Closes #25746
None
```console
% make testacc TESTS=TestAccVPCPeeringConnectionDataSource_id PKG=ec2
TF_ACC=1 go1.21.8 test ./internal/service/ec2/... -v -count 1 -parallel 20 -run='TestAccVPCPeeringConnectionDataSource_id'  -timeout 360m
=== RUN   TestAccVPCPeeringConnectionDataSource_id
=== PAUSE TestAccVPCPeeringConnectionDataSource_id
=== CONT  TestAccVPCPeeringConnectionDataSource_id
--- PASS: TestAccVPCPeeringConnectionDataSource_id (58.20s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/ec2        76.192s
```

d/aws_vpc_peering_connection: Add IPv6 CIDR block attributes

---

.changelog/36481.txt
internal/service/redshift/producer_data_shares_data_source.go
internal/service/redshift/producer_data_shares_data_source_test.go
internal/service/redshift/service_package_gen.go
website/docs/d/redshift_producer_data_shares.html.markdown

This data source will allow practitioners to list existing Redshift data shares in a given producer.
Closes #35916
- https://docs.aws.amazon.com/redshift/latest/APIReference/API_DescribeDataSharesForProducer.html
```console
% make testacc PKG=redshift TESTS=TestAccRedshiftProducerDataSharesDataSource_
TF_ACC=1 go1.21.8 test ./internal/service/redshift/... -v -count 1 -parallel 20 -run='TestAccRedshiftProducerDataSharesDataSource_'  -timeout 360m
--- PASS: TestAccRedshiftProducerDataSharesDataSource_basic (487.34s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/redshift   491.714s
```

d/aws_redshift_producer_data_shares: new data source

---

.changelog/36484.txt
internal/service/eks/access_entry.go
internal/service/eks/access_entry_test.go

The problematic behavior is pretty well explained in https://github.com/hashicorp/terraform-provider-aws/issues/36480 so I'm not going to repeat that here, but there is a problem with updating an aws_eks_access_entry where omitting certain fields will not keep them as-is, but replace it with the default that AWS has. So this is consistent AWS API behavior that is currently not modeled correctly in the AWS provider.
After implementing this fix, the behavior is correct and you can update only the username or kubernetes_groups without impacting the other.
Closes #36480

Bugfix: Resource aws_eks_access_entry only updates group OR username

---

.changelog/36485.txt
internal/service/devopsguru/devopsguru_test.go
internal/service/devopsguru/event_sources_config.go
internal/service/devopsguru/event_sources_config_test.go
internal/service/devopsguru/exports_test.go
internal/service/devopsguru/service_package_gen.go
names/names.go
website/docs/r/devopsguru_event_sources_config.html.markdown

This resource will allow practitioners to manage DevOps Guru event sources configurations with Terraform. Event sources are configured at the account level, and therefore should not be included in multiple configurations to avoid persistent differences.
Relates #17919
Closes #36333 
- https://docs.aws.amazon.com/devops-guru/latest/APIReference/API_UpdateEventSourcesConfig.html
```console
% make testacc PKG=devopsguru TESTS=TestAccDevOpsGuru_serial
TF_ACC=1 go1.21.8 test ./internal/service/devopsguru/... -v -count 1 -parallel 20 -run='TestAccDevOpsGuru_serial'  -timeout 360m
--- PASS: TestAccDevOpsGuru_serial (22.05s)
--- PASS: TestAccDevOpsGuru_serial/EventSourcesConfig (22.05s)
--- PASS: …
```

r/aws_devopsguru_event_sources_config: new resource

---

.github/workflows/issues.yml

Add a job to the existing issues workflow that comments on closed issues that looks like:
> [!WARNING]
> This issue has been closed, meaning that any additional comments are hard for our team to see.
>
> Ongoing conversations amongst community members under this issue are welcomed, however, the issue will be locked after 30 days, so these conversations may fit better in the [AWS Provider forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33). If additional assistance is needed, please open a new issue, referencing this one where needed.
- [GitHub documentation on the alerts syntax](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#alerts)
N/a, workflows

Adds workflow job for commenting on closed issues

---

.changelog/30399.txt
.github/workflows/semgrep-ci.yml
GNUmakefile
internal/service/dynamodb/find.go
internal/service/dynamodb/service_package_gen.go
internal/service/dynamodb/status.go
internal/service/dynamodb/table_export.go
internal/service/dynamodb/table_export_test.go
internal/service/dynamodb/wait.go
website/docs/r/codebuild_source_credential.html.markdown
website/docs/r/dynamodb_table_export.html.markdown

Add `aws_dynamodb_table_export` resource.
This change introduces support for the DynamoDB [ExportTableToPointInTime](https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_ExportTableToPointInTime.html) API. 
As issue #28917 describes, that this is not a conventional CRUD resources/API but will prove useful for ops tasks. Here are some observations and notes relating to this implementation:
* AWS provides no mechanism for deleting export table tasks. Even after deleting the table and S3 bucket used in an export, it's still visible in the AWS API - see the [AWS Docs](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/S3DataExport_Requesting.html#S3DataExport_Requesting_CLI_Details)
> You can find information about export tasks you've run in the past by using the …

r/aws_dynamodb_table_export - support DynamoDB ExportTableToPointInTime API.

---

.changelog/36488.txt
internal/service/lexv2models/slot.go

Fixes a typo which causes plan to fail.
Closes #35670
```console
> make testacc TESTS=TestAccLexV2ModelsSlot_ PKG=lexv2models
TF_ACC=1 go1.21.8 test ./internal/service/lexv2models/... -v -count 1 -parallel 20 -run='TestAccLexV2ModelsSlot_'  -timeout 360m
=== RUN   TestAccLexV2ModelsSlot_basic
=== PAUSE TestAccLexV2ModelsSlot_basic
=== RUN   TestAccLexV2ModelsSlot_updateMultipleValuesSetting
=== PAUSE TestAccLexV2ModelsSlot_updateMultipleValuesSetting
=== RUN   TestAccLexV2ModelsSlot_ObfuscationSetting
=== PAUSE TestAccLexV2ModelsSlot_ObfuscationSetting
=== RUN   TestAccLexV2ModelsSlot_disappears
=== PAUSE TestAccLexV2ModelsSlot_disappears
=== CONT  TestAccLexV2ModelsSlot_basic
=== CONT  TestAccLexV2ModelsSlot_ObfuscationSetting …
```

Fix custom payload typo

---

.changelog/36489.txt
internal/service/devopsguru/devopsguru_test.go
internal/service/devopsguru/exports_test.go
internal/service/devopsguru/resource_collection.go
internal/service/devopsguru/resource_collection_test.go
internal/service/devopsguru/service_package_gen.go
website/docs/r/devopsguru_resource_collection.html.markdown

This resource will allow practitioners to manage Amazon DevOps Guru resource collections with Terraform. Resource collections are configured at the account level, so this resource should be configured only once to avoid competing definitions resulting in persistent differences. 
Additional information can be found the in Amazon DevOps Guru User Guide:
https://docs.aws.amazon.com/devops-guru/latest/userguide/welcome.html
Relates #17919 
Closes #36332
Depends on #36410 
Relates #36437
- https://docs.aws.amazon.com/devops-guru/latest/APIReference/API_GetResourceCollection.html
- https://docs.aws.amazon.com/devops-guru/latest/APIReference/API_UpdateResourceCollection.html
```console
% make testacc PKG=devopsguru TESTS=TestAccDevOpsGuru_serial/ResourceCollection/ …
```

r/aws_devopsguru_resource_collection: new resource

---

website/docs/r/appstream_image_builder.html.markdown

This PR is to improve the description of the `access_endpoint` config block attributes for the `aws_appstream_image_builder` resource. What I noticed is that the description for `vpce_id` is consistently incorrect in AWS documentations, so I just used my own wordings for more accuracy. Also, the schema seems to set a lot of attributes to optional but in fact they would be required. For consistency, I still left `vpce_id` as optional.
Closes #33029
Referred to [CreateImageBuilder](https://docs.aws.amazon.com/appstream2/latest/APIReference/API_CreateImageBuilder.html#AppStream2-CreateImageBuilder-request-DomainJoinInfo) in the API reference for schema and descriptions.
n/a

docs: Improve access_endpoint attr desc for aws_appstream_image_builder

---

.changelog/34227.txt
internal/service/quicksight/dashboard.go
internal/service/quicksight/dashboard_test.go
internal/service/quicksight/schema/template_sheet.go
internal/service/quicksight/schema/visual_table.go
internal/service/quicksight/status.go
internal/service/quicksight/wait.go

This PR addresses a bug in the aws_quicksight_dashboard resource.
When terraform updates a dashboard resource, two AWS API calls are made. The first updates the dashboard which results in a new dashboard version. The second call should update the published version of the dashboard to the new version.
The bug manifests when the first call takes a little time, which results in the second call returning an error about the dashboard creation still being in progress.
This is because the provider waits for the dashboard status to change to creation successful, however the API call used is checking the current published version, not the new version just made. As such it returns early and doesn’t actually wait.
This PR fixes this by explicitly waiting for the new version of the dashboard to be …

fix resourceDashboardUpdate

---

.changelog/36538.txt
internal/service/ec2/ec2_host.go
internal/service/ec2/wait.go
website/docs/r/ec2_host.html.markdown

Add user-configurable timeouts to `aws_ec2_host` just like `aws_instance` has.
In AWS sometimes resources like `mac2.metal` instances are depleted within an AZ and a timeout earlier than the default 10 minutes is desired.
_I don't have an AWS account that I could use for testing._

aws_ec2_host: Add configurable timeout

---

docs/acc-test-environment-variables.md
docs/add-a-new-datasource.md
docs/add-a-new-function.md
docs/add-a-new-region.md
docs/add-a-new-resource.md
docs/add-a-new-service.md
docs/aws-go-sdk-migrations.md
docs/aws-go-sdk-versions.md
docs/changelog-process.md
docs/data-handling-and-conversion.md
docs/debugging.md
docs/dependency-updates.md
docs/design-decisions/rds-bluegreen-deployments.md
docs/design-decisions/relationship-resource-design-standards.md
docs/documentation-changes.md
docs/error-handling.md
docs/faq.md
docs/index.md
docs/issue-reporting-and-lifecycle.md
docs/naming.md
docs/prioritization.md
docs/provider-design.md
docs/raising-a-pull-request.md
docs/resource-filtering.md
docs/resource-name-generation.md
docs/resource-tagging.md
docs/retries-and-waiters.md
docs/running-and-writing-acceptance-tests.md
docs/skaff.md
docs/terraform-plugin-migrations.md

This PR aims to improve the quality of **terraform-provider-aws** documentation by addressing various grammar errors, typos, misspellings, and inconsistencies. The goal is to have clear and concise documentation that adheres to standard grammar rules so that users can access accurate information without encountering linguistic hurdles.
**Key changes:**
- typo and misspelling corrections - to prevent confusion among users and enhance the professionalism of the documentation,
- grammar corrections - ensuring proper subject-verb agreement and fixing article usage,
- enhanced readability - by adding missing verbs, prepositions or punctuation marks,
- consistency in terminology.
N/A, docs
N/A, docs
N/A

[docs] Fix terraform-provider-aws documentation typos, misspellings

---

.changelog/36557.txt
internal/framework/flex/auto_expand.go
internal/service/devopsguru/devopsguru_test.go
internal/service/devopsguru/exports_test.go
internal/service/devopsguru/notification_channel.go
internal/service/devopsguru/notification_channel_test.go
internal/service/devopsguru/service_package_gen.go
website/docs/r/devopsguru_notification_channel.html.markdown

This resource will allow practitioners to manage AWS DevOps Guru notification channels with Terraform.
Thing change also adds AutoFlex support for "list of enum" fields.
Relates #17919 
Closes #36334 
Closes #36556
- https://docs.aws.amazon.com/devops-guru/latest/APIReference/API_AddNotificationChannel.html
- https://docs.aws.amazon.com/devops-guru/latest/APIReference/API_ListNotificationChannels.html
- https://docs.aws.amazon.com/devops-guru/latest/APIReference/API_RemoveNotificationChannel.html
```console
% make testacc PKG=devopsguru TESTS=TestAccDevOpsGuru_serial/NotificationChannel
TF_ACC=1 go1.21.8 test ./internal/service/devopsguru/... -v -count 1 -parallel 20 -run='TestAccDevOpsGuru_serial/NotificationChannel'  -timeout …
```

r/aws_devopsguru_notification_channel: new resource 

---

internal/service/iam/instance_profile_test.go
website/docs/r/iam_instance_profile.html.markdown

Closes #8041
```console
% make t T=TestAccIAMInstanceProfile_ K=iam
TF_ACC=1 go1.21.8 test ./internal/service/iam/... -v -count 1 -parallel 20 -run='TestAccIAMInstanceProfile_'  -timeout 360m
=== RUN   TestAccIAMInstanceProfile_tags_null
=== PAUSE TestAccIAMInstanceProfile_tags_null
=== RUN   TestAccIAMInstanceProfile_tags_AddOnUpdate
=== PAUSE TestAccIAMInstanceProfile_tags_AddOnUpdate
=== RUN   TestAccIAMInstanceProfile_tags_EmptyTag_OnCreate
=== PAUSE TestAccIAMInstanceProfile_tags_EmptyTag_OnCreate
=== RUN   TestAccIAMInstanceProfile_tags_EmptyTag_OnUpdate_Add
=== PAUSE TestAccIAMInstanceProfile_tags_EmptyTag_OnUpdate_Add
=== RUN …
```

iam/instance_profile: Clarify docs

---

internal/service/lakeformation/resource_lf_tag.go

Relates #36537
```console
% make testacc TESTARGS="-run=TestAccLakeFormation_serial/ResourceLFTag/\$" PKG=lakeformation
TF_ACC=1 go1.21.8 test ./internal/service/lakeformation/... -v -count 1 -parallel 20  -run=TestAccLakeFormation_serial/ResourceLFTag/ -timeout 360m
--- PASS: TestAccLakeFormation_serial (184.14s)
--- PASS: TestAccLakeFormation_serial/ResourceLFTag (49.99s)
--- PASS: TestAccLakeFormation_serial/ResourceLFTag/basic (12.56s)
--- PASS: TestAccLakeFormation_serial/ResourceLFTag/disappears (11.96s)
--- PASS: TestAccLakeFormation_serial/ResourceLFTag/table (12.73s)
--- PASS: TestAccLakeFormation_serial/ResourceLFTag/tableWithColumns (12.73s)
--- PASS: TestAccLakeFormation_serial/ResourceLFTags (134.15s)
--- PASS: …
```

r/aws_lakeformation_resource_lf_tag: remove unneeded validation

---

website/docs/r/lb_target_group_attachment.html.markdown

Cannot use dynamic values as map keys, change to static keys to cater for the error thrown.
Closes #36541
Successfully run `terraform apply` with the following:
```hcl
resource "aws_vpc" "example" {
cidr_block = "172.16.0.0/16"
tags = {
Name = "tf-example"
}
}
resource "aws_subnet" "example" {
vpc_id            = aws_vpc.example.id
cidr_block        = "172.16.10.0/24"
availability_zone = "ap-southeast-1a"
tags = {
Name = "tf-example"
}
}
data "aws_ami" "amzn-linux-2023-ami" {
most_recent = true
owners      = ["amazon"]
filter {
name   = "name"
values = ["al2023-ami-2023.*-x86_64"]
}
}
resource "aws_instance" "example" {
count         = 3
ami           = data.aws_ami.amzn-linux-2023-ami.id
instance_type = "t2.micro"
subnet_id     = aws_subnet.example.id
tags = {
Name = "tf-example"
}
} …
```

Fix doc on setting up multiple alb targets

---

.changelog/36563.txt
internal/service/route53/zone.go
internal/service/route53/zone_data_source.go
internal/service/route53/zone_test.go

This change handles normalizing the `name` argument such that the value returned from the Route53 API matches what is stored in state. Previously, if the `name` argument included an uppercase letter a persistent difference would be present, causing the resource to be re-created.
Closes #35022 
- https://docs.aws.amazon.com/Route53/latest/APIReference/API_CreateHostedZone.html
```console
% make testacc PKG=route53 TESTS=TestAccRoute53Zone_
TF_ACC=1 go1.21.8 test ./internal/service/route53/... -v -count 1 -parallel 20 -run='TestAccRoute53Zone_'  -timeout 360m
--- PASS: TestAccRoute53Zone_disappears (57.95s)
--- PASS: TestAccRoute53Zone_delegationSetID (65.40s)
--- PASS: TestAccRoute53Zone_basic (66.34s)
--- PASS: …
```

r/aws_route53_zone: prevent re-creation with uppercase name

---

.changelog/36590.txt
internal/service/ec2/ec2_instance.go
internal/service/ec2/ec2_instance_test.go

Closes #36376
```console
% make t T=TestAccEC2Instance_changeInstanceType K=ec2
TF_ACC=1 go1.21.8 test ./internal/service/ec2/... -v -count 1 -parallel 20 -run='TestAccEC2Instance_changeInstanceType'  -timeout 360m
=== RUN   TestAccEC2Instance_changeInstanceType
=== PAUSE TestAccEC2Instance_changeInstanceType
=== RUN   TestAccEC2Instance_changeInstanceTypeReplace
=== PAUSE TestAccEC2Instance_changeInstanceTypeReplace
=== RUN   TestAccEC2Instance_changeInstanceTypeAndUserData
=== PAUSE TestAccEC2Instance_changeInstanceTypeAndUserData
=== RUN   TestAccEC2Instance_changeInstanceTypeAndUserDataBase64
=== PAUSE TestAccEC2Instance_changeInstanceTypeAndUserDataBase64
=== CONT  TestAccEC2Instance_changeInstanceType
=== CONT …
```

ec2/instance: Replace instance when architecture changes

---

.changelog/36277.txt
internal/service/servicecatalogappregistry/application.go
internal/service/servicecatalogappregistry/application_test.go
internal/service/servicecatalogappregistry/exports_test.go
internal/service/servicecatalogappregistry/service_package_gen.go
names/names.go
website/docs/r/servicecatalogappregistry_application.html.markdown

This PR adds a new resource: `aws_servicecatalogappregistry_application`
In AWS this is now also launched as `myApplications`([announcement](https://aws.amazon.com/about-aws/whats-new/2023/11/myapplications-view-manage-applications-aws/), [documentation](https://docs.aws.amazon.com/awsconsolehelpdocs/latest/gsg/aws-myApplications.html))
So the naming can be "confusing", since the application itself technically is a "Service Catalog App Registry Application" (and I wanted to stick with the naming convention). But to somehow make clear it's the base of `myApplication` added it as a note to the documentation (so it's clear and findable if you search for TF and myApplications)
Closes https://github.com/hashicorp/terraform-provider-aws/issues/34702
Closes …

[New Resource] aws_servicecatalogappregistry_application

---

.changelog/36592.txt
internal/service/elasticsearch/domain_policy.go
internal/service/opensearch/domain_policy.go

This change adds logic to retry ValidationExceptions which indicate a domain change is in-progress. When a domain policy change immediately follows domain creation or modification, delays in propagation of the ACTIVE status can cause intermittent ValidationExceptions. These errors are now retried for a short interval (2 minutes), which should allow configurations pairing domain and domain policy resources to complete successfully on the first apply.
Closes #35811
```console
% make testacc PKG=elasticsearch TESTS=TestAccElasticsearchDomainPolicy_
TF_ACC=1 go1.21.8 test ./internal/service/elasticsearch/... -v -count 1 -parallel 20 -run='TestAccElasticsearchDomainPolicy_'  -timeout 360m
--- PASS: …
```

r/aws_opensearch_domain_policy: handle domain update propagation delays

---

.changelog/36534.txt
.github/labeler-pr-triage.yml
internal/errs/fwdiag/diags.go
internal/errs/fwdiag/must.go
internal/service/cloudfrontkeyvaluestore/exports_test.go
internal/service/cloudfrontkeyvaluestore/key.go
internal/service/cloudfrontkeyvaluestore/key_test.go
internal/service/cloudfrontkeyvaluestore/service_package_gen.go
names/data/names_data.csv
website/docs/r/cloudfrontkeyvaluestore_key.html.markdown

This pull requests adds the ability to create and manage Cloudfront Key Value Store Keys with terraform utilizing the `aws_cloudfrontkeyvaluestore_key` resource.
Closes #35793
```console
% make testacc TESTARGS='-run=TestAccCloudFrontKeyValueStoreKey' PKG=cloudfrontkeyvaluestore
TF_ACC=1 go1.21.8 test ./internal/service/cloudfrontkeyvaluestore/... -v -count 1 -parallel 20  -run=TestAccCloudFrontKeyValueStoreKey -timeout 360m
=== RUN   TestAccCloudFrontKeyValueStoreKey_basic
=== PAUSE TestAccCloudFrontKeyValueStoreKey_basic
=== RUN   TestAccCloudFrontKeyValueStoreKey_value
=== PAUSE TestAccCloudFrontKeyValueStoreKey_value
=== RUN   TestAccCloudFrontKeyValueStoreKey_disappears
=== PAUSE TestAccCloudFrontKeyValueStoreKey_disappears …
```

New Resource: `aws_cloudfrontkeyvaluestore_key`

---

.changelog/36597.txt
internal/service/iam/policy_test.go
internal/verify/validate.go
internal/verify/validate_test.go
website/docs/r/glacier_vault_lock.html.markdown
website/docs/r/iam_group_policy.html.markdown
website/docs/r/iam_policy.html.markdown
website/docs/r/iam_role.html.markdown
website/docs/r/iam_role_policy.html.markdown
website/docs/r/iam_user_policy.html.markdown
website/docs/r/media_store_container_policy.html.markdown
website/docs/r/ssoadmin_permission_set_inline_policy.html.markdown
website/docs/r/transfer_access.html.markdown
website/docs/r/transfer_user.html.markdown

This issue has persisted for quite some time and requires resolution.
One factor contributing to the delay in addressing it is the historical issue where leading whitespace would create complications during JSON normalization. However, significant improvements have been made since then, particularly with the enhancement brought by #22067 to our normalization and difference detection processes. As a result, leading whitespace no longer poses a problem, and we have decided to permit it. Given the potential ramifications of this decision, we will carefully monitor for any unforeseen consequences.
Closes #1873
Closes #5887
Closes #21016 (fixed by #22067)
Closes #438 (fixed by #22067)
Relates #22048
```console
% make t T=TestAccIAMPolicy K=iam            …
```

iam/policy: Allow IAM policy leading whitespace

---

.changelog/36589.txt
internal/service/ec2/ec2_instance_metadata_defaults.go
internal/service/ec2/ec2_instance_metadata_defaults_test.go
internal/service/ec2/exports_test.go
internal/service/ec2/service_package_gen.go
website/docs/r/ec2_instance_metadata_defaults.html.markdown

AWS recently released a new API to set the default IMDS behavior globally at the region level, instead of at the EC2 instance level as before. This is extremely useful for practitioners who wish to use "secure defaults" to ensure that instances launched in that region enforce IMDSv2, which is a strongly recommended security practice.
Sample usage:
```hcl
resource "aws_ec2_instance_metadata_defaults" "test" {
http_tokens                 = "required" # non-default
instance_metadata_tags      = "disabled"
http_endpoint               = "enabled"
http_put_response_hop_limit = 1
}
```
I had to bump the AWS SDK v2 version to get support for `GetInstanceMetadataDefaults` / `ModifyInstanceMetadataDefaults`. In addition to acceptance tests, I have also tested this implementation locally with a few …

New resource: aws_ec2_instance_metadata_defaults

---

.changelog/36609.txt
internal/service/secretsmanager/secret_version.go
website/docs/r/secretsmanager_secret_version.html.markdown

This allows the resource to be removed from state gracefully when either the secret or secret version is deleted.
Closes #36607
- https://docs.aws.amazon.com/secretsmanager/latest/userguide/reference_limits.html
```console
% make testacc PKG=secretsmanager TESTS=TestAccSecretsManagerSecretVersion_
TF_ACC=1 go1.21.8 test ./internal/service/secretsmanager/... -v -count 1 -parallel 20 -run='TestAccSecretsManagerSecretVersion_'  -timeout 360m
--- PASS: TestAccSecretsManagerSecretVersion_disappears (15.02s)
--- PASS: TestAccSecretsManagerSecretVersion_Disappears_secret (15.74s)
--- PASS: TestAccSecretsManagerSecretVersion_multipleVersions (16.14s)
--- PASS: TestAccSecretsManagerSecretVersion_basicString (17.43s)
--- PASS: …
```

r/aws_secretsmanager_secret_version: shorten expected error message text

---

.changelog/36586.txt
internal/service/autoscaling/group.go

See #36584
Fix regression on ASG destruction. Only call SetInstanceProtection on instances that are protected.
Re-incorporate logic from #23187
Closes #36584
#23187

ASG check instance protection

---

.changelog/36615.txt
internal/service/applicationinsights/wait.go

In some configurations with `auto_config_enabled = true`, intermittent errors are observed waiting for application creation.
```
│ Error: waiting for ApplicationInsights Application (example) create: unexpected state 'ACTIVE', wanted target 'NOT_CONFIGURED'. last error: %!s(<nil>)
```
The current assumption is that all applications enter a `NOT_CONFIGURED` lifecycle status upon initial creation (which is why this succeeds most of the time in minimal configurations such as our acceptance test), but in some instances can proceed into an `ACTIVE` status before the create waiter has polled for and observed a `NOT_CONFIGURED` status. The AWS documentation on the [LifeCycle argument](https://docs.aws.amazon.com/cloudwatch/latest/APIReference/API_ApplicationInfo.html#appinsights-Type-ApplicationI …

r/aws_applicationinsights_application: ACTIVE is a valid create target status

---

.changelog/34099.txt
internal/service/iam/instance_profile.go

Changed to detect when aws_iam_instance_profile is deleted in the aws environment.
<details>
<summary>example main.tf</summary>
```terraform {
aws = {
version = "~> 5.0"
}
}
}
region = "ap-northeast-1"
}
resource "aws_iam_role" "sample_role" {
name = "sample_role_20231024"
assume_role_policy = <<EOF
{
"Version": "2012-10-17",
"Statement": [
{
"Action": "sts:AssumeRole",
"Principal": {
"Service": "ec2.amazonaws.com"
},
"Effect": "Allow",
"Sid": ""
}
]
}
EOF
}
resource "aws_iam_instance_profile" "sample_profile" {
name  = "sample_profile_20231024"
role = aws_iam_role.sample_role.name
}
```
</details>
```console
terraform apply
aws iam remove-role-from-instance-profile --instance-profile-name "sample_profile_20231024" …
```

 Fix aws_iam_instance_profile detects that the instance profile is not associated with IAM Role.

---

internal/generate/tags/templates/v2/list_tags_body.tmpl
internal/generate/tags/templates/v2/service_tags_slice_body.tmpl

These were spotted during an attempt to migrate `autoscaling` to AWS SDK v2. That service has quite a complex set of tag gen parameters which happened to hit these code paths.
Closes #0000
```console
...
```

generate/tags: Fix a couple of bugs with AWS SDKv2 gen

---

website/docs/r/acmpca_certificate.html.markdown

I have update the document 
Closes https://github.com/hashicorp/terraform-provider-aws/issues/33481.
```console
...
```

key_algorithm argument in the tls_cert_request resource is read only

---

internal/service/iam/policy_document_data_source_test.go

Closes #22959
```console
% make t T=TestAccIAMPolicyDocumentDataSource_ K=iam                              
TF_ACC=1 go1.21.8 test ./internal/service/iam/... -v -count 1 -parallel 20 -run='TestAccIAMPolicyDocumentDataSource_'  -timeout 360m
=== RUN   TestAccIAMPolicyDocumentDataSource_basic
=== PAUSE TestAccIAMPolicyDocumentDataSource_basic
=== RUN   TestAccIAMPolicyDocumentDataSource_singleConditionValue
=== PAUSE TestAccIAMPolicyDocumentDataSource_singleConditionValue
=== RUN   TestAccIAMPolicyDocumentDataSource_multipleConditionKeys
=== PAUSE TestAccIAMPolicyDocumentDataSource_multipleConditionKeys
=== RUN   TestAccIAMPolicyDocumentDataSource_duplicateConditionKeys
=== PAUSE …
```

iam/policy_doc: Test there's no panic

---

.changelog/36560.txt
docs/acc-test-environment-variables.md
internal/service/resourceexplorer2/resourceexplorer2_test.go
internal/service/resourceexplorer2/search_data_source.go
internal/service/resourceexplorer2/search_data_source_test.go
internal/service/resourceexplorer2/service_package_gen.go
website/docs/d/resourceexplorer2_search.html.markdown

New datasource Search for Resource Explorer 2
Relates #36033
```console
> make testacc TESTARGS="-run=TestAccResourceExplorer2_serial/SearchDataSource" PKG=resourceexplorer2
TF_ACC=1 go1.21.8 test ./internal/service/resourceexplorer2/... -v -count 1 -parallel 20  -run=TestAccResourceExplorer2_serial/SearchDataSource -timeout 360m
=== RUN   TestAccResourceExplorer2_serial
=== PAUSE TestAccResourceExplorer2_serial
=== CONT  TestAccResourceExplorer2_serial
=== RUN   TestAccResourceExplorer2_serial/SearchDataSource
=== RUN   TestAccResourceExplorer2_serial/SearchDataSource/basic
=== RUN   TestAccResourceExplorer2_serial/SearchDataSource/indexType
--- PASS: TestAccResourceExplorer2_serial (30.28s)
--- PASS: …
```

New Datasource Resource Explorer2 Search

---

.changelog/36635.txt
internal/service/redshift/cluster.go

Previously an update to `skip_final_snapshot` would trigger a call to the ModifyCluster API, which fails if no other arguments are modified.
Before:
```
~ resource "aws_redshift_cluster" "example" {
id                                   = "tf-redshift-cluster"
~ skip_final_snapshot                  = false -> true
tags                                 = {}
}
Plan: 0 to add, 1 to change, 0 to destroy.
aws_redshift_cluster.example: Modifying... [id=tf-redshift-cluster] ╷
│ Error: modifying Redshift Cluster (tf-redshift-cluster): InvalidParameterCombination: No modifications were requested
│       status code: 400, request id: 0b087c95-ac6b-4ad6-8eed-ded497fb4a2e
│
│   with aws_redshift_cluster.example,
│   on main.tf line 13, in resource …
```

r/aws_redshift_cluster: skip_final_snapshot updates state only

---

.changelog/36640.txt
GNUmakefile
internal/service/iam/exports.go
internal/service/iam/sweep.go
internal/service/iam/user.go
internal/service/iam/user_test.go

Closes #12903
```console
% make t T=TestAccIAMUser K=iam P=12                       
TF_ACC=1 go1.21.8 test ./internal/service/iam/... -v -count 1 -parallel 12 -run='TestAccIAMUser'  -timeout 360m
=== RUN   TestAccIAMUserDataSource_basic
=== PAUSE TestAccIAMUserDataSource_basic
=== RUN   TestAccIAMUserDataSource_tags
=== PAUSE TestAccIAMUserDataSource_tags
=== RUN   TestAccIAMUserGroupMembership_basic
=== PAUSE TestAccIAMUserGroupMembership_basic
=== RUN   TestAccIAMUserLoginProfile_basic
=== PAUSE TestAccIAMUserLoginProfile_basic
=== RUN   TestAccIAMUserLoginProfile_keybase
=== PAUSE TestAccIAMUserLoginProfile_keybase
=== RUN   TestAccIAMUserLoginProfile_keybaseDoesntExist
=== PAUSE TestAccIAMUserLoginProfile_keybaseDoesntExist …
```

iam/user: Force destroy with policies

---

internal/flex/flex.go
internal/service/lakeformation/data_lake_settings.go
internal/service/lakeformation/permissions.go

```console
% make testacc TESTARGS="-run=TestAccLakeFormation_serial/DataLakeSettings\|TestAccLakeFormation_serial/Permissions" PKG=lakeformation
TF_ACC=1 go1.21.8 test ./internal/service/lakeformation/... -v -count 1 -parallel 20  -run=TestAccLakeFormation_serial/DataLakeSettings\|TestAccLakeFormation_serial/Permissions -timeout 360m
--- PASS: TestAccLakeFormation_serial (818.66s)
--- PASS: TestAccLakeFormation_serial/PermissionsDataSource (163.71s)
--- PASS: TestAccLakeFormation_serial/PermissionsDataSource/dataCellsFilter (22.72s)
--- PASS: TestAccLakeFormation_serial/PermissionsDataSource/database (20.52s)
--- PASS: TestAccLakeFormation_serial/PermissionsDataSource/dataLocation (18.53s)
--- PASS: …
```

r/lakeformation_permissions: use flex functions to flatten/expand permissions

---

.changelog/36655.txt
internal/service/redshift/cluster.go
internal/service/redshift/cluster_test.go

This change fixes an issue preventing clusters with the `snapshot_copy` block configured from updating any nested arguments.
Before:
```console
% make testacc PKG=redshift TESTS=TestAccRedshiftCluster_snapshotCopy
TF_ACC=1 go1.21.8 test ./internal/service/redshift/... -v -count 1 -parallel 20 -run='TestAccRedshiftCluster_snapshotCopy'  -timeout 360m
=== RUN   TestAccRedshiftCluster_snapshotCopy
=== PAUSE TestAccRedshiftCluster_snapshotCopy
=== CONT  TestAccRedshiftCluster_snapshotCopy
cluster_test.go:311: Step 2/3 error: Error running apply: exit status 1
Error: updating Redshift Cluster (tf-acc-test-3261690877562655687) snapshot_copy: enabling snapshot copy: SnapshotCopyAlreadyEnabledFault: Snapshot Copy is already enabled on …
```

r/aws_redshift_cluster: allow snapshot_copy modifications

---

.changelog/36656.txt
internal/service/devopsguru/devopsguru_test.go
internal/service/devopsguru/notification_channel_data_source.go
internal/service/devopsguru/notification_channel_data_source_test.go
internal/service/devopsguru/service_package_gen.go
website/docs/d/devopsguru_notification_channel.html.markdown
website/docs/r/devopsguru_notification_channel.html.markdown

This data source will allow practitioners to read AWS DevOps Guru notification channel data with Terraform.
- Relates #17919 
- Closes #36354 
- https://docs.aws.amazon.com/devops-guru/latest/APIReference/API_ListNotificationChannels.html
```console
% make testacc PKG=devopsguru TESTS=TestAccDevOpsGuru_serial/NotificationChannelDataSource/
TF_ACC=1 go1.21.8 test ./internal/service/devopsguru/... -v -count 1 -parallel 20 -run='TestAccDevOpsGuru_serial/NotificationChannelDataSource/'  -timeout 360m
=== RUN   TestAccDevOpsGuru_serial
=== PAUSE TestAccDevOpsGuru_serial
=== CONT  TestAccDevOpsGuru_serial
=== RUN   TestAccDevOpsGuru_serial/NotificationChannelDataSource
=== RUN …
```

d/aws_devopsguru_notification_channel: new data source

---

.changelog/35231.txt
internal/service/ecr/lifecycle_policy.go
internal/service/ecr/lifecycle_policy_test.go

This PR is to fix change detection issues (specifically the lack of it) with the `tagPatternList` attribute in the ECR lifecycle policy JSON for the `aws_ecr_lifecycle_policy` resource.
Closes #35184
[Lifecycle policies](https://docs.aws.amazon.com/AmazonECR/latest/userguide/LifecyclePolicies.html) provides more details on the syntax of the policy JSON.
Note: `TestAccECRLifecyclePolicy_detectTagPatternListDiff` is a new test case.
```console
$ make testacc TESTS=TestAccECRLifecyclePolicy_ PKG=ecr
TF_ACC=1 go test ./internal/service/ecr/... -v -count 1 -parallel 20 -run='TestAccECRLifecyclePolicy_'  -timeout 360m
=== RUN   TestAccECRLifecyclePolicy_basic
=== PAUSE TestAccECRLifecyclePolicy_basic
=== RUN …
```

fix: Add missing aws_ecr_lifecycle_policy tagPatternList change detection

---

internal/conns/awsclient.go
internal/conns/config.go
internal/conns/conns.go
internal/service/ds/region.go
internal/service/dynamodb/table.go
internal/service/dynamodb/table_replica.go
internal/service/dynamodb/table_replica_test.go
internal/service/dynamodb/table_test.go
internal/service/dynamodb/wait.go
internal/service/efs/replication_configuration.go
internal/service/kms/exports.go
internal/service/kms/find.go
internal/service/kms/replica_external_key.go
internal/service/kms/replica_key.go
internal/service/opsworks/stack.go
internal/service/opsworks/stack_test.go
internal/service/rds/custom_db_engine_version.go
internal/service/rds/global_cluster.go
internal/service/rds/instance_automated_backups_replication.go

Closes https://github.com/hashicorp/terraform-provider-aws/issues/23694.
```console
% make testacc TESTARGS='-run=TestAccRDSInstanceAutomatedBackupsReplication_basic' PKG=rds ACCTEST_PARALLELISM=2
TF_ACC=1 go1.21.8 test ./internal/service/rds/... -v -count 1 -parallel 2  -run=TestAccRDSInstanceAutomatedBackupsReplication_basic -timeout 360m
=== RUN   TestAccRDSInstanceAutomatedBackupsReplication_basic
=== PAUSE TestAccRDSInstanceAutomatedBackupsReplication_basic
=== CONT  TestAccRDSInstanceAutomatedBackupsReplication_basic
--- PASS: TestAccRDSInstanceAutomatedBackupsReplication_basic (1288.35s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/rds	1299.277s
```
```console
% make testacc …
```

Simplify creation of AWS SDK for Go v1 API clients for alternate AWS Regions

---

.changelog/36659.txt
internal/service/imagebuilder/distribution_configuration.go
internal/service/imagebuilder/distribution_configuration_test.go

This PR is to fix the regular expression in the validation function for the `name` arg of the `ami_distribution_configuration` configuration block for the `aws_imagebuilder_distribution_configuration` resource.
Closes #36610
Referred to [AmiDistributionConfiguration](https://docs.aws.amazon.com/imagebuilder/latest/APIReference/API_AmiDistributionConfiguration.html) for the correct regular expression.
```console
$ make testacc TESTS=TestAccImageBuilderDistributionConfiguration_DistributionAMIDistribution_name PKG=imagebuilder
TF_ACC=1 go test ./internal/service/imagebuilder/... -v -count 1 -parallel 20 -run='TestAccImageBuilderDistributionConfiguration_DistributionAMIDistribution_name'  -timeout 360m
=== RUN …
```

fix: Add '.' to name regex in ami_distribution_configuration block for aws_imagebuilder_distribution_configuration

---

.changelog/36661.txt
internal/service/cognitoidp/user_pool.go
internal/service/cognitoidp/user_pool_test.go
internal/service/cognitoidp/validate.go
internal/service/cognitoidp/validate_test.go

This PR is to fix the validation functions of the `*message` and `*subject` arguments in the `aws_cognito_user_pool` resource, which allows UTF-8 characters, so that the # of characters are counted by runes and not by bytes.
**Note:** When I initially added a new test case with max size messages and subjects, the API will fail with a 413 object too large error. I believe this is a bug with the AWS API since the API specs should technically allow messages up to 20000 characters, including UTF-8. To allow the test case to pass, I've reduced the message sizes to 1000 characters. Meanwhile I've opened an AWS support case to see if they can address it. So be aware that even with this fix, you probably can't use very long messages.
Closes #32607
Referred to …

fix: Count UTF-8 string length by # of chars vs. bytes in message and subject args for aws_cognito_user_pool

---

.changelog/36647.txt
internal/service/servicecatalogappregistry/application.go
internal/service/servicecatalogappregistry/application_data_source.go
internal/service/servicecatalogappregistry/application_data_source_test.go
internal/service/servicecatalogappregistry/application_test.go
website/docs/d/servicecatalogappregistry_application.html.markdown
website/docs/r/servicecatalogappregistry_application.html.markdown

This PR adds the `application_tag` attribute to the `aws_servicecatalogappregistry_application` resource. There is a design flaw in the new resource. It's not the Application's ARN that has to be assigned to the resource.
The actual tag(s) (key and name) are available in the SDK so just needs to be added.
This PR adds the new attribute and updates the documentation. Also implemented this in the tests
Closes #0000
```console
% make testacc TESTS=TestAccServiceCatalogAppRegistryApplication PKG=servicecatalogappregistry
TF_ACC=1 go1.21.8 test ./internal/service/servicecatalogappregistry/... -v -count 1 -parallel 20 -run='TestAccServiceCatalogAppRegistryApplication'  -timeout 360m
=== RUN …
```

Fix/Enhancement: Add application_tag attribute to aws_servicecatalogappregistry_application

---

.changelog/35149.txt
internal/service/batch/findv2.go
internal/service/batch/job_definition.go
internal/service/batch/job_definition_data_source_test.go
internal/service/batch/job_definition_test.go
website/docs/r/batch_job_definition.html.markdown

This change first started as a [larger PR](https://github.com/hashicorp/terraform-provider-aws/pull/34281) and the commits were pulled into a separate PR for isolation
`job_definition` (JD) was previously a ForceNew resource on all parameters. This was interesting because when a JD is deleted in AWS the revision still lasts but is marked as inactive. In some ways, the ForceNew didnt matter because a new revision was being created. This PR modifies the behavior so that instead of deleting each revision as a new is created, we merely add a new one. 
- old revisions are deactivated by default (prior behavior). This can be disabled by new param `deregister_on_new_revision`
- delete now deregisters all JDs with the associated name
- testing delete function (`testAccCheckJobDefinitionDestroy`) …

batch job definition remove force new and increment revisions

---

.changelog/36691.txt
internal/service/ecs/service.go

When you configure
```HCL
resource "aws_ecs_service" "ext" {
...
alarms {
enable   = true
rollback = false
alarm_names = [
"xyz"
]
}
}
```
The `rollback` flag is always set to true. Even though it gets detected as it should be set to false.
Truth be told, the setting also doesn't seem to do anything meaningful on the AWS side with that parameter combination. While it's not documented to not be meaningful.
Still you can configure it as such with the AWS console or API, so given line is a bug none the less.
(I have not touched or run acceptance test, I hope that can be taken care of by the receiving end of this PR)

ECS Service Alarm Config read uses wrong key

---

.changelog/35978.txt
internal/service/glue/data_catalog_encryption_settings.go
internal/service/glue/data_catalog_encryption_settings_data_source.go
internal/service/glue/data_catalog_encryption_settings_test.go
website/docs/cdktf/python/d/glue_data_catalog_encryption_settings.html.markdown
website/docs/d/glue_data_catalog_encryption_settings.html.markdown
website/docs/r/glue_data_catalog_encryption_settings.html.markdown

Add `catalog_encryption_service_role` property to `aws_glue_data_catalog_encryption_settings` (resource and data).
Closes #35978
https://aws.amazon.com/about-aws/whats-new/2024/02/aws-glue-data-catalog-delegating-kms-key-permissions-iam-role/
https://docs.aws.amazon.com/glue/latest/dg/encrypt-glue-data-catalog.html
https://docs.aws.amazon.com/glue/latest/webapi/API_PutDataCatalogEncryptionSettings.html
```console
% make testacc TESTS='TestAccGlue_serial' PKG=glue
TF_ACC=1 go1.21.8 test ./internal/service/glue/... -v -count 1 -parallel 20 -run='TestAccGlue_serial'  -timeout 360m
=== RUN   TestAccGlue_serial
=== PAUSE TestAccGlue_serial
=== CONT  TestAccGlue_serial
=== RUN   TestAccGlue_serial/ResourcePolicy
=== RUN …
```

Add catalog_encryption_service_role to aws_glue_data_catalog_encryption_settings

---

.changelog/36699.txt
internal/service/route53/record.go
internal/service/route53/record_test.go

The response for ListResourceRecordSet encodes special characters like `*` as octal escape sequences. This causes plans to see drift in the alias records where none actually exists.
* https://github.com/hashicorp/terraform/issues/501
This seems unnecessarily involved and expensive for what this PR is trying to accomplish.

r/aws_route53_record(fix): correctly interpret wildcard record names

---

internal/service/transfer/ssh_key_test.go
website/docs/r/transfer_ssh_key.html.markdown

- Fix a couple typos and grammar errors in the acceptance test suite for `aws_transfer_ssh_key`
- Update the example in the `aws_transfer_ssh_key` docs to use [tls_private_key](https://registry.terraform.io/providers/hashicorp/tls/latest/docs/resources/private_key#public_key_openssh) in OpenSSH format and with the `trimspace()` function
N/A
N/A
N/A

aws_transfer_ssh_key: Fix typos in error messages

---

.changelog/36518.txt
internal/errs/diag.go
internal/service/rds/instance.go
internal/service/rds/instance_test.go
website/docs/r/db_instance.html.markdown

The `character_set_name` parameter can only be set when creating a new DB instance. Adds a conflict warning when setting it when `replicate_source_db`, `restore_to_point_in_time`, or `snapshot_identifier` is set. It was already an error when setting it with `s3_import`.
Relates ##20379
```console
% make testacc PKG=rds TESTS='TestAccRDSInstance_\w*characterSet'
instance_test.go:2284: Skipping due to upstream error
--- SKIP: TestAccRDSInstance_ReplicateSourceDB_CrossRegion_characterSet (0.00s)
--- PASS: TestAccRDSInstance_ReplicateSourceDB_characterSet_Replica (2379.74s)
--- PASS: TestAccRDSInstance_ReplicateSourceDB_characterSet_Source (2422.93s)
```

resource/aws_db_instance: Adds warning when setting `character_set_name` on replica- or restore-type resources

---

website/docs/cdktf/python/r/quicksight_data_set.html.markdown
website/docs/cdktf/typescript/r/quicksight_data_set.html.markdown
website/docs/r/quicksight_data_set.html.markdown

"Resource: aws_quicksight_data_set physical_table_map" is (Required) in the documentation, but should have been changed to Optional as of the link Pull Request.
Closes #36744 
```console
...
```

[Docs]: modified aws_quicksight_data_set.physical_table_map from required to optional 

---

.changelog/36740.txt
internal/service/securityhub/configuration_policy.go
internal/service/securityhub/configuration_policy_test.go
website/docs/r/securityhub_configuration_policy.html.markdown

If `enabled_standard_arns` is used, and `service_enabled` is set to `false`, it will be included in the AWS API call. Now it's only added if it is not empty.
This will fix the issue when trying to create a SecurityHub configuration policy without enabling any standards.
Current version ConfigurationPolicy:
```
2024-04-05T09:11:42.103+1030 [DEBUG] provider.terraform-provider-aws_v5.43.0_x5: HTTP Request Sent: ...
http.request.body=
| {"ConfigurationPolicy":{"SecurityHub":{"SecurityControlsConfiguration":{"DisabledSecurityControlIdentifiers":[]},"ServiceEnabled":true}},"Description":"ExampleDescription","Name":"Example"}
```
With the proposed fix:
```
2024-04-05T08:59:08.187+1030 [DEBUG] provider.terraform-provider-aws: HTTP Request Sent: http.request.header.x_amz_security_token="*****" …
```

fix: add enabled_standard_arns if service_enabled is true in aws_securityhub_configuration_policy

---

examples/transit-gateway-cross-account-peering-attachment/main.tf

When peering transit gateways across different accounts, the `attachment_id` needs to be retrieved from the peer account. This `id` can be retrieved by using the `aws_transit_gateway_peering_attachment` data source.
It should be noted that this data source is only necessary when trying to peer on different accounts.
Closes #24677
```console
...
```

update transitgateway cross account peering example

---

website/docs/r/rds_cluster.html.markdown

This PR adds more information about RDS multi-AZ DB cluster support for the `aws_rds_cluster` resource documentation. I also noticed some links to AWS docs are using `http` and some are referring to older locations, so I've fixed them in this PR as well.
Closes #36712
Referred to [CreateDBCluster](https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_CreateDBCluster.html) and [Creating a Multi-AZ DB cluster](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/create-multi-az-db-cluster.html) for more info and wordings.
n/a

docs: Add more info about multi-AZ DB cluster support for aws_rds_cluster

---

website/docs/r/route53_resolver_rule.html.markdown

The documentation of the [`target_ip`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/route53_resolver_rule#target_ip) object of the resource  `aws_route53_resolver_rule` is missing the `protocol` argument.  Based on the existing [implementation](https://github.com/hashicorp/terraform-provider-aws/blob/fb68fa7d9c2a1afc1243902d3a85bcb99cd1e633/internal/service/route53resolver/rule.go#L104) details on the default value have been added.
The valid allowed values have also been added. There is only one unclarity: should we add also `DoH-FIPS`? 
`DoH-FIPS`  is listed as third option in the [AWS SDKv2](https://github.com/aws/aws-sdk-go/blob/90cffbc8aed533a77667a5ee66c3727cb5237b26/service/route53resolver/api.go#L19629) string enum and the `validateFunc` makes use of …

docs: add protocol to target_ip object in route53 resolver rule

---

.github/labeler-issue-triage.yml
internal/generate/issuelabels/file.tmpl

Only `actions/labeler`s configuration file syntax changed, not `github/issue-labeler`'s.
Closes https://github.com/hashicorp/terraform-provider-aws/issues/36785.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/34853.
PR labeler is [working OK](https://github.com/hashicorp/terraform-provider-aws/actions/runs/8604615137/job/23579110421):
```
Run actions/labeler@8558fd74291d67161a8a78ce36a881fa63b766a9
with:
configuration-path: .github/labeler-pr-triage.yml
repo-token: ***
sync-labels: false
dot: true
The configuration file (path: .github/labeler-pr-triage.yml) was found locally, reading from the file
```

Restore `v5.44.0` GH Issue labeler generator

---

internal/framework/flex/auto_expand.go
internal/framework/flex/auto_expand_test.go

This change enables expansion of sets of string enum types with AutoFlex.
```console
% go test ./internal/framework/flex/... -run=TestExpandSetOfStringEnum
--- FAIL: TestExpandSetOfStringEnum (0.00s)
--- FAIL: TestExpandSetOfStringEnum/empty_value (0.00s)
panic: reflect.Set: value of type []string is not assignable to type []flex.testEnum [recovered]
panic: reflect.Set: value of type []string is not assignable to type []flex.testEnum
goroutine 6 [running]:
testing.tRunner.func1.2({0x1014e13a0, 0x140006ba040})
/opt/homebrew/Cellar/go/1.22.2/libexec/src/testing/testing.go:1631 +0x1c4
testing.tRunner.func1()
/opt/homebrew/Cellar/go/1.22.2/libexec/src/testing/testing.go:1634 +0x33c
panic({0x1014e13a0?, 0x140006ba040?})
/opt/homebrew/Cellar/go/1.22.2/libexec/src/runtime/panic.go:770 +0x124 …
```

internal/framework/flex: support set of enum expansion

---

.changelog/36803.txt
internal/service/sagemaker/prebuilt_ecr_image_data_source.go

The `prebuiltECRImageIDByRegion_deepLearning` map is missing the account-id / registry-id for the `af-south-1` (South Africa) region. This PR adds that missing account-id to ensure we avoid below error on `af-south-1`:
```
Planning failed. Terraform encountered an error while generating this plan.
╷
│ Error: no registry ID available for region (af-south-1) and repository (huggingface-pytorch-inference)
│ 
│   with data.aws_sagemaker_prebuilt_ecr_image.deploy_image[0],
│   on main.tf line 29, in data "aws_sagemaker_prebuilt_ecr_image" "deploy_image":
│   29: data "aws_sagemaker_prebuilt_ecr_image" "deploy_image" {
│ 
╵
exit status 1
```
https://docs.aws.amazon.com/sagemaker/latest/dg-ecr-paths/ecr-af-south-1.html#huggingface-af-south-1.title …

fix: add af-south-1 registry id for sagemaker prebuilt ECR image data source

---

.changelog/36804.txt
internal/service/devopsguru/notification_channel.go
internal/service/devopsguru/notification_channel_test.go

This changes the type of the `filters.message_types` and `filters.severities` arguments to `TypeSet`, preventing persistent differences when the AWS API returns elements in a different order than they were sent.
Depends on #36789 
Closes #36731
```console
% make testacc PKG=devopsguru TESTS=TestAccDevOpsGuru_serial/NotificationChannel/
TF_ACC=1 go1.21.8 test ./internal/service/devopsguru/... -v -count 1 -parallel 20 -run='TestAccDevOpsGuru_serial/NotificationChannel/'  -timeout 360m
--- PASS: TestAccDevOpsGuru_serial (48.85s)
--- PASS: TestAccDevOpsGuru_serial/NotificationChannel (37.73s)
--- PASS: TestAccDevOpsGuru_serial/NotificationChannel/disappears (12.13s)
--- PASS: TestAccDevOpsGuru_serial/NotificationChannel/filters …
```

r/aws_devopsguru_notification_channel: fix filters persistent diff

---

internal/framework/flex/auto_expand_test.go

The `TestExpandSetOfStringEnum` and `TestExpandListOfStringEnum` tests both contained a race condition caused by re-use of a slice across test cases. This change initializes new slices for each case instead.
```console
% go test -race ./internal/framework/flex/... -run=TestExpandSetOfStringEnum
ok      github.com/hashicorp/terraform-provider-aws/internal/framework/flex     1.632s
```
```console
% go test -race ./internal/framework/flex/... -run=TestExpandListOfStringEnum
ok      github.com/hashicorp/terraform-provider-aws/internal/framework/flex     1.483s
```
Fixes #36832
Relates #36789

internal/framework/flex(test): fix race condition

---

.changelog/36810.txt
internal/service/redshift/cluster.go
internal/service/redshift/exports_test.go
internal/service/redshift/service_package_gen.go
internal/service/redshift/snapshot_copy.go
internal/service/redshift/snapshot_copy_test.go
website/docs/r/redshift_cluster.html.markdown
website/docs/r/redshift_snapshot_copy.html.markdown

This resource will allow practitioners to manage Amazon Redshift cluster snapshot copy configurations with Terraform. This standalone resource will replace the optional `snapshot_copy` block within the `aws_redshift_cluster` resource, allowing snapshot copy configurations to be managed independent of the parent cluster.
The `snapshot_copy` argument within the `aws_redshift_cluster` resource is now deprecated.
Closes #36637
- https://docs.aws.amazon.com/redshift/latest/APIReference/API_EnableSnapshotCopy.html
- https://docs.aws.amazon.com/redshift/latest/APIReference/API_DisableSnapshotCopy.html
- https://docs.aws.amazon.com/redshift/latest/APIReference/API_ModifySnapshotCopyRetentionPeriod.html
```console
% make testacc PKG=redshift TESTS=TestAccRedshiftSnapshotCopy_
==> Checking that …
```

r/aws_redshift_snapshot_copy: new resource

---

.changelog/36862.txt
internal/service/redshift/cluster.go
internal/service/redshift/exports_test.go
internal/service/redshift/logging.go
internal/service/redshift/logging_test.go
internal/service/redshift/service_package_gen.go
website/docs/r/redshift_cluster.html.markdown
website/docs/r/redshift_logging.html.markdown

This resource will allow practitioners to manage Amazon Redshift cluster logging configurations with Terraform. This standalone resource will replace the optional `logging` block within the `aws_redshift_cluster` resource, allowing logging configurations to be managed independent of the parent cluster.
The `logging` argument within the `aws_redshift_cluster` resource is now deprecated.
Closes #36651
- https://docs.aws.amazon.com/redshift/latest/APIReference/API_EnableLogging.html
- https://docs.aws.amazon.com/redshift/latest/APIReference/API_DisableLogging.html
- https://docs.aws.amazon.com/redshift/latest/APIReference/API_DescribeLoggingStatus.html
```console
% make testacc PKG=redshift TESTS=TestAccRedshiftLogging_
TF_ACC=1 …
```

r/aws_redshift_logging: new resource 

---

website/docs/r/codebuild_webhook.html.markdown

This PR is to update the `aws_codebuild_webhook` resource documentation to include new webhook filter types `WORKFLOW_NAME`, `TAG_NAME`, and `RELEASE_NAME`.
Closes #34627
Referred to [WebhookFilter](https://docs.aws.amazon.com/codebuild/latest/APIReference/API_WebhookFilter.html) as a reference, even though the list of valid values is still not updated in the documentation! Also referred to the source code and CLI commands linked in the associated issue - see comments for details.
n/a

docs: Add new filter type values for aws_codebuild_webhook

---

website/docs/r/ce_anomaly_subscription.html.markdown

This PR is to fix the basic example in the `aws_ce_anomaly_subscription` resource doc. Since `Threshold` is deprecated, `ThresholdExpression` must be included in the request. So for the basic example, I added an absolute threshold, and changed the 2nd example to use a percentage threshold for a bit more variation.
Closes #36853
Checked [AnomalySubscription](https://docs.aws.amazon.com/aws-cost-management/latest/APIReference/API_AnomalySubscription.html) on why the exception occurred.
n/a

docs: Fix basic example in `aws_ce_anomaly_subscription` resource doc

---

website/docs/d/ce_tags.html.markdown

This PR is to fix the heading of the `aws_ce_tags` data source documentation. I also noticed that the configuration blocks are not linked in the argument descriptions, so I added those as well.
Closes #36841
Referred to [GetTags](https://docs.aws.amazon.com/aws-cost-management/latest/APIReference/API_GetTags.html) for some wordings.
n/a

docs: Fix aws_ce_tags data source doc heading + add config block links

---

website/docs/d/ssm_document.html.markdown
website/docs/r/ssm_document.html.markdown

This PR is to add the missing attributes `arn` and `id`. Some argument and attribute descriptions are also outdates, so I updated them in this PR as well. I've also aligned some updated descriptions in the data source reference for consistency.
Closes #36838
Referred to [CreateDocument](https://docs.aws.amazon.com/systems-manager/latest/APIReference/API_CreateDocument.html) and [create-document](https://docs.aws.amazon.com/cli/latest/reference/ssm/create-document.html) for wordings.
n/a

docs: Add missing arg and attr descs for aws_ssm_document

---

website/docs/cdktf/python/r/launch_template.html.markdown
website/docs/cdktf/typescript/r/launch_template.html.markdown
website/docs/r/launch_template.html.markdown

This PR updates the link to the documentation page preserving EBS volumes after EC2 instance termination. The page was referenced as https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/terminating-instances.html#preserving-volumes-on-termination but has since been moved to https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/preserving-volumes-on-termination.html.
_No related or closed issues_
```console
...
```
_NB: This is a documentation only change so I'm hoping it's fine, but if this is still required nonetheless I can add it._

Update preserving EBS volume documentation link

---

website/docs/r/wafv2_web_acl.html.markdown

In https://github.com/hashicorp/terraform-provider-aws/pull/19415 was added possibility to define [`custom_request_handling`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/wafv2_web_acl#custom_request_handling) or [`custom_response`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/wafv2_web_acl#custom_response) blocks for [`default_action`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/wafv2_web_acl#default_action-block) in [`aws_wafv2_web_acl`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/wafv2_web_acl) and for [`action`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/wafv2_rule_group#action) in …

d/wafv2_web_acl: Update default action docs

---

website/docs/r/apigatewayv2_route_response.html.markdown

Including information in docs for enabling two-way communication. Current AWS implementation requires specific inputs that aren't clear from terraform arguments.
Closes #36711
(Overview of integration responses)[https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-websocket-api-integration-responses.html#apigateway-websocket-api-integration-response-overview]

Updated docs for aws_apigatewayv2_route_response

---

.changelog/14270.txt
internal/verify/json.go
internal/verify/json_test.go

Removes carriage return characters from CF stacks during normalize

---

.changelog/25967.txt
internal/service/iam/policy_model.go
internal/service/iam/policy_model_test.go

As depicted here https://github.com/hashicorp/terraform-provider-aws/issues/9042#issuecomment-1132992037
It seems the order of services is not predictable, causing Terraform to think it has changes to perform
This change avoid this by sorting the order always in the same predictable order
Relates #9042

fix(iam): the order of service principals should not matter

---

docs/skaff.md
skaff/cmd/function.go
skaff/cmd/root.go
skaff/convert/convert.go
skaff/convert/convert_test.go
skaff/datasource/datasource.go
skaff/datasource/datasource_test.go
skaff/function/function.go
skaff/function/function.tmpl
skaff/function/functiontest.tmpl
skaff/function/websitedoc.tmpl
skaff/resource/resource.go

This command will allow contributors to generate the scaffolding of a new provider defined function, similar to the functionality available for resources and data sources.
Also moves the helper functions shared across the various subcommand packages into their own, standalone package, `convert`.
Closes #36805 
```console
% cd skaff/ && go test -count=1 ./... && cd ..
?       github.com/hashicorp/terraform-provider-aws/skaff       [no test files]
?       github.com/hashicorp/terraform-provider-aws/skaff/cmd   [no test files]
?       github.com/hashicorp/terraform-provider-aws/skaff/datasource    [no test files]
?       github.com/hashicorp/terraform-provider-aws/skaff/function      [no test files]
?       github.com/hashicorp/terraform-provider-aws/skaff/resource      [no test files]
ok …
```

skaff: add function subcommand

---

internal/service/rds/cluster.go
internal/service/rds/cluster_test.go

Closes #0000
```console
% make t T=TestAccRDSCluster_enableHTTPEndpointProvisioned K=rds
TF_ACC=1 go1.21.8 test ./internal/service/rds/... -v -count 1 -parallel 20 -run='TestAccRDSCluster_enableHTTPEndpointProvisioned'  -timeout 360m
=== RUN   TestAccRDSCluster_enableHTTPEndpointProvisioned
=== PAUSE TestAccRDSCluster_enableHTTPEndpointProvisioned
=== CONT  TestAccRDSCluster_enableHTTPEndpointProvisioned
--- PASS: TestAccRDSCluster_enableHTTPEndpointProvisioned (147.24s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/rds	149.615s
```

rds/cluster: Add test for serverlessv2 with HTTP endpoint enabled

---

internal/function/arn_build_test.go
internal/function/arn_parse_test.go
internal/function/trim_iam_role_path_test.go

Now that Terraform 1.8 is generally available, the `TerraformVersionChecks` pre-check can refer to a proper minimum version, rather than the beta.
```console
% terraform -version
Terraform v1.8.0
on darwin_arm64
```
```console
% go test ./internal/function/...
ok      github.com/hashicorp/terraform-provider-aws/internal/function   10.935s
```

internal/function(test): change terraform version checks to 1.8.0

---

docs/add-a-new-resource.md
docs/resource-tagging.md
docs/terraform-plugin-migrations.md
skaff/resource/resourcefw.tmpl
tools/tfsdk2fw/resource.tmpl

When tag test generation is implemented for a service, the resource type name is required in the `@FrameworkResource` annotation. Updates documentation and the `skaff` and `tfsdk2fw` tools.
Existing code will be updated as generation is rolled out.
Closes #36875

Update documentation for `@FrameworkResource` annotation

---

.changelog/36797.txt
internal/service/organizations/organization.go
internal/service/organizations/organization_data_source.go
internal/service/organizations/organization_data_source_test.go
website/docs/d/organizations_organization.html.markdown
website/docs/r/organizations_organization.html.markdown

add master_account_name to data source
Closes #0000
```console
...
```

add master_account_name to oragnization's data source

---

.changelog/36928.txt
internal/service/fsx/windows_file_system.go
internal/service/fsx/windows_file_system_test.go

Closes #36927
```console
% make t T=TestAccFSxWindowsFileSystem_audit K=fsx
TF_ACC=1 go1.21.8 test ./internal/service/fsx/... -v -count 1 -parallel 20 -run='TestAccFSxWindowsFileSystem_audit'  -timeout 360m
=== RUN   TestAccFSxWindowsFileSystem_audit
=== PAUSE TestAccFSxWindowsFileSystem_audit
=== CONT  TestAccFSxWindowsFileSystem_audit
--- PASS: TestAccFSxWindowsFileSystem_audit (3343.73s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/fsx	3348.663s
```

fsx/windows_file_system: Allow updates to disable audit logs

---

.changelog/36933.txt
internal/service/ec2/errors.go
internal/service/ec2/vpc_dhcp_options.go

The `DeleteDhcpOptions` API can return a slightly different error code than the associated read operation. This change introduces a new error code constant, preventing the delete operation from failing if the DHCP options have been deleted out-of-band.
Before: 
```console
% make testacc PKG=ec2 TESTS="TestAccVPCDHCPOptions_disappears|TestAccVPCDHCPOptionsAssociation_Disappears_dhcp"
TF_ACC=1 go1.21.8 test ./internal/service/ec2/... -v -count 1 -parallel 20 -run='TestAccVPCDHCPOptions_disappears|TestAccVPCDHCPOptionsAssociation_Disappears_dhcp'  -timeout 360m
=== RUN   TestAccVPCDHCPOptionsAssociation_Disappears_dhcp
=== PAUSE TestAccVPCDHCPOptionsAssociation_Disappears_dhcp
=== RUN   TestAccVPCDHCPOptions_disappears
=== PAUSE …
```

r/aws_vpc_dhcp_options: fix not found error handling on delete

---

.changelog/36898.txt
internal/service/ec2/ipam_pool.go
internal/service/ec2/ipam_pool_test.go
website/docs/r/vpc_ipam_pool.html.markdown

Closes #36245
```console
% make testacc TESTS=TestAccIPAM_cascade PKG=ec2
TF_ACC=1 go1.21.8 test ./internal/service/ec2/... -v -count 1 -parallel 20 -run='TestAccIPAM_cascade'  -timeout 360m
=== RUN   TestAccIPAM_cascade
=== PAUSE TestAccIPAM_cascade
=== CONT  TestAccIPAM_cascade
--- PASS: TestAccIPAM_cascade (73.75s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/ec2	92.230s
...
```

f-aws_vpc_ipam_pool support for cascade

---

website/docs/r/organizations_account.html.markdown

`aws_organizations_account` resource has `status` output. But, there is not defined in the docs.
```
" {
"arn" = "arn:aws:organizations:xxxxx:account/o-zzzzzz/111111"
"email" = "test@example.com"
"id" = "xxxxx"
.....
"status" = "ACTIVE"
}
```

Add status output for organizations_account resource

---

.changelog/36942.txt
internal/service/codebuild/project.go
website/docs/r/codebuild_project.html.markdown

This PR is to add GitLab and GitLab Self Managed support to the `report_build_status` and `build_status_config` arguments in the `aws_codebuild_project` resource. The expansion code apparently has code logic to detect the build type to determine whether these arguments/config blocks should be added. Personally I think it should be deferred to the API to determine that, but to fix the issue quickly I just follow suit for now.
Closes #36937
Referred to [ProjectSource](https://docs.aws.amazon.com/codebuild/latest/APIReference/API_ProjectSource.html) for specs and documentation wordings. Also cross-checked the availability of options in the AWS Management Console - note that `git_submodules_config` is grayed out (and thus not supported) for GitLab source types.
**Note:** Unfortunately I don't …

feat: Add GitLab support to report_build_status and build_status_config for aws_codebuild_project

---

.changelog/36969.txt
internal/service/elbv2/const.go
internal/service/elbv2/exports_test.go
internal/service/elbv2/load_balancer.go
internal/service/elbv2/load_balancer_data_source.go
internal/service/elbv2/load_balancer_test.go
internal/service/iam/access_key_test.go
website/docs/r/lb.html.markdown

Closes #36402
```console
% make t T='TestAccELBV2LoadBalancersDataSource_|TestAccELBV2LoadBalancer_' K=elbv2
TF_ACC=1 go1.21.8 test ./internal/service/elbv2/... -v -count 1 -parallel 20 -run='TestAccELBV2LoadBalancersDataSource_|TestAccELBV2LoadBalancer_'  -timeout 360m
=== RUN   TestAccELBV2LoadBalancer_ALB_basic
=== PAUSE TestAccELBV2LoadBalancer_ALB_basic
=== RUN   TestAccELBV2LoadBalancer_NLB_basic
=== PAUSE TestAccELBV2LoadBalancer_NLB_basic
=== RUN   TestAccELBV2LoadBalancer_LoadBalancerType_gateway
=== PAUSE TestAccELBV2LoadBalancer_LoadBalancerType_gateway
=== RUN   TestAccELBV2LoadBalancer_disappears
=== PAUSE TestAccELBV2LoadBalancer_disappears
=== RUN   TestAccELBV2LoadBalancer_nameGenerated
=== PAUSE …
```

elbv2/lb: Add client keep alive

---

.changelog/36953.txt
internal/service/imagebuilder/flex.go
internal/service/imagebuilder/image.go
internal/service/imagebuilder/image_test.go
website/docs/r/imagebuilder_image.html.markdown

ImageBuilder now  allows for customized workflows: https://aws.amazon.com/about-aws/whats-new/2023/12/ec2-image-builder-image-workflows/
This adds that functionality to `imagebuilder_image`
Relates #35045 
CreateImage input: https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/imagebuilder#CreateImageInput
```console
% make testacc TESTS=TestAccImageBuilderImage_workflows PKG=imagebuilder
TF_ACC=1 go1.21.8 test ./internal/service/imagebuilder/... -v -count 1 -parallel 20 -run='TestAccImageBuilderImage_workflows'  -timeout 360m
=== RUN   TestAccImageBuilderImage_workflows
=== PAUSE TestAccImageBuilderImage_workflows
=== CONT  TestAccImageBuilderImage_workflows
--- PASS: TestAccImageBuilderImage_workflows (1046.22s)
PASS
ok …
```

r/imagebuilder_image: adds workflow functionality

---

.changelog/36982.txt
internal/service/cloudformation/stack_set.go
internal/service/cloudformation/status.go
internal/service/cloudformation/wait.go

Relates to #32536
```console
% make t T=TestAccCloudFormationStackSet_ K=cloudformation 
TF_ACC=1 go1.21.8 test ./internal/service/cloudformation/... -v -count 1 -parallel 20 -run='TestAccCloudFormationStackSet_'  -timeout 360m
=== RUN   TestAccCloudFormationStackSet_basic
=== PAUSE TestAccCloudFormationStackSet_basic
=== RUN   TestAccCloudFormationStackSet_disappears
=== PAUSE TestAccCloudFormationStackSet_disappears
=== RUN   TestAccCloudFormationStackSet_administrationRoleARN
=== PAUSE TestAccCloudFormationStackSet_administrationRoleARN
=== RUN   TestAccCloudFormationStackSet_description
=== PAUSE TestAccCloudFormationStackSet_description
=== RUN   TestAccCloudFormationStackSet_executionRoleName
=== PAUSE …
```

cloudformation/stack_set: Add retry on create

---

.changelog/35413.txt
go.mod
go.sum
internal/service/verifiedpermissions/exports_test.go
internal/service/verifiedpermissions/policy.go
internal/service/verifiedpermissions/policy_test.go
internal/service/verifiedpermissions/service_package_gen.go
internal/service/verifiedpermissions/sweep.go
internal/sweep/register_gen_test.go
website/docs/r/verifiedpermissions_policy.html.markdown

Adding Verified Permission Policy
WIP - Need help
Relates #32158
Closes #35412
https://docs.aws.amazon.com/verifiedpermissions/latest/apireference/API_CreatePolicy.html
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-verifiedpermissions-policy.html
```console
...
```

feat: add aws_verifiedpermissions_policy

---

website/docs/r/codecommit_repository.html.markdown

Fix a typo in the documentation for `r/aws_codecommit_repository`
When the `aws_codecommit_repository` resource was enhanced to add the `kms_key_id` parameter in https://github.com/hashicorp/terraform-provider-aws/pull/35095, the documentation added for the new parameter had a typo in it, and closed the name of the fallback AWS-managed key with a double backtick ` `` ` instead of a single `. 
This results in [the name not rendering properly on the terraform provider registry website](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/codecommit_repository#kms_key_id), and for some strange reason I haven't pinned down yet, only sometimes breaks a tool I use that parses the terraform provider documentation. I'll take care of fixing the tool, but I thought I'd open …

[docs] Typo fix in website docs

---

.changelog/37059.txt
internal/service/sagemaker/app_image_config.go
internal/service/sagemaker/app_image_config_test.go
website/docs/r/sagemaker_app_image_config.html.markdown

Closes #36828
Closes #36321
```console
...
```

r/sagemaker_app_image_config - add `code_editor_app_image_config`

---

internal/framework/flex/auto_flatten.go
internal/framework/flex/auto_flatten_test.go
internal/framework/flex/autoflex_test.go
internal/framework/flex/string.go
internal/json/smithy.go
internal/service/opensearchserverless/access_policy.go
internal/service/opensearchserverless/access_policy_data_source.go
internal/service/opensearchserverless/lifecycle_policy.go
internal/service/opensearchserverless/lifecycle_policy_data_source.go

Auto flex understands AWS interface types that convert JSON
`document.Interface` contains the following:
- MarshalSmithyDocument()
- UnmarshalSmithyDocument()
Relates #36508
```console
% make testacc TESTARGS='-run=TestAccOpenSearchServerlessLifecyclePolicy_\|TestAccOpenSearchServerlessLifecyclePolicyDataSource_\|TestAccOpenSearchServerlessAccessPolicy_\|TestAccOpenSearchServerlessAccessPolicyDataSource_' PKG=opensearchserverless
TF_ACC=1 go1.22.2 test ./internal/service/opensearchserverless/... -v -count 1 -parallel 20  -run=TestAccOpenSearchServerlessLifecyclePolicy_\|TestAccOpenSearchServerlessLifecyclePolicyDataSource_\|TestAccOpenSearchServerlessAccessPolicy_\|TestAccOpenSearchServerlessAccessPolicyDataSource_ -timeout 360m …
```

autoflex: json interface

---

.changelog/37069.txt
internal/service/cloudformation/stack_set.go
internal/service/cloudformation/stack_set_test.go
website/docs/r/cloudformation_stack_set.html.markdown

When using a delegation administrator account with `aws_cloudformation_stack_set`, if the IAM User or Role does not have the `organizations:ListDelegatedAdministrators` permission, the AWS API returns the error
> ValidationError: Account used is not a delegated administrator
instead of indicating that there are not sufficient permissions.
Adds guidance to the error message to point to the IAM permissions.
Closes #32536
```console
% make testacc PKG=cloudformation TESTS=TestAccCloudFormationStackSet_
--- SKIP: TestAccCloudFormationStackSet_delegatedAdministrator (1.05s)
--- SKIP: TestAccCloudFormationStackSet_autoDeploymentEnabled (1.50s)
--- SKIP: TestAccCloudFormationStackSet_autoDeploymentDisabled (1.54s)
--- PASS: TestAccCloudFormationStackSet_managedExecution (42.52s)
--- PASS: …
```

resource/aws_cloudformation_stack_set: Adds guidance about required permissions to error message

---

internal/framework/flex/auto_flatten.go
internal/framework/flex/auto_flatten_test.go

Avoids loss of equivalence when flattening `float32`s by using [`InexactFloat64`](https://pkg.go.dev/github.com/shopspring/decimal#Decimal.InexactFloat64).
Closes https://github.com/hashicorp/terraform-provider-aws/issues/37103.
```console
% go test ./internal/framework/flex 
--- FAIL: TestFlattenSimpleNestedBlockWithFloat32 (0.00s)
--- FAIL: TestFlattenSimpleNestedBlockWithFloat32/single_nested_valid_value (0.00s)
auto_flatten_test.go:991: unexpected diff (+wanted, -got):   &flex.tf01{
  	Field1: s"1",
- 	Field2: basetypes.Float64Value{
- 		state: 2,
- 		value: &big.Float{prec: 53, form: 1, mant: big.nat{11805915943291322368}, exp: -6},
- 	},
+ 	Field2: basetypes.Float64Value{
+ 		state: 2,
+ 		value: &big.Float{prec: 53, form: 1, mant: big.nat{11805916207174113280}, exp: -6},
+ 	},
  } …
```

AutoFlEx: Avoid loss of equivalence when flattening `float32`

---

internal/acctest/acctest.go
internal/framework/flex/list.go
internal/service/bedrockagent/agent.go
internal/service/bedrockagent/bedrockagent_test.go
internal/service/bedrockagent/knowledge_base.go
internal/service/bedrockagent/knowledge_base_test.go
internal/service/rds/cluster_instance_test.go

Makes the Aurora Cluster used in `aws_bedrockagent_knowledge_base` acceptance tests publicly accessible so that tests can be run from a laptop.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/36783.
```console
% make testacc TESTARGS='-run=TestAccBedrockAgent_serial/KnowledgeBase/basicRDS\|TestAccBedrockAgent_serial/KnowledgeBase/disappears\|TestAccBedrockAgent_serial/KnowledgeBase/tags' PKG=bedrockagent ACCTEST_PARALLELISM=1
TF_ACC=1 go1.22.2 test ./internal/service/bedrockagent/... -v -count 1 -parallel 1  -run=TestAccBedrockAgent_serial/KnowledgeBase/basicRDS\|TestAccBedrockAgent_serial/KnowledgeBase/disappears\|TestAccBedrockAgent_serial/KnowledgeBase/tags -timeout 360m
=== RUN   TestAccBedrockAgent_serial
=== …
```

r/aws_bedrockagent_knowledge_base: Aurora Cluster is publicly accessible in acceptance tests

---

website/docs/r/auditmanager_framework.html.markdown

This PR is to improve the description of the `control_sets` and `controls` configuration block arguments for the `aws_auditmanager_framework` resource. Earlier description mentions the word "list" (copied from the AWS API reference) which leaves some room for confusion about the data type.
Closes #37000
Referred to documentation for EKS resources, e.g. [aws_eks_fargate_profile](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/eks_fargate_profile) for patterns in describing config block arguments.
n/a

docs: Improved desc for control_sets and controls blocks for aws_auditmanager_framework resource

---

website/docs/r/verifiedpermissions_policy.html.markdown

Closes #37115
```console
...
```

d/aws_verifiedpermissions_policy: fix documentation

---

.teamcity/scripts/provider_tests/acceptance_tests.sh
.teamcity/scripts/provider_tests/unit_tests.sh
internal/sdkv2/resource_differ.go
internal/semver/semver.go
internal/semver/semver_test.go
internal/service/elasticache/replication_group.go
internal/service/elasticsearch/domain.go
internal/service/kafka/cluster.go
internal/service/lambda/function.go
internal/service/lambda/layer_version_permission.go
internal/service/lexmodels/bot.go
internal/service/lexmodels/intent.go
internal/service/lexmodels/slot_type.go
internal/service/opensearch/domain.go
internal/service/s3/bucket_object.go
internal/service/s3/object.go
internal/service/sns/topic.go
internal/service/sqs/queue.go
internal/service/ssm/patch_baseline.go

Moves the `internal/verify/ResourceDiffer` type to the `internal/sdkv2` package.

Tech debt: Move `verify/ResourceDiffer` to `sdkv2` package

---

internal/framework/flex/auto_expand.go
internal/framework/flex/auto_expand_test.go
internal/framework/flex/auto_flatten_test.go
internal/framework/flex/autoflex_test.go
internal/framework/types/smithy_json.go
internal/framework/types/smithy_json_test.go
internal/service/opensearchserverless/lifecycle_policy.go

First pass at expanding JSON strings into Smithy objects
Uses `jsontypes.Normalized` as the standard for validating the document
```console
% go test -count=1 ./internal/framework/flex/... -run=TestFlatten\|TestExpand -v
--- PASS: TestFlattenFrameworkStringValueMapLegacy (0.00s)
--- PASS: TestFlattenFrameworkStringValueMapLegacy/two_elements (0.00s)
--- PASS: TestFlattenFrameworkStringValueMapLegacy/zero_elements (0.00s)
--- PASS: TestFlattenFrameworkStringValueMapLegacy/nil_map (0.00s)
--- PASS: TestExpandFrameworkStringSet (0.00s)
--- PASS: TestExpandFrameworkStringSet/null (0.00s)
--- PASS: TestExpandFrameworkStringSet/zero_elements (0.00s)
--- PASS: TestExpandFrameworkStringSet/unknown (0.00s)
--- PASS: TestExpandFrameworkStringSet/two_elements (0.00s)
--- PASS: …
```

autoflex/ expand json interface type

---

internal/service/opensearchserverless/collection.go
internal/service/opensearchserverless/collection_data_source.go

Use autoflex in collection resource and datasource.
```console
> make testacc TESTARGS="-run=TestAccOpenSearchServerlessCollection_" PKG=opensearchserverless
TF_ACC=1 go1.22.2 test ./internal/service/opensearchserverless/... -v -count 1 -parallel 20  -run=TestAccOpenSearchServerlessCollection_ -timeout 360m
=== RUN   TestAccOpenSearchServerlessCollection_basic
=== PAUSE TestAccOpenSearchServerlessCollection_basic
=== RUN   TestAccOpenSearchServerlessCollection_standbyReplicas
=== PAUSE TestAccOpenSearchServerlessCollection_standbyReplicas
=== RUN   TestAccOpenSearchServerlessCollection_tags
=== PAUSE TestAccOpenSearchServerlessCollection_tags
=== RUN   TestAccOpenSearchServerlessCollection_update
=== PAUSE …
```

f-aws_opensearchserverless_collection autoflex

---

.changelog/37189.txt
internal/service/bcmdataexports/export.go
internal/service/bcmdataexports/export_test.go
website/docs/r/bcmdataexports_export.html.markdown

This PR does not fix the issue but highlights it in a new test. The test `TestAccBCMDataExportsExport_curSubset` selects all the columns except `line_item_resource_id` and returns no error. 
Relates #37126
```console
% make t T=TestAccBCMDataExportsExport_curSubset K=bcmdataexports
TF_ACC=1 go1.22.2 test ./internal/service/bcmdataexports/... -v -count 1 -parallel 20 -run='TestAccBCMDataExportsExport_curSubset'  -timeout 360m
=== RUN   TestAccBCMDataExportsExport_curSubset
=== PAUSE TestAccBCMDataExportsExport_curSubset
=== CONT  TestAccBCMDataExportsExport_curSubset
--- PASS: TestAccBCMDataExportsExport_curSubset (21.20s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/bcmdataexports	23.638s
```

bcmdataexports/export: Add test for bad column

---

.changelog/37180.txt
internal/service/ec2/vpc_endpoint_test.go

Acceptance tests `TestAccVPCEndpoint_ignoreEquivalent` and `TestAccVPCEndpoint_gatewayPolicy` both use a data source to retrieve the service name for DynamoDB as part of testing gateway endpoints. AWS recently announced interface endpoint support for DynamoDB - previously DynamoDB supported a gateway endpoint only.  This changes updates the HCL in the acceptance tests to explicitly request a gateway type endpoint, preventing the tests from failing due to ambiguity about the requested endpoint type.
Before:
```
$ make testacc TESTS="TestAccVPCEndpoint_ignoreEquivalent|TestAccVPCEndpoint_gatewayPolicy" PKG=ec2                                
TF_ACC=1 go1.21.8 test ./internal/service/ec2/... -v -count 1 -parallel 20 …
```

r/aws_vpc_endpoint: fix multiple services matched in DynamoDB gateway endpoint tests

---

website/docs/r/sagemaker_pipeline.html.markdown

Minor documentation fix for resource [aws_sagemaker_pipeline](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sagemaker_pipeline), had description for pipeline name in the argument `role_arn`

:pencil: docs fix for role_arn argument

---

.changelog/37189.txt
.changelog/37205.txt
internal/framework/flex/auto_expand.go
internal/framework/flex/auto_expand_test.go
internal/framework/flex/auto_flatten.go
internal/framework/flex/auto_flatten_test.go
internal/framework/flex/autoflex_test.go
internal/service/bcmdataexports/export.go
internal/service/bcmdataexports/export_test.go
website/docs/r/bcmdataexports_export.html.markdown

Closes #37126
```console
% make testacc TESTARGS="-run=TestAccBCMDataExportsExport_" PKG=bcmdataexports
TF_ACC=1 go1.22.2 test ./internal/service/bcmdataexports/... -v -count 1 -parallel 20  -run=TestAccBCMDataExportsExport_ -timeout 360m
--- PASS: TestAccBCMDataExportsExport_curSubset (18.99s)
--- PASS: TestAccBCMDataExportsExport_disappears (19.11s)
--- PASS: TestAccBCMDataExportsExport_basic (21.43s)
--- PASS: TestAccBCMDataExportsExport_update (29.31s)
--- PASS: TestAccBCMDataExportsExport_updateTable (31.95s)
--- PASS: TestAccBCMDataExportsExport_tags (41.44s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/bcmdataexports	46.669s
```

r/aws_bcmdataexports_export: fix error on table configuration

---

website/docs/r/bcmdataexports_export.html.markdown

This resource was added in v5.47.0 and I took it for a test run. We have an existing v2.0 export that was manually created, and I wanted to import it into terraform management.
It wasn't clear from the docs what format the ID should be in, but by reading the provider source I could see it was the export ARN. I thought I'd mention that in the docs to help others.
Interestingly, finding the export ARN from the AWS web console wasn't easy. The URL was the only option I could find.
Relates: #36847

Improve import docs for aws_bcmdataexports_export resource

---

tools/awssdkpatch/patch.tmpl

This change will covert the assignment and conversion of enum types when being passed into Input and read from Output structs, respectively.
See this related item in the AWS SDK migration guide:
- https://hashicorp.github.io/terraform-provider-aws/aws-go-sdk-migrations/#input-structs
Relates #32976

tools/awssdkpatch: enum type input/output patch

---

internal/framework/flex/auto_expand.go
internal/framework/flex/auto_expand_test.go
internal/framework/flex/auto_flatten.go
internal/framework/flex/auto_flatten_test.go
internal/framework/flex/autoflex.go

This change implements AutoFlex options, allowing custom options to be passed to `flex.Expand` or `flex.Flatten`. The changes include:
- Adding a new `AutoFlexOptions` struct, which stores all configurable options
- Embedding the `AutoFlexOptions` struct into the `autoExpand` and `autoFlatten` flexer structs
- Adjusting the `AutoFlexOptionsFunc` signature to accept a pointer to `AutoFlexOptions`
As a first use case, the `IgnoreFieldNames` option was added. This option is a slice of strings, with a default value of `[]string{"Tags"}`. This replaces the previously hardcoded logic which skipped processing of any fields named `Tags`, and instead makes this configurable. Test cases have been added to exercise the behavior with default options and overrides to remove defaults and add custom …

autoflex: wire up option functions, add `IgnoreFieldNames` option

---

internal/service/ec2/ebs_default_kms_key_data_source_test.go
internal/service/ec2/ebs_volume_attachment.go

```console
=== CONT  TestAccEC2EBSVolumeAttachment_disappears
ebs_volume_attachment_test.go:185: Error running post-test destroy, there may be dangling resources: exit status 1
```
```console
% make testacc TESTARGS="-run=TestAccEC2EBSDefaultKMSKeyDataSource_basic\|TestAccEC2EBSVolumeAttachment_disappears" PKG=ec2
TF_ACC=1 go1.22.2 test ./internal/service/ec2/... -v -count 1 -parallel 20  -run=TestAccEC2EBSDefaultKMSKeyDataSource_basic\|TestAccEC2EBSVolumeAttachment_disappears -timeout 360m
--- PASS: TestAccEC2EBSDefaultKMSKeyDataSource_basic (11.18s)
--- PASS: TestAccEC2EBSVolumeAttachment_disappears (108.27s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/ec2	114.023s
```

td/fix various EBS test failures

---

.github/workflows/regressions.yml

Updates the regression Slack notifier to use `pull_request_target` rather than `pull_request`. This ensures that the action runs without needing to be approved, and that it can access the necessary secrets.
N/a, Actions

Ensure regressions action runs on pull_request_target

---

.changelog/37251.txt
internal/service/rds/orderable_instance_data_source.go

RDS `DescribeOrderableDBInstanceOptions` `MaxRecords` is 1000.
Doc: https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_DescribeOrderableDBInstanceOptions.html
Closes #37221 
Closes #37258
Introduced in: https://github.com/hashicorp/terraform-provider-aws/pull/35698
```console
% make t T=TestAccRDSOrderableInstanceDataSource_ K=rds
...
```

fix(rds): DescribeOrderableDBInstanceOptionsInput MaxRecords to 1000

---

internal/service/datazone/domain.go
internal/service/datazone/domain_test.go
internal/service/datazone/environment_blueprint_configuration.go
internal/service/datazone/environment_blueprint_configuration_test.go
internal/service/datazone/environment_blueprint_data_source.go
internal/service/datazone/environment_blueprint_data_source_test.go
internal/service/datazone/errors.go
internal/service/datazone/exports_test.go
internal/service/datazone/service_package_gen.go
website/docs/d/datazone_environment_blueprint.html.markdown
website/docs/r/datazone_domain.html.markdown
website/docs/r/datazone_environment_blueprint_configuration.html.markdown

Add resources for DataZone:
- Domain
- Environment Blueprint Configuration
Additionally add a data source for Environment Blueprints in order to retrieve the IDs of managed blueprints without hardcoding.
Relates #33792
https://docs.aws.amazon.com/datazone/latest/userguide/datazone-concepts.html
```console
$ AWS_REGION=ap-southeast-2 AWS_PROFILE=default make testacc TESTS=TestAccDataZone PKG=datazone
TF_ACC=1 go1.21.8 test ./internal/service/datazone/... -v -count 1 -parallel 20 -run='TestAccDataZone'  -timeout 360m
=== RUN   TestAccDataZoneDomain_basic
=== PAUSE TestAccDataZoneDomain_basic
=== RUN   TestAccDataZoneDomain_disappears
=== PAUSE TestAccDataZoneDomain_disappears
=== RUN   TestAccDataZoneDomain_kms_key_identifier
=== …
```

feat(datazone): add domain and environment blueprint configuration resources

---

.changelog/37140.txt
internal/service/kms/key.go
internal/service/kms/key_test.go
website/docs/r/kms_key.html.markdown

`rotation_period_in_days` enables a custom rotation period when you enable key rotation.
I've included it as an argument instead of using a separate resource, as enablement of key rotation was already included in the `aws_kms_key` resource.
**Edit:** I've rebased on `main` as #37092 is now merged
Closes #36948
[RotationPeriodInDays AWS docs](https://docs.aws.amazon.com/kms/latest/APIReference/API_EnableKeyRotation.html#API_EnableKeyRotation_RequestSyntax)
```console
% make testacc TESTS=TestAccKMSKey_rotation PKG=kms 
TF_ACC=1 go1.22.2 test ./internal/service/kms/... -v -count 1 -parallel 20 -run='TestAccKMSKey_rotation'  -timeout 360m
=== RUN   TestAccKMSKey_rotation
=== PAUSE TestAccKMSKey_rotation
=== CONT …
```

`r/kms_key`: add support for `rotation_period_in_days`

---

tools/awssdkpatch/patch.tmpl

By switching the metavariable from an `identifier` to an `expression`, this patch will now also be able to patch cases where the function argument is a struct field. For example, the following case works with an `identifier` metavariable:
```go
var thing []*string
// match
d.Set("thing", aws.StringValueSlice(thing))
```
But if a struct field is passed, the patch does not match:
```go
type Output struct {
Field []*string
}
// No match
d.Set("thing", aws.StringValueSlice(out.Field))
```
Changing to an `expression` means anything that has a value (and can therefore be passed into a function) will now match.
Ref: https://github.com/uber-go/gopatch/blob/main/docs/Appendix.md#identifiers-vs-expressions-vs-statements
Relates #32976

tools/awssdkpatch: use expression for string slice/map patch

---

.ci/.semgrep.yml
internal/service/meta/region_data_source.go
internal/service/meta/region_data_source_test.go

Closes #37293
```console
% make t T=TestAcc K=meta
TF_ACC=1 go1.22.2 test ./internal/service/meta/... -v -count 1 -parallel 20 -run='TestAcc'  -timeout 360m
=== RUN   TestAccMetaARNDataSource_basic
=== PAUSE TestAccMetaARNDataSource_basic
=== RUN   TestAccMetaARNDataSource_s3Bucket
=== PAUSE TestAccMetaARNDataSource_s3Bucket
=== RUN   TestAccMetaBillingServiceAccountDataSource_basic
=== PAUSE TestAccMetaBillingServiceAccountDataSource_basic
=== RUN   TestAccMetaDefaultTagsDataSource_basic
=== PAUSE TestAccMetaDefaultTagsDataSource_basic
=== RUN   TestAccMetaDefaultTagsDataSource_empty
=== PAUSE TestAccMetaDefaultTagsDataSource_empty
=== RUN   TestAccMetaDefaultTagsDataSource_multiple
=== PAUSE …
```

meta: Prefer constants over string literals

---

website/docs/r/glue_data_catalog_encryption_settings.html.markdown

This PR is to add the missing valid value `SSE-KMS-WITH-SERVICE-ROLE` for the `catalog_encryption_mode` argument in the `aws_glue_data_catalog_encryption_settings` resource doc.
Closes #37243
Referred to [EncryptionAtRest](https://docs.aws.amazon.com/glue/latest/webapi/API_EncryptionAtRest.html) to confirm list of valid values.
n/a

docs: Add missing SSE-KMS-WITH-SERVICE-ROLE valid value to catalog_encryption_mode for aws_glue_data_catalog_encryption_settings

---

website/docs/r/securityhub_standards_subscription.html.markdown

This PR is to add the ARN of the newly released AWS Resource Tagging Standard to the `aws_securityhub_standards_subscription` resource documentation. I've also changed the partition segment of all ARNs to `${var.partition}` to account for partition differences.
Closes #37272
[AWS Resource Tagging Standard](https://docs.aws.amazon.com/securityhub/latest/userguide/standards-tagging.html) for more info, although the page has the wrong standard name - it shouldn't have the account ID. I checked the ARN using AWS CLI and verify it by enabling it in the CLI as well:
```bash
$ aws securityhub batch-enable-standards --standards-subscription-requests StandardsArn=arn:aws:securityhub:ca-central-1::standards/aws-resource-ta
gging-standard/v/1.0.0 …
```

docs: Add AWS Resource Tagging Standard ARN to the ref list in the aws_securityhub_standards_subscription resource doc

---

website/docs/r/db_instance.html.markdown

Update mysql major version for db_instance to 8.0
Support for mysql 5.7 has been discontinued and AWS now offers extended support which can be up-to 100 times more costly: https://aws.amazon.com/blogs/aws/your-mysql-5-7-and-postgresql-11-databases-will-be-automatically-enrolled-into-amazon-rds-extended-support
This bump to the major version avoids billing surprises (once the free tier expires).

Docs: Update mysql major version for db_instance to 8.0

---

internal/service/bedrockagent/agent_action_group_test.go
internal/service/bedrockagent/agent_alias_test.go
internal/service/bedrockagent/agent_test.go

Fixes a broken IAM role reference in the base configuration shared by all acceptance tests.
Also aligns acceptance test names with the corresponding resources.
Relates #36851
```console
% make testacc PKG=bedrockagent TESTS=TestAccBedrockAgentAgent_
TF_ACC=1 go1.22.2 test ./internal/service/bedrockagent/... -v -count 1 -parallel 20 -run='TestAccBedrockAgentAgent_'  -timeout 360m
--- PASS: TestAccBedrockAgentAgent_full (19.72s)
--- PASS: TestAccBedrockAgentAgent_basic (23.29s)
--- PASS: TestAccBedrockAgentAgent_tags (35.97s)
--- PASS: TestAccBedrockAgentAgent_update (39.29s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/bedrockagent       44.344s
```
```console
% make testacc PKG=bedrockagent …
```

r/aws_bedrockagent_agent(test): fix test configuration

---

.changelog/37332.txt
internal/service/securitylake/exports_test.go
internal/service/securitylake/securitylake_test.go
internal/service/securitylake/subscriber_notification.go
internal/service/securitylake/subscriber_notification_test.go
website/docs/r/securitylake_subscriber.html.markdown
website/docs/r/securitylake_subscriber_notification.html.markdown

Various fixes to `aws_securitylake_subscriber_notification`:
* Deprecates `endpoint_id` and adds `subscriber_endpoint` to match documentation and API
* Requires value for `configuration.https_notification_configuration.endpoint`
* Better handles `import` by reading available data from API
* Marks `configuration.https_notification_configuration. authorization_api_key_value` as `Sensitive`
* Allows resource to be modified in-place
Relates #36325
```console
% make testacc PKG=securitylake TESTS=TestAccSecurityLake_serial/SubscriberNotification
--- PASS: TestAccSecurityLake_serial (481.97s)
--- PASS: TestAccSecurityLake_serial/SubscriberNotification (481.97s)
--- PASS: TestAccSecurityLake_serial/SubscriberNotification/sqs_basic (62.10s)
--- PASS: …
```

resource/aws_securitylake_subscriber_notification: Fixes

---

.changelog/36983.txt
website/docs/r/ecs_service.html.markdown

`name`, `Iam_role`, `desired_count` are all attribute arguments to `ecs_service` but the docs listed them both as attribute-arguments and as additional attributes. My brain tripped over this when it came to `iam_role` because I thought to myself "wait, I thought the IAM role was an argument on this resource". 
This isn't a big change and maybe it too much of a nit pick vs perhaps it's useful to keep this thing in multiple places, but I know I tripped over it and figured I cast a PR out there to see if this is thing kind of thing that's worth a quick clean up for the next me/ person like me. 
Closes #0000
```console
...
```

r/ecs_sevice doc: removes duplicate references

---

.changelog/37394.txt
internal/service/elasticsearch/domain_structure.go
internal/service/opensearch/domain.go
internal/service/opensearch/domain_structure.go

Previously omitting this optional argument resulted in a failure when creating or updating the domain:
```
Error: modifying config for OpenSearch Domain: ValidationException: 1 validation error detected: Value '' at 'autoTuneOptions.rollbackOnDisable' failed to satisfy constraint: Member must satisfy enum value set: [DEFAULT_ROLLBACK, NO_ROLLBACK]
```
The `auto_tune_options` expander logic has been updated to properly handle cases where `rollback_on_disable` is unset. 
Also adds a missing waiter in create operation when `auto_tune_options` are configured.
Closes #37234
```console
% make testacc PKG=opensearch TESTS=TestAccOpenSearchDomain_autoTuneOptions
TF_ACC=1 go1.22.2 test ./internal/service/opensearch/... -v -count 1 …
```

r/aws_opensearch_domain: handle unset auto_tune_options.rollback_on_disable

---

.changelog/35677.txt
internal/service/iam/policy_document_data_source.go
internal/service/iam/policy_document_data_source_test.go
website/docs/cdktf/python/d/iam_policy_document.html.markdown
website/docs/d/iam_policy_document.html.markdown

This PR adds a new attribute to the `aws_iam_policy_document` data source to enable producing smaller JSONs. AWS Service Control Policies have a character limit of 5120 characters and in many cases I have seen policies approaching this limit.
The current `json` attribute is padded which wastes characters. One way to solve this is to wrap the `json` attribute in the `jsondecode` and `jsonencode` functions as these don't pad the output.
Having this as a direct attribute from the data source seems more efficient and allows for cleaner terraform files.
https://docs.aws.amazon.com/organizations/latest/userguide/org_troubleshoot_policies.html#scptoolong
I haven't currently got access to an environment where I can run the tests but from running the provider locally I can see the length is …

Add `minified_json` to `aws_iam_policy_document` data source

---

website/docs/r/route.html.markdown

Associating `vpc_endpoint_id` and `destination_prefix_list_id` on the resource causes a conflict because it is not allowed in  the AWS API. Documentation update advises to use the `aws_vpc_endpoint_route_table_association` resource instead.
Closes #18607
```console
...
```

d/aws_route: update documentation for `vpc_route_id`

---

.changelog/37405.txt
internal/service/bedrockagent/agent.go
internal/service/bedrockagent/agent_test.go
website/docs/r/bedrockagent_agent.html.markdown

This changes removes logic in the read operation which adjusted the `prepare_agent` argument based on whether or not the agent status was `Prepared`. Now the configured `prepare_agent` value is always used, regardless of the status of the agent. If omitted, the default value of `true` is inherited, meaning that by default agents will always be prepared as part of the create or update operation. The `prepare_agent` value is now also set to `true` when an agent is imported.
Closes #37162
- https://docs.aws.amazon.com/bedrock/latest/APIReference/API_agent_PrepareAgent.html
```console
% make testacc PKG=bedrockagent TESTS=TestAccBedrockAgentAgent_
TF_ACC=1 go1.22.2 test ./internal/service/bedrockagent/... -v -count 1 -parallel 20 …
```

r/aws_bedrockagent_agent: use configured `prepare_agent` value 

---

.changelog/37347.txt
internal/service/glue/job.go

Added a check for nil values.
Closes https://github.com/hashicorp/terraform-provider-aws/issues/37325
```console
➜  terraform-provider-aws git:(main) make testacc TESTARGS='-run=TestAccGlueJob_notificationProperty' PKG=glue
TF_ACC=1 go1.22.2 test ./internal/service/glue/... -v -count 1 -parallel 20  -run=TestAccGlueJob_notificationProperty -timeout 360m
=== RUN   TestAccGlueJob_notificationProperty
=== PAUSE TestAccGlueJob_notificationProperty
=== CONT  TestAccGlueJob_notificationProperty
--- PASS: TestAccGlueJob_notificationProperty (59.50s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/glue       64.144s
```

Added `nil` check for `notification_property` on the `glue_job` resource

---

.changelog/37433.txt
internal/service/lakeformation/data_cells_filter.go
internal/service/lakeformation/data_cells_filter_test.go
internal/service/lakeformation/lakeformation_test.go

Closes #36574
```console
% make testacc TESTARGS="-run=TestAccLakeFormation_serial/DataCellsFilter/" PKG=lakeformation
TF_ACC=1 go1.22.2 test ./internal/service/lakeformation/... -v -count 1 -parallel 20  -run=TestAccLakeFormation_serial/DataCellsFilter/ -timeout 360m
--- PASS: TestAccLakeFormation_serial (60.35s)
--- PASS: TestAccLakeFormation_serial/DataCellsFilter (60.35s)
--- PASS: TestAccLakeFormation_serial/DataCellsFilter/columnWildcard (12.59s)
--- PASS: TestAccLakeFormation_serial/DataCellsFilter/disappears (12.74s)
--- PASS: TestAccLakeFormation_serial/DataCellsFilter/rowFilter (20.37s)
--- PASS: TestAccLakeFormation_serial/DataCellsFilter/basic (14.64s)
PASS
ok …
```

r/lakeformation_data_cells_filter: fix error when using `row_filter.all_rows_wildcard`

---

internal/generate/tagstests/test.go.gtpl
internal/service/accessanalyzer/analyzer_tags_gen_test.go
internal/service/acmpca/certificate_authority_tags_gen_test.go
internal/service/batch/compute_environment_tags_gen_test.go
internal/service/batch/job_definition_tags_gen_test.go
internal/service/batch/job_queue_tags_gen_test.go
internal/service/batch/scheduling_policy_tags_gen_test.go
internal/service/iam/instance_profile_tags_gen_test.go
internal/service/iam/openid_connect_provider_tags_gen_test.go
internal/service/iam/policy_tags_gen_test.go
internal/service/iam/role_tags_gen_test.go
internal/service/iam/service_linked_role_tags_gen_test.go
internal/service/iam/user_tags_gen_test.go
internal/service/iam/virtual_mfa_device_tags_gen_test.go
internal/service/servicecatalog/portfolio_tags_gen_test.go
internal/service/servicecatalog/product_tags_gen_test.go
internal/service/servicecatalog/provisioned_product_tags_test.go
internal/service/xray/group_tags_gen_test.go
internal/service/xray/sampling_rule_tags_gen_test.go

Uses `names` constants in generated tagging tests

Uses `names` constants in generated tagging tests

---

.changelog/37306.txt
internal/service/bedrock/foundation_models_data_source.go
internal/service/bedrock/foundation_models_data_source_test.go

This PR is to fix the regex for the `by_provider` argument in the `aws_bedrock_foundation_models` data source.
Closes #37305
Referred to [ListFoundationModels](https://docs.aws.amazon.com/bedrock/latest/APIReference/API_ListFoundationModels.html) for the correct regex.
```bash
$ make testacc TESTS=TestAccBedrockFoundationModelsDataSource_ PKG=bedrock
TF_ACC=1 go1.22.2 test ./internal/service/bedrock/... -v -count 1 -parallel 20 -run='TestAccBedrockFoundationModelsDataSource_'  -timeout 360m
=== RUN   TestAccBedrockFoundationModelsDataSource_basic
=== PAUSE TestAccBedrockFoundationModelsDataSource_basic
=== RUN   TestAccBedrockFoundationModelsDataSource_byCustomizationType
=== PAUSE …
```

fix: Fix by_provider regex for aws_bedrock_foundation_models data source

---

docs/resource-tagging.md
skaff/datasource/websitedoc.tmpl
skaff/resource/websitedoc.tmpl
website/docs/r/codeguruprofiler_profiling_group.html.markdown
website/docs/r/m2_application.html.markdown
website/docs/r/rekognition_collection.html.markdown

Updates the `skaff` website template to use generic descriptions for the `tags` and `tags_all` attributes. Previously a hardcoded workspace resource name was present in the description, which would need manually adjusted. Also updates the descriptions in the contributor documentation to match skaff, and fixes places where the errant hardcoded resource name was included in `skaff`-generated registry documentation.
Relates #32513

skaff: consistent tags, tags_all website descriptions

---

internal/service/bedrock/foundation_models_data_source_test.go

Fixes a failing semgrep finding on `main`.
https://github.com/hashicorp/terraform-provider-aws/actions/runs/9062758632/job/24897300698
Relates #37306
```console
% make testacc PKG=bedrock TESTS=TestAccBedrockFoundationModelsDataSource_
TF_ACC=1 go1.22.2 test ./internal/service/bedrock/... -v -count 1 -parallel 20 -run='TestAccBedrockFoundationModelsDataSource_'  -timeout 360m
--- PASS: TestAccBedrockFoundationModelsDataSource_byCustomizationType (9.86s)
--- PASS: TestAccBedrockFoundationModelsDataSource_byInferenceType (10.17s)
--- PASS: TestAccBedrockFoundationModelsDataSource_byProvider (10.20s)
--- PASS: TestAccBedrockFoundationModelsDataSource_basic (10.24s)
--- PASS: TestAccBedrockFoundationModelsDataSource_byOutputModality …
```

d/aws_bedrock_foundation_models(test): fix semgrep finding

---

website/docs/r/db_instance.html.markdown

Relates [#34216 Add postgres to supported blue green engines](https://github.com/hashicorp/terraform-provider-aws/pull/34216)

rds: Mention PostgreSQL in low-downtime update docs

---

GNUmakefile
docs/aws-go-sdk-migrations.md
tools/awssdkpatch/README.md
tools/awssdkpatch/main.go
tools/awssdkpatch/patch.tmpl

The new `-multiclient` flag supports services where both V1 and V2 AWS SDK clients are used simultaneously. This is a common pattern for large services (e.g. `ec2`), where the migration will take place in parts. When set, the generated patch file will include additional patches to migrate tagging and filter helper functions to the appropriate V2 variant.
Relates https://github.com/hashicorp/terraform-provider-aws/issues/32976

tools/awssdkpatch: add multiclient support

---

website/docs/r/cloud9_environment_ec2.html.markdown

As mentioned in #37554, the AWS API docs for [CreateEnvironmentEC2](https://docs.aws.amazon.com/cloud9/latest/APIReference/API_CreateEnvironmentEC2.html#cloud9-CreateEnvironmentEC2-request-imageId) have been updated where `imageId` no longer specifies Amazon Linux 1. Probably because it has reached end of life.
Again as mentioned in the linked issue, it would be worth investigating if create a Cloud9 instance with Amazon Linux 1 via Terraform is even possible or would the API return an error but that should be tracked in another issue/pr.
Closes #37554
- https://docs.aws.amazon.com/cloud9/latest/APIReference/API_CreateEnvironmentEC2.html#cloud9-CreateEnvironmentEC2-request-imageId
N/A

docs!: remove al1 references from image_id for `aws_cloud9_environment_ec2`

---

website/docs/r/securityhub_configuration_policy_association.markdown

Correct securityhub_configuration_policy_association import documentation.
Tested; also matches the other import documentation right above it.

Correct securityhub_configuration_policy_association import docs

---

.changelog/37565.txt
internal/service/route53/service_package.go

Change `route53` region default to `us-east-1`
Closes #34016
```
> make testacc TESTS=TestAccRoute53Record_ PKG=route53
TF_ACC=1 go1.22.2 test ./internal/service/route53/... -v -count 1 -parallel 20 -run='TestAccRoute53Record_'  -timeout 360m
=== RUN   TestAccRoute53Record_basic
=== PAUSE TestAccRoute53Record_basic
=== RUN   TestAccRoute53Record_disappears
=== PAUSE TestAccRoute53Record_disappears
=== RUN   TestAccRoute53Record_Disappears_multipleRecords
=== PAUSE TestAccRoute53Record_Disappears_multipleRecords
=== RUN   TestAccRoute53Record_underscored
=== PAUSE TestAccRoute53Record_underscored
=== RUN   TestAccRoute53Record_fqdn
=== PAUSE TestAccRoute53Record_fqdn
=== RUN   TestAccRoute53Record_trailingPeriodAndZoneID
=== PAUSE …
```

r/route53_record Check region set

---

docs/development-environment.md

While setting up the Terraform AWS provider locally I noticed an issue with the instructions.
I believe the original version contains a mistake, as executing the command leads to an error:
```console
$ ls -la ./$GOPATH/bin/terraform-provider-aws
ls: .//Users/<xyz_user>/go/bin/terraform-provider-aws: No such file or directory
```
Instead, when the fixed version of the command is run, the expected output is received:
```console
$ ls -la $GOPATH/bin/terraform-provider-aws
-rwxr-xr-x@ 1 <xyz_user>  user  709759170 May 13 21:05 /Users/<xyz_user>/go/bin/terraform-provider-aws
```
Closes #37477
Webpage with mistake:
https://hashicorp.github.io/terraform-provider-aws/development-environment/

[DOCS] fix console command in developer environment setup instructions

---

.github/actionlint.yaml
.github/workflows/acctest-terraform-lint.yml
.github/workflows/examples.yml
.github/workflows/golangci-lint.yml
.github/workflows/goreleaser-ci.yml
.github/workflows/provider.yml
.github/workflows/providerlint.yml
.github/workflows/website.yml

👋 Greetings! 
To align with Github’s removal of [custom labels on larger runners](https://github.blog/changelog/2023-02-15-github-actions-removal-of-additional-label-option-for-github-hosted-larger-runners/), this PR is updating the labels defined in your Github Action jobs. Moving forward, only one label (the name of GH runner type)  will be needed to ensure an appropriate runner is used for your GHA job.
Please review for accuracy and merge before May 27, 2024. Thank you!
Closes #0000
```console
...
```

Use single custom label in GHA jobs

---

.changelog/37581.txt
internal/service/m2/deployment.go
internal/service/m2/deployment_test.go

**Before:**
```console
% make testacc TESTARGS="-run=TestAccM2Deployment_start" PKG=m2
TF_ACC=1 go1.22.2 test ./internal/service/m2/... -v -count 1 -parallel 20  -run=TestAccM2Deployment_nostart -timeout 360m
=== RUN   TestAccM2Deployment_start
=== PAUSE TestAccM2Deployment_start
=== CONT  TestAccM2Deployment_start
deployment_test.go:97: Step 3/3 error: Error running apply: exit status 1
Error: Provider returned invalid result object after apply
After the apply operation, the provider still indicated an unknown value for
aws_m2_deployment.test.deployment_id. All values must be known after apply,
so this is always a bug in the provider and should be reported in the
provider's own repository. Terraform will still save the other …
```

r/aws_m2_deployment: set `deployment_id` on start/stop

---

.changelog/37618.txt
internal/service/route53/traffic_policy_document_model.go
website/docs/cdktf/typescript/d/route53_traffic_policy_document.html.markdown
website/docs/d/route53_traffic_policy_document.html.markdown

This PR adds application-load-balancer endpoint type according to https://docs.aws.amazon.com/Route53/latest/APIReference/api-policies-traffic-policy-document-format.html to the traffic_policy_document_model.
Closes https://github.com/hashicorp/terraform-provider-aws/issues/34315.

chore(route53): add traffic policy document endpoint type 'application-load-balancer'

---

.changelog/37628.txt
internal/service/ec2/service_package_gen.go
internal/service/ec2/vpc_endpoint.go
internal/service/ec2/vpc_endpoint_private_dns.go
internal/service/ec2/vpc_endpoint_private_dns_test.go
website/docs/r/vpc_endpoint_private_dns.html.markdown

This resource will allow practitioners to enable and disable private DNS for a VPC endpoint.
This allows private DNS to be enabled on the VPC endpoint distinctly from the initial create operation, supporting use cases where additional actions must be taken between creation of the endpoint and enabling of private DNS.
```terraform
resource "aws_vpc_endpoint" "test" {
vpc_id            = aws_vpc.test.id
service_name      = "producer service name"
vpc_endpoint_type = "Interface"
}
resource "aws_vpc_endpoint_connection_accepter" "test" {
vpc_endpoint_service_id = "producer service id"
vpc_endpoint_id         = aws_vpc_endpoint.test.id
}
resource "aws_vpc_endpoint_private_dns" "test" {
depends_on = [aws_vpc_endpoint_connection_accepter.test]
vpc_endpoint_id     = aws_vpc_endpoint.test.id …
```

r/aws_vpc_endpoint_private_dns: new resource

---

.changelog/37643.txt
internal/service/lambda/exports_test.go
internal/service/lambda/runtime_management_config.go
internal/service/lambda/runtime_management_config_test.go
internal/service/lambda/service_package_gen.go
website/docs/r/lambda_runtime_management_config.html.markdown

This resource will allow practitioners to manage AWS Lambda runtime management configurations via Terraform.
Closes #29210
Closes #32138
- https://docs.aws.amazon.com/lambda/latest/api/API_PutRuntimeManagementConfig.html
- https://docs.aws.amazon.com/lambda/latest/api/API_GetRuntimeManagementConfig.html
- https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html
```console
% make testacc PKG=lambda TESTS="TestAccLambdaRuntimeManagementConfig_"
TF_ACC=1 go1.22.2 test ./internal/service/lambda/... -v -count 1 -parallel 20 -run='TestAccLambdaRuntimeManagementConfig_'  -timeout 360m
--- PASS: TestAccLambdaRuntimeManagementConfig_disappears_Function (37.05s)
--- PASS: TestAccLambdaRuntimeManagementConfig_basic (38.77s)
--- …
```

r/aws_lambda_runtime_management_config: new resource

---

.changelog/37624.txt
internal/service/ec2/findv2.go
internal/service/lambda/function.go
website/docs/r/lambda_function.html.markdown

This change implements an alternative approach for improving deletion times of security groups associated with deleted Lambda functions. Previously, the `replace_security_groups_on_destroy` and `replacement_security_group_ids` were deprecated as AWS began disallowing modification of the security groups assigned to orphaned ENI's left behind after destruction of a Lambda function.
The deprecations on these arguments will be removed with this re-implementation. Instead of attempting to modify orphaned ENI's after deletion of the function, this approach replaces the security groups assigned in the functions VPC configuration, waits for the configuration update to complete, and then deletes the function. This re-ordering allows for faster security group deletion as the lambda function ENI's …

r/aws_lambda_function: re-implement replace_security_groups_on_destroy

---

website/docs/r/lakeformation_lf_tag.html.markdown

The maximum number of values that can be defined for a LF-Tag is 1000.
Closes #37608
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lakeformation_lf_tag
```console
...
```

Update lakeformation tag value limitation to real in documentation

---

.changelog/37669.txt
internal/service/lambda/function.go
internal/service/lambda/function_data_source.go
internal/service/lambda/function_data_source_test.go
internal/service/lambda/function_test.go
website/docs/d/lambda_function.html.markdown
website/docs/r/lambda_function.html.markdown

Relates #17989
Relates #37646
```console
% make testacc TESTARGS="-run=TestAccLambdaFunction" PKG=lambda
TF_ACC=1 go1.22.2 test ./internal/service/lambda/... -v -count 1 -parallel 20  -run=TestAccLambdaFunction -timeout 360m
function_test.go:977: Environment variable AWS_LAMBDA_IMAGE_LATEST_ID is not set
--- SKIP: TestAccLambdaFunction_image (0.00s)
--- PASS: TestAccLambdaFunctionDataSource_ephemeralStorage (43.30s)
--- PASS: TestAccLambdaFunctionDataSource_basic (56.38s)
--- PASS: TestAccLambdaFunctionEventInvokeConfig_QualifierFunctionName_arn (77.34s)
--- PASS: TestAccLambdaFunctionEventInvokeConfig_Destination_swap (85.73s)
--- PASS: TestAccLambdaFunctionEventInvokeConfig_FunctionName_arn (91.51s)
--- PASS: …
```

r/lambda_function: fix drift when `source_code_hash` does not match upstream value

---

.changelog/37218.txt
internal/service/chatbot/service_package_gen.go
internal/service/chatbot/slack_workspace_data_source.go
internal/service/chatbot/slack_workspace_data_source_test.go
website/docs/d/chatbot_slack_workspace.html.markdown

Added a new data source Slack Workspace for the service AWS Chatbot
Relates #12304
or 
Closes #37123
https://awscli.amazonaws.com/v2/documentation/api/latest/reference/chatbot/delete-slack-workspace-authorization.html
https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/chatbot#Client.DescribeSlackWorkspaces
```console
$ make testacc PKG=chatbot TESTS=TestAccChatbotSlackWorkspace*
TF_ACC=1 go1.22.2 test ./internal/service/chatbot/... -v -count 1 -parallel 20 -run='TestAccChatbotSlackWorkspace*'  -timeout 360m
=== RUN   TestAccChatbotSlackWorkspaceDataSource_basic
=== PAUSE TestAccChatbotSlackWorkspaceDataSource_basic
=== CONT  TestAccChatbotSlackWorkspaceDataSource_basic
--- PASS: TestAccChatbotSlackWorkspaceDataSource_basic …
```

Added the data source for a Slack Workspace

---

.changelog/37019.txt
GNUmakefile
internal/service/ecs/service.go
internal/service/ecs/service_test.go
internal/service/ecs/task_definition.go
internal/service/ecs/task_definition_test.go
website/docs/r/ecs_service.html.markdown
website/docs/r/ecs_task_definition.html.markdown

Closes #35279
```console
% make testacc TESTS=TestAccECSTaskDefinition_configuredAtLaunch PKG=ecs
TF_ACC=1 go1.22.2 test ./internal/service/ecs/... -v -count 1 -parallel 20 -run='TestAccECSTaskDefinition_configuredAtLaunch'  -timeout 360m
=== RUN   TestAccECSTaskDefinition_configuredAtLaunch
=== PAUSE TestAccECSTaskDefinition_configuredAtLaunch
=== CONT  TestAccECSTaskDefinition_configuredAtLaunch
--- PASS: TestAccECSTaskDefinition_configuredAtLaunch (54.53s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/ecs	126.627s
% make testacc TESTS=TestAccECSTaskDefinition_ PKG=ecs                    
TF_ACC=1 go1.22.2 test ./internal/service/ecs/... -v …
```

f-aws_ecs_service: support for EBS

---

.changelog/37685.txt
internal/service/route53/zone.go

The migration of route53 to AWS SDK V2 introduced a regression which caused the `name_servers` attribute to be set to a list of record sets, rather than a list of name servers. This change returns the value to a list of name servers.
Given a minimal configuration with an internal VPC and associated hosted zone, the `name_servers` output from `v5.51.0` is:
```
Apply complete! Resources: 2 added, 0 changed, 0 destroyed.
Outputs:
name_server = tolist([
"jb-test.internal.",
"jb-test.internal.",
])
```
After this patch is applied:
```
Apply complete! Resources: 2 added, 0 changed, 0 destroyed.
Outputs:
name_server = tolist([
"ns-0.awsdns-00.com.",
"ns-1024.awsdns-00.org.",
"ns-1536.awsdns-00.co.uk.",
"ns-512.awsdns-00.net.",
])
```
Closes #37681
Relates #37510
```console
% make testacc …
```

r/aws_route53_zone: fix invalid `name_servers` values

---

.changelog/37686.txt
internal/service/route53/zone_data_source.go
internal/service/route53/zone_data_source_test.go

As part of the migration of the `route53` service to AWS SDK V2, an `ExactlyOneOf` constraint was added to the `name` and `zone_id` arguments in the `aws_route53_zone` data source. This is technically a regression as the data source functioned correctly in earlier versions when `name` is set and `zone_id` is an empty string. This change reverts the constraint and adds an acceptance test to cover this potential configuration.
Closes #37683
Relates #37510 
```console
% make testacc PKG=route53 TESTS=TestAccRoute53ZoneDataSource_
TF_ACC=1 go1.22.2 test ./internal/service/route53/... -v -count 1 -parallel 20 -run='TestAccRoute53ZoneDataSource_'  -timeout 360m
--- PASS: TestAccRoute53ZoneDataSource_id (91.23s)
--- PASS: …
```

d/aws_route53_zone: permit both `name` and `zone_id` arguments

---

website/docs/d/chatbot_slack_workspace.html.markdown

When trying to use the new data source, I copied the example from the docs and found out that the argument is referenced incorrectly. This tiny PR fixes it
As per the [guidelines](https://hashicorp.github.io/terraform-provider-aws/changelog-process/) no changelog is required for documentation changes

fix wrong argument name in example and a  typo

---

.changelog/37714.txt
internal/service/kinesisanalyticsv2/application.go
internal/service/kinesisanalyticsv2/application_test.go
website/docs/r/kinesisanalyticsv2_application.html.markdown

Closes #31130
```console
% make testacc TESTS=TestAccKinesisAnalyticsV2Application_applicationMode PKG=kinesisanalyticsv2
TF_ACC=1 go1.22.2 test ./internal/service/kinesisanalyticsv2/... -v -count 1 -parallel 20 -run='TestAccKinesisAnalyticsV2Application_applicationMode'  -timeout 360m
=== RUN   TestAccKinesisAnalyticsV2Application_applicationMode
=== PAUSE TestAccKinesisAnalyticsV2Application_applicationMode
=== CONT  TestAccKinesisAnalyticsV2Application_applicationMode
--- PASS: TestAccKinesisAnalyticsV2Application_applicationMode (52.05s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/kinesisanalyticsv2	71.031s
--- PASS: TestAccKinesisAnalyticsV2Application_FlinkApplicationStartApplication_onCreate …
```

r/kinesisanalyticsv2_application: add `application_mode` attribute

---

website/docs/r/s3_access_point.html.markdown

Add information about the naming convention  to the required argument `name`.
Closes #37656 
* [Link](https://docs.aws.amazon.com/AmazonS3/latest/userguide/creating-access-points.html?icmpid=docs_amazons3_console#access-points-names) to the naming convention for S3 access points.
Not applicable

docs: add link to s3 access point naming convention

---

.changelog/37700.txt
internal/service/elbv2/load_balancer_test.go
website/docs/r/lb.html.markdown

Adds support for IPv6-only internet-facing Application Load Balancers (ALBs). These load balancers do not require IPv4 addresses and can be used for clients that can connect using just IPv6 addresses.
Note this was already technically supported in the provider as the `ip_address_type` attribute uses the `elbv2.IpAddressType_Values()` function, which was updated with the SDK. This PR adds an appropriate acceptance test and updates the resource documentation to reflect the change.
Closes #37695
- What's New: https://aws.amazon.com/about-aws/whats-new/2024/05/application-load-balancer-ipv6-internet-clients/
- API reference: https://docs.aws.amazon.com/elasticloadbalancing/latest/APIReference/API_CreateLoadBalancer.html
```console
$ make testacc …
```

r/aws-lb: Add support for IPv6-only ALB

---

.changelog/36506.txt
internal/service/mq/broker.go

Rebooting the Amazon MQ broker is not necessary for modifications to `maintenance_window_start_time` or to `auto_minor_version_upgrade`. These changes take effect immediately.

fix(aws_mq_broker): Do not reboot on changes to `maintenance_window_start_time` or `auto_minor_version_upgrade`

---

internal/generate/common/generator.go
internal/generate/tagresource/main.go
internal/generate/tagresource/tests.tmpl
internal/generate/tags/main.go
internal/service/autoscaling/generate.go
internal/service/dynamodb/exports_test.go
internal/service/dynamodb/tag_gen.go
internal/service/dynamodb/tag_gen_test.go
internal/service/dynamodb/tags_gen.go
internal/service/ec2/exports_test.go
internal/service/ec2/tag_gen.go
internal/service/ec2/tag_gen_test.go
internal/service/ec2/tagsv2_gen.go
internal/service/ecs/exports_test.go
internal/service/ecs/tag_gen.go
internal/service/ecs/tag_gen_test.go
internal/service/ecs/tagsv2_gen.go
internal/service/route53domains/generate.go
internal/service/route53domains/tags_gen.go
internal/service/route53resolver/generate.go
internal/service/route53resolver/tags_gen.go
internal/service/transfer/exports_test.go
internal/service/transfer/tag_gen.go
internal/service/transfer/tag_gen_test.go
internal/service/transfer/tags_gen.go

Uses a lowercase function name to reduce visibility.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/35700.
```console
% make testacc TESTARGS='-run=TestAccECSTag_' PKG=ecs
TF_ACC=1 go1.22.2 test ./internal/service/ecs/... -v -count 1 -parallel 20  -run=TestAccECSTag_ -timeout 360m
=== RUN   TestAccECSTag_basic
=== PAUSE TestAccECSTag_basic
=== RUN   TestAccECSTag_disappears
=== PAUSE TestAccECSTag_disappears
=== RUN   TestAccECSTag_ResourceARN_batchComputeEnvironment
=== PAUSE TestAccECSTag_ResourceARN_batchComputeEnvironment
=== RUN   TestAccECSTag_value
=== PAUSE TestAccECSTag_value
=== CONT  TestAccECSTag_basic
=== CONT …
```

Tech debt: Use `findTag` as default generated `GetTag` function name

---

.changelog/37868.txt
go.mod
go.sum
internal/service/fsx/lustre_file_system.go
internal/service/fsx/lustre_file_system_test.go
website/docs/r/fsx_lustre_file_system.html.markdown

New Amazon FSx for Lustre Metadata Feature. 
```console
% make testacc TESTARGS='-run=TestAccFSxLustreFileSystem_metadataConfig' PKG_NAME=internal/service/fsx ACCTEST_PARALLELISM=3
TF_ACC=1 go1.21.8 test ./internal/service/fsx/... -v -count 1 -parallel 3  -run=TestAccFSxLustreFileSystem_metadataConfig -timeout 360m
=== RUN   TestAccFSxLustreFileSystem_metadataConfig
=== PAUSE TestAccFSxLustreFileSystem_metadataConfig
=== RUN   TestAccFSxLustreFileSystem_metadataConfig_increase
=== PAUSE TestAccFSxLustreFileSystem_metadataConfig_increase
=== RUN   TestAccFSxLustreFileSystem_metadataConfig_decrease
=== PAUSE TestAccFSxLustreFileSystem_metadataConfig_decrease
=== CONT  TestAccFSxLustreFileSystem_metadataConfig
=== CONT …
```

[new feature] fsx lustre file system metadata

---

internal/service/ec2/vpnsite_customer_gateway.go

Parses integer value to correct bit size
Resolves https://github.com/hashicorp/terraform-provider-aws/security/code-scanning/281
```console
% make testacc PKG=ec2 TESTS=TestAccSiteVPNCustomerGateway_
--- PASS: TestAccSiteVPNCustomerGateway_disappears (25.34s)
--- PASS: TestAccSiteVPNCustomerGateway_deviceName (27.28s)
--- PASS: TestAccSiteVPNCustomerGateway_4ByteASN (27.49s)
--- PASS: TestAccSiteVPNCustomerGateway_bgpASNExtended (27.50s)
--- PASS: TestAccSiteVPNCustomerGateway_basic (27.65s)
--- PASS: TestAccSiteVPNCustomerGateway_tags (39.55s)
--- PASS: TestAccSiteVPNCustomerGateway_certificate (60.33s)
```

Fixes integer size

---

website/docs/r/detective_organization_configuration.html.markdown

This PR is to fix the ID description in the import section of the `aws_detective_organization_configuration` resource doc. For good measure, I've also updated `id` to `graph_arn` for the `aws_detective_graph` reference in the example to avoid confusion.
Closes #37822
Reviewed `organization_configuration.go` to see what `id` is set to.
```console
n/a
```

docs: Fix import ID desc for aws_detective_organization_configuration

---

website/docs/r/codepipeline.html.markdown

See #37906 : The current documentation for the AWS CodePipeline resource contains an incomplete sentence under 
`git_configuration`/` source_action_name`.
Closes #37906 
- [Latest AWS provider documentation for AWS CodePipeline source_action_name](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/codepipeline#source_action_name)
- [Cloudformation documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-codepipeline-pipeline-gitconfiguration.html#cfn-codepipeline-pipeline-gitconfiguration-sourceactionname)
Not required. Only documentation/ website is update.

docs: update details on source_action_name for aws_codepipeline

---

website/docs/r/guardduty_detector_feature.html.markdown
website/docs/r/guardduty_organization_configuration_feature.html.markdown

`r/aws_guardduty_organization_configuration_feature` and `r/guardduty_detector_feature` have the same configuration of features and additional configuration for features. Synchronize documentation between these resources. Add notice about mutualy exclusive features.

Sync documentation for guardduty feature and guardduty configuration feature

---

.github/workflows/generate_changelog.yml

Updates the `generate_changelog.yml` workflow to use a GitHub app to generate a token to push changelog changes back to main. This is so we can enable branch protection rulesets in a future step, but allow changelog automation to continue to work without a PR review.
Based on:
- https://github.com/orgs/community/discussions/25305#discussioncomment-8256560

Modify changelog generation to use a GitHub app token

---

CODEOWNERS

Uncomment default owner and add a more specific owner for the `/.github` directory.

Enable codeowners for `default` and `/.github`

---

internal/service/appflow/exports_test.go
internal/service/appflow/flow.go
internal/service/appflow/flow_tags_gen_test.go
internal/service/appflow/flow_test.go

The resource `aws_appflow_flow` uses the ARN as the ID, but all API calls take the name. Replaces calls to `findFlowByARN`, which iterates over `ListFlows`, with calls to `findFlowByName` which directly returns a single Flow
```console
% make testacc PKG=appflow TESTS=TestAccAppFlowFlow_
--- PASS: TestAccAppFlowFlow_taskProperties (37.83s)
--- PASS: TestAccAppFlowFlow_disappears (41.93s)
--- PASS: TestAccAppFlowFlow_basic (45.62s)
--- PASS: TestAccAppFlowFlow_task_mapAll (55.12s)
--- PASS: TestAccAppFlowFlow_tags_DefaultTags_nullNonOverlappingResourceTag (55.26s)
--- PASS: TestAccAppFlowFlow_tags_ComputedTag_OnCreate (56.46s)
--- PASS: TestAccAppFlowFlow_taskUpdate (68.10s)
--- PASS: TestAccAppFlowFlow_tags_null (68.14s)
--- PASS: TestAccAppFlowFlow_S3_outputFormatConfig_ParquetFileType …
```

Uses `name` parameter to look up Flow

---

.changelog/37958.txt
internal/flex/flex.go
internal/service/ec2/filters.go

There was a [change/bug fix](https://github.com/aws/aws-sdk-go/blob/main/CHANGELOG.md#sdk-bugs-1) in the aws_sdk where they no longer serialize empty, non-nil lists for ec2.
This impacted the way the aws_ami datasource filter was being created. It will now call a different expand function.
Closes #37709 
```console
> make testacc TESTARGS="-run=TestAccEC2AMIDataSource_" PKG=ec2
TF_ACC=1 go1.22.2 test ./internal/service/ec2/... -v -count 1 -parallel 20  -run=TestAccEC2AMIDataSource_ -timeout 360m
=== RUN   TestAccEC2AMIDataSource_linuxInstance
=== PAUSE TestAccEC2AMIDataSource_linuxInstance
=== RUN   TestAccEC2AMIDataSource_windowsInstance
=== PAUSE TestAccEC2AMIDataSource_windowsInstance …
```

Fix ami query returning no results

---

.changelog/37970.txt
internal/service/codebuild/project.go
internal/service/codebuild/project_test.go
website/docs/cdktf/python/r/codebuild_project.html.markdown
website/docs/r/codebuild_project.html.markdown

The maximum timeout for AWS CodeBuild has been updated to 36 hours (2160 minutes). Update the provider configuration to allow setting values > 480. Currently, trying to set values > 480 will result in the following provider error:
```
Error: 
expected build_timeout to be in the range (5 - 480), got 2160
```
Fixes hashicorp/terraform-provider-aws#37823
[Quotas for AWS CodeBuild](https://docs.aws.amazon.com/codebuild/latest/userguide/limits.html)
```console
make testacc TESTS=TestAccCodeBuildProject_buildBatchConfigDelete PKG=codebuild
TF_ACC=1 go1.22.2 test ./internal/service/codebuild/... -v -count 1 -parallel 20 -run='TestAccCodeBuildProject_buildBatchConfigDelete'  -timeout 360m
=== RUN …
```

bugfix: Update maximum build_timeout for codebuild from 8 hours to 36 hours

---

.changelog/#####.txt
internal/service/ec2/ec2_ami_data_source.go
internal/service/ec2/ec2_ami_data_source_test.go

Removes the custom set hash functions from the `aws_ami` data source -- these are not required for _Computed_ attributes.
Closes https://github.com/hashicorp/terraform-provider-aws/issues/37973.
```console
% make testacc TESTARGS='-run=TestAccEC2AMIDataSource_productCode' PKG=ec2
TF_ACC=1 go1.22.2 test ./internal/service/ec2/... -v -count 1 -parallel 20  -run=TestAccEC2AMIDataSource_productCode -timeout 360m
=== RUN   TestAccEC2AMIDataSource_productCode
=== PAUSE TestAccEC2AMIDataSource_productCode
=== CONT  TestAccEC2AMIDataSource_productCode
panic: interface conversion: interface {} is types.ProductCodeValues, not string
goroutine 108 [running]: …
```

d/aws_ami: Fix `interface conversion: interface {} is types.ProductCodeValues, not string` panic

---

internal/service/xray/group.go

Ignore `NotFound` error when deleting X-Ray Group.
Acceptance test `TestAccXRayGroup_disappears` was failing
```console
% make testacc PKG=xray TESTS=TestAccXRayGroup_
--- PASS: TestAccXRayGroup_disappears (40.57s)
--- PASS: TestAccXRayGroup_tags_ComputedTag_OnCreate (56.25s)
--- PASS: TestAccXRayGroup_tags_DefaultTags_emptyResourceTag (56.26s)
--- PASS: TestAccXRayGroup_tags_DefaultTags_nullOverlappingResourceTag (56.49s)
--- PASS: TestAccXRayGroup_tags_DefaultTags_emptyProviderOnlyTag (56.53s)
--- PASS: TestAccXRayGroup_tags_DefaultTags_nullNonOverlappingResourceTag (56.55s)
--- PASS: TestAccXRayGroup_basic (69.97s)
--- PASS: TestAccXRayGroup_insights (70.47s)
--- PASS: TestAccXRayGroup_tags_DefaultTags_updateToResourceOnly (76.23s)
--- PASS: …
```

Ignore `NotFound` error when deleting X-Ray Group

---

internal/service/bedrock/bedrock_test.go
internal/service/bedrock/custom_model_data_source_test.go
internal/service/bedrock/custom_model_test.go

Bedrock Custom Models have a maximum training concurrency of 2, and this limit cannot adjusted. Serializes the acceptance tests.
```console
% make testacc PKG=bedrock TESTS='TestAccBedrock_serial/CustomModel'
--- PASS: TestAccBedrock_serial (14500.35s)
--- PASS: TestAccBedrock_serial/CustomModel (14500.35s)
--- PASS: TestAccBedrock_serial/CustomModel/vpcConfig (78.05s)
--- PASS: TestAccBedrock_serial/CustomModel/dataSourceBasic (7069.65s)
--- PASS: TestAccBedrock_serial/CustomModel/basic (67.86s)
--- PASS: TestAccBedrock_serial/CustomModel/disappears (68.86s)
--- PASS: TestAccBedrock_serial/CustomModel/tags (54.00s)
--- PASS: TestAccBedrock_serial/CustomModel/kmsKey (58.00s)
--- PASS: TestAccBedrock_serial/CustomModel/validationDataConfig (63.64s)
--- PASS: …
```

Bedrock Custom Models have a maximum training concurrency of 2

---

.changelog/37991.txt
internal/service/dynamodb/table.go
internal/service/dynamodb/table_test.go
website/docs/r/dynamodb_table.html.markdown

If `ttl.attribute_name` is set when not enabled, it would cause a perpetual diff. Adds validation to require `attribute_name` when enabled, and not allow it when not enabled.
Closes #10304
```console
% make testacc PKG=dynamodb TESTS=TestAccDynamoDBTable
--- PASS: TestAccDynamoDBTable_streamSpecificationValidation (9.82s)
--- PASS: TestAccDynamoDBTable_attributeUpdateValidation (18.27s)
--- PASS: TestAccDynamoDBTableItem_disappears (26.63s)
--- PASS: TestAccDynamoDBTableItem_withDuplicateItemsSameRangeKey (37.70s)
--- PASS: TestAccDynamoDBTableItem_mapOutOfBandUpdate (42.48s)
--- PASS: TestAccDynamoDBTable_TTL_enabled (44.35s)
--- PASS: TestAccDynamoDBTable_TTL_validate (6.02s)
--- PASS: TestAccDynamoDBTableDataSource_basic (57.47s)
--- PASS: TestAccDynamoDBTableItem_updateWithRangeKey …
```

resource/aws_dynamodb_table: Fixes perpetual diff when `ttl.attribute_name` is set when not enabled

---

website/docs/r/eks_cluster.html.markdown

Clarifies documentation which makes it sound as if this is only for EKS clusters running EOL versions of Kubernetes. This is now guaranteed to be available for all EKS clusters, running any available Kubernetes version.  
https://docs.aws.amazon.com/eks/latest/userguide/enable-iam-roles-for-service-accounts.html
https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html

Update EKS Cluster IRSA Documentation - Remove References to now EOL K8S Versions

---

.changelog/33128.txt
website/docs/r/medialive_channel.html.markdown

This PR fixes typos `audio_selectors` and `caption_selectors` to be singular in the documentation.
N/A
[audio_selectors documentation](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/medialive_channel#audio_selectors)
[caption_selctors documentation](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/medialive_channel#caption_selectors)
N/A

medialive/channel: fix typos audio_selectors and caption_selectors.

---

website/docs/cdktf/python/r/codebuild_webhook.html.markdown
website/docs/cdktf/typescript/r/codebuild_webhook.html.markdown
website/docs/r/codebuild_webhook.html.markdown

Add `WORKFLOW_JOB_QUEUED` pattern for [self-hosted GitHub Actions runners in AWS CodeBuild](https://docs.aws.amazon.com/codebuild/latest/userguide/action-runner.html).
Closes #37904

Add missing pattern for `aws_codebuild_webhook`

---

website/docs/d/route53_zone.html.markdown

- Add missing fields `name`, `private_zone`, `tags`, `zone_id`
- Re-ordered attributes alphabetically
Additional cleanup:
- Removed blank link from Argument Reference section
- Add missing `.` to a sentence in Argument Reference section
Closes #37908 .
In the title of the related issue "missing id" is mentioned. In the description and code example `zone_id` is mentioned, e.g.
```hcl
output "zone_id" {
value = data.aws_route53_zone.id
}
```
I opted for adding `zone_id`, and leaving `id` out. 
Please let me know if I should add `id` also. Contentwise `id` and `zone_id` are identical.
None.
- Not applicable. Only documentation was updated.

doc: add fields to attribute reference of route53 zone data

---

.changelog/38085.txt
internal/service/sagemaker/endpoint_configuration.go
internal/service/sagemaker/endpoint_configuration_test.go
website/docs/r/sagemaker_endpoint_configuration.html.markdown

Closes #0000
```console
% make testacc TESTS=TestAccSageMakerEndpointConfiguration_ProductionVariants_ami  PKG=sagemaker
--- PASS: TestAccSageMakerEndpointConfiguration_ProductionVariants_ami (24.29s)
```

r/sagemaker_endpoint_configuration - add support for `inference_ami_version`

---

.changelog/38087.txt
internal/service/sagemaker/sagemaker_test.go
internal/service/sagemaker/workteam.go
internal/service/sagemaker/workteam_test.go
website/docs/r/sagemaker_workteam.html.markdown

Closes #0000
```console
% make testacc TESTS=TestAccSageMaker_serial/Workteam/WorkerAccessConfiguration  PKG=sagemaker
--- PASS: TestAccSageMaker_serial (23.02s)
--- PASS: TestAccSageMaker_serial/Workteam (23.02s)
--- PASS: TestAccSageMaker_serial/Workteam/WorkerAccessConfiguration (23.02s)
```

r/sagemaker_workteam - add support for `worker_access_configuration`

---

.github/workflows/snapshot.yml
.goreleaser.yml

#38062 updates the [ghaction-terraform-provider-release](https://github.com/hashicorp/ghaction-terraform-provider-release) action to a new major version which begins to use [GoReleaser v2](https://goreleaser.com/blog/goreleaser-v2/) under the hood.  GoReleaser v2 includes a number of [deprecations](https://goreleaser.com/deprecations/#removed-in-v2). Currently the snapshot.yml action is [failing](https://github.com/hashicorp/terraform-provider-aws/actions/runs/9640011043/job/26583087087#step:5:15) due to use of a deprecated flag (`--rm-dist`) as we have already updated https://github.com/goreleaser/goreleaser-action to the latest version including those deprecations.
This PR updates usage of any deprecated flags as well as update the goreleaser.yml file to use v2. This should resolve the …

Updates for GoReleaser v2 / ghaction-terraform-provider-release

---

.changelog/38168.txt
internal/service/cognitoidp/user_pool_client_data_source.go
internal/service/cognitoidp/user_pool_client_data_source_test.go

Fixes the bug in dataSourceUserPoolClientRead and adds additional acceptance test.
The bug seems to be introduced in the PR below.
https://github.com/hashicorp/terraform-provider-aws/pull/37024/files#diff-7756a038996f7336f61d258833fecdc9c15d8a139179e33686cbbde60b920d5eR190
Closes https://github.com/hashicorp/terraform-provider-aws/issues/38167
before
```console
-> % make testacc TESTARGS='-run=TestAccCognitoIDPUserPoolClientDataSource_' PKG=cognitoidp ACCTEST_PARALLELISM=3
TF_ACC=1 go1.22.4 test ./internal/service/cognitoidp/... -v -count 1 -parallel 3  -run=TestAccCognitoIDPUserPoolClientDataSource_ -timeout 360m
=== RUN   TestAccCognitoIDPUserPoolClientDataSource_basic
=== PAUSE …
```

BugFix: Fixes 400 error in dataSourceUserPoolClientRead

---

go.mod
go.sum

Closes #36185
Required for #37808, #37645
#32976
```console
% make testacc TESTS=TestAccXXX PKG=grafana
TF_ACC=1 go1.22.2 test ./internal/service/grafana/... -v -count 1 -parallel 20   -timeout 360m
=== RUN   TestAccGrafana_serial
=== PAUSE TestAccGrafana_serial
=== RUN   TestEndpointConfiguration
=== RUN   TestEndpointConfiguration/package_name_endpoint_config_overrides_alias_name_0_config
=== RUN   TestEndpointConfiguration/service_aws_envvar
=== RUN   TestEndpointConfiguration/alias_name_0_endpoint_config_overrides_aws_service_envvar
=== RUN   TestEndpointConfiguration/alias_name_0_endpoint_config_overrides_base_envvar
=== RUN …
```

Grafana: migrate to AWS SDK v2

---

website/docs/d/fsx_ontap_file_system.html.markdown
website/docs/r/fsx_ontap_file_system.html.markdown

This PR is to add a note about the `dns_name` attribute of the `aws_fsx_ontap_file_system` resource and data source to indicate that it is not set because it does not apply to FSx for ONTAP file systems.
Closes #38179
n/a
n/a

docs: Add note indiciating that dns_name is not set for aws_fsx_ontap_file_system

---

website/docs/d/oam_link.html.markdown
website/docs/d/oam_sink.html.markdown
website/docs/r/oam_link.html.markdown
website/docs/r/oam_sink.html.markdown
website/docs/r/oam_sink_policy.html.markdown

This PR is to add the missing `id` attribute description to the `aws_oam_*` resource and data source documentation.
Closes #38169
n/a
n/a

docs: Add missing id attr for aws_oam resources and data sources

---

internal/framework/flex/auto_expand_test.go
internal/framework/flex/auto_flatten_test.go

Currently the tests for AutoFlEx check simply for the presence of an error, not the contents. Tests do not capture logs.
This PR replaces the boolean `WantErr` field with the `diag.Diagnostics` `expectedDiags` field to validate the error messages. It also adds the field `expectedLogLines` to capture logs.
In addition to explicitly expecting error messages and log entries, this sets the baseline for what is currently output so that we can update them as we define the expected behaviour.
Relates #38192

Adds validation of Diagnostics and logging to AutoFlEx tests

---

internal/service/iot/sweep.go

This PR addresses technical debt in the `iot` sweepers, it migrates the sweepers to use paginators.
Closes https://github.com/hashicorp/terraform-provider-aws/issues/38230
```console
...
```

[Tech Debt] - Migrate `iot` sweepers to use paginators

---

.changelog/38273.txt
internal/service/cloudtrail/event_data_store.go
internal/service/cloudtrail/event_data_store_test.go
internal/service/cloudtrail/sweep.go
website/docs/r/cloudtrail_event_data_store.html.markdown

Closes #34494
```console
% make testacc TESTS=TestAccCloudTrailEventDataStore_ PKG=cloudtrail 
TF_ACC=1 go1.22.4 test ./internal/service/cloudtrail/... -v -count 1 -parallel 20 -run='TestAccCloudTrailEventDataStore_'  -timeout 360m
=== RUN   TestAccCloudTrailEventDataStore_basic
=== PAUSE TestAccCloudTrailEventDataStore_basic
=== RUN   TestAccCloudTrailEventDataStore_kmsKeyId
=== PAUSE TestAccCloudTrailEventDataStore_kmsKeyId
=== RUN   TestAccCloudTrailEventDataStore_disappears
=== PAUSE TestAccCloudTrailEventDataStore_disappears
=== RUN   TestAccCloudTrailEventDataStore_tags
=== PAUSE TestAccCloudTrailEventDataStore_tags
=== RUN   TestAccCloudTrailEventDataStore_options
=== PAUSE …
```

aws_cloudtrail_event_data_store

---

.teamcity/components/generated/services_all.kt
internal/generate/teamcity/acctest_services.hcl

AMP has a maximum of 10 scrapers per region, and this quota cannot be adjusted.

ci: Sets the parallelism for AMP acceptance tests to 10

---

.changelog/38196.txt
internal/service/globalaccelerator/cross_account_attachment.go
internal/service/globalaccelerator/cross_account_attachment_test.go
website/docs/r/globalaccelerator_cross_account_attachment.html.markdown

Closes #38117
```console
% make testacc TESTS=TestAccGlobalAcceleratorCrossAccountAttachment_ PKG=globalaccelerator
TF_ACC=1 go1.22.4 test ./internal/service/globalaccelerator/... -v -count 1 -parallel 20 -run='TestAccGlobalAcceleratorCrossAccountAttachment_'  -timeout 360m
=== RUN   TestAccGlobalAcceleratorCrossAccountAttachment_basic
=== PAUSE TestAccGlobalAcceleratorCrossAccountAttachment_basic
=== RUN   TestAccGlobalAcceleratorCrossAccountAttachment_principals
=== PAUSE TestAccGlobalAcceleratorCrossAccountAttachment_principals
=== RUN   TestAccGlobalAcceleratorCrossAccountAttachment_resources
=== PAUSE TestAccGlobalAcceleratorCrossAccountAttachment_resources
=== RUN …
```

aws_globalaccelerator_cross_account_attachment

---

.changelog/38292.txt
.ci/semgrep/errors/error-checks.go
.ci/semgrep/errors/error-checks.yml
.github/workflows/semgrep-ci.yml
GNUmakefile
internal/retry/wrappers.go
internal/service/directconnect/lag.go
internal/service/dynamodb/kinesis_streaming_destination.go
internal/service/ec2/ec2_capacity_block_reservation.go
internal/service/ec2/vpc_route_table.go
internal/service/opensearchserverless/access_policy.go
internal/service/opensearchserverless/collection.go
internal/service/opensearchserverless/security_config.go
internal/service/opensearchserverless/security_policy.go
internal/service/opensearchserverless/vpc_endpoint.go
internal/service/opsworks/stack.go
internal/service/ram/principal_association_test.go
internal/service/rds/instance.go
internal/service/ssmincidents/replication_set_test.go

In a number of cases, only `tfresource.NotFound` is checked, but other errors are not checked.
Closes #38138

Ensure that all errors are checked during read, not just `tfresource.NotFound`

---

.changelog/38161.txt
internal/service/fms/fms_test.go
internal/service/fms/policy.go
internal/service/fms/policy_test.go

Add resource_set_ids attribute to fms policy
Closes #33372
```console
> make testacc TESTARGS="-run=TestAccFMS_serial/Policy/rscSet" PKG=fms
TF_ACC=1 go1.22.4 test ./internal/service/fms/... -v -count 1 -parallel 20  -run=TestAccFMS_serial/Policy/rscSet -timeout 360m
=== RUN   TestAccFMS_serial
=== PAUSE TestAccFMS_serial
=== CONT  TestAccFMS_serial
=== RUN   TestAccFMS_serial/Policy
=== RUN   TestAccFMS_serial/Policy/rscSet
--- PASS: TestAccFMS_serial (1110.98s)
--- PASS: TestAccFMS_serial/Policy (1110.98s)
--- PASS: TestAccFMS_serial/Policy/rscSet (1110.98s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/fms        1116.454s
...
```

Add resource_set_ids attribute to fms policy

---

go.mod
go.sum
internal/service/logs/service_package_gen.go

Adds the `aws_cloudwatch_log_account_policy` resource, which can create account-level subscription filters and/or data protection policies.
Closes #35278
```console
%make testacc TESTS=TestAccLogsAccountPolicy PKG=logs
TF_ACC=1 go1.22.4 test ./internal/service/logs/... -v -count 1 -parallel 20 -run='TestAccLogsAccountPolicy'  -timeout 360m
=== RUN   TestAccLogsAccountPolicy_basicSubscriptionFilter
=== PAUSE TestAccLogsAccountPolicy_basicSubscriptionFilter
=== RUN   TestAccLogsAccountPolicy_basicDataProtection
=== PAUSE TestAccLogsAccountPolicy_basicDataProtection
=== RUN   TestAccLogsAccountPolicy_disappears
=== PAUSE TestAccLogsAccountPolicy_disappears
=== RUN …
```

add aws_cloudwatch_log_account_policy resource

---

internal/service/pinpoint/app.go
internal/service/pinpoint/app_test.go

Fixes panic when nested objects, e.g. `campaign_hook`, `limits`, or `quiet_time`, are empty
Closes #25861
```console
% make testacc PKG=pinpoint TESTS=TestAccPinpointApp_
--- PASS: TestAccPinpointApp_nameGenerated (18.97s)
--- PASS: TestAccPinpointApp_namePrefix (20.51s)
--- PASS: TestAccPinpointApp_disappears (21.36s)
--- PASS: TestAccPinpointApp_basic (24.33s)
--- PASS: TestAccPinpointApp_campaignHookEmpty (25.11s)
--- PASS: TestAccPinpointApp_quietTimeEmpty (25.25s)
--- PASS: TestAccPinpointApp_limitsEmpty (25.26s)
--- PASS: TestAccPinpointApp_limits (25.30s)
--- PASS: TestAccPinpointApp_quietTime (25.34s)
--- PASS: TestAccPinpointApp_campaignHookLambda (34.25s)
--- PASS: TestAccPinpointApp_tags (37.32s)
```

resource/aws_pinpoint_app: Fix panic when nested objects are empty

---

website/docs/r/docdb_cluster.html.markdown

I was confused as to whether this should be a string (eg, `enabled`) or a boolean. It was easy enough to find out, but it would have been nicer if the docs had been more explicit.
This commit makes the boolean type of the value explicit.
current docs
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/docdb_cluster#deletion_protection

add explicit reference to the type of the expected value

---

website/docs/r/wafv2_web_acl.html.markdown
website/docs/r/wafv2_web_acl_logging_configuration.html.markdown

This PR is to update the documentation to reflect 
- that the `name` in the `single_header` block  of  resource `aws_wafv2_web_acl_logging_configuration`  is not optional, but required.  See [this section](https://github.com/hashicorp/terraform-provider-aws/blob/cd31961d3f059ad85e67474c1484065d899b607b/internal/service/wafv2/web_acl_logging_configuration.go#L141) in the provider code base and also the [CloudFormation documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-wafv2-loggingconfiguration-singleheader.html).
- a similar change in the resource `aws_wafv2_web_acl` for the `single_header` blocker. Here `name` is also marked as optional, but should be marked as required.  [Here](https://github.com/hashicorp/terraform-provider-aws/blob/cd31961d3f05 …

docs: mark attributes as required in  wafv2 web acl  and wafv2 web acl logging configuration

---

.changelog/37317.txt
internal/service/imagebuilder/image_pipeline.go
internal/service/imagebuilder/image_pipeline_test.go
website/docs/r/imagebuilder_image_pipeline.html.markdown

This PR adds support for Image Builder workflows to Image Builder pipelines. Similar to https://github.com/hashicorp/terraform-provider-aws/pull/36953.
Closes #35045.
https://aws.amazon.com/about-aws/whats-new/2023/12/ec2-image-builder-image-workflows/
https://docs.aws.amazon.com/imagebuilder/latest/APIReference/API_CreateImagePipeline.html
https://docs.aws.amazon.com/imagebuilder/latest/APIReference/API_UpdateImagePipeline.html
```console
% make testacc TESTARGS="-run=TestAccImageBuilderImagePipeline_workflow" PKG=imagebuilder
TF_ACC=1 go1.22.2 test ./internal/service/imagebuilder/... -v -count 1 -parallel 20  -run=TestAccImageBuilderImagePipeline_workflow -timeout 360m
=== RUN   TestAccImageBuilderImagePipeline_workflow
=== …
```

r/aws_imagebuilder_pipeline: add support for workflows

---

.changelog/38350.txt
website/docs/r/kinesisanalyticsv2_application.html.markdown

Add documentation for supported Flink runtime 1.19
Closes #38348
The option was added in release [v1.54.11](https://github.com/aws/aws-sdk-go/commit/9607ced1cc4b6b39263b9017eea3185ec15636ee#diff-034b3d8a3c745211948e31a862fa399c4c2a131e7facc0eede08307be9481d18)
```console
...
```

r/aws_kinesisanalyticsv2_application: Document support for FLINK-1_19

---

website/docs/r/fsx_ontap_storage_virtual_machine.html.markdown

The documenation is missing the argument `svm_admin_password` for the resource `aws_fsx_ontap_storage_virtual_machine`.
Closes #38154
- [AWS Cloudformation Docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-fsx-storagevirtualmachine.html#cfn-fsx-storagevirtualmachine-svmadminpassword)
- [Terraform Provider Code](https://github.com/hashicorp/terraform-provider-aws/blob/26d1b59bef1a1462f08c637b0c1cf297ba763292/internal/service/fsx/ontap_storage_virtual_machine.go#L222)
Not required as only documentation is updated.

docs: add svm_admin_password to fsx_ontap_storage_virtual_machine args

---

go.mod
go.sum
internal/conns/awsclient_gen.go
internal/service/serverlessrepo/application_data_source.go
internal/service/serverlessrepo/cloudformation_stack.go
internal/service/serverlessrepo/cloudformation_stack_test.go
internal/service/serverlessrepo/find.go
internal/service/serverlessrepo/generate.go
internal/service/serverlessrepo/service_endpoint_resolver_gen.go
internal/service/serverlessrepo/service_endpoints_gen_test.go
internal/service/serverlessrepo/service_package_gen.go
internal/service/serverlessrepo/tags_gen.go
names/data/names_data.hcl

Closes #36210
Relates #38363
```console
% make testacc TESTARGS="-run=TestAccServerlessRepo" PKG=serverlessrepo
TF_ACC=1 go1.22.5 test ./internal/service/serverlessrepo/... -v -count 1 -parallel 20  -run=TestAccServerlessRepo -timeout 360m
--- PASS: TestAccServerlessRepoApplicationDataSource_basic (14.25s)
--- PASS: TestAccServerlessRepoApplicationDataSource_versioned (20.22s)
--- PASS: TestAccServerlessRepoCloudFormationStack_paired (88.61s)
--- PASS: TestAccServerlessRepoCloudFormationStack_basic (95.04s)
--- PASS: TestAccServerlessRepoCloudFormationStack_disappears (101.57s)
--- PASS: TestAccServerlessRepoCloudFormationStack_update (160.21s)
--- PASS: …
```

td/serverless application repository: migrate to AWS go SDKv2

---

website/docs/r/sagemaker_space.html.markdown

Updates `aws_sagemaker_space` documentation to:
- Correctly link to headers of sub blocks by changing the header title + moving from H4 to H3
- Alphabetize the arguments a bit better, though the organization of the various block is a bit tricky for this resource
N/a, docs

Correct `aws_sagemaker_space` header links

---

.changelog/38345.txt
internal/service/datazone/exports_test.go
internal/service/datazone/project.go
internal/service/datazone/project_test.go
internal/service/datazone/service_package_gen.go
names/names.go
website/docs/r/datazone_project.html.markdown

This resource will allow practitioners to create DataZone Projects for a DataZone Domain via Terraform.
Relates #37423
Closes #38231
https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/datazone
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-datazone-project.html
```console 
% make testacc TESTS=TestAccDataZoneProject_basic PKG=datazone     
TF_ACC=1 go1.22.4 test ./internal/service/datazone/... -v -count 1 -parallel 20 -run='TestAccDataZoneProject_basic'  -timeout 360m
=== RUN   TestAccDataZoneProject_basic
=== PAUSE TestAccDataZoneProject_basic
=== CONT  TestAccDataZoneProject_basic
--- PASS: TestAccDataZoneProject_basic (27.47s)
PASS
ok …
```

[New Resource]: DataZone Project

---

website/docs/r/rds_cluster.html.markdown

This Pull Request is to edit the following document:
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/rds_cluster.html
In the current document example, the master password is set to "bar".
However, according to AWS specifications, the master password must be at least 8 characters long, which causes an error during terraform apply.
> Must contain from 8 to 41 characters.
https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_CreateDBCluster.html
Error during terraform apply
```
aws_rds_cluster.postgresql: Creating...
╷
│ Error: creating RDS Cluster (aurora-cluster-demo): InvalidParameterValue: The parameter MasterUserPassword is not a valid password because it is shorter than 8 characters.
```
There are no changes to the source code.

docs: [aws_rds_cluster] Change the sample string for the Master Password

---

website/docs/r/rds_cluster_instance.html.markdown

When creating an Aurora Serverless v2 cluster in Terraform, users must add an instance to the cluster. The documentation points to the AWS documentation page on the currently available instance classes, but this documentation does not include `db.serverless`.
The Aurora Serverless v2 documentation itself also has scant mention of it.
Including the information here as well ought to help users.
[AWS documentation for the instance type](https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/aurora-serverless-v2.create.html#:~:text=When%20you%20use%20the%20AWS%20CLI%20or%20the%20Amazon%20RDS%20API%2C%20the%20parameter%20that%20you%20specify%20for%20the%20DB%20instance%20class%20is%20db.serverless.)
Docs change. Acceptance tests should be unaffected?

Clarify the instance type to use for Aurora Serverless v2

---

.changelog/38245.txt
internal/service/firehose/delivery_stream.go
internal/service/firehose/delivery_stream_test.go
website/docs/r/kinesis_firehose_delivery_stream.html.markdown

Closes #38210
```console
% make testacc TESTS=TestAccFirehoseDeliveryStream_HTTPEndpoint_ PKG=firehose
TF_ACC=1 go1.22.4 test ./internal/service/firehose/... -v -count 1 -parallel 20 -run='TestAccFirehoseDeliveryStream_HTTPEndpoint_'  -timeout 360m
=== RUN   TestAccFirehoseDeliveryStream_HTTPEndpoint_ErrorOutputPrefix
=== PAUSE TestAccFirehoseDeliveryStream_HTTPEndpoint_ErrorOutputPrefix
=== RUN   TestAccFirehoseDeliveryStream_HTTPEndpoint_retryDuration
=== PAUSE TestAccFirehoseDeliveryStream_HTTPEndpoint_retryDuration
=== RUN   TestAccFirehoseDeliveryStream_HTTPEndpoint_SecretsManagerConfiguration
=== PAUSE TestAccFirehoseDeliveryStream_HTTPEndpoint_SecretsManagerConfiguration
=== CONT …
```

aws_kinesis_firehose_delivery_stream

---

website/docs/r/ses_domain_mail_from.html.markdown

Closes #38242
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ses_domain_mail_from#domain-identity-mail-from
Changed ~All instead of -All

38242 - The example does not correspond recomendation from AWS. Use ~All instead of -All

---

.github/workflows/issue_comment.yml

Similar to other recent PRs, moves the workflow to use the new composite action style community check. Also introduces:
- `permissions` block to limit token permissions
- Only runs the label removing job if the labels exist on the issue
N/a, Actions

Update `issue_comment` workflow to use new community check

---

docs/naming.md

Coverts a note missed in the original conversion to the admonition component.

docs: use note admonition on naming standards

---

internal/service/chime/sweep.go
internal/sweep/register_gen_test.go

Adds a sweeper for the `aws_chime_voice_connector` resource. AWS has a regional limit of 3 voice connectors, so this sweeper will prevent scheduled acceptance tests from continuously hitting this limit in cases where voice connectors are inadvertently left behind.
```
=== RUN   TestAccChime_serial/VoiceConnector/basic
voice_connector_test.go:30: Step 1/2 error: Error running apply: exit status 1
Error: creating Chime Voice connector: operation error Chime SDK Voice: CreateVoiceConnector, https response error StatusCode: 400, RequestID: 84e3d0e6-dc62-4e29-b9cf-e2f76ab770dd, BadRequestException: checkCreateVoiceConnectorRegionalLimit:: aws account 187416307283 reached its regional voice connector limit 3
with aws_chime_voice_connector.test,
on terraform_plugin_test.tf line 12, in resource …
```

chime: add voice connector sweeper

---

internal/service/bedrockagent/agent_action_group.go
internal/service/bedrockagent/agent_action_group_test.go
website/docs/r/bedrockagent_agent_action_group.html.markdown

The `aws_bedrockagent_agent_action_group` parameter `function_schema` is a tagged union type, so needs an extra level of indirection to capture the types.
```console
% make testacc PKG=bedrockagent TESTS=TestAccBedrockAgentAgentActionGroup_
--- PASS: TestAccBedrockAgentAgentActionGroup_ActionGroupExecutor_customControl (35.69s)
--- PASS: TestAccBedrockAgentAgentActionGroup_APISchema_s3 (42.56s)
--- PASS: TestAccBedrockAgentAgentActionGroup_basic (49.53s)
--- PASS: TestAccBedrockAgentAgentActionGroup_update (56.04s)
--- PASS: TestAccBedrockAgentAgentActionGroup_FunctionSchema_memberFunctions (57.87s)
```

resource/aws_bedrockagent_agent_action_group: updates `function_schema` to allow other tagged union types

---

website/docs/r/wafv2_rule_group.html.markdown
website/docs/r/wafv2_web_acl.html.markdown

This PR is to document the `sensitivity_level` argument for the `sqli_match_statement` block which is applicable to both the `aws_wafv2_rule_group` and `aws_wafv2_web_acl` resources. It was added via #29672 but the documentation update wasn't complete.
Closes #38000
Referred to [SqliMatchStatement](https://docs.aws.amazon.com/waf/latest/APIReference/API_SqliMatchStatement.html) for wordings.
n/a

docs: Add sensitivity_level arg to sqli_match_statement block for aws_wafv2_rule_group and aws_wafv2_web_acl

---

website/docs/r/glue_classifier.html.markdown

- Add the argument `serde` and valid values to the resource description.
- Streamline different ways of writing CVS  (csv,Csv, CSV) into one.
- Closes #38431  
(Issue on missing documentation)
- Relates to #33787  
(Implementation of functionality)
- [AWS Glue WebAPI reference](https://docs.aws.amazon.com/glue/latest/webapi/API_CsvClassifier.html)
- Not applicable, only documentation was updated.

docs: add missing serde argument

---

.changelog/38449.txt
internal/service/ce/cost_category.go

This PR is to fix perpetual diff with the `rule` argument when updating a `aws_ce_cost_category` resource, because of a subtle state differences with the nested `rule` argument being set during flattening regardless of whether the API response value is set. For good measure, I added similar checks for other optional values in all flatten functions where appropriate.
Closes #38215
n/a
```console
$ make testacc TESTS=TestAccCECostCategory_ PKG=ce
TF_ACC=1 go1.22.5 test ./internal/service/ce/... -v -count 1 -parallel 20 -run='TestAccCECostCategory_'  -timeout 360m
=== RUN   TestAccCECostCategory_basic
=== PAUSE TestAccCECostCategory_basic
=== RUN   TestAccCECostCategory_effectiveStart
=== …
```

fix: Add nil checks to fix perpetual diff of rule arg for aws_ce_cost_category

---

.changelog/38458.txt
internal/service/sesv2/configuration_set_event_destination.go
internal/service/sesv2/configuration_set_event_destination_test.go
website/docs/r/sesv2_configuration_set_event_destination.html.markdown

This PR is to add the `event_destination.event_bridge_destination` block to the `aws_sesv2_configuration_set_event_destination` resource to support tracking email sending activity by delivering sending events to EventBridge.
I opted to use `event_bridge_destination` instead of `eventbridge_destination` since the AWSCC provider also uses [`event_bridge_destination`](https://registry.terraform.io/providers/hashicorp/awscc/latest/docs/resources/ses_configuration_set_event_destination#event_bridge_destination) as the arg/block name.
Closes #38021
Referred to [EventDestinationDefinition](https://docs.aws.amazon.com/ses/latest/APIReference-V2/API_EventDestinationDefinition.html) for specs.
```console
$ make testacc TESTS=TestAccSESV2ConfigurationSetEventDestination_ PKG=sesv2
make: Verifying …
```

feat: Add event_bridge_destination block for aws_sesv2_configuration_set_event_destination

---

.github/workflows/pull_request_feed.yml

- Moves the pull request feed workflow over to the new community check 
- Combines the jobs to further cut down noise in PR checks (4 -> 1)
- Adds `permissions` block to limit generated token to necessary permissions
- Removed unused `GH_TOKEN` environment variable
N/a, Actions

Move pull request feed to new community check

---

website/docs/r/securitylake_subscriber.html.markdown

Updates the `aws_securitylake_subscriber` docs to be a bit more clear. Namely:
- Add documentation for `access_type`
- Create headers and linked to them for block type arguments
- Added similar headers and links for the attributes of the `custom_log_source_resource` block
For the last point above, this is a bit of a unique resource that I'm not certain we have many other examples of. There's a block within another that exports read-only attributes. I tried to make this as clear as possible, but if there are other examples that I'm not finding, I'd be happy to modify this to be more in line with prior art.
Closes #38324
- [Schema](https://github.com/hashicorp/terraform-provider-aws/blob/main/internal/service/securitylake/subscriber.go)
- [AWS API …

Clarify aws_securitylake_subscriber docs

---

internal/service/fsx/lustre_file_system.go
internal/service/fsx/ontap_storage_virtual_machine_test.go
internal/service/fsx/openzfs_file_system.go
internal/service/fsx/openzfs_file_system_test.go
internal/service/fsx/openzfs_volume.go

Fixes new failing acceptance tests after AWS SDK for Go v2 migration.
Closes https://github.com/hashicorp/terraform-provider-aws/issues/38468.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/38343.
```console
% ACCTEST_TIMEOUT=720m make testacc TESTARGS='-run=TestAccFSxLustreFileSystem_metadataConfig' PKG=fsx ACCTEST_PARALLELISM=3
TF_ACC=1 go1.22.5 test ./internal/service/fsx/... -v -count 1 -parallel 3  -run=TestAccFSxLustreFileSystem_metadataConfig -timeout 720m
=== RUN   TestAccFSxLustreFileSystem_metadataConfig
=== PAUSE TestAccFSxLustreFileSystem_metadataConfig
=== RUN   TestAccFSxLustreFileSystem_metadataConfig_increase
=== PAUSE …
```

Fix failing acceptance tests after AWS SDK for Go v2 migration

---

.changelog/38437.txt
internal/service/rds/cluster.go
internal/service/rds/cluster_snapshot.go
internal/service/rds/consts.go
internal/service/rds/exports_test.go
internal/service/rds/find.go
internal/service/rds/service_package_gen.go
internal/service/rds/sweep.go
internal/service/rds/wait.go

When waiting for `aws_rds_cluster` to update and `apply_immediately` is `true`, ensure that there are no pending modified values if the cluster's status is `available`.
I _think_ we will need to do the same for `aws_rds_cluster_instance` and `aws_db_instance` to resolve e.g. https://github.com/hashicorp/terraform-provider-aws/issues/31529.
Closes https://github.com/hashicorp/terraform-provider-aws/issues/28339.
```console
% ACCTEST_TIMEOUT=1080m make testacc TESTARGS='-run=TestAccRDSCluster_' PKG=rds ACCTEST_PARALLELISM=4
TF_ACC=1 go1.22.5 test ./internal/service/rds/... -v -count 1 -parallel 4  -run=TestAccRDSCluster_ -timeout 1080m
=== RUN   TestAccRDSCluster_basic
=== PAUSE …
```

r/aws_rds_cluster: Wait for no pending modified values on Update if `apply_immediately` is `true`

---

website/docs/r/lambda_runtime_management_config.html.markdown

* Fixed a typo in the resource not for the `aws_lambda_runtime_management_config` resource.
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lambda_runtime_management_config

Fixed typo in resource note for aws_lambda_runtime_management_config

---

website/docs/r/sagemaker_space.html.markdown

- Corrects a few blocks that had incorrect arguments
- Added documentation for `space_storage_settings` and it's nested blocks
Relates #38370
- [Schema](https://github.com/hashicorp/terraform-provider-aws/blob/main/internal/service/sagemaker/space.go)
- [AWS docs for `space_storage_settings`](https://docs.aws.amazon.com/sagemaker/latest/APIReference/API_SpaceStorageSettings.html)
N/a, docs

Fix `aws_sagemaker_space` documentation

---

.changelog/38476.txt
internal/service/elasticache/replication_group_migrate.go
internal/service/elasticache/replication_group_test.go

The **v4.67.0** schema contained block attribute named `cluster_mode` which was removed at **v5.0.0**.
The **v5.59.0** schema introduced a new string attribute named `cluster_mode`.
This caused an error when upgrading state from v4.67.0 to v5.59.0.
Closes https://github.com/hashicorp/terraform-provider-aws/issues/38464.
```console
% ACCTEST_TIMEOUT=1080m make testacc TESTARGS='-run=TestAccElastiCacheReplicationGroup_stateUpgrade5590' PKG=elasticache
TF_ACC=1 go1.22.5 test ./internal/service/elasticache/... -v -count 1 -parallel 20  -run=TestAccElastiCacheReplicationGroup_stateUpgrade5590 -timeout 1080m
=== RUN   TestAccElastiCacheReplicationGroup_stateUpgrade5590
=== PAUSE …
```

r/aws_elasticache_replication_group: Fix `error marshaling prior state` when upgrading from v4.67.0 to v5.59.0

---

website/docs/r/ecs_task_definition.html.markdown

Add more clarity for the documentation on the `track_latest`. I was somewhat confused initially reading it and utilizing it, along with others (https://github.com/hashicorp/terraform-provider-aws/issues/20121#issuecomment-2071533920)
This is the original PR https://github.com/hashicorp/terraform-provider-aws/pull/30154
This is the original PR https://github.com/hashicorp/terraform-provider-aws/pull/30154
No tests required. Documentation enhancement

Documentation Enhancement(ecs_task_definition): more clarity on `track_latest`

---

.changelog/38471.txt
internal/sdkv2/state.go
internal/sdkv2/state_test.go
internal/service/ecs/task_definition.go
internal/service/ecs/task_definition_equivalency.go
internal/service/ecs/task_definition_test.go

The root cause was a change in the behavior of the `container_definitions` attribute's [`StateFunc`](https://developer.hashicorp.com/terraform/plugin/sdkv2/schemas/schema-behaviors#statefunc) when the value is [unknown](https://developer.hashicorp.com/terraform/language/expressions/references#values-not-yet-known), for example during `terraform plan` when the attribute's value refers to attributes of other to-be-created resources.
For **v5.58.0** the returned value in such cases was `[]` (an empty array):
```
2024-07-23T14:34:21.637-0400 [INFO]  provider.terraform-provider-aws: [INFO] container_definitions.StateFunc: v: 74D93920-ED26-11E3-AC10-0800200C9A66, err: decoding JSON: invalid character 'D' after top-level value
2024-07-23T14:34:21.637-0400 [INFO]  provider.terraform-provider-aws: …
```

r/aws_ecs_task_definition: `Provider produced inconsistent final plan` for `container_definitions` after v5.59.0

---

.changelog/38498.txt
internal/service/cloudformation/stack_set_instance.go
internal/service/cloudformation/stack_set_instance_test.go
internal/service/cloudformation/type.go
website/docs/r/cloudformation_stack_set_instance.html.markdown

Introduces a `concurrency_mode` argument within the `operation_preferences` argument block of the `aws_cloudformation_stack_set_instance` resource 
Closes #38496
* [Blogpost announcing support](https://aws.amazon.com/about-aws/whats-new/2023/11/deploy-stack-sets-faster-concurrencymode-aws-cloudformation/)
* [Parameter description](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/concurrency-mode.html)
* [OperationPreferences reference](https://docs.aws.amazon.com/AWSCloudFormation/latest/APIReference/API_StackSetOperationPreferences.html)
```console
% make testacc TESTS=TestAccCloudFormationStackSetInstance_operationPreferences PKG=cloudformation
TF_ACC=1 go1.22.5 test …
```

Add concurrency_mode parameter to aws_cloudformation_stack_set_instance

---

internal/service/ec2/ec2_fleet_test.go
internal/service/ec2/find.go
internal/service/ec2/vpc_ipv4_cidr_block_association.go
internal/service/ec2/vpc_peering_connection_options_test.go
internal/service/ec2/vpc_peering_connection_test.go
internal/service/ec2/wait.go

Fixes some of the remaining EC2 service CI acceptance test failures.
```
=== RUN   TestAccEC2Fleet_TargetCapacitySpecification_targetCapacityUnitType
=== PAUSE TestAccEC2Fleet_TargetCapacitySpecification_targetCapacityUnitType
=== CONT  TestAccEC2Fleet_TargetCapacitySpecification_targetCapacityUnitType
ec2_fleet_test.go:2963: Step 2/2 error running import: ImportStateVerify attributes not equivalent. Difference is shown below. The - symbol indicates attributes missing after import.
map[string]string{
-   "fulfilled_capacity": "0",
+   "fulfilled_capacity": "32",
}
--- FAIL: TestAccEC2Fleet_TargetCapacitySpecification_targetCapacityUnitType (646.27s)
```
```
=== RUN   TestAccEC2Fleet_TargetCapacitySpecification_totalTargetCapacity
=== PAUSE …
```

Fix `ec2` service acceptance test errors

---

.changelog/38513.txt
internal/service/codebuild/webhook.go

When `scope_configuration` was added to the `aws_codebuild_webhook` resource the validation for `scopes` was incorrectly applied to the `domain` section.  As a result the validation is checking if `example.com` matches either `GITHUB_ORGANIZATION` or `GITHUB_GLOBAL` (which would make sense if applied to `scopes` instead of `domains`).  Moving the validation line fixes errors like:
```
│ Error: expected domain to be one of ["GITHUB_ORGANIZATION" "GITHUB_GLOBAL"], got example.com
```
when using a `scope_configuration` like:
```
scope_configuration {                                                                                                                                                                         
domain = "example.com"
name   = "my-org-name"
scope  = "GITHUB_ORGANIZATION" …
```

Fix scope attribute validation for codebuild webhooks

---

.changelog/38517.txt
internal/service/batch/eks_properties.go
internal/service/batch/job_definition.go
internal/service/batch/job_definition_test.go
website/docs/r/batch_job_definition.html.markdown

Closes #38520
```console
% make t T='TestAccBatchJobDefinition_EKSProperties_imagePullSecrets|TestAccBatchJobDefinition_basic|TestAccBatchJobDefinition_EKSProperties_basic' K=batch
TF_ACC=1 go1.22.5 test ./internal/service/batch/... -v -count 1 -parallel 20 -run='TestAccBatchJobDefinition_EKSProperties_imagePullSecrets|TestAccBatchJobDefinition_basic|TestAccBatchJobDefinition_EKSProperties_basic'  -timeout 360m
=== RUN   TestAccBatchJobDefinition_basic
=== PAUSE TestAccBatchJobDefinition_basic
=== RUN   TestAccBatchJobDefinition_EKSProperties_basic
=== PAUSE TestAccBatchJobDefinition_EKSProperties_basic
=== RUN   TestAccBatchJobDefinition_EKSProperties_imagePullSecrets
=== PAUSE …
```

batch/jobdef: Add image_pull_secret

---

.changelog/38492.txt
internal/service/events/bus.go
internal/service/events/bus_data_source.go
internal/service/events/bus_data_source_test.go
internal/service/events/bus_test.go
website/docs/d/cloudwatch_event_bus.html.markdown
website/docs/r/cloudwatch_event_bus.html.markdown

This PR adds the `kms_key_identifier` argument to the `aws_cloudwatch_event_bus` resource and data source.
Closes #37531.
https://docs.aws.amazon.com/eventbridge/latest/APIReference/API_CreateEventBus.html
https://docs.aws.amazon.com/eventbridge/latest/APIReference/API_DescribeEventBus.html
https://docs.aws.amazon.com/eventbridge/latest/APIReference/API_UpdateEventBus.html
```console
% make testacc PKG=events ACCTEST_PARALLELISM=1 TESTARGS="-run=TestAccEventsBus"
TF_ACC=1 go1.22.5 test ./internal/service/events/... -v -count 1 -parallel 1  -run=TestAccEventsBus -timeout 360m
=== RUN   TestAccEventsBusDataSource_basic
=== PAUSE TestAccEventsBusDataSource_basic
=== RUN …
```

rd/aws_cloudwatch_event_bus: Add `kms_key_identifier` argument

---

website/docs/d/iam_account_alias.html.markdown

Updates documentation on `data "aws_iam_account_alias" "current" {}` documentation page example section ( https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/iam_account_alias ) where output says `account_id` while it echoes the account alias. ( I think this was a copy paste mistake by someone in the past )

docs: update account alias output docs

---

.changelog/38559.txt
internal/service/elasticache/user_group_association.go
website/docs/r/elasticache_user_group_association.html.markdown

The default create and delete values will be 10 minutes, matching the previously hardcoded values.
Closes #38555
- https://developer.hashicorp.com/terraform/language/resources/syntax#operation-timeouts
```console
% make testacc PKG=elasticache TESTS="TestAccElastiCacheUserGroupAssociation_"
TF_ACC=1 go1.22.5 test ./internal/service/elasticache/... -v -count 1 -parallel 20 -run='TestAccElastiCacheUserGroupAssociation_'  -timeout 360m
--- PASS: TestAccElastiCacheUserGroupAssociation_disappears (285.34s)
--- PASS: TestAccElastiCacheUserGroupAssociation_basic (286.65s)
--- PASS: TestAccElastiCacheUserGroupAssociation_multiple (404.72s)
--- PASS: TestAccElastiCacheUserGroupAssociation_update …
```

r/aws_elasticache_user_group_association: add configurable timeouts

---

.changelog/38569.txt
internal/service/pipes/log_configuration.go
internal/service/pipes/pipe_test.go
website/docs/r/pipes_pipe.html.markdown

This PR is to add the `include_execution_data` argument to the `log_configuration` block for the `aws_pipes_pipe` resource.
While running the acceptance tests, I found that the `TestAccPipesPipe_rabbitMQSourceEventBusTarget` failed due a deprecated version of RabbitMQ version. I've updated the version to 3.12.13 to fix the test case as part of this PR.
Closes #38565
Referred to [PipeLogConfiguration](https://docs.aws.amazon.com/eventbridge/latest/pipes-reference/API_PipeLogConfiguration.html) for specs.
```console
$ make testacc TESTS=TestAccPipesPipe_ PKG=pipes
TF_ACC=1 go1.22.5 test ./internal/service/pipes/... -v -count 1 -parallel 20 -run='TestAccPipesPipe_'  -timeout 360m
=== RUN …
```

feat: add log_configuration.include_execution_data arg for aws_pipes_pipe

---

.changelog/38570.txt
internal/service/appsync/appsync_test.go
internal/service/appsync/graphql_api.go
internal/service/appsync/graphql_api_test.go
website/docs/r/appsync_graphql_api.html.markdown

This PR is to add the `enhanced_metrics_config` configuration block to the `aws_appsync_graphql_api` resource.
Closes #38566
Referred to [EnhancedMetricsConfig](https://docs.aws.amazon.com/appsync/latest/APIReference/API_EnhancedMetricsConfig.html) for specs.
```console
$ make testacc TESTS="TestAccAppSync_serial/GraphQLAPI/basic|TestAccAppSync_serial/GraphQLAPI/enhancedMetricsConfig" PKG=appsync
TF_ACC=1 go1.22.5 test ./internal/service/appsync/... -v -count 1 -parallel 20 -run='TestAccAppSync_serial/GraphQLAPI/basic|TestAccAppSync_serial/GraphQLAPI/enhancedMetricsConfig'  -timeout 360m
=== RUN   TestAccAppSync_serial
=== PAUSE TestAccAppSync_serial
=== CONT  TestAccAppSync_serial
=== RUN …
```

feat: Add enhanced_metrics_config config block for aws_appsync_graphql_api

---

.changelog/38571.txt
internal/service/appstream/image_data_source.go

This PR is to fix the create timestamp comparison logic that determines the most recent image for the `aws_appstream_image` data source.
Since the acceptance tests does not really check for the actual image to see whether it's the most recent, I've done a manual test by comparing the result from the following TF configuration and the console.
```terraform
data "aws_appstream_image" "test" {
name_regex  = "^AppStream-Graphics-.*-WinServer.*$"
type        = "PUBLIC"
most_recent = true
}
output "image_id" {
value = data.aws_appstream_image.test.name
}
```
Results from re-apply after the code fix:
```console
PS C:\working\tf-test> terraform apply
╷
│ Warning: Provider development overrides are in effect
│
│ The following provider development overrides are set in the CLI configuration:
│  - …
```

fix: Fix create timestamp cmp for aws_appstream_image data source

---

internal/acctest/acctest.go
internal/service/ce/cost_allocation_tag_test.go
internal/service/ce/cost_category_data_source_test.go
internal/service/ce/cost_category_test.go

This PR is to add prechecks for payer accounts to the acceptance tests for the `aws_ce_cost_allocation_tag` resource, and the `aws_ce_cost_category` resource and data source.
Closes #38465
n/a
In a non-payer/org member account:
```console
$ make testacc TESTS="TestAccCECostAllocationTag|TestAccCECostCategory" PKG=ce
TF_ACC=1 go1.22.5 test ./internal/service/ce/... -v -count 1 -parallel 20 -run='TestAccCECostAllocationTag|TestAccCECostCategory'  -timeout 360m
=== RUN   TestAccCECostAllocationTag_basic
=== PAUSE TestAccCECostAllocationTag_basic
=== RUN   TestAccCECostAllocationTag_disappears
=== PAUSE TestAccCECostAllocationTag_disappears
=== RUN   TestAccCECostCategoryDataSource_basic
=== …
```

chore: Add payer account precheck for CE tests

---

.github/actions/community_check/action.yml
.github/workflows/pull_request_target.yml

While looking into the PR linked below, I realized that the community check wasn't working quite as expected. The culprit was the use of the `$INPUT_` variables, which works with `nektos/act`, but doesn't appear to work as expected in reality. I tested this solution in my private test repo (which reproduced the incorrect behavior), and this resolves it.
While troubleshooting, I made a few other changes that I thought were worth keeping, and so are included:
- The Labelers job was generating a token using a GitHub App. It was the only job in this workflow to do so, so wasn't saving us any time or making anything more secure. That's been replaced with using the automatically generated token and restricting its permissions at the job level.
- Core Contributor and Partner PRs now get their …

Fix pull request target labeler

---

.changelog/38595.txt
internal/service/networkmanager/core_network_policy_document_data_source_test.go
internal/service/networkmanager/core_network_policy_model.go

Customise marshalling for single wildcards to match services expectation.
Closes #38145
```console
make testacc TESTS=TestAccNetworkManagerCoreNetworkPolicyDocumentDataSource PKG=networkmanager
TF_ACC=1 go1.22.5 test ./internal/service/networkmanager/... -v -count 1 -parallel 20 -run='TestAccNetworkManagerCoreNetworkPolicyDocumentDataSource'  -timeout 360m
=== RUN   TestAccNetworkManagerCoreNetworkPolicyDocumentDataSource_basic
=== PAUSE TestAccNetworkManagerCoreNetworkPolicyDocumentDataSource_basic
=== RUN   TestAccNetworkManagerCoreNetworkPolicyDocumentDataSource_serviceInsertion
=== PAUSE TestAccNetworkManagerCoreNetworkPolicyDocumentDataSource_serviceInsertion
=== RUN …
```

Core CoreNetworkPolicyException when a policy has a single wildcard in `when_sent_to`

---

internal/acctest/acctest.go
internal/service/cloudsearch/domain_service_access_policy_test.go
internal/service/cloudsearch/domain_test.go

his PR is to add a precheck, which ensures that the account is allowlisted to create new CloudSearch domains (generally equates to the account having an existing CloudSerach domain prior to July 25, 2024), to the acceptance tests for the `aws_cloudsearch_domain` and `aws_cloudsearch_domain_service_access_policy` resources.
Closes #38584
n/a
**Note:** Unfortunately I don't have an account with existing CloudSearch domain, so I cannot test the case where it passes the check.
```console
$ make testacc TESTS="TestAccCloudSearchDomain_|TestAccCloudSearchDomainServiceAccessPolicy_" PKG=cloudsearch
TF_ACC=1 go1.22.5 test ./internal/service/cloudsearch/... -v -count 1 -parallel 20 …
```

chore: Add domain creation allowlist precheck for CloudSearch tests

---

docs/continuous-integration.md
mkdocs.yml

This will allow the footnotes in the relationship design standards design document to render properly.
Before:
After:

docs: add footnotes extension 

---

.changelog/38604.txt
internal/service/opensearchserverless/security_policy.go
internal/service/opensearchserverless/security_policy_test.go

The `policy` attribute is a string type, but requires the string to be valid json. The user can input json with the keys in any order, but the value stored in state will have the keys in order causing an error message on apply (see linked issue for details).
This resource is very similar to the `access_policy` resource which uses `jsontypes.Normalize` as the type instead of `types.String`. I have copied most of the implementation from `access_policy` and added tests which test using a string value instead of `jsonencode`.
closes #38603
```console
% make testacc TESTS=TestAccOpenSearchServerlessSecurityPolicy PKG=opensearchserverless
TF_ACC=1 go1.22.5 test …
```

fix(opensearchserverless): security_policy policy attribute doesn't normalize json strings

---

.changelog/38618.txt
internal/service/ec2/ipam_pool_cidr_allocation.go
internal/service/ec2/ipam_pool_cidr_allocation_test.go
website/docs/r/vpc_ipam_pool_cidr_allocation.html.markdown

Practitioner-facing changes
- Read `description` and `netmask_length` into state. This allows the resource to be imported when those arguments are specified
- Update documentation to specify arguments as force new
Internal changes
- Test for `description` create, import, re-create
- Test for `netmask_length` import, re-create
- Test for `netmask_length` attribute when `cidr` argument is used in create
Closes #38613
Closes #38614
```console
% make testacc TESTARGS='-run=TestAccIPAMPoolCIDRAllocation_' PKG=ec2 ACCTEST_PARALLELISM=1
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 1  -run=TestAccIPAMPoolCIDRAllocation_ -timeout 360m
=== RUN …
```

b/aws_vpc_ipam_pool_cidr_allocation-read `description` and `netmask_length`

---

.changelog/38597.txt
.ci/.semgrep-service-name1.yml
internal/generate/servicesemgrep/service.tmpl
internal/service/ecr/exports_test.go
internal/service/ecr/repository_creation_template.go
internal/service/ecr/repository_creation_template_data_source.go
internal/service/ecr/repository_creation_template_data_source_test.go
internal/service/ecr/repository_creation_template_test.go
internal/service/ecr/service_package_gen.go
website/docs/d/ecr_repository_creation_template.html.markdown
website/docs/r/ecr_repository_creation_template.html.markdown

Adds support for ECR Repository Creation Templates.
Example:
```terraform
resource "aws_ecr_repository_creation_template" "example" {
prefix               = "example"
description          = "A description"
image_tag_mutability = "IMMUTABLE"
custom_role_arn      = "arn:aws:iam::123456689012:role/somerole"
applied_for = [
"PULL_THROUGH_CACHE",
]
encryption_configuration {
encryption_type = "AES256"
}
lifecycle_policy = "…"
repository_policy = "…"
resource_tags = {
One = "Two"
}
}
```
Closes #34503 
```console
% make testacc TESTS=TestAccECRRepositoryCreationTemplate PKG=ecr
TF_ACC=1 go test ./internal/service/ecr/... -v -count 1 -parallel 20 -run='TestAccECRRepositoryCreationTemplate' …
```

r/aws_ecr_repository_creation_template: New resource.

---

.changelog/38598.txt
internal/service/pipes/pipe.go
internal/service/pipes/pipe_test.go

Ensures the inputTemplate field of EventBridge pipes is reset only on change detected, so it's not removed on updates to other pipe attributes (such as filter criteria).
Closes #33938
```console
tin@tin-mbp ~/D/terraform-provider-aws (fix_eventbridge_input_template) [2]> make testacc TESTS=TestAccPipesPipe_targetParameters PKG=pipes
TF_ACC=1 go test ./internal/service/pipes/... -v -count 1 -parallel 20 -run='TestAccPipesPipe_targetParameters'  -timeout 360m
=== RUN   TestAccPipesPipe_targetParameters_inputTemplate
=== PAUSE TestAccPipesPipe_targetParameters_inputTemplate
=== RUN   TestAccPipesPipe_targetParameters_inputTemplate_preserveUnchanged
=== PAUSE …
```

fix: Reset EventBridge pipe input template only on change detected

---

internal/framework/flex/auto_expand.go
internal/framework/flex/auto_expand_test.go
internal/framework/flex/auto_flatten.go
internal/framework/flex/auto_flatten_test.go
internal/framework/flex/autoflex.go
internal/framework/flex/autoflex_test.go
internal/service/verifiedpermissions/identity_source.go

For some resources, the Create and Update calls take different parameter types. Adds `TypedExpander` interface to allow model types to customize their expansion when there may be different targets
```console
% make testacc PKG=verifiedpermissions TESTS=TestAccVerifiedPermissionsIdentitySource_
--- PASS: TestAccVerifiedPermissionsIdentitySource_disappears (13.44s)
--- PASS: TestAccVerifiedPermissionsIdentitySource_Cognito_basic (15.37s)
--- PASS: TestAccVerifiedPermissionsIdentitySource_OpenID_basic (15.43s)
--- PASS: TestAccVerifiedPermissionsIdentitySource_Cognito_convertToOpenID (26.30s)
--- PASS: TestAccVerifiedPermissionsIdentitySource_Cognito_update (26.41s)
--- PASS: TestAccVerifiedPermissionsIdentitySource_OpenID_convertToCognito (30.36s)
--- PASS: …
```

AutoFlex: Adds `TypedExpander` interface for models which can expand into multiple target types

---

.changelog/38630.txt
docs/acc-test-environment-variables.md
internal/service/chatbot/consts.go
internal/service/chatbot/exports_test.go
internal/service/chatbot/service_package_gen.go
internal/service/chatbot/teams_channel_configuration.go
internal/service/chatbot/teams_channel_configuration_test.go
website/docs/r/chatbot_teams_channel_configuration.html.markdown

Closes #12304
Relates #38124
We are currently unable to fully test this resource and ask for community with testing.
```console
% make t T=TestAccChatbotTeamsChannelConfiguration_serial K=chatbot
TF_ACC=1 go1.22.5 test ./internal/service/chatbot/... -v -count 1 -parallel 20 -run='TestAccChatbotTeamsChannelConfiguration_serial'  -timeout 360m
=== RUN   TestAccChatbotTeamsChannelConfiguration_serial
=== PAUSE TestAccChatbotTeamsChannelConfiguration_serial
=== CONT  TestAccChatbotTeamsChannelConfiguration_serial
=== RUN   TestAccChatbotTeamsChannelConfiguration_serial/basic
teams_channel_configuration_test.go:52: Environment variable CHATBOT_TEAMS_TEAM_ID is not set, skipping test
=== RUN …
```

aws_chatbot_teams_channel_configuration: New resource

---

.changelog/38547.txt
internal/service/sagemaker/domain.go
internal/service/sagemaker/domain_test.go
internal/service/sagemaker/sagemaker_test.go

Attribute `r_studio_package_manager_url` in SageMaker domain shows up in Terraform plan but is not used on API calls to AWS due to a typo.
Closes #38546
In order to run this tests you'd need a license shared from Posit to your account: https://docs.aws.amazon.com/sagemaker/latest/dg/rstudio-license.html
Please see comments below.

fix: typo r_studio_package_manager_url in sagemaker domain

---

.changelog/38602.txt
internal/service/datazone/exports_test.go
internal/service/datazone/glossary.go
internal/service/datazone/glossary_test.go
internal/service/datazone/service_package_gen.go
website/docs/r/datazone_glossary.html.markdown

This resource will allow practitioners to create DataZone Glossary for a DataZone Domain via Terraform.
Relates #37423 
```console
% make testacc TESTS=TestAccDataZoneGlossary PKG=datazone
TF_ACC=1 go1.22.5 test ./internal/service/datazone/... -v -count 1 -parallel 20 -run='TestAccDataZoneGlossary'  -timeout 360m
=== RUN   TestAccDataZoneGlossary_basic
=== PAUSE TestAccDataZoneGlossary_basic
=== RUN   TestAccDataZoneGlossary_update
=== PAUSE TestAccDataZoneGlossary_update
=== RUN   TestAccDataZoneGlossary_disappears
=== PAUSE TestAccDataZoneGlossary_disappears
=== CONT  TestAccDataZoneGlossary_basic
=== CONT  TestAccDataZoneGlossary_disappears
=== CONT  TestAccDataZoneGlossary_update
--- …
```

[New Resource]: DataZone Glossary

---

.changelog/38657.txt
internal/service/sfn/state_machine.go

State Machine resource is currently unaware that the version_arn and revision_id attributes will be updated when the resource is updated. This result in resources that depend on the new version only getting updated on subsequent terraform runs.
Took inspiration from how Lambda and CloudFormation resources are handling the updates.
Closes #36272
```console
% make testacc PKG=sfn
=== RUN   TestAccSFNActivityDataSource_basic
=== PAUSE TestAccSFNActivityDataSource_basic
=== RUN   TestAccSFNActivity_basic
=== PAUSE TestAccSFNActivity_basic
=== RUN   TestAccSFNActivity_disappears
=== PAUSE TestAccSFNActivity_disappears
=== RUN   TestAccSFNActivity_tags
=== PAUSE TestAccSFNActivity_tags
=== RUN   TestAccSFNActivity_encryptionConfigurationCustomerManagedKMSKey
--- PASS: …
```

Fix state machine update bug

---

.changelog/38654.txt
internal/service/elbv2/const.go
internal/service/elbv2/target_group.go
internal/service/elbv2/target_group_test.go
website/docs/r/lb_target_group.html.markdown

Description
Added the unhealthy draining interval in target_state_health in elbv2
Relations
Closes https://github.com/hashicorp/terraform-provider-aws/issues/38393

[Enhancements] Unhealthy draining Internal in elbv2

---

docs/data-handling-and-conversion.md
internal/framework/flex/auto_expand_test.go
internal/framework/flex/auto_flatten_test.go
internal/framework/flex/autoflex.go
internal/framework/flex/options.go
internal/service/drs/replication_configuration_template.go
internal/service/lexv2models/exports_test.go
internal/service/lexv2models/intent.go
internal/service/lexv2models/intent_test.go
internal/service/lexv2models/slot.go
internal/service/lexv2models/slot_type.go

This AutoFlex option will allow a field name prefix to be passed into the `Flatten` and `Expand` functions to improve fuzzy matching between Terraform and AWS data structures. Replaces the previous method of providing the prefix via a context key.
Also adjusts the entry point of the ignored field names option from methods on the option struct to exported constructor functions. This should simplify the syntax when used in service packages.
Closes #37266
```console
% make testacc PKG=drs TESTS=TestAccDRSReplicationConfigurationTemplate_
TF_ACC=1 go1.22.5 test ./internal/service/drs/... -v -count 1 -parallel 20 -run='TestAccDRSReplicationConfigurationTemplate_'  -timeout 360m
=== RUN …
```

internal/framework/flex: add field name prefix option 

---

website/docs/r/lightsail_disk.html.markdown

The resource description (argument as well as attribute reference)  contains multiple times the term "load balancer", but a lightsail disk is described here.
Closes #38256 
* [AWS CloudFormation reference](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lightsail-disk.html)
Not applicable as only documentation was updated.

docs: replace load balancer in resource description

---

website/docs/r/ecs_cluster.html.markdown

Fix one-character typo in `ecs_cluster` (originally added in https://github.com/hashicorp/terraform-provider-aws/commit/ecbc4ff5439ca66845acdd38ffc501dffbdb63a4): `configueration` -> `configuration`
I have not touched the cdk documentation (which has the same typos), as my understanding is that those are generated automatically (per [docs](https://hashicorp.github.io/terraform-provider-aws/documentation-changes/) and https://github.com/hashicorp/terraform-provider-aws/pull/37798).

Fix typo: configueration -> configuration

---

.changelog/38685.txt
internal/service/ecr/repository_creation_template.go
internal/service/ecr/repository_creation_template_data_source.go
internal/service/ecr/repository_creation_template_data_source_test.go
internal/service/ecr/repository_creation_template_test.go
website/docs/r/ecr_repository_creation_template.html.markdown

This fixes the `aws_ecr_repository_creation_template` resource and data source so they accept `ROOT` as a valid value. I think this was missed as I originally copied the validator from the pull-through cache code without adding this additional special case.
Tests added, explicitly not using `ParallelTest` so the resource and data source tests don’t fight over the one template that can exist.
Closes #38650 
```console
% make testacc TESTS=TestAccECRRepositoryCreationTemplate PKG=ecr
TF_ACC=1 go test ./internal/service/ecr/... -v -count 1 -parallel 20 -run='TestAccECRRepositoryCreationTemplate'  -timeout 360m
=== RUN   TestAccECRRepositoryCreationTemplateDataSource_basic
=== PAUSE …
```

fix: Allow ROOT as a Repository Creation Template prefix

---

.changelog/38661.txt
internal/service/lexv2models/bot.go
internal/service/lexv2models/bot_locale.go
internal/service/lexv2models/bot_version.go

Fixes `_disappears` tests for the bot, bot locale, and bot version resources which were not handling `PreconditionFailedException` errors.
Before:
```console
% make testacc PKG=lexv2models TESTS="TestAccLexV2ModelsBot_disappears|TestAccLexV2ModelsBotLocale_disappears|TestAccLexV2ModelsBotVersion_disappears"
TF_ACC=1 go1.22.5 test ./internal/service/lexv2models/... -v -count 1 -parallel 20 -run='TestAccLexV2ModelsBot_disappears|TestAccLexV2ModelsBotLocale_disappears|TestAccLexV2ModelsBotVersion_disappears'  -timeout 360m
bot_test.go:124: Error running post-test destroy, there may be dangling resources: exit status 1
Error: deleting AWS Lex V2 Models Bot ("5FUXN7KX75"): operation error Lex …
```

r/aws_lexmodelsv2(test): handle `PreconditionFailedException` on delete

---

internal/service/sns/topic_subscription_test.go

Before:
```console
% make testacc PKG=sns TESTS=TestAccSNSTopicSubscription_autoConfirming
TF_ACC=1 go1.22.5 test ./internal/service/sns/... -v -count 1 -parallel 20 -run='TestAccSNSTopicSubscription_autoConfirming'  -timeout 360m
=== NAME  TestAccSNSTopicSubscription_autoConfirmingEndpoint
topic_subscription_test.go:536: Step 1/2 error: Error running apply: exit status 1
Error: creating Lambda Function (tf-acc-test-913109990468982250): operation error Lambda: CreateFunction, https response error StatusCode: 400, RequestID: a7a32e51-557b-4d89-879a-77fe32ce61f3, InvalidParameterValueException: The runtime parameter of python3.7 is no longer supported for creating or updating AWS Lambda …
```

r/aws_sns_topic_subscription(test): fix auto confirming acceptance tests

---

.changelog/38689.txt
internal/service/ec2/ec2_capacity_block_reservation.go

Fix error while flattening.
Closes #38652
Best effort resource.
```console
...
```

b/aws_ec2_capacity_block_reservation: add `created_date` attribute

---

.changelog/38642.txt
internal/service/networkmanager/core_network_policy_model.go

Fixes the `"$.network-function-groups: null found, array expected"` error when creating a `aws_networkmanager_core_network` resource with the `create_base_policy` argument set to true. Also fixes currently failing acceptance tests for the `aws_networkmanager_core_network` resource.
Closes #38255
Core network policy version parameters in AWS Cloud WAN: https://docs.aws.amazon.com/network-manager/latest/cloudwan/cloudwan-policies-json.html
```console
$ make testacc TESTS='TestAccNetworkManagerCoreNetwork__*' PKG=networkmanager ACCTEST_PARALLELISM=3
TF_ACC=1 go1.22.5 test ./internal/service/networkmanager/... -v -count 1 -parallel 3 -run='TestAccNetworkManagerCoreNetwork__*'  -timeout 360m …
```

[Bugfix] r/aws_networkmanager_core_network: Fix network-function-groups null error with base policy

---

internal/provider/provider_acc_test.go

DMS has been migrated to AWS SDK for Go V2, and thus the corresponding `DMSConn` method to create a V1 client no longer exists. The generic `TestAccProvider_endpoints` test effectively ignores services which use V2 AWS SDK clients with the following conditional in the test check function (`serviceConn` will always return a method name ending in `Conn`):
```go
methodName := serviceConn(serviceKey)
method := reflect.ValueOf(providerClient).MethodByName(methodName)
if !method.IsValid() {
continue
}
```
Because this generic test check ignores V2 clients, the DMS case for the unusual endpoints tests has been removed entirely rather than including new conditional logic which would effectively just skip the case before executing any real checks.
Relates #37780
```console
% TF_ACC=1 go test …
```

internal/provider(test): remove DMS from unusual endpoint tests

---

internal/framework/flex/auto_expand_test.go
internal/framework/flex/auto_flatten_test.go
internal/framework/flex/autoflex.go
internal/framework/flex/autoflex_test.go
internal/framework/flex/options.go

This option will allow a suffix to be provided which can improve matching of field names between Terraform and AWS data structures. This can be useful in cases where field names differ by a consistent suffix between the Create/Update and Read AWS data structures.
Closes #38626

internal/framework/flex: add WithFieldNameSuffix option

---

website/docs/r/wafv2_web_acl.html.markdown

The [example](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/wafv2_web_acl#managed-rule) provided in the documentation does not pass a `terraform validate` run.
Reason: `token_domains` is in the wrong place. In the example it is part of a `rule` inside , but it needs to be provided on resource level.  Under references I provided a link to the relevant source code section.
Closes #38703 
- [Source code reference](https://github.com/hashicorp/terraform-provider-aws/blob/0a8bbd706b6e776e343dde4409c27ad41ca5636a/internal/service/wafv2/web_acl.go#L171)

docs: move attribute to correct location in example code

---

internal/service/s3/bucket_notification_test.go
internal/service/s3/bucket_policy_data_source_test.go
internal/service/s3/bucket_policy_test.go
internal/service/s3/bucket_replication_configuration_test.go
internal/service/s3/bucket_test.go

With the release of the AWS Service Principal Name Data Source in [v5.60.0](https://github.com/hashicorp/terraform-provider-aws/releases/tag/v5.60.0) this PR updates S3 test resources to use it, in order to provide more effective testing across partitions
Relates #38307
N/A
```console
%  TF_ACC=1 go test ./internal/service/s3/ -v -run="TestAccS3BucketPolicyDataSource"
=== RUN   TestAccS3BucketPolicyDataSource_basic
=== PAUSE TestAccS3BucketPolicyDataSource_basic
=== CONT  TestAccS3BucketPolicyDataSource_basic
--- PASS: TestAccS3BucketPolicyDataSource_basic (18.81s)
PASS
% TF_ACC=1 go test ./internal/service/s3/ -v -run="TestAccS3BucketPolicy"
=== RUN   TestAccS3BucketPolicyDataSource_basic
=== PAUSE TestAccS3BucketPolicyDataSource_basic
=== RUN   TestAccS3BucketPolicy_basic
=== PAUSE …
```

tests(s3): updated s3 test data config to use aws_service_principal data source

---

.changelog/38716.txt
internal/service/batch/job_definition.go

Extra nil check in the `aws_batch_job_definition` resource
Closes #38710
Closes #38684 
```console
% make testacc TESTS=TestAccXXX PKG=batch
...
```

[BUG] `aws_batch_job_definition`: add extra nil checks

---

internal/service/appautoscaling/sweep.go
internal/service/appflow/sweep.go
internal/service/iam/sweep.go
internal/service/lakeformation/sweep.go
internal/service/m2/sweep.go
internal/service/sqs/sweep.go
internal/service/xray/sweep.go
internal/sweep/awsv1/register.go
internal/sweep/awsv2/register.go
internal/sweep/context.go
internal/sweep/internal/log/log.go
internal/sweep/sweep.go

Adds `awsv2.Register` to transparently handle AWS SDK for Go v2 errors
Moves `sweep.Register` to `awsv1` to clarify that it's for AWS SDK for Go v1

sweepers: Separates `Register` functions for AWS SDK versions

---

internal/service/ds/directory.go
internal/service/ds/sweep.go

Sweeping a large number of directories, e.g. 20 would hit rate limits that prevented any directories from being swept. Adds some delay, which addresses the rate limit to some extent.

sweeper/aws_directory_service_directory:Addresses API rate limiting when sweeping many directories

---

.changelog/38756.txt
internal/service/elbv2/trust_store_revocation.go

Previously the error was appended to the existing diagnostics but not returned, allowing the create operation to proceed and eventually attempt dereferencing a nil pointer to the create API response.
Closes #38353 
```console
% make testacc PKG=elbv2 TESTS=TestAccELBV2TrustStoreRevocation_
TF_ACC=1 go1.22.6 test ./internal/service/elbv2/... -v -count 1 -parallel 20 -run='TestAccELBV2TrustStoreRevocation_'  -timeout 360m
--- PASS: TestAccELBV2TrustStoreRevocation_basic (53.44s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/elbv2      59.341s
```

r/aws_elbv2_trust_store_revocation: fix to properly return create errors

---

.changelog/38752.txt
internal/service/quicksight/account_subscription.go

Previously the read operation did not handle an `EmptyResultError` prior to attempting to reference fields from the output. The additional handling added in this change will prevent dereferencing of a nil output.
Closes #38637
```console
% make testacc PKG=quicksight TESTS="TestAccQuickSight_serial/AccountSubscription"
TF_ACC=1 go1.22.5 test ./internal/service/quicksight/... -v -count 1 -parallel 20 -run='TestAccQuickSight_serial/AccountSubscription'  -timeout 360m
--- PASS: TestAccQuickSight_serial (329.40s)
--- PASS: TestAccQuickSight_serial/AccountSubscription (329.40s)
--- PASS: …
```

r/aws_quicksight_account_subscription: fix panic reading nil account info

---

website/docs/r/guardduty_malware_protection_plan.html.markdown

Update the description for the argument `role` for resource `aws_guardduty_malware_protection_plan`. 
The existing documentation was not providing details on exact input (i.e. role name or ARN)
Closes #38719 
- [Source code reference](https://github.com/hashicorp/terraform-provider-aws/blob/30ff9c056572127506da56f67ed69be0b99799b4/internal/service/guardduty/malware_protection_plan.go#L83)

docs: improve role description details

---

internal/service/servicequotas/service_quota.go

Removes resource instead of throwing error when default quota value is not found. This can happen if an invalid quota exists in state.
```console
% make testacc PKG=servicequotas TESTS=TestAccServiceQuotasServiceQuota_
--- PASS: TestAccServiceQuotasServiceQuota_basic_Unset (14.68s)
--- PASS: TestAccServiceQuotasServiceQuota_basic (14.97s)
--- PASS: TestAccServiceQuotasServiceQuota_basic_hasUsageMetric (15.44s)
```

resource/aws_servicequotas_service_quota: Does not error when default value not found

---

.changelog/38773.txt
internal/service/emr/cluster.go

Fixes a panic when reading an instance fleet with an empty `launch_specifications` argument.
Closes #38276
```console
% make testacc PKG=emr TESTS=TestAccEMRCluster_
TF_ACC=1 go1.22.6 test ./internal/service/emr/... -v -count 1 -parallel 20 -run='TestAccEMRCluster_'  -timeout 360m
--- PASS: TestAccEMRCluster_basic (434.89s)
=== CONT  TestAccEMRCluster_autoTerminationPolicy
--- PASS: TestAccEMRCluster_Step_basic (458.24s)
=== CONT  TestAccEMRCluster_MasterInstanceGroup_instanceCount
--- PASS: TestAccEMRCluster_sJSON (463.57s)
=== CONT  TestAccEMRCluster_security
--- PASS: TestAccEMRCluster_additionalInfo (478.89s)
=== CONT  TestAccEMRCluster_MasterInstanceGroup_name
--- PASS: …
```

r/aws_emr_cluster: fix panic reading instance fleet

---

.changelog/38799.txt
internal/service/bedrockagent/agent_knowledge_base_association.go
website/docs/r/bedrockagent_agent_knowledge_base_association.html.markdown

After associating a knowledge base we need to prepare the agent again before we can use it.
Closes #38660
```console
% make testacc TESTS=TestAccBedrockAgentAgentKnowledgeBaseAssociation_ PKG=bedrockagent
TF_ACC=1 go1.22.6 test ./internal/service/bedrockagent/... -v -count 1 -parallel 20 -run='TestAccBedrockAgentAgentKnowledgeBaseAssociation_'  -timeout 360m
=== RUN   TestAccBedrockAgentAgentKnowledgeBaseAssociation_basic
=== PAUSE TestAccBedrockAgentAgentKnowledgeBaseAssociation_basic
=== RUN   TestAccBedrockAgentAgentKnowledgeBaseAssociation_update
=== PAUSE TestAccBedrockAgentAgentKnowledgeBaseAssociation_update
=== RUN   TestAccBedrockAgentAgentKnowledgeBaseAssociation_disappears
=== …
```

Prepare agent after knowledge base association

---

.changelog/38797.txt
internal/service/elasticache/replication_group.go

In cases where the `NodeGroups` list in the read ouput is empty, the provider would crash attempting to read the `NodeGroupMembers` count from the first item in the list.
Closes #37771
```console
% make testacc PKG=elasticache TESTS="TestAccElastiCacheReplicationGroup_basic|TestAccElastiCacheReplicationGroup_ClusterMode_basic"
TF_ACC=1 go1.22.6 test ./internal/service/elasticache/... -v -count 1 -parallel 20 -run='TestAccElastiCacheReplicationGroup_basic|TestAccElastiCacheReplicationGroup_ClusterMode_basic'  -timeout 360m
--- PASS: TestAccElastiCacheReplicationGroup_basic_v5 (775.08s)
--- PASS: TestAccElastiCacheReplicationGroup_basic (775.23s)
--- PASS: …
```

r/aws_elasticache_replication_group: fix crash setting `replicas_per_node_group`

---

.changelog/38800.txt
internal/service/events/connection.go

Changes the location of the type assertion to `[]interface{}` on all expanders to prevent nil values from triggering a crash. Adjusts all expanders to check for nil items in an `[]interface{}` before asserting to `map[string]interface{}`.
Closes #35326
Closes #31671 
```console
% make testacc PKG=events TESTS=TestAccEventsConnection_
TF_ACC=1 go1.22.6 test ./internal/service/events/... -v -count 1 -parallel 20 -run='TestAccEventsConnection_'  -timeout 360m
--- PASS: TestAccEventsConnection_disappears (14.70s)
--- PASS: TestAccEventsConnection_invocationHTTPParameters (31.96s)
--- PASS: TestAccEventsConnection_apiKey (33.89s)
--- PASS: TestAccEventsConnection_basic (33.99s)
--- PASS: …
```

r/aws_cloudwatch_event_connection: fix expander assertions

---

.changelog/38828.txt
internal/service/redshift/cluster.go

Closes #38827
```console
% make testacc TESTARGS="-run=TestAccRedshiftCluster_restoreFromSnapshot\|TestAccRedshiftCluster_basic\|TestAccRedshiftCluster_disappears" PKG=redshift
TF_ACC=1 go1.22.6 test ./internal/service/redshift/... -v -count 1 -parallel 20  -run=TestAccRedshiftCluster_restoreFromSnapshot\|TestAccRedshiftCluster_basic\|TestAccRedshiftCluster_disappears -timeout 360m
--- PASS: TestAccRedshiftCluster_basic (160.04s)
--- PASS: TestAccRedshiftCluster_disappears (165.32s)
--- PASS: TestAccRedshiftCluster_restoreFromSnapshotARN (490.19s)
--- PASS: TestAccRedshiftCluster_restoreFromSnapshot (628.82s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/redshift …
```

r/aws_redshift_cluster: set encrypted value on restore

---

website/docs/r/lb_listener.html.markdown

- Make explicit use of `ssl_policy` in the NLB example available [here](https://registry.terraform.io/providers/hashicorp/aws/5.62.0/docs/resources/lb_listener#forward-action).
- In addition, the description for `ssl_policy` changes slightly. In the original version below statement can be found
> Required if protocol is HTTPS or TLS.
Actually one does not need to specify an SSL policy when using `TLS`/`HTTPS` protocol. Whenever it is missing, the default SSL policy will be used. Details on this can found [here](https://docs.aws.amazon.com/elasticloadbalancing/latest/network/create-tls-listener.html#describe-ssl-policies).
To test this behaviour this code snippet can be used
```hcl
resource "aws_lb" "front_end" {
name               = "test"
internal           = true
load_balancer_type = …
```

docs: set explicit ssl_policy in network load balancer example

---

.changelog/38775.txt
internal/service/grafana/workspace.go

The expanders for the `network_access_control` and `vpc_configuration` arguments did not check for a list of one nil item, resulting in a failed type assertion and panic when a single, empty configuration is provided.
Closes #38264
```console
% make testacc PKG=grafana TESTS=TestAccGrafana_serial/Workspace
TF_ACC=1 go1.22.6 test ./internal/service/grafana/... -v -count 1 -parallel 20 -run='TestAccGrafana_serial/Workspace'  -timeout 360m
--- PASS: TestAccGrafana_serial (6114.72s)
--- PASS: TestAccGrafana_serial/Workspace (6114.72s)
--- PASS: TestAccGrafana_serial/Workspace/saml (350.87s)
--- PASS: TestAccGrafana_serial/Workspace/permissionType (402.51s)
--- PASS: …
```

r/aws_grafana_workspace: fix expander panics

---

.changelog/38776.txt
internal/service/iot/thing_group.go

Setting the `attribute_payload` argument to an empty block resulted the in the associated expander attempting to assert the lists single nil item into a map. This change adds a check for nil items to prevent this.
Closes #38093
```console
% make testacc PKG=iot TESTS=TestAccIoTThingGroup_
TF_ACC=1 go1.22.6 test ./internal/service/iot/... -v -count 1 -parallel 20 -run='TestAccIoTThingGroup_'  -timeout 360m
--- PASS: TestAccIoTThingGroup_disappears (12.93s)
--- PASS: TestAccIoTThingGroup_basic (15.24s)
--- PASS: TestAccIoTThingGroup_parentGroup (19.73s)
--- PASS: TestAccIoTThingGroup_properties (22.78s)
--- PASS: TestAccIoTThingGroup_tags (30.27s)
PASS
ok …
```

r/aws_iot_thing_group: fix crash with empty `attribute_payload` block

---

internal/framework/flex/auto_flatten.go
internal/framework/flex/auto_flatten_test.go
internal/framework/flex/autoflex.go

Fixes error when flattening `nil` primitive values
Closes #38830

AutoFlex: No longer log error when flattening `nil` primitive

---

.changelog/38798.txt
internal/service/networkmanager/connect_peer.go
internal/service/networkmanager/connect_peer_test.go

When you create a connect peer in AWS Network Manager, AWS sets up two BGP endpoints. However, the code for the `aws_networkmanager_connect_peer` resource only returns the first entry in the list. This commit updates the resource to loop over all BGP configurations returned by the API.
Closes #29680
```console
% make testacc TESTS='TestAccNetworkManagerConnectPeer_.*' PKG=networkmanager
TF_ACC=1 go1.22.6 test ./internal/service/networkmanager/... -v -count 1 -parallel 20 -run='TestAccNetworkManagerConnectPeer_.*'  -timeout 360m
=== RUN   TestAccNetworkManagerConnectPeer_basic
=== PAUSE TestAccNetworkManagerConnectPeer_basic
=== RUN   TestAccNetworkManagerConnectPeer_noDependsOn
=== PAUSE …
```

r/aws_networkmanager_connect_peer: return all BGP configurations

---

internal/service/ec2/ebs_default_kms_key_data_source_test.go
internal/service/ec2/ebs_default_kms_key_test.go
internal/service/ec2/ebs_test.go

tests for `aws_ebs_default_kms_key` fail intermittently when run in parallel.
```console
% make testacc TESTARGS='-run=TestAccEC2EBSDefaultKMSKey_basic\|TestAccEC2EBSDefaultKMSKeyDataSource_basic' PKG=ec2
TF_ACC=1 go1.22.6 test ./internal/service/ec2/... -v -count 1 -parallel 20  -run=TestAccEC2EBSDefaultKMSKey_basic\|TestAccEC2EBSDefaultKMSKeyDataSource_basic -timeout 360m
=== RUN   TestAccEC2EBSDefaultKMSKeyDataSource_basic
=== PAUSE TestAccEC2EBSDefaultKMSKeyDataSource_basic
=== RUN   TestAccEC2EBSDefaultKMSKey_basic
=== PAUSE TestAccEC2EBSDefaultKMSKey_basic
=== CONT  TestAccEC2EBSDefaultKMSKeyDataSource_basic
=== CONT  TestAccEC2EBSDefaultKMSKey_basic
ebs_default_kms_key_test.go:27: …
```

td/ebs_default_kms_key: run as serial test

---

.teamcity/components/generated/services_all.kt
internal/generate/teamcity/acctest_services.hcl
internal/service/appfabric/app_authorization.go

Converts `credentialModel` to `fwflex.Expander`. Prevents error log when expanding

resource/aws_appfabric_app_authorization: Convert `credentialModel` to `fwflex.Expander`

---

.ci/semgrep/framework/map_block_key.go
.ci/semgrep/framework/map_block_key.yml
.github/workflows/semgrep-ci.yml
.semgrepignore
GNUmakefile
internal/service/bedrockagent/agent_action_group.go
internal/service/lexv2models/intent.go
internal/service/lexv2models/slot.go
internal/service/ssmcontacts/rotation.go

While AutoFlex currently requires the struct field name of a Map Block Key to be `MapBlockKey`, the attribute name in the schema should be something meaningful rather than `map_block_key`. Adds a Semgrep rule to catch this and allows existing `map_block_key` attributes to ignore the rule.

Map Block Key fields should have meaningful names

---

internal/service/redshiftserverless/workgroup.go
internal/service/redshiftserverless/workgroup_test.go

The `Redshift Serverless Workgroup` resource can only update capacity arguments if a snapshot or recovery point exist.
Because the first recovery point can take a few minutes, you cannot update capacity arguments till this point has been created.
This means that the `TestAccRedshiftServerlessWorkgroup_baseAndMaxCapacityAndPubliclyAccessible` test which immediately after the initial creation tries to update the resource which in turn will fail.
That will also happen for any consumers of this resource that when they want to resize immediately after creation it will fail.
The API will return the following, I inaccurately assumed the API meant an actual snapshot but a recovery point suffices as well.
```
ValidationException: Failed to update the RPU capacity for Serverless workgroup. Wait …
```

fix: `TestAccRedshiftServerlessWorkgroup_baseAndMaxCapacityAndPubliclyAccessible` test in `redshiftserverless`

---

website/docs/r/pipes_pipe.html.markdown

The  [example](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/pipes_pipe#sqs-source-and-target-configuration-usage) in the documentation  fails when running `terraform validate`. The error message is
> Blocks of type "sqs_queue" are not expected here.
As mentioned in #38842 the correct name is `sqs_queue_parameters`.
In the References section I added a link to the source code/ schema for `target_parameters`.
Closes #38842 
- [Source code reference](https://github.com/hashicorp/terraform-provider-aws/blob/26accfa55c799e121ae1de17845facab0f920d6d/internal/service/pipes/target_parameters.go#L755)

docs: fix broken example code for aws_pipes_pipe

---

.changelog/38854.txt
.ci/.semgrep.yml
internal/service/acm/certificate_data_source.go
internal/service/appstream/stack.go
internal/service/controltower/landing_zone.go
internal/service/ecs/cluster_capacity_providers.go
internal/service/fms/policy.go
internal/service/rolesanywhere/profile.go
internal/service/rolesanywhere/trust_anchor.go
internal/service/s3/bucket_lifecycle_configuration.go

Fixes various calls to the `sdkdiag.AppendErrorf` function which are neither returned nor re-assigned to the `diags` variable.
Closes #38769
```console
% make testacc PKG=acm TESTS=TestAccACMCertificateDataSource_
TF_ACC=1 go1.22.6 test ./internal/service/acm/... -v -count 1 -parallel 20 -run='TestAccACMCertificateDataSource_'  -timeout 360m
--- PASS: TestAccACMCertificateDataSource_tags (17.25s)
--- PASS: TestAccACMCertificateDataSource_keyTypes (18.50s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/acm        24.817s
```
```console
% make testacc PKG=appstream TESTS=TestAccAppStreamStack_ …
```

[Bug]: Fix unreturned `sdkdiag.AppendErrorf` function calls

---

.changelog/38883.txt
internal/service/ecs/flex.go

This appears only to be possible with dynamic blocks as explicitly setting a nil `service_registries` block will prompt for the required attributes within the block. However, this fix should prevent the nil value from being expanded and causing a crash under the dynamic block scenario.
Closes #34166
```console
% make testacc PKG=ecs TESTS=TestAccECSService_ServiceRegistries
TF_ACC=1 go1.22.6 test ./internal/service/ecs/... -v -count 1 -parallel 20 -run='TestAccECSService_ServiceRegistries'  -timeout 360m
--- PASS: TestAccECSService_ServiceRegistries_basic (145.59s)
--- PASS: TestAccECSService_ServiceRegistries_container (145.60s)
--- PASS: TestAccECSService_ServiceRegistries_removal …
```

r/aws_ecs_service: fix crash from nil service_registries item

---

internal/framework/flex/auto_flatten.go
internal/framework/flex/auto_flatten_test.go
internal/framework/flex/autoflex.go
internal/framework/flex/logging_test.go

Updates handling of flattening `interface`:
* Logs error if not a valid conversion
* Logs if interface implements `json.JSONStringer` (the only valid source type to flatten to string)
* If flattening `json.JSONStringer` with `null ` value, logs that value is `null`
Closes #38671

autoflex: Corrects logging when flattening `interface`

---

website/docs/r/cloudfront_response_headers_policy.html.markdown

Add `remove_headers_config` example for the `aws_cloudfront_response_headers_policy` resource
Closes #38174
[Resource Page](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudfront_response_headers_policy)

docs: Add remove_headers_config example

---

go.mod
go.sum

This PR migrates the remaining `Redshift` resources to AWS SDKv2.
Closes https://github.com/hashicorp/terraform-provider-aws/issues/36201
Relates https://github.com/hashicorp/terraform-provider-aws/issues/32976
**Currently running tests overnight - will update results soon**
```console
...
```

Migrate `Redshift` resources to AWS SDK v2

---

docs/data-handling-and-conversion.md

Updates AutoFlex documentation with note about not using it for SDK to Framework migrations

AutoFlex: Add note about not using AutoFlex for SDK to Framework migrations

---

docs/add-a-new-resource.md

The guide was making a distinction between different cases but used the same name for both. It looks like it intended to use the actual case name for the `snake_case` example

Correct case name in new resource dev guide

---

website/docs/r/grafana_workspace.html.markdown

Add example for `configuration` to enable `Unified Grafana Alerting` and `Plugins Management` on Grafana Workspaces
Relates  #38826
[Resource Page](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/grafana_workspace)

docs: Add section with example for Grafana Workspace Options

---

docs/development-environment.md

This adds an extra requirement to the Development Environment docs, making it clear that raw Windows OS can't be used for building the plugin, since it requires `make` to be available.

Add OS requirement to development environment docs

---

.changelog/38921.txt
internal/service/ses/configuration_set.go

Migration of this service to AWS SDK for Go V2 unintentionally introduced an assertion to a pointer to bool, rather than a bool.
Closes #38918
Relates #38568
```console
% make testacc PKG=ses TESTS=TestAccSESConfigurationSet_
TF_ACC=1 go1.22.6 test ./internal/service/ses/... -v -count 1 -parallel 20 -run='TestAccSESConfigurationSet_'  -timeout 360m
--- PASS: TestAccSESConfigurationSet_disappears (13.24s)
--- PASS: TestAccSESConfigurationSet_deliveryOptions (15.27s)
--- PASS: TestAccSESConfigurationSet_basic (15.29s)
--- PASS: TestAccSESConfigurationSet_emptyDeliveryOptions (20.05s)
--- PASS: TestAccSESConfigurationSet_sendingEnabled (29.13s)
--- PASS: …
```

r/aws_ses_configuration_set: fix crash when `reputation_metrics_enabled` is set

---

internal/service/redshift/sweep.go
internal/service/redshiftserverless/sweep.go
internal/sweep/awsv2/skip.go

Fixes
```
2024/08/19 07:37:34 [DEBUG] Running Sweeper (aws_redshiftserverless_snapshot) in region (us-gov-east-1)
[signal SIGSEGV: segmentation violation code=0x2 addr=0x8 pc=0x11469c420]
goroutine 1 [running]:
github.com/hashicorp/terraform-provider-aws/internal/service/redshiftserverless.sweepSnapshots({0x16ae6373b, 0xd})
/Users/kewbank/altsrc.2/github.com/hashicorp/terraform-provider-aws/internal/service/redshiftserverless/sweep.go:137 +0x1c0
github.com/hashicorp/terraform-plugin-testing/helper/resource.runSweeperWithRegion({0x16ae6373b, 0xd}, 0x14000716ab0, 0x1400111ccf0, 0x14000726c00, 0x0)
/Users/kewbank/go/pkg/mod/github.com/hashicorp/terraform-plugin-testing@v1.10.0/helper/resource/testing.go:273 +0x42c …
```

Fix sweeper crashes

---

.changelog/38924.txt
internal/service/datazone/project.go
website/docs/r/datazone_project.html.markdown

Previously a diagnostic was appended to the response but the method did not return, resulting in an index out of bounds error when a non-delimited value is provided as the import identifier.
Closes #38923
```console
% make testacc PKG=datazone TESTS=TestAccDataZoneProject_
TF_ACC=1 go1.22.6 test ./internal/service/datazone/... -v -count 1 -parallel 20 -run='TestAccDataZoneProject_'  -timeout 360m
--- PASS: TestAccDataZoneProject_disappears (27.44s)
--- PASS: TestAccDataZoneProject_basic (29.53s)
--- PASS: TestAccDataZoneProject_update (41.54s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/datazone   47.580s
```

r/aws_datazone_project: properly surface import id parsing errors

---

go.mod
go.sum
internal/conns/awsclient_gen.go
internal/service/worklink/exports_test.go
internal/service/worklink/fleet.go
internal/service/worklink/fleet_test.go
internal/service/worklink/flex.go
internal/service/worklink/generate.go
internal/service/worklink/service_endpoint_resolver_gen.go
internal/service/worklink/service_endpoints_gen_test.go
internal/service/worklink/service_package_gen.go
internal/service/worklink/tags_gen.go
internal/service/worklink/website_certificate_authority_association.go
internal/service/worklink/website_certificate_authority_association_test.go
names/data/names_data.hcl
tools/tfsdk2fw/go.mod
tools/tfsdk2fw/go.sum

This PR migrates the `WorkLink` resources to AWS SDKv2.
Because this service has been deprecated all tests are skipped with an explanation.
Closes https://github.com/hashicorp/terraform-provider-aws/issues/36227
Relates https://github.com/hashicorp/terraform-provider-aws/issues/32976
```console
% make testacc TESTARGS='-run=TestAcc' PKG=worklink
TF_ACC=1 go1.22.6 test ./internal/service/worklink/... -v -count 1 -parallel 20  -run=TestAcc -timeout 360m
=== RUN   TestAccWorkLinkFleet_basic
fleet_test.go:27: skipping test; Amazon WorkLink has been deprecated and will be removed in the next major release
--- SKIP: TestAccWorkLinkFleet_basic (0.00s)
=== RUN   TestAccWorkLinkFleet_displayName …
```

Migrate `WorkLink` resources to AWS SDK v2

---

.changelog/38953.txt
internal/acctest/acctest.go
internal/service/dynamodb/table.go
internal/service/dynamodb/table_test.go
website/docs/r/dynamodb_table.html.markdown

Closes #34911
```console
% make testacc TESTARGS='-run=TestAccDynamoDBTable_restoreCrossRegion' PKG=dynamodb
TF_ACC=1 go1.22.6 test ./internal/service/dynamodb/... -v -count 1 -parallel 20  -run=TestAccDynamoDBTable_restoreCrossRegion -timeout 360m
--- PASS: TestAccDynamoDBTable_restoreCrossRegion (820.98s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/dynamodb	831.689s
```
```console
% make testacc TESTARGS='-run=TestAccDynamoDBTable_ -short' PKG=dynamodb
TF_ACC=1 go1.22.6 test ./internal/service/dynamodb/... -v -count 1 -parallel 20  -run=TestAccDynamoDBTable_ …
```

f/dynamodb_table: add `restore_source_table_arn` to support cross region table restore

---

website/docs/r/instance.html.markdown

The default value does not reflect reality and in #38294 there were two proposals to deal with the situation.
- Option 1: remove the information about a default value for `http_tokens`
- Option 2: recommend to configure that option explicitly
In this pull request I applied option 1.
For option 2 I tried to understand how a good/ correct recommendation could look like and learned how the `http_tokens` value is set. In the References section I added a link to my starting point, a specific section of the AWS SDK Go v2 code base. There the default value for `http_tokens` is defined by 
```go
//   - If the value of ImdsSupport for the Amazon Machine Image (AMI) for your
//   instance is v2.0 and the account level default is set to no-preference , the
//   default is required .
//
//   - If the …
```

docs: remove detail on default value for http_tokens

---

.changelog/38969.txt
internal/service/cloudformation/stack_set_instance.go

Fixes a crash caused by incorrect logic used to construct the multi-part key for `id` and improper handling of the error returned from the resource ID constructor helper.
Closes #38846
```console
%  make testacc PKG=cloudformation TESTS=TestAccCloudFormationStackSetInstance_
TF_ACC=1 go1.22.6 test ./internal/service/cloudformation/... -v -count 1 -parallel 20 -run='TestAccCloudFormationStackSetInstance_'  -timeout 360m
=== CONT  TestAccCloudFormationStackSetInstance_delegatedAdministrator
stack_set_instance_test.go:375: skipping test because at least one environment variable of [AWS_ALTERNATE_PROFILE AWS_ALTERNATE_ACCESS_KEY_ID] must be set. Usage: credentials for running acceptance …
```

r/aws_cloudformation_stack_set_instance: fix crash during ID construction

---

.changelog/38997.txt
internal/service/rds/cluster.go
internal/service/rds/cluster_test.go

The [AWS documentation](https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/data-api.html#data-api.enabling) clarifies this detail, but it's not mentioned in the Go SDK documentation. There are two methods to enable the HTTP endpoint (Data API): a newer method and an older method. The newer method, which applies to both provisioned and serverlessv2 engine modes, involves using the `EnableHTTPEndpoint` and `DisableHTTPEndpoint` operations. The older method involves modifying the DB cluster and setting the `EnableHttpEndpoint` field. Before this pull request, we were only using the older method.
Closes terraform-aws-modules/terraform-aws-rds-aurora#464
Closes #37125
```console
% make t T=TestAccRDSCluster_enableHTTPEndpoint K=rds            
make: Verifying source code with …
```

aws_rds_cluster: Fix Data API for serverlessv2

---

.changelog/38994.txt
internal/service/glue/trigger.go
internal/service/glue/trigger_test.go

Previously a null action caused the provider to panic. Now null actions are not expanded, which may result an error from the AWS API if only null actions are present, but prevents a complete crash.
Also addressed missing nil checks in the remaining expand functions for this resource.
Closes #31213
```console
% make testacc PKG=glue TESTS=TestAccGlueTrigger_Actions_null
TF_ACC=1 go1.22.6 test ./internal/service/glue/... -v -count 1 -parallel 20 -run='TestAccGlueTrigger_Actions_null'  -timeout 360m
--- PASS: TestAccGlueTrigger_Actions_null (6.53s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/glue       15.712s
```
```console
% make testacc PKG=glue …
```

r/aws_glue_trigger: fix crash when null `action` is configured

---

website/docs/r/rds_cluster.html.markdown

Adds a note to the `aws_rds_cluster` to give a bit of clarity around usage of `master_user_secret`.
Closes #38948
[Schema](https://github.com/hashicorp/terraform-provider-aws/blob/67c89ea17c8ee0ec8d86af82a9ffbe6ffc2318e3/internal/service/rds/cluster.go#L308-L327)
N/a, docs

`aws_rds_cluster `: Add note about `master_user_secret` usage

---

internal/service/lexmodels/sweep.go
internal/sweep/awsv2/skip.go

Fixes:
```
2024/08/23 10:40:01 [DEBUG] Running Sweeper (aws_lex_bot_alias) in region (us-gov-east-1)
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x10fcc0758]
goroutine 1 [running]:
github.com/hashicorp/terraform-provider-aws/internal/service/lexmodels.sweepBotAliases({0x16f6af72b, 0xd})
/Users/kewbank/altsrc.2/github.com/hashicorp/terraform-provider-aws/internal/service/lexmodels/sweep.go:67 +0x1f8
github.com/hashicorp/terraform-plugin-testing/helper/resource.runSweeperWithRegion({0x16f6af72b, 0xd}, 0x140011486f0, 0x1400109bd40, 0x140012ed6b0, 0x0)
/Users/kewbank/go/pkg/mod/github.com/hashicorp/terraform-plugin-testing@v1.10.0/helper/resource/testing.go:273 +0x42c …
```

lexmodels: Fix crash in sweepers

---

.github/workflows/label-notifications.yml

This change extends the existing workflow which prioritized issues labeled `regression`, including sending a slack notification. The workflow has been named more generically and completes the same steps for issues labeled `crash`.

chore(ci): notify and prioritize `crash` labeled issues

---

website/docs/r/auditmanager_control.html.markdown

Add two missing values for the attribute `keyword_input_type` of resource `auditmanager`.
Closes #39020 
- [Audit Manager API Reference](https://docs.aws.amazon.com/audit-manager/latest/APIReference/API_SourceKeyword.html#API_SourceKeyword_Contents)  
showing the three supported values for `keywordInputType`
- [Definition of `KeywordInputType` in AWS SDK Go v2](https://github.com/aws/aws-sdk-go-v2/blob/84ca95e16adf482b8a80069d5ffa85814c7f61a2/service/auditmanager/types/types.go#L1636)

docs: add missing types for keyword_input in auditmanager control

---

.changelog/39022.txt
internal/service/gamelift/game_server_group.go

The read operation assumed a non-`nil` value for the `AutoScalingGroupArn` field in the Describe API response. This field may be `nil` if the scaling group cannot be created or is deleted out of band. Previously, when a `nil` value was returned, the provider attempted to split the result to retrieve the name of the auto scaling group from the full ARN, resulting in an `index out of range` panic when referencing the second item of the split function.
The read operation now ensures the `AutoScalingGroupArn` field is not `nil` and can be split into the appropriate number of parts before attempting to complete subsequent read operations on the auto scaling group. When `nil`, these read operations are skipped entirely.
Closes #29759
```console
% make testacc PKG=gamelift …
```

r/aws_gamelift_game_server_group: fix crash reading group with nil ASG ARN

---

website/docs/r/db_option_group.html.markdown

- Fixed the mismatch in the documentation for `aws_db_option_group` for the `option_settings` blocked which had the fields `name` and `value` marked as optional when they are actually required
Closes #38992

docs(aws_db_option_group): fix requirement tags for `option_settings` block 

---

.changelog/39039.txt
internal/service/elbv2/listener.go

Adds a check to the `flattenLbForwardAction` function to verify the default actions attribute is known and not null before checking the length. Previously the length was checked without verifying the attribute was known, potentially resulting in a crash during read operations.
Closes #39031
```console
% make testacc PKG=elbv2 TESTS=TestAccELBV2Listener_
TF_ACC=1 go1.22.6 test ./internal/service/elbv2/... -v -count 1 -parallel 20 -run='TestAccELBV2Listener_'  -timeout 360m
--- PASS: TestAccELBV2Listener_mutualAuthenticationPassthrough (227.28s)
=== CONT  TestAccELBV2Listener_ActionForward_ForwardBlock_AddStickiness
--- PASS: TestAccELBV2Listener_mutualAuthentication (229.83s)
=== CONT …
```

r/aws_elbv2_listener: fix crash reading forward action

---

internal/service/glue/catalog_table_optimizer.go
internal/service/glue/catalog_table_optimizer_test.go
internal/service/glue/glue_test.go

Relates #38052
```console
% make testacc TESTARGS='-run=TestAccGlue_serial/CatalogTableOptimizer/' PKG=glue
TF_ACC=1 go1.22.6 test ./internal/service/glue/... -v -count 1 -parallel 20  -run=TestAccGlue_serial/CatalogTableOptimizer/ -timeout 360m
=== RUN   TestAccGlue_serial
=== PAUSE TestAccGlue_serial
=== CONT  TestAccGlue_serial
=== RUN   TestAccGlue_serial/CatalogTableOptimizer
=== RUN   TestAccGlue_serial/CatalogTableOptimizer/disappears
=== RUN   TestAccGlue_serial/CatalogTableOptimizer/basic
=== RUN   TestAccGlue_serial/CatalogTableOptimizer/update
=== PAUSE TestAccGlue_serial/CatalogTableOptimizer/update
=== CONT  TestAccGlue_serial/CatalogTableOptimizer/update
--- PASS: …
```

r/aws_glue_catalog_table_optimizer: add disappears test

---

.changelog/39041.txt
internal/service/amplify/app.go

The update operation was missing the appropriate checks to ensure nil values were not passed into the expander function.
Closes #29691
```console
% make testacc PKG=amplify TESTS=TestAccAmplify_serial/App
TF_ACC=1 go1.22.6 test ./internal/service/amplify/... -v -count 1 -parallel 20 -run='TestAccAmplify_serial/App'  -timeout 360m
--- FAIL: TestAccAmplify_serial (7326.08s)
--- FAIL: TestAccAmplify_serial/App (7326.08s)
--- PASS: TestAccAmplify_serial/App/tags (5258.13s)
--- PASS: TestAccAmplify_serial/App/tags/EmptyTag_OnCreate (292.74s)
--- PASS: TestAccAmplify_serial/App/tags/DefaultTags_providerOnly (311.60s)
--- PASS: TestAccAmplify_serial/App/tags/DefaultTags_nonOverlapping (302.30s) …
```

r/aws_amplify_app: fix crash updating `auto_branch_creation_config`

---

.changelog/39043.txt
internal/service/cognitoidp/user_pool.go
internal/service/cognitoidp/user_pool_test.go
website/docs/r/cognito_user_pool.html.markdown

This PR is to add a new argument `password_history_size` to the `password_policy` configuration block for the `aws_cognito_user_pool` to implement the [Password reuse prevention](https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-pool-settings-advanced-security-password-reuse.html) feature.
Closes #39016
Referred to [PasswordPolicyType](https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_PasswordPolicyType.html#CognitoUserPools-Type-PasswordPolicyType-PasswordHistorySize) for specs and wordings for documentation.
```console
$ make testacc TESTS"=TestAccCognitoIDPUserPool_passwordHistorySize|TestAccCognitoIDPUserPool_basic|TestAccCognitoIDPUserPool_withAdminCreateUserAndPasswordPolicy" PKG=cognitoidp …
```

feat: Add password_policy.password_history_size arg for aws_cognito_user_pool

---

internal/sweep/awsv2/skip.go

Fixes:
```
2024/08/27 08:38:49 [ERROR] Error running Sweeper (aws_route53_query_log) in region (us-gov-east-1): listing Route 53 Query Logging Configs (us-gov-east-1): operation error Route 53: ListQueryLoggingConfigs, https response error StatusCode: 403, RequestID: 0330c9f1-27f4-4049-8e6e-49b8878f6470, api error AccessDenied: The operation ListQueryLoggingConfigs is not available for the current AWS account 123456789012.
```

r/aws_route53_query_log: Fix sweeper in US GovCloud

---

website/docs/r/route53_health_check.html.markdown

The resource `aws_route53_health_check` contains a note that states
> At least one of either fqdn or ip_address must be specified.
The Route53 Health check supports different check types as described [here](https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/health-checks-types.html). In short, 
- endpoint
- calculated
- cloudwatch metric/ alarm
Only for endpoint checks it is required to specify IP address or FQDN. For the other types this is not applicable or even possible.
Closes #39013 
Links to the implementation in the AWS SDK GO v2 as we validate in the AWS provider code base against types defined there
```golang
names.AttrType: {
Type:             schema.TypeString,
Required:         true,
ForceNew:         true,
ValidateDiagFunc: enum.Validate[awstypes.HealthCheckType](), …
```

docs: update node for route53_health_check

---

internal/service/emr/managed_scaling_policy.go

Fix aws_emr_managed_scaling_policy for compatibility with the behavior of emr_cluster that was fixed as a part of the next problem
https://github.com/hashicorp/terraform-provider-aws/pull/16924
https://github.com/hashicorp/terraform-provider-aws/issues/7783
Relates https://github.com/hashicorp/terraform-provider-aws/pull/16924
Relates …

Fix EMR is not valid for managed_scaling_policy

---

names/data/read.go
skaff/datasource/datasource.go
skaff/function/function.go
skaff/resource/resource.go

Uses ServiceRecord data instead of `names` for `skaff`

Use ServiceRecord instead of `names` for `skaff`

---

.github/actions/team_working_board/README.md
.github/actions/team_working_board/action.yml
.github/workflows/pull_request_target.yml

Adds a new Composite Action to automate the team's working board. This lets us add logic to prevent no-op calls to `gh project item-edit` that have been failing lately. Bonus points, it cleans up the calling workflow files quite a bit, and will allow us to remove some of the infrastructure around the working board variables.
I used `act` to test locally using my test project, so it wasn't perfectly 1:1, but it worked. Since I'm not able to test this particularly well locally, I only moved `pull_request_target.yml` over to the new composite action, until we validate it.

Add Team Working Board Composite Action
