website/docs/r/db_instance_role_association.html.markdown
I wrote quite a [long comment](https://github.com/hashicorp/terraform-provider-aws/issues/38765#issuecomment-2313008183) on the referenced issue that gives more detail as to what's going on here. The tl;dr is:
- You can use a known, static string for `aws_db_instance.example.identifier`
- Since it's known, if `aws_db_instance.example` is recreated, Terraform has no reason to recreate the `aws_db_instance_role_association`, since the `db_instance_identifier` is unchanged
- On a second apply, the drift is detected/corrected
I didn't dig too far into when this became necessary, but I suspect it may have been when the `id` / `identifier` / `resource_id` changes happened ("Schema notes" in references).
I'm a bit on the fence on exactly how to document this. It's not required in all cases …
=> docs: `db_instance_role_association`: add `replace_triggered_by` to example config

internal/service/fms/sweep.go, internal/sweep/register_gen_test.go
Adds sweeper for `aws_fms_admin_account`. Deregisters FMS admin account or skips on `AccessDeniedException`
=> Adds sweeper for `aws_fms_admin_account`

.changelog/39090.txt, internal/service/sagemaker/wait.go
SageMaker endpoints are now taking a little over 10 minutes to become InService. This aligns the hardcoded endpoint timeout to 60 minutes.
This primarily effects SageMaker serverless endpoints. As an example, a test endpoint that deploys in >10m is using an xgboost model and associated container.
i.e.
```
...
module.tf_modules_sagemaker.module.endpoint.aws_sagemaker_endpoint.sagemaker_endpoint[0]: Still creating... [9m40s elapsed]
module.tf_modules_sagemaker.module.endpoint.aws_sagemaker_endpoint.sagemaker_endpoint[0]: Still creating... [9m50s elapsed]
module.tf_modules_sagemaker.module.endpoint.aws_sagemaker_endpoint.sagemaker_endpoint[0]: Still creating... [10m0s elapsed]
╷
│ Error: waiting for SageMaker Endpoint (ep-demo-sample-svrless) to be in service: timeout while waiting for state …
```
=> Increase endpointInServiceTimeout from 10m to 60m

.changelog/39107.txt, internal/service/wafv2/schemas.go
AWS recently announced the ability to have lower rate limits 
Closes #39106
https://aws.amazon.com/fr/about-aws/whats-new/2024/08/aws-waf-rate-based-rules-lower-rate-limits/
=> Improve aws_wafv2_web_acl (rate_based_statement limit now manage values from 10)

.changelog/39126.txt, internal/service/lexv2models/slot_type.go, internal/service/lexv2models/slot_type_test.go
Previously the `slot_type_values` validator limited the configuration to a maximum of 1 block. The corresponding AWS API accepts a minimum of 1 and maximum of 10000 items. This changes removes provider validation entirely, relying on the AWS API instead.
Before:
```console
% make testacc PKG=lexv2models TESTS=TestAccLexV2ModelsSlotType_values
TF_ACC=1 go1.23.0 test ./internal/service/lexv2models/... -v -count 1 -parallel 20 -run='TestAccLexV2ModelsSlotType_values'  -timeout 360m
slot_type_test.go:70: Step 1/2 error: Error running pre-apply plan: exit status 1
Error: Invalid Attribute Value
with aws_lexv2models_slot_type.test,
on terraform_plugin_test.tf line 62, in resource …
```
=> r/aws_lexmodelsv2_slot_type: fix `slot_type_values` validator

internal/service/quicksight/exports_test.go, internal/service/quicksight/refresh_schedule.go, internal/service/quicksight/refresh_schedule_test.go
Adds tests for setting `start_after_date_time` in `aws_quicksight_refresh_schedule`
```console
% make testacc PKG=quicksight TESTS=TestAccQuickSightRefreshSchedule_
--- PASS: TestAccQuickSightRefreshSchedule_invalidMonthlyRefresh (3.57s)
--- PASS: TestAccQuickSightRefreshSchedule_invalidWeeklyRefresh (3.70s)
--- PASS: TestAccQuickSightRefreshSchedule_invalidRefreshInterval (5.03s)
--- PASS: TestAccQuickSightRefreshSchedule_disappears (23.02s)
--- PASS: TestAccQuickSightRefreshSchedule_weeklyRefresh (24.40s)
--- PASS: TestAccQuickSightRefreshSchedule_startAfterDateTime (25.27s)
--- PASS: TestAccQuickSightRefreshSchedule_basic (25.27s)
--- PASS: TestAccQuickSightRefreshSchedule_monthlyRefresh (25.65s)
```
=> resource/aws_quicksight_refresh_schedule: Adds tests for `start_after_date_time`

internal/service/quicksight/data_source.go, website/docs/cdktf/python/r/quicksight_data_source.html.markdown, website/docs/cdktf/typescript/r/quicksight_data_source.html.markdown, website/docs/r/quicksight_data_source.html.markdown
Added databricks paramter into [aws\_quicksight\_data\_source | Resources | hashicorp/aws | Terraform | Terraform Registry](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/quicksight_data_source)
Closes #33616
I just followed the current code base, but please let me know if something is missing.
- [aws\_quicksight\_data\_source | Resources | hashicorp/aws | Terraform | Terraform Registry](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/quicksight_data_source)
- https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/quicksight@v1.43.0/types#DatabricksParameters
```console
%  make testacc PKG=quicksight TESTS=TestAccQuickSightDataSetDataSource …
```
=> feat: support databricks connectivity in quicksight data source

internal/framework/flex/autoflex.go
Updates `findFieldFuzzy` to take types instead of values and to return struct field instead of value and name
Relates #36815
=> AutoFlex: cleans up `findFieldFuzzy`

internal/acctest/acctest.go, internal/errs/unsupported.go, internal/service/dax/cluster_test.go, internal/service/mwaa/environment.go, internal/service/mwaa/exports_test.go, internal/service/mwaa/service_package_gen.go, internal/service/mwaa/sweep.go, internal/tfresource/retry.go
With the near completion of the migration to AWS SDK for Go v2 (https://github.com/hashicorp/terraform-provider-aws/issues/32976), cleanup any errant uses of `aws-sdk-go-base/v2/awsv1shim/v2/tfawserr` (which checks only AWS SDK for Go v1 errors).
```console
% SWEEPERS=aws_mwaa_environment make sweep
go1.23.0 test ./internal/sweep -v -sweep=us-west-2,us-east-1,us-east-2,us-west-1 -sweep-run='aws_mwaa_environment' -timeout 360m
2024/09/04 15:35:05 [DEBUG] Running Sweepers for region (us-west-2):
2024/09/04 15:35:05 [DEBUG] Running Sweeper (aws_mwaa_environment) in region (us-west-2)
2024/09/04 15:35:05 [DEBUG] sweeper: Configuring Terraform AWS Provider: sweeper_region=us-west-2
2024-09-04T15:35:05.404-0400 [DEBUG] …
```
=> Clean up uses of `aws-sdk-go-base/v2/awsv1shim/v2/tfawserr`

website/docs/r/lexv2models_slot.html.markdown
Adds an example documenting how to use the `value_elicitation_setting` with a `prompt_specification` configured to match the default configuration generated by AWS.
Also adds the argument reference for all nested arguments under `value_elicitation_setting`.
Closes #36845
- https://docs.aws.amazon.com/lexv2/latest/APIReference/API_SlotValueElicitationSetting.html
=> r/aws_lexv2models_slot(doc): add `value_elicitation_setting` example

go.mod, go.sum, internal/acctest/acctest.go, internal/service/networkmanager/core_network_policy_document_data_source.go, internal/service/networkmanager/core_network_policy_document_data_source_test.go
Fixes schema and generated JSON to match expectations of service per the bug in #38134 
Closes #38134
```console
% make testacc TESTS=TestAccNetworkManagerCoreNetworkPolicyDocumentDataSource_ PKG=networkmanager
TF_ACC=1 go1.23.0 test ./internal/service/networkmanager/... -v -count 1 -parallel 20 -run='TestAccNetworkManagerCoreNetworkPolicyDocumentDataSource_'  -timeout 360m
=== RUN   TestAccNetworkManagerCoreNetworkPolicyDocumentDataSource_basic
=== PAUSE TestAccNetworkManagerCoreNetworkPolicyDocumentDataSource_basic
=== RUN   TestAccNetworkManagerCoreNetworkPolicyDocumentDataSource_serviceInsertion
=== PAUSE TestAccNetworkManagerCoreNetworkPolicyDocumentDataSource_serviceInsertion
=== RUN …
```
=> Fix errors in JSON produced not matching service expectations

.changelog/39159.txt, internal/service/appsync/appsync_test.go, internal/service/appsync/graphql_api.go, internal/service/appsync/graphql_api_test.go, website/docs/r/appsync_graphql_api.html.markdown
Add the `api_type` and `merged_api_execution_role_arn` to support MERGED apis
Relates #33148
```console
%  make testacc TESTS=TestAccAppSync_serial/GraphQLAPI PKG=appsync
TF_ACC=1 go1.23.0 test ./internal/service/appsync/... -v -count 1 -parallel 20 -run='TestAccAppSync_serial/GraphQLAPI'  -timeout 360m
=== RUN   TestAccAppSync_serial
=== PAUSE TestAccAppSync_serial
=== CONT  TestAccAppSync_serial
=== RUN   TestAccAppSync_serial/GraphQLAPI
=== RUN   TestAccAppSync_serial/GraphQLAPI/basic
=== RUN   TestAccAppSync_serial/GraphQLAPI/OpenIDConnect_issuer
=== RUN   TestAccAppSync_serial/GraphQLAPI/UserPool_awsRegion
=== RUN   TestAccAppSync_serial/GraphQLAPI/xrayEnabled
=== RUN …
```
=> Add support for appsync MERGED api type

internal/service/autoscaling/group.go, internal/service/connect/routing_profile.go, internal/service/docdb/cluster_parameter_group.go, internal/service/kafka/scram_secret_association.go, internal/service/lakeformation/exports_test.go, internal/service/lakeformation/lf_tag.go, internal/service/lakeformation/lf_tag_test.go, internal/service/neptune/cluster_parameter_group.go, internal/service/neptune/parameter_group.go, internal/service/rds/cluster_parameter_group.go, internal/service/route53/zone.go, internal/service/ssm/document.go, internal/slices/slices.go, internal/slices/slices_test.go
Use the new Go 1.23 [`slices.Chunk`](https://go.dev/pkg/slices#Chunk) function as a replacement for our `internal/slices.Chunks`.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/38999.
```console
% make testacc TESTARGS='-run=TestAccLakeFormation_serial/^LFTags$$' PKG=lakeformation
TF_ACC=1 go1.23.0 test ./internal/service/lakeformation/... -v -count 1 -parallel 20  -run=TestAccLakeFormation_serial/^LFTags$ -timeout 360m
=== RUN   TestAccLakeFormation_serial
=== PAUSE TestAccLakeFormation_serial
=== CONT  TestAccLakeFormation_serial
=== RUN   TestAccLakeFormation_serial/LFTags
=== RUN   TestAccLakeFormation_serial/LFTags/values
=== RUN …
```
=> Use Go 1.23 `slices.Chunk` as a replacement for `internal/slices.Chunks`

website/docs/r/elasticsearch_domain.html.markdown
Updates the list of valid values for `tls_security_policy
Closes #39158
- [Schema](https://github.com/hashicorp/terraform-provider-aws/blob/6a28717037912f5b295495f18091cb62c2f658e9/internal/service/elasticsearch/domain.go#L379)
- [`types` reference for `TLSSecurityPolicy`](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/elasticsearchservice@v1.30.7/types#TLSSecurityPolicy)
N/a, docs
=> `aws_elasticache_domain`: Update list of valid options for `tls_security_policy`

.ci/semgrep/framework/flex.yml
With the general availability of AutoFlex, manual flexer functions should be discouraged.
Relates #36815
=> Adds Semgrep rules to discourage manual expanders and flatteners

internal/service/quicksight/sweep.go
Add handling for errors indicating the account is not configured with a default namespace. 
```
2024/09/05 13:58:18 [ERROR] Error running Sweeper (aws_quicksight_group) in region (us-west-2): error listing QuickSight Groups (us-west-2): operation error QuickSight: ListGroups, https response error StatusCode: 404, RequestID: 12a908dc-d8d2-4cd5-a146-9a354bcdcb07, ResourceNotFoundException: Account 727561393803 is not signed up with QuickSight with namespace default. AWS account ID: 727561393803, Namespace: default.
```
Also updates skip checks to use `tfawserr` for consistency with the shared sweeper skip checks.
```console
% make sweep SWEEPARGS=-sweep-run=aws_quicksight
go1.23.0 test ./internal/sweep -v …
```
=> r/aws_quicksight: fix groups sweeper

internal/service/apprunner/auto_scaling_configuration_version.go, internal/service/apprunner/custom_domain_association.go, internal/service/apprunner/default_auto_scaling_configuration_version.go, internal/service/codepipeline/custom_action_type.go, internal/service/codepipeline/webhook.go, internal/service/controltower/control.go, internal/service/controltower/controls_data_source.go, internal/service/securitylake/data_lake.go, internal/tfresource/not_found_error.go, internal/tfresource/not_found_error_test.go
After migration to AWS SDK for Go v2, finder functions that return multiple AWS API objects should return slices of values, not slices of pointers. This requires use of `tfresource.AssertSingleValueResult` instead of `tfresource.AssertSinglePtrResult`.
```console
% make testacc TESTARGS='-run=TestAccAppRunnerAutoScalingConfigurationVersion_' PKG=apprunner ACCTEST_PARALLELISM=3
TF_ACC=1 go1.23.0 test ./internal/service/apprunner/... -v -count 1 -parallel 3  -run=TestAccAppRunnerAutoScalingConfigurationVersion_ -timeout 360m
=== RUN   TestAccAppRunnerAutoScalingConfigurationVersion_tags
=== PAUSE TestAccAppRunnerAutoScalingConfigurationVersion_tags
=== RUN …
```
=> Tech debt: Replace `tfresource.AssertSinglePtrResult` by `tfresource.AssertSingleValueResult`

skaff/datasource/datasourcefw.gtpl
This PR is to replace the invalid variable reference `.Resource` with `.DataSource` in `datasourcefw.gtpl` which prevented `skaff datasource` from being run successfully to generate new data source artifacts.
Closes #39207
n/a
```console
$ cd internal/service/synthetics
$ skaff datasource -f -n RuntimeVersion
$
```
Source code and documentation are generated successfully.
=> fix: Replace bad .Resource ref with .DataSource in datasourcefw.gtpl

.changelog/39220.txt, internal/service/quicksight/user.go, website/docs/r/quicksight_user.html.markdown
Add validation support for the following QuickSight PRO user roles - `READER_PRO`, `AUTHOR_PRO`, and `ADMIN_PRO`.
NA
- Valid `UserRole` in AWS [documentation](https://docs.aws.amazon.com/quicksight/latest/APIReference/API_RegisterUser.html#API_RegisterUser_RequestSyntax)
```console
% AWS_REGION=us-east-1 make testacc TESTS=TestAccQuickSightUser PKG=quicksight
TF_ACC=1 go1.23.0 test ./internal/service/quicksight/... -v -count 1 -parallel 20 -run='TestAccQuickSightUser'  -timeout 360m
=== RUN   TestAccQuickSightUserDataSource_basic
=== PAUSE TestAccQuickSightUserDataSource_basic
=== RUN   TestAccQuickSightUser_basic
=== PAUSE TestAccQuickSightUser_basic
=== RUN   TestAccQuickSightUser_withInvalidFormattedEmailStillWorks
=== PAUSE …
```
=> Add validation support for QuickSight PRO user roles

internal/service/quicksight/sweep.go
Fixes sweeper error:
```
2024/09/09 08:47:00 [ERROR] Error running Sweeper (aws_quicksight_group) in region (us-east-2): error listing QuickSight Groups (us-east-2): operation error QuickSight: ListGroups, https response error StatusCode: 404, RequestID: c66b43e6-c7d3-48b6-be9c-55b6b994220a, ResourceNotFoundException: Namespace default not found in account 927163995318. AWS account ID: 927163995318, Namespace: default.
```
Relates https://github.com/hashicorp/terraform-provider-aws/pull/39168.
=> quicksight: `skipSweepUsersError` -> `skipSweepUsersOrGroupsError`

.changelog/39196.txt, internal/service/ec2/verifiedaccess_endpoint.go, internal/service/ec2/verifiedaccess_endpoint_test.go, internal/service/ec2/verifiedaccess_test.go
Fixes an incorrect assertion of a set type to an `[]interface{}`.
Closes #39186
```console
% make testacc PKG=ec2 TESTS=TestAccVerifiedAccess_serial/Endpoint/basic
TF_ACC=1 go1.23.0 test ./internal/service/ec2/... -v -count 1 -parallel 20 -run='TestAccVerifiedAccess_serial/Endpoint/basic'  -timeout 360m
--- PASS: TestAccVerifiedAccess_serial (0.59s)
--- PASS: TestAccVerifiedAccess_serial/Endpoint_networkInterface (1115.35s)
--- PASS: TestAccVerifiedAccess_serial/Endpoint_tags (1278.48s)
--- PASS: TestAccVerifiedAccess_serial/Endpoint_policyDocument (1289.64s)
--- PASS: TestAccVerifiedAccess_serial/Endpoint_basic (1371.40s)
--- PASS: TestAccVerifiedAccess_serial/Endpoint_disappears …
```
=> r/aws_verifiedaccess_endpoint: fix crash when updating `load_balancer_options.subnet_ids`

website/docs/cdktf/python/r/db_instance.html.markdown, website/docs/cdktf/typescript/r/db_instance.html.markdown, website/docs/r/db_instance.html.markdown
Update the documentation for `aws_db_instance` to add `io2` as a storage type option. This was applied for `aws_rds_cluster` but not `aws_db_instance`.
Relates #36252 
- https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/CHAP_Storage.html#Concepts.Storage
=> docs: Add io2 as an RDS DB instance storage_type

.changelog/35479.txt, internal/service/sagemaker/endpoint_configuration.go, internal/service/sagemaker/endpoint_configuration_test.go, website/docs/r/sagemaker_endpoint_configuration.html.markdown
Add managed_instance_scaling to sagemaker endpoint config production_variants
Fixes #35011
[Create Endpint Config API](https://docs.aws.amazon.com/sagemaker/latest/APIReference/API_CreateEndpointConfig.html)
```
$ make testacc TESTS=TestAccSageMakerEndpointConfiguration_productionVariantsManagedInstanceScaling PKG=sagemaker
TF_ACC=1 go1.22.5 test ./internal/service/sagemaker/... -v -count 1 -parallel 20 -run='TestAccSageMakerEndpointConfiguration_productionVariantsManagedInstanceScaling'  -timeout 360m
=== RUN   TestAccSageMakerEndpointConfiguration_productionVariantsManagedInstanceScaling
=== PAUSE TestAccSageMakerEndpointConfiguration_productionVariantsManagedInstanceScaling
=== CONT …
```
=> add managed_instance_scaling to sagemaker endpoint config production_variants

.changelog/39254.txt, internal/service/lexv2models/slot_type.go, internal/service/lexv2models/slot_type_test.go, website/docs/r/lexv2models_slot_type.html.markdown
Previously this nested argument was misnamed `audio_recognition_settings`. If the correct name was provided, Terraform would fail indicating the argument name did not exist.
```
│ Error: Unsupported argument
│
│   on main.tf line 71, in resource "aws_lexv2models_slot_type" "test":
│   71:       audio_recognition_strategy = "UseSlotValuesAsCustomVocabulary"
│
│ An argument named "audio_recognition_strategy" is not expected here.
```
If the incorrect name was provided, creation would fail as AutoFlex would be unable to write the result from the AWS data structure back to the Terraform data structure due to the mismatch in field names.
```
aws_lexv2models_slot_type.test: Creating...
╷
│ Error: Provider produced inconsistent result after apply
│
│ When applying changes to …
```
=> r/aws_lexv2models_slot_type: fix `audio_recognition_strategy` argument name

website/docs/r/ebs_snapshot_block_public_access.html.markdown
In the textual description of the resource, one of the mentioned/ allowed values is incomplete:
instead of  `block-all` it should read `block-all-sharing`.
In the refences section I provided a link to the official CF documentation.
Closes #39243 
- [CloudFormation documentation ](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-snapshotblockpublicaccess.html)
=> docs: update allowed value for state in ebs_snapshot_block_public_access

.changelog/39257.txt, internal/service/batch/job_queue_migrate.go
When the `aws_batch_job_queue` schema migration function is called, it returns a type conversion error.
Closes #39198
```console
% make testacc PKG=batch TESTS=TestAccBatchJobQueue_
--- PASS: TestAccBatchJobQueue_ComputeEnvironments_externalOrderUpdate (147.38s)
--- PASS: TestAccBatchJobQueue_tags_DefaultTags_emptyResourceTag (156.46s)
--- PASS: TestAccBatchJobQueue_tags_DefaultTags_nullNonOverlappingResourceTag (162.39s)
--- PASS: TestAccBatchJobQueue_tags_DefaultTags_nullOverlappingResourceTag (163.34s)
--- PASS: TestAccBatchJobQueue_tags_ComputedTag_OnCreate (164.75s)
--- PASS: TestAccBatchJobQueue_tags_DefaultTags_emptyProviderOnlyTag (164.76s)
--- PASS: TestAccBatchJobQueue_tags_EmptyTag_OnUpdate_Replace (186.04s)
--- PASS: TestAccBatchJobQueue_tags_AddOnUpdate (188.26s)
--- PASS: …
```
=> resource/aws_batch_job_queue: Fixes type conversion error in migration function

.changelog/39215.txt, internal/service/amplify/amplify_test.go, internal/service/amplify/app.go, internal/service/amplify/app_test.go, website/docs/r/amplify_app.html.markdown
This PR is to add the `cache_config` configuration block argument to the `aws_amplify_app` resource.
Closes #38864
Referred to [CreateApp](https://docs.aws.amazon.com/amplify/latest/APIReference/API_CreateApp.html) for specs and wordings.
```console
$ make testacc TESTS="TestAccAmplify_serial/App/basic|TestAccAmplify_serial/App/CacheConfig" PKG=amplify
TF_ACC=1 go1.23.0 test ./internal/service/amplify/... -v -count 1 -parallel 20 -run='TestAccAmplify_serial/App/basic|TestAccAmplify_serial/App/CacheConfig'  -timeout 360m
=== RUN   TestAccAmplify_serial
=== PAUSE TestAccAmplify_serial
=== CONT  TestAccAmplify_serial
=== RUN   TestAccAmplify_serial/App
=== RUN …
```
=> feat: Add cache_config arg for aws_amplify_app

website/docs/r/imagebuilder_image_recipe.html.markdown
The `systems_manager_agent.uninstall_after_build` argument does not have a default value. This change removes mention of a default from the registry documentation to avoid confusion about whether the argument must be provided.
Also includes some general cleanup for this resource documentation.
=> r/aws_imagebuilder_image_recipe(doc): remove uninstall_after_build default

.changelog/36440.txt, internal/service/costoptimizationhub/costoptimizationhub_test.go, internal/service/costoptimizationhub/enrollment_status.go, internal/service/costoptimizationhub/enrollment_status_test.go, internal/service/costoptimizationhub/exports_test.go, internal/service/costoptimizationhub/service_package_gen.go, website/docs/r/costoptimizationhub_enrollment_status.html.markdown
This change adds a new resource to Cost Optimization Hub
Related #34588
https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/costoptimizationhub
https://docs.aws.amazon.com/aws-cost-management/latest/APIReference/https://docs.aws.amazon.com/aws-cost-management/latest/APIReference/API_Operations_Cost_Optimization_Hub.html
```console
bash-3.2$ make testacc PKG=costoptimizationhub
TF_ACC=1 go test ./internal/service/costoptimizationhub/... -v -count 1 -parallel 20   -timeout 360m
=== RUN   TestAccCostOptimizationHub_serial
=== PAUSE TestAccCostOptimizationHub_serial
=== RUN   TestEndpointConfiguration
=== RUN   TestEndpointConfiguration/package_name_endpoint_config_overrides_service_config_file
=== RUN …
```
=> New resource: aws_costoptimizationhub_enrollment_status

.changelog/39315.txt, internal/service/synthetics/canary.go
Canary name can now be a maximum of 255 characters.
Closes #39313
Depends on #39299 
- https://github.com/aws/aws-sdk-go-v2/blob/main/CHANGELOG.md#release-2024-09-12
```console
% make testacc PKG=synthetics TESTS=TestAccSyntheticsCanary_
TF_ACC=1 go1.22.6 test ./internal/service/synthetics/... -v -count 1 -parallel 20 -run='TestAccSyntheticsCanary_'  -timeout 360m
--- PASS: TestAccSyntheticsCanary_runtimeVersion (98.95s)
--- PASS: TestAccSyntheticsCanary_artifactEncryption (100.34s)
--- PASS: TestAccSyntheticsCanary_tags (150.84s)
--- PASS: TestAccSyntheticsCanary_runEnvironmentVariables (155.54s)
--- PASS: TestAccSyntheticsCanary_runTracing (239.88s)
--- PASS: TestAccSyntheticsCanary_run …
```
=> r/aws_synthetics_canary: increase maximum `name` length to 255 characters

.changelog/39322.txt, internal/framework/flex/auto_flatten.go, internal/framework/types/smithy_json.go, internal/service/opensearchserverless/access_policy.go, internal/service/opensearchserverless/access_policy_test.go
Autoflex type check for `Interface` type checks that the interface is implemented
Closes #39319
```console
% make testacc TESTARGS='-run=TestAccOpenSearchServerlessAccessPolicy_' PKG=opensearchserverless
TF_ACC=1 go1.22.6 test ./internal/service/opensearchserverless/... -v -count 1 -parallel 20  -run=TestAccOpenSearchServerlessAccessPolicy_ -timeout 360m
--- PASS: TestAccOpenSearchServerlessAccessPolicy_disappears (13.68s)
--- PASS: TestAccOpenSearchServerlessAccessPolicy_basic (16.03s)
--- PASS: TestAccOpenSearchServerlessAccessPolicy_update (32.87s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/opensearchserverless	38.603s.
```
=> r/opensearchserverless_access_policy: policy is not set correctly

internal/framework/flex/auto_expand_test.go, internal/framework/flex/auto_flatten.go, internal/framework/flex/auto_flatten_test.go, internal/framework/flex/autoflex_test.go
Adds autoflex support for flattening struct fields that are of type slice of Smithy string [enum](https://smithy.io/2.0/spec/simple-types.html#enum) into our `StringEnum` Plugin Framework custom type.
Note that support for slice of string enum pointers was not added as these are not present in the AWS SDK for Go v2.
Closes https://github.com/hashicorp/terraform-provider-aws/issues/39292.
```console
% go test ./internal/framework/flex
ok  	github.com/hashicorp/terraform-provider-aws/internal/framework/flex	0.569s
```
=> AutoFlex: Flatten list/set of string enum struct fields

.changelog/39326.txt, internal/service/dynamodb/generate.go, internal/service/dynamodb/tags_gen.go
Previously the `TagResource` and `UntagResource` API's in the DynamoDB service were strongly consistent. An AWS change in August 2024 made these API's eventually consistent, resulting in failures when the `aws_dynamodb_tag` resource (or other resources which support the `tags` argument) attempted to read back tags at the end of a create or update operation. This change adds waiting logic into the generated `UpdateTags` function, ensuring the tags exist before proceeding with any subsequent read operations.
Closes #39275
```console
% make testacc PKG=dynamodb TESTS=TestAccDynamoDBTag_
TF_ACC=1 go1.22.6 test ./internal/service/dynamodb/... -v -count 1 -parallel 20 -run='TestAccDynamoDBTag_' …
```
=> r/aws_dynamodb: wait for tag propagation

.changelog/31284.txt, internal/service/dynamodb/table.go, internal/service/dynamodb/table_test.go, internal/service/dynamodb/wait.go
Fixes update DDB table action to only try and update replicas CMK if actually using a CMK.
Closes https://github.com/hashicorp/terraform-provider-aws/issues/31153
Built and tested this locally. Ran what was failing on the linked bug report which applied clean.
Before change:
```
❯ TF_ACC=1 go test ./internal/service/dynamodb/... -v -count 1 -parallel 20 -run='TestAccDynamoDBTable_Replica_singleDefaultKeyEncryptedAmazonOwned'  -timeout 180m
=== RUN   TestAccDynamoDBTable_Replica_singleDefaultKeyEncryptedAmazonOwned
=== PAUSE TestAccDynamoDBTable_Replica_singleDefaultKeyEncryptedAmazonOwned
=== CONT  TestAccDynamoDBTable_Replica_singleDefaultKeyEncryptedAmazonOwned
table_test.go:1771: Step 2/2 error: Error running apply: exit status 1
Error: updating DynamoDB Table …
```
=> DDB update replica Amazon Owned SSE

website/docs/r/lb_listener.html.markdown
The mapping of protocols to listeners (HTTP/HTTPS -> ALB, TCP/UDP -> NLB) is already explained as part of the description for argument `protocol`.
In addition, the details in the note are incomplete as it only mentions TCP and leaves out UDP. This causes additinal confusion.
Closes #39316 
- [Description of AWS LB listener `protocol` argument](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lb_listener#protocol)
=> docs: remove unneeded note for load balancer listener

.changelog/39328.txt, internal/provider/provider.go, internal/provider/provider_config_test.go
For backwards compatibility, defining an `assume_role` block with a `null` or empty `role_arn` is supported, and does not attempt to assume a role. The PR #39255 did not check the empty string case.
Closes #39296.
Closes #39306.
Closes https://github.com/hashicorp/terraform-provider-aws/issues/39331.
=> provider: Allow empty string in `assume_role.role_arn`

internal/service/opensearchserverless/sweep.go
opensearchserverless APIs return HTTP 500s in `us-gov-east-1`.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/33592.
=> opensearchserveless: Skip sweepers in `us-gov-east-1`

.changelog/39353.txt, internal/service/lexv2models/slot_type.go, internal/service/lexv2models/slot_type_test.go
Add tests for `composite_slot_type_setting` as well as various fixes for naming errors and mix match.
Previously the nested argument `sub_slots` was misnamed. There was a discrepancy between between the struct and schema - when the current name in the schema is used this error would occur: 
```
Error: Unable to Convert Configuration
with aws_lexv2models_slot_type.test,
on terraform_plugin_test.tf line 62, in resource "aws_lexv2models_slot_type" "test":
62: resource "aws_lexv2models_slot_type" "test" {
An unexpected error was encountered when converting the configuration from
the protocol type. This is always an issue in terraform-plugin-framework used
to implement the provider and should be reported to the provider developers.
Please report this to the provider developer:
Unable to …
```
=> td/Add tests to slot_type and fixes

.changelog/39203.txt, internal/service/iam/exports_test.go, internal/service/iam/role.go, internal/service/iam/role_policies_exclusive.go, internal/service/iam/role_policies_exclusive_test.go, internal/service/iam/service_package_gen.go, website/docs/r/iam_role_policies_exclusive.html.markdown
This resource will enable exclusive management of inline policy assignments to an IAM role. This functions similar to the `inline_policy` blocks when defined on the `aws_iam_role` resource, but as a standalone resource.
Relates #22336
Relates #39204 
```console
% make testacc PKG=iam TESTS=TestAccIAMRolePoliciesExclusive_
TF_ACC=1 go1.23.0 test ./internal/service/iam/... -v -count 1 -parallel 20 -run='TestAccIAMRolePoliciesExclusive_'  -timeout 360m
--- PASS: TestAccIAMRolePoliciesExclusive_empty (13.72s)
--- PASS: TestAccIAMRolePoliciesExclusive_disappears_Role (13.72s)
--- PASS: TestAccIAMRolePoliciesExclusive_basic (15.84s)
--- PASS: TestAccIAMRolePoliciesExclusive_multiple (24.25s) …
```
=> r/aws_iam_role_policies_exclusive: new resource

.changelog/29832.txt, docs/acc-test-environment-variables.md, docs/data-handling-and-conversion.md, internal/framework/flex/autoflex.go, internal/framework/flex/tags.go, internal/framework/types/rfc3339_duration.go, internal/framework/types/rfc3339_duration_test.go, internal/service/elasticache/consts.go, internal/service/elasticache/exports_test.go, internal/service/elasticache/reserved_cache_node.go, internal/service/elasticache/reserved_cache_node_offering_data_source.go, internal/service/elasticache/reserved_cache_node_offering_data_source_test.go, internal/service/elasticache/reserved_cache_node_test.go, internal/service/elasticache/service_package_gen.go, internal/types/duration/duration.go, internal/types/duration/duration_test.go, tools/tfsdk2fw/datasource.gtpl, tools/tfsdk2fw/go.mod, tools/tfsdk2fw/go.sum, website/docs/d/elasticache_reserved_cache_node_offering.html.markdown, website/docs/r/elasticache_cluster.html.markdown, website/docs/r/elasticache_replication_group.html.markdown, website/docs/r/elasticache_reserved_cache_node.html.markdown
Added support for purchasing ElastiCache reserved Cache Nodes via Terraform. 
Closes #28060
- [aws . elasticache . describe-reserved-cache-nodes-offerings](https://docs.aws.amazon.com/cli/latest/reference/elasticache/describe-reserved-cache-nodes-offerings.html) 
- [aws . elasticache . purchase-reserved-cache-nodes-offering](https://docs.aws.amazon.com/cli/latest/reference/elasticache/purchase-reserved-cache-nodes-offering.html)
- [Go API Reference](https://docs.aws.amazon.com/sdk-for-go/api/service/elasticache/)
⚠️ Since reservations can't be deleted without getting help from AWS Support, Unfortunately I am not able to run this test. Unless you don't have the budget allocated for this kind of stuff, we probably should just rely on the community to test —  similar to …
=> Added Support for ElastiCache Reserved Cache Nodes

.changelog/39397.txt, internal/service/amplify/app.go
Previously existing `environment_variables` were removed by sending a map with an empty key/value pair. The `UpdateApp` API appears to have added restrictions around keys with empty values, so this approach began to fail the corresponding acceptance test. After reporting the issue to the AWS Go SDK V2, the new method for removing environment variables is to pass a key containing a single space character and an empty string value.
Closes #39327
Relates https://github.com/aws/aws-sdk-go-v2/issues/2788
- https://docs.aws.amazon.com/amplify/latest/APIReference/API_UpdateApp.html#amplify-UpdateApp-request-environmentVariables
```console
% make testacc PKG=amplify TESTS=TestAccAmplify_serial/App/EnvironmentVariables …
```
=> r/aws_amplify_app: fix removal of `environment_variables`

website/docs/r/backup_region_settings.html.markdown
Include newly-supported services in documentation for AWS resource backup_region_settings.
https://docs.aws.amazon.com/aws-backup/latest/devguide/backup-feature-availability.html#features-by-resource
=> Include all services in backup_region_settings documentation

.changelog/39402.txt, internal/service/connect/connect_test.go, internal/service/connect/instance.go, internal/service/connect/instance_data_source.go, internal/service/connect/instance_data_source_test.go, internal/service/connect/instance_test.go, internal/service/connect/service_package_gen.go, website/docs/d/connect_instance.html.markdown, website/docs/r/connect_instance.html.markdown
This adds `tag` support to the already existing `aws_connect_instance ` resource
Closes #38849 
```console
% make testacc TESTS=TestAccConnect_serial PKG=connect
TF_ACC=1 go1.22.7 test ./internal/service/connect/... -v -count 1 -parallel 20 -run='TestAccConnect_serial'  -timeout 360m
=== RUN   TestAccConnect_serial
=== PAUSE TestAccConnect_serial
=== CONT  TestAccConnect_serial
=== RUN   TestAccConnect_serial/Instance
=== RUN   TestAccConnect_serial/Instance/tags
--- PASS: TestAccConnect_serial (131.62s)
--- PASS: TestAccConnect_serial/Instance (131.62s)
--- PASS: TestAccConnect_serial/Instance/tags (131.62s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/connect …
```
=> [enhancement] Add `tags` to`aws_connect_instance ` resource

.github/dependabot.yml
In an attempt to address regular _dependabot_ timeouts (https://github.com/hashicorp/terraform-provider-aws/issues/39287), split the checking of the top-level Go dependencies into 4 using [`allow`](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#allow) and [`ignore`](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#ignore) directives:
* Everything but the AWS SDK for Go v2 service modules
* The AWS SDK for Go v2 service modules, roughly divided into 3 groups based on the first letter of the service name and how many services are in each group
Relates https://github.com/hashicorp/terraform-provider-aws/pull/39409.
=> dependabot: Split top-level Go dependency checks into 4

.github/dependabot.yml
After merging https://github.com/hashicorp/terraform-provider-aws/pull/39422 we get:
> Dependabot encountered the following error when parsing your .github/dependabot.yml:
> Update configs must have a unique combination of 'package-ecosystem', 'directory', and 'target-branch'. Ecosystem 'gomod' has overlapping directories.
This PR reverts the split of AWS SDK for Go v2 dependencies.
=> dependabot: Don't split checking of AWS SDK for Go v2 dependencies

.changelog/39429.txt, internal/service/iam/role.go
This condition is not easily reproducible, but has been the subject of a regression report. This change will retry `ConcurrentModificationException`s during role creation, alongside other retryable conditions resulting from IAM propagation delays.
From the [`CreateRole` API documentation](https://docs.aws.amazon.com/IAM/latest/APIReference/API_CreateRole.html#API_CreateRole_Errors).
> ConcurrentModification
> The request was rejected because multiple requests to change this object were submitted simultaneously. Wait a few minutes and submit your request again.
Closes #39421
```console
% make testacc PKG=iam TESTS=TestAccIAMRole_
TF_ACC=1 go1.22.7 test ./internal/service/iam/... -v -count 1 …
```
=> r/aws_iam_role: retry `ConcurrentModificationException`s

.changelog/39427.txt, internal/service/ec2/vpc_dhcp_options.go
Closes #39343
```console
% make t T=TestAccVPCDHCPOptions_ K=vpc P=14
TF_ACC=1 go1.22.7 test ./internal/service/ec2/... -v -count 1 -parallel 14 -run='TestAccVPCDHCPOptions_'  -timeout 360m
=== RUN   TestAccVPCDHCPOptions_basic
=== PAUSE TestAccVPCDHCPOptions_basic
=== RUN   TestAccVPCDHCPOptions_full
=== PAUSE TestAccVPCDHCPOptions_full
=== RUN   TestAccVPCDHCPOptions_tags
=== PAUSE TestAccVPCDHCPOptions_tags
=== RUN   TestAccVPCDHCPOptions_disappears
=== PAUSE TestAccVPCDHCPOptions_disappears
=== CONT  TestAccVPCDHCPOptions_basic
=== CONT  TestAccVPCDHCPOptions_tags
=== CONT  TestAccVPCDHCPOptions_disappears
=== CONT  TestAccVPCDHCPOptions_full
--- PASS: TestAccVPCDHCPOptions_disappears …
```
=> vpc/dhcp_options: Fix panic

website/docs/d/launch_configuration.html.markdown, website/docs/r/launch_template.html.markdown
This PR is to correctly put the `primary_ipv6` argument description in the `aws_launch_template` resource doc instead of the `aws_launch_configuration` data source doc. The `aws_launch_template` data source doc does not need to be updated because it just has a blanket reference to the resource doc.
Closes #39434
n/a
n/a
=> docs: Move primary_ipv6 arg desc from aws_launch_configuration doc to aws_launch_template doc

website/docs/r/elasticache_serverless_cache.html.markdown
This PR standardizes the descriptions for configuration blocks and argument/attribute links to them, so that it is clearer that they are config blocks.
Closes #39417
n/a
n/a
=> docs: Standardize config block descs and refs for aws_elasticache_serverless_cache

website/docs/r/ecs_capacity_provider.html.markdown
This PR is to add additional information about managed scale-out behavior for the `instance_warmup_period` argument in the `aws_ecs_capacity_provider` resource doc. Instead of adding excessive details to the documentation, I decided to keep the argument description consistent with the AWS API doc and link to additional information in the ECS Developer Guide.
Closes #39420
Referenced [Control the instances Amazon ECS terminates](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/managed-termination-protection.html#managed-scaling-scaleout) for context and [CreateCapacityProvider](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_CreateCapacityProvider.html) for specs.
n/a
=> docs: Added behavior ref to instance_warmup_period arg desc for aws_ecs_capacity_provider

internal/service/iam/role.go, website/docs/r/iam_role.html.markdown
The updated deprecation message now includes the impacted argument name, providing clarity around what argument should be addressed.
```
│ Warning: Argument is deprecated
│
│   with aws_iam_role.test,
│   on main.tf line 33, in resource "aws_iam_role" "test":
│   33: resource "aws_iam_role" "test" {
│
│ The inline_policy argument is deprecated. Use the aws_iam_role_policy resource instead. If Terraform should exclusively manage all inline policy associations (the current behavior
│ of this argument), use the aws_iam_role_policies_exclusive resource as well.
```
Also updates the registry documentation to include deprecation warnings above the `inline_policy` examples.
Relates #39203
Relates #22336
=> r/aws_iam_role: improve `inline_policy` deprecation message 

.changelog/39448.txt, internal/service/rds/instance.go, internal/service/rds/instance_test.go
```console
% make testacc PKG=rds TESTS="TestAccRDSInstance_ReplicateSourceDB_mssqlDomain"
TF_ACC=1 go1.22.7 test ./internal/service/rds/... -v -count 1 -parallel 20 -run='TestAccRDSInstance_ReplicateSourceDB_mssqlDomain'  -timeout 360m
=== RUN   TestAccRDSInstance_ReplicateSourceDB_mssqlDomain
=== PAUSE TestAccRDSInstance_ReplicateSourceDB_mssqlDomain
=== CONT  TestAccRDSInstance_ReplicateSourceDB_mssqlDomain
--- PASS: TestAccRDSInstance_ReplicateSourceDB_mssqlDomain (5167.75s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/rds	5174.387s
```
=> r/aws_ db_cluster: add read replica to domain on create

.changelog/39457.txt, internal/service/rds/cluster.go, internal/service/rds/cluster_role_association.go, internal/service/rds/errors.go, internal/service/rds/instance_role_association.go, website/docs/r/db_instance_role_association.html.markdown
Role association will intermittently fail to apply if the cluster/instance is not in an available state.
```console
% make testacc TESTARGS="-run=TestAccRDSInstanceRoleAssociation_\|TestAccRDSClusterRoleAssociation_" PKG=rds
TF_ACC=1 go1.22.7 test ./internal/service/rds/... -v -count 1 -parallel 20  -run=TestAccRDSInstanceRoleAssociation_\|TestAccRDSClusterRoleAssociation_ -timeout 360m
--- PASS: TestAccRDSClusterRoleAssociation_Disappears_cluster (176.35s)
--- PASS: TestAccRDSClusterRoleAssociation_disappears (197.03s)
--- PASS: TestAccRDSClusterRoleAssociation_basic (199.32s)
--- PASS: TestAccRDSClusterRoleAssociation_Disappears_role (207.08s)
--- PASS: …
```
=> r/rds_role_association: wait for cluster/instance to be available

.changelog/38993.txt, internal/service/ecs/validate.go
Previous regex was not complete and allowed for apply time failures
Updating the ECS `validateClusterName` which contained and incomplete regex allowing for many cases with plans that wouldn't fail as expected
n/a
n/a
n/a
=> Update ECS cluster name validation

website/docs/r/backup_vault_policy.html.markdown
The current example of an AWS Backup vault policy allows any user to put a new policy (since it uses Principal "*"). Therefore deploying the provided example would allow anyone to replace this policy with one in which they had full control over the backup vault. This would include taking copies of the data in there or deleting snapshots.
AWS "[strongly recommend that you do not use a wildcard (*) in the Principal element of a resource-based policy with an Allow effect](https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements_principal.html#principal-anonymous)". Following this, this PR replaces the Principal with the account id, therefore giving this power only to roles already within this account,  which is much less dangerous.
None …
=> Restrict backup example policy

.goreleaser.yml
Resolves current ci [failure](https://github.com/hashicorp/terraform-provider-aws/actions/runs/11046711477/job/30706399075?pr=39493) here:
```console
/opt/hostedtoolcache/goreleaser-action/2.3.2/x64/goreleaser check
• checking                                 path=.goreleaser.yml
• DEPRECATED: snapshot.name_template should not be used anymore, check https://goreleaser.com/deprecations#snapshotnametemplate for more info
• .goreleaser.yml                                  error=configuration is valid, but uses deprecated properties
⨯ command failed                                   error=1 out of 1 configuration file(s) have issues
Error: The process '/opt/hostedtoolcache/goreleaser-action/2.3.2/x64/goreleaser' failed with exit code 2
``` …
=> [chore] Update .goreleaser.yml to correct use of deprecated snapshot attribute

.changelog/39498.txt, internal/create/errors.go, internal/service/medialive/multiplex.go, internal/service/medialive/multiplex_tags_gen_test.go, internal/service/medialive/testdata/Multiplex/tags/main_gen.tf, internal/service/medialive/testdata/Multiplex/tagsComputed1/main_gen.tf, internal/service/medialive/testdata/Multiplex/tagsComputed2/main_gen.tf, internal/service/medialive/testdata/Multiplex/tags_defaults/main_gen.tf, internal/service/medialive/testdata/Multiplex/tags_ignore/main_gen.tf, internal/service/medialive/testdata/tmpl/multiplex_tags.gtpl
- Fixes an error which was silently swallowed by a diagnostic helper that did not append to the response `Diagnostics` field.
- Fixes generated tagging tests for the `aws_medialive_multiplex` resource.
- Removes unused helpers from the `create` package.
```console
% make testacc PKG=medialive TESTS=TestAccMediaLive_serial/Multiplex/basic
TF_ACC=1 go1.22.7 test ./internal/service/medialive/... -v -count 1 -parallel 20 -run='TestAccMediaLive_serial/Multiplex/basic'  -timeout 360m
--- PASS: TestAccMediaLive_serial (129.39s)
--- PASS: TestAccMediaLive_serial/MultiplexProgram (74.15s)
--- PASS: TestAccMediaLive_serial/MultiplexProgram/basic (74.15s)
--- PASS: TestAccMediaLive_serial/Multiplex …
```
=> r/aws_medialive_multiplex: handle read failure during delete

.github/workflows/provider.yml, .github/workflows/resource-counts.yml
The default ubuntu image no longer includes Terraform by default. We now need to install it at runtime instead.
Closes #39501 
Relates https://github.com/actions/runner-images/issues/10636
=> ci(provider): use `hashicorp/setup-terraform` in tfproviderdocs check

.changelog/39496.txt, internal/service/ec2/exports_test.go, internal/service/ec2/service_package_gen.go, internal/service/ec2/transitgateway_default_route_table_association.go, internal/service/ec2/transitgateway_default_route_table_association_test.go, internal/service/ec2/transitgateway_test.go, internal/service/ec2/wait.go, website/docs/r/ec2_transit_gateway_default_route_table_association.html.markdown
New resource `aws_ec2_transit_gateway_default_route_table_association` that allows you to manage setting the default route table for associations on a transit gateway.
Relates #35085 creates one of the two resources required to fix this.
```console
% make testacc TESTS='TestAccTransitGateway_serial/DefaultRouteTableAssociation_' PKG=ec2
TF_ACC=1 go1.22.7 test ./internal/service/ec2/... -v -count 1 -parallel 20 -run='TestAccTransitGateway_serial/DefaultRouteTableAssociation_'  -timeout 360m
=== RUN   TestAccTransitGateway_serial
=== PAUSE TestAccTransitGateway_serial
=== CONT  TestAccTransitGateway_serial
=== RUN   TestAccTransitGateway_serial/DefaultRouteTableAssociation_disappears
=== …
```
=> New Resource: aws_ec2_transit_gateway_default_route_table_association

website/docs/r/elasticache_reserved_cache_node.html.markdown
Replace 'instance_count' with 'cache_node_count'  to match with the internal implementation.
Closes #39452 
- The `instance_count`  slipped in is as part of the initial [pull request](https://github.com/hashicorp/terraform-provider-aws/pull/29832/files#diff-bc5d1fb3c6f5b1447badc1c7d3afa2f7777af01fc6ab5b084af4b4fe365c6d92) that added support for the resource `aws_elasticache_reserved_cache_node`.
- [Link](https://github.com/hashicorp/terraform-provider-aws/blob/465d0690625e474010378042164d42595e617d1a/internal/service/elasticache/reserved_cache_node.go#L62) to internal schema.
=> docs: replace invalid argument for aws_elasticache_reserved_cache_node

go.mod, go.sum, website/docs/r/ec2_transit_gateway_default_route_table_propagation.html.markdown
Add `aws_ec2_transit_gateway_default_route_table_propagation` for setting the default propagation route table on a transit gateway.
Depends on #39496
Closes #35085
```console
%  make testacc TESTS='TestAccTransitGateway_serial/DefaultRouteTablePropagation_' PKG=ec2
TF_ACC=1 go1.23.1 test ./internal/service/ec2/... -v -count 1 -parallel 20 -run='TestAccTransitGateway_serial/DefaultRouteTablePropagation_'  -timeout 360m
=== RUN   TestAccTransitGateway_serial
=== PAUSE TestAccTransitGateway_serial
=== CONT  TestAccTransitGateway_serial
=== RUN   TestAccTransitGateway_serial/DefaultRouteTablePropagation_basic
=== PAUSE TestAccTransitGateway_serial/DefaultRouteTablePropagation_basic
=== RUN …
```
=> New Resource: aws_ec2_transit_gateway_default_route_table_propagation

.changelog/39453.txt, internal/service/quicksight/schema/template_control.go, internal/service/quicksight/schema/template_parameter.go
The internally used key `cacading_control_configuration` contains a typo, so that the mapping fails.
Closes #39139 
- [Cloudformation User Guide](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-quicksight-template-cascadingcontrolconfiguration.html)
TDB - I would need to check how to provide a test for the fix.
=> fix: fix typo in mapping for cascading_control_configuration

website/docs/r/s3_bucket_object_lock_configuration.html.markdown
Fixes formatting of the `import` section and removes redundant descriptions of import arguments.
=> r/aws_s3_bucket_object_lock_configuration(doc): fix import section formatting

internal/service/appfabric/sweep.go, internal/sweep/awsv2/register.go, internal/sweep/register_gen_test.go
Adds sweepers for `aws_appfabric_app_authorization` and `aws_appfabric_app_bundle`.
Fixes a bug in `awsv2.Register` where `dependencies` weren't being set.
Closes https://github.com/hashicorp/terraform-provider-aws/issues/39542.
```console
% SWEEPERS=aws_appfabric_app_bundle make sweep
go1.23.1 test ./internal/sweep -v -sweep=us-west-2,us-east-1,us-east-2,us-west-1 -sweep-run='aws_appfabric_app_bundle' -timeout 360m
2024/09/30 15:12:55 [DEBUG] Running Sweepers for region (us-west-2):
2024/09/30 15:12:55 [DEBUG] Sweeper (aws_appfabric_app_bundle) has dependency (aws_appfabric_app_authorization), running..
2024/09/30 15:12:55 [DEBUG] Running Sweeper (aws_appfabric_app_authorization) in region (us-west-2)
2024/09/30 …
```
=> appfabric: Add sweepers

.changelog/39565.txt, internal/service/bedrockagent/agent.go, internal/service/bedrockagent/agent_test.go
Fix bug where customer_encryption_key_arn was not passed in on update
Fix bug where prompt configuration is lost if you update a different property.
Closes #39548 
```console
%  make testacc TESTS=TestAccBedrockAgentAgent_ PKG=bedrockagent
TF_ACC=1 go1.23.1 test ./internal/service/bedrockagent/... -v -count 1 -parallel 20 -run='TestAccBedrockAgentAgent_'  -timeout 360m
=== RUN   TestAccBedrockAgentAgent_basic
=== PAUSE TestAccBedrockAgentAgent_basic
=== RUN   TestAccBedrockAgentAgent_full
=== PAUSE TestAccBedrockAgentAgent_full
=== RUN   TestAccBedrockAgentAgent_singlePrompt
=== PAUSE TestAccBedrockAgentAgent_singlePrompt
=== RUN   TestAccBedrockAgentAgent_singlePromptUpdate
=== PAUSE …
```
=> Bug Fix bug where customer_encryption_key_arn was not passed in on update

.changelog/39544.txt, internal/service/iam/exports_test.go, internal/service/iam/service_package_gen.go, internal/service/iam/user_policies_exclusive.go, internal/service/iam/user_policies_exclusive_test.go, website/docs/r/iam_user_policies_exclusive.html.markdown
This resource will enable exclusive management of inline policy assignments to an IAM user via Terraform.
Relates #39376
Closes #39377 
```console
% make testacc PKG=iam TESTS=TestAccIAMUserPoliciesExclusive_
TF_ACC=1 go1.23.1 test ./internal/service/iam/... -v -count 1 -parallel 20 -run='TestAccIAMUserPoliciesExclusive_'  -timeout 360m
--- PASS: TestAccIAMUserPoliciesExclusive_empty (14.20s)
--- PASS: TestAccIAMUserPoliciesExclusive_disappears_User (14.87s)
--- PASS: TestAccIAMUserPoliciesExclusive_basic (16.78s)
--- PASS: TestAccIAMUserPoliciesExclusive_outOfBandRemoval (23.39s)
--- PASS: TestAccIAMUserPoliciesExclusive_outOfBandAddition (23.42s)
--- PASS: …
```
=> r/aws_iam_user_policies_exclusive: new resource

.changelog/39554.txt, internal/service/iam/exports_test.go, internal/service/iam/group_policies_exclusive.go, internal/service/iam/group_policies_exclusive_test.go, internal/service/iam/service_package_gen.go, website/docs/r/iam_group_policies_exclusive.html.markdown
This resource will enable exclusive management of inline policy assignments to an IAM group via Terraform.
Relates #39376
Closes #39378
```console
% make testacc PKG=iam TESTS=TestAccIAMGroupPoliciesExclusive_
TF_ACC=1 go1.23.1 test ./internal/service/iam/... -v -count 1 -parallel 20 -run='TestAccIAMGroupPoliciesExclusive_'  -timeout 360m
--- PASS: TestAccIAMGroupPoliciesExclusive_disappears_Group (15.36s)
--- PASS: TestAccIAMGroupPoliciesExclusive_empty (15.37s)
--- PASS: TestAccIAMGroupPoliciesExclusive_basic (17.31s)
--- PASS: TestAccIAMGroupPoliciesExclusive_outOfBandAddition (23.80s)
--- PASS: TestAccIAMGroupPoliciesExclusive_outOfBandRemoval (23.85s)
--- PASS: …
```
=> r/aws_iam_group_policies_exclusive: new resource

.changelog/39557.txt, internal/service/ec2/ebs_snapshot_data_source.go, internal/service/ec2/ebs_snapshot_data_source_test.go, website/docs/d/ebs_snapshot.html.markdown
Add start time attribute to the data source.
Closes #39497 
- [Snapshot Definition in AWS Go SDK v2](https://github.com/aws/aws-sdk-go-v2/blob/service/ec2/v1.179.2/service/ec2/types/types.go#L15556)
```console
$ make testacc TESTS=TestAccEC2EBSSnapshotDataSource PKG=ec2
TF_ACC=1 go1.23.1 test ./internal/service/ec2/... -v -count 1 -parallel 5 -run='TestAccEC2EBSSnapshotDataSource'  -timeout 360m
=== RUN   TestAccEC2EBSSnapshotDataSource_basic
=== PAUSE TestAccEC2EBSSnapshotDataSource_basic
=== RUN   TestAccEC2EBSSnapshotDataSource_filter
=== PAUSE TestAccEC2EBSSnapshotDataSource_filter
=== RUN   TestAccEC2EBSSnapshotDataSource_mostRecent
=== PAUSE TestAccEC2EBSSnapshotDataSource_mostRecent …
```
=> feat: add start_time attribute to data source aws_ebs_snapshot

.changelog/39567.txt, internal/service/bedrockagent/agent_knowledge_base_association_test.go, internal/service/bedrockagent/data_source_test.go, internal/service/bedrockagent/knowledge_base.go, internal/service/bedrockagent/knowledge_base_test.go
Marks attributes that can't be updated as RequiresReplace.
Closes #38022
```console
%  make testacc TESTS=TestAccBedrockAgent_serial/KnowledgeBase PKG=bedrockagent
TF_ACC=1 go1.23.1 test ./internal/service/bedrockagent/... -v -count 1 -parallel 20 -run='TestAccBedrockAgent_serial/KnowledgeBase'  -timeout 360m
=== RUN   TestAccBedrockAgent_serial
=== PAUSE TestAccBedrockAgent_serial
=== CONT  TestAccBedrockAgent_serial
=== RUN   TestAccBedrockAgent_serial/KnowledgeBase
=== RUN   TestAccBedrockAgent_serial/KnowledgeBase/basicRDS
=== RUN   TestAccBedrockAgent_serial/KnowledgeBase/disappears
=== RUN   TestAccBedrockAgent_serial/KnowledgeBase/tags
=== RUN …
```
=> Add RequiresReplace to attributes that can't be modified by update

internal/provider/factory_test.go, internal/provider/provider_test.go, internal/service/ec2/tags.go, internal/service/wafv2/schemas.go, internal/tags/tags.go
Reduces schema memory usage by approximately 18 MB and eliminates approximately 117,600 allocations
1. Shares Plugin SDK tag schemas across resources and data sources. Saves approximately 1 MB and eliminates approximately 3,100 allocations.
Before: BenchmarkSDKProviderInitialization-10 40 29284118 ns/op 70426029 B/op 448276 allocs/op
After: BenchmarkSDKProviderInitialization-10 40 28709038 ns/op 69434669 B/op 445177 allocs/op
2. Shares repeated WAFv2 schemas. Saves approximately 17 MB and eliminates approximately 114,500 allocations.
Before: BenchmarkSDKProviderInitialization-10 40 28709038 ns/op 69434669 B/op 445177 allocs/op
After: BenchmarkSDKProviderInitialization-10 50 22838247 ns/op 52270798 B/op 330692 allocs/op
Relates #31722
=> provider: Reduce schema memory usage by 18 MB

go.mod, go.sum, internal/service/elasticache/replication_group_test.go
Fix issue causing `aws_elasticache_replication_group` to be recreated after import.
Closes #32835
* [AWS API - DescribeReplicationGroups action](https://docs.aws.amazon.com/AmazonElastiCache/latest/APIReference/API_DescribeReplicationGroups.html)
* [AWS API - DescribeCacheClusters action](https://docs.aws.amazon.com/AmazonElastiCache/latest/APIReference/API_DescribeCacheClusters.html)
* [AWS API - ReplicationGroup object](https://docs.aws.amazon.com/AmazonElastiCache/latest/APIReference/API_ReplicationGroup.html)
* [AWS API - CacheCluster object](https://docs.aws.amazon.com/AmazonElastiCache/latest/APIReference/API_CacheCluster.html)
No new acceptance test was created. I'm not sure how to make one to test the import workflow and assert that the resource is not replaced afterwards.
=> Fix aws_elasticache_replication_group recreation on import

internal/service/ec2/ec2_spot_instance_request.go
The resource `aws_spot_instance_request` modifies the `aws_instance` schema. When shared schema elements are in use, this caused them to be overwritten. 
```console
% make testacc PKG=iam TESTS=TestAccIAMPolicy_tags
--- PASS: TestAccIAMPolicy_tags_ComputedTag_OnCreate (71.93s)
--- PASS: TestAccIAMPolicy_tags_DefaultTags_emptyResourceTag (75.99s)
--- PASS: TestAccIAMPolicy_tags_DefaultTags_nullNonOverlappingResourceTag (76.01s)
--- PASS: TestAccIAMPolicy_tags_DefaultTags_nullOverlappingResourceTag (76.25s)
--- PASS: TestAccIAMPolicy_tags_DefaultTags_emptyProviderOnlyTag (76.37s)
--- PASS: TestAccIAMPolicy_tags_EmptyMap (95.83s)
--- PASS: TestAccIAMPolicy_tags_null (96.91s)
--- PASS: TestAccIAMPolicy_tags_DefaultTags_updateToResourceOnly (110.99s)
--- PASS: TestAccIAMPolicy_tags_AddOnUpdate …
```
=> resource/aws_spot_instance_request : Fix issue with overwriting shared schema elements

go.mod, go.sum, internal/service/securityhub/automation_rule.go
The ``aws_securityhub_automation_rule`` resource has ``criteria``  configuration block. Here, the following stringFilter attributes
- [aws_account_id](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/securityhub_automation_rule#aws_account_id)
- [generator_id](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/securityhub_automation_rule#generator_id)
- [title](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/securityhub_automation_rule#title)
- [resource_id](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/securityhub_automation_rule#resource_id)
are Array Members with a max size of 100 items according to documentation but the code only allows a max of 20 items.
Closes #39161
AWS CLI …
=> Update string filters in the criteria block of ``aws_securityhub_automation_rule`` to allow different Max Item sizes

.changelog/37441.txt, internal/provider/intercept.go, internal/provider/tags_interceptor.go, internal/service/ec2/ebs_volume.go, internal/service/ec2/ec2_instance.go, internal/service/ec2/ec2_instance_test.go, internal/tags/key_value_tags.go, website/docs/r/ebs_volume.html.markdown
`default_tags` support for EC2 root block devices was introduced in hashicorp/terraform-provider-aws#33769, which is great ... except it makes the mix of `default_tags` and `tags` on a `root_block_device` perpetually showing drift even when there is none.
The solution is to not remove the default tags config from the volume tags in ec2_instance.
This diff fixes hashicorp/terraform-provider-aws#36448 for us in our environment (which references hashicorp/terraform-provider-aws#33769 as the change that introduced this bug).
This diff possibly fixes hashicorp/terraform-provider-aws#36706 too, but we weren't hitting this issue.
Relates #33769
Relates #36706
Closes #36448 
```console
% make testacc TESTS=TestAccEC2 PKG=ec2
<in progress>
```
=> Fix for default_tags and tags on EC2 block devices

CHANGELOG.md
Modifies the CHANGELOG to note the retraction of the `v5.71.0` release.
Relates https://github.com/hashicorp/terraform-provider-aws/issues/39681.
Relates https://github.com/hashicorp/terraform-provider-aws/issues/39676.
Relates https://github.com/hashicorp/terraform-provider-aws/issues/39675.
=> CHANGELOG: `v5.71.0` release retracted

.changelog/20386.txt, internal/service/cognitoidp/user_pool.go, internal/service/cognitoidp/user_pool_test.go
Closes #20276
Closes #37687
```
make testacc TESTARGS='-run=TestAccAWSCognitoUserPool_*'               
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSCognitoUserPool_* -timeout 180m
=== RUN   TestAccAWSCognitoUserPoolClient_basic
=== PAUSE …
```
=> r/aws_cognito_user_pool: fix empty string_attribute_constraints on user_pool attribute creates no-op update that results in a failure when applied

website/docs/d/cloudfront_log_delivery_canonical_user_id.html.markdown
- The `owner` is required as part of the `access_control_policy` provided in the example
- The example also requires to modify the ownership controls. The default value `BucketOwnerEnforced` disables ACLs.
Closes #39667 
- [`s3_bucket_acl` Documentation](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket_acl#access_control_policy)
- [Controlling ownership of objects and disabling ACLs for your bucket
](https://docs.aws.amazon.com/AmazonS3/latest/userguide/about-object-ownership.html)  
Explaining that we need to move to either `Bucket owner preferred` or `Object writer`
Not required as only documentation is updated.
=> docs: add missing owner to aws_s3_bucket_acl

.changelog/39697.txt, internal/service/rds/cluster.go, internal/service/rds/cluster_test.go, website/docs/r/rds_cluster.html.markdown
This PR increases max capacity for Aurora Serverless v2 from 128 to 256.
Closes #39672
=> Increase Aurora Serverless V2 Max Capacity to 256

internal/service/athena/data_catalog.go, internal/service/athena/database.go, internal/service/athena/sweep.go, internal/service/athena/workgroup.go
Adds sweepers for `aws_athena_data_catalog` and `aws_athena_workgroup`.
```console
% SWEEPERS=aws_athena_workgroup make sweep
go1.23.2 test ./internal/sweep -v -sweep=us-west-2,us-east-1,us-east-2,us-west-1 -sweep-run='aws_athena_workgroup' -timeout 360m
2024/10/11 11:58:56 [DEBUG] Running Sweepers for region (us-west-2):
2024/10/11 11:58:56 [DEBUG] Sweeper (aws_athena_workgroup) has dependency (aws_athena_data_catalog), running..
2024/10/11 11:58:56 [DEBUG] Sweeper (aws_athena_data_catalog) has dependency (aws_athena_database), running..
2024/10/11 11:58:56 [DEBUG] Running Sweeper (aws_athena_database) in region (us-west-2)
2024/10/11 11:58:56 [DEBUG] sweeper: Configuring Terraform AWS Provider: …
```
=> Additional Athena sweepers

.changelog/39718.txt, internal/service/iam/exports_test.go, internal/service/iam/role.go, internal/service/iam/role_policy_attachments_exclusive.go, internal/service/iam/role_policy_attachments_exclusive_test.go, internal/service/iam/service_package_gen.go, website/docs/r/iam_role.html.markdown, website/docs/r/iam_role_policy_attachments_exclusive.html.markdown
This resource will allow practitioners to retain exclusive ownership of customer managed policy attachments to IAM roles via Terraform.
Relates #39376
Closes #39379
- https://docs.aws.amazon.com/IAM/latest/APIReference/API_AttachRolePolicy.html
- https://docs.aws.amazon.com/IAM/latest/APIReference/API_DetachRolePolicy.html
```console
% make testacc PKG=iam TESTS=TestAccIAMRolePolicyAttachmentsExclusive_
TF_ACC=1 go1.23.2 test ./internal/service/iam/... -v -count 1 -parallel 20 -run='TestAccIAMRolePolicyAttachmentsExclusive_'  -timeout 360m
2024/10/14 15:25:06 Initializing Terraform AWS Provider...
--- PASS: TestAccIAMRolePolicyAttachmentsExclusive_empty (16.00s)
--- PASS: …
```
=> r/aws_iam_role_policy_attachments_exclusive: new resource

internal/service/ecs/task_definition.go, internal/service/ecs/task_definition_test.go
If an `aws_ecs_task_definition` is deleted outside of Terraform, it would cause an error
Closes #29749.
```console
% make testacc PKG=ecs TESTS=TestAccECSTaskDefinition_
--- PASS: TestAccECSTaskDefinition_invalidContainerDefinition (5.57s)
--- PASS: TestAccECSTaskDefinition_containerDefinitionDockerLabels (61.26s)
--- PASS: TestAccECSTaskDefinition_containerDefinitionNullPortMapping (65.35s)
--- PASS: TestAccECSTaskDefinition_unknownContainerDefinitions (65.69s)
--- PASS: TestAccECSTaskDefinition_pidMode (74.77s)
--- PASS: TestAccECSTaskDefinition_inferenceAccelerator (79.75s)
--- PASS: TestAccECSTaskDefinition_arrays (80.21s)
--- PASS: TestAccECSTaskDefinition_constraint (87.62s)
--- PASS: TestAccECSTaskDefinition_Fargate_ephemeralStorage (88.30s)
--- PASS: …
```
=> resource/aws_ecs_task_definition: Prevents failures when target was deleted outside of Terraform

internal/service/iam/role_policy_attachments_exclusive_test.go
During a refactor of the initial implementation, the `Config` field was updated during the first test step but not the second. This introduced a race condition between detachment and deletion of the out of band policy, resulting in intermittent failures deleting the policy. The impacted test now appropriately uses the same configuration throughout all test steps.
Relates #39718
```console
% make testacc PKG=iam TESTS=TestAccIAMRolePolicyAttachmentsExclusive_
TF_ACC=1 go1.23.2 test ./internal/service/iam/... -v -count 1 -parallel 20 -run='TestAccIAMRolePolicyAttachmentsExclusive_'  -timeout 360m
2024/10/15 13:56:16 Initializing Terraform AWS Provider...
--- PASS: …
```
=> r/aws_iam_role_policy_attachments_exclusive(test): fix test configuration

.changelog/39731.txt, internal/service/iam/exports_test.go, internal/service/iam/service_package_gen.go, internal/service/iam/user_policy_attachments_exclusive.go, internal/service/iam/user_policy_attachments_exclusive_test.go, website/docs/r/iam_role_policy_attachments_exclusive.html.markdown, website/docs/r/iam_user_policy_attachments_exclusive.html.markdown
This resource will allow practitioners to retain exclusive ownership of customer managed policy attachments to IAM users via Terraform.
Relates #39376
Closes #39380
```console
% make testacc PKG=iam TESTS=TestAccIAMUserPolicyAttachmentsExclusive_
TF_ACC=1 go1.23.2 test ./internal/service/iam/... -v -count 1 -parallel 20 -run='TestAccIAMUserPolicyAttachmentsExclusive_'  -timeout 360m
2024/10/15 14:35:20 Initializing Terraform AWS Provider...
--- PASS: TestAccIAMUserPolicyAttachmentsExclusive_empty (14.88s)
--- PASS: TestAccIAMUserPolicyAttachmentsExclusive_disappears_Policy (17.33s)
--- PASS: TestAccIAMUserPolicyAttachmentsExclusive_basic (17.45s)
--- PASS: …
```
=> r/aws_iam_user_policy_attachments_exclusive: new resource

.changelog/39732.txt, internal/service/iam/exports_test.go, internal/service/iam/group_policy_attachments_exclusive.go, internal/service/iam/group_policy_attachments_exclusive_test.go, internal/service/iam/service_package_gen.go, website/docs/r/iam_group_policy_attachments_exclusive.html.markdown
This resource will allow practitioners to retain exclusive ownership of customer managed policy attachments to IAM groups via Terraform.
Relates #39376
Closes #39381 
```console
% make testacc PKG=iam TESTS=TestAccIAMGroupPolicyAttachmentsExclusive_
TF_ACC=1 go1.23.2 test ./internal/service/iam/... -v -count 1 -parallel 20 -run='TestAccIAMGroupPolicyAttachmentsExclusive_'  -timeout 360m
2024/10/15 15:41:33 Initializing Terraform AWS Provider...
--- PASS: TestAccIAMGroupPolicyAttachmentsExclusive_empty (14.72s)
--- PASS: TestAccIAMGroupPolicyAttachmentsExclusive_disappears_Policy (15.88s)
--- PASS: TestAccIAMGroupPolicyAttachmentsExclusive_disappears_Group (15.92s)
--- PASS: …
```
=> r/aws_iam_group_policy_attachments_exclusive: new resource

.changelog/39752.txt, internal/service/dynamodb/table.go, internal/service/dynamodb/table_test.go
Relates #37799
Closes #39747
```console
% make testacc TESTARGS='-run=TestAccDynamoDBTable_BillingMode_payPerRequestBasic' PKG=dynamodb
TF_ACC=1 go1.23.2 test ./internal/service/dynamodb/... -v -count 1 -parallel 20  -run=TestAccDynamoDBTable_BillingMode_payPerRequestBasic -timeout 360m
2024/10/16 09:01:53 Initializing Terraform AWS Provider...
[signal SIGSEGV: segmentation violation code=0x2 addr=0x8 pc=0x114f376cc]
```
```console
% make testacc TESTARGS='-run=TestAccDynamoDBTable_' PKG=dynamodb
TF_ACC=1 go1.23.2 test …
```
=> r/dynamodb_table: fix crash when table is updated without GSI updates

.changelog/39728.txt, internal/service/route53/record.go, internal/service/route53/record_test.go
Updated route53/record.go to allow creation of record with ttl = 0.
Closes #36411
https://github.com/hashicorp/terraform-provider-aws/issues/36411
```console
terraform-provider-aws % go test ./internal/service/route53/...
ok      github.com/hashicorp/terraform-provider-aws/internal/service/route53 
```
=> Update record.go allow ttl to be 0

website/docs/r/kinesis_firehose_delivery_stream.html.markdown
Documents two new processor types that are currently available in the AWS provider but not documented
Processor types:
* `Decompression`
* `CloudWatchLogProcessing`
Parameters:
* `CompressionFormat`
* `DataMessageExtraction`
Supporting AWS docs:
* https://docs.aws.amazon.com/firehose/latest/APIReference/API_Processor.html
* https://docs.aws.amazon.com/cli/latest/reference/firehose/update-destination.html
N/A
=> Updated FH docs with Decompression & CloudWatchLogProcessing

website/docs/r/verifiedaccess_group.html.markdown
The example for verified access group set with SSE encryption was mentioned incorrectly.
Referred Doc : https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/verifiedaccess_group
Open Issue: #39769
=> Update Verified Access Group SSE Config Example

internal/sweep/awsv2/skip.go
Fixes
```
2024/10/17 08:02:39 [DEBUG] Running Sweeper (aws_imagebuilder_lifecycle_policy) in region (us-gov-east-1)
2024/10/17 08:02:39 [DEBUG] Completed Sweeper (aws_imagebuilder_lifecycle_policy) in region (us-gov-east-1) in 307.255416ms
2024/10/17 08:02:39 [ERROR] Error running Sweeper (aws_imagebuilder_lifecycle_policy) in region (us-gov-east-1): error listing Image Builder Lifecycle Policies (us-gov-east-1): operation error imagebuilder: ListLifecyclePolicies, https response error StatusCode: 403, RequestID: 4220474b-da8b-44ed-afd4-edd4c36bd0d8, ForbiddenException: HTTP status code 403: Access forbidden. You do not have permission to perform this operation. Check your credentials and try your request again.
FAIL	github.com/hashicorp/terraform-provider-aws/internal/sweep	32.242s
FAIL …
```
=> Fix GovCloud `imagebuilder` sweepers

website/docs/r/securityhub_standards_subscription.html.markdown
The documentation for the resoure `aws_securityhub_standards_subscription` contains a table showing standards and their ARN. This pull requests adds the entry for the CIS 3.0.0 benchmark.
In general the ARN can be found by executing `aws securityhub describe-standards`. Below is the relevant entry for the mentioned benchmark
```shell
STANDARDS       The Center for Internet Security (CIS) AWS Foundations Benchmark v3.0.0 is a set of security configuration best practices for AWS. This Security Hub standard automatically checks for your compliance readiness against a subset of CIS requirements.  False   CIS AWS Foundations Benchmark v3.0.0    arn:aws:securityhub:eu-central-1::standards/cis-aws-foundations-benchmark/v/3.0.0
```
Closes #39740 
=> docs: add ARN for new CIS benchmark to resource description

website/docs/d/subnet.html.markdown
The resource name `subnet` is misleading in this example, because it's returning a security group, not the subnet. It makes more sense to call this `subnet_security_group` to indicate that this is the security group attached to the subnet.
=> Update the name of the resource to be more accurate.

.changelog/39778.txt, internal/service/quicksight/schema/data_set.go
Currently trying to apply any Quicksight data set with a `row_level_permission_data_set` block with `format_version = VERSION_2` will fail with:
> Error: updating QuickSight Data Set (...): operation error QuickSight: UpdateDataSet, https response error StatusCode: 400, InvalidParameterValueException: Invalid RowLevelPermissionDataSet. Namespace parameter should not be specified for Version 2
The AWS [documentation](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/Package/-aws-sdk-client-quicksight/Interface/RowLevelPermissionDataSet/) states that the `Namespace` parameter must not exist if format VERSION_2 is passed.
The fix is fairly trivial; i.e. it prevents setting the `Namespace` parameter in the request body if the format version is not 1.
Fixes #33114
The existing code has no …
=> Fix #33114

.changelog/39784.txt, internal/service/dynamodb/table.go
During expansion the Go `int` default value `0` is being included in the request. This happens when either optional attribute `max_read_request_units` or `max_write_request_units` is omitted.
Closes #39760
```console
% make testacc TESTARGS='-run=TestAccDynamoDBTable_gsi\|TestAccDynamoDBTable_onDemandThroughput\|TestAccDynamoDBTable_basic\|TestAccDynamoDBTable_disappears' PKG=dynamodb
TF_ACC=1 go1.23.2 test ./internal/service/dynamodb/... -v -count 1 -parallel 20  -run=TestAccDynamoDBTable_gsi\|TestAccDynamoDBTable_onDemandThroughput\|TestAccDynamoDBTable_basic\|TestAccDynamoDBTable_disappears -timeout 360m
2024/10/17 15:42:16 Initializing Terraform AWS Provider...
--- PASS: …
```
=> r/aws_dynamodb_table: ignore go default value when expanding `on_demand_throughput`

.changelog/39779.txt, internal/service/ssm/patch_baselines_data_source.go, internal/service/ssm/patch_baselines_data_source_test.go, internal/service/ssm/service_package_gen.go, website/docs/d/ssm_patch_baselines.html.markdown
This data source will allow practitioners to list all AWS SSM patch baselines, with optional filters.
The forthcoming `aws_ssmquicksetup_configuration_manager` resource accepts a JSON string of selected patch baselines as part of the configuration for a patch policy, for which the output of this data source can be used. For example,
```terraform
locals {
selected_patch_baselines = jsonencode({
for baseline in data.aws_ssm_patch_baselines.test.baseline_identities : baseline.operating_system => {
"value" : baseline.baseline_id
"label" : baseline.baseline_name
"description" : baseline.baseline_description
"disabled" : !baseline.default_baseline
}
})
}
```
Relates #29549
- https://docs.aws.amazon.com/systems-manager/latest/APIReference/API_DescribePatchBaselines.html
```console
% make testacc …
```
=> d/aws_ssm_patch_baselines: new data source

.changelog/39800.txt, internal/service/sagemaker/sagemaker_test.go, internal/service/sagemaker/space.go, internal/service/sagemaker/space_test.go, website/docs/r/sagemaker_space.html.markdown
Closes #0000
```console
% make testacc TESTS=TestAccSageMaker_serial/Space/jupyterLabAppSettingsLifecycle  PKG=sagemaker
--- PASS: TestAccSageMaker_serial/Space/basic (248.37s)
--- PASS: TestAccSageMaker_serial/Space/jupyterLabAppSettingsLifecycle (278.43s)
--- PASS: TestAccSageMaker_serial/Space/jupyterLabAppSettings (280.42s)
```
=> r/sagemaker_space - support app lifecycle management

internal/service/sagemaker/image.go, internal/service/sagemaker/wait.go
Closes #0000
```console
% make testacc TESTS=TestAccSageMakerImage_basic  PKG=sagemaker
--- PASS: TestAccSageMakerImage_basic (77.43s)
```
=> r/sagemaker_app_image and image_version - log errors better

.changelog/39842.txt, internal/service/iam/policy_test.go, internal/verify/json.go, internal/verify/json_test.go
Plugin SDK V2 based resources can set malformed policy content in state despite a failed update. In these cases, parsing the old content will fail (it is still malformed). Surfacing parsing errors during read operations causes a persistent plan-time validation error, so this changes the behavior to return the "new" content read directly from the remote resource instead.
This fix is applied as far down in the provider codebase as possible, directly after calling the `PoliciesAreEquivalent` function from `github.com/hashicorp/awspolicyequivalence`. The `SecondJSONUnlessEquivalent` function is called across a variety of services which have arguments that expect IAM policy JSON, as well by other upstream functions within `internal/verify` which apply additional normalization on top of the …
=> internal/verify: handle policy parsing errors of state content 

.changelog/39843.txt, internal/service/apprunner/auto_scaling_configuration_version.go
As per #39830, while there is a default maximum autoscaling limit of 25 for AppRunner, it has been possible for some time now to raise the limit with a support request. Indeed, once this limit is raised, you can create an autoscaling config via the API with that arbitrary higher limit. Enforcing a limit in Terraform means we cannot create/update or maintain our actual working autoscaling config that has a higher limit (100 in our case).
There's no advertised _actual_ limit that is possible, so it seems the most practical thing is just to validate the lower limit. At worst, an API error will be returned rather than an error at validation time.
Closes #39830
No tests affect this change.
=> Remove unnecessary upper limit on AppRunner Autoscaling Config max size.

website/docs/d/networkmanager_core_network_policy_document.html.markdown
Updating the documentation for `data.aws_networkmanager_core_network_policy_document` to remove `add_to_network_function_group` from the `attachment_policies` block. 
Based on [AWS docs](https://docs.aws.amazon.com/network-manager/latest/cloudwan/cloudwan-policies-json.html#cloudwan-attach-policies-json) and [the code](https://github.com/hashicorp/terraform-provider-aws/blob/aa3208fef4f4b80e37333362f60118ee29cd44aa/internal/service/networkmanager/core_network_policy_document_data_source.go#L376) for this data resource, `add_to_network_function_group` should only be available under the `action` block. 
n/a
[Code](https://github.com/hashicorp/terraform-provider-aws/blob/aa3208fef4f4b80e37333362f60118ee29cd44aa/internal/service/networkmanager/core_network_policy_document_data_source.go#L376) …
=> docs: update `aws_networkmanager_core_network_policy_document`

.changelog/39882.txt, internal/service/ec2/ec2_launch_template.go
- Add support for `efa-only` interface types
- Ref https://aws.amazon.com/about-aws/whats-new/2024/10/aws-efa-updates-scalability-ai-ml-applications/
From [here](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/efa.html):
Closes https://github.com/hashicorp/terraform-provider-aws/issues/39891.
```console
...
```
=> feat: Add support for `efa-only` interface types

website/docs/r/imagebuilder_workflow.html.markdown
The documentation of the resource [`ami_imagebuilder_workflow`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/imagebuilder_workflow)  mentions for the argument `type`
>  Valid values: BUILD, TEST, DISTRIBUTION.
Image Builder handles the  workflow type DISTRIBUTION, it cannot be configured by users. When trying to do so, for example using the code snippet provided as part of #39785 
```hcl
resource aws_imagebuilder_workflow codebuild-projects {
name = "CodeBuildProjectsDistributionWorkflow"
version = "1.0.0"
type = "DISTRIBUTION"
data = file("${path.module}/codebuild-projects-distribution.workflow.yaml")
}
```
the API returns the error ` The value supplied for parameter 'type' is not valid. Custom distribution workflows are not supported.`
This pull request is …
=> docs: remove non-usable workflow type in ami_imagebuilder_workflow resource

website/docs/r/ami_copy.html.markdown
The example in resource `aws_ami_copy` contains a `description` field that is not documented in the _Arguments_ section.
```hcl
resource "aws_ami_copy" "example" {
name              = "terraform-example"
description       = "A copy of ami-xxxxxxxx"
source_ami_id     = "ami-xxxxxxxx"
source_ami_region = "us-west-1"
tags = {
Name = "HelloWorld"
}
}
```
This PR added the missing field.
Please note: The resource documentation contains the statement below
> This resource also exposes the full set of arguments from the [aws_ami](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ami) resource.
So, it may be the case that adding the  `description` field is not required, but it helps readers as they to not need to open another documentation page for getting details on …
=> docs: add argument description to resource aws_ami_copy

internal/service/chatbot/slack_channel_configuration_test.go, internal/service/ec2/vpc_default_route_table_test.go, internal/service/ec2/vpc_dhcp_options_association_test.go, internal/service/ec2/vpc_endpoint_private_dns_test.go, internal/service/ecs/task_definition_test.go, internal/service/events/rule_test.go, internal/service/iam/group_policies_exclusive_test.go, internal/service/iam/group_policy_attachments_exclusive_test.go, internal/service/iam/role_policies_exclusive_test.go, internal/service/iam/role_policy_attachments_exclusive_test.go, internal/service/iam/user_policies_exclusive_test.go, internal/service/iam/user_policy_attachments_exclusive_test.go, internal/service/lambda/function_recursion_config_test.go, internal/service/networkmanager/connection_test.go, internal/service/networkmanager/device_test.go, internal/service/networkmanager/link_test.go, internal/service/networkmanager/site_test.go, internal/service/pinpoint/email_template_test.go, internal/service/rekognition/stream_processor_test.go, internal/service/s3control/access_point_policy_test.go, internal/service/serverlessrepo/cloudformation_stack_test.go, internal/service/ssm/default_patch_baseline_test.go
Replaces custom single-attribute `ImportStateIdFunc`s with `acctest.AttrImportStateIdFunc`
=> Replace custom single-attribute `ImportStateIdFunc`s with `acctest.AttrImportStateIdFunc`

.changelog/39949.txt, internal/service/ssm/patch_baseline.go, internal/service/ssm/patch_baseline_test.go, website/docs/r/ssm_patch_baseline.html.markdown
As described in #39917 the validation range for the `approve_after_days`  setting is not matching the range described in the official docs (see `References` section).
The PR updates the range from 0-100 to 0-360. In addition, the documentation for the resource is updated.
Closes #39917 
- [API Reference](https://docs.aws.amazon.com/systems-manager/latest/APIReference/API_PatchRule.html)
```console
❯ make testacc TESTS=TestAccSSMPatchBaseline PKG=ssm
TF_ACC=1 go1.23.2 test ./internal/service/ssm/... -v -count 1 -parallel 5 -run='TestAccSSMPatchBaseline'  -timeout 360m
2024/10/30 19:58:29 Initializing Terraform AWS Provider...
=== RUN   TestAccSSMPatchBaselineDataSource_existingBaseline
=== …
```
=> fix: update approve_after_days validation in ssm patch baseline resource

internal/service/iam/role.go, website/docs/r/iam_role.html.markdown
The message has been updated to reflect that attachments migrated from this argument should be moved to the `aws_iam_role_policy_attachment` resource, with the optional adoption of `aws_iam_role_policy_attachments_exclusive` for use cases which prefer Terraform to retain exclusive management of all managed policies attached to the role.
Relates https://github.com/hashicorp/terraform-provider-aws/issues/39818#issuecomment-2452349035
Relates #39718
=> r/aws_iam_role: refine `managed_policy_arns` deprecation message

.changelog/40008.txt, internal/framework/types/arn.go, internal/framework/types/arn_test.go
Previously the `ARNType`s `ValueFromString` method parsed the string value and set the value to Unknown in cases where validation failed. This caused a plan time failure indicating a difference between the planned value (unknown) and config value (known string). This obfuscated the underlying error which is actually an invalid ARN value.
Invalid ARNs provided in a configuration will now produce errors similar to the following:
```
│ Error: Invalid ARN Value
│
│   with aws_bedrockagent_agent.test,
│   on main.tf line 16, in resource "aws_bedrockagent_agent" "test":
│   16:   agent_resource_role_arn = "INVALID-ARN"
│
│ The provided value cannot be parsed as an ARN.
│
│ Path: agent_resource_role_arn
│ Value: INVALID-ARN
```
```console
% go test ./internal/framework/types/...
ok …
```
=> internal/framework/types: surface ARN validation errors

.changelog/40019.txt, internal/service/batch/job_definition.go, internal/service/batch/job_definition_data_source.go, internal/service/batch/job_definition_data_source_test.go, internal/service/batch/job_definition_test.go, website/docs/d/batch_job_definition.html.markdown, website/docs/r/batch_job_definition.html.markdown
- ✨ Adds support for `initContainers` `shareProcessNamespace` on resource/data source
- ✨ Adds support for `imagePullSecrets` on data source. 
- 🔧 Increases max containers/init Containers to 10, as defined in [docs](https://docs.aws.amazon.com/batch/latest/APIReference/API_EksPodProperties.html). 
- 📝 Adds doc support for metadata (pre-existing attribute)
Closes #38606 
```console
% TF_ACC=1 make testacc TESTS=TestAccBatchJobDefinitionDataSource_ PKG=batch                                                                                                              <aws:provider> <region:us-east-2>
TF_ACC=1 go1.23.2 test ./internal/service/batch/... -v -count 1 -parallel 20 …
```
=> :sparkles: add additional properties on eks job definition

website/docs/r/db_snapshot_copy.html.markdown
The option to share a snapshot when copying it with the resource  `db_snapshot_copy` is implemented (https://github.com/hashicorp/terraform-provider-aws/blob/835fdcd788b737b95c394daed625a62b73506bb2/internal/service/rds/snapshot_copy.go#L109), but it isn't documented. This PR will fix that.
```console
...
```
=> Add missing `shared_accounts` parameter to `db_snapshot_copy` documentation

website/docs/functions/arn_build.html.markdown, website/docs/functions/arn_parse.html.markdown, website/docs/functions/trim_iam_role_path.html.markdown
The registry now includes a banner above all functions pages indicating that provider defined functions are only supported in Terraform 1.8 and later. This now makes the notes embedded in the pages themselves redundant.
=> website/docs/functions: remove required version note

internal/framework/flex/auto_expand.go, internal/framework/flex/auto_expand_test.go, internal/framework/flex/auto_flatten.go, internal/framework/flex/auto_flatten_test.go, internal/framework/flex/autoflex_test.go
Relates #39988 
```console
% cd internal/framework/flex
% go test ./...
ok  	github.com/hashicorp/terraform-provider-aws/internal/framework/flex	0.272s
```
=> autoflex: Allow []byte-string conversion

skaff/datasource/datasourcefw.gtpl
The Terraform Plugin Framework template incorrectly sets the `@SDKDataSource` annotation.
=> skaff: fix framework data source annotation

.changelog/40039.txt, internal/service/elbv2/listener.go, internal/service/elbv2/listener_test.go
This change fixes two issues related to the newly added `tcp_idle_timeout_seconds` argument.
Reported in #40000 
The `tcp_idle_timeout_seconds` default value of `350` has been removed in favor or marking this argument optional and computed. In practice, this means the default value of `350` is still read and stored in state for protocols which support this feature, but unless explicitly configured by the user, the `ModifyListenerAttributes` API will not be called during create or update operations.
This change fixes a regression introduced by the addition of the `tcp_idle_timeout_seconds` argument with a default value, which caused any existing configuration using the `aws_lb_listener` resource to now require the calling principal to include the …
=> r/aws_lb_listener: remove `tcp_idle_timeout_seconds` default value

.changelog/40004.txt, internal/framework/flex/auto_flatten.go, internal/service/apigateway/account.go, internal/service/apigateway/account_test.go, internal/service/apigateway/apigateway_test.go, internal/service/apigateway/exports_test.go, internal/service/apigateway/method_settings_test.go, internal/service/apigateway/service_package_gen.go, internal/service/apigateway/stage_test.go, internal/service/apigateway/sweep.go, tools/tfsdk2fw/main.go, website/docs/r/api_gateway_account.html.markdown
An `aws_api_gateway_account` can be unregistered by clearing the `cloudwatch_role_arn`. Do that and add sweeper.
```console
% make testacc PKG=apigateway TESTS='TestAccAPIGateway_serial/Account'
--- PASS: TestAccAPIGateway_serial (178.47s)
--- PASS: TestAccAPIGateway_serial/Account (178.47s)
--- PASS: TestAccAPIGateway_serial/Account/basic (178.47s)
```
=> resource/aws_api_gateway_account: Properly support unregistration

website/docs/r/backup_restore_testing_selection.html.markdown
The resoure `aws_backup_restore_testing_selection` is missing documentation for the argument `validation_window_hours`.
This PR adds a brief description (compared to SDK/ CLI) and details on the value range.
Closes #40011 
- [AWS CLI Docs](https://docs.aws.amazon.com/cli/latest/reference/backup/create-restore-testing-selection.html)
- [AWS SDK Go v2 -RestoreTestingSelectionForGet ](https://github.com/aws/aws-sdk-go-v2/blob/70eb57ac775f782db6856c73f1ca22eae8e48ac2/service/backup/types/types.go#L2204) 
- [Validation in TF resource](https://github.com/hashicorp/terraform-provider-aws/blob/c220a4002aa159f68a3e6e1428368918e7c7d154/internal/service/backup/restore_testing_selection.go#L115)
Not applicable. Only resource documentation changed.
=> docs: add argument `validation_window_hours`

.changelog/39980.txt, internal/service/events/bus.go, internal/service/events/bus_data_source.go, internal/service/events/bus_data_source_test.go, internal/service/events/bus_test.go, website/docs/d/cloudwatch_event_bus.html.markdown, website/docs/r/cloudwatch_event_bus.html.markdown
This PR is to add the `description` argument/attribute to the `aws_cloudwatch_event_bus` resource and data source.
Note that there is a quirk with the AWS API where you cannot unset the description on update when it is previously set. The only way is to set the description to am empty string, which is coincidentally mapped to the zero string value. So in the state, the value is never null, only empty string for now.
Closes #39900
Referred to [CreateTask](https://docs.aws.amazon.com/datasync/latest/userguide/API_CreateTask.html) for specs and wordings.
For the `aws_cloudwatch_event_bus` resource:
```console
$ make testacc TESTS=TestAccEventsBus_basic PKG=events
TF_ACC=1 go1.23.2 test …
```
=> feat: Add description arg/attr for aws_cloudwatch_event_bus resource and data source

.changelog/40049.txt, internal/service/sagemaker/domain.go, internal/service/sagemaker/domain_test.go, internal/service/sagemaker/sagemaker_test.go
It seems like AWS may return something in `app_security_group_management` and then on an update it tries to pass that to AWS when it's not allowed. Note that this is an AWS ValidationException.
Closes #39923
```console
% make t T='TestAccSageMaker_serial/Domain/rStudioDomainDisabledNetworkUpdate' K=sagemaker
TF_ACC=1 go1.23.2 test ./internal/service/sagemaker/... -v -count 1 -parallel 20 -run='TestAccSageMaker_serial/Domain/rStudioDomainDisabledNetworkUpdate'  -timeout 360m
2024/11/07 15:59:51 Initializing Terraform AWS Provider...
=== RUN   TestAccSageMaker_serial
=== PAUSE TestAccSageMaker_serial
=== CONT  TestAccSageMaker_serial
=== RUN   TestAccSageMaker_serial/Domain
=== RUN …
```
=> sagemaker/domain: Fix ValidationException with AppSecurityGroupMangement

.changelog/40046.txt, internal/service/dynamodb/table.go, internal/service/dynamodb/table_test.go
Brief history:
* #10304 describes a diff bug caused by `ttl.0.attribute_name` going out to AWS but not coming back
* #37991 attempted to fix the diff by applying validation preventing `ttl.0.attribute_name` from being set if `ttl.0.enabled` is `false`. That fixed the diff but caused another problem.
* In order to disable TTL on a table, you *_must_* pass in `ttl.0.attribute_name`, even though AWS will not return it. #37991 made it impossible to disable TTL.
* This PR removes the validation preventing `ttl.0.attribute_name` from being set if `ttl.0.enabled` is `false` and addresses the diff issue with a `DiffSuppressFunc`.
* Unfortunately, testing this fix is complicated because AWS will not allow you to disable TTL in the first hour it's enabled. I've added a test that sleeps an hour so …
=> dynamodb/table: Fix ability to disable dynamodb table ttl

internal/service/dynamodb/table_test.go
#40046 broke a test that this fixes.
Relates #40046
```console
% make t T=TestAccDynamoDBTable_TTL_validate K=dynamodb
TF_ACC=1 go1.23.2 test ./internal/service/dynamodb/... -v -count 1 -parallel 20 -run='TestAccDynamoDBTable_TTL_validate'  -timeout 360m
2024/11/08 15:02:15 Initializing Terraform AWS Provider...
=== RUN   TestAccDynamoDBTable_TTL_validate
=== PAUSE TestAccDynamoDBTable_TTL_validate
=== CONT  TestAccDynamoDBTable_TTL_validate
--- PASS: TestAccDynamoDBTable_TTL_validate (4.11s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/dynamodb	8.111s
% make testacc-short T=TestAccDynamoDBTable K=dynamodb
==> Checking …
```
=> dynamodb/table: TTL validation test no longer valid

.changelog/40067.txt, internal/service/apigateway/deployment.go, website/docs/r/api_gateway_deployment.html.markdown
The PR #39929 added the following validation to `canary_settings` and `stage_description`, since the values are ignored when `stage_name` is not set:
```go
RequiredWith: []string{
"stage_name",
},
```
This caused some users to have errors with their existing configurations.
Remove the validation error and add run-time warnings.
Also deprecates `stage_name`, `stage_description`, and `canary_settings` on the `aws_api_gateway_deployment` resource if favour of an explicit `aws_api_gateway_stage`.
Closes #39957
```console
% make testacc PKG=apigateway TESTS=TestAccAPIGatewayDeployment_
--- PASS: TestAccAPIGatewayDeployment_variables (47.22s)
--- PASS: TestAccAPIGatewayDeployment_deploymentCanarySettings (47.46s)
--- PASS: TestAccAPIGatewayDeployment_Disappears_restAPI (47.70s)
--- PASS: …
```
=> resource/aws_api_gateway_deployment: Reverts validation errors

website/docs/r/sagemaker_space.html.markdown
- The resource `aws_sagemaker_space` does not contain a `code repository` block inside the `code_editor_app_settings` block. The resource documentation available [here](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sagemaker_space#code_editor_app_settings-block) is updated accordingly.
- The documentation for the `code repository` block inside the `jupyter_lab_app_settings` is updated also. It should refer to `JupyterLab` instead of `JupyterServer`.
Closes #40038 
- [AWS Go SDK v2  - SpaceCodeEditorAppSettings](https://github.com/aws/aws-sdk-go-v2/blob/2f70834c690f3fecf04ef006f0ea7022884b367f/service/sagemaker/types/types.go#L16682)
- [AWS GO SDK v2 -SpaceJupyterLabAppSettings](https://github.com/aws/aws-sdk-go-v2/blob/2f70834c690f3fecf04ef006f0ea7022884b367f/ …
=> docs: remove invalid argument from resource documentation

.changelog/40088.txt, internal/service/autoscaling/errors.go, internal/service/autoscaling/group.go, internal/service/autoscaling/group_test.go, internal/service/ec2/ec2_launch_template.go, internal/service/ec2/find.go, internal/service/iam/instance_profile.go
When using an Auto Scaling group (ASG) with a launch template that specifies an IAM instance profile, changes to the instance profile can cause errors in the ASG due to a lack of built-in waiting for resource consistency. Specifically, if the IAM instance profile is updated, the ASG immediately updates with the outdated configuration before the change has propagated fully, leading to failures.
```
Error: updating Auto Scaling Group (xyz): ValidationError: You must use a valid fully-formed launch template. Value
(arn:aws:iam::012345678901:instance-profile/node-xyz) for parameter iamInstanceProfile.arn is invalid. Invalid IAM
Instance Profile ARN
```
This pull request addresses the issue by adding wait mechanisms for eventual consistency on the launch template and instance profile …
=> autoscaling/group: Handle eventual consistency

.github/workflows/stale.yml
I noticed some items with the  `stale` label that had been open for longer than the prescribed 30 additional days. Upon review, the stale workflow [is finishing](https://github.com/hashicorp/terraform-provider-aws/actions/runs/11746909216) with a warning indicating that we should increase [`operations-per-run`](https://github.com/actions/stale?tab=readme-ov-file#operations-per-run).
This PR increases the operations count by 50 to see if that's enough. Will monitor and increase further as needed.
N/a, workflow
=> Increase operation count of stale workflow

internal/service/evidently/sweep.go, internal/sweep/awsv2/skip.go
Evidently sweepers were failing with a panic due to the error
> api error NoLongerSupportedException: AWS Evidently has been discontinued.
=> Fix panic in Evidently sweepers

website/docs/r/elasticache_replication_group.html.markdown
Prior typo was confusing and had no semantic meaning. Updated to be accurate per AWS documentation
https://docs.aws.amazon.com/AmazonElastiCache/latest/dg/Redis-Global-Datastores-Getting-Started.html
The above documentation from AWS states:
"You can set up replication for a primary cluster from one AWS Region to a secondary cluster in up to two other AWS Regions. Note: The exception to this are China (Beijing) Region and China (Ningxia) regions, where replication can only occur between the two regions."
Closes #0000
```console
...
```
=> Correct typo in elasticache_replication_group regarding number of allowed Secondary replica groups

.changelog/40124.txt, internal/service/apigateway/integration.go, internal/service/apigateway/integration_test.go, internal/service/apigateway/method.go
This update introduces a two-stage approach to handle AWS request and cache key parameter updates more reliably due to observed challenges in API Gateway parameter behavior:
- Request parameter updates can alter cache key parameters (see #39801).
- Adding one cache key parameter may unexpectedly remove another (see #29910, #25736).
- Cache key parameters can be updated independently of request parameters.
Keeping Terraform state in sync with what is in place on AWS is problematic due to these unpredictable, from Terraform's perspective, changes. For example, trying to remove or replace a parameter that state says exists but doesn't actually exist, causes _not-found-type_ errors. Another example is simultaneously performing multiple operations that have the net effect of removing a …
=> apigateway/integration: Fix parameters issues

.changelog/39960.txt, CHANGELOG.md, internal/service/rds/global_cluster.go, internal/service/rds/global_cluster_test.go, website/docs/r/rds_global_cluster.html.markdown
AWS Started supporting [global endpoint](https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/aurora-global-database-connecting.html) for global aurora clusters. This PR is to basically add the new endpoint attribute as a new output attribute. 
This basically solves https://github.com/hashicorp/terraform-provider-aws/issues/39862
Closes #39862
```console
...
```
=> aws_rds_global_cluster: Add `endpoint` attribute for DB writer endpoint

internal/service/resourcegroups/sweep.go, internal/service/servicecatalogappregistry/sweep.go, internal/sweep/register_gen_test.go
Adds sweeper for `aws_servicecatalogappregistry_application`.
Also skips `aws_resourcegroups_group` resources with `aws:servicecatalog:applicationId` tag
=> Adds `aws_servicecatalogappregistry_application` sweeper

.changelog/40144.txt, internal/service/ec2/service_package_gen.go, internal/service/ec2/vpc_subnet_data_source.go, internal/service/ec2/vpc_subnet_data_source_tags_gen_test.go
This change modifies the transparent tagging configuration for this data source to use the `Tags` field from the `DescribeSubnets` response, rather than making an additional call to the `DescribeTags` API. As a side effect, this data source will no longer require the calling principal to have the `ec2:DescribeTags` IAM permission, fixing a regression introduced in `v5.73.0`.
---
As additional confirmation that this change no longer results in calls to the `DescribeTags` API I created a simple configuration with the following subnet data source. 
```
data "aws_subnet" "by_id" {
id = aws_subnet.test.id
}
```
After the initial infrastructure is provisioned, this data source is read on every plan operation. By searching the debug logs for a plan operation with `v5.76.0` (latest release) and a …
=> d/aws_subnet: use `Tags` field from `DescribeSubnets` response

internal/service/elbv2/listener_rule_data_source_test.go
This change prevents intermittent panics caused by variable lengths of the random integer appended to the generated resource name. This approach now mirrors how the corresponding resoure acceptance test handles truncating the generated resource name.
Closes #40136 
```console
% make testacc PKG=elbv2 TESTS=TestAccELBV2ListenerRuleDataSource_actionForwardWeightedStickiness
TF_ACC=1 go1.23.2 test ./internal/service/elbv2/... -v -count 1 -parallel 20 -run='TestAccELBV2ListenerRuleDataSource_actionForwardWeightedStickiness'  -timeout 360m
2024/11/15 09:31:54 Initializing Terraform AWS Provider...
--- PASS: TestAccELBV2ListenerRuleDataSource_actionForwardWeightedStickiness (237.37s)
PASS
ok …
```
=> d/aws_elbv2_listener_rule(test): fix flaky test configuration

.ci/.golangci2.yml
@gdavison I believe I have the right syntax for the golangci `linters.errcheck.exclude-functions` configuration.  Change is update the yaml as follows:
```
exclude-functions:
- (*github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.ResourceData).Set
- (*github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.ResourceDiff).SetNewComputed
- (*github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.ResourceDiff).ForceNew
- io:Close
```
N/a
https://github.com/hashicorp/terraform-provider-aws/blob/8d4fd10c76ecc212ac3acc4d6657772c14ff24a4/.ci/.golangci2.yml#L36-L50
(only `errcheck` run)
```console
% golangci-lint -v run -c .ci/.golangci2.yml --enable-only errcheck
INFO golangci-lint has version v1.62.0 built with go1.23.3 from (unknown, modified: ?, mod sum: "") on (unknown) 
INFO …
```
=> Replace golangci `errcheck` `ignore` with `exclude-functions`

website/docs/r/lambda_function.html.markdown
Just docs on the new extended snapstart support: https://aws.amazon.com/about-aws/whats-new/2024/11/aws-lambda-snapstart-python-net-functions/
Closes #40178 
```console
...
```
=> [Docs] Extended snapstart runtime support for lambda_function

website/docs/r/s3_bucket_acl.html.markdown
This PR aims to add more details about valid values to be set for an AWS S3 bucket canned ACL.
Closes #39582
=> chore(aws_s3_bucket_acl): add valid values for canned acl to the documentation.

.changelog/40168.txt, internal/service/eks/addon.go, internal/service/eks/addon_test.go
Previously attempting to update this argument would result in a crash similar to the following:
```
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵
Releasing state lock. This may take a few moments...
Stack trace from the terraform-provider-aws_v5.76.0_x5 plugin:
panic: interface conversion: interface {} is *schema.Set, not []interface {}
goroutine 353 [running]:
github.com/hashicorp/terraform-provider-aws/internal/service/eks.resourceAddonUpdate({0x1196189a8, 0x14001bbedb0}, 0x14006991c00, {0x1192eeb60, 0x140003aaa00})
github.com/hashicorp/terraform-provider-aws/internal/service/eks/addon.go:289 +0xdac
github.com/hashicorp/terraform-provider-aws/internal/provider.New.(*wrappedResou …
```
=> r/aws_eks_addon: fix crash when updating `pod_identity_association`

website/docs/r/eip.html.markdown
https://github.com/hashicorp/terraform-provider-aws/blob/d143dd5eeac666d07ce43bafba3a150c6951c5c7/internal/service/ec2/ec2_eip.go#L90
=> docs: indicate `domain` is optional in `aws_eip` resource

.github/workflows/comments-feed.yml, .github/workflows/label-notifications.yml, .github/workflows/post_publish.yml, .github/workflows/pull_request_feed.yml, .github/workflows/pull_request_review.yml, .github/workflows/release-tag.yml
The `webhook-type` argument is now required. The `webhook` argument is optional and can also be configured by setting the `SLACK_WEBHOOK_URL` environment variable, but I've migrated to the explicit argument to align with the documentation for the release. See the [release notes](https://github.com/slackapi/slack-github-action/releases/tag/v2.0.0) for complete details on the breaking changes.
Relates #40160 
- https://github.com/slackapi/slack-github-action/releases/tag/v2.0.0
=> .github/workflows: address breaking changes to `slack-github-action`

.changelog/40211.txt, internal/service/ec2/ec2_ami_data_source.go, internal/service/ec2/ec2_ami_data_source_test.go, internal/service/ec2/exports_test.go
When `most_recent` is set to `true` and certain filtering criteria are missing, it's possible for this data source to return an image published by a third party. To bring visibility to this possibility in a non-breaking way, the provider will now append a warning diagnostic when an affected combination of arguments is detected.
For practitioners, the resulting diagnostic will look similar to the following:
Closes #40197
```console
% make testacc PKG=ec2 TESTS=TestAccEC2AMIDataSource_
TF_ACC=1 go1.23.2 test ./internal/service/ec2/... -v -count 1 -parallel 20 -run='TestAccEC2AMIDataSource_'  -timeout 360m
--- PASS: TestAccEC2AMIDataSource_linuxInstance (11.17s)
--- PASS: …
```
=> d/aws_ami: warn when most_recent is true and filters are missing

website/docs/r/bedrockagent_data_source.html.markdown
As mentioned in #39773 the documentation for the resource[ `aws_bedrockagent_data_source`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/bedrockagent_data_source) is missing the block `transformation` inside of the `custom_transformation_configuration` block. 
Actually, the block `transformation_function` (that exists inside of `transformation`) is mentioned instead.
Closes #39773 
- [AWS CloudFormation Docs - CustomTransformationConfiguration](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-bedrock-datasource-customtransformationconfiguration.html)  
shows nesting of elements in CloudFormation: `CustomTransformationConfiguration` -> `Transformations` -> `TransformationFunction`
- [Terraform AWS Provider - Terraform code in …
=> docs: add missing transformation block

.github/workflows/post_publish.yml
A missed quote caused the script to fail during the `v5.77.0` release.
```
/home/runner/work/_temp/b9a14e53-10ad-497f-a91b-d57575e541f4.sh: line 12: unexpected EOF while looking for matching `"'
Error: Process completed with exit code 2.
```
Ref: https://github.com/hashicorp/terraform-provider-aws/actions/runs/11959899920/job/33342735174
Relates #39964
=> .github/workflows: fix formatting in `post_publish` shell script

.github/dependabot.yml
Removes `/tools/awssdkpatch` from the `.ci/tools/go.mod` `dependabot` group.
Errors were being [reported](https://github.com/hashicorp/terraform-provider-aws/actions/runs/11973703877/job/33383175737):
```
updater | 2024/11/22 13:40:44 ERROR <job_921179691> Error during file fetching; aborting: No files found in /tools/awssdkpatch
```
Relates https://github.com/hashicorp/terraform-provider-aws/pull/39926.
=> dependabot: Remove `/tools/awssdkpatch`

.changelog/40172.txt, internal/service/batch/eks_properties.go, internal/service/batch/eks_properties_test.go, internal/service/batch/exports_test.go, internal/service/batch/job_definition.go, internal/service/batch/job_definition_test.go, internal/service/batch/node_properties.go, internal/service/batch/node_properties_test.go
When specifying EKS or ECS Properties within node range properties, a nil pointer crash occurred.
Closes #38605
```console
% make testacc TESTS=TestAccBatchJobDefinition_NodeProperties PKG=batch
TF_ACC=1 go1.23.2 test ./internal/service/batch/... -v -count 1 -parallel 20 -run='TestAccBatchJobDefinition_NodeProperties'  -timeout 360m
2024/11/18 13:33:38 Initializing Terraform AWS Provider...
=== RUN   TestAccBatchJobDefinition_NodeProperties_basic
=== PAUSE TestAccBatchJobDefinition_NodeProperties_basic
=== RUN   TestAccBatchJobDefinition_NodeProperties_advanced
=== PAUSE TestAccBatchJobDefinition_NodeProperties_advanced
=== RUN   TestAccBatchJobDefinition_NodeProperties_withEKS
=== PAUSE …
```
=>  r/batch_job_definition :bug: fix crash when EKS and ECS Properties defined on node_properties

.changelog/40268.txt, internal/service/s3/bucket_lifecycle_configuration_test.go, website/docs/r/s3_bucket_lifecycle_configuration.html.markdown
Removes a note from the `aws_s3_bucket_lifecycle_configuration` documentation indicating directory buckets are not supported and adjusts the expected result from an acceptance test applying a lifecycle configuration to an S3 directory bucket.
Closes #40261
- https://aws.amazon.com/about-aws/whats-new/2024/11/amazon-s3-express-one-zone-s3-lifecycle-expirations/
```console
% make testacc PKG=s3 TESTS=TestAccS3BucketLifecycleConfiguration_directoryBucket
TF_ACC=1 go1.23.2 test ./internal/service/s3/... -v -count 1 -parallel 20 -run='TestAccS3BucketLifecycleConfiguration_directoryBucket'  -timeout 360m
2024/11/13 10:55:38 Initializing Terraform AWS Provider...
--- PASS: …
```
=> r/aws_s3_bucket_lifecycle_configuration: S3 directory buckets are now supported

CHANGELOG.md
Documents support for AWS Lambda Node.js 22 and Python 3.13 runtimes in the relevant CHANGELOG sections.
Relates https://github.com/hashicorp/terraform-provider-aws/issues/40137.
* [Python 3.13 announcement](https://aws.amazon.com/about-aws/whats-new/2024/11/aws-lambda-support-python-313/)
* [Node.js 22 announcement](https://aws.amazon.com/about-aws/whats-new/2024/11/aws-lambda-support-nodejs-22/)
=> Document support for AWS Lambda Node.js 22 and Python 3.13 runtimes

internal/service/rds/instance_test.go
I was not able to find a bug with updating certificates. We're planning to close #33546 with this PR, that makes no changes but adds a test, for these reasons:
1. I'm adding a test that shows the correct updating behavior, when `apply_immediate = "true"`, changing `ca_cert_identifier` from `rds-ca-ecc384-g1` to `rds-ca-rsa2048-g1`.
2. #33546 is stale because the cert discussed, `rds-ca-2019`, is no longer available, and there is no longer urgency to change that cert since people have already done that--the time has passed.
3. Some of the problem seemed to be related to an [AWS issue](https://repost.aws/questions/QU7Qr4sLjXTrqsMRH35WyJ0Q/applying-new-ca-cert-during-maintenance-but-shows-no-changes-pending) that may have been resolved.
4. Additional [complex …
=> rds/instance: Test correct updating of cert

.changelog/40281.txt, internal/service/rds/reserved_instance_offering_data_source.go, internal/service/rds/reserved_instance_offering_data_source_test.go
When `product_description` (e.g., "postgresql") was a substring of multiple products (e.g., "postgresql" and "aurora-postgresql"), you would get an error:
```
Error: multiple RDS Reserved Instance Offerings matched; use additional constraints to reduce matches to a single RDS Reserved Instance Offering
``` 
This fixes the issue so that you only get matches that exactly match the result such as `"postgresql" = "postgresql"` not `"postgresql" = "aurora-postgresql"`.
Closes #28358
```console
% make t T=TestAccRDSReservedInstanceOffering_ K=rds                    
TF_ACC=1 go1.23.3 test ./internal/service/rds/... -v -count 1 -parallel 20 -run='TestAccRDSReservedInstanceOffering_'  -timeout …
```
=> Fix aws_rds_reserved_instance_offering data source

internal/sweep/awsv2/skip.go
Fixes
```
% SWEEP=us-gov-west-1 make sweep
...
2024/11/26 09:18:06 [ERROR] Error running Sweeper (aws_db_proxy) in region (us-gov-west-1): error listing RDS DB Proxies (us-gov-west-1): operation error RDS: DescribeDBProxies, https response error StatusCode: 400, RequestID: 69389cd8-082d-416d-ac09-7dd093eb5060, api error InvalidAction: DescribeDBProxies is not available in this region.
```
=> r/aws_db_proxy: Fix sweeper in US GovCloud

.changelog/40304.txt, internal/service/bedrock/guardrail.go, internal/service/bedrock/guardrail_test.go, website/docs/r/bedrock_guardrail.html.markdown
The AWS API does not preserve the order of content_policy_config.filters_config`, which is causing a number of acceptance tests to fail.
Converts the parameter to a Set.
Closes https://github.com/hashicorp/terraform-provider-aws/issues/40041.
```console
% make testacc PKG=bedrock TESTS=TestAccBedrockGuardrail_basic
guardrail_test.go:32: Step 1/2 error: After applying this test step, the refresh plan was not empty.
stdout
Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
~ update in-place
~ resource "aws_bedrock_guardrail" "test" {
name                      = "tf-acc-test-2877867950171300694"
~ content_policy_config {
~ filters_config {
~ input_strength  = …
```
=> resource/aws_bedrock_guardrail: Convert `content_policy_config.filters_config` to Set

.changelog/40322.txt, internal/service/lambda/event_source_mapping.go, internal/service/lambda/event_source_mapping_test.go, website/docs/cdktf/python/r/lambda_event_source_mapping.html.markdown, website/docs/r/lambda_event_source_mapping.html.markdown
This PR adds support for `metrics_config` in the `aws_lambda_event_source_mapping` resource. Copied from the related issue:
-----
> AWS Lambda announces new Amazon CloudWatch metrics for Lambda Event Source Mappings (ESMs), which provide customers visibility into the processing state of events read by ESMs that subscribe to Amazon SQS, Amazon Kinesis, and Amazon DynamoDB event sources.
* [Announcement](https://aws.amazon.com/about-aws/whats-new/2024/11/amazon-cloudwatch-metrics-aws-lambda-esms/)
* [Blog post](https://aws.amazon.com/blogs/compute/introducing-new-event-source-mapping-esm-metrics-for-aws-lambda/)
* `aws_lambda_event_source_mapping`
```hcl
resource "aws_lambda_event_source_mapping" "example" {
metrics_config {
metrics = ["EventCount"]
}
}
```
-----
Closes #40275 …
=> Adds `metrics_config` to aws_lambda_event_source_mapping

internal/service/docdb/sweep.go
When sweeping an `aws_docdb_cluster` which is a member of a global cluster, the cluster `arn` value is needed. Otherwise it returns an error
> removing DocumentDB Cluster () from DocumentDB Global Cluster (tf-acc-test-7157141747640475231-0): operation error DocDB: RemoveFromGlobalCluster, https response error StatusCode: 400, api error InvalidParameterValue: Db cluster identifier  is not a valid arn
Note that the "()" should contain the ARN of the cluster.
=> sweeper/aws_docdb_cluster: Fix error when sweeping members of global cluster

website/docs/r/eks_cluster.html.markdown
The attribute reference for the resource `aws_eks_cluster` contains the entry `kubernetes_network_config.service_ipv6_cidr`.  
The pull request replaces this entry by introducing 
- a block `kubernetes_network_config` 
- attribute  `service_ipv6_cidr` listed under this block.
to establish consistency  with the way the other (nested) attributes are documented.
Closes #40331 
- [Attribute reference of `aws_eks_cluster`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/eks_cluster#attribute-reference)
=> docs: move attribute to separate block

.changelog/40359.txt, internal/service/fsx/openzfs_file_system.go
Increases the aws_fsx_openzfs_file_system SINGLE_AZ_2 max valid IOPS to 400000 to match what's supported by AWS and allow the terraform provider to work with larger filesystems which force IOPS to be above the current 350000 limit of the provider.
Closes #40358
Reference for max IOPS https://docs.aws.amazon.com/fsx/latest/OpenZFSGuide/performance.html#zfs-fs-performance
Let me know if I need to run the tests myself and I can try to arrange a sandbox account.
=> r/aws_fsx_openzfs_file_system increase SINGLE_AZ_2 max IOPS to 400000

internal/service/ec2/sweep.go, internal/service/ec2/vpc_network_interface.go
Uses `awsv2.Register` to register the `aws_subnet` sweeper.
Uses `tflog` for logging when detaching and deleting ENIs
=> sweeper/aws_subnet: Updates sweeper

.teamcity/scripts/provider_tests/acceptance_tests.sh, .teamcity/scripts/service_tests/acceptance_tests.sh, internal/generate/teamcity/acceptance_tests.tmpl, internal/provider/provider_acc_test.go
In the provider-level acceptance tests in the "Set Up" stage, the test run fails with no error message other than
> Process exited with code 1
It appears that the `-v` and `-json` parameters to `go test` are incompatible, but no error message is returned by the `go` executable
=> CI: Fixes "Process exited with code 1" error for non-service acceptance tests

website/docs/r/securityhub_standards_control_association.html.markdown
`aws_standards_control_association` resource does not exist in the provider. Instead, the resource in question is `aws_securityhub_standards_control_association`
=> d/aws_standards_control_association: Fix resource name in docs

.github/workflows/post_publish.yml
The version returned from the `curl` request to the registry will contain only the version number, while the release tag is prefixed with `v`.
For example, here is what is stored in the `LATEST_VERSION` environment variable:
```console
% curl -s "https://registry.terraform.io/v2/providers/323/provider-versions/latest" | jq -r '.data.attributes.version'
5.79.0
```
This changes the conditional to apply a prefix to the version number fetched from the registry to allow an accurate comparison of the two values.
Relates #40245 
Relates #39964 
https://github.com/hashicorp/terraform-provider-aws/actions/runs/12038203742/job/33563358216
=> .github/workflows: fix registry version check comparison

internal/service/rds/cluster_test.go
The original complaint was that performing an action that would destroy the security group (SG) associated with an RDS cluster caused the process to hang indefinitely. This issue raised concerns about Terraform's ability to handle such operations.  
This test case addresses the scenario by verifying that Terraform successfully manages the destruction and recreation of the security group associated with the RDS cluster. Specifically, the test validates the following:  
1. **Recreating the Security Group**: The test changes the name of the security group to trigger its destruction and subsequent recreation. Terraform should execute this process without hanging.  
2. **Handling Number Changes**: The test ensures that Terraform correctly manages changes to the number of security groups …
=> aws_rds_cluster: Verify sg destroy okay with cluster

website/docs/r/bedrockagent_agent.html.markdown
- Change `guardrail_config` to `guardrail_configuration` in the documentation . The provided reference to the source code shows `guardrail_configuration` as valid.
- Update references to ensure consistency throughout the text.
Closes #40401 
- [Resource documentation in registry](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/bedrockagent_agent#guardrail_config-block)
-  [Source code reference](https://github.com/hashicorp/terraform-provider-aws/blob/8dad2d3a602c8fc103a7eacb1fc9f4d3a9ac3994/internal/service/bedrockagent/agent.go#L103C5-L103C28)
Not applicable. Only documentation is update.
=> docs: update argument name in aws_bedrock_agent resource

.changelog/40409.txt, internal/service/rds/cluster_instance.go, internal/service/rds/cluster_instance_test.go, website/docs/r/rds_cluster_instance.html.markdown
When a `aws_rds_cluster_instance` is a part of `aws_rds_cluster` destroying failing with the following error:
```
Error: deleting RDS Cluster Instance (tf-acc-test-5080916373612377726-replica): operation error RDS: DeleteDBInstance, https response error StatusCode: 400, RequestID: d1fbb4b7-0822-40a1-b591-bf858b2a5ba5, InvalidDBClusterStateFault: Cannot delete the last instance of the read replica DB cluster. Promote the DB cluster to a standalone DB cluster in order to delete it.
```
This adds a `force_destroy` virtual attribute that will allow practitioners to destroy instances that are a part of a replica cluster. This process promotes the cluster to a standalone cluster so that the instance can be deleted.
```console
% make testacc …
```
=> r/aws_rds_cluster_instance: fix destroy error when cluster instance is in a read replica

internal/service/s3tables/sweep.go
Fixes sweeper error.
Closes https://github.com/hashicorp/terraform-provider-aws/issues/40439.
```console
% SWEEP=us-west-2 SWEEPERS=aws_s3tables_table_bucket make sweep
go1.23.3 test ./internal/sweep -v -sweep=us-west-2 -sweep-run='aws_s3tables_table_bucket' -timeout 360m
2024/12/04 11:05:44 [DEBUG] Running Sweepers for region (us-west-2):
2024/12/04 11:05:44 [DEBUG] Sweeper (aws_s3tables_table_bucket) has dependency (aws_s3tables_namespace), running..
2024/12/04 11:05:44 [DEBUG] Sweeper (aws_s3tables_namespace) has dependency (aws_s3tables_table), running..
2024/12/04 11:05:44 [DEBUG] Running Sweeper (aws_s3tables_table) in region (us-west-2)
2024/12/04 11:05:44 [DEBUG] sweeper: Configuring Terraform AWS …
```
=> r/aws_s3tables_namespace: Fix sweeper

website/docs/r/ecs_cluster.html.markdown
Minor documentation change to add `enhanced` has a potential option to `containerInsights` on ECS clusters. See #40445 for more details
I placed the new `enhanced` option at the start of the potential options in line with the order they are stated in ClusterSetting API Reference [here](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_ClusterSetting.html#API_ClusterSetting_Contents)
Closes #40445
=> Docs - ECS `containerInsights` add enhanced observability as an option

.github/workflows/post_publish.yml
Previously a version match would print the correct success message, but did not exit after doing so. This caused the loop to continue and eventually fall through to a failure message with a non-zero exit code.
Ref: https://github.com/hashicorp/terraform-provider-aws/actions/runs/12164517617/job/33926378837
Relates #40406 
Relates #40245 
Relates #39964
=> .github/workflows: exit successfully once registry and github versions match

website/docs/r/lb_listener.html.markdown
It has been pointed out by a community member that when a key `Name` is defined in the lb_listener_rule resource, it gets picked up by the AWS Console and displays the value within the `Name Tag` column. In order to save time for other users so that they don't perform the same investigation as the reporter did, this PR documents that quirk.
Closes #36386
=> docs(r-lb-listener-rule): Notes the relationship between a tag key `Name` to the AWS Console

.changelog/40241.txt, website/docs/r/route53profiles_association.html.markdown, website/docs/r/route53profiles_profile.html.markdown
This PR aims to clarify usage of `tags` arguments on the following resources:
- `aws_route53profiles_profile`
- `aws_route53profiles_association`
➡️ Code is already present, but documentation is missing.
Closes #40241.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/39661.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/38172.
I have checked provider behaviour using the following code, based on version `5.77.0`:
```hcl
resource "aws_route53profiles_profile" "dev" {
name = "example"
tags = {
IssueNumber = "40241"
IssueLink = "https://github.com/hashicorp/terraform-provider-aws/issues/40241"
}
}
```
Running a `terraform plan` command on this code output the following:
```bash
~ resource …
```
=> fix(route53profiles): improve documentation about tags usage.

.changelog/40471.txt, internal/service/rds/cluster.go, internal/service/rds/cluster_test.go
Previously if `storage_type` was configured on an RDS cluster restored from snapshot, the resulting cluster would always have the default value of `aurora` regardless of what was configured. This change properly sets the `storage_type` value, if configured.
Running a test to replicate this scenario against `main`:
```console
% make testacc PKG=rds TESTS=TestAccRDSCluster_SnapshotIdentifier_storageType
TF_ACC=1 go1.23.3 test ./internal/service/rds/... -v -count 1 -parallel 20 -run='TestAccRDSCluster_SnapshotIdentifier_storageType'  -timeout 360m
2024/12/05 14:30:09 Initializing Terraform AWS Provider...
cluster_test.go:2520: Step 1/1 error: Check failed: Check 4/4 error: …
```
=> r/aws_rds_cluster: respect `storage_type` when restored from snapshot

.changelog/39996.txt, internal/service/networkfirewall/firewall_policy.go, internal/service/networkfirewall/firewall_policy_test.go, website/docs/r/networkfirewall_firewall_policy.html.markdown
This PR is to add the `flow_timeouts` config block to the `stateful_engine_options` config block of the `aws_networkfirewall_firewall_policy` resource.
Closes #39986
Referred to [CreateFirewallPolicy](https://docs.aws.amazon.com/network-firewall/latest/APIReference/API_CreateFirewallPolicy.html) for specs and wordings.
```console
$ make testacc TESTS="TestAccNetworkFirewallFirewallPolicy_statefulEngineOption|TestAccNetworkFirewallFirewallPolicy_updateStatefulEngineOption" PKG=networkfir
ewall
TF_ACC=1 go1.23.2 test ./internal/service/networkfirewall/... -v -count 1 -parallel 20 -run='TestAccNetworkFirewallFirewallPolicy_statefulEngineOption|TestAccNetworkFirewallFirewallPolicy_updateStatefu …
```
=> feat: Add flow_timeouts arg to stateful_engine_options block for aws_networkfirewall_firewall_policy

.changelog/40468.txt, internal/service/fsx/windows_file_system.go, website/docs/r/fsx_windows_file_system.html.markdown
Update the validation for the argument `throughput_capacity` when creating an `aws_fsx_windows_file_system` resource.
The [current validation](https://github.com/hashicorp/terraform-provider-aws/blob/74707c768f1f93b2190a0b26abd1e40aa4bc93af/internal/service/fsx/windows_file_system.go#L284) allows values between 8 and 2048. Actually, 
- only a small subset of values inside this range is allowed 
- larger values are also fine in some regions.
Here an example output when a value of 2040 is specified:
```shell
Error: creating FSx for Windows File Server File System: operation error FSx: CreateFileSystem, https response error StatusCode: 400, RequestID: 39b44ab9-daca-46f1-a6c0-ec8a64c639d1, BadRequest: Invalid desired throughput capacity value provided: 2040 MB/s. Please refer to the …
```
=> fix: update validation for throughput capacity

internal/service/rds/instance.go, internal/service/rds/instance_diff_test.go, internal/service/rds/instance_test.go, website/docs/r/db_instance.html.markdown
Allow creating read replica in same region with different subnet group. This requires using the ARN, even though they are in the same region.
Closes #528
```console
% make testacc PKG=rds TESTS=TestAccRDSInstance_
--- PASS: TestAccRDSInstance_basic (479.86s)
--- PASS: TestAccRDSInstance_newIdentifier_Immediately (575.60s)
--- PASS: TestAccRDSInstance_Storage_changeThroughput (577.90s)
--- PASS: TestAccRDSInstance_newIdentifier_Pending (616.16s)
--- PASS: TestAccRDSInstance_Storage_changeIOPS (743.28s)
--- PASS: TestAccRDSInstance_Storage_typePostgres (745.61s)
--- PASS: TestAccRDSInstance_Storage_changeIOPSThroughput (776.82s)
--- PASS: TestAccRDSInstance_Storage_gp3MySQL (782.13s)
--- PASS: TestAccRDSInstance_BlueGreenDeployment_deletionProtectionBypassesBlueGreen (858.42s)
--- PASS: …
```
=> resource/aws_db_instance: Allow creating read replica in same region with different subnet group

internal/service/eks/cluster.go, internal/service/eks/cluster_test.go
- Fix enablement of EKS Auto Mode on existing clusters without forcing re-creation
Closes #40411
- Relates to #40370
```console
...
```
=> r/aws_eks_cluster: Fix enablement of EKS Auto Mode on existing clusters without forcing re-creation

.changelog/40484.txt, internal/service/sagemaker/notebook_instance.go, internal/service/sagemaker/notebook_instance_test.go, website/docs/r/sagemaker_notebook_instance.html.markdown
Change the plan-time validation to allow the platform identifier `notebook-al2-v3` (Amazon Linux 2 v3) for the resource `aws_sagemaker_notebook_instance`.
Closes #40478 
- [Supported notebook instances](https://docs.aws.amazon.com/sagemaker/latest/dg/nbi-al2.html) mentioning the new type.
- [CloudFormation](https://docs.aws.amazon.com/de_de/AWSCloudFormation/latest/UserGuide/aws-resource-sagemaker-notebookinstance.html#cfn-sagemaker-notebookinstance-platformidentifier) mentioning the pattern for allowed values. 
```shell
❯ make testacc TESTS=TestAccSageMakerNotebookInstance_Platform_identifier PKG=sagemaker
TF_ACC=1 go1.23.3 test ./internal/service/sagemaker/... -v -count 1 -parallel 3 …
```
=> feat: allow `notebook-al2-v3` as platform_identifier

website/docs/r/cognito_user_pool_domain.html.markdown
The example of `cognito_user_pool_domain` with custom domain, it needs to[ be fully-qualified domain name](https://github.com/hashicorp/terraform-provider-aws/blob/main/website/docs/r/cognito_user_pool_domain.html.markdown#argument-reference) but example is not.
* https://github.com/hashicorp/terraform-provider-aws/blob/main/website/docs/r/cognito_user_pool_domain.html.markdown#argument-reference
=> fixing the doc: Update cognito_user_pool_domain example

website/docs/r/db_proxy.html.markdown
This PR updates the documentation to address an issue where Terraform perpetually shows a diff and recreates an RDS Proxy when one or more specified subnets are in an Availability Zone (AZ) that does not support DB proxies.  
When creating an RDS Proxy, the proxy is successfully created but only includes subnets from supported AZs. If one of the specified subnets is in an unsupported AZ:  
1. The proxy is created with only the subnets in supported AZs (e.g., `supported_1` and `supported_2` instead of the expected three subnets).  
2. Subsequent Terraform plans detect a difference between the desired state (three subnets) and the actual state (two subnets) and attempt to recreate the proxy. This results in perpetual diffs and recreation cycles.  
- The AWS API does not return an error when …
=> docs: Avoid DB proxy diffs for unsupported AZs

.teamcity/components/generated/services_all.kt, internal/generate/teamcity/acctest_services.hcl
Reduce parallelism for `apigatewayv2` to 10 to prevent
> BadRequestException: There are too many Vpc Links defined for this account. Limit is 10.
=> ci: Prevent over-quota exceptions

.changelog/40511.txt, internal/service/rds/cluster.go, internal/service/rds/cluster_test.go
This PR addresses a breaking regression introduced in v5.80.0 that affects the removal of the `serverlessv2_scaling_configuration` block in RDS cluster configurations.
Prior to v5.80.0, users could remove the `serverlessv2_scaling_configuration` block from their configuration without errors or perpetual diffs. While AWS does not remove the scaling configuration metadata when the block is deleted, Terraform allowed users to remove the block without errors.  
However, v5.80.0 and #40230 introduced two issues:
1. `max_capacity` could be explicitly set to `0`, an invalid value for AWS.
2. Terraform sent `max_capacity: 0` to the AWS API when the `serverlessv2_scaling_configuration` block was removed, causing the error:  
`InvalidParameterValue: Serverless v2 maximum capacity 0.0 isn't valid. …
=> `aws_rds_cluster`: Fix Regression in `serverlessv2_scaling_configuration` Handling

.ci/semgrep/acctest/steps.yml, internal/service/ec2/ec2_instance_test.go, internal/service/ec2/vpc_security_group_test.go, internal/service/ecr/pull_through_cache_rule_test.go, internal/service/ecr/repository_creation_template_test.go, internal/service/elasticache/replication_group_test.go, internal/service/elasticsearch/domain_test.go, internal/service/iot/role_alias_test.go, internal/service/opensearch/domain_test.go, internal/service/s3/bucket_metric_test.go
Acceptance test steps with `ExpectError` ignore any `Check`s. Adds Semgrep rule to prevent `Check`s when `ExpectError` is set
=> Removes unused `Check`s when test step has `ExpectError`

website/docs/r/eks_access_policy_association.html.markdown
Substitute incorrect "a colon" for more correct "an octothorp" in eks_access_policy_association import instructions, so that english sentence matches the referenced symbol.
Updates the eks_access_policy_association import documentation to use the correct word for the separator in the import id.
The examples, and other text refer to `#` as the correct separator. I've also proven that `#` is the expected separator for this import.
`#` is called an "octothorp". It is also known by other names as well. I checked and I don't see any consistency issues with using "octothorp", but if "pound sign" or "hashtag symbol" or something else is more consistent, I'm happy to update.
...
I am unsure how to properly build the docs, but I will look into it.
=> Fix incorrect word in eks_access_policy_association import documention.

internal/framework/types/case_insensitive_string.go, internal/framework/types/case_insensitive_string_test.go, internal/framework/types/once_a_week_window.go
Adds a Terraform Plugin Framework case-insensitive [custom string type](https://developer.hashicorp.com/terraform/plugin/framework/handling-data/types/custom).
Useful for DNS domain names.
```console
% go test ./internal/framework/types 
ok  	github.com/hashicorp/terraform-provider-aws/internal/framework/types	0.665s
```
=> Add a Terraform Plugin Framework case-insensitive custom string type

.changelog/26868.txt, internal/service/acmpca/certificate_authority_data_source.go, internal/service/acmpca/certificate_authority_data_source_test.go
Given that an alternate account shared an ACM PCA with me,
When I tried to retrieve the ACM PCA resource,
I would encounter an `AccessDeniedException` as the default permission does not allow retrieval of the PCA's CSR.
Closes #26868
```
2022-11-18T19:11:47.352+0800 [DEBUG] provider.terraform-provider-aws_v4.40.0_x5: [DEBUG] Reading ACM PCA Certificate Authority Certificate Signing Request: {
2022-11-18T19:11:47.352+0800 [DEBUG] provider.terraform-provider-aws_v4.40.0_x5:   CertificateAuthorityArn: "arn:aws:acm-pca:ap-southeast-1:<account_id>:certificate-authority/<uuid>"
2022-11-18T19:11:47.352+0800 [DEBUG] provider.terraform-provider-aws_v4.40.0_x5: }
2022-11-18T19:11:47.352+0800 [DEBUG] provider.terraform-provider-aws_v4.40.0_x5: [DEBUG] [aws-sdk-go] DEBUG: Request …
```
=> d/aws_acmpca_certificate_authority - handle exception when retrieving a shared ACM PCA

website/docs/r/eks_cluster.html.markdown
This pull request updates the documentation for EKS Auto Mode to include the requirement that `bootstrap_self_managed_addons` must be set to `false`. This change is based on the following error message encountered during testing:
```shell
│ Error: creating EKS Cluster (eks-auto-mode-cluster): operation error EKS: CreateCluster, https response error StatusCode: 400, RequestID: xxxxxxxxxxxxxxx, InvalidParameterException: When EKS Auto Mode is enabled, bootstrapSelfManagedAddons must be set to false.
```
None
- AWS Error Message (see above)
=> [Docs]: `aws_eks_cluster.bootstrap_self_managed_addons` must be set to `false` for EKS Auto Mode

.changelog/40514.txt, internal/service/elasticache/replication_group.go, internal/service/elasticache/replication_group_test.go, website/docs/r/elasticache_replication_group.html.markdown
Converts `at_rest_encryption_enabled` to nullable Bool so that default of `true` when `engine` is `valkey` does not cause perpetual diff which triggers replacement.
Closes #39955
```console
% make testacc PKG=elasticache TESTS=TestAccElastiCacheReplicationGroup_
--- PASS: TestAccElastiCacheReplicationGroup_cacheClustersConflictsWithReplicasPerNodeGroup (5.71s)
--- PASS: TestAccElastiCacheReplicationGroup_ValidationMultiAz_noAutomaticFailover (6.32s)
--- PASS: TestAccElastiCacheReplicationGroup_ClusterMode_nonClusteredParameterGroup (793.40s)
--- PASS: TestAccElastiCacheReplicationGroup_Redis_basic (854.78s)
--- PASS: TestAccElastiCacheReplicationGroup_updateDescription (873.22s)
--- PASS: TestAccElastiCacheReplicationGroup_ClusterMode_singleNode (1351.93s)
--- PASS: …
```
=> resource/aws_elasticache_replication_group: Make `at_rest_encryption_enabled` nullable Bool

.changelog/33797.txt, internal/service/medialive/channel_encoder_settings_schema.go, internal/service/medialive/channel_test.go
Added missing `teletext_destinations_settings` to `captions_descriptions`.
It's just an empty struct so that's what I left it at. [docs](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/medialive/types#TeletextDestinationSettings)
Even though it's just an empty struct, it's needed because of diff. In the current state where it isn't added, it'll notice it as a change every time.
```console
% make testacc TESTS=TestAccMediaLiveChannel_captionDescriptions PKG=medialive
TF_ACC=1 go test ./internal/service/medialive/... -v -count 1 -parallel 20 -run='TestAccMediaLiveChannel_captionDescriptions'  -timeout 360m
=== RUN   TestAccMediaLiveChannel_captionDescriptions
=== PAUSE TestAccMediaLiveChannel_captionDescriptions
=== CONT …
```
=> added teletext destinations settings

.changelog/40574.txt, internal/service/codeconnections/exports_test.go, internal/service/codeconnections/host.go, internal/service/codeconnections/host_test.go
This PR fixes the `tls_certificate` attribute in `aws_codeconnections_host`, making it optional.
Closes #40573
https://docs.aws.amazon.com/codeconnections/latest/APIReference/API_VpcConfiguration.html
```console
make testacc TESTS=TestAccCodeConnectionsHost_ PKG=codeconnections 
TF_ACC=1 go1.23.3 test ./internal/service/codeconnections/... -v -count 1 -parallel 20 -run='TestAccCodeConnectionsHost_'  -timeout 360m
2024/12/16 09:26:38 Initializing Terraform AWS Provider...
=== RUN   TestAccCodeConnectionsHost_basic
=== PAUSE TestAccCodeConnectionsHost_basic
=== RUN   TestAccCodeConnectionsHost_disappears
=== PAUSE TestAccCodeConnectionsHost_disappears
=== RUN   TestAccCodeConnectionsHost_vpc …
```
=> fix tls cert for `aws_codeconnections_host`

.changelog/40584.txt, internal/service/lakeformation/resource_lf_tag.go
Currently the `aws_lakeformation_resource_lf_tag` will panic if the referenced `aws_lakeformation_lf_tag` is removed before its replacement.
```console
Stack trace from the terraform-provider-aws_v5.80.0_x5 plugin:
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x25793d7e]
goroutine 30 [running]:
github.com/hashicorp/terraform-provider-aws/internal/service/lakeformation.(*resourceResourceLFTag).Delete(0xc00429f8f0, {0x2c545368, 0xc0043833b0}, {{{{0x2c5bfae0, 0xc00417bce0}, {0x2a491e40, 0xc00417aae0}}, {0x2c5e0628, 0xc00405db30}}, {{{0x0, ...}, ...}, ...}, ...}, ...)
github.com/hashicorp/terraform-provider-aws/internal/service/lakeformation/resource_lf_tag.go:466 +0x3de
```
```console
% make testacc …
```
=> r/aws_lakeformation_resource_lf_tag: fix destroy panic

.changelog/40601.txt, internal/service/rds/cluster.go, internal/service/rds/cluster_test.go, internal/service/rds/consts.go
Modifying `allocated_storage` could produce the following error:
```console
│ Error: waiting for RDS Cluster (random-name) update: unexpected state 'scaling-storage', wanted target 'available'. last error: %!s(<nil>)
```
```console
% make testacc TESTARGS='-run=TestAccRDSCluster_allocatedStorage_\|TestAccRDSCluster_basic\|TestAccRDSCluster_disappears' PKG=rds
TF_ACC=1 go1.23.3 test ./internal/service/rds/... -v -count 1 -parallel 20  -run=TestAccRDSCluster_allocatedStorage_\|TestAccRDSCluster_basic\|TestAccRDSCluster_disappears -timeout 360m
2024/12/17 12:27:13 Initializing Terraform AWS Provider...
=== RUN   TestAccRDSCluster_basic
=== PAUSE TestAccRDSCluster_basic
=== RUN …
```
=> r/rds_cluster: fix wait error when modifying `allocated_storage`

website/docs/r/cloudwatch_log_account_policy.html.markdown
* Adds missing policy types: field index policy and transformer policy
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-logs-accountpolicy.html#:~:text=requires%3A%20Replacement-,PolicyType,-The%20type%20of
=> docs: add missing policy types

.changelog/40579.txt, internal/service/resourcegroups/resource.go, internal/service/resourcegroups/resource_migrate.go, internal/service/resourcegroups/resource_test.go, website/docs/r/resourcegroups_resource.html.markdown
Previously the `group_arn` and `resource_arn` values were assumed to be ARNs in a format which could always be split by a `/` into at least two parts. The provider did no validation of these inputs prior to attempting to split the value, causing `index out of range` crashes when values were provided that did not match these assumptions.
Instead of attempting to split ARNs of varying formatting to construct the `id` attribute, `id` will now be composed of a comma-delimited string combining `group_arn` and `resource_arn` in their entirety. This removes the logic and assumptions around splitting the ARN and should prevent future crashes regardless of the format provided. The more complete content of the `id` attribute will also enable supporting import for this resource (also added as part …
=> r/aws_resourcegroups_resource: fix crash when attempting to parse arn

skaff/datasource/datasourcetest.gtpl, skaff/resource/resourcefw.gtpl, skaff/resource/resourcetest.gtpl
* Uses `resource.ComposeAggregateTestCheckFunc` instead of `resource.ComposeTestCheckFunc` in acceptance tests
* Corrects repetition and uses attribute constant in ARN checks
* Adds instruction to only use `id` attribute if corresponding AWS API structs have `...Id` field
* Suggests alternatives to regex for ARN checks if appropriate
=> Updates to `skaff` templates

.archive/changelog/40634.txt, internal/service/autoscaling/group.go, internal/service/autoscaling/group_test.go, website/docs/r/autoscaling_group.html.markdown
Adds the new `availability_zone_distribution` argument, which features `capacity_distribution_strategy`.
* [Announcement](https://aws.amazon.com/about-aws/whats-new/2024/11/ec2-auto-scaling-strict-availability-zone-balance/)
Regarding some of the syntax, I've tried to stick with how we currently do things in this resource (e.g. casting a flatten to a slice) for consistency, making it easier to identity patterns during a potential migration to Plugin Framework.
```console
$  make testacc TESTARGS='-run=TestAccAutoScalingGroup_basic\|TestAccAutoScalingGroup_simple\|TestAccAutoScalingGroup_availabilityZoneDistribution' PKG=autoscaling
TF_ACC=1 go1.23.3 test ./internal/service/autoscaling/... …
```
=> autoscaling: add new `availability_zone_distribution` argument

.changelog/40562.txt, .changelog/40639.txt, internal/service/iam/policy_document_data_source.go, internal/service/iam/policy_document_data_source_test.go
This reverts https://github.com/hashicorp/terraform-provider-aws/pull/40562, which is causing significant issues.
Closes #40639.
=> Revert 40562 add validation for iam policy document sid

.changelog/40626.txt, internal/framework/stdattributes.go, internal/service/apigateway/account.go, internal/service/apigateway/domain_name_access_association.go, internal/service/appconfig/environment.go, internal/service/datazone/environment_profile.go, internal/service/datazone/user_profile.go, internal/service/lexv2models/bot_locale.go, internal/service/route53/cidr_location.go, internal/service/s3/bucket_accelerate_configuration_test.go, internal/service/s3/bucket_acl_test.go, internal/service/s3/bucket_cors_configuration_test.go, internal/service/s3/bucket_inventory_test.go, internal/service/s3/directory_bucket.go, website/docs/r/api_gateway_domain_name_access_association.html.markdown, website/docs/r/route53_cidr_location.html.markdown, website/docs/r/s3_directory_bucket.html.markdown
Starts the process of deprecating unneeded `id` attributes in resource types implemented using Terraform Framework.
Note that regardless of the actual `DeprecationMessage` on the attribute, Terraform will display, e.g.
> │ Warning: Deprecated attribute
│ 
│   on main.tf line 431, in resource "aws_s3_bucket_policy" "test":
│  431:   bucket = aws_s3_directory_bucket.test.id
│ 
│ The attribute "id" is deprecated. Refer to the provider documentation for details.
Adds
* `framework.IDAttributeDeprecatedWithAlternate` when there is an alternate attribute to use
* `framework.IDAttributeDeprecatedNoReplacement` when these is no replacement attribute
Deprecates `id` from
* `aws_s3_directory_bucket`
* `aws_route53_cidr_location`
* `aws_api_gateway_domain_name_access_association`
=> Deprecates some `id` attributes on Framework resources

website/docs/r/msk_replicator.html.markdown
The argument `topic_name_configuration` is mentioned is the resource documentation wrongly as  `topic_configuration_name`.
This PR updates the resource documentation.
Closes #40596 
- [Resource documentation](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/msk_replicator#topic_configuration_name)
- [Argument name in provider source code](https://github.com/hashicorp/terraform-provider-aws/blob/214d10a9cf76f6344a84bfb79f59b7bfec19c130/internal/service/kafka/replicator.go#L178)
Not applicable, only documentation is updated.
=> docs: update argument name in resource `aws_msk_replicator`

website/docs/r/db_proxy.html.markdown
The recent aws-sdk-go-v2 RDS release adds support for `MYSQL_CACHING_SHA2_PASSWORD` auth type.
https://github.com/aws/aws-sdk-go-v2/blob/5a964704cb2640ed57a74b9b37a53dcda7b6b7dd/service/rds/CHANGELOG.md#v1930-2024-12-16
This updates the docs regarding the RDS Proxy `client_password_auth_type` supported values.
[Rendered version](https://github.com/yelinaung/terraform-provider-aws/blob/51ca6207093950e07ca7b2dee2b2cf5e31923f0e/website/docs/r/db_proxy.html.markdown#attribute-reference)
=> docs: update RDS Proxy client_password_auth_type supported auth type

website/docs/r/lb_trust_store.html.markdown
The example listed [here](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lb_trust_store) contains a load balancer description 
```hcl
[...]
resource "aws_lb_listener" "example" {
[ ... ]
mutual_authentication = {
mode            = "verify"
trust_store_arn = aws_lb_trust_store.test.arn
}
}
```
with an invalid assignment ` mutual_authentication = {`.  
The PR fixes the invalid assignment 
Closes #40605 
- [Definition of mutual_authentication in provider source code](https://github.com/hashicorp/terraform-provider-aws/blob/23765762b7989c2e4b1fcaafb6da89c24e746565/internal/service/elbv2/listener.go#L347)
- [Code from Listener tests](https://github.com/hashicorp/terraform-provider-aws/blob/23765762b7989c2e4b1fcaafb6da89c24e746565/internal/service/elbv2/listener_test …
=> doc: fix example code in documentation for aws_lb_trust_store

website/docs/r/cloudfront_vpc_origin.html.markdown
An error in the [aws_cloudfront_vpc_origin](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudfront_vpc_origin) documentation has been corrected. Enclose `id` in double-quotes.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/40239
=> docs: fix example import block by quoting

website/docs/r/resiliencehub_resiliency_policy.html.markdown
As mentioned in #40334  [this example](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/resiliencehub_resiliency_policy#example-usage) throws errors when running `terraform plan` respective `terraform apply`. Reason for this is that `name` as well as `description` have an invalid prefix `policy_`.
This PR removes the prefix, so that the example can be executed successfully.
Closes #40334 
- [Current Resource documentation](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/resiliencehub_resiliency_policy)
- [Field `description` in source code](https://github.com/hashicorp/terraform-provider-aws/blob/398878c25514754dd22789c985e717c45c64a513/internal/service/resiliencehub/resiliency_policy.go#L98)
- [ Field `name` in source …
=> docs: fix example code for resource aws_resiliencehub_resiliency_policy

.changelog/40670.txt, internal/service/sesv2/configuration_set.go, internal/service/sesv2/configuration_set_test.go
This PR fixes a bug when `MaxDeliverySeconds` was included in the API request even if not set in the configuration.
Closes #40591.
https://docs.aws.amazon.com/ses/latest/APIReference-V2/API_DeliveryOptions.html#SES-Type-DeliveryOptions-MaxDeliverySeconds
```console
% make testacc PKG=sesv2 ACCTEST_PARALLELISM=1 TESTARGS="-run=TestAccSESV2ConfigurationSet_deliveryOptions"
TF_ACC=1 go1.23.3 test ./internal/service/sesv2/... -v -count 1 -parallel 1  -run=TestAccSESV2ConfigurationSet_deliveryOptions -timeout 360m
2024/12/21 16:22:19 Initializing Terraform AWS Provider...
=== RUN   TestAccSESV2ConfigurationSet_deliveryOptions
=== PAUSE TestAccSESV2ConfigurationSet_deliveryOptions
=== CONT …
```
=> r/aws_sesv2_configuration: Fix `delivery_options.max_delivery_seconds` handling

.changelog/40662.txt, internal/service/events/buses_data_source.go, internal/service/events/buses_data_source_test.go, internal/service/events/service_package_gen.go, website/docs/d/cloudwatch_event_buses.html.markdown
This PR adds a new `aws_cloudwatch_event_buses` data source.
Closes https://github.com/hashicorp/terraform-provider-aws/issues/39209.
https://docs.aws.amazon.com/eventbridge/latest/APIReference/API_ListEventBuses.html
```console
% make testacc PKG=events ACCTEST_PARALLELISM=1 TESTARGS="-run=TestAccEventsEventBusesDataSource_"      
TF_ACC=1 go1.23.1 test ./internal/service/events/... -v -count 1 -parallel 1  -run=TestAccEventsEventBusesDataSource_ -timeout 360m
=== RUN   TestAccEventsEventBusesDataSource_basic
=== PAUSE TestAccEventsEventBusesDataSource_basic
=== CONT  TestAccEventsEventBusesDataSource_basic
--- PASS: TestAccEventsEventBusesDataSource_basic (17.16s)
PASS
ok …
```
=> d/aws_cloudwatch_event_buses: new data source

README.md
Seems this group is no longer used, proposing removing
> As of July 22, 2021 inbound messages to this group have been disabled, and it will now be used for outbound announcements only.
=> Remove Google Group from README.md

website/docs/r/cloudfront_distribution.html.markdown
This is the documentation change for `logging_config` block existing in the `aws_cloudfront_distribution` page. This documentation change specifies that the version used for CloudWatch Standard (Access) logs is Legacy instead of v2. I think this change makes it more clear for the newer AWS provider and CLoudFront user.
https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/AccessLogs.html
=> Cloudfront distribution logging config documentation update

.changelog/40700.txt, internal/service/rds/engine_version_data_source.go, internal/service/rds/engine_version_data_source_test.go, website/docs/d/rds_engine_version.html.markdown
Add to  aws_rds_engine_version support for 
* supports_certificate_rotation_without_restart
* supports_integrations
* supports_local_write_forwarding
There is a test failure, but I do not think it is my PR:
```    engine_version_data_source_test.go:165: Step 1/2 error: Check failed: Check 1/1 error: data.aws_rds_engine_version.test: Attribute 'version' didn't match "^5\\.7\\.", got "8.0.40"``` 
I suspect the default has changed.
No related issue.
```console
% make testacc TESTS=TestAccRDSEngineVersion PKG=rds
TF_ACC=1 go test ./internal/service/rds/... -v -count 1 -parallel 20 -run='TestAccRDSEngineVersion'  -timeout 360m
2024/12/26 19:52:55 Initializing Terraform AWS Provider...
=== RUN …
```
=> Add support for supports_local_write_forwarding, supports_certificate_rotation_without_restart and supports_integrations

.changelog/40708.txt, internal/service/apigateway/domain_name.go, internal/service/apigateway/domain_name_test.go
Fixes #40699 where error occurs when trying to add policy to existing private domain name
Closes #40699
```console
$ ACCTEST_PARALLELISM=10 make testacc TESTS=TestAccAPIGatewayDomainName PKG=apigateway
TF_ACC=1 go1.23.3 test ./internal/service/apigateway/... -v -count 1 -parallel 10 -run='TestAccAPIGatewayDomainName'  -timeout 360m
2024/12/27 16:26:57 Initializing Terraform AWS Provider...
=== RUN   TestAccAPIGatewayDomainNameAccessAssociation_tags
=== PAUSE TestAccAPIGatewayDomainNameAccessAssociation_tags
=== RUN   TestAccAPIGatewayDomainNameAccessAssociation_tags_null
=== PAUSE TestAccAPIGatewayDomainNameAccessAssociation_tags_null
=== RUN …
```
=> aws_api_gateway_domain_name - fixed issue when policy is added to private domain name after initial creation

docs/retries-and-waiters.md
This PR fixes invalid indentation and the `function` keyword on the Retries and Waiters documentation page.
N/A
N/A
=> docs: Retries and Waiters fixes

.changelog/40761.txt, internal/service/glue/catalog_database.go
Previously a nil nested `principal` block could trigger a panic:
```
panic: interface conversion: interface {} is nil, not map[string]interface {}
```
Closes #40738
```console
% make testacc PKG=glue TESTS=TestAccGlueCatalogDatabase_
TF_ACC=1 go1.23.3 test ./internal/service/glue/... -v -count 1 -parallel 20 -run='TestAccGlueCatalogDatabase_'  -timeout 360m
2025/01/03 10:35:25 Initializing Terraform AWS Provider...
--- PASS: TestAccGlueCatalogDatabase_disappears (14.67s)
--- PASS: TestAccGlueCatalogDatabase_targetDatabaseWithRegion (24.83s)
--- PASS: TestAccGlueCatalogDatabase_createTablePermission (26.68s)
--- PASS: TestAccGlueCatalogDatabase_targetDatabase (29.36s)
--- PASS: …
```
=> r/aws_glue_catalog_database: fix crash expanding `create_table_default_permission`

.changelog/40775.txt, internal/service/quicksight/user.go, internal/service/quicksight/user_test.go, website/docs/r/quicksight_user.html.markdown
This PR is to add the attribute `user_invitation_url` to the `aws_quicksight_user` resource. Note that this attribute is only available when the resource is created using the `RegisterUser` API, so it would not be read/updated in the state thereafter.
Closes #40556
Referred to [RegisterUser](https://docs.aws.amazon.com/quicksight/latest/APIReference/API_RegisterUser.html) for specs and wordings.
```console
$ export QUICKSIGHT_NAMESPACE=default
$ make testacc TESTS=TestAccQuickSightUser_ PKG=quicksight
TF_ACC=1 go1.23.3 test ./internal/service/quicksight/... -v -count 1 -parallel 20 -run='TestAccQuickSightUser_'  -timeout 360m
2025/01/05 04:10:02 Initializing Terraform AWS Provider...
=== …
```
=> feat: Add user_invitation_url attr for aws_quicksight_user

website/docs/r/budgets_budget.html.markdown
This PR is a documentation fix that correctly marks the `limit_amount` and `limit_unit` arguments of the `aws_budgets_budget` resource as optional as per the resource code.
Closes #40760
n/a
n/a
=> docs: Mark limit_amount and limit_unit args as optional for aws_budgets_budget

.changelog/40772.txt, internal/service/ecr/account_setting.go, internal/service/ecr/account_setting_test.go, website/docs/r/ecr_account_setting.html.markdown
This PR is to add support for setting registry policy scope via appropriate values for the `name` and `value` argument in the `aws_ecr_account_setting` resource.
Closes #40705
Referred to [PutAccountSetting](https://docs.aws.amazon.com/AmazonECR/latest/APIReference/API_PutAccountSetting.html) for specs and wordings.
```console
$ make testacc TESTS=TestAccECRAccountSetting_serial PKG=ecr
TF_ACC=1 go1.23.3 test ./internal/service/ecr/... -v -count 1 -parallel 20 -run='TestAccECRAccountSetting_serial'  -timeout 360m
2025/01/04 04:12:19 Initializing Terraform AWS Provider...
=== RUN   TestAccECRAccountSetting_serial
=== PAUSE TestAccECRAccountSetting_serial
=== CONT …
```
=> feat: Add registry policy scope support for aws_ecr_account_setting

.changelog/40769.txt, internal/service/ec2/ec2_eip_association.go, internal/service/ec2/ec2_eip_association_test.go, internal/service/ec2/find.go, website/docs/r/eip_association.html.markdown
This PR is to add the `association_id` attribute to the `aws_eip_association` resource so that it is more aligned with typical convention with ID attributes. As per the original issue, the documentation has also been updated to include both `id` and `association_id`. Argument descriptions have also been updated to better reflect their specs.
Closes #40766
Referred to [AssociateAddress](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_AssociateAddress.html) for specs and wordings.
```console
$ make testacc TESTS=TestAccEC2EIPAssociation_ PKG=ec2
TF_ACC=1 go1.23.3 test ./internal/service/ec2/... -v -count 1 -parallel 20 -run='TestAccEC2EIPAssociation_'  -timeout 360m
2025/01/03 …
```
=> feat: Add association_id arg for aws_eip_association + improve docs

website/docs/r/fsx_windows_file_system.html.markdown
The examples provided for the resource [`aws_fsx_windows_file_system`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/fsx_windows_file_system
) use a throughput capacity of 1024 MBps.
The AWS pricing calculator shows  cost of 1.10 USD per  MBps-month  (or more), so that each of the example creates  monthly cost of > 1k USD.
With this PR we update throughput capacity and storage, so that users can still run the example code but with significantly less cost.
Closes #40817 
- [FSx pricing](https://aws.amazon.com/fsx/windows/pricing/)
- [Announcement: Minimum storage size FSx Windows](https://aws.amazon.com/about-aws/whats-new/2019/11/amazon-fsx-for-windows-file-server-reduces-the-minimum-size-for-file-systems-from-300-gbs-to-32-gbs/)
Not applicable, only …
=> docs: reduce cost foot print of example code

internal/service/opensearchserverless/sweep.go
Multiple sweeper fixes
```console
% make sweep SWEEPARGS='-sweep-run=aws_opensearchserverless -sweep-allow-failures'
go1.23.3 test ./internal/sweep -v -sweep=us-west-2,us-east-1,us-east-2,us-west-1 -sweep-run=aws_opensearchserverless -sweep-allow-failures -timeout 360m
2025/01/08 11:16:38 [DEBUG] Running Sweepers for region (us-west-2):
2025/01/08 11:16:38 [DEBUG] Running Sweeper (aws_opensearchserverless_vpc_endpoint) in region (us-west-2)
2025/01/08 11:16:38 [DEBUG] sweeper: Configuring Terraform AWS Provider: sweeper_region=us-west-2
2025-01-08T11:16:38.134-0600 [DEBUG] sweeper.aws-base: Resolving credentials provider: sweeper_region=us-west-2
2025-01-08T11:16:38.134-0600 [DEBUG] sweeper.aws-base: Using …
```
=> sweepers: fix opensearchserverless resource references

internal/service/amp/scraper_test.go, internal/service/amp/workspace_test.go, internal/service/appautoscaling/target_test.go, internal/service/appfabric/ingestion_destination_test.go, internal/service/appfabric/ingestion_test.go, internal/service/appintegrations/data_integration_test.go, internal/service/appintegrations/event_integration_test.go, internal/service/appstream/image_data_source_test.go
Reduce uses of `resource.TestCheckResourceAttrSet` with ARN attributes in favour of explicit checks
=> testing: Reduce uses of `resource.TestCheckResourceAttrSet` with ARN attributes: `a` services

.changelog/40842.txt, internal/service/codebuild/project.go, internal/service/codebuild/project_test.go
This PR fixes the `aws_codebuild_project` to allow the `file_system_locations` configuration to be removed on Update.
Closes #38888.
https://docs.aws.amazon.com/codebuild/latest/APIReference/API_UpdateProject.html
```console
% make testacc PKG=codebuild ACCTEST_PARALLELISM=1 TESTARGS="-run=TestAccCodeBuildProject_fileSystemLocations"
TF_ACC=1 go1.23.3 test ./internal/service/codebuild/... -v -count 1 -parallel 1  -run=TestAccCodeBuildProject_fileSystemLocations -timeout 360m
2025/01/08 16:48:54 Initializing Terraform AWS Provider...
=== RUN   TestAccCodeBuildProject_fileSystemLocations
=== PAUSE TestAccCodeBuildProject_fileSystemLocations
=== CONT …
```
=> r/aws_codebuild_project: Allow `file_system_locations` to be removed on Update

website/docs/r/guardduty_organization_configuration.html.markdown
This PR is to add a deprecation notice for the `datasources` argument for the `aws_guardduty_organization_configuration` resource, similar to that of the `aws_guardduty_detector` resource.
Closes #37809
Referred to the [`aws_guardduty_detector` resource doc](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/guardduty_detector) for wordings.
n/a
=> docs: Add deprecation notice of datasources arg for aws_guardduty_organization_configuration

.changelog/40840.txt, internal/service/apigatewayv2/service_package.go
This change adds an additional step to the `apigatewayv2` service client retry logic to check for `ConflictException` error responses based solely on the message content. This is intended to address cases where the error is not serialized into the higher level `types.ConflictException` defined as the service package level (which the existing logic expects). Local testing of the configuration provided in the linked issue confirmed this additional logic prevents the intermittent failures observed during destruction of large numbers of routes in parallel.
Closes #40575
- [`*smithy.OperationError`](https://github.com/aws/smithy-go/blob/v1.22.1/errors.go#L42-L48)
```console
% make testacc PKG=apigatewayv2 TESTS=TestAccAPIGatewayV2Route_
==> Checking …
```
=> r/aws_apigatewayv2: additional `ConflictException` retry logic

.changelog/40873.txt, internal/service/ses/errors.go, internal/service/ses/receipt_rule.go
This PR adds retries for IAM eventual consistency errors when creating or updating the `aws_ses_receipt_rule` resource.
Closes #7917
Closes #34259 
https://docs.aws.amazon.com/ses/latest/APIReference/API_CreateReceiptRule.html
https://docs.aws.amazon.com/ses/latest/APIReference/API_UpdateReceiptRule.html
```console
% make testacc PKG=ses ACCTEST_PARALLELISM=1 TESTARGS="-run=TestAccSESReceiptRule_"  
TF_ACC=1 go1.23.3 test ./internal/service/ses/... -v -count 1 -parallel 1  -run=TestAccSESReceiptRule_ -timeout 360m
2025/01/10 19:09:47 Initializing Terraform AWS Provider...
=== RUN   TestAccSESReceiptRule_basic
=== PAUSE TestAccSESReceiptRule_basic
=== RUN   TestAccSESReceiptRule_s3Action …
```
=> r/aws_ses_receipt_rule: Retry IAM eventual consistency errors

.ci/semgrep/acctest/checks/arn.go, .ci/semgrep/acctest/checks/arn.yml, GNUmakefile, internal/acctest/arn.go, internal/service/amp/scraper_test.go, internal/service/amp/workspace_test.go, internal/service/appintegrations/event_integration_test.go, internal/service/backup/framework_test.go, internal/service/backup/report_plan_test.go, internal/service/backup/restore_testing_plan_test.go, internal/service/batch/scheduling_policy_test.go, internal/service/chimesdkvoice/sip_media_application_test.go, internal/service/cloudfront/key_value_store_test.go, internal/service/cloudfront/vpc_origin_test.go, internal/service/cloudtrail/organization_delegated_admin_account_test.go, internal/service/codeguruprofiler/profiling_group_test.go, internal/service/configservice/aggregate_authorization_test.go
Reduce uses of `resource.TestCheckResourceAttrSet` on ARN attributes in favour of explicit checks
Addresses `b` and most of the `c` services
=> testing: Reduce uses of `resource.TestCheckResourceAttrSet` with ARN attributes: `b` and `c` services

ROADMAP.md
Pull request 40877 fixed an issue with the wrong year in the roadmap, but not all references were updated. Only a heading changed.
This pull requests updates two locations in the roadmap that also references the year 2024 instead of 2025.
[PR 40877](https://github.com/hashicorp/terraform-provider-aws/pull/40877)
Not applicable
=> fix: update year in ROADMAP

internal/service/lambda/function.go
This fixes a small typo in error messages (missing the second `a` of `awaiting`):
```
╷
│ Error: awiting for Lambda Function (******) create: unexpected state 'Failed', wanted target 'Active'. last error: InternalError: Error while creating lambda: 
│ 
│   with module.******.aws_lambda_function.this,
│   on main.tf line 66, in resource "aws_lambda_function" "this":
│   66: resource "aws_lambda_function" "this" {
│ 
╵
```
Edit: switched to `waiting` for sake of consistency
=> fix(typo): fixes typo in "awiting for Lambda Function" message

website/docs/r/dataexchange_data_set.html.markdown
In #40871 an issue related to the resource `aws_dataexchange_data_set` is described. The user followed the import instructions available in the [official documentation](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/dataexchange_data_set#import) and ran into an issue.
The pull requests updates the import instructions, so that imports can be executed successfully.
In the documentation it is stated that the resource ARN should be used when importing, e.g.
```shell
terraform import aws_dataexchange_data_set.datashare arn:aws:dataexchange:eu-west-1:123456789012:data-sets/3e2a5bd133cf6247a3198410370444f6
```
This leads to a failed import and also validation error messages (likely from the AWS Go SDK). 
I tried similar import with debug logs enabled:
```plain …
```
=> docs: update import instructions for aws_dataexchange_data_set

.changelog/40882.txt, internal/service/sagemaker/endpoint_configuration.go, internal/service/sagemaker/endpoint_configuration_test.go
Closes #40606
```console
% make testacc TESTS=TestAccSageMakerEndpointConfiguration_productionVariantsManagedInstanceScaling PKG=sagemaker
--- PASS: TestAccSageMakerEndpointConfiguration_productionVariantsManagedInstanceScalingZero (26.61s)
--- PASS: TestAccSageMakerEndpointConfiguration_productionVariantsManagedInstanceScaling (30.29s)
```
=> r/sagemaker_endpoint_configuration - allow scaling endpoints to zero

internal/generate/servicepackage/main.go, internal/service/apigateway/account.go, internal/service/apigateway/service_package_gen.go, internal/service/auditmanager/account_registration.go, internal/service/auditmanager/assessment_delegation.go, internal/service/auditmanager/assessment_report.go, internal/service/auditmanager/framework_share.go, internal/service/auditmanager/organization_admin_account_registration.go, internal/service/auditmanager/service_package_gen.go, internal/service/elasticache/reserved_cache_node.go, internal/service/elasticache/service_package_gen.go, internal/service/medialive/multiplex_program.go, internal/service/medialive/service_package_gen.go, internal/service/rds/export_task.go, internal/service/rds/service_package_gen.go, internal/service/simpledb/domain.go, internal/service/simpledb/service_package_gen.go
Enforce setting a friendly name for every ephemeral resource declared with the `@EphemeralResource` annotation and resource declared with the `@FrameworkResource` annotation.
Backfill those resources that were missing such a value.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/40917.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/40913.
=> Tech debt: Require `name=` value for `@EphemeralResource` and `@FrameworkResource` annotations

.changelog/40918.txt, internal/service/route53/health_check.go, internal/service/route53/health_check_test.go, website/docs/r/route53_health_check.html.markdown
This argument will allow for the health check to be synchronized with the upstream CloudWatch alarm when changes are made.
```console
% make testacc PKG=route53 TESTS=TestAccRoute53HealthCheck_triggers
TF_ACC=1 go1.23.3 test ./internal/service/route53/... -v -count 1 -parallel 20 -run='TestAccRoute53HealthCheck_triggers'  -timeout 360m -vet=off
2025/01/14 10:39:47 Initializing Terraform AWS Provider...
--- PASS: TestAccRoute53HealthCheck_triggers (23.64s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/route53    28.800s
```
Closes #29251
- https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/health-checks-updating-cloudwatch-alarm-settings.html
```console
% …
```
=> r/aws_route53_health_check: add `triggers` argument

.changelog/40794.txt, internal/service/elasticache/cluster.go, internal/service/elasticache/user.go, internal/service/elasticache/user_group.go, internal/service/elasticache/user_test.go, website/docs/r/elasticache_user.html.markdown, website/docs/r/elasticache_user_group.html.markdown
From what I can tell, the name isn't case sensitive, and even if you set it with the uppercase version, AWS will return the lowercase version (and the diff was already case-insensitive).
=> feat(elasticache): Make engine name case insensitive for user and user_group

.changelog/40910.txt, internal/service/kafka/cluster.go, internal/service/kafka/cluster_test.go
This change includes two fixes for the `broker_node_group_info.0.storage_info.0.ebs_storage_info.0.provisioned_throughput` block:
1. The update method now includes logic to handle the case where the block previously existed but has been removed. Removal will cause the nested `enabled` value to be set to `false` in the call to the Update API, disabling provisioned throughput.
2. Differences between an unset `provisioned_throughput` block and the default value returned from AWS (a nested block with `enabled` set to `false`) will now be suppressed. This should prevent perpetual differences in configurations which choose to omit this block to disable it.
```console
% make testacc PKG=kafka TESTS=TestAccKafkaCluster_BrokerNodeGroupInfo_StorageInfo_
==> …
```
=> r/aws_msk_cluster: fix `provisioned_throughput` block update behavior

.changelog/40927.txt, internal/service/apprunner/vpc_ingress_connection.go, internal/service/apprunner/vpc_ingress_connection_test.go
This pull request addresses the mentioned issue by ensuring that changes to the service_arn attribute of the `aws_apprunner_vpc_ingress_connection` resource trigger a recreation of the resource. This is achieved by setting `ForceNew: true` on the `service_arn` schema definition.
Additionally, a new acceptance test `TestAccAppRunnerVPCIngressConnection_serviceARNChange` has been added to verify that the resource is recreated when the `service_arn` changes.
Closes #40896 
```console
% make testacc P=3 TESTS=TestAccAppRunnerVPCIngressConnection_ PKG=apprunner
TF_ACC=1 go test ./internal/service/apprunner/... -v -count 1 -parallel 3 -run='TestAccAppRunnerVPCIngressConnection_'  -timeout 360m …
```
=> [Bug]: AWS Apprunner Vpc Ingress Connection recreate upon service arn modification

.changelog/40210.txt, internal/service/ec2/ec2_ami.go, internal/service/ec2/ec2_ami_copy.go, internal/service/ec2/ec2_ami_data_source.go, internal/service/ec2/ec2_ami_from_instance.go, website/docs/d/ami.html.markdown, website/docs/r/ami.html.markdown
This PR provides support to use UEFI secure boot with `terraform-provider-aws`.
Closes #40094
The requirement originates from enabling UEFI secure boot with custom config and keys. See https://github.com/gardenlinux/gardenlinux/issues/2472
=> Add support for UEFI data

.changelog/40969.txt, internal/service/elasticache/serverless_cache.go, internal/service/elasticache/serverless_cache_test.go
When modifying and `aws_elasticache_serverless_cache` the resource can sometimes throw the following error due all parameters being passed to the update:
```console
% make testacc TESTARGS='-run=TestAccElastiCacheServerlessCache_redisUpdateWithUserGroup' PKG=elasticache
TF_ACC=1 go1.23.3 test ./internal/service/elasticache/... -v -count 1 -parallel 20  -run=TestAccElastiCacheServerlessCache_redisUpdateWithUserGroup -timeout 360m -vet=off
2025/01/16 09:43:53 Initializing Terraform AWS Provider...
=== RUN   TestAccElastiCacheServerlessCache_redisUpdateWithUserGroup
=== PAUSE TestAccElastiCacheServerlessCache_redisUpdateWithUserGroup
=== CONT …
```
=> r/elasticache_serverless_cache: fix modify error using autoflex

website/docs/r/rds_global_cluster.html.markdown
Modify the  `rds_global_cluster` examples to include an ignore of  `replication_source_identifier`.
The `aws_rds_cluster` docs note that this must be ignored for the secondary cluster. 
Without this any additional run after the initial one will promote the secondary instance to a standalone instance. 
>[replication_source_identifier](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/rds_cluster#replication_source_identifier-3) - (Optional) ARN of a source DB cluster or DB instance if this DB cluster is to be created as a Read Replica. Note: Removing this attribute after creation will promote the read replica to a standalone cluster. If DB Cluster is part of a Global Cluster, use the [lifecycle configuration block ignore_changes …
=> rds_global_cluster: Ensure replication_source_identifier changes ignored on secondary

website/docs/r/vpc_ipv6_cidr_block_association.html.markdown
For the resource [`aws_vpc_ipv6_cidr_block_association` ](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/vpc_ipv6_cidr_block_association.html) the attributes
* ipv6_ipam_pool_id
* ipv6_pool
* ipv6_netmask_length
do contain details on possible attribute conflict. The details in the current documentation are not correct and updated by this pull request.
One example from the current documentation:
> [ipv6_pool](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/vpc_ipv6_cidr_block_association.html#ipv6_pool-1) - (Optional) The ID of an IPv6 address pool from which to allocate the IPv6 CIDR block. Conflicts with ipv6_pam_pool_id, ipv6_pool.
Here the attribute `ipv6_pool` is in conflict with itself.
Closes #40977 
- [Schema definition for …
=> docs: update conflict details for ipv6 cidr block association

website/docs/r/wafv2_web_acl_logging_configuration.html.markdown
Update valid values of `action` property of WAFv2 logging configuration. Added missing values from [aws-sdk-go-v2](https://github.com/aws/aws-sdk-go-v2/blob/7ea97e576564775a287646a2b992f7b31a48b785/service/wafv2/types/enums.go#L8-L15): CAPTCHA, CHALLENGE, and EXCLUDED_AS_COUNT.
Closes #40978
- https://docs.aws.amazon.com/waf/latest/APIReference/API_ActionCondition.html
- https://github.com/aws/aws-sdk-go-v2/blob/7ea97e576564775a287646a2b992f7b31a48b785/service/wafv2/types/enums.go#L8-L15
```console
% make testacc TESTS=TestAccXXX PKG=wafv2
TF_ACC=1 go1.23.3 test ./internal/service/wafv2/... -v -count 1 -parallel 20 -run='TestAccXXX'  -timeout 360m -vet=off
2025/01/17 14:43:25 Initializing …
```
=> fix(doc): update valid values for action property of wafv2 logging configuration

website/docs/r/cognito_user_pool_client.html.markdown
In the documentation for the resource [`aws_cognito_user_pool_client`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cognito_user_pool_client) the option  `ALLOW_USER_AUTH` for the argument [`explicit_auth_flows`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cognito_user_pool_client#explicit_auth_flows-1) is missing.
This PR adds the missing option and also formats the options for the argument `explicit_auth_flows` as `code`.
Closes #41028 
* [AWS Go SDK v2 release v1.47.0](https://github.com/aws/aws-sdk-go-v2/releases/tag/release-2024-11-22) containing the new flow, release 22 Nov 2024
* [Validation in provider source code](https://github.com/hashicorp/terraform-provider-aws/blob/1043db5c182e08c339273be64ef5233cad114064/internal …
=> docs: add missing explicit auth flow option for cognito user pool client

.changelog/41042.txt, internal/service/ec2/vpc_endpoint_security_group_association.go, internal/service/ec2/vpc_endpoint_security_group_association_test.go, website/docs/r/vpc_endpoint_security_group_association.html.markdown
This PR is to add support for importing `aws_vpc_endpoint_security_group_association` resources.
Closes #41039
n/a
```console
$ make testacc TESTS=TestAccVPCEndpointSecurityGroupAssociation_ PKG=ec2
TF_ACC=1 go1.23.3 test ./internal/service/ec2/... -v -count 1 -parallel 20 -run='TestAccVPCEndpointSecurityGroupAssociation_'  -timeout 360m -vet=off
2025/01/22 23:45:03 Initializing Terraform AWS Provider...
=== RUN   TestAccVPCEndpointSecurityGroupAssociation_basic
=== PAUSE TestAccVPCEndpointSecurityGroupAssociation_basic
=== RUN   TestAccVPCEndpointSecurityGroupAssociation_disappears
=== PAUSE TestAccVPCEndpointSecurityGroupAssociation_disappears
=== RUN …
```
=> feat: Support resource import for aws_vpc_endpoint_security_group_association

.changelog/41043.txt, internal/service/pinpoint/email_channel.go, internal/service/pinpoint/email_channel_test.go, website/docs/r/pinpoint_email_channel.html.markdown
This PR is to add the `orchestration_sending_role_arn` argument to the `aws_pinpoint_email_channel` resource.
Closes #40947
Referred to [Email Channel](https://docs.aws.amazon.com/pinpoint/latest/apireference/apps-application-id-channels-email.html#apps-application-id-channels-email-properties) for specs and wordings.
```console
$ make testacc TESTS=TestAccPinpointEmailChannel_ PKG=pinpoint
TF_ACC=1 go1.23.3 test ./internal/service/pinpoint/... -v -count 1 -parallel 20 -run='TestAccPinpointEmailChannel_'  -timeout 360m -vet=off
2025/01/23 00:22:28 Initializing Terraform AWS Provider...
=== RUN   TestAccPinpointEmailChannel_basic
=== PAUSE TestAccPinpointEmailChannel_basic
=== RUN …
```
=> feat: Add orchestration_sending_role_arn arg for aws_pinpoint_email_channel

.changelog/41012.txt, internal/service/mediaconvert/queue.go, internal/service/mediaconvert/queue_test.go, website/docs/r/media_convert_queue.html.markdown
This PR is for adding the `concurrent_jobs` argument to the `aws_media_convert_queue` resource. However, there are a few issues I found that would affect some edge cases:
1. The default value is different per region, so one cannot be set. 
2. The API does not allow un-setting `concurrent_jobs`, so removing it from the configuration and applying would simply retain the custom value.
3. The API returns a quota exception as a 429 error, leading to a long wait as it falls under the standard retry mechanism. I think this is a mis-categorization of the error at the AWS API level, so I will open a separate issue and an AWS support ticket to track it. But for now, if the provided concurrent job value exceeds the quota limit, it will only fail after an hour.
Closes #41003
Referred to …
=> feat: Add concurrent_jobs arg for aws_media_convert_queue

.changelog/41059.txt, internal/service/organizations/account.go, website/docs/r/organizations_account.html.markdown
This PR is to add configurable timeouts for create and delete to the `aws_organizations_account` resource. Based on the problem description in 40894, I also increased the default timeout from 5 minutes to 10 minutes, which hopefully will cover the general use cases.
**Note:** that I do not have a management account where I can freely create and close accounts. I would thus need assistance from a maintainer to help run the resource test cases. Thank you.
Closes #40894
n/a
TBD - I need help with running these tests in a management account!
=> feat: Add configurable timeouts to aws_organizations_account

website/docs/d/lambda_invocation.html.markdown
This PR is to add a note that explains when the `aws_lambda_function` will invoke the Lambda function, which is on the first apply and every subsequent plan.
Closes #41051
Referred to [Ephemeral: aws_lambda_invocation](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/ephemeral-resources/lambda_invocation) for similar wordings.
n/a
=> docs: Clarify when the Lambda function is invoked for the aws_lambda_function data source

website/docs/r/budgets_budget.html.markdown
- Add details on expected keys to the [_Cost Filter_](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/budgets_budget) section. 
- Update one resource tag  example with real world values, so that the usage of AWS/ user created cost allocation tags is displayed.
- Minor updates (lower case/ upper case)   
Closes #40987 
(title of the issue is misleading)
- [Resource documentation](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/budgets_budget)
=> docs: update cost filter example and description in aws_budgets_budget

.ci/.golangci4.yml, internal/service/workspaces/ip_group_test.go
This PR is to remove the remaining use of deprecated function `strings.Title` and the associated linter exclusion.
Closes #30321
n/a
```console
$ make testacc TESTS=TestAccWorkSpaces_serial/IpGroup/ PKG=workspaces
TF_ACC=1 go1.23.3 test ./internal/service/workspaces/... -v -count 1 -parallel 20 -run='TestAccWorkSpaces_serial/IpGroup/'  -timeout 360m -vet=off
2025/01/26 16:59:03 Initializing Terraform AWS Provider...
=== RUN   TestAccWorkSpaces_serial
=== PAUSE TestAccWorkSpaces_serial
=== CONT  TestAccWorkSpaces_serial
=== RUN   TestAccWorkSpaces_serial/IpGroup
=== RUN   TestAccWorkSpaces_serial/IpGroup/basic
=== RUN   TestAccWorkSpaces_serial/IpGroup/disappears
=== RUN …
```
=> chore: Remove reamining use of deprecated strings.Title function and its linter exclusion

.goreleaser.yml
Fixes goreleaser error: https://github.com/hashicorp/terraform-provider-aws/actions/runs/12956906005/job/36144213625.
```
Run goreleaser/goreleaser-action@9ed2f89a662bf1735a48bc8557fd212fa902bebf
with:
args: check
distribution: goreleaser
version: ~> v[2](https://github.com/hashicorp/terraform-provider-aws/actions/runs/12956906005/job/36144213625#step:5:2)
workdir: .
install-only: false
Downloading https://github.com/goreleaser/goreleaser/releases/download/v2.6.1/goreleaser_Linux_x86_64.tar.gz
Extracting GoReleaser
/usr/bin/tar xz --warning=no-unknown-keyword --overwrite -C /home/runner/work/_temp/8dd0f82d-0[3](https://github.com/hashicorp/terraform-provider-aws/actions/runs/12956906005/job/36144213625#step:5:3)a1-4470-a496-dbdfbf05f21[4](https://github.com/hashicorp/terraform-provider-aws …
```
=> Tech debt: Fix `goreleaser` error `• DEPRECATED: archives.format should not be used any more`

.changelog/41072.txt, internal/acctest/configs.go, internal/service/bedrockagent/knowledge_base.go, internal/service/bedrockagent/knowledge_base_test.go, website/docs/r/bedrockagent_knowledge_base.html.markdown
This PR is to fix an issue with the `aws_bedrockagent_knowledge_base` resource where updating the `role_arn` argument would force new resource creation despite direct update is supported. The resource documentation is also incorrect on specifying which arguments would force new resources, so it is being fixed in this PR as well.
**Note:** For development I use a Windows machine with git bash, and the test cases are failing when running the `local-exec` commands in `null_resource.db_setup`. I had to add `interpreter = ["bash", "-c"]` temporarily just to get the commands to run with bash instead of cmd. I am not sure if adding the `interpreter` argument would break things, so I decided to leave it out of the test config for now.
Closes #41024
Referred to …
=> fix: Don't force new resource on role_arn update for aws_bedrockagent_knowledge_base

.changelog/41082.txt, internal/service/pipes/pipe.go, internal/service/pipes/pipe_test.go, website/docs/r/pipes_pipe.html.markdown
This PR is to add the `kms_key_identifier` argument to the `aws_pipes_pipe` resource.
Closes #39288
Referred to [CreatePipe](https://docs.aws.amazon.com/eventbridge/latest/pipes-reference/API_CreatePipe.html) for specs and wordings.
```console
$ make testacc "TESTS=TestAccPipesPipe_basicSQS|TestAccPipesPipe_kmsKeyIdentifier" PKG=pipes
TF_ACC=1 go1.23.3 test ./internal/service/pipes/... -v -count 1 -parallel 20 -run='TestAccPipesPipe_basicSQS|TestAccPipesPipe_kmsKeyIdentifier'  -timeout 360m -vet=off
2025/01/25 23:29:01 Initializing Terraform AWS Provider...
=== RUN   TestAccPipesPipe_basicSQS
=== PAUSE TestAccPipesPipe_basicSQS
=== RUN   TestAccPipesPipe_kmsKeyIdentifier
=== PAUSE …
```
=> feat: Add kms_key_identifier arg for aws_pipes_pipe

.changelog/41084.txt, internal/service/ec2/transitgateway_vpc_attachment.go, internal/service/ec2/transitgateway_vpc_attachment_data_source.go, internal/service/ec2/transitgateway_vpc_attachment_data_source_test.go, internal/service/ec2/transitgateway_vpc_attachment_test.go, website/docs/d/ec2_transit_gateway_vpc_attachment.html.markdown, website/docs/r/ec2_transit_gateway_vpc_attachment.html.markdown
The PR is to add the (calculated) `arn` attribute to the `aws_ec2_transit_gateway_vpc_attachment` resource and data source.
Relates #40923 (partly resolves it)
Referred to ARN format in [Actions, resources, and condition keys for Amazon EC2](https://docs.aws.amazon.com/service-authorization/latest/reference/list_amazonec2.html#amazonec2-transit-gateway-attachment) as referenced in the original GitHub issue.
For the `aws_ec2_transit_gateway_vpc_attachment` resource:
```console
$ make testacc TESTS=TestAccTransitGateway_serial/VpcAttachment_basic PKG=ec2
TF_ACC=1 go1.23.3 test ./internal/service/ec2/... -v -count 1 -parallel 20 -run='TestAccTransitGateway_serial/VpcAttachment_basic' …
```
=> feat: Add arn attribute to aws_ec2_transit_gateway_vpc_attachment resource and data source

.changelog/41111.txt, internal/service/rds/cluster_test.go, internal/service/rds/consts.go
There is a new value `instance` for aurora-postgresql that is accepted in the `enabled_cloudwatch_logs_exports` field. It looks like this is currently being rolled out and is only available in some regions (can be tested in `us-west-2`).
**Output from Acceptance Testing**
```
% make testacc TESTS=TestAccRDSCluster_EnabledCloudWatchLogsExports_aurora_postgresql_instance PKG=rds
TF_ACC=1 go1.23.3 test ./internal/service/rds/... -v -count 1 -parallel 20 -run='TestAccRDSCluster_EnabledCloudWatchLogsExports_aurora_postgresql_instance'  -timeout 360m -vet=off
2025/01/27 15:05:24 Initializing Terraform AWS Provider...
=== RUN   TestAccRDSCluster_EnabledCloudWatchLogsExports_aurora_postgresql_insta …
```
=> fix(rds): cluster enabled_cloudwatch_logs_exports doesn't allow instance

.changelog/41087.txt, internal/service/ec2/transitgateway_peering_attachment.go, internal/service/ec2/transitgateway_peering_attachment_data_source.go, internal/service/ec2/transitgateway_peering_attachment_data_source_test.go, internal/service/ec2/transitgateway_peering_attachment_test.go, website/docs/d/ec2_transit_gateway_peering_attachment.html.markdown, website/docs/r/ec2_transit_gateway_peering_attachment.html.markdown
The PR is to add the (calculated) `arn` attribute to the `aws_ec2_transit_gateway_peering_attachment` resource and data source.
Closes #40923 (along with #41084 and #41086)
Referred to ARN format in [Actions, resources, and condition keys for Amazon EC2](https://docs.aws.amazon.com/service-authorization/latest/reference/list_amazonec2.html#amazonec2-transit-gateway-attachment) as referenced in the original GitHub issue.
For the `aws_ec2_transit_gateway_peering_attachment` resource:
```console
$ make testacc TESTS=TestAccTransitGateway_serial/PeeringAttachment_basic PKG=ec2
TF_ACC=1 go1.23.3 test ./internal/service/ec2/... -v -count 1 -parallel 20 …
```
=> feat: Add arn attribute to aws_ec2_transit_gateway_peering_attachment resource and data source

.changelog/41086.txt, internal/service/ec2/transitgateway_dx_gateway_attachment_data_source.go, internal/service/ec2/transitgateway_dx_gateway_attachment_data_source_test.go, website/docs/d/ec2_transit_gateway_dx_gateway_attachment.html.markdown
The PR is to add the (calculated) `arn` attribute to the `aws_ec2_transit_gateway_dx_gateway_attachment` data source.
Relates #40923 (partly resolves it)
Referred to ARN format in [Actions, resources, and condition keys for Amazon EC2](https://docs.aws.amazon.com/service-authorization/latest/reference/list_amazonec2.html#amazonec2-transit-gateway-attachment) as referenced in the original GitHub issue.
```console
$ make testacc TESTS=TestAccTransitGatewayDataSource_serial/DxGatewayAttachment PKG=ec2
TF_ACC=1 go1.23.3 test ./internal/service/ec2/... -v -count 1 -parallel 20 -run='TestAccTransitGatewayDataSource_serial/DxGatewayAttachment'  -timeout 360m -vet=off
2025/01/26 15:04:30 …
```
=> feat: Add arn attribute to aws_ec2_transit_gateway_dx_gateway_attachment data source

.changelog/41081.txt, internal/service/ecs/task_definition_data_source.go, internal/service/ecs/task_definition_data_source_test.go, website/docs/d/ecs_task_definition.html.markdown
This PR is to add the missing attributes (compared to the resource) for the `aws_ecs_task_definition` data source.
Note that unit tests depend on #41078 because it needs the `enable_fault_injection` argument in the resource. 
Closes #40214
Referred to [TaskDefinition](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_TaskDefinition.html) for specs and wordings.
```console
$ make testacc TESTS="TestAccECSTaskDefinitionDataSource_" PKG=ecs
TF_ACC=1 go1.23.3 test ./internal/service/ecs/... -v -count 1 -parallel 20 -run='TestAccECSTaskDefinitionDataSource_'  -timeout 360m -vet=off
2025/01/25 21:01:42 Initializing Terraform AWS Provider...
=== RUN …
```
=> feat: Add missing attributes to aws_ecs_task_definition data source

.changelog/41096.txt, internal/service/dms/task_settings_json.go, internal/service/dms/task_settings_json_test.go
The task setting validation has no proper type assertion what results into broken plan change when the types cannot be converted (or do not match):
```
╷
│ Error: Request cancelled
│ 
│   with module.database_migration_service.aws_dms_replication_task.this["cdc_ex"],
│   on .terraform/modules/database_migration_service/main.tf line 386, in resource "aws_dms_replication_task" "this":
│  386: resource "aws_dms_replication_task" "this" {
│ 
│ The plugin.(*GRPCProvider).PlanResourceChange request was cancelled.
╵
Stack trace from the terraform-provider-aws_v5.84.0_x5 plugin:
panic: interface conversion: interface {} is float64, not string
goroutine 510 [running]:
github.com/hashicorp/terraform-provider-aws/internal/service/dms.taskSettingsEqual({0x17942720?, 0xc003096680?}, {0x17942ae0?, …
```
=> fix: `aws_dms_replication_task` - type assertion to avoid nil pointer panics

.changelog/41105.txt, internal/service/opensearchserverless/collection_data_source.go, internal/service/opensearchserverless/service_package_gen.go, website/docs/d/opensearchserverless_collection.html.markdown
The `created_date` and `last_modified_date` attributes are string types, while the AWS data structure represents these fields in Unix time as `int64` pointers. The mismatch between types resulted in AutoFlex diagnostic errors being printed to stdout, despite the custom handling being present on the Read method to covert Unix time to an RFC3339 formatted string. This change adds an option to ignore these fields during the flatten operation to prevent errant error logs.
```
2025-01-27T11:41:39.949-0500 [ERROR] aws.autoflex: AutoFlex Flatten; incompatible types: autoflex.source.type="*int64" tf_rpc=ReadDataSource tf_provider_addr=registry.terraform.io/hashicorp/aws tf_req_id=440f6267-4953-4dbb-2934-fc20eece0f95 tf_mux_provider="*proto5server.Server" autoflex.target.path=CreatedDate …
```
=> d/aws_opensearch_serverless_collection: fix autoflex failure

.changelog/37885.txt, CHANGELOG.md
Adds missing CHANGELOG entries from prior v5.x.y release (malformed entries -- "`" or "``").
Correct CHANGELOG entry for unreleased new resource.
Relates #37885.
Relates #37255.
Relates #39478.
Relates #39353.
Relates #34931.
=> Missing CHANGELOG entries

website/docs/r/db_instance.html.markdown
- Update details for `max_allocated_storage` to provide clearer behaviour on Storage Autoscaling
Closes #41063
[Reference documentation](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/db_instance)
=> [docs]: update details for max allocated storage

.changelog/41168.txt, .ci/.golangci4.yml, internal/service/cloudtrail/cloudtrail_test.go, internal/service/cloudtrail/trail.go, internal/service/cloudtrail/trail_test.go, website/docs/r/cloudtrail.html.markdown
This PR is to add the `sns_topic_arn` attribute to the `aws_cloudtrail` resource. Also the `sns_topic_name` argument, which is a deprecated API response field but still a valid request field interestingly, is derived from `sns_topic_arn` on read. Lastly the linter exclusion rule for deprecated field is removed.
Closes #30329
Referred to [CreateTrail](https://docs.aws.amazon.com/awscloudtrail/latest/APIReference/API_CreateTrail.html) for specs and wordings.
```console
$ make testacc TESTS="TestAccCloudTrail_serial/Trail/basic|TestAccCloudTrail_serial/Trail/snsTopicName" PKG=cloudtrail
TF_ACC=1 go1.23.5 test ./internal/service/cloudtrail/... -v -count 1 -parallel 20 …
```
=> feat: Add sns_topic_arn attr to aws_cloudtrail

.changelog/41163.txt, internal/service/macie2/invitation_accepter.go
This fixes a regression introduced during migration of the `macie2` service to AWS SDK V2. Specifically, the `invitationID` variable inside the create retrier shadows a variable of the same name at the root of the create function. This led to the `InvitationId` value always being sent as an empty string in the `AcceptInvitation` API request, despite being successfully retrieved from the `ListInvitations` API. The variable from the outer scope is now used inside the retrier's scope (rather than a new variable), which should return the original intended behavior.
Closes #40587
Relates #37999
> [!NOTE]
> Acceptance tests for this resource require out of band email verification for the Macie2 service, which maintainers do not currently have the capability to do in our testing accounts. As …
=> r/aws_macie2_invitation_accepter: properly set `invitation_id` during creation

.ci/semgrep/acctest/checks/arn.yml, internal/service/kafka/replicator_test.go, internal/service/kafka/vpc_connection_test.go, internal/service/kafkaconnect/connector_test.go, internal/service/kafkaconnect/custom_plugin_test.go, internal/service/kafkaconnect/worker_configuration_test.go, internal/service/kendra/index_test.go, internal/service/kinesis/stream_data_source_test.go, internal/service/kinesis/stream_test.go, internal/service/kinesisvideo/stream_test.go, internal/service/lexmodels/bot_alias_test.go, internal/service/lexmodels/bot_test.go, internal/service/lexmodels/intent_test.go, internal/service/lightsail/container_service_test.go, internal/service/lightsail/database_test.go, internal/service/lightsail/key_pair_test.go, internal/service/medialive/input_security_group_test.go, internal/service/medialive/input_test.go, internal/service/medialive/medialive_test.go, internal/service/medialive/multiplex_test.go, internal/service/memorydb/multi_region_cluster_test.go
Reduce uses of `resource.TestCheckResourceAttrSet` on ARN attributes in favour of explicit checks
Addresses `k` through `m` services
=> testing: Reduce uses of `resource.TestCheckResourceAttrSet` with ARN attributes: `k` to `m` services

.ci/semgrep/acctest/checks/arn.yml, internal/service/oam/link_data_source_test.go, internal/service/oam/link_test.go, internal/service/oam/links_data_source_test.go, internal/service/oam/sink_data_source_test.go, internal/service/oam/sink_policy_test.go, internal/service/oam/sink_test.go, website/docs/d/oam_link.html.markdown, website/docs/d/oam_sink.html.markdown, website/docs/r/oam_link.html.markdown, website/docs/r/oam_sink.html.markdown, website/docs/r/oam_sink_policy.html.markdown
Reduce uses of `resource.TestCheckResourceAttrSet` on ARN attributes in favour of explicit checks.
Also:
* replaces use of `id` in acceptance tests and documentation with `arn`
* adds `depends_on` relationship with `aws_oam_sink_policy` to prevent intermittent failures
=> testing: Reduce uses of `resource.TestCheckResourceAttrSet` with ARN attributes: `oam`

.changelog/41192.txt, internal/service/rekognition/project.go, internal/service/rekognition/project_test.go, internal/service/rekognition/service_package_gen.go, website/docs/r/rekognition_project.html.markdown
This PR is to add tagging support to the `aws_rekognition_project` resource.
Closes #41102
Referred to [CreateProject](https://docs.aws.amazon.com/rekognition/latest/APIReference/API_CreateProject.html) for specs.
```console
$ make testacc TESTS=TestAccRekognitionProject_ PKG=rekognition
TF_ACC=1 go1.23.5 test ./internal/service/rekognition/... -v -count 1 -parallel 20 -run='TestAccRekognitionProject_'  -timeout 360m -vet=off
2025/02/02 16:08:18 Initializing Terraform AWS Provider...
=== RUN   TestAccRekognitionProject_basic
=== PAUSE TestAccRekognitionProject_basic
=== RUN   TestAccRekognitionProject_ContentModeration
=== PAUSE TestAccRekognitionProject_ContentModeration
=== RUN …
```
=> feat: Add tagging support for aws_rekognition_project

website/docs/r/wafv2_web_acl.html.markdown
Update  the documentation of the resource `aws_wafv2_web_acl` by changing `identifier` to `identifiers` in the blocks `address_fields` and `phone_number_fields`.
This is required to match the implementation of the resource. The section References contains links to the relevant lines in the source code.
Closes #41182 
References in provider source code
- [`identifiers` in `address_fields`](https://github.com/hashicorp/terraform-provider-aws/blob/2a3e17f26ff3aaac571448c11e99aecd0d230219/internal/service/wafv2/schemas.go#L1378)
- [`identifiers` in `phone_number_fields`](https://github.com/hashicorp/terraform-provider-aws/blob/2a3e17f26ff3aaac571448c11e99aecd0d230219/internal/service/wafv2/schemas.go#L1427)
=> docs: fix argument names for resource aws_wafv2_web_acl

website/docs/r/cognito_managed_user_pool_client.html.markdown
This PR improve the example usages and descriptions of the `name_pattern` and `name_prefix` arguments for the `aws_cognito_managed_user_pool_client` resources.
Closes #40488
n/a
n/a
=> docs: Clarify usage of name_pattern and name_prefix args for aws_cognito_managed_user_pool_client

.changelog/41186.txt, internal/service/iam/server_certificate.go, internal/service/iam/server_certificate_test.go, website/docs/r/iam_server_certificate.html.markdown
This PR is to allow updating the `name`, `name_prefix`, and `path` arguments of the `aws_iam_server_certificate` resource without force creating a new one.
Note that there is still one limitation, where you cannot update the resource with both `name` and `name_prefix` set to null to change to a fully-generated name. Since both of these arguments are optional + computed, the plan will simply detect no changes.
As well, there is an account-level quota limit on 20 IAM server certificates. You'll either have to request for a quota increase (which I did, to 40) or set `-parallel` to a smaller number than 20.
Closes #37479
Referred to [UpdateServerCertificate](https://docs.aws.amazon.com/IAM/latest/APIReference/API_UpdateServerCertificate.html) for specs and wordings.
```console
$ make testacc …
```
=> fix: Allow name, name_prefix_and path update for aws_iam_server_certificate

.changelog/41187.txt, internal/service/cognitoidp/identity_provider.go, internal/service/cognitoidp/identity_provider_test.go, internal/service/cognitoidp/user_group_test.go, internal/service/cognitoidp/user_pool_client_test.go, internal/service/cognitoidp/validate.go, internal/service/cognitoidp/validate_test.go
This PR fixes the string length validation logic to account for UTF-8 characters for the following resources and argument:
- For `aws_cognito_identity_provider`, the `provider_name` argument
- For `aws_cognito_user_group`, the `name` argument
- For `aws_cognito_user_pool_client`, the `callback_urls`, `default_redirect_uri`, `logout_urls`, and `supported_identity_providers` arguments
Closes #41171
Referred to [CreateIdentityProvider](https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_CreateIdentityProvider.html), [CreateGroup](https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_CreateGroup.html) , and [CreateUserPoolClient](https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_CreateUserPoolClient.html) for …
=> fix: Fix string length checks for UTF-8 fields for aws_cognito_identity_provider, aws_cognito_user_group, and aws_cognito_user_pool_client

.changelog/41232.txt, internal/service/sqs/attribute_funcs.go, internal/service/sqs/consts.go, internal/service/sqs/queue.go, internal/service/sqs/queue_test.go, website/docs/r/sqs_queue.html.markdown
There are concerns that long timeouts cause problems because mistakes take too long to surface. This is a note and constant being removed with this PR:
```go
// Maximum amount of time to wait for SQS queue attribute changes to propagate
// This timeout should not be increased without strong consideration
// as this will negatively impact user experience when configurations
// have incorrect references or permissions.
// Reference: https://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_SetQueueAttributes.html
queueAttributePropagationTimeout = 2 * time.Minute
```
The trouble is that SQS seems to vary from region to region, partition to partition, and account to account. Some accounts cannot create a queue within 2 minutes with `kms_data_key_reuse_period_seconds` set in …
=> aws_sqs_queue: Add customizable timeouts

website/docs/r/sqs_queue.html.markdown, website/docs/r/sqs_queue_policy.html.markdown
Closes #29497
```console
...
```
=> `aws_sqs_queue` and `aws_sqs_queue_policy`: Add warning and clean up docs

internal/flex/write_only.go, internal/flex/write_only_test.go
add flex functions to simplify getting write-only attributes from config
```console
% go test -count=1 -v ./internal/flex/... -run='TestGetWriteOnly'
=== RUN   TestGetWriteOnlyValue
=== PAUSE TestGetWriteOnlyValue
=== RUN   TestGetWriteOnlyStringValue
=== PAUSE TestGetWriteOnlyStringValue
=== CONT  TestGetWriteOnlyValue
=== RUN   TestGetWriteOnlyValue/invalid_value_type
=== PAUSE TestGetWriteOnlyValue/invalid_value_type
=== RUN   TestGetWriteOnlyValue/invalid_path
=== CONT  TestGetWriteOnlyStringValue
=== RUN   TestGetWriteOnlyStringValue/valid_value
=== PAUSE TestGetWriteOnlyStringValue/valid_value
=== RUN   TestGetWriteOnlyStringValue/value_empty_string
=== PAUSE TestGetWriteOnlyStringValue/value_empty_string
=== CONT  TestGetWriteOnlyStringValue/valid_value
=== PAUSE …
```
=> flex: add write only flex functions

internal/flex/write_only.go, internal/flex/write_only_test.go
Relates #41255
```console
% go test -count=1 -v ./internal/flex/... -run='TestGetWriteOnlyStringValue'
=== RUN   TestGetWriteOnlyStringValue
=== PAUSE TestGetWriteOnlyStringValue
=== CONT  TestGetWriteOnlyStringValue
=== RUN   TestGetWriteOnlyStringValue/valid_value
=== PAUSE TestGetWriteOnlyStringValue/valid_value
=== RUN   TestGetWriteOnlyStringValue/value_empty_string
=== PAUSE TestGetWriteOnlyStringValue/value_empty_string
=== CONT  TestGetWriteOnlyStringValue/valid_value
=== CONT  TestGetWriteOnlyStringValue/value_empty_string
--- PASS: TestGetWriteOnlyStringValue (0.00s)
--- PASS: TestGetWriteOnlyStringValue/valid_value (0.00s)
--- PASS: TestGetWriteOnlyStringValue/value_empty_string (0.00s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/flex	0.586s
```
=> flex: simplify func signature for string write-only

website/docs/r/backup_selection.html.markdown
The [documentation](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/backup_selection) for the resource `aws_backup_selection` mentions
> [type](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/backup_selection#type-1) - (Required) An operation, such as `StringEquals`, that is applied to a key-value pair used to filter resources in a selection.
Actually `StringEquals` is not correct. It should read `STRINGEQUALS`.
- Relates #41191 
The wrong value was spotted while working on this issue.
- [AWS Provider source code](https://github.com/hashicorp/terraform-provider-aws/blob/5772b4568fdadb632f8769c921864a041f72f166/internal/service/backup/selection.go#L166)  
Here one can see for the argument `type`:
```go
ValidateDiagFunc: …
```
=> docs: fix invalid value for type in resource aws_backup_selection

.changelog/41295.txt, internal/service/ram/principal_association.go, internal/service/sts/caller_identity_data_source.go, internal/service/vpclattice/service_data_source.go, internal/service/vpclattice/service_network_data_source.go, internal/service/vpclattice/service_package_gen.go
Using tags interceptor does not work for these shareable resources since tags cannot be listed for another account. This skips tags when the account is not the same or Access is denied.
Closes #41270 
* Fixes regression in #41019
* Relates #32938 
* Relates #32939 
```console
...
```
=> Fix AccessDeniedError listing tags in aws_vpclattice_service_network, aws_vpclattice_service data sources

.changelog/41304.txt, internal/service/vpclattice/access_log_subscription.go, internal/service/vpclattice/access_log_subscription_test.go, website/docs/r/vpclattice_access_log_subscription.html.markdown
This PR is to add the `service_network_log_type`a argument to the `aws_vpclattice_access_log_subscription` resource.
Closes #41286
Referred to [API_CreateAccessLogSubscription](https://docs.aws.amazon.com/vpc-lattice/latest/APIReference/API_CreateAccessLogSubscription.html) for specs and wordings.
```console
$ make testacc TESTS="TestAccVPCLatticeAccessLogSubscription_" PKG=vpclattice
TF_ACC=1 go1.23.5 test ./internal/service/vpclattice/... -v -count 1 -parallel 20 -run='TestAccVPCLatticeAccessLogSubscription_'  -timeout 360m -vet=off
2025/02/09 21:31:34 Initializing Terraform AWS Provider...
=== RUN   TestAccVPCLatticeAccessLogSubscription_basic
=== PAUSE …
```
=> feat: Add service_network_log_type arg for aws_vpclattice_access_log_subscription

.changelog/41292.txt, internal/service/ec2/transitgateway_route_table_association.go, internal/service/ec2/transitgateway_route_table_association_test.go, internal/service/ec2/transitgateway_test.go, internal/service/ec2/transitgateway_vpc_attachment_accepter_test.go, internal/service/ec2/transitgateway_vpc_attachment_test.go
Previously, we would ForceNew always on changes to `transit_gateway_attachment_id` regardless. However, there are times when the `transit_gateway_attachment_id` is not known because a dependency changes, such as described in #30085, but the `transit_gateway_attachment_id` won't change. In these cases, the resource should not be ForceNew based on the `transit_gateway_attachment_id` change.
Closes #30085
```console
% make t T='TestAccTransitGateway_serial/RouteTableAssociation_' K=ec2            
TF_ACC=1 go1.23.5 test ./internal/service/ec2/... -v -count 1 -parallel 20 -run='TestAccTransitGateway_serial/RouteTableAssociation_'  -timeout 360m -vet=off
2025/02/10 17:03:47 Initializing …
```
=> Avoid recreating aws_ec2_transit_gateway_route_table_association when unnecessary

internal/service/appstream/fleet_test.go, internal/service/appstream/stack_test.go
Fixes `TestAccAppStreamStack_withTags`
Fixes `TestAccAppStreamFleet_multiSession`
```console
% make testacc PKG=appstream TESTS='TestAccAppStreamStack_withTags|TestAccAppStreamFleet_multiSession'
--- PASS: TestAccAppStreamStack_withTags (38.95s)
--- PASS: TestAccAppStreamFleet_multiSession (779.75s)
```
=> Fixes `appstream` test errors

.changelog/41346.txt, internal/service/ec2/vpc_internet_gateway.go, internal/service/ec2/vpc_internet_gateway_test.go
This fixes a regression introduced in `v5.83.0` which caused destruction of the `aws_internet_gateway` resource to exit early if an attempt to detach the internet gateway returned a not found error. Rather than exit early, the operation should just proceed after `NotFound` errors to allow the internet gateway to be deleted.
Also updates the `_Disappears_attachment` acceptance test to delete a standalone attachment out-of-band, rather than the entire internet gateway.
Closes #41327
Relates #40790
```console
% make testacc PKG=ec2 TESTS=TestAccVPCInternetGateway_
TF_ACC=1 go1.23.5 test ./internal/service/ec2/... -v -count 1 -parallel 20 -run='TestAccVPCInternetGateway_'  -timeout 360m …
```
=> r/aws_internet_gateway: continue to deletion when attachment not found

internal/errs/diag.go, internal/errs/sdkdiag/diags.go, internal/service/sagemaker/endpoint_configuration.go, internal/service/sagemaker/endpoint_configuration_test.go, website/docs/r/sagemaker_endpoint_configuration.html.markdown
In `aws_sagemaker_endpoint_configuration` an empty `data_capture_config.capture_content_type_header`, either by not setting any values or setting them all to `nil`, would cause a panic. Adds validation to require at least one of `csv_content_types` or `json_content_types`.
```console
% make testacc PKG=sagemaker TESTS=TestAccSageMakerEndpointConfiguration_
--- PASS: TestAccSageMakerEndpointConfiguration_dataCapture_EmptyHeaders (5.99s)
--- PASS: TestAccSageMakerEndpointConfiguration_kmsKeyID (36.65s)
--- PASS: TestAccSageMakerEndpointConfiguration_disappears (41.72s)
--- PASS: TestAccSageMakerEndpointConfiguration_ProductionVariants_routing (51.72s)
--- PASS: TestAccSageMakerEndpointConfiguration_Async_client_failurePath (58.50s)
--- PASS: TestAccSageMakerEndpointConfiguration_async …
```
=> resource/aws_sagemaker_endpoint_configuration: Prevents panic when `data_capture_config.capture_content_type_header` empty

website/docs/r/eks_cluster.html.markdown
* The resource `aws_eks_cluster`  contains a `storage_config` block, see e.g. example code available [here](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/eks_cluster#eks-cluster-with-eks-auto-mode).
* The provider documentation is missing details on the `storage_config`. 
The pull requests 
- adds the missing documentation for `storage_config`
- adds links from "config block" argument to the corresponding description.
Closes #41226 
- [AWS Provider Source code](https://github.com/hashicorp/terraform-provider-aws/blob/16b3f1f59e22a57aedfe0fbe37926031608910b2/internal/service/eks/cluster.go#L394)
=> docs: add storage configuration block for eks_cluster resource

.changelog/41350.txt, internal/service/dynamodb/table_data_source.go, internal/service/dynamodb/table_data_source_test.go
This PR is to add the missing `on_demand_throughput` configuration block to the resource root and the `global_secondary_index` configuration block in the `aws_dynamodb_table` resource.
Closes #41343
Relates #37799
n/a
```console
$ make testacc TESTS=TestAccDynamoDBTableDataSource_ PKG=dynamodb
TF_ACC=1 go1.23.5 test ./internal/service/dynamodb/... -v -count 1 -parallel 20 -run='TestAccDynamoDBTableDataSource_'  -timeout 360m -vet=off
2025/02/11 23:25:48 Initializing Terraform AWS Provider...
=== RUN   TestAccDynamoDBTableDataSource_tags
=== PAUSE TestAccDynamoDBTableDataSource_tags
=== RUN   TestAccDynamoDBTableDataSource_tags_NullMap
=== PAUSE TestAccDynamoDBTableDataSource_tags_NullMap …
```
=> fix: Add missing on_demand_throughput attrs for aws_dynamodb_table data source

website/docs/r/config_configuration_recorder.html.markdown
Fix typo in `config_configuration_recorder`: Change `reecording` to `recording`
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/config_configuration_recorder#recording_mode-configuration-block
=> docs: fix typo in `config_configuration_recorder`

website/docs/r/eks_cluster.html.markdown
With this document of resource aws_eks_cluster, The [example](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/eks_cluster#eks-cluster-with-eks-hybrid-nodes) here is written like below
```hcl
resource "aws_eks_cluster" "example" {
name = "example"
cluster_remote_network_config = {
remote_node_networks = {
cidrs = ["172.16.0.0/18"]
}
remote_pod_networks = {
cidrs = ["172.16.64.0/18"]
}
}
}
```
The `cluster_remote_network_config` block has to be rewritten like below.
```hcl
resource "aws_eks_cluster" "example" {
name = "example"
remote_network_config {
remote_node_networks {
cidrs = ["172.16.0.0/18"]
}
remote_pod_networks {
cidrs = ["172.16.64.0/18"]
}
}
```
Closes #41421 
```console
...
```
=> Fix document `remote_network_config` attribute `aws_eks_cluster`(#41421)

website/docs/r/cloudfront_vpc_origin.html.markdown
In #41392 it is mentioned that the example provided in the documentation for resource `aws_cloudfront_vpc_origin` is containing an invalid value: The value `Example VPC Origin` for the attribute `name` is not allowed. 
When specifying this value, the API call made to the endpoint fails with
>  InvalidArgument: The parameter Name contains characters other than alphanumericals, dashes, and underscores.
This pull request updates the value by replacing blanks and moving to lower-case.
I had a look into the [AWS SDK Go v2 docs](https://github.com/aws/aws-sdk-go-v2/blob/5c34f50a752430b2cda9b64d1a6206ce0cc18f79/service/cloudfront/types/types.go#L5860), there is also no hint on the restrictions for the name.
Closes #41392 
=> docs: fix invalid name in example

website/docs/r/redshiftserverless_namespace.html.markdown
PR #41224: Added the missing reference to the admin_password_secret_arn attribute in the Redshift Serverless Namespace documentation
Closes #41224
Not applicable, Updated the Docs.
=> docs: add admin_password_secret_arn attribute to Redshift Serverless namespace

.changelog/41434.txt, internal/service/glue/partition.go, internal/service/glue/partition_test.go, website/docs/r/glue_partition.html.markdown
Support `storage_descriptor.additional_locations` for Glue Partition.
Closes #38925
Relates #37891
- [API_CreatePartition](https://docs.aws.amazon.com/glue/latest/webapi/API_CreatePartition.html)
- Supports [StorageDescriptor-AdditionalLocations](https://docs.aws.amazon.com/glue/latest/webapi/API_StorageDescriptor.html#Glue-Type-StorageDescriptor-AdditionalLocations)
```console
% make testacc TESTARGS='-run=TestAccGluePartition' PKG=glue
TF_ACC=1 go test ./internal/service/glue/... -v -count 1 -parallel 20  -run=TestAccGluePartition -timeout 360m -vet=off
2025/02/18 06:17:53 Initializing Terraform AWS Provider...
=== RUN   TestAccGluePartitionIndex_basic
=== PAUSE …
```
=> r/aws_glue_partition - storage_descriptor.additional_locations

website/docs/r/route53_resolver_rule.html.markdown
The documentation currently claims that the IPv4 address parameter is mandatory. This doesn’t make sense, as the API Reference specifies that you can specify IPv4 or IPv6 addresses but not both in the same rule, and checking the actual code, sure enough, it’s optional.
N/A
https://github.com/hashicorp/terraform-provider-aws/blob/main/internal/service/route53resolver/rule.go#L95
N/A — minor documentation fix only
=> [Docs]: `target_ip.ip` is optional in Route 53 Resolver rule

website/docs/r/s3tables_table.html.markdown, website/docs/r/s3tables_table_bucket.html.markdown
Formats argument sub-headings consistently across the table and table bucket registry documentation. Also adds missing links to the S3 tables documentation on naming requirements and missing punctuation.
=> r/aws_s3tables_table[_bucket](doc): tidy headings, add documentation links

.changelog/41451.txt, internal/acctest/knownvalue/regional_arn_exact.go, internal/acctest/knownvalue/regional_arn_regexp.go, internal/service/dynamodb/table.go, internal/service/dynamodb/table_test.go
When  creating a `aws_dynamodb_table` with inline `replica`s, the provider can hang for 30 minutes, even when the replica is active according to the AWS Console.
At https://github.com/hashicorp/terraform-provider-aws/blob/ac38d5621423ce6ec46529c4a46371a85ea3eb12/internal/service/dynamodb/table.go#L1433, the delay and timeout parameters of `waitReplicaActive` are reversed, so that the delay is 30 minutes and the timeout is 0 seconds.
Closes #40531
```console
% make testacc PKG=dynamodb TESTS=TestAccDynamoDBTable_Replica
--- PASS: TestAccDynamoDBTable_Replica_singleStreamSpecification (273.17s)
--- PASS: TestAccDynamoDBTable_Replica_singleCMK (281.90s)
--- PASS: TestAccDynamoDBTable_Replica_tagsTwoOfTwo (291.16s)
--- PASS: TestAccDynamoDBTable_Replica_tagsOneOfTwo (387.66s)
--- PASS: …
```
=> resource/aws_dynamodb_table: Fix hang when creating inline `replica`s

.changelog/41449.txt, internal/service/cloudwatch/contributor_insight_rule.go, internal/service/cloudwatch/contributor_managed_insight_rule.go, internal/service/cloudwatch/contributor_managed_insight_rule_test.go, internal/service/cloudwatch/exports_test.go, internal/service/cloudwatch/service_package_gen.go, website/docs/r/cloudwatch_contributor_managed_insight_rule.html.markdown
New Resource Cloudwatch Contributor Managed Insight Rule
Closes #17877
```console
> make testacc PKG=cloudwatch TESTS=TestAccCloudWatchContributorManagedInsightRule_
TF_ACC=1 go1.23.5 test ./internal/service/cloudwatch/... -v -count 1 -parallel 20 -run='TestAccCloudWatchContributorManagedInsightRule_'  -timeout 360m -vet=off
2025/02/19 11:00:42 Initializing Terraform AWS Provider...
=== RUN   TestAccCloudWatchContributorManagedInsightRule_basic
=== PAUSE TestAccCloudWatchContributorManagedInsightRule_basic
=== RUN   TestAccCloudWatchContributorManagedInsightRule_disappears
=== PAUSE TestAccCloudWatchContributorManagedInsightRule_disappears
=== RUN …
```
=> f/ New Resource aws_cloudwatch_contributor_managed_insight_rule

.changelog/41411.txt, internal/service/redshift/cluster.go, internal/service/redshift/cluster_test.go, website/docs/r/redshift_cluster.html.markdown
add `master_password_wo` write-only attribute
```console
% make testacc TESTARGS="-run=TestAccRedshiftCluster_basic\|TestAccRedshiftCluster_disappears\|TestAccRedshiftCluster_passwordWriteOnly" PKG=redshift
TF_ACC=1 go1.23.5 test ./internal/service/redshift/... -v -count 1 -parallel 20  -run=TestAccRedshiftCluster_basic\|TestAccRedshiftCluster_disappears\|TestAccRedshiftCluster_passwordWriteOnly -timeout 360m -vet=off
2025/02/15 12:29:05 Initializing Terraform AWS Provider...
=== RUN   TestAccRedshiftCluster_basic
=== PAUSE TestAccRedshiftCluster_basic
=== RUN   TestAccRedshiftCluster_disappears
=== PAUSE TestAccRedshiftCluster_disappears
=== RUN   TestAccRedshiftCluster_passwordWriteOnly …
```
=> r/redshift_cluster: add `master_password_wo` write-only attribute

.changelog/41413.txt, internal/service/docdb/cluster.go, internal/service/docdb/cluster_test.go, website/docs/r/docdb_cluster.html.markdown
add `master_password_wo` write-only attribute
```console
% make testacc TESTARGS='-run=TestAccDocDBCluster_basic\|TestAccDocDBCluster_disappears\|TestAccDocDBCluster_passwordWriteOnly' PKG=docdb
TF_ACC=1 go1.23.5 test ./internal/service/docdb/... -v -count 1 -parallel 20  -run=TestAccDocDBCluster_basic\|TestAccDocDBCluster_disappears\|TestAccDocDBCluster_passwordWriteOnly -timeout 360m -vet=off
2025/02/15 13:27:09 Initializing Terraform AWS Provider...
=== RUN   TestAccDocDBCluster_basic
=== PAUSE TestAccDocDBCluster_basic
=== RUN   TestAccDocDBCluster_disappears
=== PAUSE TestAccDocDBCluster_disappears
=== RUN   TestAccDocDBCluster_passwordWriteOnly
=== PAUSE …
```
=> r/docdb_cluster: add `master_password_wo` write-only attribute

.changelog/41412.txt, internal/service/redshiftserverless/namespace.go, internal/service/redshiftserverless/namespace_test.go, website/docs/r/redshiftserverless_namespace.html.markdown
add `admin_user_password_wo` write-only attribute
```console
% make testacc TESTARGS="-run=TestAccRedshiftServerlessNamespace_basic\|TestAccRedshiftServerlessNamespace_user\|TestAccRedshiftServerlessNamespace_diappears\|TestAccRedshiftServerlessNamespace_userPasswordWriteOnly" PKG=redshiftserverless
TF_ACC=1 go1.23.5 test ./internal/service/redshiftserverless/... -v -count 1 -parallel 20  -run=TestAccRedshiftServerlessNamespace_basic\|TestAccRedshiftServerlessNamespace_user\|TestAccRedshiftServerlessNamespace_diappears\|TestAccRedshiftServerlessNamespace_userPasswordWriteOnly -timeout 360m -vet=off
2025/02/15 12:38:23 Initializing Terraform AWS Provider...
=== RUN …
```
=> r/redshiftserverless_namespace: add `admin_user_password_wo` write-only attribute

website/docs/r/backup_selection.html.markdown
The documentation for the resource [`aws_backup_selection`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/backup_selection) is missing details for the two configuration blocks
- [`selection_tag`](https://github.com/hashicorp/terraform-provider-aws/blob/d205660dcd528f389d3e5190d0f0df30a2021066/internal/service/backup/selection.go#L155)
- [`condition`](https://github.com/hashicorp/terraform-provider-aws/blob/d205660dcd528f389d3e5190d0f0df30a2021066/internal/service/backup/selection.go#L51)
The pull request adds basic details for both configuration blocks.
- Relates #41191 
- Relates #41274 
- [AWS Backup API Docs Conditions](https://docs.aws.amazon.com/aws-backup/latest/devguide/API_Conditions.html)
- [AWS Backup API Docs …
=> docs: add docs for aws_backup_selection

internal/acctest/acctest.go, internal/service/apprunner/service.go, internal/service/ec2/vpc_endpoint.go, internal/service/elasticbeanstalk/environment.go, internal/service/pipes/pipe.go, internal/service/pipes/source_parameters.go, internal/verify/validate.go
AWS launched `ap-southeast-4` in 2023 -> `ap-southeast-7` in 2025:
https://aws.amazon.com/blogs/aws/now-open-aws-asia-pacific-melbourne-region-in-australia/ 
https://aws.amazon.com/blogs/aws/now-open-aws-asia-pacific-malaysia-region/
https://aws.amazon.com/blogs/aws/in-the-works-aws-region-in-taiwan/
https://aws.amazon.com/blogs/aws/announcing-the-new-aws-asia-pacific-thailand-region/
(_updating well in advance helps AWS build future regions_)
=> double digit region regex

.changelog/36961.txt, internal/service/amplify/amplify_test.go, internal/service/amplify/domain_association.go, internal/service/amplify/domain_association_test.go
Adds `AWAITING_APP_CNAME` to the pending state for awaiting domain association verification and the target state for awaiting domain association creation.
Closes #29791
I'm on Windows. I couldn't get the tests to work. In WSL, I ran out of memory while trying to run it. If someone could run this, that would be excellent.
=> Fix issue #29791

.changelog/41462.txt, internal/service/s3/bucket_lifecycle_configuration.go, internal/service/s3/bucket_lifecycle_configuration_migrate_v0_test.go, internal/service/s3/bucket_lifecycle_configuration_test.go
This change should enable configurations with the `rule.exipration.expired_object_delete_maker` set alongside one of the other nested arguments (`date` or `days`) to remove the configured argument in order to resolve inconsistent result after apply errors. Previously, `expired_object_delete_marker` must have been explicitly set to `false` in order to resolve the issue.
Also introduces a warning diagnostic to provide additional context when arguments are provided together that may produce an `inconsistent result after apply` error. In practice the diagnostic will appear as follows.
```
│ Warning: Invalid Attribute Combination
│
│   with aws_s3_bucket_lifecycle_configuration.test,
│   on main.tf line 33, in resource "aws_s3_bucket_lifecycle_configuration" "test":
│   33: …
```
=> r/aws_s3_bucket_lifecycle_configuration: remove `expired_object_delete_marker` plan modifier

website/docs/r/vpclattice_resource_configuration.html.markdown
Just two line documentation addition for aws_vpclattice_resource_configuration examples as described in #41491 
The `protocol` argument was missing, leading to errors when plan/apply using these examples.
Closes #41491
=> docs/aws_vpclattice_resource_configuration: added missing protocol arguments to examples

.changelog/41408.txt, internal/service/rds/consts.go, internal/service/rds/instance_test.go
There is a new instance value for aurora-postgresql that is accepted in the `enabled_cloudwatch_logs_exports` field. It looks like this is currently being rolled out and is only available in some regions (can be tested in `us-west-2`).
Closes https://github.com/hashicorp/terraform-provider-aws/issues/41407
```console
make testacc TESTS=TestAccRDSInstance_CloudWatchLogsExport_postgresql PKG=rds
TF_ACC=1 go1.23.5 test ./internal/service/rds/... -v -count 1 -parallel 20 -run='TestAccRDSInstance_CloudWatchLogsExport_postgresql'  -timeout 360m -vet=off
2025/02/14 16:33:21 Initializing Terraform AWS Provider...
=== RUN   TestAccRDSInstance_CloudWatchLogsExport_postgresql
=== PAUSE …
```
=> fix(rds): instance enabled_cloudwatch_logs_exports doesn't allow iam-db-auth-error

.changelog/41443.txt, internal/service/s3/object_data_source.go, website/docs/d/s3_object.html.markdown
The YAML media type has been standardized last year to `application/yaml`. This pull requests updates the `aws_s3_object` data source so that it will return a body for objects using the `application/yaml` Content-Type.
https://datatracker.ietf.org/doc/html/rfc9512
The `aws_s3_object` datasource's tests do not test each content-type individually so no tests have been added.
=> data-source/aws_s3_object: add `application/yaml` to the list of `Content-Type` that return a body.

.changelog/41497.txt, internal/framework/resource_list_of_object.go, internal/service/logs/delivery.go, internal/service/route53domains/domain.go
Provider produces an error during create when `s3_delivery_configuration.suffix_path` is set to a value that is different than the config.
```console
% make testacc TESTARGS='-run=TestAccLogs_serial/Delivery/cloudFrontDistribution$' PKG=logs AWS_DEFAULT_REGION=us-east-1
TF_ACC=1 go1.23.5 test ./internal/service/logs/... -v -count 1 -parallel 20  -run=TestAccLogs_serial/Delivery/cloudFrontDistribution -timeout 360m -vet=off
2025/02/20 13:30:13 Initializing Terraform AWS Provider...
=== RUN   TestAccLogs_serial
=== PAUSE TestAccLogs_serial
=== CONT  TestAccLogs_serial
=== RUN   TestAccLogs_serial/Delivery
=== RUN   TestAccLogs_serial/Delivery/cloudFrontDistribution
delivery_test.go:290: Step …
```
=> r/cloudwatch_log_delivery: fix provider error on `s3_delivery_configuration.suffix_path`

internal/service/memorydb/acl.go, internal/service/memorydb/cluster.go, internal/service/memorydb/cluster_test.go, internal/service/memorydb/sweep.go
Updates `aws_memorydb_cluster` sweeper to set `multi_region_cluster_name` if present
Adds sweeper for `aws_memorydb_multi_region_cluster`
=> sweeper/memorydb: Adds support for multi-region clusters

website/docs/d/cloudfront_cache_policy.html.markdown
The [documentation for data `aws_cloudfront_cache_policy`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/cloudfront_cache_policy#aws-managed-policies) states
> AWS managed cache policy names are prefixed with `Managed-`:
which is not true for two of the policies: `UseOriginCacheControlHeaders` and `UseOriginCacheControlHeaders-QueryStrings`.
```shell
$ aws cloudfront list-cache-policies --query "CachePolicyList.Items[?Type=='managed']" | jq '.[] | .CachePolicy.CachePolicyConfig.Name'
"Managed-CachingOptimized"
"Managed-CachingDisabled"
"Managed-CachingOptimizedForUncompressedObjects"
"Managed-Elemental-MediaPackage"
"Managed-Amplify"
"Managed-Amplify-DefaultNoCookies"
"Managed-Amplify-DefaultNoCookies-V2"
"Managed-Amplify-Default" …
```
=> docs: add details on exceptions and example code

.ci/.golangci5.yml, internal/provider/provider_config_test.go, internal/provider/provider_test.go, internal/service/s3/object_test.go
Replaces `tenv` linter by `usetesting`.
Closes https://github.com/hashicorp/terraform-provider-aws/issues/41510.
```console
% make testacc TESTARGS='-run=TestAccS3Object_source' PKG=s3
TF_ACC=1 go1.23.5 test ./internal/service/s3/... -v -count 1 -parallel 20  -run=TestAccS3Object_source -timeout 360m -vet=off
2025/02/21 16:15:25 Initializing Terraform AWS Provider...
=== RUN   TestAccS3Object_source
=== PAUSE TestAccS3Object_source
=== RUN   TestAccS3Object_sourceHashTrigger
=== PAUSE TestAccS3Object_sourceHashTrigger
=== CONT  TestAccS3Object_source
=== CONT  TestAccS3Object_sourceHashTrigger
--- PASS: TestAccS3Object_source (17.75s)
--- PASS: TestAccS3Object_sourceHashTrigger (29.58s) …
```
=> Replace `tenv` linter by `usetesting`

.changelog/41385.txt, internal/service/autoscaling/policy.go, internal/service/autoscaling/policy_test.go, website/docs/r/autoscaling_policy.html.markdown
Following up from #41066, this patch adds the `period` field to the `customized_metric_specification` to allow overriding the period the metric is observed.
Relates #41066 
- https://docs.aws.amazon.com/autoscaling/ec2/APIReference/API_CustomizedMetricSpecification.html
```console
% make testacc TESTS=TestAccAutoScalingPolicy PKG=autoscaling
...
```
My accounts don't support launch configuration so I can't test. It's the [same reason as in the previous PR I opened before](https://github.com/hashicorp/terraform-provider-aws/pull/41066#issuecomment-2612831833).
=> Support defining period in custom metrics for target tracking policies

.changelog/41272.txt, internal/service/ec2/ec2_fleet.go, internal/service/ec2/ec2_fleet_test.go
Implement the missing `spot_options` arguments from #41237 
The code is pretty much copy and pasted from the `on_demand_options` implementation of the same arguments (added in #29181)
Closes #41237
```console
% make testacc TESTS=TestAccEC2Fleet_SpotOptions PKG=ec2 ACCTEST_PARALLELISM=5
TF_ACC=1 go1.23.5 test ./internal/service/ec2/... -v -count 1 -parallel 5 -run='TestAccEC2Fleet_SpotOptions'  -timeout 360m -vet=off
2025/02/06 22:10:26 Initializing Terraform AWS Provider...
=== RUN   TestAccEC2Fleet_SpotOptions_allocationStrategy
=== PAUSE TestAccEC2Fleet_SpotOptions_allocationStrategy
=== RUN   TestAccEC2Fleet_SpotOptions_capacityRebalance
=== PAUSE …
```
=> Fix missing arguments in `spot_options` block for `aws_ec2_fleet` resource

.changelog/41335.txt, CHANGELOG.md, internal/service/elbv2/load_balancer.go, internal/service/elbv2/load_balancer_test.go
More info on issue: https://github.com/hashicorp/terraform-provider-aws/issues/41355#issuecomment-2657268663
Closes #41355.
Closes https://github.com/hashicorp/terraform-provider-aws/issues/40837.
```console
...
```
=> enable zonal shift for application loadbalancers

internal/framework/flex/diff.go, internal/framework/flex/diff_test.go, internal/service/apigateway/account.go, internal/service/chatbot/slack_channel_configuration.go, internal/service/chatbot/teams_channel_configuration.go, internal/service/cleanrooms/membership.go, internal/service/datazone/user_profile.go, internal/service/docdbelastic/cluster.go, internal/service/elasticache/serverless_cache.go, internal/service/logs/anomaly_detector.go, internal/service/medialive/multiplex_program.go, internal/service/mediapackagev2/channel_group.go, internal/service/opensearchserverless/security_config.go, internal/service/opensearchserverless/security_policy.go, internal/service/resiliencehub/resiliency_policy.go, internal/service/timestreamquery/scheduled_query.go, skaff/resource/resourcefw.gtpl
In Go, function names are typically short, descriptive, and clear in their purpose without unnecessary redundancy. Given the function's role in computing differences between read AWS data and Terraform state, an idiomatic name could be:
1. **`Diff`** – Simple, clear, and follows Go conventions (like `cmp.Diff`).  
```go
diff, d := flex.Diff(ctx, plan, state)
```
This is concise and immediately communicates the function's purpose.
2. **`ComputeDiff`** – Explicitly states that it calculates a difference.  
```go
diff, d := flex.ComputeDiff(ctx, plan, state)
```
This follows Go’s `ComputeX` pattern, which is seen in some standard library and popular Go packages.
3. **`DetermineDiff`** – If the emphasis is on figuring out *what* changed rather than computing values.  
4. **`PlanDiff`** – More …
=> autoflex: Rename Calculate to Diff

examples/sagemaker/main.tf
https://github.com/hashicorp/terraform-provider-aws/actions/runs/13521816083/job/37782597956
```
===> Initializing Example: ./examples/sagemaker <===
Initializing the backend...
Initializing provider plugins...
- Checking for available provider plugins...
Provider "random" v3.7.0-alpha1 is not compatible with Terraform 0.12.31.
Provider version 2.2.1 is the latest compatible version. Select it with 
the following constraint:
version = "~> 2.2"
Terraform checked all of the plugin versions matching the given constraint:
(any version)
Consult the documentation for this provider for more information on
compatibility between provider and Terraform versions.
Alternatively, upgrade to the latest version of Terraform for compatibility with newer provider releases.
Error: incompatible provider …
```
=> Fix `Examples Checks / validate-terraform (0.12.31)` CI check

internal/sweep/framework/resource.go
```
2025/02/25 15:17:05 [DEBUG] Running Sweeper (aws_api_gateway_account) in region (us-east-2)
2025/02/25 15:17:05 [INFO]  sweeper: listing resources: sweeper_region=us-east-2 tf_resource_type=aws_api_gateway_account
panic: not implemented
goroutine 1904 [running]:
github.com/hashicorp/terraform-provider-aws/internal/framework.(*ResourceWithConfigure).Metadata(...)
/Users/kewbank/altsrc.2/github.com/hashicorp/terraform-provider-aws/internal/framework/resource_with_configure.go:22
github.com/hashicorp/terraform-provider-aws/internal/sweep/framework.resourceMetadata(...)
/Users/kewbank/altsrc.2/github.com/hashicorp/terraform-provider-aws/internal/sweep/framework/resource.go:130
github.com/hashicorp/terraform-provider-aws/internal/sweep/framework.(*sweepResource).Delete(0x14002ed3a40, …
```
=> Sweepers: Fix `panic: not implemented` for Framework resources

.changelog/41542.txt, internal/framework/flex/int.go, internal/framework/flex/int_test.go, internal/framework/flex/string.go, internal/service/s3/bucket_lifecycle_configuration.go, internal/service/s3/bucket_lifecycle_configuration_migrate_v0_test.go
Prevents sending invalid 0 for `rule.and.object_size_less_than`
Closes #41521
```console
% make testacc PKG=s3 TESTS=TestAccS3BucketLifecycleConfiguration_
--- PASS: TestAccS3BucketLifecycleConfiguration_RulePrefix (52.63s)
--- PASS: TestAccS3BucketLifecycleConfiguration_Filter_Tag (52.64s)
--- PASS: TestAccS3BucketLifecycleConfiguration_nonCurrentVersionTransition (52.64s)
--- PASS: TestAccS3BucketLifecycleConfiguration_multipleRules_noFilterOrPrefix (53.08s)
--- PASS: TestAccS3BucketLifecycleConfiguration_Filter_ObjectSizeRange (53.10s)
--- PASS: TestAccS3BucketLifecycleConfiguration_nonCurrentVersionExpiration (54.82s)
--- PASS: TestAccS3BucketLifecycleConfiguration_upgradeV5_86_0_Filter_ObjectSizeLessThan (102.19s)
--- PASS: TestAccS3BucketLifecycleConfiguration_upgradeV5_86_0_Transiti …
```
=> resource/aws_s3_bucket_lifecycle_configuration: Prevents sending 0 for `rule.and.object_size_less_than`

.changelog/41556.txt, internal/service/redshift/cluster.go, internal/service/redshift/cluster_test.go
Fixes validation on the `master_username` argument by allowing additional special characters permitted by the AWS API but incorrectly flagged by plan time validation.
Closes #41437 
Ported from #41522
```console
% make testacc PKG=redshift TESTS=TestAccRedshiftCluster_masterUsername
TF_ACC=1 go1.23.5 test ./internal/service/redshift/... -v -count 1 -parallel 20 -run='TestAccRedshiftCluster_masterUsername'  -timeout 360m -vet=off
2025/02/24 15:28:42 Initializing Terraform AWS Provider...
--- PASS: TestAccRedshiftCluster_masterUsername_invalid (2.85s)
--- PASS: TestAccRedshiftCluster_masterUsername (361.88s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/redshift …
```
=> r/aws_redshift_cluster: Fix `master_username` validation

.changelog/41562.txt, internal/service/docdb/cluster.go, internal/service/rds/cluster.go, internal/service/rds/instance.go, internal/service/redshift/cluster.go, internal/service/redshiftserverless/namespace.go, internal/service/secretsmanager/secret_version.go, internal/service/ssm/parameter.go, website/docs/r/db_instance.html.markdown, website/docs/r/docdb_cluster.html.markdown, website/docs/r/rds_cluster.html.markdown, website/docs/r/redshift_cluster.html.markdown, website/docs/r/redshiftserverless_namespace.html.markdown, website/docs/r/secretsmanager_secret_version.html.markdown, website/docs/r/ssm_parameter.html.markdown
`PreferWriteOnlyAttribute` validation will be displayed as a `warning` when the following conditions are met:
- Using Terraform 1.11.0
- Not using a `write-only` attribute on a resource when one is available
This warning can be polarizing since there is nothing wrong with the configuration and the validation is simply a suggestion.
This PR also adds additional `RequiredWith` validation to `_wo` and `_wo_version` attributes
```console
...
```
=> validations: remove `PreferWriteOnlyAttribute` validations

internal/framework/flex/auto_expand_test.go, internal/framework/flex/auto_flatten_test.go, internal/framework/flex/bool.go, internal/framework/flex/bool_test.go, internal/framework/flex/float.go, internal/framework/flex/float_test.go, internal/framework/flex/int.go, internal/framework/flex/int_test.go, internal/framework/flex/logging_test.go, internal/framework/flex/string.go, internal/framework/flex/string_test.go, internal/service/emr/supported_instance_types_data_source.go
Currnently, type-specific Flattener and Expander functions call through into `flex.Flatten` or `flex.Expand`, which need to determine source and target types and perform debug logging. These are not needed when the source and target types are known. Logging and type reflection performs on approximately 100 allocations for a total of 6500 to 9000 bytes.
By directly calling Framework `types` functions, allocations are reduced to 0 to 2 allocations of minor size. Execution time is also reduced by approximately 99%.
See commit messages for specific improvements.
=> Tech Debt: Improve memory behaviour of type-specific Flattener and Expander functions

.changelog/41589.txt, docs/acc-test-environment-variables.md, internal/service/quicksight/exports_test.go, internal/service/quicksight/quicksight_test.go, internal/service/quicksight/role_membership.go, internal/service/quicksight/role_membership_test.go, internal/service/quicksight/service_package_gen.go, website/docs/r/quicksight_account_subscription.html.markdown, website/docs/r/quicksight_role_membership.html.markdown
This resource will allow practitioners to manage QuickSight role memberships via Terraform. The role membership APIs are disabled for identities managed by QuickSight. This resource can only be used when the QuickSight account subscription uses the Active Directory or IAM Identity Center authentication methods.
Closes #39155
- https://docs.aws.amazon.com/quicksight/latest/APIReference/API_CreateRoleMembership.html
- https://docs.aws.amazon.com/quicksight/latest/APIReference/API_DeleteRoleMembership.html
- https://docs.aws.amazon.com/quicksight/latest/APIReference/API_ListRoleMemberships.html
> Note: tests require an active IAM Identity Center configuration and a group name to be passed in via the `TF_AWS_QUICKSIGHT_IDC_GROUP` environment variable.
```console
% …
```
=> r/aws_quicksight_role_membership: new resource

website/docs/r/sqs_queue.html.markdown
SQS has an unusual behavior where certain misconfigurations cause it to hang indefinitely rather than return an error. Specifically, creating or updating an `aws_sqs_queue` results in a `timeout while waiting` error if:  
- `kms_data_key_reuse_period_seconds` is set to a non-default value,  
- `sqs_managed_sse_enabled` is `false` (explicitly or by default), and  
- `kms_master_key_id` is not set.  
While `resourceQueueCustomizeDiff` already handles `kms_data_key_reuse_period_seconds` in some cases, we don't modify configurations to prevent this hanging behavior. Instead of enforcing a change, this PR updates the documentation to make users aware of the issue. We could also connect `kms_data_key_reuse_period_seconds`, `sqs_managed_sse_enabled`, and `kms_master_key_id` to provide invalid …
=> docs/aws_sqs_queue: Timeout with incompatible arguments

website/docs/r/lightsail_instance.html.markdown
- Add the missing value `ipv6` to the list of possible values for `ip_address_type` of the resource `aws_lightsail_instance`.
- In the resource documentation there is also inconsistent spelling of _add-on_:  add-on vs. add on. This was changed to add-on in all places as this term in used in the official AWS docs (e.g. [here](https://docs.aws.amazon.com/lightsail/2016-11-28/api-reference/API_AddOn.html) or [here](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/lightsail/enable-add-on.html)). 
When using `ipv6` as value, one needs to specify a bundle that supports this type. Here an example
```hcl
resource "aws_lightsail_instance" "gitlab_test" {
name              = "custom_gitlab"
availability_zone = "us-east-1b"
blueprint_id      = "amazon_linux_2"
bundle_id         = …
```
=> docs: add missing ip_address_type option for aws_lightsail_instance

.ci/.semgrep.yml, internal/service/bedrock/model_invocation_logging_configuration.go, internal/service/elbv2/listener_rule_data_source.go, internal/service/opensearchserverless/security_config.go, internal/service/opensearchserverless/security_config_data_source.go, internal/service/paymentcryptography/key.go, internal/service/rekognition/stream_processor.go, internal/service/resiliencehub/resiliency_policy.go, internal/service/verifiedpermissions/schema.go
This rule will check for any usage of `schema.SingleNestedBlock` within the `internal/service` subfolder. Pre-existing instances of `SingleNestedBlock`s have been annotated with `nosemgrep` trailing comments. These will be migrated in the future.
Relates #35813
=> .ci/semgrep: add `avoid-SingleNestedBlock` rule

website/docs/d/secretsmanager_secret_versions.html.markdown
Update secretsmanager_secret_versions attributes to match what they actually are.
https://github.com/hashicorp/terraform-provider-aws/blob/1ee987528f7d96390c56bc4c9439fc0de0d40828/internal/service/secretsmanager/secret_versions_data_source.go#L114-L117
=> docs: fix attributes on secretsmanager_secret_versions data source

.changelog/41463.txt, internal/service/sagemaker/wait.go
As mentioned in issue #41436 , the 30-minute timeout is not always sufficient for creating an MLflow tracking server.. This PR increases the timeout to 45 minutes. 
Closes #41436
The `mlflowTrackingServerTimeout` is being used by the [`waitMlflowTrackingServerCreated`](waitMlflowTrackingServerCreated), [`waitMlflowTrackingServerUpdated`](https://github.com/hashicorp/terraform-provider-aws/blob/main/internal/service/sagemaker/wait.go#L653) and [`waitMlflowTrackingServerDeleted`](https://github.com/hashicorp/terraform-provider-aws/blob/main/internal/service/sagemaker/wait.go#L670C6-L670C37) functions.
=> fix (sagemaker): increase mlflowTrackingServerTimeout

.ci/semgrep/migrate/context.yml, internal/service/configservice/sweep.go, internal/service/datasync/sweep.go, internal/service/dynamodb/sweep.go, internal/service/fms/sweep.go, internal/service/iam/sweep.go, internal/service/organizations/sweep.go, internal/service/rds/sweep.go, internal/service/s3/sweep.go, internal/service/sagemaker/sweep.go, internal/service/ssm/sweep.go, internal/sweep/framework/resource.go, internal/sweep/sdk/resource.go, internal/sweep/sweep.go
Adds sweeper for `aws_rds_shard_group`.
Migrates RDS sweepers to `awsv2.Register` pattern.
Adds sweeper for RDS Blue/Green Deployments.
Removes 10 minute hard timeout for resource deletion in sweepers.
Relates #41254.
=> r/aws_rds_shard_group: Add sweeper

skaff/datasource/datasourcefw.gtpl, skaff/resource/resourcefw.gtpl
Currently the hardcoded attribute names will be flagged by the attribute constants semgrep rule. This change brings the preferred pattern into `skaff`.
Relates #41583
=> skaff: use `names` package attribute constants

.ci/semgrep/acctest/checks/arn.yml, internal/service/controltower/landing_zone_test.go, internal/service/organizations/account_test.go, internal/service/organizations/organization_data_source_test.go, internal/service/organizations/organizational_unit_test.go, internal/service/redshift/cluster_data_source_test.go, internal/service/redshift/snapshot_schedule_test.go
Reduce uses of `resource.TestCheckResourceAttrSet` on ARN attributes in favour of explicit checks.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/41271.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/41107.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/40993.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/40930.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/40928.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/40909.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/40854.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/40822.
=> testing: Reduce uses of resource.TestCheckResourceAttrSet with ARN attributes: remaining services

.changelog/41674.txt, internal/service/opsworks/application.go, internal/service/opsworks/instance.go, internal/service/opsworks/layers.go, internal/service/opsworks/permission.go, internal/service/opsworks/rds_db_instance.go, internal/service/opsworks/stack.go, internal/service/opsworks/user_profile.go, website/docs/r/opsworks_application.html.markdown, website/docs/r/opsworks_custom_layer.html.markdown, website/docs/r/opsworks_ecs_cluster_layer.html.markdown, website/docs/r/opsworks_ganglia_layer.html.markdown, website/docs/r/opsworks_haproxy_layer.html.markdown, website/docs/r/opsworks_instance.html.markdown, website/docs/r/opsworks_java_app_layer.html.markdown, website/docs/r/opsworks_memcached_layer.html.markdown, website/docs/r/opsworks_mysql_layer.html.markdown, website/docs/r/opsworks_nodejs_app_layer.html.markdown, website/docs/r/opsworks_permission.html.markdown, website/docs/r/opsworks_php_app_layer.html.markdown, website/docs/r/opsworks_rails_app_layer.html.markdown, website/docs/r/opsworks_rds_db_instance.html.markdown, website/docs/r/opsworks_stack.html.markdown, website/docs/r/opsworks_static_web_layer.html.markdown, website/docs/r/opsworks_user_profile.html.markdown
This ensures that we're all on the same page, providing notice that opsworks resources will be removed as part of v6.0.
Relates #35701
```console
...
```
=> Deprecate aws_opsworks*

.github/workflows/triage.yml
Corrects an incorrect environment variable name
Relates #41657
=> Fix typo in gh command for closed items

.changelog/41676.txt, internal/service/ecs/task_execution_data_source.go, website/docs/d/ecs_task_execution.html.markdown
The Elastic Inference service has been removed from AWS. EC2 and ECS references to it are not supported.
Relates #40992
```console
...
```
=> Deprecate `aws_ecs_task_execution` `overrides.inference_accelerator_overrides`

.changelog/41662.txt, internal/service/s3/bucket_lifecycle_configuration.go, internal/service/s3/bucket_lifecycle_configuration_migrate_v0_test.go, internal/service/s3/bucket_lifecycle_configuration_test.go, internal/service/s3/bucket_lifecycle_configuration_upgrade_v5_86_0_test.go, internal/service/s3/warn_exactly_one_of.go
When converting a `rule` from using `rulefilter.prefix` to `rule.filter.and.prefix`, the value for `rule.filter.prefix` stored in state was populated in the request. Removes `UseStateForUnknown` from `rule.filter.prefix` and `rule.prefix`. Also adds `ExactlyOneOf` warning validators.
Closes #41592
```console
% make testacc PKG=s3 TESTS=TestAccS3BucketLifecycleConfiguration_
--- PASS: TestAccS3BucketLifecycleConfiguration_disappears (46.79s)
--- PASS: TestAccS3BucketLifecycleConfiguration_basic (52.25s)
--- PASS: TestAccS3BucketLifecycleConfiguration_Filter_ObjectSizeRange (52.26s)
--- PASS: TestAccS3BucketLifecycleConfiguration_multipleRules_noFilterOrPrefix (54.59s)
--- PASS: TestAccS3BucketLifecycleConfiguration_multipleRules (57.36s)
--- PASS: …
```
=> resource/aws_s3_bucket_lifecycle_configuration: Fix additional "Invalid XML" errors

.github/workflows/triage.yml
Fixes interpolation because `string` != `${{ string }}`, and I am once again wishing for a better way to test workflows locally 😅
=> Fix interpolation of token output in triage workflow

.changelog/41677.txt, internal/service/ec2/ec2_launch_template.go, internal/service/ec2/ec2_launch_template_data_source.go, website/docs/r/launch_template.html.markdown
Deprecate arguments related to Elastic Graphics and Elastic Inference, which AWS no longer supports, so that they can be removed in the next major version.
Relates:
* #40991 
* #40992
```console
...
```
=> Deprecate Elastic Graphics/Inference in `aws_launch_template`

internal/service/dataexchange/event_action.go
Adds `IsRequired` validation to nested blocks
Relates #40552
```console
% make testacc PKG=dataexchange TESTS=TestAccDataExchangeEventAction_ ACCTEST_PARALLELISM=5
--- PASS: TestAccDataExchangeEventAction_basic (21.00s)
--- PASS: TestAccDataExchangeEventAction_keyPattern (34.55s)
--- PASS: TestAccDataExchangeEventAction_encryption_kmsKey (34.92s)
--- PASS: TestAccDataExchangeEventAction_encryption_AES256 (34.03s)
--- PASS: TestAccDataExchangeEventAction_disappears (17.64s)
--- PASS: TestAccDataExchangeEventAction_update (35.31s)
```
=> resource/aws_dataexchange_event_action: Adds `IsRequired` validation to nested blocks

infrastructure/repository/labels-workflow.tf
Adds a label for tracking issues that pertain to AWS-compatible services for better tracking
=> Add aws-compatible-server label

.changelog/41678.txt, internal/service/account/region.go
Currently, when attempting to enable a region that is already in the enabling  or  enabled status, an error occurs. This change will prevent this error by allowing the process to skip the EnableRegion API call. Instead, it would go directly to the waitRegionEnabled status if the region is already enabling or enabled. Essentially, this change modifies the behavior by letting the process continue without error/failing.
Closes #41430
```console
> make testacc TESTARGS="-run=TestAccAccount_serial/Region" PKG=account
TF_ACC=1 go1.23.5 test ./internal/service/account/... -v -count 1 -parallel 20  -run=TestAccAccount_serial/Region -timeout 360m -vet=off
2025/03/06 10:23:09 Initializing Terraform …
```
=> B account region enable

website/docs/d/vpclattice_service.html.markdown
This is a documentation change for the VPC lattice service data source attributes. The current documentation does not indicate the the `dns_entry` attribute is a list of objects. The updated documentation is based on the schema defined in the data source itself.
None
Data source schema for `dns_entry`: https://github.com/hashicorp/terraform-provider-aws/blob/main/internal/service/vpclattice/service_data_source.go#L47-L62
N/A - only documentation changed
=> update VPC Lattice documentation

.changelog/41685.txt, internal/service/kafkaconnect/connector.go
Removes _ForceNew_ from `aws_mskconnect_connector.connector_configuration`.
Closes https://github.com/hashicorp/terraform-provider-aws/pull/41685.
Closes https://github.com/hashicorp/terraform-provider-aws/issues/40914.
```console
% make testacc TESTARGS='-run=TestAccKafkaConnectConnector_update' PKG=kafkaconnect
TF_ACC=1 go1.23.5 test ./internal/service/kafkaconnect/... -v -count 1 -parallel 20  -run=TestAccKafkaConnectConnector_update -timeout 360m -vet=off
2025/03/06 15:42:19 Initializing Terraform AWS Provider...
=== RUN   TestAccKafkaConnectConnector_update
=== PAUSE TestAccKafkaConnectConnector_update
=== CONT  TestAccKafkaConnectConnector_update
--- PASS: …
```
=> r/aws_mskconnect_connector: Allow `connector_configuration` to be updated in-place

internal/service/kafkaconnect/connector.go, internal/service/kafkaconnect/connector_test.go
In January 2025 MSK was updated to allow changes to a connector's configuration without recreating the connector.
The `aws_mskconnect_connector` needs updating to handle this. `UpdateConnector` only accepts **one of** `capacity` or `connectorConfiguration` per call. As such, we need to check which of these has changes and call the API separately for each change. We also need to get the new connector version in between the requests.
Closes #40914
* [Announcement about config updates](https://aws.amazon.com/about-aws/whats-new/2025/01/amazon-msk-connect-updating-connector-configuration/)
* [UpdateConnector documentation](https://docs.aws.amazon.com/MSKC/latest/mskc/API_UpdateConnector.html) 
The test should pass (verified the expected values in the console), but ran into some errors on the …
=> Allow updates to aws_msk_connector connector_configuration

internal/provider/fwprovider/provider.go, internal/provider/fwprovider/tags_interceptor.go, internal/provider/fwprovider/wrap.go, internal/provider/provider.go, internal/provider/tags_interceptor.go, internal/provider/wrap.go
Instead of hard-coding knowledge of resource transparent tagging into `wrap.go`, pass a list of plan modifiers (`CustomizeDiffFunc`s for Plugin SDK resources).
This can then be extended for per-resource Region override.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/41576.
Relates https://github.com/hashicorp/terraform-provider-aws/issues/27758.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/41207.
```console
% make sane
make: Sane Smoke Tests (x tests of Top y resources)
2025/03/06 15:24:53 Initializing Terraform AWS Provider...
=== …
```
=> Per-resource Region override prep 2

examples/workspaces/main.tf, internal/service/kms/testdata/Key/tags/main_gen.tf, internal/service/kms/testdata/Key/tagsComputed1/main_gen.tf, internal/service/kms/testdata/Key/tagsComputed2/main_gen.tf, internal/service/kms/testdata/Key/tags_defaults/main_gen.tf, internal/service/kms/testdata/Key/tags_ignore/main_gen.tf, internal/service/kms/testdata/tmpl/key_tags.gtpl
Addresses the semgrep `terraform.aws.security.aws-kms-no-rotation.aws-kms-no-rotation` code scanning security findings such as https://github.com/hashicorp/terraform-provider-aws/security/code-scanning/356.
```console
% make testacc TESTARGS='-run=^TestAccKMSKey_tags$$' PKG=kms
TF_ACC=1 go1.23.5 test ./internal/service/kms/... -v -count 1 -parallel 20  -run=^TestAccKMSKey_tags$ -timeout 360m -vet=off
2025/03/07 12:57:42 Initializing Terraform AWS Provider...
=== RUN   TestAccKMSKey_tags
=== PAUSE TestAccKMSKey_tags
=== CONT  TestAccKMSKey_tags
--- PASS: TestAccKMSKey_tags (79.41s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/kms	84.892s
```
=> Fix `terraform.aws.security.aws-kms-no-rotation.aws-kms-no-rotation` security findings

examples/ecs-alb/main.tf, internal/service/logs/testdata/LogGroup/data.tags/main_gen.tf, internal/service/logs/testdata/LogGroup/data.tags_defaults/main_gen.tf, internal/service/logs/testdata/LogGroup/data.tags_ignore/main_gen.tf, internal/service/logs/testdata/LogGroup/tags/main_gen.tf, internal/service/logs/testdata/LogGroup/tagsComputed1/main_gen.tf, internal/service/logs/testdata/LogGroup/tagsComputed2/main_gen.tf, internal/service/logs/testdata/LogGroup/tags_defaults/main_gen.tf, internal/service/logs/testdata/LogGroup/tags_ignore/main_gen.tf, internal/service/logs/testdata/tmpl/group_tags.gtpl
Addresses the semgrep `terraform.aws.security.aws-cloudwatch-log-group-no-retention.aws-cloudwatch-log-group-no-retention` code scanning security findings such as https://github.com/hashicorp/terraform-provider-aws/security/code-scanning/462.
```console
% make testacc TESTARGS='-run=^TestAccLogsLogGroup_tags$$' PKG=logs
TF_ACC=1 go1.23.5 test ./internal/service/logs/... -v -count 1 -parallel 20  -run=^TestAccLogsLogGroup_tags$ -timeout 360m -vet=off
2025/03/07 12:43:56 Initializing Terraform AWS Provider...
=== RUN   TestAccLogsLogGroup_tags
=== PAUSE TestAccLogsLogGroup_tags
=== CONT  TestAccLogsLogGroup_tags
--- PASS: TestAccLogsLogGroup_tags (51.09s)
PASS
ok …
```
=> Fix `terraform.aws.security.aws-cloudwatch-log-group-no-retention.aws-cloudwatch-log-group-no-retention` security findings

examples/count/main.tf, examples/eip/main.tf, examples/elb/main.tf, examples/two-tier/main.tf, internal/service/ec2/testdata/Instance/data.tags/main_gen.tf, internal/service/ec2/testdata/Instance/data.tags_defaults/main_gen.tf, internal/service/ec2/testdata/Instance/data.tags_ignore/main_gen.tf, internal/service/ec2/testdata/Instance/tags/main_gen.tf, internal/service/ec2/testdata/Instance/tagsComputed1/main_gen.tf, internal/service/ec2/testdata/Instance/tagsComputed2/main_gen.tf, internal/service/ec2/testdata/Instance/tags_defaults/main_gen.tf, internal/service/ec2/testdata/Instance/tags_ignore/main_gen.tf, internal/service/ec2/testdata/tmpl/ec2_instance_tags.gtpl
Addresses the semgrep `terraform.lang.security.ec2-imdsv1-optional.ec2-imdsv1-optional` code scanning security findings such as https://github.com/hashicorp/terraform-provider-aws/security/code-scanning/450.
```console
% make testacc TESTARGS='-run=^TestAccEC2Instance_tags$$' PKG=ec2
TF_ACC=1 go1.23.5 test ./internal/service/ec2/... -v -count 1 -parallel 20  -run=^TestAccEC2Instance_tags$ -timeout 360m -vet=off
2025/03/07 12:18:26 Initializing Terraform AWS Provider...
=== RUN   TestAccEC2Instance_tags
=== PAUSE TestAccEC2Instance_tags
=== CONT  TestAccEC2Instance_tags
--- PASS: TestAccEC2Instance_tags (416.26s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/ec2 …
```
=> Fix `terraform.lang.security.ec2-imdsv1-optional.ec2-imdsv1-optional` security findings

website/docs/r/msk_replicator.html.markdown
The resource `aws_msk_replicator` [supports tags](https://github.com/hashicorp/terraform-provider-aws/blob/793bac2f1da36ca0802d7b677fd9e301e206622e/internal/service/kafka/replicator.go#L30), but misses this detail in the [current document](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/msk_replicator).
This pull requests adds documentation  for the argument `tags`. In addition,
- fixes a typo in the import section
- removes some "odd" text from the attribute `arn`.
Closes #40926 
Not applicable, only documentation is updated.
=> docs: add description for tags

internal/acctest/acctest.go
Otherwise
```console
% make sane
make: Sane Smoke Tests (x tests of Top y resources)
2025/03/07 16:41:00 Initializing Terraform AWS Provider...
=== RUN   TestAccIAMInstanceProfile_basic
=== PAUSE TestAccIAMInstanceProfile_basic
=== RUN   TestAccIAMPolicyDocumentDataSource_basic
=== PAUSE TestAccIAMPolicyDocumentDataSource_basic
=== RUN   TestAccIAMPolicyDocumentDataSource_sourceConflicting
=== PAUSE TestAccIAMPolicyDocumentDataSource_sourceConflicting
=== RUN   TestAccIAMPolicy_tags
=== PAUSE TestAccIAMPolicy_tags
=== RUN   TestAccIAMPolicy_basic
=== PAUSE …
```
=> Set Terraform version for `acctest Provider`

internal/service/codebuild/sweep.go, internal/sweep/awsv2/skip.go
Adds missing `aws_codebuild_fleet` sweeper, burning 💲💲💲.
```console
% SWEEPERS=aws_codebuild_fleet make sweep
go1.23.7 test ./internal/sweep -v -sweep=us-west-2,us-east-1,us-east-2,us-west-1 -sweep-run='aws_codebuild_fleet' -timeout 360m -vet=off
2025/03/10 13:58:58 [DEBUG] Running Sweepers for region (us-west-2):
2025/03/10 13:58:58 [DEBUG] Running Sweeper (aws_codebuild_fleet) in region (us-west-2)
2025/03/10 13:58:58 [DEBUG] sweeper: Configuring Terraform AWS Provider: sweeper_region=us-west-2 tf_resource_type=aws_codebuild_fleet
2025-03-10T13:58:58.962-0400 [DEBUG] sweeper.aws-base: Resolving credentials provider: sweeper_region=us-west-2 tf_resource_type=aws_codebuild_fleet
2025-03-10T13:58:58.962-0400 …
```
=> r/aws_codebuild_fleet: Add sweeper

internal/framework/flex/auto_expand.go, internal/framework/flex/auto_flatten.go
The function `mapBlockKey` currently uses `reflect.Value.MethodByName` to detect values that can be converted to `StringValue`. Instead, check for any type that implements `StringValuable`
Note: Uses of `reflect.Value.MethodByName` weaken the dead code elimination in the Go linker
=> autoflex: Handle all `StringValuable` values consistently

internal/acctest/context.go
After upgrade to Go v1.24, use `t.Context()` instead of `context.Background()` for the acceptance testing `Context`.
Relates https://github.com/hashicorp/terraform-provider-aws/issues/41755.
```console
% make sane
make: Sane Smoke Tests (x tests of Top y resources)
2025/03/11 09:47:49 Initializing Terraform AWS Provider...
=== RUN   TestAccIAMInstanceProfile_basic
=== PAUSE TestAccIAMInstanceProfile_basic
=== RUN   TestAccIAMPolicyDocumentDataSource_basic
=== PAUSE TestAccIAMPolicyDocumentDataSource_basic
=== RUN   TestAccIAMPolicyDocumentDataSource_sourceConflicting
=== …
```
=> acctest: Use `t.Context()`

skaff/resource/resourcefw.gtpl
This is a more recent pattern resources have been adopting which emits a warning diagnostic when the read operation detects a `NotFound` error from the corresponding AWS API. Adding this diagnostic provides practitioners with additional context about why a resource may be re-created (it was deleted out of band), and in general is a good practice to embed into `skaff`.
Relates #41583
=> skaff: add not found warning diagnostic to read

website/docs/r/cloudwatch_metric_alarm.html.markdown
On the documentation of [cloudwatch_metric_alarm](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudwatch_metric_alarm) that is write : 
> return_data: (Optional) Specify exactly one metric_query to be true to use that metric_query result as the alarm.
But the example with anomaly detection contains 2 return_data. To work we only need to keep the value on m1 metric query.
Closes #0000
```console
...
```
=> docs: Fix cloudwatch metric alarm example with anomaly detection

.github/workflows/modern_go.yml, internal/service/wafregional/byte_match_set.go, internal/service/wafregional/flex.go, internal/service/wafregional/geo_match_set.go, internal/service/wafregional/ipset.go, internal/service/wafregional/ipset_data_source.go, internal/service/wafregional/rate_based_rule.go, internal/service/wafregional/rate_based_rule_data_source.go, internal/service/wafregional/regex_match_set.go, internal/service/wafregional/regex_match_set_test.go, internal/service/wafregional/regex_pattern_set.go, internal/service/wafregional/rule.go, internal/service/wafregional/rule_data_source.go, internal/service/wafregional/rule_group.go, internal/service/wafregional/rule_group_test.go, internal/service/wafregional/rule_test.go, internal/service/wafregional/size_constraint_set.go, internal/service/wafregional/sql_injection_match_set.go, internal/service/wafregional/subscribed_rule_group_data_source.go, internal/service/wafregional/token_handlers.go, internal/service/wafregional/validate.go, internal/service/wafregional/web_acl.go, internal/service/wafregional/web_acl_association.go, internal/service/wafregional/web_acl_data_source.go, internal/service/wafregional/web_acl_test.go, internal/service/wafregional/xss_match_set.go
Relates #41807
```console
% make t T='TestAccWAFRegionalIPSetDataSource_basic|TestAccWAFRegionalIPSet_basic|TestAccWAFRegionalWebACL_basic|TestAccWAFRegionalRegexPatternSet_basic|TestAccWAFRegionalRegexPatternSetDataSource_basic|TestAccWAFRegionalRuleGroup_basic|TestAccWAFRegionalRuleGroupDataSource_basic|TestAccWAFRegionalWebACLDataSource …
```
=> wafregional: Modernize Go code

.changelog/41794.txt, internal/service/firehose/delivery_stream.go, internal/service/firehose/delivery_stream_test.go, website/docs/r/kinesis_firehose_delivery_stream.html.markdown
add read_from_timestamp option to msk_source_configuration for Firehose delivery stream
Closes #41700 
```console
make testacc TESTS=TestAccFirehoseDeliveryStream_basic PKG=firehose
TF_ACC=1 go1.23.7 test ./internal/service/firehose/... -v -count 1 -parallel 20 -run='TestAccFirehoseDeliveryStream_basic'  -timeout 360m -vet=off
2025/03/12 07:57:04 Initializing Terraform AWS Provider...
=== RUN   TestAccFirehoseDeliveryStream_basic
=== PAUSE TestAccFirehoseDeliveryStream_basic
=== CONT  TestAccFirehoseDeliveryStream_basic
--- PASS: TestAccFirehoseDeliveryStream_basic (100.64s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/firehose   106.099s
```
=> feat: add read_from_timestamp option to msk_source_configuration for Firehose delivery stream

.github/workflows/modern_go.yml, internal/service/sns/platform_application.go, internal/service/sns/sms_preferences.go, internal/service/sns/topic.go, internal/service/sns/topic_data_protection_policy.go, internal/service/sns/topic_data_source.go, internal/service/sns/topic_policy.go, internal/service/sns/topic_subscription.go
Relates #41807
```console
% make t T='TestAccSNSSMSPreferences_serial/deliveryRole|TestAccSNSTopic_basic|TestAccSNSTopicDataProtectionPolicy_basic|TestAccSNSTopicDataSource_basic|TestAccSNSTopicPolicy_basic|TestAccSNSTopicSubscription_basic' K=sns …
```
=> sns: Modernize Go code

docs/running-and-writing-acceptance-tests.md, skaff/resource/resourcefw.gtpl
This will encourage new resources to implement the corresponding sweeper function. Comments are included with direction on how to register the generated function in the services `sweep.go` file.
Also includes documentation updates to the example sweeper functions:
- Provide both Plugin SDK and Plugin Framework based implementations 
- Remove much of the boilerplate setup and error checking which is now handled centrally by the `awsv2.Register` helper function
=> skaff: add sweeper function to resource template

go.mod, go.sum
Manual update of `github.com/aws/aws-sdk-go-v2/aws` dependencies to [`Release 2024-03-13`](https://github.com/aws/aws-sdk-go-v2/commit/67579f790bd1d46e6363a28b5e8c2fc53c854928) as [`dependabot` failed](https://github.com/hashicorp/terraform-provider-aws/network/updates/980499807).
Relates: https://github.com/hashicorp/terraform-provider-aws/issues/39287.
=> `aws-sdk-go-v2` updates (Release 2025-03-13)

.github/workflows/modern_go.yml, GNUmakefile, internal/service/appmesh/flex.go, internal/service/appmesh/gateway_route.go, internal/service/appmesh/gateway_route_data_source.go, internal/service/appmesh/mesh.go, internal/service/appmesh/mesh_data_source.go, internal/service/appmesh/route.go, internal/service/appmesh/route_data_source.go, internal/service/appmesh/virtual_gateway.go, internal/service/appmesh/virtual_gateway_data_source.go, internal/service/appmesh/virtual_node.go, internal/service/appmesh/virtual_node_data_source.go, internal/service/appmesh/virtual_node_migrate.go, internal/service/appmesh/virtual_node_migrate_test.go, internal/service/appmesh/virtual_router.go, internal/service/appmesh/virtual_router_data_source.go, internal/service/appmesh/virtual_router_migrate.go, internal/service/appmesh/virtual_router_migrate_test.go, internal/service/appmesh/virtual_service.go, internal/service/appmesh/virtual_service_data_source.go
Relates #41807
```console
...
```
=> appmesh: Modernize Go code

.changelog/41839.txt, internal/service/ec2/ebs_volume.go, internal/service/ec2/ebs_volume_data_source.go, internal/service/ec2/ebs_volume_data_source_test.go, internal/service/ec2/ebs_volume_test.go, website/docs/d/ebs_volume.html.markdown, website/docs/r/ebs_volume.html.markdown
Add the attribute `create_time` to data source `aws_ebs_volume`
Closes #41796 
- [Data source documentation](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/ebs_volume)
- [API Documentation CreateVolume - ResponseElement](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_CreateVolume.html#API_CreateVolume_ResponseElements)
```console
❯ make testacc TESTS=TestAccEC2EBSVolumeDataSource_basic PKG=ec2
TF_ACC=1 go1.23.7 test ./internal/service/ec2/... -v -count 1 -parallel 20 -run='TestAccEC2EBSVolumeDataSource_basic'  -timeout 360m -vet=off
2025/03/13 20:12:44 Initializing Terraform AWS Provider...
=== RUN   TestAccEC2EBSVolumeDataSource_basic
=== PAUSE …
```
=> feat: add attribute `create_time` to data source

.github/workflows/modern_go.yml, internal/service/lambda/alias.go, internal/service/lambda/alias_data_source.go, internal/service/lambda/code_signing_config.go, internal/service/lambda/code_signing_config_data_source.go, internal/service/lambda/event_source_mapping.go, internal/service/lambda/flex.go, internal/service/lambda/function.go, internal/service/lambda/function_data_source.go, internal/service/lambda/function_event_invoke_config.go, internal/service/lambda/function_url.go, internal/service/lambda/function_url_data_source.go, internal/service/lambda/functions_data_source.go, internal/service/lambda/invocation.go, internal/service/lambda/invocation_data_source.go, internal/service/lambda/invocation_migrate.go, internal/service/lambda/layer_version.go, internal/service/lambda/layer_version_data_source.go, internal/service/lambda/layer_version_permission.go, internal/service/lambda/permission.go, internal/service/lambda/permission_test.go, internal/service/lambda/policy_model.go, internal/service/lambda/provisioned_concurrency_config.go, internal/service/lambda/provisioned_concurrency_config_migrate.go
Relates #41807
```console
...
```
=> lambda: Modernize Go code

.github/workflows/modern_go.yml, internal/service/glue/catalog_database.go, internal/service/glue/catalog_table.go, internal/service/glue/catalog_table_data_source.go, internal/service/glue/catalog_table_optimizer.go, internal/service/glue/classifier.go, internal/service/glue/connection.go, internal/service/glue/connection_data_source.go, internal/service/glue/crawler.go, internal/service/glue/data_catalog_encryption_settings.go, internal/service/glue/data_catalog_encryption_settings_data_source.go, internal/service/glue/data_quality_ruleset.go, internal/service/glue/dev_endpoint.go, internal/service/glue/id.go, internal/service/glue/job.go, internal/service/glue/ml_transform.go, internal/service/glue/partition.go, internal/service/glue/partition_index.go, internal/service/glue/registry.go, internal/service/glue/resource_policy.go, internal/service/glue/schema.go, internal/service/glue/script_data_source.go, internal/service/glue/security_configuration.go, internal/service/glue/status.go, internal/service/glue/trigger.go, internal/service/glue/user_defined_function.go, internal/service/glue/workflow.go
Relates #41807
```console
...
```
=> glue: Modernize Go code

.github/workflows/modern_go.yml, internal/service/batch/compute_environment.go, internal/service/batch/compute_environment_data_source.go, internal/service/batch/compute_environment_test.go, internal/service/batch/job_definition.go, internal/service/batch/job_queue.go, internal/service/batch/job_queue_data_source.go, internal/service/batch/scheduling_policy.go, internal/service/batch/scheduling_policy_data_source.go, internal/service/batch/validate.go
Relates #41807
```console
...
```
=> batch: Modernize Go code

.github/workflows/modern_go.yml, internal/service/apigatewayv2/api.go, internal/service/apigatewayv2/api_data_source.go, internal/service/apigatewayv2/api_mapping.go, internal/service/apigatewayv2/api_mapping_test.go, internal/service/apigatewayv2/apis_data_source.go, internal/service/apigatewayv2/authorizer.go, internal/service/apigatewayv2/deployment.go, internal/service/apigatewayv2/domain_name.go, internal/service/apigatewayv2/export_data_source.go, internal/service/apigatewayv2/integration.go, internal/service/apigatewayv2/integration_response.go, internal/service/apigatewayv2/model.go, internal/service/apigatewayv2/route.go, internal/service/apigatewayv2/route_response.go, internal/service/apigatewayv2/stage.go, internal/service/apigatewayv2/vpc_link.go, internal/service/apigatewayv2/vpc_link_data_source.go
Relates #41807
```console
...
```
=> apigatewayv2: Modernize Go code

.github/workflows/modern_go.yml, internal/service/ecs/account_setting_default.go, internal/service/ecs/capacity_provider.go, internal/service/ecs/cluster.go, internal/service/ecs/cluster_capacity_providers.go, internal/service/ecs/cluster_data_source.go, internal/service/ecs/container_definition_data_source.go, internal/service/ecs/container_definitions.go, internal/service/ecs/flex.go, internal/service/ecs/service.go, internal/service/ecs/service_data_source.go, internal/service/ecs/task_definition.go, internal/service/ecs/task_definition_data_source.go, internal/service/ecs/task_definition_migrate.go, internal/service/ecs/task_execution_data_source.go, internal/service/ecs/task_set.go, internal/service/ecs/validate.go
Relates #41807
```console
...
```
=> ecs: Modernize Go code

.github/workflows/modern_go.yml, internal/service/cloudfront/cache_policy.go, internal/service/cloudfront/cache_policy_data_source.go, internal/service/cloudfront/distribution.go, internal/service/cloudfront/distribution_data_source.go, internal/service/cloudfront/distribution_migrate.go, internal/service/cloudfront/distribution_migrate_test.go, internal/service/cloudfront/field_level_encryption_config.go, internal/service/cloudfront/field_level_encryption_profile.go, internal/service/cloudfront/function.go, internal/service/cloudfront/function_data_source.go, internal/service/cloudfront/key_group.go, internal/service/cloudfront/key_value_store.go, internal/service/cloudfront/log_delivery_canonical_user_id_data_source.go, internal/service/cloudfront/monitoring_subscription.go, internal/service/cloudfront/origin_access_control.go, internal/service/cloudfront/origin_access_identities_data_source.go, internal/service/cloudfront/origin_access_identity.go, internal/service/cloudfront/origin_access_identity_data_source.go, internal/service/cloudfront/origin_request_policy.go, internal/service/cloudfront/origin_request_policy_data_source.go, internal/service/cloudfront/public_key.go, internal/service/cloudfront/realtime_log_config.go, internal/service/cloudfront/realtime_log_config_data_source.go, internal/service/cloudfront/response_headers_policy.go, internal/service/cloudfront/response_headers_policy_data_source.go, internal/service/cloudfront/vpc_origin.go
Relates #41807
```console
...
```
=> cloudfront: Modernize Go code

website/docs/cdktf/python/r/datazone_environment.html.markdown, website/docs/r/datazone_environment.html.markdown
Update documentation for AWS DataZone, the account identifier is optional (like the region).
Fix a typo as well.
Closes #41851.
https://docs.aws.amazon.com/datazone/latest/APIReference/API_CreateEnvironment.html#API_CreateEnvironment_RequestBody
=> docs(datazone): account_identifier is optional

.github/workflows/modern_go.yml, internal/service/elasticache/cluster.go, internal/service/elasticache/cluster_data_source.go, internal/service/elasticache/engine_version.go, internal/service/elasticache/flex.go, internal/service/elasticache/global_replication_group.go, internal/service/elasticache/parameter_group.go, internal/service/elasticache/parameter_group_test.go, internal/service/elasticache/replication_group.go, internal/service/elasticache/replication_group_data_source.go, internal/service/elasticache/replication_group_migrate.go, internal/service/elasticache/replication_group_test.go, internal/service/elasticache/serverless_cache.go, internal/service/elasticache/subnet_group.go, internal/service/elasticache/subnet_group_data_source.go, internal/service/elasticache/user.go, internal/service/elasticache/user_data_source.go, internal/service/elasticache/user_group.go, internal/service/elasticache/user_group_association.go, internal/service/elasticache/validate.go
Relates #41807
```console
...
```
=> elasticache: Modernize Go code

internal/service/emr/cluster_test.go, internal/service/emr/studio_test.go
Part of fixing a bunch of issues I am running into while implementing a few features for EMR. The existing acceptance tests create, in a few cases, world-open KMS keys.
While this is for acceptance testing, and not necessarily a security concern, I do get paged for these at the moment :)
Please close if this is undesired.
Relates #41869
As this is purely a change in test resources, running this only for the three affected tests.
```console
% make testacc PKG=emr TESTS='(TestAccEMRCluster_security|TestAccEMRCluster_s3LogEncryption|TestAccEMRStudio_workspaceStorageEncryption)'
TF_ACC=1 go test ./internal/service/emr/... -v -count 1 -parallel 35 …
```
=>  r/aws_emr_cluster: kms key test resources should not have open policies

website/docs/r/api_gateway_rest_api_policy.html.markdown
`/*` is required after execution ARN of REST API if you want to allow arbitary stage, HTTP verb, resource path of API.
https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-control-access-using-iam-policies-to-invoke-api.html#api-gateway-iam-policy-resource-format-for-executing-api
=> docs(aws_api_gateway_rest_api_policy): Fix example IAM policy document to work correctly

website/docs/r/cognito_user_pool.html.markdown
The attribute `lambda_config.pre_token_generation_configlambda_version` of the resource `aws_cognito_user_pool`  supports now a new value `v3_0`.
Code snippet that can be used for testing
```hcl
resource "aws_cognito_user_pool" "test" {
name = "mypool"
lambda_config {
pre_token_generation_config {
lambda_arn = "arn:aws:lambda:eu-central-1:123456789012:function:my-function"
lambda_version = "V3_0"
}
}
```
Closes #41870 
- [AWS SDK Go - PreTokenGenerationLambdaVersionType](https://github.com/aws/aws-sdk-go-v2/blob/38f558d56fec53d857ae8e21b316ca0f2858fabd/service/cognitoidentityprovider/types/enums.go#L750)
- [AWS SDK Go - Cognito IDP v1.51.0 Release link](https://github.com/aws/aws-sdk-go-v2/releases/tag/service/cognitoidentityprovider/v1.51.0) (Provider version 5.90.0 uses v1.51.1 of the …
=> docs: add missing supported version for pre_token_configuration_type

.changelog/41921.txt, internal/service/bedrockagent/agent.go, internal/service/bedrockagent/agent_test.go
Fix this issue by using `stringvalidator.UTF8LengthBetween`
Closes #41783
```console
%  make testacc ACCTEST_PARALLELISM=3 TESTS=TestAccBedrockAgentAgent_ PKG=bedrockagent
TF_ACC=1 go1.23.7 test ./internal/service/bedrockagent/... -v -count 1 -parallel 3 -run='TestAccBedrockAgentAgent_'  -timeout 360m -vet=off
2025/03/19 19:55:20 Initializing Terraform AWS Provider...
=== RUN   TestAccBedrockAgentAgent_basic
=== PAUSE TestAccBedrockAgentAgent_basic
=== RUN   TestAccBedrockAgentAgent_full
=== PAUSE TestAccBedrockAgentAgent_full
=== RUN   TestAccBedrockAgentAgent_singlePrompt
=== PAUSE TestAccBedrockAgentAgent_singlePrompt
=== RUN   TestAccBedrockAgentAgent_singlePromptUpdate
=== PAUSE …
```
=> [Bug] Agent instruction limit does not cater for multi-byte characters

.changelog/41939.txt, internal/framework/flex/bool.go, internal/service/lakeformation/lakeformation_test.go, internal/service/lakeformation/opt_in.go, internal/service/lakeformation/opt_in_test.go
- Expands `table.wildcard` into AWS structure 
- Run test as serial
- make resource structs local to package
Closes #41916
```console
% make testacc TESTARGS="-run=TestAccLakeFormation_serial/OptIn" PKG=lakeformation
TF_ACC=1 go1.23.7 test ./internal/service/lakeformation/... -v -count 1 -parallel 20  -run=TestAccLakeFormation_serial/OptIn -timeout 360m -vet=off
2025/03/20 14:10:29 Initializing Terraform AWS Provider...
=== RUN   TestAccLakeFormation_serial
=== PAUSE TestAccLakeFormation_serial
=== CONT  TestAccLakeFormation_serial
=== RUN   TestAccLakeFormation_serial/OptIn
=== RUN   TestAccLakeFormation_serial/OptIn/basic
=== RUN   TestAccLakeFormation_serial/OptIn/disappears
=== RUN …
```
=> r/lakeformation_opt_in: fix error when using table `wildcard`

website/docs/cdktf/python/r/s3tables_namespace.html.markdown, website/docs/cdktf/python/r/s3tables_table.html.markdown, website/docs/cdktf/python/r/s3tables_table_policy.html.markdown, website/docs/cdktf/typescript/r/s3tables_namespace.html.markdown, website/docs/cdktf/typescript/r/s3tables_table.html.markdown, website/docs/cdktf/typescript/r/s3tables_table_policy.html.markdown, website/docs/r/s3tables_namespace.html.markdown, website/docs/r/s3tables_table.html.markdown, website/docs/r/s3tables_table_policy.html.markdown
Fix S3Tables-related examples.
On S3 Tables, table name and namespace name cannot include hyphens (`-`). So I replaced it with underscore (`_`).
table naming rules can be found in:
https://docs.aws.amazon.com/AmazonS3/latest/userguide/s3-tables-buckets-naming.html#naming-rules-table
=> docs: fix table and namespace name of s3tables-related examples

.changelog/41940.txt, internal/service/elasticache/cluster.go
The registry documentation for the `aws_elasticache_cluster` resource already includes a `Timeouts` section, however, these were hardcoded into the Create, Update, and Delete methods and not configurable. This change adds configurable timeouts using the pre-existing hardcoded values, allowing practitioners to adjust the timeout values as needed (and as the registry documentation already implies).
- https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/elasticache_cluster#timeouts
```console
% make testacc PKG=elasticache TESTS="TestAccElastiCacheCluster_" ACCTEST_PARALLELISM=10
TF_ACC=1 go1.23.7 test ./internal/service/elasticache/... -v -count 1 -parallel 10 …
```
=> r/aws_elasticache_cluster: add configurable timeouts

internal/sdkv2/suppress.go, internal/sdkv2/suppress_test.go, internal/service/vpclattice/access_log_subscription.go, internal/service/vpclattice/access_log_subscription_test.go, internal/service/vpclattice/auth_policy.go, internal/service/vpclattice/auth_policy_data_source.go, internal/service/vpclattice/auth_policy_data_source_test.go, internal/service/vpclattice/auth_policy_test.go, internal/service/vpclattice/exports_test.go, internal/service/vpclattice/listener.go, internal/service/vpclattice/listener_data_source.go, internal/service/vpclattice/listener_data_source_test.go, internal/service/vpclattice/listener_rule.go, internal/service/vpclattice/listener_rule_test.go, internal/service/vpclattice/listener_test.go, internal/service/vpclattice/resource_policy.go, internal/service/vpclattice/resource_policy_data_source.go, internal/service/vpclattice/resource_policy_data_source_test.go, internal/service/vpclattice/resource_policy_test.go, internal/service/vpclattice/service_network.go, internal/service/vpclattice/service_network_data_source.go, internal/service/vpclattice/service_network_service_association.go, internal/service/vpclattice/service_network_service_association_test.go, internal/service/vpclattice/service_network_test.go, internal/service/vpclattice/service_network_vpc_association.go, internal/service/vpclattice/service_network_vpc_association_test.go, internal/service/vpclattice/service_package_gen.go, internal/service/vpclattice/target_group.go, internal/service/vpclattice/target_group_attachment.go, internal/service/vpclattice/target_group_attachment_test.go
Prevent `vpclattice` functions from being exported directly.
```console
% make testacc TESTARGS='-run=TestAccVPCLattice' PKG=vpclattice ACCTEST_PARALLELISM=3
TF_ACC=1 go1.23.7 test ./internal/service/vpclattice/... -v -count 1 -parallel 3  -run=TestAccVPCLattice -timeout 360m -vet=off
2025/03/20 12:07:08 Initializing Terraform AWS Provider...
=== RUN   TestAccVPCLatticeAccessLogSubscription_basic
=== PAUSE TestAccVPCLatticeAccessLogSubscription_basic
=== RUN   TestAccVPCLatticeAccessLogSubscription_disappears
=== PAUSE TestAccVPCLatticeAccessLogSubscription_disappears
=== RUN   TestAccVPCLatticeAccessLogSubscription_arn
=== PAUSE TestAccVPCLatticeAccessLogSubscription_arn
=== RUN …
```
=> Tech debt: Don't export`vpclattice` functions

go.mod, go.sum
Manual update of `github.com/aws/aws-sdk-go-v2/aws` dependencies to [`Release 2025-03-21`](https://github.com/aws/aws-sdk-go-v2/commit/d96b0023dfa1379858d52722c3626466afa26896) due to dependabot failures.
Relates https://github.com/hashicorp/terraform-provider-aws/issues/41898.
=> `aws-sdk-go-v2` updates (Release 2025-03-21)

infrastructure/repository/labels-workflow.tf
Adds a `beta-feedback` label for our receiving feedback on beta releases.
=> Add `beta-feedback` label

.github/workflows/maintainer_helpers.yml
This PR updates the regressions notifier to use a `rich_text` block rather than a `section` with a `mrkdwn` block for linking to the affected item. This helps fix weird quoting issues that let to some items being posted without working links. While I was at it, I made some slight adjustments to formatting.
Whilst writing this PR description, I've started to wonder if the text should be updated to say "The following **(item|Pull Request|Issue)** has been labeled...", (change bolded) so if that reads better to the team, I'm happy to make those changes prior to merge.
- [A recent example of a failure](https://github.com/hashicorp/terraform-provider-aws/actions/runs/14000394430)
- [`rich_text` block reference](https://api.slack.com/reference/block-kit/blocks#rich_text)
- [`header` block …
=> Fix regressions notifier

.changelog/39979.txt, internal/service/datasync/location_s3_test.go, internal/service/datasync/task.go, internal/service/datasync/task_test.go, website/docs/r/datasync_task.html.markdown
This PR is to add the recently released (enhanced) task mode feature to the `aws_datasync_task` resource. Note that enhanced task mode currently only supports transfer between S3 locations, and once set it cannot be changed (hence force new on this new argument).
Closes #39965
Referred to [CreateTask](https://docs.aws.amazon.com/datasync/latest/userguide/API_CreateTask.html#API_CreateTask_RequestSyntax) for specs and wordings. Also referred to [Choosing a task mode for your data transfer](https://docs.aws.amazon.com/datasync/latest/userguide/choosing-task-mode.html) to confirm that task mode can only be set during task creation and not update.
```console
$ make testacc TESTS="TestAccDataSyncTask_basic|TestAccDataSyncTask_taskMode" PKG=datasync
==> …
```
=> feat: Add task_mode attr for aws_datasync_task

.changelog/41954.txt, internal/generate/tags/main.go, internal/generate/tags/templates/get_tag_body.gtpl, internal/generate/tags/templates/list_tags_body.gtpl, internal/generate/tags/templates/update_tags_body.gtpl, internal/service/elasticache/generate.go, internal/service/elasticache/tags_gen.go, internal/tfresource/retry.go
This fixes a regression introduced during the AWS SDK for Go V2 migration of Elasticache. Previously, the generated tagging logic for AWS SDK for Go V1 included retry logic around the list, tag, and untag operations. These were inadvertently dropped during the SDK migration, and have been added back here using the AWS SDK V2 form of retry handling which accepts error types as an argument. As with the previous implementation tagging operations will have a retry timeout of 15 minutes.
Closes #35952 
Closes #40948 
Relates #36310 (Initial implementation of tag operation retries, `v5.41.0`)
Relates #38046  (AWS SDK migration which removed retries and caused the regression, `v5.59.0`)
```console
% make testacc PKG=elasticache TESTS="TestAccElastiCacheReplicationGroup_tag|TestAccElastiCacheRepli …
```
=> r/aws_elasticache_replication_group: retry `InvalidReplicationGroupStateFault` errors in tag operations

website/docs/r/sns_topic_subscription.html.markdown
This PR enhances the `aws_sns_topic_subscription` documentation by adding an **'Example with Delivery Policy'** section. The new example demonstrates how to define a `delivery_policy` for an HTTPS subscription, clarifying that, unlike the `aws_sns_topic` resource, the `delivery_policy` for `aws_sns_topic_subscription` should **not** be wrapped in an `"http"` object.
Closes #41885
=> docs: Add 'Example with Delivery Policy' to aws_sns_topic_subscription

website/docs/r/lambda_event_source_mapping.html.markdown
Improve the `enabled` parameter on aws_lambda_event_source_mapping resource.
The `enabled` parameter is described as:
```
enabled - (Optional) Determines if the mapping will be enabled on creation. Defaults to true.
```
This parameter not only applies on the resource creation. It also works for already created resources.
I have updated the documentation to:
```
enabled - (Optional) Determines if the mapping is enabled. This parameter can be used to enable or disable the mapping, both during resource creation and for already created resources. Defaults to true.
```
Closes [#41999](https://github.com/hashicorp/terraform-provider-aws/issues/41999)
=> d/aws_lambda_event_source_mapping improve 'enabled' parameter description

.changelog/41995.txt, internal/service/redshift/cluster.go, internal/service/redshift/cluster_test.go, website/docs/guides/version-6-upgrade.html.markdown, website/docs/r/redshift_cluster.html.markdown
Closes #36869
```console
% make testacc TESTARGS="-run=TestAccRedshiftCluster_" PKG=redshift
TF_ACC=1 go1.24.1 test ./internal/service/redshift/... -v -count 1 -parallel 20  -run=TestAccRedshiftCluster_ -timeout 360m -vet=off
2025/03/27 10:39:11 Initializing Terraform AWS Provider...
--- PASS: TestAccRedshiftCluster_masterUsername_invalid (8.21s)
--- PASS: TestAccRedshiftCluster_manageMasterPassword (171.92s)
--- PASS: TestAccRedshiftCluster_availabilityZoneRelocation_publiclyAccessible (174.01s)
--- PASS: TestAccRedshiftCluster_changeAvailabilityZone_availabilityZoneRelocationNotSet (178.85s)
--- PASS: TestAccRedshiftCluster_iamRoles (186.02s)
--- PASS: …
```
=> r/aws_redshift_cluster: remove `snapshot_copy` attribute

.changelog/42008.txt, internal/service/codepipeline/codepipeline.go, internal/service/codepipeline/codepipeline_test.go, website/docs/r/codepipeline.html.markdown
Previously the `trigger` argument was optional and computed, meaning that removal of a configured trigger definition would not result in planned changes as the value would be interpreted as computed only. This change switches the `trigger` argument back to optional only, and adds a computed `trigger_all` block which is used to track both custom trigger configurations provided by the user and default configurations added by AWS for `V2` pipelines. The downside of this approach is that drift between the remote and configured `trigger` definition can no longer be detected. This was deemed an acceptable trade-off in order to ensure trigger removals operate as intended without manual intervention.
Closes #39347 
- https://docs.aws.amazon.com/codepipeline/latest/APIReference/API_CreatePipeline.h …
=> r/aws_codepipeline: support removal of `trigger` arguments

.github/workflows/maintainer_helpers.yml
Adds a missing comma and wraps the URL in `toJSON` to ensure it's wrapped in quotes
=> Further regressions notifier fixes

website/docs/r/ssm_maintenance_window.html.markdown
While working on [SSM maintenance windows](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ssm_maintenance_window) (for OS patching inside EC2s) I noticed that  a `terraform plan` failed with an error  message related to `schedule_offset`. 
The reason: my configuration contained a value of `12` for `schedule_offset`, the provider reported that only 1-6 are allowed.
This pull request adds the allowed range for the attribute to the documentation. In section _References_ I added a link to the validation in the provider source file.
- [Current attribute documentation](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ssm_maintenance_window#schedule_offset-1)
- [Validation in resource source …
=> docs: add valid range for schedule_offset in aws_ssm_maintenance_window

internal/service/elb/app_cookie_stickiness_policy.go, internal/service/elb/lb_cookie_stickiness_policy.go, internal/service/elb/lb_ssl_negotiation_policy.go
Addresses https://github.com/hashicorp/terraform-provider-aws/security/code-scanning/472.
```console
% make testacc TESTARGS='-run=TestAccELBSSLNegotiationPolicy_\|TestAccELBCookieStickinessPolicy_\|TestAccELBAppCookieStickinessPolicy_' PKG=elb ACCTEST_PARALLELISM=3
TF_ACC=1 go1.23.7 test ./internal/service/elb/... -v -count 1 -parallel 3  -run=TestAccELBSSLNegotiationPolicy_\|TestAccELBCookieStickinessPolicy_\|TestAccELBAppCookieStickinessPolicy_ -timeout 360m -vet=off
2025/03/28 08:56:46 Initializing Terraform AWS Provider...
=== RUN   TestAccELBAppCookieStickinessPolicy_basic
=== PAUSE TestAccELBAppCookieStickinessPolicy_basic
=== RUN   TestAccELBAppCookieStickinessPolicy_disappears
=== …
```
=> Fix CodeQL `Incorrect conversion between integer types` warning

.changelog/42030.txt, internal/service/ssm/parameter.go, website/docs/r/ssm_parameter.html.markdown
After assessing community feedback on the intended removal, we have determined the impact to existing use cases relying on this behavior would be too significant to move forward with in `v6`. The deprecation message is now removed from the resource schema and registry documentation, and the argument can continue to be used with the pre-existing behavior.
Relates #25636
Relates #31566
```console
% make testacc PKG=ssm TESTS=TestAccSSMParameter_
TF_ACC=1 go1.23.7 test ./internal/service/ssm/... -v -count 1 -parallel 20 -run='TestAccSSMParameter_'  -timeout 360m -vet=off
2025/03/28 11:46:27 Initializing Terraform AWS Provider...
--- PASS: TestAccSSMParameter_DataType_ssmIntegration (31.88s) …
```
=> r/aws_ssm_parameter: remove `overwrite` deprecation

internal/service/securitylake/sweep.go, internal/sweep/register_gen_test.go
Adds a sweeper for `aws_securitylake_data_lake`.
Closes https://github.com/hashicorp/terraform-provider-aws/issues/42061.
```console
% SWEEPERS=aws_securitylake_data_lake make sweep
go1.23.7 test ./internal/sweep -v -sweep=us-west-2,us-east-1,us-east-2,us-west-1 -sweep-run='aws_securitylake_data_lake' -timeout 360m -vet=off
2025/03/31 16:32:07 [DEBUG] Running Sweepers for region (us-west-2):
2025/03/31 16:32:07 [DEBUG] Running Sweeper (aws_securitylake_data_lake) in region (us-west-2)
2025/03/31 16:32:07 [DEBUG] sweeper: Configuring Terraform AWS Provider: sweeper_region=us-west-2 tf_resource_type=aws_securitylake_data_lake
2025-03-31T16:32:07.012-0400 [DEBUG] sweeper.aws-base: Resolving credentials provider: …
```
=> r/aws_securitylake_data_lake: Add sweeper

.changelog/40953.txt, internal/service/workspaces/workspace.go, internal/service/workspaces/workspace_test.go, internal/service/workspaces/workspaces_test.go
As described in #40580 updates to the value of `running_mode_auto_stop_timeout_in_minutes` in the resource `aws_workspaces_workspace` are not forwarded to the AWS Go SDK v2.
Example configuration of the resource:
```hcl
resource "aws_workspaces_workspace" "workspace" {
directory_id = "d-2783a367e8"
bundle_id    = "wsb-8ry31mu7v"
user_name    = "john.johnson"
root_volume_encryption_enabled = true
user_volume_encryption_enabled = true
volume_encryption_key          = "arn:aws:kms:us-east-1:012345678912:key/05e668b8-debd-9829-8e18-ad62a787863f"
workspace_prooperties {
compute_type_name                 = STANDARD
root_volume_size_gib              = 80
user_volume_size_gib              = 10
running_mode                      = "AUTO_STOP"
running_mode_auto_stop_in_minutes = 120
}
}
``` …
=> fix: update comparison

.changelog/42062.txt, internal/service/sqs/queue.go, internal/service/sqs/queue_test.go, website/docs/r/sqs_queue.html.markdown
This PR fixes a bug where Terraform would hang indefinitely while waiting for SQS queue attributes to propagate. The issue occurred because the resource was incorrectly expecting the `kms_data_key_reuse_period_seconds` attribute to match the configured value, even when encryption was not enabled. Since AWS does not return this attribute unless encryption is enabled via either a KMS master key or SQS-managed SSE, Terraform would continue waiting indefinitely.  
- Updated the attribute propagation logic to account for cases where encryption is not enabled.  
- Now, if neither `kms_master_key_id` nor `sqs_managed_sse_enabled` is set, Terraform will no longer wait for `kms_data_key_reuse_period_seconds` to match.  
- This prevents unnecessary timeouts and ensures the resource creation …
=> Fix SQS Queue Timeout When Waiting for KMS Data Key Reuse Period Propagation

.github/ISSUE_TEMPLATE/01_documentation.yml
Updates the documentation issue form to modernize it a bit and remove the default title.
I uploaded the same form to my [test repository](https://github.com/justinretzolk/issue-forms-test/issues/new?template=03_documentation.yml) to preview what it will look like while filling out the form, and opened an [example issue](https://github.com/justinretzolk/issue-forms-test/issues/42) in that repository to preview a final rendered issue.
=> Update documentation issue form

.github/ISSUE_TEMPLATE/04_repository.yml
Updates the repository/meta issue form to modernize it a bit and remove the default title. 
I uploaded the same form to my [test repository](https://github.com/justinretzolk/issue-forms-test/issues/new?template=04_repository.yml) to preview what it will look like while filling out the form, and opened an [example issue](https://github.com/justinretzolk/issue-forms-test/issues/45) in that repository to preview a final rendered issue.
=> Update repository issue form

.github/ISSUE_TEMPLATE/06_other.yml
Updates the "other" issue form to modernize it a bit. 
I uploaded the same form to my [test repository](https://github.com/justinretzolk/issue-forms-test/issues/new?template=05_other.yml) to preview what it will look like while filling out the form, and opened an [example issue](https://github.com/justinretzolk/issue-forms-test/issues/46) in that repository to preview a final rendered issue.
=> Update "other" issue form

.changelog/38448.txt, internal/service/cloudfront/response_headers_policy.go, website/docs/guides/version-6-upgrade.html.markdown
This PR is to change the `etag` argument of the `aws_cloudfront_response_headers_policy` resource to read-only, since users cannot really set it according to the AWS API reference.
Closes #38244
See https://github.com/hashicorp/terraform-provider-aws/issues/38244#issuecomment-2241328041 for list of resources referenced during the investigation.
```console
$ make testacc TESTS=TestAccCloudFrontResponseHeadersPolicy PKG=cloudfront
TF_ACC=1 go1.22.5 test ./internal/service/cloudfront/... -v -count 1 -parallel 20 -run='TestAccCloudFrontResponseHeadersPolicy'  -timeout 360m
=== RUN   TestAccCloudFrontResponseHeadersPolicyDataSource_basic
=== PAUSE …
```
=> fix: Change etag to read-only for aws_cloudfront_response_headers_policy

.changelog/42097.txt, internal/service/globalaccelerator/accelerator_data_source.go, website/docs/guides/version-6-upgrade.html.markdown
Closes #39236
```console
> make testacc TESTARGS='-run=TestAccGlobalAcceleratorAcceleratorDataSource_' PKG=globalaccelerator
TF_ACC=1 go1.24.1 test ./internal/service/globalaccelerator/... -v -count 1 -parallel 20  -run=TestAccGlobalAcceleratorAcceleratorDataSource_ -timeout 360m -vet=off
2025/04/02 12:32:34 Initializing Terraform AWS Provider...
=== RUN   TestAccGlobalAcceleratorAcceleratorDataSource_basic
=== PAUSE TestAccGlobalAcceleratorAcceleratorDataSource_basic
=== CONT  TestAccGlobalAcceleratorAcceleratorDataSource_basic
--- PASS: TestAccGlobalAcceleratorAcceleratorDataSource_basic (93.61s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/globalaccelerator …
```
=> r/aws_globalaccelerator/accelerator_data_source: Make ID only computed

.changelog/40777.txt, internal/service/servicediscovery/service.go, website/docs/r/service_discovery_service.html.markdown
This PR will try to resolve the issue with the `aws_service_discovery_service` resource where setting the `health_check_custom_config.failure_threshold` to a value other than `1` results into the following behaviors:
- During resource creation, the value is getting ignored as the AWS SDK overrides it to `1`
- After the initial resource creation, the resource always gets recreated as terraform detects that the value written in the terraform file is not on par with the setting in the AWS Cloudformation Stack. This causes uninteded `terraform apply` failures since terraform will try to destroy and then recreate the resource again even with tight depedencies that terraform won't simply allow.
Closes #37955 
#35559 
```console
...
```
=> r/aws_service_discovery_service: Deprecates `health_check_custom_config.failure_threshold`

.changelog/42099.txt, internal/service/sagemaker/notebook_instance.go, internal/service/sagemaker/notebook_instance_test.go, website/docs/guides/version-6-upgrade.html.markdown, website/docs/r/sagemaker_notebook_instance.html.markdown
Closes #38844
Relates #41673
Relates #41101
```console
% make t T=TestAccSageMakerNotebookInstance_basic K=sagemaker
TF_ACC=1 go1.24.1 test ./internal/service/sagemaker/... -v -count 1 -parallel 20 -run='TestAccSageMakerNotebookInstance_basic'  -timeout 360m -vet=off
2025/04/02 16:52:24 Initializing Terraform AWS Provider...
=== RUN   TestAccSageMakerNotebookInstance_basic
=== PAUSE TestAccSageMakerNotebookInstance_basic
=== CONT  TestAccSageMakerNotebookInstance_basic
--- PASS: TestAccSageMakerNotebookInstance_basic (361.72s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/sagemaker	366.991s
```
=> sagemaker: Remove `accelerator_types` from notebook instance

examples/eip/variables.tf
The former AMI ubuntu14.04 is too old and  is out of DeprecationTime. The nginx welcome page can not be accessed 
Replace with ubuntu-22.04 AMI and works well
Closes #0000
```console
...
```
=> The former AMI ubuntu14.04 is too old & The nginx welcome page can not be accessed

.changelog/42108.txt, internal/service/connect/queue.go
The `AssociateQueueQuickConnects` and `DisassociateQueueQuickConnects` APIs accept a maximum of 50 items (_quick connects IDs_) per request. Currently, when passing more than 50 items to the `quick_connect_ids` argument of `aws_connect_queue` resource, it fails with the following error:
```
Error: associating Connect Queue (XXX:XXX) Quick Connects: operation error Connect: AssociateQueueQuickConnects, https response error StatusCode: 400, RequestID:XXX, InvalidParameterException: QuickConnectIds must include at most 50 items
```
This pull request addresses this issue by splitting API requests against both endpoints into chunks of 50 items.
Closes https://github.com/hashicorp/terraform-provider-aws/issues/33447
https://docs.aws.amazon.com/connect/latest/APIReference/API_AssociateQueueQuickC …
=> r/aws_connect_queue: Fix API limitation when assigning more than 50 Quick Connects to a queue

internal/service/osis/pipeline.go, internal/service/osis/pipeline_test.go, internal/service/osis/sweep.go, internal/sweep/register_gen_test.go
Adds a sweeper for `aws_osis_pipeline`.
Attempting to reproduce (unsuccessfully) the error in https://github.com/hashicorp/terraform-provider-aws/issues/41769.
```console
% make testacc TESTARGS='-run=TestAccOpenSearchIngestionPipeline_' PKG=osis ACCTEST_PARALLELISM=2
TF_ACC=1 go1.23.7 test ./internal/service/osis/... -v -count 1 -parallel 2  -run=TestAccOpenSearchIngestionPipeline_ -timeout 360m -vet=off
2025/04/02 16:47:28 Initializing Terraform AWS Provider...
=== RUN   TestAccOpenSearchIngestionPipeline_basic
=== PAUSE TestAccOpenSearchIngestionPipeline_basic
=== RUN   TestAccOpenSearchIngestionPipeline_disappears
=== PAUSE TestAccOpenSearchIngestionPipeline_disappears
=== RUN …
```
=> r/aws_osis_pipeline: Add sweeper

website/docs/r/s3tables_table.html.markdown, website/docs/r/s3tables_table_bucket.html.markdown
This PR updates the description of several arguments of the `aws_s3tables_table` and `aws_s3tables_table_bucket` resources to indicate that they are [object attributes](https://developer.hashicorp.com/terraform/plugin/framework/handling-data/attributes/object) rather than [blocks](https://developer.hashicorp.com/terraform/plugin/framework/handling-data/blocks).
Since they were previously described as blocks, operators intuited that they were compatible with `dynamic` blocks, which isn't the case. Updating the description will hopefully make it more clear that these arguments are incompatible with `dynamic` and that other approaches should be used. 
Closes #40569
=> s3tables: Correctly identify arguments as objects rather than blocks

.changelog/42114.txt, internal/service/ec2/ec2_ami_data_source.go, internal/service/ec2/ec2_ami_data_source_test.go, website/docs/d/ami.html.markdown, website/docs/guides/version-6-upgrade.html.markdown
`v5.77.0` of the AWS provider introduced a warning diagnostic on the `aws_ami` data source to notify practitioners of certain cases when filtering criteria are missing. In `v6.0.0` of the AWS provider, the diagnostic severity is increased to an error. To allow users to opt-in to the unsafe behavior, the error can be suppressed by setting a new, optional argument `allow_unsafe_filter`. The same diagnostic message will still be displayed, but at a warning severity level.
Screenshots of the varying diagnostic severities are included below for reference.
Default:
With `allow_unsafe_filter` set to `true`:
Closes #40198
Relates #40211
Relates https://github.com/hashicorp/terraform-provider-aws/issues/40197
Relates https://github.com/hashicorp/terraform-provider-aws/issues/14158
Relates …
=> d/aws_ami: upgrade unsafe filter warning to suppressible error

.changelog/42117.txt, internal/service/sns/topic_subscription.go
`v5.94.0` introduced an additional call to the `ListSubscriptionByTopic` API during the read operation to properly detect topic and subscription deletions which are only eventually consistent from the `GetSubscriptionAttributes` API. An unintended side effect of this addition was that existing principals which lack the appropriate IAM permissions to call `ListSubscriptionsByTopic` will observe apply time failures similar to:
```
AuthorizationError: User: arn:aws:sts::111111111111:assumed-role/abc123/terraform-run-V6rpqcU7sztpyrnS is not authorized to perform: SNS:ListSubscriptionsByTopic on resource: arn:aws:sns:us-west-2:222222222222:TopicName because no resource-based policy allows the SNS:ListSubscriptionsByTopic action
```
This change addresses the regression by skipping …
=> r/aws_sns_topic_subscription: ignore `AuthorizationError` for `ListSubscriptionByTopic` operations

.changelog/42119.txt, internal/service/redshift/cluster.go, website/docs/guides/version-6-upgrade.html.markdown
The documentation for this resource is already up to date for this change.
Closes #41044 
```console
...
```
=> redshift_cluster: Remove optional for computed-only attributes

website/docs/r/wafv2_ip_set.html.markdown
The [code](https://github.com/hashicorp/terraform-provider-aws/blob/main/internal/service/wafv2/ip_set.go#L63) suggests that actually addresses is optional. In practice this also seems to the case
=> Update docs to make addresses optional to match the code

.changelog/42136.txt, internal/service/servicediscovery/service_data_source.go, website/docs/guides/version-6-upgrade.html.markdown, website/docs/r/service_discovery_service.html.markdown
`tags_all` are not included in data sources. Here they were included erroneously.
Closes #31163 
```console
% make t T=TestAccServiceDiscoveryServiceDataSource_ K=servicediscovery
make: go1.24.2 not found
make: installing go1.24.2...
make: if you get an error, see https://go.dev/doc/manage-install to locally install various Go versions
Downloaded   0.0% (   16384 / 76241216 bytes) ...
Downloaded  79.4% (60538432 / 76241216 bytes) ...
Downloaded 100.0% (76241216 / 76241216 bytes)
Unpacking /Users/dirk/sdk/go1.24.2/go1.24.2.darwin-arm64.tar.gz ...
Success. You may now run 'go1.24.2'
make: go1.24.2 ready
TF_ACC=1 go1.24.2 test ./internal/service/servicediscovery/... -v -count …
```
=> ds/servicediscovery_service: Remove tags_all

website/docs/r/vpc_ipv6_cidr_block_association.html.markdown
This PR fixes a couple of typos in the `aws_vpc_ipv6_cidr_block_association` docs
N/A
N/A
=> docs: typo in `aws_vpc_ipv6_cidr_block_association`

.changelog/42144.txt, internal/service/sagemaker/domain.go, internal/service/sagemaker/domain_test.go
Closes #35503
```console
% make testacc TESTS=TestAccSageMaker_serial/Domain/efs  PKG=sagemaker
--- PASS: TestAccSageMaker_serial (341.54s)
--- PASS: TestAccSageMaker_serial/Domain (341.54s)
--- PASS: TestAccSageMaker_serial/Domain/efs (341.54s)
```
=> r/sagemaker_domain - allow removing custom file config

examples/elb/variables.tf
The former AMI ubuntu14.04 is too old and is out of DeprecationTime. The nginx welcome page can not be accessed Replace with ubuntu-22.04 AMI and works well
The former AMI ubuntu14.04 is too old and is out of DeprecationTime. The nginx welcome page can not be accessed. 
This commit replaces with ubuntu-22.04 AMI and the ec2 instance works well.
Closes #0000
```console
...
```
=> Update variables.tf -- update new AMI ubuntu 22.04

.changelog/42164.txt, internal/service/transfer/server.go, internal/service/transfer/server_test.go, website/docs/r/transfer_server.html.markdown
eFIPS_2025_03,securityPolicyNameSshAuditCompliant_2025_02 support to server.go
transfer service add support for securityPolicyName2025_03, securityPolicyNameFIPS_2025_03, securityPolicyNameSshAuditCompliant_2025_02
Closes #42164
https://docs.aws.amazon.com/transfer/latest/userguide/security-policies.html#security-policy-transferSecurityPolicy-SshAuditCompliant-2025-02
```
🕙[ 20:43:48 ] ➜ aws transfer list-security-policies
{
"SecurityPolicyNames": [
"TransferSFTPConnectorSecurityPolicy-2023-07",
"TransferSFTPConnectorSecurityPolicy-2024-03",
"TransferSFTPConnectorSecurityPolicy-FIPS-2024-10",
"TransferSecurityPolicy-2018-11",
"TransferSecurityPolicy-2020-06",
"TransferSecurityPolicy-2022-03",
"TransferSecurityPolicy-2023-05",
"TransferSecurityPolicy-2024-01", …
```
=> 42164 aws transfer server policy support

website/docs/r/lakeformation_opt_in.html.markdown
This PR corrects the documentation for the `aws_lakeformation_opt_in` resource by fixing the parameter name for table wildcard functionality. The documentation incorrectly referred to the parameter as `table_wild_card`, but the actual parameter name in the Terraform AWS provider is `wildcard`. This change ensures the documentation accurately reflects the provider's implementation.
Opt-in creation error with current doc:
```
│ Error: Unsupported block type
│ 
│   on src/lakeformation_restrictions/opt_in_commands.tf line 64, in resource "aws_lakeformation_opt_in" "app_database_lakeformation_opt_in":
│   64:       table_wildcard {}
│ 
│ Blocks of type "table_wildcard" are not expected here.
```
Terraform import error:
```
│ Error: Resource Import Not Implemented
│ 
│ This resource does not …
```
=> doc: Fix parameter name from table_wild_card to wildcard in aws_lakeformation_opt_in resource

internal/service/transfer/server.go
* Since #42164 was merged, the CI check *Naming Scan Caps/AWS/EC2* continues to fail.  
* Example log: https://github.com/hashicorp/terraform-provider-aws/actions/runs/14372058248/job/40296841581?pr=42188  
* This is because a variable name containing *SSH* does not comply with the naming caps rule.  
* This PR fixes the variable name to prevent the CI check from failing.
* It has been confirmed that the renamed variable is not referenced in any other files.
=> Fix "Ssh" in variable name to "SSH" to comply with naming caps rule to prevent CI failure (Naming Scan Caps/AWS/EC2)

website/docs/r/backup_restore_testing_plan.html.markdown
FIxes an error in doc for aws_backup_restore_testing_plan where a required argument (`name`) was missing from the example code for the resource
Closes #0000
Link to [doc](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/backup_restore_testing_plan)
=> docs: fixed missing required name-argument in example

docs/running-and-writing-acceptance-tests.md, skaff/resource/resourcetest.gtpl
Updates `skaff` and the `_disappears` test examples in the contributor guide to include a post-apply, post-refresh `ExpectResourceAction` plan check. This change does not modify existing `_disappears` tests, though an attempt may be made at doing so in the future.
Relates #42206
=> [TechDebt]: add `ExpectResourceAction` plan check to `_disappears` test examples, skaff

.changelog/42208.txt, internal/service/elasticache/serverless_cache.go, internal/service/elasticache/serverless_cache_test.go
Previously changing the `engine` from `redis` to `valkey` would have forced a replacement of the resource. Migrations from `redis` to `valkey` are now supported in-place as intended in the original implementation of `valkey` support.
Relates #39745
Closes #42204 
- https://discuss.hashicorp.com/t/in-place-update-for-aws-elasticache-serverless-cache-from-redis-to-valkey/73319
- https://docs.aws.amazon.com/AmazonElastiCache/latest/APIReference/API_ModifyServerlessCache.html
```console
% make testacc PKG=elasticache TESTS=TestAccElastiCacheServerlessCache_
TF_ACC=1 go1.23.8 test ./internal/service/elasticache/... -v -count 1 -parallel 20 -run='TestAccElastiCacheServerlessCache_'  -timeout …
```
=> r/aws_elasticache_serverless_cache: allow in-place `redis` to `valkey` engine updates

.changelog/42137.txt, internal/service/ec2/ec2_launch_template.go, internal/service/ec2/ec2_launch_template_data_source.go, internal/service/ec2/ec2_launch_template_data_source_test.go, internal/service/ec2/ec2_launch_template_test.go, internal/service/ecs/task_definition.go, internal/service/ecs/task_definition_data_source.go, internal/service/ecs/task_definition_data_source_test.go, internal/service/ecs/task_definition_test.go, internal/service/ecs/task_execution_data_source.go, website/docs/d/ecs_task_definition.html.markdown, website/docs/d/ecs_task_execution.html.markdown, website/docs/guides/version-6-upgrade.html.markdown, website/docs/r/ecs_task_definition.html.markdown, website/docs/r/launch_template.html.markdown
Amazon Elastic Inference reached end of life on April, 2024. This removes places in EC2 and ECS where it was used.
This equates to the following changes:
Closes #40992 
Relates #41101
```console
% make t T='TestAccEC2LaunchTemplate_|TestAccEC2LaunchTemplateDataSource_|TestAccECSTaskDefinition_|TestAccECSTaskDefinitionDataSource_|TestAccECSTaskExecutionDataSource_' K=ec2 P=10
TF_ACC=1 go1.24.2 test ./internal/service/ec2/... -v -count 1 -parallel 10 -run='TestAccEC2LaunchTemplate_|TestAccEC2LaunchTemplateDataSource_|TestAccECSTaskDefinition_|TestAccECSTaskDefinitionDataSource_|TestAccECSTaskExecutionDataSource_'  -timeout 360m -vet=off
2025/04/04 15:42:19 Initializing Terraform AWS …
```
=> ec2, ecs: EOL Amazon Elastic Inference

.changelog/42226.txt, internal/service/apigateway/account.go, internal/service/apigateway/account_test.go, internal/service/apigateway/apigateway_test.go, website/docs/guides/version-6-upgrade.html.markdown
The default behavior of this resource is now to always reset account settings upon destruction. Practitioners may use a [`removed`](https://developer.hashicorp.com/terraform/language/resources/syntax#removing-resources) block if the previous behavior of leaving settings unmodified upon destruction is desired.
Closes #40043
Relates #40004
Relates #41101
```console
% make testacc PKG=apigateway TESTS=TestAccAPIGateway_serial/Account/
TF_ACC=1 go1.24.2 test ./internal/service/apigateway/... -v -count 1 -parallel 20 -run='TestAccAPIGateway_serial/Account/'  -timeout 360m -vet=off
2025/04/14 15:41:21 Initializing Terraform AWS Provider...
--- PASS: TestAccAPIGateway_serial (520.30s)
--- PASS: …
```
=> r/aws_api_gateway_account: remove `reset_on_delete` argument

.changelog/42228.txt, internal/framework/planmodifiers/boolplanmodifier/legacy_value.go, internal/framework/planmodifiers/boolplanmodifier/legacy_value_test.go, internal/framework/planmodifiers/int32planmodifier/legacy_value.go, internal/framework/planmodifiers/int32planmodifier/legacy_value_test.go, internal/framework/planmodifiers/int64planmodifier/legacy_value.go, internal/framework/planmodifiers/int64planmodifier/legacy_value_test.go, internal/framework/planmodifiers/stringplanmodifier/legacy_value.go, internal/framework/planmodifiers/stringplanmodifier/legacy_value_test.go, internal/service/s3/bucket_lifecycle_configuration.go, internal/service/s3/bucket_lifecycle_configuration_test.go
Prevents error when removing rules from top of list
Closes #41835
```console
% make testacc TPKG=s3 TESTS=TestAccS3BucketLifecycleConfiguration_
--- PASS: TestAccS3BucketLifecycleConfiguration_directoryBucket (76.14s)
--- PASS: TestAccS3BucketLifecycleConfiguration_removeRule (109.39s)
--- PASS: TestAccS3BucketLifecycleConfiguration_RulePrefixToFilter (111.10s)
--- PASS: TestAccS3BucketLifecycleConfiguration_RuleExpiration_expireMarkerOnly (117.92s)
--- PASS: TestAccS3BucketLifecycleConfiguration_RuleExpiration_emptyBlock (118.49s)
--- PASS: TestAccS3BucketLifecycleConfiguration_transitionDefaultMinimumObjectSize_remove (118.52s)
--- PASS: TestAccS3BucketLifecycleConfiguration_transitionDefaultMinimumObjectSize_update (119.04s)
--- PASS: …
```
=> resource/aws_s3_bucket_lifecycle_configuration: Fixes error when removing rules from top of list

.changelog/42230.txt, internal/service/cloudfront/key_value_store.go, internal/service/cloudfront/key_value_store_test.go, website/docs/guides/version-6-upgrade.html.markdown, website/docs/r/cloudfront_key_value_store.html.markdown
The `id` attribute was set to `name`, though the AWS API returned an `Id` parameter. Update `id` to `Id`
Closes #40839
```console
% make testacc PKG=cloudfront TESTS=TestAccCloudFrontKeyValueStore_
--- PASS: TestAccCloudFrontKeyValueStore_disappears (28.86s)
--- PASS: TestAccCloudFrontKeyValueStore_basic (31.18s)
--- PASS: TestAccCloudFrontKeyValueStore_comment (42.87s)
```
=> resource/aws_cloudfront_key_value_store: Set `id` attribute to remote object's `Id`

.changelog/42244.txt, internal/service/apigateway/deployment.go, website/docs/r/api_gateway_deployment.html.markdown
This PR deprecates the `invoke_url` and `execution_arn` computed attributes from the `aws_api_gateway_deployment` resource.
The `invoke_url` and `execution_arn` attributes were originally included in the `aws_api_gateway_deployment` resource to support the now-deprecated behavior of implicitly creating a stage when a deployment was created. This approach has been phased out in favor of explicitly managing stages using the `aws_api_gateway_stage` resource.
- Marked the `invoke_url` and `execution_arn` attributes on `aws_api_gateway_deployment` as deprecated.
- Updated documentation to direct users to retrieve these attributes from the `aws_api_gateway_stage` resource instead.
These attributes will no longer be populated in the `aws_api_gateway_deployment` resource and should be accessed …
=> apigateway_deployment: Deprecate `invoke_url`, `execution_arn`

.changelog/42041.txt, internal/service/s3/bucket_lifecycle_configuration.go, website/docs/r/s3_bucket_lifecycle_configuration.html.markdown
Requires at least one `rule.filter.and.tags` in `aws_s3_bucket_lifecycle_configuration`
Closes #41821
```console
% make testacc PKG=s3 TESTS=TestAccS3BucketLifecycleConfiguration_ ACCTEST_PARALLELISM=10
--- PASS: TestAccS3BucketLifecycleConfiguration_upgradeV5_86_0_ruleAbortIncompleteMultipartUpload (100.05s)
--- PASS: TestAccS3BucketLifecycleConfiguration_RulePrefix (105.57s)
--- PASS: TestAccS3BucketLifecycleConfiguration_upgradeV5_86_0_RuleExpiration_expireMarkerOnly (111.11s)
--- PASS: TestAccS3BucketLifecycleConfiguration_upgradeV5_86_0_TransitionStorageClassOnly_intelligentTiering (111.65s)
--- PASS: TestAccS3BucketLifecycleConfiguration_upgradeV5_86_0_TransitionZeroDays_intelligentTiering (114.77s)
--- PASS: TestAccS3BucketLifecycleConfiguration_upgradeV5_86_0_rule_NoFilterOrPrefix …
```
=> resource/aws_s3_bucket_lifecycle_configuration: Requires at least one `rule.filter.and.tags`

.changelog/41764.txt, internal/service/s3/bucket_lifecycle_configuration.go, internal/service/s3/bucket_lifecycle_configuration_migrate_v0_test.go, internal/service/s3/bucket_lifecycle_configuration_test.go, internal/service/s3/bucket_lifecycle_configuration_upgrade_v5_86_0_test.go, internal/service/s3/directory_bucket_test.go, internal/service/s3/exports_test.go
Some regions, such as `eu-west-2` and `me-central-1`, take significantly longer for eventual consistency to resolve. Adds more delay.
Closes #41363
```console
% AWS_DEFAULT_REGION=eu-west-2 make testacc PKG=s3 TESTS=TestAccS3BucketLifecycleConfiguration_
--- PASS: TestAccS3BucketLifecycleConfiguration_nonCurrentVersionExpiration (312.22s)
--- PASS: TestAccS3BucketLifecycleConfiguration_Filter_ObjectSizeLessThan (313.89s)
--- PASS: TestAccS3BucketLifecycleConfiguration_Filter_ObjectSizeRangeAndPrefix (315.62s)
--- PASS: TestAccS3BucketLifecycleConfiguration_nonCurrentVersionTransition (315.70s)
--- PASS: TestAccS3BucketLifecycleConfiguration_multipleRules_noFilterOrPrefix (315.79s)
--- PASS: TestAccS3BucketLifecycleConfiguration_RulePrefix (316.27s)
--- PASS: …
```
=> resource/aws_s3_bucket_lifecycle_configuration: Better handles eventual consistency for some regions

.changelog/42232.txt, internal/service/codeconnections/host.go, internal/service/codeconnections/host_test.go, website/docs/r/codeconnections_host.html.markdown
Deprecates `id` in favour of `arn` in resource `aws_codeconnections_host`
```console
% make testacc PKG=codeconnections TESTS=TestAccCodeConnectionsHost_
--- PASS: TestAccCodeConnectionsHost_disappears (12.32s)
--- PASS: TestAccCodeConnectionsHost_basic (14.51s)
--- PASS: TestAccCodeConnectionsHost_tags (28.58s)
--- PASS: TestAccCodeConnectionsHost_vpc (582.97s)
```
=> resource/aws_codeconnections_host: Deprecates `id` in favour of `arn`

.changelog/42241.txt, internal/service/kms/custom_key_store.go
This PR fixes a panic in the `kms_custom_key_store` resource when no proxy configuration is returned. I've verified the fix on the following program:
```hcl
terraform {
aws = {
version = "5.94.1"
}
}
}
region = "eu-west-1"
}
resource "random_password" "keystore_pw" {
length = 32
}
resource "aws_kms_custom_key_store" "custom_key_store" {
custom_key_store_name    = "customkeystore"
cloud_hsm_cluster_id     = "REDACTED"
key_store_password       = random_password.keystore_pw.result
trust_anchor_certificate = file("./clusterCA.crt")
}
```
Closes https://github.com/hashicorp/terraform-provider-aws/issues/42240
```console
...
```
=> Fix panic in kms_custom_key_store

.changelog/42260.txt, internal/service/quicksight/data_set_data_source.go, website/docs/guides/version-6-upgrade.html.markdown
The previously deprecated `tags_all` attribute has now been removed. Configurations referencing this argument should use the `tags` attribute instead.
Closes #31164
Relates #30710 
```console
% make testacc PKG=quicksight TESTS=TestAccQuickSightDataSetDataSource_basic
TF_ACC=1 go1.24.2 test ./internal/service/quicksight/... -v -count 1 -parallel 20 -run='TestAccQuickSightDataSetDataSource_basic'  -timeout 360m -vet=off
2025/04/16 10:59:05 Initializing Terraform AWS Provider...
--- PASS: TestAccQuickSightDataSetDataSource_basic (32.93s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/quicksight 39.859s
```
=> d/aws_quicksight_data_set: remove `tags_all`

.changelog/42249.txt, internal/service/apigateway/deployment.go, internal/service/apigateway/deployment_test.go, website/docs/guides/version-6-upgrade.html.markdown, website/docs/r/api_gateway_deployment.html.markdown, website/docs/r/api_gateway_stage.html.markdown
This PR removes implicit stage management from the `aws_api_gateway_deployment` resource by deleting the following attributes:
- `stage_name`
- `stage_description`
- `canary_settings`
- `execution_arn`
- `invoke_url`
These attributes were previously deprecated in #39957 and #42244.
This change finalizes the deprecation of the legacy behavior where a stage could be implicitly created or updated through the `aws_api_gateway_deployment` resource.
Maintaining private state to silently manage an implicitly created stage is not sustainable—especially in the context of state upgrades. Continuing to do so would essentially be a "deprecation of the deprecation," postponing the inevitable removal of the behavior and prolonging user confusion. It’s time to rip off the bandaid.
Users have been …
=> apigateway_deployment: Remove stage from deployment

.changelog/42264.txt, internal/service/paymentcryptography/key.go, internal/service/paymentcryptography/key_migrate.go, internal/service/paymentcryptography/key_test.go, website/docs/guides/version-6-upgrade.html.markdown
These changes are part of a larger effort to remove the use of `SingleNestedBlock` arguments. A state upgrader has been added to make the update seamless across the major version upgrade.
Relates #41379
Relates #41402
```console
% make testacc PKG=paymentcryptography TESTS=TestAccPaymentCryptographyKey_
TF_ACC=1 go1.24.2 test ./internal/service/paymentcryptography/... -v -count 1 -parallel 20 -run='TestAccPaymentCryptographyKey_'  -timeout 360m -vet=off
2025/04/16 13:43:11 Initializing Terraform AWS Provider...
--- PASS: …
```
=> r/aws_paymentcryptography_key: `key_attributes` and `key_attributes.key_modes_of_use` to list nested blocks

.changelog/42270.txt, internal/service/opensearchserverless/security_config.go, internal/service/opensearchserverless/security_config_data_source.go, internal/service/opensearchserverless/security_config_migrate.go, internal/service/opensearchserverless/security_config_test.go, website/docs/guides/version-6-upgrade.html.markdown
These changes are part of a larger effort to remove the use of `SingleNestedBlock` arguments. A state upgrader has been added to make the update seamless across the major version upgrade.
```console
% make testacc PKG=opensearchserverless TESTS="TestAccOpenSearchServerlessSecurityConfig_|TestAccOpenSearchServerlessSecurityConfigDataSource_"
TF_ACC=1 go1.24.2 test ./internal/service/opensearchserverless/... -v -count 1 -parallel 20 -run='TestAccOpenSearchServerlessSecurityConfig_|TestAccOpenSearchServerlessSecurityConfigDataSource_'  -timeout 360m …
```
=> [r|d]/aws_opensearchserverless_security_config: `saml_options` to list nested block

.changelog/42268.txt, internal/service/opensearch/domain.go, internal/service/opensearch/domain_data_source.go, internal/service/opensearch/domain_test.go, website/docs/d/opensearch_domain.html.markdown, website/docs/guides/version-6-upgrade.html.markdown, website/docs/r/opensearch_domain.html.markdown
This PR removes the `kibana_endpoint` output attribute from both the `aws_opensearch_domain` **resource** and **data source**. Users should use the `dashboard_endpoint` or `dashboard_endpoint_v2` attributes instead.
OpenSearch no longer uses Kibana as the visualization interface. Instead, OpenSearch provides a native interface called **Dashboards**, which replaces Kibana.
While legacy Elasticsearch domains may have used the `/ _plugin/kibana` path, OpenSearch domains expose Dashboards at the following path:
```
https://<domain-endpoint>/_dashboards/
```
The name "Kibana" is no longer relevant or accurate in the context of OpenSearch, and AWS documentation now refers to **OpenSearch Dashboards** rather than Kibana.
Closes #31491
Relates #29867
Relates #29995 
Relates #31490 
- [OpenSearch …
=> Remove `kibana_endpoint` Output from `aws_opensearch_domain` Resource and Data Source

website/docs/r/route53_key_signing_key.html.markdown
Fixes a minor typo in the [Route 53 Key Signing Key ](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/route53_key_signing_key) Resource documentation page.
N/A
N/A
N/A
=> Fix typo in route53_key_signing_key docs

.changelog/42283.txt, internal/service/elbv2/listener_rule_data_source.go, internal/service/elbv2/listener_rule_data_source_test.go, website/docs/guides/version-6-upgrade.html.markdown
These changes are part of a larger effort to remove the use of `SingleNestedBlock` arguments. As this is a data source, no state upgrader is necessary because the state is refreshed on each execution.
```console
% make testacc PKG=elbv2 TESTS=TestAccELBV2ListenerRuleDataSource_
TF_ACC=1 go1.24.2 test ./internal/service/elbv2/... -v -count 1 -parallel 20 -run='TestAccELBV2ListenerRuleDataSource_'  -timeout 360m -vet=off
2025/04/17 15:05:28 Initializing Terraform AWS Provider...
--- PASS: TestAccELBV2ListenerRuleDataSource_conditionHTTPRequestMethod …
```
=> d/aws_elbv2_listener_rule: `SingleNestedBlock` to `ListNestedBlock`

.changelog/42300.txt, internal/service/dms/endpoint.go, internal/service/dms/endpoint_data_source.go, internal/service/dms/endpoint_test.go, website/docs/r/dms_endpoint.html.markdown
As mentioned in #42178 the Kinesis configuration for DMS support a new option
> useLargeIntegerValue – Use up to 18 digit int instead of casting ints as doubles, available from AWS DMS version 3.5.4. The default is false.
This pull requests adds this option to 
- resource `aws_dms_endpoint` 
- data source `aws_dms_endpoint`
Closes #42178 
- [AWS SDK Go v2 Docs](https://github.com/aws/aws-sdk-go-v2/blob/a7e1ecdfe59ec95482796a75d99a1ad8cdf919d5/service/databasemigrationservice/types/types.go#L1721)
- [Using Amazon Kinesis Data Streams as a target for AWS Database Migration Service](https://docs.aws.amazon.com/dms/latest/userguide/CHAP_Target.Kinesis.html)
```console
❯ make testacc TESTS=TestAccDMSEndpoint_kinesis PKG=dms …
```
=> feat: add new argument to kinesis configuration of aws_dms_endpoint

.changelog/42227.txt, internal/service/evidently/feature.go, internal/service/evidently/launch.go, internal/service/evidently/project.go, internal/service/evidently/segment.go, website/docs/guides/version-6-upgrade.html.markdown, website/docs/r/evidently_feature.html.markdown, website/docs/r/evidently_launch.html.markdown, website/docs/r/evidently_project.html.markdown, website/docs/r/evidently_segment.html.markdown
In accordance with the AWS announcement that support for CloudWatch Evidently will be discontinued effective 10/17/2025, the corresponding Terraform resource are being deprecated.
Closes #39915
- https://aws.amazon.com/blogs/mt/support-for-amazon-cloudwatch-evidently-ending-soon/
N/a
=> TechDebt: Resource aws_evidently deprecation

.changelog/42297.txt, internal/service/resiliencehub/resiliency_policy.go, internal/service/resiliencehub/resiliency_policy_migrate.go, internal/service/resiliencehub/resiliency_policy_test.go, website/docs/guides/version-6-upgrade.html.markdown
These changes are part of a larger effort to remove the use of `SingleNestedBlock` arguments. A state upgrader has been added to make the update seamless across the major version upgrade.
```console
% make testacc PKG=resiliencehub ACCTEST_PARALLELISM=8 TESTS=TestAccResilienceHubResiliencyPolicy_
TF_ACC=1 go1.24.2 test ./internal/service/resiliencehub/... -v -count 1 -parallel 8 -run='TestAccResilienceHubResiliencyPolicy_'  -timeout 360m -vet=off
2025/04/18 14:44:56 Initializing Terraform AWS Provider...
--- PASS: …
```
=> r/aws_resiliencehub_resiliency_policy: `SingleNestedBlock` to `ListNestedBlock`

website/docs/r/route53_record.html.markdown
Updates the documentation for `aws_route53_record` to add additional accepted values for `type`.
Closes #42299
- [`RRType` enum](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/route53/types#RRType) in the AWS Go SDK (what's used in the validation for this argument)
N/a, docs
=> Update `aws_route53_record.type` accepted values

website/docs/r/cloudfront_distribution.html.markdown
Explains how to set up CloudFront v2 standard logging (to S3).
**Edit:** I can target 6.0 as well if that makes more sense and change to new region annotation! Please let me know.
Closes #40925
https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/standard-logging.html#send-logs-s3
n/a
=> [Docs]: add example of CloudFront V2 standard logging to S3

.changelog/42305.txt, internal/service/verifiedpermissions/schema.go, internal/service/verifiedpermissions/schema_migrate.go, internal/service/verifiedpermissions/schema_test.go, website/docs/guides/version-6-upgrade.html.markdown
These changes are part of a larger effort to remove the use of `SingleNestedBlock` arguments. A state upgrader has been added to make the update seamless across the major version upgrade.
```console
% make testacc PKG=verifiedpermissions TESTS=TestAccVerifiedPermissionsSchema_
TF_ACC=1 go1.24.2 test ./internal/service/verifiedpermissions/... -v -count 1 -parallel 20 -run='TestAccVerifiedPermissionsSchema_'  -timeout 360m -vet=off
2025/04/21 15:08:50 Initializing Terraform AWS Provider...
--- PASS: TestAccVerifiedPermissionsSchema_disappears …
```
=> r/aws_verifiedpermissions_schema: `SingleNestedBlock` to `ListNestedBlock`

.changelog/42312.txt, internal/service/ec2/ec2_launch_template.go, internal/service/ec2/ec2_launch_template_data_source.go, website/docs/guides/version-6-upgrade.html.markdown, website/docs/r/launch_template.html.markdown
These deprecated attributes are being removed as Amazon Elastic Graphics reached end of life on January 8, 2024.
Closes #40991
Relates #41101
- https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DescribeElasticGpus.html
```console
% make testacc PKG=ec2 TESTS=TestAccEC2LaunchTemplateDataSource_
TF_ACC=1 go1.24.2 test ./internal/service/ec2/... -v -count 1 -parallel 20 -run='TestAccEC2LaunchTemplateDataSource_'  -timeout 360m -vet=off
2025/04/21 17:01:22 Initializing Terraform AWS Provider...
--- PASS: TestAccEC2LaunchTemplateDataSource_filter (18.73s)
--- PASS: TestAccEC2LaunchTemplateDataSource_id (18.79s)
--- PASS: TestAccEC2LaunchTemplateDataSource_matchTags (18.80s)
--- PASS: …
```
=> [r/d]/aws_launch_template: remove `elastic_gpu_specifications` attribute

.changelog/42313.txt, internal/service/elastictranscoder/pipeline.go, internal/service/elastictranscoder/preset.go, website/docs/guides/version-6-upgrade.html.markdown, website/docs/r/elastictranscoder_pipeline.html.markdown, website/docs/r/elastictranscoder_preset.html.markdown
In accordance with the AWS announcement that support for Amazon Elastic Transcoder will be discontinued effective, November 13, 2025, the corresponding Terraform resources are being deprecated.
Closes #40318
- https://aws.amazon.com/blogs/media/support-for-amazon-elastic-transcoder-ending-soon/
N/a
=> r/aws_elastictranscoder_*: deprecate resources

website/docs/r/elasticache_cluster.html.markdown
I noticed that there were several links in the `aws_elasticache_cluster` docs that were either malformed or no longer worked (they went straight to the main documentation landing page in AWS). This PR updates them.
N/a, docs
=> Update links in `aws_elasticache_cluster` docs

.github/workflows/triage.yml, infrastructure/repository/labels-workflow.tf
Adds a section to the warning comment workflow to indicate that a changelog entry is needed on non-test changes to files within `internal/service/` subdirectories
Also adds the requisite `no-changelog-needed` label to help with exclusions where the general check provides a false-positive.
N/a, workflow
=> Add check to notify if a changelog entry is needed

.changelog/42320.txt, internal/service/cloudtrail/service_account_data_source.go, website/docs/d/cloudtrail_service_account.html.markdown
This data source is deprecated. The AWS documentation [states that](https://docs.aws.amazon.com/awscloudtrail/latest/userguide/create-s3-bucket-policy-for-cloudtrail.html#troubleshooting-s3-bucket-policy) a [service principal name](https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements_principal.html#principal-services) should be used instead of an AWS account ID in any relevant IAM policy.
As no direct action is required from users to upgrade to `v6.0.0`, no entry is included in the V6 upgrade guide. This data source will be removed in a future major version.
Closes #35130
Relates #41101
- https://docs.aws.amazon.com/awscloudtrail/latest/userguide/create-s3-bucket-policy-for-cloudtrail.html#troubleshooting-s3-bucket-policy
=> d/aws_cloudtrail_service_account: deprecate data source

.changelog/42323.txt, internal/service/directconnect/gateway_association.go, internal/service/directconnect/gateway_association_test.go, website/docs/guides/version-6-upgrade.html.markdown, website/docs/r/dx_gateway_association.html.markdown
Removes deprecate attribute `vpn_gateway_id` from `aws_dx_gateway_association`
Closes #31383
```console
% make testacc PKG=directconnect TESTS=TestAccDirectConnectGatewayAssociation_
--- SKIP: TestAccDirectConnectGatewayAssociation_allowedPrefixesVPNGatewayCrossAccount (0.26s)
--- SKIP: TestAccDirectConnectGatewayAssociation_recreateProposal (0.26s)
--- SKIP: TestAccDirectConnectGatewayAssociation_basicTransitGatewayCrossAccount (0.27s)
--- SKIP: TestAccDirectConnectGatewayAssociation_basicVPNGatewayCrossAccount (0.27s)
--- PASS: TestAccDirectConnectGatewayAssociation_basicVPNGatewaySingleAccount (1192.60s)
--- PASS: TestAccDirectConnectGatewayAssociation_v0StateUpgrade (1199.89s)
--- PASS: TestAccDirectConnectGatewayAssociation_multiVPNGatewaysSingleAccount (1267.57s)
--- PASS: …
```
=> resource/aws_dx_gateway_association: Removes deprecated attribute `vpn_gateway_id`

.github/workflows/triage.yml
Corrects the test in the warning comment to check whether the actual comment step was skipped rather than the filter step.
N/a, workflows
=> Correct test in auto triage

.changelog/42081.txt, internal/service/iam/user.go
Retries ConcurrentModificationExceptions on the IAM CreateRole action. This addresses reported errors in #42079.
Closes https://github.com/hashicorp/terraform-provider-aws/issues/42079
```console
...
```
=> r/aws_iam_user: retry ConcurrentModificationExceptions

.changelog/42336.txt, internal/service/elasticache/replication_group.go, internal/service/elasticache/replication_group_migrate.go, internal/service/elasticache/replication_group_migrate_test.go, internal/service/elasticache/replication_group_test.go, website/docs/guides/version-6-upgrade.html.markdown, website/docs/r/elasticache_replication_group.html.markdown
A state upgrader has been included to remove the default value from state in cases where `auth_token` is not configured. Practitioners will now need to explicitly set a corresponding update strategy when `auth_token` is set.
Closes #34496
Relates https://github.com/hashicorp/terraform-provider-aws/pull/34460
Relates https://github.com/hashicorp/terraform-provider-aws/issues/33439
Relates #41104
```console
% make testacc PKG=elasticache TESTS=TestAccElastiCacheReplicationGroup_
TF_ACC=1 go1.24.2 test ./internal/service/elasticache/... -v -count 1 -parallel 20 -run='TestAccElastiCacheReplicationGroup_'  -timeout 360m -vet=off
2025/04/23 11:30:21 Initializing Terraform AWS Provider...
--- …
```
=> r/aws_elasticache_replication_group: remove `auth_token_update_strategy` default

.changelog/42346.txt, internal/service/elasticache/engine_version.go, internal/service/elasticache/replication_group.go, internal/service/elasticache/replication_group_test.go
The provider can fail to parse a  v7.x `engine_version` upgrade.
```console
% make testacc TESTARGS='-run=TestAccElastiCacheReplicationGroup_OutOfBandUpgrade' PKG=elasticache    
TF_ACC=1 go1.23.8 test ./internal/service/elasticache/... -v -count 1 -parallel 20  -run=TestAccElastiCacheReplicationGroup_OutOfBandUpgrade -timeout 360m -vet=off
2025/04/23 14:49:25 Initializing Terraform AWS Provider...
=== RUN   TestAccElastiCacheReplicationGroup_OutOfBandUpgrade
=== PAUSE TestAccElastiCacheReplicationGroup_OutOfBandUpgrade
=== CONT  TestAccElastiCacheReplicationGroup_OutOfBandUpgrade
replication_group_test.go:246: Step 2/2 error running refresh: exit status 1
Error: parsing old …
```
=> r/aws_elasticache_replication_group: malformed version error

.changelog/42348.txt, internal/service/rds/instance.go, internal/service/rds/instance_test.go, website/docs/guides/version-6-upgrade.html.markdown
Attribute conflict warnings for `character_set_name` with `replicate_source_db`, `restore_to_point_in_time`, `s3_import`, or `snapshot_identifier` errors
Closes #36519 
```console
% make testacc PKG=rds TESTS=TestAccRDSInstance_
--- FAIL: TestAccRDSInstance_MSSQL_domain (4.52s)
--- FAIL: TestAccRDSInstance_MSSQL_domainSnapshotRestore (4.53s)
--- FAIL: TestAccRDSInstance_dedicatedLogVolume_enableOnUpdate (17.62s)
--- PASS: TestAccRDSInstance_NewIdentifier_pending (453.59s)
--- SKIP: TestAccRDSInstance_Outposts_backupTarget (0.24s)
--- SKIP: TestAccRDSInstance_Outposts_coIPSnapshotIdentifier (0.11s)
--- SKIP: TestAccRDSInstance_Outposts_coIPRestoreToPointInTime (0.13s)
--- SKIP: TestAccRDSInstance_Outposts_coIPEnabledToDisabled (0.10s)
--- PASS: TestAccRDSInstance_basic …
```
=> resource/aws_db_instance: Makes attribute conflict warnings for `character_set_name` errors

.changelog/42325.txt, internal/service/identitystore/group.go, internal/service/identitystore/group_data_source.go, internal/service/identitystore/group_data_source_test.go, internal/service/identitystore/user.go, internal/service/identitystore/user_data_source.go, internal/service/identitystore/user_data_source_test.go, website/docs/d/identitystore_group.html.markdown, website/docs/d/identitystore_user.html.markdown, website/docs/guides/version-6-upgrade.html.markdown
Removes `filter` from `data.aws_identitystore_group` and `data.aws_identitystore_user`
Closes #33312
```console
% make testacc PKG=identitystore TESTS=TestAccIdentityStoreGroupDataSource_
--- PASS: TestAccIdentityStoreGroupDataSource_groupID (14.36s)
--- PASS: TestAccIdentityStoreGroupDataSource_uniqueAttributeDisplayName (14.47s)
```
```console
% make testacc PKG=identitystore TESTS=TestAccIdentityStoreUserDataSource_
--- PASS: TestAccIdentityStoreUserDataSource_userID (14.96s)
--- PASS: TestAccIdentityStoreUserDataSource_basic (15.01s)
--- PASS: TestAccIdentityStoreUserDataSource_email (15.24s)
--- PASS: TestAccIdentityStoreUserDataSource_uniqueAttributeUserName (15.35s)
```
=> Removes `filter` from `data.aws_identitystore_group` and `data.aws_identitystore_user`

website/docs/r/shield_proactive_engagement.html.markdown
While the `phone_number` argument is optional, one must be defined (either within the configuration or within AWS) in order to prevent errors.
Note: I'm waiting to hear back from the user who initially reported the linked issue to make sure that my understanding is correct here, since I'm not able to test in my test account.
Closes #42266
[Note in the Go SDK](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/shield#AssociateProactiveEngagementDetailsInput)
n/a, docs
=> Add note to `aws_shield_proactive_engagement` regarding phone number requirement

.changelog/42347.txt, internal/service/imagebuilder/infrastructure_configuration.go, internal/service/imagebuilder/infrastructure_configuration_data_source.go, internal/service/imagebuilder/infrastructure_configuration_data_source_test.go, internal/service/imagebuilder/infrastructure_configuration_test.go, website/docs/d/imagebuilder_infrastructure_configuration.html.markdown, website/docs/r/imagebuilder_infrastructure_configuration.html.markdown
* Add `placement` configuration block, which enables to specify tenancy (dedicated, host) and availability zone to launch instances, to resource and data source.
Closes #40361
https://docs.aws.amazon.com/imagebuilder/latest/APIReference/API_Placement.html
```console
$ make testacc TESTS=TestAccImageBuilderInfrastructureConfiguration_ PKG=imagebuilder
TF_ACC=1 go1.23.8 test ./internal/service/imagebuilder/... -v -count 1 -parallel 20 -run='TestAccImageBuilderInfrastructureConfiguration_'  -timeout 360m -vet=off
2025/04/24 10:49:30 Initializing Terraform AWS Provider...
=== RUN   TestAccImageBuilderInfrastructureConfiguration_basic
=== PAUSE …
```
=> [Enhancement] aws_imagebuilder_infrastructure_configuration: add `placement` configuration block

.github/workflows/triage.yml
Adds `synchronize` to the list of triggers for the AutoTriage action. 
Where `edited` means:
> The title or body of a pull request was edited, or the base branch of a pull request was changed.
`synchronize` means:
> A pull request's head branch was updated. For example, the head branch was updated from the base branch or new commits were pushed to the head branch.
This is useful for the labeler job, where labels will be updated if later commits introduce changes that affect additional services, or make the PR large enough to require a different size label. For the warning comment job, this enables the PR to be reevaluated on new commits to update the comment if an issue is resolved by later commits (e.g. when a changelog entry is added where one was not present before).
[GitHub …
=> Add synchonize to triggers for AutoTriage

website/docs/r/bedrockagent_data_source.html.markdown
This PR updates the documentation for `aws_bedrockagent_data_source` to include all valid values for `data_source_configuration.type`. Previously, only `S3` was listed, but additional valid types are available.
Link to AWS Documentation -https://docs.aws.amazon.com/bedrock/latest/APIReference/API_agent_DataSourceConfiguration.html#API_agent_DataSourceConfiguration_Contents
=> docs(aws_bedrockagent_data_source): update valid values for data_source_configuration.type

.changelog/42376.txt, internal/service/fis/experiment_template.go, internal/service/fis/experiment_template_test.go, website/docs/r/fis_experiment_template.html.markdown
The resource `aws_fis_experiment_templates` is missing support for a specific action target: `ManagedResources`
Closes #42368 
- [Supported action targets](https://docs.aws.amazon.com/fis/latest/userguide/action-sequence.html#action-targets)
- [Validation in Provider](https://github.com/hashicorp/terraform-provider-aws/blob/cb6263a24341a385cd929a477416140389c8c48d/internal/service/fis/experiment_template.go#L1324) missing the relevant action target
```console
❯ make testacc TESTS=TestAccFISExperimentTemplate_managedResource PKG=fis
TF_ACC=1 go1.23.8 test ./internal/service/fis/... -v -count 1 -parallel 20 -run='TestAccFISExperimentTemplate_managedResource'  -timeout 360m -vet=off …
```
=> feat: add missing target key in aws_fis_experiment_template

website/docs/r/eks_cluster.html.markdown
This PR fixes an incorrect variable name in the aws_eks_cluster documentation example.
- Replaces `aws_iam_role.example.arn` with `aws_iam_role.cluster.arn` to match the correct variable declaration.
Fixes #42395
=> Fix aws_eks_cluster documentation to use correct aws_iam_role variable name (#42395)

.changelog/39858.txt, internal/service/wafv2/schemas.go, internal/service/wafv2/web_acl_test.go, website/docs/guides/version-6-upgrade.html.markdown
- The Bot Control managed rule group offers two inspection levels: `COMMON` and `TARGETED`. While there's no default inspection level, enabling `enable_machine_learning = true` forces the inspection level to be set to `TARGETED`, which is nine times more expensive than `COMMON`. This configuration mismatch has led to continual drift in our setup.
- Closes #39825
- [AWS WAF Bot Control rule group Docs](https://docs.aws.amazon.com/waf/latest/developerguide/aws-managed-rule-groups-bot.html)
```console
❯ make testacc TESTS=TestAccWAFV2WebACL_ManagedRuleGroup_ManagedRuleGroupConfig_BotControl PKG=wafv2
TF_ACC=1 go1.23.2 test ./internal/service/wafv2/... -v -count 1 -parallel 20 …
```
=> fix: adjust `enable_machine_learning` default configuration

.changelog/42375.txt, internal/provider/provider.go, website/docs/guides/version-6-upgrade.html.markdown, website/docs/index.html.markdown
In `v6.0.0` support for the `s3_us_east_1_regional_endpoint` provider argument, and the ability to use the global S3 endpoint is being deprecated. This argument will be removed in `v7.0.0`.
If `s3_us_east_1_regional_endpoint` is configured with a value of `legacy`, a warning diagnostic will now be returned indicating that support for the global S3 endpoint is deprecated and instructions on how to validate that the regional S3 endpoint is functional in a given AWS environment.
Closes #33305
Relates https://github.com/hashicorp/terraform-provider-aws/issues/33028
=> provider: deprecate support for s3 global endpoints

internal/service/ecr/replication_configuration_test.go
* Add a test for `aws_ecr_replication_configuration` to verify that combined cross-account and cross-region destination configurations work correctly.
* This test was motivated by #42155. While investigating the reported issue, I found that there was no existing test case covering both cross-account and cross-region replication together.
* Passing the newly added test indicates that combined a cross-account and cross-region destination configuration works as expected with the current implementation.
Closes #42155 
```console
$ AWS_ALTERNATE_PROFILE=admin-alt AWS_PROFILE=admin make testacc TESTS=TestAccECRReplicationConfiguration_ PKG=ecr      
TF_ACC=1 go1.23.7 test …
```
=> [add test] `aws_ecr_replication_configuration` for cross-account and cross-region destination configuration

.changelog/42419.txt, internal/service/elasticache/replication_group.go, internal/service/elasticache/user.go, internal/service/elasticache/user_group.go, internal/verify/validate.go, internal/verify/validate_test.go, website/docs/guides/version-6-upgrade.html.markdown
This change deprecates the ability to provide values to the `engine` argument which do not match the casing returned by the AWS API. In `v7.0.0` these resources will require exact value matches during plan time validation.
Closes #40813
Relates #41101
- https://docs.aws.amazon.com/AmazonElastiCache/latest/APIReference/API_CreateUser.html
- https://docs.aws.amazon.com/AmazonElastiCache/latest/APIReference/API_CreateUserGroup.html
```console
% make testacc PKG=elasticache TESTS=TestAccElastiCacheUser_
TF_ACC=1 go1.24.2 test ./internal/service/elasticache/... -v -count 1 -parallel 20 -run='TestAccElastiCacheUser_'  -timeout 360m -vet=off
2025/04/29 15:02:18 Initializing Terraform AWS …
```
=> r/aws_elasticache[user|user_group|replication_group]: deprecate non-exact `engine` values

.ci/.tflint.hcl
* Update `tflint-ruleset-aws` to version 0.39.0  
* In this version, `defaultLogDriverMode` in `aws_ecs_account_setting_default`—introduced by PR #42418—is recognized as a valid value.  
* https://github.com/terraform-linters/tflint-ruleset-aws/blob/5ca13abb32c573530ad00895d0ce32d66aa24952/rules/models/aws_ecs_account_setting_default_invalid_name.go#L37
* This resolves the CI failure observed in #42418.  
* In my local environment, I ran TFLint with the updated `tflint-ruleset-aws`, using a branch that combines this change with the one from #42418, and confirmed that no errors (including the one related to `defaultLogDriverMode`) were reported.
Relates #42418
=> [TFLint] update tflint-ruleset-aws version to fix CI failure

.changelog/42434.txt, internal/sdkv2/types/nullable/bool.go, internal/sdkv2/types/nullable/bool_test.go, internal/sdkv2/types/nullable/testing.go, website/docs/guides/version-6-upgrade.html.markdown
Arguments of the type `TypeNullableBool` will now only accept one of `""` (empty string), `true`, or `false`. An upgrade guide entry is included enumerating the resources and arguments which are affected by this validation change.
Closes #29379
Relates #32090
Relates #41101
```console
% go test -count=1 ./internal/sdkv2/types/nullable/...
ok      github.com/hashicorp/terraform-provider-aws/internal/sdkv2/types/nullable       0.208s
```
=> internal/sdkv2/types/nullable: refine `TypeNullableBool` validation

.changelog/42326.txt, internal/service/elbv2/listener.go, internal/service/elbv2/listener_test.go, website/docs/guides/version-6-upgrade.html.markdown, website/docs/r/lb_listener.html.markdown
Updates validation for `mutual_authentication` attributes in `aws_lb_listener`
Closes #35452
```console
% make testacc PKG=elbv2 TESTS=TestAccELBV2Listener_
--- PASS: TestAccELBV2Listener_Gateway_basic (195.61s)
--- PASS: TestAccELBV2Listener_DefaultAction_actionDisappears (229.58s)
--- PASS: TestAccELBV2Listener_oidc (241.30s)
--- PASS: TestAccELBV2Listener_Application_basic (248.00s)
--- PASS: TestAccELBV2Listener_redirectWithTargetGroupARN (253.53s)
--- PASS: TestAccELBV2Listener_DefaultAction_defaultOrder (254.12s)
--- PASS: TestAccELBV2Listener_DefaultAction_specifyOrder (260.50s)
--- PASS: TestAccELBV2Listener_Forward_ingest (260.82s)
--- PASS: TestAccELBV2Listener_Forward_update (266.36s)
--- PASS: TestAccELBV2Listener_disappears (267.22s)
--- PASS: …
```
=> resource/aws_lb_listener: Updates validation for `mutual_authentication` attributes

.changelog/42369.txt, internal/service/ec2/vpc_network_insights_path.go, internal/service/ec2/vpc_network_insights_path_test.go
* The recently merged PR #42214 has an issue where resource creation fails when `filter_at_source.source_address` is unspecified, as reported in https://github.com/hashicorp/terraform-provider-aws/issues/38132#issuecomment-2829327235.
* This PR fixes incorrect handling of deserialization for the `source_address` string argument in `filter_at_source`.
* When `source_address` is not specified in the Terraform configuration, the `SourceAddress` field in the AWS SDK for Go structure should be set to `nil` by ignoring the empty string resulting from deserialization. However, the empty string was incorrectly passed instead of being ignored.
* As a result, an empty string was passed to the AWS API parameter, leading to the error: `api error InvalidParameterValue: FilterAtSource.SourceAddress () …
=> [Bug fix] Fix `aws_ec2_network_insights_path` failure when `filter_at_source.source_address` is unspecified (related to recently merged PR #42214)

.changelog/42473.txt, internal/service/networkfirewall/firewall_policy_data_source.go, internal/service/networkfirewall/firewall_policy_data_source_test.go
The data source [`aws_networkfirewall_firewall_policy`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/networkfirewall_firewall_policy)  is missing the attribute `policy_variables` (and contained other attributes).
When a resource [`aws_networkfirewall_firewall_policy`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/networkfirewall_firewall_policy)   containing `policy_variables` is created and its contents read by the data source, an error similar to the one  below is thrown
```shell
Error: setting firewall_policy: Invalid address to set: []string{"firewall_policy", "0", "policy_variables"}
```
Example code demonstrating the issue
```hcl
resource "aws_networkfirewall_firewall_policy" "test" {
name = "Test"
firewall_policy { …
```
=> fix: add missing attribute `policy_variables` in data source `aws_networkfirewall_firewall_policy`

.changelog/42390.txt, internal/service/cloudwatch/metric_alarm.go, website/docs/r/cloudwatch_metric_alarm.html.markdown
To support both API PutMetricAlarm, MetricDataQuery for period value 20
https://docs.aws.amazon.com/AmazonCloudWatch/latest/APIReference/API_PutMetricAlarm.html
https://docs.aws.amazon.com/AmazonCloudWatch/latest/APIReference/API_MetricDataQuery.html
Closes #42389
Will need help with acceptance test
=> Support for metric period value 20 - #42389

.changelog/42407.txt, internal/service/wafv2/flex.go, internal/service/wafv2/rule_group_test.go, internal/service/wafv2/schemas.go, internal/service/wafv2/web_acl_test.go, website/docs/r/wafv2_rule_group.html.markdown, website/docs/r/wafv2_web_acl.html.markdown
* Support URI fragment field matching in `aws_wafv2_web_acl` and `aws_wafv2_rule_group` resouces by introducing `uri_fragment` block into `field_to_match` block.
Closes #41905
* https://docs.aws.amazon.com/waf/latest/developerguide/waf-rule-statement-fields-list.html#waf-rule-statement-request-component-uri-fragment
* https://docs.aws.amazon.com/ja_jp/waf/latest/APIReference/API_FieldToMatch.html#WAF-Type-FieldToMatch-UriFragment
* https://docs.aws.amazon.com/ja_jp/waf/latest/APIReference/API_UriFragment.html
```console
$ make testacc TESTS=TestAccWAFV2WebACL_ PKG=wafv2
TF_ACC=1 go1.23.8 test ./internal/service/wafv2/... -v -count 1 -parallel 20 -run='TestAccWAFV2WebACL_'  -timeout 360m …
```
=> [Enhancement] WAFv2: Support URI fragment field matching in aws_wafv2_web_acl and aws_wafv2_rule_group resources

.changelog/42494.txt, docs/acc-test-environment-variables.md, internal/service/controltower/control.go, internal/service/controltower/control_test.go, internal/service/controltower/controltower_test.go
Previously, removal of a configured `parameters` block would result in an error due to the update request body being serialized with a nil `Parameters` argument rather than an empty array. This change now returns an empty slice from the `parameters` expander when no value is configured.
Closes #42485
```console
% TF_AWS_CONTROLTOWER_CONTROL_OU_NAME=<redacted> make testacc PKG=controltower TESTS=TestAccControlTower_serial/Control/
TF_ACC=1 go1.23.8 test ./internal/service/controltower/... -v -count 1 -parallel 20 -run='TestAccControlTower_serial/Control/'  -timeout 360m -vet=off
2025/05/05 16:50:01 Initializing Terraform AWS Provider...
=== RUN   TestAccControlTower_serial
=== PAUSE …
```
=> r/aws_controltower_control: handle removal of parameters block

website/docs/r/codebuild_project.html.markdown
As mentioned in #42488 the documentation for resource [`aws_codebuild_project`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/codebuild_project) misses a valid value for `environment.compute_type`.
This pull request 
- adds the missing value `BUILD_GENERAL1_XLARGE`
- removes no longer valid information:
> `BUILD_GENERAL1_SMALL` is only valid   if `type` is set to `LINUX_CONTAINER`.
`BUILD_GENERAL1_SMALL`  works also with `ARM_CONTAINER`, `ARM_EC2`, `LINUX_EC2`, and `LINUX_GPU_CONTAINER`.
>When `type` is set to `LINUX_GPU_CONTAINER`, `compute_type` must be  `BUILD_GENERAL1_LARGE`
`LINUX_GPU_CONTAINER` works also with `BUILD_GENERAL1_SMALL`
- adds under `environment.compute_type` a link to the AWS documentation on combinations/ restrictions for compute and …
=> docs: update environment and compute type details for codebuild project

website/docs/r/cloudwatch_metric_alarm.html.markdown
For creating a CloudWatch Alarm with Anomaly Detection, the example in the current documentation does not work. (At least did not for me, and as far as I can see, there are a lot of confusion about the usage of `return_data` attribute due to AWS documentation saying "only one metric should set this to `true`", but that's apparently not the case for alarms with anomaly detection)
If only the `metric_query` block with the anomaly detection expression has `return_data` set to `true`, we get;
`Error: creating CloudWatch Metric Alarm (<redacted>): operation error CloudWatch: PutMetricAlarm, https response error StatusCode: 400, RequestID: <redacted>, api error ValidationError: Exactly two elements of the metrics list should return data.`
If only the `metric_query` block with the actual metric …
=> docs: fix cloudwatch alarm example for anomaly detection

website/docs/r/glue_partition.html.markdown
See line 28 - should be `partition_values` not `values`
This fixes a small typo in the website docs.  The correct parameter is `partition_values` but the example currently uses `values`
Closes #0000
```console
...
```
=> Glue Partition Documentation Typo Fix

website/docs/r/lambda_event_source_mapping.html.markdown
* fix typos in the documentation of `aws_lambda_event_source_mapping`
* `maximum_poller` and `mimimum_poller` in the example should be plural
* I confirmed by reviewing implementation and document that they should be plural.
Closes #42570 
Implementation in the source codes:
https://github.com/hashicorp/terraform-provider-aws/blob/d45a5fde7cafea5cf8549f15bcdc3128ff3f36a3/internal/service/lambda/event_source_mapping.go#L264-L284
=> [document typo fix] aws_lambda_event_source_mapping: `maximum_poller` and `mimimum_poller` in the example to be plural

.changelog/42563.txt, internal/service/docdb/cluster.go, internal/service/docdb/cluster_test.go, website/docs/r/docdb_cluster.html.markdown
This PR adds support for the `manage_master_user_password` argument to the `aws_docdb_cluster` resource, allowing users to manage their DocumentDB master user password through AWS Secrets Manager rather than storing it as plaintext in Terraform state.
- Added the `manage_master_user_password` boolean parameter to the resource schema (defaults to false)
- Added a computed `master_user_secret` attribute that returns information about the secret in Secrets Manager when enabled
- Updated validation logic to make `master_password` optional when `manage_master_user_password` is set to true
Closes #41115
- Definition of `ManageMasterUserPassword` in `CreateDBClusterInput`: https://github.com/aws/aws-sdk-go-v2/blob/main/service/docdb/api_op_CreateDBCluster.go#L127
- Definition of …
=> r/aws_docdb_cluster: add support for `manage_master_user_password` argument 

.changelog/42536.txt, internal/service/sagemaker/exports_test.go, internal/service/sagemaker/image_version.go, internal/service/sagemaker/image_version_migrate.go, internal/service/sagemaker/image_version_test.go, internal/service/sagemaker/status.go, internal/service/sagemaker/wait.go, website/docs/guides/version-6-upgrade.html.markdown, website/docs/r/sagemaker_image_version.html.markdown
Previously the read operation would always retrieve the latest image version matching the `image_name` argument, rather than tracking the version created by a given resource instance. This change updates the `id` attribute to a comma-delimited string concatenating `image_name` and `version`, enabling subsequent read operations to correctly match the version created by this resource, and supporting import of existing versions which are not the most recently created. It also fixes issues observed when managing multiple image versions of the same name in a single workspace.
Closes #40597
Relates #41101
```console
% SAGEMAKER_IMAGE_VERSION_BASE_IMAGE="<redacted>" make testacc PKG=sagemaker TESTS=TestAccSageMakerImageVersion_ …
```
=> r/aws_sagemaker_image_version: read correct `version` after create

website/docs/r/rds_certificate.html.markdown
Corrects `aws_rds_certificate` import documentation
=> Corrects `aws_rds_certificate` import documentation

internal/service/backup/region_settings_test.go
Some time between 29 March and 12 April, AWS added `Redshift Serverless` to `aws_backup_region_settings`. This caused acceptance tests to fail.
```console
% make testacc PKG=backup TESTS=TestAccBackupRegionSettings_serial
--- PASS: TestAccBackupRegionSettings_serial (26.48s)
--- PASS: TestAccBackupRegionSettings_serial/basic (26.47s)
```
=> resource/aws_backup_region_settings: Fix error in acceptance test

.changelog/42624.txt, internal/framework/validators/objectvalidator/at_most_one_of_children.go, internal/framework/validators/objectvalidator/warn_at_most_one_of_children.go, internal/service/s3/bucket_lifecycle_configuration.go
No
Fixes `filter` validation to allow empty block
Closes #42515
Closes #42274
Closes #42112
```console
% make testacc PKG=s3 TESTS=TestAccS3BucketLifecycleConfiguration_
--- PASS: TestAccS3BucketLifecycleConfiguration_multipleRules_noFilterOrPrefix (87.79s)
--- PASS: TestAccS3BucketLifecycleConfiguration_multipleRules (88.12s)
--- PASS: TestAccS3BucketLifecycleConfiguration_removeRule (161.72s)
--- PASS: TestAccS3BucketLifecycleConfiguration_nonCurrentVersionTransition (162.27s)
--- PASS: TestAccS3BucketLifecycleConfiguration_nonCurrentVersionExpiration (163.40s)
--- PASS: TestAccS3BucketLifecycleConfiguration_RulePrefixToFilter (163.71s)
--- PASS: TestAccS3BucketLifecycleConfiguration_RulePrefix …
```
=> resource/aws_s3_bucket_lifecycle_configuration: Fixes `filter` validation to allow empty block

CHANGELOG.md
The **Post Publish** action, which adds a new _Unreleased_ CHANGELOG entry, [failed](https://github.com/hashicorp/terraform-provider-aws/actions/runs/15055797308) after yesterday's `v5.98.0` release (because the `v6.0.0-beta1` release is still the _semver_ latest).
Manually fix up the CHANGELOG.
=> Correct `v5.98.0` and `v5.99.0` CHANGELOG headings

docs/data-handling-and-conversion.md
Documents the recommended practice for the use of provider side default values. In general, arguments with server side default should store the value returned from AWS rather than setting a matching provider side default.
Relates #42598
=> docs: add default values recommendation

.github/workflows/pull_request_target.yml, GNUmakefile, docs/continuous-integration.md, docs/makefile-cheat-sheet.md
This PR:
* Fixes the CI workflow in .github/workflows/dependencies.yml so that it checks the actual changes in pull requests, not the base branch. The previous use of pull_request_target caused broken dependencies in PRs to go undetected. Switching to pull_request ensures accurate validation moving forward.
* Adds a CI check for use of pull_request_target except in approved places.
Relates #42543
Relates #42634
```console
% make pr-target-check 
make: Checking for pull request target...
make: pr-target-check passed.
```
=> Fix CI deps checks on main

GNUmakefile
This PR aligns the make file between v5 and v6.
Relates #42633
Relates #42543
```console
% make pr-target-check 
make: Checking for pull request target...
make: pr-target-check passed.
```
=> Align `make` between v5 and v6

.changelog/42631.txt, internal/service/dms/endpoint_test.go, internal/service/pipes/pipe_test.go, internal/service/redshift/cluster.go, internal/service/redshift/cluster_data_source_test.go, internal/service/redshift/cluster_iam_roles_test.go, internal/service/redshift/cluster_test.go, internal/service/redshift/consts.go, internal/service/redshift/endpoint_access_test.go, internal/service/redshift/endpoint_authorization_test.go, internal/service/redshift/logging.go, internal/service/redshift/logging_test.go, internal/service/redshift/snapshot_copy_test.go, internal/service/redshiftdata/statement_test.go, website/docs/guides/version-6-upgrade.html.markdown, website/docs/r/redshift_cluster.html.markdown, website/docs/r/redshift_logging.html.markdown
If a change needs to be reverted, we will publish an updated version of the provider.
None
AWS defaults to encryption at rest, but the default value of `encrypted` is `false`. This PR updates the default value to `true`. It also fixes a bug where encryption cannot be set to `false` on creation.
Additionally removes unneeded availability zone restrictions on acceptance tests.
Closes #42598
```console
...
```
=> resource/aws_redshift_cluster: Update default value of `encrypted` to `true` to match AWS default

.changelog/42726.txt, internal/service/elasticache/replication_group.go
Previously, if both `ConfigurationEndpoint` was nil and `NodeGroups` was an empty list, the provider would panic during the read operation while attempting to set port and endpoint address arguments. This change adds a check for empty `NodeGroups` to prevent `index out of range` errors under these conditions.
Closes #42720
```console
% make testacc PKG=elasticache TESTS=TestAccElastiCacheReplicationGroup_multiAzInVPC
TF_ACC=1 go1.23.9 test ./internal/service/elasticache/... -v -count 1 …
```
=> r/aws_elasticache_replication_group: fix crash reading empty node groups

.changelog/42733.txt, internal/acctest/state_id.go, internal/acctest/statecheck/expect_regional_arn_format.go, internal/acctest/statecheck/format.go, internal/service/ecs/cluster.go, internal/service/ecs/cluster_test.go, internal/service/ecs/service.go, internal/service/ecs/service_package_gen.go, internal/service/ecs/service_test.go, website/docs/r/ecs_service.html.markdown
The ECS resource types `aws_ecs_cluster` and `aws_ecs_service` have custom import functions that didn't handle Enhanced Regions.
```console
% make testacc PKG=ecs TESTS=TestAccECSCluster_
--- PASS: TestAccECSCluster_disappears (29.48s)
--- PASS: TestAccECSCluster_basic (31.56s)
--- PASS: TestAccECSCluster_Identity_Basic (33.16s)
--- PASS: TestAccECSCluster_Identity_RegionOverride (33.23s)
--- PASS: TestAccECSCluster_tags (48.86s)
--- PASS: TestAccECSCluster_configuration (54.73s)
--- PASS: TestAccECSCluster_containerInsights (64.95s)
--- PASS: TestAccECSCluster_managedStorageConfiguration (65.90s)
--- PASS: TestAccECSCluster_serviceConnectDefaults (133.08s)
```
```console
% make testacc PKG=ecs TESTS=TestAccECSService_
--- PASS: TestAccECSService_DeploymentControllerType_external (72.38s) …
```
=> ECS Enhanced Region import support

website/docs/r/quicksight_data_source.html.markdown
Not applicable - only documentation is updated.
None
The [2nd example](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/quicksight_data_source#s3-data-source-with-iam-role-arn) for the usage of resource [`aws_quicksight_data_source`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/quicksight_data_source) contains an invalid configuration. In below code it references `aws_s3_bucket.example.arn`, it should read `aws_s3_bucket.example.bucket`.
```hcl
resource "aws_quicksight_data_source" "example" {
data_source_id = "example-id"
name           = "manifest in S3"
parameters {
s3 {
manifest_file_location {
bucket = aws_s3_bucket.example.arn
key    = aws_s3_object.example.key
}
role_arn = aws_iam_role.example.arn
}
}
type = "S3"
}
``` …
=> fix: replace bucket arn with bucket name

.changelog/42719.txt, internal/service/logs/stream.go, internal/slices/options.go
Addresses a performance regression introduced in `v5.83.0` which can surface in log groups with large numbers of stream prefixes matching a stream name. The read operation will once again return the first stream with an exact name match, rather than exhausting the full list of results from the `DesribeLogStreams` API before asserting only a single result is found.
This fix introduces a `filterOptions` struct to prototype how a generic options structure that can be shared across finders might be designed. If we opt to extend this to finders in other packages we can migrate this struct and …
=> r/aws_cloudwatch_log_stream: return first match during read

internal/service/elbv2/errors.go, internal/service/elbv2/load_balancer.go
As https://github.com/hashicorp/terraform-provider-aws/pull/42685 introduced new IAM permission requirements, gracefully ignore `AccessDenied` errors from `DescribeCapacityReservation` during Read, e.g.
```
operation error Elastic Load Balancing v2: DescribeCapacityReservation, https response error StatusCode: 403, RequestID: 19ac3d93-272b-4134-9769-88316b3a3f39, api error AccessDenied: User: arn:aws:iam::123456789012:user/kit is not authorized to perform: elasticloadbalancing:DescribeCapacityReservation on resource: * with an explicit deny in an identity-based policy
```
```console
% …
```
=> r/aws_lb: Gracefully ignore `AccessDenied` errors from `DescribeCapacityReservation`

.changelog/42793.txt, internal/service/cognitoidp/user_pool.go
Prevents a crash when the `user_pool_add_ons.advanced_security_additional_flows` block is non-empty, but contains only a single `nil` value. For example,
```
Stack trace from the terraform-provider-aws_v5.98.0_x5.exe plugin:
panic: interface conversion: interface {} is nil, not map[string]interface {}
goroutine 31 [running]:
github.com/hashicorp/terraform-provider-aws/internal/service/cognitoidp.expandUserPoolAddOnsType(0xc003c0e450)
github.com/hashicorp/terraform-provider-aws/internal/service/cognitoidp/user_pool.go:1853 +0x1e9 …
```
=> r/aws_cognitoidp_user_pool: prevent crash with certain `user_pool_add_ons` values

website/docs/r/backup_region_settings.html.markdown
Updates to aws_backup_region_settings resource documentation. Adding recently added services, and updating links to AWS docs.
https://docs.aws.amazon.com/aws-backup/latest/devguide/backup-feature-availability.html
https://docs.aws.amazon.com/aws-backup/latest/devguide/whatisbackup.html#full-management
=> Update aws_backup_region_settings documentation

website/docs/r/quicksight_account_subscription.html.markdown
In #42457 a user noticed that Terraform encounters an error when creating an `aws_quicksight_account_subscription` with 
* `authentication method = "IAM_IDENTITY_CENTER"`  and 
* no `admin_group` argument 
provided.
The AWS documentation (link in reference section) states for `admin_group`
> The admin group associated with your Active Directory or IAM Identity Center account. Either this field or the AdminProGroup field is required if ACTIVE_DIRECTORY or IAM_IDENTITY_CENTER is the selected authentication method of the new Amazon QuickSight account.
I updated the documentation accordingly - also for the the author and reader groups - and left out the `AdminProGroup` part as the provider does not …
=> docs: update description for multiple groups

internal/generate/identitytests/resource_test.go.gtpl, internal/service/apigateway/domain_name_access_association.go, internal/service/apigateway/domain_name_access_association_tags_gen_test.go, internal/service/logs/anomaly_detector.go
If a change needs to be reverted, we will publish an updated version of the provider.
None
Some generated test code had missing Go imports, which causes `goimports` to take longer time.
=> test generation: Improves test generation time

internal/framework/types/listof.go, internal/framework/types/listof_test.go
To properly validate values in a list the `ValidateAttribute` interface must be implemented. This implements and adds custom validation for StringEnumTypes.
```go
names.AttrPermissions: schema.ListAttribute{
CustomType: fwtypes.ListOfStringEnumType[awstypes.ScopePermission](),
Optional: true,
},
```
Relates #42338
```console
go test -count=1 -v internal/framework/types/listof_test.go
=== RUN   TestListOfStringFromTerraform
=== PAUSE TestListOfStringFromTerraform
=== RUN   TestListOfValidateAttribute
=== PAUSE TestListOfValidateAttribute
=== CONT  TestListOfStringFromTerraform
=== CONT …
```
=> add ValidateAttribute to listOf custom type

.github/workflows/post_publish.yml, .github/workflows/registry-check.yml
This PR copies the initialization check workflow that was recently introduced in the AWSCC provider over to the mainline provider.
Relates https://github.com/hashicorp/terraform-provider-awscc/pull/2303
Relates https://github.com/hashicorp/terraform-provider-awscc/pull/2313
N/a, workflows
=> Split initialization check into a distinct workflow

.changelog/42896.txt, internal/service/logs/delivery.go, internal/service/logs/destination.go, internal/service/logs/group.go, internal/service/logs/metric_filter.go, internal/service/logs/query_definition.go, internal/service/logs/resource_policy.go, internal/service/logs/stream.go, internal/service/logs/subscription_filter.go, internal/slices/options.go
Prior to a recent refactoring of the finders in the `logs` package, the behavior of calls to paginated APIs was to return immediately upon finding a match to the provided filter (e.g. and exact log stream name). The refactor changed this behavior slightly to iterate over all pages of the response instead and assert that the filtered output contains only a single result. While this change ensures filters are written accurately (any filtered response containing multiple values will now trigger an error), it introduced a potential performance regression when paginating over large sets of …
=> r/aws_logs: add return first match option to resource finders

website/docs/r/lambda_function.html.markdown
No security controls are modified.
In the [documentation](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lambda_function) for the resource `aws_lambda_function` an invalid value `ERROR`  is specified for `system_log_level`.
Allowed values are defined in the SDK and used as part of the validation function.
```golang
type SystemLogLevel string
// Enum values for SystemLogLevel
const (
SystemLogLevelDebug SystemLogLevel = "DEBUG"
SystemLogLevelInfo  SystemLogLevel = "INFO"
SystemLogLevelWarn  SystemLogLevel = "WARN"
)
```
Closes #42893 
- [Validation function in provider](https://github.com/hashicorp/terraform-provider-aws/blob/d76c5d0ebf839e577b310753ba3e35f8f3bdf93a/internal/service/lambda/function.go#L269)
Not …
=> docs: replace invalid system log level in lambda function docs

website/docs/r/inspector2_filter.html.markdown
No security controls are modified.
The import statement for the resource [aws_inspector2_filter](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/inspector2_filter) uses `arn` instead of `id` as key:
```hcl
import {
to  = aws_inspector2_filter.example
arn = "arn:aws:inspector2:us-east-1:111222333444:owner/111222333444/filter/abcdefgh12345678"
}
```
This pull requests updates the import statement so that it no longer throws errors.
Closes #42889 
=> docs: update key in resource import statement

website/docs/r/bedrock_custom_model.html.markdown, website/docs/r/bedrock_provisioned_model_throughput.html.markdown
None
* Updated the import block references with incorrect attributes
```
=== bedrock_custom_model.html.markdown ===
model_id = "arn:aws:bedrock:us-west-2:123456789012:model-customization-job/amazon.titan-text-express-v1:0:8k/1y5n57gh5y2e"
=== bedrock_provisioned_model_throughput.html.markdown ===
model_id = "arn:aws:bedrock:us-west-2:123456789012:provisioned-model/1y5n57gh5y2e"
```
Same issues as in https://github.com/hashicorp/terraform-provider-aws/issues/42889
```console
...
```
=> docs: fix import block reference in bedrock resources

website/docs/r/glue_job.html.markdown
None.
The PR updates the examples for provisioning Glue jobs to support glueetl or pythonshell type workloads. 
Removes the ambiguity called out in https://github.com/hashicorp/terraform-provider-aws/issues/42302
Closes #42302 
```console
...
```
=> docs: glue_job examples for glueetl and pythonshell jobs

.changelog/42965.txt, internal/service/wafv2/flex.go, internal/service/wafv2/rule_group_test.go, internal/service/wafv2/schemas.go, internal/service/wafv2/web_acl_test.go, website/docs/r/wafv2_rule_group.html.markdown, website/docs/r/wafv2_web_acl.html.markdown
* Support `asn_match_statement` for WAF V2 statement in `aws_wafv2_web_acl` and `aws_wafv2_rule_group`.
* This block can also be used in `scope_down_statement` in `rate_based_statement`.
Closes #42895
* https://aws.amazon.com/jp/about-aws/whats-new/2025/06/asn-match-aws-waf/
* https://docs.aws.amazon.com/ja_jp/waf/latest/APIReference/API_Statement.html#WAF-Type-Statement-AsnMatchStatement
```console
% make testacc TESTS=TestAccWAFV2RuleGroup_ PKG=wafv2 
TF_ACC=1 go1.23.9 test …
```
=> [Enhancement] aws_wafv2_web_acl, aws_wafv2_rule_group: Support `asn_match_statement`

internal/conns/awsclient.go, internal/conns/awsclient_test.go
When connecting to non-Amazon, [AWS-compatible APIs](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/guides/custom-service-endpoints) the `AWSClient.partition` field may be empty. In these cases don't validate the top-level `region` argument.
=> Don't validate `region` if partition is empty

website/docs/r/grafana_workspace.html.markdown
No security controls have been modified.
The  example `Workspace configuration options` for the the resource [aws_grafana_workspace](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/grafana_workspace#example-usage) consists of code and a textual description. Both are out of sync for `unifiedAlerting`.  In the code `enabled`  is set to `false`, in the text it is mentioned that unified alerting is enabled:
```hcl
configuration = jsonencode(
{
"plugins" = {
"pluginAdminEnabled" = true
},
"unifiedAlerting" = {
"enabled" = false
}
}
)
}
```
>The optional argument configuration is a JSON string that enables the unified Grafana Alerting (Grafana version 10 or newer) and Plugins …
=> docs: fix textual description of the workspace configuration example

internal/framework/flex/autoflex.go, internal/generate/identitytests/resource_test.go.gtpl, internal/generate/servicepackage/service_package_gen.go.gtpl, internal/service/batch/job_definition_identity_gen_test.go, internal/service/batch/service_package_gen.go, internal/service/ec2/vpc_block_public_access_exclusion.go, internal/service/route53/record_test.go, internal/service/route53/service_package_gen.go, internal/vault/helper/pgpkeys/keybase.go
Disables Resource Identity for resource types with Mutable Identity, as it is not fully supported.
Includes fix to `modern-check` issue
=> Resource Identity: Disable for Mutable Identity

internal/provider/sdkv2/provider.go
Removes the Terraform 0.12 blockade added for v6.0.0 betas.
Because of the way the CHANGELOG is generated and the various `v6.0.0.beta` release we will have to fixup the CHANGELOG manually after release.
Closes https://github.com/hashicorp/terraform-provider-aws/issues/43071.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/41722.
```console
% make sane
make: Sane Smoke Tests (x tests of Top y resources)
2025/06/18 11:18:58 Creating …
```
=> Re-enable Terraform 0.12 support

.changelog/43014.txt, internal/service/quicksight/user.go, internal/service/quicksight/user_test.go
No changes to security controls by this pull request.
The resource `aws_quicksight_user` contains an argument `email`. 
At the moment the argument is configured with [`ForceNew`](https://github.com/hashicorp/terraform-provider-aws/blob/4e1ffae7052c85018b1d1546e4524eaa486e661d/internal/service/quicksight/user.go#L52).  Actually `email` can be updated without re-creating the resource, hence `ForceNew` is removed from the argument.
Closes #42944 
I updated the existing test `TestAccQuickSightUser_withInvalidFormattedEmailStillWorks`. When changing the e-mail address, a validation checks for an `update` action (instead of `delete, create`) on the resource.
```console
❯ make testacc TESTS=TestAccQuickSightUser …
```
=> feat: remove ForceNew for email

.changelog/42982.txt, internal/service/codebuild/project.go, internal/service/codebuild/project_test.go, website/docs/r/codebuild_project.html.markdown
* Add `docker_server` block to support remote Docker servers.
* The `status` field in the `DockerServer` object is documented as a request parameter. However, it appears to be used only in responses, not during create or update operations. Furthermore, it does not represent a persistent state. Therefore, `status` is not included in the Terraform schema.
Closes #42647 
https://aws.amazon.com/jp/blogs/aws/accelerate-ci-cd-pipelines-with-the-new-aws-codebuild-docker-server-capability/
https://docs.aws.amazon.com/codebuild/latest/APIReference/API_ProjectEnvironment.html#CodeBuild-Type-Project …
=> [Enhancement]: aws_codebuild_project: Support `docker_server` block for remote Docker servers

internal/provider/framework/identity_interceptor.go, internal/provider/sdkv2/identity_interceptor.go
When removing a resource during Read because it is not found, the Identity must not be set for Framework-based resource types. Skips setting Identity for both SDKv2- and Framework-based types.
=> Resource Identity: Don't set Identity when removing resource

website/docs/r/s3_bucket_policy.html.markdown
No security controls have been modified
- Updated the `website/docs/r/s3_bucket_policy.md` file
- Added a note warning users about the overwrite behavior when multiple policies are defined for the same bucket
- Emphasized the recommendation to manage only one policy per bucket
Closes #43060  
No Response
No Response
=> aws_s3_bucket_policy overwrite behavior clarification #43060

.changelog/43018.txt, internal/service/emr/cluster.go, internal/service/emr/cluster_test.go, website/docs/r/emr_cluster.html.markdown
n/a
This PR is to add the `os_release_label` argument to the `aws_emr_cluster` resource.
Note that there are three existing acceptance test case failures described below, but they are unrelated to this PR.
Closes #42977
Referred to [RunJobFlow](https://docs.aws.amazon.com/emr/latest/APIReference/API_RunJobFlow.html) for specs and wordings.
Note that there are three unrelated test case that failed:
- `TestAccEMRCluster_ebs` and `TestAccEMRCluster_CustomAMI_id` failed because the core and primary instances kept failing bootstrap with a timeout. I suspect this is related to the release and application being included in the configuration. I am not familiar with EMR enough to continue troubleshooting.
- …
=> feat: Add os_release_label arg to aws_emr_cluster

website/docs/r/guardduty_detector_feature.html.markdown
n/a
This PR is to update the `aws_guardduty_detector` resource documentation with information about the extended threat detection for EKS feature and an example usage for it (which effectively amounts to enabling EKS protection and EKS runtime monitoring).
Closes #43082
Referred to the [announcement blog post](https://aws.amazon.com/blogs/aws/amazon-guardduty-expands-extended-threat-detection-coverage-to-amazon-eks-clusters/) and associated documentation for specs and wordings.
n/a
=> docs: Add extended threat detection for EKS info and example to aws_guardduty_detector_feature doc

.changelog/43139.txt, internal/service/events/archive.go, internal/service/events/archive_test.go, website/docs/r/cloudwatch_event_archive.html.markdown
n/a
This PR is to add the `kms_key_identifier` argument to the `aws_cloudwatch_event_archive` resource.
Closes #43050
Referred to [CreateArchive](https://docs.aws.amazon.com/eventbridge/latest/APIReference/API_CreateArchive.html) and [Archive](https://docs.aws.amazon.com/eventbridge/latest/APIReference/API_Archive.html) for specs and wordings.
```console
$ make testacc TESTS=TestAccEventsArchive_ PKG=events
TF_ACC=1 go1.24.4 test ./internal/service/events/... -v -count 1 -parallel 20 -run='TestAccEventsArchive_'  -timeout 360m -vet=off
2025/06/22 23:44:38 Creating Terraform AWS Provider (SDKv2-style)... …
```
=> feat: Add kms_key_identifier arg to aws_cloudwatch_event_archive

.changelog/43183.txt, internal/service/logs/query_definition.go, internal/service/logs/query_definition_test.go
N/A
This pull request enhances the `aws_cloudwatch_query_definition` resource by adding support for specifying log group ARNs in addition to log group names. It also introduces a new acceptance test to validate this functionality.
* Updated the `log_group_names` schema to allow validation of both log group names and ARNs using `validation.Any`. This ensures compatibility with ARNs while maintaining support for log group names. (`internal/service/logs/query_definition.go`, [internal/service/logs/query_definition.goL55-R58](diffhunk://#diff-484ed3d559befc5b790fbc050763e6473a4996c4003cd21259534379c672895aL55-R58))
* Added a new acceptance test, `TestAccLogsQueryDefinition_logGroupARNs`, to verify the …
=> Fix: add ARN support in log_group_names for aws_cloudwatch_query_definition

.changelog/43252.txt, internal/service/cognitoidp/user_pool_domain.go, internal/service/cognitoidp/user_pool_domain_test.go
No changes to security controls
The aim of this PR is to allow changes to the managed login version for custom Cognito domains.
Requests to update the managed login version for custom domains without a certificate arn fail with 
> An error occurred (InvalidParameterException) when calling the UpdateUserPoolDomain operation: Cannot convert custom domain to prefix domain.
This happens from terraform and the aws cli. This means the aws provider should send the certificate arn if it's a custom domain. 
Closes #43248
Running only the new test for cost concerns.
```console
% make testacc TESTS=TestAccCognitoIDPUserPoolDomain_customCustomDomainManagedLoginVersionUpdate PKG=cognitoidp
make: Verifying source code …
```
=> Fix: Managed login version updates for custom Cognito domains

.changelog/43222.txt, internal/service/amp/exports_test.go, internal/service/amp/query_logging_configuration.go, internal/service/amp/query_logging_configuration_test.go, internal/service/amp/service_package_gen.go, website/docs/r/prometheus_query_logging_configuration.html.markdown
No
This implement Terraform support for new AWS APIs including https://docs.aws.amazon.com/prometheus/latest/APIReference/API_CreateQueryLoggingConfiguration.html
Closes https://github.com/hashicorp/terraform-provider-aws/issues/42776
```console
% make build && make testacc TESTARGS='-run=TestAccAMPQueryLoggingConfiguration' PKG=amp ACCTEST_PARALLELISM=5
make: Building provider...
TF_ACC=1 …
```
=> [New resource] Support for amp_query_logging_configuration

.changelog/43270.txt, internal/service/dms/endpoint_test.go, internal/service/events/target_test.go, internal/service/firehose/delivery_stream_test.go, internal/service/pipes/pipe_test.go, internal/service/redshift/cluster_credentials_data_source_test.go, internal/service/redshift/cluster_data_source_test.go, internal/service/redshift/cluster_iam_roles_test.go, internal/service/redshift/cluster_test.go, internal/service/redshift/logging_test.go, internal/service/redshift/orderable_cluster_data_source_test.go, internal/service/redshift/scheduled_action_test.go, internal/service/redshift/snapshot_copy_test.go, internal/service/redshiftdata/statement_test.go
Most acceptance tests using `aws_redshift_cluster` use a `node_type` of `dc2.*`, which is no longer available. Switch to `ra3.*`.
Also correctly sets `availability_zone_relocation_enabled` in API calls.
Some acceptance tests still fail due to `ra3.*` instances need completed snapshots, unlike `dc2.*` instances.
Closes #43268
=> resource/aws_redshift_cluster: Update `node_type` to valid value

internal/service/apigateway/domain_name_access_association_test.go, internal/service/batch/job_queue_test.go, internal/service/bedrock/provisioned_model_throughput_test.go, internal/service/codeconnections/connection_test.go, internal/service/codeconnections/host_test.go, internal/service/docdbelastic/cluster_test.go, internal/service/dynamodb/resource_policy_test.go, internal/service/globalaccelerator/cross_account_attachment_test.go, internal/service/imagebuilder/lifecycle_policy_test.go, internal/service/kinesis/resource_policy_test.go, internal/service/networkfirewall/tls_inspection_configuration_test.go, internal/service/paymentcryptography/key_test.go, internal/service/shield/application_layer_automatic_response_test.go
Converts `ExistingResource` tests to `resource.ParallelTest`
=> Converts `ExistingResource` tests to `resource.ParallelTest`

internal/service/elasticache/cluster.go, internal/service/elasticache/cluster_data_source_test.go, internal/service/elasticache/cluster_test.go, internal/service/elasticache/global_replication_group.go, internal/service/elasticache/global_replication_group_test.go, internal/service/elasticache/parameter_group.go, internal/service/elasticache/parameter_group_test.go, internal/service/elasticache/replication_group.go, internal/service/elasticache/replication_group_data_source_test.go, internal/service/elasticache/replication_group_test.go, internal/service/elasticache/reserved_cache_node.go, internal/service/elasticache/reserved_cache_node_offering_data_source_test.go, internal/service/elasticache/reserved_cache_node_test.go, internal/service/elasticache/serverless_cache.go, internal/service/elasticache/serverless_cache_data_source_test.go, internal/service/elasticache/serverless_cache_test.go, internal/service/elasticache/subnet_group.go, internal/service/elasticache/subnet_group_data_source_test.go, internal/service/elasticache/subnet_group_test.go, internal/service/elasticache/user.go, internal/service/elasticache/user_data_source_test.go, internal/service/elasticache/user_group.go, internal/service/elasticache/user_group_association.go, internal/service/elasticache/user_group_association_test.go, internal/service/elasticache/user_group_test.go, internal/service/elasticache/user_test.go, internal/vcr/.semgrep-vcr.yml
Enables Go-VCR in the `elasticache` service.
```console
% VCR_MODE=REPLAY_ONLY VCR_PATH=/Users/jaredbaker/development/_worktrees/td-vcr-elasticache/testdata/ make testacc PKG=elasticache TESTS=TestAccElastiCacheCluster_Engine_redis
TF_ACC=1 go1.24.4 test ./internal/service/elasticache/... -v -count 1 -parallel 20 -run='TestAccElastiCacheCluster_Engine_redis'  -timeout 360m -vet=off
2025/06/26 15:19:45 Creating Terraform AWS Provider (SDKv2-style)...
2025/06/26 15:19:45 Initializing …
```
=> Go-VCR: support `elasticache`

internal/service/ssoadmin/application_access_scope_test.go, internal/service/ssoadmin/application_assignment_test.go, internal/service/ssoadmin/application_assignments_data_source_test.go, internal/service/ssoadmin/application_data_source_test.go, internal/service/ssoadmin/principal_application_assignments_data_source_test.go, internal/service/ssoadmin/testdata/ApplicationAssignmentConfiguration/basic/main_gen.tf, internal/service/ssoadmin/testdata/ApplicationAssignmentConfiguration/region_override/main_gen.tf, internal/service/ssoadmin/testdata/tmpl/application_assignment_configuration_basic.gtpl, website/docs/d/ssoadmin_application_assignments.html.markdown, website/docs/r/ssoadmin_application_access_scope.html.markdown, website/docs/r/ssoadmin_application_assignment.html.markdown, website/docs/r/ssoadmin_application_assignment_configuration.html.markdown
Update tests and documentation to use `arn` instead of `application_arn` for `aws_ssoadmin_application`
Relates #43261
=> ssoadmin: Update tests and documentation to use `arn` instead of `application_arn` for `aws_ssoadmin_application`

.changelog/42562.txt, internal/service/route53profiles/resource_association.go, internal/service/route53profiles/resource_association_test.go
Mark `aws_route53profiles_resource_association` `resource_properties` attribute as Computed to enable `aws_vpc_endpoint` association.
Closes #42558
Closes #42489
```console
% make testacc TESTS=TestAccRoute53ProfilesResourceAssociation_vpcEndpoint PKG=route53profiles 
TF_ACC=1 go1.23.8 test ./internal/service/route53profiles/... -v -count 1 -parallel 20 -run='TestAccRoute53ProfilesResourceAssociation_vpcEndpoint'  -timeout 360m -vet=off
2025/05/10 11:38:58 Initializing Terraform AWS Provider...
=== RUN   TestAccRoute53ProfilesResourceAssociation_vpcEndpoint
=== PAUSE TestAccRoute53ProfilesResourceAssociation_vpcEndpoint
=== CONT  TestAccRoute53ProfilesResourceAssociation_vpcEndpoint
--- …
```
=> fix: mark aws_route53profiles_resource_association resource_properties as Computed

.changelog/43355.txt, internal/service/bedrockagent/agent_action_group.go, internal/service/bedrockagent/agent_action_group_test.go
Fix read of `parent_action_group_signature` as the field is named differently in input and outputs.
Closes #43045
```console
% make testacc TESTARGS='-run=TestAccBedrockAgentAgentActionGroup_' PKG=bedrockagent ACCTEST_PARALLELISM=4
make: Verifying source code with gofmt...               <aws:terraform-testing>
TF_ACC=1 go1.24.4 test ./internal/service/bedrockagent/... -v -count 1 -parallel 4  -run=TestAccBedrockAgentAgentActionGroup_ -timeout 360m -vet=off
2025/07/11 13:26:56 Creating Terraform AWS Provider (SDKv2-style)... …
```
=> [Bug] Fix read back of `parent_action_group_signature`

website/docs/r/cloudfront_distribution.html.markdown
No security controls are modified.
The example [With Managed Caching Policy](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudfront_distribution#with-managed-caching-policy) for resource `aws_cloudfront_distribution` is missing required fields in `default_cache_behavior`.
When trying to run the example code below errors are reported
-  The argument ["viewer_protocol_policy"](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudfront_distribution#viewer_protocol_policy-1) is required, but no definition was found.
- The argument ["cached_methods"](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudfront_distribution#cac …
=> docs: add required attributes to example

website/docs/r/lambda_permission.html.markdown
This PR improves the documentation for the `aws_lambda_permission` resource by specifying that the function ARN is also a possible value for the `function_name` argument, as seen [here](https://github.com/hashicorp/terraform-provider-aws/blob/229b588b9676522d110ebdf0accffa821aef6b51/website/docs/r/config_organization_custom_rule.html.markdown?plain=1#L22) for example.
=> Add possible `ARN` value for `function_name` in `aws_lambda_permission` resource

website/docs/d/bedrock_inference_profiles.html.markdown
Removed two words from the documentation which says the string  "AWS Bedrock" twice back-to-back.
=> Remove duplicated words from the aws_bedrock_inference_profiles documentation

.changelog/43377.txt, internal/service/lakeformation/resource.go, internal/service/lakeformation/resource_data_source.go, internal/service/lakeformation/resource_data_source_test.go, internal/service/lakeformation/resource_test.go, website/docs/d/lakeformation_resource.html.markdown, website/docs/r/lakeformation_resource.html.markdown
* Added the `with_privileged_access` argument to the `aws_lakeformation_resource` resource.
* Added the following attributes to the `aws_lakeformation_resource` data source:
* `hybrid_access_enabled`
* `with_federation`
* `with_privileged_access`
Closes #43334 
https://docs.aws.amazon.com/lake-formation/latest/APIReference/API_RegisterResource.html#lakeformation-RegisterResource-request-WithPrivilegedAccess
```console
$ make testacc TESTS=TestAccLakeFormationResource_withPrivilegedAccessEnabled PKG=lakeformation
==> Checking that code complies …
```
=> [Enhancement] aws_lakeformation_resource: support `with_privileged_access` argument

internal/service/logs/sweep.go
Adds a sweeper for the `aws_cloudwatch_log_account_policy` resource.
Detected while testing #43332 
```console
% make sweep SWEEPARGS="-sweep-run=aws_cloudwatch_log_account_policy"
go1.24.5 test ./internal/sweep -v -sweep=us-west-2,us-east-1,us-east-2,us-west-1 -sweep-run=aws_cloudwatch_log_account_policy -timeout 360m -vet=off
2025/07/16 09:45:55 [DEBUG] Running Sweepers for region (us-west-2):
2025/07/16 09:45:55 [DEBUG] Running Sweeper (aws_cloudwatch_log_account_policy) in region (us-west-2)
2025/07/16 …
```
=> r/aws_cloudwatch_log_account_policy: add sweeper

.changelog/43415.txt, internal/service/s3/bucket_public_access_block.go, internal/service/s3/bucket_public_access_block_test.go, website/docs/r/s3_bucket_public_access_block.html.markdown
This optional argument will enable use cases where practitioners want to leave a public access block in-place during a `destroy` operation. Setting `skip_destroy` to `true` can replace the manual `terraform state rm` operations many users have reported utilizing in the linked issue related to GuardDuty alerts.
For example:
```hcl
resource "aws_s3_bucket_public_access_block" "test" {
bucket = aws_s3_bucket.test.bucket
block_public_acls       = true
block_public_policy     = true
ignore_public_acls      = true
restrict_public_buckets = true
skip_destroy = true
}
```
Closes #12153 …
=> r/aws_s3_bucket_public_access_block: add `skip_destroy` argument

website/docs/r/ssm_association.html.markdown
No changes to security controls are applied
The code blocks for the examples 
- [Create an association with multiple instances with their instance ids](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ssm_association#create-an-association-with-multiple-instances-with-their-instance-ids) and 
- [Create an association with multiple instances with their values matching their tags](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ssm_association#create-an-association-with-multiple-instances-with-their-values-matching-their-tags) 
are missing the language identifier `terraform`. Hence the HTML rendering is not as expected.
This PR ass the required …
=> docs: add missing code block identifiers for aws_ssm_association resource documentation

website/docs/d/secretsmanager_secret_rotation.html.markdown
N/A
No changes.
Should fix up incorrect documentation relating to aws_secretsmanager_secret_rotation data source attributes [here](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/secretsmanager_secret_rotation#attribute-reference)
Closes #42781
N/A
N/A
=> Documentation - data source aws_secretsmanager_secret_rotation attributes fix

internal/service/elasticbeanstalk/application_version_test.go, internal/service/elasticbeanstalk/environment_test.go
n/a
This PR is to fix the references to `aws_s3_object` attributes in `internal/service/elasticbeanstalk/application_version_test.go` and `internal/service/elasticbeanstalk/environment_test.go`.
Relates #43420
n/a
For `application_version_test.go`:
```console
$ make testacc TESTS=TestAccElasticBeanstalkApplicationVersion_ PKG=elasticbeanstalk
TF_ACC=1 go1.24.5 test ./internal/service/elasticbeanstalk/... -v -count 1 -parallel 20 -run='TestAccElasticBeanstalkApplicationVersion_'  -timeout 360m -vet=off
2025/07/20 16:57:01 Creating Terraform AWS Provider (SDKv2-style)...
2025/07/20 16:57:01 Initializing …
```
=> fix: Fix aws_s3_object attr references in aws_elasticbeanstalk tests

website/docs/r/bedrockagent_agent_collaborator.html.markdown
Fixes #43380
Corrected a spelling mistake in the documentation for the `aws_bedrock_agent_collaborator` resource.
Replaced `collbaorator_name` with the correct spelling `collaborator_name`.
=> Fix typo in aws_bedrock_agent_collaborator documentation

website/docs/r/lb_listener.html.markdown
Hello! Thank you for maintaining this provider👍 
This PR adds a comprehensive example for configuring ALB listener default forward actions with weighted target groups to the `aws_lb_listener` resource documentation.
ALB listeners support weighted target groups for default actions. The `target_group_arn` parameter documentation states:
> To route to one or more target groups, use a forward block instead.
This means users should use `forward` block instead of `target_group_arn` for weighted routing, but there is no complete example showing how to actually implement this configuration. …
=> r/lb_listener(doc): Add weighted target groups example

.changelog/43158.txt, internal/service/ec2/ec2_instance.go, internal/service/ec2/ec2_instance_test.go
No changes
Updates `aws_instance` so that `ipv6_addresses` are recomputed when `ipv6_address_count` is updated.
In order to achieve this, I needed to remove `ForceNew` from `ipv6_addresses`, but reimplemented the functionality via `customdiff.ForceNewIf`.
The `TestAccEC2Instance_IPv6AddressesExplicit` test may be overkill -- since the instance is recreated when `ipv6_addresses` is explicitly changed, `ipv6_address_count` should inherently be recomputed since it's a new instance. I introduced it anyways, to make sure that the `customdiff.ForceNewIf` did what I was expecting.
I also updated the name of the `TestAccEC2Instance_IPv6AddressCountAndSingleAddressCausesError` test function in order to make it …
=> `aws_instance`: fix `ipv6_addresses` / `ipv6_addresses_count` refresh

.changelog/43215.txt, internal/service/apigateway/resource.go, internal/service/apigateway/resource_test.go
No changes
Recomputes `path` when `path_part` is updated. Helps prevent situations where downstream resources are dependent on the `path` attribute requiring two applies.
Closes #42904
```console
$ make testacc TESTS=TestAccAPIGatewayResource_ PKG=apigateway
TF_ACC=1 go1.24.4 test ./internal/service/apigateway/... -v -count 1 -parallel 20 -run='TestAccAPIGatewayResource_'  -timeout 360m -vet=off
2025/06/27 11:08:35 Creating Terraform AWS Provider (SDKv2-style)...
2025/06/27 11:08:35 Initializing Terraform AWS Provider (SDKv2-style)...
=== RUN   TestAccAPIGatewayResource_basic
=== PAUSE …
```
=> `aws_api_gateway_resource`: recompute `path` when `path_part` changes

.changelog/43471.txt, internal/service/bedrockagent/flow.go
No changes to security controls
This removes the limits on the number of nodes and connections within a flow. It is possible to create a flow which exceed the limits currently defined in the validators.
Closes #43470
```console
% make testacc TESTS=TestAccBedrockAgentFlow PKG=bedrockagent
TF_ACC=1 go1.24.5 test ./internal/service/bedrockagent/... -v -count 1 -parallel 20 -run='TestAccBedrockAgentFlow'  -timeout 360m -vet=off
2025/07/21 15:53:44 Creating Terraform AWS Provider (SDKv2-style)...
2025/07/21 15:53:44 Initializing Terraform AWS Provider (SDKv2-style)...
=== RUN   TestAccBedrockAgentFlow_basic …
```
=> Remove flow node/connection limits

internal/provider/framework/identity_interceptor.go, internal/provider/framework/identity_interceptor_test.go, internal/provider/framework/importer/parameterized.go, internal/provider/framework/importer/parameterized_test.go, internal/provider/sdkv2/importer/parameterized_test.go, internal/types/service_package.go
Adds attribute name mapping for Framework resource types. Name mapping was added to SDKv2 resource types in #43476
=> Resource Identity: Adds attribute name mapping for Framework resource types

.changelog/433245.txt, internal/service/wafv2/flex.go, internal/service/wafv2/rule_group.go, internal/service/wafv2/rule_group_test.go, website/docs/r/wafv2_rule_group.html.markdown
Added `rule_json` attribute  to the `aws_wafv2_rule_group` resource.
Relates #38309
```console
TF_ACC=1 go1.24.4 test ./internal/service/wafv2/... -v -count 1 -parallel 20 -run='TestAccWAFV2RuleGroup'  -timeout 360m -vet=off
2025/07/15 15:10:10 Creating Terraform AWS Provider (SDKv2-style)...
2025/07/15 15:10:10 Initializing Terraform AWS Provider (SDKv2-style)...
=== RUN   TestAccWAFV2RuleGroupDataSource_basic
=== PAUSE TestAccWAFV2RuleGroupDataSource_basic
=== RUN   TestAccWAFV2RuleGroup_basic
=== PAUSE TestAccWAFV2RuleGroup_basic
=== RUN   TestAccWAFV2RuleGroup_nameGenerated
=== PAUSE …
```
=> New Attribute for r/wafv2_rule_group: rule_json attribute

.changelog/43506.txt, internal/service/wafv2/flex.go, internal/service/wafv2/schemas.go, internal/service/wafv2/web_acl_test.go, website/docs/r/wafv2_web_acl.html.markdown
* Added `asn` (empty block) as `custom_key` to `rate_based_statement`.
Closes #43492 
https://docs.aws.amazon.com/ja_jp/waf/latest/APIReference/API_RateBasedStatementCustomKey.html#WAF-Type-RateBasedStatementCustomKey-ASN
```console
$ make testacc TESTS=TestAccWAFV2WebACL_ PKG=wafv2 
TF_ACC=1 go1.24.5 test ./internal/service/wafv2/... -v -count 1 -parallel 20 -run='TestAccWAFV2WebACL_'  -timeout 360m -vet=off
2025/07/23 07:37:39 Creating Terraform AWS Provider (SDKv2-style)...
2025/07/23 …
```
=> [Enhancement] aws_wafv2_web_acl: Support `asn` custom key in `rate_based_statement`

internal/generate/servicepackage/main.go, internal/generate/servicepackage/service_package_gen.go.gtpl, internal/provider/sdkv2/identity_interceptor.go, internal/provider/sdkv2/importer/arn.go, internal/provider/sdkv2/importer/arn_test.go, internal/provider/sdkv2/importer/context.go, internal/provider/sdkv2/importer/parameterized.go, internal/provider/sdkv2/importer/parameterized_test.go, internal/provider/sdkv2/provider.go, internal/service/acmpca/certificate.go, internal/service/acmpca/certificate_authority.go, internal/service/acmpca/service_package_gen.go, internal/service/batch/job_definition.go, internal/service/iam/role.go, internal/service/iam/service_package_gen.go, internal/service/organizations/account.go, internal/service/organizations/organization.go, internal/service/organizations/policy.go, internal/service/organizations/service_package_gen.go, internal/service/s3/bucket.go, internal/service/s3/service_package_gen.go, internal/types/service_package.go
Passes Identity Spec to SDKv2 custom imports rather than requiring developers to hardcode the Identity attributes in the custom import function.
Adds `@CustomImport` annotation
Builds on #43496
=> Resource Identity: Passes Identity Spec to SDKv2 custom imports

.changelog/43501.txt, internal/service/quicksight/account_subscription.go, internal/service/quicksight/account_subscription_test.go, website/docs/r/quicksight_account_subscription.html.markdown
This resource can now be imported via the `aws_account_id` argument.
Closes #43351
```console
% make testacc PKG=quicksight TESTS="TestAccQuickSight_serial/AccountSubscription/"
TF_ACC=1 go1.24.5 test ./internal/service/quicksight/... -v -count 1 -parallel 20 -run='TestAccQuickSight_serial/AccountSubscription/'  -timeout 360m -vet=off
2025/07/22 15:34:57 Creating Terraform AWS Provider (SDKv2-style)...
2025/07/22 15:34:57 Initializing Terraform AWS Provider (SDKv2-style)...
--- PASS: …
```
=> r/aws_quicksight_account_subscription: add import support

.changelog/43502.txt, internal/service/ecs/service.go, internal/service/ecs/service_test.go
This PR addresses an issue with the ECS Service provider's stabilization logic for Terraform. The problem occurred during in-place updates where the primary deployment being updated was more than 3 months old. The ListServiceDeployments API call, which is used to obtain the primary deployment ARN, filters using a CreatedAt attribute that must be within 3 months from now.
The solution introduces a new approach to handle both new deployments and in-place updates:
1.    For new deployments (including those resulting from changes to immutable properties), we use the new stabilization logic …
=> Fixes in-place UpdateService stabilization

.changelog/41702.txt, internal/service/cognitoidp/resource_server.go, internal/service/cognitoidp/resource_server_test.go
Allow updates to the name (which is really just a description) of the cognito resource server without deleting and recreating it.
Closes #41347 
```console
% make testacc TESTS=TestAccCognitoIDPResourceServer PKG=cognitoidp
TF_ACC=1 go1.23.5 test ./internal/service/cognitoidp/... -v -count 1 -parallel 20 -run='TestAccCognitoIDPResourceServer'  -timeout 360m -vet=off
2025/03/06 09:32:09 Initializing Terraform AWS Provider...
=== RUN   TestAccCognitoIDPResourceServer_basic
=== PAUSE TestAccCognitoIDPResourceServer_basic
=== RUN   TestAccCognitoIDPResourceServer_disappears
=== PAUSE TestAccCognitoIDPResourceServer_disappears
=== RUN   TestAccCognitoIDPResourceServer_scope
=== PAUSE …
```
=> r/cognito_resource_server allow name change without ForceNew

.changelog/43523.txt, internal/service/appsync/api_cache.go, internal/service/appsync/api_cache_test.go
* Fixed the update process to avoid "missing required field" errors, reported by #43519 .
* `apiCachingBehavior`, `ttl`, and `type` are required attributes for the `UpdateApiCache` action, but they were previously only specified when changes were detected.
* Added an acceptance test to validate the update process.
Closes #43519 
https://docs.aws.amazon.com/appsync/latest/APIReference/API_UpdateApiCache.html
```console
$ make testacc TESTS=TestAccAppSync_serial/ApiCache PKG=appsync …
```
=> [bug fix] aws_appsync_api_cache: Fix "missing required field" errors during update

.changelog/43558.txt, internal/service/ecs/service.go, internal/service/ecs/service_test.go
* Fixed the expander and flattener for the `test_listener_rule` argument in the `load_balancer.advanced_configuration` block to treat it as optional and allow it to be unspecified.
* Previously, an unspecified `test_listener_rule` was incorrectly set as an empty string in the `load_balancer.advanced_configuration` block.
Closes #43552
```console
$ make testacc TESTS=TestAccECSService_ PKG=ecs                                           
TF_ACC=1 go1.24.5 test ./internal/service/ecs/... -v …
```
=> [bugfix] aws_ecs_service: Allow unspecified `test_listener_rule` in `load_balancer.advanced_configuration` block

internal/service/cloudfront/distribution.go, internal/service/datazone/domain.go, internal/service/ec2/tags.go, internal/service/ecs/cluster.go, internal/service/kms/grant.go, internal/service/kms/key.go, internal/service/lambda/permission.go, internal/service/sns/topic.go, internal/service/wafv2/rule_group.go, internal/service/wafv2/web_acl.go, internal/tfresource/retry.go
Use the new primitives in `internal/retry` (as a replacement for the SDKv2 `helper/retry` package) for `tfresource.RetryWhenIsOneOf(2|3|4)` and `tfresource.RetryWhenAWSErrCodeContains`.
Relates https://github.com/hashicorp/terraform-provider-aws/issues/42554.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/43267.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/43341.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/43412.
```console
% make testacc TESTARGS='-run=TestAccECSCluster_basic' PKG=ecs …
```
=> Technical debt: Use `internal/retry` for `tfresource.RetryWhenIsOneOf` and `tfresource.RetryWhenAWSErrCodeContains`

website/docs/r/transcribe_vocabulary.html.markdown
This pull request only updates the documentation. I noticed that the `vocabulary_file_uri` parameter is defined twice in the Markdown file, one instance is marked "Required", and the other "Optional". Because the implementation treats this parameter as optional, we should delete the first (required) entry.
=> Delete duplicated definition from transcribe_vocabulary.html.markdown

.changelog/43562.txt, internal/service/ssm/service_setting.go, internal/service/ssm/service_setting_test.go, website/docs/r/ssm_service_setting.html.markdown
* The `setting_id` for the `aws_ssm_service_setting` resource typically begins with the `/ssm/` prefix (referred to as the "short format" below), according to the [AWS documentation](https://docs.aws.amazon.com/systems-manager/latest/APIReference/API_GetServiceSetting.html#API_GetServiceSetting_RequestSyntax)
* However, the AWS API also accepts the full ARN format, and the current implementation of this resource assumes that `setting_id` is provided in that format.
* As reported in #43551, when `setting_id` is specified using the short format, the API call succeeds, but a difference …
=> [Enhancement] aws_ssm_service_setting: Fix perpetual diff issue by supporting short format (with `/ssm/` prefix) for `setting_id`

.changelog/43449.txt, internal/service/codebuild/fleet.go, internal/service/codebuild/fleet_data_source.go, internal/service/codebuild/fleet_data_source_test.go, internal/service/codebuild/fleet_test.go, website/docs/d/codebuild_fleet.html.markdown, website/docs/r/codebuild_fleet.html.markdown
* Added the `instance_type` argument to the `compute_configuration` block of the `aws_codebuild_fleet` resource, as well as to the `aws_codebuild_fleet` data source, to support custom instance types in fleets.
Closes #43384 
https://docs.aws.amazon.com/codebuild/latest/APIReference/API_CreateFleet.html
```console
$ make testacc TESTS=TestAccCodeBuildFleet_ PKG=codebuild               
TF_ACC=1 go1.24.5 test ./internal/service/codebuild/... -v -count 1 -parallel 20 …
```
=> [Enhancement] aws_codebuild_fleet: Support custom instance type in the fleet

.changelog/43452.txt, internal/service/verifiedpermissions/policy_store.go, internal/service/verifiedpermissions/policy_store_data_source.go, internal/service/verifiedpermissions/policy_store_data_source_test.go, internal/service/verifiedpermissions/policy_store_test.go, website/docs/d/verifiedpermissions_policy_store.html.markdown, website/docs/r/verifiedpermissions_policy_store.html.markdown
No changes to security controls.
Add deletion protection support for the Amazon Verified Permissions Policy Store.
Closes #43330
- [AWS What`s new](https://aws.amazon.com/about-aws/whats-new/2025/04/amazon-verified-permissions-policy-store-deletion-protection/?nc1=h_ls)
- [CreatePolicyStore API](https://docs.aws.amazon.com/verifiedpermissions/latest/apireference/API_CreatePolicyStore.html)
Resource
```console
❯ make testacc TESTS=TestAccVerifiedPermissionsPolicyStore  PKG=verifiedpermissions
TF_ACC=1 go1.24.5 test ./internal/service/verifiedpermissions/... -v -count 1 -parallel 20 …
```
=> feat: add deletion protection for verifiedpermissions_policy_store

.changelog/43606.txt, internal/service/servicequotas/service_quota.go
When a service quota increase is still pending, subsequent updates can produce the following error:
```console
ResourceAlreadyExistsException: Only one open service quota increase request is allowed per qu
```
Closes #0000
```console
% make testacc TESTARGS='-run=TestAccServiceQuotasServiceQuota_' PKG=servicequotas
TF_ACC=1 go1.24.5 test ./internal/service/servicequotas/... -v -count 1 -parallel 20  -run=TestAccServiceQuotasServiceQuota_ -timeout 360m -vet=off
2025/07/30 09:34:21 Creating …
```
=> r/aws_servicequotas_service_quota: fix error when updating pending quota increase

skaff/resource/resourcefw.gtpl
No
Line 363 of resourcefw.gtpl template contains following line:
```go
smerr.append(ctx, &resp.Diagnostics, fwdiag.NewResourceNotFoundWarningDiagnostic(err))
```
which does not compile.
The most suitable fix seems to be:
```go
smerr.EnrichAppend(ctx, &resp.Diagnostics, diag.Diagnostics{fwdiag.NewResourceNotFoundWarningDiagnostic(err)})
```
however, because smerr.EnrichAppend for passed in `WarningDiagnostic` still outputs `ErrorDiagnostic` it is not a valid solution because disappeared resources would cause error on plan.
The most suitable solution currently seems to be:
```go
resp.Diagnostics.Append(fwdiag.NewResourceNotFoundWarningDiagnostic(err))
```
which preserves `WarningDiagnostic ` nature of the …
=> fix: compilation errors in "resource not found" code in Read method

.changelog/43659.txt, internal/provider/framework/region.go, internal/provider/framework/region_test.go, internal/provider/sdkv2/region.go, internal/service/appfabric/app_bundle_test.go, internal/service/ec2/vpc_test.go, internal/service/s3control/access_point_test.go, internal/service/s3tables/table_test.go
No changes to security controls (access controls, encryption, logging) in this pull request.
Fixes `resourceSetRegionInStateInterceptor` preventing proper resource removal detection for Framework resources. The interceptor was setting region attributes on null state after
`RemoveResource()` was called, preventing Terraform from detecting disappeared resources correctly.
Closes #43655.
Closes https://github.com/hashicorp/terraform-provider-aws/issues/43537.
Closes https://github.com/hashicorp/terraform-provider-aws/issues/43323.
Closes https://github.com/hashicorp/terraform-provider-aws/issues/43530.
- Related to #42261 (improving "_disappears" test coverage) - this fix is a prerequisite
- Follows existing …
=> fix: setting the region after resource has been removed from state due resource disappearance

internal/service/emr/cluster_test.go, website/docs/r/emr_cluster.html.markdown
n/a
This PR is for removing the test case `TestAccEMRCluster_visibleToAllUsers` which is no longer relevant because the `visible_to_all_user` argument is no longer supported on AWS side. A note is added to the resource doc to remind users not to use the argument, especially setting it to `false`, as it would lead to perpetual differences.
Closes #43019
Referred to [RunJobFlow](https://docs.aws.amazon.com/emr/latest/APIReference/API_RunJobFlow.html#EMR-RunJobFlow-request-VisibleToAllUsers) and [SetVisibleToAllUsers](https://docs.aws.amazon.com/emr/latest/APIReference/API_SetVisibleToAllUsers.html) for the deprecation notice.
n/a
=> fix: Remove related test case and update doc for visible_to_all_users being no longer supported for r/aws_emr_cluster

.changelog/43673.txt, internal/service/inspector2/enabler.go, internal/service/inspector2/enabler_test.go, website/docs/r/inspector2_enabler.html.markdown
* Fix to support resource import for `aws_inspector2_enabler`.
* A simple `Importer` is added to the schema definition.
* Instructions for importing, including the complex `id` structure, are added to the documentation.
* Test cases for resource import are added to some of the existing acceptance tests.
Closes #33723
```console
$ make testacc TESTS=TestAccInspector2_serial/Enabler PKG=inspector2 
TF_ACC=1 go1.24.5 test ./internal/service/inspector2/... -v -count 1 -parallel 20 …
```
=> [Enhancement] aws_inspector2_enabler: Support resource import

.changelog/43693.txt, internal/service/wafv2/regex_pattern_set.go, website/docs/r/wafv2_regex_pattern_set.html.markdown
No changes to security controls are implemented.
The OP in #43615 is hitting a limit of maximum 10 `regular_expression`s in [`aws_wafv2_regex_pattern_set`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/wafv2_regex_pattern_set).
The [provider code](https://github.com/hashicorp/terraform-provider-aws/blob/4adef3e358624a9fe8eaa80b237789f556035781/internal/service/wafv2/regex_pattern_set.go#L94) is
```golang
"regular_expression": {
Type:     schema.TypeSet,
Optional: true,
MaxItems: 10,
Elem: &schema.Resource{
...
},
},
```
The value 10 is the default quota in an AWS account and can be raised via support request.
This pull request removes the limitation `MaxItems: 10`. I linked a …
=> remove max limit from regular expression argument

.changelog/43605.txt, internal/service/fsx/lustre_file_system.go, internal/service/fsx/lustre_file_system_test.go
* Fix validation logic for the read cache size `data_read_cache_configuration.size`.
* As explained in #43599, the valid range of `data_read_cache_configuration.size` depends on the value of `throughput_capacity`, and is calculated as follows:
```
N = throughput_capacity / 4000
32 * N <= SSD Read Cache <= 131072 * N
```
* However, [the current validation](https://github.com/hashicorp/terraform-provider-aws/blob/main/internal/service/fsx/lustre_file_system.go#L113) is implemented as:
```go
validation.IntBetween(32, 131072),
```
which does not take `throughput_capacity` into account.
* …
=> [bugfix] aws_fsx_lustre_file_system: Fix validation of SSD read cache size for file systems using the Intelligent-Tiering storage class

.changelog/43751.txt, internal/service/sagemaker/image.go
Previously the regex was more restrictive than the AWS API in that dots (`.`) were not allowed. The expression has been updated to match the AWS constraints.
- https://docs.aws.amazon.com/sagemaker/latest/APIReference/API_CreateImage.html#sagemaker-CreateImage-request-ImageName
Closes #43750
```console
% make testacc PKG=sagemaker TESTS="TestAccSageMakerImage_"
TF_ACC=1 go1.24.5 test ./internal/service/sagemaker/... -v -count 1 -parallel 20 -run='TestAccSageMakerImage_'  -timeout 360m …
```
=> r/aws_sagemaker_image: correct `image_name` validation

.changelog/43753.txt, internal/service/lambda/function.go, internal/service/lambda/function_data_source.go, internal/service/lambda/function_data_source_test.go, internal/service/lambda/function_test.go
* As reported in #43711, the `aws_lambda_function` data source returns `null` for `reserved_concurrent_executions` when a published version exists.
* The `GetFunction` API returns `null` for `Concurrency` when a `Qualifier` is specified. The data source reflects this `null` value.
* `Concurrency` appears to be version-agnostic. The other APIs, `GetFunctionConcurrency` and `PutFunctionConcurrency`, accept only a `FunctionName` and do not support a `Qualifier`.
* To return the correct value for `reserved_concurrent_executions`, `GetFunctionConcurrency` is called when the `Concurrency` …
=> [bugfix] aws_lambda_function: Fix missing concurrency information when published version exists

internal/service/route53resolver/endpoint_test.go, website/docs/r/route53_resolver_endpoint.html.markdown
* Due to updates in AWS SDK for Go v2, `INBOUND_DELEGATION` is now supported as a valid value for `direction` in the `aws_route53_resolver_endpoint` resource.
* The documentation has been updated to include `INBOUND_DELEGATION` as a valid value for `direction`.
* An acceptance test has been added to confirm that `INBOUND_DELEGATION` is supported.
Relates #43745 
https://docs.aws.amazon.com/Route53/latest/APIReference/API_route53resolver_CreateResolverEndpoint.html#Route53Resolver-route53resolver_CreateResolverEndpoint-request-Direction
```console
$ make testacc …
```
=> [Docs/Test] aws_route53_resolver_endpoint:  Update the documentation to add `INBOUND_DELEGATION` as a valid value for `direction`

.changelog/43816.txt, internal/service/ecs/service.go, internal/service/ecs/service_test.go
This PR fixes the issue reported in #43570.
* It was reported that after upgrading the provider to v6, the tagging process no longer works.
* The issue does not occur when an ECS Service is created using the v6 provider.
* The newly added acceptance test reproduces the issue: when `aws_ecs_service` is created with the v5.100.0 provider and its tags are modified using the latest provider, the expected results are not obtained.
* The acceptance test fails without the changes in this PR:
```console
$ make testacc TESTS=TestAccECSService_Tags_UpgradeFromV5_100_0 PKG=ecs
make: Verifying …
```
=> [bugfix] aws_ecs_service: Fix tagging failure after upgrading to v6 due to missing refreshing process for `arn` in the Read function

internal/service/ec2/vpnclient_endpoint.go, internal/service/ec2/vpnclient_endpoint_data_source.go
n/a
This PR is to remove `aws.StringSlice` usage from the `aws_ec2_client_vpn_endpoint` resource and data source, specifically for the `dns_servers` and `security_group_ids` arguments.
Relates #41800
n/a
```console
$ make testacc TESTS=TestAccClientVPNEndpoint_serial/Endpoint PKG=ec2
TF_ACC=1 go1.24.5 test ./internal/service/ec2/... -v -count 1 -parallel 20 -run='TestAccClientVPNEndpoint_serial/Endpoint'  -timeout 360m -vet=off
2025/08/10 03:16:07 Creating Terraform AWS Provider (SDKv2-style)...
2025/08/10 03:16:07 Initializing Terraform AWS Provider (SDKv2-style)...
=== RUN …
```
=> chore: Remove aws.StringSlice usages from aws_ec2_client_vpn_endpoint

internal/service/iot/indexing_configuration.go
n/a
his PR is to remove `aws.StringSlice` usage from the `aws_iot_indexing_configuration` resource, specifically for the `named_shadow_names` argument.
**Note:** The test case `TestAccIoTIndexingConfiguration_serial/Identity/ExistingResource` is failing for an unrelated reason.
Relates #41800
n/a
```console
$ make testacc TESTS=TestAccIoTIndexingConfiguration_serial PKG=iot
TF_ACC=1 go1.24.5 test ./internal/service/iot/... -v -count 1 -parallel 20 -run='TestAccIoTIndexingConfiguration_serial'  -timeout 360m -vet=off
2025/08/10 03:59:36 Creating Terraform AWS Provider (SDKv2-style)...
2025/08/10 03:59:36 …
```
=> chore: Remove aws.StringSlice usage from r/aws_iot_indexing_configuration

internal/service/iot/topic_rule_destination.go, internal/service/iot/topic_rule_destination_test.go
n/a
This PR is to remove `aws.StringSlice` usages from the `aws_iot_topic_rule_destination` resource, specifically for the `security_groups` and `subnet_ids` arguments.
Relates #41800 
n/a
```console
$ make testacc TESTS=TestAccIoTTopicRuleDestination_ PKG=iot
TF_ACC=1 go1.24.5 test ./internal/service/iot/... -v -count 1 -parallel 20 -run='TestAccIoTTopicRuleDestination_'  -timeout 360m -vet=off
2025/08/10 04:19:04 Creating Terraform AWS Provider (SDKv2-style)...
2025/08/10 04:19:04 Initializing Terraform AWS Provider (SDKv2-style)...
=== RUN   TestAccIoTTopicRuleDestination_basic
=== PAUSE …
```
=> chore: Remove aws.StringSlice usages from r/aws_iot_topic_rule_destination

internal/service/storagegateway/smb_file_share.go
n/a
This PR is to remove `aws.StringSlice` usages from the `aws_storagegateway_smb_file_share` resource, specifically for the security_groups and `admin_user_list`, `invalid_user_list`, and `valid_user_list` arguments.
Relates #41800
n/a
```console
$ make testacc TESTS=TestAccStorageGatewaySMBFileShare_ PKG=storagegateway
TF_ACC=1 go1.24.5 test ./internal/service/storagegateway/... -v -count 1 -parallel 8 -run='TestAccStorageGatewaySMBFileShare_'  -timeout 360m -vet=off
2025/08/10 12:58:29 Creating Terraform AWS Provider (SDKv2-style)...
2025/08/10 12:58:29 Initializing Terraform AWS Provider …
```
=> chore: Remove aws.StringSlice usages from r/aws_storagegateway_smb_file_share

internal/service/imagebuilder/image_pipeline.go
This PR is to remove `aws.StringSlice` usage from the `aws_imagebuilder_image_pipeline` resource, specifically for the `container_tags` argument.
Note that the acceptance test case `TestAccImageBuilderImagePipeline_Identity_ExistingResource` but it is failing for the usual reason, that it doesn't seem to be using the old provider. It's not related to this change so I'll ignore it for now.
Relates #41800
n/a
```console
$ make testacc TESTS="TestAccImageBuilderImagePipeline_" PKG=imagebuilder …
```
=> chore: Remove aws.StringSlice usage from r/aws_imagebuilder_image_pipeline

website/docs/d/ram_resource_share.html.markdown
No changes to security controls are made.
As mentioned in #40970 the [`filter`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/ram_resource_share#filter-1) in the data source [`aws_ram_resource_share`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/ram_resource_share) only works with resources that are owned (`resource_owner = "SELF"`).
The documentation is updated to reflect this detail.
Example code for showing the issue  when combining `resource_owner = "OTHER-ACCOUNTS"` and `filter`
```hcl
terraform {
aws = {
version = "6.8.0"
}
}
required_version = "~> 1.12.2"
}
region = …
```
=> docs: add detail on TagFilter usage

internal/service/finspace/kx_volume.go, website/docs/r/finspace_kx_volume.html.markdown
n/a
This PR is to remove `aws.StringSlice` usages from the `aws_finspace_kx_volume` resource, specifically for the `availability_zones` argument.
I noticed that `availability_zones` in the example usage is incorrectly set as a value instead of a list, so I fixed that in this PR too.
Relates #41800
n/a
Note that `TestAccFinSpaceKxVolume_basic` failed because of the account quota limit of 2 environments. I reran the test case individually afterwards and it's fine.
```console
$ make testacc TESTS=TestAccFinSpaceKxVolume_ PKG=finspace
TF_ACC=1 go1.24.5 test ./internal/service/finspace/... -v -count 1 -parallel …
```
=>  chore: Remove aws.StringSlice usage from r/aws_finspace_kx_volume

internal/service/wafv2/flex.go
n/a
This PR is to remove `aws.StringSlice` usages from the `aws_wafv2_web_acl` resource, specifically for the `included_cookies` and `excluded_cookies` arguments.
Relates #41800
n/a
```console
$ make testacc TESTS=TestAccWAFV2WebACL_ PKG=wafv2
make: go1.24.6 not found
make: installing go1.24.6...
make: if you get an error, see https://go.dev/doc/manage-install to locally install various Go versions
go: downloading golang.org/dl v0.0.0-20250812204734-236a62c85c37
Downloaded   0.0% (   16384 / 87261212 bytes) ...
Downloaded   0.2% (  212992 / 87261212 bytes) ...
Downloaded  15.0% (13123488 / 87261212 bytes) ...
Downloaded  31.0% (27082560 / 87261212 bytes) ...
Downloaded  45.0% (39288544 / 87261212 bytes) …
```
=> chore: Remove aws.StringSlice usages from r/aws_wafv2_web_acl

website/docs/r/msk_cluster.html.markdown
* Update the documentation to add cross-reference links for "See below" references.
* Additionally:
* Fix some typos.
* Add missing “logging_info broker_logs Argument Reference.”
Closes #43869
https://docs.aws.amazon.com/msk/1.0/apireference/clusters.html#clusters-prop-createclusterrequest-logginginfo
=> [Docs] r/aws_msk_cluster: Add cross-reference links for “See below” references

internal/provider/framework/provider.go, internal/provider/framework/wrap.go
Uses `sync.Once` instead of mutex and boolean to ensure schema validation is called once. 
Simplifies Framework Data Source registration:
* Defers creating `inner` wrapped resource until wrapper is called
* Makes `boostrapContext` a method on wrappers instead of function pointer
* Encapsulates configuration of interceptors
=> Simplify Framework registration

website/docs/r/gamelift_fleet.html.markdown
* Add description of conflicts between `build_id` and `script_id`.
```
ExactlyOneOf: []string{"build_id", "script_id"},
```
Closes #43897
https://github.com/hashicorp/terraform-provider-aws/blob/791e2b7854ee029d50f5c8c7a6f58df20e32764c/internal/service/gamelift/fleet.go#L61-L66
https://github.com/hashicorp/terraform-provider-aws/blob/791e2b7854ee029d50f5c8c7a6f58df20e32764c/internal/service/gamelift/fleet.go#L233-L238
=> [Docs] aws_gamelift_fleet: Add description of conflicts between `build_id` and `script_id`

.changelog/43874.txt, internal/service/lightsail/static_ip_attachment.go, internal/service/lightsail/static_ip_attachment_test.go
* Fix to support the import operation for `aws_lightsail_static_ip_attachment`.
* In the same way as `aws_lightsail_static_ip` in #43672
* In the `Read` function:
* `d.Id()` is used to obtain the static IP name instead of `d.Get("static_ip_name")`, because the `static_ip_name` attribute is unknown and only `id` is known during import.
* `d.Set("static_ip_name", ...)` is called to populate the `name` attribute in the import process.
* The `Importer` is defined in the schema.
* A test case is added to verify the import functionality.
* Although import was previously unsupported, …
=> [Enhancement] r/aws_lightsail_static_ip_attachment: Support resource import

.changelog/43886.txt, internal/service/ecr/repository_creation_template.go, internal/service/ecr/repository_creation_template_data_source.go, internal/service/ecr/repository_creation_template_data_source_test.go, internal/service/ecr/repository_creation_template_test.go, internal/service/ecr/repository_data_source.go, internal/service/ecr/repository_data_source_test.go, website/docs/d/ecr_repository.html.markdown, website/docs/d/ecr_repository_creation_template.html.markdown, website/docs/r/ecr_repository_creation_template.html.markdown
* Add the `image_tag_mutability_exclusion_filter` configuration block for `aws_ecr_repository_creation_template`.
* The same configuration block for `aws_ecr_repository` was implemented in #43569. The schema (including validation) is copied, and the existing expander and flattener are reused.
* Add support for the `image_tag_mutability_exclusion_filter` block in the `aws_ecr_repository_creation_template` data source.
* Also add `image_tag_mutability_exclusion_filter` to the `aws_ecr_repository` data source.
Closes #43882
https://docs.aws.amazon.com/AmazonECR/latest/APIReference/API_Create …
=> [Enhancement] aws_ecr_repository_creation_template: Support `image_tag_mutability_exclusion_filter`

internal/provider/framework/tags_interceptor.go, internal/tags/key_value_tags.go
Allows use of `tags.ResolveDuplicatesFramework` without `resource.ReadResponse`
=> Decouples `tags.ResolveDuplicatesFramework` from `resource.ReadResponse`

website/docs/d/rds_reserved_instance_offering.html.markdown
Adds most common product types for the reserved instance offering data source. This is to explicitly show that there are differences between aurora postgresql and rds postgresql offerings.
=> [doc]: add example values to reserved instance offering

.changelog/43925.txt, internal/service/imagebuilder/lifecycle_policy.go, internal/service/imagebuilder/lifecycle_policy_test.go
No changes to security controls are  implemented.
Not specifying the argument `policy_detail.exclusion_rules.amis.is_public` in the resource [`aws_imagebuilder_lifecycle_policy`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/imagebuilder_lifecycle_policy) leads to an error during `terraform apply`. The error is as below:
```plain
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to aws_imagebuilder_lifecycle_policy.default, provider "provider[\"registry.terraform.io/hashicorp/aws\"]" produced an unexpected new value: .policy_detail: planned set element
│ cty.ObjectVal(map[string]cty.Value{"action":cty.ListVal([]cty.Value{cty.ObjectVal(map[st …
```
=> fix: fix inconsistent result after apply for imagebuilder_lifecycle_policy

internal/service/lambda/permission_test.go
Previously the `_FunctionURLs` acceptance test configurations granted permissions to a wildcard (`*`) principal. The permissions have been scoped down to an individual IAM role for least privileged access instead.
- https://docs.aws.amazon.com/lambda/latest/dg/urls-auth.html#urls-auth-iam
```console
% make testacc PKG=lambda TESTS=TestAccLambdaPermission_FunctionURLs
TF_ACC=1 go1.24.6 test ./internal/service/lambda/... -v -count 1 -parallel 20 -run='TestAccLambdaPermission_FunctionURLs' …
```
=> r/aws_lambda_permission(test): scope down invoke function url permissions

website/docs/r/quicksight_account_subscription.html.markdown
Due to the limited fields returned by the `DescribeAccountSettings` API, an imported account subscription resource will always be immediately planned for replacement. This adds a note to the registry documentation describing this limitation.
```
-/+ resource "aws_quicksight_account_subscription" "test" {
~ account_subscription_status      = "ACCOUNT_CREATED" -> (known after apply)
+ authentication_method            = "IAM_AND_QUICKSIGHT" # forces replacement
+ aws_account_id                   = (known after apply)
~ id                               = "<redacted>" -> (known after apply)
}
Plan: 1 to add, 0 to change, 1 to destroy.
```
An `ignore_changes` lifecycle argument may be used to suppress the difference for any configured arguments …
=> r/aws_quicksight_account_subscription(doc): add note on import limitations

internal/service/apigateway/account.go, internal/service/bedrock/inference_profile.go, internal/service/bedrockagent/agent.go, internal/service/cloudformation/stack_set_instance.go, internal/service/quicksight/account_settings.go, internal/tfresource/retry.go
Use the new primitives in `internal/retry` (as a replacement for the SDKv2 `helper/retry` package) for `tfresource.RetryWhenG`.
Relates https://github.com/hashicorp/terraform-provider-aws/issues/42554.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/43267.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/43341.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/43412.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/43521.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/43573.
Relates …
=> Technical debt: Use `internal/retry` for `tfresource.RetryWhenG`

.changelog/44050.txt, internal/service/rds/instance.go, internal/service/rds/instance_test.go
Fixes RDS instance `database_insights_mode` updates when using a custom KMS key for Performance Insights encryption.
This fix is the same as #43942, which addressed the same issue for RDS clusters.
When updating the `database_insights_mode` parameter on an RDS instance that has a custom KMS key configured for Performance Insights encryption, the provider was not properly setting the `performance_insights_kms_key_id` parameter in the `ModifyDBInstance` API call. As a result, the KMS key was being reset during the update, causing the update operation to fail.
This PR fixes the issue by …
=> [bugfix] aws_db_instance: Fix to enable to update `database_insights_mode` with custom KMS key

.changelog/44042.txt, internal/service/datazone/domain.go, internal/service/datazone/domain_test.go, website/docs/r/datazone_domain.html.markdown
* To support V2 domains, the `domain_version` and `service_role` arguments have been added.
* Since the AWS API returns `domain_version` even if it is not specified, it is marked as `Computed`.
* Because the UpdateDomain API does not accept `domain_version` as an argument, it is marked as `ForceNew`.
* An example for a V2 domain, including domain execution and a service role (identical to what the AWS Management Console creates), has been added.
* This example is also used in the newly added acceptance test.
Closes #44039
https://docs.aws.amazon.com/datazone/latest/APIReference/API_Create …
=> [Enhancement] aws_datazone_domain: Support v2 domain by adding `domain_version` and `service_role` arguments

website/docs/r/ecs_service.html.markdown
* This PR updates the documentation for `aws_ecs_service` to clarify that `service_connect_configuration.service.client_alias` must contain exactly one `client_alias`.
* [According to the AWS documentation](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_ServiceConnectService.html#ECS-Type-ServiceConnectService-clientAliases):
* The maximum number of client aliases you can have in this list is 1.
* You must provide at least one `client_alias` with one port.
Taken together, these statements imply that exactly one `client_alias` must be specified, even though the …
=> [Docs] aws_ecs_service: Update `service_connect_configuration.service.client_alias` argument description to require exactly one alias

internal/service/apigateway/service_package.go, internal/service/apigatewayv2/service_package.go, internal/service/appsync/service_package.go, internal/service/cloudformation/service_package.go, internal/service/cloudhsmv2/service_package.go, internal/service/dynamodb/service_package.go, internal/service/ec2/service_package.go, internal/service/fms/service_package.go, internal/service/kafka/service_package.go, internal/service/kinesis/service_package.go, internal/service/lightsail/service_package.go, internal/service/organizations/service_package.go, internal/service/s3/service_package.go, internal/service/schemas/service_package.go, internal/service/ssoadmin/service_package.go
All generated service clients contain a functional option which overrides the default retryer with additional handling for `go-vcr`-specific errors. However, a handful of service clients include additional hand-written options which _also_ override the default retryer, typically addressing some nuance related to error codes unique to a given service. To ensure these service-local overrides do not overwrite the `go-vcr` handling, the extra options implementations have been modified to merge both sets of retryables.
Closes #42949
Relates https://github.com/hashicorp/terraform-provider-aws/issues/25602
Relates https://github.com/hashicorp/terraform-provider-aws/pull/42801
Example of a `go-vcr` failure which previously hung due to unintentional retries on the EC2 client. This now fails …
=> feat(go-vcr): include `go-vcr` retryer override when configured via extra options

.changelog/44080.txt, internal/service/lambda/function.go, internal/service/lambda/function_data_source.go, internal/service/lambda/function_data_source_test.go, internal/service/lambda/function_test.go, website/docs/d/lambda_function.html.markdown, website/docs/r/lambda_function.html.markdown
* Add `source_kms_key_arn` argument to allow users to provide their own KMS key for encrypting Lambda function source code.
*  The new attribute is available in both the resource and data source.
Closes #43055 
Closes #40276
https://docs.aws.amazon.com/lambda/latest/api/API_CreateFunction.html
https://docs.aws.amazon.com/lambda/latest/api/API_UpdateFunction.html
https://docs.aws.amazon.com/lambda/latest/api/API_GetFunction.html
```console
$ make testacc TESTS=TestAccLambdaFunction_ PKG=lambda  …
```
=> [Enhancement] aws lambda function:  Add `source_kms_key_arn` argument to encrypt deployment package with custom KMS key

internal/service/ecs/service_test.go
The `TestAccECSService_AvailabilityZoneRebalancing_UpgradeV6_8_0_unconfigured` test incorrectly expects `availability_zone_rebalancing` to default to `DISABLED` when using v6.8.0 of the Terraform AWS provider.
Per the behavior change, creating an ECS Service with an unconfigured (null) `availability_zone_rebalancing` value now defaults to `ENABLED` instead of `DISABLED`. When updating a service with a persisted null value for `availability_zone_rebalancing`, the value will remain as `ENABLED`. Since this change is dictated by ECS backend rather than the Terraform resource provider, this …
=> Remove incorrect availability zone rebalancing upgrade tests

.changelog/44143.txt, internal/service/rds/cluster_role_association.go, internal/service/rds/cluster_role_association_test.go, website/docs/r/rds_cluster_role_association.html.markdown
* The `feature_name` argument in `aws_rds_cluster_role_association` was previously marked as required.
* However:
* The [current AWS documentation](https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_AddRoleToDBCluster.html) describes it as `Required: No`.
* The newly added acceptance test confirmed that API requests without `feature_name` are accepted when the DB engine is MySQL, which means the `feature_name` argument is not always required.
* The AWS Management Console for a MySQL cluster also provides a UI to specify only the role without a feature name.
* This PR changes …
=> [bugfix] r/aws_rds_cluster_role_association: Change `feature_name` argument from required to optional

website/docs/r/datasync_location_object_storage.html.markdown
* PR #43400 made `agent_arns` optional.
* However, the documentation was not updated to reflect this change.
* This PR updates the documentation to indicate that `agent_arns` is optional.
Closes #44158
Relates #43400
https://docs.aws.amazon.com/datasync/latest/userguide/API_CreateLocationObjectStorage.html#DataSync-CreateLocationObjectStorage-request-AgentArns
=> [Docs] `aws_datasync_location_object_storage`: Update the documentation to reflect that `agent_arns` is optional

.changelog/44163.txt, internal/service/cloudfront/distribution.go, internal/service/cloudfront/distribution_test.go, website/docs/r/cloudfront_distribution.html.markdown
* This PR adds the `origin.response_completion_timeout` argument.
* Issue #44116 requests support for both `origin.response_completion_timeout` and `origin.s3_origin_config.origin_read_timeout`.
* Since the implementation of `origin.s3_origin_config.origin_read_timeout` is currently blocked due to an unexpected behavior in the Terraform Plugin SDK, `origin.response_completion_timeout` has been implemented first.
* I opened issue #44172 to clarify what is blocking its implementation.
* `origin.response_completion_timeout` is marked as `Computed`.
* If this argument is not specified in the …
=> [Enhancement] r/aws_cloudfront_distribution: Add `origin.response_completion_timeout` argument

docs/ai-agent-guides/arn-based-resource-identity.md, docs/ai-agent-guides/parameterized-resource-identity.md, website/docs/r/acm_certificate.html.markdown
Extends the AI agent guides for implementing resource identity with instructions for updating the relevant section of the registry documentation.
Also adds "import by identity" documentation for the `aws_acm_certificate` resource as a reference. This is the first resource with an ARN-based identity to have the corresponding registry documentation.
Relates #42983
=> docs: add import by identity instructions to resource identity guides

.changelog/44201.txt, internal/service/codebuild/project_test.go, internal/service/codebuild/webhook.go, internal/service/codebuild/webhook_test.go, website/docs/r/codebuild_webhook.html.markdown
* Adds the `pull_request_build_policy` configuration block to `aws_codebuild_webhook`.
* The `pull_request_build_policy` block is marked as `Computed`.
* The AWS API returns this object even if the block is not specified in the configuration.
* The `approver_roles` argument in `pull_request_build_policy` block is also marked as `Computed`.
* The AWS API returns a default value for this block even if it is not specified in the configuration.
* Adds the `codeconnections:GetConnectionToken` permission to the role assumed by the CodeBuild service in acceptance tests, since this permission is …
=> [Enhancement] aws_codebuild_webhook: Add `pull_request_build_policy` configuration block

.changelog/44224.txt, internal/service/bedrock/guardrail.go, internal/service/bedrock/guardrail_test.go, website/docs/r/bedrock_guardrail.html.markdown
* Add action arguments to `word_policy_config` in `aws_bedrock_guardrail`
* Affected Arguments
* `word_policy_config.managed_word_lists_config`
- `input_action`
- `input_enabled`
- `output_action`
- `output_enabled`
* word_policy_config.words_config
- `input_action`
- `input_enabled`
- `output_action`
- `output_enabled`
* If these arguments are not specified in the configuration, the "Read" API returns `null` for them. This means that it should not be marked as `Computed`.
Closes #44220
https://docs.aws.amazon.com/bedrock/latest/APIReference/API_CreateGuardrail.html
```console
$ make …
```
=> [Enhancement]  r/aws_bedrock_guardrail: Add action arguments to `word_policy_config`

.changelog/44252.txt, internal/service/rds/global_cluster.go, internal/service/rds/global_cluster_test.go, website/docs/r/rds_global_cluster.html.markdown
This enables both arguments to be set upon creation, rather than requiring users to set a source DB for the initial global cluster creation and removing it to set `engine` and `engine_version` for subsequent major version upgrades. During create operations the `engine` and `engine_version` values will be ignored if `source_db_cluster_identifier` is set. If the engine version varies from what is inherited from the source cluster a second change will be planned immediately following the initial apply.
To support future major version upgrades on a promoted global cluster, the following configuration is now valid.
```terraform
resource "aws_rds_global_cluster" "test" {
force_destroy                = true
global_cluster_identifier    = "my-cluster"
engine                       = local.engine …
```
=> r/aws_rds_global_cluster: remove `engine` and `source_db_cluster_identifier` conflict

website/docs/r/lambda_function.html.markdown
No changes to security controls are implemented.
This [commit](https://github.com/hashicorp/terraform-provider-aws/commit/2e516d75803c62445b13597ac5b0dc66b9ba5e5b#diff-dbb900253ab554e20258590c65deb99a6a85788310ee15ec5bc59cd03075ad51L355) re-worked parts of the Lambda function documentation. As part of this, a note on the `vpc_config` block was removed.
This note is re-added to the documentation.
Closes #44115 
- Pull request for [resource/aws_lambda_function: Ignore the VPC configuration if it is empty](https://github.com/hashicorp/terraform-provider-aws/pull/1341) (handling empty VPC configuration)
- Commit [https://github.com/hashicorp/terraform-provider-aws/commit/a0cbaed98bc37acf6967e35205495e49db42c2f …
=> docs: add note to vpc_config section

website/docs/r/autoscaling_group.html.markdown
N/a
Fixes the details for the `skip_matching` argument of the `aws_autoscaling_group` resource.
Closes #44292
[AWS Documentation](https://docs.aws.amazon.com/cli/latest/reference/autoscaling/start-instance-refresh.html):
> Indicates whether skip matching is enabled. If enabled (`true`), then Amazon EC2 Auto Scaling skips replacing instances that match the desired configuration. If no desired configuration is specified, then it skips replacing instances that have the same launch template and instance types that the Auto Scaling group was using before the start of the instance refresh. The default is `false`.
N/a, docs
=> Update `skip_matching` documentation for `aws_autoscaling_group`

internal/service/athena/data_catalog.go
The AWS API has been returning `InvalidRequestException` instead of `ResourceNotFoundException` when trying to delete missing Data Catalog.
The description of `InvalidRequestException` is
> Indicates that something is wrong with the input to the request. For example, a required parameter may be missing or out of range.
This was causing the acceptance test `TestAccAthenaDataCatalog_disappears` to fail with the error
> Error: deleting Athena Data Catalog (tf-test-alu48tu6): operation error Athena: DeleteDataCatalog, https response error StatusCode: 400, RequestID: ..., …
=> aws_athena_data_catalog: Handles incorrect error type now returned by AWS

internal/service/acm/sweep.go, internal/service/apigateway/sweep.go
Fixes to sweepers:
* `aws_acm_certificate`: By default `ListCertificates` doesn't list all certificate types
* `aws_api_gateway_domain_name`: Failed to delete domain names with private endpoints
=> sweepers: `aws_acm_certificate` and `aws_api_gateway_domain_name`

docs/ai-agent-guides/go-vcr-migration.md, internal/service/polly/voices_data_source_test.go
Enables `go-vcr` support for the `polly` service. Also adds a AI agent guide for enabling `go-vcr` by service.
Relates #25602
Relates #43717
```console
% make testacc PKG=polly VCR_MODE=REPLAY_ONLY VCR_PATH=/tmp/polly-vcr-testdata/
make: Running acceptance tests on branch: 🌿 f-go-vcr-polly 🌿...
TF_ACC=1 go1.24.6 test ./internal/service/polly/... -v -count 1 -parallel 20   -timeout 360m -vet=off
2025/09/18 12:02:01 Creating Terraform AWS Provider (SDKv2-style)...
2025/09/18 12:02:01 …
```
=> polly: enable `go-vcr` support

internal/service/dsql/cluster_peering_test.go, internal/service/dsql/cluster_test.go
DSQL was made [generally available on 27 May 2025](https://www.google.com/url?sa=t&source=web&rct=j&opi=89978449&url=https://aws.amazon.com/blogs/aws/amazon-aurora-dsql-is-now-generally-available/&ved=2ahUKEwj5io3T6-WPAxWpLDQIHZJ1AWsQFnoECCEQAQ&usg=AOvVaw2_WA2DD2htaMX0M_MKGGPZ). Remove region restrictions on tests.
```console
% make testacc PKG=dsql TESTS='TestAccDSQLCluster_|TestAccDSQLClusterPeering_'
--- PASS: TestAccDSQLCluster_disappears (190.75s)
--- PASS: TestAccDSQLCluster_tags_DefaultTags_emptyResourceTag (205.40s)
--- PASS: TestAccDSQLCluster_tags_EmptyTag_OnUpdate_Replace …
```
=> DSQL: remove preview restrictions on tests

website/docs/r/macie2_member.html.markdown
There is a duplicated `tags` property in the docs for `macie2_member` resource.
=> Remove duplicated `tags` property in docs

internal/service/rds/cluster_instance.go, internal/service/rds/instance.go, internal/service/rds/instance_test.go, internal/tfresource/retry.go, internal/tfresource/retry_test.go
Use `internal/retry.StateChangeConf` with `tfresource.Options`.
Relates https://github.com/hashicorp/terraform-provider-aws/issues/42554.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/44093.
```console
% ACCTEST_TIMEOUT=720m make testacc TESTARGS='-run=TestAccRDSInstance_\|TestAccRDSClusterInstance_' PKG=rds ACCTEST_PARALLELISM=4
make: Running acceptance tests on branch: 🌿 td-tfresource.Options-use-internal/retry 🌿...
TF_ACC=1 go1.24.6 test ./internal/service/rds/... -v …
```
=> Technical debt: Use `internal/retry.StateChangeConf` with `tfresource.Options`

.changelog/44444.txt, .github/workflows/semgrep-ci.yml, GNUmakefile, internal/service/codebuild/service_package_gen.go, internal/service/codebuild/start_build_action.go, internal/service/codebuild/start_build_action_test.go, website/docs/actions/codebuild_start_build.html.markdown
Implements a new Terraform action to start AWS CodeBuild project builds imperatively within Terraform configurations.
• **Start builds** for any CodeBuild project by name
• **Environment variable overrides** for build-specific configuration
• **Source version control** (branch, commit, tag)
• **Configurable timeouts** with progress monitoring
• **Build completion tracking** with status updates
• Uses AutoFlex for clean data conversion
• Follows established action patterns from existing actions
• Proper polling with progress updates during build execution
• Comprehensive error handling …
=> New action: `aws_codebuild_start_build`

website/docs/cdktf/python/r/pipes_pipe.html.markdown
* Fix the attribute description for `starting_position` in `source_parameters.dynamodb_stream_parameters` block from `Optional` to `Required`.
* It is implemented as `Required` in the AWS Provider
* https://github.com/hashicorp/terraform-provider-aws/blob/033da7288cd09f84fe227fccdf0688be4a18bc70/internal/service/pipes/source_parameters.go#L149-L154
* The [AWS documentation](https://docs.aws.amazon.com/eventbridge/latest/pipes-reference/API_PipeSourceDynamoDBStreamParameters.html#eventbridge-Type-PipeSourceDynamoDBStreamParameters-StartingPosition) describes it `Required`.
Closes #44450 …
=> [Docs] aws_pipes_pipe: Correct `starting_position` in `dynamodb_stream_parameters` from `Optional` to `Required`

.changelog/44449.txt, internal/service/servicequotas/service_quota_data_source.go, internal/service/servicequotas/service_quota_data_source_test.go
* Fix panic of `aws_servicequotas_service_quota` caused by missing error handling when a `quota_code` is not found for a given `quota_name`.
* The `err` returned from `findDefaultServiceQuotaByServiceCodeAndQuotaName` is now caught and properly handled.
Related to the [comment](https://github.com/hashicorp/terraform-provider-aws/issues/44366#issuecomment-3333269231)
```console
$ make testacc TESTS='TestAccServiceQuotasServiceQuotaDataSource_' PKG=servicequotas
make: Running acceptance …
```
=> [bugfix] d/aws_servicequotas_service_quota: Fix panic when non-existing `quota_name` is specified

.changelog/44372.txt, internal/service/pinpointsmsvoicev2/phone_number.go, internal/service/pinpointsmsvoicev2/phone_number_test.go, website/docs/r/pinpointsmsvoicev2_phone_number.html.markdown
This PR updates the `two_way_channel_arn` argument to support using Amazon Connect as the inbound destination for two-way SMS.  
* The argument type is changed from `ARNType` to `StringType`, removing the strict ARN-only validation.  
* Instead of removing validation entirely, new checks ensure the value either starts with `arn` or matches `connect\.[a-z0-9-]+\.amazonaws.com`.  
* A new acceptance test confirms that `connect.[region].amazonaws.com` is accepted as a valid value for `two_way_channel_arn`.  
Closes #44321
https://docs.aws.amazon.com/sms-voice/latest/userguide/two-way-sms-pho …
=> [Enhancement] aws_pinpointsmsvoice2_phone_number: Support Amazon Connect as the inbound destination for two-way SMS

.changelog/44328.txt, internal/service/ec2/ec2_instance_type_offering_data_source.go, internal/service/ec2/ec2_instance_type_offering_data_source_test.go, website/docs/d/ec2_instance_type_offering.html.markdown
* Add the `location` attribute to the `aws_ec2_instance_type_offering` data source.  
* Previously, only the `instance_type` was retrieved from the AWS API response, and filtering was performed against a list of instance types.  
* This PR updates the implementation to use the raw objects returned by the AWS API for filtering, allowing the `location` attribute to be retrieved as well.  
* Update acceptance tests to compare concrete values instead of only checking for attribute existence.  
* The expected values are obtained from the `data.aws_ec2_instance_type_offerings` data source used …
=> [Enhancement] d/aws_ec2_instance_type_offering: Add `location` attribute

.changelog/44464.txt, internal/service/sfn/service_package_gen.go, internal/service/sfn/start_execution_action.go, internal/service/sfn/start_execution_action_test.go, website/docs/actions/sfn_start_execution.html.markdown
This PR adds the `aws_sfn_start_execution` action, enabling imperative execution of Step Functions state machines within Terraform configurations. The action supports all key `StartExecution` API parameters including JSON input data, custom execution names, version/alias-qualified ARNs, and X-Ray tracing headers. Implementation includes comprehensive end-to-end acceptance tests that validate real AWS integration, proper error handling, and idempotency behavior for both STANDARD and EXPRESS workflows. The action follows established provider patterns and includes complete documentation …
=> New action: `aws_sfn_start_execution`

.changelog/44463.txt, internal/service/cloudfront/distribution.go, internal/service/cloudfront/distribution_test.go, website/docs/r/cloudfront_distribution.html.markdown
* Added `ip_address_type` to `origin.custom_origin_config` configuration block
Closes #44458
https://docs.aws.amazon.com/cloudfront/latest/APIReference/API_CustomOriginConfig.html#cloudfront-Type-CustomOriginConfig-IpAddressType
```console
$ make testacc TESTS='TestAccCloudFrontDistribution_' PKG=cloudfront 
make: Running acceptance tests on branch: 🌿 f-aws_cloudfront_distribution-add_custom_origin_config_ip_address_type 🌿...
TF_ACC=1 go1.24.6 test ./internal/service/cloudfront/... -v …
```
=> [Enhancement] aws_cloudfront_distribution: Add `ip_address_type` argument to `origin.custom_origin_config` block

.changelog/44459.txt, internal/service/ec2/ec2_instance.go, internal/service/ec2/ec2_instance_test.go
No changes to security controls are implemented.
* Terraform version 1.13.2
* AWS Provider version 6.14.1
When setting up EC2 instances in combination with capacity reservations we ran into a panic. The stack trace is below
```plain
Stack trace from the terraform-provider-aws_v6.14.1_x5 plugin:
panic: interface conversion: interface {} is nil, not map[string]interface {}
goroutine 89 [running]:
github.com/hashicorp/terraform-provider-aws/internal/service/ec2.expandCapacityReservationSpecification(0xc004afb920)
github.com/hashicorp/terraform-provider-aws/internal/service/ec2/ec2_instance.go:3819 +0x2ba
github.com/hashicorp/terraform-provider-aws/internal/service/ec2.buildInstanceOpts({0x22b47f28, …
```
=> fix: fix interface conversion panic

.changelog/44485.txt, internal/service/elbv2/load_balancer_data_source.go, internal/service/elbv2/load_balancer_data_source_test.go
* #44481 reported a panic error: `Invalid address to set: []string{"secondary_ips_auto_assigned_per_subnet"}`  
* The `secondary_ips_auto_assigned_per_subnet` argument was introduced to the resource in #43699.  
* Even though the same flattener is used in both the resource and the data source, this attribute had not yet been implemented for the data source.  
* This PR adds `secondary_ips_auto_assigned_per_subnet` to the data source schema.  
* The newly added acceptance test confirms that:  
* Without this change, the reported panic can be reproduced.  
* With this change, no panic …
=> [bugfix] d/aws_lb: Fix panic caused by missing `secondary_ips_auto_assigned_per_subnet` in schema definition

.changelog/44487.txt, internal/service/events/put_events_action.go, internal/service/events/put_events_action_test.go, internal/service/events/service_package_gen.go, website/docs/actions/events_put_events.html.markdown
Adds a new beta Terraform action `aws_events_put_events` that imperatively sends one or more custom EventBridge events during an apply lifecycle via `config { entry { ... } }` blocks. It supports multiple event entries, optional custom event buses, RFC3339 `time`, `resources` ARNs. Acceptance tests were strengthened to verify real delivery by wiring an EventBridge rule and SQS target (with ordering enforced via `depends_on`) instead of only asserting bus existence. Documentation includes a technical preview note (breaking changes still possible) and examples for basic, multi‑entry, …
=> New action: `aws_events_put_events`

internal/service/ec2/find.go, internal/slices/slices.go, internal/slices/slices_test.go
Adds `internal/slices.CollectWithError` to act on `iter.Seq2[E, error]`.
```console
% make testacc TESTARGS='-run=TestAccEC2Instance_basic$$' PKG=ec2
make: Running acceptance tests on branch: 🌿 f-iter-funcs 🌿...
TF_ACC=1 go1.24.6 test ./internal/service/ec2/... -v -count 1 -parallel 20  -run=TestAccEC2Instance_basic$ -timeout 360m -vet=off
2025/09/26 16:21:52 Creating Terraform AWS Provider (SDKv2-style)...
2025/09/26 16:21:52 Initializing Terraform AWS Provider (SDKv2-style)...
=== RUN …
```
=> Add `WithError` functions to `internal/slices`

.changelog/44516.txt, internal/service/dms/endpoint.go, internal/service/dms/endpoint_data_source.go, internal/service/dms/endpoint_test.go, website/docs/r/dms_endpoint.html.markdown
* Add `mysql_settings` configuration block to both the `aws_dms_endpoint` resource and data source.
* The implementation follows the existing pattern for `postgres_settings`.
* All arguments in the block are marked as `Computed`.
* When updating, since [`ExactSettings`](https://docs.aws.amazon.com/ja_jp/dms/latest/APIReference/API_ModifyEndpoint.html#DMS-ModifyEndpoint-request-ExactSettings) is not specified (i.e., `false`) in the current implementation, removing arguments from the configuration has no effect and values are inherited from the previous configuration. This is why …
=> [Enhancement] aws_dms_endpoint: Add `mysql_settings` configuration block

internal/service/elasticbeanstalk/environment.go, internal/service/elasticbeanstalk/environment_migrate.go, internal/service/elasticbeanstalk/environment_test.go, internal/service/elasticbeanstalk/exports_test.go
WIP for fixing Inconsistent Final Plan error when nested set values change
Closes #0000
```console
...
```
=> [WIP] Inconsistent Final Plan when nested set values change

go.mod, go.sum
Reverts hashicorp/terraform-provider-aws#44493
The additional error diagnostics added in this version have uncovered some discrepancies between how the AWS provider implemented resource identity support for Plugin Framework resources, and the expectations held by the upstream library. Specifically, the library assumes that a resource implements the `ResourceWithIdentity` interface when identity is fully supported, and always returns a non-nil schema. 
In versions `v6.0.0` to current, the provider has implemented an `IdentitySchema` method on all Plugin Framework resources by wrapping the base resource implementation, therefore satisfying the `ResourceWithIdentity` interface. A resource was only considered supported when the schema contained greater than 0 attributes. 
This difference in …
=> Revert "Bump github.com/hashicorp/terraform-plugin-framework from 1.16.0 to 1.16.1 in the terraform-devex group across 1 directory"

internal/provider/framework/wrap.go
Only implement `resource.ResourceWithIdentity` if resource type supports Resource Identity
Closes #0000
```console
...
```
=> Only implement `resource.ResourceWithIdentity` if resource type supports Resource Identity

.changelog/44522.txt, internal/service/logs/service_package.go
N/A
This PR updates the CloudWatch Logs options to prevent infinite retries on `LimitExceededException` which indicates that no more resoures can be created.
Closes #41503.
Reproduce using:
```terraform
data "aws_caller_identity" "current" {}
data "aws_region" "current" {}
resource "aws_cloudwatch_log_resource_policy" "example" {
count       = 11
policy_name = "example-policy-${count.index}"
policy_document = jsonencode({
Version = "2012-10-17"
Statement = [
{
Effect    = "Allow"
Principal = { "AWS" = data.aws_caller_identity.current.account_id }
Action    = "logs:PutLogEvents"
Resource  = "arn:aws:logs:${data.aws_region.current.name}:${data.aws_caller_identity.current.account_id}:log-group:/aws/lambda/my- …
```
=> r/aws_cloudwatch_log_resource_policy: Do not retry on `LimitExceededException`

.changelog/44478.txt, internal/service/emr/validate.go, internal/service/kms/validate.go, internal/verify/validate.go
This PR fixes an admittedly minor grammar error in the validation messages for the EMR and KMS services.
`be comprised of only` -> `only contain`
I don't think this needs one, as it's just a message fix. The actual text also isn't checked for in the tests.
None.
=> fix: Corrects grammar in EMR and KMS validation messages

.changelog/44540.txt, internal/service/lambda/event_source_mapping.go, internal/service/lambda/event_source_mapping_test.go, website/docs/r/lambda_event_source_mapping.html.markdown
* Add `schema_registry_config` block to both `amazon_managed_kafka_event_source_config` and `self_managed_kafka_event_source_config`.
* The AWS API uses the same object for `schema_registry_config` in both blocks, so the same schema definition applies to both.
* Update `kafka_version` in existing acceptance tests, as the previous version is no longer supported.
Closes #43143 
Closes #44496 
https://docs.aws.amazon.com/lambda/latest/api/API_KafkaSchemaRegistryConfig.html
One test failed, but it appears not to be related to the fix in this PR.
```console
$ make testacc …
```
=> [Enhancement] r/aws_lambda_event_source_mapping: Add `schema_registry_config` to both MSK and self-managed Kafka event sources

.changelog/44560.txt, internal/service/vpclattice/resource_gateway.go, internal/service/vpclattice/resource_gateway_test.go, website/docs/r/vpclattice_resource_gateway.html.markdown
- Add `ipv4_addresses_per_eni` argument to `aws_vpclattice_resource_gateway`.
- This argument is optional, and defaults to `16`. According to 
- It is only applicable to `IPV4` and `DUALSTACK` IP address types.
- The number of addresses per ENI must range from 1 to 62.
- The number of addresses per ENI cannot be edited after resource creation.
Closes #44555
- Create Resource Gateway docs now call out the new "Pv4 addresses per ENI" option: https://docs.aws.amazon.com/vpc/latest/privatelink/create-resource-gateway.html
- Latest go-sdk-v2: …
=> [Enhancement]: `aws_vpclattice_resource_gateway`:  add `ipv4_addresses_per_eni` argument

website/docs/r/service_discovery_service.html.markdown
n/a
This change adapts the example usage to use the non-deprecated block `health_check_config` instead of `health_check_custom_config`. 
Additionally, a note regarding the deprecation of `health_check_custom_config` is added.
Closes #0000
n/a
=> Docs: Clarify deprecations in `aws_service_discovery_service`
