hashicorp/terraform-provider-aws

README.md
=> Fix repository and provider name references in README

aws/resource_aws_elasticache_parameter_group.go
```
=== RUN   TestAccAWSElasticacheParameterGroup_importBasic
--- FAIL: TestAccAWSElasticacheParameterGroup_importBasic (6.98s)
testing.go:492: Error destroying resource! WARNING: Dangling resources
Error: Error applying: 1 error(s) occurred:
* aws_elasticache_parameter_group.bar (destroy): 1 error(s) occurred:
* aws_elasticache_parameter_group.bar: InvalidCacheParameterGroupState: Cache parameter group parameter-group-test-terraform-620255685172994862 can not be deleted in the current state.
status code: 400, request id: 1bb9eeba-4cd3-11e7-8b4a-e9587f270628
State: aws_elasticache_parameter_group.bar:
ID = parameter-group-test-terraform-620255685172994862
description = Managed by Terraform …
```
=> elasticache: Retry deletion of param grp on InvalidCacheParameterGroupState

aws/resource_aws_rds_cluster.go
```
=== RUN   TestAccAWSRDSCluster_backupsUpdate
--- FAIL: TestAccAWSRDSCluster_backupsUpdate (110.40s)
testing.go:428: Step 1 error: Error applying: 1 error(s) occurred:
* aws_rds_cluster.default: 1 error(s) occurred:
* aws_rds_cluster.default: [WARN] Error modifying RDS Cluster (tf-aurora-cluster-4399690208005989315): InvalidDBClusterStateFault: Db Cluster is not available for modifcation with status backing-up
status code: 400, request id: 96fafc6a-4f48-11e7-a506-eb730ce30037
```
5 mins is just an arbitrary value which may change if we see failures in the future.
```
$ make testacc TESTARGS='-run=TestAccAWSRDSCluster_'
TF_ACC=1 go test $(go list ./... |grep -v 'vendor') -v …
```
=> resource/rds_cluster: Retry modification on InvalidDBClusterStateFault

.github/CONTRIBUTING.md
Copied over from hashicorp/terraform
=> Add Contributing guide

aws/resource_aws_codebuild_project.go
```
=== RUN   TestAccAWSCodeBuildProject_basic
--- FAIL: TestAccAWSCodeBuildProject_basic (15.12s)
testing.go:428: Step 0 error: Error applying: 1 error(s) occurred:
* aws_codebuild_project.foo: 1 error(s) occurred:
* aws_codebuild_project.foo: [ERROR] Error updating CodeBuild project (arn:aws:codebuild:us-west-2:*******:project/test-project-6kum6jemzb): InvalidInputException: CodeBuild is not authorized to perform: sts:AssumeRole on arn:aws:iam::*******:role/codebuild-role-6kum6jemzb
status code: 400, request id: 4f535692-5320-11e7-8006-2d816cc1e349
```
I'm aware this may uncover some other errors, but I think it's better to scope down the retry to specific error codes rather than blindly retry on any error and delay displaying genuine user …
=> resource/codebuild: Increase timeout for creation retry (IAM)

website/docs/index.html.markdown
A more appropriate take on #937
Unrelated; is there a trick to running tests locally?
=> Mention AWS environment variable precedence

aws/resource_aws_spot_fleet_request.go
=> r/aws_spot_fleet_request: Raise the create timeout to be 10m

website/docs/d/elasticache_cluster.html.markdown
=> docs: close code block

README.md
refs: https://github.com/hashicorp/terraform/commit/31b8c3c6ad6c4b0be0eec5b153f2a25a3a220a37
=> Fix broken terraform image in README

vendor/github.com/aws/aws-sdk-go/aws/endpoints/defaults.go, vendor/github.com/aws/aws-sdk-go/aws/version.go, vendor/github.com/aws/aws-sdk-go/service/cloudwatch/api.go, vendor/github.com/aws/aws-sdk-go/service/cloudwatch/doc.go, vendor/github.com/aws/aws-sdk-go/service/cloudwatch/errors.go, vendor/github.com/aws/aws-sdk-go/service/cloudwatchevents/api.go, vendor/github.com/aws/aws-sdk-go/service/cloudwatchevents/errors.go, vendor/github.com/aws/aws-sdk-go/service/s3/api.go, vendor/github.com/aws/aws-sdk-go/service/ssm/api.go, vendor/github.com/aws/aws-sdk-go/service/ssm/errors.go, vendor/vendor.json
This will allow to implement Cloudwatch Dashboards using the API :)
=> Bumped SDK to 1.10.7

aws/data_source_aws_db_snapshot_test.go, aws/resource_aws_db_instance_test.go, aws/resource_aws_db_option_group_test.go, aws/resource_aws_db_snapshot_test.go, aws/resource_aws_opsworks_rds_db_instance_test.go
RDS seems to not be finding 5.6.21 despite it being listed. CI is results to follow..
=> Bump mysql engine version

aws/resource_aws_kms_alias.go
This is to address the following test failures:
```
=== RUN   TestAccAWSKmsAlias_basic
--- FAIL: TestAccAWSKmsAlias_basic (24.32s)
testing.go:280: Step 0 error: After applying this step, the plan was not empty:
DIFF:
CREATE: aws_kms_alias.nothing
arn:           "" => "<computed>"
target_key_id: "" => "950636dd-a68b-4db1-a623-5872e0a9bfeb"
=== RUN   TestAccAWSKmsAlias_importBasic
--- FAIL: TestAccAWSKmsAlias_importBasic (25.50s)
testing.go:428: Step 0 error: After applying this step, the plan was not empty:
DIFF:
CREATE: aws_kms_alias.name_prefix
arn:           "" => "<computed>"
name_prefix:   "" => "alias/tf-acc-key-alias-9109626292984107802" (forces new resource)
target_key_id: "" => "cc70e683-f4b6-4ca3-a6ce-b53d4805f89b"
=== RUN   TestAccAWSKmsAlias_no_name
--- FAIL: …
```
=> r/kms_alias: Retry lookups after creation

aws/resource_aws_ami.go, aws/resource_aws_ami_test.go
This is mainly to address the following flaky tests, but it may also reduce the flakiness for some users:
```
=== RUN   TestAccAWSAMI_basic
--- FAIL: TestAccAWSAMI_basic (2443.32s)
testing.go:492: Error destroying resource! WARNING: Dangling resources
Error: Check failed: InvalidAMIID.NotFound: The image id '[ami-f6a4b18f]' does not exist
status code: 400, request id: 00d82bfc-bf05-4227-852f-202dc6b833de
State: <no state>
=== RUN   TestAccAWSAMIFromInstance
--- FAIL: TestAccAWSAMIFromInstance (103.70s)
testing.go:492: Error destroying resource! WARNING: Dangling resources
Error: Check failed: InvalidAMIID.NotFound: The image id '[ami-a48fb9b2]' does not exist
status code: 400, request …
```
=> r/ami: Retry on InvalidAMIID.NotFound

aws/resource_aws_dms_replication_instance.go
This was mentioned in https://github.com/hashicorp/terraform/issues/119#issuecomment-314408125
=> resource/aws_dms_replication_instance: Add modifying as a pending creation state

website/docs/r/ebs_volume.html.md
=> docs/ebs_volume: Add a note about the Elastic Volumes considerations

aws/resource_aws_spot_instance_request.go, aws/resource_aws_spot_instance_request_test.go, website/docs/r/spot_instance_request.html.markdown
Added an option for setting the launch group when creating a spot instance request.
=> spot instance request launch group

aws/data_source_aws_db_instance.go
=> data/aws_db_instance: Fix the output of subnet_group_name

aws/resource_aws_rds_cluster_instance.go, aws/resource_aws_rds_cluster_instance_test.go, website/docs/r/rds_cluster_instance.html.markdown
=> resource/rds_cluster_instance: Export the RDI Resource ID for the instance

aws/resource_aws_eip.go
We experience a significant amount of flakes when destroying a cluster. The error that occurs is as follows:
```
Error applying plan:
1 error(s) occurred:
* module.vpc.aws_nat_gateway.nat_gw[2]: index 2 out of range for list aws_eip.nat_eip.*.id (max 2) in:
${aws_eip.nat_eip.*.id[count.index]}
```
CI jenkins log, filtered by the relationship between `aws_nat_gateway` and `nat_eip`:
```
$ egrep 'nat_eip|aws_nat_gateway' jenkins-tectonic-installer.prod.coreos.systems.txt 
+ module.vpc.aws_eip.nat_eip.0
+ module.vpc.aws_eip.nat_eip.1
+ module.vpc.aws_eip.nat_eip.2
+ module.vpc.aws_nat_gateway.nat_gw.0
allocation_id:        "${aws_eip.nat_eip.*.id[count.index]}"
+ module.vpc.aws_nat_gateway.nat_gw.1
allocation_id:        "${aws_eip.nat_eip.*.id[count.index]}"
+ …
```
=> r/resource_aws_eip: implement retry reading EIPs

aws/resource_aws_elasticache_parameter_group.go
Using the same logic than rds to support more than 20 parameters in one group.
```
* aws_elasticache_parameter_group.elasticache_parameter_group: Error modifying Cache Parameter Group: InvalidParameterCombination: Cannot modify more than 20 parameters in a single request
status code: 400, request id: b3421980-7069-11e7-a959-9f5837c56da2
```
=> support more than 20 parameters in elasticacheGroupParameterGroup

aws/resource_aws_api_gateway_account_test.go
```
=== RUN   TestAccAWSAPIGatewayAccount_basic
--- FAIL: TestAccAWSAPIGatewayAccount_basic (2.58s)
testing.go:428: Step 0 error: Error applying: 1 error(s) occurred:
* aws_iam_role.cloudwatch: 1 error(s) occurred:
* aws_iam_role.cloudwatch: Error creating IAM Role api_gateway_cloudwatch_global: EntityAlreadyExists: Role with name api_gateway_cloudwatch_global already exists.
status code: 409, request id: d856fc95-7030-11e7-b2bc-c757bd196036
FAIL
```
```
make testacc TEST=./aws TESTARGS='-run=TestAccAWSAPIGatewayAccount_'
TF_ACC=1 go test ./aws -v -run=TestAccAWSAPIGatewayAccount_ -timeout 120m
=== RUN   TestAccAWSAPIGatewayAccount_importBasic
--- PASS: …
```
=> r/api_gateway_account: Randomize IAM role name in test

aws/import_aws_cloudwatch_dashboard_test.go, aws/provider.go, aws/resource_aws_cloudwatch_dashboard.go, aws/resource_aws_cloudwatch_dashboard_test.go, aws/validators.go, aws/validators_test.go
Hi there! I noticed that there wasn't any support for CloudWatch dashboards yet, so I though I'd throw together a little something to at least see if I'm approaching this from the correct standpoint! If this looks mostly good, I'll go ahead with writing more acceptance tests and writing up the documentation for this section.
Thanks!
=> Add support for aws_cloudwatch_dashboard resource

aws/data_source_aws_internet_gateway.go, aws/data_source_aws_internet_gateway_test.go, aws/provider.go, website/aws.erb, website/docs/d/internet_gateway.html.markdown
This implements `DescribeInternetGateways` API
Fixes #1196
=> #1196: added data source aws_internet_gateway

vendor/github.com/aws/aws-sdk-go/aws/version.go, vendor/github.com/aws/aws-sdk-go/service/ec2/api.go, vendor/vendor.json
=> dependencies: Bump AWS SDK to 1.10.18

website/docs/d/iam_role.html.markdown, website/docs/r/iam_role_policy.html.markdown
Fixes https://github.com/terraform-providers/terraform-provider-aws/issues/830
=> Updated IAM Role & IAM Role Policy documentation

website/docs/r/iam_role.html.markdown
=> docs/aws_iam_role: Fix the ordering of the docs for assume_role note

aws/data_source_aws_iam_role.go
=> Fixed required name in iam role data source

aws/resource_aws_instance_test.go
```
=== RUN   TestAccAWSInstanceDataSource_keyPair
--- PASS: TestAccAWSInstanceDataSource_keyPair (87.33s)
=== RUN   TestAccAWSInstance_GP2IopsDevice
--- PASS: TestAccAWSInstance_GP2IopsDevice (94.00s)
=== RUN   TestAccAWSInstance_blockDevices
--- PASS: TestAccAWSInstance_blockDevices (99.94s)
=== RUN   TestAccAWSInstanceDataSource_SecurityGroups
--- PASS: TestAccAWSInstanceDataSource_SecurityGroups (110.42s)
=== RUN   TestAccAWSInstance_noAMIEphemeralDevices
--- PASS: TestAccAWSInstance_noAMIEphemeralDevices (115.98s)
=== RUN   TestAccAWSInstance_rootInstanceStore
--- PASS: TestAccAWSInstance_rootInstanceStore (116.43s)
=== RUN   TestAccAWSInstanceDataSource_basic
--- PASS: TestAccAWSInstanceDataSource_basic (140.72s)
=== RUN   TestAccAWSInstance_ipv6AddressCountAndSingleAddressCausesErro …
```
=> r/aws_instance: Randomize security group names

website/docs/r/route_table.html.markdown
=> Fix for route_table.html typography

website/docs/d/iam_role.html.markdown
=> Fixed the documentation for the IAM role data source

aws/resource_aws_elasticsearch_domain.go, aws/resource_aws_elasticsearch_domain_test.go
=> r/elasticsearch_domain: Check for duplicate domain name

aws/resource_aws_ssm_patch_baseline.go, aws/resource_aws_ssm_patch_baseline_test.go, website/docs/r/ssm_patch_baseline.html.markdown
Hi All - This pull request includes an update to support per patch rule compliance levels. 
- Documentation has been updated
- Acceptance tests have been updated and run on the SSM provider
Please let me know if you need anything else to get this merged in. 🍻
=> resource/ssm_patch_baseline: Add compliance level to patch approval rules

vendor/github.com/aws/aws-sdk-go/aws/endpoints/defaults.go, vendor/github.com/aws/aws-sdk-go/aws/version.go, vendor/github.com/aws/aws-sdk-go/service/applicationautoscaling/api.go, vendor/github.com/aws/aws-sdk-go/service/applicationautoscaling/doc.go, vendor/github.com/aws/aws-sdk-go/service/ec2/api.go, vendor/github.com/aws/aws-sdk-go/service/elbv2/api.go, vendor/github.com/aws/aws-sdk-go/service/elbv2/doc.go, vendor/github.com/aws/aws-sdk-go/service/elbv2/errors.go, vendor/github.com/aws/aws-sdk-go/service/route53/api.go, vendor/github.com/aws/aws-sdk-go/service/route53/errors.go, vendor/vendor.json
Adds support for filtering NATGateways based on Tags
=> Dependencies: Bump AWS SDK to 1.10.40

aws/provider.go, aws/resource_aws_waf_rate_based_rule.go, aws/resource_aws_waf_rate_based_rule_test.go
https://docs.aws.amazon.com/waf/latest/APIReference/API_regional_RateBasedRule.html#WAF-Type-regional_RateBasedRule-MatchPredicates
=> Add Waf RateBasedRule

website/docs/r/appautoscaling_policy.html.markdown
This was forgotten in https://github.com/terraform-providers/terraform-provider-aws/pull/1620
=> docs: Update appautoscaling_policy docs

website/docs/r/alb.html.markdown
Just a small formatting correction I noticed while looking through docs and evaluating https://github.com/terraform-community-modules/tf_aws_alb/pull/13
=> Docs: updated attribute list item to match others

aws/resource_aws_route53_record.go, aws/resource_aws_route53_record_test.go, website/docs/r/route53_record.html.markdown
https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/routing-policy.html#routing-policy-multivalue
Fixes #1205
=> Add support for Route53 multi-value answer routing policy

website/docs/d/iam_role.html.markdown
Fix  broken example code for #1724
=> Update iam_role data source example to provide working example

vendor/github.com/aws/aws-sdk-go/aws/endpoints/defaults.go, vendor/github.com/aws/aws-sdk-go/aws/session/env_config.go, vendor/github.com/aws/aws-sdk-go/aws/version.go, vendor/github.com/aws/aws-sdk-go/service/apigateway/api.go, vendor/github.com/aws/aws-sdk-go/service/apigateway/errors.go, vendor/github.com/aws/aws-sdk-go/service/cloudwatchlogs/api.go, vendor/github.com/aws/aws-sdk-go/service/codebuild/api.go, vendor/github.com/aws/aws-sdk-go/service/codepipeline/api.go, vendor/github.com/aws/aws-sdk-go/service/codepipeline/doc.go, vendor/github.com/aws/aws-sdk-go/service/configservice/api.go, vendor/github.com/aws/aws-sdk-go/service/ec2/api.go, vendor/github.com/aws/aws-sdk-go/service/ecs/api.go, vendor/github.com/aws/aws-sdk-go/service/iam/api.go, vendor/github.com/aws/aws-sdk-go/service/iam/errors.go, vendor/github.com/aws/aws-sdk-go/service/rds/api.go, vendor/github.com/aws/aws-sdk-go/service/servicecatalog/api.go, vendor/github.com/aws/aws-sdk-go/service/ses/api.go, vendor/github.com/aws/aws-sdk-go/service/ses/doc.go, vendor/github.com/aws/aws-sdk-go/service/ses/errors.go, vendor/vendor.json
Adds support for:
* KMS on aws_cloudwatch_log_group
* InstanceInterruptionBehavior on aws_spot_instance_request
+ logs more
=> dependencies: Bump AWS SDK to 1.10.51

aws/resource_aws_rds_cluster_instance.go
Fixes #1743 
https://github.com/terraform-providers/terraform-provider-aws/issues/1743
=> Add configuring-enhanced-monitoring to Pending state list

aws/resource_aws_rds_cluster_instance.go
=> Add states to pending list

aws/resource_aws_kinesis_stream.go, aws/resource_aws_kinesis_stream_test.go, website/docs/r/kinesis_stream.html.markdown
Fixes: #1109
Got an issue with StopEncryption - working on this atm
=> resource/aws_kinesis_stream: Add support for encryption

vendor/github.com/aws/aws-sdk-go/aws/endpoints/defaults.go, vendor/github.com/aws/aws-sdk-go/aws/version.go, vendor/github.com/aws/aws-sdk-go/private/protocol/query/queryutil/queryutil.go, vendor/github.com/aws/aws-sdk-go/service/cloudformation/api.go, vendor/github.com/aws/aws-sdk-go/service/codebuild/api.go, vendor/github.com/aws/aws-sdk-go/service/codebuild/doc.go, vendor/github.com/aws/aws-sdk-go/service/codebuild/errors.go, vendor/github.com/aws/aws-sdk-go/service/dynamodb/doc_custom.go, vendor/github.com/aws/aws-sdk-go/service/ec2/api.go, vendor/github.com/aws/aws-sdk-go/service/ec2/waiters.go, vendor/github.com/aws/aws-sdk-go/service/redshift/api.go, vendor/github.com/aws/aws-sdk-go/service/route53/api.go, vendor/github.com/aws/aws-sdk-go/service/s3/api.go, vendor/github.com/aws/aws-sdk-go/service/ssm/api.go, vendor/github.com/aws/aws-sdk-go/service/ssm/doc.go, vendor/github.com/aws/aws-sdk-go/service/ssm/errors.go, vendor/vendor.json
Required for new SSM features for tagging restrictions
=> dependencies: Bump SDK to 1.12.6

examples/ecs-alb/main.tf
CoreOS have updated descriptions of their AMIs recently.
=> examples: Update CoreOS AMI description

aws/resource_aws_elastic_beanstalk_application_test.go, aws/resource_aws_elastic_beanstalk_environment_test.go
Adds sweepers for Beanstalk ENV/Application. We had some leaks
=> r/beanstalk_environment, r/beanstalk_application: Add sweepers

aws/resource_aws_kms_key.go
This is to address the following test failure from this morning:
```
=== RUN   TestAccAWSEBSVolume_kmsKey
--- FAIL: TestAccAWSEBSVolume_kmsKey (22.84s)
testing.go:434: Step 0 error: Error applying: 1 error(s) occurred:
* aws_kms_key.foo: 1 error(s) occurred:
* aws_kms_key.foo: NotFoundException: Key 'arn:aws:kms:us-west-2:*******:key/eb421bb3-2865-4d7d-b7c6-2c2c3a07dc40' does not exist
status code: 400, request id: f2006223-ad80-11e7-8981-d922c7ad0e59
```
Snippet from related debug log:
```
-----------------------------------------------------
2017/10/10 06:04:58 [DEBUG] [aws-sdk-go] DEBUG: Response kms/DescribeKey Details:
---[ RESPONSE ]--------------------------------------
HTTP/1.1 200 OK
Connection: close
Content-Length: 373
Content-Type: application/x-amz-json-1.1
X-Amzn-Requestid: …
```
=> r/kms_key: Retry getting key policy

aws/resource_aws_lambda_function.go
When updating an existing lambda function and the publish attribute is set to `true` attribute changes do not get applied to the published version of the lambda.  These are things like environment variables and the lambda description.
In order to fix this I have reversed the order of update so that the lambda code gets updated after other attributes have been updated.
=> Fix Lambda Function Updates When Published

website/docs/r/security_group.html.markdown
=> Adding vpc_id to aws_security_group resource md (fixes #1670)

aws/resource_aws_security_group_rule.go
It’s a valid combination to set `self false` and using `cidr_blocks`. So changing the validation to reflect this as currently this gives you a validation error.
=> Using `self false` icw `cidr_blocks` should be allowed

vendor/github.com/aws/aws-sdk-go/service/codecommit/api.go, vendor/github.com/aws/aws-sdk-go/service/codecommit/doc.go, vendor/github.com/aws/aws-sdk-go/service/codecommit/errors.go, vendor/github.com/aws/aws-sdk-go/service/databasemigrationservice/api.go, vendor/github.com/aws/aws-sdk-go/service/ec2/api.go, vendor/github.com/aws/aws-sdk-go/service/ecr/api.go, vendor/github.com/aws/aws-sdk-go/service/ecr/doc.go, vendor/github.com/aws/aws-sdk-go/service/ecr/errors.go, vendor/github.com/aws/aws-sdk-go/service/elasticbeanstalk/api.go, vendor/github.com/aws/aws-sdk-go/service/elasticbeanstalk/errors.go, vendor/github.com/aws/aws-sdk-go/service/elasticsearchservice/api.go, vendor/github.com/aws/aws-sdk-go/service/rds/api.go, vendor/github.com/aws/aws-sdk-go/service/rds/waiters.go, vendor/github.com/aws/aws-sdk-go/service/ses/api.go, vendor/github.com/aws/aws-sdk-go/service/ses/errors.go, vendor/github.com/aws/aws-sdk-go/service/waf/api.go, vendor/github.com/aws/aws-sdk-go/service/waf/errors.go, vendor/github.com/aws/aws-sdk-go/service/wafregional/api.go, vendor/github.com/aws/aws-sdk-go/service/wafregional/errors.go, vendor/vendor.json
`govendor fetch github.com/aws/aws-sdk-go/service/elasticsearchservice@v1.12.12` for https://github.com/terraform-providers/terraform-provider-aws/issues/1949
=> Add aws-sdk-go/service/...@v1.12.12

website/docs/r/api_gateway_integration.html.markdown
=> Documentation fix in api_gateway_integration example - fixes #1934

README.md
Added some instructions to the README on using this provider as a plugin after you've built it.
=> Add instructions on using the provider

aws/data_source_aws_security_group_test.go, aws/resource_aws_elasticache_cluster_test.go, aws/resource_aws_subnet_test.go, aws/resource_aws_vpc_test.go
More _getting things in order, cleaning house_
=> Fix up some missing tags, expand on VPC sweeper, add Subnet sweeper

website/docs/r/ecr_lifecycle_policy.html.markdown
Update the ecr_lifecycle_policy documentation page:
- Fix typo in title
- Add another policy sample based on "tagged" images
=> website: Fix typo + Add another sample in ecr_lifecycle_policy.html

aws/resource_aws_vpc_test.go, aws/resource_aws_vpn_gateway_test.go
```
=== RUN   TestAccAWSVpnGatewayAttachment_basic
--- PASS: TestAccAWSVpnGatewayAttachment_basic (47.99s)
=== RUN   TestAccAWSVpnGatewayAttachment_deleted
--- PASS: TestAccAWSVpnGatewayAttachment_deleted (66.01s)
=== RUN   TestAccAWSVpnGateway_disappears
--- PASS: TestAccAWSVpnGateway_disappears (69.91s)
=== RUN   TestAccAWSVpnGateway_tags
--- PASS: TestAccAWSVpnGateway_tags (76.40s)
=== RUN   TestAccAWSVpnGateway_importBasic
--- PASS: TestAccAWSVpnGateway_importBasic (89.80s)
=== RUN   TestAccAWSVpnGateway_withAvailabilityZoneSetToState
--- PASS: TestAccAWSVpnGateway_withAvailabilityZoneSetToState (91.35s)
=== RUN   TestAccAWSVpnGateway_delete
--- PASS: TestAccAWSVpnGateway_delete (93.43s)
=== RUN   TestAccAWSVpnGateway_basic
--- PASS: TestAccAWSVpnGateway_basic (141.21s)
=== RUN …
```
=> r/aws_vpn_gateway: Add sweeper

aws/resource_aws_vpn_gateway.go
```
=== RUN   TestAccAWSVpnGateway_reattach
--- FAIL: TestAccAWSVpnGateway_reattach (288.76s)
testing.go:492: Step 1 error: Error applying: 1 error(s) occurred:
* aws_vpn_gateway.foo: 1 error(s) occurred:
* aws_vpn_gateway.foo: Gateway not found, retry for eventual consistancy
```
=> r/vpn_gateway: Raise timeout for attach retry

aws/data_source_aws_elasticache_replication_group.go, aws/data_source_aws_elasticache_replication_group_test.go, aws/provider.go, website/aws.erb, website/docs/d/elasticache_replication_group.html.markdown
=> New Data Source: aws_elasticache_replication_group

README.md
As per discussion with @radeksimko in #2177, the readme has been updated with specific instructions for updating the vendor folder.
=> Added note about updating the vendor folder.

website/docs/r/dynamodb_table.html.markdown
I was required at least one`attribute` .
=> aws_dynamodb_table Add: required

aws/resource_aws_elasticsearch_domain_policy.go
=> r/aws_elasticsearch_domain_policy: Fix typo in err code

vendor/github.com/aws/aws-sdk-go/aws/endpoints/defaults.go, vendor/github.com/aws/aws-sdk-go/aws/request/request.go, vendor/github.com/aws/aws-sdk-go/aws/signer/v4/v4.go, vendor/github.com/aws/aws-sdk-go/aws/version.go, vendor/github.com/aws/aws-sdk-go/service/ecs/api.go, vendor/github.com/aws/aws-sdk-go/service/lightsail/api.go, vendor/github.com/aws/aws-sdk-go/service/route53/api.go, vendor/github.com/aws/aws-sdk-go/service/ssm/api.go, vendor/vendor.json
=> Bump aws sdk to v1.12.27

website/docs/r/instance.html.markdown
=> Additional EC2 instance resource documentation surrounding iam_instance_profile permissions

website/docs/r/cognito_user_pool.markdown
=> docs: Fix layout for cognito_user_pool

aws/structure.go
Fixes https://github.com/terraform-providers/terraform-provider-aws/issues/2365
=> Fixed Cognito Lambda Config Validation for optional ARN configurations

aws/resource_aws_api_gateway_method_response.go
This hopefully fixes #483 
I have added a mutex to prevent concurrent method response creations. As this does not help with simultaneous executions of terraform (e.g., multiple developers deploying to the same AWS account), I have also added a retry block.
@radeksimko @steve-gray Does this look good to you?
=> Fix conflict exception in API gateway method response

website/docs/r/rds_cluster.html.markdown
=> r/aws_rds_cluster: Update database_name documentation with link to RDS naming constraints documentation

website/docs/r/elasticache_replication_group.html.markdown
Fix typo on example title and change snapshot_window description.
=> Minor fix for elasticache_replication_group documentation

aws/resource_aws_elasticache_parameter_group.go, aws/resource_aws_elasticache_parameter_group_test.go
=> r/elasticache_parameter_group: Add StateFunc to make name lowercase

vendor/github.com/aws/aws-sdk-go/aws/version.go, vendor/github.com/aws/aws-sdk-go/service/apigateway/api.go, vendor/github.com/aws/aws-sdk-go/service/apigateway/doc.go, vendor/github.com/aws/aws-sdk-go/service/ec2/api.go, vendor/github.com/aws/aws-sdk-go/service/lambda/api.go, vendor/github.com/aws/aws-sdk-go/service/lambda/errors.go, vendor/vendor.json
[CHANGELOG](https://github.com/aws/aws-sdk-go/blob/v1.12.38/CHANGELOG.md)
```
go get -u github.com/kardianos/govendor
govendor --version v1.0.9
govendor fetch github.com/aws/aws-sdk-go/...@v1.12.38
```
=> Bump aws-sdk-go to v1.12.38

aws/resource_aws_iam_server_certificate_test.go
To clean up leaked certificates from tests.
=> Add sweeper for IAM Server Certificates

website/docs/r/eip.html.markdown
depends_on                = ["aws_internet_gateway.gw"] is the correct syntax
=> Corrected depends_on entry for EIP

aws/resource_aws_api_gateway_api_key.go, aws/resource_aws_api_gateway_base_path_mapping.go, aws/resource_aws_api_gateway_deployment.go, aws/resource_aws_api_gateway_domain_name.go, aws/resource_aws_api_gateway_integration.go, aws/resource_aws_api_gateway_integration_response.go, aws/resource_aws_api_gateway_method.go, aws/resource_aws_api_gateway_method_response.go, aws/resource_aws_api_gateway_method_settings.go, aws/resource_aws_api_gateway_model.go, aws/resource_aws_api_gateway_request_validator.go, aws/resource_aws_api_gateway_rest_api.go, aws/resource_aws_api_gateway_stage.go, aws/resource_aws_api_gateway_usage_plan.go, aws/resource_aws_api_gateway_usage_plan_key.go
Context: API Gateway resources
=> Added missing WARN debug lines when reading a non-existing resource

vendor/github.com/aws/aws-sdk-go/aws/endpoints/defaults.go, vendor/github.com/aws/aws-sdk-go/aws/version.go, vendor/github.com/aws/aws-sdk-go/service/cognitoidentityprovider/api.go, vendor/vendor.json
`govendor fetch github.com/aws/aws-sdk-go/...@v1.12.45`
=> Bump aws-sdk-go to v.1.12.45

website/docs/r/api_gateway_method.html.markdown
Because I had some trouble to find how to add "URL Query String Parameters" and a request validator.
=> Add more example and missing field

website/docs/d/db_snapshot.html.markdown, website/docs/d/kinesis_stream.html.markdown, website/docs/r/api_gateway_method.html.markdown, website/docs/r/autoscaling_group.html.markdown, website/docs/r/cognito_identity_pool.markdown, website/docs/r/cognito_identity_pool_roles_attachment.markdown, website/docs/r/db_snapshot.html.md, website/docs/r/default_subnet.html.markdown, website/docs/r/default_vpc.html.markdown, website/docs/r/default_vpc_dhcp_options.html.markdown, website/docs/r/ecs_task_definition.html.markdown, website/docs/r/emr_cluster.html.md, website/docs/r/flow_log.html.markdown, website/docs/r/network_interface_attachment.html.markdown, website/docs/r/wafregional_byte_match_set.html.markdown, website/docs/r/wafregional_ipset.html.markdown
I add language name to code block by reason of syntax highlighting.
=> Update docs for syntax lighlighting

website/docs/r/cognito_user_pool.markdown
=> docs/cognito_user_pool: Add notes to email message and subject

vendor/github.com/aws/aws-sdk-go/aws/endpoints/defaults.go, vendor/github.com/aws/aws-sdk-go/aws/version.go, vendor/github.com/aws/aws-sdk-go/service/apigateway/api.go, vendor/github.com/aws/aws-sdk-go/service/mediastoredata/api.go, vendor/github.com/aws/aws-sdk-go/service/route53/api.go, vendor/github.com/aws/aws-sdk-go/service/route53/errors.go, vendor/vendor.json
`govendor fetch github.com/aws/aws-sdk-go/...@v1.12.50`
=> Bump aws-sdk-go to v1.12.50

aws/resource_aws_s3_bucket_object.go
Fix https://github.com/terraform-providers/terraform-provider-aws/issues/2664
=> add support for govcloud s3 object tags

website/docs/r/ecs_task_definition.html.markdown
=> Fix FARGATE ECS task definition doc

vendor/github.com/aws/aws-sdk-go/aws/endpoints/defaults.go, vendor/github.com/aws/aws-sdk-go/aws/version.go, vendor/github.com/aws/aws-sdk-go/service/configservice/api.go, vendor/github.com/aws/aws-sdk-go/service/iot/api.go, vendor/vendor.json
`govendor fetch github.com/aws/aws-sdk-go/...@v1.12.51`
=> Bump aws-sdk-go to v1.12.51

website/docs/d/network_interface.html.markdown
For consistency, let's document that ENIs can be imported and how to do that.
=> document import for ENIs

aws/resource_aws_elasticsearch_domain.go
=> r/elasticsearch_domain: Avoid nil pointer when Enabled=false

website/docs/index.html.markdown
New endpoints were added in #2795 and #2641 - here I'm just adding some missing docs.
=> docs: Document new custom endpoints

vendor/github.com/aws/aws-sdk-go/aws/endpoints/defaults.go, vendor/github.com/aws/aws-sdk-go/aws/version.go, vendor/github.com/aws/aws-sdk-go/service/rds/api.go, vendor/github.com/aws/aws-sdk-go/service/workspaces/api.go, vendor/github.com/aws/aws-sdk-go/service/workspaces/doc.go, vendor/vendor.json
`govendor fetch github.com/aws/aws-sdk-go/...@v1.12.55`
=> Bump aws-sdk-go to v1.12.55

aws/resource_aws_db_parameter_group.go, aws/resource_aws_db_parameter_group_test.go
@radeksimko @korfuri - I have also hit this bug and would like to get this pushed through. This is a continuation of PR #2620 with the additional test requested. 
fixes #490 
cc/ @nrvale0
=> Addresses #490 - DB Parameter Group Not Found

vendor/github.com/aws/aws-sdk-go/aws/version.go, vendor/github.com/aws/aws-sdk-go/service/inspector/api.go, vendor/github.com/aws/aws-sdk-go/service/ssm/api.go, vendor/github.com/aws/aws-sdk-go/service/ssm/errors.go, vendor/vendor.json
`govendor fetch github.com/aws/aws-sdk-go/...@v1.12.56`
=> Bump aws-sdk-go to v1.12.56

aws/resource_aws_load_balancer_backend_server_policy_test.go
This is to avoid test failure related to leaked LBs and to follow best practice.
```
=== RUN   TestAccAWSLoadBalancerBackendServerPolicy_basic
--- PASS: TestAccAWSLoadBalancerBackendServerPolicy_basic (180.42s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	180.448s
```
=> test/aws_load_balancer_backend_server_policy: Randomize LB name

aws/resource_aws_ssm_maintenance_window.go, aws/resource_aws_ssm_maintenance_window_test.go
`enabled` isn't set correctly via create cycle.
=> r/ssm_maintenance_window: Fix ssm maintenance window

vendor/github.com/aws/aws-sdk-go/aws/version.go, vendor/github.com/aws/aws-sdk-go/service/codedeploy/api.go, vendor/github.com/aws/aws-sdk-go/service/codedeploy/doc.go, vendor/github.com/aws/aws-sdk-go/service/codedeploy/errors.go, vendor/github.com/aws/aws-sdk-go/service/route53/api.go, vendor/github.com/aws/aws-sdk-go/service/route53/errors.go, vendor/vendor.json
`govendor fetch github.com/aws/aws-sdk-go/...@v1.12.57`
=> Bump aws-sdk-go to v1.12.57

website/docs/r/code_commit_repository.html.markdown
`import` function in code but not documented
=> docs/r/codecommit_repository: document import for resource codecommit_repository

aws/resource_aws_ecs_cluster.go, aws/resource_aws_ecs_cluster_test.go, website/docs/r/ecs_cluster.html.markdown
Part of #1762.
This pull request is kind of duplicate of #1962, but there's no move over one month. It also include suggestion from @bflad to allow read function to do extra logics.
Eager to get this feature done.
Closes #1962
=> r/aws_ecs_cluster: support resource import

vendor/github.com/aws/aws-sdk-go/aws/version.go, vendor/github.com/aws/aws-sdk-go/service/elb/api.go, vendor/github.com/aws/aws-sdk-go/service/elb/doc.go, vendor/github.com/aws/aws-sdk-go/service/elb/errors.go, vendor/github.com/aws/aws-sdk-go/service/elbv2/api.go, vendor/github.com/aws/aws-sdk-go/service/elbv2/errors.go, vendor/github.com/aws/aws-sdk-go/service/rds/api.go, vendor/github.com/aws/aws-sdk-go/service/ssm/api.go, vendor/github.com/aws/aws-sdk-go/service/ssm/errors.go, vendor/vendor.json
`govendor fetch github.com/aws/aws-sdk-go/...@v1.12.60`
=> Bump aws-sdk-go to v1.12.60

CHANGELOG.md
=> CHANGELOG: Fix link to 1.7.0 released #2082

vendor/github.com/aws/aws-sdk-go/aws/version.go, vendor/github.com/aws/aws-sdk-go/service/glue/api.go, vendor/vendor.json
`govendor fetch github.com/aws/aws-sdk-go/...@v1.12.61`
=> Bump aws-sdk-go to v1.12.61

.github/CONTRIBUTING.md
I'm not sure how to structure this quite yet, nor sure to its accuracy, but most of it is lifted from my discussion with @bflad and @radeksimko in #2175.
=> [RFC] Code Style and Schema Structure

aws/resource_aws_sns_topic_subscription.go
Fixes #2557 by removing some duplicate update logic causing panics that would be caught by running the existing error checking already handled on create, e.g.
```go
if err != nil {
return err
}
if subscriptionHasPendingConfirmation(output.SubscriptionArn) {
log.Printf("[WARN] Invalid SNS Subscription, received a \"%s\" ARN", awsSNSPendingConfirmationMessage)
return nil
}
```
Tests pass locally for me:
```
make testacc TEST=./aws TESTARGS='-run=TestAccAWSSNSTopicSubscription'
TF_ACC=1 go test ./aws -v -run=TestAccAWSSNSTopicSubscription -timeout 120m
=== RUN   TestAccAWSSNSTopicSubscription_importBasic
--- PASS: TestAccAWSSNSTopicSubscription_importBasic (16.90s)
=== RUN   TestAccAWSSNSTopicSubscription_basic
--- PASS: …
```
=> r/aws_sns_topic_subscription: Use ForceNew instead of custom logic to reduce chances for panic

aws/resource_aws_autoscaling_schedule_test.go
Fixes the following tests:
```
=== RUN   TestAccAWSAutoscalingSchedule_negativeOne
--- FAIL: TestAccAWSAutoscalingSchedule_negativeOne (128.46s)
* aws_autoscaling_schedule.foobar: 1 error(s) occurred:
* aws_autoscaling_schedule.foobar: Error Creating Autoscaling Scheduled Action: ValidationError: Given start time is in the past
status code: 400, request id: 2208d251-fb48-11e7-b3f1-65197f129532
=== RUN   TestAccAWSAutoscalingSchedule_zeroValues
--- FAIL: TestAccAWSAutoscalingSchedule_zeroValues (155.86s)
* aws_autoscaling_schedule.foobar: 1 error(s) occurred:
* aws_autoscaling_schedule.foobar: Error Creating Autoscaling Scheduled Action: ValidationError: …
```
=> resource/aws_autoscaling_schedule: Remove hardcoded start/end times from acceptance testing

vendor/github.com/aws/aws-sdk-go/aws/version.go, vendor/github.com/aws/aws-sdk-go/service/applicationautoscaling/api.go, vendor/github.com/aws/aws-sdk-go/service/applicationautoscaling/doc.go, vendor/github.com/aws/aws-sdk-go/service/applicationautoscaling/errors.go, vendor/github.com/aws/aws-sdk-go/service/ec2/api.go, vendor/github.com/aws/aws-sdk-go/service/ec2/doc.go, vendor/github.com/aws/aws-sdk-go/service/rds/api.go, vendor/github.com/aws/aws-sdk-go/service/sagemaker/api.go, vendor/vendor.json
`govendor fetch github.com/aws/aws-sdk-go/...@v1.12.65`
=> Bump aws-sdk-go to v1.12.65

vendor/github.com/hashicorp/terraform/helper/customdiff/compose.go, vendor/github.com/hashicorp/terraform/helper/customdiff/computed.go, vendor/github.com/hashicorp/terraform/helper/customdiff/condition.go, vendor/github.com/hashicorp/terraform/helper/customdiff/doc.go, vendor/github.com/hashicorp/terraform/helper/customdiff/force_new.go, vendor/github.com/hashicorp/terraform/helper/customdiff/validate.go, vendor/vendor.json
Fixes #3082
`govendor fetch github.com/hashicorp/terraform/helper/customdiff@v0.11.2`
=> Vendor in 'github.com/hashicorp/terraform/helper/customdiff' @v0.11.2

website/docs/r/lb_target_group.html.markdown
=> docs/r/lb_load_target_group: update healthy_threshold and healthy_threshold

aws/resource_aws_eip_association.go, aws/resource_aws_eip_association_test.go
Closes #74
Closes #3041 
Created failing acceptance test:
```
make testacc TEST=./aws TESTARGS='-run=TestAccAWSEIPAssociation_spotInstance'
TF_ACC=1 go test ./aws -v -run=TestAccAWSEIPAssociation_spotInstance -timeout 120m
=== RUN   TestAccAWSEIPAssociation_spotInstance
--- FAIL: TestAccAWSEIPAssociation_spotInstance (83.92s)
* aws_eip_association.test: 1 error(s) occurred:
* aws_eip_association.test: [WARN] Error attaching EIP, message: "The pending instance 'i-0fd1d57b0b3e9ea0a' is not in a valid state for this operation.", code: "InvalidInstanceID"
FAIL
exit status 1
FAIL	github.com/terraform-providers/terraform-provider-aws/aws	83.975s
make: *** [testacc] Error …
```
=> resource/aws_eip_assocation: Retry association for pending instances

aws/resource_aws_lambda_function_test.go
This is a simple approach to make the test pass, but the real (clean) solution will most likely require some core changes to allow us change dependencies during destruction of specific resources.
Basically we'd need to reverse the ordering of destroy/apply operations between `aws_kms_key` & `aws_lambda_function`.
Fixes #2959
```
=== RUN   TestAccAWSLambdaFunction_encryptedEnvVariables
--- PASS: TestAccAWSLambdaFunction_encryptedEnvVariables (118.99s)
```
=> test/aws_lambda_function: Keep KMS key enabled during decryption

aws/resource_aws_spot_fleet_request.go
This is to provide more details to currently very brief error message:
```
=== RUN   TestAccAWSSpotFleetRequest_lowestPriceSubnetInGivenList
--- FAIL: TestAccAWSSpotFleetRequest_lowestPriceSubnetInGivenList (71.94s)
* aws_spot_fleet_request.foo: 1 error(s) occurred:
* aws_spot_fleet_request.foo: unexpected state 'error', wanted target 'fulfilled'. last error: %!s(<nil>)
```
```
=== RUN   TestAccAWSSpotFleetRequest_CannotUseEmptyKeyName
--- PASS: TestAccAWSSpotFleetRequest_CannotUseEmptyKeyName (0.00s)
=== RUN   TestAccAWSSpotFleetRequest_placementTenancy
--- PASS: TestAccAWSSpotFleetRequest_placementTenancy (61.38s)
=== RUN   TestAccAWSSpotFleetRequest_lowestPriceSubnetInGivenList
--- FAIL: …
```
=> resource/aws_spot_fleet_request: Expose reason of erroneous state

vendor/github.com/aws/aws-sdk-go/aws/endpoints/defaults.go, vendor/github.com/aws/aws-sdk-go/aws/version.go, vendor/github.com/aws/aws-sdk-go/service/budgets/api.go, vendor/github.com/aws/aws-sdk-go/service/glue/api.go, vendor/vendor.json
`govendor fetch github.com/aws/aws-sdk-go/...@v1.12.67`
=> Bump aws-sdk-go to v1.12.67

aws/resource_aws_cognito_user_pool.go, aws/resource_aws_cognito_user_pool_test.go, aws/structure.go, examples/cognito-user-pool/main.tf, website/docs/r/cognito_user_pool.markdown
=> r/cognito_user_pool: support pre_token_generation in lambda_config

aws/resource_aws_sqs_queue_test.go
Addressing intermittent test failure (presumably some slight eventual consistency with SQS):
```
=== RUN   TestAccAWSSQSQueue_basic
--- FAIL: TestAccAWSSQSQueue_basic (29.39s)
testing.go:573: Error destroying resource! WARNING: Dangling resources
Error: Check failed: Queue https://sqs.us-west-2.amazonaws.com/*******/sqs-queue-nrjuzb94sv still exists. Failing!
```
Passes locally for me:
```
make testacc TEST=./aws TESTARGS='-run=TestAccAWSSQSQueue_'
TF_ACC=1 go test ./aws -v -run=TestAccAWSSQSQueue_ -timeout 120m
=== RUN   TestAccAWSSQSQueue_importBasic
--- PASS: TestAccAWSSQSQueue_importBasic (13.26s)
=== RUN   TestAccAWSSQSQueue_importFifo
--- PASS: TestAccAWSSQSQueue_importFifo …
```
=> test/aws_sqs_queue: Add short retry for check destroy testing

vendor/github.com/aws/aws-sdk-go/aws/endpoints/decode.go, vendor/github.com/aws/aws-sdk-go/aws/endpoints/defaults.go, vendor/github.com/aws/aws-sdk-go/aws/request/request_pagination.go, vendor/github.com/aws/aws-sdk-go/aws/version.go, vendor/github.com/aws/aws-sdk-go/service/codebuild/api.go, vendor/github.com/aws/aws-sdk-go/service/devicefarm/api.go, vendor/github.com/aws/aws-sdk-go/service/guardduty/api.go, vendor/github.com/aws/aws-sdk-go/service/lambda/api.go, vendor/github.com/aws/aws-sdk-go/service/lambda/errors.go, vendor/github.com/aws/aws-sdk-go/service/medialive/api.go, vendor/vendor.json
`govendor fetch github.com/aws/aws-sdk-go/...@v1.12.70`
=> Bump aws-sdk-go to v1.12.70

website/docs/r/codepipeline.markdown
updating codepipeline encryption key documentation
=> CodePipeline Doc Update Encryption Key

aws/provider.go, aws/resource_aws_guardduty_test.go, aws/resource_aws_guardduty_threatintelset.go, aws/resource_aws_guardduty_threatintelset_test.go, aws/validators.go, aws/validators_test.go, website/aws.erb, website/docs/r/guardduty_threatintelset.html.markdown
```
TF_ACC=1 go test ./aws -v -run=TestAccAWSGuardDuty -timeout 120m
=== RUN   TestAccAWSGuardDuty
=== RUN   TestAccAWSGuardDuty/Member
=== RUN   TestAccAWSGuardDuty/Member/basic
=== RUN   TestAccAWSGuardDuty/Member/import
=== RUN   TestAccAWSGuardDuty/Detector
=== RUN   TestAccAWSGuardDuty/Detector/basic
=== RUN   TestAccAWSGuardDuty/Detector/import
=== RUN   TestAccAWSGuardDuty/IPSet
=== RUN   TestAccAWSGuardDuty/IPSet/basic
=== RUN   TestAccAWSGuardDuty/IPSet/import
=== RUN   TestAccAWSGuardDuty/ThreatIntelSet
=== RUN   TestAccAWSGuardDuty/ThreatIntelSet/basic
=== RUN   TestAccAWSGuardDuty/ThreatIntelSet/import
--- PASS: TestAccAWSGuardDuty (878.71s)
--- PASS: TestAccAWSGuardDuty/Member (128.47s)
--- PASS: TestAccAWSGuardDuty/Member/basic (59.46s)
--- PASS: …
```
=> New Resource: aws_guardduty_threatintelset

website/docs/d/instances.html.markdown
Had a hard time figuring out how to use the `filter` map from the description. (Had to read [PR's code](https://github.com/terraform-providers/terraform-provider-aws/pull/2266/files#diff-9d56daa8743436fdb33d32ed662f421bR85) actually.)
* Add example usage for the `filter` map.
=> website: Improve d/instances example

aws/resource_aws_dx_connection_association.go
```
=== RUN   TestAccAwsDxConnectionAssociation_multiConns
--- FAIL: TestAccAwsDxConnectionAssociation_multiConns (6.83s)
testing.go:573: Error destroying resource! WARNING: Dangling resources
Error: Error applying: 2 error(s) occurred:
* aws_dx_connection_association.test1 (destroy): 1 error(s) occurred:
* aws_dx_connection_association.test1: DirectConnectClientException: Connection dxcon-fh9yptf2 is in a transitioning state.
status code: 400, request id: 8c7f1f03-0323-11e8-9b6e-1bcbdac10921
* aws_dx_connection_association.test2 (destroy): 1 error(s) occurred:
* aws_dx_connection_association.test2: DirectConnectClientException: Connection dxcon-ffrm1ruk is in a transitioning state.
status …
```
=> resource/aws_dx_connection_association: Retry disassociation

aws/resource_aws_ssm_resource_data_sync.go, aws/resource_aws_ssm_resource_data_sync_test.go, website/docs/r/ssm_resource_data_sync.html.markdown
```
TF_ACC=1 go test ./aws -v -run=TestAccAWSSsmResourceDataSync_import -timeout 120m
=== RUN   TestAccAWSSsmResourceDataSync_import
--- PASS: TestAccAWSSsmResourceDataSync_import (67.45s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	67.480s
```
=> resource/ssm_resource_data_sync: Support import

aws/resource_aws_athena_named_query.go, aws/resource_aws_athena_named_query_test.go, website/docs/r/athena_named_query.html.markdown
```
TF_ACC=1 go test ./aws -v -run=TestAccAwsAthenaNamedQuery_import -timeout 120m
=== RUN   TestAccAwsAthenaNamedQuery_import
--- PASS: TestAccAwsAthenaNamedQuery_import (108.15s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	108.182s
```
=> resource/athena_named_query: Support import

vendor/github.com/hashicorp/terraform/LICENSE, vendor/github.com/hashicorp/terraform/config/config.go, vendor/github.com/hashicorp/terraform/helper/schema/provider.go, vendor/github.com/hashicorp/terraform/plugin/discovery/find.go, vendor/github.com/hashicorp/terraform/plugin/discovery/get.go, vendor/github.com/hashicorp/terraform/registry/client.go, vendor/github.com/hashicorp/terraform/svchost/disco/disco.go, vendor/github.com/hashicorp/terraform/terraform/diff.go, vendor/github.com/hashicorp/terraform/terraform/eval_diff.go, vendor/github.com/hashicorp/terraform/terraform/node_resource_apply.go, vendor/github.com/hashicorp/terraform/terraform/plan.go, vendor/github.com/hashicorp/terraform/version/version.go, vendor/vendor.json
```
$ govendor fetch github.com/hashicorp/terraform/...@v0.11.3
$ make test TEST=./aws
go test ./aws -timeout=30s -parallel=4
ok  	github.com/terraform-providers/terraform-provider-aws/aws	1.820s
```
=> vendor: Bump hashicorp/terraform to v0.11.3

aws/resource_aws_service_discovery_service.go, aws/resource_aws_service_discovery_service_test.go, website/docs/r/service_discovery_service.html.markdown
```
TF_ACC=1 go test ./aws -v -run=TestAccAwsServiceDiscoveryService_import -timeout 120m
=== RUN   TestAccAwsServiceDiscoveryService_import
--- PASS: TestAccAwsServiceDiscoveryService_import (79.24s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	79.273s
```
=> resource/aws_service_discovery_service: Support import

aws/resource_aws_ecr_lifecycle_policy.go, aws/resource_aws_ecr_lifecycle_policy_test.go, website/docs/r/ecr_lifecycle_policy.html.markdown
```
TF_ACC=1 go test ./aws -v -run=TestAccAWSEcrLifecyclePolicy_* -timeout 120m
=== RUN   TestAccAWSEcrLifecyclePolicy_basic
--- PASS: TestAccAWSEcrLifecyclePolicy_basic (61.88s)
=== RUN   TestAccAWSEcrLifecyclePolicy_import
--- PASS: TestAccAWSEcrLifecyclePolicy_import (79.13s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	141.054s
```
=> resource/ecr_lifecycle_policy: Support import

aws/data_source_aws_iam_policy_document.go, aws/iam_policy_model.go
Implemented @bflad's [suggestion](https://github.com/terraform-providers/terraform-provider-aws/pull/2890#discussion_r166090513) to refactor previous changes to IAMPolicyDoc and data-source/aws_iam_policy_document.
=> Refactor IAMPolicyDoc.DeDupSids to IAMPolicyDoc.Merge

website/docs/r/codebuild_project.html.markdown
Updates aws_codebuild_project.environment.image description and example.
=> docs: updates CodeBuild image attribute docs

aws/resource_aws_acm_certificate_test.go, aws/resource_aws_acm_certificate_validation_test.go
Simplifying the configuration functions for external acceptance testing usage (validation resource now, data source shortly 😉 ).
```
=== RUN   TestAccAwsAcmCertificate_emailValidation
--- PASS: TestAccAwsAcmCertificate_emailValidation (18.25s)
=== RUN   TestAccAwsAcmCertificate_dnsValidation
--- PASS: TestAccAwsAcmCertificate_dnsValidation (17.47s)
=== RUN   TestAccAwsAcmCertificate_subjectAlternativeNames
--- PASS: TestAccAwsAcmCertificate_subjectAlternativeNames (20.24s)
=== RUN   TestAccAwsAcmCertificate_tags
--- PASS: TestAccAwsAcmCertificate_tags (41.99s)
=== RUN   TestAccAwsAcmCertificateValidation_basic
--- PASS: TestAccAwsAcmCertificateValidation_basic (363.21s)
```
=> test/resource/aws_acm_certificate: Refactor function naming and better parameterize

aws/config.go, aws/provider.go, aws/resource_aws_cloud9_environment_ec2.go, aws/resource_aws_cloud9_environment_ec2_test.go, website/aws.erb, website/docs/r/cloud9_environment_ec2.html.markdown
~Pending: #3290 (I will rebase after merging)~
```
=== RUN   TestAccAWSCloud9EnvironmentEc2_basic
--- PASS: TestAccAWSCloud9EnvironmentEc2_basic (167.80s)
=== RUN   TestAccAWSCloud9EnvironmentEc2_importBasic
--- PASS: TestAccAWSCloud9EnvironmentEc2_importBasic (181.27s)
=== RUN   TestAccAWSCloud9EnvironmentEc2_allFields
--- PASS: TestAccAWSCloud9EnvironmentEc2_allFields (347.28s)
```
=> New Resource: aws_cloud9_environment_ec2

aws/config.go, aws/resource_aws_kinesis_stream.go
```
=== RUN   TestAccAWSKinesisStream_shardLevelMetrics
--- FAIL: TestAccAWSKinesisStream_shardLevelMetrics (149.15s)
testing.go:573: Error destroying resource! WARNING: Dangling resources
Error: Error applying: 1 error(s) occurred:
* aws_kinesis_stream.test_stream (destroy): 1 error(s) occurred:
* aws_kinesis_stream.test_stream: LimitExceededException: Rate exceeded for stream terraform-kinesis-test-6203015600745191945 under account *******.
status code: 400, request id: e8d516ee-dc31-d34e-ba35-e408e9363a84
State: aws_kinesis_stream.test_stream:
ID = arn:aws:kinesis:us-west-2:*******:stream/terraform-kinesis-test-6203015600745191945
provider = provider.aws
arn = …
```
=> resource/aws_kinesis_stream: Retry deletion on LimitExceededException

aws/resource_aws_kinesis_firehose_delivery_stream.go, aws/resource_aws_kinesis_firehose_delivery_stream_test.go
Closes #3133 (incorrect type for extended_s3_configuration.0.kms_key_arn)
Closes #3226 (crash on CloudWatchLoggingOptions)
Closes #3300 (crash on CloudWatchLoggingOptions)
New test fails on master:
```
make testacc TEST=./aws TESTARGS='-run=TestAccAWSKinesisFirehoseDeliveryStream_ExtendedS3KmsKeyArn'
TF_ACC=1 go test ./aws -v -run=TestAccAWSKinesisFirehoseDeliveryStream_ExtendedS3KmsKeyArn -timeout 120m
=== RUN   TestAccAWSKinesisFirehoseDeliveryStream_ExtendedS3KmsKeyArn
--- FAIL: TestAccAWSKinesisFirehoseDeliveryStream_ExtendedS3KmsKeyArn (91.88s)
* aws_kinesis_firehose_delivery_stream.test_stream: 1 error(s) occurred:
* …
```
=> resource/aws_kinesis_firehose_delivery_stream: Prevent crashes on empty CloudWatchLoggingOptions and fix extended_s3_configuration kms_key_arn

aws/resource_aws_cloudtrail.go, aws/resource_aws_cloudtrail_test.go
=> resource/aws_cloudtrail: Replace GetOk with GetOkExists

website/docs/r/db_instance.html.markdown
Refs. https://www.terraform.io/docs/providers/aws/r/db_instance.html
=> Fix a mistake of markdown

aws/provider.go, aws/resource_aws_gamelift_build_test.go, aws/resource_aws_gamelift_fleet.go, aws/resource_aws_gamelift_fleet_test.go, aws/resource_aws_gamelift_test.go, website/aws.erb, website/docs/r/gamelift_fleet.html.markdown
```
=== RUN   TestAccAWSGameliftFleet_basic
--- PASS: TestAccAWSGameliftFleet_basic (1111.72s)
=== RUN   TestAccAWSGameliftFleet_allFields
--- PASS: TestAccAWSGameliftFleet_allFields (1262.53s)
```
Related: https://github.com/terraform-providers/terraform-provider-aws/issues/2546
=> New Resource: aws_gamelift_fleet

vendor/github.com/aws/aws-sdk-go/aws/endpoints/defaults.go, vendor/github.com/aws/aws-sdk-go/aws/version.go, vendor/github.com/aws/aws-sdk-go/service/cognitoidentityprovider/api.go, vendor/github.com/aws/aws-sdk-go/service/ec2/api.go, vendor/github.com/aws/aws-sdk-go/service/ec2/doc.go, vendor/github.com/aws/aws-sdk-go/service/guardduty/api.go, vendor/github.com/aws/aws-sdk-go/service/kms/api.go, vendor/github.com/aws/aws-sdk-go/service/lexmodelbuildingservice/api.go, vendor/github.com/aws/aws-sdk-go/service/rds/api.go, vendor/vendor.json
```
govendor fetch github.com/aws/aws-sdk-go/...@v1.12.75
```
=> deps: Bump aws-sdk-go@v1.12.75

aws/resource_aws_redshift_cluster.go, aws/resource_aws_redshift_cluster_test.go
```
=== RUN   TestAccAWSRedshiftCluster_basic
--- PASS: TestAccAWSRedshiftCluster_basic (623.67s)
=== RUN   TestAccAWSRedshiftCluster_loggingEnabledDeprecated
--- PASS: TestAccAWSRedshiftCluster_loggingEnabledDeprecated (648.81s)
=== RUN   TestAccAWSRedshiftCluster_tags
--- PASS: TestAccAWSRedshiftCluster_tags (766.44s)
=== RUN   TestAccAWSRedshiftCluster_loggingEnabled
--- PASS: TestAccAWSRedshiftCluster_loggingEnabled (771.54s)
=== RUN   TestAccAWSRedshiftCluster_importBasic
--- PASS: TestAccAWSRedshiftCluster_importBasic (771.83s)
=== RUN   TestAccAWSRedshiftCluster_publiclyAccessible
--- PASS: TestAccAWSRedshiftCluster_publiclyAccessible (862.83s)
=== RUN   TestAccAWSRedshiftCluster_kmsKey
--- PASS: TestAccAWSRedshiftCluster_kmsKey (914.46s)
=== RUN …
```
=> resource/aws_redshift_cluster: Add sweepers

aws/resource_aws_dynamodb_table_test.go
=> test/resource/aws_dynamodb_table: Add sweeper

website/docs/r/codebuild_project.html.markdown
Also includes @atsushi-ishibashi doc addition from https://github.com/terraform-providers/terraform-provider-aws/pull/2811 - they kinda need to go together or not at all.
=> Fix docs for codebuild, so the markdown parses properly

aws/config.go, aws/import_aws_dax_cluster_test.go, aws/provider.go, aws/resource_aws_dax_cluster.go, aws/resource_aws_dax_cluster_test.go, aws/structure.go, aws/tagsDAX.go, aws/tagsDAX_test.go, website/aws.erb, website/docs/r/dax_cluster.html.markdown
This adds support for managing AWS DynamoDB Accelerator (DAX). It adds a new aws_dax_cluster resource. Addresses #936
=> New Resource: aws_dax_cluster

aws/resource_aws_vpc_peering_connection.go
```
=== RUN   TestAccAWSVPCPeeringConnection_region
--- FAIL: TestAccAWSVPCPeeringConnection_region (198.11s)
testing.go:573: Error destroying resource! WARNING: Dangling resources
Error: Error applying: 1 error(s) occurred:
* aws_vpc_peering_connection.foo (destroy): 1 error(s) occurred:
* aws_vpc_peering_connection.foo: Error waiting for VPC Peering Connection (pcx-0d36da34ca261a3a8) to be deleted: unexpected state 'pending-acceptance', wanted target 'rejecting, deleted'. last error: %!s(<nil>)
```
```
=== RUN   TestAccAWSVPCPeeringConnection_peerRegionAndAutoAccept
--- PASS: TestAccAWSVPCPeeringConnection_peerRegionAndAutoAccept (26.95s)
=== RUN …
```
=> resource/aws_vpc_peering_connection: Treat pending-acceptance as expected during deletion

website/aws.erb, website/docs/guides/serverless-with-aws-lambda-and-api-gateway.html.md
This is a common pattern that requires some non-obvious interactions between different resources, so we'll present it in tutorial form as a way to present all of the necessary parts together as a working system.
=> website: A guide on serverless apps with Lambda and API Gateway

website/docs/r/cognito_user_group.html.markdown
As noted in https://github.com/terraform-providers/terraform-provider-aws/pull/3347#issuecomment-366075135
cc @jayanderson
=> docs/aws_cognito_user_pool: Fix formatting

website/docs/d/instance.html.markdown
=> Exposed the AMI field in instance.html.markdown

aws/resource_aws_codedeploy_deployment_group.go
Add missing triggerEvents
https://docs.aws.amazon.com/codedeploy/latest/APIReference/API_TriggerConfig.html
=> resource/codedeploy_deployment_group: Add missing triggerEvents

website/docs/guides/serverless-with-aws-lambda-and-api-gateway.html.md
Self-merging, manually verified.
=> docs/guides/serverless: Fix links

website/docs/r/lambda_permission.html.markdown
Minor documentation update as requested in issue #3111
=> #3111 Improve description for Argument "source_account"

website/docs/r/network_acl.html.markdown, website/docs/r/network_acl_rule.html.markdown
Fixes #197. Well, at least it adds some guard rails to prevent others
having the same issue.
=> Mention network_acl rule / network_acl_rule issue

vendor/github.com/aws/aws-sdk-go/aws/endpoints/defaults.go, vendor/github.com/aws/aws-sdk-go/aws/session/session.go, vendor/github.com/aws/aws-sdk-go/aws/version.go, vendor/github.com/aws/aws-sdk-go/service/applicationautoscaling/api.go, vendor/github.com/aws/aws-sdk-go/service/applicationautoscaling/doc.go, vendor/github.com/aws/aws-sdk-go/service/cloudwatchevents/api.go, vendor/github.com/aws/aws-sdk-go/service/ec2/api.go, vendor/github.com/aws/aws-sdk-go/service/ecr/api.go, vendor/github.com/aws/aws-sdk-go/service/ecr/doc.go, vendor/github.com/aws/aws-sdk-go/service/ecr/errors.go, vendor/github.com/aws/aws-sdk-go/service/route53/api.go, vendor/github.com/aws/aws-sdk-go/service/servicecatalog/api.go, vendor/github.com/aws/aws-sdk-go/service/ssm/api.go, vendor/github.com/aws/aws-sdk-go/service/sts/api.go, vendor/vendor.json
```
govendor fetch github.com/aws/aws-sdk-go/...@v1.13.8
```
=> deps: Bump aws-sdk-go@v1.13.8

website/docs/r/directory_service_directory.html.markdown
Would help any confusion with #76. Admittedly this resource is a little weird due to the backend API supporting parameters in various configurations.
=> docs/resource/directory_service_directory: Additional examples

aws/resource_aws_lambda_function.go
Also set resource ID before calling `PutFunctionConcurrency`. Closes #3563 
```
30 tests passed (all tests)
=== RUN   TestAccAWSLambdaFunction_expectFilenameAndS3Attributes
--- PASS: TestAccAWSLambdaFunction_expectFilenameAndS3Attributes (60.13s)
=== RUN   TestAccAWSLambdaFunction_importLocalFile_VPC
--- PASS: TestAccAWSLambdaFunction_importLocalFile_VPC (60.71s)
=== RUN   TestAccAWSLambdaFunction_s3
--- PASS: TestAccAWSLambdaFunction_s3 (61.47s)
=== RUN   TestAccAWSLambdaFunction_importS3
--- PASS: TestAccAWSLambdaFunction_importS3 (80.50s)
=== RUN   TestAccAWSLambdaFunction_DeadLetterConfigUpdated
--- PASS: TestAccAWSLambdaFunction_DeadLetterConfigUpdated (81.52s)
=== RUN   TestAccAWSLambdaFunction_runtimeValidation_noRuntime
--- PASS: …
```
=> resource/aws_lambda_function: Allow PutFunctionConcurrency retries on creation

aws/resource_aws_cloudfront_distribution_test.go
♻️ 
```
$ aws cloudfront list-distributions | jq '.DistributionList.Items | length'
28
$ make sweep SWEEPARGS='-sweep-run=aws_cloudfront_distribution'
go test ./... -v -sweep=us-east-1,us-west-2 -sweep-run=aws_cloudfront_distribution
?   	github.com/terraform-providers/terraform-provider-aws	[no test files]
2018/03/01 11:50:54 [DEBUG] Running Sweepers for region (us-east-1):
...
2018/03/01 11:52:13 Sweeper Tests ran:
- aws_cloudfront_distribution
2018/03/01 11:52:13 [DEBUG] Running Sweepers for region (us-west-2):
...
2018/03/01 11:52:14 [DEBUG] No CloudFront Distributions to sweep
2018/03/01 11:52:14 Sweeper Tests ran:
- aws_cloudfront_distribution
ok  	github.com/terraform-providers/terraform-provider-aws/aws …
```
=> tests/resource/aws_cloudfront_distribution: Add sweeper

website/docs/r/lb.html.markdown
I think the first `will` in this sentence does not need.
=> Fix mistake in grammar

aws/resource_aws_ebs_snapshot.go, aws/resource_aws_ebs_snapshot_test.go
Fix #3460 
Also enhance error checking in case of any other error.
=> resource/ebs_snapshot: fix crash in case of manual deletion

website/docs/r/db_instance.html.markdown
Not directly but might help with this: https://github.com/terraform-providers/terraform-provider-aws/issues/518
=> docs/aws_db_instance: Add doc notes regarding cross-region replication of encrypted RDS instances

aws/resource_aws_cloud9_environment_ec2.go
To address the following test failure:
```
=== RUN   TestAccAWSCloud9EnvironmentEc2_allFields
--- FAIL: TestAccAWSCloud9EnvironmentEc2_allFields (308.07s)
* aws_cloud9_environment_ec2.test: 1 error(s) occurred:
* aws_cloud9_environment_ec2.test: NotFoundException: User arn:aws:iam::*******:user/tf_acc_cloud9_env_7kfkcqqz does not exist.
status code: 400, request id: 3a531ada-2138-11e8-9203-1925f346b668
```
```
=== RUN   TestAccAWSCloud9EnvironmentEc2_importBasic
--- PASS: TestAccAWSCloud9EnvironmentEc2_importBasic (147.96s)
=== RUN   TestAccAWSCloud9EnvironmentEc2_basic
--- PASS: TestAccAWSCloud9EnvironmentEc2_basic (163.00s)
=== RUN   TestAccAWSCloud9EnvironmentEc2_allFields
--- PASS: …
```
=> resource/aws_cloud9_environment_ec2: Retry creation for IAM eventual consistency

aws/resource_aws_dynamodb_table.go, aws/resource_aws_dynamodb_table_test.go, aws/validators.go
=> resource/dynamodb_table: drop custom ValidateFunc for stream_view_type

vendor/github.com/aws/aws-sdk-go/aws/endpoints/defaults.go, vendor/github.com/aws/aws-sdk-go/aws/version.go, vendor/github.com/aws/aws-sdk-go/service/ecs/api.go, vendor/github.com/aws/aws-sdk-go/service/ecs/errors.go, vendor/github.com/aws/aws-sdk-go/service/medialive/api.go, vendor/github.com/aws/aws-sdk-go/service/rds/api.go, vendor/vendor.json
Closes #3691 
`govendor fetch github.com/aws/aws-sdk-go/...@v1.13.11`
=> deps: Bump aws-sdk-go@v1.13.11

website/docs/r/rds_cluster.html.markdown, website/docs/r/rds_cluster_instance.html.markdown
This issue https://github.com/terraform-providers/terraform-provider-aws/issues/1412 has been addressed, however the document is not updated.
=> adding the valid values for RDS engine parameter

aws/resource_aws_network_interface.go, aws/resource_aws_network_interface_attachment.go
=> Dettached should be spelled detached

aws/resource_aws_sqs_queue.go
This is a reimplementation of #3376 that future-proofs the resource as well as supports the `ListQueueTags` API call being missing from other non-standard AWS implementations (e.g. localstack).
Closes #3727
Passes same way as before in us-gov-west-1 (resource does not just error out, eventual consistency hasn't been fixed yet):
```
make testacc TEST=./aws TESTARGS='-run=TestAccAWSSQSQueue_basic'
TF_ACC=1 go test ./aws -v -run=TestAccAWSSQSQueue_basic -timeout 120m
=== RUN   TestAccAWSSQSQueue_basic
--- FAIL: TestAccAWSSQSQueue_basic (29.54s)
testing.go:513: Step 1 error: After applying this step, the plan was not empty:
DIFF:
UPDATE: aws_sqs_queue.queue
delay_seconds:              "0" => "90"
max_message_size:           "262144" …
```
=> resource/aws_sqs_queue: Remove explicit IsGovCloud() check

aws/resource_aws_api_gateway_rest_api_test.go
♻️ 
```
$ aws apigateway get-rest-apis | jq '.items | length'
59
$ make sweep SWEEPARGS='-sweep-run=aws_api_gateway_rest_api -timeout=60m'
...
2018/03/16 11:35:19 Sweeper Tests ran:
- aws_api_gateway_rest_api
ok  	github.com/terraform-providers/terraform-provider-aws/aws	1063.607s
$ aws apigateway get-rest-apis | jq '.items | length'
4
```
=> tests/resource/aws_api_gateway_rest_api: Add sweeper

aws/provider.go, aws/resource_aws_wafregional_rule.go, aws/resource_aws_wafregional_web_acl.go, aws/resource_aws_wafregional_web_acl_test.go, website/aws.erb, website/docs/r/wafregional_web_acl.html.markdown
Trying to help a bit to finish the WAF Regional PRs, this is the result of the split up of #3199
Related PRs: #1046 hashicorp/terraform#13711
Thanks to the contributors: @yusukegoto @DennyLoko @BSick7
=> New Resource: aws_wafregional_web_acl

aws/resource_aws_acm_certificate.go
=> Retry acm certificate delete when in use exception.

website/docs/r/db_instance.html.markdown
=> docs/resource/aws_db_instance: Document engine_version DiffSuppressFunc support

website/docs/r/waf_rule.html.markdown
I'll pull this into `stable-website` after merge.
=> docs/resource/aws_waf_rule: Fix broken links

vendor/github.com/aws/aws-sdk-go/aws/version.go, vendor/github.com/aws/aws-sdk-go/service/dynamodb/api.go, vendor/github.com/aws/aws-sdk-go/service/dynamodb/errors.go, vendor/vendor.json
`govendor fetch github.com/aws/aws-sdk-go/...@v1.13.21`
* Adds support for DynamoDB PITR (#3927)
=> deps: Bump aws-sdk-go@v1.13.21

aws/provider.go, aws/resource_aws_waf_rule_group.go, aws/resource_aws_waf_rule_group_test.go, aws/waf_helpers.go, website/aws.erb, website/docs/r/waf_rule_group.html.markdown
```
make testacc TEST=./aws TESTARGS='-run=TestAccAWSWafRuleGroup_'
TF_ACC=1 go test ./aws -v -run=TestAccAWSWafRuleGroup_ -timeout 120m
=== RUN   TestAccAWSWafRuleGroup_basic
--- PASS: TestAccAWSWafRuleGroup_basic (36.98s)
=== RUN   TestAccAWSWafRuleGroup_changeNameForceNew
--- PASS: TestAccAWSWafRuleGroup_changeNameForceNew (63.07s)
=== RUN   TestAccAWSWafRuleGroup_disappears
--- PASS: TestAccAWSWafRuleGroup_disappears (34.66s)
=== RUN   TestAccAWSWafRuleGroup_changeActivatedRules
--- PASS: TestAccAWSWafRuleGroup_changeActivatedRules (67.41s)
=== RUN   TestAccAWSWafRuleGroup_noActivatedRules
--- PASS: TestAccAWSWafRuleGroup_noActivatedRules (26.29s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	228.450s
```
=> New Resource: aws_waf_rule_group

aws/provider.go, aws/resource_aws_wafregional_rule_group.go, aws/resource_aws_wafregional_rule_group_test.go, website/aws.erb, website/docs/r/wafregional_rule_group.html.markdown
```
TF_ACC=1 go test ./aws -v -run=TestAccAWSWafRegionalRuleGroup_ -timeout 120m
=== RUN   TestAccAWSWafRegionalRuleGroup_basic
--- PASS: TestAccAWSWafRegionalRuleGroup_basic (57.77s)
=== RUN   TestAccAWSWafRegionalRuleGroup_changeNameForceNew
--- PASS: TestAccAWSWafRegionalRuleGroup_changeNameForceNew (99.76s)
=== RUN   TestAccAWSWafRegionalRuleGroup_disappears
--- PASS: TestAccAWSWafRegionalRuleGroup_disappears (50.13s)
=== RUN   TestAccAWSWafRegionalRuleGroup_changeActivatedRules
--- PASS: TestAccAWSWafRegionalRuleGroup_changeActivatedRules (102.85s)
=== RUN   TestAccAWSWafRegionalRuleGroup_noActivatedRules
--- PASS: TestAccAWSWafRegionalRuleGroup_noActivatedRules (38.91s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	349.468s
```
=> New Resource: aws_wafregional_rule_group

aws/provider.go, aws/resource_aws_waf_regex_match_set.go, aws/resource_aws_waf_regex_match_set_test.go, aws/waf_helpers.go, website/aws.erb, website/docs/r/waf_regex_match_set.html.markdown
```
TF_ACC=1 go test ./aws -v -run=TestAccAWSWafRegexMatchSet_ -timeout 120m
=== RUN   TestAccAWSWafRegexMatchSet_basic
--- PASS: TestAccAWSWafRegexMatchSet_basic (46.22s)
=== RUN   TestAccAWSWafRegexMatchSet_changePatterns
--- PASS: TestAccAWSWafRegexMatchSet_changePatterns (73.11s)
=== RUN   TestAccAWSWafRegexMatchSet_noPatterns
--- PASS: TestAccAWSWafRegexMatchSet_noPatterns (32.71s)
=== RUN   TestAccAWSWafRegexMatchSet_disappears
--- PASS: TestAccAWSWafRegexMatchSet_disappears (42.55s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	194.634s
```
=> New Resource: aws_waf_regex_match_set

website/docs/r/wafregional_web_acl.html.markdown
"predicate", "ip_set_descriptor" and "rule" are singular, not plural.
=> Fixing typo

website/docs/r/waf_regex_match_set.html.markdown, website/docs/r/waf_rule_group.html.markdown, website/docs/r/wafregional_regex_match_set.html.markdown, website/docs/r/wafregional_rule_group.html.markdown
Will push into `stable-website` after merge.
=> docs: Fix broken WAF links

website/docs/r/wafregional_geo_match_set.html.markdown
=> docs: Fix formatting of wafregional_geo_match_set

website/docs/r/appautoscaling_target.html.markdown
=> docs/resource/aws_appautoscaling_target: Link to aws_appautoscaling_policy resource

aws/config.go
Followup PR to the vendoring in #4048
=> provider: Support acmpca, fms, and secretsmanager connections

aws/provider.go, aws/resource_aws_directory_service_conditional_forwarder.go, aws/resource_aws_directory_service_conditional_forwarder_test.go, website/aws.erb, website/docs/r/directory_service_conditional_forwarder.html.markdown
Test result
```
TF_ACC=1 go test -v -run=TestACCAwsDirectoryServiceConditionForwarder_* -timeout 120m
=== RUN   TestACCAwsDirectoryServiceConditionForwarder_basic
--- PASS: TestACCAwsDirectoryServiceConditionForwarder_basic (1739.65s)
PASS
ok      github.com/terraform-providers/terraform-provider-aws/aws   1739.686s
```
=> New resource: aws_directory_service_conditional_forwarder

website/docs/r/appautoscaling_policy.html.markdown, website/docs/r/appautoscaling_target.html.markdown
It took some time for me to figure this out, so I figured I'd help improve the documentation. Let me know what you think!
Fixes https://github.com/terraform-providers/terraform-provider-aws/issues/2576
=> Add documentation examples for Aurora Read Replica Autoscaling

aws/data_source_aws_iam_server_certificate.go, aws/data_source_aws_iam_server_certificate_test.go, aws/resource_aws_iam_server_certificate_test.go, website/docs/d/iam_server_certificate.html.markdown
Not sure how to test this, but the code is pretty straightforward.
=> Optionally filter server certificates by path prefix.

.travis.yml, GNUmakefile
~Depends on https://github.com/terraform-providers/terraform-provider-aws/pull/4122 and https://github.com/hashicorp/terraform-website/pull/235~
=> make: Add website-test (link checker)

aws/resource_aws_codebuild_project.go
Replicates the retry for CreateProject
Split off from #3929
=> CodeBuild retry UpdateProject for IAM eventual consistency

aws/resource_aws_codebuild_project.go
* https://github.com/terraform-providers/terraform-provider-aws/issues/4261
=> (Fix) Mark auth.resource as `Sensitive`

aws/resource_aws_api_gateway_stage.go, aws/resource_aws_api_gateway_stage_test.go, aws/tags_apigateway.go, website/docs/r/api_gateway_stage.html.markdown
=> r/api_gateway_stage: Support tags

website/docs/r/api_gateway_method.html.markdown
=> docs/resource/api_gateway_method: add example with cognito user pool authorizer

aws/provider.go, aws/resource_aws_organizations_policy.go, aws/resource_aws_organizations_policy_test.go, website/aws.erb, website/docs/r/organizations_policy.html.markdown
Reference: #571 
```
make testacc TEST=./aws TESTARGS='-run=TestAccAwsOrganizationsPolicy'
TF_ACC=1 go test ./aws -v -run=TestAccAwsOrganizationsPolicy -timeout 120m
=== RUN   TestAccAwsOrganizationsPolicy_basic
--- PASS: TestAccAwsOrganizationsPolicy_basic (20.05s)
=== RUN   TestAccAwsOrganizationsPolicy_description
--- PASS: TestAccAwsOrganizationsPolicy_description (19.12s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	39.211s
```
=> New Resource: aws_organizations_policy

aws/resource_aws_api_gateway_stage.go, aws/resource_aws_api_gateway_stage_test.go, website/docs/r/api_gateway_stage.html.markdown
=> aws_api_gateway_stage outputs invoke_url and execution_arn

aws/data_source_aws_redshift_cluster.go, aws/data_source_aws_redshift_cluster_test.go, aws/provider.go, website/aws.erb, website/docs/d/redshift_cluster.html.markdown
```bash
TF_ACC=1 go test ./aws -v -run=TestAccAWSDataSourceRedshiftCluster -timeout 120m                                        
=== RUN   TestAccAWSDataSourceRedshiftCluster_basic
--- PASS: TestAccAWSDataSourceRedshiftCluster_basic (911.35s)
=== RUN   TestAccAWSDataSourceRedshiftCluster_vpc
--- PASS: TestAccAWSDataSourceRedshiftCluster_vpc (1121.35s)
=== RUN   TestAccAWSDataSourceRedshiftCluster_logging
--- PASS: TestAccAWSDataSourceRedshiftCluster_logging (779.21s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	2811.937s
```
=> New Data Source: aws_redshift_cluster

website/docs/r/ecs_service.html.markdown
Closes #335
Closes #752
Closes #1028
=> docs/resource/aws_ecs_service: Add lifecycle ignore_changes example

website/docs/r/cognito_user_group.html.markdown, website/docs/r/cognito_user_pool.markdown, website/docs/r/cognito_user_pool_client.markdown, website/docs/r/cognito_user_pool_domain.markdown, website/docs/r/s3_bucket_metric.html.markdown, website/docs/r/s3_bucket_notification.html.markdown
removed underscore from the tag in some yaml sections
=> fix sidebar_current yaml tag

website/docs/r/flow_log.html.markdown, website/docs/r/iam_group_policy_attachment.markdown, website/docs/r/iam_policy.html.markdown, website/docs/r/iam_policy_attachment.html.markdown, website/docs/r/iam_role_policy_attachment.markdown, website/docs/r/iam_user_policy_attachment.markdown, website/docs/r/iot_policy.html.markdown
: added missing example headers
=> Added missing '## Example Usage' headers

aws/resource_aws_rds_cluster_instance.go
Found during acceptance testing:
```
--- FAIL: TestAccAWSRDSClusterInstance_withInstanceEnhancedMonitor (148.81s)
testing.go:518: Step 0 error: Error applying: 1 error(s) occurred:
* aws_rds_cluster_instance.cluster_instances: 1 error(s) occurred:
* aws_rds_cluster_instance.cluster_instances: InvalidParameterValue: IAM role ARN value is invalid or does not include the required permissions for: ENHANCED_MONITORING
```
Tests
```
9 tests passed (all tests)
=== RUN   TestAccAWSRDSClusterInstance_generatedName
--- PASS: TestAccAWSRDSClusterInstance_generatedName (637.65s)
=== RUN   TestAccAWSRDSClusterInstance_namePrefix
--- PASS: TestAccAWSRDSClusterInstance_namePrefix (668.34s)
=== RUN   TestAccAWSRDSClusterInstance_withInstanceEnhancedMonitor
--- PASS: …
```
=> resource/aws_rds_cluster_instance: Add retries for IAM eventual consistency

aws/data_source_aws_mq_broker.go, aws/data_source_aws_mq_broker_test.go, aws/provider.go, aws/resource_aws_mq_broker.go, aws/structure.go, website/aws.erb, website/docs/d/mq_broker.html.markdown
=> New Data Source: aws_mq_broker

website/docs/r/appautoscaling_policy.html.markdown
=> fix docs for appautoscaling_policy policy_type

website/docs/r/organizations_account.html.markdown
Document ARN, and correct typo in importing instructions.
=> make corrections to aws_organizations_account documentation

aws/data_source_aws_autoscaling_groups.go
=> Paginate auto-scaling groups.

aws/data_source_aws_autoscaling_groups_test.go
=> Allow autoscaling group tests to run in multiple regions.

.github/ISSUE_TEMPLATE.md, .github/ISSUE_TEMPLATE/Bug_Report.md, .github/ISSUE_TEMPLATE/Feature_Request.md, .github/ISSUE_TEMPLATE/Question.md, .github/PULL_REQUEST_TEMPLATE.md
GitHub now supports split templates for issues 🎉 
https://help.github.com/articles/about-issue-and-pull-request-templates/
=> GitHub: New Issue and Pull Request Templates

vendor/github.com/aws/aws-sdk-go/aws/endpoints/defaults.go, vendor/github.com/aws/aws-sdk-go/aws/version.go, vendor/github.com/aws/aws-sdk-go/service/appsync/api.go, vendor/github.com/aws/aws-sdk-go/service/appsync/errors.go, vendor/github.com/aws/aws-sdk-go/service/configservice/api.go, vendor/github.com/aws/aws-sdk-go/service/guardduty/api.go, vendor/github.com/aws/aws-sdk-go/service/secretsmanager/api.go, vendor/vendor.json
`govendor fetch github.com/aws/aws-sdk-go/...@v1.13.42`
=> Deps: Bump aws-sdk-go@v1.13.42

website/docs/r/ecs_service.html.markdown
Fixes #4474 
* Fix reference in documentation
=> docs/resource/aws_ecs_service: Clarify ordered_placement_strategy maximum

website/docs/r/dynamodb_table.html.markdown
update document for resource "aws_dynamodb_table"
Detail discussion in #728
=> #728 - update document for resource "aws_dynamodb_table"

aws/resource_aws_lightsail_static_ip_test.go
* Add test sweeper for `aws_lightsail_static_ip` resource
Previously:
```
=== RUN   TestAccAWSLightsailStaticIp_disappears
--- FAIL: TestAccAWSLightsailStaticIp_disappears (4.04s)
testing.go:518: Step 0 error: Error applying: 1 error(s) occurred:
* aws_lightsail_static_ip.test: 1 error(s) occurred:
* aws_lightsail_static_ip.test: InvalidInputException: Sorry, you have reached the maximum number of static IPs for your account.
status code: 400, request id: 5fc0edc8-5a76-11e8-a6f8-d772f57f805e
```
```
$ aws --region us-east-1 lightsail get-static-ips | jq '.staticIps | length'
2
$ make sweep SWEEPARGS='-sweep-run=aws_lightsail_static_ip'
go test …
```
=> tests/resource/aws_lightsail_static_ip: Add sweeper

aws/resource_aws_cloudwatch_event_permission_test.go
* Add test sweeper for `aws_cloudwatch_event_permission` resource to prevent currently failing acceptance testing
```
=== RUN   TestAccAWSCloudWatchEventPermission_Action
--- FAIL: TestAccAWSCloudWatchEventPermission_Action (8.06s)
testing.go:518: Step 4 error: Error applying: 1 error(s) occurred:
* aws_cloudwatch_event_permission.test1: 1 error(s) occurred:
* aws_cloudwatch_event_permission.test1: Creating CloudWatch Events permission failed: PolicyLengthExceededException: Policy size would be larger than the maximum allowed.
status code: 400, request id: 3222ff89-5a5e-11e8-af85-cbe3b31b4224
```
```
$ aws events describe-event-bus | jq '.Policy | length'
9952
$ make sweep …
```
=> tests/resource/aws_cloudwatch_event_permission: Add sweeper

vendor/github.com/aws/aws-sdk-go/aws/version.go, vendor/github.com/aws/aws-sdk-go/service/codebuild/api.go, vendor/github.com/aws/aws-sdk-go/service/codedeploy/api.go, vendor/github.com/aws/aws-sdk-go/service/cognitoidentityprovider/api.go, vendor/github.com/aws/aws-sdk-go/service/configservice/api.go, vendor/github.com/aws/aws-sdk-go/service/ec2/api.go, vendor/github.com/aws/aws-sdk-go/service/organizations/api.go, vendor/github.com/aws/aws-sdk-go/service/organizations/doc.go, vendor/github.com/aws/aws-sdk-go/service/organizations/errors.go, vendor/github.com/aws/aws-sdk-go/service/secretsmanager/api.go, vendor/github.com/aws/aws-sdk-go/service/servicecatalog/api.go, vendor/vendor.json
* `govendor fetch github.com/aws/aws-sdk-go/...@v1.13.51`
Output from acceptance testing: N/A will be handled with daily acceptance testing
=> Deps: Bump aws-sdk-go@v1.13.51

aws/resource_aws_s3_bucket.go
[Fixes #4598]
Note: it looks like many api requests in this provider use type assertions without checking error values or that the assertion is ok. I'm happy to expand the patch to address more issues, but thought I would start with the reported issue to begin with.
=> Return unexpected errors on cors read.

aws/resource_aws_api_gateway_rest_api.go
Fixes #4397
This is required to unescape non-quote characters, e.g. forward slashes
in CIDR blocks, which the AWS API escapes in its JSON responses.
~Acceptance test results to follow.~
=> Normalize REST API Policy JSON before unquoting

aws/resource_aws_cloudwatch_event_rule.go
Fixes #4547 
* Only perform name_prefix/generated name logic once on creation
Create -> Update -> Read strikes again! Similar as observed in the issue, the daily acceptance testing has been leaving dangling rules:
```
$ aws events list-rules | jq '.Rules[] | .Name'
"tf-acc-cw-event-rule-prefix-20180426162323934100000002"
"tf-acc-cw-event-rule-prefix-20180426162514120400000002"
"tf-acc-cw-event-rule-prefix-20180427053026579200000002"
"tf-acc-cw-event-rule-prefix-20180428060328552200000002"
"tf-acc-cw-event-rule-prefix-20180429060519520300000002"
"tf-acc-cw-event-rule-prefix-20180501053203121800000002"
"tf-acc-cw-event-rule-prefix-20180502053210453100000002"
"tf-acc-cw-event-rule-prefix-20180503060601159900000002" …
```
=> resource/aws_cloudwatch_event_rule: Prevent multiple names on creation

aws/resource_aws_lambda_function.go
As written, the lambda function data source always returns the most
recent version and qualified arn, even if a different qualifier is set.
This patch respects the qualifier if provided.
=> Respect lambda function qualifier on data source.

vendor/github.com/aws/aws-sdk-go/aws/request/request_pagination.go, vendor/github.com/aws/aws-sdk-go/aws/version.go, vendor/github.com/aws/aws-sdk-go/service/cloudwatchlogs/api.go, vendor/github.com/aws/aws-sdk-go/service/codebuild/api.go, vendor/github.com/aws/aws-sdk-go/service/elbv2/api.go, vendor/github.com/aws/aws-sdk-go/service/rds/api.go, vendor/github.com/aws/aws-sdk-go/service/secretsmanager/api.go, vendor/vendor.json
* `govendor fetch github.com/aws/aws-sdk-go/...@v1.13.55`
=> Deps: Bump aws-sdk-go@v1.13.55

vendor/github.com/aws/aws-sdk-go/aws/endpoints/defaults.go, vendor/github.com/aws/aws-sdk-go/aws/version.go, vendor/github.com/aws/aws-sdk-go/private/protocol/rest/build.go, vendor/github.com/aws/aws-sdk-go/private/protocol/rest/unmarshal.go, vendor/github.com/aws/aws-sdk-go/service/configservice/api.go, vendor/github.com/aws/aws-sdk-go/service/configservice/errors.go, vendor/github.com/aws/aws-sdk-go/service/glue/api.go, vendor/github.com/aws/aws-sdk-go/service/iot/api.go, vendor/vendor.json
* `govendor fetch github.com/aws/aws-sdk-go/...@v1.13.57`
=> Deps: Bump aws-sdk-go@v1.13.57

aws/resource_aws_lb_target_group_test.go, aws/resource_aws_lb_test.go, aws/resource_aws_subnet_test.go
Consistently causing issues with sweeping VPCs.
* Add test sweeper for `aws_lb` and `aws_lb_target_group`
* Make `aws_subnet` sweeper dependent on `aws_lb`
```
$ make sweep SWEEPARGS='-sweep-run=aws_lb_target_group'
go test ./... -v -sweep=us-east-1,us-west-2 -sweep-run=aws_lb_target_group
...
2018/05/28 21:40:21 [INFO] Deleting LB Target Group: testaccawslb-basic-ffapbscv8j
2018/05/28 21:40:21 [INFO] Deleting LB Target Group: testaccawslb-basic-n1oxsvqaoc
2018/05/28 21:40:22 [INFO] Deleting LB Target Group: testtargetgroup-1zamk78apf
2018/05/28 21:40:22 [INFO] Deleting LB Target Group: testtargetgroup-2stcfl6sfd
2018/05/28 21:40:22 [INFO] …
```
=> tests/resource/aws_lb*: Add sweepers

aws/data_source_aws_lambda_function_test.go, aws/resource_aws_lambda_function.go, aws/resource_aws_lambda_function_test.go
* Introspect partition in acceptance tests
* Handle missing tracing config feature in govcloud
cc @bflad
=> Update lambda tests to run in govcloud.

website/docs/r/eip.html.markdown, website/docs/r/eip_association.html.markdown
Fixes #3572
* Document cases where AWS should manage EIP associations
=> docs/resource/aws_eip*: Note that AWS must manage EIP associations with LBs and NAT Gateways

aws/data_source_aws_ecs_service.go, aws/data_source_aws_ecs_service_test.go, aws/provider.go, website/docs/d/ecs_service.html.markdown
Closes https://github.com/terraform-providers/terraform-provider-aws/issues/1681
=> New Data Source: ECS Service

website/docs/d/db_snapshot.html.markdown
=> Fix copy-paste mistake in db_snapshot attributes

website/docs/r/cloudtrail.html.markdown
=> docs/r/cloudtrail: Fix typo: witch -> which

website/docs/r/rds_cluster.html.markdown
This documents that it is possible to tag tags `aws_rds_cluster` resources. I also fixed minor punctuation. I do not like double spacing either, it is a sin that should not be practiced.
=> r/aws_rds_cluster: Document tags

vendor/github.com/aws/aws-sdk-go/aws/version.go, vendor/github.com/aws/aws-sdk-go/service/rds/api.go, vendor/github.com/aws/aws-sdk-go/service/secretsmanager/api.go, vendor/vendor.json
* `govendor fetch github.com/aws/aws-sdk-go/...@v1.14.1`
=> Deps: Bump aws-sdk-go@v1.14.1

website/docs/r/api_gateway_method.html.markdown
Fixes documentation of API Gateway Method
=> Fix documentaion on API Gateway method introduced by #4533

aws/resource_aws_lambda_permission.go
Hi team,
Fixes spelling mistake: cosistent -> consistent
Regards Oscar
=> Fix spelling

vendor/github.com/aws/aws-sdk-go/aws/version.go, vendor/github.com/aws/aws-sdk-go/service/apigateway/api.go, vendor/github.com/aws/aws-sdk-go/service/dynamodb/api.go, vendor/github.com/aws/aws-sdk-go/service/dynamodb/errors.go, vendor/github.com/aws/aws-sdk-go/service/ssm/api.go, vendor/github.com/aws/aws-sdk-go/service/ssm/doc.go, vendor/github.com/aws/aws-sdk-go/service/ssm/errors.go, vendor/vendor.json
* `govendor fetch github.com/aws/aws-sdk-go/...@v1.14.7`
=> Deps: Bump aws-sdk-go@v1.14.7

vendor/github.com/aws/aws-sdk-go/aws/version.go, vendor/github.com/aws/aws-sdk-go/service/mediaconvert/api.go, vendor/vendor.json
* `govendor fetch github.com/aws/aws-sdk-go/...@v1.14.8`
=> Deps: Bump aws-sdk-go@v1.14.8

website/docs/events/gardening-summer-2018.html.md
* Gitter room is `hashicorp-terraform/gardening`
=> events/gardening-summer-2018: Add Gitter room name

website/docs/events/gardening-summer-2018.html.md
Add a clickable link to make it easier to find/join.
=> docs/events/gardening: Add link to Gitter room

website/docs/d/elasticache_cluster.html.markdown, website/docs/r/route53_record.html.markdown, website/docs/r/subnet.html.markdown
Fixes #2660
Fixes #3386
Fixes #2678
=> Small updates in documentation

website/docs/r/iam_group_membership.html.markdown
If two or more aws_iam_group_membership resources have the same group name, then terraform will oscillate between the two (or more) sets of users with repeated `terraform apply` commands.
This behavior makes sense, given that we can only read all of the users from a group in the api, and not users divided between arbitrary iam_group_membership terraform resources.
However, it is still problematic because each apply changes the users in the group.
Given the complicated edge cases, there are only two solutions I can think of:
1. Error early if more than one aws_iam_group_membership has the same group name
2. Warn users about this behavior in the documentation
I'm unaware if solution 1 is feasible, so I've opted for solution 2.
---
Example terraform code:
```
variable "user-set-1" { default …
```
=> Add warning to aws_iam_group_membership docs

aws/resource_aws_launch_template.go
Fixes #4857 
* Change 1:
By default, if we didn't mention the `valid_until` option in config then the default end date is 7 days from the current date.
But I was getting the below error if I didn't mention the `valid_until` option.
* aws_launch_template.foo: Error Parsing Launch Template Spot Options valid until: parsing time "" as "2006-01-02T15:04:05Z07:00": cannot parse "" as "2006"
Implemented the value validation before referencing the value.
* Change 2:
If I mention the `valid_until` to some valid value `2020-11-04T20:44:20.000Z`, then I was getting the below error(state)
* aws_launch_template.foo: instance_market_options.0.spot_options.0.valid_until: '' expected type 'string', got unconvertible type 'time.Time'
Formatting the value before …
=> issue #4857 Can't use spot instances with aws_launch_template

website/docs/r/acm_certificate.html.markdown
I ran code from [this comment](https://github.com/terraform-providers/terraform-provider-aws/issues/4537#issuecomment-393502015) and verified that added lifecycle resolved the problem.
Fixes #4537 and #4712.
=> Added lifecycle note to aws_acm_certificate resource

aws/provider.go, aws/resource_aws_media_store_container_policy.go, aws/resource_aws_media_store_container_policy_test.go, website/aws.erb, website/docs/r/media_store_container_policy.html.markdown
```
TF_ACC=1 go test ./aws -v -run=TestAccAWSMediaStoreContainerPolicy_* -timeout 120m
=== RUN   TestAccAWSMediaStoreContainerPolicy_basic
--- PASS: TestAccAWSMediaStoreContainerPolicy_basic (175.87s)
=== RUN   TestAccAWSMediaStoreContainerPolicy_import
--- PASS: TestAccAWSMediaStoreContainerPolicy_import (101.83s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	277.734s
```
=> New Resource: aws_media_store_container_policy

aws/resource_aws_config_configuration_recorder_test.go, aws/resource_aws_config_delivery_channel_test.go
This is to isolate test failures and prevent them, e.g.
```
--- FAIL: TestAccAWSConfig/ConfigurationRecorder (344.96s)
--- FAIL: TestAccAWSConfig/ConfigurationRecorder/basic (23.23s)
testing.go:503: Step 0 error: Error applying: 1 error(s) occurred:
* aws_config_delivery_channel.foo: 1 error(s) occurred:
* aws_config_delivery_channel.foo: Creating Delivery Channel failed: MaxNumberOfDeliveryChannelsExceededException: Failed to put delivery channel 'tf-acc-test-awsconfig-6379587365361428533' because the maximum number of delivery channels: 1 is reached.
status code: 400, request id: 4b0bfe9d-df0f-11e7-aa42-c989f54ca168
```
=> test/aws_config_*: Add sweepers

aws/data_source_aws_subnet_ids.go, aws/data_source_aws_subnet_ids_test.go
* Add filtering to subnet ids data source
```
make testacc TEST=./aws TESTARGS='-run=TestAccDataSourceAwsSubnetIDs'
TF_ACC=1 go test ./aws -v -run=TestAccDataSourceAwsSubnetIDs -timeout 120m
=== RUN   TestAccDataSourceAwsSubnetIDs
--- PASS: TestAccDataSourceAwsSubnetIDs (37.54s)
=== RUN   TestAccDataSourceAwsSubnetIDs_filter
--- PASS: TestAccDataSourceAwsSubnetIDs_filter (26.28s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	63.861s
```
=> d/aws_subnet_ids: Add filtering

website/docs/d/pricing_product.html.markdown
Noticed that the doc for aws_pricing_product data_source looks pretty bad. Some minor adjustments.
=> Minor pricing_product doc adjustments

website/docs/d/cloudformation_export.html.markdown, website/docs/d/ecs_service.html.markdown, website/docs/d/launch_configuration.html.markdown, website/docs/r/dx_gateway.html.markdown, website/docs/r/dx_hosted_private_virtual_interface.html.markdown, website/docs/r/dx_hosted_private_virtual_interface_accepter.html.markdown, website/docs/r/dx_hosted_public_virtual_interface.html.markdown, website/docs/r/dx_hosted_public_virtual_interface_accepter.html.markdown, website/docs/r/dx_private_virtual_interface.html.markdown, website/docs/r/dx_public_virtual_interface.html.markdown, website/docs/r/neptune_parameter_group.html.markdown, website/docs/r/vpc_ipv4_cidr_block_association.html.markdown
Reference (among others): #5163 
* On the tin, matches consistency with rest of project
=> docs: Adjust older attributes bylines to "In addition to all argument s above, the following attributes are exported:"

website/docs/r/glue_crawler.html.markdown
=> [GLUE] Add missing quote to Glue example

aws/provider.go, aws/resource_aws_neptune_cluster.go, aws/resource_aws_neptune_cluster_test.go, aws/tagsNeptune.go, aws/validators.go, website/aws.erb, website/docs/r/neptune_cluster.html.markdown
~~Fixes #4713~~
Reference: #4713 
```
$ make testacc TEST=./aws/ TESTARGS='-run=TestAccAWSNeptuneCluster'
TF_ACC=1 go test ./aws/ -v -run=TestAccAWSNeptuneCluster -timeout 120m
=== RUN   TestAccAWSNeptuneClusterParameterGroup_basic
--- PASS: TestAccAWSNeptuneClusterParameterGroup_basic (55.86s)
=== RUN   TestAccAWSNeptuneClusterParameterGroup_namePrefix
--- PASS: TestAccAWSNeptuneClusterParameterGroup_namePrefix (54.48s)
=== RUN   TestAccAWSNeptuneClusterParameterGroup_generatedName
--- PASS: TestAccAWSNeptuneClusterParameterGroup_generatedName (55.00s)
=== RUN   TestAccAWSNeptuneClusterParameterGroup_Description
--- PASS: TestAccAWSNeptuneClusterParameterGroup_Description (55.70s)
=== RUN …
```
=> issue #4713 New Resource: aws_neptune_cluster

website/docs/r/iam_policy.html.markdown
Fixes #5270
* Modify documentation
Not executed for this change
```
...
```
=> Change the description of iam_policy resource, force new resource

aws/resource_aws_kinesis_firehose_delivery_stream.go
Fixes #5145 
* Change 1
Add `ForceNew ` to source configuration child attributes to take effect.
=> issue #5145 aws_kinesis_firehose_delivery_stream not updating on kinesis_source_configuration change

aws/resource_aws_dax_cluster.go
* Use API provided ARN instead of manually created one
```
3 tests passed (all tests)
=== RUN   TestAccAWSDAXCluster_basic
--- PASS: TestAccAWSDAXCluster_basic (583.03s)
=== RUN   TestAccAWSDAXCluster_importBasic
--- PASS: TestAccAWSDAXCluster_importBasic (603.20s)
=== RUN   TestAccAWSDAXCluster_resize
--- PASS: TestAccAWSDAXCluster_resize (1183.52s)
```
=> resource/aws_dax_cluster: Use API provided ARN instead of manually created one

aws/resource_aws_codebuild_project.go
Found via daily acceptance testing:
```
=== RUN   TestAccAWSCodeBuildProject_VpcConfig
--- FAIL: TestAccAWSCodeBuildProject_VpcConfig (15.89s)
testing.go:518: Step 0 error: Error applying: 1 error(s) occurred:
* aws_codebuild_project.test: 1 error(s) occurred:
* aws_codebuild_project.test: [ERROR] Error updating CodeBuild project (arn:aws:codebuild:us-west-2:*******:project/tf-acc-test-6715853446408871432): InvalidInputException: Not authorized to perform DescribeSecurityGroups
```
* Retry `InvalidInputException: Not authorized to perform DescribeSecurityGroups` during update for IAM eventual consistency
* Call read after create instead of update
```
20 tests passed (all tests)
=== RUN …
```
=> resource/aws_codebuild_project: Handle additional IAM retry case during update, remove update after create

website/docs/r/ecr_lifecycle_policy.html.markdown
Adds a note to docs on how to avoid #5233 
* Added note based on suggestion by @bflad 
None, only changed documentation
=> Add note warning to sort the rules based on rulePriority

aws/provider.go, aws/resource_aws_neptune_cluster_instance.go, aws/resource_aws_neptune_cluster_instance_test.go, website/aws.erb, website/docs/r/neptune_cluster_instance.html.markdown
Reference #4713 
* Change 1
Added new resource aws_neptune_cluster_instance
=> New resource: aws_neptune_cluster_instance

website/docs/d/db_instance.html.markdown, website/docs/r/db_instance.html.markdown
=> docs/aws_db_instance: Clarify address and endpoint attributes

aws/resource_aws_elasticsearch_domain.go, website/docs/r/elasticsearch_domain.html.markdown
=> Add "ES_APPLICATION_LOGS" log_type for aws_elasticsearch_domain

vendor/github.com/aws/aws-sdk-go/aws/version.go, vendor/github.com/aws/aws-sdk-go/service/cloudwatchlogs/api.go, vendor/github.com/aws/aws-sdk-go/service/cloudwatchlogs/errors.go, vendor/github.com/aws/aws-sdk-go/service/codebuild/api.go, vendor/github.com/aws/aws-sdk-go/service/dynamodb/api.go, vendor/github.com/aws/aws-sdk-go/service/ec2/api.go, vendor/github.com/aws/aws-sdk-go/service/pinpoint/api.go, vendor/github.com/aws/aws-sdk-go/service/secretsmanager/api.go, vendor/github.com/aws/aws-sdk-go/service/ssm/api.go, vendor/vendor.json
* Updated via: `govendor fetch github.com/aws/aws-sdk-go/...@v1.15.8`
=> vendor: aws/aws-sdk-go@v1.15.8

aws/resource_aws_cognito_user_pool.go, aws/resource_aws_cognito_user_pool_test.go
closed: #3389 
```
TF_ACC=1 go test ./aws -v -run=TestAccAWSCognitoUserPool_update -timeout 120m
=== RUN   TestAccAWSCognitoUserPool_update
--- PASS: TestAccAWSCognitoUserPool_update (107.53s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	107.564s
```
=> resource/cognito_user_pool: Modify update params

vendor/github.com/aws/aws-sdk-go/aws/endpoints/defaults.go, vendor/github.com/aws/aws-sdk-go/aws/version.go, vendor/github.com/aws/aws-sdk-go/service/devicefarm/api.go, vendor/github.com/aws/aws-sdk-go/service/ec2/api.go, vendor/github.com/aws/aws-sdk-go/service/mediaconvert/api.go, vendor/github.com/aws/aws-sdk-go/service/redshift/api.go, vendor/github.com/aws/aws-sdk-go/service/ssm/api.go, vendor/github.com/aws/aws-sdk-go/service/ssm/errors.go, vendor/vendor.json
Notably includes:
* redshift: ResizeCluster
* `govendor fetch github.com/aws/aws-sdk-go/...@v1.15.14`
=> vendor: aws/aws-sdk-go@v1.15.14

website/docs/r/rds_cluster.html.markdown
=> docs/resource/aws_rds_cluster: Clarify usage for Aurora only and guidance towards other RDS resources

website/docs/r/storagegateway_nfs_file_share.html.markdown
Fixes #0000
* Change 1
* Change 2
```
...
```
=> Typo in Example Usage

vendor/github.com/aws/aws-sdk-go/aws/endpoints/defaults.go, vendor/github.com/aws/aws-sdk-go/aws/version.go, vendor/github.com/aws/aws-sdk-go/service/codebuild/api.go, vendor/github.com/aws/aws-sdk-go/service/eks/api.go, vendor/github.com/aws/aws-sdk-go/service/eks/doc.go, vendor/github.com/aws/aws-sdk-go/service/eks/errors.go, vendor/github.com/aws/aws-sdk-go/service/iot/api.go, vendor/github.com/aws/aws-sdk-go/service/mediapackage/api.go, vendor/github.com/aws/aws-sdk-go/service/redshift/api.go, vendor/github.com/aws/aws-sdk-go/service/sagemaker/api.go, vendor/github.com/aws/aws-sdk-go/service/waf/api.go, vendor/github.com/aws/aws-sdk-go/service/waf/errors.go, vendor/github.com/aws/aws-sdk-go/service/wafregional/api.go, vendor/github.com/aws/aws-sdk-go/service/wafregional/errors.go, vendor/vendor.json
Notable changes since v1.15.21:
* CodeBuild Project multiple artifacts/sources
* EKS Cluster platform version
* WAF (Regional) logging configuration
* Updated via `govendor fetch github.com/aws/aws-sdk-go/...@v1.15.26`
=> vendor: aws/aws-sdk-go@v1.15.26

website/docs/r/instance.html.markdown
* Add example of credit specification block syntax
Documentation change, not testable.
=> Add example of credit specification block syntax

vendor/github.com/mitchellh/copystructure/go.mod, vendor/github.com/mitchellh/copystructure/go.sum, vendor/github.com/mitchellh/reflectwalk/go.mod, vendor/vendor.json
Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/5773
* Updated via:
```
govendor fetch github.com/mitchellh/copystructure/...@v1.0.0
govendor fetch github.com/mitchellh/reflectwalk/...@v1.0.0
```
Output from acceptance testing: No-op change 😄
=> vendor: Pin mitchellh/copystructure@v1.0.0 and mitchellh/reflectwalk@v1.0.0

vendor/vendor.json
Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/5773
* Updated via: `govendor fetch github.com/ulikunitz/xz/...@v0.5.4`
Output from acceptance testing: No-op change 😄
=> vendor: Pin ulikunitz/xz@v0.5.4

aws/resource_aws_lambda_function.go
Refer #5791 
* Change 1
Fixes the panic runtime error `index out of range` in `vpc_config` attribute
=> Fix panic runtime error - aws_lambda_function

aws/data_source_aws_eks_cluster.go, aws/data_source_aws_eks_cluster_test.go, aws/resource_aws_eks_cluster.go, aws/resource_aws_eks_cluster_test.go, website/docs/d/eks_cluster.html.markdown, website/docs/r/eks_cluster.html.markdown
Fixes https://github.com/terraform-providers/terraform-provider-aws/issues/5796.
Acceptance tests:
```console
=== RUN   TestAccAWSEksClusterDataSource_basic
--- PASS: TestAccAWSEksClusterDataSource_basic (1171.79s)
=== RUN   TestAccAWSEksCluster_basic
--- PASS: TestAccAWSEksCluster_basic (1073.15s)
```
=> r/aws_eks_cluster, d/aws_eks_cluster: Add support for EKS Platform Version

aws/resource_aws_vpn_gateway_test.go
The Direct Connect Gateway testing can be flakey with VPN Gateway associations, which then cause the following issues during the TeamCity CI pre-sweeper step:
```
[06:15:31][Step 2/4] 2018/09/10 06:15:31 [ERR] error running (aws_vpn_gateway): Error deleting VPN Gateway (vgw-0ab6d375ee407dddc): IncorrectState: The VPN gateway is in use.
[06:15:31][Step 2/4] 	status code: 400, request id: 1a6b988e-4297-4f80-a664-6dd103bd9dd4
[06:15:31][Step 2/4] FAIL	github.com/terraform-providers/terraform-provider-aws/aws	128.515s
[06:15:31][Step 2/4] Process exited with code 1
[06:15:31][Step 2/4] Process exited with code 1 (Step: Pre-Sweeper (Command Line))
[06:15:31][Step 2/4] Step Pre-Sweeper (Command Line) failed
```
* Call `DetachVpnGateway` for all associated …
=> tests/resource/aws_vpn_gateway: Ensure sweeper handles VPC detachment prior to deletion

website/docs/r/elasticsearch_domain.html.markdown, website/docs/r/elasticsearch_domain_policy.html.markdown
Fixes #5806 
* Update to aws_elasticsearch_domain website doc
* Update to aws_elasticsearch_domain_policy website doc
```
$ make website-test
==> Testing aws provider website in Docker...
Error response from daemon: No such container: tf-website-aws-temp
make[1]: [website-provider-test] Error 1 (ignored)
Unable to find image 'hashicorp/middleman-hashicorp:0.3.35' locally
0.3.35: Pulling from hashicorp/middleman-hashicorp
81033e7c1d6a: Already exists
a83827892197: Already exists
e6837157ff44: Pull complete
d339fbbb4ad6: Pull complete
cb68b82a17fd: Pull complete
45ddb7d2ce56: Pull complete
1cf13860aa9e: Pull complete
c2f2e55b12ed: Pull complete
1940b7744ad5: Pull complete
7915a19d792d: Pull complete
Digest: …
```
=> Updating elasticsearch resource website documentation. Fixes #5806

aws/resource_aws_vpc_test.go
e.g. When the test sweepers detach an attached VPN gateway, it can take a few seconds for the change to propagate in the EC2 system and can throw an error if you attempt to delete the VPC even with a short delay:
```
[12:38:25][Step 2/4] 2018/09/11 12:38:25 [DEBUG] [aws-sdk-go] DEBUG: Validate Response ec2/DeleteVpc failed, not retrying, error DependencyViolation: The vpc 'vpc-08d394d80c2367cee' has dependencies and cannot be deleted.
[12:38:25][Step 2/4] 	status code: 400, request id: 8a916294-07fc-4855-9617-f0c25e5c16e3
[12:38:25][Step 2/4] 2018/09/11 12:38:25 [ERR] error running (aws_vpc): Error deleting VPC (vpc-08d394d80c2367cee): DependencyViolation: The vpc 'vpc-08d394d80c2367cee' has dependencies and cannot be deleted.
[12:38:25][Step 2/4] 	status code: 400, request id: …
```
=> tests/resource/aws_vpc: Allow sweeper to handle EC2 eventual consistency

aws/resource_aws_security_group_test.go
EC2 regions may manually or automatically had their rules per group limit increased, which will cause the acceptance tests to fail expecting the limit errors at the wrong value. Unfortunately, there is no EC2 or Trusted Advisor API lookup for this particular limit so for now we will allow configuration via `EC2_SECURITY_GROUP_RULES_PER_GROUP_LIMIT` environment variable or it will default to 50.
Previously:
```
$ make testacc TEST=./aws TESTARGS='-run=TestAccAWSSecurityGroup_ruleLimit'
TF_ACC=1 go test ./aws -v -run=TestAccAWSSecurityGroup_ruleLimit -timeout 120m
=== RUN   TestAccAWSSecurityGroup_ruleLimitExceededAppend
--- FAIL: TestAccAWSSecurityGroup_ruleLimitExceededAppend (45.77s)
testing.go:508: Step 1, no error received, but …
```
=> tests/resource/aws_security_group: Allow security group rules per group limit to be configurable via environment variable

vendor/github.com/aws/aws-sdk-go/aws/version.go, vendor/github.com/aws/aws-sdk-go/service/cloudwatch/api.go, vendor/github.com/aws/aws-sdk-go/service/codebuild/api.go, vendor/github.com/aws/aws-sdk-go/service/ec2/api.go, vendor/github.com/aws/aws-sdk-go/service/ecs/api.go, vendor/github.com/aws/aws-sdk-go/service/elasticache/api.go, vendor/github.com/aws/aws-sdk-go/service/elasticache/errors.go, vendor/github.com/aws/aws-sdk-go/service/elasticsearchservice/api.go, vendor/github.com/aws/aws-sdk-go/service/elastictranscoder/api.go, vendor/github.com/aws/aws-sdk-go/service/fms/api.go, vendor/github.com/aws/aws-sdk-go/service/fms/errors.go, vendor/github.com/aws/aws-sdk-go/service/organizations/api.go, vendor/github.com/aws/aws-sdk-go/service/organizations/errors.go, vendor/github.com/aws/aws-sdk-go/service/s3/api.go, vendor/github.com/aws/aws-sdk-go/service/secretsmanager/api.go, vendor/github.com/aws/aws-sdk-go/service/ses/api.go, vendor/vendor.json
Updated via:
* `govendor fetch github.com/aws/aws-sdk-go/...@v1.15.38`
=> vendor: aws/aws-sdk-go@v1.15.38

website/docs/r/instance.html.markdown
Updating  https://www.terraform.io/docs/providers/aws/r/instance.html to match volume types on
https://www.terraform.io/docs/providers/aws/r/ebs_volume.html
=> Updating per #5923

website/docs/r/launch_configuration.html.markdown
Clarified by adding "The name attribute..." Fixes #5746
=> Update to iam_instance_profile

vendor/github.com/aws/aws-sdk-go/aws/credentials/endpointcreds/provider.go, vendor/github.com/aws/aws-sdk-go/aws/defaults/defaults.go, vendor/github.com/aws/aws-sdk-go/aws/ec2metadata/service.go, vendor/github.com/aws/aws-sdk-go/aws/version.go, vendor/github.com/aws/aws-sdk-go/service/directoryservice/api.go, vendor/github.com/aws/aws-sdk-go/service/ec2/api.go, vendor/github.com/aws/aws-sdk-go/service/mediaconvert/api.go, vendor/github.com/aws/aws-sdk-go/service/rds/api.go, vendor/github.com/aws/aws-sdk-go/service/rds/errors.go, vendor/vendor.json
Updated via:
* `govendor fetch github.com/aws/aws-sdk-go/...@v1.15.41`
=> vendor: aws/aws-sdk-go@v1.15.41

aws/resource_aws_elb_test.go, aws/resource_aws_load_balancer_policy.go, aws/resource_aws_load_balancer_policy_test.go
Fixes #5914 
Previously (after testing changes, but before code changes):
```
$ make testacc TEST=./aws TESTARGS='-run=TestAccAWSELB_disappears'
TF_ACC=1 go test ./aws -v -run=TestAccAWSELB_disappears -timeout 120m
=== RUN   TestAccAWSELB_disappears
--- PASS: TestAccAWSELB_disappears (17.12s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	19.324s
$ make testacc TEST=./aws TESTARGS='-run=TestAccAWSLoadBalancerPolicy_'
TF_ACC=1 go test ./aws -v -run=TestAccAWSLoadBalancerPolicy_ -timeout 120m
=== RUN   TestAccAWSLoadBalancerPolicy_basic
--- PASS: TestAccAWSLoadBalancerPolicy_basic (24.76s)
=== RUN   TestAccAWSLoadBalancerPolicy_disappears
--- FAIL: …
```
=> resource/aws_load_balancer_policy: Properly handle resource when ELB is deleted

vendor/github.com/aws/aws-sdk-go/aws/endpoints/defaults.go, vendor/github.com/aws/aws-sdk-go/aws/version.go, vendor/github.com/aws/aws-sdk-go/private/protocol/jsonrpc/jsonrpc.go, vendor/github.com/aws/aws-sdk-go/private/protocol/restjson/restjson.go, vendor/github.com/aws/aws-sdk-go/service/cloudfront/api.go, vendor/github.com/aws/aws-sdk-go/service/directoryservice/api.go, vendor/github.com/aws/aws-sdk-go/service/directoryservice/errors.go, vendor/github.com/aws/aws-sdk-go/service/ec2/api.go, vendor/github.com/aws/aws-sdk-go/service/glue/api.go, vendor/github.com/aws/aws-sdk-go/service/rds/api.go, vendor/github.com/aws/aws-sdk-go/service/sqs/api.go, vendor/github.com/aws/aws-sdk-go/service/sqs/doc.go, vendor/github.com/aws/aws-sdk-go/service/sqs/errors.go, vendor/vendor.json
Updated via: `govendor fetch github.com/aws/aws-sdk-go/...@v1.15.43`
Notable changes:
* Directory Service Shared Directory support
* EC2 `DescribeRouteTables` paginator
* RDS deletion protection support
=> vendor: aws/aws-sdk-go@v1.15.43

.travis.yml
=> tests/provider: Switch TravisCI to Go 1.11.1

website/docs/r/acm_certificate_validation.html.markdown
* Change terraform example whitespace to what terraform fmt would produce
=> Align resource example like terraform fmt would do

website/docs/d/cloudformation_export.html.markdown
Fixes #5872
* Minor documentation tweak.
=> data/aws_cloudformation_export: Clarify name documentation

aws/data_source_aws_launch_template.go, aws/data_source_aws_launch_template_test.go, aws/provider.go, website/aws.erb, website/docs/d/launch_template.html.markdown
Fixes #5272
* Ad new aws_launch_template datasource
```
coming soon...
...
```
=> datasource/launch_template: Add new datasource

website/docs/r/waf_web_acl.html.markdown
This is just fixing some minor issues in the documentation and adding missing parts about constraints which took me some time to figure out before getting it working in my setup.
* Fix `aws_waf_web_acl` `action` and `action_override` documentation
* Add more details for the constraints of `action` and `action_override`
=> Update aws_waf_web_acl action documentation

aws/resource_aws_codebuild_project.go, aws/resource_aws_codebuild_project_test.go
Fixes #6076 
* Support for `NO_SOURCE` as project source's type.
```
$ make testacc TESTARGS='-run=TestAccAWSCodeBuildProject_Source_Type_NoSource'
TF_ACC=1 go test ./... -v -run=TestAccAWSCodeBuildProject_Source_Type_NoSource -timeout 120m
?   	github.com/terraform-providers/terraform-provider-aws	[no test files]
=== RUN   TestAccAWSCodeBuildProject_Source_Type_NoSource
--- PASS: TestAccAWSCodeBuildProject_Source_Type_NoSource (47.43s)
=== RUN   TestAccAWSCodeBuildProject_Source_Type_NoSourceInvalid
--- PASS: TestAccAWSCodeBuildProject_Source_Type_NoSourceInvalid (31.68s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	79.153s
...
```
=> resource/aws_codebuild_project: Support `NO_SOURCE` as source's type

website/docs/r/vpc_peering.html.markdown, website/docs/r/vpc_peering_options.html.markdown
=> Add copy about inter-region VPC peering limitations

vendor/github.com/hashicorp/terraform/helper/resource/testing.go, vendor/github.com/hashicorp/terraform/helper/schema/resource_data.go, vendor/github.com/hashicorp/terraform/helper/schema/resource_diff.go, vendor/github.com/hashicorp/terraform/helper/schema/schema.go, vendor/github.com/hashicorp/terraform/terraform/test_failure, vendor/github.com/hashicorp/terraform/version/version.go, vendor/vendor.json
Updated via: `govendor fetch github.com/hashicorp/terraform/...@v0.11.9-beta1`
Notable changes:
* `resource.ParallelTest` for #5874 
=> vendor: hashicorp/terraform@v0.11.9-beta1

vendor/github.com/aws/aws-sdk-go/aws/defaults/defaults.go, vendor/github.com/aws/aws-sdk-go/aws/session/session.go, vendor/github.com/aws/aws-sdk-go/aws/session/shared_config.go, vendor/github.com/aws/aws-sdk-go/aws/version.go, vendor/github.com/aws/aws-sdk-go/internal/shareddefaults/ecs_container.go, vendor/github.com/aws/aws-sdk-go/service/cloudtrail/api.go, vendor/github.com/aws/aws-sdk-go/service/cloudtrail/errors.go, vendor/github.com/aws/aws-sdk-go/service/lambda/api.go, vendor/github.com/aws/aws-sdk-go/service/lambda/errors.go, vendor/github.com/aws/aws-sdk-go/service/rds/api.go, vendor/github.com/aws/aws-sdk-go/service/servicecatalog/api.go, vendor/vendor.json
Updated via: `govendor fetch github.com/aws/aws-sdk-go/...@v1.15.55`
Reference: #6163 
=> vendor: aws/aws-sdk-go@v1.15.55

website/docs/r/db_instance.html.markdown
Fixes #0000
* Change 1
* Change 2
```
...
```
=> backup_retention_period allowed range

README.md
=> readme: Add link to docs page of AWS provider

aws/data_source_aws_lambda_invocation.go, aws/resource_aws_api_gateway_rest_api.go, aws/resource_aws_cloudformation_stack.go, aws/resource_aws_cloudwatch_dashboard.go, aws/resource_aws_config_config_rule.go, aws/resource_aws_dms_replication_task.go, aws/resource_aws_ecr_lifecycle_policy.go, aws/resource_aws_elasticsearch_domain.go, aws/resource_aws_emr_cluster.go, aws/resource_aws_emr_security_configuration.go, aws/resource_aws_glacier_vault.go, aws/resource_aws_glue_crawler.go, aws/resource_aws_iam_role.go, aws/resource_aws_kinesis_firehose_delivery_stream.go, aws/resource_aws_kms_key.go, aws/resource_aws_organizations_policy.go, aws/resource_aws_s3_bucket.go, aws/resource_aws_s3_bucket_policy.go, aws/resource_aws_secretsmanager_secret.go, aws/resource_aws_service_discovery_service.go, aws/resource_aws_sns_topic.go, aws/resource_aws_sns_topic_policy.go, aws/resource_aws_sns_topic_subscription.go, aws/resource_aws_sqs_queue.go, aws/resource_aws_sqs_queue_policy.go, aws/validators.go, aws/validators_test.go
Fixes https://github.com/terraform-providers/terraform-provider-aws/issues/6147.
Similar to https://github.com/terraform-providers/terraform-provider-aws/pull/6156.
=> Refactor some validators

aws/resource_aws_network_acl_rule.go, aws/resource_aws_network_acl_rule_test.go
Reference https://github.com/terraform-providers/terraform-provider-aws/issues/222
~The following issue was already closed but it's only for one protocol.~
~Now the bug is not fixed in other protocols.~
~This code fix it.~
~issue: https://github.com/hashicorp/terraform/issues/13012~
~pr: https://github.com/hashicorp/terraform/pull/13049~
This is `"best effort" implementations of acceptance tests`.
I hope Terraform team check this pr.
Thanks.
=> resource/aws_network_acl_rule: Fix DiffSuppressFunc

website/docs/r/codebuild_project.html.markdown
Updates doc as https://github.com/terraform-providers/terraform-provider-aws/pull/6140 is released
=> Added NO_SOURCE as a possible value for source type

website/docs/r/ecs_service.html.markdown
Fixes #0000
* Change 1
* Change 2
```
...
```
=> Load balancer formatting

aws/resource_aws_iam_user_test.go, vendor/github.com/boombuler/barcode/LICENSE, vendor/github.com/boombuler/barcode/README.md, vendor/github.com/boombuler/barcode/barcode.go, vendor/github.com/boombuler/barcode/go.mod, vendor/github.com/boombuler/barcode/qr/alphanumeric.go, vendor/github.com/boombuler/barcode/qr/automatic.go, vendor/github.com/boombuler/barcode/qr/blocks.go, vendor/github.com/boombuler/barcode/qr/encoder.go, vendor/github.com/boombuler/barcode/qr/errorcorrection.go, vendor/github.com/boombuler/barcode/qr/numeric.go, vendor/github.com/boombuler/barcode/qr/qrcode.go, vendor/github.com/boombuler/barcode/qr/unicode.go, vendor/github.com/boombuler/barcode/qr/versioninfo.go, vendor/github.com/boombuler/barcode/scaledbarcode.go, vendor/github.com/boombuler/barcode/utils/base1dcode.go, vendor/github.com/boombuler/barcode/utils/bitlist.go, vendor/github.com/boombuler/barcode/utils/galoisfield.go, vendor/github.com/boombuler/barcode/utils/gfpoly.go, vendor/github.com/boombuler/barcode/utils/reedsolomon.go, vendor/github.com/boombuler/barcode/utils/runeint.go, vendor/github.com/pquerna/otp/LICENSE, vendor/github.com/pquerna/otp/NOTICE, vendor/github.com/pquerna/otp/README.md, vendor/github.com/pquerna/otp/doc.go, vendor/github.com/pquerna/otp/hotp/hotp.go, vendor/github.com/pquerna/otp/otp.go, vendor/github.com/pquerna/otp/totp/totp.go, vendor/vendor.json
Changes proposed:
* `govendor fetch github.com/pquerna/otp/totp`
* Implement MFA device code generation for acceptance testing
```
--- PASS: TestAccAWSUser_ForceDestroy_MFADevice (9.16s)
```
=> tests/resource/aws_iam_user: Enable TestAccAWSUser_ForceDestroy_MFADevice

aws/resource_aws_opsworks_application.go
Fixes #6306 
* Change 1
create new resource when update `short_name`
=> create new resource during short_name update in aws_opsworks_application

vendor/github.com/aws/aws-sdk-go/aws/endpoints/defaults.go, vendor/github.com/aws/aws-sdk-go/aws/version.go, vendor/github.com/aws/aws-sdk-go/internal/ini/ini_parser.go, vendor/github.com/aws/aws-sdk-go/service/batch/api.go, vendor/github.com/aws/aws-sdk-go/service/budgets/api.go, vendor/github.com/aws/aws-sdk-go/service/budgets/doc.go, vendor/github.com/aws/aws-sdk-go/service/cloudformation/api.go, vendor/github.com/aws/aws-sdk-go/service/codepipeline/api.go, vendor/github.com/aws/aws-sdk-go/service/firehose/api.go, vendor/github.com/aws/aws-sdk-go/service/mediapackage/api.go, vendor/github.com/aws/aws-sdk-go/service/rds/api.go, vendor/github.com/aws/aws-sdk-go/service/rds/errors.go, vendor/vendor.json
Updated via: `govendor fetch github.com/aws/aws-sdk-go/...@v1.15.74`
Not a small update, notable changes:
* INI parser fix for left-hand side tokenization issues
* Batch Launch Template support
* CloudFormation drift detection support
* Firehose SSE support
* RDS custom endpoint support
=> deps: aws/aws-sdk-go@v1.15.74

vendor/github.com/aws/aws-sdk-go/aws/endpoints/defaults.go, vendor/github.com/aws/aws-sdk-go/aws/version.go, vendor/github.com/aws/aws-sdk-go/service/autoscaling/api.go, vendor/github.com/aws/aws-sdk-go/service/autoscaling/doc.go, vendor/github.com/aws/aws-sdk-go/service/budgets/api.go, vendor/github.com/aws/aws-sdk-go/service/ec2/api.go, vendor/github.com/aws/aws-sdk-go/service/redshift/api.go, vendor/github.com/aws/aws-sdk-go/service/resourcegroups/api.go, vendor/github.com/aws/aws-sdk-go/service/sagemaker/api.go, vendor/github.com/aws/aws-sdk-go/service/servicecatalog/api.go, vendor/github.com/aws/aws-sdk-go/service/sns/api.go, vendor/github.com/aws/aws-sdk-go/service/sns/errors.go, vendor/vendor.json
Updated via: `govendor fetch github.com/aws/aws-sdk-go/...@v1.15.76`
=> deps: aws/aws-sdk-go@v1.15.76

website/docs/r/dlm_lifecycle_policy.markdown
This is just an update for example code in docs. Current code there doesn't work and created policy ends up in ERROR state.
=> aws_dlm_lifecycle_policy: improved example in docs

website/docs/r/budgets_budget.html.markdown
Fixes #6467
* Fixes the first example
=> Budgets budget docs: fix the first example

vendor/github.com/aws/aws-sdk-go/aws/crr/cache.go, vendor/github.com/aws/aws-sdk-go/aws/version.go, vendor/github.com/aws/aws-sdk-go/service/ec2/api.go, vendor/github.com/aws/aws-sdk-go/service/iot/api.go, vendor/github.com/aws/aws-sdk-go/service/kms/api.go, vendor/github.com/aws/aws-sdk-go/service/kms/doc.go, vendor/github.com/aws/aws-sdk-go/service/kms/errors.go, vendor/github.com/aws/aws-sdk-go/service/s3/api.go, vendor/vendor.json
Updated via: `govendor fetch github.com/aws/aws-sdk-go/...@v1.15.83`
=> deps: aws/aws-sdk-go@v1.15.83

vendor/github.com/aws/aws-sdk-go/aws/request/retryer.go, vendor/github.com/aws/aws-sdk-go/aws/version.go, vendor/github.com/aws/aws-sdk-go/service/cloudwatchlogs/api.go, vendor/github.com/aws/aws-sdk-go/service/cloudwatchlogs/errors.go, vendor/github.com/aws/aws-sdk-go/service/codedeploy/api.go, vendor/github.com/aws/aws-sdk-go/service/codedeploy/errors.go, vendor/github.com/aws/aws-sdk-go/service/ec2/api.go, vendor/github.com/aws/aws-sdk-go/service/ecs/api.go, vendor/github.com/aws/aws-sdk-go/service/ecs/errors.go, vendor/github.com/aws/aws-sdk-go/service/kinesisanalytics/api.go, vendor/github.com/aws/aws-sdk-go/service/kinesisanalytics/errors.go, vendor/vendor.json
Updated via: `govendor fetch github.com/aws/aws-sdk-go/...@v1.15.84`
=> deps: aws/aws-sdk-go@v1.15.84

vendor/github.com/aws/aws-sdk-go/aws/version.go, vendor/github.com/aws/aws-sdk-go/service/dynamodb/api.go, vendor/github.com/aws/aws-sdk-go/service/dynamodb/errors.go, vendor/github.com/aws/aws-sdk-go/service/rds/api.go, vendor/github.com/aws/aws-sdk-go/service/rds/errors.go, vendor/vendor.json
Updated via: govendor fetch github.com/aws/aws-sdk-go/...@v1.15.85
=> deps: aws/aws-sdk-go@v1.15.85

website/aws.erb
The data sources were slightly unsorted.
=> Sort the data sources

website/docs/r/lambda_function.html.markdown
=> Lambda-Docs: Add logging policy example

aws/resource_aws_s3_bucket.go, aws/resource_aws_s3_bucket_test.go, website/docs/r/s3_bucket.html.markdown
Fixes https://github.com/terraform-providers/terraform-provider-aws/issues/6611.
Related:
* https://github.com/terraform-providers/terraform-provider-aws/pull/6589
Acceptance tests:
```console
$ make testacc TEST=./aws/ TESTARGS='-run=TestAccAWSS3Bucket_Replication'
TF_ACC=1 go test ./aws/ -v -parallel 20 -run=TestAccAWSS3Bucket_Replication -timeout 120m
=== RUN   TestAccAWSS3Bucket_Replication
=== PAUSE TestAccAWSS3Bucket_Replication
=== RUN   TestAccAWSS3Bucket_ReplicationConfiguration_Rule_Destination_AccessControlTranslation
=== PAUSE TestAccAWSS3Bucket_ReplicationConfiguration_Rule_Destination_AccessControlTranslation
=== RUN   TestAccAWSS3Bucket_ReplicationWithoutStorageClass
=== PAUSE …
```
=> Support S3 S3 Cross-Region Replication to Glacier

vendor/github.com/aws/aws-sdk-go/aws/endpoints/defaults.go, vendor/github.com/aws/aws-sdk-go/aws/version.go, vendor/github.com/aws/aws-sdk-go/service/devicefarm/api.go, vendor/github.com/aws/aws-sdk-go/service/mediaconvert/api.go, vendor/github.com/aws/aws-sdk-go/service/servicecatalog/api.go, vendor/github.com/aws/aws-sdk-go/service/storagegateway/api.go, vendor/vendor.json
Updated via: govendor fetch github.com/aws/aws-sdk-go/...@v1.15.89
=> deps: aws/aws-sdk-go@v1.15.89

vendor/github.com/aws/aws-sdk-go/aws/version.go, vendor/github.com/aws/aws-sdk-go/service/s3/api.go, vendor/vendor.json
Updated via: govendor fetch github.com/aws/aws-sdk-go/...@v1.15.90
=> deps: aws/aws-sdk-go@v1.15.90

aws/resource_aws_cloudwatch_log_subscription_filter.go, aws/resource_aws_cloudwatch_log_subscription_filter_test.go
=> Fix log group and filter deletion race condition

website/docs/r/codebuild_project.html.markdown
=> docs/resource/aws_codebuild_project: Cross-link aws_codebuild_webhook resource

aws/resource_aws_ec2_transit_gateway_route.go
Another pull request in the series to reduce flakey/failing tests before our next major version development.
Presumably the EC2 API previously omitted the route when deleted and now uses the deleted/deleting route states. This also fixes the error codes to ignore during deletion as seen below.
Previous output from acceptance testing:
```
--- FAIL: TestAccAWSEc2TransitGatewayRoute_disappears (136.87s)
testing.go:538: Step 0 error: Expected a non-empty plan, but got an empty plan!
testing.go:599: Error destroying resource! WARNING: Dangling resources
Error: Error applying: 1 error occurred:
* aws_ec2_transit_gateway_route.test (destroy): 1 error occurred:
* aws_ec2_transit_gateway_route.test: error deleting EC2 Transit Gateway Route: …
```
=> resource/aws_ec2_transit_gateway_route: Trigger resource recreation with deleted/deleting route state

vendor/github.com/aws/aws-sdk-go/aws/version.go, vendor/github.com/aws/aws-sdk-go/service/eks/api.go, vendor/github.com/aws/aws-sdk-go/service/eks/errors.go, vendor/github.com/aws/aws-sdk-go/service/glue/api.go, vendor/github.com/aws/aws-sdk-go/service/route53/api.go, vendor/github.com/aws/aws-sdk-go/service/sagemaker/api.go, vendor/vendor.json
Updated via: govendor fetch github.com/aws/aws-sdk-go/...@v1.16.4
=> deps: aws/aws-sdk-go@v1.16.4

aws/data_source_aws_cloudtrail_service_account.go, aws/data_source_aws_elb_hosted_zone_id.go, aws/data_source_aws_elb_service_account.go, aws/hosted_zones.go
=> add support for eu-north-1 region

aws/resource_aws_cognito_identity_pool_roles_attachment_test.go, aws/resource_aws_cognito_identity_pool_test.go, aws/resource_aws_cognito_user_group_test.go, aws/resource_aws_cognito_user_pool_client_test.go, aws/resource_aws_cognito_user_pool_domain_test.go, aws/resource_aws_cognito_user_pool_test.go
=> Fix gosimple cognito issues

vendor/github.com/aws/aws-sdk-go/aws/endpoints/defaults.go, vendor/github.com/aws/aws-sdk-go/aws/version.go, vendor/github.com/aws/aws-sdk-go/service/organizations/api.go, vendor/vendor.json
`govendor fetch github.com/aws/aws-sdk-go/...@v1.16.5`
=> deps: aws/aws-sdk-go@v1.16.5

aws/resource_aws_iam_group_membership.go, aws/resource_aws_iam_group_policy_attachment.go, aws/resource_aws_iam_instance_profile.go, aws/resource_aws_iam_openid_connect_provider_test.go, aws/resource_aws_iam_policy.go, aws/resource_aws_iam_policy_attachment.go, aws/resource_aws_iam_role.go, aws/resource_aws_iam_role_policy_attachment.go, aws/resource_aws_iam_saml_provider_test.go, aws/resource_aws_iam_server_certificate.go, aws/resource_aws_iam_user_group_membership.go, aws/resource_aws_iam_user_login_profile.go, aws/resource_aws_iam_user_policy_attachment.go, aws/resource_aws_iam_user_policy_test.go, aws/resource_aws_internet_gateway.go
=> Fix gosimple iam issues

aws/autoscaling_tags.go, aws/s3_tags.go, aws/tags.go, aws/tagsBeanstalk.go, aws/tagsCloudtrail.go, aws/tagsDAX.go, aws/tagsDS.go, aws/tagsDX.go, aws/tagsEC.go, aws/tagsECS.go, aws/tagsEFS.go, aws/tagsELB.go, aws/tagsGeneric.go, aws/tagsIAM.go, aws/tagsInspector.go, aws/tagsKMS.go, aws/tagsKinesisFirehose.go, aws/tagsNeptune.go, aws/tagsRDS.go, aws/tagsRedshift.go, aws/tagsSSM.go, aws/tagsSecretsManager.go, aws/tags_elasticsearchservice.go, aws/tags_kinesis.go, aws/tags_route53.go
=> Fix gosimple tags issues

aws/import_aws_s3_bucket.go, aws/resource_aws_s3_bucket_inventory.go, aws/resource_aws_s3_bucket_notification_test.go, aws/resource_aws_s3_bucket_object_test.go, aws/resource_aws_s3_bucket_test.go
=> Fix gosimple s3 issues

aws/resource_aws_acmpca_certificate_authority.go, aws/resource_aws_acmpca_certificate_authority_test.go
=> Fix gosimple acmpca issues

aws/resource_aws_ami_launch_permission_test.go
=> Fix gosimple ami issues

aws/resource_aws_app_cookie_stickiness_policy_test.go, aws/resource_aws_appautoscaling_policy.go, aws/resource_aws_appmesh_route.go, aws/resource_aws_appmesh_virtual_node.go, aws/resource_aws_appmesh_virtual_router.go, aws/resource_aws_appsync_graphql_api_test.go
=> Fix gosimple app issues

vendor/github.com/aws/aws-sdk-go/aws/version.go, vendor/github.com/aws/aws-sdk-go/service/ec2/api.go, vendor/github.com/aws/aws-sdk-go/service/elasticbeanstalk/api.go, vendor/vendor.json
Updated via: govendor fetch github.com/aws/aws-sdk-go/...@v1.16.8
=> deps: aws/aws-sdk-go@v1.16.8

aws/resource_aws_api_gateway_documentation_part.go, aws/resource_aws_api_gateway_method_response_test.go, aws/resource_aws_api_gateway_method_test.go, aws/resource_aws_api_gateway_stage.go, aws/resource_aws_api_gateway_vpc_link.go, aws/resource_aws_api_gateway_vpc_link_test.go
=> Fix gosimple api issues

aws/resource_aws_athena_database_test.go, aws/resource_aws_athena_named_query.go, aws/resource_aws_athena_named_query_test.go
=> Fix gosimple athena issues

aws/resource_aws_autoscaling_group.go, aws/resource_aws_autoscaling_group_waiting.go, aws/resource_aws_autoscaling_notification.go, aws/resource_aws_autoscaling_schedule_test.go
Fix gosimple autoscaling issues
=> Fix gosimple autoscaling issues

aws/resource_aws_cloudwatch_event_permission_test.go, aws/resource_aws_cloudwatch_log_group_test.go, aws/resource_aws_cloudwatch_log_stream_test.go, aws/resource_aws_cloudwatch_log_subscription_filter_test.go
Fix gosimple cloudwatch issues
=> Fix cloudwatch issues

aws/resource_aws_cloudwatch_event_permission_test.go, aws/resource_aws_cloudwatch_log_group_test.go, aws/resource_aws_cloudwatch_log_stream_test.go, aws/resource_aws_cloudwatch_log_subscription_filter_test.go, aws/resource_aws_db_instance.go, aws/resource_aws_db_snapshot.go
=> Fix gosimple db issues

aws/resource_aws_dms_certificate.go, aws/resource_aws_dms_replication_subnet_group.go, aws/resource_aws_dms_replication_task.go
=> Fix gosimple dms issues

aws/resource_aws_dx_connection.go, aws/resource_aws_dx_hosted_private_virtual_interface_accepter.go, aws/resource_aws_dx_hosted_public_virtual_interface_accepter.go, aws/resource_aws_dx_lag.go, aws/resource_aws_dx_private_virtual_interface.go, aws/resource_aws_dx_public_virtual_interface.go
=> Fix gosimple dx issues

aws/resource_aws_codebuild_project.go, aws/resource_aws_codecommit_trigger.go, aws/resource_aws_codedeploy_deployment_config.go, aws/resource_aws_codedeploy_deployment_group.go, aws/resource_aws_codepipeline.go, aws/resource_aws_codepipeline_test.go, aws/resource_aws_codepipeline_webhook.go, aws/resource_aws_codepipeline_webhook_test.go
Fix gosimple code issues (codedeployment, codepipeline)
=> Fix gosimple code issues

aws/resource_aws_cloudwatch_event_permission_test.go, aws/resource_aws_cloudwatch_log_group_test.go, aws/resource_aws_cloudwatch_log_stream_test.go, aws/resource_aws_cloudwatch_log_subscription_filter_test.go, aws/resource_aws_elastic_beanstalk_application_version.go, aws/resource_aws_elastic_transcoder_pipeline.go, aws/resource_aws_elastic_transcoder_pipeline_test.go, aws/resource_aws_elasticache_cluster.go, aws/resource_aws_elasticache_replication_group_test.go, aws/resource_aws_elasticsearch_domain.go, aws/resource_aws_elasticsearch_domain_policy.go
=> Fix gosimple elastic issues

aws/provider.go, aws/resource_aws_s3_bucket_public_access_block.go, aws/resource_aws_s3_bucket_public_access_block_test.go, website/aws.erb, website/docs/r/s3_bucket_public_access_block.html.markdown
fixes #6489
- add new s3_bucket_public_access_block_resource and tests
```
...
```
TODO:
=> r/s3: add public access block resource

aws/resource_aws_dynamodb_global_table.go
=> Fix gosimple dynamodb issues

website/docs/r/ami.html.markdown, website/docs/r/ami_copy.html.markdown, website/docs/r/ami_from_instance.html.markdown, website/docs/r/appmesh_virtual_node.html.markdown, website/docs/r/cloudhsm_v2_cluster.html.markdown, website/docs/r/load_balancer_backend_server_policy.html.markdown, website/docs/r/load_balancer_listener_policy.html.markdown, website/docs/r/load_balancer_policy.html.markdown, website/docs/r/redshift_snapshot_copy_grant.html.markdown, website/docs/r/spot_fleet_request.html.markdown, website/docs/r/spot_instance_request.html.markdown, website/docs/r/transfer_user.html.markdown
Fixes #0000
Small documentation fixes:
* added `tag` attribute reference to resources which support them, but were missing
* resource titles which were mis-titled
=> Documentation Update

website/docs/r/transfer_user.html.markdown
=> Fix title for Transfer User

website/docs/r/network_interface.markdown
=> Missing id attribute from network_interface

aws/resource_aws_db_instance_test.go
When omitted, the backup and maintenance windows for RDS Database Instances are randomly generated by the API. When restoring from snapshot or creating a replication database, the parameter setting occurs in a followup ModifyDBInstance call after the initial creation calls because the creation calls do not support the parameters directly. Injecting an expected value for one but not both of the parameters meant the testing could randomly fail with errors similar to the below during that ModifyDBInstance call:
```
--- FAIL: TestAccAWSDBInstance_SnapshotIdentifier_BackupWindow (1136.04s)
testing.go:538: Step 0 error: Error applying: 1 error occurred:
* aws_db_instance.test: 1 error occurred:
* aws_db_instance.test: error modifying DB Instance (tf-acc-test-418376986433548694): …
```
=> tests/resource/aws_db_instance: Prevent overlap errors with backup_window and maintenance_window in acceptance testing

vendor/github.com/aws/aws-sdk-go/aws/client/client.go, vendor/github.com/aws/aws-sdk-go/aws/credentials/credentials.go, vendor/github.com/aws/aws-sdk-go/aws/ec2metadata/api.go, vendor/github.com/aws/aws-sdk-go/aws/ec2metadata/service.go, vendor/github.com/aws/aws-sdk-go/aws/endpoints/defaults.go, vendor/github.com/aws/aws-sdk-go/aws/endpoints/endpoints.go, vendor/github.com/aws/aws-sdk-go/aws/request/request.go, vendor/github.com/aws/aws-sdk-go/aws/session/doc.go, vendor/github.com/aws/aws-sdk-go/aws/session/env_config.go, vendor/github.com/aws/aws-sdk-go/aws/signer/v4/v4.go, vendor/github.com/aws/aws-sdk-go/aws/version.go, vendor/github.com/aws/aws-sdk-go/internal/ini/ini_parser.go, vendor/github.com/aws/aws-sdk-go/internal/ini/statement.go, vendor/github.com/aws/aws-sdk-go/internal/shareddefaults/ecs_container.go, vendor/github.com/aws/aws-sdk-go/service/devicefarm/api.go, vendor/github.com/aws/aws-sdk-go/service/ecs/api.go, vendor/github.com/aws/aws-sdk-go/service/s3/api.go, vendor/vendor.json
Updated via govendor fetch github.com/aws/aws-sdk-go/...@v1.16.14
=> deps: aws/aws-sdk-go@v1.16.14

aws/resource_aws_dynamodb_table.go
Fixes #6919
Previous output from acceptance testing (AWS GovCloud (US), all aws_dynamodb_table tests):
```
--- FAIL: TestAccAWSDynamoDbTable_basic (0.39s)
testing.go:538: Step 0 error: Error applying: 1 error occurred:
* aws_dynamodb_table.basic-dynamodb-table: 1 error occurred:
* aws_dynamodb_table.basic-dynamodb-table: ValidationException: One or more parameter values were invalid: Unsupported input parameter BillingMode
```
Output from acceptance testing (AWS GovCloud (US), no new failures from pre-BillingMode):
```
--- PASS: TestAccAWSDynamoDbTable_streamSpecificationValidation (3.64s)
--- PASS: TestAccAWSDynamoDbTable_attributeUpdateValidation (5.13s)
--- FAIL: TestAccAWSDynamoDbTable_encryption (5.43s)
testing.go:538: Step 0 error: Error applying: 1 error occurred:
* …
```
=> resource/aws_dynamodb_table: Fix table creation in GovCloud (US) and China due to missing BillingMode support

aws/resource_aws_ebs_volume_test.go
💸 
Output from test sweeper:
```
$ aws ec2 describe-volumes | jq '.Volumes | length'
176
$ go test ./aws -v -sweep=us-west-2 -sweep-run=aws_ebs_volume -timeout 10h
...
2019/01/09 22:03:58 [INFO] Deleting EC2 EBS Volume: vol-03f00bd46faa7de3e
2019/01/09 22:03:58 [INFO] Deleting EC2 EBS Volume: vol-01f56b518592a9da5
2019/01/09 22:03:59 Sweeper Tests ran:
- aws_instance
- aws_ebs_volume
ok    github.com/terraform-providers/terraform-provider-aws/aws 107.042s
$ aws ec2 describe-volumes | jq '.Volumes | length'
13
```
=> tests/resource/aws_ebs_volume: Add test sweeper

aws/resource_aws_ec2_fleet.go
=> Fix gosimple ec2 issues

aws/resource_aws_eip_association_test.go, aws/resource_aws_eip_test.go
=> fix gosimple eip issues

aws/resource_aws_ebs_snapshot_copy_test.go, aws/resource_aws_ebs_snapshot_test.go
=> Fix gosimple ebs issues

aws/resource_aws_emr_cluster.go, aws/resource_aws_emr_instance_group.go
=> Fix gosimple emr issues

aws/resource_aws_ses_configuration_set.go, aws/resource_aws_ses_domain_dkim_test.go, aws/resource_aws_ses_domain_identity_test.go, aws/resource_aws_ses_event_destination.go, aws/resource_aws_ses_receipt_rule.go, aws/resource_aws_ses_receipt_rule_set.go, aws/resource_aws_ses_receipt_rule_set_test.go, aws/resource_aws_ses_template_test.go
=> Fix gosimpel ses issues

aws/resource_aws_service_discovery_http_namespace_test.go, aws/resource_aws_service_discovery_private_dns_namespace.go, aws/resource_aws_service_discovery_public_dns_namespace.go, aws/resource_aws_service_discovery_public_dns_namespace_test.go, aws/resource_aws_service_discovery_service.go, aws/resource_aws_service_discovery_service_test.go, aws/resource_aws_servicecatalog_portfolio_test.go
=> Fix gosimple service issues

aws/resource_aws_glacier_vault.go, aws/resource_aws_glue_crawler.go, aws/resource_aws_guardduty_ipset_test.go, aws/resource_aws_guardduty_threatintelset_test.go, aws/resource_aws_instance.go, aws/resource_aws_kinesis_firehose_delivery_stream.go, aws/resource_aws_kinesis_stream.go, aws/resource_aws_lambda_function_test.go, aws/resource_aws_launch_configuration.go, aws/resource_aws_mq_broker.go, aws/resource_aws_pinpoint_app.go, aws/resource_aws_security_group.go, aws/resource_aws_security_group_rules_matching_test.go, aws/resource_aws_spot_fleet_request.go, aws/resource_aws_spot_fleet_request_test.go, aws/resource_aws_sqs_queue.go, aws/tagsTransfer.go
Fix gosimple issues include: 
- Glacier                        - Glue
- Guardduty                  - Instance
- Kinesis                        - Lambda
- Pintpoint                    - Security
- Spot                           - sqs
- TagsTransfer
=> Fix various minor gosimple issues

aws/resource_aws_ecs_service.go
=> Fix gosimple ecs issues

aws/resource_aws_gamelift_alias.go, aws/resource_aws_gamelift_build.go, aws/resource_aws_gamelift_fleet.go
=> Fix gosimple gamelift issues

aws/resource_aws_elb.go
=> Fix gosimple elb issues

vendor/github.com/aws/aws-sdk-go/aws/endpoints/defaults.go, vendor/github.com/aws/aws-sdk-go/aws/version.go, vendor/github.com/aws/aws-sdk-go/service/codedeploy/api.go, vendor/github.com/aws/aws-sdk-go/service/codedeploy/doc.go, vendor/github.com/aws/aws-sdk-go/service/codedeploy/errors.go, vendor/github.com/aws/aws-sdk-go/service/ec2/api.go, vendor/github.com/aws/aws-sdk-go/service/emr/api.go, vendor/github.com/aws/aws-sdk-go/service/iot/api.go, vendor/github.com/aws/aws-sdk-go/service/sagemaker/api.go, vendor/vendor.json
Updated via govendor fetch github.com/aws/aws-sdk-go/...@v1.16.18
=> deps: aws/aws-sdk-go@v1.16.18

.github/ISSUE_TEMPLATE/Feature_Request.md, .github/ISSUE_TEMPLATE/Question.md
This will (hopefully) save us some triaging time. 😉
=> Add labels to issue templates

vendor/github.com/aws/aws-sdk-go/aws/endpoints/decode.go, vendor/github.com/aws/aws-sdk-go/aws/endpoints/defaults.go, vendor/github.com/aws/aws-sdk-go/aws/version.go, vendor/github.com/aws/aws-sdk-go/service/mediaconvert/api.go, vendor/github.com/aws/aws-sdk-go/service/s3control/api.go, vendor/github.com/aws/aws-sdk-go/service/s3control/customizations.go, vendor/github.com/aws/aws-sdk-go/service/storagegateway/api.go, vendor/vendor.json
Fixes #7067 
Updated via `govendor fetch github.com/aws/aws-sdk-go/...@v1.16.19`
```
TF_ACC=1 go test ./... -v -parallel 20 -run=TestAccAWSAvailabilityZones -timeout 120m
?   	github.com/terraform-providers/terraform-provider-aws	[no test files]
=== RUN   TestAccAWSAvailabilityZones_basic
=== PAUSE TestAccAWSAvailabilityZones_basic
=== RUN   TestAccAWSAvailabilityZones_stateFilter
=== PAUSE TestAccAWSAvailabilityZones_stateFilter
=== CONT  TestAccAWSAvailabilityZones_basic
=== CONT  TestAccAWSAvailabilityZones_stateFilter
--- PASS: TestAccAWSAvailabilityZones_basic (16.39s)
--- PASS: TestAccAWSAvailabilityZones_stateFilter (16.40s)
PASS
ok …
```
=> deps: aws/aws-sdk-go@v1.16.19

go.mod, go.sum, vendor/github.com/hashicorp/terraform/command/format/diff.go, vendor/github.com/hashicorp/terraform/config/hcl2shim/values_equiv.go, vendor/github.com/hashicorp/terraform/helper/plugin/grpc_provider.go, vendor/github.com/hashicorp/terraform/terraform/diff.go, vendor/github.com/hashicorp/terraform/terraform/eval_apply.go, vendor/github.com/hashicorp/terraform/terraform/resource.go, vendor/modules.txt
Latest upstream adjustments to Terraform provider SDK.
```
go get github.com/hashicorp/terraform@1592b4aa67ad
go mod tidy
go mod vendor
```
=> deps: Update github.com/hashicorp/terraform@1592b4aa67ad

website/docs/r/ssm_parameter.html.markdown
=> docs/resource/aws_ssm_parameter: Fix name example and enhance name argument documentation

aws/resource_aws_lambda_permission.go, aws/resource_aws_lambda_permission_test.go
We also add an acceptance test verify that a `ResourceConflictException` is thrown with duplicate Statement IDs to catch any potential future change in that behavior.
Fixes #7214
```
--- PASS: TestAccAWSLambdaPermission_basic (68.41s)
--- PASS: TestAccAWSLambdaPermission_withRawFunctionName (68.48s)
--- PASS: TestAccAWSLambdaPermission_withStatementIdPrefix (71.39s)
--- PASS: TestAccAWSLambdaPermission_withIAMRole (78.98s)
--- PASS: TestAccAWSLambdaPermission_withQualifier (86.21s)
--- PASS: TestAccAWSLambdaPermission_withSNS (86.29s)
--- PASS: TestAccAWSLambdaPermission_multiplePerms (88.26s)
--- PASS: TestAccAWSLambdaPermission_StatementId_Duplicate (131.99s)
--- PASS: TestAccAWSLambdaPermission_withS3 (148.42s)
```
=> resource/aws_lambda_permission: Retry for Lambda function eventual consistency on creation

website/docs/r/api_gateway_integration.html.markdown
website/docs/r/api_gateway_integration: Fix source_arn path
resolves #7321
=> Update lambda integration example

aws/resource_aws_iam_user_test.go
Previous error from test sweeper:
```
[04:47:57][Step 2/4] 2019/01/29 04:47:57 [ERR] error running (aws_iam_user): Error deleting IAM User (test-user-zkodnc7v92): DeleteConflict: Cannot delete entity, must detach all policies first.
[04:47:57][Step 2/4] 	status code: 409, request id: 0c063f3a-2381-11e9-b836-47b1dc7da9f6
```
Output from test sweeper:
```
$ go test ./aws -v -sweep=us-west-2 -sweep-run=aws_iam_user -timeout 10h
2019/01/29 22:27:08 [DEBUG] Running Sweepers for region (us-west-2):
...
2019/01/29 22:27:09 [DEBUG] Deleting IAM User: test-user-zkodnc7v92
2019/01/29 22:27:09 [DEBUG] Detaching IAM User (test-user-zkodnc7v92) attached policy: arn:aws:iam::187416307283:policy/test-policy-vbj0vfrqc7
2019/01/29 22:27:10 [DEBUG] Waiting for state to become: [success]
2019/01/29 22:27:10 …
```
=> tests/resource/aws_iam_user: Detach IAM policies in sweeper before deleting user

aws/resource_aws_dynamodb_table.go, aws/resource_aws_dynamodb_table_test.go
Added while attempting to verify https://github.com/terraform-providers/terraform-provider-aws/issues/7420
```
--- PASS: TestAccAWSDynamoDbTable_disappears (20.29s)
--- PASS: TestAccAWSDynamoDbTable_disappears_PayPerRequestWithGSI (176.18s)
```
=> tests/resource/aws_dynamodb_table: Add disappears tests

aws/resource_aws_lb.go
=> tech debt: return the appropriate error aws_lb

aws/resource_aws_s3_bucket_test.go
Fixes https://github.com/terraform-providers/terraform-provider-aws/issues/7485.
Acceptance tests:
```console
$ make testacc TEST=./aws/ TESTARGS='-run=TestAccAWSS3Bucket_'
TF_ACC=1 go test ./aws/ -v -parallel 5 -run=TestAccAWSS3Bucket_ -timeout 120m
=== RUN   TestAccAWSS3Bucket_importBasic
=== PAUSE TestAccAWSS3Bucket_importBasic
=== RUN   TestAccAWSS3Bucket_importWithPolicy
=== PAUSE TestAccAWSS3Bucket_importWithPolicy
=== RUN   TestAccAWSS3Bucket_basic
=== PAUSE TestAccAWSS3Bucket_basic
=== RUN   TestAccAWSS3Bucket_namePrefix
=== PAUSE TestAccAWSS3Bucket_namePrefix
=== RUN   TestAccAWSS3Bucket_generatedName
=== PAUSE TestAccAWSS3Bucket_generatedName
=== RUN   TestAccAWSS3Bucket_region
=== PAUSE TestAccAWSS3Bucket_region
=== RUN …
```
=> r/aws_s3_bucket: Only check bucket existence in 'testAccCheckAWSS3BucketDestroy'

go.mod, go.sum, vendor/github.com/aws/aws-sdk-go/aws/version.go, vendor/github.com/aws/aws-sdk-go/service/applicationautoscaling/api.go, vendor/github.com/aws/aws-sdk-go/service/applicationautoscaling/doc.go, vendor/github.com/aws/aws-sdk-go/service/applicationautoscaling/errors.go, vendor/github.com/aws/aws-sdk-go/service/codebuild/api.go, vendor/github.com/aws/aws-sdk-go/service/codecommit/api.go, vendor/github.com/aws/aws-sdk-go/service/dlm/api.go, vendor/github.com/aws/aws-sdk-go/service/dlm/doc.go, vendor/github.com/aws/aws-sdk-go/service/ec2/api.go, vendor/github.com/aws/aws-sdk-go/service/ecs/api.go, vendor/github.com/aws/aws-sdk-go/service/elasticsearchservice/api.go, vendor/github.com/aws/aws-sdk-go/service/fsx/api.go, vendor/github.com/aws/aws-sdk-go/service/fsx/errors.go, vendor/github.com/aws/aws-sdk-go/service/gamelift/api.go, vendor/github.com/aws/aws-sdk-go/service/gamelift/doc.go, vendor/github.com/aws/aws-sdk-go/service/medialive/api.go, vendor/github.com/aws/aws-sdk-go/service/mediapackage/api.go, vendor/github.com/aws/aws-sdk-go/service/servicecatalog/api.go, vendor/github.com/aws/aws-sdk-go/service/workspaces/api.go, vendor/modules.txt
Required by:
* #7503 
* #7504 
Updated via:
```
go get github.com/aws/aws-sdk-go@v1.16.32
go mod tidy
go mod vendor
```
=> deps: github.com/aws/aws-sdk-go@v1.16.32

aws/resource_aws_appsync_graphql_api_test.go
Output from sweeper:
```
$ go test ./aws -v -sweep=us-west-2 -sweep-run=aws_appsync_graphql_api -timeout 10h
2019/02/13 14:00:13 [INFO] Deleting AppSync GraphQL API ax6aiyqtozcazbd6ntrlpukegi
2019/02/13 14:00:13 [INFO] Deleting AppSync GraphQL API eymhewdtlvcu5ldpetp7v2d5v4
2019/02/13 14:00:13 [INFO] Deleting AppSync GraphQL API f6imyfpurvetvo5pqcgmqdipna
2019/02/13 14:00:14 [INFO] Deleting AppSync GraphQL API fuupczy4aveo5jw4dz47wompna
2019/02/13 14:00:14 [INFO] Deleting AppSync GraphQL API h2bwiqynvra2xl4fbqke2apnyy
2019/02/13 14:00:14 [INFO] Deleting AppSync GraphQL API kv2mbozo3rbtbhytkb7trsilm4
2019/02/13 14:00:14 [INFO] Deleting AppSync GraphQL API lpcadqy7x5dhbaoftdbrzbskry
2019/02/13 14:00:15 [INFO] Deleting AppSync GraphQL API mibh73jn5ngwbh2tj4wseo45im
2019/02/13 14:00:15 [INFO] …
```
=> tests/resource/aws_appsync_graphql_api: Add sweeper

website/docs/r/redshift_event_subscription.html.markdown
* Example code parameter 'sns_topic' should be 'sns_topic_arn' as documented in argument reference.
=> Documentation update for r/redshift_event_subscription

aws/resource_aws_instance.go
Finally remove `network_interface_id` in favor of
`primary_network_interface_id`.
=> Remove `network_interface_id`

aws/provider.go, aws/resource_aws_codebuild_project.go, aws/resource_aws_instance.go, aws/resource_aws_route53_record.go
Reference: https://www.terraform.io/docs/extend/best-practices/deprecations.html#provider-attribute-removal
=> provider: Cleanup all attributes previously marked Removed

website/docs/guides/version-2-upgrade.html.md
Changes:
* Remove any future tense/wording
* Fill in latest 1.X version as 1.60.0
* Add full `aws_api_gateway_api_key` resource update example
* Add full `aws_dx_lag` resource update example
* Fix `aws_wafregional_byte_match_set` example
=> docs/guides/version-2-upgrade: Various preparations for actual release

aws/resource_aws_cognito_user_pool.go, aws/resource_aws_cognito_user_pool_test.go
=> r/cognito_user_pool: Add ConflictsWith to a few fields

aws/data_source_aws_redshift_service_account.go
Closes #7629 
References:
* https://docs.aws.amazon.com/govcloud-us/latest/ug-east/govcloud-redshift.html
* https://docs.aws.amazon.com/govcloud-us/latest/ug-west/govcloud-redshift.html
=> data-source/aws_redshift_service_account: Add us-gov-east-1 and us-gov-west-1 region mappings

aws/data_source_aws_ebs_volume.go, aws/resource_aws_autoscaling_policy_test.go, go.mod, go.sum, vendor/github.com/davecgh/go-spew/LICENSE, vendor/github.com/davecgh/go-spew/spew/bypass.go, vendor/github.com/davecgh/go-spew/spew/bypasssafe.go, vendor/github.com/davecgh/go-spew/spew/common.go, vendor/github.com/davecgh/go-spew/spew/dump.go, vendor/github.com/davecgh/go-spew/spew/format.go, vendor/modules.txt
Updated via:
```
go mod tidy
go mod vendor
```
=> provider: Remove direct dependency on github.com/davecgh/go-spew

website/docs/r/eks_cluster.html.markdown
=> docs/resource/aws_eks_cluster: Clarify version argument handling

website/docs/r/cloudwatch_metric_alarm.html.markdown
* Threshold appears to be wrong based on the comment intending a 10% threshold plus the expression used in the metric
=> Threshold appears to be wrong

aws/data_source_aws_elastic_beanstalk_hosted_zone.go
Closes #7763
Reference: https://docs.aws.amazon.com/en_us/general/latest/gr/rande.html#elasticbeanstalk_region
=> data-source/aws_elastic_beanstalk_hosted_zone: Add eu-north-1 region support

website/docs/d/secretsmanager_secret_version.html.markdown, website/docs/r/secretsmanager_secret_version.html.markdown
Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/4789
=> docs/service/secretsmanager: Show jsondecode() examples for Terraform 0.12 and later

website/docs/r/sns_topic_subscription.html.markdown
* Wording appears to be the result of a copy/paste mistake.  The Terraform AWS account should be in the same AWS account as the SQS Queue as stated in the sentence prior.  Without this change the paragraph conflicts with itself.
With this already being a confusing topic requiring multiple information callouts, this change should be made promptly.
=> Fixed typo regarding SNS Topic

aws/resource_aws_kinesis_analytics_application.go, aws/resource_aws_kinesis_analytics_application_test.go, website/docs/r/kinesis_analytics_application.html.markdown
Closes #7549
* `aws_kinesis_analytics_application` supports import
```
$ make testacc TESTARGS='-run=TestAccAWSKinesisAnalyticsApplication_basic'
TF_ACC=1 go test ./aws -v -parallel 20 -run=TestAccAWSKinesisAnalyticsApplication_basic -timeout 120m
=== RUN   TestAccAWSKinesisAnalyticsApplication_basic
=== PAUSE …
```
=> r/kinesis_analytics_application: Support import

website/docs/r/iam_policy_attachment.html.markdown
Closes https://github.com/terraform-providers/terraform-provider-aws/issues/98
=> add policy examples to iam policy attachment docs

website/docs/r/volume_attachment.html.markdown
Fixes #5180
* Documentation update for aws_volume_attachment to include links to AWS documentation for device naming rules for Linux and Windows instances
=> documentation fix - Issue 5180

website/docs/r/load_balancer_listener_policy.html.markdown, website/docs/r/load_balancer_policy.html.markdown
Clarifies #1669
Clarifies #822
Adds additional documentation around utilizing a Predefined AWS ELB Cipher policy
=> Elb load balancer policy docs

website/docs/index.html.markdown
Fixes #6886
* Updates provider page to clarify that token attribute is for temporary session token (retrieved from MFA device, not the MFA token code itself).
=> 6886 doc update - token attribute

aws/resource_aws_acmpca_certificate_authority.go, aws/resource_aws_acmpca_certificate_authority_test.go, website/docs/r/acmpca_certificate_authority.html.markdown
Related #4994 
Add new feature permanent_deletion_time_in_days for resource acmpca_certificate_authority
=> Add new feature for resoure acmpca_certificate_authority

website/docs/r/autoscaling_group.html.markdown
* Fixes document typo in [here](https://www.terraform.io/docs/providers/aws/r/autoscaling_group.html#with-latest-version-of-launch-template).
=> Fix $Latest typo

go.mod, go.sum, vendor/github.com/hashicorp/terraform/config/module/storage.go, vendor/github.com/hashicorp/terraform/helper/schema/schema.go, vendor/github.com/hashicorp/terraform/version/version.go, vendor/modules.txt
Required for new `ConfigMode` schema parameter.
References:
* https://github.com/hashicorp/terraform/issues/20505
* https://github.com/hashicorp/terraform/pull/20626
Updated via:
```
go get github.com/hashicorp/terraform@44702fa6c163391fe7295b6004a06cefe150daa0
go mod tidy
go mod vendor
```
=> deps: github.com/hashicorp/terraform@44702fa6c163391fe7295b6004a06cefe150daa0

website/docs/r/launch_template.html.markdown
=> r/launch_template.html.markdown: fix indent

go.mod, go.sum, vendor/github.com/aws/aws-sdk-go/aws/endpoints/defaults.go, vendor/github.com/aws/aws-sdk-go/aws/version.go, vendor/github.com/aws/aws-sdk-go/service/acm/api.go, vendor/github.com/aws/aws-sdk-go/service/acm/errors.go, vendor/github.com/aws/aws-sdk-go/service/batch/api.go, vendor/github.com/aws/aws-sdk-go/service/ec2/api.go, vendor/github.com/aws/aws-sdk-go/service/eks/api.go, vendor/github.com/aws/aws-sdk-go/service/emr/api.go, vendor/github.com/aws/aws-sdk-go/service/iam/api.go, vendor/github.com/aws/aws-sdk-go/service/iam/doc.go, vendor/github.com/aws/aws-sdk-go/service/iam/errors.go, vendor/github.com/aws/aws-sdk-go/service/securityhub/api.go, vendor/github.com/aws/aws-sdk-go/service/securityhub/doc.go, vendor/github.com/aws/aws-sdk-go/service/securityhub/errors.go, vendor/github.com/aws/aws-sdk-go/service/ssm/api.go, vendor/modules.txt
Required for (among other things) EKS control plane logs.
[Release notes](https://github.com/aws/aws-sdk-go/releases/tag/v1.19.10).
```console
$ go get github.com/aws/aws-sdk-go@v1.19.10
$ go mod tidy
$ go mod vendor
```
=> Bump AWS SDK to v1.19.10

aws/resource_aws_launch_template.go, aws/resource_aws_launch_template_test.go, website/docs/r/launch_template.html.markdown
```
--- PASS: TestAccAWSLaunchTemplate_disappears (8.61s)
--- PASS: TestAccAWSLaunchTemplate_networkInterface_ipv6Addresses (10.38s)
--- PASS: TestAccAWSLaunchTemplate_capacityReservation_preference (10.41s)
--- PASS: TestAccAWSLaunchTemplate_creditSpecification_nonBurstable (10.46s)
--- PASS: TestAccAWSLaunchTemplate_IamInstanceProfile_EmptyConfigurationBlock (10.55s)
--- PASS: …
```
=> resource/aws_launch_template: Add elastic_inference_accelerator configuration block

website/docs/r/backup_selection.html.markdown
This PR adds a bit more clarity to the backup_selection doc.
=> make iam_role_arn more explanatory

aws/resource_aws_wafregional_web_acl_association.go
Add support for API Gateway to `wafregional_web_acl_association`
by including list of resource types to query for association.
Default behavior of `ListResourcesForWebACL` is to only
return associations of type `APPLICATION_LOAD_BALANCER`. Associations
for API Gateways require explicitly requesting `API_GATEWAY`
resourcetype.
Fixes #6441
* Iterate through list of ResourceTypes for possible web acl associations to enable API Gateway type in `ListResourcesForWebACL`
```
gofmt needs running on the following files:
./aws/resource_aws_kinesis_analytics_application.go …
```
=> [wafregional_web_acl] Add support for ApiGateway

website/docs/r/vpc.html.markdown
Fixes #0000
* Change 1
* Change 2
```
...
```
=> Minor grammar

website/docs/r/ram_principal_association.markdown
* Docs: fix typo in import example for `aws_ram_principal_association`
=> docs/resource/aws_ram_principal_association: fix small typo in import example

website/docs/r/launch_template.html.markdown
Fixes #0000
* Change 1
* Change 2
```
...
```
=> Correcting spelling error:  interence -> inference

aws/data_source_aws_cloudtrail_service_account.go, aws/data_source_aws_elb_hosted_zone_id.go, aws/data_source_aws_elb_service_account.go, aws/data_source_aws_redshift_service_account.go, aws/hosted_zones.go
Fixes #8433 
* adds IDs for new ap-east-1 region
=> add new ap-east-1 region

aws/resource_aws_db_subnet_group_test.go, aws/resource_aws_subnet_test.go
Previous output from acceptance testing:
```
--- FAIL: TestAccAWSDBSubnetGroup_basic (6.78s)
testing.go:538: Step 0 error: Error applying: 1 error occurred:
* aws_db_subnet_group.foo: 1 error occurred:
* aws_db_subnet_group.foo: Error creating DB Subnet Group: DBSubnetGroupQuotaExceeded: You have already reached your quota of 50 DB subnet groups per customer.
```
Previous output from AWS CLI:
```
$ aws rds …
```
=> tests/resource/aws_db_subnet_group: Add sweeper

website/docs/r/dx_gateway_association.html.markdown, website/docs/r/dx_gateway_association_proposal.html.markdown
=> docs/r/dx_gateway_association: Fix broken resource links

.github/PULL_REQUEST_TEMPLATE.md
=> Update Pull Request Template to allow PR authors to suggest release notes

aws/data_source_aws_availability_zones.go, aws/data_source_aws_availability_zones_test.go, website/docs/d/availability_zones.html.markdown
Closes #8462
```
--- PASS: TestAccAWSAvailabilityZones_basic (9.66s)
--- PASS: TestAccAWSAvailabilityZones_stateFilter (9.90s)
--- PASS: TestAccAWSAvailabilityZones_BlacklistedZoneIds (10.80s)
--- PASS: TestAccAWSAvailabilityZones_BlacklistedNames (10.80s)
```
=> data-source/aws_availability_zones: Add blacklisted_names and blacklisted_zone_ids arguments

aws/provider.go, aws/resource_aws_db_instance_role_association.go, aws/resource_aws_db_instance_role_association_test.go, website/aws.erb, website/docs/r/db_instance_role_association.html.markdown
Closes #8038
* **New Resource:** `aws_db_instance_role_association`
```
--- PASS: TestAccAWSDbInstanceRoleAssociation_basic (561.71s)
--- PASS: TestAccAWSDbInstanceRoleAssociation_disappears (675.31s)
```
=> New Resource: aws_db_instance_role_association

aws/resource_aws_cloudwatch_metric_alarm.go, aws/resource_aws_dlm_lifecycle_policy.go, aws/resource_aws_dx_hosted_private_virtual_interface.go, aws/resource_aws_dx_private_virtual_interface.go, aws/validators.go, aws/validators_test.go
Fixes #7906
* replace validateAny() with validation.Any()
* replace validateIntegerInSlice() with validators.IntInSlice()
```
$ make testacc TESTARGS='-run=TestAccAWSCloudWatchMetricAlarm_basic'
TF_ACC=1 go test ./... -v -parallel 20 -run=TestAccAWSCloudWatchMetricAlarm_basic -timeout 120m
? …
```
=> Tech debt: Replace 'validateAny' and 'validateIntegerInSlice' with upstream 'validation.Any' and 'validation.IntInSlice'

website/docs/r/route53_delegation_set.html.markdown
Fixes a broken link in the doc.
=> route53_delegation_set: fix link to AWS API reference

.github/CONTRIBUTING.md
=> docs/provider: Update contributing guide Documentation Update section with common review items

website/docs/r/iot_thing_principal_attachment.html.markdown
Fixes #8584
```release-note
Fixed the documentation for `aws_iot_thing_principal_attachment`
```
=> updated aws_iot_thing_principal_attachment documentation to fix error

website/docs/r/rds_cluster.html.markdown
Closes #7779
```release-note
NONE
```
=> docs/resource/aws_rds_cluster: Note availability_zones argument behavior with 3 Availability Zones

website/docs/r/eks_cluster.html.markdown
Closes #8562
Managing the CloudWatch Log Group retention period for EKS Control Plane Logging is an important aspect of using the functionality to reduce costs and appropriate handle compliance concerns. Since the Terraform configuration has ordering considerations, we provide this short example in the resource documentation, rather than a shorter approach of just documenting the log group naming format with the …
=> docs/resource/aws_eks_cluster: Add Enabling Control Plane Logging example

website/docs/r/kinesis_stream.html.markdown
Fixes #0000
```release-note
Documentation update.
```
```
No change.
...
```
=> alias update to reduce confusion

aws/provider.go, aws/resource_aws_msk_configuration.go, aws/resource_aws_msk_configuration_test.go, website/aws.erb, website/docs/r/msk_configuration.html.markdown
Closes #8736
```release-note
**New Resource:** `aws_msk_configuration`
```
```
--- PASS: TestAccAWSMskConfiguration_KafkaVersions (14.14s)
--- PASS: TestAccAWSMskConfiguration_Description (19.35s)
--- PASS: TestAccAWSMskConfiguration_basic (27.64s)
--- PASS: …
```
=> New Resource: aws_msk_configuration

website/docs/r/rds_cluster.html.markdown
Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/7566
```release-note
NONE
```
=> docs/resource/aws_rds_cluster: Additional engine_version argument information and examples

website/docs/d/subnet_ids.html.markdown
```release-note
Add `filter` documentation for `aws_subnet_ids` data resource
```
```
TF_ACC=1 go test ./... -v -parallel 20 -run=TestAccXXX -timeout 120m
go: …
```
=> Add filter documentation for d/aws_subnet_ids

aws/resource_aws_msk_cluster.go, website/docs/r/msk_cluster.html.markdown
Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/8793
```release-note
NONE
```
=> resource/aws_msk_cluster: Document az_distribution valid value and ensure validation uses proper casing

website/docs/r/route53_record.html.markdown
Closes #8778
Reference: #8598
```release-note
NONE
```
=> docs/resource/aws_route53_record: Add NS and SOA Record Management example

aws/resource_aws_waf_byte_match_set_test.go, aws/resource_aws_waf_geo_match_set_test.go, aws/resource_aws_waf_ipset_test.go, aws/resource_aws_waf_rate_based_rule_test.go, aws/resource_aws_waf_regex_match_set_test.go, aws/resource_aws_waf_regex_pattern_set_test.go, aws/resource_aws_waf_rule_group_test.go, aws/resource_aws_waf_rule_test.go, aws/resource_aws_waf_size_constraint_set_test.go, aws/resource_aws_waf_sql_injection_match_set_test.go, aws/resource_aws_waf_web_acl_test.go, aws/resource_aws_waf_xss_match_set_test.go
```release-note
NONE
```
Previously from AWS GovCloud (US) acceptance testing:
```
--- FAIL: TestAccAWSWafRule_basic (1.22s)
testing.go:568: Step 0 error: errors during apply:
Error: Failed to acquire change token: RequestError: send request failed
caused by: Post …
```
=> tests/service/waf: Add PreCheck for service availability

.github/CONTRIBUTING.md
There was a bracket where there should have been a parens.
=> Fixes link to "Common Review Items"

aws/resource_aws_dynamodb_table_item.go
Fixes #6106
```release-note
BUG FIXES:
* resource/aws_dynamodb_table_item: add a nil check when building the table item ID
```
```
$ make testacc TESTARGS="-run=TestAccAWSDynamoDbTableItem"
TF_ACC=1 go test ./... …
```
=> Add nil check when building dynamo table item id

go.mod, go.sum, vendor/github.com/hashicorp/hcl/go.mod, vendor/github.com/hashicorp/hcl/go.sum, vendor/github.com/terraform-providers/terraform-provider-tls/tls/data_source_public_key.go, vendor/github.com/terraform-providers/terraform-provider-tls/tls/provider.go, vendor/github.com/terraform-providers/terraform-provider-tls/tls/resource_cert_request.go, vendor/github.com/terraform-providers/terraform-provider-tls/tls/resource_certificate.go, vendor/github.com/terraform-providers/terraform-provider-tls/tls/resource_private_key.go, vendor/modules.txt
Closes #8368
Updated via:
```
go get github.com/terraform-providers/terraform-provider-tls@v2.0.1+incompatible
go mod tidy
go mod vendor
```
```release-note
NONE
```
Output from acceptance testing: Checked via daily acceptance testing
=> deps: github.com/terraform-providers/terraform-provider-tls@v2.0.1+incompatible

.travis.yml
Fixes #0000
```release-note
```
```
...
```
=> travis: Add matrix builds

aws/data_source_aws_customer_gateway.go, aws/data_source_aws_customer_gateway_test.go, aws/provider.go, website/aws.erb, website/docs/d/customer_gateway.html.markdown
Fixes #5007
```release-note
**New Data Source:** `aws_customer_gateway`
```
```
% make testacc TEST=./aws TESTARGS='-run=TestAccAWSCustomerGatewayDataSource*'
TF_ACC=1 go test ./aws -v -parallel 20 …
```
=> New Data Source: aws_customer_gateway

.github/CONTRIBUTING.md
Focused on more accurately following current practices and removing ambiguous language.
```release-note
Update CONTRIBUTING guide.
```
```
N/A
```
=> Update CONTRIBUTING guide to clarify expectations

website/docs/r/organizations_account.html.markdown
Closes #8947
```release-note
NONE
```
Output from acceptance testing: N/A documentation update
=> docs/resource/aws_organization_account: Additional information about role_name drift detection and import

website/docs/d/availability_zones.html.markdown
Encourage usage of only returning available AZs
```release-note
NONE
```
=> Add state to availability_zones example

website/docs/r/rds_cluster.html.markdown
https://forums.aws.amazon.com/ann.jspa?annID=6771
https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_ScalingConfiguration.html
Fixes NONE
```release-note
NONE
```
```
NONE
```
=> aws_rds_cluster: 1 ACU is valid now

website/docs/r/cloudfront_distribution.html.markdown
Closes #3705
```release-note
NONE
```
Output from acceptance testing: N/A documentation update
=> docs/resource/aws_cloudfront_distribution: Additional information for web_acl_id argument

.github/CODEOWNERS
```release-note
NONE
```
```
N/A
```
=> Add CODEOWNERS file to automatically assign pull requests for review

website/docs/r/autoscaling_group.html.markdown
=> Mention Network LB in target_group_arns arg

.github/ISSUE_TEMPLATE/Question.md
Updates community resource to https://discuss.hashicorp.com/
=> Updates resource to new Community Forum

aws/config.go
Closes #8999
Reference: https://aws.amazon.com/about-aws/whats-new/2019/05/amazon-route-53-launches-private-dns-and-health-checks-in-the-aws-govcloud-us-west-region/
Previously, the provider service client customizations would hardcode the following region configurations:
* globalaccelerator: us-west-2
* route53: us-east-1
* shield: us-east-1
With the launch of private Route 53 Hosted Zones in AWS GovCloud (US), …
=> provider: Adjust globalaccelerator, route53, and shield service client regions to only configure in appropriate partition

aws/resource_aws_ses_receipt_rule_set.go
Closes #6470
Prefer the direct `DescribeReceiptRuleSet` API call over the `ListReceiptRuleSets` API call for the `Read` function. Certain APIs have eventual consistency delays with list API calls and here we can refactor away all the additional logic as well.
```release-note …
```
=> resource/aws_ses_receipt_rule_set: Prevent missing Terraform state for newly created resources

.hashibot.hcl
* Add service/amplify
* Add service/apigatewayv2
* Ignore service/apigatewayv2 with service/apigateway
* Add service/appmesh
* Add service/datapipeline
* Add service/datasync
* Add service/fsx
* Add service/globalaccelerator
* Add service/licensemanager
* Add service/mediaconnect
* Modify service/mediaconvert to include underscore for consistency with other media services
* Modify service/medialive to include underscore …
=> provider: Configure additional hashibot labeling, format configuration

.hashibot.hcl
Coming soon: https://github.com/aws/aws-sdk-go/releases/tag/v1.20.7
```release-note
NONE
```
=> provider: Add automatic service labels for applicationinsights and servicequotas

website/docs/r/kinesis_stream.html.markdown
Fixes a typo in the Kinesis Streams documentation.
```release-note
Fixes a typo in the Kinesis Streams documentation
```
=> kinesis_streams - Fix typo in documentation

website/docs/d/customer_gateway.html.markdown
Update the documentation page for the Customer Gateway data source. Currently, the example of a 'tag' argument is used.
=> Docs: Update CGW 'filter' argument example

website/docs/r/msk_cluster.html.markdown
The above parameter is required to deploy an msk cluster. See https://github.com/terraform-providers/terraform-provider-aws/pull/8635/files for further details
Fixes #0000
```release-note
```
```
...
```
=> added required parameter ebs_volume_size

website/docs/r/dms_replication_instance.html.markdown
Closes #7748
This configuration matches what is used in our acceptance testing account setup process.
```release-note
NONE
```
Output from acceptance testing: N/A documentation only
=> docs/resource/aws_dms_replication_instance: Add example IAM Role configuration for required roles

website/docs/r/appsync_resolver.html.markdown
Added PIPELINE AppSync example to aws_appsync_resolver docs as a quick follow up for just released AppSync PIPELINE resolver support.
Fixes #9175
Relates #8127
Relates #8502
```
NONE
```
```
n/a ?
```
=> Added PIPELINE example to appsync_resolver.html.markdown

website/docs/r/config_config_rule.html.markdown
Closes #8908
```release-note
NONE
```
Output from acceptance testing: N/A documentation update only
=> docs/resource/aws_config_config_rule: Additional information for AWS Managed Rules and Custom Rules

aws/data_source_aws_msk_configuration.go, aws/data_source_aws_msk_configuration_test.go, aws/provider.go, website/aws.erb, website/docs/d/msk_configuration.html.markdown
Closes #9082
```release-note
* **New Data Source:** `aws_msk_configuration`
```
```
--- PASS: TestAccAWSMskConfigurationDataSource_Name (15.27s)
```
=> New Data Source: aws_msk_configuration

website/docs/r/api_gateway_stage.html.markdown
Closes #8413
```release-note
NONE
```
=> docs/resource/aws_api_gateway_stage: Add information about managing the API logging CloudWatch Log Group

GNUmakefile
Closes #8958
Pull requests will now be checked for resource `TestCase` `CheckDestroy` implementation.
```release-note
NONE
```
Output from acceptance testing: Handled via TravisCI.
=> tests/provider: Enable tfproviderlint AT001 check

aws/resource_aws_db_parameter_group_test.go
```release-note
NONE
```
Previously:
```
--- FAIL: TestAccAWSDBEventSubscription_withSourceIds (8.73s)
testing.go:568: Step 0 error: errors during apply:
Error: Error creating DB Parameter Group: DBParameterGroupQuotaExceeded: You have already met your quota of 50 DB parameter groups
```
Output from test …
=> tests/resource/aws_db_parameter_group: Add sweeper

.github/CONTRIBUTING.md
=> docs/provider: Initial Adding Resource Import Support section for Contributing Guide

aws/resource_aws_api_gateway_domain_name.go, aws/resource_aws_api_gateway_domain_name_test.go, website/docs/r/api_gateway_domain_name.html.markdown
=> resource/api_gateway_domain_name: Add support for security_policy

.github/MAINTAINING.md
Some starting information for a long form Maintainers Guide to complement the existing [Contributing Guide](https://github.com/terraform-providers/terraform-provider-aws/blob/master/.github/CONTRIBUTING.md).
```release-note
NONE
```
=> docs/provider: Initial Maintainers Guide

website/docs/r/ssm_maintenance_window_task.html.markdown
Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/4408
Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/5700
```release-note
NONE
```
=> docs/resource/aws_ssm_maintenance_window_task: Provide examples of all four task types and add valid values for some task_invocation_parameters

website/docs/d/secretsmanager_secret_version.html.markdown
=> Fixed an example in the secretsmanager data source docs

website/docs/r/security_group_rule.html.markdown
Fixes #0000
```release-note
Fixed documentation for aws_security_group_rule resource
```
This is fix for https://github.com/terraform-providers/terraform-provider-aws/issues/9395
=> fix for 9395

examples/transit-gateway-cross-account-vpc-attachment/README.md, examples/transit-gateway-cross-account-vpc-attachment/main.tf
Specify an AWS provisioner for the last Terraform resources and complete the README.md
=> Fix TGW example

aws/resource_aws_customer_gateway.go
Relates #7873
```release-note
BUG FIXES
* aws/customer_gateway: Final retry after timeout deleting customer gateway
```
```
$ make testacc TESTARGS="-run=TestAccAWSCustomerGateway"
TF_ACC=1 go test ./... -v …
```
=> Final retry after timeout deleting customer gateway

.github/PULL_REQUEST_TEMPLATE.md
To hopefully make it more clear when a related issue will be automatically closed versus left open.
```release-note
NONE
```
```
N/A
```
=> Change the wording for related issues

website/aws.erb
=> website: Quick sidebar docs fix

.hashibot.hcl
=> provider: Enable Issue Service Labeling based on Resource Naming

.github/MAINTAINING.md
=> docs/provider: Add New Region information to Maintaining Guide

.hashibot.hcl
* Label is service/kafka for aws_msk_ resources (missing from PR behavior)
* Fix typo in aws_cloudwatch_metric_alarm
```release-note
NONE
```
=> provider: Minor fixes for hashibot configuration

examples/eks-getting-started/eks-cluster.tf, examples/eks-getting-started/eks-worker-nodes.tf
```release-note
```
```
...
```
=> simple syntax error fix

.hashibot.hcl
Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/9564
Reference: https://www.terraform.io/docs/providers/aws/r/codepipeline.html
Reference: https://www.terraform.io/docs/providers/aws/d/s3_bucket.html
Reference: https://www.terraform.io/docs/providers/aws/r/s3_bucket.html …
=> provider: Ensure hashibot issue labeling catches aws_codepipeline and  aws_s3_bucket resources/data sources

aws/resource_aws_fms_admin_account.go
No Issue.
```release-note
NONE
```
```
Nothing to test.
```
=> Execute make fmt for aws_fms_admin_account resource

website/docs/r/ssm_association.html.markdown
```release-note
NA
```
```
NA
...
```
=> Fix SSM association example with correct list type

aws/resource_aws_cloudfront_distribution.go
Accoding to the docs (and our own experience), it may take up to 90 minutes before an update is
complete: https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/HowToDeleteDistribution.html
=> r/cloudfront_distribution: update timeout

website/docs/r/waf_rule_group.html.markdown
=> Fix WAF rule group markdown

aws/resource_aws_cognito_identity_pool.go, aws/resource_aws_cognito_identity_pool_test.go, aws/tagsCognito.go, aws/tagsCognito_test.go, website/docs/r/cognito_identity_pool.markdown
Fixes #0000
```release-note
Added tags section for aws_cognito_identity_pool resource
```
```
$ make testacc TESTARGS='-run=TestAccAWSCognitoIdentityPoolWithTags'
--- PASS: TestAccAWSCognitoIdentityPoolWithTags (44.57s)
PASS
ok …
```
=> added tags for aws_cognito_identity_pool

website/docs/r/ses_event_destination.markdown
```release-note
Fix examples in aws_ses_event_destination
```
```
...
```
=> Remove extraneous equal signs

aws/resource_aws_vpn_gateway_test.go
```release-note
NONE
```
EC2 VPN Gateways and EC2 VPN Gateway Attachments enter a "deleted"/"detached" state before becoming fully removed, which needs to be handled by the sweeper, otherwise errors like the below occur:
```
[17:47:58][Step 2/5] 2019/08/06 17:47:58 [ERR] error running (aws_vpn_gateway): …
```
=> tests/resource/aws_vpn_gateway: Ensure sweeper skips detached/deleted infrastructure and ignores already deleted errors

aws/resource_aws_cloudhsm2_cluster.go, aws/resource_aws_cloudhsm2_hsm.go
Relates #7873
```release-note
* resource/aws_cloudhsm2_cluster: Final retries after timeouts creating, updating, and deleting CloudHSM clusters
* resource/aws_cloudhsm2_hsm: Final retries after timeouts creating and deleting CloudHSM modules
```
```
$ make testacc …
```
=> Final retries after timeouts creating, updating, and deleting CloudHSM resources

aws/resource_aws_dynamodb_table.go
Relates #7873
```release-note
BUG FIXES:
* resource/aws_dynamodb_table: Final retries after timeouts creating, updating, and deleting DynamoDB tables
```
```
$ make testacc TESTARGS="-run=TestAccAWSDynamoDbTable"    …
```
=> Final retries after timeouts creating, updating, and deleting dynamodb tables

aws/resource_aws_ebs_snapshot.go, aws/resource_aws_ebs_snapshot_copy.go
Relates #7873
```release-note
BUG FIXES:
* resource/aws_ebs_snapshot: Final retries after timeouts creating, deleting or waiting for available EBS snapshots
* resource/aws_ebs_snapshot_copy: Final retry after timeout deleting EBS snapshot copies
```
```
$ make testacc …
```
=> Final retries after timeouts for EBS snapshot resources

aws/resource_aws_guardduty_member.go
Relates #7873
```release-note
BUG FIXES
* resource/aws_guardduty_member: Final retry after timeout waiting for email invitation
```
```
$ make testacc TESTARGS="-run=TestAccAWSGuardDuty/Member" …
```
=> Final guard duty retry

aws/resource_aws_launch_configuration.go
Relates #7873
```release-note
BUG FIXES:
* resource/aws_launch_configuration: Final retry after timeout creating launch configuration
```
```
$ make testacc TESTARGS="-run=TestAccAWSLaunchConfiguration"             …
```
=> Final retry after timeout creating launch config

aws/resource_aws_s3_bucket_object_test.go, aws/resource_aws_s3_bucket_test.go
```release-note
NONE
```
To prevent errors in the sweepers such as:
```
2019/08/30 12:23:14 [ERR] error running (aws_s3_bucket_object): error listing S3 Bucket (tf-acc-test-6376821381526517605) Objects: AccessDenied: Access Denied
```
And
```
2019/08/30 11:38:01 [INFO] Skipping S3 Bucket …
```
=> tests/service/s3: Check S3 Bucket location before attempting other S3 operations in sweepers

go.mod, go.sum, vendor/github.com/aws/aws-sdk-go/aws/endpoints/defaults.go, vendor/github.com/aws/aws-sdk-go/aws/version.go, vendor/github.com/aws/aws-sdk-go/service/ecs/api.go, vendor/github.com/aws/aws-sdk-go/service/eks/api.go, vendor/github.com/aws/aws-sdk-go/service/gamelift/api.go, vendor/github.com/aws/aws-sdk-go/service/sfn/api.go, vendor/github.com/aws/aws-sdk-go/service/sfn/errors.go, vendor/modules.txt
Replaces #9970 
Updated via:
```console
$ go get github.com/aws/aws-sdk-go@v1.23.15
$ go mod tidy
$ go mod vendor
```
Pulling this in manually now so its included with tomorrow's release.
```release-note
* provider: Support AWS C2S and SC2S endpoints
```
Output from acceptance testing: Handled via daily …
=> deps: Update github.com/aws/aws-sdk-go@v1.23.15

aws/resource_aws_ses_template_test.go
Relates #8944
```release-note
NONE
```
```
$ make testacc TESTARGS="-run=TestAccAWSSesTemplate"
TF_ACC=1 go test ./... -v -parallel 20 -run=TestAccAWSSesTemplate -timeout 120m
? …
```
=> Acceptance test import refactor for SES template

website/docs/r/lightsail_instance.html.markdown
```release-note
```
```
...
```
=> Update CentOS 7's Blueprint ID to latest

aws/resource_aws_media_store_container_policy_test.go, aws/resource_aws_media_store_container_test.go
Relates #8944
```release-note
NONE
```
```
$ make testacc TESTARGS="-run=TestAccAWSMediaStoreContainer"
TF_ACC=1 go test ./... -v -parallel 20 -run=TestAccAWSMediaStoreContainer -timeout 120m
? …
```
=> Acceptance test import refactor for mediastore container resources

website/docs/r/lambda_permission.html.markdown
Closes #9978
```release-note
NONE
```
```
NA
```
Local screenshot:
=> Fix lambda permission import docs

website/docs/d/db_snapshot.html.markdown
Closes #9798
```release-note
NONE
```
```
NONE
```
Screenshot from local:
=> Add note about required/optional arguments to db snapshot docs

website/docs/r/iam_policy.html.markdown
```release-note
none
```
This reverts commit 8d24ade0d20f44ff69481c097456a286c4a4fead.
=> Revert "Update iam_policy.html.markdown"

website/docs/r/fsx_windows_file_system.html.markdown
* update skip_final_snapshot to proper value of skip_final_backup
```release-note
```
```
...
```
=> fix final backup property

website/docs/r/iot_thing_type.html.markdown
Fixes #10178
```release-note
Updated the documentation for `aws_iot_thing_type`
```
=> updated the aws_iot_thing_type documentation to include the import step

website/docs/index.html.markdown
Appears to be a simple off-by-one in that there are three approaches. If that's not the case and there's a better way to make the docs less confusing for this section please close this and do that :+1:
=> Docs - Fix presumed off-by-one 

website/docs/d/eks_cluster_auth.html.markdown
=> Typo in eks_cluster_auth.html.markdown

website/docs/r/cloudwatch_event_rule.html.markdown
```release-note
```
```
...
```
=> Added reference to the id attribute

website/docs/r/api_gateway_gateway_response.markdown
Pretty sure these labels got flipped ;)
```release-note
NONE
```
=> small documentation fix

aws/resource_aws_ec2_client_vpn_endpoint_test.go
Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/10023
```release-note
NONE
```
```
--- PASS: TestAccAwsEc2ClientVpnEndpoint_disappears (18.01s)
--- PASS: TestAccAwsEc2ClientVpnEndpoint_basic (17.22s)
--- PASS: …
```
=> tests/resource/aws_ec2_client_vpn_endpoint: Use internal implementation for TLS key/certificate

aws/resource_aws_elb_test.go
Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/10023
```release-note
NONE
```
```
--- PASS: TestAccAWSELB_Listener_SSLCertificateID_IAMServerCertificate (38.75s)
```
=> tests/resource/aws_elb: Use internal implementation for TLS key/certificate

.hashibot.hcl
Reference: https://github.com/terraform-providers/terraform-provider-aws/pull/10291
```release-note
NONE
```
=> provider: Ensure aws_load_balancer* pull request files are labeled with service/elb

website/docs/r/lambda_function.html.markdown
```release-note
NONE
```
```
...
```
=> Add link to Lambda APIGW guide

website/docs/r/api_gateway_integration.html.markdown
Closes #10330
* Minor documentation tweak.
=> resource/api_gateway_integration: Use lambda invoke_url in docs

website/docs/r/ssm_association.html.markdown
Closes #9724
* Minor documentation tweak.
=> resource/aws_ssm_association: Fix instance_id attribute documentation

website/docs/r/api_gateway_method.html.markdown
See https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigateway-method.html#cfn-apigateway-method-requestparameters
=> aws_api_gateway_method: document request_parameters

website/docs/r/s3_bucket_notification.html.markdown
```release-note
```
```
...
```
=> service/s3: Add clarification to bucket notification docs

.github/CONTRIBUTING.md
Reference: https://github.com/terraform-providers/terraform-provider-aws/pull/10399
```release-note
NONE
```
=> docs/provider: Add .hashibot.hcl changes to New Service checklist

website/docs/r/backup_plan.html.markdown
Fixes https://github.com/terraform-providers/terraform-provider-aws/issues/10392
```
Updated the documentation for `aws_backup_plan`
```
=> updated the aws_backup_plan documentaiton to include the id

.github/workflows/issues.yml
=> githhub/workflows/issues:  Add new issues to triage project board

aws/resource_aws_securityhub_product_subscription.go
```release-note
NONE
```
```
...
...
```
=> Return nil and do not use resource data when resource does not exists

.github/workflows/issues.yml
=> github/workflow/issues: Fix syntax issue

.github/workflows/issues.yml
=> github/workflows/issues: Add Actions Token

website/docs/r/codebuild_project.html.markdown
Minor typo fix.
```release-note
NONE
```
=> Minor typo

website/docs/r/elasticsearch_domain.html.markdown
```release-note
```
```
...
```
=> VPC cidr_block instead of cidr_blocks

aws/resource_aws_directory_service_directory_test.go
Relates #8944
```release-note
NONE
```
```
$  make testacc TESTARGS="-run=TestAccAWSDirectoryServiceDirectory_"
TF_ACC=1 go test ./... -v -count 1 -parallel 20 -run=TestAccAWSDirectoryServiceDirectory_ -timeout …
```
=> Import test refactor for directory service directory

aws/resource_aws_codepipeline_test.go
Relates #8944
```release-note
NONE
```
```
--- PASS: TestAccAWSCodePipeline_basic (26.24s)
--- PASS: TestAccAWSCodePipeline_emptyArtifacts (28.48s)
--- PASS: TestAccAWSCodePipeline_deployWithServiceRole (30.05s)
--- PASS: TestAccAWSCodePipeline_tags (42.98s)
```
=> Import test refactor for codepipeline

aws/resource_aws_acm_certificate_test.go
Relates #8944
```release-note
NONE
```
```
NA
```
=> import test lintignores for ACM cert tests

aws/resource_aws_lightsail_key_pair_test.go
Relates #8944
```release-note
NONE
```
```
NONE
```
=> import test lintignore for lightsail key pairs

aws/resource_aws_subnet_test.go, aws/resource_aws_vpc_test.go
```release-note
NONE
```
Previously, the sweepers would stop immediately at the first error encountered. This allows the sweepers to continue against further resources while still reporting back the error(s).
Output from sweepers:
```console
$ go test ./aws -v -timeout=10h -sweep=us-west-2 …
```
=> tests/service/ec2: Combine multiple errors and use paginated SDK functions in aws_subnet and aws_vpc sweepers

website/docs/r/codebuild_project.html.markdown
```release-note
```
```
...
```
=> Fix small typo of gorup --> group in codebuild_project docs

aws/resource_aws_kinesis_stream_test.go
```release-note
NONE
```
Output from sweeper in AWS Commercial:
```console
$ go test ./aws -v -timeout=10h -sweep=us-west-2,us-east-1 -sweep-run=aws_kinesis_stream -sweep-allow-failures
2019/10/29 01:24:49 [DEBUG] Running Sweepers for region (us-west-2):
2019/10/29 01:24:49 [DEBUG] Running Sweeper …
```
=> tests/resource/aws_kinesis_stream: Add sweeper

.github/workflows/pull_requests.yml
```release-note
```
```
...
```
=> Fix PR triage GH Action

.hashibot.hcl
Relates OR Closes #10592 
```release-note
Update .hashibot.hcl with iotanalytics service
```
=> Add iotanalytics service regex

.hashibot.hcl
Relates OR Closes #10591 
```release-note
Update .hashibot.hcl with iotevents service
```
=> Add iotevents service regex

.hashibot.hcl
Please see individual commits for references.
```release-note
NONE
```
=> Various hashibot labeling fixes/additions

aws/resource_aws_glue_crawler.go, aws/resource_aws_glue_crawler_test.go, website/docs/r/glue_crawler.html.markdown
Relates #7668
```release-note
* resource/aws_glue_crawler: Add `tags` argument
```
```
--- PASS: TestAccAWSGlueCrawler_Role_ARN_NoPath (28.38s)
=== CONT  TestAccAWSGlueCrawler_Description
--- PASS: TestAccAWSGlueCrawler_DynamodbTarget (40.11s)
--- PASS: …
```
=> resource/aws_glue_crawler: Add tags argument

website/docs/r/mq_broker.html.markdown
```release-note
Fix typo in mq_broker docs
```
=> Fix typo in mq_broker docs

website/docs/r/api_gateway_domain_name.html.markdown
Documenting workarounds for #10447 
Relates #10447 
```release-note
NONE
```
=> Add note for api_gateway_domain_name about implicit dependency on acm_certificate_validation

.github/PULL_REQUEST_TEMPLATE.md
```release-note
NONE
```
N/A, documentation only
=> Adds instructions for correctly including acceptance test results in a PR

website/docs/r/autoscaling_group.html.markdown
```release-note
update spot-allocation-strategy attribute with supported values.
```
```
...
```
=> update spot-allocation-strategy attribute

website/docs/r/autoscaling_policy.html.markdown
Relates OR Closes #9464
```release-note
```
```
...
```
=> fix documentation mistakes

website/docs/r/launch_template.html.markdown
Closes #6434
```release-note
none
```
=> website/docs/r/launch_template: Update default value for `block_device_mappings.delete_on_termination`

examples/two-tier/README.md
```release-note
NONE
```
```
...
```
=> Fix spacing in readme

website/docs/r/rds_cluster_instance.html.markdown
I believe the original author intended to write "promoted" as opposed to "promoter".
```release-note
```
```
...
```
=> Spelling correction.

aws/resource_aws_glue_trigger.go, aws/resource_aws_glue_trigger_test.go
```release-note
```
```
...
```
=> Add glue.trigger.workflow_name

aws/resource_aws_glue_trigger.go, aws/resource_aws_glue_trigger_test.go, website/docs/r/glue_trigger.html.markdown
Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/7668
```release-note
* resource/aws_glue_trigger: Add `tags` argument and `arn` attribute
```
```
--- PASS: TestAccAWSGlueTrigger_Basic (24.18s)
--- PASS: TestAccAWSGlueTrigger_WorkflowName …
```
=> resource/aws_glue_trigger: Add tags argument and arn attribute

website/docs/r/iot_thing_type.html.markdown
Closes #10547
```release-note
NONE
```
```
NONE
...
```
Screenshot:
=> Update the iot thing type docs to match the schema

website/docs/r/eks_cluster.html.markdown
Closes #11047
```release-note
NONE
```
Output from acceptance testing: N/A (testing already includes this configuration)
=> docs/resource/aws_eks_cluster: Ensure documentation includes depends_on information for IAM Role permissions

aws/provider.go, aws/resource_aws_eks_fargate_profile.go, aws/resource_aws_eks_fargate_profile_test.go, website/aws.erb, website/docs/r/eks_fargate_profile.html.markdown
Closes #11109
Closes #11110
```release-note
* **New Resource:** `aws_eks_fargate_profile`
```
Output from acceptance testing: 
```
--- PASS: TestAccAWSEksFargateProfile_Selector_Labels (1511.68s)
--- PASS: TestAccAWSEksFargateProfile_basic (1599.46s)
--- PASS: TestAccAWSEksFargateProfile_disappears …
```
=> New Resource: aws_eks_fargate_profile

aws/data_source_aws_route_table.go, aws/data_source_aws_route_table_test.go, aws/provider_test.go, aws/resource_aws_route_table_association.go, aws/resource_aws_route_table_association_test.go, website/docs/d/route_table.html.markdown, website/docs/r/route_table_association.html.markdown
Closes #11121
```release-note
* resource/aws_route_table_association: adds attribute `gateway_id`
* data-source/aws_route_table: adds attributes `gateway_id` and `associations.gateway_id`
```
Output from acceptance testing: Pending AWS Go SDK release
=> VPC Ingress Routing

aws/resource_aws_iam_role.go
Closes #136
```release-note
* resource/aws_iam_role: Ignore additional `NoSuchEntity` errors on deletion
```
Found (fairly consistently) while testing an unrelated resource:
```
--- FAIL: TestAccAWSEksFargateProfile_Tags (1867.13s)
testing.go:696: Error destroying resource! WARNING: Dangling resources …
```
=> resource/aws_iam_role: Ignore additional NoSuchEntity errors on deletion

website/docs/r/autoscaling_group.html.markdown
```release-note
```
```
...
```
=> Adding acceptable values for max_instance_lifetime

website/docs/r/elasticsearch_domain.html.markdown
=> Documentation update: Fix elasticsearch_domain.html tags (block -> arg)

website/aws.erb
Moves Resource for ECS Capacity Provider to Resources.
Relates #11150
=> Move resource of capacity provider to resources

.github/ISSUE_TEMPLATE/Bug_Report.md, .github/ISSUE_TEMPLATE/Feature_Request.md, .github/PULL_REQUEST_TEMPLATE.md
Modifications to PR/issue templates.
=> Add some minor additional copy to the comm note

website/docs/d/ecs_cluster.html.markdown, website/docs/r/ecs_cluster.html.markdown
Relates #11151
```release-note
NONE
```
```
...
```
=> [WIP] Add capacity provider to ecs cluster resources

.github/CODE_OF_CONDUCT.md
Removing repo specific CoC in favor of org one.
=> Falling back to org file

website/docs/r/autoscaling_group.html.markdown
```release-note
NONE
```
```
NONE
```
Screenshot:
=> Add note about default ASG tags

aws/resource_aws_ami_copy.go, aws/resource_aws_ami_copy_test.go
read after create
Relates #10688
```release-note
None
```
```
$ make testacc TESTARGS='-run=TestAccAWSAMICopy_'
--- PASS: TestAccAWSAMICopy_basic (422.75s)
--- PASS: TestAccAWSAMICopy_Description (457.52s)
--- …
```
=> ami copy - refactor to use keyvaluetags support + read after create

aws/resource_aws_iam_user_test.go
The test sweeper for `aws_iam_user` returns the error
```
DeleteConflict: Cannot delete entity, must delete policies first.
```
when there is an inline IAM policy.
Also does not quit IAM user sweeper on first error.
Closes #11315  …
=> IAM user test sweeper fails for users with inline policies

aws/provider.go, aws/resource_aws_accessanalyzer_analyzer.go, aws/resource_aws_accessanalyzer_analyzer_test.go, aws/resource_aws_accessanalyzer_test.go, website/aws.erb, website/docs/r/accessanalyzer_analyzer.html.markdown
Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/11102
```release-note
* **New Resource:** `aws_accessanalyzer_analyzer`
```
```
--- PASS: TestAccAWSAccessAnalyzer (62.76s)
--- PASS: TestAccAWSAccessAnalyzer/Analyzer (62.76s)
--- PASS: …
```
=> New Resource: aws_accessanalyzer_analyzer

aws/resource_aws_globalaccelerator_endpoint_group.go
Closes #11182
```release-note
None
```
```
...
```
=> Fixes issue 11182

aws/resource_aws_emr_cluster_test.go
```release-note
NONE
```
Many instance types are not available in us2w-az4 (us-west-2d), e.g.
```
--- FAIL: TestAccAWSEMRCluster_basic (97.00s)
testing.go:635: Step 0 error: errors during apply:
Error: Error waiting for EMR Cluster state to be "WAITING" or "RUNNING": TERMINATING: VALIDATION_ERROR: The …
```
=> tests/resource/aws_emr_cluster: Refactor testing configurations to use single base VPC configuration, blacklist usw2-az4

website/docs/r/budgets_budget.html.markdown
Relates OR Closes #10529
```release-note
Updates budgets_budget docs with sample Savings Plan and RI budget
```
```
...
```
=> Update budgets_budget docs with sample Savings Plan and RI budget

aws/resource_aws_directory_service_directory_test.go, aws/resource_aws_workspaces_directory.go, aws/resource_aws_workspaces_directory_test.go
Creates sweeper for `aws_workspaces_directory`, defined in #11023. We had some dangling resources left from testing, which was impacting other sweepers.
Relates  #11023
```release-note
NONE
```
```
$ …
```
=> Adds sweeper for `aws_workspaces_directory`

website/aws.erb
```release-note
Changed URL data source for aws_directory_service_directory in documentation
```
```
...
```
=> Changed url data source for aws_directory_service_directory

aws/resource_aws_cloudwatch_event_rule.go, aws/resource_aws_cloudwatch_event_target.go
Closes #1479
Reference: https://docs.aws.amazon.com/eventbridge/latest/userguide/
Reference: https://docs.aws.amazon.com/eventbridge/latest/APIReference/API_RemoveTargets.html
```release-note
* resource/aws_cloudwatch_event_rule: Retry …
```
=> service/cloudwatchevents: Handling for RemoveTargets failure entries and eventual consistency

website/docs/r/quicksight_user.html.markdown
The document was originally copied from the `group` resource.
```release-note
```
```
...
```
=> Fix copy-paste in QuickSight user documentation

website/docs/r/ecr_repository.html.markdown
I noticed there was no closing parenthesis.
so I add closing parenthesis to ecr repository.
```release-note
```
```
...
```
=> docs: add closing parenthesis to ecr repository

website/docs/r/iam_role_policy.html.markdown
```release-note
```
```
...
```
=> Updated documentation for terraform 0.12 improvements.

website/docs/d/availability_zones.html.markdown
```release-note
```
```
...
```
=> Update variable references to 0.12 syntax

examples/eks-getting-started/eks-cluster.tf, examples/eks-getting-started/eks-worker-nodes.tf, examples/eks-getting-started/outputs.tf, examples/eks-getting-started/variables.tf, examples/eks-getting-started/vpc.tf
=> fix pre 0.11 interpolation warnings

aws/resource_aws_acm_certificate.go
Closes #10992
```release-note
resource/resource_aws_acm_certificate.go : Add tag on create support.
```
```
$ make testacc TESTARGS='-run=TestAccAWSAcmCertificate_tags'
=== RUN   TestAccAWSAcmCertificate_tags
=== PAUSE TestAccAWSAcmCertificate_tags
=== CONT …
```
=> ACM tag on create support

website/docs/r/autoscaling_group.html.markdown
Reason for change: Typo fix
```release-note
NONE
```
=> Remove duplicate punctuation

aws/internal/keyvaluetags/generators/updatetags/main.go, aws/internal/keyvaluetags/update_tags_gen.go
Reference: https://github.com/terraform-providers/terraform-provider-aws/pull/11352#discussion_r362942801
```release-note
NONE
```
Updated via:
```
make gen
```
```
--- PASS: TestAccAWSKinesisStream_Tags …
```
=> internal/keyvaluetags: Simplify updatetags generator template batching support

website/docs/r/ssm_patch_baseline.html.markdown
Relates #8942
```release-note
NONE
```
N/A
=> Add docs for application patch baseline rules

website/docs/r/msk_configuration.html.markdown
```release-note
Fix typo in `msk_configuration` docs
```
```
...
```
=> Fix typo in msk_configuration docs

website/docs/r/ssm_patch_baseline.html.markdown
Closes #11824
```release-note
NONE
```
=> Fix broken documentation formatting for ssm_patch_baseline.html.markdown

aws/resource_aws_cloud9_environment_ec2_test.go
```release-note
NONE
```
Previously in the acceptance testing:
```
--- FAIL: TestAccAWSCloud9EnvironmentEc2_basic (660.80s)
testing.go:640: Step 0 error: errors during apply:
Error: timeout while waiting for state to become 'ready' (last …
```
=> tests/resource/aws_cloud9_environment_ec2: Remove dependency on Default VPC and blacklist usw2-az4

.github/MAINTAINING.md
```release-note
NONE
```
Output from acceptance testing: N/A documentation update
=> docs/provider: Add information for tfproviderdocs, tfproviderlint, and yaml.v2 in Maintaining Guide Dependency Updates section

aws/resource_aws_guardduty_detector_test.go
```release-note
NONE
```
Previously in the acceptance testing:
```
--- FAIL: TestAccAWSGuardDuty (35.95s)
--- FAIL: TestAccAWSGuardDuty/Detector (6.32s)
--- FAIL: TestAccAWSGuardDuty/Detector/basic (3.60s)
testing.go:640: Step 0 error: errors …
```
=> tests/resource/aws_guardduty_detector: Add sweeper

website/aws.erb
```release-note
Add DX resource documentation links which is omitted
```
```
...
```
=> Add DX resource documentation links which is omitted

aws/internal/keyvaluetags/generators/listtags/main.go, aws/internal/keyvaluetags/generators/updatetags/main.go, aws/internal/keyvaluetags/list_tags_gen.go, aws/internal/keyvaluetags/service_generation_customizations.go, aws/internal/keyvaluetags/update_tags_gen.go, aws/resource_aws_glacier_vault.go, aws/resource_aws_glacier_vault_test.go
Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/10688
```release-note
NONE
```
```
--- PASS: TestAccAWSGlacierVault_basic (21.69s)
--- PASS: TestAccAWSGlacierVault_full (25.78s) …
```
=> resource/aws_glacier_vault: Refactor to use keyvaluetags package

aws/data_source_aws_nat_gateway.go, aws/resource_aws_nat_gateway.go
Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/10688
```release-note
NONE
```
```
--- PASS: TestAccAWSNatGateway_basic (233.41s)
--- PASS: TestAccAWSNatGateway_tags (256.93s) …
```
=> service/ec2: Refactor aws_nat_gateway data source and resource to use keyvaluetags package

renovate.json
Reference: https://github.com/terraform-providers/terraform-provider-aws/pull/11532
Reference: https://github.com/terraform-providers/terraform-provider-aws/pull/11884
```release-note
NONE
```
Output from acceptance testing: N/A (dependency …
=> deps: Update renovate ignoreDeps to include golang.org/x/tools, remove unused dependencies, and alphabetize list

README.md
Fixed link and modified sentence for readability (too many "its")
```release-note
Fixed "installing plugin" link and modified sentence for readability (too many "its") on README
```
```
No modification to code …
```
=> Fixed link and modified sentence

website/docs/r/codebuild_project.html.markdown
Relates https://github.com/terraform-providers/terraform-provider-aws/issues/11966.
```release-note
NONE
```
```
n/a
```
=> r/aws_codebuild_project: Fix documentation example for 'source_version' attribute

website/docs/r/kinesis_firehose_delivery_stream.html.markdown
```release-note
Corrected Splunk configuration option description
```
```
...
```
=> Fixed Splunk configuration option description

website/docs/r/globalaccelerator_endpoint_group.html.markdown
Closes #12058.
```release-note
NONE
```
=> update r/aws_globalaccelerator_endpoint_group documentation

website/docs/r/sns_topic_subscription.html.markdown
```release-note
Update the syntax of the examples in sns_topic_subscription to terraform 0.12.x syntax.
```
=> Update the syntax of the examples in sns_topic_subscription to terraform 0.12.x syntax.

aws/resource_aws_lambda_permission.go
Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/11864
```release-note
NONE
```
`RetryFunc` should only be used when logic has a retryable condition. In the case of working with the AWS Go SDK, it also …
=> resource/aws_lambda_permission: Fixes for tfproviderlint R006

website/docs/r/codestarnotifications_notification_rule.markdown
```release-note
Fixed spacing and spelling mistakes
```
```
...
```
=> Fixed spacing and spelling

website/docs/r/glue_job.html.markdown
Adding detailed documentations over pythonshell Glue Job Type
```release-note
```
```
...
```
=> Updating pythonshell details

website/docs/r/s3_bucket_notification.html.markdown
Relates #7021
```release-note
NONE
```
```
...
```
=> Fix race condition in examples

website/docs/r/sns_topic_policy.html.markdown
```release-note
NONE
```
---
This PR just fixes some kebab cases to snake cases
=> docs(website): update module name to snake case

website/docs/r/elasticsearch_domain.html.markdown
Its not clear that you have to set zone_awareness_enabled to true for muli-az deployments.  Yes its logical however I battled this for a while today until I came across a stack overflow article that cleared up the confusion.  
This is the error you get when specifying two subnets with zone_awwareness_enabled set to false:
```
Error: Error applying plan:
1 error(s) occurred:
* module.elasticsearch.aws_elasticsearch_domain.example: 1 error(s) occurred:
* aws_elasticsearch_domain.example: ValidationException: You must specify exactly one subnet.
status code: 400, request id: 80a3e9fa-ef83-45bb-a869-95c406b046f1
```
* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request …
=> zone_awareness_enabled - elaboration

.hashibot.hcl
Reference: https://github.com/terraform-providers/terraform-provider-aws/pull/11567 (missing aws_cur_report service label)
Reference: https://github.com/terraform-providers/terraform-provider-aws/pull/12103 (missing aws_snapshot_create_volume_permission service label)
Reference: https://github.com/terraform-providers/terraform-provider-aws/pull/12020 / …
=> provider: Additional hashibot pull request labeling

aws/resource_aws_cloudwatch_metric_alarm_test.go
```release-note
NONE
```
Previously in the acceptance testing:
```
--- FAIL: TestAccAWSCloudWatchMetricAlarm_AlarmActions_EC2Automate (9.91s)
testing.go:640: Step 0 error: errors during apply:
Error: Error launching source instance: …
```
=> tests/resource/aws_cloudwatch_metric_alarm: Prevent instance type errors during instance testing

aws/resource_aws_ebs_snapshot_copy.go
```release-note
Improve EBS Snapshot copy error handling
```
=> Fix error handling for alternative errors

CHANGELOG.md
**note** this is a change to the `CHANGELONG.md` itself, thus it will not pass the automatic build process.  Maintainers, I guess it should be merged by hand?
=> spellcheck fixes for CHANGELOG

website/docs/r/cognito_user_pool.markdown
```release-note
```
```
...
```
=> Update the resource definition

aws/data_source_aws_launch_template.go, aws/data_source_aws_launch_template_test.go, website/docs/d/launch_template.html.markdown
Closes #8367, Relates #11994
```release-note
data_source_aws_launch_template - add `filter` support
```
```
$ make testacc TESTARGS='-run=TestAccAWSLaunchTemplateDataSource_'
--- PASS: …
```
=> d/aws_launch_template - filter support

.github/workflows/stale.yml, .hashibot.hcl
Reference: https://github.com/hashicorp/github-hashibot/pull/105
Reference: https://github.com/hashicorp/github-hashibot/pull/106
```release-note
NONE
```
=> provider: Updates to verify hashibot behaviors and increase stale handling per run

aws/resource_aws_codebuild_project.go
https://www.terraform.io/docs/providers/aws/r/codebuild_project.html#buildspec
=> typo: want option is buildspec

website/docs/r/s3_bucket.html.markdown
Closes #12321
```release-note
Fixes documentation and example of S3 buckets' ACL permissions
```
=> fix S3 ACL permissions

website/docs/r/neptune_cluster.html.markdown
None
```release-note
fix document typo: aws_neptune_cluster resouce
```
```
None
```
=> fix attribute name typo deletion_protection

website/aws.erb
Fixes `master` Travis errors:
```
$ make docscheck
Error checking Terraform Provider documentation: 2 errors occurred:
* website/aws.erb: missing side navigation link for resource: aws_apigatewayv2_integration
* website/aws.erb: missing side navigation link for resource: aws_apigatewayv2_model
GNUmakefile:53: recipe for target 'docscheck' failed
make: *** …
```
=> Fix missing side navigation links: aws_apigatewayv2_integration and aws_apigatewayv2_model

aws/resource_aws_db_instance_test.go, aws/resource_aws_rds_cluster_instance_test.go
Relates OR Closes #12854
```release-note
```
https://gist.github.com/jbarnes7952/21cac1b172c3153b14b25299b363b1ce
https://gist.github.com/jbarnes7952/bfa335d899b122c1fa9eeaa8c44a91fc
=> test_update_rds-ca-2019

.github/CONTRIBUTING.md
Relates https://github.com/terraform-providers/terraform-provider-aws/issues/12940.
Relates https://github.com/terraform-providers/terraform-provider-aws/issues/12941.
Corrects ELB, S3 and Elastic Beanstalk links when adding [new regions](https://github.com/terraform-providers/terraform-provider-aws/blob/master/.github/CONTRIBUTING.md#new-region).
Release …
=> Contributing Guide: Correct ELB, S3 and Elastic Beanstalk links for new AWS regions

aws/resource_aws_db_snapshot.go, aws/resource_aws_db_snapshot_test.go, website/docs/r/db_snapshot.html.markdown
Closes #12915
```release-note
resource_aws_db_snapshot: add import support
```
```
--- PASS: TestAccAWSDBSnapshot_disappears (783.47s)
--- PASS: …
```
=> r/db_snapshot: import support

website/docs/r/appautoscaling_policy.html.markdown, website/docs/r/appautoscaling_scheduled_action.html.markdown, website/docs/r/appautoscaling_target.html.markdown
Closes #5023
Reference: https://docs.aws.amazon.com/autoscaling/application/userguide/security_iam_service-with-iam.html#security_iam_service-with-iam-roles
```release-note
NONE
```
Output from acceptance testing: N/A (documentation update)
=> docs/resource/aws_appautoscaling_target: Additional information about role_arn

aws/resource_aws_iam_openid_connect_provider.go
Relates #9953.
```release-note
NONE
```
```console
$ make testacc TEST=./aws/ TESTARGS='-run=TestAccAWSIAMOpenIDConnectProvider_'  …
```
=> r/aws_iam_openid_connect_provider: Remove extraneous Exists function

aws/resource_aws_ssm_parameter.go
Relates #9953.
```release-note
NONE
```
```console
$ make testacc TEST=./aws/ TESTARGS='-run=TestAccAWSSSMParameter_disappears'
TF_ACC=1 go test ./aws/ …
```
=> r/aws_ssm_parameter: Remove extraneous Exists function

website/docs/r/appautoscaling_policy.html.markdown
Closes #11627
Reference: https://docs.aws.amazon.com/autoscaling/application/userguide/application-auto-scaling-target-tracking.html
```release-note
NONE
```
Output from acceptance testing: N/A (documentation update)
=> docs/resource/aws_appautoscaling_policy: Additional customized_metric_specification documentation

aws/resource_aws_storagegateway_gateway.go
Closes #12618
```release-note
* resource/aws_storagegateway_gateway: Retry 504 status code on activation
```
```
--- PASS: TestAccAWSStorageGatewayGateway_CloudWatchLogs (300.32s)
--- PASS: …
```
=> resource/aws_storagegateway_gateway: Retry 504 status code on activation

aws/resource_aws_cloudwatch_log_group_test.go
Closes #12655
```release-note
NONE
```
Output from sweeper:
```console
$ aws logs describe-log-groups | jq '.logGroups | length'
76
$ go test ./aws -v -timeout=10h -sweep-allow-failures -sweep=us-west-2 -sweep-run=aws_cloudwatch_log_group …
```
=> tests/resource/aws_cloudwatch_log_group: Add sweeper

aws/resource_aws_api_gateway_stage.go, aws/resource_aws_api_gateway_stage_test.go
Closes #12756
```release-note
* resource/aws_api_gateway_stage: Ignore `NotFoundException` error on destroy
```
Previously:
```
TestAccAWSAPIGatewayStage_disappears_ReferencingDeployment: testing.go:730: Error destroying resource! WARNING: …
```
=> resource/aws_api_gateway_stage: Ignore NotFoundException on destroy

.github/workflows/website.yml, .gitignore, .markdownlinkcheck.json, GNUmakefile, scripts/markdown-link-check.sh, website/docs/r/cognito_user_pool.markdown
```release-note
NONE
```
To potentially replace the terraform-website and Middleman testing currently done today.
=> docs: Experimental markdown-link-check testing

aws/resource_aws_iot_topic_rule_test.go
Relates #12658.
Relates #13167.
Relates #12659.
Relates https://github.com/terraform-providers/terraform-provider-aws/pull/13244.
```release-note
NONE
```
```console
$ TEST=./aws SWEEP=us-west-2,us-east-1 …
```
=> r/aws_iot_topic_rule: Add test sweeper

aws/resource_aws_iam_saml_provider.go, aws/resource_aws_iam_saml_provider_test.go
```release-note
NONE
```
```
$ make testacc TESTARGS='-run=TestAccAWSIAMSamlProvider_'
--- PASS: TestAccAWSIAMSamlProvider_basic (70.74s)
--- PASS: TestAccAWSIAMSamlProvider_disappears …
```
=> r/iam_saml_provider - refactor to use arn package + disappearing test case

aws/resource_aws_iot_topic_rule.go, aws/resource_aws_iot_topic_rule_test.go, aws/structure.go, website/docs/r/iot_topic_rule.html.markdown
Closes #12830
```release-note
add QoS field to aws_iot_topic_rule republish action
```
```
$ make testacc TEST=./aws TESTARGS='-run=TestAccAWSIoTTopicRule_republish' …
```
=> add QoS field to aws_iot_topic_rule republish action

aws/resource_aws_sns_topic_test.go
Closes https://github.com/terraform-providers/terraform-provider-aws/issues/12658.
```release-note
NONE
```
```console
TODO
```
=> r/aws_sns_topic: Add test sweeper

aws/resource_aws_sqs_queue_test.go
Closes https://github.com/terraform-providers/terraform-provider-aws/issues/12659.
```release-note
NONE
```
```
TODO
```
=> [WIP] r/aws_sqs_queue: Add test sweeper

docs/contributing/pullrequest-submission-and-lifecycle.md
=> Move branch prefix section from wiki into docs

ROADMAP.md
Relates https://github.com/terraform-providers/terraform-provider-aws/pull/13187.
Relates https://github.com/terraform-providers/terraform-provider-aws/pull/13218.
```release-note
NONE
```
```
n/a
```
=> ROADMAP.md: Fix a couple of broken/incorrect links

aws/resource_aws_datasync_task.go, aws/resource_aws_datasync_task_test.go, website/docs/r/datasync_task.html.markdown
Closes #11191
```release-note
resource/aws_dms_endpoint: Add "ONLY_FILES_TRANSFERRED" option to verify_mode
```
```
=> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 …
```
=> aws_datasync_task: verify_mode option ONLY_FILES_TRANSFERRED

docs/contributing/running-and-writing-acceptance-tests.md
```release-note
NONE
```
These sections are designed to document the Terraform AWS Provider "best practices" around writing acceptance testing for resources and data sources. The goal is to remove the current ambiguity of these practices for …
=> docs/contributing: Initial Resource and Data Source Acceptance Testing sections

website/docs/r/eks_node_group.html.markdown
Closes #11296
Reference: https://registry.terraform.io/providers/hashicorp/aws/2.62.0/docs/resources/ecs_service#ignoring-changes-to-desired-count
```release-note
NONE
```
=> docs/resource/aws_eks_node_group: Add ignore_changes example, similar to aws_ecs_service resource

website/docs/d/eks_cluster.html.markdown, website/docs/r/eks_cluster.html.markdown, website/docs/r/eks_node_group.html.markdown
Closes #12157
Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/13355
```release-note
NONE
```
Applied via `make website-lint-fix` and files selected to prevent too-large PR. …
=> docs/service/eks: markdownlint MD007 fixes

docs/contributing/contribution-checklists.md
Reference: https://github.com/terraform-providers/terraform-provider-aws/pull/11960#pullrequestreview-409674625
```release-note
NONE
```
=> docs/contributing: Add Resource Policy Support section, fix tagging documentation heading level

website/docs/d/vpc_peering_connection.html.markdown, website/docs/r/vpc_peering_connection.html.markdown, website/docs/r/vpc_peering_connection_accepter.html.markdown, website/docs/r/vpc_peering_connection_options.html.markdown, website/docs/r/waf_size_constraint_set.html.markdown, website/docs/r/wafregional_size_constraint_set.html.markdown
```release-note
update URLs in docs for permanently moved sites (including: vpc and waf)
```
```
N/A
```
=> docs: update URLs for permanently moved sites

docs/MAINTAINING.md
Add section detailing go default version update process.
```release-note
NONE
```
=> add golang version update section

aws/resource_aws_batch_job_definition_test.go
Closes https://github.com/terraform-providers/terraform-provider-aws/issues/12656.
```release-note
NONE
```
```console
$ TEST=./aws SWEEP=us-west-2,us-east-1 SWEEPARGS=-sweep-run=aws_batch_job_definition make …
```
=> r/aws_batch_job_definition: Add sweeper

website/docs/d/rds_cluster.html.markdown, website/docs/r/db_cluster_snapshot.html.markdown, website/docs/r/db_event_subscription.html.markdown, website/docs/r/db_instance_role_association.html.markdown, website/docs/r/db_snapshot.html.markdown, website/docs/r/rds_cluster.html.markdown, website/docs/r/rds_cluster_endpoint.html.markdown, website/docs/r/rds_global_cluster.html.markdown
```release-note
NONE
```
```
...
```
---
This pull request replaces "a RDS" with "an RDS" for the documentation.
Note that there are still three "a RDS" under the …
=> Replace "a RDS" with "an RDS"

aws/resource_aws_ssm_activation.go, aws/resource_aws_ssm_document.go, aws/resource_aws_ssm_document_test.go, website/docs/r/ssm_document.html.markdown
Relates #13312 
```release-note
* resource/aws_ssm_document: Expose `document_version` attribute
* resource/aws_ssm_activation: `expired` now properly set
```
```
... …
```
=> service/ssm: Fix schema errors

website/docs/r/codestarnotifications_notification_rule.markdown
```release-note
NONE
```
Output from acceptance testing: NONE(docs change only)
=> docs: r/aws_codestarnotifications_notification_rule: Fix invalid import command

.github/PULL_REQUEST_TEMPLATE.md
Reference: https://github.com/terraform-providers/terraform-provider-aws/pull/13465
```release-note
NONE
```
=> provider: Update pull request template link to Contributing Guide

examples/workspaces/README.md, examples/workspaces/iam.tf, examples/workspaces/main.tf, examples/workspaces/variables.tf
Allows the WorkSpaces example to run out-of-the-box.
```release-note
NONE
```
N/A
=> Fix WorkSpaces example

docs/contributing/running-and-writing-acceptance-tests.md
Adds a section describing a service availability precheck.
```release-note
NONE
```
=> add new section on service availablity precheck

README.md
```release-note
* Fixes typo in README.md
```
=> Fixes tiny typo in logo title in README.md

website/docs/r/security_group.html.markdown
I think this should be a list?
```release-note
```
```
...
```
=> Update security group example

website/docs/r/placement_group.html.markdown
References:
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/placement-groups.html
https://github.com/terraform-providers/terraform-provider-aws/blob/7fd165ff84fd05cce64bed17d20a69f0c684fd9e/aws/resource_aws_placement_group.go#L37-L39
=> Provide examples of placement strategy

website/docs/r/workspaces_directory.html.markdown
```release-note
```
```
...
```
=> Update workspaces_directory.html.markdown typo

.github/workflows/changelog.yml, .github/workflows/examples.yml, .github/workflows/terraform_provider.yml
Reference: https://github.blog/changelog/2020-05-27-github-actions-v2-cache-actions/
Reference: https://github.com/actions/checkout/pull/258
```release-note
NONE
```
Output from acceptance testing: N/A (CI configurations)
=> tests/provider: Bump GitHub Actions versions and minor adjustments examples handling

website/docs/r/autoscaling_group.html.markdown
```release-note
```
```
...
```
=> Fix autoscaling_group.html.markdown typo

docs/contributing/pullrequest-submission-and-lifecycle.md
```release-note
NONE
```
```
n/a
```
=> Documentation: Add 't' branch prefix for tests to Contributing Guide

aws/resource_aws_opsworks_instance.go
Relates #13278 
```release-note
resource/opsworks_instance: remove unused error return param
```
```
--- PASS: TestAccAWSOpsworksInstance_basic (80.78s)
--- PASS: …
```
=> resource/opsworks_instance: remove unused error return param

aws/internal/keyvaluetags/generators/listtags/main.go, aws/internal/keyvaluetags/generators/servicetags/main.go, aws/internal/keyvaluetags/generators/updatetags/main.go, aws/internal/keyvaluetags/list_tags_gen.go, aws/internal/keyvaluetags/service_generation_customizations.go, aws/internal/keyvaluetags/service_tags_gen.go, aws/internal/keyvaluetags/update_tags_gen.go
Reference: https://github.com/terraform-providers/terraform-provider-aws/pull/13459
Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/13696
```release-note
NONE
```
Supports them in the generated code for easier …
=> internal/keyvaluetags: Support servicediscovery and worklink

.github/ISSUE_TEMPLATE/config.yml
Adding roadmap link to issue chooser to send people there who may have roadmap related questions.
=> Add roadmap to issue chooser

aws/resource_aws_devicefarm_project.go, aws/resource_aws_devicefarm_project_test.go, website/docs/r/devicefarm_project.html.markdown
Closes #12914
```release-note
resource_aws_devicefarm_project: import support
```
```
$ make testacc TESTARGS='-run=TestAccAWSDeviceFarmProject_'
--- PASS: TestAccAWSDeviceFarmProject_basic (42.76s)
--- PASS: …
```
=> r/devicefarm_project - import support

aws/data_source_aws_outposts_outpost.go, aws/data_source_aws_outposts_outpost_test.go, aws/data_source_aws_outposts_outposts.go, aws/data_source_aws_outposts_outposts_test.go, aws/provider.go, website/aws.erb, website/docs/d/outposts_outpost.html.markdown, website/docs/d/outposts_outposts.html.markdown
```release-note
* **New Data Source:** `aws_outposts_outpost`
* **New Data Source:** `aws_outposts_outposts`
```
```
--- PASS: TestAccAWSOutpostsOutpostDataSource_Id (25.86s)
--- PASS: …
```
=> New Data Sources: aws_outposts_outpost(s)

docs/MAINTAINING.md
=> Expand contributing response timing guidelines and fix a couple links.

aws/resource_aws_wafv2_web_acl.go
Reference: https://github.com/hashicorp/terraform-plugin-sdk/issues/457
Closes #13863
```release-note
* resource/aws_wafv2_web_acl: Prevent unexpected `UpdateWebACL` API errors on tags only updates
```
```
--- …
```
=> resource/aws_wafv2_web_acl: Skip UpdateWebACL call on tags only updates

aws/resource_aws_ecs_service.go, website/docs/r/ecs_service.html.markdown
=> r/ecs_service: Add EXTERNAL to deployment_controller

website/docs/r/cloudfront_distribution.html.markdown
```release-note
```
```
...
```
=> Add note on how to use wafv2 in CloudFront

website/docs/r/media_store_container_policy.html.markdown
```release-note
Minor documentation change (correcting a typo)
```
```
...
```
=> Corrected the ARN in the Resource of the policy

aws/resource_aws_ecs_service.go, aws/resource_aws_ecs_service_test.go
Closes #13146
```release-note
* resource/aws_ecs_service: Add plan-time validation and prevent panics with empty `type` argument in `ordered_placement_strategy` configuration block
```
Previously (before code update):
```
=== CONT …
```
=> resource/aws_ecs_service: Add plan-time validation and prevent panics with empty `type` argument in `ordered_placement_strategy` configuration block

.markdownlint.yml, website/docs/r/organizations_organizational_unit.html.markdown, website/docs/r/rds_global_cluster.html.markdown, website/docs/r/s3_access_point.html.markdown, website/docs/r/s3_account_public_access_block.html.markdown, website/docs/r/s3_bucket_public_access_block.html.markdown, website/docs/r/snapshot_create_volume_permission.html.markdown, website/docs/r/ssm_patch_baseline.html.markdown, website/docs/r/waf_regex_match_set.html.markdown, website/docs/r/waf_rule_group.html.markdown, website/docs/r/waf_web_acl.html.markdown, website/docs/r/wafregional_regex_match_set.html.markdown, website/docs/r/wafregional_rule_group.html.markdown
Relates  #13355
```release-note
NONE
```
```
$  make website-lint                                                         
==> Checking website against linters...
$
...
```
=> MD007 changes part 5/5

website/docs/r/acm_certificate.html.markdown, website/docs/r/ami_launch_permission.html.markdown, website/docs/r/api_gateway_usage_plan.html.markdown, website/docs/r/appautoscaling_policy.html.markdown, website/docs/r/appsync_resolver.html.markdown, website/docs/r/budgets_budget.html.markdown, website/docs/r/cloudfront_distribution.html.markdown, website/docs/r/cloudhsm_v2_cluster.html.markdown, website/docs/r/codedeploy_deployment_group.html.markdown, website/docs/r/cognito_identity_pool.markdown, website/docs/r/cognito_user_pool.markdown, website/docs/r/config_config_rule.html.markdown
Relates  #13355
```release-note
NONE
```
```
$  make website-lint                                                         
==> Checking website against linters...
$
...
```
=> MD007 changes part 3/5

.github/workflows/team_slack_bot.yml
Revise action to filter at the repository rather than the org level
=> Revise action to filter at the repository rather than the org level

website/docs/r/docdb_cluster.html.markdown, website/docs/r/docdb_cluster_instance.html.markdown
```release-note
```
```
...
```
=> Fix docdb_cluster/_instance.html.markdown doc

.github/workflows/website.yml
Relates #13355
```release-note
tech-debt: add gh-action for markdownlint and misspell
```
```
N/A -- GH checks (though not triggered by this PR as website/docs/** have no change)
```
=> tech-debt: add gh-actions for markdownlint and misspell

.github/workflows/website.yml
```release-note
NONE
```
Previously handled in TravisCI via `make website-lint`.
Output from acceptance testing: N/A (CI testing)
=> tests/provider: Ensure terrafmt check runs on website updates

awsproviderlint/README.md
```release-note
NONE
```
Output from acceptance testing: N/A (documentation update)
=> awsproviderlint: Add missing AWSR002 link and docs to add these links to README

aws/resource_aws_organizations_organization.go, aws/resource_aws_organizations_organization_test.go, aws/resource_aws_organizations_policy.go, aws/resource_aws_organizations_policy_test.go, aws/resource_aws_organizations_test.go, website/docs/r/organizations_organization.html.markdown, website/docs/r/organizations_policy.html.markdown
Reference: https://docs.aws.amazon.com/organizations/latest/userguide/orgs_manage_policies_backup.html
Closes #14055
```release-note
* resource/aws_organizations_organization: Support `BACKUP_POLICY` value in `enabled_policy_types` plan-time …
```
=> service/organizations: Support Backup policies

website/docs/r/apigatewayv2_domain_name.html.markdown
Relates https://github.com/terraform-providers/terraform-provider-aws/issues/12892.
```release-note
NONE
```
```
n/a
```
=> r/aws_apigatewayv2_domain_name: Document association of a Route 53 RR

website/docs/r/lb_target_group_attachment.html.markdown
```release-note
```
```
...
```
=> Added use case of private IP outside of VPC scope

website/docs/r/cloudwatch_event_rule.html.markdown
```release-note
Fixed a mistake in documentation.
```
=> Fix multiline pattern in an example.

website/docs/r/instance.html.markdown
=> Updated example Ubuntu AMI 14.04 -> 20.04 and variable interpolation to 0.12 syntax 

docs/FAQ.md
=> FAQ.md  Link reactions to sorted PRs and issues

website/docs/r/autoscaling_group.html.markdown, website/docs/r/ecs_capacity_provider.html.markdown
Closes #12582
```release-note
NONE
```
Output from acceptance testing: N/A (documentation update)
=> docs/service/ecs: Update wording around ECS Capacity Provider and Auto Scaling Group handling with AmazonECSManaged tag

ROADMAP.md, docs/roadmaps/2020_May_to_July.md
This is a documentation update to add the roadmap for the upcoming quarter and retain the older one within `docs/roadmaps`
=> Add roadmap for August to October and archive existing roadmap

website/docs/index.html.markdown
=> Document max_retries default

aws/resource_aws_s3_bucket_test.go
Add an acceptance test for the `aws_s3_bucket` resource to verify that [S3 Same-Region Replication](https://aws.amazon.com/about-aws/whats-new/2019/09/amazon-s3-introduces-same-region-replication/) just works.
```release-note
n/a
```
```console
$ make testacc TEST=./aws/ …
```
=> r/aws_s3_bucket: Add S3 Same-Region Replication acceptance test

GNUmakefile
Reference: https://github.com/terraform-providers/terraform-provider-aws/pull/14097
```release-note
NONE
```
Output from acceptance testing: N/A (CI testing)
=> tests/provider: Enable AWSAT004 check for CI

awsproviderlint/passes/AWSAT005/AWSAT005.go, awsproviderlint/passes/AWSAT005/testdata/src/a/main.go
This makes partition check dynamic in case there are ARNs hardcoded from other partitions.
```release-note
NONE
```
Output from acceptance testing: NA
=> Improve static check for hardcoded partition in ARN

aws/resource_aws_autoscaling_notification_test.go
Relates #12994
```release-note
NONE
```
The output from GovCloud acceptance testing:
```
--- PASS: TestAccAWSASGNotification_Pagination (124.28s)
--- PASS: TestAccAWSASGNotification_basic (147.82s)
--- PASS: TestAccAWSASGNotification_update …
```
=> Remove hardcoded AMIs and AZs 

aws/resource_aws_network_interface_attachment_test.go
Relates #12994
```release-note
NONE
```
The output from GovCloud partition acceptance testing:
```
% testacc TestAccAWSNetworkInterfaceAttachment_basic
TF_ACC=1 go test ./aws -v …
```
=> Remove hardcoded AMI and AZ

.github/workflows/dependencies.yml, .github/workflows/terraform_provider.yml, GNUmakefile
Reference: https://github.com/terraform-providers/terraform-provider-aws/pull/14129
```release-note
NONE
```
Output from acceptance testing: N/A (CI testing)
=> tests/provider: Ensure awsproviderlint source is dependency and lint checked

.github/workflows/snapshot.yml
```release-note
NONE
```
Using GitHub Actions artifacts, sets up daily snapshot builds of master and allows other snapshot builds.
Output from acceptance testing: N/A (GitHub Actions configuration)
=> provider: Initial snapshot build workflow

website/docs/r/security_group_rule.html.markdown
```release-note
```
```
...
```
=> Update `cidr_blocks` value to list

aws/resource_aws_route_test.go
Relates #12994 
```release-note
NONE
```
| Partition | Passing | Failing | Test |
| ---------|-------:|------:|:-----:|
| us-gov | 12 | 0 | With-PR |
| us-gov | 10 | 3 | Pre-PR |
| standard | 13 | 0 | With-PR |
| standard | 13 | 0 | Pre-PR |
=> r/aws_route_test: Remove hardcoded AMI ID, AZ, instance type

aws/data_source_aws_ec2_instance_type_offerings_test.go, aws/data_source_aws_ec2_transit_gateway_dx_gateway_attachment_test.go, aws/data_source_aws_ec2_transit_gateway_peering_attachment_test.go, aws/data_source_aws_ec2_transit_gateway_route_table_test.go, aws/data_source_aws_ec2_transit_gateway_test.go, aws/data_source_aws_ec2_transit_gateway_vpc_attachment_test.go, aws/data_source_aws_ec2_transit_gateway_vpn_attachment_test.go, aws/data_source_aws_ecr_authorization_token_test.go, aws/data_source_aws_ecr_image_test.go, aws/data_source_aws_ecr_repository_test.go, aws/data_source_aws_ecs_cluster_test.go, aws/data_source_aws_ecs_container_definition_test.go, aws/data_source_aws_ecs_service_test.go, aws/data_source_aws_ecs_task_definition_test.go, aws/data_source_aws_efs_access_point_test.go, aws/data_source_aws_efs_file_system_test.go, aws/data_source_aws_efs_mount_target_test.go
Relates #8950
```release-note
NONE
```
```
...
```
=> Fix config for data source tests

aws/data_source_aws_lambda_alias_test.go, aws/data_source_aws_lambda_function_test.go, aws/data_source_aws_lambda_invocation_test.go, aws/data_source_aws_lambda_layer_version_test.go, aws/data_source_aws_launch_configuration_test.go, aws/data_source_aws_launch_template_test.go, aws/data_source_aws_lb_listener_test.go, aws/data_source_aws_lb_target_group_test.go, aws/data_source_aws_lb_test.go, aws/data_source_aws_mq_broker_test.go, aws/data_source_aws_msk_cluster_test.go, aws/data_source_aws_msk_configuration_test.go
Relates #8950
```release-note
NONE
```
```
...
```
=> Fix config for data sources tests

.github/workflows/examples.yml, examples/count/main.tf, examples/dx-gateway-cross-account-vgw-association/main.tf, examples/eks-getting-started/outputs.tf, examples/eks-getting-started/providers.tf, examples/transit-gateway-cross-account-peering-attachment/main.tf, examples/transit-gateway-cross-account-vpc-attachment/main.tf
Enables `tflint` for examples
Relates #8950
```release-note
NONE
```
```
...
```
=> Enables `tflint` for examples and fixes issues

aws/resource_aws_backup_plan_test.go, aws/resource_aws_backup_selection_test.go, aws/resource_aws_backup_vault_test.go, aws/resource_aws_batch_compute_environment_test.go, aws/resource_aws_batch_job_definition_test.go, aws/resource_aws_budgets_budget_test.go
=> tests/provider: Update resource testing to 0.12 syntax (B Resources)

website/docs/r/wafv2_web_acl.html.markdown
The block `excluded_rule` in `resource/wafv2_web_acl` is _optional_ (see `aws/resource_aws_wafv2_web_acl.go`) but the documentation states that it is _required_ for `managed_rule_group_statement` and `rule_group_reference_statement`. This PR fixes the documentation to state that the `excluded_rule` block is indeed optional.
Release note for …
=> resource/wafv2_web_acl: Fix documentation for excluded_rule

aws/data_source_aws_vpc_endpoint_test.go, aws/data_source_aws_vpc_peering_connection_test.go, aws/data_source_aws_vpc_test.go, aws/data_source_aws_vpcs_test.go, aws/data_source_aws_vpn_gateway_test.go, aws/data_source_aws_waf_ipset_test.go, aws/data_source_aws_waf_rate_based_rule_test.go, aws/data_source_aws_waf_rule_test.go, aws/data_source_aws_waf_web_acl_test.go, aws/data_source_aws_wafregional_ipset_test.go, aws/data_source_aws_wafregional_rate_based_rule_test.go, aws/data_source_aws_wafregional_rule_test.go, aws/data_source_aws_wafregional_web_acl_test.go, aws/data_source_aws_workspaces_bundle_test.go, aws/data_source_aws_workspaces_directory_test.go
Relates #8950
```release-note
NONE
```
```
...
```
=> Fix acc test configs (up to workspaces)

docs/DEVELOPMENT.md, docs/contributing/running-and-writing-acceptance-tests.md
Closes https://github.com/terraform-providers/terraform-provider-aws/issues/14648.
```release-note
NONE
```
```
n/a
```
=> Document requirement of Terraform CLI v0.12.26+ for acceptance tests

aws/resource_aws_pinpoint_adm_channel_test.go, aws/resource_aws_pinpoint_apns_channel_test.go, aws/resource_aws_pinpoint_apns_sandbox_channel_test.go, aws/resource_aws_pinpoint_apns_voip_channel_test.go, aws/resource_aws_pinpoint_apns_voip_sandbox_channel_test.go, aws/resource_aws_pinpoint_app_test.go, aws/resource_aws_pinpoint_baidu_channel_test.go, aws/resource_aws_pinpoint_email_channel_test.go, aws/resource_aws_pinpoint_event_stream_test.go, aws/resource_aws_pinpoint_gcm_channel_test.go, aws/resource_aws_pinpoint_sms_channel_test.go, aws/resource_aws_proxy_protocol_policy_test.go
=> tests/provider: Update resource testing to 0.12 syntax (P Resources)

aws/resource_aws_opsworks_application_test.go, aws/resource_aws_opsworks_custom_layer_test.go, aws/resource_aws_opsworks_ganglia_layer_test.go, aws/resource_aws_opsworks_haproxy_layer_test.go, aws/resource_aws_opsworks_instance_test.go, aws/resource_aws_opsworks_java_app_layer_test.go, aws/resource_aws_opsworks_memcached_layer_test.go, aws/resource_aws_opsworks_mysql_layer_test.go, aws/resource_aws_opsworks_nodejs_app_layer_test.go, aws/resource_aws_opsworks_permission_test.go, aws/resource_aws_opsworks_php_app_layer_test.go, aws/resource_aws_opsworks_rails_app_layer_test.go, aws/resource_aws_opsworks_rds_db_instance_test.go, aws/resource_aws_opsworks_stack_test.go, aws/resource_aws_opsworks_static_web_layer_test.go, aws/resource_aws_opsworks_user_profile_test.go, aws/resource_aws_organizations_account_test.go, aws/resource_aws_organizations_organizational_unit_test.go, aws/resource_aws_organizations_policy_attachment_test.go, aws/resource_aws_organizations_policy_test.go
=> tests/provider: Update resource testing to 0.12 syntax (O Resources)

aws/resource_aws_macie_member_account_association_test.go, aws/resource_aws_macie_s3_bucket_association_test.go, aws/resource_aws_main_route_table_association_test.go, aws/resource_aws_media_convert_queue_test.go, aws/resource_aws_media_package_channel_test.go, aws/resource_aws_media_store_container_policy_test.go, aws/resource_aws_media_store_container_test.go, aws/resource_aws_mq_broker_test.go, aws/resource_aws_mq_configuration_test.go, aws/resource_aws_msk_cluster_test.go, aws/resource_aws_msk_configuration_test.go
=> tests/provider: Update resource testing to 0.12 syntax (M Resources)

aws/resource_aws_lambda_alias_test.go, aws/resource_aws_lambda_event_source_mapping_test.go, aws/resource_aws_lambda_function_event_invoke_config_test.go, aws/resource_aws_lambda_function_test.go, aws/resource_aws_lambda_layer_version_test.go, aws/resource_aws_lambda_permission_test.go, aws/resource_aws_lambda_provisioned_concurrency_config_test.go, aws/resource_aws_launch_configuration_test.go, aws/resource_aws_launch_template_test.go, aws/resource_aws_lb_cookie_stickiness_policy_test.go, aws/resource_aws_lb_listener_certificate_test.go, aws/resource_aws_lb_listener_rule_test.go, aws/resource_aws_lb_listener_test.go, aws/resource_aws_lb_ssl_negotiation_policy_test.go, aws/resource_aws_lb_target_group_attachment_test.go, aws/resource_aws_lb_target_group_test.go, aws/resource_aws_lb_test.go, aws/resource_aws_licensemanager_association_test.go, aws/resource_aws_licensemanager_license_configuration_test.go, aws/resource_aws_lightsail_domain_test.go, aws/resource_aws_lightsail_instance_test.go, aws/resource_aws_lightsail_key_pair_test.go, aws/resource_aws_lightsail_static_ip_attachment_test.go, aws/resource_aws_lightsail_static_ip_test.go, aws/resource_aws_load_balancer_backend_server_policy_test.go, aws/resource_aws_load_balancer_listener_policy_test.go, aws/resource_aws_load_balancer_policy_test.go
=> tests/provider: Update resource testing to 0.12 syntax (L Resources)

aws/resource_aws_glue_catalog_table_test.go, aws/resource_aws_glue_classifier_test.go, aws/resource_aws_glue_connection_test.go, aws/resource_aws_glue_crawler_test.go, aws/resource_aws_glue_job_test.go, aws/resource_aws_glue_security_configuration_test.go, aws/resource_aws_glue_trigger_test.go, aws/resource_aws_glue_workflow_test.go
=> tests/provider: Update resource testing to 0.12 syntax (Glue Resources)

aws/resource_aws_gamelift_alias_test.go, aws/resource_aws_gamelift_fleet_test.go, aws/resource_aws_gamelift_game_session_queue_test.go, aws/resource_aws_glacier_vault_lock_test.go, aws/resource_aws_glacier_vault_test.go, aws/resource_aws_globalaccelerator_accelerator_test.go, aws/resource_aws_globalaccelerator_endpoint_group_test.go, aws/resource_aws_globalaccelerator_listener_test.go, aws/resource_aws_guardduty_detector_test.go, aws/resource_aws_guardduty_invite_accepter_test.go, aws/resource_aws_guardduty_ipset_test.go, aws/resource_aws_guardduty_member_test.go, aws/resource_aws_guardduty_threatintelset_test.go
=> tests/provider: Update resource testing to 0.12 syntax (G Resources except Glue)

aws/resource_aws_flow_log_test.go, aws/resource_aws_fms_admin_account_test.go, aws/resource_aws_fsx_lustre_file_system_test.go, aws/resource_aws_fsx_windows_file_system_test.go
=> tests/provider: Update resource testing to 0.12 syntax (F Resources)

aws/data_source_aws_autoscaling_group_test.go, aws/data_source_aws_autoscaling_groups_test.go, aws/data_source_aws_availability_zone_test.go
Relates #12995 
Depends on #14568
```release-note
NONE
```
```
...
```
=> Use availability zones config func

aws/data_source_aws_cloudhsm2_cluster_test.go, aws/data_source_aws_db_cluster_snapshot_test.go, aws/data_source_aws_directory_service_directory_test.go
Relates #12995
Depends on #14568
```release-note
NONE
```
```
...
```
=> Use availability zone config func
